In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import random
import missingno as msno
import pandas_profiling
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline
#解决中文显示问题
plt.rcParams["font.sans-serif"] = [u"SimHei"]
plt.rcParams["axes.unicode_minus"] = False
#解决图中负号问题
plt.rcParams['axes.unicode_minus']=False

In [9]:
# 构造内部表示号：

nbbsh_df=pd.DataFrame([index for index in range(1,120001)])
nbbsh_df.to_excel('d:\\内部标识号.xlsx',index=None)

In [4]:
# 构造业务日期···
date_list=['2019-06-01','2019-07-01','2019-08-01','2019-09-01','2019-10-01','2019-11-01','2019-12-01']
result_date=[]
for date in date_list:
    for number_index in range(120000):
        for repeate in range(2):
            result_date.append(date)

ywrq=pd.DataFrame(result_date)
ywrq.to_excel('d:\\业务日期.xlsx',index=None)

In [20]:
# 生成资产负债月切片表····

zcfz_origin_df=pd.read_excel('d:\\兴业资产负债月切片表.xlsx',header=0)

zcfz_resulte_df=zcfz_origin_df
for repetition in range(6):
    zcfz_resulte_df=zcfz_resulte_df.append(zcfz_origin_df)
zcfz_resulte_df.to_excel('d:\\兴业资产负债月切片表汇总.xlsx',index=None)

In [ ]:
# 生成交易基本信息表···
date_list=['2019-06-01']
nbbsh_list=[]
jyje_list=[]
jyrq_list=[]

jyjbxi_origin_df=pd.read_excel('d:\\交易基本文件.xlsx',header=0)

for date in date_list:
    for row_data in range(len(jyjbxi_origin_df)):
        for pay_number in range(jyjbxi_origin_df.iloc[row_data,:]['交易次数']):
            nbbsh_list.append(jyjbxi_origin_df.iloc[row_data,:]['内部标识号'])
            jyje_list.append(jyjbxi_origin_df.iloc[row_data,:]['交易金额'])
            jyrq_list.append(date)
    
result_jyjbxxb_df=pd.DataFrame({'内部标识号':nbbsh_list,'交易金额':jyje_list,'交易日期':jyrq_list,})
    
result_jyjbxxb_df.to_excel('d:\\交易基本信息汇总.xlsx',index=None)

In [5]:
result_jyjbxxb_df.shape
result_jyjbxxb_df.to_csv('d:\\交易基本信息汇总.csv',index=None)

In [3]:
# 生成交易往来文件···
jywlwj_origin_df=pd.read_excel('d:\\交易往来文件.xlsx',header=0)

jywlwj_resulte_dict={'内部标识号':[],'交易金额':[],'收支标志':[],}

for row_data in range(len(jywlwj_origin_df)):    
    jywlwj_resulte_dict['内部标识号'].append(jywlwj_origin_df.iloc[row_data,:]['内部标识号'])
    jywlwj_resulte_dict['交易金额'].append(jywlwj_origin_df.iloc[row_data,:]['收入金额'])
    jywlwj_resulte_dict['收支标志'].append(0)
    jywlwj_resulte_dict['内部标识号'].append(jywlwj_origin_df.iloc[row_data,:]['内部标识号'])
    jywlwj_resulte_dict['交易金额'].append(jywlwj_origin_df.iloc[row_data,:]['支出金额'])
    jywlwj_resulte_dict['收支标志'].append(1)

jywlwj_resulte_df=pd.DataFrame(jywlwj_resulte_dict)

for repetition in range(6):
    jywlwj_resulte_df=jywlwj_resulte_df.append(jywlwj_resulte_df)
jywlwj_resulte_df.to_excel('d:\\交易往来文件汇总.xlsx',index=None)

In [25]:
for row_data in range(len(jyjbxi_origin_df)):
    print(jyjbxi_origin_df.iloc[row_data,:])

内部标识号       1
交易次数        0
交易金额     6208
Name: 0, dtype: int64
内部标识号      2
交易次数      12
交易金额     697
Name: 1, dtype: int64
内部标识号      3
交易次数      13
交易金额     411
Name: 2, dtype: int64
内部标识号      4
交易次数      12
交易金额     630
Name: 3, dtype: int64
内部标识号       5
交易次数       25
交易金额     6928
Name: 4, dtype: int64
内部标识号      6
交易次数      11
交易金额     425
Name: 5, dtype: int64
内部标识号      7
交易次数      12
交易金额     396
Name: 6, dtype: int64
内部标识号      8
交易次数       5
交易金额     102
Name: 7, dtype: int64
内部标识号      9
交易次数       3
交易金额     368
Name: 8, dtype: int64
内部标识号      10
交易次数        0
交易金额     1956
Name: 9, dtype: int64
内部标识号     11
交易次数       8
交易金额     327
Name: 10, dtype: int64
内部标识号     12
交易次数       3
交易金额     303
Name: 11, dtype: int64
内部标识号     13
交易次数      22
交易金额     748
Name: 12, dtype: int64
内部标识号     14
交易次数       2
交易金额     454
Name: 13, dtype: int64
内部标识号      15
交易次数        1
交易金额     6612
Name: 14, dtype: int64
内部标识号     16
交易次数      13
交易金额     810
Name: 15, dtype: int64
内部标识号     17
交易次数       2
交易金额     305
Name: 16, dtype: int64
内部标识号     18
交易次数       9
交易金额     478
Name: 17, dtype: int64
内部标识号     19
交易次数      14
交易金额     738
Name: 18, dtype: int64
内部标识号     20
交易次数       2
交易金额     801
Name: 19, dtype: int64
内部标识号     21
交易次数      25
交易金额     667
Name: 20, dtype: int64
内部标识号     22
交易次数       2
交易金额     349
Name: 21, dtype: int64
内部标识号     23
交易次数      13
交易金额     686
Name: 22, dtype: int64
内部标识号     24
交易次数       8
交易金额     500
Name: 23, dtype: int64
内部标识号     25
交易次数      11
交易金额     593
Name: 24, dtype: int64
内部标识号     26
交易次数       8
交易金额     840
Name: 25, dtype: int64
内部标识号     27
交易次数       4
交易金额     186
Name: 26, dtype: int64
内部标识号     28
交易次数       1
交易金额     574
Name: 27, dtype: int64
内部标识号     29
交易次数      14
交易金额     833
Name: 28, dtype: int64
内部标识号       30
交易次数         5
交易金额     15227
Name: 29, dtype: int64
内部标识号     31
交易次数      15
交易金额     313
Name: 30, dtype: int64
内部标识号      32
交易次数       20
交易金额     3210
Name: 31, dtype: int64
内部标识号     33
交易次数      10
交易金额     415
Name: 32, dtype: int64
内部标识号     34
交易次数      25
交易金额     749
Name: 33, dtype: int64
内部标识号     35
交易次数       4
交易金额     107
Name: 34, dtype: int64
内部标识号     36
交易次数       1
交易金额     622
Name: 35, dtype: int64
内部标识号     37
交易次数       2
交易金额     818
Name: 36, dtype: int64
内部标识号     38
交易次数       3
交易金额     371
Name: 37, dtype: int64
内部标识号     39
交易次数       3
交易金额     151
Name: 38, dtype: int64
内部标识号       40
交易次数       247
交易金额     46696
Name: 39, dtype: int64
内部标识号       41
交易次数        30
交易金额     51004
Name: 40, dtype: int64
内部标识号       42
交易次数       140
交易金额     56785
Name: 41, dtype: int64
内部标识号     43
交易次数       6
交易金额     123
Name: 42, dtype: int64
内部标识号     44
交易次数       8
交易金额     895
Name: 43, dtype: int64
内部标识号     45
交易次数       1
交易金额     540
Name: 44, dtype: int64
内部标识号     46
交易次数       8
交易金额     177
Name: 45, dtype: int64
内部标识号     47
交易次数       8
交易金额     214
Name: 46, dtype: int64
内部标识号     48
交易次数       3
交易金额     407
Name: 47, dtype: int64
内部标识号     49
交易次数       5
交易金额     281
Name: 48, dtype: int64
内部标识号     50
交易次数      15
交易金额     562
Name: 49, dtype: int64
内部标识号     51
交易次数       5
交易金额     223
Name: 50, dtype: int64
内部标识号     52
交易次数       2
交易金额     329
Name: 51, dtype: int64
内部标识号     53
交易次数       2
交易金额     722
Name: 52, dtype: int64
内部标识号     54
交易次数       9
交易金额     544
Name: 53, dtype: int64
内部标识号     55
交易次数      11
交易金额     371
Name: 54, dtype: int64
内部标识号     56
交易次数      14
交易金额     826
Name: 55, dtype: int64
内部标识号       57
交易次数       288
交易金额     86246
Name: 56, dtype: int64
内部标识号       58
交易次数       215
交易金额     21532
Name: 57, dtype: int64
内部标识号     59
交易次数       4
交易金额     293
Name: 58, dtype: int64
内部标识号     60
交易次数      18
交易金额     830
Name: 59, dtype: int64
内部标识号     61
交易次数       7
交易金额     174
Name: 60, dtype: int64
内部标识号     62
交易次数       2
交易金额     998
Name: 61, dtype: int64
内部标识号     63
交易次数       9
交易金额     338
Name: 62, dtype: int64
内部标识号     64
交易次数       8
交易金额     387
Name: 63, dtype: int64
内部标识号     65
交易次数       2
交易金额     321
Name: 64, dtype: int64
内部标识号     66
交易次数      12
交易金额     472
Name: 65, dtype: int64
内部标识号       67
交易次数         3
交易金额     29882
Name: 66, dtype: int64
内部标识号     68
交易次数       9
交易金额     835
Name: 67, dtype: int64
内部标识号      69
交易次数       16
交易金额     1641
Name: 68, dtype: int64
内部标识号     70
交易次数       3
交易金额     399
Name: 69, dtype: int64
内部标识号     71
交易次数      10
交易金额     440
Name: 70, dtype: int64
内部标识号     72
交易次数      12
交易金额     639
Name: 71, dtype: int64
内部标识号     73
交易次数       1
交易金额     692
Name: 72, dtype: int64
内部标识号     74
交易次数      11
交易金额     994
Name: 73, dtype: int64
内部标识号     75
交易次数      11
交易金额     972
Name: 74, dtype: int64
内部标识号     76
交易次数      23
交易金额     701
Name: 75, dtype: int64
内部标识号     77
交易次数       4
交易金额     231
Name: 76, dtype: int64
内部标识号     78
交易次数      10
交易金额     473
Name: 77, dtype: int64
内部标识号      79
交易次数       18
交易金额     7324
Name: 78, dtype: int64
内部标识号     80
交易次数      19
交易金额     858
Name: 79, dtype: int64
内部标识号     81
交易次数       2
交易金额     579
Name: 80, dtype: int64
内部标识号      82
交易次数        1
交易金额     5630
Name: 81, dtype: int64
内部标识号      83
交易次数       29
交易金额     6523
Name: 82, dtype: int64
内部标识号     84
交易次数       5
交易金额     149
Name: 83, dtype: int64
内部标识号     85
交易次数      12
交易金额     333
Name: 84, dtype: int64
内部标识号     86
交易次数       2
交易金额     335
Name: 85, dtype: int64
内部标识号     87
交易次数      13
交易金额     559
Name: 86, dtype: int64
内部标识号     88
交易次数      15
交易金额     592
Name: 87, dtype: int64
内部标识号     89
交易次数       1
交易金额     666
Name: 88, dtype: int64
内部标识号       90
交易次数         6
交易金额     35459
Name: 89, dtype: int64
内部标识号      91
交易次数        0
交易金额     6397
Name: 90, dtype: int64
内部标识号       92
交易次数         3
交易金额     90333
Name: 91, dtype: int64
内部标识号     93
交易次数      14
交易金额     893
Name: 92, dtype: int64
内部标识号       94
交易次数         5
交易金额     58901
Name: 93, dtype: int64
内部标识号      95
交易次数       17
交易金额     4749
Name: 94, dtype: int64
内部标识号     96
交易次数      26
交易金额     892
Name: 95, dtype: int64
内部标识号     97
交易次数      13
交易金额     510
Name: 96, dtype: int64
内部标识号     98
交易次数       2
交易金额     542
Name: 97, dtype: int64
内部标识号      99
交易次数       27
交易金额     2800
Name: 98, dtype: int64
内部标识号    100
交易次数       2
交易金额     484
Name: 99, dtype: int64
内部标识号    101
交易次数      12
交易金额     619
Name: 100, dtype: int64
内部标识号    102
交易次数      27
交易金额      63
Name: 101, dtype: int64
内部标识号    103
交易次数       6
交易金额     100
Name: 102, dtype: int64
内部标识号     104
交易次数       27
交易金额     9942
Name: 103, dtype: int64
内部标识号     105
交易次数        1
交易金额     8045
Name: 104, dtype: int64
内部标识号    106
交易次数       7
交易金额     207
Name: 105, dtype: int64
内部标识号    107
交易次数       9
交易金额     427
Name: 106, dtype: int64
内部标识号    108
交易次数       2
交易金额     773
Name: 107, dtype: int64
内部标识号      109
交易次数         8
交易金额     29215
Name: 108, dtype: int64
内部标识号    110
交易次数       3
交易金额     228
Name: 109, dtype: int64
内部标识号    111
交易次数      13
交易金额     782
Name: 110, dtype: int64
内部标识号     112
交易次数        1
交易金额     7117
Name: 111, dtype: int64
内部标识号    113
交易次数       9
交易金额     449
Name: 112, dtype: int64
内部标识号     114
交易次数        0
交易金额     3132
Name: 113, dtype: int64
内部标识号     115
交易次数        0
交易金额     3931
Name: 114, dtype: int64
内部标识号      116
交易次数         4
交易金额     78092
Name: 115, dtype: int64
内部标识号    117
交易次数      11
交易金额     437
Name: 116, dtype: int64
内部标识号    118
交易次数       8
交易金额     535
Name: 117, dtype: int64
内部标识号    119
交易次数      15
交易金额     304
Name: 118, dtype: int64
内部标识号    120
交易次数       5
交易金额     285
Name: 119, dtype: int64
内部标识号    121
交易次数       7
交易金额     185
Name: 120, dtype: int64
内部标识号    122
交易次数      15
交易金额     501
Name: 121, dtype: int64
内部标识号      123
交易次数       182
交易金额     62409
Name: 122, dtype: int64
内部标识号    124
交易次数       8
交易金额     293
Name: 123, dtype: int64
内部标识号    125
交易次数       1
交易金额     801
Name: 124, dtype: int64
内部标识号    126
交易次数       4
交易金额     283
Name: 125, dtype: int64
内部标识号    127
交易次数       2
交易金额     408
Name: 126, dtype: int64
内部标识号    128
交易次数       2
交易金额     467
Name: 127, dtype: int64
内部标识号    129
交易次数       2
交易金额     522
Name: 128, dtype: int64
内部标识号    130
交易次数       4
交易金额     150
Name: 129, dtype: int64
内部标识号    131
交易次数      22
交易金额      90
Name: 130, dtype: int64
内部标识号    132
交易次数      13
交易金额     575
Name: 131, dtype: int64
内部标识号      133
交易次数         3
交易金额     28440
Name: 132, dtype: int64
内部标识号    134
交易次数      30
交易金额       4
Name: 133, dtype: int64
内部标识号    135
交易次数       2
交易金额     414
Name: 134, dtype: int64
内部标识号    136
交易次数       6
交易金额     122
Name: 135, dtype: int64
内部标识号    137
交易次数       6
交易金额     170
Name: 136, dtype: int64
内部标识号    138
交易次数       9
交易金额     606
Name: 137, dtype: int64
内部标识号    139
交易次数       3
交易金额     167
Name: 138, dtype: int64
内部标识号    140
交易次数       2
交易金额     670
Name: 139, dtype: int64
内部标识号    141
交易次数       8
交易金额     399
Name: 140, dtype: int64
内部标识号    142
交易次数      10
交易金额     382
Name: 141, dtype: int64
内部标识号    143
交易次数       8
交易金额     145
Name: 142, dtype: int64
内部标识号     144
交易次数       18
交易金额     1293
Name: 143, dtype: int64
内部标识号      145
交易次数        43
交易金额     20652
Name: 144, dtype: int64
内部标识号    146
交易次数       2
交易金额     449
Name: 145, dtype: int64
内部标识号     147
交易次数       15
交易金额     7869
Name: 146, dtype: int64
内部标识号    148
交易次数       3
交易金额     281
Name: 147, dtype: int64
内部标识号    149
交易次数       3
交易金额     261
Name: 148, dtype: int64
内部标识号      150
交易次数        59
交易金额     93713
Name: 149, dtype: int64
内部标识号    151
交易次数       3
交易金额     381
Name: 150, dtype: int64
内部标识号    152
交易次数      27
交易金额     704
Name: 151, dtype: int64
内部标识号    153
交易次数       2
交易金额     540
Name: 152, dtype: int64
内部标识号    154
交易次数       1
交易金额     505
Name: 153, dtype: int64
内部标识号    155
交易次数      11
交易金额     390
Name: 154, dtype: int64
内部标识号      156
交易次数         5
交易金额     27198
Name: 155, dtype: int64
内部标识号    157
交易次数       3
交易金额     198
Name: 156, dtype: int64
内部标识号    158
交易次数      11
交易金额     983
Name: 157, dtype: int64
内部标识号    159
交易次数       2
交易金额     200
Name: 158, dtype: int64
内部标识号    160
交易次数       2
交易金额     667
Name: 159, dtype: int64
内部标识号     161
交易次数        1
交易金额     4092
Name: 160, dtype: int64
内部标识号    162
交易次数       3
交易金额     309
Name: 161, dtype: int64
内部标识号    163
交易次数       2
交易金额     412
Name: 162, dtype: int64
内部标识号    164
交易次数       3
交易金额     315
Name: 163, dtype: int64
内部标识号    165
交易次数       2
交易金额     458
Name: 164, dtype: int64
内部标识号    166
交易次数       2
交易金额     300
Name: 165, dtype: int64
内部标识号    167
交易次数      11
交易金额     708
Name: 166, dtype: int64
内部标识号    168
交易次数       8
交易金额     166
Name: 167, dtype: int64
内部标识号     169
交易次数       21
交易金额     3260
Name: 168, dtype: int64
内部标识号      170
交易次数         3
交易金额     69752
Name: 169, dtype: int64
内部标识号    171
交易次数      12
交易金额     375
Name: 170, dtype: int64
内部标识号    172
交易次数       1
交易金额     977
Name: 171, dtype: int64
内部标识号    173
交易次数       2
交易金额     668
Name: 172, dtype: int64
内部标识号    174
交易次数       3
交易金额     244
Name: 173, dtype: int64
内部标识号    175
交易次数      10
交易金额     366
Name: 174, dtype: int64
内部标识号    176
交易次数      15
交易金额     541
Name: 175, dtype: int64
内部标识号    177
交易次数       2
交易金额     418
Name: 176, dtype: int64
内部标识号    178
交易次数       2
交易金额     413
Name: 177, dtype: int64
内部标识号    179
交易次数      14
交易金额     837
Name: 178, dtype: int64
内部标识号    180
交易次数       3
交易金额     422
Name: 179, dtype: int64
内部标识号    181
交易次数       2
交易金额     305
Name: 180, dtype: int64
内部标识号    182
交易次数       4
交易金额     108
Name: 181, dtype: int64
内部标识号    183
交易次数       2
交易金额     477
Name: 182, dtype: int64
内部标识号    184
交易次数       8
交易金额     821
Name: 183, dtype: int64
内部标识号    185
交易次数       3
交易金额     317
Name: 184, dtype: int64
内部标识号    186
交易次数       9
交易金额     878
Name: 185, dtype: int64
内部标识号    187
交易次数       3
交易金额     217
Name: 186, dtype: int64
内部标识号    188
交易次数       8
交易金额     462
Name: 187, dtype: int64
内部标识号    189
交易次数       8
交易金额     893
Name: 188, dtype: int64
内部标识号    190
交易次数       2
交易金额     362
Name: 189, dtype: int64
内部标识号    191
交易次数      15
交易金额     911
Name: 190, dtype: int64
内部标识号     192
交易次数       21
交易金额     2862
Name: 191, dtype: int64
内部标识号    193
交易次数       3
交易金额     297
Name: 192, dtype: int64
内部标识号    194
交易次数      20
交易金额     916
Name: 193, dtype: int64
内部标识号    195
交易次数       2
交易金额     325
Name: 194, dtype: int64
内部标识号    196
交易次数       5
交易金额     211
Name: 195, dtype: int64
内部标识号    197
交易次数       2
交易金额     469
Name: 196, dtype: int64
内部标识号    198
交易次数       1
交易金额     628
Name: 197, dtype: int64
内部标识号    199
交易次数       3
交易金额     427
Name: 198, dtype: int64
内部标识号    200
交易次数      10
交易金额     704
Name: 199, dtype: int64
内部标识号    201
交易次数       2
交易金额     599
Name: 200, dtype: int64
内部标识号    202
交易次数      12
交易金额     474
Name: 201, dtype: int64
内部标识号    203
交易次数       3
交易金额     488
Name: 202, dtype: int64
内部标识号    204
交易次数       2
交易金额     433
Name: 203, dtype: int64
内部标识号    205
交易次数       5
交易金额     255
Name: 204, dtype: int64
内部标识号      206
交易次数         7
交易金额     41917
Name: 205, dtype: int64
内部标识号    207
交易次数       1
交易金额     842
Name: 206, dtype: int64
内部标识号    208
交易次数      14
交易金额     401
Name: 207, dtype: int64
内部标识号    209
交易次数       8
交易金额     744
Name: 208, dtype: int64
内部标识号     210
交易次数        0
交易金额     4356
Name: 209, dtype: int64
内部标识号     211
交易次数       24
交易金额     5698
Name: 210, dtype: int64
内部标识号    212
交易次数      13
交易金额     397
Name: 211, dtype: int64
内部标识号    213
交易次数       2
交易金额     852
Name: 212, dtype: int64
内部标识号    214
交易次数       7
交易金额     268
Name: 213, dtype: int64
内部标识号    215
交易次数       8
交易金额     966
Name: 214, dtype: int64
内部标识号     216
交易次数       15
交易金额     5469
Name: 215, dtype: int64
内部标识号    217
交易次数      11
交易金额     990
Name: 216, dtype: int64
内部标识号    218
交易次数       3
交易金额     337
Name: 217, dtype: int64
内部标识号    219
交易次数       2
交易金额     311
Name: 218, dtype: int64
内部标识号    220
交易次数       6
交易金额     168
Name: 219, dtype: int64
内部标识号     221
交易次数        0
交易金额     7944
Name: 220, dtype: int64
内部标识号    222
交易次数       4
交易金额     175
Name: 221, dtype: int64
内部标识号    223
交易次数      10
交易金额     901
Name: 222, dtype: int64
内部标识号    224
交易次数       3
交易金额     455
Name: 223, dtype: int64
内部标识号     225
交易次数        0
交易金额     5235
Name: 224, dtype: int64
内部标识号    226
交易次数       2
交易金额     442
Name: 225, dtype: int64
内部标识号    227
交易次数      15
交易金额     891
Name: 226, dtype: int64
内部标识号    228
交易次数       5
交易金额     110
Name: 227, dtype: int64
内部标识号    229
交易次数      11
交易金额     437
Name: 228, dtype: int64
内部标识号    230
交易次数       2
交易金额     625
Name: 229, dtype: int64
内部标识号    231
交易次数       8
交易金额     300
Name: 230, dtype: int64
内部标识号    232
交易次数       3
交易金额     189
Name: 231, dtype: int64
内部标识号     233
交易次数        1
交易金额     4579
Name: 232, dtype: int64
内部标识号    234
交易次数      10
交易金额     875
Name: 233, dtype: int64
内部标识号     235
交易次数        0
交易金额     5771
Name: 234, dtype: int64
内部标识号      236
交易次数       149
交易金额     52402
Name: 235, dtype: int64
内部标识号    237
交易次数       1
交易金额     807
Name: 236, dtype: int64
内部标识号    238
交易次数      24
交易金额      41
Name: 237, dtype: int64
内部标识号    239
交易次数       1
交易金额     550
Name: 238, dtype: int64
内部标识号    240
交易次数       3
交易金额     266
Name: 239, dtype: int64
内部标识号     241
交易次数        1
交易金额     7181
Name: 240, dtype: int64
内部标识号    242
交易次数       5
交易金额     176
Name: 241, dtype: int64
内部标识号    243
交易次数       9
交易金额     369
Name: 242, dtype: int64
内部标识号     244
交易次数        0
交易金额     8334
Name: 243, dtype: int64
内部标识号    245
交易次数      15
交易金额     405
Name: 244, dtype: int64
内部标识号    246
交易次数       1
交易金额     632
Name: 245, dtype: int64
内部标识号    247
交易次数      20
交易金额      53
Name: 246, dtype: int64
内部标识号    248
交易次数      25
交易金额     762
Name: 247, dtype: int64
内部标识号     249
交易次数       18
交易金额     3168
Name: 248, dtype: int64
内部标识号    250
交易次数       7
交易金额     263
Name: 249, dtype: int64
内部标识号    251
交易次数       2
交易金额     474
Name: 250, dtype: int64
内部标识号    252
交易次数       5
交易金额     104
Name: 251, dtype: int64
内部标识号    253
交易次数       4
交易金额     103
Name: 252, dtype: int64
内部标识号      254
交易次数         3
交易金额     62391
Name: 253, dtype: int64
内部标识号      255
交易次数         8
交易金额     32626
Name: 254, dtype: int64
内部标识号    256
交易次数      12
交易金额     671
Name: 255, dtype: int64
内部标识号     257
交易次数       17
交易金额     1634
Name: 256, dtype: int64
内部标识号    258
交易次数       3
交易金额     415
Name: 257, dtype: int64
内部标识号    259
交易次数      12
交易金额     575
Name: 258, dtype: int64
内部标识号     260
交易次数       17
交易金额     9240
Name: 259, dtype: int64
内部标识号    261
交易次数      14
交易金额     360
Name: 260, dtype: int64
内部标识号    262
交易次数       9
交易金额     428
Name: 261, dtype: int64
内部标识号    263
交易次数       2
交易金额     408
Name: 262, dtype: int64
内部标识号    264
交易次数       2
交易金额     640
Name: 263, dtype: int64
内部标识号     265
交易次数        1
交易金额     8964
Name: 264, dtype: int64
内部标识号    266
交易次数       2
交易金额     643
Name: 265, dtype: int64
内部标识号    267
交易次数       9
交易金额     656
Name: 266, dtype: int64
内部标识号    268
交易次数      13
交易金额     533
Name: 267, dtype: int64
内部标识号     269
交易次数        1
交易金额     7311
Name: 268, dtype: int64
内部标识号    270
交易次数       1
交易金额     582
Name: 269, dtype: int64
内部标识号    271
交易次数       8
交易金额     412
Name: 270, dtype: int64
内部标识号    272
交易次数       7
交易金额     259
Name: 271, dtype: int64
内部标识号    273
交易次数       5
交易金额     182
Name: 272, dtype: int64
内部标识号     274
交易次数       23
交易金额     2250
Name: 273, dtype: int64
内部标识号    275
交易次数      14
交易金额     307
Name: 274, dtype: int64
内部标识号      276
交易次数         4
交易金额     58869
Name: 275, dtype: int64
内部标识号     277
交易次数        1
交易金额     4675
Name: 276, dtype: int64
内部标识号     278
交易次数       29
交易金额     1098
Name: 277, dtype: int64
内部标识号      279
交易次数       196
交易金额     18642
Name: 278, dtype: int64
内部标识号    280
交易次数       2
交易金额     700
Name: 279, dtype: int64
内部标识号    281
交易次数       2
交易金额     399
Name: 280, dtype: int64
内部标识号    282
交易次数       2
交易金额     883
Name: 281, dtype: int64
内部标识号    283
交易次数       4
交易金额     217
Name: 282, dtype: int64
内部标识号    284
交易次数      12
交易金额     665
Name: 283, dtype: int64
内部标识号     285
交易次数        0
交易金额     6210
Name: 284, dtype: int64
内部标识号     286
交易次数        1
交易金额     5162
Name: 285, dtype: int64
内部标识号    287
交易次数       1
交易金额     819
Name: 286, dtype: int64
内部标识号      288
交易次数       131
交易金额     12206
Name: 287, dtype: int64
内部标识号    289
交易次数       3
交易金额     203
Name: 288, dtype: int64
内部标识号      290
交易次数       272
交易金额     51531
Name: 289, dtype: int64
内部标识号    291
交易次数       8
交易金额     330
Name: 290, dtype: int64
内部标识号    292
交易次数       9
交易金额     964
Name: 291, dtype: int64
内部标识号    293
交易次数       3
交易金额     353
Name: 292, dtype: int64
内部标识号     294
交易次数       17
交易金额     2607
Name: 293, dtype: int64
内部标识号    295
交易次数       7
交易金额     218
Name: 294, dtype: int64
内部标识号     296
交易次数       15
交易金额     1152
Name: 295, dtype: int64
内部标识号     297
交易次数       24
交易金额     1768
Name: 296, dtype: int64
内部标识号     298
交易次数       30
交易金额     5846
Name: 297, dtype: int64
内部标识号    299
交易次数       6
交易金额     200
Name: 298, dtype: int64
内部标识号      300
交易次数       210
交易金额     85466
Name: 299, dtype: int64
内部标识号    301
交易次数      26
交易金额     547
Name: 300, dtype: int64
内部标识号    302
交易次数       4
交易金额     294
Name: 301, dtype: int64
内部标识号    303
交易次数       8
交易金额     448
Name: 302, dtype: int64
内部标识号      304
交易次数         7
交易金额     23358
Name: 303, dtype: int64
内部标识号     305
交易次数       23
交易金额     9923
Name: 304, dtype: int64
内部标识号    306
交易次数      10
交易金额     723
Name: 305, dtype: int64
内部标识号    307
交易次数       2
交易金额     421
Name: 306, dtype: int64
内部标识号     308
交易次数        0
交易金额     7131
Name: 307, dtype: int64
内部标识号      309
交易次数         8
交易金额     63580
Name: 308, dtype: int64
内部标识号    310
交易次数       2
交易金额     326
Name: 309, dtype: int64
内部标识号    311
交易次数      15
交易金额     706
Name: 310, dtype: int64
内部标识号    312
交易次数      14
交易金额     480
Name: 311, dtype: int64
内部标识号     313
交易次数       20
交易金额     8256
Name: 312, dtype: int64
内部标识号    314
交易次数       9
交易金额     690
Name: 313, dtype: int64

Name: 364, dtype: int64
内部标识号    366
交易次数       9
交易金额     853
Name: 365, dtype: int64
内部标识号    367
交易次数      14
交易金额     764
Name: 366, dtype: int64
内部标识号      368
交易次数        59
交易金额     97789
Name: 367, dtype: int64
内部标识号    369
交易次数      11
交易金额     343
Name: 368, dtype: int64
内部标识号    370
交易次数       3
交易金额     403
Name: 369, dtype: int64
内部标识号    371
交易次数       8
交易金额     988
Name: 370, dtype: int64
内部标识号    372
交易次数       5
交易金额     159
Name: 371, dtype: int64
内部标识号    373
交易次数       8
交易金额     290
Name: 372, dtype: int64
内部标识号    374
交易次数       3
交易金额     269
Name: 373, dtype: int64
内部标识号    375
交易次数       8
交易金额     849
Name: 374, dtype: int64
内部标识号    376
交易次数       2
交易金额     549
Name: 375, dtype: int64
内部标识号      377
交易次数       300
交易金额     66523
Name: 376, dtype: int64
内部标识号    378
交易次数       2
交易金额     458
Name: 377, dtype: int64
内部标识号     379
交易次数        0
交易金额     5700
Name: 378, dtype: int64
内部标识号    380
交易次数       3
交易金额     421
Name: 379, dtype: int64
内部标识号    381
交易次数       5
交易金额     209
Name: 380, dtype: int64
内部标识号    382
交易次数      12
交易金额     760
Name: 381, dtype: int64
内部标识号    383
交易次数       7
交易金额     187
Name: 382, dtype: int64
内部标识号    384
交易次数       2
交易金额     728
Name: 383, dtype: int64
内部标识号    385
交易次数       1
交易金额     758
Name: 384, dtype: int64
内部标识号    386
交易次数       3
交易金额     266
Name: 385, dtype: int64
内部标识号    387
交易次数       1
交易金额     944
Name: 386, dtype: int64
内部标识号    388
交易次数      15
交易金额     439
Name: 387, dtype: int64
内部标识号    389
交易次数      12
交易金额     342
Name: 388, dtype: int64
内部标识号    390
交易次数       2
交易金额     425
Name: 389, dtype: int64
内部标识号    391
交易次数      12
交易金额     410
Name: 390, dtype: int64
内部标识号      392
交易次数       157
交易金额     73735
Name: 391, dtype: int64
内部标识号    393
交易次数       6
交易金额     155
Name: 392, dtype: int64
内部标识号    394
交易次数      13
交易金额     306
Name: 393, dtype: int64
内部标识号     395
交易次数        0
交易金额     4493
Name: 394, dtype: int64
内部标识号      396
交易次数         7
交易金额     29883
Name: 395, dtype: int64
内部标识号      397
交易次数         7
交易金额     32745
Name: 396, dtype: int64
内部标识号    398
交易次数       2
交易金额     839
Name: 397, dtype: int64
内部标识号      399
交易次数         6
交易金额     58911
Name: 398, dtype: int64
内部标识号    400
交易次数      14
交易金额     966
Name: 399, dtype: int64
内部标识号    401
交易次数       8
交易金额     147
Name: 400, dtype: int64
内部标识号    402
交易次数      22
交易金额     933
Name: 401, dtype: int64
内部标识号    403
交易次数       7
交易金额     282
Name: 402, dtype: int64
内部标识号    404
交易次数       2
交易金额     465
Name: 403, dtype: int64
内部标识号     405
交易次数       19
交易金额     3106
Name: 404, dtype: int64
内部标识号     406
交易次数       21
交易金额     2208
Name: 405, dtype: int64
内部标识号     407
交易次数        0
交易金额     4698
Name: 406, dtype: int64
内部标识号    408
交易次数       3
交易金额     454
Name: 407, dtype: int64
内部标识号    409
交易次数      22
交易金额     552
Name: 408, dtype: int64
内部标识号    410
交易次数       1
交易金额     710
Name: 409, dtype: int64
内部标识号    411
交易次数       4
交易金额     200
Name: 410, dtype: int64
内部标识号    412
交易次数      10
交易金额     668
Name: 411, dtype: int64
内部标识号    413
交易次数       2
交易金额     939
Name: 412, dtype: int64
内部标识号    414
交易次数       7
交易金额     170
Name: 413, dtype: int64
内部标识号    415
交易次数       3
交易金额     214
Name: 414, dtype: int64
内部标识号      416
交易次数         8
交易金额     67799
Name: 415, dtype: int64
内部标识号    417
交易次数      15
交易金额     343
Name: 416, dtype: int64
内部标识号    418
交易次数      15
交易金额     921
Name: 417, dtype: int64
内部标识号    419
交易次数       2
交易金额     448
Name: 418, dtype: int64
内部标识号     420
交易次数        0
交易金额     5313
Name: 419, dtype: int64
内部标识号    421
交易次数      12
交易金额     365
Name: 420, dtype: int64
内部标识号    422
交易次数       4
交易金额     152
Name: 421, dtype: int64
内部标识号    423
交易次数       2
交易金额     319
Name: 422, dtype: int64
内部标识号    424
交易次数       3
交易金额     368
Name: 423, dtype: int64
内部标识号    425
交易次数       9
交易金额     965
Name: 424, dtype: int64
内部标识号    426
交易次数      11
交易金额     711
Name: 425, dtype: int64
内部标识号    427
交易次数       8
交易金额     235
Name: 426, dtype: int64
内部标识号    428
交易次数       2
交易金额     994
Name: 427, dtype: int64
内部标识号    429
交易次数       4
交易金额     127
Name: 428, dtype: int64
内部标识号     430
交易次数        0
交易金额     7625
Name: 429, dtype: int64
内部标识号    431
交易次数       6
交易金额     144
Name: 430, dtype: int64
内部标识号    432
交易次数      11
交易金额     791
Name: 431, dtype: int64
内部标识号    433
交易次数      23
交易金额     611
Name: 432, dtype: int64
内部标识号    434
交易次数       5
交易金额     227
Name: 433, dtype: int64
内部标识号    435
交易次数       2
交易金额     299
Name: 434, dtype: int64
内部标识号    436
交易次数       3
交易金额     322
Name: 435, dtype: int64
内部标识号    437
交易次数      28
交易金额     758
Name: 436, dtype: int64
内部标识号    438
交易次数      10
交易金额     869
Name: 437, dtype: int64
内部标识号      439
交易次数       161
交易金额     69746
Name: 438, dtype: int64
内部标识号    440
交易次数      15
交易金额     741
Name: 439, dtype: int64
内部标识号    441
交易次数       2
交易金额     322
Name: 440, dtype: int64
内部标识号    442
交易次数       9
交易金额     696
Name: 441, dtype: int64
内部标识号    443
交易次数       4
交易金额     176
Name: 442, dtype: int64
内部标识号    444
交易次数       9
交易金额     830
Name: 443, dtype: int64
内部标识号    445
交易次数       2
交易金额     439
Name: 444, dtype: int64
内部标识号    446
交易次数      11
交易金额     492
Name: 445, dtype: int64
内部标识号      447
交易次数       136
交易金额     80674
Name: 446, dtype: int64
内部标识号    448
交易次数       2
交易金额     245
Name: 447, dtype: int64
内部标识号    449
交易次数       7
交易金额     203
Name: 448, dtype: int64
内部标识号     450
交易次数       24
交易金额     8264
Name: 449, dtype: int64
内部标识号    451
交易次数       5
交易金额     202
Name: 450, dtype: int64
内部标识号    452
交易次数      15
交易金额     309
Name: 451, dtype: int64
内部标识号    453
交易次数       9
交易金额     590
Name: 452, dtype: int64
内部标识号    454
交易次数       1
交易金额     984
Name: 453, dtype: int64
内部标识号    455
交易次数       8
交易金额     320
Name: 454, dtype: int64
内部标识号    456
交易次数       1
交易金额     752
Name: 455, dtype: int64
内部标识号     457
交易次数       25
交易金额     1024
Name: 456, dtype: int64
内部标识号    458
交易次数       1
交易金额     707
Name: 457, dtype: int64
内部标识号    459
交易次数       5
交易金额     168
Name: 458, dtype: int64
内部标识号    460
交易次数      18
交易金额     530
Name: 459, dtype: int64
内部标识号    461
交易次数       3
交易金额     318
Name: 460, dtype: int64
内部标识号    462
交易次数       1
交易金额     602
Name: 461, dtype: int64
内部标识号    463
交易次数      26
交易金额      95
Name: 462, dtype: int64
内部标识号    464
交易次数      13
交易金额     724
Name: 463, dtype: int64
内部标识号    465
交易次数      10
交易金额     460
Name: 464, dtype: int64
内部标识号    466
交易次数       3
交易金额     472
Name: 465, dtype: int64
内部标识号    467
交易次数       2
交易金额     343
Name: 466, dtype: int64
内部标识号    468
交易次数       5
交易金额     241
Name: 467, dtype: int64
内部标识号    469
交易次数       1
交易金额     545
Name: 468, dtype: int64
内部标识号    470
交易次数       1
交易金额     801
Name: 469, dtype: int64
内部标识号    471
交易次数       1
交易金额     867
Name: 470, dtype: int64
内部标识号    472
交易次数      20
交易金额     885
Name: 471, dtype: int64
内部标识号    473
交易次数       4
交易金额     267
Name: 472, dtype: int64
内部标识号    474
交易次数       2
交易金额     276
Name: 473, dtype: int64
内部标识号      475
交易次数         5
交易金额     99192
Name: 474, dtype: int64
内部标识号    476
交易次数       3
交易金额     165
Name: 475, dtype: int64
内部标识号    477
交易次数       2
交易金额     354
Name: 476, dtype: int64
内部标识号    478
交易次数       3
交易金额     291
Name: 477, dtype: int64
内部标识号    479
交易次数      19
交易金额     986
Name: 478, dtype: int64
内部标识号      480
交易次数       201
交易金额     79391
Name: 479, dtype: int64
内部标识号    481
交易次数      21
交易金额      57
Name: 480, dtype: int64
内部标识号      482
交易次数         5
交易金额     64206
Name: 481, dtype: int64
内部标识号    483
交易次数       3
交易金额     132
Name: 482, dtype: int64
内部标识号      484
交易次数         7
交易金额     69938
Name: 483, dtype: int64
内部标识号    485
交易次数       8
交易金额     298
Name: 484, dtype: int64
内部标识号    486
交易次数      22
交易金额     999
Name: 485, dtype: int64
内部标识号    487
交易次数       2
交易金额     427
Name: 486, dtype: int64
内部标识号    488
交易次数       2
交易金额     555
Name: 487, dtype: int64
内部标识号    489
交易次数      15
交易金额     631
Name: 488, dtype: int64
内部标识号    490
交易次数      12
交易金额     766
Name: 489, dtype: int64
内部标识号    491
交易次数       3
交易金额     323
Name: 490, dtype: int64
内部标识号     492
交易次数        1
交易金额     8623
Name: 491, dtype: int64
内部标识号    493
交易次数      15
交易金额     535
Name: 492, dtype: int64
内部标识号      494
交易次数       226
交易金额     47612
Name: 493, dtype: int64
内部标识号    495
交易次数       3
交易金额     310
Name: 494, dtype: int64
内部标识号     496
交易次数       19
交易金额     7164
Name: 495, dtype: int64
内部标识号     497
交易次数       25
交易金额     6018
Name: 496, dtype: int64
内部标识号     498
交易次数       18
交易金额     5190
Name: 497, dtype: int64
内部标识号    499
交易次数      25
交易金额     738
Name: 498, dtype: int64
内部标识号     500
交易次数        1
交易金额     8411
Name: 499, dtype: int64
内部标识号    501
交易次数      14
交易金额     716
Name: 500, dtype: int64
内部标识号    502
交易次数      14
交易金额     464
Name: 501, dtype: int64
内部标识号      503
交易次数        49
交易金额     12548
Name: 502, dtype: int64
内部标识号    504
交易次数       2
交易金额     583
Name: 503, dtype: int64
内部标识号    505
交易次数       8
交易金额     171
Name: 504, dtype: int64
内部标识号    506
交易次数      15
交易金额     692
Name: 505, dtype: int64
内部标识号     507
交易次数       21
交易金额     2684
Name: 506, dtype: int64
内部标识号    508
交易次数       7
交易金额     144
Name: 507, dtype: int64
内部标识号    509
交易次数       9
交易金额     779
Name: 508, dtype: int64
内部标识号    510
交易次数       9
交易金额     488
Name: 509, dtype: int64
内部标识号    511
交易次数      11
交易金额     471
Name: 510, dtype: int64
内部标识号    512
交易次数       4
交易金额     112
Name: 511, dtype: int64
内部标识号    513
交易次数       8
交易金额     300
Name: 512, dtype: int64
内部标识号    514
交易次数       3
交易金额     168
Name: 513, dtype: int64
内部标识号    515
交易次数       8
交易金额     112
Name: 514, dtype: int64
内部标识号    516
交易次数       8
交易金额     106
Name: 515, dtype: int64
内部标识号    517
交易次数       3
交易金额     339
Name: 516, dtype: int64
内部标识号     518
交易次数        1
交易金额     4365
Name: 517, dtype: int64
内部标识号    519
交易次数       6
交易金额     268
Name: 518, dtype: int64
内部标识号    520
交易次数       5
交易金额     265
Name: 519, dtype: int64
内部标识号    521
交易次数      11
交易金额     794
Name: 520, dtype: int64
内部标识号      522
交易次数         6
交易金额     65537
Name: 521, dtype: int64
内部标识号    523
交易次数       8
交易金额     201
Name: 522, dtype: int64
内部标识号    524
交易次数       3
交易金额     406
Name: 523, dtype: int64
内部标识号    525
交易次数       1
交易金额     873
Name: 524, dtype: int64
内部标识号     526
交易次数       25
交易金额     5160
Name: 525, dtype: int64
内部标识号    527
交易次数       2
交易金额     765
Name: 526, dtype: int64
内部标识号    528
交易次数       3
交易金额     449
Name: 527, dtype: int64
内部标识号    529
交易次数       6
交易金额     288
Name: 528, dtype: int64
内部标识号    530
交易次数       7
交易金额     203
Name: 529, dtype: int64
内部标识号    531
交易次数       6
交易金额     187
Name: 530, dtype: int64
内部标识号    532
交易次数       9
交易金额     948
Name: 531, dtype: int64
内部标识号    533
交易次数       1
交易金额     986
Name: 532, dtype: int64
内部标识号    534
交易次数       2
交易金额     754
Name: 533, dtype: int64
内部标识号    535
交易次数      18
交易金额     801
Name: 534, dtype: int64
内部标识号    536
交易次数       8
交易金额     234
Name: 535, dtype: int64
内部标识号    537
交易次数       2
交易金额     637
Name: 536, dtype: int64
内部标识号    538
交易次数       2
交易金额     979
Name: 537, dtype: int64
内部标识号    539
交易次数       4
交易金额     239
Name: 538, dtype: int64
内部标识号    540
交易次数       9
交易金额     959
Name: 539, dtype: int64
内部标识号     541
交易次数       18
交易金额     3450
Name: 540, dtype: int64
内部标识号    542
交易次数       8
交易金额     247
Name: 541, dtype: int64
内部标识号      543
交易次数       107
交易金额     69996
Name: 542, dtype: int64
内部标识号    544
交易次数       2
交易金额     965
Name: 543, dtype: int64
内部标识号    545
交易次数      13
交易金额     695
Name: 544, dtype: int64
内部标识号    546
交易次数      14
交易金额     891
Name: 545, dtype: int64
内部标识号    547
交易次数       2
交易金额     401
Name: 546, dtype: int64
内部标识号    548
交易次数       2
交易金额     727
Name: 547, dtype: int64
内部标识号    549
交易次数      10
交易金额     683
Name: 548, dtype: int64
内部标识号    550
交易次数       6
交易金额     109
Name: 549, dtype: int64
内部标识号     551
交易次数        0
交易金额     7525
Name: 550, dtype: int64
内部标识号     552
交易次数        0
交易金额     5192
Name: 551, dtype: int64
内部标识号    553
交易次数       8
交易金额     182
Name: 552, dtype: int64
内部标识号    554
交易次数       3
交易金额     262
Name: 553, dtype: int64
内部标识号    555
交易次数       3
交易金额     357
Name: 554, dtype: int64
内部标识号    556
交易次数       2
交易金额     413
Name: 555, dtype: int64
内部标识号    557
交易次数       3
交易金额     152
Name: 556, dtype: int64
内部标识号      558
交易次数       230
交易金额     95143
Name: 557, dtype: int64
内部标识号     559
交易次数       24
交易金额     4529
Name: 558, dtype: int64
内部标识号    560
交易次数       1
交易金额     783
Name: 559, dtype: int64
内部标识号      561
交易次数         5
交易金额     54524
Name: 560, dtype: int64
内部标识号    562
交易次数       9
交易金额     369
Name: 561, dtype: int64
内部标识号    563
交易次数      15
交易金额     654
Name: 562, dtype: int64
内部标识号    564
交易次数      12
交易金额     442
Name: 563, dtype: int64
内部标识号    565
交易次数      10
交易金额     419
Name: 564, dtype: int64
内部标识号      566
交易次数        38
交易金额     51799
Name: 565, dtype: int64
内部标识号    567
交易次数       5
交易金额     292
Name: 566, dtype: int64
内部标识号    568
交易次数       8
交易金额     437
Name: 567, dtype: int64
内部标识号     569
交易次数       19
交易金额     7895
Name: 568, dtype: int64
内部标识号    570
交易次数       3
交易金额     120
Name: 569, dtype: int64
内部标识号    571
交易次数       2
交易金额     558
Name: 570, dtype: int64
内部标识号    572
交易次数       1
交易金额     653
Name: 571, dtype: int64
内部标识号    573
交易次数       9
交易金额     714
Name: 572, dtype: int64
内部标识号    574
交易次数       2
交易金额     476
Name: 573, dtype: int64
内部标识号    575
交易次数       2
交易金额     275
Name: 574, dtype: int64
内部标识号    576
交易次数       1
交易金额     788
Name: 575, dtype: int64
内部标识号    577
交易次数       2
交易金额     464
Name: 576, dtype: int64
内部标识号    578
交易次数       2
交易金额     485
Name: 577, dtype: int64
内部标识号     579
交易次数        0
交易金额     9484
Name: 578, dtype: int64
内部标识号    580
交易次数       3
交易金额     331
Name: 579, dtype: int64
内部标识号    581
交易次数       5
交易金额     225
Name: 580, dtype: int64
内部标识号    582
交易次数      18
交易金额     780
Name: 581, dtype: int64
内部标识号     583
交易次数       19
交易金额     7832
Name: 582, dtype: int64
内部标识号    584
交易次数       2
交易金额     315
Name: 583, dtype: int64
内部标识号    585
交易次数       3
交易金额     347
Name: 584, dtype: int64
内部标识号      586
交易次数       144
交易金额     21581
Name: 585, dtype: int64
内部标识号    587
交易次数      17
交易金额      67
Name: 586, dtype: int64
内部标识号    588
交易次数       1
交易金额     620
Name: 587, dtype: int64
内部标识号    589
交易次数      12
交易金额     718
Name: 588, dtype: int64
内部标识号    590
交易次数       3
交易金额     257
Name: 589, dtype: int64
内部标识号    591
交易次数      13
交易金额     349
Name: 590, dtype: int64
内部标识号    592
交易次数      20
交易金额      51
Name: 591, dtype: int64
内部标识号    593
交易次数       5
交易金额     263
Name: 592, dtype: int64
内部标识号    594
交易次数       8
交易金额     411
Name: 593, dtype: int64
内部标识号    595
交易次数       8
交易金额     271
Name: 594, dtype: int64
内部标识号    596
交易次数       1
交易金额     626
Name: 595, dtype: int64
内部标识号    597
交易次数      10
交易金额     477
Name: 596, dtype: int64
内部标识号    598
交易次数      11
交易金额     576
Name: 597, dtype: int64
内部标识号    599
交易次数      12
交易金额     355
Name: 598, dtype: int64
内部标识号     600
交易次数        1
交易金额     4200
Name: 599, dtype: int64
内部标识号    601
交易次数      15
交易金额     762
Name: 600, dtype: int64
内部标识号    602
交易次数      13
交易金额     448
Name: 601, dtype: int64
内部标识号    603
交易次数      13
交易金额     446
Name: 602, dtype: int64
内部标识号    604
交易次数       5
交易金额     153
Name: 603, dtype: int64
内部标识号    605
交易次数       3
交易金额     136
Name: 604, dtype: int64
内部标识号    606
交易次数       9
交易金额     565
Name: 605, dtype: int64
内部标识号      607
交易次数       118
交易金额     55792
Name: 606, dtype: int64
内部标识号    608
交易次数      13
交易金额     890
Name: 607, dtype: int64
内部标识号    609
交易次数       7
交易金额     233
Name: 608, dtype: int64
内部标识号    610
交易次数      13
交易金额     776
Name: 609, dtype: int64
内部标识号    611
交易次数       2
交易金额     410
Name: 610, dtype: int64
内部标识号    612
交易次数       9
交易金额     909
Name: 611, dtype: int64
内部标识号    613
交易次数       8
交易金额     233
Name: 612, dtype: int64
内部标识号     614
交易次数       21
交易金额     5687
Name: 613, dtype: int64
内部标识号    615
交易次数      14
交易金额     306
Name: 614, dtype: int64
内部标识号    616
交易次数       2
交易金额     630
Name: 615, dtype: int64
内部标识号    617
交易次数       6
交易金额     191
Name: 616, dtype: int64
内部标识号     618
交易次数        1
交易金额     3014
Name: 617, dtype: int64
内部标识号     619
交易次数       30
交易金额     7571
Name: 618, dtype: int64
内部标识号    620
交易次数       2
交易金额     648
Name: 619, dtype: int64
内部标识号     621
交易次数        1
交易金额     7150
Name: 620, dtype: int64
内部标识号    622
交易次数      11
交易金额     653
Name: 621, dtype: int64
内部标识号    623
交易次数      13
交易金额     589
Name: 622, dtype: int64
内部标识号    624
交易次数       8
交易金额     424
Name: 623, dtype: int64
内部标识号    625
交易次数       6
交易金额     110
Name: 624, dtype: int64
内部标识号    626
交易次数       7
交易金额     223
Name: 625, dtype: int64
内部标识号    627
交易次数      10
交易金额     302
Name: 626, dtype: int64
内部标识号    628
交易次数       5
交易金额     229
Name: 627, dtype: int64
内部标识号    629
交易次数       2
交易金额     466
Name: 628, dtype: int64
内部标识号    630
交易次数       9
交易金额     544
Name: 629, dtype: int64
内部标识号      631
交易次数        37
交易金额     34665
Name: 630, dtype: int64
内部标识号     632
交易次数       29
交易金额     4939
Name: 631, dtype: int64
内部标识号    633
交易次数      12
交易金额     457
Name: 632, dtype: int64
内部标识号    634
交易次数       6
交易金额     233
Name: 633, dtype: int64
内部标识号    635
交易次数      25
交易金额      66
Name: 634, dtype: int64
内部标识号    636
交易次数       1
交易金额     707
Name: 635, dtype: int64
内部标识号    637
交易次数       3
交易金额     317
Name: 636, dtype: int64
内部标识号    638
交易次数       2
交易金额     503
Name: 637, dtype: int64
内部标识号    639
交易次数       1
交易金额     699
Name: 638, dtype: int64
内部标识号    640
交易次数       8
交易金额     453
Name: 639, dtype: int64
内部标识号    641
交易次数      10
交易金额     579
Name: 640, dtype: int64
内部标识号    642
交易次数       2
交易金额     379
Name: 641, dtype: int64
内部标识号    643
交易次数       3
交易金额     216
Name: 642, dtype: int64
内部标识号    644
交易次数       6
交易金额     120
Name: 643, dtype: int64
内部标识号    645
交易次数      13
交易金额     925
Name: 644, dtype: int64
内部标识号    646
交易次数       4
交易金额     263
Name: 645, dtype: int64
内部标识号    647
交易次数       6
交易金额     276
Name: 646, dtype: int64
内部标识号    648
交易次数       6
交易金额     105
Name: 647, dtype: int64
内部标识号    649
交易次数       6
交易金额     125
Name: 648, dtype: int64
内部标识号    650
交易次数       3
交易金额     234
Name: 649, dtype: int64
内部标识号    651
交易次数       9
交易金额     417
Name: 650, dtype: int64
内部标识号    652
交易次数       8
交易金额     577
Name: 651, dtype: int64
内部标识号    653
交易次数       3
交易金额     431
Name: 652, dtype: int64
内部标识号    654
交易次数       8
交易金额     314
Name: 653, dtype: int64
内部标识号     655
交易次数        0
交易金额     9611
Name: 654, dtype: int64
内部标识号    656
交易次数       2
交易金额     648
Name: 655, dtype: int64
内部标识号    657
交易次数       1
交易金额     531
Name: 656, dtype: int64
内部标识号    658
交易次数       2
交易金额     174
Name: 657, dtype: int64
内部标识号     659
交易次数       27
交易金额     8513
Name: 658, dtype: int64
内部标识号    660
交易次数      11
交易金额     587
Name: 659, dtype: int64
内部标识号    661
交易次数      11
交易金额     797
Name: 660, dtype: int64
内部标识号    662
交易次数       1
交易金额     947
Name: 661, dtype: int64
内部标识号    663
交易次数       7
交易金额     224
Name: 662, dtype: int64
内部标识号    664
交易次数       6
交易金额     205
Name: 663, dtype: int64
内部标识号     665
交易次数       27
交易金额     5539
Name: 664, dtype: int64
内部标识号    666
交易次数      11
交易金额     606
Name: 665, dtype: int64
内部标识号      667
交易次数       299
交易金额     96987
Name: 666, dtype: int64
内部标识号    668
交易次数      10
交易金额     932
Name: 667, dtype: int64
内部标识号    669
交易次数      11
交易金额     818
Name: 668, dtype: int64
内部标识号    670
交易次数       1
交易金额     679
Name: 669, dtype: int64
内部标识号    671
交易次数       8
交易金额     197
Name: 670, dtype: int64
内部标识号    672
交易次数       2
交易金额     513
Name: 671, dtype: int64
内部标识号    673
交易次数       2
交易金额     311
Name: 672, dtype: int64
内部标识号      674
交易次数         7
交易金额     20726
Name: 673, dtype: int64
内部标识号    675
交易次数       2
交易金额     383
Name: 674, dtype: int64
内部标识号    676
交易次数      29
交易金额      70
Name: 675, dtype: int64
内部标识号    677
交易次数       9
交易金额     916
Name: 676, dtype: int64
内部标识号    678
交易次数       9
交易金额     917
Name: 677, dtype: int64

Name: 722, dtype: int64
内部标识号    724
交易次数       8
交易金额     400
Name: 723, dtype: int64
内部标识号    725
交易次数       2
交易金额     396
Name: 724, dtype: int64
内部标识号    726
交易次数       8
交易金额     265
Name: 725, dtype: int64
内部标识号    727
交易次数       5
交易金额     125
Name: 726, dtype: int64
内部标识号    728
交易次数       2
交易金额     735
Name: 727, dtype: int64
内部标识号    729
交易次数       3
交易金额     242
Name: 728, dtype: int64
内部标识号    730
交易次数      15
交易金额     677
Name: 729, dtype: int64
内部标识号     731
交易次数       19
交易金额     1508
Name: 730, dtype: int64
内部标识号    732
交易次数       7
交易金额     179
Name: 731, dtype: int64
内部标识号    733
交易次数      14
交易金额     323
Name: 732, dtype: int64
内部标识号     734
交易次数        0
交易金额     1804
Name: 733, dtype: int64
内部标识号    735
交易次数       3
交易金额     437
Name: 734, dtype: int64
内部标识号    736
交易次数       2
交易金额     224
Name: 735, dtype: int64
内部标识号    737
交易次数       5
交易金额     127
Name: 736, dtype: int64
内部标识号    738
交易次数      14
交易金额     389
Name: 737, dtype: int64
内部标识号      739
交易次数         4
交易金额     16388
Name: 738, dtype: int64
内部标识号    740
交易次数       1
交易金额     782
Name: 739, dtype: int64
内部标识号    741
交易次数       5
交易金额     289
Name: 740, dtype: int64
内部标识号    742
交易次数      11
交易金额     379
Name: 741, dtype: int64
内部标识号    743
交易次数      10
交易金额     352
Name: 742, dtype: int64
内部标识号    744
交易次数       3
交易金额     341
Name: 743, dtype: int64
内部标识号      745
交易次数        37
交易金额     98246
Name: 744, dtype: int64
内部标识号    746
交易次数       2
交易金额     876
Name: 745, dtype: int64
内部标识号      747
交易次数         6
交易金额     37788
Name: 746, dtype: int64
内部标识号     748
交易次数        0
交易金额     7222
Name: 747, dtype: int64
内部标识号    749
交易次数       2
交易金额     515
Name: 748, dtype: int64
内部标识号    750
交易次数      10
交易金额     702
Name: 749, dtype: int64
内部标识号     751
交易次数        1
交易金额     8877
Name: 750, dtype: int64
内部标识号     752
交易次数        1
交易金额     4892
Name: 751, dtype: int64
内部标识号    753
交易次数      12
交易金额     401
Name: 752, dtype: int64
内部标识号     754
交易次数       25
交易金额     8081
Name: 753, dtype: int64
内部标识号    755
交易次数      21
交易金额     665
Name: 754, dtype: int64
内部标识号     756
交易次数       28
交易金额     3437
Name: 755, dtype: int64
内部标识号    757
交易次数       2
交易金额     765
Name: 756, dtype: int64
内部标识号    758
交易次数       5
交易金额     254
Name: 757, dtype: int64
内部标识号    759
交易次数      15
交易金额     805
Name: 758, dtype: int64
内部标识号    760
交易次数      10
交易金额     989
Name: 759, dtype: int64
内部标识号    761
交易次数      11
交易金额     365
Name: 760, dtype: int64
内部标识号    762
交易次数       9
交易金额     459
Name: 761, dtype: int64
内部标识号     763
交易次数       26
交易金额     3279
Name: 762, dtype: int64
内部标识号    764
交易次数       7
交易金额     146
Name: 763, dtype: int64
内部标识号    765
交易次数      13
交易金额     988
Name: 764, dtype: int64
内部标识号    766
交易次数       3
交易金额     257
Name: 765, dtype: int64
内部标识号     767
交易次数        1
交易金额     9960
Name: 766, dtype: int64
内部标识号    768
交易次数       1
交易金额     969
Name: 767, dtype: int64
内部标识号    769
交易次数       6
交易金额     147
Name: 768, dtype: int64
内部标识号     770
交易次数       30
交易金额     3857
Name: 769, dtype: int64
内部标识号    771
交易次数       4
交易金额     188
Name: 770, dtype: int64
内部标识号    772
交易次数      12
交易金额     976
Name: 771, dtype: int64
内部标识号    773
交易次数      11
交易金额     390
Name: 772, dtype: int64
内部标识号    774
交易次数       2
交易金额     890
Name: 773, dtype: int64
内部标识号    775
交易次数       1
交易金额     565
Name: 774, dtype: int64
内部标识号    776
交易次数       8
交易金额     488
Name: 775, dtype: int64
内部标识号     777
交易次数        0
交易金额     9735
Name: 776, dtype: int64
内部标识号    778
交易次数       3
交易金额     259
Name: 777, dtype: int64
内部标识号    779
交易次数       9
交易金额     611
Name: 778, dtype: int64
内部标识号      780
交易次数         3
交易金额     21428
Name: 779, dtype: int64
内部标识号    781
交易次数      14
交易金额     832
Name: 780, dtype: int64
内部标识号     782
交易次数        0
交易金额     7108
Name: 781, dtype: int64
内部标识号    783
交易次数      15
交易金额     862
Name: 782, dtype: int64
内部标识号    784
交易次数       4
交易金额     272
Name: 783, dtype: int64
内部标识号    785
交易次数      13
交易金额     789
Name: 784, dtype: int64
内部标识号    786
交易次数       8
交易金额     265
Name: 785, dtype: int64
内部标识号     787
交易次数       27
交易金额     9288
Name: 786, dtype: int64
内部标识号     788
交易次数        1
交易金额     1760
Name: 787, dtype: int64
内部标识号    789
交易次数       2
交易金额     645
Name: 788, dtype: int64
内部标识号    790
交易次数      13
交易金额     385
Name: 789, dtype: int64
内部标识号    791
交易次数       1
交易金额     529
Name: 790, dtype: int64
内部标识号    792
交易次数       5
交易金额     248
Name: 791, dtype: int64
内部标识号     793
交易次数       19
交易金额     2206
Name: 792, dtype: int64
内部标识号      794
交易次数         4
交易金额     42905
Name: 793, dtype: int64
内部标识号    795
交易次数       2
交易金额     457
Name: 794, dtype: int64
内部标识号    796
交易次数      12
交易金额     665
Name: 795, dtype: int64
内部标识号    797
交易次数       1
交易金额     823
Name: 796, dtype: int64
内部标识号    798
交易次数      12
交易金额     498
Name: 797, dtype: int64
内部标识号    799
交易次数       3
交易金额     314
Name: 798, dtype: int64
内部标识号    800
交易次数       1
交易金额     896
Name: 799, dtype: int64
内部标识号     801
交易次数       23
交易金额     2038
Name: 800, dtype: int64
内部标识号     802
交易次数       30
交易金额     1978
Name: 801, dtype: int64
内部标识号    803
交易次数      11
交易金额     494
Name: 802, dtype: int64
内部标识号    804
交易次数      12
交易金额     759
Name: 803, dtype: int64
内部标识号    805
交易次数       3
交易金额     494
Name: 804, dtype: int64
内部标识号    806
交易次数      13
交易金额     722
Name: 805, dtype: int64
内部标识号    807
交易次数       3
交易金额     395
Name: 806, dtype: int64
内部标识号     808
交易次数        0
交易金额     1956
Name: 807, dtype: int64
内部标识号     809
交易次数        0
交易金额     8371
Name: 808, dtype: int64
内部标识号    810
交易次数      15
交易金额     886
Name: 809, dtype: int64
内部标识号    811
交易次数       2
交易金额     700
Name: 810, dtype: int64
内部标识号    812
交易次数       4
交易金额     189
Name: 811, dtype: int64
内部标识号    813
交易次数      15
交易金额     544
Name: 812, dtype: int64
内部标识号    814
交易次数      12
交易金额     573
Name: 813, dtype: int64
内部标识号    815
交易次数       3
交易金额     245
Name: 814, dtype: int64
内部标识号    816
交易次数      15
交易金额     912
Name: 815, dtype: int64
内部标识号    817
交易次数       2
交易金额     852
Name: 816, dtype: int64
内部标识号    818
交易次数      15
交易金额     694
Name: 817, dtype: int64
内部标识号    819
交易次数       9
交易金额     799
Name: 818, dtype: int64
内部标识号     820
交易次数        1
交易金额     6481
Name: 819, dtype: int64
内部标识号    821
交易次数       3
交易金额     340
Name: 820, dtype: int64
内部标识号      822
交易次数       200
交易金额     95574
Name: 821, dtype: int64
内部标识号    823
交易次数      11
交易金额     332
Name: 822, dtype: int64
内部标识号    824
交易次数      26
交易金额      81
Name: 823, dtype: int64
内部标识号    825
交易次数       2
交易金额     944
Name: 824, dtype: int64
内部标识号    826
交易次数      13
交易金额     854
Name: 825, dtype: int64
内部标识号    827
交易次数      13
交易金额     486
Name: 826, dtype: int64
内部标识号     828
交易次数       27
交易金额     8464
Name: 827, dtype: int64
内部标识号     829
交易次数       22
交易金额     3765
Name: 828, dtype: int64
内部标识号    830
交易次数       4
交易金额     286
Name: 829, dtype: int64
内部标识号    831
交易次数      14
交易金额     418
Name: 830, dtype: int64
内部标识号    832
交易次数       3
交易金额     326
Name: 831, dtype: int64
内部标识号    833
交易次数      14
交易金额     920
Name: 832, dtype: int64
内部标识号    834
交易次数       3
交易金额     153
Name: 833, dtype: int64
内部标识号     835
交易次数        0
交易金额     9397
Name: 834, dtype: int64
内部标识号    836
交易次数      15
交易金额     920
Name: 835, dtype: int64
内部标识号    837
交易次数       3
交易金额     249
Name: 836, dtype: int64
内部标识号    838
交易次数      12
交易金额     352
Name: 837, dtype: int64
内部标识号    839
交易次数      12
交易金额     470
Name: 838, dtype: int64
内部标识号    840
交易次数       7
交易金额     181
Name: 839, dtype: int64
内部标识号    841
交易次数      12
交易金额     914
Name: 840, dtype: int64
内部标识号    842
交易次数      14
交易金额     384
Name: 841, dtype: int64
内部标识号    843
交易次数      11
交易金额     603
Name: 842, dtype: int64
内部标识号      844
交易次数         5
交易金额     65624
Name: 843, dtype: int64
内部标识号    845
交易次数      15
交易金额     884
Name: 844, dtype: int64
内部标识号      846
交易次数         4
交易金额     19492
Name: 845, dtype: int64
内部标识号      847
交易次数       215
交易金额     87475
Name: 846, dtype: int64
内部标识号      848
交易次数       231
交易金额     14888
Name: 847, dtype: int64
内部标识号    849
交易次数       2
交易金额     819
Name: 848, dtype: int64
内部标识号      850
交易次数       152
交易金额     86680
Name: 849, dtype: int64
内部标识号    851
交易次数       7
交易金额     177
Name: 850, dtype: int64
内部标识号    852
交易次数      10
交易金额     798
Name: 851, dtype: int64
内部标识号    853
交易次数       1
交易金额     979
Name: 852, dtype: int64
内部标识号    854
交易次数       8
交易金额     938
Name: 853, dtype: int64
内部标识号    855
交易次数      15
交易金额     524
Name: 854, dtype: int64
内部标识号    856
交易次数       2
交易金额     596
Name: 855, dtype: int64
内部标识号    857
交易次数      10
交易金额     489
Name: 856, dtype: int64
内部标识号    858
交易次数      11
交易金额     320
Name: 857, dtype: int64
内部标识号    859
交易次数       2
交易金额     837
Name: 858, dtype: int64
内部标识号    860
交易次数       2
交易金额     661
Name: 859, dtype: int64
内部标识号    861
交易次数      20
交易金额     523
Name: 860, dtype: int64
内部标识号    862
交易次数       3
交易金额     213
Name: 861, dtype: int64
内部标识号     863
交易次数       30
交易金额     4674
Name: 862, dtype: int64
内部标识号    864
交易次数       5
交易金额     176
Name: 863, dtype: int64
内部标识号     865
交易次数       27
交易金额     5050
Name: 864, dtype: int64
内部标识号    866
交易次数       2
交易金额     463
Name: 865, dtype: int64
内部标识号    867
交易次数      14
交易金额     333
Name: 866, dtype: int64
内部标识号    868
交易次数       2
交易金额     634
Name: 867, dtype: int64
内部标识号    869
交易次数      10
交易金额     428
Name: 868, dtype: int64
内部标识号     870
交易次数       27
交易金额     5426
Name: 869, dtype: int64
内部标识号    871
交易次数       1
交易金额     644
Name: 870, dtype: int64
内部标识号    872
交易次数       8
交易金额     788
Name: 871, dtype: int64
内部标识号     873
交易次数       15
交易金额     7297
Name: 872, dtype: int64
内部标识号    874
交易次数       2
交易金额     484
Name: 873, dtype: int64
内部标识号    875
交易次数       3
交易金额     421
Name: 874, dtype: int64
内部标识号    876
交易次数       3
交易金额     385
Name: 875, dtype: int64
内部标识号     877
交易次数        0
交易金额     6164
Name: 876, dtype: int64
内部标识号     878
交易次数        0
交易金额     9974
Name: 877, dtype: int64
内部标识号    879
交易次数       3
交易金额     309
Name: 878, dtype: int64
内部标识号     880
交易次数       28
交易金额     1251
Name: 879, dtype: int64
内部标识号    881
交易次数      11
交易金额     380
Name: 880, dtype: int64
内部标识号    882
交易次数      10
交易金额     308
Name: 881, dtype: int64
内部标识号     883
交易次数        1
交易金额     1914
Name: 882, dtype: int64
内部标识号     884
交易次数       21
交易金额     1619
Name: 883, dtype: int64
内部标识号    885
交易次数       2
交易金额     524
Name: 884, dtype: int64
内部标识号    886
交易次数       6
交易金额     229
Name: 885, dtype: int64
内部标识号    887
交易次数      15
交易金额     302
Name: 886, dtype: int64
内部标识号    888
交易次数       1
交易金额     984
Name: 887, dtype: int64
内部标识号    889
交易次数       3
交易金额     114
Name: 888, dtype: int64
内部标识号    890
交易次数      14
交易金额     644
Name: 889, dtype: int64
内部标识号    891
交易次数      14
交易金额     338
Name: 890, dtype: int64
内部标识号    892
交易次数      10
交易金额     746
Name: 891, dtype: int64
内部标识号    893
交易次数       3
交易金额     398
Name: 892, dtype: int64
内部标识号    894
交易次数       8
交易金额     285
Name: 893, dtype: int64
内部标识号    895
交易次数       4
交易金额     162
Name: 894, dtype: int64
内部标识号    896
交易次数       3
交易金额     317
Name: 895, dtype: int64
内部标识号    897
交易次数       3
交易金额     317
Name: 896, dtype: int64
内部标识号    898
交易次数       3
交易金额     258
Name: 897, dtype: int64
内部标识号      899
交易次数       181
交易金额     30171
Name: 898, dtype: int64
内部标识号    900
交易次数      11
交易金额     394
Name: 899, dtype: int64
内部标识号    901
交易次数      11
交易金额     584
Name: 900, dtype: int64
内部标识号    902
交易次数       3
交易金额     223
Name: 901, dtype: int64
内部标识号     903
交易次数        0
交易金额     2493
Name: 902, dtype: int64
内部标识号     904
交易次数       18
交易金额     1220
Name: 903, dtype: int64
内部标识号    905
交易次数       2
交易金额     690
Name: 904, dtype: int64
内部标识号    906
交易次数       3
交易金额     178
Name: 905, dtype: int64
内部标识号    907
交易次数       9
交易金额     865
Name: 906, dtype: int64
内部标识号     908
交易次数       22
交易金额     1936
Name: 907, dtype: int64
内部标识号     909
交易次数       15
交易金额     9989
Name: 908, dtype: int64
内部标识号    910
交易次数      14
交易金额     923
Name: 909, dtype: int64
内部标识号    911
交易次数      18
交易金额     769
Name: 910, dtype: int64
内部标识号     912
交易次数        0
交易金额     6789
Name: 911, dtype: int64
内部标识号    913
交易次数      15
交易金额     801
Name: 912, dtype: int64
内部标识号    914
交易次数       9
交易金额     732
Name: 913, dtype: int64
内部标识号    915
交易次数       8
交易金额     778
Name: 914, dtype: int64
内部标识号    916
交易次数      12
交易金额     859
Name: 915, dtype: int64
内部标识号    917
交易次数       3
交易金额     362
Name: 916, dtype: int64
内部标识号    918
交易次数       5
交易金额     196
Name: 917, dtype: int64
内部标识号    919
交易次数       1
交易金额     510
Name: 918, dtype: int64
内部标识号    920
交易次数       8
交易金额     576
Name: 919, dtype: int64
内部标识号    921
交易次数       2
交易金额     483
Name: 920, dtype: int64
内部标识号    922
交易次数       6
交易金额     102
Name: 921, dtype: int64
内部标识号    923
交易次数      14
交易金额     820
Name: 922, dtype: int64
内部标识号    924
交易次数       6
交易金额     223
Name: 923, dtype: int64
内部标识号    925
交易次数      13
交易金额     321
Name: 924, dtype: int64
内部标识号    926
交易次数       8
交易金额     156
Name: 925, dtype: int64
内部标识号     927
交易次数        0
交易金额     5144
Name: 926, dtype: int64
内部标识号     928
交易次数       24
交易金额     4214
Name: 927, dtype: int64
内部标识号    929
交易次数       7
交易金额     231
Name: 928, dtype: int64
内部标识号      930
交易次数         8
交易金额     78727
Name: 929, dtype: int64
内部标识号    931
交易次数      29
交易金额      34
Name: 930, dtype: int64
内部标识号    932
交易次数      11
交易金额     613
Name: 931, dtype: int64
内部标识号     933
交易次数        0
交易金额     1792
Name: 932, dtype: int64
内部标识号    934
交易次数       1
交易金额     677
Name: 933, dtype: int64
内部标识号    935
交易次数       9
交易金额     333
Name: 934, dtype: int64
内部标识号     936
交易次数        0
交易金额     9685
Name: 935, dtype: int64
内部标识号    937
交易次数       8
交易金额     305
Name: 936, dtype: int64
内部标识号    938
交易次数       3
交易金额     347
Name: 937, dtype: int64
内部标识号    939
交易次数      29
交易金额     827
Name: 938, dtype: int64
内部标识号      940
交易次数         3
交易金额     31268
Name: 939, dtype: int64
内部标识号    941
交易次数       2
交易金额     428
Name: 940, dtype: int64
内部标识号    942
交易次数       8
交易金额     196
Name: 941, dtype: int64
内部标识号    943
交易次数       6
交易金额     194
Name: 942, dtype: int64
内部标识号     944
交易次数       23
交易金额     7174
Name: 943, dtype: int64
内部标识号    945
交易次数      14
交易金额     419
Name: 944, dtype: int64
内部标识号     946
交易次数       26
交易金额     4773
Name: 945, dtype: int64
内部标识号    947
交易次数       8
交易金额     825
Name: 946, dtype: int64
内部标识号     948
交易次数       16
交易金额     9482
Name: 947, dtype: int64
内部标识号    949
交易次数       2
交易金额     920
Name: 948, dtype: int64
内部标识号    950
交易次数      14
交易金额     323
Name: 949, dtype: int64
内部标识号    951
交易次数       3
交易金额     253
Name: 950, dtype: int64
内部标识号      952
交易次数         5
交易金额     20645
Name: 951, dtype: int64
内部标识号      953
交易次数        70
交易金额     17549
Name: 952, dtype: int64
内部标识号    954
交易次数       2
交易金额     783
Name: 953, dtype: int64
内部标识号    955
交易次数       7
交易金额     172
Name: 954, dtype: int64
内部标识号     956
交易次数       20
交易金额     4619
Name: 955, dtype: int64
内部标识号    957
交易次数       3
交易金额     457
Name: 956, dtype: int64
内部标识号    958
交易次数       1
交易金额     675
Name: 957, dtype: int64
内部标识号    959
交易次数       3
交易金额     289
Name: 958, dtype: int64
内部标识号    960
交易次数       8
交易金额     173
Name: 959, dtype: int64
内部标识号    961
交易次数       1
交易金额     932
Name: 960, dtype: int64
内部标识号    962
交易次数      13
交易金额     748
Name: 961, dtype: int64
内部标识号    963
交易次数       4
交易金额     255
Name: 962, dtype: int64
内部标识号    964
交易次数      16
交易金额     626
Name: 963, dtype: int64
内部标识号    965
交易次数      12
交易金额     993
Name: 964, dtype: int64
内部标识号    966
交易次数       3
交易金额     378
Name: 965, dtype: int64
内部标识号    967
交易次数       8
交易金额     942
Name: 966, dtype: int64
内部标识号     968
交易次数        1
交易金额     2669
Name: 967, dtype: int64
内部标识号    969
交易次数       3
交易金额     440
Name: 968, dtype: int64
内部标识号    970
交易次数       9
交易金额     736
Name: 969, dtype: int64
内部标识号    971
交易次数      11
交易金额     347
Name: 970, dtype: int64
内部标识号    972
交易次数       1
交易金额     974
Name: 971, dtype: int64
内部标识号      973
交易次数       294
交易金额     95825
Name: 972, dtype: int64
内部标识号     974
交易次数        1
交易金额     2935
Name: 973, dtype: int64
内部标识号    975
交易次数       2
交易金额     886
Name: 974, dtype: int64
内部标识号    976
交易次数      21
交易金额      26
Name: 975, dtype: int64
内部标识号    977
交易次数       4
交易金额     200
Name: 976, dtype: int64
内部标识号    978
交易次数       1
交易金额     761
Name: 977, dtype: int64
内部标识号    979
交易次数      12
交易金额     940
Name: 978, dtype: int64
内部标识号    980
交易次数      12
交易金额     862
Name: 979, dtype: int64
内部标识号      981
交易次数       143
交易金额     97657
Name: 980, dtype: int64
内部标识号    982
交易次数       6
交易金额     172
Name: 981, dtype: int64
内部标识号    983
交易次数       8
交易金额     618
Name: 982, dtype: int64
内部标识号    984
交易次数       1
交易金额     800
Name: 983, dtype: int64
内部标识号    985
交易次数       6
交易金额     237
Name: 984, dtype: int64
内部标识号    986
交易次数       3
交易金额     152
Name: 985, dtype: int64
内部标识号    987
交易次数      29
交易金额     798
Name: 986, dtype: int64
内部标识号     988
交易次数       29
交易金额     3750
Name: 987, dtype: int64
内部标识号     989
交易次数       21
交易金额     6383
Name: 988, dtype: int64
内部标识号      990
交易次数         8
交易金额     29125
Name: 989, dtype: int64
内部标识号    991
交易次数       8
交易金额     280
Name: 990, dtype: int64
内部标识号    992
交易次数       3
交易金额     293
Name: 991, dtype: int64
内部标识号      993
交易次数       298
交易金额     10762
Name: 992, dtype: int64
内部标识号    994
交易次数      11
交易金额     557
Name: 993, dtype: int64
内部标识号    995
交易次数      12
交易金额     880
Name: 994, dtype: int64
内部标识号    996
交易次数      12
交易金额     697
Name: 995, dtype: int64
内部标识号    997
交易次数      11
交易金额     355
Name: 996, dtype: int64
内部标识号    998
交易次数       9
交易金额     332
Name: 997, dtype: int64
内部标识号      999
交易次数        45
交易金额     83982
Name: 998, dtype: int64
内部标识号    1000
交易次数        0
交易金额     2988
Name: 999, dtype: int64
内部标识号    1001
交易次数        1
交易金额      600
Name: 1000, dtype: int64
内部标识号    1002
交易次数       28
交易金额     3032
Name: 1001, dtype: int64
内部标识号    1003
交易次数       28
交易金额       72
Name: 1002, dtype: int64
内部标识号    1004
交易次数        3
交易金额      133
Name: 1003, dtype: int64
内部标识号    1005
交易次数        9
交易金额      716
Name: 1004, dtype: int64
内部标识号    1006
交易次数        1
交易金额      560
Name: 1005, dtype: int64
内部标识号    1007
交易次数        7
交易金额      281
Name: 1006, dtype: int64
内部标识号    1008
交易次数        0
交易金额     8671
Name: 1007, dtype: int64
内部标识号    1009
交易次数       12
交易金额      361
Name: 1008, dtype: int64
内部标识号    1010
交易次数       12
交易金额      355
Name: 1009, dtype: int64
内部标识号    1011
交易次数        0
交易金额     6267

Name: 1010, dtype: int64
内部标识号    1012
交易次数        2
交易金额      170
Name: 1011, dtype: int64
内部标识号    1013
交易次数        1
交易金额     1247
Name: 1012, dtype: int64
内部标识号     1014
交易次数        36
交易金额     86347
Name: 1013, dtype: int64
内部标识号    1015
交易次数        3
交易金额      500
Name: 1014, dtype: int64
内部标识号    1016
交易次数        3
交易金额      439
Name: 1015, dtype: int64
内部标识号    1017
交易次数        4
交易金额      219
Name: 1016, dtype: int64
内部标识号    1018
交易次数       12
交易金额      500
Name: 1017, dtype: int64
内部标识号    1019
交易次数        9
交易金额      617
Name: 1018, dtype: int64
内部标识号    1020
交易次数        2
交易金额      371
Name: 1019, dtype: int64
内部标识号    1021
交易次数        5
交易金额      148
Name: 1020, dtype: int64
内部标识号    1022
交易次数        2
交易金额      419
Name: 1021, dtype: int64
内部标识号    1023
交易次数        2
交易金额      301
Name: 1022, dtype: int64
内部标识号    1024
交易次数       13
交易金额      529
Name: 1023, dtype: int64
内部标识号    1025
交易次数       29
交易金额     5915
Name: 1024, dtype: int64
内部标识号    1026
交易次数       14
交易金额      834
Name: 1025, dtype: int64
内部标识号     1027
交易次数         7
交易金额     83637
Name: 1026, dtype: int64
内部标识号    1028
交易次数       30
交易金额      538
Name: 1027, dtype: int64
内部标识号     1029
交易次数       126
交易金额     12042
Name: 1028, dtype: int64
内部标识号    1030
交易次数        3
交易金额      310
Name: 1029, dtype: int64
内部标识号    1031
交易次数        3
交易金额      274
Name: 1030, dtype: int64
内部标识号     1032
交易次数         4
交易金额     53695
Name: 1031, dtype: int64
内部标识号    1033
交易次数       29
交易金额      738
Name: 1032, dtype: int64
内部标识号    1034
交易次数        2
交易金额      984
Name: 1033, dtype: int64
内部标识号    1035
交易次数       14
交易金额      366
Name: 1034, dtype: int64
内部标识号    1036
交易次数       10
交易金额      569
Name: 1035, dtype: int64
内部标识号    1037
交易次数        0
交易金额     8618
Name: 1036, dtype: int64
内部标识号    1038
交易次数       30
交易金额     1958
Name: 1037, dtype: int64
内部标识号    1039
交易次数       13
交易金额      948
Name: 1038, dtype: int64
内部标识号    1040
交易次数       15
交易金额      996
Name: 1039, dtype: int64
内部标识号    1041
交易次数        9
交易金额      973
Name: 1040, dtype: int64
内部标识号    1042
交易次数        5
交易金额      229
Name: 1041, dtype: int64
内部标识号    1043
交易次数       23
交易金额      780
Name: 1042, dtype: int64
内部标识号    1044
交易次数        3
交易金额      119
Name: 1043, dtype: int64
内部标识号    1045
交易次数        9
交易金额      790
Name: 1044, dtype: int64
内部标识号    1046
交易次数        1
交易金额      733
Name: 1045, dtype: int64
内部标识号    1047
交易次数       14
交易金额      517
Name: 1046, dtype: int64
内部标识号    1048
交易次数        3
交易金额      344
Name: 1047, dtype: int64
内部标识号    1049
交易次数       23
交易金额     7668
Name: 1048, dtype: int64
内部标识号    1050
交易次数        3
交易金额      345
Name: 1049, dtype: int64
内部标识号    1051
交易次数        3
交易金额      372
Name: 1050, dtype: int64
内部标识号    1052
交易次数        4
交易金额      199
Name: 1051, dtype: int64
内部标识号    1053
交易次数        4
交易金额      114
Name: 1052, dtype: int64
内部标识号     1054
交易次数         3
交易金额     10218
Name: 1053, dtype: int64
内部标识号     1055
交易次数         8
交易金额     84299
Name: 1054, dtype: int64
内部标识号    1056
交易次数        8
交易金额      352
Name: 1055, dtype: int64
内部标识号    1057
交易次数       26
交易金额      929
Name: 1056, dtype: int64
内部标识号    1058
交易次数        2
交易金额      354
Name: 1057, dtype: int64
内部标识号    1059
交易次数       15
交易金额      878
Name: 1058, dtype: int64
内部标识号    1060
交易次数        0
交易金额     1143
Name: 1059, dtype: int64
内部标识号    1061
交易次数       18
交易金额     4043
Name: 1060, dtype: int64
内部标识号    1062
交易次数       11
交易金额      348
Name: 1061, dtype: int64
内部标识号    1063
交易次数       14
交易金额      462
Name: 1062, dtype: int64
内部标识号    1064
交易次数       11
交易金额      975
Name: 1063, dtype: int64
内部标识号    1065
交易次数       23
交易金额      917
Name: 1064, dtype: int64
内部标识号    1066
交易次数       13
交易金额      809
Name: 1065, dtype: int64
内部标识号    1067
交易次数       16
交易金额     4178
Name: 1066, dtype: int64
内部标识号    1068
交易次数        2
交易金额      540
Name: 1067, dtype: int64
内部标识号    1069
交易次数        1
交易金额      918
Name: 1068, dtype: int64
内部标识号    1070
交易次数       15
交易金额      441
Name: 1069, dtype: int64
内部标识号    1071
交易次数       10
交易金额      643
Name: 1070, dtype: int64
内部标识号    1072
交易次数        9
交易金额      324
Name: 1071, dtype: int64
内部标识号     1073
交易次数         4
交易金额     63389
Name: 1072, dtype: int64
内部标识号    1074
交易次数        0
交易金额     9789
Name: 1073, dtype: int64
内部标识号    1075
交易次数        1
交易金额      739
Name: 1074, dtype: int64
内部标识号    1076
交易次数       13
交易金额      733
Name: 1075, dtype: int64
内部标识号    1077
交易次数       12
交易金额      985
Name: 1076, dtype: int64
内部标识号    1078
交易次数       10
交易金额      849
Name: 1077, dtype: int64
内部标识号     1079
交易次数       183
交易金额     34567
Name: 1078, dtype: int64
内部标识号    1080
交易次数        1
交易金额      956
Name: 1079, dtype: int64
内部标识号    1081
交易次数        4
交易金额      275
Name: 1080, dtype: int64
内部标识号    1082
交易次数       27
交易金额      993
Name: 1081, dtype: int64
内部标识号    1083
交易次数        8
交易金额      182
Name: 1082, dtype: int64
内部标识号    1084
交易次数       13
交易金额      753
Name: 1083, dtype: int64
内部标识号    1085
交易次数        3
交易金额      307
Name: 1084, dtype: int64
内部标识号    1086
交易次数        3
交易金额      478
Name: 1085, dtype: int64
内部标识号    1087
交易次数       11
交易金额      585
Name: 1086, dtype: int64
内部标识号    1088
交易次数        6
交易金额      155
Name: 1087, dtype: int64
内部标识号    1089
交易次数        2
交易金额      541
Name: 1088, dtype: int64
内部标识号    1090
交易次数        4
交易金额      277
Name: 1089, dtype: int64
内部标识号     1091
交易次数        97
交易金额     88075
Name: 1090, dtype: int64
内部标识号    1092
交易次数        0
交易金额     2971
Name: 1091, dtype: int64
内部标识号    1093
交易次数        5
交易金额      255
Name: 1092, dtype: int64
内部标识号    1094
交易次数       15
交易金额     4449
Name: 1093, dtype: int64
内部标识号    1095
交易次数       24
交易金额     9814
Name: 1094, dtype: int64
内部标识号    1096
交易次数       14
交易金额      370
Name: 1095, dtype: int64
内部标识号    1097
交易次数        3
交易金额      249
Name: 1096, dtype: int64
内部标识号    1098
交易次数        3
交易金额      205
Name: 1097, dtype: int64
内部标识号    1099
交易次数       10
交易金额      944
Name: 1098, dtype: int64
内部标识号    1100
交易次数       12
交易金额      534
Name: 1099, dtype: int64
内部标识号    1101
交易次数       15
交易金额      925
Name: 1100, dtype: int64
内部标识号    1102
交易次数       22
交易金额     3182
Name: 1101, dtype: int64
内部标识号    1103
交易次数       10
交易金额      552
Name: 1102, dtype: int64
内部标识号    1104
交易次数       14
交易金额      989
Name: 1103, dtype: int64
内部标识号    1105
交易次数        1
交易金额      567
Name: 1104, dtype: int64
内部标识号    1106
交易次数        3
交易金额      266
Name: 1105, dtype: int64
内部标识号    1107
交易次数        6
交易金额      128
Name: 1106, dtype: int64
内部标识号    1108
交易次数       21
交易金额     2609
Name: 1107, dtype: int64
内部标识号    1109
交易次数        9
交易金额      435
Name: 1108, dtype: int64
内部标识号     1110
交易次数       154
交易金额     15561
Name: 1109, dtype: int64
内部标识号    1111
交易次数        0
交易金额     8248
Name: 1110, dtype: int64
内部标识号    1112
交易次数        3
交易金额      439
Name: 1111, dtype: int64
内部标识号    1113
交易次数        2
交易金额      667
Name: 1112, dtype: int64
内部标识号    1114
交易次数        2
交易金额      304
Name: 1113, dtype: int64
内部标识号    1115
交易次数        3
交易金额      342
Name: 1114, dtype: int64
内部标识号    1116
交易次数        7
交易金额      272
Name: 1115, dtype: int64
内部标识号    1117
交易次数        3
交易金额      348
Name: 1116, dtype: int64
内部标识号    1118
交易次数        3
交易金额      337
Name: 1117, dtype: int64
内部标识号    1119
交易次数        2
交易金额      308
Name: 1118, dtype: int64
内部标识号    1120
交易次数        3
交易金额      431
Name: 1119, dtype: int64
内部标识号     1121
交易次数         5
交易金额     56498
Name: 1120, dtype: int64
内部标识号    1122
交易次数        2
交易金额      999
Name: 1121, dtype: int64
内部标识号    1123
交易次数       15
交易金额      792
Name: 1122, dtype: int64
内部标识号    1124
交易次数        1
交易金额      935
Name: 1123, dtype: int64
内部标识号    1125
交易次数        3
交易金额      380
Name: 1124, dtype: int64
内部标识号    1126
交易次数        3
交易金额      144
Name: 1125, dtype: int64
内部标识号    1127
交易次数       30
交易金额     3486
Name: 1126, dtype: int64
内部标识号    1128
交易次数       19
交易金额      746
Name: 1127, dtype: int64
内部标识号    1129
交易次数       10
交易金额      347
Name: 1128, dtype: int64
内部标识号    1130
交易次数        7
交易金额      151
Name: 1129, dtype: int64
内部标识号    1131
交易次数        7
交易金额      176
Name: 1130, dtype: int64
内部标识号    1132
交易次数       14
交易金额      982
Name: 1131, dtype: int64
内部标识号    1133
交易次数        3
交易金额      276
Name: 1132, dtype: int64
内部标识号    1134
交易次数       14
交易金额      895
Name: 1133, dtype: int64
内部标识号    1135
交易次数        8
交易金额      268
Name: 1134, dtype: int64
内部标识号     1136
交易次数       288
交易金额     14078
Name: 1135, dtype: int64
内部标识号    1137
交易次数       10
交易金额      489
Name: 1136, dtype: int64
内部标识号    1138
交易次数        8
交易金额      608
Name: 1137, dtype: int64
内部标识号    1139
交易次数       12
交易金额      887
Name: 1138, dtype: int64
内部标识号    1140
交易次数       13
交易金额      776
Name: 1139, dtype: int64
内部标识号    1141
交易次数        1
交易金额      838
Name: 1140, dtype: int64
内部标识号    1142
交易次数        1
交易金额      890
Name: 1141, dtype: int64
内部标识号    1143
交易次数       23
交易金额      637
Name: 1142, dtype: int64
内部标识号    1144
交易次数        4
交易金额      300
Name: 1143, dtype: int64
内部标识号    1145
交易次数       19
交易金额      882
Name: 1144, dtype: int64
内部标识号    1146
交易次数        8
交易金额      427
Name: 1145, dtype: int64
内部标识号    1147
交易次数       10
交易金额      555
Name: 1146, dtype: int64
内部标识号    1148
交易次数       12
交易金额      335
Name: 1147, dtype: int64
内部标识号    1149
交易次数       28
交易金额      828
Name: 1148, dtype: int64
内部标识号    1150
交易次数        8
交易金额      744
Name: 1149, dtype: int64
内部标识号    1151
交易次数        7
交易金额      102
Name: 1150, dtype: int64
内部标识号     1152
交易次数        90
交易金额     11875
Name: 1151, dtype: int64
内部标识号    1153
交易次数        9
交易金额      388
Name: 1152, dtype: int64
内部标识号    1154
交易次数        9
交易金额      425
Name: 1153, dtype: int64
内部标识号    1155
交易次数       13
交易金额      429
Name: 1154, dtype: int64
内部标识号    1156
交易次数       13
交易金额      370
Name: 1155, dtype: int64
内部标识号    1157
交易次数        9
交易金额      755
Name: 1156, dtype: int64
内部标识号    1158
交易次数        5
交易金额      169
Name: 1157, dtype: int64
内部标识号    1159
交易次数        1
交易金额      848
Name: 1158, dtype: int64
内部标识号    1160
交易次数       12
交易金额      494
Name: 1159, dtype: int64
内部标识号    1161
交易次数        8
交易金额      223
Name: 1160, dtype: int64
内部标识号    1162
交易次数        1
交易金额      808
Name: 1161, dtype: int64
内部标识号     1163
交易次数        83
交易金额     68557
Name: 1162, dtype: int64
内部标识号    1164
交易次数       13
交易金额      441
Name: 1163, dtype: int64
内部标识号    1165
交易次数        8
交易金额      103
Name: 1164, dtype: int64
内部标识号    1166
交易次数       14
交易金额      762
Name: 1165, dtype: int64
内部标识号    1167
交易次数        2
交易金额      384
Name: 1166, dtype: int64
内部标识号    1168
交易次数       18
交易金额     2277
Name: 1167, dtype: int64
内部标识号    1169
交易次数        8
交易金额      463
Name: 1168, dtype: int64
内部标识号    1170
交易次数        8
交易金额      174
Name: 1169, dtype: int64
内部标识号    1171
交易次数       13
交易金额      326
Name: 1170, dtype: int64
内部标识号    1172
交易次数        3
交易金额      276
Name: 1171, dtype: int64
内部标识号    1173
交易次数        0
交易金额     5875
Name: 1172, dtype: int64
内部标识号    1174
交易次数       18
交易金额      891
Name: 1173, dtype: int64
内部标识号    1175
交易次数        2
交易金额      479
Name: 1174, dtype: int64
内部标识号    1176
交易次数       12
交易金额      506
Name: 1175, dtype: int64
内部标识号    1177
交易次数       14
交易金额      631
Name: 1176, dtype: int64
内部标识号    1178
交易次数        2
交易金额      142
Name: 1177, dtype: int64
内部标识号     1179
交易次数         7
交易金额     50637
Name: 1178, dtype: int64
内部标识号    1180
交易次数       20
交易金额     4415
Name: 1179, dtype: int64
内部标识号    1181
交易次数       13
交易金额      597
Name: 1180, dtype: int64
内部标识号    1182
交易次数        8
交易金额      235
Name: 1181, dtype: int64
内部标识号    1183
交易次数        2
交易金额      746
Name: 1182, dtype: int64
内部标识号    1184
交易次数        7
交易金额      287
Name: 1183, dtype: int64
内部标识号    1185
交易次数       11
交易金额      682
Name: 1184, dtype: int64
内部标识号    1186
交易次数        2
交易金额      773
Name: 1185, dtype: int64
内部标识号    1187
交易次数        2
交易金额      640
Name: 1186, dtype: int64
内部标识号    1188
交易次数        7
交易金额      206
Name: 1187, dtype: int64
内部标识号    1189
交易次数        0
交易金额     9661
Name: 1188, dtype: int64
内部标识号    1190
交易次数       21
交易金额      882
Name: 1189, dtype: int64
内部标识号    1191
交易次数       13
交易金额      533
Name: 1190, dtype: int64
内部标识号    1192
交易次数       23
交易金额     6958
Name: 1191, dtype: int64
内部标识号     1193
交易次数       209
交易金额     12739
Name: 1192, dtype: int64
内部标识号    1194
交易次数       12
交易金额      556
Name: 1193, dtype: int64
内部标识号    1195
交易次数        0
交易金额     7652
Name: 1194, dtype: int64
内部标识号    1196
交易次数        3
交易金额      349
Name: 1195, dtype: int64
内部标识号    1197
交易次数        2
交易金额      667
Name: 1196, dtype: int64
内部标识号    1198
交易次数        8
交易金额      954
Name: 1197, dtype: int64
内部标识号    1199
交易次数       12
交易金额      596
Name: 1198, dtype: int64
内部标识号    1200
交易次数        1
交易金额      763
Name: 1199, dtype: int64
内部标识号    1201
交易次数        2
交易金额      886
Name: 1200, dtype: int64
内部标识号    1202
交易次数        9
交易金额      320
Name: 1201, dtype: int64
内部标识号    1203
交易次数       23
交易金额     1814
Name: 1202, dtype: int64
内部标识号    1204
交易次数        9
交易金额      725
Name: 1203, dtype: int64
内部标识号    1205
交易次数       15
交易金额      508
Name: 1204, dtype: int64
内部标识号    1206
交易次数        7
交易金额      292
Name: 1205, dtype: int64
内部标识号    1207
交易次数       25
交易金额      610
Name: 1206, dtype: int64
内部标识号    1208
交易次数       11
交易金额      440
Name: 1207, dtype: int64
内部标识号    1209
交易次数        2
交易金额      307
Name: 1208, dtype: int64
内部标识号    1210
交易次数        2
交易金额      480
Name: 1209, dtype: int64
内部标识号    1211
交易次数        7
交易金额      168
Name: 1210, dtype: int64
内部标识号    1212
交易次数        6
交易金额      265
Name: 1211, dtype: int64
内部标识号    1213
交易次数        1
交易金额      930
Name: 1212, dtype: int64
内部标识号    1214
交易次数        4
交易金额      229
Name: 1213, dtype: int64
内部标识号    1215
交易次数        0
交易金额     9633
Name: 1214, dtype: int64
内部标识号    1216
交易次数        5
交易金额      275
Name: 1215, dtype: int64
内部标识号    1217
交易次数       21
交易金额     8579
Name: 1216, dtype: int64
内部标识号    1218
交易次数        2
交易金额      345
Name: 1217, dtype: int64
内部标识号    1219
交易次数       10
交易金额      385
Name: 1218, dtype: int64
内部标识号    1220
交易次数        0
交易金额     1293
Name: 1219, dtype: int64
内部标识号    1221
交易次数       28
交易金额      566
Name: 1220, dtype: int64
内部标识号    1222
交易次数        2
交易金额      796
Name: 1221, dtype: int64
内部标识号    1223
交易次数       23
交易金额      893
Name: 1222, dtype: int64
内部标识号    1224
交易次数        9
交易金额      754
Name: 1223, dtype: int64
内部标识号    1225
交易次数       15
交易金额      825
Name: 1224, dtype: int64
内部标识号    1226
交易次数       29
交易金额     6284
Name: 1225, dtype: int64
内部标识号    1227
交易次数        9
交易金额      401
Name: 1226, dtype: int64
内部标识号    1228
交易次数        2
交易金额      646
Name: 1227, dtype: int64
内部标识号    1229
交易次数       11
交易金额      474
Name: 1228, dtype: int64
内部标识号    1230
交易次数       14
交易金额      399
Name: 1229, dtype: int64
内部标识号    1231
交易次数        3
交易金额      380
Name: 1230, dtype: int64
内部标识号    1232
交易次数       11
交易金额      368
Name: 1231, dtype: int64
内部标识号    1233
交易次数        1
交易金额      727
Name: 1232, dtype: int64
内部标识号    1234
交易次数        8
交易金额      154
Name: 1233, dtype: int64
内部标识号    1235
交易次数       14
交易金额      563
Name: 1234, dtype: int64
内部标识号    1236
交易次数        2
交易金额      344
Name: 1235, dtype: int64
内部标识号    1237
交易次数        9
交易金额      375
Name: 1236, dtype: int64
内部标识号    1238
交易次数        1
交易金额      983
Name: 1237, dtype: int64
内部标识号     1239
交易次数         8
交易金额     96679
Name: 1238, dtype: int64
内部标识号    1240
交易次数        3
交易金额      238
Name: 1239, dtype: int64
内部标识号    1241
交易次数        7
交易金额      207
Name: 1240, dtype: int64
内部标识号    1242
交易次数        8
交易金额      546
Name: 1241, dtype: int64
内部标识号    1243
交易次数        8
交易金额      199
Name: 1242, dtype: int64
内部标识号    1244
交易次数       10
交易金额      892
Name: 1243, dtype: int64
内部标识号    1245
交易次数        4
交易金额      195
Name: 1244, dtype: int64
内部标识号    1246
交易次数       15
交易金额      520
Name: 1245, dtype: int64
内部标识号    1247
交易次数       12
交易金额      369
Name: 1246, dtype: int64
内部标识号     1248
交易次数         3
交易金额     28568
Name: 1247, dtype: int64
内部标识号    1249
交易次数        4
交易金额      239
Name: 1248, dtype: int64
内部标识号    1250
交易次数        9
交易金额      564
Name: 1249, dtype: int64
内部标识号    1251
交易次数        3
交易金额      451
Name: 1250, dtype: int64
内部标识号    1252
交易次数        1
交易金额     3443
Name: 1251, dtype: int64
内部标识号    1253
交易次数        1
交易金额      648
Name: 1252, dtype: int64
内部标识号    1254
交易次数       24
交易金额       61
Name: 1253, dtype: int64
内部标识号    1255
交易次数        3
交易金额      374
Name: 1254, dtype: int64
内部标识号    1256
交易次数       15
交易金额      627
Name: 1255, dtype: int64
内部标识号    1257
交易次数       13
交易金额      750
Name: 1256, dtype: int64
内部标识号    1258
交易次数        3
交易金额      406
Name: 1257, dtype: int64
内部标识号    1259
交易次数        9
交易金额      373
Name: 1258, dtype: int64
内部标识号    1260
交易次数       27
交易金额      572
Name: 1259, dtype: int64
内部标识号    1261
交易次数        2
交易金额      468
Name: 1260, dtype: int64
内部标识号     1262
交易次数       114
交易金额     53106
Name: 1261, dtype: int64
内部标识号    1263
交易次数        2
交易金额      306
Name: 1262, dtype: int64
内部标识号    1264
交易次数        9
交易金额      517
Name: 1263, dtype: int64
内部标识号    1265
交易次数       15
交易金额      931
Name: 1264, dtype: int64
内部标识号    1266
交易次数        8
交易金额      270
Name: 1265, dtype: int64
内部标识号     1267
交易次数       153
交易金额     83657
Name: 1266, dtype: int64
内部标识号    1268
交易次数        9
交易金额      644
Name: 1267, dtype: int64
内部标识号    1269
交易次数        5
交易金额      127
Name: 1268, dtype: int64
内部标识号    1270
交易次数       12
交易金额      321
Name: 1269, dtype: int64
内部标识号    1271
交易次数        1
交易金额      733
Name: 1270, dtype: int64
内部标识号     1272
交易次数         3
交易金额     75916
Name: 1271, dtype: int64
内部标识号    1273
交易次数        3
交易金额      454
Name: 1272, dtype: int64
内部标识号    1274
交易次数        0
交易金额     2150
Name: 1273, dtype: int64
内部标识号    1275
交易次数       15
交易金额      574
Name: 1274, dtype: int64
内部标识号    1276
交易次数        4
交易金额      275

Name: 1275, dtype: int64
内部标识号    1277
交易次数       14
交易金额      810
Name: 1276, dtype: int64
内部标识号    1278
交易次数       15
交易金额      905
Name: 1277, dtype: int64
内部标识号    1279
交易次数        3
交易金额      375
Name: 1278, dtype: int64
内部标识号    1280
交易次数       13
交易金额      679
Name: 1279, dtype: int64
内部标识号    1281
交易次数        3
交易金额      434
Name: 1280, dtype: int64
内部标识号    1282
交易次数        1
交易金额      504
Name: 1281, dtype: int64
内部标识号     1283
交易次数         7
交易金额     86252
Name: 1282, dtype: int64
内部标识号    1284
交易次数        3
交易金额      377
Name: 1283, dtype: int64
内部标识号    1285
交易次数        2
交易金额      376
Name: 1284, dtype: int64
内部标识号    1286
交易次数       11
交易金额      698
Name: 1285, dtype: int64
内部标识号     1287
交易次数         5
交易金额     96496
Name: 1286, dtype: int64
内部标识号    1288
交易次数        3
交易金额      407
Name: 1287, dtype: int64
内部标识号    1289
交易次数       21
交易金额       19
Name: 1288, dtype: int64
内部标识号    1290
交易次数        3
交易金额      494
Name: 1289, dtype: int64
内部标识号    1291
交易次数        3
交易金额      337
Name: 1290, dtype: int64
内部标识号    1292
交易次数        2
交易金额      373
Name: 1291, dtype: int64
内部标识号    1293
交易次数        5
交易金额      131
Name: 1292, dtype: int64
内部标识号    1294
交易次数        2
交易金额      434
Name: 1293, dtype: int64
内部标识号    1295
交易次数        9
交易金额      340
Name: 1294, dtype: int64
内部标识号    1296
交易次数        2
交易金额      154
Name: 1295, dtype: int64
内部标识号    1297
交易次数       22
交易金额     9963
Name: 1296, dtype: int64
内部标识号    1298
交易次数       30
交易金额     3604
Name: 1297, dtype: int64
内部标识号    1299
交易次数       17
交易金额     8479
Name: 1298, dtype: int64
内部标识号    1300
交易次数        3
交易金额      420
Name: 1299, dtype: int64
内部标识号    1301
交易次数        6
交易金额      137
Name: 1300, dtype: int64
内部标识号    1302
交易次数        9
交易金额      838
Name: 1301, dtype: int64
内部标识号    1303
交易次数        1
交易金额     8431
Name: 1302, dtype: int64
内部标识号    1304
交易次数        9
交易金额      549
Name: 1303, dtype: int64
内部标识号    1305
交易次数        1
交易金额      576
Name: 1304, dtype: int64
内部标识号    1306
交易次数        7
交易金额      260
Name: 1305, dtype: int64
内部标识号     1307
交易次数       204
交易金额     83436
Name: 1306, dtype: int64
内部标识号    1308
交易次数        1
交易金额     6092
Name: 1307, dtype: int64
内部标识号    1309
交易次数       10
交易金额      912
Name: 1308, dtype: int64
内部标识号    1310
交易次数       11
交易金额      363
Name: 1309, dtype: int64
内部标识号    1311
交易次数        9
交易金额      669
Name: 1310, dtype: int64
内部标识号     1312
交易次数         5
交易金额     15337
Name: 1311, dtype: int64
内部标识号    1313
交易次数       25
交易金额     4828
Name: 1312, dtype: int64
内部标识号     1314
交易次数       224
交易金额     85249
Name: 1313, dtype: int64
内部标识号    1315
交易次数        3
交易金额      445
Name: 1314, dtype: int64
内部标识号    1316
交易次数       15
交易金额     9058
Name: 1315, dtype: int64
内部标识号    1317
交易次数        9
交易金额      930
Name: 1316, dtype: int64
内部标识号    1318
交易次数        8
交易金额      781
Name: 1317, dtype: int64
内部标识号    1319
交易次数        4
交易金额      148
Name: 1318, dtype: int64
内部标识号    1320
交易次数        9
交易金额      623
Name: 1319, dtype: int64
内部标识号     1321
交易次数       163
交易金额     51338
Name: 1320, dtype: int64
内部标识号    1322
交易次数        6
交易金额      172
Name: 1321, dtype: int64
内部标识号    1323
交易次数        9
交易金额      912
Name: 1322, dtype: int64
内部标识号    1324
交易次数       12
交易金额      600
Name: 1323, dtype: int64
内部标识号    1325
交易次数        0
交易金额     2363
Name: 1324, dtype: int64
内部标识号    1326
交易次数       16
交易金额     2039
Name: 1325, dtype: int64
内部标识号    1327
交易次数        6
交易金额      124
Name: 1326, dtype: int64
内部标识号    1328
交易次数       22
交易金额     7904
Name: 1327, dtype: int64
内部标识号    1329
交易次数       26
交易金额     8417
Name: 1328, dtype: int64
内部标识号    1330
交易次数        1
交易金额      763
Name: 1329, dtype: int64
内部标识号     1331
交易次数         4
交易金额     95957
Name: 1330, dtype: int64
内部标识号    1332
交易次数        2
交易金额      373
Name: 1331, dtype: int64
内部标识号    1333
交易次数       27
交易金额      667
Name: 1332, dtype: int64
内部标识号    1334
交易次数       26
交易金额     9564
Name: 1333, dtype: int64
内部标识号     1335
交易次数         8
交易金额     17403
Name: 1334, dtype: int64
内部标识号    1336
交易次数       13
交易金额      406
Name: 1335, dtype: int64
内部标识号    1337
交易次数       28
交易金额     3007
Name: 1336, dtype: int64
内部标识号    1338
交易次数        0
交易金额     9058
Name: 1337, dtype: int64
内部标识号    1339
交易次数       10
交易金额      969
Name: 1338, dtype: int64
内部标识号     1340
交易次数         6
交易金额     28717
Name: 1339, dtype: int64
内部标识号    1341
交易次数        3
交易金额      349
Name: 1340, dtype: int64
内部标识号    1342
交易次数       10
交易金额      689
Name: 1341, dtype: int64
内部标识号    1343
交易次数       15
交易金额      779
Name: 1342, dtype: int64
内部标识号    1344
交易次数       15
交易金额        4
Name: 1343, dtype: int64
内部标识号    1345
交易次数        3
交易金额      295
Name: 1344, dtype: int64
内部标识号    1346
交易次数       13
交易金额      996
Name: 1345, dtype: int64
内部标识号    1347
交易次数       13
交易金额      863
Name: 1346, dtype: int64
内部标识号    1348
交易次数        3
交易金额      164
Name: 1347, dtype: int64
内部标识号    1349
交易次数        1
交易金额      925
Name: 1348, dtype: int64
内部标识号    1350
交易次数       26
交易金额     9689
Name: 1349, dtype: int64
内部标识号    1351
交易次数       24
交易金额      885
Name: 1350, dtype: int64
内部标识号    1352
交易次数       13
交易金额      483
Name: 1351, dtype: int64
内部标识号    1353
交易次数       17
交易金额     2609
Name: 1352, dtype: int64
内部标识号    1354
交易次数        8
交易金额      106
Name: 1353, dtype: int64
内部标识号    1355
交易次数       11
交易金额      941
Name: 1354, dtype: int64
内部标识号    1356
交易次数        2
交易金额      292
Name: 1355, dtype: int64
内部标识号    1357
交易次数       14
交易金额      404
Name: 1356, dtype: int64
内部标识号    1358
交易次数       10
交易金额      963
Name: 1357, dtype: int64
内部标识号    1359
交易次数        6
交易金额      253
Name: 1358, dtype: int64
内部标识号    1360
交易次数       12
交易金额      794
Name: 1359, dtype: int64
内部标识号    1361
交易次数        8
交易金额      287
Name: 1360, dtype: int64
内部标识号    1362
交易次数        3
交易金额      328
Name: 1361, dtype: int64
内部标识号    1363
交易次数        8
交易金额      544
Name: 1362, dtype: int64
内部标识号    1364
交易次数        1
交易金额     9286
Name: 1363, dtype: int64
内部标识号    1365
交易次数       30
交易金额     1067
Name: 1364, dtype: int64
内部标识号    1366
交易次数       10
交易金额      427
Name: 1365, dtype: int64
内部标识号    1367
交易次数       15
交易金额      592
Name: 1366, dtype: int64
内部标识号    1368
交易次数        5
交易金额      171
Name: 1367, dtype: int64
内部标识号    1369
交易次数       10
交易金额      437
Name: 1368, dtype: int64
内部标识号    1370
交易次数        3
交易金额      434
Name: 1369, dtype: int64
内部标识号    1371
交易次数        6
交易金额      272
Name: 1370, dtype: int64
内部标识号    1372
交易次数        3
交易金额      452
Name: 1371, dtype: int64
内部标识号    1373
交易次数        1
交易金额      525
Name: 1372, dtype: int64
内部标识号    1374
交易次数       24
交易金额     5140
Name: 1373, dtype: int64
内部标识号    1375
交易次数       17
交易金额      749
Name: 1374, dtype: int64
内部标识号    1376
交易次数       12
交易金额      323
Name: 1375, dtype: int64
内部标识号    1377
交易次数        4
交易金额      223
Name: 1376, dtype: int64
内部标识号    1378
交易次数        4
交易金额      173
Name: 1377, dtype: int64
内部标识号    1379
交易次数        1
交易金额      745
Name: 1378, dtype: int64
内部标识号    1380
交易次数        3
交易金额      437
Name: 1379, dtype: int64
内部标识号    1381
交易次数       17
交易金额     4775
Name: 1380, dtype: int64
内部标识号    1382
交易次数        0
交易金额     2817
Name: 1381, dtype: int64
内部标识号    1383
交易次数        2
交易金额      407
Name: 1382, dtype: int64
内部标识号    1384
交易次数       10
交易金额      978
Name: 1383, dtype: int64
内部标识号    1385
交易次数        9
交易金额      860
Name: 1384, dtype: int64
内部标识号    1386
交易次数       20
交易金额     8916
Name: 1385, dtype: int64
内部标识号    1387
交易次数        4
交易金额      250
Name: 1386, dtype: int64
内部标识号    1388
交易次数       15
交易金额      311
Name: 1387, dtype: int64
内部标识号     1389
交易次数         4
交易金额     71241
Name: 1388, dtype: int64
内部标识号    1390
交易次数        0
交易金额     2232
Name: 1389, dtype: int64
内部标识号     1391
交易次数       122
交易金额     22621
Name: 1390, dtype: int64
内部标识号    1392
交易次数       13
交易金额      678
Name: 1391, dtype: int64
内部标识号    1393
交易次数        3
交易金额      426
Name: 1392, dtype: int64
内部标识号    1394
交易次数       15
交易金额      918
Name: 1393, dtype: int64
内部标识号    1395
交易次数       14
交易金额      418
Name: 1394, dtype: int64
内部标识号    1396
交易次数       17
交易金额     3168
Name: 1395, dtype: int64
内部标识号    1397
交易次数        5
交易金额      157
Name: 1396, dtype: int64
内部标识号    1398
交易次数        3
交易金额      347
Name: 1397, dtype: int64
内部标识号    1399
交易次数        8
交易金额      830
Name: 1398, dtype: int64
内部标识号    1400
交易次数        7
交易金额      254
Name: 1399, dtype: int64
内部标识号    1401
交易次数        2
交易金额      335
Name: 1400, dtype: int64
内部标识号    1402
交易次数        9
交易金额      998
Name: 1401, dtype: int64
内部标识号    1403
交易次数        3
交易金额      358
Name: 1402, dtype: int64
内部标识号    1404
交易次数        7
交易金额      190
Name: 1403, dtype: int64
内部标识号    1405
交易次数        3
交易金额      341
Name: 1404, dtype: int64
内部标识号    1406
交易次数       14
交易金额      336
Name: 1405, dtype: int64
内部标识号    1407
交易次数        1
交易金额      771
Name: 1406, dtype: int64
内部标识号    1408
交易次数        5
交易金额      283
Name: 1407, dtype: int64
内部标识号    1409
交易次数        1
交易金额      530
Name: 1408, dtype: int64
内部标识号    1410
交易次数        2
交易金额      680
Name: 1409, dtype: int64
内部标识号    1411
交易次数        8
交易金额      572
Name: 1410, dtype: int64
内部标识号    1412
交易次数        8
交易金额      971
Name: 1411, dtype: int64
内部标识号    1413
交易次数       12
交易金额      538
Name: 1412, dtype: int64
内部标识号    1414
交易次数        8
交易金额      264
Name: 1413, dtype: int64
内部标识号    1415
交易次数       15
交易金额     7153
Name: 1414, dtype: int64
内部标识号    1416
交易次数       12
交易金额      393
Name: 1415, dtype: int64
内部标识号    1417
交易次数        3
交易金额      381
Name: 1416, dtype: int64
内部标识号    1418
交易次数        8
交易金额      142
Name: 1417, dtype: int64
内部标识号    1419
交易次数        8
交易金额      335
Name: 1418, dtype: int64
内部标识号    1420
交易次数       10
交易金额      301
Name: 1419, dtype: int64
内部标识号    1421
交易次数        1
交易金额     8513
Name: 1420, dtype: int64
内部标识号    1422
交易次数       29
交易金额      686
Name: 1421, dtype: int64
内部标识号    1423
交易次数        0
交易金额     6496
Name: 1422, dtype: int64
内部标识号    1424
交易次数       10
交易金额      711
Name: 1423, dtype: int64
内部标识号    1425
交易次数        9
交易金额      569
Name: 1424, dtype: int64
内部标识号    1426
交易次数       15
交易金额      898
Name: 1425, dtype: int64
内部标识号    1427
交易次数        2
交易金额      406
Name: 1426, dtype: int64
内部标识号    1428
交易次数        3
交易金额      272
Name: 1427, dtype: int64
内部标识号    1429
交易次数        2
交易金额      713
Name: 1428, dtype: int64
内部标识号    1430
交易次数        1
交易金额      840
Name: 1429, dtype: int64
内部标识号     1431
交易次数       202
交易金额     40109
Name: 1430, dtype: int64
内部标识号    1432
交易次数        9
交易金额      438
Name: 1431, dtype: int64
内部标识号    1433
交易次数        3
交易金额      354
Name: 1432, dtype: int64
内部标识号    1434
交易次数       18
交易金额     7273
Name: 1433, dtype: int64
内部标识号    1435
交易次数        1
交易金额      775
Name: 1434, dtype: int64
内部标识号    1436
交易次数        0
交易金额     7517
Name: 1435, dtype: int64
内部标识号    1437
交易次数        2
交易金额      517
Name: 1436, dtype: int64
内部标识号    1438
交易次数       11
交易金额      771
Name: 1437, dtype: int64
内部标识号    1439
交易次数       30
交易金额      686
Name: 1438, dtype: int64
内部标识号    1440
交易次数       23
交易金额      860
Name: 1439, dtype: int64
内部标识号    1441
交易次数       10
交易金额      580
Name: 1440, dtype: int64
内部标识号    1442
交易次数       15
交易金额      374
Name: 1441, dtype: int64
内部标识号    1443
交易次数        4
交易金额      217
Name: 1442, dtype: int64
内部标识号    1444
交易次数        5
交易金额      182
Name: 1443, dtype: int64
内部标识号    1445
交易次数       20
交易金额     9549
Name: 1444, dtype: int64
内部标识号    1446
交易次数       14
交易金额      379
Name: 1445, dtype: int64
内部标识号    1447
交易次数        1
交易金额      620
Name: 1446, dtype: int64
内部标识号    1448
交易次数        3
交易金额      134
Name: 1447, dtype: int64
内部标识号    1449
交易次数        0
交易金额     4182
Name: 1448, dtype: int64
内部标识号    1450
交易次数        6
交易金额      128
Name: 1449, dtype: int64
内部标识号    1451
交易次数        4
交易金额      292
Name: 1450, dtype: int64
内部标识号    1452
交易次数        3
交易金额      324
Name: 1451, dtype: int64
内部标识号    1453
交易次数        3
交易金额      141
Name: 1452, dtype: int64
内部标识号    1454
交易次数        4
交易金额      208
Name: 1453, dtype: int64
内部标识号    1455
交易次数       13
交易金额      465
Name: 1454, dtype: int64
内部标识号    1456
交易次数        8
交易金额      789
Name: 1455, dtype: int64
内部标识号     1457
交易次数         8
交易金额     28260
Name: 1456, dtype: int64
内部标识号    1458
交易次数       12
交易金额      348
Name: 1457, dtype: int64
内部标识号    1459
交易次数        1
交易金额      845
Name: 1458, dtype: int64
内部标识号    1460
交易次数       15
交易金额     6998
Name: 1459, dtype: int64
内部标识号    1461
交易次数       27
交易金额     2404
Name: 1460, dtype: int64
内部标识号    1462
交易次数        3
交易金额      356
Name: 1461, dtype: int64
内部标识号    1463
交易次数        1
交易金额     2448
Name: 1462, dtype: int64
内部标识号     1464
交易次数         7
交易金额     25512
Name: 1463, dtype: int64
内部标识号    1465
交易次数       15
交易金额      867
Name: 1464, dtype: int64
内部标识号    1466
交易次数        0
交易金额     6349
Name: 1465, dtype: int64
内部标识号    1467
交易次数        2
交易金额      914
Name: 1466, dtype: int64
内部标识号    1468
交易次数       15
交易金额      388
Name: 1467, dtype: int64
内部标识号    1469
交易次数        4
交易金额      177
Name: 1468, dtype: int64
内部标识号    1470
交易次数        0
交易金额     8115
Name: 1469, dtype: int64
内部标识号    1471
交易次数        2
交易金额      340
Name: 1470, dtype: int64
内部标识号    1472
交易次数        2
交易金额      303
Name: 1471, dtype: int64
内部标识号     1473
交易次数         7
交易金额     85558
Name: 1472, dtype: int64
内部标识号     1474
交易次数         7
交易金额     49658
Name: 1473, dtype: int64
内部标识号     1475
交易次数        83
交易金额     51772
Name: 1474, dtype: int64
内部标识号    1476
交易次数        1
交易金额      814
Name: 1475, dtype: int64
内部标识号    1477
交易次数        2
交易金额      717
Name: 1476, dtype: int64
内部标识号    1478
交易次数        3
交易金额      409
Name: 1477, dtype: int64
内部标识号    1479
交易次数        8
交易金额      297
Name: 1478, dtype: int64
内部标识号    1480
交易次数       10
交易金额      680
Name: 1479, dtype: int64
内部标识号    1481
交易次数        1
交易金额     7610
Name: 1480, dtype: int64
内部标识号    1482
交易次数        1
交易金额      704
Name: 1481, dtype: int64
内部标识号    1483
交易次数        8
交易金额      371
Name: 1482, dtype: int64
内部标识号    1484
交易次数        3
交易金额      334
Name: 1483, dtype: int64
内部标识号    1485
交易次数       12
交易金额      655
Name: 1484, dtype: int64
内部标识号    1486
交易次数        4
交易金额      163
Name: 1485, dtype: int64
内部标识号    1487
交易次数       26
交易金额     4762
Name: 1486, dtype: int64
内部标识号    1488
交易次数       25
交易金额     1850
Name: 1487, dtype: int64
内部标识号     1489
交易次数       236
交易金额     85785
Name: 1488, dtype: int64
内部标识号    1490
交易次数       26
交易金额     6472
Name: 1489, dtype: int64
内部标识号    1491
交易次数        1
交易金额     9866
Name: 1490, dtype: int64
内部标识号    1492
交易次数        2
交易金额      316
Name: 1491, dtype: int64
内部标识号    1493
交易次数        3
交易金额      319
Name: 1492, dtype: int64
内部标识号    1494
交易次数        9
交易金额      730
Name: 1493, dtype: int64
内部标识号    1495
交易次数        3
交易金额      355
Name: 1494, dtype: int64
内部标识号    1496
交易次数        3
交易金额      447
Name: 1495, dtype: int64
内部标识号    1497
交易次数        0
交易金额     7461
Name: 1496, dtype: int64
内部标识号    1498
交易次数        3
交易金额      367
Name: 1497, dtype: int64
内部标识号    1499
交易次数       13
交易金额      346
Name: 1498, dtype: int64
内部标识号    1500
交易次数        0
交易金额     2756
Name: 1499, dtype: int64
内部标识号    1501
交易次数        2
交易金额      382
Name: 1500, dtype: int64
内部标识号    1502
交易次数       12
交易金额      810
Name: 1501, dtype: int64
内部标识号     1503
交易次数       119
交易金额     52123
Name: 1502, dtype: int64
内部标识号    1504
交易次数        3
交易金额      166
Name: 1503, dtype: int64
内部标识号    1505
交易次数        8
交易金额      246
Name: 1504, dtype: int64
内部标识号    1506
交易次数       10
交易金额      849
Name: 1505, dtype: int64
内部标识号    1507
交易次数        5
交易金额      128
Name: 1506, dtype: int64
内部标识号    1508
交易次数        3
交易金额      135
Name: 1507, dtype: int64
内部标识号    1509
交易次数       11
交易金额      493
Name: 1508, dtype: int64
内部标识号    1510
交易次数       11
交易金额      578
Name: 1509, dtype: int64
内部标识号    1511
交易次数       15
交易金额      769
Name: 1510, dtype: int64
内部标识号    1512
交易次数        8
交易金额      765
Name: 1511, dtype: int64
内部标识号    1513
交易次数        8
交易金额      118
Name: 1512, dtype: int64
内部标识号    1514
交易次数       15
交易金额     3924
Name: 1513, dtype: int64
内部标识号    1515
交易次数       12
交易金额      356
Name: 1514, dtype: int64
内部标识号     1516
交易次数         8
交易金额     53582
Name: 1515, dtype: int64
内部标识号    1517
交易次数       27
交易金额     9976
Name: 1516, dtype: int64
内部标识号    1518
交易次数        5
交易金额      152
Name: 1517, dtype: int64
内部标识号    1519
交易次数        4
交易金额      278
Name: 1518, dtype: int64
内部标识号    1520
交易次数       22
交易金额      601
Name: 1519, dtype: int64
内部标识号    1521
交易次数        6
交易金额      231
Name: 1520, dtype: int64
内部标识号    1522
交易次数        4
交易金额      205
Name: 1521, dtype: int64
内部标识号    1523
交易次数        2
交易金额      125
Name: 1522, dtype: int64
内部标识号    1524
交易次数        7
交易金额      293
Name: 1523, dtype: int64
内部标识号    1525
交易次数        3
交易金额      261
Name: 1524, dtype: int64
内部标识号    1526
交易次数        4
交易金额      210
Name: 1525, dtype: int64
内部标识号    1527
交易次数        3
交易金额      314
Name: 1526, dtype: int64
内部标识号    1528
交易次数        2
交易金额      433
Name: 1527, dtype: int64
内部标识号    1529
交易次数        7
交易金额      242
Name: 1528, dtype: int64
内部标识号    1530
交易次数        8
交易金额      923
Name: 1529, dtype: int64
内部标识号    1531
交易次数       25
交易金额     4111
Name: 1530, dtype: int64
内部标识号    1532
交易次数        2
交易金额      432
Name: 1531, dtype: int64
内部标识号    1533
交易次数        1
交易金额      697
Name: 1532, dtype: int64
内部标识号    1534
交易次数        3
交易金额      463
Name: 1533, dtype: int64
内部标识号    1535
交易次数        3
交易金额      206
Name: 1534, dtype: int64
内部标识号    1536
交易次数       22
交易金额     1318
Name: 1535, dtype: int64
内部标识号     1537
交易次数       184
交易金额     85618
Name: 1536, dtype: int64
内部标识号    1538
交易次数        0
交易金额     7515
Name: 1537, dtype: int64
内部标识号    1539
交易次数        1
交易金额     7362
Name: 1538, dtype: int64
内部标识号    1540
交易次数       15
交易金额      465
Name: 1539, dtype: int64
内部标识号    1541
交易次数        3
交易金额      365
Name: 1540, dtype: int64
内部标识号    1542
交易次数        1
交易金额      612
Name: 1541, dtype: int64
内部标识号    1543
交易次数        7
交易金额      206
Name: 1542, dtype: int64
内部标识号    1544
交易次数        2
交易金额      314
Name: 1543, dtype: int64
内部标识号    1545
交易次数       10
交易金额      854
Name: 1544, dtype: int64
内部标识号    1546
交易次数        1
交易金额      936
Name: 1545, dtype: int64
内部标识号     1547
交易次数         4
交易金额     83526
Name: 1546, dtype: int64
内部标识号    1548
交易次数        4
交易金额      111
Name: 1547, dtype: int64
内部标识号    1549
交易次数        2
交易金额      466
Name: 1548, dtype: int64
内部标识号    1550
交易次数        2
交易金额      524
Name: 1549, dtype: int64
内部标识号    1551
交易次数        1
交易金额      996
Name: 1550, dtype: int64
内部标识号    1552
交易次数        2
交易金额      318
Name: 1551, dtype: int64
内部标识号    1553
交易次数        8
交易金额      106
Name: 1552, dtype: int64
内部标识号    1554
交易次数       22
交易金额      949
Name: 1553, dtype: int64
内部标识号    1555
交易次数        8
交易金额      510
Name: 1554, dtype: int64
内部标识号     1556
交易次数       103
交易金额     28264
Name: 1555, dtype: int64
内部标识号    1557
交易次数        8
交易金额      387
Name: 1556, dtype: int64
内部标识号    1558
交易次数        3
交易金额      168
Name: 1557, dtype: int64
内部标识号     1559
交易次数         6
交易金额     87723
Name: 1558, dtype: int64
内部标识号    1560
交易次数       11
交易金额      793
Name: 1559, dtype: int64
内部标识号    1561
交易次数       13
交易金额      772
Name: 1560, dtype: int64
内部标识号    1562
交易次数       10
交易金额      736
Name: 1561, dtype: int64
内部标识号    1563
交易次数       25
交易金额     7977
Name: 1562, dtype: int64
内部标识号    1564
交易次数        1
交易金额     2359
Name: 1563, dtype: int64
内部标识号    1565
交易次数        2
交易金额      436
Name: 1564, dtype: int64
内部标识号     1566
交易次数         3
交易金额     44300
Name: 1565, dtype: int64
内部标识号    1567
交易次数        1
交易金额      869
Name: 1566, dtype: int64
内部标识号    1568
交易次数       21
交易金额     2704
Name: 1567, dtype: int64
内部标识号    1569
交易次数        9
交易金额      648
Name: 1568, dtype: int64
内部标识号    1570
交易次数        3
交易金额      371
Name: 1569, dtype: int64
内部标识号    1571
交易次数       15
交易金额      615
Name: 1570, dtype: int64
内部标识号    1572
交易次数        8
交易金额      284
Name: 1571, dtype: int64
内部标识号    1573
交易次数        9
交易金额      503
Name: 1572, dtype: int64

Name: 1623, dtype: int64
内部标识号    1625
交易次数       12
交易金额      872
Name: 1624, dtype: int64
内部标识号    1626
交易次数        0
交易金额     5393
Name: 1625, dtype: int64
内部标识号     1627
交易次数        91
交易金额     92348
Name: 1626, dtype: int64
内部标识号    1628
交易次数        5
交易金额      279
Name: 1627, dtype: int64
内部标识号    1629
交易次数        5
交易金额      100
Name: 1628, dtype: int64
内部标识号    1630
交易次数       12
交易金额      918
Name: 1629, dtype: int64
内部标识号    1631
交易次数       13
交易金额      839
Name: 1630, dtype: int64
内部标识号    1632
交易次数        3
交易金额      126
Name: 1631, dtype: int64
内部标识号    1633
交易次数        2
交易金额      935
Name: 1632, dtype: int64
内部标识号    1634
交易次数        2
交易金额      469
Name: 1633, dtype: int64
内部标识号    1635
交易次数        3
交易金额      483
Name: 1634, dtype: int64
内部标识号    1636
交易次数       10
交易金额      509
Name: 1635, dtype: int64
内部标识号     1637
交易次数        77
交易金额     83999
Name: 1636, dtype: int64
内部标识号    1638
交易次数        9
交易金额      773
Name: 1637, dtype: int64
内部标识号    1639
交易次数       11
交易金额      812
Name: 1638, dtype: int64
内部标识号     1640
交易次数         4
交易金额     46160
Name: 1639, dtype: int64
内部标识号    1641
交易次数        2
交易金额      333
Name: 1640, dtype: int64
内部标识号    1642
交易次数        6
交易金额      233
Name: 1641, dtype: int64
内部标识号    1643
交易次数        0
交易金额     2561
Name: 1642, dtype: int64
内部标识号    1644
交易次数        5
交易金额      181
Name: 1643, dtype: int64
内部标识号    1645
交易次数       12
交易金额      576
Name: 1644, dtype: int64
内部标识号    1646
交易次数        8
交易金额      290
Name: 1645, dtype: int64
内部标识号    1647
交易次数       14
交易金额      831
Name: 1646, dtype: int64
内部标识号    1648
交易次数       25
交易金额     4220
Name: 1647, dtype: int64
内部标识号    1649
交易次数       29
交易金额       84
Name: 1648, dtype: int64
内部标识号    1650
交易次数       15
交易金额      356
Name: 1649, dtype: int64
内部标识号    1651
交易次数        2
交易金额      639
Name: 1650, dtype: int64
内部标识号    1652
交易次数        1
交易金额      827
Name: 1651, dtype: int64
内部标识号    1653
交易次数        4
交易金额      134
Name: 1652, dtype: int64
内部标识号    1654
交易次数        6
交易金额      128
Name: 1653, dtype: int64
内部标识号    1655
交易次数        1
交易金额     5767
Name: 1654, dtype: int64
内部标识号     1656
交易次数       207
交易金额     69797
Name: 1655, dtype: int64
内部标识号    1657
交易次数       25
交易金额      830
Name: 1656, dtype: int64
内部标识号    1658
交易次数        3
交易金额      374
Name: 1657, dtype: int64
内部标识号    1659
交易次数        7
交易金额      162
Name: 1658, dtype: int64
内部标识号    1660
交易次数       22
交易金额      544
Name: 1659, dtype: int64
内部标识号     1661
交易次数       204
交易金额     90736
Name: 1660, dtype: int64
内部标识号    1662
交易次数       19
交易金额     3474
Name: 1661, dtype: int64
内部标识号    1663
交易次数        8
交易金额      172
Name: 1662, dtype: int64
内部标识号    1664
交易次数       14
交易金额      443
Name: 1663, dtype: int64
内部标识号    1665
交易次数        2
交易金额      339
Name: 1664, dtype: int64
内部标识号    1666
交易次数       13
交易金额      520
Name: 1665, dtype: int64
内部标识号    1667
交易次数       22
交易金额       85
Name: 1666, dtype: int64
内部标识号    1668
交易次数        3
交易金额      130
Name: 1667, dtype: int64
内部标识号    1669
交易次数        3
交易金额      150
Name: 1668, dtype: int64
内部标识号    1670
交易次数       21
交易金额     8608
Name: 1669, dtype: int64
内部标识号    1671
交易次数       10
交易金额      496
Name: 1670, dtype: int64
内部标识号    1672
交易次数       22
交易金额     5365
Name: 1671, dtype: int64
内部标识号    1673
交易次数        3
交易金额      284
Name: 1672, dtype: int64
内部标识号     1674
交易次数       211
交易金额     10277
Name: 1673, dtype: int64
内部标识号    1675
交易次数        1
交易金额     7837
Name: 1674, dtype: int64
内部标识号    1676
交易次数        1
交易金额      984
Name: 1675, dtype: int64
内部标识号    1677
交易次数       29
交易金额     3435
Name: 1676, dtype: int64
内部标识号    1678
交易次数        3
交易金额      349
Name: 1677, dtype: int64
内部标识号    1679
交易次数        3
交易金额      364
Name: 1678, dtype: int64
内部标识号    1680
交易次数        6
交易金额      218
Name: 1679, dtype: int64
内部标识号     1681
交易次数        36
交易金额     15437
Name: 1680, dtype: int64
内部标识号    1682
交易次数        3
交易金额      408
Name: 1681, dtype: int64
内部标识号    1683
交易次数        4
交易金额      251
Name: 1682, dtype: int64
内部标识号    1684
交易次数        5
交易金额      117
Name: 1683, dtype: int64
内部标识号    1685
交易次数        9
交易金额      470
Name: 1684, dtype: int64
内部标识号    1686
交易次数        4
交易金额      300
Name: 1685, dtype: int64
内部标识号    1687
交易次数       15
交易金额      335
Name: 1686, dtype: int64
内部标识号    1688
交易次数        2
交易金额      480
Name: 1687, dtype: int64
内部标识号    1689
交易次数        1
交易金额      659
Name: 1688, dtype: int64
内部标识号    1690
交易次数       11
交易金额      652
Name: 1689, dtype: int64
内部标识号    1691
交易次数        3
交易金额      316
Name: 1690, dtype: int64
内部标识号    1692
交易次数        6
交易金额      242
Name: 1691, dtype: int64
内部标识号    1693
交易次数       29
交易金额     9953
Name: 1692, dtype: int64
内部标识号     1694
交易次数        83
交易金额     72767
Name: 1693, dtype: int64
内部标识号    1695
交易次数       12
交易金额      420
Name: 1694, dtype: int64
内部标识号    1696
交易次数       13
交易金额      749
Name: 1695, dtype: int64
内部标识号    1697
交易次数        3
交易金额      354
Name: 1696, dtype: int64
内部标识号    1698
交易次数        2
交易金额      943
Name: 1697, dtype: int64
内部标识号    1699
交易次数        1
交易金额      678
Name: 1698, dtype: int64
内部标识号    1700
交易次数        3
交易金额      214
Name: 1699, dtype: int64
内部标识号    1701
交易次数       10
交易金额      543
Name: 1700, dtype: int64
内部标识号    1702
交易次数        2
交易金额      537
Name: 1701, dtype: int64
内部标识号     1703
交易次数        63
交易金额     84700
Name: 1702, dtype: int64
内部标识号    1704
交易次数        2
交易金额      341
Name: 1703, dtype: int64
内部标识号    1705
交易次数       12
交易金额      609
Name: 1704, dtype: int64
内部标识号    1706
交易次数        8
交易金额      364
Name: 1705, dtype: int64
内部标识号    1707
交易次数        3
交易金额      355
Name: 1706, dtype: int64
内部标识号    1708
交易次数       25
交易金额     2529
Name: 1707, dtype: int64
内部标识号    1709
交易次数        1
交易金额     9121
Name: 1708, dtype: int64
内部标识号    1710
交易次数        2
交易金额      399
Name: 1709, dtype: int64
内部标识号     1711
交易次数       132
交易金额     51307
Name: 1710, dtype: int64
内部标识号     1712
交易次数        35
交易金额     92790
Name: 1711, dtype: int64
内部标识号    1713
交易次数        3
交易金额      270
Name: 1712, dtype: int64
内部标识号     1714
交易次数         7
交易金额     79378
Name: 1713, dtype: int64
内部标识号    1715
交易次数       14
交易金额      454
Name: 1714, dtype: int64
内部标识号    1716
交易次数       15
交易金额      563
Name: 1715, dtype: int64
内部标识号    1717
交易次数       13
交易金额      794
Name: 1716, dtype: int64
内部标识号    1718
交易次数        1
交易金额      669
Name: 1717, dtype: int64
内部标识号    1719
交易次数        7
交易金额      220
Name: 1718, dtype: int64
内部标识号    1720
交易次数        3
交易金额      307
Name: 1719, dtype: int64
内部标识号    1721
交易次数        6
交易金额      117
Name: 1720, dtype: int64
内部标识号    1722
交易次数        1
交易金额     8871
Name: 1721, dtype: int64
内部标识号    1723
交易次数       16
交易金额     9201
Name: 1722, dtype: int64
内部标识号    1724
交易次数        3
交易金额      351
Name: 1723, dtype: int64
内部标识号    1725
交易次数        6
交易金额      259
Name: 1724, dtype: int64
内部标识号    1726
交易次数        2
交易金额      706
Name: 1725, dtype: int64
内部标识号    1727
交易次数        3
交易金额      162
Name: 1726, dtype: int64
内部标识号    1728
交易次数        2
交易金额      892
Name: 1727, dtype: int64
内部标识号    1729
交易次数       13
交易金额      844
Name: 1728, dtype: int64
内部标识号    1730
交易次数       15
交易金额      874
Name: 1729, dtype: int64
内部标识号    1731
交易次数       10
交易金额      779
Name: 1730, dtype: int64
内部标识号    1732
交易次数        8
交易金额      772
Name: 1731, dtype: int64
内部标识号    1733
交易次数       23
交易金额     7706
Name: 1732, dtype: int64
内部标识号    1734
交易次数        1
交易金额      777
Name: 1733, dtype: int64
内部标识号    1735
交易次数        9
交易金额      568
Name: 1734, dtype: int64
内部标识号    1736
交易次数        8
交易金额      650
Name: 1735, dtype: int64
内部标识号    1737
交易次数       15
交易金额      548
Name: 1736, dtype: int64
内部标识号    1738
交易次数        8
交易金额      149
Name: 1737, dtype: int64
内部标识号    1739
交易次数        8
交易金额      238
Name: 1738, dtype: int64
内部标识号    1740
交易次数        9
交易金额      814
Name: 1739, dtype: int64
内部标识号    1741
交易次数        3
交易金额      359
Name: 1740, dtype: int64
内部标识号    1742
交易次数        2
交易金额      462
Name: 1741, dtype: int64
内部标识号    1743
交易次数        7
交易金额      108
Name: 1742, dtype: int64
内部标识号     1744
交易次数         4
交易金额     64205
Name: 1743, dtype: int64
内部标识号    1745
交易次数        1
交易金额      982
Name: 1744, dtype: int64
内部标识号    1746
交易次数        2
交易金额      678
Name: 1745, dtype: int64
内部标识号    1747
交易次数        1
交易金额     8154
Name: 1746, dtype: int64
内部标识号    1748
交易次数        3
交易金额      470
Name: 1747, dtype: int64
内部标识号    1749
交易次数        1
交易金额     8973
Name: 1748, dtype: int64
内部标识号    1750
交易次数        2
交易金额      893
Name: 1749, dtype: int64
内部标识号    1751
交易次数        2
交易金额      430
Name: 1750, dtype: int64
内部标识号    1752
交易次数        1
交易金额      617
Name: 1751, dtype: int64
内部标识号    1753
交易次数        2
交易金额      852
Name: 1752, dtype: int64
内部标识号    1754
交易次数       15
交易金额      482
Name: 1753, dtype: int64
内部标识号     1755
交易次数       107
交易金额     26388
Name: 1754, dtype: int64
内部标识号    1756
交易次数        1
交易金额      659
Name: 1755, dtype: int64
内部标识号    1757
交易次数        8
交易金额      105
Name: 1756, dtype: int64
内部标识号    1758
交易次数        9
交易金额      813
Name: 1757, dtype: int64
内部标识号    1759
交易次数       24
交易金额     2757
Name: 1758, dtype: int64
内部标识号    1760
交易次数        5
交易金额      188
Name: 1759, dtype: int64
内部标识号    1761
交易次数        1
交易金额     3225
Name: 1760, dtype: int64
内部标识号    1762
交易次数       13
交易金额      712
Name: 1761, dtype: int64
内部标识号    1763
交易次数        7
交易金额      212
Name: 1762, dtype: int64
内部标识号    1764
交易次数       15
交易金额      450
Name: 1763, dtype: int64
内部标识号    1765
交易次数        7
交易金额      235
Name: 1764, dtype: int64
内部标识号    1766
交易次数        2
交易金额      146
Name: 1765, dtype: int64
内部标识号    1767
交易次数       13
交易金额      808
Name: 1766, dtype: int64
内部标识号    1768
交易次数       10
交易金额      825
Name: 1767, dtype: int64
内部标识号    1769
交易次数       15
交易金额      317
Name: 1768, dtype: int64
内部标识号    1770
交易次数        1
交易金额     7493
Name: 1769, dtype: int64
内部标识号    1771
交易次数        0
交易金额     2711
Name: 1770, dtype: int64
内部标识号    1772
交易次数       15
交易金额      651
Name: 1771, dtype: int64
内部标识号    1773
交易次数       21
交易金额       49
Name: 1772, dtype: int64
内部标识号    1774
交易次数        2
交易金额      490
Name: 1773, dtype: int64
内部标识号     1775
交易次数         4
交易金额     68199
Name: 1774, dtype: int64
内部标识号    1776
交易次数        6
交易金额      283
Name: 1775, dtype: int64
内部标识号     1777
交易次数        61
交易金额     10554
Name: 1776, dtype: int64
内部标识号    1778
交易次数        8
交易金额      654
Name: 1777, dtype: int64
内部标识号    1779
交易次数        3
交易金额      360
Name: 1778, dtype: int64
内部标识号    1780
交易次数        1
交易金额      534
Name: 1779, dtype: int64
内部标识号    1781
交易次数       23
交易金额     1673
Name: 1780, dtype: int64
内部标识号     1782
交易次数       161
交易金额     55897
Name: 1781, dtype: int64
内部标识号    1783
交易次数        4
交易金额      170
Name: 1782, dtype: int64
内部标识号    1784
交易次数       15
交易金额     9247
Name: 1783, dtype: int64
内部标识号    1785
交易次数        3
交易金额      337
Name: 1784, dtype: int64
内部标识号    1786
交易次数       14
交易金额      806
Name: 1785, dtype: int64
内部标识号    1787
交易次数       14
交易金额      504
Name: 1786, dtype: int64
内部标识号    1788
交易次数       30
交易金额     5981
Name: 1787, dtype: int64
内部标识号    1789
交易次数        8
交易金额      247
Name: 1788, dtype: int64
内部标识号    1790
交易次数       12
交易金额      489
Name: 1789, dtype: int64
内部标识号    1791
交易次数        7
交易金额      115
Name: 1790, dtype: int64
内部标识号    1792
交易次数        8
交易金额      159
Name: 1791, dtype: int64
内部标识号    1793
交易次数        2
交易金额      958
Name: 1792, dtype: int64
内部标识号    1794
交易次数        6
交易金额      176
Name: 1793, dtype: int64
内部标识号    1795
交易次数        8
交易金额      312
Name: 1794, dtype: int64
内部标识号    1796
交易次数       11
交易金额      958
Name: 1795, dtype: int64
内部标识号    1797
交易次数        8
交易金额      267
Name: 1796, dtype: int64
内部标识号    1798
交易次数        3
交易金额      496
Name: 1797, dtype: int64
内部标识号    1799
交易次数       14
交易金额      650
Name: 1798, dtype: int64
内部标识号    1800
交易次数       13
交易金额      672
Name: 1799, dtype: int64
内部标识号    1801
交易次数        1
交易金额      713
Name: 1800, dtype: int64
内部标识号     1802
交易次数         8
交易金额     34744
Name: 1801, dtype: int64
内部标识号    1803
交易次数       11
交易金额      903
Name: 1802, dtype: int64
内部标识号    1804
交易次数        8
交易金额      333
Name: 1803, dtype: int64
内部标识号    1805
交易次数        8
交易金额      693
Name: 1804, dtype: int64
内部标识号    1806
交易次数        9
交易金额      462
Name: 1805, dtype: int64
内部标识号    1807
交易次数       12
交易金额      558
Name: 1806, dtype: int64
内部标识号    1808
交易次数        4
交易金额      285
Name: 1807, dtype: int64
内部标识号    1809
交易次数       12
交易金额      385
Name: 1808, dtype: int64
内部标识号    1810
交易次数       22
交易金额      738
Name: 1809, dtype: int64
内部标识号    1811
交易次数        0
交易金额     8175
Name: 1810, dtype: int64
内部标识号    1812
交易次数        3
交易金额      406
Name: 1811, dtype: int64
内部标识号    1813
交易次数        6
交易金额      293
Name: 1812, dtype: int64
内部标识号    1814
交易次数       11
交易金额      814
Name: 1813, dtype: int64
内部标识号    1815
交易次数       19
交易金额     8237
Name: 1814, dtype: int64
内部标识号    1816
交易次数        8
交易金额      160
Name: 1815, dtype: int64
内部标识号    1817
交易次数       29
交易金额     5828
Name: 1816, dtype: int64
内部标识号    1818
交易次数        7
交易金额      275
Name: 1817, dtype: int64
内部标识号     1819
交易次数       210
交易金额     10702
Name: 1818, dtype: int64
内部标识号    1820
交易次数        2
交易金额      745
Name: 1819, dtype: int64
内部标识号    1821
交易次数       15
交易金额      911
Name: 1820, dtype: int64
内部标识号    1822
交易次数       10
交易金额      477
Name: 1821, dtype: int64
内部标识号    1823
交易次数        4
交易金额      132
Name: 1822, dtype: int64
内部标识号    1824
交易次数       28
交易金额     4524
Name: 1823, dtype: int64
内部标识号    1825
交易次数        3
交易金额      467
Name: 1824, dtype: int64
内部标识号     1826
交易次数         6
交易金额     20610
Name: 1825, dtype: int64
内部标识号    1827
交易次数        3
交易金额      490
Name: 1826, dtype: int64
内部标识号    1828
交易次数        3
交易金额      406
Name: 1827, dtype: int64
内部标识号    1829
交易次数       14
交易金额      728
Name: 1828, dtype: int64
内部标识号    1830
交易次数       25
交易金额     3451
Name: 1829, dtype: int64
内部标识号    1831
交易次数       12
交易金额      581
Name: 1830, dtype: int64
内部标识号    1832
交易次数        0
交易金额     5954
Name: 1831, dtype: int64
内部标识号    1833
交易次数        1
交易金额     3888
Name: 1832, dtype: int64
内部标识号    1834
交易次数       18
交易金额       52
Name: 1833, dtype: int64
内部标识号    1835
交易次数        1
交易金额     1414
Name: 1834, dtype: int64
内部标识号    1836
交易次数       13
交易金额      464
Name: 1835, dtype: int64
内部标识号    1837
交易次数        3
交易金额      451
Name: 1836, dtype: int64
内部标识号    1838
交易次数        8
交易金额      152
Name: 1837, dtype: int64
内部标识号    1839
交易次数        1
交易金额      545
Name: 1838, dtype: int64
内部标识号    1840
交易次数       11
交易金额      399
Name: 1839, dtype: int64
内部标识号    1841
交易次数        8
交易金额      847

Name: 1840, dtype: int64
内部标识号    1842
交易次数        2
交易金额      392
Name: 1841, dtype: int64
内部标识号     1843
交易次数       149
交易金额     16552
Name: 1842, dtype: int64
内部标识号    1844
交易次数        2
交易金额      419
Name: 1843, dtype: int64
内部标识号    1845
交易次数        2
交易金额      711
Name: 1844, dtype: int64
内部标识号    1846
交易次数        8
交易金额      339
Name: 1845, dtype: int64
内部标识号     1847
交易次数       235
交易金额     21849
Name: 1846, dtype: int64
内部标识号    1848
交易次数       10
交易金额      919
Name: 1847, dtype: int64
内部标识号    1849
交易次数       10
交易金额      678
Name: 1848, dtype: int64
内部标识号    1850
交易次数       14
交易金额      705
Name: 1849, dtype: int64
内部标识号    1851
交易次数        0
交易金额     4080
Name: 1850, dtype: int64
内部标识号    1852
交易次数        3
交易金额      215
Name: 1851, dtype: int64
内部标识号    1853
交易次数        8
交易金额      108
Name: 1852, dtype: int64
内部标识号    1854
交易次数        2
交易金额      331
Name: 1853, dtype: int64
内部标识号    1855
交易次数        0
交易金额     7072
Name: 1854, dtype: int64
内部标识号    1856
交易次数       12
交易金额      303
Name: 1855, dtype: int64
内部标识号    1857
交易次数        3
交易金额      144
Name: 1856, dtype: int64
内部标识号    1858
交易次数        8
交易金额      736
Name: 1857, dtype: int64
内部标识号    1859
交易次数        1
交易金额      629
Name: 1858, dtype: int64
内部标识号    1860
交易次数       29
交易金额     3657
Name: 1859, dtype: int64
内部标识号    1861
交易次数        3
交易金额      349
Name: 1860, dtype: int64
内部标识号    1862
交易次数       14
交易金额      846
Name: 1861, dtype: int64
内部标识号    1863
交易次数       14
交易金额      356
Name: 1862, dtype: int64
内部标识号    1864
交易次数        0
交易金额     7472
Name: 1863, dtype: int64
内部标识号    1865
交易次数        6
交易金额      154
Name: 1864, dtype: int64
内部标识号    1866
交易次数        0
交易金额     3932
Name: 1865, dtype: int64
内部标识号    1867
交易次数       20
交易金额     5896
Name: 1866, dtype: int64
内部标识号    1868
交易次数       24
交易金额     7643
Name: 1867, dtype: int64
内部标识号    1869
交易次数        9
交易金额      327
Name: 1868, dtype: int64
内部标识号    1870
交易次数       12
交易金额      677
Name: 1869, dtype: int64
内部标识号    1871
交易次数        5
交易金额      298
Name: 1870, dtype: int64
内部标识号    1872
交易次数        1
交易金额      602
Name: 1871, dtype: int64
内部标识号    1873
交易次数       18
交易金额     2055
Name: 1872, dtype: int64
内部标识号    1874
交易次数       14
交易金额      519
Name: 1873, dtype: int64
内部标识号    1875
交易次数       15
交易金额      467
Name: 1874, dtype: int64
内部标识号    1876
交易次数        3
交易金额      328
Name: 1875, dtype: int64
内部标识号    1877
交易次数        2
交易金额      444
Name: 1876, dtype: int64
内部标识号    1878
交易次数        2
交易金额      987
Name: 1877, dtype: int64
内部标识号    1879
交易次数        1
交易金额      629
Name: 1878, dtype: int64
内部标识号    1880
交易次数        1
交易金额      985
Name: 1879, dtype: int64
内部标识号    1881
交易次数        2
交易金额      350
Name: 1880, dtype: int64
内部标识号    1882
交易次数       11
交易金额      780
Name: 1881, dtype: int64
内部标识号    1883
交易次数        1
交易金额     7947
Name: 1882, dtype: int64
内部标识号    1884
交易次数        3
交易金额      419
Name: 1883, dtype: int64
内部标识号    1885
交易次数        1
交易金额      581
Name: 1884, dtype: int64
内部标识号    1886
交易次数        0
交易金额     2474
Name: 1885, dtype: int64
内部标识号    1887
交易次数       24
交易金额     6277
Name: 1886, dtype: int64
内部标识号    1888
交易次数       13
交易金额      558
Name: 1887, dtype: int64
内部标识号    1889
交易次数        0
交易金额     7821
Name: 1888, dtype: int64
内部标识号    1890
交易次数        2
交易金额      280
Name: 1889, dtype: int64
内部标识号    1891
交易次数        0
交易金额     5496
Name: 1890, dtype: int64
内部标识号    1892
交易次数       15
交易金额      662
Name: 1891, dtype: int64
内部标识号    1893
交易次数        2
交易金额      394
Name: 1892, dtype: int64
内部标识号    1894
交易次数        1
交易金额     8041
Name: 1893, dtype: int64
内部标识号    1895
交易次数        7
交易金额      121
Name: 1894, dtype: int64
内部标识号    1896
交易次数        6
交易金额      212
Name: 1895, dtype: int64
内部标识号    1897
交易次数        3
交易金额      444
Name: 1896, dtype: int64
内部标识号    1898
交易次数        7
交易金额      267
Name: 1897, dtype: int64
内部标识号    1899
交易次数       14
交易金额      647
Name: 1898, dtype: int64
内部标识号     1900
交易次数         3
交易金额     37936
Name: 1899, dtype: int64
内部标识号    1901
交易次数       22
交易金额     3566
Name: 1900, dtype: int64
内部标识号    1902
交易次数        8
交易金额      620
Name: 1901, dtype: int64
内部标识号    1903
交易次数       27
交易金额       89
Name: 1902, dtype: int64
内部标识号    1904
交易次数        6
交易金额      287
Name: 1903, dtype: int64
内部标识号    1905
交易次数        1
交易金额     8537
Name: 1904, dtype: int64
内部标识号    1906
交易次数        2
交易金额      424
Name: 1905, dtype: int64
内部标识号    1907
交易次数        2
交易金额      462
Name: 1906, dtype: int64
内部标识号    1908
交易次数        8
交易金额      562
Name: 1907, dtype: int64
内部标识号    1909
交易次数        1
交易金额      687
Name: 1908, dtype: int64
内部标识号     1910
交易次数       114
交易金额     32878
Name: 1909, dtype: int64
内部标识号    1911
交易次数       11
交易金额      886
Name: 1910, dtype: int64
内部标识号    1912
交易次数       12
交易金额      610
Name: 1911, dtype: int64
内部标识号    1913
交易次数        1
交易金额      535
Name: 1912, dtype: int64
内部标识号    1914
交易次数        0
交易金额     2927
Name: 1913, dtype: int64
内部标识号    1915
交易次数        8
交易金额      372
Name: 1914, dtype: int64
内部标识号    1916
交易次数        3
交易金额      457
Name: 1915, dtype: int64
内部标识号    1917
交易次数       12
交易金额      667
Name: 1916, dtype: int64
内部标识号    1918
交易次数        8
交易金额      171
Name: 1917, dtype: int64
内部标识号    1919
交易次数        2
交易金额      810
Name: 1918, dtype: int64
内部标识号    1920
交易次数        1
交易金额      613
Name: 1919, dtype: int64
内部标识号    1921
交易次数        5
交易金额      100
Name: 1920, dtype: int64
内部标识号    1922
交易次数       10
交易金额      542
Name: 1921, dtype: int64
内部标识号    1923
交易次数       15
交易金额      740
Name: 1922, dtype: int64
内部标识号    1924
交易次数        3
交易金额      165
Name: 1923, dtype: int64
内部标识号    1925
交易次数       15
交易金额      486
Name: 1924, dtype: int64
内部标识号    1926
交易次数        6
交易金额      235
Name: 1925, dtype: int64
内部标识号    1927
交易次数        3
交易金额      419
Name: 1926, dtype: int64
内部标识号    1928
交易次数        7
交易金额      294
Name: 1927, dtype: int64
内部标识号    1929
交易次数       11
交易金额      602
Name: 1928, dtype: int64
内部标识号    1930
交易次数        2
交易金额      425
Name: 1929, dtype: int64
内部标识号    1931
交易次数       23
交易金额     1936
Name: 1930, dtype: int64
内部标识号    1932
交易次数        3
交易金额      469
Name: 1931, dtype: int64
内部标识号    1933
交易次数        5
交易金额      125
Name: 1932, dtype: int64
内部标识号    1934
交易次数       13
交易金额      480
Name: 1933, dtype: int64
内部标识号     1935
交易次数       237
交易金额     50338
Name: 1934, dtype: int64
内部标识号    1936
交易次数       15
交易金额      614
Name: 1935, dtype: int64
内部标识号    1937
交易次数       26
交易金额     8843
Name: 1936, dtype: int64
内部标识号    1938
交易次数        8
交易金额      758
Name: 1937, dtype: int64
内部标识号    1939
交易次数        9
交易金额      380
Name: 1938, dtype: int64
内部标识号    1940
交易次数        8
交易金额      344
Name: 1939, dtype: int64
内部标识号    1941
交易次数        1
交易金额      717
Name: 1940, dtype: int64
内部标识号    1942
交易次数        8
交易金额      207
Name: 1941, dtype: int64
内部标识号    1943
交易次数       11
交易金额      436
Name: 1942, dtype: int64
内部标识号    1944
交易次数       12
交易金额      304
Name: 1943, dtype: int64
内部标识号    1945
交易次数       30
交易金额     9846
Name: 1944, dtype: int64
内部标识号    1946
交易次数       11
交易金额      976
Name: 1945, dtype: int64
内部标识号    1947
交易次数        9
交易金额      460
Name: 1946, dtype: int64
内部标识号    1948
交易次数        2
交易金额      495
Name: 1947, dtype: int64
内部标识号    1949
交易次数       16
交易金额     8685
Name: 1948, dtype: int64
内部标识号    1950
交易次数       18
交易金额      756
Name: 1949, dtype: int64
内部标识号    1951
交易次数        2
交易金额      749
Name: 1950, dtype: int64
内部标识号    1952
交易次数       18
交易金额       43
Name: 1951, dtype: int64
内部标识号    1953
交易次数        1
交易金额      877
Name: 1952, dtype: int64
内部标识号    1954
交易次数        3
交易金额      249
Name: 1953, dtype: int64
内部标识号    1955
交易次数       12
交易金额      700
Name: 1954, dtype: int64
内部标识号    1956
交易次数        1
交易金额      610
Name: 1955, dtype: int64
内部标识号    1957
交易次数        9
交易金额      464
Name: 1956, dtype: int64
内部标识号    1958
交易次数        9
交易金额      944
Name: 1957, dtype: int64
内部标识号    1959
交易次数        9
交易金额      447
Name: 1958, dtype: int64
内部标识号    1960
交易次数        2
交易金额      918
Name: 1959, dtype: int64
内部标识号    1961
交易次数        1
交易金额     5010
Name: 1960, dtype: int64
内部标识号    1962
交易次数       15
交易金额      444
Name: 1961, dtype: int64
内部标识号    1963
交易次数        0
交易金额     6551
Name: 1962, dtype: int64
内部标识号    1964
交易次数       11
交易金额      385
Name: 1963, dtype: int64
内部标识号    1965
交易次数       15
交易金额      514
Name: 1964, dtype: int64
内部标识号    1966
交易次数        9
交易金额      540
Name: 1965, dtype: int64
内部标识号     1967
交易次数       166
交易金额     86569
Name: 1966, dtype: int64
内部标识号    1968
交易次数        3
交易金额      387
Name: 1967, dtype: int64
内部标识号     1969
交易次数       112
交易金额     32448
Name: 1968, dtype: int64
内部标识号    1970
交易次数       14
交易金额      778
Name: 1969, dtype: int64
内部标识号    1971
交易次数        3
交易金额      494
Name: 1970, dtype: int64
内部标识号    1972
交易次数        3
交易金额      457
Name: 1971, dtype: int64
内部标识号     1973
交易次数         7
交易金额     73559
Name: 1972, dtype: int64
内部标识号    1974
交易次数        3
交易金额      373
Name: 1973, dtype: int64
内部标识号    1975
交易次数        0
交易金额     7177
Name: 1974, dtype: int64
内部标识号    1976
交易次数       13
交易金额      317
Name: 1975, dtype: int64
内部标识号    1977
交易次数       15
交易金额      958
Name: 1976, dtype: int64
内部标识号    1978
交易次数       15
交易金额      853
Name: 1977, dtype: int64
内部标识号    1979
交易次数       11
交易金额      439
Name: 1978, dtype: int64
内部标识号    1980
交易次数       23
交易金额       19
Name: 1979, dtype: int64
内部标识号    1981
交易次数        2
交易金额      505
Name: 1980, dtype: int64
内部标识号    1982
交易次数       15
交易金额      772
Name: 1981, dtype: int64
内部标识号    1983
交易次数        0
交易金额     3978
Name: 1982, dtype: int64
内部标识号    1984
交易次数        8
交易金额      202
Name: 1983, dtype: int64
内部标识号    1985
交易次数        2
交易金额      733
Name: 1984, dtype: int64
内部标识号    1986
交易次数        3
交易金额      329
Name: 1985, dtype: int64
内部标识号    1987
交易次数        3
交易金额      361
Name: 1986, dtype: int64
内部标识号    1988
交易次数        0
交易金额     1358
Name: 1987, dtype: int64
内部标识号    1989
交易次数        2
交易金额      419
Name: 1988, dtype: int64
内部标识号    1990
交易次数        7
交易金额      174
Name: 1989, dtype: int64
内部标识号    1991
交易次数        5
交易金额      256
Name: 1990, dtype: int64
内部标识号    1992
交易次数       10
交易金额      398
Name: 1991, dtype: int64
内部标识号    1993
交易次数        3
交易金额      376
Name: 1992, dtype: int64
内部标识号    1994
交易次数       23
交易金额      601
Name: 1993, dtype: int64
内部标识号    1995
交易次数       10
交易金额      337
Name: 1994, dtype: int64
内部标识号    1996
交易次数        4
交易金额      134
Name: 1995, dtype: int64
内部标识号    1997
交易次数       15
交易金额      714
Name: 1996, dtype: int64
内部标识号    1998
交易次数        0
交易金额     3907
Name: 1997, dtype: int64
内部标识号    1999
交易次数       14
交易金额      369
Name: 1998, dtype: int64
内部标识号    2000
交易次数        9
交易金额      412
Name: 1999, dtype: int64
内部标识号     2001
交易次数       191
交易金额     62344
Name: 2000, dtype: int64
内部标识号    2002
交易次数        6
交易金额      160
Name: 2001, dtype: int64
内部标识号    2003
交易次数        2
交易金额      446
Name: 2002, dtype: int64
内部标识号    2004
交易次数        3
交易金额      404
Name: 2003, dtype: int64
内部标识号    2005
交易次数       27
交易金额     9388
Name: 2004, dtype: int64
内部标识号    2006
交易次数       12
交易金额      862
Name: 2005, dtype: int64
内部标识号    2007
交易次数       11
交易金额      794
Name: 2006, dtype: int64
内部标识号     2008
交易次数         8
交易金额     35213
Name: 2007, dtype: int64
内部标识号    2009
交易次数       20
交易金额      979
Name: 2008, dtype: int64
内部标识号    2010
交易次数        1
交易金额      692
Name: 2009, dtype: int64
内部标识号    2011
交易次数        6
交易金额      189
Name: 2010, dtype: int64
内部标识号    2012
交易次数       14
交易金额      526
Name: 2011, dtype: int64
内部标识号    2013
交易次数        7
交易金额      222
Name: 2012, dtype: int64
内部标识号    2014
交易次数        2
交易金额      419
Name: 2013, dtype: int64
内部标识号    2015
交易次数        2
交易金额      520
Name: 2014, dtype: int64
内部标识号    2016
交易次数        0
交易金额     2446
Name: 2015, dtype: int64
内部标识号    2017
交易次数        8
交易金额      432
Name: 2016, dtype: int64
内部标识号    2018
交易次数       14
交易金额      646
Name: 2017, dtype: int64
内部标识号    2019
交易次数       15
交易金额      399
Name: 2018, dtype: int64
内部标识号     2020
交易次数         7
交易金额     16092
Name: 2019, dtype: int64
内部标识号    2021
交易次数        1
交易金额      593
Name: 2020, dtype: int64
内部标识号    2022
交易次数        2
交易金额      400
Name: 2021, dtype: int64
内部标识号    2023
交易次数       13
交易金额      887
Name: 2022, dtype: int64
内部标识号    2024
交易次数        8
交易金额      361
Name: 2023, dtype: int64
内部标识号    2025
交易次数        7
交易金额      131
Name: 2024, dtype: int64
内部标识号    2026
交易次数        1
交易金额      884
Name: 2025, dtype: int64
内部标识号    2027
交易次数        2
交易金额      400
Name: 2026, dtype: int64
内部标识号    2028
交易次数       19
交易金额      714
Name: 2027, dtype: int64
内部标识号    2029
交易次数        9
交易金额      474
Name: 2028, dtype: int64
内部标识号    2030
交易次数       12
交易金额      506
Name: 2029, dtype: int64
内部标识号    2031
交易次数        0
交易金额     8167
Name: 2030, dtype: int64
内部标识号    2032
交易次数       15
交易金额      432
Name: 2031, dtype: int64
内部标识号    2033
交易次数        4
交易金额      264
Name: 2032, dtype: int64
内部标识号    2034
交易次数       15
交易金额      531
Name: 2033, dtype: int64
内部标识号    2035
交易次数        6
交易金额      287
Name: 2034, dtype: int64
内部标识号    2036
交易次数        6
交易金额      260
Name: 2035, dtype: int64
内部标识号    2037
交易次数        5
交易金额      291
Name: 2036, dtype: int64
内部标识号    2038
交易次数       20
交易金额     9905
Name: 2037, dtype: int64
内部标识号    2039
交易次数       10
交易金额      952
Name: 2038, dtype: int64
内部标识号    2040
交易次数       12
交易金额      381
Name: 2039, dtype: int64
内部标识号    2041
交易次数       29
交易金额     8342
Name: 2040, dtype: int64
内部标识号    2042
交易次数        3
交易金额      478
Name: 2041, dtype: int64
内部标识号    2043
交易次数       18
交易金额     6649
Name: 2042, dtype: int64
内部标识号     2044
交易次数         4
交易金额     92083
Name: 2043, dtype: int64
内部标识号    2045
交易次数       11
交易金额      616
Name: 2044, dtype: int64
内部标识号    2046
交易次数        2
交易金额      496
Name: 2045, dtype: int64
内部标识号    2047
交易次数        2
交易金额      475
Name: 2046, dtype: int64
内部标识号    2048
交易次数       21
交易金额     5228
Name: 2047, dtype: int64
内部标识号    2049
交易次数        5
交易金额      158
Name: 2048, dtype: int64
内部标识号    2050
交易次数        1
交易金额      766
Name: 2049, dtype: int64
内部标识号    2051
交易次数       11
交易金额      330
Name: 2050, dtype: int64
内部标识号    2052
交易次数       24
交易金额     5556
Name: 2051, dtype: int64
内部标识号    2053
交易次数        3
交易金额      386
Name: 2052, dtype: int64
内部标识号    2054
交易次数        5
交易金额      230
Name: 2053, dtype: int64
内部标识号    2055
交易次数        4
交易金额      167
Name: 2054, dtype: int64
内部标识号    2056
交易次数        5
交易金额      283
Name: 2055, dtype: int64
内部标识号    2057
交易次数        5
交易金额      137
Name: 2056, dtype: int64
内部标识号    2058
交易次数       13
交易金额      673
Name: 2057, dtype: int64
内部标识号    2059
交易次数       20
交易金额     2647
Name: 2058, dtype: int64
内部标识号    2060
交易次数        8
交易金额      283
Name: 2059, dtype: int64
内部标识号    2061
交易次数        6
交易金额      246
Name: 2060, dtype: int64
内部标识号    2062
交易次数       10
交易金额      957
Name: 2061, dtype: int64
内部标识号    2063
交易次数        1
交易金额      603
Name: 2062, dtype: int64
内部标识号    2064
交易次数        8
交易金额      419
Name: 2063, dtype: int64
内部标识号    2065
交易次数       12
交易金额      670
Name: 2064, dtype: int64
内部标识号    2066
交易次数       21
交易金额     5468
Name: 2065, dtype: int64
内部标识号    2067
交易次数        3
交易金额      234
Name: 2066, dtype: int64
内部标识号     2068
交易次数        58
交易金额     63087
Name: 2067, dtype: int64
内部标识号    2069
交易次数        2
交易金额      488
Name: 2068, dtype: int64
内部标识号    2070
交易次数       29
交易金额     3661
Name: 2069, dtype: int64
内部标识号    2071
交易次数        3
交易金额      403
Name: 2070, dtype: int64
内部标识号    2072
交易次数        9
交易金额      745
Name: 2071, dtype: int64
内部标识号    2073
交易次数       18
交易金额     8828
Name: 2072, dtype: int64
内部标识号    2074
交易次数        3
交易金额      295
Name: 2073, dtype: int64
内部标识号    2075
交易次数        2
交易金额      434
Name: 2074, dtype: int64
内部标识号    2076
交易次数       12
交易金额      818
Name: 2075, dtype: int64
内部标识号    2077
交易次数       19
交易金额     2270
Name: 2076, dtype: int64
内部标识号    2078
交易次数       22
交易金额     9084
Name: 2077, dtype: int64
内部标识号    2079
交易次数       17
交易金额     5180
Name: 2078, dtype: int64
内部标识号    2080
交易次数        6
交易金额      155
Name: 2079, dtype: int64
内部标识号     2081
交易次数        57
交易金额     20605
Name: 2080, dtype: int64
内部标识号    2082
交易次数        1
交易金额     7453
Name: 2081, dtype: int64
内部标识号    2083
交易次数        0
交易金额     7003
Name: 2082, dtype: int64
内部标识号    2084
交易次数        0
交易金额     3199
Name: 2083, dtype: int64
内部标识号     2085
交易次数       257
交易金额     29400
Name: 2084, dtype: int64
内部标识号    2086
交易次数       10
交易金额      662
Name: 2085, dtype: int64
内部标识号    2087
交易次数        8
交易金额      476
Name: 2086, dtype: int64
内部标识号    2088
交易次数        6
交易金额      294
Name: 2087, dtype: int64
内部标识号    2089
交易次数        1
交易金额      815
Name: 2088, dtype: int64
内部标识号    2090
交易次数        6
交易金额      229
Name: 2089, dtype: int64
内部标识号    2091
交易次数        2
交易金额      372
Name: 2090, dtype: int64
内部标识号    2092
交易次数        4
交易金额      168
Name: 2091, dtype: int64
内部标识号    2093
交易次数        2
交易金额      323
Name: 2092, dtype: int64
内部标识号    2094
交易次数        2
交易金额      944
Name: 2093, dtype: int64
内部标识号    2095
交易次数       10
交易金额      611
Name: 2094, dtype: int64
内部标识号    2096
交易次数        8
交易金额      838
Name: 2095, dtype: int64
内部标识号    2097
交易次数       15
交易金额      933
Name: 2096, dtype: int64
内部标识号    2098
交易次数       20
交易金额     5433
Name: 2097, dtype: int64
内部标识号    2099
交易次数       18
交易金额     3549
Name: 2098, dtype: int64
内部标识号     2100
交易次数         4
交易金额     61556
Name: 2099, dtype: int64
内部标识号    2101
交易次数        9
交易金额      497
Name: 2100, dtype: int64
内部标识号    2102
交易次数       18
交易金额      844
Name: 2101, dtype: int64
内部标识号    2103
交易次数        9
交易金额      939
Name: 2102, dtype: int64
内部标识号    2104
交易次数        2
交易金额      915
Name: 2103, dtype: int64
内部标识号    2105
交易次数        0
交易金额     8508
Name: 2104, dtype: int64
内部标识号    2106
交易次数        2
交易金额      236
Name: 2105, dtype: int64
内部标识号    2107
交易次数        3
交易金额      404
Name: 2106, dtype: int64
内部标识号    2108
交易次数        9
交易金额      628
Name: 2107, dtype: int64
内部标识号    2109
交易次数        8
交易金额      164
Name: 2108, dtype: int64
内部标识号    2110
交易次数        2
交易金额      670
Name: 2109, dtype: int64
内部标识号    2111
交易次数        7
交易金额      285
Name: 2110, dtype: int64
内部标识号    2112
交易次数        0
交易金额     6277
Name: 2111, dtype: int64
内部标识号    2113
交易次数        3
交易金额      206
Name: 2112, dtype: int64
内部标识号    2114
交易次数        1
交易金额     5697
Name: 2113, dtype: int64
内部标识号    2115
交易次数        9
交易金额      363
Name: 2114, dtype: int64
内部标识号    2116
交易次数       15
交易金额       91
Name: 2115, dtype: int64
内部标识号    2117
交易次数       12
交易金额      570
Name: 2116, dtype: int64
内部标识号     2118
交易次数         4
交易金额     21668
Name: 2117, dtype: int64
内部标识号    2119
交易次数        6
交易金额      100
Name: 2118, dtype: int64
内部标识号    2120
交易次数        9
交易金额      808
Name: 2119, dtype: int64
内部标识号    2121
交易次数       12
交易金额      483
Name: 2120, dtype: int64
内部标识号    2122
交易次数        3
交易金额      494
Name: 2121, dtype: int64
内部标识号    2123
交易次数        8
交易金额      197
Name: 2122, dtype: int64
内部标识号    2124
交易次数        5
交易金额      252
Name: 2123, dtype: int64
内部标识号    2125
交易次数       16
交易金额      715
Name: 2124, dtype: int64
内部标识号    2126
交易次数        9
交易金额      786
Name: 2125, dtype: int64
内部标识号    2127
交易次数        2
交易金额      324
Name: 2126, dtype: int64
内部标识号    2128
交易次数        2
交易金额      344
Name: 2127, dtype: int64
内部标识号    2129
交易次数        2
交易金额      550
Name: 2128, dtype: int64
内部标识号     2130
交易次数         5
交易金额     11715
Name: 2129, dtype: int64
内部标识号    2131
交易次数        8
交易金额      223
Name: 2130, dtype: int64
内部标识号    2132
交易次数       15
交易金额      540
Name: 2131, dtype: int64
内部标识号    2133
交易次数        1
交易金额      634
Name: 2132, dtype: int64
内部标识号    2134
交易次数        3
交易金额      304
Name: 2133, dtype: int64
内部标识号    2135
交易次数       15
交易金额      479
Name: 2134, dtype: int64
内部标识号    2136
交易次数        3
交易金额      352
Name: 2135, dtype: int64
内部标识号     2137
交易次数         7
交易金额     40341
Name: 2136, dtype: int64
内部标识号    2138
交易次数       13
交易金额      331
Name: 2137, dtype: int64
内部标识号    2139

Name: 2184, dtype: int64
内部标识号    2186
交易次数       14
交易金额      872
Name: 2185, dtype: int64
内部标识号    2187
交易次数       29
交易金额       92
Name: 2186, dtype: int64
内部标识号    2188
交易次数       10
交易金额      403
Name: 2187, dtype: int64
内部标识号    2189
交易次数       10
交易金额      929
Name: 2188, dtype: int64
内部标识号    2190
交易次数       18
交易金额     2990
Name: 2189, dtype: int64
内部标识号    2191
交易次数       10
交易金额      616
Name: 2190, dtype: int64
内部标识号    2192
交易次数        3
交易金额      222
Name: 2191, dtype: int64
内部标识号    2193
交易次数        3
交易金额      300
Name: 2192, dtype: int64
内部标识号    2194
交易次数        7
交易金额      191
Name: 2193, dtype: int64
内部标识号    2195
交易次数        2
交易金额      478
Name: 2194, dtype: int64
内部标识号    2196
交易次数        8
交易金额      589
Name: 2195, dtype: int64
内部标识号    2197
交易次数        6
交易金额      135
Name: 2196, dtype: int64
内部标识号    2198
交易次数        2
交易金额      300
Name: 2197, dtype: int64
内部标识号    2199
交易次数        3
交易金额      379
Name: 2198, dtype: int64
内部标识号    2200
交易次数       14
交易金额      650
Name: 2199, dtype: int64
内部标识号    2201
交易次数        1
交易金额      676
Name: 2200, dtype: int64
内部标识号    2202
交易次数        7
交易金额      187
Name: 2201, dtype: int64
内部标识号    2203
交易次数        9
交易金额      428
Name: 2202, dtype: int64
内部标识号    2204
交易次数        7
交易金额      273
Name: 2203, dtype: int64
内部标识号    2205
交易次数        2
交易金额      471
Name: 2204, dtype: int64
内部标识号     2206
交易次数         4
交易金额     87927
Name: 2205, dtype: int64
内部标识号    2207
交易次数        7
交易金额      266
Name: 2206, dtype: int64
内部标识号     2208
交易次数         6
交易金额     55664
Name: 2207, dtype: int64
内部标识号    2209
交易次数        2
交易金额      926
Name: 2208, dtype: int64
内部标识号    2210
交易次数        2
交易金额      395
Name: 2209, dtype: int64
内部标识号    2211
交易次数        6
交易金额      261
Name: 2210, dtype: int64
内部标识号    2212
交易次数        8
交易金额      566
Name: 2211, dtype: int64
内部标识号    2213
交易次数       10
交易金额      393
Name: 2212, dtype: int64
内部标识号     2214
交易次数        90
交易金额     40048
Name: 2213, dtype: int64
内部标识号     2215
交易次数        77
交易金额     21211
Name: 2214, dtype: int64
内部标识号    2216
交易次数        2
交易金额      881
Name: 2215, dtype: int64
内部标识号    2217
交易次数       14
交易金额      424
Name: 2216, dtype: int64
内部标识号    2218
交易次数       21
交易金额     6074
Name: 2217, dtype: int64
内部标识号    2219
交易次数        1
交易金额     6785
Name: 2218, dtype: int64
内部标识号    2220
交易次数       15
交易金额      345
Name: 2219, dtype: int64
内部标识号    2221
交易次数        8
交易金额      288
Name: 2220, dtype: int64
内部标识号    2222
交易次数        3
交易金额      289
Name: 2221, dtype: int64
内部标识号    2223
交易次数        2
交易金额      884
Name: 2222, dtype: int64
内部标识号    2224
交易次数       21
交易金额      870
Name: 2223, dtype: int64
内部标识号    2225
交易次数       17
交易金额     3698
Name: 2224, dtype: int64
内部标识号    2226
交易次数       13
交易金额      471
Name: 2225, dtype: int64
内部标识号    2227
交易次数        1
交易金额      864
Name: 2226, dtype: int64
内部标识号    2228
交易次数       11
交易金额      408
Name: 2227, dtype: int64
内部标识号    2229
交易次数        7
交易金额      173
Name: 2228, dtype: int64
内部标识号    2230
交易次数        0
交易金额     6958
Name: 2229, dtype: int64
内部标识号    2231
交易次数       10
交易金额      996
Name: 2230, dtype: int64
内部标识号    2232
交易次数        4
交易金额      156
Name: 2231, dtype: int64
内部标识号    2233
交易次数        5
交易金额      116
Name: 2232, dtype: int64
内部标识号    2234
交易次数        2
交易金额      792
Name: 2233, dtype: int64
内部标识号    2235
交易次数        8
交易金额      822
Name: 2234, dtype: int64
内部标识号    2236
交易次数       27
交易金额     9301
Name: 2235, dtype: int64
内部标识号    2237
交易次数        5
交易金额      282
Name: 2236, dtype: int64
内部标识号    2238
交易次数       14
交易金额      324
Name: 2237, dtype: int64
内部标识号    2239
交易次数        1
交易金额     1981
Name: 2238, dtype: int64
内部标识号    2240
交易次数       29
交易金额     4985
Name: 2239, dtype: int64
内部标识号    2241
交易次数        0
交易金额     5869
Name: 2240, dtype: int64
内部标识号    2242
交易次数       14
交易金额      482
Name: 2241, dtype: int64
内部标识号    2243
交易次数       29
交易金额       43
Name: 2242, dtype: int64
内部标识号     2244
交易次数        72
交易金额     63188
Name: 2243, dtype: int64
内部标识号    2245
交易次数        0
交易金额     9895
Name: 2244, dtype: int64
内部标识号    2246
交易次数        2
交易金额      657
Name: 2245, dtype: int64
内部标识号    2247
交易次数       18
交易金额      542
Name: 2246, dtype: int64
内部标识号    2248
交易次数       15
交易金额      917
Name: 2247, dtype: int64
内部标识号    2249
交易次数        2
交易金额      354
Name: 2248, dtype: int64
内部标识号    2250
交易次数       10
交易金额      581
Name: 2249, dtype: int64
内部标识号    2251
交易次数        3
交易金额      486
Name: 2250, dtype: int64
内部标识号    2252
交易次数        3
交易金额      500
Name: 2251, dtype: int64
内部标识号    2253
交易次数       12
交易金额      778
Name: 2252, dtype: int64
内部标识号    2254
交易次数       25
交易金额     4039
Name: 2253, dtype: int64
内部标识号     2255
交易次数         7
交易金额     86253
Name: 2254, dtype: int64
内部标识号    2256
交易次数       13
交易金额      333
Name: 2255, dtype: int64
内部标识号    2257
交易次数       13
交易金额      474
Name: 2256, dtype: int64
内部标识号    2258
交易次数        3
交易金额      171
Name: 2257, dtype: int64
内部标识号    2259
交易次数        4
交易金额      271
Name: 2258, dtype: int64
内部标识号    2260
交易次数        1
交易金额     4450
Name: 2259, dtype: int64
内部标识号    2261
交易次数       10
交易金额      362
Name: 2260, dtype: int64
内部标识号    2262
交易次数        8
交易金额      617
Name: 2261, dtype: int64
内部标识号    2263
交易次数        5
交易金额      291
Name: 2262, dtype: int64
内部标识号    2264
交易次数        3
交易金额      151
Name: 2263, dtype: int64
内部标识号    2265
交易次数        6
交易金额      297
Name: 2264, dtype: int64
内部标识号     2266
交易次数        41
交易金额     31125
Name: 2265, dtype: int64
内部标识号    2267
交易次数        0
交易金额     8292
Name: 2266, dtype: int64
内部标识号    2268
交易次数        1
交易金额     3577
Name: 2267, dtype: int64
内部标识号    2269
交易次数        0
交易金额     3410
Name: 2268, dtype: int64
内部标识号    2270
交易次数        2
交易金额      374
Name: 2269, dtype: int64
内部标识号    2271
交易次数       14
交易金额      565
Name: 2270, dtype: int64
内部标识号     2272
交易次数        78
交易金额     21481
Name: 2271, dtype: int64
内部标识号    2273
交易次数        8
交易金额      590
Name: 2272, dtype: int64
内部标识号    2274
交易次数       21
交易金额     1956
Name: 2273, dtype: int64
内部标识号    2275
交易次数        3
交易金额      480
Name: 2274, dtype: int64
内部标识号    2276
交易次数        0
交易金额     4997
Name: 2275, dtype: int64
内部标识号    2277
交易次数        3
交易金额      472
Name: 2276, dtype: int64
内部标识号    2278
交易次数        2
交易金额      493
Name: 2277, dtype: int64
内部标识号    2279
交易次数       15
交易金额      639
Name: 2278, dtype: int64
内部标识号    2280
交易次数       30
交易金额     1425
Name: 2279, dtype: int64
内部标识号    2281
交易次数        3
交易金额      168
Name: 2280, dtype: int64
内部标识号    2282
交易次数       28
交易金额     6536
Name: 2281, dtype: int64
内部标识号    2283
交易次数        9
交易金额      335
Name: 2282, dtype: int64
内部标识号    2284
交易次数       11
交易金额      608
Name: 2283, dtype: int64
内部标识号    2285
交易次数       20
交易金额     8251
Name: 2284, dtype: int64
内部标识号    2286
交易次数        3
交易金额      412
Name: 2285, dtype: int64
内部标识号    2287
交易次数       10
交易金额      616
Name: 2286, dtype: int64
内部标识号    2288
交易次数        2
交易金额      542
Name: 2287, dtype: int64
内部标识号    2289
交易次数        2
交易金额      413
Name: 2288, dtype: int64
内部标识号    2290
交易次数        3
交易金额      167
Name: 2289, dtype: int64
内部标识号    2291
交易次数        2
交易金额      476
Name: 2290, dtype: int64
内部标识号    2292
交易次数        4
交易金额      203
Name: 2291, dtype: int64
内部标识号    2293
交易次数        2
交易金额      683
Name: 2292, dtype: int64
内部标识号    2294
交易次数       15
交易金额      331
Name: 2293, dtype: int64
内部标识号    2295
交易次数        2
交易金额      320
Name: 2294, dtype: int64
内部标识号     2296
交易次数       142
交易金额     51475
Name: 2295, dtype: int64
内部标识号    2297
交易次数        3
交易金额      290
Name: 2296, dtype: int64
内部标识号    2298
交易次数       14
交易金额      710
Name: 2297, dtype: int64
内部标识号    2299
交易次数        5
交易金额      223
Name: 2298, dtype: int64
内部标识号    2300
交易次数       29
交易金额     4889
Name: 2299, dtype: int64
内部标识号     2301
交易次数         8
交易金额     91545
Name: 2300, dtype: int64
内部标识号     2302
交易次数       127
交易金额     74139
Name: 2301, dtype: int64
内部标识号     2303
交易次数         3
交易金额     98321
Name: 2302, dtype: int64
内部标识号    2304
交易次数        6
交易金额      219
Name: 2303, dtype: int64
内部标识号    2305
交易次数        1
交易金额     9851
Name: 2304, dtype: int64
内部标识号    2306
交易次数        8
交易金额      225
Name: 2305, dtype: int64
内部标识号    2307
交易次数       11
交易金额      432
Name: 2306, dtype: int64
内部标识号     2308
交易次数         4
交易金额     31305
Name: 2307, dtype: int64
内部标识号    2309
交易次数        2
交易金额      398
Name: 2308, dtype: int64
内部标识号    2310
交易次数        5
交易金额      267
Name: 2309, dtype: int64
内部标识号    2311
交易次数        5
交易金额      164
Name: 2310, dtype: int64
内部标识号    2312
交易次数       12
交易金额      722
Name: 2311, dtype: int64
内部标识号    2313
交易次数        0
交易金额     9232
Name: 2312, dtype: int64
内部标识号    2314
交易次数        8
交易金额      397
Name: 2313, dtype: int64
内部标识号    2315
交易次数        8
交易金额      404
Name: 2314, dtype: int64
内部标识号    2316
交易次数        2
交易金额      149
Name: 2315, dtype: int64
内部标识号    2317
交易次数       14
交易金额      393
Name: 2316, dtype: int64
内部标识号    2318
交易次数       11
交易金额      399
Name: 2317, dtype: int64
内部标识号    2319
交易次数        0
交易金额     9048
Name: 2318, dtype: int64
内部标识号    2320
交易次数        2
交易金额      450
Name: 2319, dtype: int64
内部标识号    2321
交易次数        2
交易金额      121
Name: 2320, dtype: int64
内部标识号    2322
交易次数        8
交易金额      476
Name: 2321, dtype: int64
内部标识号    2323
交易次数       14
交易金额      425
Name: 2322, dtype: int64
内部标识号    2324
交易次数        3
交易金额      360
Name: 2323, dtype: int64
内部标识号    2325
交易次数        3
交易金额      362
Name: 2324, dtype: int64
内部标识号    2326
交易次数       22
交易金额      693
Name: 2325, dtype: int64
内部标识号    2327
交易次数        2
交易金额      357
Name: 2326, dtype: int64
内部标识号    2328
交易次数       12
交易金额      807
Name: 2327, dtype: int64
内部标识号    2329
交易次数        2
交易金额      345
Name: 2328, dtype: int64
内部标识号     2330
交易次数         8
交易金额     15590
Name: 2329, dtype: int64
内部标识号    2331
交易次数        3
交易金额      313
Name: 2330, dtype: int64
内部标识号     2332
交易次数         6
交易金额     17936
Name: 2331, dtype: int64
内部标识号    2333
交易次数       20
交易金额       11
Name: 2332, dtype: int64
内部标识号    2334
交易次数        4
交易金额      184
Name: 2333, dtype: int64
内部标识号    2335
交易次数        5
交易金额      116
Name: 2334, dtype: int64
内部标识号    2336
交易次数        2
交易金额      157
Name: 2335, dtype: int64
内部标识号    2337
交易次数        2
交易金额      765
Name: 2336, dtype: int64
内部标识号    2338
交易次数        1
交易金额     6278
Name: 2337, dtype: int64
内部标识号    2339
交易次数        2
交易金额      784
Name: 2338, dtype: int64
内部标识号    2340
交易次数        2
交易金额      385
Name: 2339, dtype: int64
内部标识号    2341
交易次数        9
交易金额      525
Name: 2340, dtype: int64
内部标识号    2342
交易次数       19
交易金额     7294
Name: 2341, dtype: int64
内部标识号    2343
交易次数       29
交易金额      597
Name: 2342, dtype: int64
内部标识号    2344
交易次数        7
交易金额      231
Name: 2343, dtype: int64
内部标识号    2345
交易次数        2
交易金额      609
Name: 2344, dtype: int64
内部标识号    2346
交易次数       18
交易金额      649
Name: 2345, dtype: int64
内部标识号    2347
交易次数        1
交易金额      753
Name: 2346, dtype: int64
内部标识号    2348
交易次数       29
交易金额     7247
Name: 2347, dtype: int64
内部标识号    2349
交易次数       14
交易金额      363
Name: 2348, dtype: int64
内部标识号    2350
交易次数        9
交易金额      876
Name: 2349, dtype: int64
内部标识号    2351
交易次数       10
交易金额      559
Name: 2350, dtype: int64
内部标识号    2352
交易次数        3
交易金额      360
Name: 2351, dtype: int64
内部标识号    2353
交易次数       11
交易金额      680
Name: 2352, dtype: int64
内部标识号    2354
交易次数        9
交易金额      417
Name: 2353, dtype: int64
内部标识号    2355
交易次数       15
交易金额      975
Name: 2354, dtype: int64
内部标识号    2356
交易次数        2
交易金额      837
Name: 2355, dtype: int64
内部标识号    2357
交易次数        2
交易金额      488
Name: 2356, dtype: int64
内部标识号    2358
交易次数       15
交易金额      516
Name: 2357, dtype: int64
内部标识号    2359
交易次数       10
交易金额      479
Name: 2358, dtype: int64
内部标识号    2360
交易次数       17
交易金额     7563
Name: 2359, dtype: int64
内部标识号    2361
交易次数        8
交易金额      249
Name: 2360, dtype: int64
内部标识号    2362
交易次数        7
交易金额      249
Name: 2361, dtype: int64
内部标识号    2363
交易次数       30
交易金额       29
Name: 2362, dtype: int64
内部标识号    2364
交易次数        4
交易金额      222
Name: 2363, dtype: int64
内部标识号    2365
交易次数        9
交易金额      379
Name: 2364, dtype: int64
内部标识号    2366
交易次数       16
交易金额     3837
Name: 2365, dtype: int64
内部标识号    2367
交易次数        3
交易金额      413
Name: 2366, dtype: int64
内部标识号    2368
交易次数       11
交易金额      420
Name: 2367, dtype: int64
内部标识号    2369
交易次数        7
交易金额      222
Name: 2368, dtype: int64
内部标识号    2370
交易次数       23
交易金额      736
Name: 2369, dtype: int64
内部标识号    2371
交易次数        8
交易金额      206
Name: 2370, dtype: int64
内部标识号    2372
交易次数       21
交易金额      542
Name: 2371, dtype: int64
内部标识号    2373
交易次数        1
交易金额      980
Name: 2372, dtype: int64
内部标识号    2374
交易次数       16
交易金额      890
Name: 2373, dtype: int64
内部标识号    2375
交易次数        0
交易金额     6654
Name: 2374, dtype: int64
内部标识号    2376
交易次数        2
交易金额      439
Name: 2375, dtype: int64
内部标识号    2377
交易次数        9
交易金额      302
Name: 2376, dtype: int64
内部标识号    2378
交易次数       28
交易金额     7709
Name: 2377, dtype: int64
内部标识号    2379
交易次数        3
交易金额      486
Name: 2378, dtype: int64
内部标识号    2380
交易次数        4
交易金额      282
Name: 2379, dtype: int64
内部标识号    2381
交易次数        0
交易金额     4013
Name: 2380, dtype: int64
内部标识号    2382
交易次数       14
交易金额      824
Name: 2381, dtype: int64
内部标识号    2383
交易次数       14
交易金额      832
Name: 2382, dtype: int64
内部标识号    2384
交易次数        3
交易金额      333
Name: 2383, dtype: int64
内部标识号    2385
交易次数        3
交易金额      450
Name: 2384, dtype: int64
内部标识号    2386
交易次数       12
交易金额      451
Name: 2385, dtype: int64
内部标识号    2387
交易次数       15
交易金额      574
Name: 2386, dtype: int64
内部标识号    2388
交易次数        2
交易金额      720
Name: 2387, dtype: int64
内部标识号    2389
交易次数       18
交易金额      885
Name: 2388, dtype: int64
内部标识号    2390
交易次数        3
交易金额      420
Name: 2389, dtype: int64
内部标识号    2391
交易次数        2
交易金额      908
Name: 2390, dtype: int64
内部标识号    2392
交易次数        0
交易金额     9774
Name: 2391, dtype: int64
内部标识号     2393
交易次数         4
交易金额     73429
Name: 2392, dtype: int64
内部标识号    2394
交易次数        1
交易金额      971
Name: 2393, dtype: int64
内部标识号    2395
交易次数       13
交易金额      798
Name: 2394, dtype: int64
内部标识号    2396
交易次数       17
交易金额     2621
Name: 2395, dtype: int64
内部标识号    2397
交易次数        3
交易金额      405
Name: 2396, dtype: int64
内部标识号     2398
交易次数         3
交易金额     49659
Name: 2397, dtype: int64
内部标识号    2399
交易次数        3
交易金额      148
Name: 2398, dtype: int64
内部标识号    2400
交易次数        3
交易金额      346
Name: 2399, dtype: int64
内部标识号    2401
交易次数        0
交易金额     9388
Name: 2400, dtype: int64
内部标识号    2402
交易次数       28
交易金额      605
Name: 2401, dtype: int64
内部标识号    2403
交易次数       25
交易金额     2021
Name: 2402, dtype: int64
内部标识号    2404
交易次数        9
交易金额      416
Name: 2403, dtype: int64
内部标识号    2405
交易次数       12
交易金额      505
Name: 2404, dtype: int64
内部标识号    2406
交易次数        2
交易金额      822
Name: 2405, dtype: int64
内部标识号    2407
交易次数       13
交易金额      699
Name: 2406, dtype: int64
内部标识号    2408
交易次数       21
交易金额      947
Name: 2407, dtype: int64
内部标识号    2409
交易次数        1
交易金额      566
Name: 2408, dtype: int64
内部标识号    2410
交易次数        2
交易金额      350
Name: 2409, dtype: int64
内部标识号    2411
交易次数       15
交易金额      653
Name: 2410, dtype: int64
内部标识号    2412
交易次数        6
交易金额      298
Name: 2411, dtype: int64
内部标识号    2413
交易次数        5
交易金额      151
Name: 2412, dtype: int64
内部标识号    2414
交易次数        8
交易金额      629
Name: 2413, dtype: int64
内部标识号    2415
交易次数        3
交易金额      298
Name: 2414, dtype: int64
内部标识号    2416
交易次数       27
交易金额       28
Name: 2415, dtype: int64
内部标识号    2417
交易次数       11
交易金额      708
Name: 2416, dtype: int64
内部标识号     2418
交易次数       140
交易金额     32519
Name: 2417, dtype: int64
内部标识号    2419
交易次数       17
交易金额     4208
Name: 2418, dtype: int64
内部标识号    2420
交易次数       15
交易金额      460
Name: 2419, dtype: int64
内部标识号    2421
交易次数        2
交易金额      340
Name: 2420, dtype: int64
内部标识号    2422
交易次数        3
交易金额      227
Name: 2421, dtype: int64
内部标识号    2423
交易次数       20
交易金额     3532
Name: 2422, dtype: int64
内部标识号    2424
交易次数       22
交易金额     6785
Name: 2423, dtype: int64
内部标识号    2425
交易次数        6
交易金额      172

Name: 2424, dtype: int64
内部标识号    2426
交易次数        4
交易金额      262
Name: 2425, dtype: int64
内部标识号    2427
交易次数        3
交易金额      169
Name: 2426, dtype: int64
内部标识号     2428
交易次数       250
交易金额     23265
Name: 2427, dtype: int64
内部标识号     2429
交易次数         8
交易金额     40610
Name: 2428, dtype: int64
内部标识号    2430
交易次数        3
交易金额      237
Name: 2429, dtype: int64
内部标识号    2431
交易次数        3
交易金额      271
Name: 2430, dtype: int64
内部标识号    2432
交易次数        8
交易金额      358
Name: 2431, dtype: int64
内部标识号    2433
交易次数        2
交易金额      309
Name: 2432, dtype: int64
内部标识号    2434
交易次数        1
交易金额      542
Name: 2433, dtype: int64
内部标识号    2435
交易次数        3
交易金额      345
Name: 2434, dtype: int64
内部标识号    2436
交易次数        2
交易金额      314
Name: 2435, dtype: int64
内部标识号    2437
交易次数        1
交易金额     3539
Name: 2436, dtype: int64
内部标识号    2438
交易次数        9
交易金额      989
Name: 2437, dtype: int64
内部标识号    2439
交易次数       14
交易金额      862
Name: 2438, dtype: int64
内部标识号    2440
交易次数       21
交易金额     4072
Name: 2439, dtype: int64
内部标识号    2441
交易次数       13
交易金额      497
Name: 2440, dtype: int64
内部标识号     2442
交易次数       241
交易金额     35497
Name: 2441, dtype: int64
内部标识号    2443
交易次数        4
交易金额      191
Name: 2442, dtype: int64
内部标识号     2444
交易次数       116
交易金额     50630
Name: 2443, dtype: int64
内部标识号    2445
交易次数       10
交易金额      891
Name: 2444, dtype: int64
内部标识号    2446
交易次数       11
交易金额      318
Name: 2445, dtype: int64
内部标识号    2447
交易次数        3
交易金额      115
Name: 2446, dtype: int64
内部标识号    2448
交易次数        1
交易金额     8847
Name: 2447, dtype: int64
内部标识号    2449
交易次数        2
交易金额      337
Name: 2448, dtype: int64
内部标识号    2450
交易次数        7
交易金额      278
Name: 2449, dtype: int64
内部标识号    2451
交易次数       17
交易金额     5015
Name: 2450, dtype: int64
内部标识号    2452
交易次数        1
交易金额      778
Name: 2451, dtype: int64
内部标识号    2453
交易次数       13
交易金额      327
Name: 2452, dtype: int64
内部标识号    2454
交易次数        2
交易金额      319
Name: 2453, dtype: int64
内部标识号    2455
交易次数       10
交易金额      988
Name: 2454, dtype: int64
内部标识号    2456
交易次数        2
交易金额      300
Name: 2455, dtype: int64
内部标识号    2457
交易次数       15
交易金额       78
Name: 2456, dtype: int64
内部标识号    2458
交易次数       28
交易金额     5674
Name: 2457, dtype: int64
内部标识号     2459
交易次数         4
交易金额     96797
Name: 2458, dtype: int64
内部标识号    2460
交易次数        4
交易金额      240
Name: 2459, dtype: int64
内部标识号    2461
交易次数       30
交易金额     9202
Name: 2460, dtype: int64
内部标识号    2462
交易次数        2
交易金额      618
Name: 2461, dtype: int64
内部标识号    2463
交易次数       21
交易金额      571
Name: 2462, dtype: int64
内部标识号    2464
交易次数       17
交易金额     3318
Name: 2463, dtype: int64
内部标识号    2465
交易次数       29
交易金额       86
Name: 2464, dtype: int64
内部标识号    2466
交易次数       16
交易金额     6854
Name: 2465, dtype: int64
内部标识号    2467
交易次数        7
交易金额      175
Name: 2466, dtype: int64
内部标识号    2468
交易次数        3
交易金额      358
Name: 2467, dtype: int64
内部标识号     2469
交易次数         7
交易金额     67808
Name: 2468, dtype: int64
内部标识号    2470
交易次数       13
交易金额      917
Name: 2469, dtype: int64
内部标识号    2471
交易次数        2
交易金额      477
Name: 2470, dtype: int64
内部标识号    2472
交易次数        0
交易金额     1900
Name: 2471, dtype: int64
内部标识号    2473
交易次数       15
交易金额     9519
Name: 2472, dtype: int64
内部标识号    2474
交易次数       14
交易金额      538
Name: 2473, dtype: int64
内部标识号    2475
交易次数        8
交易金额      108
Name: 2474, dtype: int64
内部标识号    2476
交易次数       14
交易金额      563
Name: 2475, dtype: int64
内部标识号    2477
交易次数       15
交易金额      806
Name: 2476, dtype: int64
内部标识号    2478
交易次数        0
交易金额     7167
Name: 2477, dtype: int64
内部标识号    2479
交易次数       11
交易金额      457
Name: 2478, dtype: int64
内部标识号     2480
交易次数       103
交易金额     53180
Name: 2479, dtype: int64
内部标识号    2481
交易次数        0
交易金额     4142
Name: 2480, dtype: int64
内部标识号    2482
交易次数        3
交易金额      486
Name: 2481, dtype: int64
内部标识号    2483
交易次数       13
交易金额      941
Name: 2482, dtype: int64
内部标识号    2484
交易次数       15
交易金额      464
Name: 2483, dtype: int64
内部标识号     2485
交易次数         5
交易金额     55680
Name: 2484, dtype: int64
内部标识号    2486
交易次数        3
交易金额      473
Name: 2485, dtype: int64
内部标识号    2487
交易次数       19
交易金额     7157
Name: 2486, dtype: int64
内部标识号    2488
交易次数        3
交易金额      488
Name: 2487, dtype: int64
内部标识号    2489
交易次数        2
交易金额      335
Name: 2488, dtype: int64
内部标识号    2490
交易次数       14
交易金额      457
Name: 2489, dtype: int64
内部标识号    2491
交易次数        8
交易金额      202
Name: 2490, dtype: int64
内部标识号     2492
交易次数         8
交易金额     92903
Name: 2491, dtype: int64
内部标识号    2493
交易次数       11
交易金额      961
Name: 2492, dtype: int64
内部标识号    2494
交易次数        6
交易金额      297
Name: 2493, dtype: int64
内部标识号    2495
交易次数        2
交易金额      236
Name: 2494, dtype: int64
内部标识号    2496
交易次数       11
交易金额      438
Name: 2495, dtype: int64
内部标识号    2497
交易次数        9
交易金额      473
Name: 2496, dtype: int64
内部标识号    2498
交易次数       18
交易金额     1138
Name: 2497, dtype: int64
内部标识号    2499
交易次数        3
交易金额      315
Name: 2498, dtype: int64
内部标识号    2500
交易次数       10
交易金额      927
Name: 2499, dtype: int64
内部标识号    2501
交易次数       13
交易金额      493
Name: 2500, dtype: int64
内部标识号    2502
交易次数        8
交易金额      423
Name: 2501, dtype: int64
内部标识号    2503
交易次数       16
交易金额     8122
Name: 2502, dtype: int64
内部标识号    2504
交易次数       17
交易金额     8677
Name: 2503, dtype: int64
内部标识号    2505
交易次数       13
交易金额      322
Name: 2504, dtype: int64
内部标识号     2506
交易次数         5
交易金额     88804
Name: 2505, dtype: int64
内部标识号     2507
交易次数         6
交易金额     42312
Name: 2506, dtype: int64
内部标识号     2508
交易次数       181
交易金额     95666
Name: 2507, dtype: int64
内部标识号    2509
交易次数       18
交易金额      660
Name: 2508, dtype: int64
内部标识号    2510
交易次数        8
交易金额      122
Name: 2509, dtype: int64
内部标识号    2511
交易次数        2
交易金额      443
Name: 2510, dtype: int64
内部标识号    2512
交易次数        3
交易金额      114
Name: 2511, dtype: int64
内部标识号    2513
交易次数       13
交易金额      322
Name: 2512, dtype: int64
内部标识号    2514
交易次数        3
交易金额      238
Name: 2513, dtype: int64
内部标识号    2515
交易次数        0
交易金额     1888
Name: 2514, dtype: int64
内部标识号    2516
交易次数        0
交易金额     3862
Name: 2515, dtype: int64
内部标识号    2517
交易次数        3
交易金额      293
Name: 2516, dtype: int64
内部标识号    2518
交易次数        3
交易金额      206
Name: 2517, dtype: int64
内部标识号    2519
交易次数       19
交易金额     9135
Name: 2518, dtype: int64
内部标识号    2520
交易次数       15
交易金额      421
Name: 2519, dtype: int64
内部标识号    2521
交易次数        4
交易金额      214
Name: 2520, dtype: int64
内部标识号     2522
交易次数        68
交易金额     15763
Name: 2521, dtype: int64
内部标识号    2523
交易次数       10
交易金额      330
Name: 2522, dtype: int64
内部标识号    2524
交易次数        7
交易金额      224
Name: 2523, dtype: int64
内部标识号    2525
交易次数        1
交易金额      902
Name: 2524, dtype: int64
内部标识号    2526
交易次数       25
交易金额     1584
Name: 2525, dtype: int64
内部标识号     2527
交易次数       263
交易金额     32081
Name: 2526, dtype: int64
内部标识号    2528
交易次数        0
交易金额     7890
Name: 2527, dtype: int64
内部标识号     2529
交易次数         3
交易金额     33568
Name: 2528, dtype: int64
内部标识号    2530
交易次数       24
交易金额      972
Name: 2529, dtype: int64
内部标识号     2531
交易次数         8
交易金额     81313
Name: 2530, dtype: int64
内部标识号    2532
交易次数        2
交易金额      954
Name: 2531, dtype: int64
内部标识号    2533
交易次数       11
交易金额      434
Name: 2532, dtype: int64
内部标识号    2534
交易次数        3
交易金额      314
Name: 2533, dtype: int64
内部标识号    2535
交易次数       14
交易金额      574
Name: 2534, dtype: int64
内部标识号     2536
交易次数         6
交易金额     98383
Name: 2535, dtype: int64
内部标识号    2537
交易次数       12
交易金额      952
Name: 2536, dtype: int64
内部标识号    2538
交易次数       27
交易金额       58
Name: 2537, dtype: int64
内部标识号    2539
交易次数        3
交易金额      414
Name: 2538, dtype: int64
内部标识号    2540
交易次数       14
交易金额      461
Name: 2539, dtype: int64
内部标识号    2541
交易次数        4
交易金额      183
Name: 2540, dtype: int64
内部标识号    2542
交易次数       13
交易金额      408
Name: 2541, dtype: int64
内部标识号    2543
交易次数       11
交易金额      983
Name: 2542, dtype: int64
内部标识号    2544
交易次数        3
交易金额      138
Name: 2543, dtype: int64
内部标识号    2545
交易次数       24
交易金额     7437
Name: 2544, dtype: int64
内部标识号    2546
交易次数       28
交易金额     6205
Name: 2545, dtype: int64
内部标识号    2547
交易次数        8
交易金额      162
Name: 2546, dtype: int64
内部标识号    2548
交易次数       27
交易金额     6620
Name: 2547, dtype: int64
内部标识号    2549
交易次数       13
交易金额      777
Name: 2548, dtype: int64
内部标识号     2550
交易次数        98
交易金额     37322
Name: 2549, dtype: int64
内部标识号    2551
交易次数       18
交易金额     6168
Name: 2550, dtype: int64
内部标识号    2552
交易次数       20
交易金额     4044
Name: 2551, dtype: int64
内部标识号    2553
交易次数        8
交易金额      176
Name: 2552, dtype: int64
内部标识号    2554
交易次数       30
交易金额       67
Name: 2553, dtype: int64
内部标识号     2555
交易次数         6
交易金额     18567
Name: 2554, dtype: int64
内部标识号    2556
交易次数       15
交易金额      598
Name: 2555, dtype: int64
内部标识号    2557
交易次数       12
交易金额      882
Name: 2556, dtype: int64
内部标识号    2558
交易次数       23
交易金额      605
Name: 2557, dtype: int64
内部标识号    2559
交易次数        4
交易金额      141
Name: 2558, dtype: int64
内部标识号    2560
交易次数       13
交易金额      549
Name: 2559, dtype: int64
内部标识号    2561
交易次数       24
交易金额      775
Name: 2560, dtype: int64
内部标识号    2562
交易次数       13
交易金额      459
Name: 2561, dtype: int64
内部标识号    2563
交易次数       10
交易金额      583
Name: 2562, dtype: int64
内部标识号    2564
交易次数        3
交易金额      415
Name: 2563, dtype: int64
内部标识号    2565
交易次数        3
交易金额      292
Name: 2564, dtype: int64
内部标识号     2566
交易次数         3
交易金额     74655
Name: 2565, dtype: int64
内部标识号    2567
交易次数       14
交易金额      903
Name: 2566, dtype: int64
内部标识号    2568
交易次数       27
交易金额      593
Name: 2567, dtype: int64
内部标识号    2569
交易次数        8
交易金额      183
Name: 2568, dtype: int64
内部标识号    2570
交易次数        9
交易金额      743
Name: 2569, dtype: int64
内部标识号    2571
交易次数        1
交易金额     2073
Name: 2570, dtype: int64
内部标识号    2572
交易次数       17
交易金额     7451
Name: 2571, dtype: int64
内部标识号    2573
交易次数        2
交易金额      448
Name: 2572, dtype: int64
内部标识号    2574
交易次数        2
交易金额      632
Name: 2573, dtype: int64
内部标识号    2575
交易次数        3
交易金额      387
Name: 2574, dtype: int64
内部标识号    2576
交易次数        8
交易金额      790
Name: 2575, dtype: int64
内部标识号    2577
交易次数        8
交易金额      400
Name: 2576, dtype: int64
内部标识号    2578
交易次数       10
交易金额      528
Name: 2577, dtype: int64
内部标识号    2579
交易次数        6
交易金额      272
Name: 2578, dtype: int64
内部标识号    2580
交易次数        1
交易金额     5875
Name: 2579, dtype: int64
内部标识号    2581
交易次数        2
交易金额      903
Name: 2580, dtype: int64
内部标识号    2582
交易次数        2
交易金额      567
Name: 2581, dtype: int64
内部标识号    2583
交易次数       21
交易金额     6855
Name: 2582, dtype: int64
内部标识号    2584
交易次数        5
交易金额      179
Name: 2583, dtype: int64
内部标识号    2585
交易次数        8
交易金额      852
Name: 2584, dtype: int64
内部标识号    2586
交易次数        3
交易金额      106
Name: 2585, dtype: int64
内部标识号    2587
交易次数        1
交易金额      944
Name: 2586, dtype: int64
内部标识号     2588
交易次数         8
交易金额     77250
Name: 2587, dtype: int64
内部标识号    2589
交易次数        4
交易金额      170
Name: 2588, dtype: int64
内部标识号    2590
交易次数       13
交易金额      658
Name: 2589, dtype: int64
内部标识号    2591
交易次数        1
交易金额     3244
Name: 2590, dtype: int64
内部标识号    2592
交易次数        9
交易金额      569
Name: 2591, dtype: int64
内部标识号    2593
交易次数       19
交易金额      691
Name: 2592, dtype: int64
内部标识号     2594
交易次数         6
交易金额     35731
Name: 2593, dtype: int64
内部标识号    2595
交易次数        8
交易金额      169
Name: 2594, dtype: int64
内部标识号    2596
交易次数        0
交易金额     8126
Name: 2595, dtype: int64
内部标识号    2597
交易次数       14
交易金额      737
Name: 2596, dtype: int64
内部标识号    2598
交易次数        9
交易金额      679
Name: 2597, dtype: int64
内部标识号    2599
交易次数        3
交易金额      270
Name: 2598, dtype: int64
内部标识号    2600
交易次数        8
交易金额      138
Name: 2599, dtype: int64
内部标识号    2601
交易次数        4
交易金额      292
Name: 2600, dtype: int64
内部标识号    2602
交易次数        3
交易金额      315
Name: 2601, dtype: int64
内部标识号    2603
交易次数        8
交易金额      823
Name: 2602, dtype: int64
内部标识号    2604
交易次数        3
交易金额      255
Name: 2603, dtype: int64
内部标识号    2605
交易次数       12
交易金额      302
Name: 2604, dtype: int64
内部标识号    2606
交易次数        3
交易金额      485
Name: 2605, dtype: int64
内部标识号    2607
交易次数        0
交易金额     3132
Name: 2606, dtype: int64
内部标识号    2608
交易次数        0
交易金额     3450
Name: 2607, dtype: int64
内部标识号    2609
交易次数       12
交易金额      365
Name: 2608, dtype: int64
内部标识号    2610
交易次数        9
交易金额      907
Name: 2609, dtype: int64
内部标识号    2611
交易次数       10
交易金额      411
Name: 2610, dtype: int64
内部标识号    2612
交易次数        1
交易金额      536
Name: 2611, dtype: int64
内部标识号    2613
交易次数        3
交易金额      238
Name: 2612, dtype: int64
内部标识号    2614
交易次数        3
交易金额      455
Name: 2613, dtype: int64
内部标识号    2615
交易次数        2
交易金额      450
Name: 2614, dtype: int64
内部标识号    2616
交易次数       12
交易金额      484
Name: 2615, dtype: int64
内部标识号    2617
交易次数        1
交易金额     5278
Name: 2616, dtype: int64
内部标识号    2618
交易次数        3
交易金额      275
Name: 2617, dtype: int64
内部标识号    2619
交易次数       15
交易金额      676
Name: 2618, dtype: int64
内部标识号    2620
交易次数        0
交易金额     2080
Name: 2619, dtype: int64
内部标识号    2621
交易次数        5
交易金额      141
Name: 2620, dtype: int64
内部标识号    2622
交易次数       12
交易金额      346
Name: 2621, dtype: int64
内部标识号    2623
交易次数        3
交易金额      127
Name: 2622, dtype: int64
内部标识号    2624
交易次数        9
交易金额      837
Name: 2623, dtype: int64
内部标识号    2625
交易次数       17
交易金额      755
Name: 2624, dtype: int64
内部标识号    2626
交易次数        2
交易金额      869
Name: 2625, dtype: int64
内部标识号    2627
交易次数        4
交易金额      224
Name: 2626, dtype: int64
内部标识号    2628
交易次数        0
交易金额     7325
Name: 2627, dtype: int64
内部标识号    2629
交易次数        3
交易金额      131
Name: 2628, dtype: int64
内部标识号    2630
交易次数        2
交易金额      816
Name: 2629, dtype: int64
内部标识号    2631
交易次数        0
交易金额     1571
Name: 2630, dtype: int64
内部标识号    2632
交易次数        3
交易金额      203
Name: 2631, dtype: int64
内部标识号    2633
交易次数        0
交易金额     6637
Name: 2632, dtype: int64
内部标识号    2634
交易次数        2
交易金额      636
Name: 2633, dtype: int64
内部标识号    2635
交易次数        9
交易金额      780
Name: 2634, dtype: int64
内部标识号    2636
交易次数        7
交易金额      173
Name: 2635, dtype: int64
内部标识号    2637
交易次数       13
交易金额      805
Name: 2636, dtype: int64
内部标识号    2638
交易次数        1
交易金额      559
Name: 2637, dtype: int64
内部标识号    2639
交易次数        7
交易金额      181
Name: 2638, dtype: int64
内部标识号    2640
交易次数        3
交易金额      236
Name: 2639, dtype: int64
内部标识号    2641
交易次数        0
交易金额     6366
Name: 2640, dtype: int64
内部标识号    2642
交易次数        7
交易金额      205
Name: 2641, dtype: int64
内部标识号    2643
交易次数        1
交易金额      862
Name: 2642, dtype: int64
内部标识号    2644
交易次数        2
交易金额      853
Name: 2643, dtype: int64
内部标识号    2645
交易次数        1
交易金额      567
Name: 2644, dtype: int64
内部标识号    2646
交易次数        2
交易金额      760
Name: 2645, dtype: int64
内部标识号    2647
交易次数       11
交易金额      650
Name: 2646, dtype: int64
内部标识号    2648
交易次数        1
交易金额      932
Name: 2647, dtype: int64
内部标识号    2649
交易次数        8
交易金额      891
Name: 2648, dtype: int64
内部标识号    2650
交易次数       15
交易金额      822
Name: 2649, dtype: int64
内部标识号     2651
交易次数        53
交易金额     81688
Name: 2650, dtype: int64
内部标识号    2652
交易次数       15
交易金额      377
Name: 2651, dtype: int64
内部标识号    2653
交易次数        9
交易金额      456
Name: 2652, dtype: int64
内部标识号    2654
交易次数        2
交易金额      448
Name: 2653, dtype: int64
内部标识号    2655
交易次数        3
交易金额      302
Name: 2654, dtype: int64
内部标识号    2656
交易次数       12
交易金额      606
Name: 2655, dtype: int64
内部标识号    2657
交易次数       18
交易金额       10
Name: 2656, dtype: int64
内部标识号    2658
交易次数        2
交易金额      164
Name: 2657, dtype: int64
内部标识号    2659
交易次数       27
交易金额       81
Name: 2658, dtype: int64
内部标识号    2660
交易次数        8
交易金额      329
Name: 2659, dtype: int64
内部标识号    2661
交易次数       26
交易金额     3447
Name: 2660, dtype: int64
内部标识号    2662
交易次数        2
交易金额      418
Name: 2661, dtype: int64
内部标识号    2663
交易次数        2
交易金额      300
Name: 2662, dtype: int64
内部标识号    2664
交易次数       13
交易金额      510
Name: 2663, dtype: int64
内部标识号    2665
交易次数       13
交易金额      350
Name: 2664, dtype: int64
内部标识号    2666
交易次数       12
交易金额      654
Name: 2665, dtype: int64
内部标识号    2667
交易次数        8
交易金额      175
Name: 2666, dtype: int64
内部标识号    2668
交易次数        3
交易金额      369
Name: 2667, dtype: int64
内部标识号    2669
交易次数       24
交易金额     6648
Name: 2668, dtype: int64
内部标识号    2670
交易次数       14
交易金额      821
Name: 2669, dtype: int64
内部标识号    2671
交易次数       23
交易金额      826
Name: 2670, dtype: int64
内部标识号    2672
交易次数        4
交易金额      288
Name: 2671, dtype: int64
内部标识号    2673
交易次数       25
交易金额        3
Name: 2672, dtype: int64
内部标识号    2674
交易次数        3
交易金额      257
Name: 2673, dtype: int64
内部标识号    2675
交易次数        2
交易金额      492
Name: 2674, dtype: int64
内部标识号    2676
交易次数       17
交易金额     6006
Name: 2675, dtype: int64
内部标识号     2677
交易次数       139
交易金额     14358
Name: 2676, dtype: int64
内部标识号    2678
交易次数        3
交易金额      129
Name: 2677, dtype: int64
内部标识号    2679
交易次数        2
交易金额      777
Name: 2678, dtype: int64
内部标识号    2680
交易次数        2
交易金额      331
Name: 2679, dtype: int64
内部标识号     2681
交易次数         7
交易金额     87531
Name: 2680, dtype: int64
内部标识号    2682
交易次数        6
交易金额      292
Name: 2681, dtype: int64
内部标识号    2683
交易次数        3
交易金额      384
Name: 2682, dtype: int64
内部标识号    2684
交易次数        0
交易金额     8941
Name: 2683, dtype: int64
内部标识号     2685
交易次数       155
交易金额     69081
Name: 2684, dtype: int64
内部标识号    2686
交易次数       12
交易金额      334
Name: 2685, dtype: int64
内部标识号    2687
交易次数        6
交易金额      139
Name: 2686, dtype: int64
内部标识号    2688
交易次数       14
交易金额      541
Name: 2687, dtype: int64
内部标识号    2689
交易次数       12
交易金额      394
Name: 2688, dtype: int64
内部标识号    2690
交易次数        9
交易金额      549
Name: 2689, dtype: int64
内部标识号    2691
交易次数       15
交易金额     8613
Name: 2690, dtype: int64
内部标识号    2692
交易次数        1
交易金额      689
Name: 2691, dtype: int64
内部标识号    2693
交易次数        6
交易金额      196
Name: 2692, dtype: int64
内部标识号    2694
交易次数       19
交易金额     8734
Name: 2693, dtype: int64
内部标识号    2695
交易次数       14
交易金额      344
Name: 2694, dtype: int64
内部标识号    2696
交易次数        2
交易金额      349
Name: 2695, dtype: int64
内部标识号    2697
交易次数        9
交易金额      966
Name: 2696, dtype: int64
内部标识号    2698
交易次数        7
交易金额      214
Name: 2697, dtype: int64
内部标识号    2699
交易次数        2
交易金额      913
Name: 2698, dtype: int64
内部标识号     2700
交易次数         3
交易金额     28545
Name: 2699, dtype: int64
内部标识号    2701
交易次数        3
交易金额      394
Name: 2700, dtype: int64
内部标识号     2702
交易次数       151
交易金额     20327
Name: 2701, dtype: int64
内部标识号    2703
交易次数       13
交易金额      540
Name: 2702, dtype: int64
内部标识号    2704
交易次数        3
交易金额      404
Name: 2703, dtype: int64
内部标识号    2705
交易次数       10
交易金额      541
Name: 2704, dtype: int64
内部标识号    2706
交易次数       17
交易金额     1211
Name: 2705, dtype: int64
内部标识号    2707
交易次数        8
交易金额      624
Name: 2706, dtype: int64
内部标识号    2708
交易次数       15
交易金额      431
Name: 2707, dtype: int64
内部标识号    2709
交易次数        1
交易金额     9478
Name: 2708, dtype: int64
内部标识号    2710
交易次数        1
交易金额     9745
Name: 2709, dtype: int64
内部标识号    2711
交易次数        2
交易金额      250
Name: 2710, dtype: int64
内部标识号    2712
交易次数        2
交易金额      993
Name: 2711, dtype: int64
内部标识号    2713
交易次数       14
交易金额      934
Name: 2712, dtype: int64
内部标识号    2714
交易次数        2
交易金额      384
Name: 2713, dtype: int64
内部标识号    2715
交易次数        5
交易金额      213
Name: 2714, dtype: int64
内部标识号    2716
交易次数        1
交易金额     7861
Name: 2715, dtype: int64
内部标识号    2717
交易次数        3
交易金额      172
Name: 2716, dtype: int64
内部标识号    2718
交易次数        2
交易金额      819
Name: 2717, dtype: int64
内部标识号    2719
交易次数       15
交易金额      989
Name: 2718, dtype: int64
内部标识号    2720
交易次数        3
交易金额      445
Name: 2719, dtype: int64
内部标识号    2721
交易次数        9
交易金额      722
Name: 2720, dtype: int64
内部标识号    2722
交易次数       22
交易金额     4582

内部标识号    2774
交易次数       14
交易金额      681
Name: 2773, dtype: int64
内部标识号    2775
交易次数       13
交易金额      591
Name: 2774, dtype: int64
内部标识号    2776
交易次数        1
交易金额     3076
Name: 2775, dtype: int64
内部标识号    2777
交易次数        2
交易金额      726
Name: 2776, dtype: int64
内部标识号    2778
交易次数       12
交易金额      545
Name: 2777, dtype: int64
内部标识号    2779
交易次数        2
交易金额      450
Name: 2778, dtype: int64
内部标识号    2780
交易次数       26
交易金额     3013
Name: 2779, dtype: int64
内部标识号    2781
交易次数       15
交易金额      729
Name: 2780, dtype: int64
内部标识号    2782
交易次数       13
交易金额      795
Name: 2781, dtype: int64
内部标识号    2783
交易次数        2
交易金额      345
Name: 2782, dtype: int64
内部标识号    2784
交易次数       14
交易金额      815
Name: 2783, dtype: int64
内部标识号    2785
交易次数        2
交易金额      604
Name: 2784, dtype: int64
内部标识号    2786
交易次数        3
交易金额      117
Name: 2785, dtype: int64
内部标识号    2787
交易次数       22
交易金额     2255
Name: 2786, dtype: int64
内部标识号    2788
交易次数       15
交易金额      734
Name: 2787, dtype: int64
内部标识号    2789
交易次数        2
交易金额      337
Name: 2788, dtype: int64
内部标识号    2790
交易次数       15
交易金额      360
Name: 2789, dtype: int64
内部标识号    2791
交易次数        9
交易金额      869
Name: 2790, dtype: int64
内部标识号    2792
交易次数       10
交易金额      396
Name: 2791, dtype: int64
内部标识号    2793
交易次数        8
交易金额      296
Name: 2792, dtype: int64
内部标识号    2794
交易次数        7
交易金额      134
Name: 2793, dtype: int64
内部标识号    2795
交易次数        7
交易金额      148
Name: 2794, dtype: int64
内部标识号    2796
交易次数        2
交易金额      157
Name: 2795, dtype: int64
内部标识号    2797
交易次数       11
交易金额      532
Name: 2796, dtype: int64
内部标识号    2798
交易次数       15
交易金额      479
Name: 2797, dtype: int64
内部标识号    2799
交易次数       15
交易金额      792
Name: 2798, dtype: int64
内部标识号    2800
交易次数       26
交易金额     3477
Name: 2799, dtype: int64
内部标识号    2801
交易次数        9
交易金额      741
Name: 2800, dtype: int64
内部标识号    2802
交易次数        4
交易金额      256
Name: 2801, dtype: int64
内部标识号    2803
交易次数       25
交易金额      536
Name: 2802, dtype: int64
内部标识号    2804
交易次数        2
交易金额      185
Name: 2803, dtype: int64
内部标识号    2805
交易次数        7
交易金额      259
Name: 2804, dtype: int64
内部标识号    2806
交易次数        8
交易金额      163
Name: 2805, dtype: int64
内部标识号    2807
交易次数       11
交易金额      531
Name: 2806, dtype: int64
内部标识号    2808
交易次数        2
交易金额      141
Name: 2807, dtype: int64
内部标识号    2809
交易次数        8
交易金额      280
Name: 2808, dtype: int64
内部标识号    2810
交易次数       10
交易金额      564
Name: 2809, dtype: int64
内部标识号     2811
交易次数         7
交易金额     76546
Name: 2810, dtype: int64
内部标识号    2812
交易次数       14
交易金额      374
Name: 2811, dtype: int64
内部标识号    2813
交易次数        7
交易金额      247
Name: 2812, dtype: int64
内部标识号    2814
交易次数        0
交易金额     8426
Name: 2813, dtype: int64
内部标识号    2815
交易次数       14
交易金额      340
Name: 2814, dtype: int64
内部标识号    2816
交易次数        2
交易金额      522
Name: 2815, dtype: int64
内部标识号    2817
交易次数       14
交易金额      877
Name: 2816, dtype: int64
内部标识号    2818
交易次数        2
交易金额      302
Name: 2817, dtype: int64
内部标识号    2819
交易次数        3
交易金额      270
Name: 2818, dtype: int64
内部标识号    2820
交易次数        2
交易金额      699
Name: 2819, dtype: int64
内部标识号    2821
交易次数        2
交易金额      378
Name: 2820, dtype: int64
内部标识号    2822
交易次数        2
交易金额      612
Name: 2821, dtype: int64
内部标识号     2823
交易次数       273
交易金额     53827
Name: 2822, dtype: int64
内部标识号    2824
交易次数       13
交易金额      762
Name: 2823, dtype: int64
内部标识号    2825
交易次数        7
交易金额      245
Name: 2824, dtype: int64
内部标识号    2826
交易次数        2
交易金额      402
Name: 2825, dtype: int64
内部标识号    2827
交易次数       10
交易金额      579
Name: 2826, dtype: int64
内部标识号    2828
交易次数        1
交易金额      694
Name: 2827, dtype: int64
内部标识号    2829
交易次数       14
交易金额      440
Name: 2828, dtype: int64
内部标识号    2830
交易次数        0
交易金额     7067
Name: 2829, dtype: int64
内部标识号    2831
交易次数        0
交易金额     2744
Name: 2830, dtype: int64
内部标识号    2832
交易次数       11
交易金额      971
Name: 2831, dtype: int64
内部标识号    2833
交易次数        4
交易金额      202
Name: 2832, dtype: int64
内部标识号     2834
交易次数         5
交易金额     10468
Name: 2833, dtype: int64
内部标识号    2835
交易次数        4
交易金额      189
Name: 2834, dtype: int64
内部标识号    2836
交易次数       30
交易金额     9356
Name: 2835, dtype: int64
内部标识号    2837
交易次数       15
交易金额     7912
Name: 2836, dtype: int64
内部标识号     2838
交易次数         3
交易金额     18066
Name: 2837, dtype: int64
内部标识号    2839
交易次数       10
交易金额      891
Name: 2838, dtype: int64
内部标识号    2840
交易次数        1
交易金额      957
Name: 2839, dtype: int64
内部标识号    2841
交易次数        3
交易金额      471
Name: 2840, dtype: int64
内部标识号     2842
交易次数         6
交易金额     37376
Name: 2841, dtype: int64
内部标识号    2843
交易次数       17
交易金额      793
Name: 2842, dtype: int64
内部标识号    2844
交易次数       23
交易金额      678
Name: 2843, dtype: int64
内部标识号    2845
交易次数       20
交易金额      956
Name: 2844, dtype: int64
内部标识号    2846
交易次数        0
交易金额     9560
Name: 2845, dtype: int64
内部标识号    2847
交易次数        2
交易金额      375
Name: 2846, dtype: int64
内部标识号    2848
交易次数       13
交易金额      351
Name: 2847, dtype: int64
内部标识号    2849
交易次数       10
交易金额      494
Name: 2848, dtype: int64
内部标识号    2850
交易次数       12
交易金额      743
Name: 2849, dtype: int64
内部标识号    2851
交易次数        3
交易金额      475
Name: 2850, dtype: int64
内部标识号    2852
交易次数        2
交易金额      763
Name: 2851, dtype: int64
内部标识号    2853
交易次数        2
交易金额      460
Name: 2852, dtype: int64
内部标识号    2854
交易次数       20
交易金额     9498
Name: 2853, dtype: int64
内部标识号    2855
交易次数        2
交易金额      497
Name: 2854, dtype: int64
内部标识号     2856
交易次数       142
交易金额     23398
Name: 2855, dtype: int64
内部标识号    2857
交易次数        0
交易金额     5074
Name: 2856, dtype: int64
内部标识号    2858
交易次数       11
交易金额      389
Name: 2857, dtype: int64
内部标识号    2859
交易次数        1
交易金额      852
Name: 2858, dtype: int64
内部标识号    2860
交易次数        7
交易金额      196
Name: 2859, dtype: int64
内部标识号    2861
交易次数        8
交易金额      832
Name: 2860, dtype: int64
内部标识号    2862
交易次数       20
交易金额     5472
Name: 2861, dtype: int64
内部标识号    2863
交易次数        5
交易金额      252
Name: 2862, dtype: int64
内部标识号    2864
交易次数        4
交易金额      207
Name: 2863, dtype: int64
内部标识号     2865
交易次数       286
交易金额     13754
Name: 2864, dtype: int64
内部标识号    2866
交易次数        9
交易金额      972
Name: 2865, dtype: int64
内部标识号     2867
交易次数        82
交易金额     45596
Name: 2866, dtype: int64
内部标识号     2868
交易次数       215
交易金额     44135
Name: 2867, dtype: int64
内部标识号    2869
交易次数       13
交易金额      747
Name: 2868, dtype: int64
内部标识号    2870
交易次数       13
交易金额      957
Name: 2869, dtype: int64
内部标识号    2871
交易次数       18
交易金额     8039
Name: 2870, dtype: int64
内部标识号    2872
交易次数        5
交易金额      166
Name: 2871, dtype: int64
内部标识号    2873
交易次数       12
交易金额      709
Name: 2872, dtype: int64
内部标识号    2874
交易次数       11
交易金额      635
Name: 2873, dtype: int64
内部标识号    2875
交易次数        6
交易金额      106
Name: 2874, dtype: int64
内部标识号    2876
交易次数        2
交易金额      275
Name: 2875, dtype: int64
内部标识号    2877
交易次数       15
交易金额      964
Name: 2876, dtype: int64
内部标识号    2878
交易次数       25
交易金额      697
Name: 2877, dtype: int64
内部标识号     2879
交易次数         7
交易金额     11107
Name: 2878, dtype: int64
内部标识号    2880
交易次数        2
交易金额      578
Name: 2879, dtype: int64
内部标识号    2881
交易次数        0
交易金额     6562
Name: 2880, dtype: int64
内部标识号    2882
交易次数       28
交易金额       20
Name: 2881, dtype: int64
内部标识号    2883
交易次数        1
交易金额     6942
Name: 2882, dtype: int64
内部标识号    2884
交易次数        8
交易金额      512
Name: 2883, dtype: int64
内部标识号    2885
交易次数       13
交易金额      763
Name: 2884, dtype: int64
内部标识号    2886
交易次数       24
交易金额     4835
Name: 2885, dtype: int64
内部标识号    2887
交易次数        1
交易金额      790
Name: 2886, dtype: int64
内部标识号    2888
交易次数       17
交易金额      621
Name: 2887, dtype: int64
内部标识号    2889
交易次数        4
交易金额      130
Name: 2888, dtype: int64
内部标识号    2890
交易次数       26
交易金额     7778
Name: 2889, dtype: int64
内部标识号     2891
交易次数         5
交易金额     39091
Name: 2890, dtype: int64
内部标识号    2892
交易次数       15
交易金额      874
Name: 2891, dtype: int64
内部标识号     2893
交易次数       234
交易金额     63809
Name: 2892, dtype: int64
内部标识号    2894
交易次数       15
交易金额      321
Name: 2893, dtype: int64
内部标识号    2895
交易次数       14
交易金额      715
Name: 2894, dtype: int64
内部标识号    2896
交易次数        6
交易金额      274
Name: 2895, dtype: int64
内部标识号    2897
交易次数        8
交易金额      917
Name: 2896, dtype: int64
内部标识号    2898
交易次数       30
交易金额     8623
Name: 2897, dtype: int64
内部标识号    2899
交易次数       10
交易金额      829
Name: 2898, dtype: int64
内部标识号    2900
交易次数        8
交易金额      195
Name: 2899, dtype: int64
内部标识号    2901
交易次数       11
交易金额      315
Name: 2900, dtype: int64
内部标识号    2902
交易次数        2
交易金额      486
Name: 2901, dtype: int64
内部标识号    2903
交易次数        0
交易金额     8987
Name: 2902, dtype: int64
内部标识号    2904
交易次数       27
交易金额     8352
Name: 2903, dtype: int64
内部标识号    2905
交易次数       15
交易金额      870
Name: 2904, dtype: int64
内部标识号    2906
交易次数        1
交易金额      536
Name: 2905, dtype: int64
内部标识号     2907
交易次数         4
交易金额     48202
Name: 2906, dtype: int64
内部标识号    2908
交易次数        1
交易金额      878
Name: 2907, dtype: int64
内部标识号    2909
交易次数       16
交易金额      802
Name: 2908, dtype: int64
内部标识号    2910
交易次数        3
交易金额      246
Name: 2909, dtype: int64
内部标识号    2911
交易次数        6
交易金额      113
Name: 2910, dtype: int64
内部标识号     2912
交易次数         3
交易金额     52963
Name: 2911, dtype: int64
内部标识号    2913
交易次数       30
交易金额     7368
Name: 2912, dtype: int64
内部标识号    2914
交易次数        8
交易金额      173
Name: 2913, dtype: int64
内部标识号    2915
交易次数       25
交易金额      757
Name: 2914, dtype: int64
内部标识号    2916
交易次数       11
交易金额      605
Name: 2915, dtype: int64
内部标识号    2917
交易次数       15
交易金额      968
Name: 2916, dtype: int64
内部标识号     2918
交易次数       248
交易金额     11785
Name: 2917, dtype: int64
内部标识号    2919
交易次数        2
交易金额      409
Name: 2918, dtype: int64
内部标识号    2920
交易次数        0
交易金额     2026
Name: 2919, dtype: int64
内部标识号    2921
交易次数       19
交易金额     9710
Name: 2920, dtype: int64
内部标识号    2922
交易次数        2
交易金额      470
Name: 2921, dtype: int64
内部标识号    2923
交易次数       22
交易金额     1609
Name: 2922, dtype: int64
内部标识号    2924
交易次数        0
交易金额     8490
Name: 2923, dtype: int64
内部标识号    2925
交易次数        1
交易金额      818
Name: 2924, dtype: int64
内部标识号    2926
交易次数        1
交易金额      557
Name: 2925, dtype: int64
内部标识号    2927
交易次数       15
交易金额      345
Name: 2926, dtype: int64
内部标识号    2928
交易次数        4
交易金额      296
Name: 2927, dtype: int64
内部标识号    2929
交易次数       11
交易金额      928
Name: 2928, dtype: int64
内部标识号    2930
交易次数       13
交易金额      415
Name: 2929, dtype: int64
内部标识号    2931
交易次数        0
交易金额     2038
Name: 2930, dtype: int64
内部标识号    2932
交易次数        4
交易金额      207
Name: 2931, dtype: int64
内部标识号    2933
交易次数        1
交易金额      588
Name: 2932, dtype: int64
内部标识号    2934
交易次数       10
交易金额      435
Name: 2933, dtype: int64
内部标识号    2935
交易次数       28
交易金额     9551
Name: 2934, dtype: int64
内部标识号    2936
交易次数       10
交易金额      802
Name: 2935, dtype: int64
内部标识号    2937
交易次数        9
交易金额      629
Name: 2936, dtype: int64
内部标识号    2938
交易次数        2
交易金额      346
Name: 2937, dtype: int64
内部标识号     2939
交易次数         8
交易金额     90158
Name: 2938, dtype: int64
内部标识号    2940
交易次数        8
交易金额      696
Name: 2939, dtype: int64
内部标识号     2941
交易次数        54
交易金额     17977
Name: 2940, dtype: int64
内部标识号    2942
交易次数        6
交易金额      105
Name: 2941, dtype: int64
内部标识号    2943
交易次数       18
交易金额     7468
Name: 2942, dtype: int64
内部标识号     2944
交易次数         8
交易金额     30537
Name: 2943, dtype: int64
内部标识号    2945
交易次数        3
交易金额      458
Name: 2944, dtype: int64
内部标识号    2946
交易次数        3
交易金额      139
Name: 2945, dtype: int64
内部标识号    2947
交易次数       15
交易金额      407
Name: 2946, dtype: int64
内部标识号    2948
交易次数       11
交易金额      500
Name: 2947, dtype: int64
内部标识号    2949
交易次数        6
交易金额      170
Name: 2948, dtype: int64
内部标识号    2950
交易次数        0
交易金额     1979
Name: 2949, dtype: int64
内部标识号    2951
交易次数       28
交易金额      940
Name: 2950, dtype: int64
内部标识号     2952
交易次数         3
交易金额     88347
Name: 2951, dtype: int64
内部标识号    2953
交易次数       12
交易金额      873
Name: 2952, dtype: int64
内部标识号    2954
交易次数        1
交易金额      840
Name: 2953, dtype: int64
内部标识号    2955
交易次数        2
交易金额      398
Name: 2954, dtype: int64
内部标识号    2956
交易次数        1
交易金额     5675
Name: 2955, dtype: int64
内部标识号    2957
交易次数       30
交易金额     5493
Name: 2956, dtype: int64
内部标识号    2958
交易次数        2
交易金额      442
Name: 2957, dtype: int64
内部标识号    2959
交易次数       11
交易金额      901
Name: 2958, dtype: int64
内部标识号    2960
交易次数       24
交易金额     7824
Name: 2959, dtype: int64
内部标识号    2961
交易次数       12
交易金额      476
Name: 2960, dtype: int64
内部标识号    2962
交易次数        2
交易金额      623
Name: 2961, dtype: int64
内部标识号    2963
交易次数        2
交易金额      506
Name: 2962, dtype: int64
内部标识号    2964
交易次数       29
交易金额     3057
Name: 2963, dtype: int64
内部标识号    2965
交易次数        1
交易金额     7603
Name: 2964, dtype: int64
内部标识号    2966
交易次数        0
交易金额     7396
Name: 2965, dtype: int64
内部标识号    2967
交易次数       12
交易金额      619
Name: 2966, dtype: int64
内部标识号    2968
交易次数        6
交易金额      227
Name: 2967, dtype: int64
内部标识号    2969
交易次数        3
交易金额      199
Name: 2968, dtype: int64
内部标识号    2970
交易次数        2
交易金额      991
Name: 2969, dtype: int64
内部标识号    2971
交易次数       14
交易金额      995
Name: 2970, dtype: int64
内部标识号    2972
交易次数        1
交易金额      521
Name: 2971, dtype: int64
内部标识号     2973
交易次数        83
交易金额     34404
Name: 2972, dtype: int64
内部标识号    2974
交易次数        2
交易金额      194
Name: 2973, dtype: int64
内部标识号    2975
交易次数       25
交易金额      814
Name: 2974, dtype: int64
内部标识号    2976
交易次数       12
交易金额      619
Name: 2975, dtype: int64
内部标识号     2977
交易次数         8
交易金额     31039
Name: 2976, dtype: int64
内部标识号    2978
交易次数        2
交易金额      174
Name: 2977, dtype: int64
内部标识号    2979
交易次数        2
交易金额      796
Name: 2978, dtype: int64
内部标识号    2980
交易次数       19
交易金额     3084
Name: 2979, dtype: int64
内部标识号    2981
交易次数        7
交易金额      270
Name: 2980, dtype: int64
内部标识号    2982
交易次数        2
交易金额      773
Name: 2981, dtype: int64
内部标识号    2983
交易次数        9
交易金额      916
Name: 2982, dtype: int64
内部标识号    2984
交易次数        0
交易金额     8763
Name: 2983, dtype: int64
内部标识号    2985
交易次数        8
交易金额      206
Name: 2984, dtype: int64
内部标识号    2986
交易次数        1
交易金额      710
Name: 2985, dtype: int64
内部标识号    2987
交易次数        3
交易金额      274
Name: 2986, dtype: int64
内部标识号    2988
交易次数        0
交易金额     5229
Name: 2987, dtype: int64
内部标识号    2989
交易次数        3
交易金额      215
Name: 2988, dtype: int64
内部标识号    2990
交易次数        1
交易金额      901
Name: 2989, dtype: int64
内部标识号    2991
交易次数        0
交易金额     6849
Name: 2990, dtype: int64
内部标识号    2992
交易次数        2
交易金额      459
Name: 2991, dtype: int64
内部标识号    2993
交易次数       14
交易金额      589
Name: 2992, dtype: int64
内部标识号    2994
交易次数        8
交易金额      483
Name: 2993, dtype: int64
内部标识号     2995
交易次数         5
交易金额     82579
Name: 2994, dtype: int64
内部标识号    2996
交易次数       14
交易金额      588
Name: 2995, dtype: int64
内部标识号    2997
交易次数        7
交易金额      248
Name: 2996, dtype: int64
内部标识号    2998
交易次数        3
交易金额      325
Name: 2997, dtype: int64
内部标识号    2999
交易次数        2
交易金额      422
Name: 2998, dtype: int64
内部标识号    3000
交易次数       12
交易金额      417
Name: 2999, dtype: int64
内部标识号     3001
交易次数       281
交易金额     91456
Name: 3000, dtype: int64
内部标识号    3002
交易次数        2
交易金额      754
Name: 3001, dtype: int64
内部标识号    3003
交易次数       15
交易金额      620
Name: 3002, dtype: int64
内部标识号    3004
交易次数       14
交易金额      870
Name: 3003, dtype: int64
内部标识号    3005
交易次数        1
交易金额      750
Name: 3004, dtype: int64
内部标识号    3006
交易次数        3
交易金额      399
Name: 3005, dtype: int64
内部标识号    3007
交易次数        3
交易金额      211
Name: 3006, dtype: int64
内部标识号    3008
交易次数       15
交易金额      348
Name: 3007, dtype: int64
内部标识号    3009
交易次数        0
交易金额     8404
Name: 3008, dtype: int64
内部标识号    3010
交易次数        5
交易金额      270
Name: 3009, dtype: int64
内部标识号    3011
交易次数        1
交易金额      704
Name: 3010, dtype: int64
内部标识号    3012
交易次数       14
交易金额      460
Name: 3011, dtype: int64
内部标识号    3013
交易次数        2
交易金额      304
Name: 3012, dtype: int64
内部标识号    3014
交易次数        0
交易金额     6109
Name: 3013, dtype: int64
内部标识号    3015
交易次数        3
交易金额      377
Name: 3014, dtype: int64
内部标识号    3016
交易次数        1
交易金额      958
Name: 3015, dtype: int64
内部标识号    3017
交易次数        1
交易金额     2384
Name: 3016, dtype: int64
内部标识号    3018
交易次数        8
交易金额      531
Name: 3017, dtype: int64
内部标识号    3019
交易次数        9
交易金额      494
Name: 3018, dtype: int64
内部标识号    3020
交易次数        6
交易金额      223
Name: 3019, dtype: int64
内部标识号    3021
交易次数       15
交易金额      909
Name: 3020, dtype: int64
内部标识号    3022
交易次数        9
交易金额      716
Name: 3021, dtype: int64
内部标识号    3023
交易次数        1
交易金额      987
Name: 3022, dtype: int64
内部标识号    3024
交易次数        8
交易金额      236
Name: 3023, dtype: int64
内部标识号    3025
交易次数        0
交易金额     4699
Name: 3024, dtype: int64
内部标识号    3026
交易次数        0
交易金额     7499
Name: 3025, dtype: int64
内部标识号    3027
交易次数       15
交易金额      345
Name: 3026, dtype: int64
内部标识号    3028
交易次数        5
交易金额      156
Name: 3027, dtype: int64
内部标识号    3029
交易次数       10
交易金额      741
Name: 3028, dtype: int64
内部标识号    3030
交易次数        7
交易金额      206
Name: 3029, dtype: int64
内部标识号    3031
交易次数        7
交易金额      218
Name: 3030, dtype: int64
内部标识号    3032
交易次数        2
交易金额      570
Name: 3031, dtype: int64
内部标识号    3033
交易次数        5
交易金额      198
Name: 3032, dtype: int64
内部标识号    3034
交易次数       13
交易金额      524
Name: 3033, dtype: int64
内部标识号    3035
交易次数        0
交易金额     9167
Name: 3034, dtype: int64
内部标识号     3036
交易次数       194
交易金额     21698
Name: 3035, dtype: int64
内部标识号    3037
交易次数       11
交易金额      917
Name: 3036, dtype: int64
内部标识号    3038
交易次数        2
交易金额      638
Name: 3037, dtype: int64
内部标识号    3039
交易次数       13
交易金额      401
Name: 3038, dtype: int64
内部标识号    3040
交易次数       13
交易金额      410
Name: 3039, dtype: int64
内部标识号    3041
交易次数        2
交易金额      489
Name: 3040, dtype: int64
内部标识号     3042
交易次数         8
交易金额     60806
Name: 3041, dtype: int64
内部标识号    3043
交易次数        2
交易金额      475
Name: 3042, dtype: int64
内部标识号    3044
交易次数        5
交易金额      263
Name: 3043, dtype: int64
内部标识号    3045
交易次数        4
交易金额      121
Name: 3044, dtype: int64
内部标识号    3046
交易次数       16
交易金额     5805
Name: 3045, dtype: int64
内部标识号     3047
交易次数         8
交易金额     71510
Name: 3046, dtype: int64
内部标识号    3048
交易次数        0
交易金额     1922
Name: 3047, dtype: int64
内部标识号    3049
交易次数        2
交易金额      678
Name: 3048, dtype: int64
内部标识号    3050
交易次数        2
交易金额      801
Name: 3049, dtype: int64
内部标识号    3051
交易次数       14
交易金额      798
Name: 3050, dtype: int64
内部标识号    3052
交易次数       12
交易金额      408
Name: 3051, dtype: int64
内部标识号    3053
交易次数        7
交易金额      255
Name: 3052, dtype: int64
内部标识号    3054
交易次数        0
交易金额     1851
Name: 3053, dtype: int64
内部标识号    3055
交易次数        2
交易金额      315
Name: 3054, dtype: int64
内部标识号    3056
交易次数       30
交易金额     3734
Name: 3055, dtype: int64
内部标识号    3057
交易次数       15
交易金额      893
Name: 3056, dtype: int64
内部标识号     3058
交易次数       165
交易金额     26267
Name: 3057, dtype: int64
内部标识号     3059
交易次数       144
交易金额     34640
Name: 3058, dtype: int64
内部标识号     3060
交易次数         4
交易金额     10178
Name: 3059, dtype: int64
内部标识号    3061
交易次数        7
交易金额      159
Name: 3060, dtype: int64
内部标识号    3062
交易次数       27
交易金额      836
Name: 3061, dtype: int64
内部标识号     3063
交易次数         6
交易金额     49465
Name: 3062, dtype: int64
内部标识号    3064
交易次数        3
交易金额      258
Name: 3063, dtype: int64
内部标识号    3065
交易次数        3
交易金额      440
Name: 3064, dtype: int64
内部标识号    3066
交易次数       17
交易金额     4990
Name: 3065, dtype: int64
内部标识号    3067
交易次数       11
交易金额      577
Name: 3066, dtype: int64
内部标识号    3068
交易次数        9
交易金额     1000
Name: 3067, dtype: int64
内部标识号     3069
交易次数         7
交易金额     45674
Name: 3068, dtype: int64
内部标识号    3070
交易次数        8
交易金额      799
Name: 3069, dtype: int64

Name: 3151, dtype: int64
内部标识号    3153
交易次数        8
交易金额      268
Name: 3152, dtype: int64
内部标识号    3154
交易次数       24
交易金额      949
Name: 3153, dtype: int64
内部标识号    3155
交易次数       26
交易金额       82
Name: 3154, dtype: int64
内部标识号    3156
交易次数       11
交易金额      353
Name: 3155, dtype: int64
内部标识号    3157
交易次数       20
交易金额     1000
Name: 3156, dtype: int64
内部标识号    3158
交易次数        5
交易金额      109
Name: 3157, dtype: int64
内部标识号    3159
交易次数        8
交易金额      710
Name: 3158, dtype: int64
内部标识号    3160
交易次数        3
交易金额      446
Name: 3159, dtype: int64
内部标识号    3161
交易次数       13
交易金额      941
Name: 3160, dtype: int64
内部标识号    3162
交易次数        3
交易金额      496
Name: 3161, dtype: int64
内部标识号    3163
交易次数        1
交易金额      507
Name: 3162, dtype: int64
内部标识号    3164
交易次数        2
交易金额      639
Name: 3163, dtype: int64
内部标识号     3165
交易次数         3
交易金额     18964
Name: 3164, dtype: int64
内部标识号    3166
交易次数        8
交易金额      793
Name: 3165, dtype: int64
内部标识号    3167
交易次数        9
交易金额      520
Name: 3166, dtype: int64
内部标识号    3168
交易次数       27
交易金额      629
Name: 3167, dtype: int64
内部标识号    3169
交易次数       14
交易金额      923
Name: 3168, dtype: int64
内部标识号     3170
交易次数         6
交易金额     89210
Name: 3169, dtype: int64
内部标识号    3171
交易次数        3
交易金额      275
Name: 3170, dtype: int64
内部标识号    3172
交易次数        2
交易金额      367
Name: 3171, dtype: int64
内部标识号    3173
交易次数        2
交易金额      722
Name: 3172, dtype: int64
内部标识号    3174
交易次数        3
交易金额      317
Name: 3173, dtype: int64
内部标识号    3175
交易次数       14
交易金额      641
Name: 3174, dtype: int64
内部标识号    3176
交易次数        8
交易金额      183
Name: 3175, dtype: int64
内部标识号    3177
交易次数        5
交易金额      170
Name: 3176, dtype: int64
内部标识号    3178
交易次数        2
交易金额      748
Name: 3177, dtype: int64
内部标识号    3179
交易次数        3
交易金额      481
Name: 3178, dtype: int64
内部标识号    3180
交易次数       12
交易金额      798
Name: 3179, dtype: int64
内部标识号    3181
交易次数       10
交易金额      918
Name: 3180, dtype: int64
内部标识号    3182
交易次数        3
交易金额      431
Name: 3181, dtype: int64
内部标识号    3183
交易次数        6
交易金额      114
Name: 3182, dtype: int64
内部标识号    3184
交易次数        3
交易金额      319
Name: 3183, dtype: int64
内部标识号    3185
交易次数        9
交易金额      854
Name: 3184, dtype: int64
内部标识号    3186
交易次数        9
交易金额      695
Name: 3185, dtype: int64
内部标识号    3187
交易次数        4
交易金额      151
Name: 3186, dtype: int64
内部标识号    3188
交易次数        9
交易金额      956
Name: 3187, dtype: int64
内部标识号    3189
交易次数        3
交易金额      412
Name: 3188, dtype: int64
内部标识号    3190
交易次数        1
交易金额      750
Name: 3189, dtype: int64
内部标识号    3191
交易次数        8
交易金额      208
Name: 3190, dtype: int64
内部标识号    3192
交易次数        3
交易金额      234
Name: 3191, dtype: int64
内部标识号    3193
交易次数        9
交易金额      664
Name: 3192, dtype: int64
内部标识号    3194
交易次数       12
交易金额      668
Name: 3193, dtype: int64
内部标识号     3195
交易次数         7
交易金额     92829
Name: 3194, dtype: int64
内部标识号    3196
交易次数       23
交易金额     7825
Name: 3195, dtype: int64
内部标识号     3197
交易次数         8
交易金额     20828
Name: 3196, dtype: int64
内部标识号    3198
交易次数       11
交易金额      888
Name: 3197, dtype: int64
内部标识号    3199
交易次数        1
交易金额      966
Name: 3198, dtype: int64
内部标识号    3200
交易次数       17
交易金额        6
Name: 3199, dtype: int64
内部标识号    3201
交易次数       14
交易金额      582
Name: 3200, dtype: int64
内部标识号    3202
交易次数        3
交易金额      382
Name: 3201, dtype: int64
内部标识号     3203
交易次数        98
交易金额     68870
Name: 3202, dtype: int64
内部标识号     3204
交易次数         8
交易金额     45261
Name: 3203, dtype: int64
内部标识号    3205
交易次数       12
交易金额      435
Name: 3204, dtype: int64
内部标识号    3206
交易次数        9
交易金额      466
Name: 3205, dtype: int64
内部标识号    3207
交易次数       10
交易金额      415
Name: 3206, dtype: int64
内部标识号    3208
交易次数       13
交易金额      490
Name: 3207, dtype: int64
内部标识号     3209
交易次数         7
交易金额     71522
Name: 3208, dtype: int64
内部标识号    3210
交易次数        9
交易金额      792
Name: 3209, dtype: int64
内部标识号    3211
交易次数        1
交易金额      943
Name: 3210, dtype: int64
内部标识号    3212
交易次数        3
交易金额      340
Name: 3211, dtype: int64
内部标识号    3213
交易次数       13
交易金额      797
Name: 3212, dtype: int64
内部标识号    3214
交易次数        2
交易金额      209
Name: 3213, dtype: int64
内部标识号    3215
交易次数       30
交易金额     6522
Name: 3214, dtype: int64
内部标识号    3216
交易次数        2
交易金额      825
Name: 3215, dtype: int64
内部标识号    3217
交易次数        9
交易金额      837
Name: 3216, dtype: int64
内部标识号     3218
交易次数         6
交易金额     99401
Name: 3217, dtype: int64
内部标识号    3219
交易次数        2
交易金额      323
Name: 3218, dtype: int64
内部标识号    3220
交易次数        0
交易金额     2281
Name: 3219, dtype: int64
内部标识号    3221
交易次数        2
交易金额      412
Name: 3220, dtype: int64
内部标识号    3222
交易次数        3
交易金额      169
Name: 3221, dtype: int64
内部标识号    3223
交易次数       19
交易金额       95
Name: 3222, dtype: int64
内部标识号     3224
交易次数         7
交易金额     47778
Name: 3223, dtype: int64
内部标识号    3225
交易次数        1
交易金额      753
Name: 3224, dtype: int64
内部标识号    3226
交易次数        2
交易金额      311
Name: 3225, dtype: int64
内部标识号     3227
交易次数         5
交易金额     84843
Name: 3226, dtype: int64
内部标识号    3228
交易次数        0
交易金额     1000
Name: 3227, dtype: int64
内部标识号    3229
交易次数       11
交易金额      496
Name: 3228, dtype: int64
内部标识号    3230
交易次数        7
交易金额      149
Name: 3229, dtype: int64
内部标识号    3231
交易次数        3
交易金额      108
Name: 3230, dtype: int64
内部标识号    3232
交易次数       19
交易金额     1861
Name: 3231, dtype: int64
内部标识号    3233
交易次数       12
交易金额      489
Name: 3232, dtype: int64
内部标识号    3234
交易次数        8
交易金额      127
Name: 3233, dtype: int64
内部标识号    3235
交易次数       14
交易金额      698
Name: 3234, dtype: int64
内部标识号    3236
交易次数        3
交易金额      461
Name: 3235, dtype: int64
内部标识号    3237
交易次数        2
交易金额      752
Name: 3236, dtype: int64
内部标识号    3238
交易次数       11
交易金额      524
Name: 3237, dtype: int64
内部标识号    3239
交易次数        3
交易金额      111
Name: 3238, dtype: int64
内部标识号    3240
交易次数       27
交易金额     6141
Name: 3239, dtype: int64
内部标识号    3241
交易次数       13
交易金额      482
Name: 3240, dtype: int64
内部标识号    3242
交易次数       13
交易金额      468
Name: 3241, dtype: int64
内部标识号    3243
交易次数        9
交易金额      309
Name: 3242, dtype: int64
内部标识号    3244
交易次数        8
交易金额      806
Name: 3243, dtype: int64
内部标识号    3245
交易次数       14
交易金额      313
Name: 3244, dtype: int64
内部标识号    3246
交易次数        2
交易金额      344
Name: 3245, dtype: int64
内部标识号    3247
交易次数        8
交易金额      399
Name: 3246, dtype: int64
内部标识号    3248
交易次数        2
交易金额      530
Name: 3247, dtype: int64
内部标识号    3249
交易次数        2
交易金额      561
Name: 3248, dtype: int64
内部标识号    3250
交易次数        8
交易金额      455
Name: 3249, dtype: int64
内部标识号    3251
交易次数       10
交易金额      859
Name: 3250, dtype: int64
内部标识号    3252
交易次数       10
交易金额      755
Name: 3251, dtype: int64
内部标识号    3253
交易次数       27
交易金额     5121
Name: 3252, dtype: int64
内部标识号    3254
交易次数        0
交易金额     4768
Name: 3253, dtype: int64
内部标识号    3255
交易次数        8
交易金额      286
Name: 3254, dtype: int64
内部标识号    3256
交易次数       15
交易金额      549
Name: 3255, dtype: int64
内部标识号    3257
交易次数        3
交易金额      409
Name: 3256, dtype: int64
内部标识号    3258
交易次数       18
交易金额      962
Name: 3257, dtype: int64
内部标识号    3259
交易次数       27
交易金额     7527
Name: 3258, dtype: int64
内部标识号    3260
交易次数        8
交易金额      867
Name: 3259, dtype: int64
内部标识号    3261
交易次数        4
交易金额      161
Name: 3260, dtype: int64
内部标识号    3262
交易次数       13
交易金额      907
Name: 3261, dtype: int64
内部标识号    3263
交易次数        0
交易金额     2268
Name: 3262, dtype: int64
内部标识号    3264
交易次数       28
交易金额      638
Name: 3263, dtype: int64
内部标识号    3265
交易次数       30
交易金额     8669
Name: 3264, dtype: int64
内部标识号    3266
交易次数       10
交易金额      303
Name: 3265, dtype: int64
内部标识号    3267
交易次数       16
交易金额     8611
Name: 3266, dtype: int64
内部标识号    3268
交易次数        2
交易金额      440
Name: 3267, dtype: int64
内部标识号    3269
交易次数       13
交易金额      736
Name: 3268, dtype: int64
内部标识号    3270
交易次数       10
交易金额      575
Name: 3269, dtype: int64
内部标识号     3271
交易次数       104
交易金额     81211
Name: 3270, dtype: int64
内部标识号    3272
交易次数       15
交易金额      824
Name: 3271, dtype: int64
内部标识号    3273
交易次数       11
交易金额      746
Name: 3272, dtype: int64
内部标识号    3274
交易次数       24
交易金额     1308
Name: 3273, dtype: int64
内部标识号    3275
交易次数        2
交易金额      448
Name: 3274, dtype: int64
内部标识号    3276
交易次数       16
交易金额      502
Name: 3275, dtype: int64
内部标识号    3277
交易次数       15
交易金额      980
Name: 3276, dtype: int64
内部标识号     3278
交易次数         8
交易金额     21814
Name: 3277, dtype: int64
内部标识号    3279
交易次数       13
交易金额      612
Name: 3278, dtype: int64
内部标识号    3280
交易次数        6
交易金额      192
Name: 3279, dtype: int64
内部标识号    3281
交易次数        3
交易金额      250
Name: 3280, dtype: int64
内部标识号    3282
交易次数        6
交易金额      271
Name: 3281, dtype: int64
内部标识号    3283
交易次数       15
交易金额      740
Name: 3282, dtype: int64
内部标识号    3284
交易次数        4
交易金额      158
Name: 3283, dtype: int64
内部标识号    3285
交易次数        3
交易金额      139
Name: 3284, dtype: int64
内部标识号    3286
交易次数        3
交易金额      486
Name: 3285, dtype: int64
内部标识号    3287
交易次数       15
交易金额      384
Name: 3286, dtype: int64
内部标识号     3288
交易次数         3
交易金额     17175
Name: 3287, dtype: int64
内部标识号    3289
交易次数        1
交易金额     3967
Name: 3288, dtype: int64
内部标识号    3290
交易次数       16
交易金额     9656
Name: 3289, dtype: int64
内部标识号     3291
交易次数         4
交易金额     16373
Name: 3290, dtype: int64
内部标识号    3292
交易次数        8
交易金额      357
Name: 3291, dtype: int64
内部标识号    3293
交易次数        3
交易金额      457
Name: 3292, dtype: int64
内部标识号     3294
交易次数         6
交易金额     46483
Name: 3293, dtype: int64
内部标识号     3295
交易次数         8
交易金额     80473
Name: 3294, dtype: int64
内部标识号    3296
交易次数       12
交易金额      942
Name: 3295, dtype: int64
内部标识号    3297
交易次数        0
交易金额     6829
Name: 3296, dtype: int64
内部标识号    3298
交易次数        2
交易金额      731
Name: 3297, dtype: int64
内部标识号    3299
交易次数       19
交易金额     1954
Name: 3298, dtype: int64
内部标识号    3300
交易次数        1
交易金额     9855
Name: 3299, dtype: int64
内部标识号    3301
交易次数       15
交易金额      362
Name: 3300, dtype: int64
内部标识号    3302
交易次数        3
交易金额      115
Name: 3301, dtype: int64
内部标识号    3303
交易次数        4
交易金额      104
Name: 3302, dtype: int64
内部标识号    3304
交易次数       12
交易金额      374
Name: 3303, dtype: int64
内部标识号    3305
交易次数       11
交易金额      701
Name: 3304, dtype: int64
内部标识号    3306
交易次数        0
交易金额     1981
Name: 3305, dtype: int64
内部标识号     3307
交易次数        81
交易金额     64902
Name: 3306, dtype: int64
内部标识号    3308
交易次数       21
交易金额      862
Name: 3307, dtype: int64
内部标识号    3309
交易次数        8
交易金额      268
Name: 3308, dtype: int64
内部标识号    3310
交易次数       11
交易金额      511
Name: 3309, dtype: int64
内部标识号    3311
交易次数       10
交易金额      876
Name: 3310, dtype: int64
内部标识号    3312
交易次数       29
交易金额     7482
Name: 3311, dtype: int64
内部标识号    3313
交易次数        2
交易金额      687
Name: 3312, dtype: int64
内部标识号    3314
交易次数        4
交易金额      267
Name: 3313, dtype: int64
内部标识号    3315
交易次数       15
交易金额      701
Name: 3314, dtype: int64
内部标识号    3316
交易次数       11
交易金额      781
Name: 3315, dtype: int64
内部标识号    3317
交易次数        7
交易金额      161
Name: 3316, dtype: int64
内部标识号    3318
交易次数        3
交易金额      388
Name: 3317, dtype: int64
内部标识号    3319
交易次数       18
交易金额     3589
Name: 3318, dtype: int64
内部标识号    3320
交易次数       11
交易金额      835
Name: 3319, dtype: int64
内部标识号    3321
交易次数       10
交易金额      604
Name: 3320, dtype: int64
内部标识号    3322
交易次数       14
交易金额      493
Name: 3321, dtype: int64
内部标识号    3323
交易次数        2
交易金额      368
Name: 3322, dtype: int64
内部标识号    3324
交易次数       13
交易金额      302
Name: 3323, dtype: int64
内部标识号     3325
交易次数         4
交易金额     27758
Name: 3324, dtype: int64
内部标识号    3326
交易次数       25
交易金额     9743
Name: 3325, dtype: int64
内部标识号    3327
交易次数        1
交易金额      984
Name: 3326, dtype: int64
内部标识号    3328
交易次数        3
交易金额      235
Name: 3327, dtype: int64
内部标识号     3329
交易次数       269
交易金额     61438
Name: 3328, dtype: int64
内部标识号    3330
交易次数       12
交易金额      735
Name: 3329, dtype: int64
内部标识号    3331
交易次数        1
交易金额      979
Name: 3330, dtype: int64
内部标识号    3332
交易次数       14
交易金额      442
Name: 3331, dtype: int64
内部标识号    3333
交易次数        5
交易金额      116
Name: 3332, dtype: int64
内部标识号    3334
交易次数       12
交易金额      845
Name: 3333, dtype: int64
内部标识号    3335
交易次数       12
交易金额      630
Name: 3334, dtype: int64
内部标识号    3336
交易次数        7
交易金额      253
Name: 3335, dtype: int64
内部标识号     3337
交易次数       194
交易金额     69106
Name: 3336, dtype: int64
内部标识号    3338
交易次数       11
交易金额      651
Name: 3337, dtype: int64
内部标识号    3339
交易次数       25
交易金额     5877
Name: 3338, dtype: int64
内部标识号    3340
交易次数        7
交易金额      139
Name: 3339, dtype: int64
内部标识号    3341
交易次数       10
交易金额      632
Name: 3340, dtype: int64
内部标识号    3342
交易次数       11
交易金额      463
Name: 3341, dtype: int64
内部标识号    3343
交易次数       25
交易金额       71
Name: 3342, dtype: int64
内部标识号    3344
交易次数        8
交易金额      287
Name: 3343, dtype: int64
内部标识号    3345
交易次数       14
交易金额      867
Name: 3344, dtype: int64
内部标识号    3346
交易次数        2
交易金额      842
Name: 3345, dtype: int64
内部标识号    3347
交易次数        5
交易金额      217
Name: 3346, dtype: int64
内部标识号    3348
交易次数        3
交易金额      300
Name: 3347, dtype: int64
内部标识号    3349
交易次数        3
交易金额      345
Name: 3348, dtype: int64
内部标识号    3350
交易次数        1
交易金额      509
Name: 3349, dtype: int64
内部标识号    3351
交易次数        1
交易金额      928
Name: 3350, dtype: int64
内部标识号    3352
交易次数       10
交易金额      796
Name: 3351, dtype: int64
内部标识号    3353
交易次数        2
交易金额      742
Name: 3352, dtype: int64
内部标识号    3354
交易次数        4
交易金额      146
Name: 3353, dtype: int64
内部标识号    3355
交易次数       29
交易金额      675
Name: 3354, dtype: int64
内部标识号    3356
交易次数        2
交易金额      411
Name: 3355, dtype: int64
内部标识号    3357
交易次数       27
交易金额     3481
Name: 3356, dtype: int64
内部标识号    3358
交易次数        3
交易金额      285
Name: 3357, dtype: int64
内部标识号     3359
交易次数       184
交易金额     86178
Name: 3358, dtype: int64
内部标识号    3360
交易次数       13
交易金额      847
Name: 3359, dtype: int64
内部标识号    3361
交易次数       14
交易金额      746
Name: 3360, dtype: int64
内部标识号    3362
交易次数        1
交易金额      798
Name: 3361, dtype: int64
内部标识号    3363
交易次数       14
交易金额      803
Name: 3362, dtype: int64
内部标识号    3364
交易次数        3
交易金额      364
Name: 3363, dtype: int64
内部标识号    3365
交易次数        3
交易金额      429
Name: 3364, dtype: int64
内部标识号    3366
交易次数        2
交易金额      427
Name: 3365, dtype: int64
内部标识号    3367
交易次数        2
交易金额      505
Name: 3366, dtype: int64
内部标识号    3368
交易次数       15
交易金额      689
Name: 3367, dtype: int64
内部标识号    3369
交易次数        2
交易金额      392
Name: 3368, dtype: int64
内部标识号    3370
交易次数        8
交易金额      450
Name: 3369, dtype: int64
内部标识号    3371
交易次数       15
交易金额     3362
Name: 3370, dtype: int64
内部标识号    3372
交易次数        8
交易金额      864
Name: 3371, dtype: int64
内部标识号     3373
交易次数         8
交易金额     88472
Name: 3372, dtype: int64
内部标识号    3374
交易次数        7
交易金额      210
Name: 3373, dtype: int64
内部标识号    3375
交易次数        0
交易金额     2532
Name: 3374, dtype: int64
内部标识号    3376
交易次数       11
交易金额      305
Name: 3375, dtype: int64
内部标识号    3377
交易次数        3
交易金额      431
Name: 3376, dtype: int64
内部标识号    3378
交易次数        6
交易金额      223
Name: 3377, dtype: int64
内部标识号    3379
交易次数       13
交易金额      746

Name: 3378, dtype: int64
内部标识号    3380
交易次数       13
交易金额      340
Name: 3379, dtype: int64
内部标识号    3381
交易次数       11
交易金额      680
Name: 3380, dtype: int64
内部标识号     3382
交易次数         6
交易金额     95096
Name: 3381, dtype: int64
内部标识号    3383
交易次数        1
交易金额      711
Name: 3382, dtype: int64
内部标识号    3384
交易次数        6
交易金额      146
Name: 3383, dtype: int64
内部标识号    3385
交易次数       10
交易金额      797
Name: 3384, dtype: int64
内部标识号    3386
交易次数        6
交易金额      131
Name: 3385, dtype: int64
内部标识号    3387
交易次数       12
交易金额      761
Name: 3386, dtype: int64
内部标识号    3388
交易次数        3
交易金额      466
Name: 3387, dtype: int64
内部标识号    3389
交易次数       10
交易金额      848
Name: 3388, dtype: int64
内部标识号    3390
交易次数       14
交易金额      480
Name: 3389, dtype: int64
内部标识号    3391
交易次数        2
交易金额      558
Name: 3390, dtype: int64
内部标识号    3392
交易次数        3
交易金额      325
Name: 3391, dtype: int64
内部标识号    3393
交易次数        1
交易金额      827
Name: 3392, dtype: int64
内部标识号    3394
交易次数       12
交易金额      580
Name: 3393, dtype: int64
内部标识号    3395
交易次数       10
交易金额      467
Name: 3394, dtype: int64
内部标识号    3396
交易次数       14
交易金额      334
Name: 3395, dtype: int64
内部标识号    3397
交易次数        2
交易金额      813
Name: 3396, dtype: int64
内部标识号    3398
交易次数        7
交易金额      198
Name: 3397, dtype: int64
内部标识号    3399
交易次数        9
交易金额      507
Name: 3398, dtype: int64
内部标识号    3400
交易次数        8
交易金额      352
Name: 3399, dtype: int64
内部标识号    3401
交易次数        6
交易金额      262
Name: 3400, dtype: int64
内部标识号    3402
交易次数        2
交易金额      471
Name: 3401, dtype: int64
内部标识号    3403
交易次数        3
交易金额      167
Name: 3402, dtype: int64
内部标识号    3404
交易次数        0
交易金额     7928
Name: 3403, dtype: int64
内部标识号    3405
交易次数        1
交易金额     4722
Name: 3404, dtype: int64
内部标识号    3406
交易次数        6
交易金额      127
Name: 3405, dtype: int64
内部标识号    3407
交易次数        9
交易金额      816
Name: 3406, dtype: int64
内部标识号    3408
交易次数       30
交易金额     9924
Name: 3407, dtype: int64
内部标识号    3409
交易次数        2
交易金额      453
Name: 3408, dtype: int64
内部标识号    3410
交易次数        1
交易金额      738
Name: 3409, dtype: int64
内部标识号    3411
交易次数        0
交易金额     4144
Name: 3410, dtype: int64
内部标识号    3412
交易次数       15
交易金额      572
Name: 3411, dtype: int64
内部标识号    3413
交易次数       15
交易金额      737
Name: 3412, dtype: int64
内部标识号    3414
交易次数       30
交易金额      875
Name: 3413, dtype: int64
内部标识号    3415
交易次数       29
交易金额     3227
Name: 3414, dtype: int64
内部标识号    3416
交易次数        2
交易金额      412
Name: 3415, dtype: int64
内部标识号    3417
交易次数        3
交易金额      499
Name: 3416, dtype: int64
内部标识号    3418
交易次数        2
交易金额      404
Name: 3417, dtype: int64
内部标识号    3419
交易次数        0
交易金额     3574
Name: 3418, dtype: int64
内部标识号    3420
交易次数        4
交易金额      163
Name: 3419, dtype: int64
内部标识号    3421
交易次数       21
交易金额      607
Name: 3420, dtype: int64
内部标识号    3422
交易次数        2
交易金额      346
Name: 3421, dtype: int64
内部标识号    3423
交易次数       15
交易金额      687
Name: 3422, dtype: int64
内部标识号    3424
交易次数        2
交易金额      825
Name: 3423, dtype: int64
内部标识号    3425
交易次数       13
交易金额      794
Name: 3424, dtype: int64
内部标识号    3426
交易次数        5
交易金额      190
Name: 3425, dtype: int64
内部标识号     3427
交易次数         6
交易金额     43235
Name: 3426, dtype: int64
内部标识号    3428
交易次数        8
交易金额      563
Name: 3427, dtype: int64
内部标识号    3429
交易次数        3
交易金额      388
Name: 3428, dtype: int64
内部标识号    3430
交易次数        0
交易金额     2448
Name: 3429, dtype: int64
内部标识号    3431
交易次数       14
交易金额      834
Name: 3430, dtype: int64
内部标识号    3432
交易次数       19
交易金额     3867
Name: 3431, dtype: int64
内部标识号    3433
交易次数        9
交易金额      434
Name: 3432, dtype: int64
内部标识号    3434
交易次数        3
交易金额      484
Name: 3433, dtype: int64
内部标识号    3435
交易次数       14
交易金额      376
Name: 3434, dtype: int64
内部标识号    3436
交易次数       15
交易金额      386
Name: 3435, dtype: int64
内部标识号    3437
交易次数        2
交易金额      669
Name: 3436, dtype: int64
内部标识号    3438
交易次数        2
交易金额      379
Name: 3437, dtype: int64
内部标识号    3439
交易次数       20
交易金额      814
Name: 3438, dtype: int64
内部标识号    3440
交易次数        3
交易金额      140
Name: 3439, dtype: int64
内部标识号    3441
交易次数        0
交易金额     9033
Name: 3440, dtype: int64
内部标识号    3442
交易次数        5
交易金额      186
Name: 3441, dtype: int64
内部标识号    3443
交易次数        7
交易金额      222
Name: 3442, dtype: int64
内部标识号    3444
交易次数        9
交易金额      550
Name: 3443, dtype: int64
内部标识号    3445
交易次数        4
交易金额      114
Name: 3444, dtype: int64
内部标识号    3446
交易次数        8
交易金额      254
Name: 3445, dtype: int64
内部标识号    3447
交易次数        3
交易金额      171
Name: 3446, dtype: int64
内部标识号    3448
交易次数       13
交易金额      633
Name: 3447, dtype: int64
内部标识号    3449
交易次数        0
交易金额     3620
Name: 3448, dtype: int64
内部标识号    3450
交易次数        0
交易金额     9597
Name: 3449, dtype: int64
内部标识号    3451
交易次数        1
交易金额      887
Name: 3450, dtype: int64
内部标识号    3452
交易次数       14
交易金额      620
Name: 3451, dtype: int64
内部标识号     3453
交易次数       201
交易金额     94147
Name: 3452, dtype: int64
内部标识号    3454
交易次数        1
交易金额      845
Name: 3453, dtype: int64
内部标识号    3455
交易次数       10
交易金额      410
Name: 3454, dtype: int64
内部标识号    3456
交易次数       24
交易金额      510
Name: 3455, dtype: int64
内部标识号    3457
交易次数        5
交易金额      162
Name: 3456, dtype: int64
内部标识号    3458
交易次数        3
交易金额      340
Name: 3457, dtype: int64
内部标识号    3459
交易次数        2
交易金额      449
Name: 3458, dtype: int64
内部标识号    3460
交易次数        2
交易金额      109
Name: 3459, dtype: int64
内部标识号    3461
交易次数       23
交易金额     6692
Name: 3460, dtype: int64
内部标识号    3462
交易次数        2
交易金额      488
Name: 3461, dtype: int64
内部标识号    3463
交易次数        7
交易金额      173
Name: 3462, dtype: int64
内部标识号    3464
交易次数        0
交易金额     7010
Name: 3463, dtype: int64
内部标识号    3465
交易次数       17
交易金额      879
Name: 3464, dtype: int64
内部标识号    3466
交易次数        7
交易金额      241
Name: 3465, dtype: int64
内部标识号    3467
交易次数        3
交易金额      393
Name: 3466, dtype: int64
内部标识号    3468
交易次数        3
交易金额      250
Name: 3467, dtype: int64
内部标识号    3469
交易次数        2
交易金额      497
Name: 3468, dtype: int64
内部标识号     3470
交易次数         4
交易金额     26828
Name: 3469, dtype: int64
内部标识号    3471
交易次数       13
交易金额      406
Name: 3470, dtype: int64
内部标识号    3472
交易次数        2
交易金额      199
Name: 3471, dtype: int64
内部标识号    3473
交易次数        8
交易金额      793
Name: 3472, dtype: int64
内部标识号    3474
交易次数       16
交易金额     1982
Name: 3473, dtype: int64
内部标识号    3475
交易次数        2
交易金额      856
Name: 3474, dtype: int64
内部标识号     3476
交易次数         4
交易金额     85406
Name: 3475, dtype: int64
内部标识号    3477
交易次数        6
交易金额      286
Name: 3476, dtype: int64
内部标识号    3478
交易次数       24
交易金额      770
Name: 3477, dtype: int64
内部标识号    3479
交易次数       20
交易金额     1392
Name: 3478, dtype: int64
内部标识号    3480
交易次数        3
交易金额      450
Name: 3479, dtype: int64
内部标识号    3481
交易次数        4
交易金额      125
Name: 3480, dtype: int64
内部标识号    3482
交易次数       14
交易金额      950
Name: 3481, dtype: int64
内部标识号    3483
交易次数        7
交易金额      134
Name: 3482, dtype: int64
内部标识号    3484
交易次数        8
交易金额      998
Name: 3483, dtype: int64
内部标识号    3485
交易次数        9
交易金额      895
Name: 3484, dtype: int64
内部标识号    3486
交易次数        2
交易金额      246
Name: 3485, dtype: int64
内部标识号    3487
交易次数        3
交易金额      378
Name: 3486, dtype: int64
内部标识号    3488
交易次数       17
交易金额     1196
Name: 3487, dtype: int64
内部标识号    3489
交易次数        8
交易金额      287
Name: 3488, dtype: int64
内部标识号    3490
交易次数        7
交易金额      266
Name: 3489, dtype: int64
内部标识号    3491
交易次数       10
交易金额      406
Name: 3490, dtype: int64
内部标识号    3492
交易次数        2
交易金额      506
Name: 3491, dtype: int64
内部标识号    3493
交易次数        9
交易金额      722
Name: 3492, dtype: int64
内部标识号    3494
交易次数       27
交易金额     9710
Name: 3493, dtype: int64
内部标识号    3495
交易次数        2
交易金额      500
Name: 3494, dtype: int64
内部标识号    3496
交易次数        0
交易金额     4879
Name: 3495, dtype: int64
内部标识号    3497
交易次数        6
交易金额      253
Name: 3496, dtype: int64
内部标识号     3498
交易次数         8
交易金额     80677
Name: 3497, dtype: int64
内部标识号    3499
交易次数       15
交易金额      338
Name: 3498, dtype: int64
内部标识号    3500
交易次数        8
交易金额      154
Name: 3499, dtype: int64
内部标识号    3501
交易次数        3
交易金额      374
Name: 3500, dtype: int64
内部标识号    3502
交易次数        3
交易金额      302
Name: 3501, dtype: int64
内部标识号    3503
交易次数        2
交易金额      931
Name: 3502, dtype: int64
内部标识号    3504
交易次数        3
交易金额      445
Name: 3503, dtype: int64
内部标识号    3505
交易次数        3
交易金额      348
Name: 3504, dtype: int64
内部标识号    3506
交易次数       12
交易金额      794
Name: 3505, dtype: int64
内部标识号    3507
交易次数       11
交易金额      443
Name: 3506, dtype: int64
内部标识号    3508
交易次数        2
交易金额      736
Name: 3507, dtype: int64
内部标识号    3509
交易次数        9
交易金额      495
Name: 3508, dtype: int64
内部标识号    3510
交易次数        7
交易金额      149
Name: 3509, dtype: int64
内部标识号    3511
交易次数       10
交易金额      487
Name: 3510, dtype: int64
内部标识号     3512
交易次数        44
交易金额     56638
Name: 3511, dtype: int64
内部标识号    3513
交易次数        3
交易金额      195
Name: 3512, dtype: int64
内部标识号    3514
交易次数        7
交易金额      298
Name: 3513, dtype: int64
内部标识号    3515
交易次数       12
交易金额      740
Name: 3514, dtype: int64
内部标识号    3516
交易次数        1
交易金额      535
Name: 3515, dtype: int64
内部标识号    3517
交易次数        1
交易金额      886
Name: 3516, dtype: int64
内部标识号    3518
交易次数       23
交易金额     4162
Name: 3517, dtype: int64
内部标识号    3519
交易次数        0
交易金额     9169
Name: 3518, dtype: int64
内部标识号    3520
交易次数        2
交易金额      345
Name: 3519, dtype: int64
内部标识号    3521
交易次数        1
交易金额     6623
Name: 3520, dtype: int64
内部标识号    3522
交易次数        1
交易金额     6993
Name: 3521, dtype: int64
内部标识号    3523
交易次数        3
交易金额      362
Name: 3522, dtype: int64
内部标识号    3524
交易次数       12
交易金额      759
Name: 3523, dtype: int64
内部标识号    3525
交易次数        5
交易金额      203
Name: 3524, dtype: int64
内部标识号    3526
交易次数        2
交易金额      701
Name: 3525, dtype: int64
内部标识号    3527
交易次数        0
交易金额     1930
Name: 3526, dtype: int64
内部标识号    3528
交易次数        6
交易金额      287
Name: 3527, dtype: int64
内部标识号    3529
交易次数        3
交易金额      200
Name: 3528, dtype: int64
内部标识号    3530
交易次数        9
交易金额      469
Name: 3529, dtype: int64
内部标识号    3531
交易次数        2
交易金额      410
Name: 3530, dtype: int64
内部标识号    3532
交易次数        8
交易金额      265
Name: 3531, dtype: int64
内部标识号    3533
交易次数       16
交易金额      609
Name: 3532, dtype: int64
内部标识号     3534
交易次数         7
交易金额     12881
Name: 3533, dtype: int64
内部标识号     3535
交易次数         6
交易金额     64160
Name: 3534, dtype: int64
内部标识号    3536
交易次数       15
交易金额      486
Name: 3535, dtype: int64
内部标识号    3537
交易次数        3
交易金额      346
Name: 3536, dtype: int64
内部标识号    3538
交易次数        0
交易金额     4004
Name: 3537, dtype: int64
内部标识号    3539
交易次数       11
交易金额      695
Name: 3538, dtype: int64
内部标识号    3540
交易次数       13
交易金额      810
Name: 3539, dtype: int64
内部标识号    3541
交易次数        1
交易金额     4951
Name: 3540, dtype: int64
内部标识号    3542
交易次数        6
交易金额      172
Name: 3541, dtype: int64
内部标识号    3543
交易次数       10
交易金额      368
Name: 3542, dtype: int64
内部标识号    3544
交易次数        1
交易金额     4223
Name: 3543, dtype: int64
内部标识号    3545
交易次数       13
交易金额      403
Name: 3544, dtype: int64
内部标识号    3546
交易次数       23
交易金额      704
Name: 3545, dtype: int64
内部标识号    3547
交易次数        3
交易金额      195
Name: 3546, dtype: int64
内部标识号    3548
交易次数        2
交易金额      377
Name: 3547, dtype: int64
内部标识号    3549
交易次数       29
交易金额     2996
Name: 3548, dtype: int64
内部标识号    3550
交易次数        3
交易金额      118
Name: 3549, dtype: int64
内部标识号    3551
交易次数        3
交易金额      207
Name: 3550, dtype: int64
内部标识号    3552
交易次数        9
交易金额      583
Name: 3551, dtype: int64
内部标识号    3553
交易次数        2
交易金额      817
Name: 3552, dtype: int64
内部标识号    3554
交易次数       19
交易金额     3652
Name: 3553, dtype: int64
内部标识号    3555
交易次数       13
交易金额      813
Name: 3554, dtype: int64
内部标识号    3556
交易次数        7
交易金额      214
Name: 3555, dtype: int64
内部标识号    3557
交易次数       11
交易金额      932
Name: 3556, dtype: int64
内部标识号    3558
交易次数        2
交易金额      989
Name: 3557, dtype: int64
内部标识号    3559
交易次数        0
交易金额     9942
Name: 3558, dtype: int64
内部标识号    3560
交易次数       12
交易金额      467
Name: 3559, dtype: int64
内部标识号    3561
交易次数        2
交易金额      898
Name: 3560, dtype: int64
内部标识号     3562
交易次数       128
交易金额     47164
Name: 3561, dtype: int64
内部标识号    3563
交易次数       30
交易金额      863
Name: 3562, dtype: int64
内部标识号    3564
交易次数       12
交易金额      592
Name: 3563, dtype: int64
内部标识号    3565
交易次数        9
交易金额      547
Name: 3564, dtype: int64
内部标识号    3566
交易次数       13
交易金额      460
Name: 3565, dtype: int64
内部标识号    3567
交易次数        3
交易金额      426
Name: 3566, dtype: int64
内部标识号    3568
交易次数       12
交易金额      774
Name: 3567, dtype: int64
内部标识号    3569
交易次数        1
交易金额      997
Name: 3568, dtype: int64
内部标识号    3570
交易次数        6
交易金额      297
Name: 3569, dtype: int64
内部标识号    3571
交易次数        3
交易金额      421
Name: 3570, dtype: int64
内部标识号    3572
交易次数        2
交易金额      909
Name: 3571, dtype: int64
内部标识号    3573
交易次数       21
交易金额     1037
Name: 3572, dtype: int64
内部标识号    3574
交易次数        1
交易金额      722
Name: 3573, dtype: int64
内部标识号    3575
交易次数       10
交易金额      374
Name: 3574, dtype: int64
内部标识号     3576
交易次数       278
交易金额     14264
Name: 3575, dtype: int64
内部标识号    3577
交易次数       15
交易金额      380
Name: 3576, dtype: int64
内部标识号    3578
交易次数       18
交易金额      993
Name: 3577, dtype: int64
内部标识号    3579
交易次数       14
交易金额      513
Name: 3578, dtype: int64
内部标识号    3580
交易次数        2
交易金额      500
Name: 3579, dtype: int64
内部标识号    3581
交易次数       25
交易金额      884
Name: 3580, dtype: int64
内部标识号    3582
交易次数       14
交易金额      847
Name: 3581, dtype: int64
内部标识号    3583
交易次数       12
交易金额      822
Name: 3582, dtype: int64
内部标识号    3584
交易次数        8
交易金额      271
Name: 3583, dtype: int64
内部标识号    3585
交易次数        0
交易金额     8316
Name: 3584, dtype: int64
内部标识号    3586
交易次数        8
交易金额      253
Name: 3585, dtype: int64
内部标识号    3587
交易次数        8
交易金额      278
Name: 3586, dtype: int64
内部标识号    3588
交易次数        1
交易金额      590
Name: 3587, dtype: int64
内部标识号    3589
交易次数        3
交易金额      455
Name: 3588, dtype: int64
内部标识号    3590
交易次数        9
交易金额      937
Name: 3589, dtype: int64
内部标识号    3591
交易次数       12
交易金额      972
Name: 3590, dtype: int64
内部标识号    3592
交易次数        3
交易金额      190
Name: 3591, dtype: int64
内部标识号    3593
交易次数       15
交易金额      922
Name: 3592, dtype: int64
内部标识号    3594
交易次数        3
交易金额      259
Name: 3593, dtype: int64
内部标识号    3595
交易次数        2
交易金额      303
Name: 3594, dtype: int64
内部标识号    3596
交易次数        2
交易金额      371
Name: 3595, dtype: int64
内部标识号     3597
交易次数         7
交易金额     38135
Name: 3596, dtype: int64
内部标识号    3598
交易次数        6
交易金额      214
Name: 3597, dtype: int64
内部标识号    3599
交易次数        2
交易金额      336
Name: 3598, dtype: int64
内部标识号    3600
交易次数        8
交易金额      641
Name: 3599, dtype: int64
内部标识号     3601
交易次数         5
交易金额     55297
Name: 3600, dtype: int64
内部标识号    3602
交易次数       10
交易金额      370
Name: 3601, dtype: int64
内部标识号    3603
交易次数        3
交易金额      500
Name: 3602, dtype: int64
内部标识号    3604
交易次数        2
交易金额      331
Name: 3603, dtype: int64
内部标识号    3605
交易次数        8
交易金额      966
Name: 3604, dtype: int64
内部标识号    3606
交易次数        0
交易金额     7314
Name: 3605, dtype: int64
内部标识号    3607
交易次数       12
交易金额      826
Name: 3606, dtype: int64
内部标识号    3608
交易次数       10
交易金额      819
Name: 3607, dtype: int64
内部标识号     3609
交易次数         6
交易金额     33291
Name: 3608, dtype: int64
内部标识号    3610
交易次数        1
交易金额     4434
Name: 3609, dtype: int64
内部标识号    3611
交易次数       12
交易金额      715
Name: 3610, dtype: int64
内部标识号    3612
交易次数        2
交易金额      310
Name: 3611, dtype: int64
内部标识号    3613
交易次数        3
交易金额      469
Name: 3612, dtype: int64
内部标识号    3614
交易次数       22
交易金额     4922
Name: 3613, dtype: int64
内部标识号    3615
交易次数        6
交易金额      255
Name: 3614, dtype: int64
内部标识号    3616
交易次数       11
交易金额      801
Name: 3615, dtype: int64
内部标识号    3617
交易次数       13
交易金额      357
Name: 3616, dtype: int64
内部标识号    3618
交易次数       12
交易金额      388
Name: 3617, dtype: int64
内部标识号     3619
交易次数       126
交易金额     98278
Name: 3618, dtype: int64
内部标识号    3620
交易次数        1
交易金额      598
Name: 3619, dtype: int64
内部标识号    3621
交易次数       14
交易金额      975
Name: 3620, dtype: int64
内部标识号     3622
交易次数       233
交易金额     19972
Name: 3621, dtype: int64
内部标识号    3623
交易次数        2
交易金额      510
Name: 3622, dtype: int64
内部标识号    3624
交易次数       14
交易金额      322
Name: 3623, dtype: int64
内部标识号    3625
交易次数       14
交易金额      364
Name: 3624, dtype: int64
内部标识号    3626
交易次数       15
交易金额      307
Name: 3625, dtype: int64
内部标识号    3627
交易次数        2
交易金额      521
Name: 3626, dtype: int64
内部标识号    3628
交易次数        6
交易金额      104
Name: 3627, dtype: int64
内部标识号    3629
交易次数        5
交易金额      267
Name: 3628, dtype: int64
内部标识号    3630
交易次数        2
交易金额      750
Name: 3629, dtype: int64
内部标识号    3631
交易次数        4
交易金额      243
Name: 3630, dtype: int64
内部标识号    3632
交易次数        3
交易金额      276
Name: 3631, dtype: int64
内部标识号    3633
交易次数        3
交易金额      131
Name: 3632, dtype: int64
内部标识号    3634
交易次数        8
交易金额      151
Name: 3633, dtype: int64
内部标识号    3635
交易次数       12
交易金额      361
Name: 3634, dtype: int64
内部标识号    3636
交易次数        2
交易金额      484
Name: 3635, dtype: int64
内部标识号    3637
交易次数        2
交易金额      470
Name: 3636, dtype: int64
内部标识号    3638
交易次数        4
交易金额      211
Name: 3637, dtype: int64
内部标识号    3639
交易次数       16
交易金额     7455
Name: 3638, dtype: int64
内部标识号    3640
交易次数       18
交易金额     4448
Name: 3639, dtype: int64
内部标识号    3641
交易次数        8
交易金额      518
Name: 3640, dtype: int64
内部标识号    3642
交易次数        2
交易金额      425
Name: 3641, dtype: int64
内部标识号    3643
交易次数       14
交易金额      798
Name: 3642, dtype: int64
内部标识号    3644
交易次数        2
交易金额      351
Name: 3643, dtype: int64
内部标识号    3645
交易次数       10
交易金额      680
Name: 3644, dtype: int64
内部标识号    3646
交易次数       12
交易金额      457
Name: 3645, dtype: int64
内部标识号    3647
交易次数        2
交易金额      937
Name: 3646, dtype: int64
内部标识号    3648
交易次数       20
交易金额       14
Name: 3647, dtype: int64
内部标识号    3649
交易次数       12
交易金额      539
Name: 3648, dtype: int64
内部标识号    3650
交易次数        4
交易金额      183
Name: 3649, dtype: int64
内部标识号    3651
交易次数        0
交易金额     6055
Name: 3650, dtype: int64
内部标识号    3652
交易次数       22
交易金额     3736
Name: 3651, dtype: int64
内部标识号    3653
交易次数       14
交易金额      356
Name: 3652, dtype: int64
内部标识号    3654
交易次数        2
交易金额      438
Name: 3653, dtype: int64
内部标识号    3655
交易次数        9
交易金额      573
Name: 3654, dtype: int64
内部标识号    3656
交易次数       15
交易金额      951
Name: 3655, dtype: int64
内部标识号    3657
交易次数        1
交易金额      685
Name: 3656, dtype: int64
内部标识号    3658
交易次数       15
交易金额     1077
Name: 3657, dtype: int64
内部标识号     3659
交易次数       127
交易金额     47396
Name: 3658, dtype: int64
内部标识号    3660
交易次数       12
交易金额      391
Name: 3659, dtype: int64
内部标识号    3661
交易次数        3
交易金额      498
Name: 3660, dtype: int64
内部标识号    3662
交易次数       14
交易金额      937
Name: 3661, dtype: int64
内部标识号    3663
交易次数       25
交易金额     6981
Name: 3662, dtype: int64
内部标识号    3664
交易次数       10
交易金额      306
Name: 3663, dtype: int64
内部标识号    3665
交易次数        5
交易金额      273
Name: 3664, dtype: int64
内部标识号    3666
交易次数        0
交易金额     8389
Name: 3665, dtype: int64
内部标识号    3667
交易次数        1
交易金额     6103
Name: 3666, dtype: int64
内部标识号    3668
交易次数        3
交易金额      485
Name: 3667, dtype: int64
内部标识号    3669
交易次数        3
交易金额      316
Name: 3668, dtype: int64
内部标识号    3670
交易次数       24
交易金额     8439
Name: 3669, dtype: int64
内部标识号    3671
交易次数        3
交易金额      284
Name: 3670, dtype: int64
内部标识号    3672
交易次数       26
交易金额       96
Name: 3671, dtype: int64
内部标识号    3673
交易次数       12
交易金额      660
Name: 3672, dtype: int64
内部标识号     3674
交易次数       118
交易金额     95113
Name: 3673, dtype: int64
内部标识号    3675
交易次数        5
交易金额      248
Name: 3674, dtype: int64
内部标识号    3676
交易次数        3
交易金额      432
Name: 3675, dtype: int64
内部标识号    3677

Name: 3771, dtype: int64
内部标识号    3773
交易次数        2
交易金额      374
Name: 3772, dtype: int64
内部标识号    3774
交易次数        3
交易金额      352
Name: 3773, dtype: int64
内部标识号    3775
交易次数       10
交易金额      905
Name: 3774, dtype: int64
内部标识号    3776
交易次数       11
交易金额      687
Name: 3775, dtype: int64
内部标识号     3777
交易次数         6
交易金额     19520
Name: 3776, dtype: int64
内部标识号    3778
交易次数        2
交易金额      464
Name: 3777, dtype: int64
内部标识号    3779
交易次数        2
交易金额      293
Name: 3778, dtype: int64
内部标识号    3780
交易次数       10
交易金额      347
Name: 3779, dtype: int64
内部标识号    3781
交易次数        1
交易金额     4217
Name: 3780, dtype: int64
内部标识号    3782
交易次数       24
交易金额      701
Name: 3781, dtype: int64
内部标识号    3783
交易次数       12
交易金额      935
Name: 3782, dtype: int64
内部标识号    3784
交易次数       12
交易金额      592
Name: 3783, dtype: int64
内部标识号    3785
交易次数        3
交易金额      228
Name: 3784, dtype: int64
内部标识号    3786
交易次数        5
交易金额      224
Name: 3785, dtype: int64
内部标识号    3787
交易次数       10
交易金额      349
Name: 3786, dtype: int64
内部标识号    3788
交易次数        1
交易金额      549
Name: 3787, dtype: int64
内部标识号    3789
交易次数        0
交易金额     4369
Name: 3788, dtype: int64
内部标识号    3790
交易次数        9
交易金额      639
Name: 3789, dtype: int64
内部标识号    3791
交易次数       21
交易金额      685
Name: 3790, dtype: int64
内部标识号    3792
交易次数       13
交易金额      822
Name: 3791, dtype: int64
内部标识号    3793
交易次数       10
交易金额      413
Name: 3792, dtype: int64
内部标识号    3794
交易次数       13
交易金额      872
Name: 3793, dtype: int64
内部标识号    3795
交易次数        9
交易金额      832
Name: 3794, dtype: int64
内部标识号    3796
交易次数       25
交易金额     1578
Name: 3795, dtype: int64
内部标识号    3797
交易次数       11
交易金额      891
Name: 3796, dtype: int64
内部标识号    3798
交易次数       11
交易金额      420
Name: 3797, dtype: int64
内部标识号    3799
交易次数       13
交易金额      426
Name: 3798, dtype: int64
内部标识号    3800
交易次数        7
交易金额      201
Name: 3799, dtype: int64
内部标识号    3801
交易次数       11
交易金额      765
Name: 3800, dtype: int64
内部标识号    3802
交易次数       18
交易金额      553
Name: 3801, dtype: int64
内部标识号    3803
交易次数        9
交易金额      371
Name: 3802, dtype: int64
内部标识号    3804
交易次数       12
交易金额      468
Name: 3803, dtype: int64
内部标识号     3805
交易次数       135
交易金额     12386
Name: 3804, dtype: int64
内部标识号    3806
交易次数        9
交易金额      844
Name: 3805, dtype: int64
内部标识号    3807
交易次数        0
交易金额     2290
Name: 3806, dtype: int64
内部标识号    3808
交易次数       11
交易金额      712
Name: 3807, dtype: int64
内部标识号    3809
交易次数        0
交易金额     4014
Name: 3808, dtype: int64
内部标识号    3810
交易次数        7
交易金额      266
Name: 3809, dtype: int64
内部标识号    3811
交易次数        3
交易金额      363
Name: 3810, dtype: int64
内部标识号    3812
交易次数        8
交易金额      892
Name: 3811, dtype: int64
内部标识号    3813
交易次数       13
交易金额      406
Name: 3812, dtype: int64
内部标识号    3814
交易次数        3
交易金额      490
Name: 3813, dtype: int64
内部标识号    3815
交易次数        4
交易金额      100
Name: 3814, dtype: int64
内部标识号    3816
交易次数        9
交易金额      404
Name: 3815, dtype: int64
内部标识号    3817
交易次数       21
交易金额       87
Name: 3816, dtype: int64
内部标识号    3818
交易次数        2
交易金额      492
Name: 3817, dtype: int64
内部标识号    3819
交易次数       23
交易金额     4478
Name: 3818, dtype: int64
内部标识号    3820
交易次数        1
交易金额      563
Name: 3819, dtype: int64
内部标识号     3821
交易次数         8
交易金额     45485
Name: 3820, dtype: int64
内部标识号    3822
交易次数       13
交易金额      807
Name: 3821, dtype: int64
内部标识号    3823
交易次数       30
交易金额       10
Name: 3822, dtype: int64
内部标识号    3824
交易次数        3
交易金额      345
Name: 3823, dtype: int64
内部标识号    3825
交易次数        0
交易金额     8909
Name: 3824, dtype: int64
内部标识号     3826
交易次数       274
交易金额     67017
Name: 3825, dtype: int64
内部标识号    3827
交易次数       13
交易金额      402
Name: 3826, dtype: int64
内部标识号    3828
交易次数        3
交易金额      311
Name: 3827, dtype: int64
内部标识号    3829
交易次数        1
交易金额     3586
Name: 3828, dtype: int64
内部标识号     3830
交易次数       293
交易金额     40087
Name: 3829, dtype: int64
内部标识号    3831
交易次数        5
交易金额      163
Name: 3830, dtype: int64
内部标识号    3832
交易次数        3
交易金额      120
Name: 3831, dtype: int64
内部标识号    3833
交易次数       15
交易金额      324
Name: 3832, dtype: int64
内部标识号     3834
交易次数         6
交易金额     99478
Name: 3833, dtype: int64
内部标识号    3835
交易次数       12
交易金额      364
Name: 3834, dtype: int64
内部标识号    3836
交易次数        5
交易金额      298
Name: 3835, dtype: int64
内部标识号    3837
交易次数        8
交易金额      256
Name: 3836, dtype: int64
内部标识号    3838
交易次数        6
交易金额      248
Name: 3837, dtype: int64
内部标识号    3839
交易次数        6
交易金额      222
Name: 3838, dtype: int64
内部标识号    3840
交易次数        3
交易金额      235
Name: 3839, dtype: int64
内部标识号    3841
交易次数        2
交易金额      500
Name: 3840, dtype: int64
内部标识号    3842
交易次数        3
交易金额      462
Name: 3841, dtype: int64
内部标识号    3843
交易次数        8
交易金额      131
Name: 3842, dtype: int64
内部标识号     3844
交易次数       103
交易金额     20427
Name: 3843, dtype: int64
内部标识号    3845
交易次数       14
交易金额      838
Name: 3844, dtype: int64
内部标识号    3846
交易次数        5
交易金额      298
Name: 3845, dtype: int64
内部标识号     3847
交易次数         3
交易金额     46890
Name: 3846, dtype: int64
内部标识号     3848
交易次数         5
交易金额     93196
Name: 3847, dtype: int64
内部标识号    3849
交易次数        4
交易金额      264
Name: 3848, dtype: int64
内部标识号    3850
交易次数       11
交易金额      306
Name: 3849, dtype: int64
内部标识号    3851
交易次数        5
交易金额      297
Name: 3850, dtype: int64
内部标识号    3852
交易次数       10
交易金额      304
Name: 3851, dtype: int64
内部标识号    3853
交易次数       14
交易金额      448
Name: 3852, dtype: int64
内部标识号    3854
交易次数        8
交易金额      889
Name: 3853, dtype: int64
内部标识号    3855
交易次数       10
交易金额      326
Name: 3854, dtype: int64
内部标识号    3856
交易次数       14
交易金额      967
Name: 3855, dtype: int64
内部标识号     3857
交易次数         7
交易金额     63863
Name: 3856, dtype: int64
内部标识号    3858
交易次数        3
交易金额      496
Name: 3857, dtype: int64
内部标识号    3859
交易次数        9
交易金额      670
Name: 3858, dtype: int64
内部标识号    3860
交易次数       10
交易金额      360
Name: 3859, dtype: int64
内部标识号     3861
交易次数        41
交易金额     45907
Name: 3860, dtype: int64
内部标识号    3862
交易次数       11
交易金额      312
Name: 3861, dtype: int64
内部标识号    3863
交易次数        0
交易金额     5846
Name: 3862, dtype: int64
内部标识号    3864
交易次数        4
交易金额      217
Name: 3863, dtype: int64
内部标识号    3865
交易次数        2
交易金额      386
Name: 3864, dtype: int64
内部标识号    3866
交易次数        4
交易金额      149
Name: 3865, dtype: int64
内部标识号    3867
交易次数       13
交易金额      329
Name: 3866, dtype: int64
内部标识号    3868
交易次数        8
交易金额      668
Name: 3867, dtype: int64
内部标识号    3869
交易次数        2
交易金额      408
Name: 3868, dtype: int64
内部标识号    3870
交易次数        8
交易金额      342
Name: 3869, dtype: int64
内部标识号    3871
交易次数       27
交易金额      724
Name: 3870, dtype: int64
内部标识号    3872
交易次数       15
交易金额     9118
Name: 3871, dtype: int64
内部标识号    3873
交易次数       10
交易金额      306
Name: 3872, dtype: int64
内部标识号    3874
交易次数        5
交易金额      160
Name: 3873, dtype: int64
内部标识号    3875
交易次数        1
交易金额     4792
Name: 3874, dtype: int64
内部标识号    3876
交易次数        2
交易金额      659
Name: 3875, dtype: int64
内部标识号    3877
交易次数       25
交易金额     1598
Name: 3876, dtype: int64
内部标识号    3878
交易次数       14
交易金额      993
Name: 3877, dtype: int64
内部标识号    3879
交易次数        8
交易金额      410
Name: 3878, dtype: int64
内部标识号    3880
交易次数       11
交易金额      306
Name: 3879, dtype: int64
内部标识号     3881
交易次数         6
交易金额     40028
Name: 3880, dtype: int64
内部标识号    3882
交易次数       14
交易金额      425
Name: 3881, dtype: int64
内部标识号    3883
交易次数        2
交易金额      596
Name: 3882, dtype: int64
内部标识号    3884
交易次数        4
交易金额      134
Name: 3883, dtype: int64
内部标识号    3885
交易次数       15
交易金额      719
Name: 3884, dtype: int64
内部标识号    3886
交易次数        2
交易金额      360
Name: 3885, dtype: int64
内部标识号    3887
交易次数        0
交易金额     2329
Name: 3886, dtype: int64
内部标识号    3888
交易次数       14
交易金额      769
Name: 3887, dtype: int64
内部标识号    3889
交易次数        1
交易金额     8516
Name: 3888, dtype: int64
内部标识号    3890
交易次数       10
交易金额      524
Name: 3889, dtype: int64
内部标识号    3891
交易次数        1
交易金额      998
Name: 3890, dtype: int64
内部标识号    3892
交易次数       23
交易金额      637
Name: 3891, dtype: int64
内部标识号    3893
交易次数       15
交易金额      385
Name: 3892, dtype: int64
内部标识号    3894
交易次数       15
交易金额      763
Name: 3893, dtype: int64
内部标识号    3895
交易次数        2
交易金额      794
Name: 3894, dtype: int64
内部标识号    3896
交易次数       17
交易金额      810
Name: 3895, dtype: int64
内部标识号    3897
交易次数        9
交易金额      305
Name: 3896, dtype: int64
内部标识号    3898
交易次数        1
交易金额      930
Name: 3897, dtype: int64
内部标识号    3899
交易次数        4
交易金额      106
Name: 3898, dtype: int64
内部标识号    3900
交易次数        9
交易金额      798
Name: 3899, dtype: int64
内部标识号    3901
交易次数        1
交易金额     9978
Name: 3900, dtype: int64
内部标识号    3902
交易次数       19
交易金额      880
Name: 3901, dtype: int64
内部标识号     3903
交易次数         5
交易金额     61351
Name: 3902, dtype: int64
内部标识号    3904
交易次数        2
交易金额      374
Name: 3903, dtype: int64
内部标识号    3905
交易次数        6
交易金额      296
Name: 3904, dtype: int64
内部标识号     3906
交易次数         8
交易金额     83208
Name: 3905, dtype: int64
内部标识号     3907
交易次数         3
交易金额     94104
Name: 3906, dtype: int64
内部标识号    3908
交易次数        2
交易金额      734
Name: 3907, dtype: int64
内部标识号    3909
交易次数       15
交易金额      508
Name: 3908, dtype: int64
内部标识号    3910
交易次数        3
交易金额      399
Name: 3909, dtype: int64
内部标识号    3911
交易次数        9
交易金额      517
Name: 3910, dtype: int64
内部标识号    3912
交易次数        0
交易金额     1221
Name: 3911, dtype: int64
内部标识号    3913
交易次数       10
交易金额      462
Name: 3912, dtype: int64
内部标识号    3914
交易次数       27
交易金额      794
Name: 3913, dtype: int64
内部标识号    3915
交易次数        0
交易金额     5491
Name: 3914, dtype: int64
内部标识号    3916
交易次数       10
交易金额      846
Name: 3915, dtype: int64
内部标识号    3917
交易次数       11
交易金额      964
Name: 3916, dtype: int64
内部标识号    3918
交易次数       15
交易金额      638
Name: 3917, dtype: int64
内部标识号    3919
交易次数        3
交易金额      105
Name: 3918, dtype: int64
内部标识号    3920
交易次数        5
交易金额      194
Name: 3919, dtype: int64
内部标识号    3921
交易次数        5
交易金额      120
Name: 3920, dtype: int64
内部标识号    3922
交易次数        3
交易金额      394
Name: 3921, dtype: int64
内部标识号    3923
交易次数        2
交易金额      312
Name: 3922, dtype: int64
内部标识号    3924
交易次数        2
交易金额      582
Name: 3923, dtype: int64
内部标识号    3925
交易次数        0
交易金额     2811
Name: 3924, dtype: int64
内部标识号     3926
交易次数        50
交易金额     39526
Name: 3925, dtype: int64
内部标识号    3927
交易次数        3
交易金额      466
Name: 3926, dtype: int64
内部标识号    3928
交易次数        1
交易金额      634
Name: 3927, dtype: int64
内部标识号    3929
交易次数        1
交易金额      693
Name: 3928, dtype: int64
内部标识号    3930
交易次数        8
交易金额      610
Name: 3929, dtype: int64
内部标识号    3931
交易次数        2
交易金额      346
Name: 3930, dtype: int64
内部标识号    3932
交易次数       11
交易金额      900
Name: 3931, dtype: int64
内部标识号    3933
交易次数        0
交易金额     2294
Name: 3932, dtype: int64
内部标识号    3934
交易次数        2
交易金额      667
Name: 3933, dtype: int64
内部标识号    3935
交易次数        4
交易金额      291
Name: 3934, dtype: int64
内部标识号    3936
交易次数        3
交易金额      144
Name: 3935, dtype: int64
内部标识号    3937
交易次数       15
交易金额      695
Name: 3936, dtype: int64
内部标识号    3938
交易次数       12
交易金额      341
Name: 3937, dtype: int64
内部标识号    3939
交易次数        2
交易金额      480
Name: 3938, dtype: int64
内部标识号    3940
交易次数       10
交易金额      312
Name: 3939, dtype: int64
内部标识号    3941
交易次数        2
交易金额      610
Name: 3940, dtype: int64
内部标识号    3942
交易次数       11
交易金额      677
Name: 3941, dtype: int64
内部标识号    3943
交易次数       10
交易金额      380
Name: 3942, dtype: int64
内部标识号     3944
交易次数         4
交易金额     62380
Name: 3943, dtype: int64
内部标识号    3945
交易次数        6
交易金额      156
Name: 3944, dtype: int64
内部标识号    3946
交易次数        7
交易金额      196
Name: 3945, dtype: int64
内部标识号    3947
交易次数       15
交易金额     7684
Name: 3946, dtype: int64
内部标识号    3948
交易次数       29
交易金额      919
Name: 3947, dtype: int64
内部标识号    3949
交易次数       20
交易金额      881
Name: 3948, dtype: int64
内部标识号     3950
交易次数       211
交易金额     98625
Name: 3949, dtype: int64
内部标识号    3951
交易次数        2
交易金额      304
Name: 3950, dtype: int64
内部标识号    3952
交易次数        2
交易金额      429
Name: 3951, dtype: int64
内部标识号    3953
交易次数        0
交易金额     2044
Name: 3952, dtype: int64
内部标识号     3954
交易次数         5
交易金额     81776
Name: 3953, dtype: int64
内部标识号    3955
交易次数        1
交易金额     2016
Name: 3954, dtype: int64
内部标识号    3956
交易次数       13
交易金额      865
Name: 3955, dtype: int64
内部标识号    3957
交易次数       12
交易金额      781
Name: 3956, dtype: int64
内部标识号    3958
交易次数        2
交易金额      578
Name: 3957, dtype: int64
内部标识号    3959
交易次数       16
交易金额      618
Name: 3958, dtype: int64
内部标识号    3960
交易次数        8
交易金额      364
Name: 3959, dtype: int64
内部标识号    3961
交易次数        6
交易金额      213
Name: 3960, dtype: int64
内部标识号    3962
交易次数        3
交易金额      191
Name: 3961, dtype: int64
内部标识号    3963
交易次数        2
交易金额      162
Name: 3962, dtype: int64
内部标识号    3964
交易次数        2
交易金额      414
Name: 3963, dtype: int64
内部标识号    3965
交易次数        9
交易金额      621
Name: 3964, dtype: int64
内部标识号    3966
交易次数       25
交易金额     7780
Name: 3965, dtype: int64
内部标识号    3967
交易次数        3
交易金额      396
Name: 3966, dtype: int64
内部标识号    3968
交易次数       20
交易金额      731
Name: 3967, dtype: int64
内部标识号    3969
交易次数       13
交易金额      447
Name: 3968, dtype: int64
内部标识号    3970
交易次数        8
交易金额      497
Name: 3969, dtype: int64
内部标识号    3971
交易次数       14
交易金额      900
Name: 3970, dtype: int64
内部标识号    3972
交易次数        2
交易金额      176
Name: 3971, dtype: int64
内部标识号    3973
交易次数        3
交易金额      424
Name: 3972, dtype: int64
内部标识号    3974
交易次数        1
交易金额      974
Name: 3973, dtype: int64
内部标识号    3975
交易次数        3
交易金额      448
Name: 3974, dtype: int64
内部标识号    3976
交易次数       14
交易金额      481
Name: 3975, dtype: int64
内部标识号    3977
交易次数        2
交易金额      347
Name: 3976, dtype: int64
内部标识号     3978
交易次数       288
交易金额     31217
Name: 3977, dtype: int64
内部标识号    3979
交易次数        5
交易金额      116
Name: 3978, dtype: int64
内部标识号    3980
交易次数        2
交易金额      855
Name: 3979, dtype: int64
内部标识号    3981
交易次数       17
交易金额     4457
Name: 3980, dtype: int64
内部标识号    3982
交易次数        3
交易金额      101
Name: 3981, dtype: int64
内部标识号    3983
交易次数       10
交易金额      317
Name: 3982, dtype: int64
内部标识号    3984
交易次数        1
交易金额     3234
Name: 3983, dtype: int64
内部标识号    3985
交易次数        1
交易金额      544
Name: 3984, dtype: int64
内部标识号     3986
交易次数         6
交易金额     62555
Name: 3985, dtype: int64
内部标识号    3987
交易次数        1
交易金额      721
Name: 3986, dtype: int64
内部标识号    3988
交易次数        2
交易金额      339
Name: 3987, dtype: int64
内部标识号    3989
交易次数       14
交易金额      478
Name: 3988, dtype: int64
内部标识号    3990
交易次数       11
交易金额      435
Name: 3989, dtype: int64
内部标识号    3991
交易次数       21
交易金额     5232
Name: 3990, dtype: int64
内部标识号    3992
交易次数       13
交易金额      386
Name: 3991, dtype: int64
内部标识号    3993
交易次数        0
交易金额     7739
Name: 3992, dtype: int64
内部标识号    3994
交易次数        0
交易金额     9066
Name: 3993, dtype: int64
内部标识号    3995
交易次数        3
交易金额      424
Name: 3994, dtype: int64
内部标识号    3996
交易次数        4
交易金额      220
Name: 3995, dtype: int64
内部标识号    3997
交易次数        5
交易金额      285
Name: 3996, dtype: int64
内部标识号    3998
交易次数       10
交易金额      371
Name: 3997, dtype: int64
内部标识号    3999
交易次数       30
交易金额     4836
Name: 3998, dtype: int64
内部标识号    4000
交易次数        0
交易金额     8639
Name: 3999, dtype: int64
内部标识号    4001
交易次数        7
交易金额      221
Name: 4000, dtype: int64
内部标识号    4002
交易次数        3
交易金额      132
Name: 4001, dtype: int64
内部标识号    4003
交易次数       15
交易金额     3053
Name: 4002, dtype: int64
内部标识号    4004
交易次数        0
交易金额     1331
Name: 4003, dtype: int64
内部标识号     4005
交易次数       187
交易金额     33173
Name: 4004, dtype: int64
内部标识号    4006
交易次数       25
交易金额     9590
Name: 4005, dtype: int64
内部标识号    4007
交易次数        2
交易金额      884
Name: 4006, dtype: int64
内部标识号    4008
交易次数       29
交易金额      592
Name: 4007, dtype: int64
内部标识号    4009
交易次数       14
交易金额      596
Name: 4008, dtype: int64
内部标识号    4010
交易次数        2
交易金额      319
Name: 4009, dtype: int64
内部标识号    4011
交易次数        3
交易金额      479
Name: 4010, dtype: int64
内部标识号    4012
交易次数       10
交易金额      715
Name: 4011, dtype: int64
内部标识号    4013
交易次数        3
交易金额      213
Name: 4012, dtype: int64
内部标识号    4014
交易次数        0
交易金额     9512
Name: 4013, dtype: int64
内部标识号    4015
交易次数       13
交易金额      452
Name: 4014, dtype: int64
内部标识号    4016
交易次数        5
交易金额      273
Name: 4015, dtype: int64
内部标识号    4017
交易次数        0
交易金额     2065
Name: 4016, dtype: int64
内部标识号    4018
交易次数        4
交易金额      197
Name: 4017, dtype: int64
内部标识号    4019
交易次数       10
交易金额      712
Name: 4018, dtype: int64
内部标识号    4020
交易次数        2
交易金额      424
Name: 4019, dtype: int64
内部标识号    4021
交易次数        1
交易金额      778
Name: 4020, dtype: int64
内部标识号    4022
交易次数        3
交易金额      219
Name: 4021, dtype: int64
内部标识号    4023
交易次数        2
交易金额      773
Name: 4022, dtype: int64
内部标识号    4024
交易次数       14
交易金额      436
Name: 4023, dtype: int64
内部标识号    4025
交易次数        3
交易金额      369
Name: 4024, dtype: int64
内部标识号    4026
交易次数        4
交易金额      212
Name: 4025, dtype: int64
内部标识号    4027
交易次数       19
交易金额      680
Name: 4026, dtype: int64
内部标识号    4028
交易次数       29
交易金额       16
Name: 4027, dtype: int64
内部标识号     4029
交易次数         4
交易金额     65658
Name: 4028, dtype: int64
内部标识号    4030
交易次数       10
交易金额      422
Name: 4029, dtype: int64
内部标识号    4031
交易次数       12
交易金额      386
Name: 4030, dtype: int64
内部标识号    4032
交易次数        5
交易金额      175
Name: 4031, dtype: int64
内部标识号    4033
交易次数        3
交易金额      213
Name: 4032, dtype: int64
内部标识号    4034
交易次数        2
交易金额      945
Name: 4033, dtype: int64
内部标识号    4035
交易次数       25
交易金额     9412
Name: 4034, dtype: int64
内部标识号    4036
交易次数        1
交易金额      781
Name: 4035, dtype: int64
内部标识号    4037
交易次数       11
交易金额      759
Name: 4036, dtype: int64
内部标识号    4038
交易次数       11
交易金额      495
Name: 4037, dtype: int64
内部标识号    4039
交易次数        1
交易金额     5561
Name: 4038, dtype: int64
内部标识号    4040
交易次数       15
交易金额      371
Name: 4039, dtype: int64
内部标识号    4041
交易次数        7
交易金额      228
Name: 4040, dtype: int64
内部标识号    4042
交易次数       13
交易金额      428
Name: 4041, dtype: int64
内部标识号    4043
交易次数        3
交易金额      472
Name: 4042, dtype: int64
内部标识号    4044
交易次数        3
交易金额      263
Name: 4043, dtype: int64
内部标识号    4045
交易次数        7
交易金额      110
Name: 4044, dtype: int64
内部标识号    4046
交易次数        1
交易金额      623
Name: 4045, dtype: int64
内部标识号    4047
交易次数       23
交易金额     9099
Name: 4046, dtype: int64
内部标识号    4048
交易次数        2
交易金额      313
Name: 4047, dtype: int64
内部标识号    4049
交易次数        4
交易金额      189
Name: 4048, dtype: int64
内部标识号    4050
交易次数        5
交易金额      130
Name: 4049, dtype: int64
内部标识号    4051
交易次数       15
交易金额      904
Name: 4050, dtype: int64
内部标识号    4052
交易次数       11
交易金额      349
Name: 4051, dtype: int64
内部标识号    4053
交易次数        8
交易金额      749
Name: 4052, dtype: int64
内部标识号    4054
交易次数        1
交易金额      698
Name: 4053, dtype: int64
内部标识号    4055
交易次数        3
交易金额      356
Name: 4054, dtype: int64
内部标识号    4056
交易次数        2
交易金额      301
Name: 4055, dtype: int64
内部标识号    4057
交易次数       29
交易金额     3951
Name: 4056, dtype: int64
内部标识号    4058
交易次数       29
交易金额      838
Name: 4057, dtype: int64
内部标识号    4059
交易次数        2
交易金额      436
Name: 4058, dtype: int64
内部标识号    4060
交易次数       17
交易金额       83
Name: 4059, dtype: int64
内部标识号    4061
交易次数       15
交易金额      392
Name: 4060, dtype: int64
内部标识号    4062
交易次数       28
交易金额     7597
Name: 4061, dtype: int64
内部标识号     4063
交易次数       227
交易金额     14498
Name: 4062, dtype: int64
内部标识号    4064
交易次数        2
交易金额      915
Name: 4063, dtype: int64
内部标识号     4065
交易次数        37
交易金额     95586
Name: 4064, dtype: int64
内部标识号     4066
交易次数         4
交易金额     72967
Name: 4065, dtype: int64
内部标识号    4067
交易次数       10
交易金额      853
Name: 4066, dtype: int64
内部标识号    4068
交易次数       12
交易金额      415
Name: 4067, dtype: int64
内部标识号    4069
交易次数        8
交易金额      646

Name: 4197, dtype: int64
内部标识号     4199
交易次数         6
交易金额     67152
Name: 4198, dtype: int64
内部标识号    4200
交易次数       12
交易金额      474
Name: 4199, dtype: int64
内部标识号    4201
交易次数        2
交易金额      529
Name: 4200, dtype: int64
内部标识号    4202
交易次数        3
交易金额      327
Name: 4201, dtype: int64
内部标识号    4203
交易次数        7
交易金额      294
Name: 4202, dtype: int64
内部标识号    4204
交易次数        4
交易金额      270
Name: 4203, dtype: int64
内部标识号    4205
交易次数        3
交易金额      446
Name: 4204, dtype: int64
内部标识号    4206
交易次数        0
交易金额     2738
Name: 4205, dtype: int64
内部标识号    4207
交易次数        8
交易金额      667
Name: 4206, dtype: int64
内部标识号    4208
交易次数       10
交易金额      521
Name: 4207, dtype: int64
内部标识号    4209
交易次数        2
交易金额      780
Name: 4208, dtype: int64
内部标识号    4210
交易次数        1
交易金额      833
Name: 4209, dtype: int64
内部标识号    4211
交易次数        8
交易金额      463
Name: 4210, dtype: int64
内部标识号    4212
交易次数        3
交易金额      205
Name: 4211, dtype: int64
内部标识号    4213
交易次数        1
交易金额      974
Name: 4212, dtype: int64
内部标识号    4214
交易次数        0
交易金额     1671
Name: 4213, dtype: int64
内部标识号    4215
交易次数        3
交易金额      401
Name: 4214, dtype: int64
内部标识号    4216
交易次数       13
交易金额      438
Name: 4215, dtype: int64
内部标识号    4217
交易次数       13
交易金额      829
Name: 4216, dtype: int64
内部标识号    4218
交易次数       29
交易金额     9078
Name: 4217, dtype: int64
内部标识号    4219
交易次数        3
交易金额      442
Name: 4218, dtype: int64
内部标识号     4220
交易次数       298
交易金额     38662
Name: 4219, dtype: int64
内部标识号    4221
交易次数        1
交易金额     3242
Name: 4220, dtype: int64
内部标识号    4222
交易次数        8
交易金额      239
Name: 4221, dtype: int64
内部标识号    4223
交易次数        5
交易金额      180
Name: 4222, dtype: int64
内部标识号     4224
交易次数         4
交易金额     42590
Name: 4223, dtype: int64
内部标识号    4225
交易次数        1
交易金额      828
Name: 4224, dtype: int64
内部标识号    4226
交易次数        3
交易金额      260
Name: 4225, dtype: int64
内部标识号    4227
交易次数        8
交易金额      449
Name: 4226, dtype: int64
内部标识号    4228
交易次数        8
交易金额      905
Name: 4227, dtype: int64
内部标识号    4229
交易次数       26
交易金额      632
Name: 4228, dtype: int64
内部标识号    4230
交易次数        8
交易金额      490
Name: 4229, dtype: int64
内部标识号    4231
交易次数       22
交易金额      930
Name: 4230, dtype: int64
内部标识号    4232
交易次数        2
交易金额      533
Name: 4231, dtype: int64
内部标识号    4233
交易次数        9
交易金额      865
Name: 4232, dtype: int64
内部标识号    4234
交易次数        2
交易金额      755
Name: 4233, dtype: int64
内部标识号    4235
交易次数        0
交易金额     9416
Name: 4234, dtype: int64
内部标识号     4236
交易次数         7
交易金额     65905
Name: 4235, dtype: int64
内部标识号    4237
交易次数        1
交易金额      611
Name: 4236, dtype: int64
内部标识号    4238
交易次数        1
交易金额      567
Name: 4237, dtype: int64
内部标识号    4239
交易次数        8
交易金额      295
Name: 4238, dtype: int64
内部标识号    4240
交易次数        4
交易金额      233
Name: 4239, dtype: int64
内部标识号    4241
交易次数       11
交易金额      860
Name: 4240, dtype: int64
内部标识号    4242
交易次数       14
交易金额      746
Name: 4241, dtype: int64
内部标识号    4243
交易次数        3
交易金额      445
Name: 4242, dtype: int64
内部标识号     4244
交易次数         4
交易金额     55401
Name: 4243, dtype: int64
内部标识号    4245
交易次数        9
交易金额      505
Name: 4244, dtype: int64
内部标识号    4246
交易次数       14
交易金额      723
Name: 4245, dtype: int64
内部标识号    4247
交易次数        1
交易金额     5693
Name: 4246, dtype: int64
内部标识号    4248
交易次数        8
交易金额      291
Name: 4247, dtype: int64
内部标识号    4249
交易次数        6
交易金额      228
Name: 4248, dtype: int64
内部标识号    4250
交易次数        3
交易金额      376
Name: 4249, dtype: int64
内部标识号    4251
交易次数       11
交易金额      386
Name: 4250, dtype: int64
内部标识号    4252
交易次数        0
交易金额     9517
Name: 4251, dtype: int64
内部标识号    4253
交易次数       30
交易金额     6231
Name: 4252, dtype: int64
内部标识号    4254
交易次数        2
交易金额      956
Name: 4253, dtype: int64
内部标识号    4255
交易次数        9
交易金额      720
Name: 4254, dtype: int64
内部标识号    4256
交易次数       12
交易金额      513
Name: 4255, dtype: int64
内部标识号    4257
交易次数       11
交易金额      475
Name: 4256, dtype: int64
内部标识号    4258
交易次数        1
交易金额      838
Name: 4257, dtype: int64
内部标识号    4259
交易次数        2
交易金额      798
Name: 4258, dtype: int64
内部标识号    4260
交易次数        2
交易金额      303
Name: 4259, dtype: int64
内部标识号    4261
交易次数        2
交易金额      804
Name: 4260, dtype: int64
内部标识号    4262
交易次数        8
交易金额      842
Name: 4261, dtype: int64
内部标识号    4263
交易次数        2
交易金额      582
Name: 4262, dtype: int64
内部标识号    4264
交易次数        2
交易金额      302
Name: 4263, dtype: int64
内部标识号     4265
交易次数         3
交易金额     66525
Name: 4264, dtype: int64
内部标识号    4266
交易次数        3
交易金额      434
Name: 4265, dtype: int64
内部标识号     4267
交易次数         6
交易金额     26451
Name: 4266, dtype: int64
内部标识号    4268
交易次数        2
交易金额      977
Name: 4267, dtype: int64
内部标识号    4269
交易次数        8
交易金额      971
Name: 4268, dtype: int64
内部标识号    4270
交易次数        2
交易金额      423
Name: 4269, dtype: int64
内部标识号    4271
交易次数        6
交易金额      112
Name: 4270, dtype: int64
内部标识号    4272
交易次数        2
交易金额      709
Name: 4271, dtype: int64
内部标识号    4273
交易次数       11
交易金额      321
Name: 4272, dtype: int64
内部标识号    4274
交易次数        2
交易金额      476
Name: 4273, dtype: int64
内部标识号    4275
交易次数        5
交易金额      129
Name: 4274, dtype: int64
内部标识号    4276
交易次数       14
交易金额      572
Name: 4275, dtype: int64
内部标识号    4277
交易次数        3
交易金额      310
Name: 4276, dtype: int64
内部标识号    4278
交易次数        8
交易金额      200
Name: 4277, dtype: int64
内部标识号    4279
交易次数        2
交易金额      697
Name: 4278, dtype: int64
内部标识号    4280
交易次数        3
交易金额      433
Name: 4279, dtype: int64
内部标识号    4281
交易次数       10
交易金额      501
Name: 4280, dtype: int64
内部标识号    4282
交易次数        6
交易金额      162
Name: 4281, dtype: int64
内部标识号    4283
交易次数        3
交易金额      482
Name: 4282, dtype: int64
内部标识号    4284
交易次数        1
交易金额      879
Name: 4283, dtype: int64
内部标识号     4285
交易次数         3
交易金额     93148
Name: 4284, dtype: int64
内部标识号    4286
交易次数        8
交易金额      341
Name: 4285, dtype: int64
内部标识号     4287
交易次数         5
交易金额     56228
Name: 4286, dtype: int64
内部标识号    4288
交易次数        9
交易金额      426
Name: 4287, dtype: int64
内部标识号    4289
交易次数        2
交易金额      418
Name: 4288, dtype: int64
内部标识号    4290
交易次数       15
交易金额      849
Name: 4289, dtype: int64
内部标识号    4291
交易次数        7
交易金额      183
Name: 4290, dtype: int64
内部标识号    4292
交易次数        5
交易金额      233
Name: 4291, dtype: int64
内部标识号     4293
交易次数       140
交易金额     42193
Name: 4292, dtype: int64
内部标识号    4294
交易次数       23
交易金额      841
Name: 4293, dtype: int64
内部标识号    4295
交易次数        3
交易金额      239
Name: 4294, dtype: int64
内部标识号    4296
交易次数        8
交易金额      162
Name: 4295, dtype: int64
内部标识号    4297
交易次数       27
交易金额     1000
Name: 4296, dtype: int64
内部标识号    4298
交易次数        4
交易金额      254
Name: 4297, dtype: int64
内部标识号     4299
交易次数         7
交易金额     70045
Name: 4298, dtype: int64
内部标识号    4300
交易次数       11
交易金额      557
Name: 4299, dtype: int64
内部标识号    4301
交易次数        1
交易金额      803
Name: 4300, dtype: int64
内部标识号    4302
交易次数       25
交易金额     4302
Name: 4301, dtype: int64
内部标识号    4303
交易次数        3
交易金额      362
Name: 4302, dtype: int64
内部标识号    4304
交易次数       11
交易金额      307
Name: 4303, dtype: int64
内部标识号    4305
交易次数        5
交易金额      181
Name: 4304, dtype: int64
内部标识号    4306
交易次数        8
交易金额      520
Name: 4305, dtype: int64
内部标识号    4307
交易次数        8
交易金额      668
Name: 4306, dtype: int64
内部标识号    4308
交易次数        3
交易金额      434
Name: 4307, dtype: int64
内部标识号    4309
交易次数        1
交易金额      917
Name: 4308, dtype: int64
内部标识号    4310
交易次数        3
交易金额      225
Name: 4309, dtype: int64
内部标识号     4311
交易次数       278
交易金额     23289
Name: 4310, dtype: int64
内部标识号    4312
交易次数        0
交易金额     4962
Name: 4311, dtype: int64
内部标识号    4313
交易次数        9
交易金额      349
Name: 4312, dtype: int64
内部标识号    4314
交易次数        7
交易金额      180
Name: 4313, dtype: int64
内部标识号    4315
交易次数       22
交易金额      851
Name: 4314, dtype: int64
内部标识号    4316
交易次数        2
交易金额      681
Name: 4315, dtype: int64
内部标识号    4317
交易次数        5
交易金额      237
Name: 4316, dtype: int64
内部标识号    4318
交易次数       12
交易金额      891
Name: 4317, dtype: int64
内部标识号     4319
交易次数         5
交易金额     90358
Name: 4318, dtype: int64
内部标识号    4320
交易次数       15
交易金额      551
Name: 4319, dtype: int64
内部标识号     4321
交易次数         6
交易金额     14473
Name: 4320, dtype: int64
内部标识号    4322
交易次数        1
交易金额      538
Name: 4321, dtype: int64
内部标识号    4323
交易次数        3
交易金额      434
Name: 4322, dtype: int64
内部标识号    4324
交易次数        9
交易金额      698
Name: 4323, dtype: int64
内部标识号    4325
交易次数       10
交易金额      625
Name: 4324, dtype: int64
内部标识号    4326
交易次数        3
交易金额      236
Name: 4325, dtype: int64
内部标识号    4327
交易次数        8
交易金额      192
Name: 4326, dtype: int64
内部标识号    4328
交易次数       15
交易金额      634
Name: 4327, dtype: int64
内部标识号    4329
交易次数        2
交易金额      804
Name: 4328, dtype: int64
内部标识号    4330
交易次数       13
交易金额      422
Name: 4329, dtype: int64
内部标识号    4331
交易次数       18
交易金额     6931
Name: 4330, dtype: int64
内部标识号    4332
交易次数        8
交易金额      485
Name: 4331, dtype: int64
内部标识号     4333
交易次数         6
交易金额     45537
Name: 4332, dtype: int64
内部标识号    4334
交易次数       10
交易金额      827
Name: 4333, dtype: int64
内部标识号     4335
交易次数       137
交易金额     43858
Name: 4334, dtype: int64
内部标识号    4336
交易次数       20
交易金额      689
Name: 4335, dtype: int64
内部标识号    4337
交易次数       30
交易金额     6876
Name: 4336, dtype: int64
内部标识号    4338
交易次数        5
交易金额      226
Name: 4337, dtype: int64
内部标识号    4339
交易次数       11
交易金额      330
Name: 4338, dtype: int64
内部标识号    4340
交易次数       21
交易金额      575
Name: 4339, dtype: int64
内部标识号    4341
交易次数        2
交易金额      414
Name: 4340, dtype: int64
内部标识号    4342
交易次数       10
交易金额      825
Name: 4341, dtype: int64
内部标识号    4343
交易次数        7
交易金额      121
Name: 4342, dtype: int64
内部标识号    4344
交易次数        6
交易金额      112
Name: 4343, dtype: int64
内部标识号    4345
交易次数        2
交易金额      750
Name: 4344, dtype: int64
内部标识号     4346
交易次数        63
交易金额     53725
Name: 4345, dtype: int64
内部标识号    4347
交易次数        2
交易金额      842
Name: 4346, dtype: int64
内部标识号    4348
交易次数       13
交易金额      880
Name: 4347, dtype: int64
内部标识号    4349
交易次数        0
交易金额     6491
Name: 4348, dtype: int64
内部标识号    4350
交易次数        1
交易金额      505
Name: 4349, dtype: int64
内部标识号    4351
交易次数        0
交易金额     9369
Name: 4350, dtype: int64
内部标识号    4352
交易次数        0
交易金额     7814
Name: 4351, dtype: int64
内部标识号    4353
交易次数        2
交易金额      416
Name: 4352, dtype: int64
内部标识号    4354
交易次数       25
交易金额       67
Name: 4353, dtype: int64
内部标识号    4355
交易次数        1
交易金额      976
Name: 4354, dtype: int64
内部标识号    4356
交易次数       13
交易金额      435
Name: 4355, dtype: int64
内部标识号    4357
交易次数       20
交易金额     8158
Name: 4356, dtype: int64
内部标识号    4358
交易次数        3
交易金额      328
Name: 4357, dtype: int64
内部标识号    4359
交易次数       12
交易金额      924
Name: 4358, dtype: int64
内部标识号    4360
交易次数       19
交易金额      639
Name: 4359, dtype: int64
内部标识号    4361
交易次数       15
交易金额      378
Name: 4360, dtype: int64
内部标识号    4362
交易次数       15
交易金额      402
Name: 4361, dtype: int64
内部标识号    4363
交易次数        0
交易金额     2581
Name: 4362, dtype: int64
内部标识号    4364
交易次数       12
交易金额      863
Name: 4363, dtype: int64
内部标识号    4365
交易次数       13
交易金额      421
Name: 4364, dtype: int64
内部标识号    4366
交易次数       23
交易金额     7863
Name: 4365, dtype: int64
内部标识号    4367
交易次数       11
交易金额      844
Name: 4366, dtype: int64
内部标识号    4368
交易次数        1
交易金额     5137
Name: 4367, dtype: int64
内部标识号    4369
交易次数        6
交易金额      289
Name: 4368, dtype: int64
内部标识号     4370
交易次数         4
交易金额     36544
Name: 4369, dtype: int64
内部标识号     4371
交易次数         3
交易金额     38712
Name: 4370, dtype: int64
内部标识号    4372
交易次数       12
交易金额      560
Name: 4371, dtype: int64
内部标识号    4373
交易次数       25
交易金额     6968
Name: 4372, dtype: int64
内部标识号    4374
交易次数        9
交易金额      704
Name: 4373, dtype: int64
内部标识号    4375
交易次数        9
交易金额      349
Name: 4374, dtype: int64
内部标识号    4376
交易次数       22
交易金额       14
Name: 4375, dtype: int64
内部标识号    4377
交易次数       16
交易金额       48
Name: 4376, dtype: int64
内部标识号    4378
交易次数        0
交易金额     2943
Name: 4377, dtype: int64
内部标识号    4379
交易次数       26
交易金额     4672
Name: 4378, dtype: int64
内部标识号    4380
交易次数        3
交易金额      313
Name: 4379, dtype: int64
内部标识号    4381
交易次数       11
交易金额      489
Name: 4380, dtype: int64
内部标识号    4382
交易次数        5
交易金额      229
Name: 4381, dtype: int64
内部标识号    4383
交易次数       28
交易金额      667
Name: 4382, dtype: int64
内部标识号    4384
交易次数       14
交易金额      658
Name: 4383, dtype: int64
内部标识号    4385
交易次数        6
交易金额      264
Name: 4384, dtype: int64
内部标识号    4386
交易次数        8
交易金额      240
Name: 4385, dtype: int64
内部标识号    4387
交易次数        3
交易金额      142
Name: 4386, dtype: int64
内部标识号    4388
交易次数       12
交易金额      791
Name: 4387, dtype: int64
内部标识号    4389
交易次数        4
交易金额      135
Name: 4388, dtype: int64
内部标识号    4390
交易次数        2
交易金额      347
Name: 4389, dtype: int64
内部标识号    4391
交易次数       14
交易金额      752
Name: 4390, dtype: int64
内部标识号    4392
交易次数        1
交易金额     7942
Name: 4391, dtype: int64
内部标识号    4393
交易次数        6
交易金额      112
Name: 4392, dtype: int64
内部标识号    4394
交易次数       13
交易金额      874
Name: 4393, dtype: int64
内部标识号    4395
交易次数        4
交易金额      172
Name: 4394, dtype: int64
内部标识号    4396
交易次数        3
交易金额      367
Name: 4395, dtype: int64
内部标识号    4397
交易次数        2
交易金额      243
Name: 4396, dtype: int64
内部标识号    4398
交易次数       29
交易金额     1323
Name: 4397, dtype: int64
内部标识号     4399
交易次数         4
交易金额     95256
Name: 4398, dtype: int64
内部标识号    4400
交易次数        2
交易金额      310
Name: 4399, dtype: int64
内部标识号    4401
交易次数        7
交易金额      127
Name: 4400, dtype: int64
内部标识号    4402
交易次数        0
交易金额     8954
Name: 4401, dtype: int64
内部标识号    4403
交易次数       22
交易金额     8510
Name: 4402, dtype: int64
内部标识号    4404
交易次数        3
交易金额      122
Name: 4403, dtype: int64
内部标识号    4405
交易次数        0
交易金额     3220
Name: 4404, dtype: int64
内部标识号    4406
交易次数        2
交易金额      355
Name: 4405, dtype: int64
内部标识号    4407
交易次数        8
交易金额      585
Name: 4406, dtype: int64
内部标识号    4408
交易次数        2
交易金额      762
Name: 4407, dtype: int64
内部标识号    4409
交易次数        8
交易金额      519
Name: 4408, dtype: int64
内部标识号    4410
交易次数        2
交易金额      711
Name: 4409, dtype: int64
内部标识号    4411
交易次数        8
交易金额      376
Name: 4410, dtype: int64
内部标识号    4412
交易次数        0
交易金额     7648
Name: 4411, dtype: int64
内部标识号    4413
交易次数        2
交易金额      400
Name: 4412, dtype: int64
内部标识号    4414
交易次数       13
交易金额      412
Name: 4413, dtype: int64
内部标识号    4415
交易次数       13
交易金额      342
Name: 4414, dtype: int64
内部标识号    4416
交易次数        9
交易金额      809
Name: 4415, dtype: int64
内部标识号    4417
交易次数       11
交易金额      539
Name: 4416, dtype: int64
内部标识号    4418
交易次数        3
交易金额      131
Name: 4417, dtype: int64
内部标识号    4419
交易次数        8
交易金额      789
Name: 4418, dtype: int64
内部标识号     4420
交易次数       278
交易金额     62193
Name: 4419, dtype: int64
内部标识号    4421
交易次数       10
交易金额      310
Name: 4420, dtype: int64
内部标识号    4422
交易次数        2
交易金额      308
Name: 4421, dtype: int64
内部标识号    4423
交易次数        3
交易金额      192
Name: 4422, dtype: int64
内部标识号    4424
交易次数        3
交易金额      434
Name: 4423, dtype: int64
内部标识号    4425
交易次数       11
交易金额      302
Name: 4424, dtype: int64
内部标识号    4426
交易次数       11
交易金额      646
Name: 4425, dtype: int64
内部标识号    4427
交易次数       14
交易金额      812
Name: 4426, dtype: int64
内部标识号    4428
交易次数        2
交易金额      449
Name: 4427, dtype: int64
内部标识号    4429
交易次数       28
交易金额     9790
Name: 4428, dtype: int64
内部标识号    4430
交易次数       10
交易金额      892
Name: 4429, dtype: int64
内部标识号     4431
交易次数       244
交易金额     65426
Name: 4430, dtype: int64
内部标识号    4432
交易次数        6
交易金额      160
Name: 4431, dtype: int64
内部标识号     4433
交易次数         4
交易金额     72161
Name: 4432, dtype: int64
内部标识号    4434
交易次数        8
交易金额      333
Name: 4433, dtype: int64
内部标识号    4435
交易次数        2
交易金额      312
Name: 4434, dtype: int64
内部标识号    4436
交易次数        3
交易金额      346
Name: 4435, dtype: int64
内部标识号    4437
交易次数        5
交易金额      170
Name: 4436, dtype: int64
内部标识号    4438
交易次数        2
交易金额      502
Name: 4437, dtype: int64
内部标识号    4439
交易次数       15
交易金额      607
Name: 4438, dtype: int64
内部标识号    4440
交易次数        0
交易金额     9589
Name: 4439, dtype: int64
内部标识号    4441
交易次数       13
交易金额      784
Name: 4440, dtype: int64
内部标识号    4442
交易次数        1
交易金额     4715
Name: 4441, dtype: int64
内部标识号     4443
交易次数         7
交易金额     64629
Name: 4442, dtype: int64
内部标识号    4444
交易次数        1
交易金额      553
Name: 4443, dtype: int64
内部标识号    4445
交易次数       12
交易金额      867
Name: 4444, dtype: int64
内部标识号    4446
交易次数        7
交易金额      114
Name: 4445, dtype: int64
内部标识号    4447
交易次数       12
交易金额      397
Name: 4446, dtype: int64
内部标识号    4448
交易次数        2
交易金额      872
Name: 4447, dtype: int64
内部标识号    4449
交易次数       13
交易金额      933
Name: 4448, dtype: int64
内部标识号    4450
交易次数        3
交易金额      325
Name: 4449, dtype: int64
内部标识号     4451
交易次数       112
交易金额     24184
Name: 4450, dtype: int64
内部标识号    4452
交易次数        2
交易金额      527
Name: 4451, dtype: int64
内部标识号    4453
交易次数       15
交易金额      666
Name: 4452, dtype: int64
内部标识号     4454
交易次数       264
交易金额     73813
Name: 4453, dtype: int64
内部标识号    4455
交易次数       14
交易金额      349
Name: 4454, dtype: int64
内部标识号    4456
交易次数       21
交易金额     8417
Name: 4455, dtype: int64
内部标识号    4457
交易次数        3
交易金额      461
Name: 4456, dtype: int64
内部标识号    4458
交易次数        2
交易金额      888
Name: 4457, dtype: int64
内部标识号    4459
交易次数       14
交易金额      904
Name: 4458, dtype: int64
内部标识号    4460
交易次数       17
交易金额      867
Name: 4459, dtype: int64
内部标识号    4461
交易次数        3
交易金额      277
Name: 4460, dtype: int64
内部标识号    4462
交易次数       20
交易金额     3426
Name: 4461, dtype: int64
内部标识号    4463
交易次数        8
交易金额      357
Name: 4462, dtype: int64
内部标识号    4464
交易次数        6
交易金额      286
Name: 4463, dtype: int64
内部标识号    4465
交易次数        1
交易金额      830
Name: 4464, dtype: int64
内部标识号    4466
交易次数        1
交易金额      791
Name: 4465, dtype: int64
内部标识号    4467
交易次数        8
交易金额      473
Name: 4466, dtype: int64
内部标识号    4468
交易次数        3
交易金额      488
Name: 4467, dtype: int64
内部标识号    4469
交易次数        0
交易金额     3746
Name: 4468, dtype: int64
内部标识号    4470
交易次数        2
交易金额      832
Name: 4469, dtype: int64
内部标识号    4471
交易次数        3
交易金额      117
Name: 4470, dtype: int64
内部标识号     4472
交易次数       197
交易金额     84220
Name: 4471, dtype: int64
内部标识号    4473
交易次数        5
交易金额      164
Name: 4472, dtype: int64
内部标识号    4474
交易次数       24
交易金额       32
Name: 4473, dtype: int64
内部标识号    4475
交易次数        3
交易金额      488
Name: 4474, dtype: int64
内部标识号    4476
交易次数       12
交易金额      402
Name: 4475, dtype: int64
内部标识号    4477
交易次数        3
交易金额      424
Name: 4476, dtype: int64
内部标识号     4478
交易次数       186
交易金额     16263
Name: 4477, dtype: int64
内部标识号    4479
交易次数        4
交易金额      248
Name: 4478, dtype: int64
内部标识号    4480
交易次数        9
交易金额      777
Name: 4479, dtype: int64
内部标识号    4481
交易次数        0
交易金额     8332

Name: 4480, dtype: int64
内部标识号    4482
交易次数       11
交易金额      485
Name: 4481, dtype: int64
内部标识号    4483
交易次数        0
交易金额     9022
Name: 4482, dtype: int64
内部标识号     4484
交易次数        30
交易金额     90690
Name: 4483, dtype: int64
内部标识号    4485
交易次数        3
交易金额      466
Name: 4484, dtype: int64
内部标识号    4486
交易次数       11
交易金额      804
Name: 4485, dtype: int64
内部标识号    4487
交易次数        5
交易金额      251
Name: 4486, dtype: int64
内部标识号    4488
交易次数        4
交易金额      191
Name: 4487, dtype: int64
内部标识号    4489
交易次数        2
交易金额      682
Name: 4488, dtype: int64
内部标识号     4490
交易次数       195
交易金额     20025
Name: 4489, dtype: int64
内部标识号    4491
交易次数        2
交易金额      372
Name: 4490, dtype: int64
内部标识号    4492
交易次数       13
交易金额      399
Name: 4491, dtype: int64
内部标识号    4493
交易次数        9
交易金额      569
Name: 4492, dtype: int64
内部标识号    4494
交易次数        2
交易金额      440
Name: 4493, dtype: int64
内部标识号    4495
交易次数        9
交易金额      343
Name: 4494, dtype: int64
内部标识号    4496
交易次数       15
交易金额        0
Name: 4495, dtype: int64
内部标识号    4497
交易次数        4
交易金额      168
Name: 4496, dtype: int64
内部标识号     4498
交易次数       232
交易金额     49296
Name: 4497, dtype: int64
内部标识号    4499
交易次数        9
交易金额      624
Name: 4498, dtype: int64
内部标识号    4500
交易次数        6
交易金额      259
Name: 4499, dtype: int64
内部标识号    4501
交易次数       15
交易金额      709
Name: 4500, dtype: int64
内部标识号    4502
交易次数        0
交易金额     9057
Name: 4501, dtype: int64
内部标识号    4503
交易次数        3
交易金额      284
Name: 4502, dtype: int64
内部标识号    4504
交易次数        9
交易金额      921
Name: 4503, dtype: int64
内部标识号    4505
交易次数        1
交易金额      518
Name: 4504, dtype: int64
内部标识号    4506
交易次数       10
交易金额      601
Name: 4505, dtype: int64
内部标识号    4507
交易次数        3
交易金额      487
Name: 4506, dtype: int64
内部标识号    4508
交易次数       20
交易金额     2846
Name: 4507, dtype: int64
内部标识号    4509
交易次数        3
交易金额      375
Name: 4508, dtype: int64
内部标识号    4510
交易次数        0
交易金额     8450
Name: 4509, dtype: int64
内部标识号    4511
交易次数        8
交易金额      626
Name: 4510, dtype: int64
内部标识号    4512
交易次数       11
交易金额      378
Name: 4511, dtype: int64
内部标识号    4513
交易次数       11
交易金额      735
Name: 4512, dtype: int64
内部标识号    4514
交易次数        0
交易金额     8817
Name: 4513, dtype: int64
内部标识号    4515
交易次数        6
交易金额      234
Name: 4514, dtype: int64
内部标识号    4516
交易次数        4
交易金额      282
Name: 4515, dtype: int64
内部标识号    4517
交易次数        3
交易金额      251
Name: 4516, dtype: int64
内部标识号    4518
交易次数       10
交易金额      343
Name: 4517, dtype: int64
内部标识号    4519
交易次数        3
交易金额      357
Name: 4518, dtype: int64
内部标识号    4520
交易次数        5
交易金额      164
Name: 4519, dtype: int64
内部标识号    4521
交易次数        2
交易金额      987
Name: 4520, dtype: int64
内部标识号     4522
交易次数       266
交易金额     11938
Name: 4521, dtype: int64
内部标识号    4523
交易次数       11
交易金额      859
Name: 4522, dtype: int64
内部标识号    4524
交易次数       28
交易金额     9920
Name: 4523, dtype: int64
内部标识号    4525
交易次数        1
交易金额      786
Name: 4524, dtype: int64
内部标识号    4526
交易次数       13
交易金额      602
Name: 4525, dtype: int64
内部标识号    4527
交易次数       13
交易金额      563
Name: 4526, dtype: int64
内部标识号    4528
交易次数        3
交易金额      311
Name: 4527, dtype: int64
内部标识号    4529
交易次数       14
交易金额      505
Name: 4528, dtype: int64
内部标识号    4530
交易次数       30
交易金额      735
Name: 4529, dtype: int64
内部标识号    4531
交易次数        2
交易金额      376
Name: 4530, dtype: int64
内部标识号    4532
交易次数        8
交易金额      178
Name: 4531, dtype: int64
内部标识号    4533
交易次数        1
交易金额      985
Name: 4532, dtype: int64
内部标识号    4534
交易次数        3
交易金额      319
Name: 4533, dtype: int64
内部标识号    4535
交易次数        1
交易金额      523
Name: 4534, dtype: int64
内部标识号     4536
交易次数       142
交易金额     52297
Name: 4535, dtype: int64
内部标识号    4537
交易次数       15
交易金额      413
Name: 4536, dtype: int64
内部标识号    4538
交易次数       17
交易金额      918
Name: 4537, dtype: int64
内部标识号    4539
交易次数        0
交易金额     9129
Name: 4538, dtype: int64
内部标识号    4540
交易次数        2
交易金额      407
Name: 4539, dtype: int64
内部标识号    4541
交易次数       11
交易金额      321
Name: 4540, dtype: int64
内部标识号    4542
交易次数        3
交易金额      377
Name: 4541, dtype: int64
内部标识号    4543
交易次数       18
交易金额     3260
Name: 4542, dtype: int64
内部标识号    4544
交易次数        2
交易金额      378
Name: 4543, dtype: int64
内部标识号    4545
交易次数        1
交易金额     3066
Name: 4544, dtype: int64
内部标识号    4546
交易次数       26
交易金额      550
Name: 4545, dtype: int64
内部标识号    4547
交易次数        6
交易金额      201
Name: 4546, dtype: int64
内部标识号    4548
交易次数       14
交易金额      729
Name: 4547, dtype: int64
内部标识号    4549
交易次数       11
交易金额      483
Name: 4548, dtype: int64
内部标识号    4550
交易次数        9
交易金额      900
Name: 4549, dtype: int64
内部标识号    4551
交易次数        2
交易金额      613
Name: 4550, dtype: int64
内部标识号    4552
交易次数        4
交易金额      110
Name: 4551, dtype: int64
内部标识号    4553
交易次数        2
交易金额      375
Name: 4552, dtype: int64
内部标识号    4554
交易次数        2
交易金额      330
Name: 4553, dtype: int64
内部标识号    4555
交易次数       15
交易金额      372
Name: 4554, dtype: int64
内部标识号    4556
交易次数       19
交易金额     3537
Name: 4555, dtype: int64
内部标识号    4557
交易次数        2
交易金额      355
Name: 4556, dtype: int64
内部标识号     4558
交易次数       134
交易金额     25236
Name: 4557, dtype: int64
内部标识号    4559
交易次数       13
交易金额      333
Name: 4558, dtype: int64
内部标识号    4560
交易次数        3
交易金额      443
Name: 4559, dtype: int64
内部标识号    4561
交易次数       13
交易金额      878
Name: 4560, dtype: int64
内部标识号     4562
交易次数         6
交易金额     22501
Name: 4561, dtype: int64
内部标识号    4563
交易次数       22
交易金额     8512
Name: 4562, dtype: int64
内部标识号    4564
交易次数        5
交易金额      155
Name: 4563, dtype: int64
内部标识号    4565
交易次数        6
交易金额      182
Name: 4564, dtype: int64
内部标识号    4566
交易次数        2
交易金额      485
Name: 4565, dtype: int64
内部标识号    4567
交易次数        5
交易金额      277
Name: 4566, dtype: int64
内部标识号    4568
交易次数        8
交易金额      228
Name: 4567, dtype: int64
内部标识号    4569
交易次数       15
交易金额      751
Name: 4568, dtype: int64
内部标识号    4570
交易次数       10
交易金额      739
Name: 4569, dtype: int64
内部标识号    4571
交易次数        0
交易金额     2867
Name: 4570, dtype: int64
内部标识号    4572
交易次数       10
交易金额      923
Name: 4571, dtype: int64
内部标识号    4573
交易次数        3
交易金额      163
Name: 4572, dtype: int64
内部标识号    4574
交易次数        2
交易金额      285
Name: 4573, dtype: int64
内部标识号    4575
交易次数       12
交易金额      334
Name: 4574, dtype: int64
内部标识号    4576
交易次数       14
交易金额      585
Name: 4575, dtype: int64
内部标识号    4577
交易次数        2
交易金额      233
Name: 4576, dtype: int64
内部标识号    4578
交易次数        2
交易金额      399
Name: 4577, dtype: int64
内部标识号    4579
交易次数        2
交易金额      282
Name: 4578, dtype: int64
内部标识号    4580
交易次数       11
交易金额      432
Name: 4579, dtype: int64
内部标识号    4581
交易次数        1
交易金额     9240
Name: 4580, dtype: int64
内部标识号    4582
交易次数        0
交易金额     3023
Name: 4581, dtype: int64
内部标识号    4583
交易次数       14
交易金额      505
Name: 4582, dtype: int64
内部标识号    4584
交易次数       14
交易金额      855
Name: 4583, dtype: int64
内部标识号     4585
交易次数       237
交易金额     53834
Name: 4584, dtype: int64
内部标识号    4586
交易次数        1
交易金额      555
Name: 4585, dtype: int64
内部标识号    4587
交易次数       26
交易金额     4694
Name: 4586, dtype: int64
内部标识号    4588
交易次数       19
交易金额     3979
Name: 4587, dtype: int64
内部标识号    4589
交易次数        9
交易金额      992
Name: 4588, dtype: int64
内部标识号    4590
交易次数       13
交易金额      356
Name: 4589, dtype: int64
内部标识号    4591
交易次数        3
交易金额      178
Name: 4590, dtype: int64
内部标识号    4592
交易次数        3
交易金额      378
Name: 4591, dtype: int64
内部标识号    4593
交易次数       15
交易金额     3087
Name: 4592, dtype: int64
内部标识号    4594
交易次数       10
交易金额      413
Name: 4593, dtype: int64
内部标识号     4595
交易次数         5
交易金额     91383
Name: 4594, dtype: int64
内部标识号    4596
交易次数        3
交易金额      268
Name: 4595, dtype: int64
内部标识号    4597
交易次数       26
交易金额     9412
Name: 4596, dtype: int64
内部标识号    4598
交易次数        1
交易金额      859
Name: 4597, dtype: int64
内部标识号    4599
交易次数       15
交易金额      398
Name: 4598, dtype: int64
内部标识号    4600
交易次数        3
交易金额      222
Name: 4599, dtype: int64
内部标识号    4601
交易次数        3
交易金额      249
Name: 4600, dtype: int64
内部标识号    4602
交易次数        3
交易金额      209
Name: 4601, dtype: int64
内部标识号    4603
交易次数       10
交易金额      593
Name: 4602, dtype: int64
内部标识号    4604
交易次数        1
交易金额     5061
Name: 4603, dtype: int64
内部标识号    4605
交易次数        1
交易金额     7335
Name: 4604, dtype: int64
内部标识号    4606
交易次数        9
交易金额      669
Name: 4605, dtype: int64
内部标识号    4607
交易次数        2
交易金额      423
Name: 4606, dtype: int64
内部标识号    4608
交易次数        1
交易金额      641
Name: 4607, dtype: int64
内部标识号    4609
交易次数        4
交易金额      238
Name: 4608, dtype: int64
内部标识号    4610
交易次数        0
交易金额     5832
Name: 4609, dtype: int64
内部标识号    4611
交易次数        3
交易金额      176
Name: 4610, dtype: int64
内部标识号    4612
交易次数        6
交易金额      196
Name: 4611, dtype: int64
内部标识号    4613
交易次数       26
交易金额      668
Name: 4612, dtype: int64
内部标识号    4614
交易次数        8
交易金额      361
Name: 4613, dtype: int64
内部标识号    4615
交易次数        0
交易金额     7244
Name: 4614, dtype: int64
内部标识号    4616
交易次数        1
交易金额      588
Name: 4615, dtype: int64
内部标识号    4617
交易次数       22
交易金额      872
Name: 4616, dtype: int64
内部标识号    4618
交易次数       15
交易金额      536
Name: 4617, dtype: int64
内部标识号     4619
交易次数       172
交易金额     26961
Name: 4618, dtype: int64
内部标识号    4620
交易次数        5
交易金额      276
Name: 4619, dtype: int64
内部标识号    4621
交易次数       17
交易金额     1039
Name: 4620, dtype: int64
内部标识号    4622
交易次数       19
交易金额     3583
Name: 4621, dtype: int64
内部标识号    4623
交易次数        3
交易金额      414
Name: 4622, dtype: int64
内部标识号    4624
交易次数        2
交易金额      531
Name: 4623, dtype: int64
内部标识号    4625
交易次数       15
交易金额      542
Name: 4624, dtype: int64
内部标识号    4626
交易次数       12
交易金额      842
Name: 4625, dtype: int64
内部标识号    4627
交易次数       29
交易金额      518
Name: 4626, dtype: int64
内部标识号    4628
交易次数        4
交易金额      213
Name: 4627, dtype: int64
内部标识号    4629
交易次数        0
交易金额     9471
Name: 4628, dtype: int64
内部标识号    4630
交易次数       21
交易金额     2008
Name: 4629, dtype: int64
内部标识号    4631
交易次数       19
交易金额       91
Name: 4630, dtype: int64
内部标识号     4632
交易次数       259
交易金额     49466
Name: 4631, dtype: int64
内部标识号    4633
交易次数       20
交易金额     9026
Name: 4632, dtype: int64
内部标识号    4634
交易次数       15
交易金额      481
Name: 4633, dtype: int64
内部标识号    4635
交易次数       15
交易金额      321
Name: 4634, dtype: int64
内部标识号    4636
交易次数        3
交易金额      363
Name: 4635, dtype: int64
内部标识号     4637
交易次数       125
交易金额     57773
Name: 4636, dtype: int64
内部标识号    4638
交易次数        2
交易金额      342
Name: 4637, dtype: int64
内部标识号    4639
交易次数        2
交易金额      240
Name: 4638, dtype: int64
内部标识号    4640
交易次数       17
交易金额     1459
Name: 4639, dtype: int64
内部标识号    4641
交易次数       15
交易金额      816
Name: 4640, dtype: int64
内部标识号    4642
交易次数        7
交易金额      242
Name: 4641, dtype: int64
内部标识号    4643
交易次数        3
交易金额      362
Name: 4642, dtype: int64
内部标识号    4644
交易次数       12
交易金额      858
Name: 4643, dtype: int64
内部标识号    4645
交易次数        1
交易金额      979
Name: 4644, dtype: int64
内部标识号    4646
交易次数        9
交易金额      361
Name: 4645, dtype: int64
内部标识号    4647
交易次数       16
交易金额      882
Name: 4646, dtype: int64
内部标识号    4648
交易次数        4
交易金额      142
Name: 4647, dtype: int64
内部标识号    4649
交易次数       15
交易金额      309
Name: 4648, dtype: int64
内部标识号    4650
交易次数        2
交易金额      420
Name: 4649, dtype: int64
内部标识号    4651
交易次数        6
交易金额      272
Name: 4650, dtype: int64
内部标识号    4652
交易次数        9
交易金额      615
Name: 4651, dtype: int64
内部标识号    4653
交易次数       21
交易金额     4813
Name: 4652, dtype: int64
内部标识号    4654
交易次数       14
交易金额     1000
Name: 4653, dtype: int64
内部标识号    4655
交易次数        2
交易金额      593
Name: 4654, dtype: int64
内部标识号    4656
交易次数       15
交易金额      441
Name: 4655, dtype: int64
内部标识号    4657
交易次数        3
交易金额      489
Name: 4656, dtype: int64
内部标识号    4658
交易次数       10
交易金额      630
Name: 4657, dtype: int64
内部标识号    4659
交易次数        2
交易金额      313
Name: 4658, dtype: int64
内部标识号    4660
交易次数        1
交易金额      521
Name: 4659, dtype: int64
内部标识号    4661
交易次数        8
交易金额      865
Name: 4660, dtype: int64
内部标识号     4662
交易次数         5
交易金额     52690
Name: 4661, dtype: int64
内部标识号    4663
交易次数       27
交易金额     8631
Name: 4662, dtype: int64
内部标识号    4664
交易次数        2
交易金额      467
Name: 4663, dtype: int64
内部标识号    4665
交易次数       12
交易金额      380
Name: 4664, dtype: int64
内部标识号    4666
交易次数       22
交易金额       11
Name: 4665, dtype: int64
内部标识号    4667
交易次数       11
交易金额      608
Name: 4666, dtype: int64
内部标识号    4668
交易次数        3
交易金额      470
Name: 4667, dtype: int64
内部标识号     4669
交易次数         7
交易金额     63476
Name: 4668, dtype: int64
内部标识号    4670
交易次数       13
交易金额      648
Name: 4669, dtype: int64
内部标识号     4671
交易次数       163
交易金额     56239
Name: 4670, dtype: int64
内部标识号    4672
交易次数       13
交易金额      369
Name: 4671, dtype: int64
内部标识号    4673
交易次数       18
交易金额      689
Name: 4672, dtype: int64
内部标识号    4674
交易次数       15
交易金额      624
Name: 4673, dtype: int64
内部标识号    4675
交易次数        3
交易金额      188
Name: 4674, dtype: int64
内部标识号    4676
交易次数        2
交易金额      436
Name: 4675, dtype: int64
内部标识号    4677
交易次数        0
交易金额     4706
Name: 4676, dtype: int64
内部标识号    4678
交易次数        8
交易金额      105
Name: 4677, dtype: int64
内部标识号    4679
交易次数        2
交易金额      321
Name: 4678, dtype: int64
内部标识号    4680
交易次数        2
交易金额      410
Name: 4679, dtype: int64
内部标识号    4681
交易次数       14
交易金额      554
Name: 4680, dtype: int64
内部标识号    4682
交易次数       21
交易金额     4111
Name: 4681, dtype: int64
内部标识号     4683
交易次数       287
交易金额     61269
Name: 4682, dtype: int64
内部标识号     4684
交易次数         7
交易金额     11192
Name: 4683, dtype: int64
内部标识号    4685
交易次数       27
交易金额      653
Name: 4684, dtype: int64
内部标识号    4686
交易次数       17
交易金额     5612
Name: 4685, dtype: int64
内部标识号     4687
交易次数        95
交易金额     77471
Name: 4686, dtype: int64
内部标识号    4688
交易次数        0
交易金额     2173
Name: 4687, dtype: int64
内部标识号     4689
交易次数         8
交易金额     39833
Name: 4688, dtype: int64
内部标识号     4690
交易次数       232
交易金额     17578
Name: 4689, dtype: int64
内部标识号    4691
交易次数        8
交易金额      279
Name: 4690, dtype: int64
内部标识号    4692
交易次数       28
交易金额       33
Name: 4691, dtype: int64
内部标识号    4693
交易次数       14
交易金额      972
Name: 4692, dtype: int64
内部标识号    4694
交易次数        2
交易金额      998
Name: 4693, dtype: int64
内部标识号    4695
交易次数       10
交易金额      892
Name: 4694, dtype: int64
内部标识号    4696
交易次数        9
交易金额      908
Name: 4695, dtype: int64
内部标识号    4697
交易次数        0
交易金额     7256
Name: 4696, dtype: int64
内部标识号    4698
交易次数        0
交易金额     7916
Name: 4697, dtype: int64
内部标识号    4699
交易次数        5
交易金额      265
Name: 4698, dtype: int64
内部标识号    4700
交易次数        1
交易金额      981
Name: 4699, dtype: int64
内部标识号    4701
交易次数        8
交易金额      264
Name: 4700, dtype: int64
内部标识号    4702
交易次数       13
交易金额      697
Name: 4701, dtype: int64
内部标识号    4703
交易次数        7
交易金额      286
Name: 4702, dtype: int64
内部标识号    4704
交易次数        1
交易金额      656
Name: 4703, dtype: int64
内部标识号    4705
交易次数       18
交易金额     9420
Name: 4704, dtype: int64
内部标识号     4706
交易次数         7
交易金额     13759
Name: 4705, dtype: int64
内部标识号     4707
交易次数       193
交易金额     62625
Name: 4706, dtype: int64
内部标识号    4708
交易次数        2
交易金额      515
Name: 4707, dtype: int64
内部标识号    4709
交易次数        3
交易金额      401
Name: 4708, dtype: int64
内部标识号    4710
交易次数       11
交易金额     1000
Name: 4709, dtype: int64
内部标识号    4711
交易次数        9
交易金额      371
Name: 4710, dtype: int64
内部标识号    4712
交易次数        0
交易金额     8210
Name: 4711, dtype: int64
内部标识号    4713
交易次数       10
交易金额      969
Name: 4712, dtype: int64
内部标识号    4714
交易次数        1
交易金额      794
Name: 4713, dtype: int64
内部标识号    4715
交易次数       11
交易金额      877
Name: 4714, dtype: int64
内部标识号    4716
交易次数       12
交易金额      349
Name: 4715, dtype: int64
内部标识号    4717
交易次数       21
交易金额     4350
Name: 4716, dtype: int64
内部标识号    4718
交易次数        8
交易金额      568
Name: 4717, dtype: int64
内部标识号     4719
交易次数       263
交易金额     74885
Name: 4718, dtype: int64
内部标识号    4720
交易次数        0
交易金额     2249
Name: 4719, dtype: int64
内部标识号    4721
交易次数       17
交易金额       59
Name: 4720, dtype: int64
内部标识号    4722
交易次数       13
交易金额      308
Name: 4721, dtype: int64
内部标识号    4723
交易次数       11
交易金额      536
Name: 4722, dtype: int64
内部标识号    4724
交易次数        2
交易金额      999
Name: 4723, dtype: int64
内部标识号    4725
交易次数       20
交易金额     2827
Name: 4724, dtype: int64
内部标识号    4726
交易次数        2
交易金额      305
Name: 4725, dtype: int64
内部标识号    4727
交易次数       11
交易金额      388
Name: 4726, dtype: int64
内部标识号    4728
交易次数        7
交易金额      169
Name: 4727, dtype: int64
内部标识号    4729
交易次数       12
交易金额      417
Name: 4728, dtype: int64
内部标识号     4730
交易次数         7
交易金额     13011
Name: 4729, dtype: int64
内部标识号    4731
交易次数       12
交易金额      303
Name: 4730, dtype: int64
内部标识号    4732
交易次数        2
交易金额      443
Name: 4731, dtype: int64
内部标识号    4733
交易次数       13
交易金额      614
Name: 4732, dtype: int64
内部标识号    4734
交易次数        9
交易金额      908
Name: 4733, dtype: int64
内部标识号     4735
交易次数         8
交易金额     45687
Name: 4734, dtype: int64
内部标识号    4736
交易次数        3
交易金额      392
Name: 4735, dtype: int64
内部标识号    4737
交易次数        0
交易金额     2203
Name: 4736, dtype: int64
内部标识号    4738
交易次数        5
交易金额      160
Name: 4737, dtype: int64
内部标识号    4739
交易次数        3
交易金额      226
Name: 4738, dtype: int64
内部标识号    4740
交易次数       11
交易金额      552
Name: 4739, dtype: int64
内部标识号    4741
交易次数       13
交易金额      479
Name: 4740, dtype: int64
内部标识号    4742
交易次数        3
交易金额      211
Name: 4741, dtype: int64
内部标识号    4743
交易次数       28
交易金额     4582
Name: 4742, dtype: int64
内部标识号    4744
交易次数        1
交易金额      579
Name: 4743, dtype: int64
内部标识号    4745
交易次数        2
交易金额      148
Name: 4744, dtype: int64
内部标识号    4746
交易次数       21
交易金额     5309
Name: 4745, dtype: int64
内部标识号    4747
交易次数       13
交易金额      316
Name: 4746, dtype: int64
内部标识号    4748
交易次数       13
交易金额      945
Name: 4747, dtype: int64
内部标识号    4749
交易次数       30
交易金额      976
Name: 4748, dtype: int64
内部标识号    4750
交易次数        1
交易金额     5324
Name: 4749, dtype: int64
内部标识号    4751
交易次数        4
交易金额      268
Name: 4750, dtype: int64
内部标识号    4752
交易次数       14
交易金额      570
Name: 4751, dtype: int64
内部标识号    4753
交易次数       10
交易金额      754
Name: 4752, dtype: int64
内部标识号    4754
交易次数        9
交易金额      711
Name: 4753, dtype: int64
内部标识号    4755
交易次数        2
交易金额      857
Name: 4754, dtype: int64
内部标识号     4756
交易次数       275
交易金额     18175
Name: 4755, dtype: int64
内部标识号    4757
交易次数        9
交易金额      447
Name: 4756, dtype: int64
内部标识号    4758
交易次数        3
交易金额      399
Name: 4757, dtype: int64
内部标识号    4759
交易次数        8
交易金额      985
Name: 4758, dtype: int64
内部标识号    4760
交易次数        7
交易金额      271
Name: 4759, dtype: int64
内部标识号    4761
交易次数       12
交易金额      432
Name: 4760, dtype: int64
内部标识号    4762
交易次数        3
交易金额      332
Name: 4761, dtype: int64
内部标识号    4763
交易次数        3
交易金额      465
Name: 4762, dtype: int64
内部标识号    4764
交易次数        3
交易金额      485
Name: 4763, dtype: int64
内部标识号    4765
交易次数        7
交易金额      282
Name: 4764, dtype: int64
内部标识号    4766
交易次数       21
交易金额     1594
Name: 4765, dtype: int64
内部标识号    4767
交易次数        8
交易金额      320
Name: 4766, dtype: int64
内部标识号    4768
交易次数       14
交易金额      760
Name: 4767, dtype: int64
内部标识号    4769
交易次数        4
交易金额      266
Name: 4768, dtype: int64
内部标识号    4770
交易次数        7
交易金额      199
Name: 4769, dtype: int64

内部标识号    4771
交易次数        8
交易金额      104
Name: 4770, dtype: int64
内部标识号    4772
交易次数        3
交易金额      167
Name: 4771, dtype: int64
内部标识号    4773
交易次数        0
交易金额     9085
Name: 4772, dtype: int64
内部标识号    4774
交易次数        3
交易金额      329
Name: 4773, dtype: int64
内部标识号    4775
交易次数        8
交易金额      497
Name: 4774, dtype: int64
内部标识号    4776
交易次数       14
交易金额      393
Name: 4775, dtype: int64
内部标识号    4777
交易次数       15
交易金额      900
Name: 4776, dtype: int64
内部标识号    4778
交易次数       11
交易金额      305
Name: 4777, dtype: int64
内部标识号    4779
交易次数       14
交易金额      368
Name: 4778, dtype: int64
内部标识号    4780
交易次数        8
交易金额      266
Name: 4779, dtype: int64
内部标识号    4781
交易次数        5
交易金额      171
Name: 4780, dtype: int64
内部标识号    4782
交易次数        2
交易金额      525
Name: 4781, dtype: int64
内部标识号     4783
交易次数         8
交易金额     43631
Name: 4782, dtype: int64
内部标识号    4784
交易次数       13
交易金额      435
Name: 4783, dtype: int64
内部标识号    4785
交易次数        1
交易金额      550
Name: 4784, dtype: int64
内部标识号    4786
交易次数        9
交易金额      872
Name: 4785, dtype: int64
内部标识号    4787
交易次数       18
交易金额     9653
Name: 4786, dtype: int64
内部标识号    4788
交易次数       10
交易金额      429
Name: 4787, dtype: int64
内部标识号     4789
交易次数        92
交易金额     31952
Name: 4788, dtype: int64
内部标识号    4790
交易次数        8
交易金额      636
Name: 4789, dtype: int64
内部标识号    4791
交易次数        2
交易金额      194
Name: 4790, dtype: int64
内部标识号    4792
交易次数       15
交易金额     8246
Name: 4791, dtype: int64
内部标识号    4793
交易次数        2
交易金额      606
Name: 4792, dtype: int64
内部标识号    4794
交易次数        3
交易金额      435
Name: 4793, dtype: int64
内部标识号    4795
交易次数        2
交易金额      375
Name: 4794, dtype: int64
内部标识号    4796
交易次数        9
交易金额      980
Name: 4795, dtype: int64
内部标识号    4797
交易次数       12
交易金额      636
Name: 4796, dtype: int64
内部标识号    4798
交易次数        9
交易金额      838
Name: 4797, dtype: int64
内部标识号    4799
交易次数        2
交易金额      321
Name: 4798, dtype: int64
内部标识号    4800
交易次数        2
交易金额      394
Name: 4799, dtype: int64
内部标识号    4801
交易次数       19
交易金额      889
Name: 4800, dtype: int64
内部标识号    4802
交易次数        0
交易金额     8992
Name: 4801, dtype: int64
内部标识号    4803
交易次数       14
交易金额      569
Name: 4802, dtype: int64
内部标识号    4804
交易次数       14
交易金额      446
Name: 4803, dtype: int64
内部标识号     4805
交易次数       140
交易金额     22987
Name: 4804, dtype: int64
内部标识号    4806
交易次数       14
交易金额      376
Name: 4805, dtype: int64
内部标识号    4807
交易次数       24
交易金额     9760
Name: 4806, dtype: int64
内部标识号    4808
交易次数        2
交易金额      281
Name: 4807, dtype: int64
内部标识号    4809
交易次数       14
交易金额      846
Name: 4808, dtype: int64
内部标识号    4810
交易次数       19
交易金额     3098
Name: 4809, dtype: int64
内部标识号    4811
交易次数       30
交易金额     9520
Name: 4810, dtype: int64
内部标识号    4812
交易次数       12
交易金额      970
Name: 4811, dtype: int64
内部标识号    4813
交易次数       15
交易金额     3017
Name: 4812, dtype: int64
内部标识号    4814
交易次数        2
交易金额      448
Name: 4813, dtype: int64
内部标识号    4815
交易次数        1
交易金额     1306
Name: 4814, dtype: int64
内部标识号    4816
交易次数        2
交易金额      475
Name: 4815, dtype: int64
内部标识号    4817
交易次数        3
交易金额      435
Name: 4816, dtype: int64
内部标识号    4818
交易次数        2
交易金额      364
Name: 4817, dtype: int64
内部标识号    4819
交易次数        9
交易金额      602
Name: 4818, dtype: int64
内部标识号    4820
交易次数       14
交易金额      712
Name: 4819, dtype: int64
内部标识号     4821
交易次数         5
交易金额     54822
Name: 4820, dtype: int64
内部标识号    4822
交易次数        7
交易金额      211
Name: 4821, dtype: int64
内部标识号    4823
交易次数       11
交易金额      810
Name: 4822, dtype: int64
内部标识号    4824
交易次数        3
交易金额      223
Name: 4823, dtype: int64
内部标识号    4825
交易次数        2
交易金额      453
Name: 4824, dtype: int64
内部标识号    4826
交易次数        3
交易金额      492
Name: 4825, dtype: int64
内部标识号    4827
交易次数        0
交易金额     9683
Name: 4826, dtype: int64
内部标识号    4828
交易次数        3
交易金额      185
Name: 4827, dtype: int64
内部标识号    4829
交易次数       10
交易金额      800
Name: 4828, dtype: int64
内部标识号    4830
交易次数        0
交易金额     1916
Name: 4829, dtype: int64
内部标识号    4831
交易次数        9
交易金额      429
Name: 4830, dtype: int64
内部标识号     4832
交易次数       199
交易金额     22505
Name: 4831, dtype: int64
内部标识号    4833
交易次数        3
交易金额      398
Name: 4832, dtype: int64
内部标识号    4834
交易次数        7
交易金额      255
Name: 4833, dtype: int64
内部标识号    4835
交易次数       24
交易金额     5453
Name: 4834, dtype: int64
内部标识号    4836
交易次数        7
交易金额      286
Name: 4835, dtype: int64
内部标识号    4837
交易次数       11
交易金额      596
Name: 4836, dtype: int64
内部标识号    4838
交易次数        8
交易金额      216
Name: 4837, dtype: int64
内部标识号    4839
交易次数        1
交易金额      992
Name: 4838, dtype: int64
内部标识号    4840
交易次数       15
交易金额      435
Name: 4839, dtype: int64
内部标识号    4841
交易次数        1
交易金额     4282
Name: 4840, dtype: int64
内部标识号    4842
交易次数        0
交易金额     4086
Name: 4841, dtype: int64
内部标识号     4843
交易次数       260
交易金额     84876
Name: 4842, dtype: int64
内部标识号    4844
交易次数       10
交易金额      670
Name: 4843, dtype: int64
内部标识号    4845
交易次数        3
交易金额      312
Name: 4844, dtype: int64
内部标识号    4846
交易次数       13
交易金额      815
Name: 4845, dtype: int64
内部标识号    4847
交易次数        9
交易金额      946
Name: 4846, dtype: int64
内部标识号    4848
交易次数        2
交易金额      309
Name: 4847, dtype: int64
内部标识号     4849
交易次数         7
交易金额     97446
Name: 4848, dtype: int64
内部标识号    4850
交易次数        0
交易金额     5640
Name: 4849, dtype: int64
内部标识号    4851
交易次数       16
交易金额     4604
Name: 4850, dtype: int64
内部标识号    4852
交易次数        2
交易金额      642
Name: 4851, dtype: int64
内部标识号    4853
交易次数        3
交易金额      333
Name: 4852, dtype: int64
内部标识号    4854
交易次数       12
交易金额      533
Name: 4853, dtype: int64
内部标识号    4855
交易次数        1
交易金额      516
Name: 4854, dtype: int64
内部标识号    4856
交易次数        2
交易金额      342
Name: 4855, dtype: int64
内部标识号    4857
交易次数        9
交易金额      444
Name: 4856, dtype: int64
内部标识号    4858
交易次数        2
交易金额      880
Name: 4857, dtype: int64
内部标识号    4859
交易次数       10
交易金额      620
Name: 4858, dtype: int64
内部标识号    4860
交易次数        2
交易金额      345
Name: 4859, dtype: int64
内部标识号    4861
交易次数       10
交易金额      805
Name: 4860, dtype: int64
内部标识号    4862
交易次数        1
交易金额      724
Name: 4861, dtype: int64
内部标识号    4863
交易次数        2
交易金额      813
Name: 4862, dtype: int64
内部标识号    4864
交易次数       27
交易金额      552
Name: 4863, dtype: int64
内部标识号    4865
交易次数        0
交易金额     9760
Name: 4864, dtype: int64
内部标识号    4866
交易次数       15
交易金额      371
Name: 4865, dtype: int64
内部标识号    4867
交易次数        6
交易金额      172
Name: 4866, dtype: int64
内部标识号    4868
交易次数       12
交易金额      934
Name: 4867, dtype: int64
内部标识号    4869
交易次数        6
交易金额      276
Name: 4868, dtype: int64
内部标识号    4870
交易次数        0
交易金额     3448
Name: 4869, dtype: int64
内部标识号    4871
交易次数        0
交易金额     8541
Name: 4870, dtype: int64
内部标识号    4872
交易次数       27
交易金额      866
Name: 4871, dtype: int64
内部标识号    4873
交易次数       12
交易金额      681
Name: 4872, dtype: int64
内部标识号    4874
交易次数        3
交易金额      480
Name: 4873, dtype: int64
内部标识号    4875
交易次数       13
交易金额      365
Name: 4874, dtype: int64
内部标识号    4876
交易次数       14
交易金额      636
Name: 4875, dtype: int64
内部标识号     4877
交易次数         6
交易金额     38651
Name: 4876, dtype: int64
内部标识号    4878
交易次数       14
交易金额      970
Name: 4877, dtype: int64
内部标识号     4879
交易次数         5
交易金额     45201
Name: 4878, dtype: int64
内部标识号    4880
交易次数       21
交易金额     4428
Name: 4879, dtype: int64
内部标识号    4881
交易次数        2
交易金额      916
Name: 4880, dtype: int64
内部标识号    4882
交易次数        0
交易金额     4177
Name: 4881, dtype: int64
内部标识号    4883
交易次数        4
交易金额      240
Name: 4882, dtype: int64
内部标识号    4884
交易次数       14
交易金额      318
Name: 4883, dtype: int64
内部标识号    4885
交易次数        5
交易金额      206
Name: 4884, dtype: int64
内部标识号    4886
交易次数       25
交易金额     4766
Name: 4885, dtype: int64
内部标识号    4887
交易次数       13
交易金额      769
Name: 4886, dtype: int64
内部标识号    4888
交易次数        4
交易金额      148
Name: 4887, dtype: int64
内部标识号    4889
交易次数        2
交易金额      443
Name: 4888, dtype: int64
内部标识号    4890
交易次数       20
交易金额     8433
Name: 4889, dtype: int64
内部标识号    4891
交易次数       10
交易金额      693
Name: 4890, dtype: int64
内部标识号     4892
交易次数       236
交易金额     20848
Name: 4891, dtype: int64
内部标识号    4893
交易次数        3
交易金额      334
Name: 4892, dtype: int64
内部标识号    4894
交易次数        2
交易金额      632
Name: 4893, dtype: int64
内部标识号    4895
交易次数        8
交易金额      997
Name: 4894, dtype: int64
内部标识号    4896
交易次数        7
交易金额      272
Name: 4895, dtype: int64
内部标识号    4897
交易次数        2
交易金额      685
Name: 4896, dtype: int64
内部标识号    4898
交易次数        7
交易金额      252
Name: 4897, dtype: int64
内部标识号    4899
交易次数       14
交易金额      978
Name: 4898, dtype: int64
内部标识号    4900
交易次数       20
交易金额     1308
Name: 4899, dtype: int64
内部标识号    4901
交易次数       13
交易金额      658
Name: 4900, dtype: int64
内部标识号    4902
交易次数        0
交易金额     5310
Name: 4901, dtype: int64
内部标识号    4903
交易次数        1
交易金额     7939
Name: 4902, dtype: int64
内部标识号    4904
交易次数       24
交易金额      515
Name: 4903, dtype: int64
内部标识号    4905
交易次数        3
交易金额      146
Name: 4904, dtype: int64
内部标识号     4906
交易次数         6
交易金额     73250
Name: 4905, dtype: int64
内部标识号     4907
交易次数        52
交易金额     97986
Name: 4906, dtype: int64
内部标识号    4908
交易次数       12
交易金额      802
Name: 4907, dtype: int64
内部标识号    4909
交易次数        2
交易金额      921
Name: 4908, dtype: int64
内部标识号    4910
交易次数        8
交易金额      929
Name: 4909, dtype: int64
内部标识号    4911
交易次数        8
交易金额      298
Name: 4910, dtype: int64
内部标识号     4912
交易次数       174
交易金额     61882
Name: 4911, dtype: int64
内部标识号    4913
交易次数        0
交易金额     3546
Name: 4912, dtype: int64
内部标识号    4914
交易次数       10
交易金额      973
Name: 4913, dtype: int64
内部标识号    4915
交易次数        6
交易金额      191
Name: 4914, dtype: int64
内部标识号    4916
交易次数        0
交易金额     2161
Name: 4915, dtype: int64
内部标识号    4917
交易次数       13
交易金额      525
Name: 4916, dtype: int64
内部标识号    4918
交易次数        3
交易金额      149
Name: 4917, dtype: int64
内部标识号    4919
交易次数       26
交易金额     3475
Name: 4918, dtype: int64
内部标识号    4920
交易次数        8
交易金额      782
Name: 4919, dtype: int64
内部标识号     4921
交易次数         5
交易金额     99225
Name: 4920, dtype: int64
内部标识号    4922
交易次数        6
交易金额      182
Name: 4921, dtype: int64
内部标识号    4923
交易次数        4
交易金额      165
Name: 4922, dtype: int64
内部标识号    4924
交易次数       14
交易金额      549
Name: 4923, dtype: int64
内部标识号    4925
交易次数       14
交易金额      624
Name: 4924, dtype: int64
内部标识号     4926
交易次数         8
交易金额     80024
Name: 4925, dtype: int64
内部标识号     4927
交易次数         8
交易金额     98821
Name: 4926, dtype: int64
内部标识号    4928
交易次数        9
交易金额      406
Name: 4927, dtype: int64
内部标识号    4929
交易次数        2
交易金额      841
Name: 4928, dtype: int64
内部标识号    4930
交易次数        3
交易金额      420
Name: 4929, dtype: int64
内部标识号    4931
交易次数       13
交易金额      371
Name: 4930, dtype: int64
内部标识号    4932
交易次数        9
交易金额      510
Name: 4931, dtype: int64
内部标识号    4933
交易次数       14
交易金额      329
Name: 4932, dtype: int64
内部标识号    4934
交易次数       10
交易金额      484
Name: 4933, dtype: int64
内部标识号    4935
交易次数       12
交易金额      797
Name: 4934, dtype: int64
内部标识号    4936
交易次数       10
交易金额      322
Name: 4935, dtype: int64
内部标识号    4937
交易次数        1
交易金额      963
Name: 4936, dtype: int64
内部标识号    4938
交易次数        3
交易金额      441
Name: 4937, dtype: int64
内部标识号    4939
交易次数        5
交易金额      132
Name: 4938, dtype: int64
内部标识号    4940
交易次数        1
交易金额     1307
Name: 4939, dtype: int64
内部标识号    4941
交易次数       14
交易金额      927
Name: 4940, dtype: int64
内部标识号    4942
交易次数        2
交易金额      192
Name: 4941, dtype: int64
内部标识号    4943
交易次数        8
交易金额      250
Name: 4942, dtype: int64
内部标识号    4944
交易次数       19
交易金额      548
Name: 4943, dtype: int64
内部标识号    4945
交易次数       12
交易金额      333
Name: 4944, dtype: int64
内部标识号    4946
交易次数       15
交易金额      699
Name: 4945, dtype: int64
内部标识号    4947
交易次数        8
交易金额      152
Name: 4946, dtype: int64
内部标识号     4948
交易次数       139
交易金额     77348
Name: 4947, dtype: int64
内部标识号    4949
交易次数        0
交易金额     6909
Name: 4948, dtype: int64
内部标识号    4950
交易次数       10
交易金额      422
Name: 4949, dtype: int64
内部标识号    4951
交易次数        9
交易金额      904
Name: 4950, dtype: int64
内部标识号    4952
交易次数        8
交易金额      184
Name: 4951, dtype: int64
内部标识号    4953
交易次数        6
交易金额      193
Name: 4952, dtype: int64
内部标识号    4954
交易次数       13
交易金额      787
Name: 4953, dtype: int64
内部标识号    4955
交易次数        3
交易金额      400
Name: 4954, dtype: int64
内部标识号    4956
交易次数       11
交易金额      351
Name: 4955, dtype: int64
内部标识号    4957
交易次数        9
交易金额      729
Name: 4956, dtype: int64
内部标识号    4958
交易次数        2
交易金额      470
Name: 4957, dtype: int64
内部标识号     4959
交易次数         6
交易金额     14998
Name: 4958, dtype: int64
内部标识号    4960
交易次数        2
交易金额      470
Name: 4959, dtype: int64
内部标识号    4961
交易次数       11
交易金额      330
Name: 4960, dtype: int64
内部标识号    4962
交易次数        1
交易金额      577
Name: 4961, dtype: int64
内部标识号    4963
交易次数       12
交易金额      759
Name: 4962, dtype: int64
内部标识号    4964
交易次数       13
交易金额      467
Name: 4963, dtype: int64
内部标识号    4965
交易次数        2
交易金额      365
Name: 4964, dtype: int64
内部标识号    4966
交易次数        3
交易金额      363
Name: 4965, dtype: int64
内部标识号    4967
交易次数        0
交易金额     9827
Name: 4966, dtype: int64
内部标识号    4968
交易次数        7
交易金额      105
Name: 4967, dtype: int64
内部标识号    4969
交易次数        2
交易金额      649
Name: 4968, dtype: int64
内部标识号    4970
交易次数        4
交易金额      234
Name: 4969, dtype: int64
内部标识号    4971
交易次数        9
交易金额      617
Name: 4970, dtype: int64
内部标识号    4972
交易次数        1
交易金额      535
Name: 4971, dtype: int64
内部标识号    4973
交易次数        8
交易金额      826
Name: 4972, dtype: int64
内部标识号    4974
交易次数       11
交易金额      918
Name: 4973, dtype: int64
内部标识号    4975
交易次数        4
交易金额      129
Name: 4974, dtype: int64
内部标识号    4976
交易次数       25
交易金额      669
Name: 4975, dtype: int64
内部标识号    4977
交易次数       22
交易金额     8036
Name: 4976, dtype: int64
内部标识号    4978
交易次数        4
交易金额      278
Name: 4977, dtype: int64
内部标识号    4979
交易次数        5
交易金额      278
Name: 4978, dtype: int64
内部标识号    4980
交易次数        2
交易金额      356
Name: 4979, dtype: int64
内部标识号    4981
交易次数        2
交易金额      959
Name: 4980, dtype: int64
内部标识号    4982
交易次数        8
交易金额      409
Name: 4981, dtype: int64
内部标识号    4983
交易次数        7
交易金额      252
Name: 4982, dtype: int64
内部标识号    4984
交易次数       18
交易金额     7973
Name: 4983, dtype: int64
内部标识号    4985
交易次数        1
交易金额      742
Name: 4984, dtype: int64
内部标识号    4986
交易次数        2
交易金额      479
Name: 4985, dtype: int64
内部标识号    4987
交易次数       14
交易金额      714
Name: 4986, dtype: int64
内部标识号    4988
交易次数        3
交易金额      115
Name: 4987, dtype: int64
内部标识号    4989
交易次数       21
交易金额     5460
Name: 4988, dtype: int64
内部标识号     4990
交易次数       297
交易金额     67960
Name: 4989, dtype: int64
内部标识号    4991
交易次数        1
交易金额      816
Name: 4990, dtype: int64
内部标识号     4992
交易次数       105
交易金额     52340
Name: 4991, dtype: int64
内部标识号    4993
交易次数       26
交易金额     2498
Name: 4992, dtype: int64
内部标识号    4994
交易次数        4
交易金额      235
Name: 4993, dtype: int64
内部标识号     4995
交易次数         3
交易金额     54930
Name: 4994, dtype: int64
内部标识号    4996
交易次数       14
交易金额      542
Name: 4995, dtype: int64
内部标识号    4997
交易次数        2
交易金额      908
Name: 4996, dtype: int64
内部标识号    4998
交易次数        3
交易金额      257
Name: 4997, dtype: int64
内部标识号     4999
交易次数         3
交易金额     53571
Name: 4998, dtype: int64
内部标识号    5000
交易次数       15
交易金额      361
Name: 4999, dtype: int64
内部标识号    5001
交易次数        9
交易金额      608
Name: 5000, dtype: int64
内部标识号    5002
交易次数        3
交易金额      309
Name: 5001, dtype: int64
内部标识号    5003
交易次数       28
交易金额       46
Name: 5002, dtype: int64
内部标识号    5004
交易次数       15
交易金额      944
Name: 5003, dtype: int64
内部标识号    5005
交易次数       15
交易金额      314
Name: 5004, dtype: int64
内部标识号    5006
交易次数        2
交易金额      443
Name: 5005, dtype: int64
内部标识号    5007
交易次数        1
交易金额      806
Name: 5006, dtype: int64
内部标识号     5008
交易次数         3
交易金额     78392
Name: 5007, dtype: int64
内部标识号    5009
交易次数        0
交易金额     3335
Name: 5008, dtype: int64
内部标识号    5010
交易次数        2
交易金额      525
Name: 5009, dtype: int64
内部标识号    5011
交易次数       14
交易金额      682
Name: 5010, dtype: int64
内部标识号    5012
交易次数        2
交易金额      916
Name: 5011, dtype: int64
内部标识号    5013
交易次数        4
交易金额      193
Name: 5012, dtype: int64
内部标识号    5014
交易次数        4
交易金额      249
Name: 5013, dtype: int64
内部标识号    5015
交易次数        2
交易金额      858
Name: 5014, dtype: int64
内部标识号    5016
交易次数       24
交易金额      605
Name: 5015, dtype: int64
内部标识号    5017
交易次数        2
交易金额      446
Name: 5016, dtype: int64
内部标识号    5018
交易次数        9
交易金额      733
Name: 5017, dtype: int64
内部标识号    5019
交易次数       21
交易金额     4467
Name: 5018, dtype: int64
内部标识号    5020
交易次数       10
交易金额      674
Name: 5019, dtype: int64
内部标识号    5021
交易次数       15
交易金额      369
Name: 5020, dtype: int64
内部标识号    5022
交易次数        2
交易金额      486
Name: 5021, dtype: int64
内部标识号     5023
交易次数         5
交易金额     96565
Name: 5022, dtype: int64
内部标识号    5024
交易次数       15
交易金额      548
Name: 5023, dtype: int64
内部标识号    5025
交易次数        6
交易金额      234
Name: 5024, dtype: int64
内部标识号    5026
交易次数        0
交易金额     4939
Name: 5025, dtype: int64
内部标识号    5027
交易次数        2
交易金额      921
Name: 5026, dtype: int64
内部标识号    5028
交易次数        2
交易金额      972
Name: 5027, dtype: int64
内部标识号    5029
交易次数       20
交易金额      852
Name: 5028, dtype: int64
内部标识号    5030
交易次数        4
交易金额      285
Name: 5029, dtype: int64
内部标识号    5031
交易次数       12
交易金额      513
Name: 5030, dtype: int64
内部标识号    5032
交易次数       11
交易金额      809
Name: 5031, dtype: int64
内部标识号    5033
交易次数        5
交易金额      274
Name: 5032, dtype: int64
内部标识号    5034
交易次数        2
交易金额      500
Name: 5033, dtype: int64
内部标识号    5035
交易次数        3
交易金额      493
Name: 5034, dtype: int64
内部标识号    5036
交易次数        3
交易金额      355
Name: 5035, dtype: int64
内部标识号    5037
交易次数        4
交易金额      260
Name: 5036, dtype: int64
内部标识号    5038
交易次数        9
交易金额      485
Name: 5037, dtype: int64
内部标识号    5039
交易次数        3
交易金额      185
Name: 5038, dtype: int64
内部标识号     5040
交易次数         8
交易金额     65337
Name: 5039, dtype: int64
内部标识号    5041
交易次数        2
交易金额      551
Name: 5040, dtype: int64
内部标识号    5042
交易次数        6
交易金额      253
Name: 5041, dtype: int64
内部标识号    5043
交易次数        2
交易金额      469
Name: 5042, dtype: int64
内部标识号    5044
交易次数        2
交易金额      328
Name: 5043, dtype: int64
内部标识号    5045
交易次数       19
交易金额      747
Name: 5044, dtype: int64
内部标识号    5046
交易次数       14
交易金额      472
Name: 5045, dtype: int64
内部标识号    5047
交易次数       12
交易金额      476
Name: 5046, dtype: int64
内部标识号    5048
交易次数        7
交易金额      272
Name: 5047, dtype: int64
内部标识号    5049
交易次数       24
交易金额      653
Name: 5048, dtype: int64
内部标识号    5050
交易次数        0
交易金额     5446
Name: 5049, dtype: int64
内部标识号    5051
交易次数        4
交易金额      250
Name: 5050, dtype: int64
内部标识号    5052
交易次数        8
交易金额      709
Name: 5051, dtype: int64
内部标识号    5053
交易次数       17
交易金额     3231
Name: 5052, dtype: int64
内部标识号     5054
交易次数         7
交易金额     72308
Name: 5053, dtype: int64
内部标识号    5055
交易次数        2
交易金额      643
Name: 5054, dtype: int64
内部标识号    5056
交易次数        1
交易金额     2220
Name: 5055, dtype: int64
内部标识号    5057
交易次数        7
交易金额      100
Name: 5056, dtype: int64
内部标识号    5058
交易次数        3
交易金额      128
Name: 5057, dtype: int64
内部标识号    5059
交易次数       15
交易金额      554
Name: 5058, dtype: int64
内部标识号    5060
交易次数        2
交易金额      651
Name: 5059, dtype: int64
内部标识号     5061
交易次数       149
交易金额     65905
Name: 5060, dtype: int64
内部标识号    5062
交易次数       18
交易金额     4771
Name: 5061, dtype: int64
内部标识号    5063
交易次数       10
交易金额      483
Name: 5062, dtype: int64
内部标识号    5064
交易次数       10
交易金额      528
Name: 5063, dtype: int64
内部标识号    5065
交易次数        3
交易金额      167
Name: 5064, dtype: int64
内部标识号    5066
交易次数       28
交易金额      550
Name: 5065, dtype: int64
内部标识号    5067
交易次数        2
交易金额      559
Name: 5066, dtype: int64
内部标识号     5068

Name: 5179, dtype: int64
内部标识号    5181
交易次数       13
交易金额      364
Name: 5180, dtype: int64
内部标识号    5182
交易次数       25
交易金额      940
Name: 5181, dtype: int64
内部标识号    5183
交易次数        2
交易金额      629
Name: 5182, dtype: int64
内部标识号    5184
交易次数       14
交易金额      372
Name: 5183, dtype: int64
内部标识号    5185
交易次数        1
交易金额      773
Name: 5184, dtype: int64
内部标识号    5186
交易次数       14
交易金额      585
Name: 5185, dtype: int64
内部标识号    5187
交易次数        9
交易金额      724
Name: 5186, dtype: int64
内部标识号    5188
交易次数       14
交易金额      672
Name: 5187, dtype: int64
内部标识号    5189
交易次数        1
交易金额      910
Name: 5188, dtype: int64
内部标识号    5190
交易次数        1
交易金额      744
Name: 5189, dtype: int64
内部标识号    5191
交易次数       22
交易金额     4838
Name: 5190, dtype: int64
内部标识号    5192
交易次数       15
交易金额      869
Name: 5191, dtype: int64
内部标识号    5193
交易次数        2
交易金额      833
Name: 5192, dtype: int64
内部标识号    5194
交易次数        5
交易金额      149
Name: 5193, dtype: int64
内部标识号    5195
交易次数        3
交易金额      200
Name: 5194, dtype: int64
内部标识号    5196
交易次数       14
交易金额      501
Name: 5195, dtype: int64
内部标识号    5197
交易次数        8
交易金额      250
Name: 5196, dtype: int64
内部标识号    5198
交易次数        1
交易金额      674
Name: 5197, dtype: int64
内部标识号     5199
交易次数         4
交易金额     75032
Name: 5198, dtype: int64
内部标识号     5200
交易次数        41
交易金额     96972
Name: 5199, dtype: int64
内部标识号    5201
交易次数        0
交易金额     2173
Name: 5200, dtype: int64
内部标识号    5202
交易次数        5
交易金额      265
Name: 5201, dtype: int64
内部标识号    5203
交易次数        2
交易金额      394
Name: 5202, dtype: int64
内部标识号    5204
交易次数        8
交易金额      101
Name: 5203, dtype: int64
内部标识号    5205
交易次数        3
交易金额      233
Name: 5204, dtype: int64
内部标识号    5206
交易次数       14
交易金额      339
Name: 5205, dtype: int64
内部标识号    5207
交易次数        0
交易金额     2685
Name: 5206, dtype: int64
内部标识号    5208
交易次数       11
交易金额      373
Name: 5207, dtype: int64
内部标识号    5209
交易次数        5
交易金额      166
Name: 5208, dtype: int64
内部标识号    5210
交易次数       10
交易金额      346
Name: 5209, dtype: int64
内部标识号    5211
交易次数        2
交易金额      364
Name: 5210, dtype: int64
内部标识号    5212
交易次数        1
交易金额      837
Name: 5211, dtype: int64
内部标识号    5213
交易次数       13
交易金额      462
Name: 5212, dtype: int64
内部标识号    5214
交易次数        3
交易金额      470
Name: 5213, dtype: int64
内部标识号    5215
交易次数        0
交易金额     5166
Name: 5214, dtype: int64
内部标识号    5216
交易次数       21
交易金额       71
Name: 5215, dtype: int64
内部标识号    5217
交易次数        0
交易金额     7531
Name: 5216, dtype: int64
内部标识号    5218
交易次数       14
交易金额      502
Name: 5217, dtype: int64
内部标识号    5219
交易次数        2
交易金额      417
Name: 5218, dtype: int64
内部标识号    5220
交易次数        2
交易金额      776
Name: 5219, dtype: int64
内部标识号    5221
交易次数       10
交易金额      477
Name: 5220, dtype: int64
内部标识号    5222
交易次数       14
交易金额      486
Name: 5221, dtype: int64
内部标识号    5223
交易次数        3
交易金额      232
Name: 5222, dtype: int64
内部标识号    5224
交易次数        1
交易金额      835
Name: 5223, dtype: int64
内部标识号    5225
交易次数       15
交易金额      533
Name: 5224, dtype: int64
内部标识号    5226
交易次数       12
交易金额      668
Name: 5225, dtype: int64
内部标识号     5227
交易次数        37
交易金额     48430
Name: 5226, dtype: int64
内部标识号    5228
交易次数       30
交易金额      750
Name: 5227, dtype: int64
内部标识号     5229
交易次数         8
交易金额     23367
Name: 5228, dtype: int64
内部标识号    5230
交易次数        3
交易金额      484
Name: 5229, dtype: int64
内部标识号    5231
交易次数       28
交易金额     7980
Name: 5230, dtype: int64
内部标识号    5232
交易次数        5
交易金额      141
Name: 5231, dtype: int64
内部标识号    5233
交易次数       13
交易金额      418
Name: 5232, dtype: int64
内部标识号    5234
交易次数       14
交易金额      485
Name: 5233, dtype: int64
内部标识号    5235
交易次数        1
交易金额      759
Name: 5234, dtype: int64
内部标识号    5236
交易次数        1
交易金额     2999
Name: 5235, dtype: int64
内部标识号    5237
交易次数        2
交易金额      470
Name: 5236, dtype: int64
内部标识号    5238
交易次数        9
交易金额      433
Name: 5237, dtype: int64
内部标识号    5239
交易次数       10
交易金额      632
Name: 5238, dtype: int64
内部标识号    5240
交易次数        9
交易金额      989
Name: 5239, dtype: int64
内部标识号    5241
交易次数       15
交易金额     6799
Name: 5240, dtype: int64
内部标识号    5242
交易次数        9
交易金额      954
Name: 5241, dtype: int64
内部标识号    5243
交易次数        8
交易金额      300
Name: 5242, dtype: int64
内部标识号    5244
交易次数       20
交易金额     2262
Name: 5243, dtype: int64
内部标识号     5245
交易次数         6
交易金额     93532
Name: 5244, dtype: int64
内部标识号    5246
交易次数        0
交易金额     4338
Name: 5245, dtype: int64
内部标识号    5247
交易次数        8
交易金额      133
Name: 5246, dtype: int64
内部标识号    5248
交易次数       24
交易金额      636
Name: 5247, dtype: int64
内部标识号    5249
交易次数        8
交易金额      319
Name: 5248, dtype: int64
内部标识号    5250
交易次数       28
交易金额      893
Name: 5249, dtype: int64
内部标识号    5251
交易次数        4
交易金额      207
Name: 5250, dtype: int64
内部标识号    5252
交易次数        6
交易金额      122
Name: 5251, dtype: int64
内部标识号    5253
交易次数       13
交易金额      833
Name: 5252, dtype: int64
内部标识号    5254
交易次数        2
交易金额      458
Name: 5253, dtype: int64
内部标识号    5255
交易次数       11
交易金额      367
Name: 5254, dtype: int64
内部标识号    5256
交易次数        2
交易金额      958
Name: 5255, dtype: int64
内部标识号    5257
交易次数        1
交易金额      649
Name: 5256, dtype: int64
内部标识号    5258
交易次数       10
交易金额      747
Name: 5257, dtype: int64
内部标识号    5259
交易次数        2
交易金额      188
Name: 5258, dtype: int64
内部标识号    5260
交易次数        1
交易金额     1930
Name: 5259, dtype: int64
内部标识号    5261
交易次数        3
交易金额      441
Name: 5260, dtype: int64
内部标识号    5262
交易次数        1
交易金额     3454
Name: 5261, dtype: int64
内部标识号    5263
交易次数        2
交易金额      322
Name: 5262, dtype: int64
内部标识号    5264
交易次数        2
交易金额      300
Name: 5263, dtype: int64
内部标识号     5265
交易次数       160
交易金额     84588
Name: 5264, dtype: int64
内部标识号    5266
交易次数       26
交易金额     9039
Name: 5265, dtype: int64
内部标识号    5267
交易次数        2
交易金额      295
Name: 5266, dtype: int64
内部标识号     5268
交易次数         6
交易金额     24451
Name: 5267, dtype: int64
内部标识号    5269
交易次数       21
交易金额     2107
Name: 5268, dtype: int64
内部标识号    5270
交易次数       25
交易金额      957
Name: 5269, dtype: int64
内部标识号     5271
交易次数         7
交易金额     57226
Name: 5270, dtype: int64
内部标识号    5272
交易次数        7
交易金额      164
Name: 5271, dtype: int64
内部标识号     5273
交易次数         3
交易金额     97572
Name: 5272, dtype: int64
内部标识号    5274
交易次数        6
交易金额      188
Name: 5273, dtype: int64
内部标识号    5275
交易次数       10
交易金额      631
Name: 5274, dtype: int64
内部标识号    5276
交易次数        7
交易金额      242
Name: 5275, dtype: int64
内部标识号    5277
交易次数       13
交易金额      620
Name: 5276, dtype: int64
内部标识号    5278
交易次数        8
交易金额      914
Name: 5277, dtype: int64
内部标识号    5279
交易次数        3
交易金额      200
Name: 5278, dtype: int64
内部标识号    5280
交易次数        0
交易金额     4129
Name: 5279, dtype: int64
内部标识号    5281
交易次数       11
交易金额      781
Name: 5280, dtype: int64
内部标识号    5282
交易次数        1
交易金额      948
Name: 5281, dtype: int64
内部标识号    5283
交易次数        8
交易金额      491
Name: 5282, dtype: int64
内部标识号    5284
交易次数        8
交易金额      136
Name: 5283, dtype: int64
内部标识号    5285
交易次数       13
交易金额      764
Name: 5284, dtype: int64
内部标识号    5286
交易次数        9
交易金额      530
Name: 5285, dtype: int64
内部标识号    5287
交易次数        1
交易金额      581
Name: 5286, dtype: int64
内部标识号    5288
交易次数       13
交易金额      314
Name: 5287, dtype: int64
内部标识号    5289
交易次数       25
交易金额     9366
Name: 5288, dtype: int64
内部标识号    5290
交易次数       11
交易金额      822
Name: 5289, dtype: int64
内部标识号    5291
交易次数        1
交易金额      524
Name: 5290, dtype: int64
内部标识号    5292
交易次数        6
交易金额      297
Name: 5291, dtype: int64
内部标识号    5293
交易次数       13
交易金额      424
Name: 5292, dtype: int64
内部标识号    5294
交易次数       29
交易金额     8232
Name: 5293, dtype: int64
内部标识号    5295
交易次数        7
交易金额      164
Name: 5294, dtype: int64
内部标识号    5296
交易次数        1
交易金额      629
Name: 5295, dtype: int64
内部标识号    5297
交易次数        2
交易金额      601
Name: 5296, dtype: int64
内部标识号    5298
交易次数        2
交易金额      354
Name: 5297, dtype: int64
内部标识号    5299
交易次数       17
交易金额     8533
Name: 5298, dtype: int64
内部标识号    5300
交易次数        0
交易金额     7914
Name: 5299, dtype: int64
内部标识号    5301
交易次数       11
交易金额      599
Name: 5300, dtype: int64
内部标识号    5302
交易次数       20
交易金额      877
Name: 5301, dtype: int64
内部标识号    5303
交易次数        9
交易金额      852
Name: 5302, dtype: int64
内部标识号    5304
交易次数        1
交易金额      565
Name: 5303, dtype: int64
内部标识号    5305
交易次数        0
交易金额     8254
Name: 5304, dtype: int64
内部标识号    5306
交易次数       14
交易金额      680
Name: 5305, dtype: int64
内部标识号    5307
交易次数        1
交易金额     4137
Name: 5306, dtype: int64
内部标识号    5308
交易次数        3
交易金额      416
Name: 5307, dtype: int64
内部标识号    5309
交易次数        9
交易金额      481
Name: 5308, dtype: int64
内部标识号    5310
交易次数       15
交易金额      819
Name: 5309, dtype: int64
内部标识号     5311
交易次数       146
交易金额     41474
Name: 5310, dtype: int64
内部标识号    5312
交易次数       15
交易金额      948
Name: 5311, dtype: int64
内部标识号    5313
交易次数        2
交易金额      358
Name: 5312, dtype: int64
内部标识号    5314
交易次数        9
交易金额      486
Name: 5313, dtype: int64
内部标识号    5315
交易次数        2
交易金额      482
Name: 5314, dtype: int64
内部标识号    5316
交易次数       20
交易金额     1133
Name: 5315, dtype: int64
内部标识号    5317
交易次数        0
交易金额     3039
Name: 5316, dtype: int64
内部标识号    5318
交易次数        2
交易金额      449
Name: 5317, dtype: int64
内部标识号     5319
交易次数         8
交易金额     54793
Name: 5318, dtype: int64
内部标识号    5320
交易次数        3
交易金额      376
Name: 5319, dtype: int64
内部标识号    5321
交易次数       14
交易金额      735
Name: 5320, dtype: int64
内部标识号    5322
交易次数       11
交易金额      616
Name: 5321, dtype: int64
内部标识号    5323
交易次数        0
交易金额     8207
Name: 5322, dtype: int64
内部标识号    5324
交易次数       11
交易金额      996
Name: 5323, dtype: int64
内部标识号    5325
交易次数        1
交易金额     4799
Name: 5324, dtype: int64
内部标识号    5326
交易次数        2
交易金额      371
Name: 5325, dtype: int64
内部标识号    5327
交易次数        5
交易金额      133
Name: 5326, dtype: int64
内部标识号    5328
交易次数        0
交易金额     5798
Name: 5327, dtype: int64
内部标识号    5329
交易次数        0
交易金额     5777
Name: 5328, dtype: int64
内部标识号    5330
交易次数        0
交易金额     3211
Name: 5329, dtype: int64
内部标识号    5331
交易次数        7
交易金额      283
Name: 5330, dtype: int64
内部标识号    5332
交易次数        3
交易金额      378
Name: 5331, dtype: int64
内部标识号    5333
交易次数       12
交易金额      433
Name: 5332, dtype: int64
内部标识号    5334
交易次数       16
交易金额     8383
Name: 5333, dtype: int64
内部标识号    5335
交易次数       18
交易金额     7598
Name: 5334, dtype: int64
内部标识号    5336
交易次数        8
交易金额      814
Name: 5335, dtype: int64
内部标识号    5337
交易次数        3
交易金额      211
Name: 5336, dtype: int64
内部标识号    5338
交易次数        3
交易金额      360
Name: 5337, dtype: int64
内部标识号    5339
交易次数        6
交易金额      236
Name: 5338, dtype: int64
内部标识号    5340
交易次数        4
交易金额      275
Name: 5339, dtype: int64
内部标识号    5341
交易次数        0
交易金额     3007
Name: 5340, dtype: int64
内部标识号    5342
交易次数        1
交易金额     5409
Name: 5341, dtype: int64
内部标识号    5343
交易次数       12
交易金额      900
Name: 5342, dtype: int64
内部标识号    5344
交易次数        7
交易金额      148
Name: 5343, dtype: int64
内部标识号     5345
交易次数         3
交易金额     98758
Name: 5344, dtype: int64
内部标识号    5346
交易次数        0
交易金额     6091
Name: 5345, dtype: int64
内部标识号    5347
交易次数        2
交易金额      440
Name: 5346, dtype: int64
内部标识号    5348
交易次数       15
交易金额      447
Name: 5347, dtype: int64
内部标识号    5349
交易次数       12
交易金额      466
Name: 5348, dtype: int64
内部标识号    5350
交易次数        2
交易金额      189
Name: 5349, dtype: int64
内部标识号    5351
交易次数        4
交易金额      250
Name: 5350, dtype: int64
内部标识号    5352
交易次数        1
交易金额      887
Name: 5351, dtype: int64
内部标识号    5353
交易次数        7
交易金额      170
Name: 5352, dtype: int64
内部标识号    5354
交易次数        0
交易金额     2124
Name: 5353, dtype: int64
内部标识号    5355
交易次数       13
交易金额      359
Name: 5354, dtype: int64
内部标识号    5356
交易次数        0
交易金额     6405
Name: 5355, dtype: int64
内部标识号    5357
交易次数        3
交易金额      261
Name: 5356, dtype: int64
内部标识号    5358
交易次数       21
交易金额     5102
Name: 5357, dtype: int64
内部标识号     5359
交易次数         3
交易金额     21130
Name: 5358, dtype: int64
内部标识号    5360
交易次数       27
交易金额       12
Name: 5359, dtype: int64
内部标识号    5361
交易次数       15
交易金额      577
Name: 5360, dtype: int64
内部标识号    5362
交易次数        2
交易金额      448
Name: 5361, dtype: int64
内部标识号    5363
交易次数        8
交易金额      320
Name: 5362, dtype: int64
内部标识号    5364
交易次数        9
交易金额      563
Name: 5363, dtype: int64
内部标识号    5365
交易次数        0
交易金额     7632
Name: 5364, dtype: int64
内部标识号    5366
交易次数       11
交易金额      329
Name: 5365, dtype: int64
内部标识号    5367
交易次数        8
交易金额      652
Name: 5366, dtype: int64
内部标识号    5368
交易次数       12
交易金额      348
Name: 5367, dtype: int64
内部标识号    5369
交易次数       11
交易金额      476
Name: 5368, dtype: int64
内部标识号    5370
交易次数        3
交易金额      391
Name: 5369, dtype: int64
内部标识号    5371
交易次数        0
交易金额     7458
Name: 5370, dtype: int64
内部标识号    5372
交易次数       24
交易金额       77
Name: 5371, dtype: int64
内部标识号    5373
交易次数       15
交易金额      805
Name: 5372, dtype: int64
内部标识号    5374
交易次数       19
交易金额      831
Name: 5373, dtype: int64
内部标识号    5375
交易次数       17
交易金额     7422
Name: 5374, dtype: int64
内部标识号    5376
交易次数        6
交易金额      141
Name: 5375, dtype: int64
内部标识号    5377
交易次数        7
交易金额      297
Name: 5376, dtype: int64
内部标识号    5378
交易次数       27
交易金额     2799
Name: 5377, dtype: int64
内部标识号     5379
交易次数       215
交易金额     38029
Name: 5378, dtype: int64
内部标识号    5380
交易次数       28
交易金额     3693
Name: 5379, dtype: int64
内部标识号     5381
交易次数         3
交易金额     54969
Name: 5380, dtype: int64
内部标识号    5382
交易次数        7
交易金额      199
Name: 5381, dtype: int64
内部标识号    5383
交易次数       11
交易金额      679
Name: 5382, dtype: int64
内部标识号    5384
交易次数       13
交易金额      548
Name: 5383, dtype: int64
内部标识号    5385
交易次数        1
交易金额     6607
Name: 5384, dtype: int64
内部标识号    5386
交易次数        2
交易金额      592
Name: 5385, dtype: int64
内部标识号    5387
交易次数       12
交易金额      617
Name: 5386, dtype: int64
内部标识号    5388
交易次数        8
交易金额      227
Name: 5387, dtype: int64
内部标识号    5389
交易次数       11
交易金额      518
Name: 5388, dtype: int64
内部标识号    5390
交易次数        0
交易金额     4625
Name: 5389, dtype: int64
内部标识号    5391
交易次数        4
交易金额      166
Name: 5390, dtype: int64
内部标识号    5392
交易次数        9
交易金额      966
Name: 5391, dtype: int64
内部标识号     5393
交易次数         3
交易金额     71678
Name: 5392, dtype: int64
内部标识号     5394
交易次数        39
交易金额     34475
Name: 5393, dtype: int64
内部标识号    5395
交易次数       13
交易金额      698
Name: 5394, dtype: int64
内部标识号    5396
交易次数        8
交易金额      118
Name: 5395, dtype: int64
内部标识号    5397
交易次数        0
交易金额     4556
Name: 5396, dtype: int64
内部标识号    5398
交易次数        3
交易金额      440
Name: 5397, dtype: int64
内部标识号     5399
交易次数         8
交易金额     70752
Name: 5398, dtype: int64
内部标识号    5400
交易次数        4
交易金额      261
Name: 5399, dtype: int64
内部标识号    5401
交易次数       15
交易金额      333
Name: 5400, dtype: int64
内部标识号    5402
交易次数       12
交易金额      424
Name: 5401, dtype: int64
内部标识号    5403
交易次数        0
交易金额     3035
Name: 5402, dtype: int64
内部标识号    5404
交易次数        3
交易金额      476
Name: 5403, dtype: int64
内部标识号    5405
交易次数        6
交易金额      178
Name: 5404, dtype: int64
内部标识号    5406
交易次数        8
交易金额      498
Name: 5405, dtype: int64
内部标识号    5407
交易次数        4
交易金额      160
Name: 5406, dtype: int64
内部标识号    5408
交易次数        1
交易金额      999
Name: 5407, dtype: int64
内部标识号     5409
交易次数         4
交易金额     61603
Name: 5408, dtype: int64
内部标识号    5410
交易次数        4
交易金额      295
Name: 5409, dtype: int64
内部标识号    5411
交易次数        3
交易金额      449
Name: 5410, dtype: int64
内部标识号    5412
交易次数       14
交易金额      309
Name: 5411, dtype: int64
内部标识号    5413
交易次数        0
交易金额     1068
Name: 5412, dtype: int64
内部标识号    5414
交易次数        2
交易金额      476
Name: 5413, dtype: int64
内部标识号    5415
交易次数       13
交易金额      383
Name: 5414, dtype: int64
内部标识号    5416
交易次数       15
交易金额     1238
Name: 5415, dtype: int64
内部标识号     5417
交易次数       283
交易金额     22928
Name: 5416, dtype: int64
内部标识号    5418
交易次数       13
交易金额      856
Name: 5417, dtype: int64
内部标识号    5419
交易次数       23
交易金额     7164
Name: 5418, dtype: int64
内部标识号    5420
交易次数        9
交易金额      613
Name: 5419, dtype: int64
内部标识号    5421
交易次数        7
交易金额      258
Name: 5420, dtype: int64
内部标识号    5422
交易次数        3
交易金额      151
Name: 5421, dtype: int64
内部标识号    5423
交易次数        3
交易金额      150
Name: 5422, dtype: int64
内部标识号    5424
交易次数       15
交易金额      935
Name: 5423, dtype: int64
内部标识号     5425
交易次数         3
交易金额     18854
Name: 5424, dtype: int64
内部标识号    5426
交易次数       14
交易金额      655
Name: 5425, dtype: int64
内部标识号    5427
交易次数        8
交易金额      866
Name: 5426, dtype: int64
内部标识号    5428
交易次数       17
交易金额     3577
Name: 5427, dtype: int64
内部标识号    5429
交易次数       14
交易金额      781
Name: 5428, dtype: int64
内部标识号    5430
交易次数       14
交易金额      639
Name: 5429, dtype: int64
内部标识号    5431
交易次数        1
交易金额     5271
Name: 5430, dtype: int64
内部标识号    5432
交易次数       22
交易金额     3414
Name: 5431, dtype: int64
内部标识号     5433
交易次数         3
交易金额     64626
Name: 5432, dtype: int64
内部标识号    5434
交易次数       28
交易金额      665
Name: 5433, dtype: int64
内部标识号     5435
交易次数       239
交易金额     69581
Name: 5434, dtype: int64
内部标识号    5436
交易次数        3
交易金额      383
Name: 5435, dtype: int64
内部标识号    5437
交易次数        1
交易金额     5712
Name: 5436, dtype: int64
内部标识号    5438
交易次数       13
交易金额      912
Name: 5437, dtype: int64
内部标识号    5439
交易次数        1
交易金额     4403
Name: 5438, dtype: int64
内部标识号    5440
交易次数        1
交易金额      859
Name: 5439, dtype: int64
内部标识号    5441
交易次数       15
交易金额      441
Name: 5440, dtype: int64
内部标识号    5442
交易次数        8
交易金额      471
Name: 5441, dtype: int64
内部标识号    5443
交易次数        2
交易金额      790
Name: 5442, dtype: int64
内部标识号    5444
交易次数       16
交易金额       33
Name: 5443, dtype: int64
内部标识号    5445
交易次数       15
交易金额      885
Name: 5444, dtype: int64
内部标识号    5446
交易次数        0
交易金额     8764
Name: 5445, dtype: int64
内部标识号    5447
交易次数        1
交易金额      596
Name: 5446, dtype: int64
内部标识号    5448
交易次数        8
交易金额      355
Name: 5447, dtype: int64
内部标识号    5449
交易次数        3
交易金额      398
Name: 5448, dtype: int64
内部标识号    5450
交易次数       13
交易金额      944
Name: 5449, dtype: int64
内部标识号    5451
交易次数       10
交易金额      627
Name: 5450, dtype: int64
内部标识号    5452
交易次数        2
交易金额      913
Name: 5451, dtype: int64
内部标识号    5453
交易次数       22
交易金额     5302
Name: 5452, dtype: int64
内部标识号    5454
交易次数       14
交易金额      305
Name: 5453, dtype: int64
内部标识号    5455
交易次数        2
交易金额      297

Name: 5454, dtype: int64
内部标识号    5456
交易次数        3
交易金额      423
Name: 5455, dtype: int64
内部标识号    5457
交易次数       15
交易金额      992
Name: 5456, dtype: int64
内部标识号    5458
交易次数        8
交易金额      426
Name: 5457, dtype: int64
内部标识号     5459
交易次数         4
交易金额     78656
Name: 5458, dtype: int64
内部标识号    5460
交易次数       13
交易金额      409
Name: 5459, dtype: int64
内部标识号    5461
交易次数        3
交易金额      342
Name: 5460, dtype: int64
内部标识号    5462
交易次数        3
交易金额      209
Name: 5461, dtype: int64
内部标识号    5463
交易次数        2
交易金额      160
Name: 5462, dtype: int64
内部标识号     5464
交易次数       121
交易金额     90771
Name: 5463, dtype: int64
内部标识号    5465
交易次数        2
交易金额      718
Name: 5464, dtype: int64
内部标识号    5466
交易次数        1
交易金额     1585
Name: 5465, dtype: int64
内部标识号    5467
交易次数       29
交易金额     2380
Name: 5466, dtype: int64
内部标识号    5468
交易次数       13
交易金额      625
Name: 5467, dtype: int64
内部标识号     5469
交易次数         4
交易金额     58384
Name: 5468, dtype: int64
内部标识号    5470
交易次数        2
交易金额      692
Name: 5469, dtype: int64
内部标识号     5471
交易次数         7
交易金额     53760
Name: 5470, dtype: int64
内部标识号    5472
交易次数        8
交易金额      268
Name: 5471, dtype: int64
内部标识号    5473
交易次数       13
交易金额      483
Name: 5472, dtype: int64
内部标识号    5474
交易次数        3
交易金额      433
Name: 5473, dtype: int64
内部标识号    5475
交易次数       16
交易金额     8925
Name: 5474, dtype: int64
内部标识号    5476
交易次数       11
交易金额      385
Name: 5475, dtype: int64
内部标识号    5477
交易次数        1
交易金额     9184
Name: 5476, dtype: int64
内部标识号    5478
交易次数       27
交易金额      530
Name: 5477, dtype: int64
内部标识号    5479
交易次数        4
交易金额      249
Name: 5478, dtype: int64
内部标识号    5480
交易次数       11
交易金额      985
Name: 5479, dtype: int64
内部标识号     5481
交易次数        37
交易金额     23858
Name: 5480, dtype: int64
内部标识号     5482
交易次数         8
交易金额     96523
Name: 5481, dtype: int64
内部标识号    5483
交易次数        1
交易金额      538
Name: 5482, dtype: int64
内部标识号    5484
交易次数        3
交易金额      321
Name: 5483, dtype: int64
内部标识号    5485
交易次数        6
交易金额      142
Name: 5484, dtype: int64
内部标识号    5486
交易次数        3
交易金额      423
Name: 5485, dtype: int64
内部标识号    5487
交易次数       18
交易金额     3382
Name: 5486, dtype: int64
内部标识号    5488
交易次数        2
交易金额      493
Name: 5487, dtype: int64
内部标识号    5489
交易次数       24
交易金额     1874
Name: 5488, dtype: int64
内部标识号    5490
交易次数        6
交易金额      296
Name: 5489, dtype: int64
内部标识号    5491
交易次数        7
交易金额      108
Name: 5490, dtype: int64
内部标识号    5492
交易次数        1
交易金额      634
Name: 5491, dtype: int64
内部标识号    5493
交易次数        3
交易金额      336
Name: 5492, dtype: int64
内部标识号    5494
交易次数       25
交易金额       57
Name: 5493, dtype: int64
内部标识号    5495
交易次数        3
交易金额      328
Name: 5494, dtype: int64
内部标识号    5496
交易次数       13
交易金额      782
Name: 5495, dtype: int64
内部标识号    5497
交易次数        0
交易金额     4963
Name: 5496, dtype: int64
内部标识号    5498
交易次数        1
交易金额     5085
Name: 5497, dtype: int64
内部标识号    5499
交易次数       14
交易金额      482
Name: 5498, dtype: int64
内部标识号    5500
交易次数       12
交易金额      875
Name: 5499, dtype: int64
内部标识号    5501
交易次数        5
交易金额      284
Name: 5500, dtype: int64
内部标识号     5502
交易次数       123
交易金额     15068
Name: 5501, dtype: int64
内部标识号    5503
交易次数       17
交易金额     2351
Name: 5502, dtype: int64
内部标识号    5504
交易次数        2
交易金额      406
Name: 5503, dtype: int64
内部标识号    5505
交易次数        1
交易金额     2058
Name: 5504, dtype: int64
内部标识号    5506
交易次数       14
交易金额      829
Name: 5505, dtype: int64
内部标识号    5507
交易次数        2
交易金额      443
Name: 5506, dtype: int64
内部标识号    5508
交易次数        0
交易金额     1688
Name: 5507, dtype: int64
内部标识号     5509
交易次数         3
交易金额     70515
Name: 5508, dtype: int64
内部标识号    5510
交易次数       15
交易金额      876
Name: 5509, dtype: int64
内部标识号    5511
交易次数       21
交易金额       25
Name: 5510, dtype: int64
内部标识号    5512
交易次数       25
交易金额      513
Name: 5511, dtype: int64
内部标识号    5513
交易次数       12
交易金额      492
Name: 5512, dtype: int64
内部标识号    5514
交易次数        3
交易金额      401
Name: 5513, dtype: int64
内部标识号    5515
交易次数        3
交易金额      278
Name: 5514, dtype: int64
内部标识号    5516
交易次数        8
交易金额      201
Name: 5515, dtype: int64
内部标识号    5517
交易次数        8
交易金额      413
Name: 5516, dtype: int64
内部标识号    5518
交易次数       11
交易金额      502
Name: 5517, dtype: int64
内部标识号    5519
交易次数        1
交易金额      964
Name: 5518, dtype: int64
内部标识号    5520
交易次数       15
交易金额      361
Name: 5519, dtype: int64
内部标识号    5521
交易次数       14
交易金额      330
Name: 5520, dtype: int64
内部标识号    5522
交易次数       13
交易金额      545
Name: 5521, dtype: int64
内部标识号    5523
交易次数       27
交易金额     8379
Name: 5522, dtype: int64
内部标识号    5524
交易次数        3
交易金额      417
Name: 5523, dtype: int64
内部标识号    5525
交易次数       10
交易金额      520
Name: 5524, dtype: int64
内部标识号    5526
交易次数        0
交易金额     2221
Name: 5525, dtype: int64
内部标识号    5527
交易次数        3
交易金额      270
Name: 5526, dtype: int64
内部标识号    5528
交易次数        2
交易金额      506
Name: 5527, dtype: int64
内部标识号    5529
交易次数        1
交易金额     7606
Name: 5528, dtype: int64
内部标识号    5530
交易次数       18
交易金额     3921
Name: 5529, dtype: int64
内部标识号     5531
交易次数       227
交易金额     99890
Name: 5530, dtype: int64
内部标识号    5532
交易次数       11
交易金额      340
Name: 5531, dtype: int64
内部标识号     5533
交易次数       115
交易金额     55002
Name: 5532, dtype: int64
内部标识号    5534
交易次数        2
交易金额      444
Name: 5533, dtype: int64
内部标识号     5535
交易次数       269
交易金额     94388
Name: 5534, dtype: int64
内部标识号    5536
交易次数       18
交易金额     9134
Name: 5535, dtype: int64
内部标识号    5537
交易次数        7
交易金额      128
Name: 5536, dtype: int64
内部标识号    5538
交易次数       12
交易金额      796
Name: 5537, dtype: int64
内部标识号    5539
交易次数        2
交易金额      314
Name: 5538, dtype: int64
内部标识号    5540
交易次数        8
交易金额      216
Name: 5539, dtype: int64
内部标识号    5541
交易次数        9
交易金额      323
Name: 5540, dtype: int64
内部标识号    5542
交易次数        2
交易金额      478
Name: 5541, dtype: int64
内部标识号    5543
交易次数       26
交易金额      789
Name: 5542, dtype: int64
内部标识号    5544
交易次数        2
交易金额      426
Name: 5543, dtype: int64
内部标识号     5545
交易次数       157
交易金额     54385
Name: 5544, dtype: int64
内部标识号    5546
交易次数       13
交易金额      848
Name: 5545, dtype: int64
内部标识号    5547
交易次数       13
交易金额      589
Name: 5546, dtype: int64
内部标识号    5548
交易次数        0
交易金额     7303
Name: 5547, dtype: int64
内部标识号    5549
交易次数        3
交易金额      407
Name: 5548, dtype: int64
内部标识号    5550
交易次数        3
交易金额      350
Name: 5549, dtype: int64
内部标识号    5551
交易次数       14
交易金额      530
Name: 5550, dtype: int64
内部标识号    5552
交易次数        8
交易金额      102
Name: 5551, dtype: int64
内部标识号    5553
交易次数        2
交易金额      957
Name: 5552, dtype: int64
内部标识号    5554
交易次数        4
交易金额      138
Name: 5553, dtype: int64
内部标识号    5555
交易次数        7
交易金额      200
Name: 5554, dtype: int64
内部标识号    5556
交易次数        3
交易金额      321
Name: 5555, dtype: int64
内部标识号    5557
交易次数        6
交易金额      140
Name: 5556, dtype: int64
内部标识号    5558
交易次数        8
交易金额      804
Name: 5557, dtype: int64
内部标识号    5559
交易次数        0
交易金额     3041
Name: 5558, dtype: int64
内部标识号    5560
交易次数        0
交易金额     4038
Name: 5559, dtype: int64
内部标识号    5561
交易次数       13
交易金额      438
Name: 5560, dtype: int64
内部标识号    5562
交易次数       22
交易金额     6628
Name: 5561, dtype: int64
内部标识号    5563
交易次数       13
交易金额      711
Name: 5562, dtype: int64
内部标识号    5564
交易次数       19
交易金额     3092
Name: 5563, dtype: int64
内部标识号    5565
交易次数        3
交易金额      224
Name: 5564, dtype: int64
内部标识号    5566
交易次数        4
交易金额      109
Name: 5565, dtype: int64
内部标识号    5567
交易次数        8
交易金额      314
Name: 5566, dtype: int64
内部标识号     5568
交易次数         5
交易金额     88076
Name: 5567, dtype: int64
内部标识号    5569
交易次数        6
交易金额      215
Name: 5568, dtype: int64
内部标识号    5570
交易次数        2
交易金额      491
Name: 5569, dtype: int64
内部标识号    5571
交易次数       13
交易金额      460
Name: 5570, dtype: int64
内部标识号    5572
交易次数       10
交易金额      759
Name: 5571, dtype: int64
内部标识号    5573
交易次数       15
交易金额      717
Name: 5572, dtype: int64
内部标识号    5574
交易次数        9
交易金额      886
Name: 5573, dtype: int64
内部标识号    5575
交易次数        2
交易金额      362
Name: 5574, dtype: int64
内部标识号    5576
交易次数        2
交易金额      300
Name: 5575, dtype: int64
内部标识号    5577
交易次数        0
交易金额     8868
Name: 5576, dtype: int64
内部标识号    5578
交易次数        0
交易金额     9654
Name: 5577, dtype: int64
内部标识号    5579
交易次数        5
交易金额      216
Name: 5578, dtype: int64
内部标识号    5580
交易次数        3
交易金额      281
Name: 5579, dtype: int64
内部标识号    5581
交易次数       11
交易金额      404
Name: 5580, dtype: int64
内部标识号    5582
交易次数        2
交易金额      343
Name: 5581, dtype: int64
内部标识号    5583
交易次数        3
交易金额      496
Name: 5582, dtype: int64
内部标识号    5584
交易次数        1
交易金额      975
Name: 5583, dtype: int64
内部标识号    5585
交易次数       27
交易金额      562
Name: 5584, dtype: int64
内部标识号    5586
交易次数        8
交易金额      108
Name: 5585, dtype: int64
内部标识号    5587
交易次数        1
交易金额      755
Name: 5586, dtype: int64
内部标识号    5588
交易次数       11
交易金额      841
Name: 5587, dtype: int64
内部标识号    5589
交易次数       11
交易金额      625
Name: 5588, dtype: int64
内部标识号    5590
交易次数        2
交易金额      358
Name: 5589, dtype: int64
内部标识号    5591
交易次数        9
交易金额      823
Name: 5590, dtype: int64
内部标识号    5592
交易次数        0
交易金额     6366
Name: 5591, dtype: int64
内部标识号    5593
交易次数        9
交易金额      512
Name: 5592, dtype: int64
内部标识号    5594
交易次数       13
交易金额      470
Name: 5593, dtype: int64
内部标识号    5595
交易次数        9
交易金额      453
Name: 5594, dtype: int64
内部标识号     5596
交易次数         6
交易金额     52668
Name: 5595, dtype: int64
内部标识号    5597
交易次数       27
交易金额     4794
Name: 5596, dtype: int64
内部标识号    5598
交易次数       23
交易金额     7946
Name: 5597, dtype: int64
内部标识号    5599
交易次数       11
交易金额      924
Name: 5598, dtype: int64
内部标识号    5600
交易次数       10
交易金额      460
Name: 5599, dtype: int64
内部标识号    5601
交易次数        2
交易金额      689
Name: 5600, dtype: int64
内部标识号    5602
交易次数       25
交易金额     5901
Name: 5601, dtype: int64
内部标识号    5603
交易次数        4
交易金额      177
Name: 5602, dtype: int64
内部标识号    5604
交易次数       10
交易金额      354
Name: 5603, dtype: int64
内部标识号     5605
交易次数         4
交易金额     79090
Name: 5604, dtype: int64
内部标识号     5606
交易次数        88
交易金额     75475
Name: 5605, dtype: int64
内部标识号    5607
交易次数       10
交易金额      694
Name: 5606, dtype: int64
内部标识号    5608
交易次数        7
交易金额      230
Name: 5607, dtype: int64
内部标识号    5609
交易次数        8
交易金额      138
Name: 5608, dtype: int64
内部标识号    5610
交易次数       17
交易金额     5776
Name: 5609, dtype: int64
内部标识号     5611
交易次数       183
交易金额     33001
Name: 5610, dtype: int64
内部标识号    5612
交易次数        0
交易金额     4431
Name: 5611, dtype: int64
内部标识号    5613
交易次数        1
交易金额      547
Name: 5612, dtype: int64
内部标识号    5614
交易次数       15
交易金额      727
Name: 5613, dtype: int64
内部标识号    5615
交易次数        1
交易金额     5308
Name: 5614, dtype: int64
内部标识号     5616
交易次数       251
交易金额     20727
Name: 5615, dtype: int64
内部标识号    5617
交易次数        1
交易金额     8049
Name: 5616, dtype: int64
内部标识号    5618
交易次数        8
交易金额      240
Name: 5617, dtype: int64
内部标识号    5619
交易次数        2
交易金额      566
Name: 5618, dtype: int64
内部标识号    5620
交易次数       15
交易金额      866
Name: 5619, dtype: int64
内部标识号    5621
交易次数        2
交易金额      410
Name: 5620, dtype: int64
内部标识号    5622
交易次数        7
交易金额      298
Name: 5621, dtype: int64
内部标识号    5623
交易次数       27
交易金额     5103
Name: 5622, dtype: int64
内部标识号    5624
交易次数        3
交易金额      270
Name: 5623, dtype: int64
内部标识号    5625
交易次数       13
交易金额      534
Name: 5624, dtype: int64
内部标识号     5626
交易次数       191
交易金额     91723
Name: 5625, dtype: int64
内部标识号    5627
交易次数       15
交易金额      837
Name: 5626, dtype: int64
内部标识号    5628
交易次数        3
交易金额      406
Name: 5627, dtype: int64
内部标识号    5629
交易次数       18
交易金额     6315
Name: 5628, dtype: int64
内部标识号    5630
交易次数        2
交易金额      494
Name: 5629, dtype: int64
内部标识号    5631
交易次数       22
交易金额     9287
Name: 5630, dtype: int64
内部标识号    5632
交易次数       15
交易金额      876
Name: 5631, dtype: int64
内部标识号    5633
交易次数        1
交易金额      992
Name: 5632, dtype: int64
内部标识号    5634
交易次数       18
交易金额      972
Name: 5633, dtype: int64
内部标识号    5635
交易次数        7
交易金额      147
Name: 5634, dtype: int64
内部标识号    5636
交易次数       14
交易金额      344
Name: 5635, dtype: int64
内部标识号     5637
交易次数       279
交易金额     79983
Name: 5636, dtype: int64
内部标识号    5638
交易次数       10
交易金额      437
Name: 5637, dtype: int64
内部标识号    5639
交易次数        4
交易金额      183
Name: 5638, dtype: int64
内部标识号    5640
交易次数        7
交易金额      128
Name: 5639, dtype: int64
内部标识号    5641
交易次数        4
交易金额      129
Name: 5640, dtype: int64
内部标识号    5642
交易次数        2
交易金额      333
Name: 5641, dtype: int64
内部标识号    5643
交易次数       20
交易金额     7253
Name: 5642, dtype: int64
内部标识号    5644
交易次数       20
交易金额     1418
Name: 5643, dtype: int64
内部标识号    5645
交易次数        2
交易金额      330
Name: 5644, dtype: int64
内部标识号    5646
交易次数        2
交易金额      343
Name: 5645, dtype: int64
内部标识号    5647
交易次数        0
交易金额     3769
Name: 5646, dtype: int64
内部标识号    5648
交易次数       10
交易金额      373
Name: 5647, dtype: int64
内部标识号    5649
交易次数        2
交易金额     1000
Name: 5648, dtype: int64
内部标识号    5650
交易次数        2
交易金额      734
Name: 5649, dtype: int64
内部标识号    5651
交易次数       14
交易金额      323
Name: 5650, dtype: int64
内部标识号    5652
交易次数        3
交易金额      449
Name: 5651, dtype: int64
内部标识号    5653
交易次数        5
交易金额      189
Name: 5652, dtype: int64
内部标识号     5654
交易次数         6
交易金额     25513
Name: 5653, dtype: int64
内部标识号    5655
交易次数       27
交易金额     5556
Name: 5654, dtype: int64
内部标识号    5656
交易次数        3
交易金额      319
Name: 5655, dtype: int64
内部标识号     5657
交易次数         5
交易金额     78744
Name: 5656, dtype: int64
内部标识号     5658
交易次数       177
交易金额     61922
Name: 5657, dtype: int64
内部标识号    5659
交易次数       12
交易金额      655
Name: 5658, dtype: int64
内部标识号    5660
交易次数       10
交易金额      354
Name: 5659, dtype: int64
内部标识号    5661
交易次数        1
交易金额     5379
Name: 5660, dtype: int64
内部标识号    5662
交易次数        3
交易金额      419
Name: 5661, dtype: int64
内部标识号    5663
交易次数       24
交易金额      649
Name: 5662, dtype: int64
内部标识号    5664
交易次数        0
交易金额     9609
Name: 5663, dtype: int64
内部标识号    5665
交易次数       14
交易金额      721
Name: 5664, dtype: int64
内部标识号    5666
交易次数       11
交易金额      999
Name: 5665, dtype: int64
内部标识号     5667
交易次数        38
交易金额     71974
Name: 5666, dtype: int64
内部标识号    5668
交易次数        0
交易金额     2918
Name: 5667, dtype: int64
内部标识号    5669
交易次数        2
交易金额      358
Name: 5668, dtype: int64
内部标识号     5670
交易次数       295
交易金额     64539
Name: 5669, dtype: int64
内部标识号    5671
交易次数       14
交易金额      766
Name: 5670, dtype: int64
内部标识号    5672
交易次数       15
交易金额      805
Name: 5671, dtype: int64
内部标识号    5673
交易次数        7
交易金额      219
Name: 5672, dtype: int64
内部标识号    5674
交易次数        7
交易金额      157
Name: 5673, dtype: int64
内部标识号    5675
交易次数       12
交易金额      482
Name: 5674, dtype: int64
内部标识号    5676
交易次数        8
交易金额      410
Name: 5675, dtype: int64
内部标识号    5677
交易次数        7
交易金额      253
Name: 5676, dtype: int64
内部标识号    5678
交易次数        0
交易金额     9641
Name: 5677, dtype: int64
内部标识号    5679
交易次数        2
交易金额      457
Name: 5678, dtype: int64
内部标识号    5680
交易次数        3
交易金额      324
Name: 5679, dtype: int64
内部标识号    5681
交易次数       12
交易金额      892
Name: 5680, dtype: int64
内部标识号    5682
交易次数        8
交易金额      620
Name: 5681, dtype: int64
内部标识号    5683
交易次数        1
交易金额      784
Name: 5682, dtype: int64
内部标识号    5684
交易次数       15
交易金额      932
Name: 5683, dtype: int64
内部标识号    5685
交易次数       11
交易金额      545
Name: 5684, dtype: int64
内部标识号     5686
交易次数        83
交易金额     29171
Name: 5685, dtype: int64
内部标识号    5687
交易次数        1
交易金额      664
Name: 5686, dtype: int64
内部标识号    5688
交易次数        8
交易金额      974
Name: 5687, dtype: int64
内部标识号    5689
交易次数        2
交易金额      959
Name: 5688, dtype: int64
内部标识号    5690
交易次数       13
交易金额      949
Name: 5689, dtype: int64
内部标识号    5691
交易次数        2
交易金额      366
Name: 5690, dtype: int64
内部标识号    5692
交易次数        4
交易金额      213
Name: 5691, dtype: int64
内部标识号    5693
交易次数       11
交易金额      956
Name: 5692, dtype: int64
内部标识号    5694
交易次数        1
交易金额     5606
Name: 5693, dtype: int64
内部标识号    5695
交易次数       14
交易金额      526
Name: 5694, dtype: int64
内部标识号    5696
交易次数       29
交易金额     3447
Name: 5695, dtype: int64
内部标识号    5697
交易次数        3
交易金额      467
Name: 5696, dtype: int64
内部标识号    5698
交易次数        5
交易金额      141
Name: 5697, dtype: int64
内部标识号    5699
交易次数        6
交易金额      214
Name: 5698, dtype: int64
内部标识号    5700
交易次数        1
交易金额      699
Name: 5699, dtype: int64
内部标识号    5701
交易次数       15
交易金额      388
Name: 5700, dtype: int64
内部标识号    5702
交易次数        8
交易金额      239
Name: 5701, dtype: int64
内部标识号    5703
交易次数        0
交易金额     6315
Name: 5702, dtype: int64
内部标识号    5704
交易次数       14
交易金额      814
Name: 5703, dtype: int64
内部标识号    5705
交易次数       14
交易金额      443
Name: 5704, dtype: int64
内部标识号    5706
交易次数        2
交易金额      800
Name: 5705, dtype: int64
内部标识号    5707
交易次数        0
交易金额     6413
Name: 5706, dtype: int64
内部标识号    5708
交易次数        0
交易金额     2855
Name: 5707, dtype: int64
内部标识号    5709
交易次数       14
交易金额      469
Name: 5708, dtype: int64
内部标识号    5710
交易次数       12
交易金额      429
Name: 5709, dtype: int64
内部标识号    5711
交易次数        0
交易金额     8610
Name: 5710, dtype: int64
内部标识号     5712
交易次数         6
交易金额     40483
Name: 5711, dtype: int64
内部标识号    5713
交易次数        8
交易金额      570
Name: 5712, dtype: int64
内部标识号    5714
交易次数       10
交易金额      375
Name: 5713, dtype: int64
内部标识号    5715
交易次数        2
交易金额      355
Name: 5714, dtype: int64
内部标识号     5716
交易次数         5
交易金额     68422
Name: 5715, dtype: int64
内部标识号    5717
交易次数        2
交易金额      430
Name: 5716, dtype: int64
内部标识号    5718
交易次数       15
交易金额     1119
Name: 5717, dtype: int64
内部标识号    5719
交易次数        2
交易金额      302
Name: 5718, dtype: int64
内部标识号    5720
交易次数        2
交易金额      994
Name: 5719, dtype: int64
内部标识号    5721
交易次数        3
交易金额      477
Name: 5720, dtype: int64
内部标识号    5722
交易次数        3
交易金额      416
Name: 5721, dtype: int64
内部标识号    5723
交易次数        2
交易金额      380
Name: 5722, dtype: int64
内部标识号    5724
交易次数        7
交易金额      112
Name: 5723, dtype: int64
内部标识号    5725
交易次数        6
交易金额      181
Name: 5724, dtype: int64
内部标识号    5726
交易次数        0
交易金额     2828
Name: 5725, dtype: int64
内部标识号    5727
交易次数       13
交易金额      967
Name: 5726, dtype: int64
内部标识号    5728
交易次数       12
交易金额      561
Name: 5727, dtype: int64
内部标识号     5729
交易次数       295
交易金额     49177
Name: 5728, dtype: int64
内部标识号    5730
交易次数        8
交易金额      119
Name: 5729, dtype: int64
内部标识号    5731
交易次数        0
交易金额     8818
Name: 5730, dtype: int64
内部标识号    5732
交易次数       15
交易金额      605
Name: 5731, dtype: int64
内部标识号     5733
交易次数       276
交易金额     19335
Name: 5732, dtype: int64
内部标识号    5734
交易次数       13
交易金额      829
Name: 5733, dtype: int64
内部标识号    5735
交易次数        3
交易金额      121
Name: 5734, dtype: int64
内部标识号    5736
交易次数       10
交易金额      770
Name: 5735, dtype: int64
内部标识号     5737
交易次数        90
交易金额     11046
Name: 5736, dtype: int64
内部标识号    5738
交易次数       15
交易金额     4764
Name: 5737, dtype: int64
内部标识号    5739
交易次数        3
交易金额      252
Name: 5738, dtype: int64
内部标识号    5740
交易次数        7
交易金额      206
Name: 5739, dtype: int64
内部标识号    5741
交易次数        7
交易金额      261
Name: 5740, dtype: int64
内部标识号    5742
交易次数       14
交易金额      673
Name: 5741, dtype: int64
内部标识号    5743
交易次数        3
交易金额      178
Name: 5742, dtype: int64
内部标识号    5744
交易次数        2
交易金额      827
Name: 5743, dtype: int64
内部标识号    5745
交易次数        3
交易金额      392
Name: 5744, dtype: int64
内部标识号    5746
交易次数       13
交易金额      402
Name: 5745, dtype: int64
内部标识号    5747
交易次数       30
交易金额     8040
Name: 5746, dtype: int64
内部标识号    5748
交易次数        1
交易金额     7991
Name: 5747, dtype: int64
内部标识号    5749
交易次数       29
交易金额     2147
Name: 5748, dtype: int64
内部标识号     5750
交易次数         4
交易金额     38121
Name: 5749, dtype: int64
内部标识号    5751
交易次数       13
交易金额      896
Name: 5750, dtype: int64
内部标识号    5752
交易次数        2
交易金额      446

Name: 5768, dtype: int64
内部标识号    5770
交易次数       21
交易金额     8865
Name: 5769, dtype: int64
内部标识号    5771
交易次数        2
交易金额      388
Name: 5770, dtype: int64
内部标识号    5772
交易次数       12
交易金额      447
Name: 5771, dtype: int64
内部标识号    5773
交易次数       14
交易金额      316
Name: 5772, dtype: int64
内部标识号    5774
交易次数        7
交易金额      273
Name: 5773, dtype: int64
内部标识号    5775
交易次数        1
交易金额     7876
Name: 5774, dtype: int64
内部标识号    5776
交易次数        4
交易金额      195
Name: 5775, dtype: int64
内部标识号    5777
交易次数        2
交易金额      614
Name: 5776, dtype: int64
内部标识号    5778
交易次数        6
交易金额      243
Name: 5777, dtype: int64
内部标识号    5779
交易次数        0
交易金额     1137
Name: 5778, dtype: int64
内部标识号    5780
交易次数        3
交易金额      241
Name: 5779, dtype: int64
内部标识号    5781
交易次数        2
交易金额      820
Name: 5780, dtype: int64
内部标识号    5782
交易次数        7
交易金额      152
Name: 5781, dtype: int64
内部标识号    5783
交易次数        2
交易金额      472
Name: 5782, dtype: int64
内部标识号    5784
交易次数        6
交易金额      246
Name: 5783, dtype: int64
内部标识号     5785
交易次数       183
交易金额     73509
Name: 5784, dtype: int64
内部标识号    5786
交易次数        2
交易金额      761
Name: 5785, dtype: int64
内部标识号     5787
交易次数       113
交易金额     57700
Name: 5786, dtype: int64
内部标识号    5788
交易次数        9
交易金额      686
Name: 5787, dtype: int64
内部标识号    5789
交易次数        8
交易金额      845
Name: 5788, dtype: int64
内部标识号    5790
交易次数       19
交易金额     1685
Name: 5789, dtype: int64
内部标识号    5791
交易次数       10
交易金额      486
Name: 5790, dtype: int64
内部标识号    5792
交易次数        0
交易金额     3648
Name: 5791, dtype: int64
内部标识号    5793
交易次数        3
交易金额      313
Name: 5792, dtype: int64
内部标识号    5794
交易次数        3
交易金额      437
Name: 5793, dtype: int64
内部标识号     5795
交易次数       247
交易金额     19082
Name: 5794, dtype: int64
内部标识号    5796
交易次数        6
交易金额      260
Name: 5795, dtype: int64
内部标识号    5797
交易次数       12
交易金额      354
Name: 5796, dtype: int64
内部标识号    5798
交易次数       15
交易金额      434
Name: 5797, dtype: int64
内部标识号    5799
交易次数        8
交易金额      164
Name: 5798, dtype: int64
内部标识号    5800
交易次数        2
交易金额      449
Name: 5799, dtype: int64
内部标识号    5801
交易次数        3
交易金额      383
Name: 5800, dtype: int64
内部标识号    5802
交易次数        3
交易金额      447
Name: 5801, dtype: int64
内部标识号    5803
交易次数        8
交易金额      481
Name: 5802, dtype: int64
内部标识号    5804
交易次数        0
交易金额     4103
Name: 5803, dtype: int64
内部标识号    5805
交易次数        4
交易金额      300
Name: 5804, dtype: int64
内部标识号    5806
交易次数        3
交易金额      165
Name: 5805, dtype: int64
内部标识号    5807
交易次数       13
交易金额      951
Name: 5806, dtype: int64
内部标识号    5808
交易次数        2
交易金额      929
Name: 5807, dtype: int64
内部标识号    5809
交易次数       15
交易金额      995
Name: 5808, dtype: int64
内部标识号     5810
交易次数         7
交易金额     22250
Name: 5809, dtype: int64
内部标识号    5811
交易次数        9
交易金额      405
Name: 5810, dtype: int64
内部标识号    5812
交易次数       24
交易金额     3874
Name: 5811, dtype: int64
内部标识号    5813
交易次数       11
交易金额      521
Name: 5812, dtype: int64
内部标识号    5814
交易次数        1
交易金额      929
Name: 5813, dtype: int64
内部标识号    5815
交易次数       12
交易金额      908
Name: 5814, dtype: int64
内部标识号    5816
交易次数       28
交易金额      524
Name: 5815, dtype: int64
内部标识号    5817
交易次数       13
交易金额      606
Name: 5816, dtype: int64
内部标识号    5818
交易次数        1
交易金额      982
Name: 5817, dtype: int64
内部标识号    5819
交易次数        2
交易金额      480
Name: 5818, dtype: int64
内部标识号    5820
交易次数       29
交易金额      749
Name: 5819, dtype: int64
内部标识号    5821
交易次数        2
交易金额      900
Name: 5820, dtype: int64
内部标识号    5822
交易次数        3
交易金额      356
Name: 5821, dtype: int64
内部标识号     5823
交易次数         6
交易金额     85079
Name: 5822, dtype: int64
内部标识号    5824
交易次数       28
交易金额     6704
Name: 5823, dtype: int64
内部标识号    5825
交易次数        6
交易金额      300
Name: 5824, dtype: int64
内部标识号    5826
交易次数       14
交易金额      423
Name: 5825, dtype: int64
内部标识号     5827
交易次数         4
交易金额     24812
Name: 5826, dtype: int64
内部标识号    5828
交易次数        1
交易金额     2863
Name: 5827, dtype: int64
内部标识号     5829
交易次数       112
交易金额     31618
Name: 5828, dtype: int64
内部标识号    5830
交易次数       10
交易金额      437
Name: 5829, dtype: int64
内部标识号     5831
交易次数         4
交易金额     43672
Name: 5830, dtype: int64
内部标识号    5832
交易次数       10
交易金额      523
Name: 5831, dtype: int64
内部标识号    5833
交易次数        0
交易金额     6664
Name: 5832, dtype: int64
内部标识号    5834
交易次数        3
交易金额      176
Name: 5833, dtype: int64
内部标识号    5835
交易次数       10
交易金额      399
Name: 5834, dtype: int64
内部标识号    5836
交易次数       14
交易金额      673
Name: 5835, dtype: int64
内部标识号    5837
交易次数        3
交易金额      362
Name: 5836, dtype: int64
内部标识号    5838
交易次数        6
交易金额      100
Name: 5837, dtype: int64
内部标识号    5839
交易次数        9
交易金额      592
Name: 5838, dtype: int64
内部标识号    5840
交易次数        3
交易金额      404
Name: 5839, dtype: int64
内部标识号    5841
交易次数       14
交易金额      412
Name: 5840, dtype: int64
内部标识号    5842
交易次数       24
交易金额     6282
Name: 5841, dtype: int64
内部标识号    5843
交易次数       12
交易金额      316
Name: 5842, dtype: int64
内部标识号    5844
交易次数        2
交易金额      447
Name: 5843, dtype: int64
内部标识号    5845
交易次数        3
交易金额      453
Name: 5844, dtype: int64
内部标识号    5846
交易次数        2
交易金额      497
Name: 5845, dtype: int64
内部标识号    5847
交易次数        7
交易金额      222
Name: 5846, dtype: int64
内部标识号    5848
交易次数        3
交易金额      306
Name: 5847, dtype: int64
内部标识号    5849
交易次数       28
交易金额      578
Name: 5848, dtype: int64
内部标识号    5850
交易次数       15
交易金额      446
Name: 5849, dtype: int64
内部标识号    5851
交易次数        1
交易金额     5343
Name: 5850, dtype: int64
内部标识号    5852
交易次数        1
交易金额      950
Name: 5851, dtype: int64
内部标识号    5853
交易次数       14
交易金额      421
Name: 5852, dtype: int64
内部标识号     5854
交易次数         8
交易金额     43293
Name: 5853, dtype: int64
内部标识号    5855
交易次数        8
交易金额      165
Name: 5854, dtype: int64
内部标识号    5856
交易次数       13
交易金额      489
Name: 5855, dtype: int64
内部标识号    5857
交易次数        3
交易金额      398
Name: 5856, dtype: int64
内部标识号    5858
交易次数        3
交易金额      496
Name: 5857, dtype: int64
内部标识号    5859
交易次数        3
交易金额      304
Name: 5858, dtype: int64
内部标识号    5860
交易次数       14
交易金额      353
Name: 5859, dtype: int64
内部标识号    5861
交易次数        2
交易金额      419
Name: 5860, dtype: int64
内部标识号    5862
交易次数       16
交易金额     6533
Name: 5861, dtype: int64
内部标识号    5863
交易次数       10
交易金额      500
Name: 5862, dtype: int64
内部标识号    5864
交易次数        9
交易金额      328
Name: 5863, dtype: int64
内部标识号     5865
交易次数         7
交易金额     31675
Name: 5864, dtype: int64
内部标识号    5866
交易次数        2
交易金额      158
Name: 5865, dtype: int64
内部标识号    5867
交易次数       15
交易金额      342
Name: 5866, dtype: int64
内部标识号    5868
交易次数       15
交易金额      333
Name: 5867, dtype: int64
内部标识号    5869
交易次数        4
交易金额      138
Name: 5868, dtype: int64
内部标识号     5870
交易次数       105
交易金额     70477
Name: 5869, dtype: int64
内部标识号    5871
交易次数        8
交易金额      232
Name: 5870, dtype: int64
内部标识号    5872
交易次数       15
交易金额      453
Name: 5871, dtype: int64
内部标识号    5873
交易次数        4
交易金额      146
Name: 5872, dtype: int64
内部标识号    5874
交易次数        3
交易金额      350
Name: 5873, dtype: int64
内部标识号    5875
交易次数        8
交易金额      452
Name: 5874, dtype: int64
内部标识号    5876
交易次数        9
交易金额      594
Name: 5875, dtype: int64
内部标识号    5877
交易次数       15
交易金额      645
Name: 5876, dtype: int64
内部标识号    5878
交易次数       10
交易金额      623
Name: 5877, dtype: int64
内部标识号    5879
交易次数        2
交易金额      311
Name: 5878, dtype: int64
内部标识号    5880
交易次数        9
交易金额      560
Name: 5879, dtype: int64
内部标识号    5881
交易次数        5
交易金额      155
Name: 5880, dtype: int64
内部标识号    5882
交易次数        2
交易金额      628
Name: 5881, dtype: int64
内部标识号    5883
交易次数       10
交易金额      597
Name: 5882, dtype: int64
内部标识号    5884
交易次数        8
交易金额      954
Name: 5883, dtype: int64
内部标识号    5885
交易次数        0
交易金额     6243
Name: 5884, dtype: int64
内部标识号    5886
交易次数       10
交易金额      436
Name: 5885, dtype: int64
内部标识号    5887
交易次数       10
交易金额      946
Name: 5886, dtype: int64
内部标识号    5888
交易次数       13
交易金额      332
Name: 5887, dtype: int64
内部标识号    5889
交易次数       11
交易金额      494
Name: 5888, dtype: int64
内部标识号    5890
交易次数        2
交易金额      763
Name: 5889, dtype: int64
内部标识号    5891
交易次数        0
交易金额     3056
Name: 5890, dtype: int64
内部标识号    5892
交易次数        1
交易金额     2535
Name: 5891, dtype: int64
内部标识号    5893
交易次数        0
交易金额     5523
Name: 5892, dtype: int64
内部标识号    5894
交易次数        3
交易金额      331
Name: 5893, dtype: int64
内部标识号    5895
交易次数        2
交易金额      918
Name: 5894, dtype: int64
内部标识号    5896
交易次数       11
交易金额      660
Name: 5895, dtype: int64
内部标识号    5897
交易次数        1
交易金额      856
Name: 5896, dtype: int64
内部标识号    5898
交易次数        2
交易金额      392
Name: 5897, dtype: int64
内部标识号    5899
交易次数       20
交易金额      741
Name: 5898, dtype: int64
内部标识号    5900
交易次数        6
交易金额      146
Name: 5899, dtype: int64
内部标识号    5901
交易次数        2
交易金额      347
Name: 5900, dtype: int64
内部标识号    5902
交易次数        6
交易金额      295
Name: 5901, dtype: int64
内部标识号     5903
交易次数         4
交易金额     84085
Name: 5902, dtype: int64
内部标识号    5904
交易次数        7
交易金额      165
Name: 5903, dtype: int64
内部标识号    5905
交易次数       10
交易金额      394
Name: 5904, dtype: int64
内部标识号    5906
交易次数        8
交易金额      290
Name: 5905, dtype: int64
内部标识号    5907
交易次数       14
交易金额      893
Name: 5906, dtype: int64
内部标识号    5908
交易次数        1
交易金额      547
Name: 5907, dtype: int64
内部标识号    5909
交易次数       19
交易金额     4240
Name: 5908, dtype: int64
内部标识号    5910
交易次数        0
交易金额     5709
Name: 5909, dtype: int64
内部标识号    5911
交易次数        6
交易金额      239
Name: 5910, dtype: int64
内部标识号    5912
交易次数       18
交易金额     9024
Name: 5911, dtype: int64
内部标识号    5913
交易次数        0
交易金额     2466
Name: 5912, dtype: int64
内部标识号    5914
交易次数       30
交易金额     3445
Name: 5913, dtype: int64
内部标识号    5915
交易次数        1
交易金额      684
Name: 5914, dtype: int64
内部标识号    5916
交易次数       11
交易金额      428
Name: 5915, dtype: int64
内部标识号    5917
交易次数       18
交易金额      651
Name: 5916, dtype: int64
内部标识号    5918
交易次数        3
交易金额      364
Name: 5917, dtype: int64
内部标识号    5919
交易次数       11
交易金额      673
Name: 5918, dtype: int64
内部标识号     5920
交易次数         8
交易金额     46744
Name: 5919, dtype: int64
内部标识号    5921
交易次数       15
交易金额      403
Name: 5920, dtype: int64
内部标识号    5922
交易次数       19
交易金额     8894
Name: 5921, dtype: int64
内部标识号    5923
交易次数        2
交易金额      476
Name: 5922, dtype: int64
内部标识号    5924
交易次数        9
交易金额      936
Name: 5923, dtype: int64
内部标识号     5925
交易次数         4
交易金额     21550
Name: 5924, dtype: int64
内部标识号     5926
交易次数         6
交易金额     23372
Name: 5925, dtype: int64
内部标识号    5927
交易次数       10
交易金额      400
Name: 5926, dtype: int64
内部标识号    5928
交易次数        1
交易金额      901
Name: 5927, dtype: int64
内部标识号    5929
交易次数       10
交易金额      888
Name: 5928, dtype: int64
内部标识号    5930
交易次数        3
交易金额      476
Name: 5929, dtype: int64
内部标识号    5931
交易次数        5
交易金额      120
Name: 5930, dtype: int64
内部标识号    5932
交易次数        7
交易金额      123
Name: 5931, dtype: int64
内部标识号    5933
交易次数       15
交易金额      469
Name: 5932, dtype: int64
内部标识号    5934
交易次数        3
交易金额      399
Name: 5933, dtype: int64
内部标识号    5935
交易次数       14
交易金额      335
Name: 5934, dtype: int64
内部标识号    5936
交易次数       25
交易金额     7358
Name: 5935, dtype: int64
内部标识号     5937
交易次数       167
交易金额     96877
Name: 5936, dtype: int64
内部标识号    5938
交易次数        2
交易金额      679
Name: 5937, dtype: int64
内部标识号    5939
交易次数       11
交易金额      404
Name: 5938, dtype: int64
内部标识号    5940
交易次数        3
交易金额      229
Name: 5939, dtype: int64
内部标识号    5941
交易次数        0
交易金额     1742
Name: 5940, dtype: int64
内部标识号    5942
交易次数        2
交易金额      914
Name: 5941, dtype: int64
内部标识号    5943
交易次数       18
交易金额      706
Name: 5942, dtype: int64
内部标识号    5944
交易次数        2
交易金额      886
Name: 5943, dtype: int64
内部标识号     5945
交易次数       153
交易金额     21613
Name: 5944, dtype: int64
内部标识号    5946
交易次数       11
交易金额      946
Name: 5945, dtype: int64
内部标识号     5947
交易次数         3
交易金额     37626
Name: 5946, dtype: int64
内部标识号    5948
交易次数        8
交易金额      722
Name: 5947, dtype: int64
内部标识号    5949
交易次数        1
交易金额     9642
Name: 5948, dtype: int64
内部标识号    5950
交易次数        3
交易金额      221
Name: 5949, dtype: int64
内部标识号    5951
交易次数        8
交易金额      269
Name: 5950, dtype: int64
内部标识号    5952
交易次数       26
交易金额     5773
Name: 5951, dtype: int64
内部标识号    5953
交易次数        6
交易金额      245
Name: 5952, dtype: int64
内部标识号    5954
交易次数       30
交易金额     4602
Name: 5953, dtype: int64
内部标识号    5955
交易次数        3
交易金额      324
Name: 5954, dtype: int64
内部标识号    5956
交易次数       15
交易金额      305
Name: 5955, dtype: int64
内部标识号    5957
交易次数       15
交易金额      985
Name: 5956, dtype: int64
内部标识号    5958
交易次数        3
交易金额      368
Name: 5957, dtype: int64
内部标识号    5959
交易次数        2
交易金额      256
Name: 5958, dtype: int64
内部标识号    5960
交易次数        1
交易金额      665
Name: 5959, dtype: int64
内部标识号    5961
交易次数       11
交易金额      347
Name: 5960, dtype: int64
内部标识号    5962
交易次数       15
交易金额      313
Name: 5961, dtype: int64
内部标识号    5963
交易次数       12
交易金额      561
Name: 5962, dtype: int64
内部标识号    5964
交易次数        2
交易金额      388
Name: 5963, dtype: int64
内部标识号     5965
交易次数         5
交易金额     20932
Name: 5964, dtype: int64
内部标识号    5966
交易次数       12
交易金额      371
Name: 5965, dtype: int64
内部标识号    5967
交易次数        8
交易金额      753
Name: 5966, dtype: int64
内部标识号    5968
交易次数        2
交易金额      607
Name: 5967, dtype: int64
内部标识号    5969
交易次数       15
交易金额      732
Name: 5968, dtype: int64
内部标识号    5970
交易次数       13
交易金额      749
Name: 5969, dtype: int64
内部标识号    5971
交易次数       13
交易金额      471
Name: 5970, dtype: int64
内部标识号    5972
交易次数        7
交易金额      137
Name: 5971, dtype: int64
内部标识号    5973
交易次数        8
交易金额      337
Name: 5972, dtype: int64
内部标识号    5974
交易次数       14
交易金额      524
Name: 5973, dtype: int64
内部标识号    5975
交易次数       15
交易金额     7299
Name: 5974, dtype: int64
内部标识号    5976
交易次数        2
交易金额      458
Name: 5975, dtype: int64
内部标识号     5977
交易次数        62
交易金额     18823
Name: 5976, dtype: int64
内部标识号    5978
交易次数        3
交易金额      498
Name: 5977, dtype: int64
内部标识号    5979
交易次数        8
交易金额      836
Name: 5978, dtype: int64
内部标识号    5980
交易次数        2
交易金额      441
Name: 5979, dtype: int64
内部标识号    5981
交易次数       12
交易金额      578
Name: 5980, dtype: int64
内部标识号    5982
交易次数        1
交易金额     4347
Name: 5981, dtype: int64
内部标识号    5983
交易次数       11
交易金额      349
Name: 5982, dtype: int64
内部标识号    5984
交易次数       12
交易金额      729
Name: 5983, dtype: int64
内部标识号    5985
交易次数        9
交易金额      402
Name: 5984, dtype: int64
内部标识号     5986
交易次数        77
交易金额     27353
Name: 5985, dtype: int64
内部标识号    5987
交易次数        1
交易金额      611
Name: 5986, dtype: int64
内部标识号    5988
交易次数        9
交易金额      824
Name: 5987, dtype: int64
内部标识号    5989
交易次数        2
交易金额      593
Name: 5988, dtype: int64
内部标识号    5990
交易次数       12
交易金额      557
Name: 5989, dtype: int64
内部标识号    5991
交易次数        6
交易金额      264
Name: 5990, dtype: int64
内部标识号    5992
交易次数        0
交易金额     3844
Name: 5991, dtype: int64
内部标识号    5993
交易次数        9
交易金额      408
Name: 5992, dtype: int64
内部标识号    5994
交易次数       11
交易金额      707
Name: 5993, dtype: int64
内部标识号    5995
交易次数        2
交易金额      871
Name: 5994, dtype: int64
内部标识号    5996
交易次数        2
交易金额      216
Name: 5995, dtype: int64
内部标识号    5997
交易次数        2
交易金额      340
Name: 5996, dtype: int64
内部标识号    5998
交易次数       13
交易金额      986
Name: 5997, dtype: int64
内部标识号    5999
交易次数        1
交易金额      603
Name: 5998, dtype: int64
内部标识号    6000
交易次数       20
交易金额     2536
Name: 5999, dtype: int64
内部标识号    6001
交易次数        1
交易金额      769
Name: 6000, dtype: int64
内部标识号    6002
交易次数        8
交易金额      275
Name: 6001, dtype: int64
内部标识号    6003
交易次数       14
交易金额      350
Name: 6002, dtype: int64
内部标识号    6004
交易次数        4
交易金额      241
Name: 6003, dtype: int64
内部标识号     6005
交易次数       251
交易金额     13093
Name: 6004, dtype: int64
内部标识号     6006
交易次数       273
交易金额     37200
Name: 6005, dtype: int64
内部标识号    6007
交易次数       11
交易金额      379
Name: 6006, dtype: int64
内部标识号     6008
交易次数       256
交易金额     23534
Name: 6007, dtype: int64
内部标识号    6009
交易次数        6
交易金额      183
Name: 6008, dtype: int64
内部标识号    6010
交易次数        0
交易金额     2714
Name: 6009, dtype: int64
内部标识号     6011
交易次数         6
交易金额     17912
Name: 6010, dtype: int64
内部标识号    6012
交易次数       27
交易金额       79
Name: 6011, dtype: int64
内部标识号    6013
交易次数       13
交易金额      952
Name: 6012, dtype: int64
内部标识号    6014
交易次数        5
交易金额      144
Name: 6013, dtype: int64
内部标识号    6015
交易次数        3
交易金额      463
Name: 6014, dtype: int64
内部标识号    6016
交易次数        7
交易金额      266
Name: 6015, dtype: int64
内部标识号    6017
交易次数       29
交易金额      884
Name: 6016, dtype: int64
内部标识号    6018
交易次数       26
交易金额      628
Name: 6017, dtype: int64
内部标识号     6019
交易次数       233
交易金额     10451
Name: 6018, dtype: int64
内部标识号    6020
交易次数       12
交易金额      815
Name: 6019, dtype: int64
内部标识号    6021
交易次数        0
交易金额     3174
Name: 6020, dtype: int64
内部标识号     6022
交易次数         6
交易金额     50177
Name: 6021, dtype: int64
内部标识号    6023
交易次数       12
交易金额      506
Name: 6022, dtype: int64
内部标识号    6024
交易次数       10
交易金额      324
Name: 6023, dtype: int64
内部标识号    6025
交易次数        8
交易金额      481
Name: 6024, dtype: int64
内部标识号    6026
交易次数       15
交易金额      832
Name: 6025, dtype: int64
内部标识号    6027
交易次数        3
交易金额      464
Name: 6026, dtype: int64
内部标识号    6028
交易次数       11
交易金额      778
Name: 6027, dtype: int64
内部标识号    6029
交易次数       11
交易金额      491
Name: 6028, dtype: int64
内部标识号    6030
交易次数        6
交易金额      292
Name: 6029, dtype: int64
内部标识号    6031
交易次数        1
交易金额      543
Name: 6030, dtype: int64
内部标识号     6032
交易次数         7
交易金额     14916
Name: 6031, dtype: int64
内部标识号    6033
交易次数        2
交易金额      788
Name: 6032, dtype: int64
内部标识号     6034
交易次数         4
交易金额     92855
Name: 6033, dtype: int64
内部标识号    6035
交易次数        1
交易金额      800
Name: 6034, dtype: int64
内部标识号    6036
交易次数        5
交易金额      240
Name: 6035, dtype: int64
内部标识号    6037
交易次数       24
交易金额     1460
Name: 6036, dtype: int64
内部标识号    6038
交易次数        1
交易金额     8998
Name: 6037, dtype: int64
内部标识号    6039
交易次数        4
交易金额      299
Name: 6038, dtype: int64
内部标识号    6040
交易次数        3
交易金额      470
Name: 6039, dtype: int64
内部标识号    6041
交易次数        2
交易金额      482
Name: 6040, dtype: int64
内部标识号    6042
交易次数       12
交易金额      333
Name: 6041, dtype: int64
内部标识号    6043
交易次数       14
交易金额      648
Name: 6042, dtype: int64
内部标识号    6044
交易次数        2
交易金额      914
Name: 6043, dtype: int64
内部标识号     6045
交易次数         6
交易金额     87836
Name: 6044, dtype: int64
内部标识号    6046
交易次数       15
交易金额      844
Name: 6045, dtype: int64
内部标识号    6047
交易次数       23
交易金额     3185
Name: 6046, dtype: int64
内部标识号    6048
交易次数       12
交易金额      600
Name: 6047, dtype: int64
内部标识号    6049
交易次数        9
交易金额      675
Name: 6048, dtype: int64
内部标识号    6050
交易次数       13
交易金额      553
Name: 6049, dtype: int64
内部标识号    6051
交易次数        2
交易金额      338
Name: 6050, dtype: int64
内部标识号    6052
交易次数        1
交易金额     4328
Name: 6051, dtype: int64
内部标识号    6053
交易次数       10
交易金额      598
Name: 6052, dtype: int64
内部标识号    6054
交易次数       24
交易金额      875
Name: 6053, dtype: int64
内部标识号     6055
交易次数         3
交易金额     85679
Name: 6054, dtype: int64
内部标识号    6056
交易次数       15
交易金额      880
Name: 6055, dtype: int64
内部标识号    6057
交易次数        2
交易金额      740
Name: 6056, dtype: int64
内部标识号    6058
交易次数        9
交易金额      311
Name: 6057, dtype: int64
内部标识号     6059
交易次数        99
交易金额     67270
Name: 6058, dtype: int64
内部标识号    6060
交易次数       14
交易金额      452
Name: 6059, dtype: int64
内部标识号    6061
交易次数       12
交易金额      887
Name: 6060, dtype: int64
内部标识号    6062
交易次数        8
交易金额      737
Name: 6061, dtype: int64
内部标识号     6063
交易次数         3
交易金额     28661
Name: 6062, dtype: int64
内部标识号     6064
交易次数         6
交易金额     82883
Name: 6063, dtype: int64
内部标识号    6065
交易次数        6
交易金额      169
Name: 6064, dtype: int64
内部标识号    6066
交易次数        2

Name: 6177, dtype: int64
内部标识号    6179
交易次数        2
交易金额      231
Name: 6178, dtype: int64
内部标识号    6180
交易次数       28
交易金额     5103
Name: 6179, dtype: int64
内部标识号    6181
交易次数       30
交易金额     3364
Name: 6180, dtype: int64
内部标识号    6182
交易次数        2
交易金额      394
Name: 6181, dtype: int64
内部标识号    6183
交易次数        4
交易金额      124
Name: 6182, dtype: int64
内部标识号    6184
交易次数       29
交易金额      838
Name: 6183, dtype: int64
内部标识号    6185
交易次数        2
交易金额      329
Name: 6184, dtype: int64
内部标识号    6186
交易次数       11
交易金额      538
Name: 6185, dtype: int64
内部标识号    6187
交易次数        2
交易金额      692
Name: 6186, dtype: int64
内部标识号    6188
交易次数       25
交易金额      656
Name: 6187, dtype: int64
内部标识号    6189
交易次数        8
交易金额      349
Name: 6188, dtype: int64
内部标识号    6190
交易次数        2
交易金额      433
Name: 6189, dtype: int64
内部标识号    6191
交易次数        8
交易金额      698
Name: 6190, dtype: int64
内部标识号    6192
交易次数        8
交易金额      719
Name: 6191, dtype: int64
内部标识号    6193
交易次数       14
交易金额      367
Name: 6192, dtype: int64
内部标识号    6194
交易次数       14
交易金额      383
Name: 6193, dtype: int64
内部标识号     6195
交易次数         3
交易金额     27093
Name: 6194, dtype: int64
内部标识号    6196
交易次数        2
交易金额      384
Name: 6195, dtype: int64
内部标识号    6197
交易次数       10
交易金额      345
Name: 6196, dtype: int64
内部标识号    6198
交易次数        1
交易金额      783
Name: 6197, dtype: int64
内部标识号    6199
交易次数        8
交易金额      153
Name: 6198, dtype: int64
内部标识号    6200
交易次数        9
交易金额     1000
Name: 6199, dtype: int64
内部标识号    6201
交易次数        7
交易金额      261
Name: 6200, dtype: int64
内部标识号    6202
交易次数        0
交易金额     1847
Name: 6201, dtype: int64
内部标识号    6203
交易次数        1
交易金额      900
Name: 6202, dtype: int64
内部标识号    6204
交易次数        3
交易金额      445
Name: 6203, dtype: int64
内部标识号    6205
交易次数        8
交易金额      520
Name: 6204, dtype: int64
内部标识号    6206
交易次数        2
交易金额      257
Name: 6205, dtype: int64
内部标识号    6207
交易次数        2
交易金额      586
Name: 6206, dtype: int64
内部标识号    6208
交易次数        2
交易金额      870
Name: 6207, dtype: int64
内部标识号    6209
交易次数        2
交易金额      656
Name: 6208, dtype: int64
内部标识号    6210
交易次数        0
交易金额     4478
Name: 6209, dtype: int64
内部标识号    6211
交易次数        2
交易金额      605
Name: 6210, dtype: int64
内部标识号    6212
交易次数        3
交易金额      284
Name: 6211, dtype: int64
内部标识号    6213
交易次数       20
交易金额     2926
Name: 6212, dtype: int64
内部标识号    6214
交易次数        1
交易金额      501
Name: 6213, dtype: int64
内部标识号    6215
交易次数        1
交易金额      504
Name: 6214, dtype: int64
内部标识号    6216
交易次数        8
交易金额      907
Name: 6215, dtype: int64
内部标识号    6217
交易次数        3
交易金额      464
Name: 6216, dtype: int64
内部标识号    6218
交易次数       13
交易金额      839
Name: 6217, dtype: int64
内部标识号    6219
交易次数       12
交易金额      312
Name: 6218, dtype: int64
内部标识号    6220
交易次数        8
交易金额      376
Name: 6219, dtype: int64
内部标识号    6221
交易次数        2
交易金额      909
Name: 6220, dtype: int64
内部标识号    6222
交易次数       13
交易金额      454
Name: 6221, dtype: int64
内部标识号    6223
交易次数        2
交易金额      107
Name: 6222, dtype: int64
内部标识号    6224
交易次数        1
交易金额      969
Name: 6223, dtype: int64
内部标识号    6225
交易次数       14
交易金额      423
Name: 6224, dtype: int64
内部标识号    6226
交易次数        8
交易金额      110
Name: 6225, dtype: int64
内部标识号    6227
交易次数        3
交易金额      365
Name: 6226, dtype: int64
内部标识号     6228
交易次数         3
交易金额     86369
Name: 6227, dtype: int64
内部标识号    6229
交易次数        0
交易金额     4831
Name: 6228, dtype: int64
内部标识号    6230
交易次数        1
交易金额      670
Name: 6229, dtype: int64
内部标识号    6231
交易次数        2
交易金额      854
Name: 6230, dtype: int64
内部标识号    6232
交易次数        8
交易金额      248
Name: 6231, dtype: int64
内部标识号    6233
交易次数        3
交易金额      366
Name: 6232, dtype: int64
内部标识号    6234
交易次数       13
交易金额      888
Name: 6233, dtype: int64
内部标识号    6235
交易次数        8
交易金额      269
Name: 6234, dtype: int64
内部标识号    6236
交易次数        3
交易金额      446
Name: 6235, dtype: int64
内部标识号    6237
交易次数        0
交易金额     7413
Name: 6236, dtype: int64
内部标识号    6238
交易次数       10
交易金额      703
Name: 6237, dtype: int64
内部标识号    6239
交易次数        9
交易金额      758
Name: 6238, dtype: int64
内部标识号    6240
交易次数        5
交易金额      234
Name: 6239, dtype: int64
内部标识号    6241
交易次数        7
交易金额      172
Name: 6240, dtype: int64
内部标识号    6242
交易次数        8
交易金额      754
Name: 6241, dtype: int64
内部标识号    6243
交易次数        1
交易金额     9817
Name: 6242, dtype: int64
内部标识号    6244
交易次数       15
交易金额      455
Name: 6243, dtype: int64
内部标识号    6245
交易次数        3
交易金额      238
Name: 6244, dtype: int64
内部标识号    6246
交易次数        8
交易金额      480
Name: 6245, dtype: int64
内部标识号    6247
交易次数       10
交易金额      878
Name: 6246, dtype: int64
内部标识号    6248
交易次数        1
交易金额     7391
Name: 6247, dtype: int64
内部标识号    6249
交易次数       16
交易金额     3322
Name: 6248, dtype: int64
内部标识号    6250
交易次数        8
交易金额      919
Name: 6249, dtype: int64
内部标识号    6251
交易次数       28
交易金额       15
Name: 6250, dtype: int64
内部标识号    6252
交易次数       28
交易金额     9219
Name: 6251, dtype: int64
内部标识号    6253
交易次数       13
交易金额      423
Name: 6252, dtype: int64
内部标识号    6254
交易次数        3
交易金额      370
Name: 6253, dtype: int64
内部标识号    6255
交易次数        3
交易金额      350
Name: 6254, dtype: int64
内部标识号    6256
交易次数        8
交易金额      522
Name: 6255, dtype: int64
内部标识号     6257
交易次数         6
交易金额     31249
Name: 6256, dtype: int64
内部标识号    6258
交易次数       26
交易金额      984
Name: 6257, dtype: int64
内部标识号     6259
交易次数         3
交易金额     36865
Name: 6258, dtype: int64
内部标识号    6260
交易次数       21
交易金额      906
Name: 6259, dtype: int64
内部标识号    6261
交易次数       11
交易金额      800
Name: 6260, dtype: int64
内部标识号    6262
交易次数        0
交易金额     2753
Name: 6261, dtype: int64
内部标识号    6263
交易次数        1
交易金额     1716
Name: 6262, dtype: int64
内部标识号    6264
交易次数       30
交易金额      922
Name: 6263, dtype: int64
内部标识号    6265
交易次数       12
交易金额      781
Name: 6264, dtype: int64
内部标识号    6266
交易次数       15
交易金额     1573
Name: 6265, dtype: int64
内部标识号    6267
交易次数        1
交易金额      731
Name: 6266, dtype: int64
内部标识号    6268
交易次数       14
交易金额      438
Name: 6267, dtype: int64
内部标识号     6269
交易次数       262
交易金额     54695
Name: 6268, dtype: int64
内部标识号    6270
交易次数        1
交易金额      884
Name: 6269, dtype: int64
内部标识号    6271
交易次数        2
交易金额      359
Name: 6270, dtype: int64
内部标识号    6272
交易次数        4
交易金额      300
Name: 6271, dtype: int64
内部标识号    6273
交易次数        1
交易金额      606
Name: 6272, dtype: int64
内部标识号    6274
交易次数        9
交易金额      418
Name: 6273, dtype: int64
内部标识号    6275
交易次数        8
交易金额      134
Name: 6274, dtype: int64
内部标识号    6276
交易次数        0
交易金额     3428
Name: 6275, dtype: int64
内部标识号    6277
交易次数        1
交易金额      807
Name: 6276, dtype: int64
内部标识号    6278
交易次数       10
交易金额      458
Name: 6277, dtype: int64
内部标识号    6279
交易次数        2
交易金额      375
Name: 6278, dtype: int64
内部标识号    6280
交易次数       20
交易金额       63
Name: 6279, dtype: int64
内部标识号     6281
交易次数         8
交易金额     63659
Name: 6280, dtype: int64
内部标识号    6282
交易次数       14
交易金额      988
Name: 6281, dtype: int64
内部标识号    6283
交易次数       10
交易金额      363
Name: 6282, dtype: int64
内部标识号    6284
交易次数       18
交易金额      769
Name: 6283, dtype: int64
内部标识号    6285
交易次数       13
交易金额      501
Name: 6284, dtype: int64
内部标识号    6286
交易次数        2
交易金额      683
Name: 6285, dtype: int64
内部标识号    6287
交易次数        3
交易金额      332
Name: 6286, dtype: int64
内部标识号    6288
交易次数        0
交易金额     5342
Name: 6287, dtype: int64
内部标识号    6289
交易次数        2
交易金额      643
Name: 6288, dtype: int64
内部标识号    6290
交易次数        0
交易金额     6209
Name: 6289, dtype: int64
内部标识号    6291
交易次数       14
交易金额      776
Name: 6290, dtype: int64
内部标识号    6292
交易次数        3
交易金额      150
Name: 6291, dtype: int64
内部标识号    6293
交易次数        8
交易金额      169
Name: 6292, dtype: int64
内部标识号    6294
交易次数       15
交易金额      754
Name: 6293, dtype: int64
内部标识号    6295
交易次数        2
交易金额      852
Name: 6294, dtype: int64
内部标识号    6296
交易次数        5
交易金额      163
Name: 6295, dtype: int64
内部标识号    6297
交易次数        2
交易金额      346
Name: 6296, dtype: int64
内部标识号    6298
交易次数        5
交易金额      144
Name: 6297, dtype: int64
内部标识号    6299
交易次数        6
交易金额      203
Name: 6298, dtype: int64
内部标识号     6300
交易次数       121
交易金额     86525
Name: 6299, dtype: int64
内部标识号    6301
交易次数        2
交易金额      632
Name: 6300, dtype: int64
内部标识号    6302
交易次数        8
交易金额      350
Name: 6301, dtype: int64
内部标识号    6303
交易次数        0
交易金额     2904
Name: 6302, dtype: int64
内部标识号     6304
交易次数         8
交易金额     21443
Name: 6303, dtype: int64
内部标识号     6305
交易次数         6
交易金额     65536
Name: 6304, dtype: int64
内部标识号    6306
交易次数        8
交易金额      156
Name: 6305, dtype: int64
内部标识号    6307
交易次数       15
交易金额      918
Name: 6306, dtype: int64
内部标识号     6308
交易次数       254
交易金额     71463
Name: 6307, dtype: int64
内部标识号    6309
交易次数        6
交易金额      298
Name: 6308, dtype: int64
内部标识号    6310
交易次数        2
交易金额      400
Name: 6309, dtype: int64
内部标识号    6311
交易次数       12
交易金额      566
Name: 6310, dtype: int64
内部标识号    6312
交易次数        8
交易金额      194
Name: 6311, dtype: int64
内部标识号    6313
交易次数       12
交易金额      637
Name: 6312, dtype: int64
内部标识号    6314
交易次数       13
交易金额      321
Name: 6313, dtype: int64
内部标识号    6315
交易次数       23
交易金额     8770
Name: 6314, dtype: int64
内部标识号    6316
交易次数        8
交易金额      187
Name: 6315, dtype: int64
内部标识号    6317
交易次数        2
交易金额      587
Name: 6316, dtype: int64
内部标识号    6318
交易次数        6
交易金额      141
Name: 6317, dtype: int64
内部标识号    6319
交易次数        1
交易金额     9045
Name: 6318, dtype: int64
内部标识号     6320
交易次数         5
交易金额     45124
Name: 6319, dtype: int64
内部标识号    6321
交易次数        5
交易金额      129
Name: 6320, dtype: int64
内部标识号    6322
交易次数        2
交易金额      422
Name: 6321, dtype: int64
内部标识号    6323
交易次数        7
交易金额      295
Name: 6322, dtype: int64
内部标识号    6324
交易次数        2
交易金额      362
Name: 6323, dtype: int64
内部标识号    6325
交易次数        3
交易金额      181
Name: 6324, dtype: int64
内部标识号     6326
交易次数         7
交易金额     64390
Name: 6325, dtype: int64
内部标识号    6327
交易次数        7
交易金额      258
Name: 6326, dtype: int64
内部标识号    6328
交易次数        3
交易金额      221
Name: 6327, dtype: int64
内部标识号    6329
交易次数        7
交易金额      198
Name: 6328, dtype: int64
内部标识号    6330
交易次数        3
交易金额      275
Name: 6329, dtype: int64
内部标识号    6331
交易次数        2
交易金额      312
Name: 6330, dtype: int64
内部标识号    6332
交易次数        3
交易金额      500
Name: 6331, dtype: int64
内部标识号    6333
交易次数       13
交易金额      454
Name: 6332, dtype: int64
内部标识号    6334
交易次数       13
交易金额      998
Name: 6333, dtype: int64
内部标识号    6335
交易次数        4
交易金额      170
Name: 6334, dtype: int64
内部标识号    6336
交易次数       10
交易金额      486
Name: 6335, dtype: int64
内部标识号    6337
交易次数       11
交易金额      374
Name: 6336, dtype: int64
内部标识号    6338
交易次数        6
交易金额      125
Name: 6337, dtype: int64
内部标识号    6339
交易次数        8
交易金额      339
Name: 6338, dtype: int64
内部标识号    6340
交易次数        8
交易金额      370
Name: 6339, dtype: int64
内部标识号    6341
交易次数        3
交易金额      266
Name: 6340, dtype: int64
内部标识号    6342
交易次数        3
交易金额      247
Name: 6341, dtype: int64
内部标识号    6343
交易次数        0
交易金额     1677
Name: 6342, dtype: int64
内部标识号    6344
交易次数       10
交易金额      630
Name: 6343, dtype: int64
内部标识号    6345
交易次数       21
交易金额     9390
Name: 6344, dtype: int64
内部标识号    6346
交易次数        3
交易金额      464
Name: 6345, dtype: int64
内部标识号    6347
交易次数        2
交易金额      904
Name: 6346, dtype: int64
内部标识号    6348
交易次数       12
交易金额      316
Name: 6347, dtype: int64
内部标识号     6349
交易次数       249
交易金额     94192
Name: 6348, dtype: int64
内部标识号    6350
交易次数       15
交易金额      549
Name: 6349, dtype: int64
内部标识号    6351
交易次数        8
交易金额      164
Name: 6350, dtype: int64
内部标识号    6352
交易次数        2
交易金额      395
Name: 6351, dtype: int64
内部标识号    6353
交易次数       14
交易金额      963
Name: 6352, dtype: int64
内部标识号    6354
交易次数        2
交易金额      444
Name: 6353, dtype: int64
内部标识号    6355
交易次数        2
交易金额      276
Name: 6354, dtype: int64
内部标识号    6356
交易次数        2
交易金额      454
Name: 6355, dtype: int64
内部标识号    6357
交易次数        2
交易金额      715
Name: 6356, dtype: int64
内部标识号     6358
交易次数         3
交易金额     23061
Name: 6357, dtype: int64
内部标识号    6359
交易次数       10
交易金额      317
Name: 6358, dtype: int64
内部标识号    6360
交易次数       15
交易金额      310
Name: 6359, dtype: int64
内部标识号    6361
交易次数        3
交易金额      291
Name: 6360, dtype: int64
内部标识号    6362
交易次数        8
交易金额      213
Name: 6361, dtype: int64
内部标识号    6363
交易次数        0
交易金额     8979
Name: 6362, dtype: int64
内部标识号    6364
交易次数        1
交易金额      801
Name: 6363, dtype: int64
内部标识号    6365
交易次数        1
交易金额      895
Name: 6364, dtype: int64
内部标识号    6366
交易次数        9
交易金额      882
Name: 6365, dtype: int64
内部标识号    6367
交易次数       22
交易金额     5638
Name: 6366, dtype: int64
内部标识号    6368
交易次数        8
交易金额      896
Name: 6367, dtype: int64
内部标识号    6369
交易次数        0
交易金额     5315
Name: 6368, dtype: int64
内部标识号     6370
交易次数       126
交易金额     30814
Name: 6369, dtype: int64
内部标识号    6371
交易次数        5
交易金额      297
Name: 6370, dtype: int64
内部标识号    6372
交易次数       14
交易金额      598
Name: 6371, dtype: int64
内部标识号    6373
交易次数       12
交易金额      584
Name: 6372, dtype: int64
内部标识号    6374
交易次数        0
交易金额     1372
Name: 6373, dtype: int64
内部标识号    6375
交易次数       10
交易金额      324
Name: 6374, dtype: int64
内部标识号    6376
交易次数        9
交易金额      356
Name: 6375, dtype: int64
内部标识号    6377
交易次数        0
交易金额     7022
Name: 6376, dtype: int64
内部标识号    6378
交易次数        0
交易金额     6829
Name: 6377, dtype: int64
内部标识号    6379
交易次数       12
交易金额      919
Name: 6378, dtype: int64
内部标识号    6380
交易次数        2
交易金额      794
Name: 6379, dtype: int64
内部标识号    6381
交易次数        2
交易金额      749
Name: 6380, dtype: int64
内部标识号    6382
交易次数        2
交易金额      869
Name: 6381, dtype: int64
内部标识号    6383
交易次数        0
交易金额     6982
Name: 6382, dtype: int64
内部标识号    6384
交易次数        2
交易金额      953
Name: 6383, dtype: int64
内部标识号    6385
交易次数        8
交易金额      373
Name: 6384, dtype: int64
内部标识号    6386
交易次数        2
交易金额      401
Name: 6385, dtype: int64
内部标识号    6387
交易次数        2
交易金额      398
Name: 6386, dtype: int64
内部标识号    6388
交易次数        1
交易金额      925
Name: 6387, dtype: int64
内部标识号    6389
交易次数       16
交易金额      926
Name: 6388, dtype: int64
内部标识号    6390
交易次数        0
交易金额     8332
Name: 6389, dtype: int64
内部标识号    6391
交易次数        1
交易金额      916
Name: 6390, dtype: int64
内部标识号    6392
交易次数       18
交易金额      573
Name: 6391, dtype: int64
内部标识号    6393
交易次数        2
交易金额      552
Name: 6392, dtype: int64
内部标识号    6394
交易次数        3
交易金额      205
Name: 6393, dtype: int64
内部标识号    6395
交易次数        9
交易金额      651
Name: 6394, dtype: int64
内部标识号    6396
交易次数       13
交易金额      669
Name: 6395, dtype: int64
内部标识号    6397
交易次数       28
交易金额       79
Name: 6396, dtype: int64
内部标识号    6398
交易次数        9
交易金额      759
Name: 6397, dtype: int64
内部标识号    6399
交易次数        3
交易金额      109
Name: 6398, dtype: int64
内部标识号    6400
交易次数        0
交易金额     9213
Name: 6399, dtype: int64
内部标识号    6401
交易次数        3
交易金额      488
Name: 6400, dtype: int64
内部标识号    6402
交易次数       11
交易金额      815
Name: 6401, dtype: int64
内部标识号    6403
交易次数       11
交易金额      385
Name: 6402, dtype: int64
内部标识号    6404
交易次数        3
交易金额      174
Name: 6403, dtype: int64
内部标识号    6405
交易次数       15
交易金额      924
Name: 6404, dtype: int64
内部标识号    6406
交易次数        4
交易金额      175
Name: 6405, dtype: int64
内部标识号    6407
交易次数        3
交易金额      491
Name: 6406, dtype: int64
内部标识号    6408
交易次数        8
交易金额      211
Name: 6407, dtype: int64
内部标识号    6409
交易次数        7
交易金额      168
Name: 6408, dtype: int64
内部标识号    6410
交易次数       10
交易金额      358
Name: 6409, dtype: int64
内部标识号    6411
交易次数       29
交易金额     1172
Name: 6410, dtype: int64
内部标识号    6412
交易次数       14
交易金额      884
Name: 6411, dtype: int64
内部标识号    6413
交易次数       30
交易金额     5628
Name: 6412, dtype: int64
内部标识号     6414
交易次数         7
交易金额     27642
Name: 6413, dtype: int64
内部标识号    6415
交易次数       13
交易金额      781
Name: 6414, dtype: int64
内部标识号    6416
交易次数        8
交易金额      502
Name: 6415, dtype: int64
内部标识号     6417
交易次数         6
交易金额     93483
Name: 6416, dtype: int64
内部标识号    6418
交易次数       23
交易金额     6596
Name: 6417, dtype: int64
内部标识号    6419
交易次数        3
交易金额      477

Name: 6418, dtype: int64
内部标识号    6420
交易次数        2
交易金额      498
Name: 6419, dtype: int64
内部标识号    6421
交易次数       13
交易金额      493
Name: 6420, dtype: int64
内部标识号     6422
交易次数       170
交易金额     72840
Name: 6421, dtype: int64
内部标识号    6423
交易次数        5
交易金额      112
Name: 6422, dtype: int64
内部标识号     6424
交易次数         3
交易金额     31033
Name: 6423, dtype: int64
内部标识号    6425
交易次数        3
交易金额      435
Name: 6424, dtype: int64
内部标识号    6426
交易次数        3
交易金额      322
Name: 6425, dtype: int64
内部标识号    6427
交易次数       12
交易金额      736
Name: 6426, dtype: int64
内部标识号    6428
交易次数        4
交易金额      161
Name: 6427, dtype: int64
内部标识号    6429
交易次数        3
交易金额      451
Name: 6428, dtype: int64
内部标识号    6430
交易次数        6
交易金额      260
Name: 6429, dtype: int64
内部标识号    6431
交易次数        0
交易金额     6360
Name: 6430, dtype: int64
内部标识号    6432
交易次数       29
交易金额      825
Name: 6431, dtype: int64
内部标识号    6433
交易次数       28
交易金额      620
Name: 6432, dtype: int64
内部标识号    6434
交易次数        8
交易金额      559
Name: 6433, dtype: int64
内部标识号    6435
交易次数        0
交易金额     5864
Name: 6434, dtype: int64
内部标识号    6436
交易次数        3
交易金额      481
Name: 6435, dtype: int64
内部标识号    6437
交易次数       13
交易金额      807
Name: 6436, dtype: int64
内部标识号    6438
交易次数       15
交易金额      477
Name: 6437, dtype: int64
内部标识号    6439
交易次数        3
交易金额      153
Name: 6438, dtype: int64
内部标识号    6440
交易次数        1
交易金额      546
Name: 6439, dtype: int64
内部标识号    6441
交易次数        0
交易金额     9245
Name: 6440, dtype: int64
内部标识号    6442
交易次数       14
交易金额      452
Name: 6441, dtype: int64
内部标识号    6443
交易次数       10
交易金额      355
Name: 6442, dtype: int64
内部标识号    6444
交易次数        3
交易金额      481
Name: 6443, dtype: int64
内部标识号    6445
交易次数       15
交易金额      663
Name: 6444, dtype: int64
内部标识号    6446
交易次数       26
交易金额     8819
Name: 6445, dtype: int64
内部标识号    6447
交易次数        9
交易金额      605
Name: 6446, dtype: int64
内部标识号    6448
交易次数        0
交易金额     4116
Name: 6447, dtype: int64
内部标识号    6449
交易次数       13
交易金额      707
Name: 6448, dtype: int64
内部标识号    6450
交易次数        7
交易金额      182
Name: 6449, dtype: int64
内部标识号    6451
交易次数        6
交易金额      125
Name: 6450, dtype: int64
内部标识号    6452
交易次数       13
交易金额      599
Name: 6451, dtype: int64
内部标识号    6453
交易次数       16
交易金额     5954
Name: 6452, dtype: int64
内部标识号    6454
交易次数       10
交易金额      731
Name: 6453, dtype: int64
内部标识号    6455
交易次数        9
交易金额      983
Name: 6454, dtype: int64
内部标识号    6456
交易次数        3
交易金额      320
Name: 6455, dtype: int64
内部标识号    6457
交易次数       16
交易金额      990
Name: 6456, dtype: int64
内部标识号    6458
交易次数        6
交易金额      158
Name: 6457, dtype: int64
内部标识号    6459
交易次数       12
交易金额      313
Name: 6458, dtype: int64
内部标识号    6460
交易次数        7
交易金额      194
Name: 6459, dtype: int64
内部标识号    6461
交易次数        0
交易金额     3844
Name: 6460, dtype: int64
内部标识号    6462
交易次数       22
交易金额     8374
Name: 6461, dtype: int64
内部标识号    6463
交易次数       15
交易金额      883
Name: 6462, dtype: int64
内部标识号    6464
交易次数        0
交易金额     6236
Name: 6463, dtype: int64
内部标识号    6465
交易次数       21
交易金额      643
Name: 6464, dtype: int64
内部标识号    6466
交易次数       21
交易金额      898
Name: 6465, dtype: int64
内部标识号    6467
交易次数       16
交易金额     9412
Name: 6466, dtype: int64
内部标识号    6468
交易次数        7
交易金额      217
Name: 6467, dtype: int64
内部标识号    6469
交易次数        2
交易金额      942
Name: 6468, dtype: int64
内部标识号    6470
交易次数       21
交易金额     2419
Name: 6469, dtype: int64
内部标识号    6471
交易次数        5
交易金额      247
Name: 6470, dtype: int64
内部标识号    6472
交易次数        1
交易金额      507
Name: 6471, dtype: int64
内部标识号    6473
交易次数        7
交易金额      236
Name: 6472, dtype: int64
内部标识号    6474
交易次数        1
交易金额      524
Name: 6473, dtype: int64
内部标识号    6475
交易次数        0
交易金额     6697
Name: 6474, dtype: int64
内部标识号    6476
交易次数       15
交易金额      706
Name: 6475, dtype: int64
内部标识号     6477
交易次数         5
交易金额     89251
Name: 6476, dtype: int64
内部标识号    6478
交易次数       22
交易金额     6009
Name: 6477, dtype: int64
内部标识号    6479
交易次数        0
交易金额     4897
Name: 6478, dtype: int64
内部标识号    6480
交易次数        8
交易金额      908
Name: 6479, dtype: int64
内部标识号    6481
交易次数        3
交易金额      221
Name: 6480, dtype: int64
内部标识号    6482
交易次数       18
交易金额     5543
Name: 6481, dtype: int64
内部标识号    6483
交易次数        0
交易金额     5332
Name: 6482, dtype: int64
内部标识号     6484
交易次数       265
交易金额     90018
Name: 6483, dtype: int64
内部标识号    6485
交易次数        3
交易金额      444
Name: 6484, dtype: int64
内部标识号    6486
交易次数        6
交易金额      270
Name: 6485, dtype: int64
内部标识号    6487
交易次数       13
交易金额      600
Name: 6486, dtype: int64
内部标识号     6488
交易次数         3
交易金额     19861
Name: 6487, dtype: int64
内部标识号    6489
交易次数       10
交易金额      431
Name: 6488, dtype: int64
内部标识号    6490
交易次数        5
交易金额      260
Name: 6489, dtype: int64
内部标识号    6491
交易次数        9
交易金额      643
Name: 6490, dtype: int64
内部标识号    6492
交易次数        9
交易金额      738
Name: 6491, dtype: int64
内部标识号    6493
交易次数        0
交易金额     9702
Name: 6492, dtype: int64
内部标识号    6494
交易次数        3
交易金额      114
Name: 6493, dtype: int64
内部标识号    6495
交易次数        1
交易金额     5123
Name: 6494, dtype: int64
内部标识号    6496
交易次数        8
交易金额      861
Name: 6495, dtype: int64
内部标识号    6497
交易次数        1
交易金额     2448
Name: 6496, dtype: int64
内部标识号    6498
交易次数       14
交易金额      981
Name: 6497, dtype: int64
内部标识号    6499
交易次数       11
交易金额      317
Name: 6498, dtype: int64
内部标识号    6500
交易次数        8
交易金额      219
Name: 6499, dtype: int64
内部标识号    6501
交易次数        6
交易金额      120
Name: 6500, dtype: int64
内部标识号    6502
交易次数        8
交易金额      653
Name: 6501, dtype: int64
内部标识号    6503
交易次数        9
交易金额      458
Name: 6502, dtype: int64
内部标识号    6504
交易次数        0
交易金额     7954
Name: 6503, dtype: int64
内部标识号    6505
交易次数       11
交易金额      874
Name: 6504, dtype: int64
内部标识号    6506
交易次数        3
交易金额      438
Name: 6505, dtype: int64
内部标识号    6507
交易次数        8
交易金额      513
Name: 6506, dtype: int64
内部标识号    6508
交易次数        6
交易金额      123
Name: 6507, dtype: int64
内部标识号    6509
交易次数        9
交易金额      514
Name: 6508, dtype: int64
内部标识号    6510
交易次数        0
交易金额     7068
Name: 6509, dtype: int64
内部标识号    6511
交易次数        3
交易金额      484
Name: 6510, dtype: int64
内部标识号    6512
交易次数        2
交易金额      500
Name: 6511, dtype: int64
内部标识号    6513
交易次数        4
交易金额      242
Name: 6512, dtype: int64
内部标识号    6514
交易次数        2
交易金额      363
Name: 6513, dtype: int64
内部标识号    6515
交易次数       23
交易金额     9757
Name: 6514, dtype: int64
内部标识号    6516
交易次数       15
交易金额     9237
Name: 6515, dtype: int64
内部标识号    6517
交易次数       23
交易金额      586
Name: 6516, dtype: int64
内部标识号    6518
交易次数       14
交易金额      649
Name: 6517, dtype: int64
内部标识号    6519
交易次数       10
交易金额      812
Name: 6518, dtype: int64
内部标识号    6520
交易次数        8
交易金额      953
Name: 6519, dtype: int64
内部标识号    6521
交易次数       10
交易金额      315
Name: 6520, dtype: int64
内部标识号    6522
交易次数       14
交易金额      400
Name: 6521, dtype: int64
内部标识号    6523
交易次数       26
交易金额       21
Name: 6522, dtype: int64
内部标识号     6524
交易次数         3
交易金额     74541
Name: 6523, dtype: int64
内部标识号    6525
交易次数        2
交易金额      340
Name: 6524, dtype: int64
内部标识号    6526
交易次数        7
交易金额      260
Name: 6525, dtype: int64
内部标识号     6527
交易次数       112
交易金额     94797
Name: 6526, dtype: int64
内部标识号    6528
交易次数       11
交易金额      605
Name: 6527, dtype: int64
内部标识号     6529
交易次数         7
交易金额     40399
Name: 6528, dtype: int64
内部标识号    6530
交易次数       13
交易金额      363
Name: 6529, dtype: int64
内部标识号    6531
交易次数        7
交易金额      194
Name: 6530, dtype: int64
内部标识号    6532
交易次数        2
交易金额      433
Name: 6531, dtype: int64
内部标识号    6533
交易次数        3
交易金额      330
Name: 6532, dtype: int64
内部标识号    6534
交易次数        2
交易金额      906
Name: 6533, dtype: int64
内部标识号    6535
交易次数        2
交易金额      366
Name: 6534, dtype: int64
内部标识号    6536
交易次数        5
交易金额      187
Name: 6535, dtype: int64
内部标识号    6537
交易次数       12
交易金额      414
Name: 6536, dtype: int64
内部标识号    6538
交易次数        1
交易金额      821
Name: 6537, dtype: int64
内部标识号    6539
交易次数        2
交易金额      363
Name: 6538, dtype: int64
内部标识号     6540
交易次数        55
交易金额     18585
Name: 6539, dtype: int64
内部标识号    6541
交易次数        8
交易金额      331
Name: 6540, dtype: int64
内部标识号    6542
交易次数        7
交易金额      206
Name: 6541, dtype: int64
内部标识号    6543
交易次数       13
交易金额      657
Name: 6542, dtype: int64
内部标识号    6544
交易次数       13
交易金额      806
Name: 6543, dtype: int64
内部标识号    6545
交易次数        7
交易金额      256
Name: 6544, dtype: int64
内部标识号    6546
交易次数       13
交易金额      463
Name: 6545, dtype: int64
内部标识号    6547
交易次数        4
交易金额      144
Name: 6546, dtype: int64
内部标识号    6548
交易次数       19
交易金额      509
Name: 6547, dtype: int64
内部标识号    6549
交易次数        2
交易金额      373
Name: 6548, dtype: int64
内部标识号    6550
交易次数       25
交易金额     6947
Name: 6549, dtype: int64
内部标识号    6551
交易次数        8
交易金额      307
Name: 6550, dtype: int64
内部标识号    6552
交易次数       21
交易金额     4012
Name: 6551, dtype: int64
内部标识号    6553
交易次数       15
交易金额      445
Name: 6552, dtype: int64
内部标识号    6554
交易次数        4
交易金额      202
Name: 6553, dtype: int64
内部标识号    6555
交易次数        1
交易金额      792
Name: 6554, dtype: int64
内部标识号     6556
交易次数       242
交易金额     11405
Name: 6555, dtype: int64
内部标识号    6557
交易次数       14
交易金额      645
Name: 6556, dtype: int64
内部标识号    6558
交易次数        8
交易金额      174
Name: 6557, dtype: int64
内部标识号    6559
交易次数        0
交易金额     9306
Name: 6558, dtype: int64
内部标识号    6560
交易次数       12
交易金额      438
Name: 6559, dtype: int64
内部标识号    6561
交易次数        3
交易金额      340
Name: 6560, dtype: int64
内部标识号     6562
交易次数         3
交易金额     79722
Name: 6561, dtype: int64
内部标识号     6563
交易次数         6
交易金额     37483
Name: 6562, dtype: int64
内部标识号    6564
交易次数       13
交易金额      659
Name: 6563, dtype: int64
内部标识号    6565
交易次数        1
交易金额      599
Name: 6564, dtype: int64
内部标识号    6566
交易次数        9
交易金额      863
Name: 6565, dtype: int64
内部标识号    6567
交易次数        3
交易金额      484
Name: 6566, dtype: int64
内部标识号     6568
交易次数         3
交易金额     12330
Name: 6567, dtype: int64
内部标识号    6569
交易次数        9
交易金额      991
Name: 6568, dtype: int64
内部标识号     6570
交易次数         3
交易金额     81998
Name: 6569, dtype: int64
内部标识号    6571
交易次数        3
交易金额      468
Name: 6570, dtype: int64
内部标识号    6572
交易次数        8
交易金额      223
Name: 6571, dtype: int64
内部标识号    6573
交易次数        2
交易金额      807
Name: 6572, dtype: int64
内部标识号    6574
交易次数       18
交易金额     8761
Name: 6573, dtype: int64
内部标识号    6575
交易次数        3
交易金额      412
Name: 6574, dtype: int64
内部标识号    6576
交易次数        2
交易金额      492
Name: 6575, dtype: int64
内部标识号    6577
交易次数       10
交易金额      509
Name: 6576, dtype: int64
内部标识号    6578
交易次数       15
交易金额      922
Name: 6577, dtype: int64
内部标识号    6579
交易次数        0
交易金额     6674
Name: 6578, dtype: int64
内部标识号    6580
交易次数       22
交易金额     6107
Name: 6579, dtype: int64
内部标识号    6581
交易次数        4
交易金额      163
Name: 6580, dtype: int64
内部标识号    6582
交易次数       18
交易金额     1572
Name: 6581, dtype: int64
内部标识号    6583
交易次数        8
交易金额      641
Name: 6582, dtype: int64
内部标识号    6584
交易次数       12
交易金额      485
Name: 6583, dtype: int64
内部标识号    6585
交易次数        2
交易金额      358
Name: 6584, dtype: int64
内部标识号    6586
交易次数        7
交易金额      158
Name: 6585, dtype: int64
内部标识号    6587
交易次数        1
交易金额     7254
Name: 6586, dtype: int64
内部标识号    6588
交易次数       15
交易金额      632
Name: 6587, dtype: int64
内部标识号    6589
交易次数        3
交易金额      227
Name: 6588, dtype: int64
内部标识号    6590
交易次数       14
交易金额      971
Name: 6589, dtype: int64
内部标识号    6591
交易次数       17
交易金额     1165
Name: 6590, dtype: int64
内部标识号    6592
交易次数        4
交易金额      226
Name: 6591, dtype: int64
内部标识号     6593
交易次数         4
交易金额     60834
Name: 6592, dtype: int64
内部标识号    6594
交易次数        3
交易金额      308
Name: 6593, dtype: int64
内部标识号    6595
交易次数       30
交易金额     7912
Name: 6594, dtype: int64
内部标识号    6596
交易次数        8
交易金额      636
Name: 6595, dtype: int64
内部标识号     6597
交易次数        97
交易金额     80788
Name: 6596, dtype: int64
内部标识号    6598
交易次数       11
交易金额      817
Name: 6597, dtype: int64
内部标识号    6599
交易次数        5
交易金额      288
Name: 6598, dtype: int64
内部标识号     6600
交易次数       128
交易金额     21129
Name: 6599, dtype: int64
内部标识号    6601
交易次数       15
交易金额      948
Name: 6600, dtype: int64
内部标识号    6602
交易次数        2
交易金额      418
Name: 6601, dtype: int64
内部标识号    6603
交易次数       10
交易金额      747
Name: 6602, dtype: int64
内部标识号    6604
交易次数        2
交易金额      579
Name: 6603, dtype: int64
内部标识号    6605
交易次数        1
交易金额     7530
Name: 6604, dtype: int64
内部标识号    6606
交易次数        3
交易金额      387
Name: 6605, dtype: int64
内部标识号     6607
交易次数         6
交易金额     26976
Name: 6606, dtype: int64
内部标识号    6608
交易次数       10
交易金额      316
Name: 6607, dtype: int64
内部标识号    6609
交易次数       14
交易金额      366
Name: 6608, dtype: int64
内部标识号    6610
交易次数       15
交易金额      921
Name: 6609, dtype: int64
内部标识号    6611
交易次数        9
交易金额      384
Name: 6610, dtype: int64
内部标识号    6612
交易次数       15
交易金额      549
Name: 6611, dtype: int64
内部标识号    6613
交易次数       11
交易金额      447
Name: 6612, dtype: int64
内部标识号    6614
交易次数        3
交易金额      344
Name: 6613, dtype: int64
内部标识号    6615
交易次数        2
交易金额      451
Name: 6614, dtype: int64
内部标识号    6616
交易次数        1
交易金额      506
Name: 6615, dtype: int64
内部标识号    6617
交易次数       11
交易金额      600
Name: 6616, dtype: int64
内部标识号    6618
交易次数        8
交易金额      115
Name: 6617, dtype: int64
内部标识号     6619
交易次数       202
交易金额     33018
Name: 6618, dtype: int64
内部标识号    6620
交易次数       10
交易金额      354
Name: 6619, dtype: int64
内部标识号    6621
交易次数       27
交易金额      645
Name: 6620, dtype: int64
内部标识号     6622
交易次数         6
交易金额     69916
Name: 6621, dtype: int64
内部标识号    6623
交易次数        1
交易金额      764
Name: 6622, dtype: int64
内部标识号    6624
交易次数        2
交易金额      765
Name: 6623, dtype: int64
内部标识号    6625
交易次数        8
交易金额      915
Name: 6624, dtype: int64
内部标识号    6626
交易次数        2
交易金额      928
Name: 6625, dtype: int64
内部标识号    6627
交易次数       10
交易金额      843
Name: 6626, dtype: int64
内部标识号    6628
交易次数       15
交易金额      327
Name: 6627, dtype: int64
内部标识号    6629
交易次数        3
交易金额      241
Name: 6628, dtype: int64
内部标识号    6630
交易次数       22
交易金额      656
Name: 6629, dtype: int64
内部标识号    6631
交易次数       15
交易金额      739
Name: 6630, dtype: int64
内部标识号    6632
交易次数       19
交易金额       59
Name: 6631, dtype: int64
内部标识号    6633
交易次数        6
交易金额      178
Name: 6632, dtype: int64
内部标识号    6634
交易次数        3
交易金额      148
Name: 6633, dtype: int64
内部标识号    6635
交易次数        1
交易金额      536
Name: 6634, dtype: int64
内部标识号    6636
交易次数        3
交易金额      474
Name: 6635, dtype: int64
内部标识号    6637
交易次数        4
交易金额      128
Name: 6636, dtype: int64
内部标识号    6638
交易次数        7
交易金额      204
Name: 6637, dtype: int64
内部标识号     6639
交易次数         8
交易金额     89296
Name: 6638, dtype: int64
内部标识号     6640
交易次数         6
交易金额     92666
Name: 6639, dtype: int64
内部标识号     6641
交易次数         8
交易金额     37389
Name: 6640, dtype: int64
内部标识号    6642
交易次数        8
交易金额      832
Name: 6641, dtype: int64
内部标识号    6643
交易次数        2
交易金额      248
Name: 6642, dtype: int64
内部标识号     6644
交易次数         5
交易金额     36815
Name: 6643, dtype: int64
内部标识号     6645
交易次数         4
交易金额     45247
Name: 6644, dtype: int64
内部标识号    6646
交易次数        0
交易金额     4142
Name: 6645, dtype: int64
内部标识号    6647
交易次数       12
交易金额      973
Name: 6646, dtype: int64
内部标识号    6648
交易次数       20
交易金额      585
Name: 6647, dtype: int64
内部标识号    6649
交易次数        3
交易金额      328
Name: 6648, dtype: int64
内部标识号    6650
交易次数        6
交易金额      118
Name: 6649, dtype: int64
内部标识号    6651
交易次数       23
交易金额       44
Name: 6650, dtype: int64
内部标识号    6652
交易次数        8
交易金额      180
Name: 6651, dtype: int64
内部标识号    6653
交易次数       27
交易金额     3593
Name: 6652, dtype: int64
内部标识号    6654
交易次数        3
交易金额      397
Name: 6653, dtype: int64
内部标识号    6655
交易次数       15
交易金额      519
Name: 6654, dtype: int64
内部标识号    6656
交易次数       15
交易金额      592
Name: 6655, dtype: int64
内部标识号    6657
交易次数        0
交易金额     1806
Name: 6656, dtype: int64
内部标识号    6658
交易次数        0
交易金额     3229
Name: 6657, dtype: int64
内部标识号    6659
交易次数       26
交易金额      802
Name: 6658, dtype: int64
内部标识号    6660
交易次数        3
交易金额      309
Name: 6659, dtype: int64
内部标识号    6661
交易次数       28
交易金额      991
Name: 6660, dtype: int64
内部标识号    6662
交易次数        8
交易金额      212
Name: 6661, dtype: int64
内部标识号    6663
交易次数       13
交易金额      850
Name: 6662, dtype: int64
内部标识号    6664
交易次数        3
交易金额      325
Name: 6663, dtype: int64
内部标识号    6665
交易次数       11
交易金额      350
Name: 6664, dtype: int64
内部标识号     6666
交易次数       123
交易金额     91717
Name: 6665, dtype: int64
内部标识号    6667
交易次数       18
交易金额     6712
Name: 6666, dtype: int64
内部标识号     6668
交易次数        33
交易金额     54034
Name: 6667, dtype: int64
内部标识号    6669
交易次数       26
交易金额     2050
Name: 6668, dtype: int64
内部标识号    6670
交易次数        0
交易金额     6464
Name: 6669, dtype: int64
内部标识号    6671
交易次数        3
交易金额      497
Name: 6670, dtype: int64
内部标识号    6672
交易次数       11
交易金额      582
Name: 6671, dtype: int64
内部标识号    6673
交易次数        2
交易金额      349
Name: 6672, dtype: int64
内部标识号    6674
交易次数       20
交易金额     3635
Name: 6673, dtype: int64
内部标识号    6675
交易次数       11
交易金额      988
Name: 6674, dtype: int64
内部标识号    6676
交易次数        0
交易金额     4992
Name: 6675, dtype: int64
内部标识号    6677
交易次数        5
交易金额      206
Name: 6676, dtype: int64
内部标识号    6678
交易次数        2
交易金额      418
Name: 6677, dtype: int64
内部标识号    6679
交易次数        0
交易金额     8434
Name: 6678, dtype: int64
内部标识号    6680
交易次数        8
交易金额      720
Name: 6679, dtype: int64
内部标识号    6681
交易次数       10
交易金额      402
Name: 6680, dtype: int64
内部标识号     6682
交易次数         4
交易金额     68545
Name: 6681, dtype: int64
内部标识号    6683
交易次数       11
交易金额      621
Name: 6682, dtype: int64
内部标识号    6684
交易次数        2
交易金额      679
Name: 6683, dtype: int64
内部标识号    6685
交易次数        8
交易金额      159
Name: 6684, dtype: int64
内部标识号    6686
交易次数       25
交易金额     3524
Name: 6685, dtype: int64
内部标识号    6687
交易次数       14
交易金额      338
Name: 6686, dtype: int64
内部标识号    6688
交易次数        2
交易金额      392
Name: 6687, dtype: int64
内部标识号     6689
交易次数         4
交易金额     31094
Name: 6688, dtype: int64
内部标识号    6690
交易次数        2
交易金额      192
Name: 6689, dtype: int64
内部标识号    6691
交易次数       13
交易金额      429
Name: 6690, dtype: int64
内部标识号    6692
交易次数        2
交易金额      301
Name: 6691, dtype: int64
内部标识号    6693
交易次数        1
交易金额     7240
Name: 6692, dtype: int64
内部标识号    6694
交易次数       15
交易金额      777
Name: 6693, dtype: int64
内部标识号    6695
交易次数        0
交易金额     9163
Name: 6694, dtype: int64
内部标识号    6696
交易次数        8
交易金额      465
Name: 6695, dtype: int64
内部标识号    6697
交易次数        3
交易金额      393
Name: 6696, dtype: int64
内部标识号    6698
交易次数       15
交易金额      954
Name: 6697, dtype: int64
内部标识号    6699
交易次数        1
交易金额     7475
Name: 6698, dtype: int64
内部标识号     6700
交易次数         4
交易金额     23931
Name: 6699, dtype: int64
内部标识号    6701
交易次数       15
交易金额      456
Name: 6700, dtype: int64
内部标识号    6702
交易次数       13
交易金额      320
Name: 6701, dtype: int64
内部标识号    6703
交易次数       11
交易金额      653
Name: 6702, dtype: int64
内部标识号    6704
交易次数        3
交易金额      416
Name: 6703, dtype: int64
内部标识号    6705
交易次数        3
交易金额      480
Name: 6704, dtype: int64
内部标识号    6706
交易次数        2
交易金额      319
Name: 6705, dtype: int64
内部标识号     6707
交易次数         5
交易金额     89079
Name: 6706, dtype: int64
内部标识号    6708
交易次数        1
交易金额     8091
Name: 6707, dtype: int64
内部标识号    6709
交易次数        8
交易金额      448
Name: 6708, dtype: int64
内部标识号    6710
交易次数       24
交易金额     4560
Name: 6709, dtype: int64
内部标识号    6711
交易次数        3
交易金额      254
Name: 6710, dtype: int64
内部标识号    6712
交易次数       14
交易金额      860
Name: 6711, dtype: int64
内部标识号    6713
交易次数        9
交易金额      529
Name: 6712, dtype: int64
内部标识号    6714
交易次数        4
交易金额      107
Name: 6713, dtype: int64
内部标识号    6715
交易次数        0
交易金额     1694
Name: 6714, dtype: int64
内部标识号    6716
交易次数        8
交易金额      160

内部标识号    6768
交易次数       12
交易金额      318
Name: 6767, dtype: int64
内部标识号    6769
交易次数        7
交易金额      220
Name: 6768, dtype: int64
内部标识号     6770
交易次数       261
交易金额     73455
Name: 6769, dtype: int64
内部标识号    6771
交易次数       15
交易金额      416
Name: 6770, dtype: int64
内部标识号     6772
交易次数         5
交易金额     64074
Name: 6771, dtype: int64
内部标识号    6773
交易次数        3
交易金额      252
Name: 6772, dtype: int64
内部标识号     6774
交易次数         3
交易金额     52881
Name: 6773, dtype: int64
内部标识号     6775
交易次数         8
交易金额     47200
Name: 6774, dtype: int64
内部标识号    6776
交易次数        9
交易金额      665
Name: 6775, dtype: int64
内部标识号    6777
交易次数        5
交易金额      268
Name: 6776, dtype: int64
内部标识号    6778
交易次数        1
交易金额     9532
Name: 6777, dtype: int64
内部标识号     6779
交易次数         5
交易金额     19904
Name: 6778, dtype: int64
内部标识号    6780
交易次数       14
交易金额      706
Name: 6779, dtype: int64
内部标识号    6781
交易次数        3
交易金额      350
Name: 6780, dtype: int64
内部标识号    6782
交易次数        3
交易金额      303
Name: 6781, dtype: int64
内部标识号    6783
交易次数        8
交易金额      405
Name: 6782, dtype: int64
内部标识号    6784
交易次数        3
交易金额      203
Name: 6783, dtype: int64
内部标识号    6785
交易次数       13
交易金额      689
Name: 6784, dtype: int64
内部标识号    6786
交易次数        1
交易金额     8524
Name: 6785, dtype: int64
内部标识号    6787
交易次数       15
交易金额      507
Name: 6786, dtype: int64
内部标识号    6788
交易次数        7
交易金额      124
Name: 6787, dtype: int64
内部标识号    6789
交易次数        0
交易金额     8032
Name: 6788, dtype: int64
内部标识号    6790
交易次数        0
交易金额     6423
Name: 6789, dtype: int64
内部标识号    6791
交易次数       14
交易金额      680
Name: 6790, dtype: int64
内部标识号    6792
交易次数        3
交易金额      439
Name: 6791, dtype: int64
内部标识号    6793
交易次数        8
交易金额      573
Name: 6792, dtype: int64
内部标识号    6794
交易次数       30
交易金额      944
Name: 6793, dtype: int64
内部标识号    6795
交易次数        0
交易金额     3455
Name: 6794, dtype: int64
内部标识号     6796
交易次数         5
交易金额     34587
Name: 6795, dtype: int64
内部标识号    6797
交易次数        3
交易金额      404
Name: 6796, dtype: int64
内部标识号    6798
交易次数        1
交易金额      885
Name: 6797, dtype: int64
内部标识号    6799
交易次数        8
交易金额      191
Name: 6798, dtype: int64
内部标识号    6800
交易次数       13
交易金额      451
Name: 6799, dtype: int64
内部标识号    6801
交易次数        1
交易金额     6241
Name: 6800, dtype: int64
内部标识号    6802
交易次数        0
交易金额     4888
Name: 6801, dtype: int64
内部标识号    6803
交易次数       10
交易金额      546
Name: 6802, dtype: int64
内部标识号    6804
交易次数       10
交易金额      340
Name: 6803, dtype: int64
内部标识号    6805
交易次数        3
交易金额      334
Name: 6804, dtype: int64
内部标识号    6806
交易次数       15
交易金额      337
Name: 6805, dtype: int64
内部标识号    6807
交易次数        4
交易金额      229
Name: 6806, dtype: int64
内部标识号    6808
交易次数        2
交易金额      471
Name: 6807, dtype: int64
内部标识号     6809
交易次数         4
交易金额     99250
Name: 6808, dtype: int64
内部标识号    6810
交易次数        1
交易金额     5507
Name: 6809, dtype: int64
内部标识号    6811
交易次数       14
交易金额      659
Name: 6810, dtype: int64
内部标识号    6812
交易次数       15
交易金额      640
Name: 6811, dtype: int64
内部标识号    6813
交易次数        2
交易金额      451
Name: 6812, dtype: int64
内部标识号    6814
交易次数        1
交易金额     8475
Name: 6813, dtype: int64
内部标识号    6815
交易次数       14
交易金额      805
Name: 6814, dtype: int64
内部标识号    6816
交易次数       15
交易金额      601
Name: 6815, dtype: int64
内部标识号    6817
交易次数        3
交易金额      437
Name: 6816, dtype: int64
内部标识号    6818
交易次数       29
交易金额     8357
Name: 6817, dtype: int64
内部标识号    6819
交易次数        9
交易金额      579
Name: 6818, dtype: int64
内部标识号    6820
交易次数       23
交易金额       56
Name: 6819, dtype: int64
内部标识号    6821
交易次数        2
交易金额      329
Name: 6820, dtype: int64
内部标识号    6822
交易次数       12
交易金额      519
Name: 6821, dtype: int64
内部标识号    6823
交易次数        7
交易金额      286
Name: 6822, dtype: int64
内部标识号    6824
交易次数       15
交易金额      697
Name: 6823, dtype: int64
内部标识号    6825
交易次数        1
交易金额     8614
Name: 6824, dtype: int64
内部标识号    6826
交易次数        5
交易金额      263
Name: 6825, dtype: int64
内部标识号    6827
交易次数        0
交易金额     7616
Name: 6826, dtype: int64
内部标识号    6828
交易次数        2
交易金额      895
Name: 6827, dtype: int64
内部标识号    6829
交易次数       10
交易金额      436
Name: 6828, dtype: int64
内部标识号    6830
交易次数        3
交易金额      129
Name: 6829, dtype: int64
内部标识号    6831
交易次数        8
交易金额      487
Name: 6830, dtype: int64
内部标识号    6832
交易次数        9
交易金额      934
Name: 6831, dtype: int64
内部标识号    6833
交易次数        1
交易金额      578
Name: 6832, dtype: int64
内部标识号    6834
交易次数       13
交易金额      841
Name: 6833, dtype: int64
内部标识号     6835
交易次数         3
交易金额     17987
Name: 6834, dtype: int64
内部标识号    6836
交易次数       13
交易金额      961
Name: 6835, dtype: int64
内部标识号    6837
交易次数        2
交易金额      815
Name: 6836, dtype: int64
内部标识号    6838
交易次数        3
交易金额      454
Name: 6837, dtype: int64
内部标识号    6839
交易次数        2
交易金额      315
Name: 6838, dtype: int64
内部标识号    6840
交易次数        0
交易金额     7590
Name: 6839, dtype: int64
内部标识号    6841
交易次数        2
交易金额      619
Name: 6840, dtype: int64
内部标识号    6842
交易次数        6
交易金额      127
Name: 6841, dtype: int64
内部标识号    6843
交易次数        2
交易金额      654
Name: 6842, dtype: int64
内部标识号    6844
交易次数        8
交易金额      863
Name: 6843, dtype: int64
内部标识号    6845
交易次数       11
交易金额      403
Name: 6844, dtype: int64
内部标识号    6846
交易次数       27
交易金额     6720
Name: 6845, dtype: int64
内部标识号    6847
交易次数        9
交易金额      496
Name: 6846, dtype: int64
内部标识号    6848
交易次数        3
交易金额      465
Name: 6847, dtype: int64
内部标识号    6849
交易次数        5
交易金额      289
Name: 6848, dtype: int64
内部标识号    6850
交易次数       16
交易金额     6401
Name: 6849, dtype: int64
内部标识号    6851
交易次数        0
交易金额     4979
Name: 6850, dtype: int64
内部标识号    6852
交易次数       16
交易金额     9528
Name: 6851, dtype: int64
内部标识号    6853
交易次数        0
交易金额     4496
Name: 6852, dtype: int64
内部标识号    6854
交易次数        7
交易金额      153
Name: 6853, dtype: int64
内部标识号    6855
交易次数        2
交易金额      386
Name: 6854, dtype: int64
内部标识号    6856
交易次数        9
交易金额      427
Name: 6855, dtype: int64
内部标识号    6857
交易次数        1
交易金额      904
Name: 6856, dtype: int64
内部标识号    6858
交易次数       26
交易金额      895
Name: 6857, dtype: int64
内部标识号    6859
交易次数        1
交易金额      544
Name: 6858, dtype: int64
内部标识号    6860
交易次数        0
交易金额     8500
Name: 6859, dtype: int64
内部标识号    6861
交易次数        1
交易金额     7148
Name: 6860, dtype: int64
内部标识号    6862
交易次数        9
交易金额      307
Name: 6861, dtype: int64
内部标识号    6863
交易次数       27
交易金额      931
Name: 6862, dtype: int64
内部标识号    6864
交易次数        3
交易金额      478
Name: 6863, dtype: int64
内部标识号    6865
交易次数       28
交易金额        1
Name: 6864, dtype: int64
内部标识号    6866
交易次数        7
交易金额      244
Name: 6865, dtype: int64
内部标识号     6867
交易次数        81
交易金额     55851
Name: 6866, dtype: int64
内部标识号    6868
交易次数       25
交易金额      625
Name: 6867, dtype: int64
内部标识号    6869
交易次数       22
交易金额     2872
Name: 6868, dtype: int64
内部标识号     6870
交易次数       228
交易金额     68226
Name: 6869, dtype: int64
内部标识号    6871
交易次数        2
交易金额      696
Name: 6870, dtype: int64
内部标识号    6872
交易次数        2
交易金额      563
Name: 6871, dtype: int64
内部标识号    6873
交易次数        3
交易金额      269
Name: 6872, dtype: int64
内部标识号    6874
交易次数        1
交易金额      614
Name: 6873, dtype: int64
内部标识号    6875
交易次数        0
交易金额     9883
Name: 6874, dtype: int64
内部标识号    6876
交易次数        6
交易金额      260
Name: 6875, dtype: int64
内部标识号    6877
交易次数        3
交易金额      411
Name: 6876, dtype: int64
内部标识号    6878
交易次数        7
交易金额      203
Name: 6877, dtype: int64
内部标识号    6879
交易次数        8
交易金额      300
Name: 6878, dtype: int64
内部标识号    6880
交易次数        8
交易金额      874
Name: 6879, dtype: int64
内部标识号    6881
交易次数        6
交易金额      247
Name: 6880, dtype: int64
内部标识号    6882
交易次数       30
交易金额      533
Name: 6881, dtype: int64
内部标识号    6883
交易次数        9
交易金额      695
Name: 6882, dtype: int64
内部标识号    6884
交易次数        2
交易金额      312
Name: 6883, dtype: int64
内部标识号    6885
交易次数       11
交易金额      765
Name: 6884, dtype: int64
内部标识号    6886
交易次数        2
交易金额      492
Name: 6885, dtype: int64
内部标识号    6887
交易次数       10
交易金额      969
Name: 6886, dtype: int64
内部标识号    6888
交易次数        1
交易金额      705
Name: 6887, dtype: int64
内部标识号    6889
交易次数        1
交易金额      632
Name: 6888, dtype: int64
内部标识号    6890
交易次数       14
交易金额      475
Name: 6889, dtype: int64
内部标识号    6891
交易次数        5
交易金额      232
Name: 6890, dtype: int64
内部标识号    6892
交易次数       11
交易金额      928
Name: 6891, dtype: int64
内部标识号    6893
交易次数        0
交易金额     5288
Name: 6892, dtype: int64
内部标识号    6894
交易次数        1
交易金额      756
Name: 6893, dtype: int64
内部标识号    6895
交易次数        8
交易金额      183
Name: 6894, dtype: int64
内部标识号    6896
交易次数       20
交易金额       38
Name: 6895, dtype: int64
内部标识号    6897
交易次数        1
交易金额      917
Name: 6896, dtype: int64
内部标识号    6898
交易次数        2
交易金额      574
Name: 6897, dtype: int64
内部标识号     6899
交易次数       121
交易金额     46154
Name: 6898, dtype: int64
内部标识号    6900
交易次数       30
交易金额     4584
Name: 6899, dtype: int64
内部标识号    6901
交易次数        8
交易金额      446
Name: 6900, dtype: int64
内部标识号     6902
交易次数         7
交易金额     92334
Name: 6901, dtype: int64
内部标识号     6903
交易次数        75
交易金额     99076
Name: 6902, dtype: int64
内部标识号    6904
交易次数       27
交易金额     1924
Name: 6903, dtype: int64
内部标识号    6905
交易次数        6
交易金额      116
Name: 6904, dtype: int64
内部标识号    6906
交易次数        3
交易金额      168
Name: 6905, dtype: int64
内部标识号    6907
交易次数        3
交易金额      323
Name: 6906, dtype: int64
内部标识号    6908
交易次数       27
交易金额     3273
Name: 6907, dtype: int64
内部标识号    6909
交易次数        8
交易金额      571
Name: 6908, dtype: int64
内部标识号    6910
交易次数        2
交易金额      565
Name: 6909, dtype: int64
内部标识号    6911
交易次数       11
交易金额      996
Name: 6910, dtype: int64
内部标识号    6912
交易次数       24
交易金额     1691
Name: 6911, dtype: int64
内部标识号    6913
交易次数        2
交易金额      885
Name: 6912, dtype: int64
内部标识号    6914
交易次数        3
交易金额      311
Name: 6913, dtype: int64
内部标识号    6915
交易次数        0
交易金额     6201
Name: 6914, dtype: int64
内部标识号    6916
交易次数       20
交易金额      902
Name: 6915, dtype: int64
内部标识号    6917
交易次数       22
交易金额     1408
Name: 6916, dtype: int64
内部标识号     6918
交易次数         6
交易金额     94979
Name: 6917, dtype: int64
内部标识号     6919
交易次数       155
交易金额     43922
Name: 6918, dtype: int64
内部标识号    6920
交易次数       10
交易金额      483
Name: 6919, dtype: int64
内部标识号    6921
交易次数        1
交易金额      731
Name: 6920, dtype: int64
内部标识号    6922
交易次数        8
交易金额      581
Name: 6921, dtype: int64
内部标识号    6923
交易次数        8
交易金额      313
Name: 6922, dtype: int64
内部标识号    6924
交易次数        8
交易金额      626
Name: 6923, dtype: int64
内部标识号    6925
交易次数        2
交易金额      402
Name: 6924, dtype: int64
内部标识号    6926
交易次数       15
交易金额      897
Name: 6925, dtype: int64
内部标识号    6927
交易次数        3
交易金额      280
Name: 6926, dtype: int64
内部标识号    6928
交易次数        2
交易金额      631
Name: 6927, dtype: int64
内部标识号    6929
交易次数        6
交易金额      127
Name: 6928, dtype: int64
内部标识号    6930
交易次数        9
交易金额      501
Name: 6929, dtype: int64
内部标识号     6931
交易次数         4
交易金额     95098
Name: 6930, dtype: int64
内部标识号    6932
交易次数        8
交易金额      459
Name: 6931, dtype: int64
内部标识号    6933
交易次数       11
交易金额      754
Name: 6932, dtype: int64
内部标识号     6934
交易次数       195
交易金额     68867
Name: 6933, dtype: int64
内部标识号    6935
交易次数        6
交易金额      123
Name: 6934, dtype: int64
内部标识号    6936
交易次数        3
交易金额      386
Name: 6935, dtype: int64
内部标识号    6937
交易次数        3
交易金额      412
Name: 6936, dtype: int64
内部标识号     6938
交易次数       147
交易金额     32489
Name: 6937, dtype: int64
内部标识号    6939
交易次数       13
交易金额      539
Name: 6938, dtype: int64
内部标识号    6940
交易次数        5
交易金额      278
Name: 6939, dtype: int64
内部标识号    6941
交易次数        4
交易金额      290
Name: 6940, dtype: int64
内部标识号    6942
交易次数        3
交易金额      403
Name: 6941, dtype: int64
内部标识号    6943
交易次数        1
交易金额     8075
Name: 6942, dtype: int64
内部标识号     6944
交易次数       118
交易金额     79066
Name: 6943, dtype: int64
内部标识号    6945
交易次数        2
交易金额      401
Name: 6944, dtype: int64
内部标识号    6946
交易次数        1
交易金额      695
Name: 6945, dtype: int64
内部标识号    6947
交易次数        0
交易金额     4436
Name: 6946, dtype: int64
内部标识号    6948
交易次数        4
交易金额      205
Name: 6947, dtype: int64
内部标识号    6949
交易次数        0
交易金额     6621
Name: 6948, dtype: int64
内部标识号    6950
交易次数       10
交易金额      409
Name: 6949, dtype: int64
内部标识号    6951
交易次数       13
交易金额      466
Name: 6950, dtype: int64
内部标识号     6952
交易次数         7
交易金额     66822
Name: 6951, dtype: int64
内部标识号    6953
交易次数        6
交易金额      135
Name: 6952, dtype: int64
内部标识号    6954
交易次数        3
交易金额      358
Name: 6953, dtype: int64
内部标识号    6955
交易次数        1
交易金额      759
Name: 6954, dtype: int64
内部标识号     6956
交易次数         5
交易金额     31959
Name: 6955, dtype: int64
内部标识号    6957
交易次数       29
交易金额      871
Name: 6956, dtype: int64
内部标识号    6958
交易次数        6
交易金额      110
Name: 6957, dtype: int64
内部标识号    6959
交易次数       14
交易金额      929
Name: 6958, dtype: int64
内部标识号    6960
交易次数        3
交易金额      431
Name: 6959, dtype: int64
内部标识号    6961
交易次数        4
交易金额      202
Name: 6960, dtype: int64
内部标识号    6962
交易次数       21
交易金额       62
Name: 6961, dtype: int64
内部标识号    6963
交易次数        0
交易金额     5833
Name: 6962, dtype: int64
内部标识号    6964
交易次数       10
交易金额      434
Name: 6963, dtype: int64
内部标识号     6965
交易次数         5
交易金额     30311
Name: 6964, dtype: int64
内部标识号    6966
交易次数        8
交易金额      489
Name: 6965, dtype: int64
内部标识号    6967
交易次数        3
交易金额      387
Name: 6966, dtype: int64
内部标识号    6968
交易次数        3
交易金额      439
Name: 6967, dtype: int64
内部标识号    6969
交易次数        2
交易金额      632
Name: 6968, dtype: int64
内部标识号    6970
交易次数        1
交易金额      626
Name: 6969, dtype: int64
内部标识号    6971
交易次数       11
交易金额      945
Name: 6970, dtype: int64
内部标识号    6972
交易次数        8
交易金额      802
Name: 6971, dtype: int64
内部标识号    6973
交易次数       13
交易金额      349
Name: 6972, dtype: int64
内部标识号    6974
交易次数        2
交易金额      988
Name: 6973, dtype: int64
内部标识号    6975
交易次数       13
交易金额      481
Name: 6974, dtype: int64
内部标识号    6976
交易次数       15
交易金额      563
Name: 6975, dtype: int64
内部标识号    6977
交易次数        7
交易金额      252
Name: 6976, dtype: int64
内部标识号    6978
交易次数       14
交易金额      343
Name: 6977, dtype: int64
内部标识号    6979
交易次数        1
交易金额      755
Name: 6978, dtype: int64
内部标识号    6980
交易次数       20
交易金额       89
Name: 6979, dtype: int64
内部标识号    6981
交易次数        0
交易金额     7259
Name: 6980, dtype: int64
内部标识号    6982
交易次数        1
交易金额      706
Name: 6981, dtype: int64
内部标识号    6983
交易次数       11
交易金额      911
Name: 6982, dtype: int64
内部标识号    6984
交易次数        0
交易金额     2989
Name: 6983, dtype: int64
内部标识号    6985
交易次数       12
交易金额      470
Name: 6984, dtype: int64
内部标识号     6986
交易次数         3
交易金额     74275
Name: 6985, dtype: int64
内部标识号    6987
交易次数       15
交易金额      462
Name: 6986, dtype: int64
内部标识号    6988
交易次数       14
交易金额      947
Name: 6987, dtype: int64
内部标识号    6989
交易次数       15
交易金额      441
Name: 6988, dtype: int64
内部标识号    6990
交易次数        8
交易金额      327
Name: 6989, dtype: int64
内部标识号    6991
交易次数        8
交易金额      867
Name: 6990, dtype: int64
内部标识号    6992
交易次数       15
交易金额      456
Name: 6991, dtype: int64
内部标识号    6993
交易次数       14
交易金额      653
Name: 6992, dtype: int64
内部标识号    6994
交易次数       11
交易金额      456
Name: 6993, dtype: int64
内部标识号    6995
交易次数        3
交易金额      368
Name: 6994, dtype: int64
内部标识号    6996
交易次数       19
交易金额     7015
Name: 6995, dtype: int64
内部标识号     6997
交易次数       108
交易金额     55709
Name: 6996, dtype: int64
内部标识号     6998
交易次数         5
交易金额     23946
Name: 6997, dtype: int64
内部标识号    6999
交易次数        1
交易金额      586
Name: 6998, dtype: int64
内部标识号    7000
交易次数        8
交易金额      433
Name: 6999, dtype: int64
内部标识号    7001
交易次数        5
交易金额      117
Name: 7000, dtype: int64
内部标识号    7002
交易次数       13
交易金额      460
Name: 7001, dtype: int64
内部标识号    7003
交易次数        0
交易金额     1390
Name: 7002, dtype: int64
内部标识号    7004
交易次数       23
交易金额     7332
Name: 7003, dtype: int64
内部标识号    7005
交易次数        2
交易金额      411
Name: 7004, dtype: int64
内部标识号    7006
交易次数        2
交易金额      867
Name: 7005, dtype: int64
内部标识号    7007
交易次数       14
交易金额      704
Name: 7006, dtype: int64
内部标识号    7008
交易次数       10
交易金额      405
Name: 7007, dtype: int64
内部标识号    7009
交易次数       11
交易金额      701
Name: 7008, dtype: int64
内部标识号    7010
交易次数        4
交易金额      244
Name: 7009, dtype: int64
内部标识号    7011
交易次数        8
交易金额      273
Name: 7010, dtype: int64
内部标识号    7012
交易次数        5
交易金额      146
Name: 7011, dtype: int64
内部标识号    7013
交易次数       29
交易金额     8993
Name: 7012, dtype: int64
内部标识号    7014
交易次数       15
交易金额     6223
Name: 7013, dtype: int64
内部标识号    7015
交易次数        2
交易金额      306
Name: 7014, dtype: int64
内部标识号    7016
交易次数        3
交易金额      212
Name: 7015, dtype: int64
内部标识号    7017
交易次数       23
交易金额     5573
Name: 7016, dtype: int64
内部标识号    7018
交易次数       26
交易金额     1803
Name: 7017, dtype: int64
内部标识号     7019
交易次数       266
交易金额     33704
Name: 7018, dtype: int64
内部标识号    7020
交易次数       10
交易金额      904
Name: 7019, dtype: int64
内部标识号    7021
交易次数       11
交易金额      478
Name: 7020, dtype: int64
内部标识号    7022
交易次数        3
交易金额      127
Name: 7021, dtype: int64
内部标识号    7023
交易次数       25
交易金额      722
Name: 7022, dtype: int64
内部标识号    7024
交易次数        8
交易金额      467
Name: 7023, dtype: int64
内部标识号    7025
交易次数        6
交易金额      131
Name: 7024, dtype: int64
内部标识号    7026
交易次数       11
交易金额      688
Name: 7025, dtype: int64
内部标识号     7027
交易次数         3
交易金额     17230
Name: 7026, dtype: int64
内部标识号    7028
交易次数       17
交易金额      664
Name: 7027, dtype: int64
内部标识号    7029
交易次数       14
交易金额      987
Name: 7028, dtype: int64
内部标识号    7030
交易次数        7
交易金额      274
Name: 7029, dtype: int64
内部标识号    7031
交易次数       10
交易金额      344
Name: 7030, dtype: int64
内部标识号     7032
交易次数        49
交易金额     96280
Name: 7031, dtype: int64
内部标识号    7033
交易次数        3
交易金额      335
Name: 7032, dtype: int64
内部标识号    7034
交易次数        8
交易金额      343
Name: 7033, dtype: int64
内部标识号    7035
交易次数       11
交易金额      767
Name: 7034, dtype: int64
内部标识号    7036
交易次数        8
交易金额      441
Name: 7035, dtype: int64
内部标识号    7037
交易次数        4
交易金额      215
Name: 7036, dtype: int64
内部标识号    7038
交易次数       13
交易金额      461
Name: 7037, dtype: int64
内部标识号    7039
交易次数       15
交易金额      911
Name: 7038, dtype: int64
内部标识号    7040
交易次数        3
交易金额      391
Name: 7039, dtype: int64
内部标识号    7041
交易次数       21
交易金额      781
Name: 7040, dtype: int64
内部标识号    7042
交易次数        2
交易金额      338
Name: 7041, dtype: int64
内部标识号    7043
交易次数        2
交易金额      305
Name: 7042, dtype: int64
内部标识号    7044
交易次数        1
交易金额      721
Name: 7043, dtype: int64
内部标识号    7045
交易次数       14
交易金额      432
Name: 7044, dtype: int64
内部标识号    7046
交易次数       19
交易金额      506
Name: 7045, dtype: int64
内部标识号    7047
交易次数        9
交易金额      573
Name: 7046, dtype: int64
内部标识号     7048
交易次数       227
交易金额     47041
Name: 7047, dtype: int64
内部标识号    7049
交易次数       12
交易金额      902
Name: 7048, dtype: int64
内部标识号    7050
交易次数        8
交易金额      576
Name: 7049, dtype: int64
内部标识号    7051
交易次数        0
交易金额     1309
Name: 7050, dtype: int64
内部标识号    7052
交易次数        7
交易金额      207
Name: 7051, dtype: int64
内部标识号    7053
交易次数       12
交易金额      625
Name: 7052, dtype: int64
内部标识号    7054
交易次数        0
交易金额     2495
Name: 7053, dtype: int64
内部标识号    7055
交易次数        7
交易金额      215
Name: 7054, dtype: int64
内部标识号    7056
交易次数        3
交易金额      150
Name: 7055, dtype: int64
内部标识号    7057
交易次数       15
交易金额     3761
Name: 7056, dtype: int64
内部标识号    7058
交易次数       28
交易金额      696
Name: 7057, dtype: int64
内部标识号    7059
交易次数        3
交易金额      249
Name: 7058, dtype: int64
内部标识号    7060
交易次数       15
交易金额      778
Name: 7059, dtype: int64
内部标识号    7061
交易次数        0
交易金额     3921
Name: 7060, dtype: int64
内部标识号    7062
交易次数       16
交易金额     8835
Name: 7061, dtype: int64
内部标识号    7063
交易次数        8
交易金额      890
Name: 7062, dtype: int64
内部标识号    7064
交易次数        1
交易金额     6061
Name: 7063, dtype: int64
内部标识号    7065

Name: 7199, dtype: int64
内部标识号    7201
交易次数       13
交易金额      397
Name: 7200, dtype: int64
内部标识号    7202
交易次数       13
交易金额      321
Name: 7201, dtype: int64
内部标识号    7203
交易次数        0
交易金额     9875
Name: 7202, dtype: int64
内部标识号    7204
交易次数        3
交易金额      450
Name: 7203, dtype: int64
内部标识号    7205
交易次数       11
交易金额      440
Name: 7204, dtype: int64
内部标识号    7206
交易次数        0
交易金额     6898
Name: 7205, dtype: int64
内部标识号     7207
交易次数       203
交易金额     56172
Name: 7206, dtype: int64
内部标识号    7208
交易次数        0
交易金额     5772
Name: 7207, dtype: int64
内部标识号    7209
交易次数        1
交易金额      609
Name: 7208, dtype: int64
内部标识号    7210
交易次数        6
交易金额      247
Name: 7209, dtype: int64
内部标识号    7211
交易次数        8
交易金额      139
Name: 7210, dtype: int64
内部标识号    7212
交易次数        1
交易金额     5594
Name: 7211, dtype: int64
内部标识号    7213
交易次数       13
交易金额      836
Name: 7212, dtype: int64
内部标识号    7214
交易次数        3
交易金额      166
Name: 7213, dtype: int64
内部标识号    7215
交易次数        3
交易金额      387
Name: 7214, dtype: int64
内部标识号    7216
交易次数        1
交易金额      891
Name: 7215, dtype: int64
内部标识号    7217
交易次数        2
交易金额      284
Name: 7216, dtype: int64
内部标识号    7218
交易次数        1
交易金额     6971
Name: 7217, dtype: int64
内部标识号     7219
交易次数       181
交易金额     38358
Name: 7218, dtype: int64
内部标识号    7220
交易次数        2
交易金额      197
Name: 7219, dtype: int64
内部标识号    7221
交易次数        3
交易金额      349
Name: 7220, dtype: int64
内部标识号    7222
交易次数        0
交易金额     9254
Name: 7221, dtype: int64
内部标识号    7223
交易次数       15
交易金额      726
Name: 7222, dtype: int64
内部标识号    7224
交易次数        0
交易金额     6647
Name: 7223, dtype: int64
内部标识号    7225
交易次数        0
交易金额     4509
Name: 7224, dtype: int64
内部标识号    7226
交易次数        3
交易金额      480
Name: 7225, dtype: int64
内部标识号    7227
交易次数        1
交易金额     3769
Name: 7226, dtype: int64
内部标识号    7228
交易次数       15
交易金额      972
Name: 7227, dtype: int64
内部标识号    7229
交易次数        1
交易金额      963
Name: 7228, dtype: int64
内部标识号    7230
交易次数        3
交易金额      394
Name: 7229, dtype: int64
内部标识号    7231
交易次数       14
交易金额      628
Name: 7230, dtype: int64
内部标识号    7232
交易次数        1
交易金额      759
Name: 7231, dtype: int64
内部标识号    7233
交易次数       10
交易金额      344
Name: 7232, dtype: int64
内部标识号    7234
交易次数        7
交易金额      268
Name: 7233, dtype: int64
内部标识号    7235
交易次数       19
交易金额      773
Name: 7234, dtype: int64
内部标识号    7236
交易次数       12
交易金额      953
Name: 7235, dtype: int64
内部标识号     7237
交易次数       136
交易金额     73790
Name: 7236, dtype: int64
内部标识号    7238
交易次数        0
交易金额     1056
Name: 7237, dtype: int64
内部标识号    7239
交易次数        1
交易金额     5476
Name: 7238, dtype: int64
内部标识号    7240
交易次数        2
交易金额      216
Name: 7239, dtype: int64
内部标识号    7241
交易次数        1
交易金额      810
Name: 7240, dtype: int64
内部标识号    7242
交易次数       14
交易金额      858
Name: 7241, dtype: int64
内部标识号    7243
交易次数       19
交易金额       23
Name: 7242, dtype: int64
内部标识号    7244
交易次数       11
交易金额      466
Name: 7243, dtype: int64
内部标识号    7245
交易次数        4
交易金额      102
Name: 7244, dtype: int64
内部标识号     7246
交易次数       120
交易金额     52786
Name: 7245, dtype: int64
内部标识号    7247
交易次数       15
交易金额      510
Name: 7246, dtype: int64
内部标识号    7248
交易次数       29
交易金额      717
Name: 7247, dtype: int64
内部标识号    7249
交易次数       13
交易金额      327
Name: 7248, dtype: int64
内部标识号    7250
交易次数       13
交易金额      983
Name: 7249, dtype: int64
内部标识号    7251
交易次数        3
交易金额      315
Name: 7250, dtype: int64
内部标识号    7252
交易次数        1
交易金额     3898
Name: 7251, dtype: int64
内部标识号    7253
交易次数        3
交易金额      337
Name: 7252, dtype: int64
内部标识号    7254
交易次数        3
交易金额      348
Name: 7253, dtype: int64
内部标识号    7255
交易次数        3
交易金额      467
Name: 7254, dtype: int64
内部标识号    7256
交易次数       15
交易金额      535
Name: 7255, dtype: int64
内部标识号    7257
交易次数       30
交易金额      747
Name: 7256, dtype: int64
内部标识号     7258
交易次数         8
交易金额     40423
Name: 7257, dtype: int64
内部标识号    7259
交易次数        7
交易金额      262
Name: 7258, dtype: int64
内部标识号    7260
交易次数        2
交易金额      487
Name: 7259, dtype: int64
内部标识号    7261
交易次数        2
交易金额      455
Name: 7260, dtype: int64
内部标识号    7262
交易次数        4
交易金额      122
Name: 7261, dtype: int64
内部标识号    7263
交易次数        5
交易金额      185
Name: 7262, dtype: int64
内部标识号    7264
交易次数        6
交易金额      180
Name: 7263, dtype: int64
内部标识号     7265
交易次数         8
交易金额     24097
Name: 7264, dtype: int64
内部标识号    7266
交易次数        0
交易金额     6676
Name: 7265, dtype: int64
内部标识号    7267
交易次数       13
交易金额      364
Name: 7266, dtype: int64
内部标识号    7268
交易次数       14
交易金额      304
Name: 7267, dtype: int64
内部标识号     7269
交易次数         4
交易金额     84965
Name: 7268, dtype: int64
内部标识号    7270
交易次数        6
交易金额      297
Name: 7269, dtype: int64
内部标识号    7271
交易次数       29
交易金额      650
Name: 7270, dtype: int64
内部标识号    7272
交易次数        1
交易金额      626
Name: 7271, dtype: int64
内部标识号    7273
交易次数        8
交易金额      599
Name: 7272, dtype: int64
内部标识号     7274
交易次数         5
交易金额     67817
Name: 7273, dtype: int64
内部标识号    7275
交易次数       26
交易金额     9440
Name: 7274, dtype: int64
内部标识号    7276
交易次数        7
交易金额      195
Name: 7275, dtype: int64
内部标识号    7277
交易次数        2
交易金额      424
Name: 7276, dtype: int64
内部标识号    7278
交易次数        2
交易金额      267
Name: 7277, dtype: int64
内部标识号    7279
交易次数       15
交易金额      344
Name: 7278, dtype: int64
内部标识号    7280
交易次数        2
交易金额      924
Name: 7279, dtype: int64
内部标识号    7281
交易次数       13
交易金额      921
Name: 7280, dtype: int64
内部标识号     7282
交易次数       250
交易金额     17115
Name: 7281, dtype: int64
内部标识号    7283
交易次数       10
交易金额      970
Name: 7282, dtype: int64
内部标识号    7284
交易次数        7
交易金额      191
Name: 7283, dtype: int64
内部标识号    7285
交易次数       14
交易金额      948
Name: 7284, dtype: int64
内部标识号    7286
交易次数        2
交易金额      412
Name: 7285, dtype: int64
内部标识号    7287
交易次数        0
交易金额     6538
Name: 7286, dtype: int64
内部标识号    7288
交易次数        2
交易金额      337
Name: 7287, dtype: int64
内部标识号    7289
交易次数        3
交易金额      209
Name: 7288, dtype: int64
内部标识号    7290
交易次数        0
交易金额     4641
Name: 7289, dtype: int64
内部标识号    7291
交易次数       11
交易金额      860
Name: 7290, dtype: int64
内部标识号    7292
交易次数        3
交易金额      170
Name: 7291, dtype: int64
内部标识号    7293
交易次数        3
交易金额      296
Name: 7292, dtype: int64
内部标识号    7294
交易次数        3
交易金额      314
Name: 7293, dtype: int64
内部标识号    7295
交易次数        8
交易金额      704
Name: 7294, dtype: int64
内部标识号    7296
交易次数       13
交易金额      375
Name: 7295, dtype: int64
内部标识号    7297
交易次数        2
交易金额      459
Name: 7296, dtype: int64
内部标识号    7298
交易次数       28
交易金额      636
Name: 7297, dtype: int64
内部标识号    7299
交易次数       22
交易金额      583
Name: 7298, dtype: int64
内部标识号    7300
交易次数        4
交易金额      284
Name: 7299, dtype: int64
内部标识号    7301
交易次数        2
交易金额      879
Name: 7300, dtype: int64
内部标识号    7302
交易次数        0
交易金额     3475
Name: 7301, dtype: int64
内部标识号    7303
交易次数        2
交易金额      204
Name: 7302, dtype: int64
内部标识号    7304
交易次数       14
交易金额      932
Name: 7303, dtype: int64
内部标识号    7305
交易次数        2
交易金额      451
Name: 7304, dtype: int64
内部标识号    7306
交易次数        4
交易金额      278
Name: 7305, dtype: int64
内部标识号    7307
交易次数        0
交易金额     1376
Name: 7306, dtype: int64
内部标识号    7308
交易次数       15
交易金额      918
Name: 7307, dtype: int64
内部标识号    7309
交易次数        2
交易金额      639
Name: 7308, dtype: int64
内部标识号    7310
交易次数       11
交易金额      983
Name: 7309, dtype: int64
内部标识号    7311
交易次数       29
交易金额      556
Name: 7310, dtype: int64
内部标识号     7312
交易次数        89
交易金额     67615
Name: 7311, dtype: int64
内部标识号    7313
交易次数        5
交易金额      256
Name: 7312, dtype: int64
内部标识号    7314
交易次数        2
交易金额      379
Name: 7313, dtype: int64
内部标识号    7315
交易次数       20
交易金额     5756
Name: 7314, dtype: int64
内部标识号     7316
交易次数         8
交易金额     61144
Name: 7315, dtype: int64
内部标识号    7317
交易次数       13
交易金额      422
Name: 7316, dtype: int64
内部标识号    7318
交易次数       13
交易金额      413
Name: 7317, dtype: int64
内部标识号    7319
交易次数       26
交易金额     1446
Name: 7318, dtype: int64
内部标识号    7320
交易次数        1
交易金额      835
Name: 7319, dtype: int64
内部标识号    7321
交易次数       14
交易金额      402
Name: 7320, dtype: int64
内部标识号    7322
交易次数        3
交易金额      338
Name: 7321, dtype: int64
内部标识号    7323
交易次数       14
交易金额      496
Name: 7322, dtype: int64
内部标识号    7324
交易次数       14
交易金额      426
Name: 7323, dtype: int64
内部标识号    7325
交易次数        8
交易金额      650
Name: 7324, dtype: int64
内部标识号    7326
交易次数        7
交易金额      214
Name: 7325, dtype: int64
内部标识号    7327
交易次数        1
交易金额      605
Name: 7326, dtype: int64
内部标识号    7328
交易次数       18
交易金额     5370
Name: 7327, dtype: int64
内部标识号    7329
交易次数        3
交易金额      407
Name: 7328, dtype: int64
内部标识号    7330
交易次数        3
交易金额      349
Name: 7329, dtype: int64
内部标识号    7331
交易次数       23
交易金额     1061
Name: 7330, dtype: int64
内部标识号    7332
交易次数        1
交易金额      949
Name: 7331, dtype: int64
内部标识号    7333
交易次数       11
交易金额      456
Name: 7332, dtype: int64
内部标识号    7334
交易次数       14
交易金额      678
Name: 7333, dtype: int64
内部标识号    7335
交易次数       11
交易金额      683
Name: 7334, dtype: int64
内部标识号    7336
交易次数        2
交易金额      325
Name: 7335, dtype: int64
内部标识号    7337
交易次数        4
交易金额      286
Name: 7336, dtype: int64
内部标识号    7338
交易次数       29
交易金额     1364
Name: 7337, dtype: int64
内部标识号    7339
交易次数        2
交易金额      695
Name: 7338, dtype: int64
内部标识号    7340
交易次数        0
交易金额     4734
Name: 7339, dtype: int64
内部标识号    7341
交易次数        9
交易金额      905
Name: 7340, dtype: int64
内部标识号    7342
交易次数        7
交易金额      250
Name: 7341, dtype: int64
内部标识号    7343
交易次数        4
交易金额      177
Name: 7342, dtype: int64
内部标识号    7344
交易次数       10
交易金额      838
Name: 7343, dtype: int64
内部标识号    7345
交易次数        2
交易金额      969
Name: 7344, dtype: int64
内部标识号    7346
交易次数        5
交易金额      137
Name: 7345, dtype: int64
内部标识号    7347
交易次数       13
交易金额      451
Name: 7346, dtype: int64
内部标识号    7348
交易次数        3
交易金额      178
Name: 7347, dtype: int64
内部标识号    7349
交易次数        0
交易金额     4225
Name: 7348, dtype: int64
内部标识号     7350
交易次数         7
交易金额     44916
Name: 7349, dtype: int64
内部标识号     7351
交易次数         3
交易金额     44897
Name: 7350, dtype: int64
内部标识号    7352
交易次数        2
交易金额      491
Name: 7351, dtype: int64
内部标识号    7353
交易次数       13
交易金额      345
Name: 7352, dtype: int64
内部标识号    7354
交易次数        0
交易金额     3037
Name: 7353, dtype: int64
内部标识号    7355
交易次数       22
交易金额      545
Name: 7354, dtype: int64
内部标识号     7356
交易次数       199
交易金额     72742
Name: 7355, dtype: int64
内部标识号    7357
交易次数        2
交易金额      404
Name: 7356, dtype: int64
内部标识号    7358
交易次数       20
交易金额      864
Name: 7357, dtype: int64
内部标识号    7359
交易次数       19
交易金额       75
Name: 7358, dtype: int64
内部标识号     7360
交易次数         6
交易金额     38824
Name: 7359, dtype: int64
内部标识号    7361
交易次数        1
交易金额      628
Name: 7360, dtype: int64
内部标识号    7362
交易次数        1
交易金额      891
Name: 7361, dtype: int64
内部标识号    7363
交易次数       14
交易金额      578
Name: 7362, dtype: int64
内部标识号    7364
交易次数       18
交易金额     3865
Name: 7363, dtype: int64
内部标识号    7365
交易次数        3
交易金额      284
Name: 7364, dtype: int64
内部标识号    7366
交易次数        2
交易金额      620
Name: 7365, dtype: int64
内部标识号    7367
交易次数        3
交易金额      342
Name: 7366, dtype: int64
内部标识号    7368
交易次数        0
交易金额     8901
Name: 7367, dtype: int64
内部标识号     7369
交易次数        60
交易金额     96254
Name: 7368, dtype: int64
内部标识号    7370
交易次数        2
交易金额      724
Name: 7369, dtype: int64
内部标识号    7371
交易次数       25
交易金额      881
Name: 7370, dtype: int64
内部标识号    7372
交易次数       14
交易金额      911
Name: 7371, dtype: int64
内部标识号    7373
交易次数       13
交易金额      863
Name: 7372, dtype: int64
内部标识号    7374
交易次数        7
交易金额      184
Name: 7373, dtype: int64
内部标识号    7375
交易次数        2
交易金额      378
Name: 7374, dtype: int64
内部标识号     7376
交易次数       239
交易金额     24605
Name: 7375, dtype: int64
内部标识号    7377
交易次数        8
交易金额      505
Name: 7376, dtype: int64
内部标识号    7378
交易次数       24
交易金额     3815
Name: 7377, dtype: int64
内部标识号    7379
交易次数        8
交易金额      153
Name: 7378, dtype: int64
内部标识号    7380
交易次数       29
交易金额      898
Name: 7379, dtype: int64
内部标识号    7381
交易次数        9
交易金额      374
Name: 7380, dtype: int64
内部标识号    7382
交易次数        8
交易金额      743
Name: 7381, dtype: int64
内部标识号    7383
交易次数       14
交易金额      538
Name: 7382, dtype: int64
内部标识号    7384
交易次数        1
交易金额     2543
Name: 7383, dtype: int64
内部标识号    7385
交易次数        0
交易金额     2140
Name: 7384, dtype: int64
内部标识号    7386
交易次数        3
交易金额      107
Name: 7385, dtype: int64
内部标识号    7387
交易次数        5
交易金额      181
Name: 7386, dtype: int64
内部标识号    7388
交易次数        2
交易金额      340
Name: 7387, dtype: int64
内部标识号    7389
交易次数        1
交易金额      973
Name: 7388, dtype: int64
内部标识号    7390
交易次数        4
交易金额      155
Name: 7389, dtype: int64
内部标识号    7391
交易次数        0
交易金额     1327
Name: 7390, dtype: int64
内部标识号    7392
交易次数        2
交易金额      345
Name: 7391, dtype: int64
内部标识号    7393
交易次数        0
交易金额     5060
Name: 7392, dtype: int64
内部标识号     7394
交易次数         8
交易金额     19247
Name: 7393, dtype: int64
内部标识号    7395
交易次数        8
交易金额      489
Name: 7394, dtype: int64
内部标识号    7396
交易次数        1
交易金额      727
Name: 7395, dtype: int64
内部标识号    7397
交易次数        2
交易金额      440
Name: 7396, dtype: int64
内部标识号    7398
交易次数       20
交易金额      907
Name: 7397, dtype: int64
内部标识号    7399
交易次数        1
交易金额     7136
Name: 7398, dtype: int64
内部标识号    7400
交易次数        3
交易金额      477
Name: 7399, dtype: int64
内部标识号    7401
交易次数        3
交易金额      368
Name: 7400, dtype: int64
内部标识号    7402
交易次数       13
交易金额      346
Name: 7401, dtype: int64
内部标识号    7403
交易次数       19
交易金额       69
Name: 7402, dtype: int64
内部标识号    7404
交易次数        1
交易金额      657
Name: 7403, dtype: int64
内部标识号    7405
交易次数        0
交易金额     2577
Name: 7404, dtype: int64
内部标识号    7406
交易次数       15
交易金额      419
Name: 7405, dtype: int64
内部标识号    7407
交易次数        3
交易金额      117
Name: 7406, dtype: int64
内部标识号    7408
交易次数        3
交易金额      225
Name: 7407, dtype: int64
内部标识号    7409
交易次数        1
交易金额     8054
Name: 7408, dtype: int64
内部标识号    7410
交易次数       13
交易金额      778
Name: 7409, dtype: int64
内部标识号    7411
交易次数        0
交易金额     2481
Name: 7410, dtype: int64
内部标识号    7412
交易次数       15
交易金额      878
Name: 7411, dtype: int64
内部标识号     7413
交易次数         5
交易金额     17292
Name: 7412, dtype: int64
内部标识号    7414
交易次数        4
交易金额      150
Name: 7413, dtype: int64
内部标识号    7415
交易次数        2
交易金额      790
Name: 7414, dtype: int64
内部标识号    7416
交易次数        0
交易金额     9259
Name: 7415, dtype: int64
内部标识号    7417
交易次数       25
交易金额     2836
Name: 7416, dtype: int64
内部标识号    7418
交易次数       16
交易金额      698
Name: 7417, dtype: int64
内部标识号     7419
交易次数         4
交易金额     52004
Name: 7418, dtype: int64
内部标识号    7420
交易次数       11
交易金额      978
Name: 7419, dtype: int64
内部标识号    7421
交易次数       10
交易金额      333
Name: 7420, dtype: int64
内部标识号    7422
交易次数        3
交易金额      331
Name: 7421, dtype: int64
内部标识号    7423
交易次数        2
交易金额      817
Name: 7422, dtype: int64
内部标识号    7424
交易次数        2
交易金额      451
Name: 7423, dtype: int64
内部标识号    7425
交易次数        2
交易金额      460
Name: 7424, dtype: int64
内部标识号    7426
交易次数       21
交易金额     5327
Name: 7425, dtype: int64
内部标识号    7427
交易次数       20
交易金额     2706
Name: 7426, dtype: int64
内部标识号    7428
交易次数        2
交易金额      169
Name: 7427, dtype: int64
内部标识号    7429
交易次数        5
交易金额      239
Name: 7428, dtype: int64
内部标识号    7430
交易次数        1
交易金额     7244
Name: 7429, dtype: int64
内部标识号    7431
交易次数       10
交易金额      303
Name: 7430, dtype: int64
内部标识号    7432
交易次数       17
交易金额     7432
Name: 7431, dtype: int64
内部标识号    7433
交易次数       11
交易金额      915
Name: 7432, dtype: int64
内部标识号    7434
交易次数       20
交易金额     7265
Name: 7433, dtype: int64
内部标识号    7435
交易次数        2
交易金额      424
Name: 7434, dtype: int64
内部标识号    7436
交易次数        9
交易金额      459
Name: 7435, dtype: int64
内部标识号     7437
交易次数        35
交易金额     53533
Name: 7436, dtype: int64
内部标识号    7438
交易次数        0
交易金额     8219
Name: 7437, dtype: int64
内部标识号    7439
交易次数        9
交易金额      340
Name: 7438, dtype: int64
内部标识号    7440
交易次数        3
交易金额      467
Name: 7439, dtype: int64
内部标识号    7441
交易次数        5
交易金额      252
Name: 7440, dtype: int64
内部标识号    7442
交易次数       12
交易金额      443
Name: 7441, dtype: int64
内部标识号    7443
交易次数        7
交易金额      165
Name: 7442, dtype: int64
内部标识号    7444
交易次数       28
交易金额     1677
Name: 7443, dtype: int64
内部标识号    7445
交易次数        9
交易金额      971
Name: 7444, dtype: int64
内部标识号    7446
交易次数        2
交易金额      963
Name: 7445, dtype: int64
内部标识号    7447
交易次数       12
交易金额      396
Name: 7446, dtype: int64
内部标识号    7448
交易次数        4
交易金额      201
Name: 7447, dtype: int64
内部标识号    7449
交易次数        0
交易金额     5007
Name: 7448, dtype: int64
内部标识号    7450
交易次数       22
交易金额      678
Name: 7449, dtype: int64
内部标识号    7451
交易次数        7
交易金额      148
Name: 7450, dtype: int64
内部标识号    7452
交易次数        6
交易金额      181
Name: 7451, dtype: int64
内部标识号    7453
交易次数       14
交易金额      631
Name: 7452, dtype: int64
内部标识号    7454
交易次数        3
交易金额      491
Name: 7453, dtype: int64
内部标识号    7455
交易次数        2
交易金额      291
Name: 7454, dtype: int64
内部标识号    7456
交易次数       14
交易金额      700
Name: 7455, dtype: int64
内部标识号    7457
交易次数       11
交易金额      845
Name: 7456, dtype: int64
内部标识号     7458
交易次数       103
交易金额     23279
Name: 7457, dtype: int64
内部标识号    7459
交易次数        6
交易金额      194
Name: 7458, dtype: int64
内部标识号    7460
交易次数        8
交易金额      191
Name: 7459, dtype: int64
内部标识号     7461
交易次数       195
交易金额     81310
Name: 7460, dtype: int64
内部标识号    7462
交易次数        0
交易金额     9828
Name: 7461, dtype: int64
内部标识号    7463
交易次数       10
交易金额      823
Name: 7462, dtype: int64
内部标识号    7464
交易次数        2
交易金额      690
Name: 7463, dtype: int64
内部标识号     7465
交易次数       122
交易金额     52448
Name: 7464, dtype: int64
内部标识号    7466
交易次数        2
交易金额      680
Name: 7465, dtype: int64
内部标识号    7467
交易次数       15
交易金额      905
Name: 7466, dtype: int64
内部标识号    7468
交易次数        1
交易金额     3977
Name: 7467, dtype: int64
内部标识号    7469
交易次数        5
交易金额      144
Name: 7468, dtype: int64
内部标识号     7470
交易次数         8
交易金额     12729
Name: 7469, dtype: int64
内部标识号    7471
交易次数        9
交易金额      460
Name: 7470, dtype: int64
内部标识号    7472
交易次数       19
交易金额     6026
Name: 7471, dtype: int64
内部标识号     7473
交易次数         5
交易金额     45663
Name: 7472, dtype: int64
内部标识号    7474
交易次数        1
交易金额      894
Name: 7473, dtype: int64
内部标识号    7475
交易次数       16
交易金额     4578
Name: 7474, dtype: int64
内部标识号    7476
交易次数       10
交易金额      937
Name: 7475, dtype: int64
内部标识号    7477
交易次数        8
交易金额      925
Name: 7476, dtype: int64
内部标识号    7478
交易次数       10
交易金额      952
Name: 7477, dtype: int64
内部标识号     7479
交易次数        30
交易金额     69103
Name: 7478, dtype: int64
内部标识号    7480
交易次数        1
交易金额     7379
Name: 7479, dtype: int64
内部标识号    7481
交易次数        1
交易金额     6756
Name: 7480, dtype: int64
内部标识号    7482
交易次数        1
交易金额     1563
Name: 7481, dtype: int64
内部标识号    7483
交易次数        1
交易金额      757
Name: 7482, dtype: int64
内部标识号    7484
交易次数        3
交易金额      252
Name: 7483, dtype: int64
内部标识号    7485
交易次数       15
交易金额      444
Name: 7484, dtype: int64
内部标识号    7486
交易次数        9
交易金额      402

Name: 7485, dtype: int64
内部标识号    7487
交易次数        9
交易金额      931
Name: 7486, dtype: int64
内部标识号    7488
交易次数        0
交易金额     8555
Name: 7487, dtype: int64
内部标识号    7489
交易次数       15
交易金额      787
Name: 7488, dtype: int64
内部标识号    7490
交易次数       12
交易金额      759
Name: 7489, dtype: int64
内部标识号    7491
交易次数       14
交易金额      928
Name: 7490, dtype: int64
内部标识号    7492
交易次数        2
交易金额      500
Name: 7491, dtype: int64
内部标识号    7493
交易次数        3
交易金额      394
Name: 7492, dtype: int64
内部标识号    7494
交易次数        9
交易金额      396
Name: 7493, dtype: int64
内部标识号    7495
交易次数        8
交易金额      260
Name: 7494, dtype: int64
内部标识号    7496
交易次数        6
交易金额      154
Name: 7495, dtype: int64
内部标识号    7497
交易次数        5
交易金额      234
Name: 7496, dtype: int64
内部标识号    7498
交易次数       11
交易金额      336
Name: 7497, dtype: int64
内部标识号    7499
交易次数        3
交易金额      141
Name: 7498, dtype: int64
内部标识号    7500
交易次数        1
交易金额      786
Name: 7499, dtype: int64
内部标识号    7501
交易次数        7
交易金额      270
Name: 7500, dtype: int64
内部标识号    7502
交易次数       15
交易金额      821
Name: 7501, dtype: int64
内部标识号    7503
交易次数        3
交易金额      488
Name: 7502, dtype: int64
内部标识号    7504
交易次数        0
交易金额     6015
Name: 7503, dtype: int64
内部标识号    7505
交易次数       23
交易金额      552
Name: 7504, dtype: int64
内部标识号     7506
交易次数       295
交易金额     56259
Name: 7505, dtype: int64
内部标识号    7507
交易次数        9
交易金额      697
Name: 7506, dtype: int64
内部标识号    7508
交易次数       12
交易金额      969
Name: 7507, dtype: int64
内部标识号    7509
交易次数        2
交易金额      847
Name: 7508, dtype: int64
内部标识号    7510
交易次数       12
交易金额      378
Name: 7509, dtype: int64
内部标识号    7511
交易次数        2
交易金额      704
Name: 7510, dtype: int64
内部标识号    7512
交易次数        9
交易金额      412
Name: 7511, dtype: int64
内部标识号    7513
交易次数        8
交易金额      271
Name: 7512, dtype: int64
内部标识号    7514
交易次数       23
交易金额     3167
Name: 7513, dtype: int64
内部标识号    7515
交易次数        8
交易金额      182
Name: 7514, dtype: int64
内部标识号    7516
交易次数        0
交易金额     8786
Name: 7515, dtype: int64
内部标识号    7517
交易次数        5
交易金额      232
Name: 7516, dtype: int64
内部标识号    7518
交易次数       15
交易金额      947
Name: 7517, dtype: int64
内部标识号    7519
交易次数       29
交易金额      669
Name: 7518, dtype: int64
内部标识号    7520
交易次数        3
交易金额      137
Name: 7519, dtype: int64
内部标识号     7521
交易次数       285
交易金额     75891
Name: 7520, dtype: int64
内部标识号    7522
交易次数       13
交易金额      640
Name: 7521, dtype: int64
内部标识号    7523
交易次数       12
交易金额      332
Name: 7522, dtype: int64
内部标识号    7524
交易次数        5
交易金额      119
Name: 7523, dtype: int64
内部标识号    7525
交易次数        3
交易金额      403
Name: 7524, dtype: int64
内部标识号     7526
交易次数         8
交易金额     49059
Name: 7525, dtype: int64
内部标识号    7527
交易次数        1
交易金额      926
Name: 7526, dtype: int64
内部标识号    7528
交易次数       10
交易金额      644
Name: 7527, dtype: int64
内部标识号    7529
交易次数        3
交易金额      446
Name: 7528, dtype: int64
内部标识号    7530
交易次数        7
交易金额      143
Name: 7529, dtype: int64
内部标识号    7531
交易次数       19
交易金额     4205
Name: 7530, dtype: int64
内部标识号    7532
交易次数       14
交易金额      864
Name: 7531, dtype: int64
内部标识号    7533
交易次数        0
交易金额     3775
Name: 7532, dtype: int64
内部标识号    7534
交易次数        9
交易金额      555
Name: 7533, dtype: int64
内部标识号    7535
交易次数       27
交易金额     2587
Name: 7534, dtype: int64
内部标识号    7536
交易次数       15
交易金额      860
Name: 7535, dtype: int64
内部标识号    7537
交易次数        9
交易金额      316
Name: 7536, dtype: int64
内部标识号    7538
交易次数       10
交易金额      802
Name: 7537, dtype: int64
内部标识号    7539
交易次数        8
交易金额      413
Name: 7538, dtype: int64
内部标识号    7540
交易次数        3
交易金额      358
Name: 7539, dtype: int64
内部标识号    7541
交易次数        2
交易金额      308
Name: 7540, dtype: int64
内部标识号    7542
交易次数       26
交易金额       81
Name: 7541, dtype: int64
内部标识号    7543
交易次数        1
交易金额      533
Name: 7542, dtype: int64
内部标识号    7544
交易次数        6
交易金额      225
Name: 7543, dtype: int64
内部标识号    7545
交易次数       15
交易金额      438
Name: 7544, dtype: int64
内部标识号    7546
交易次数        0
交易金额     5630
Name: 7545, dtype: int64
内部标识号    7547
交易次数       30
交易金额     3146
Name: 7546, dtype: int64
内部标识号    7548
交易次数        7
交易金额      170
Name: 7547, dtype: int64
内部标识号    7549
交易次数        3
交易金额      379
Name: 7548, dtype: int64
内部标识号    7550
交易次数        1
交易金额     1985
Name: 7549, dtype: int64
内部标识号    7551
交易次数        2
交易金额      300
Name: 7550, dtype: int64
内部标识号    7552
交易次数       12
交易金额      998
Name: 7551, dtype: int64
内部标识号    7553
交易次数       15
交易金额      447
Name: 7552, dtype: int64
内部标识号    7554
交易次数        7
交易金额      214
Name: 7553, dtype: int64
内部标识号    7555
交易次数        2
交易金额      824
Name: 7554, dtype: int64
内部标识号    7556
交易次数        2
交易金额      705
Name: 7555, dtype: int64
内部标识号    7557
交易次数        8
交易金额      501
Name: 7556, dtype: int64
内部标识号    7558
交易次数        7
交易金额      289
Name: 7557, dtype: int64
内部标识号    7559
交易次数       15
交易金额      923
Name: 7558, dtype: int64
内部标识号    7560
交易次数        2
交易金额      392
Name: 7559, dtype: int64
内部标识号    7561
交易次数        3
交易金额      152
Name: 7560, dtype: int64
内部标识号    7562
交易次数        2
交易金额      975
Name: 7561, dtype: int64
内部标识号    7563
交易次数       25
交易金额     9558
Name: 7562, dtype: int64
内部标识号    7564
交易次数        2
交易金额      937
Name: 7563, dtype: int64
内部标识号    7565
交易次数        2
交易金额      433
Name: 7564, dtype: int64
内部标识号    7566
交易次数        3
交易金额      499
Name: 7565, dtype: int64
内部标识号    7567
交易次数        5
交易金额      251
Name: 7566, dtype: int64
内部标识号    7568
交易次数        3
交易金额      342
Name: 7567, dtype: int64
内部标识号    7569
交易次数        2
交易金额      182
Name: 7568, dtype: int64
内部标识号    7570
交易次数        5
交易金额      259
Name: 7569, dtype: int64
内部标识号    7571
交易次数       16
交易金额     7296
Name: 7570, dtype: int64
内部标识号    7572
交易次数        9
交易金额      596
Name: 7571, dtype: int64
内部标识号    7573
交易次数       22
交易金额      803
Name: 7572, dtype: int64
内部标识号    7574
交易次数        8
交易金额      171
Name: 7573, dtype: int64
内部标识号    7575
交易次数        2
交易金额      572
Name: 7574, dtype: int64
内部标识号    7576
交易次数        2
交易金额      443
Name: 7575, dtype: int64
内部标识号    7577
交易次数        3
交易金额      418
Name: 7576, dtype: int64
内部标识号    7578
交易次数       10
交易金额      362
Name: 7577, dtype: int64
内部标识号    7579
交易次数        1
交易金额     6632
Name: 7578, dtype: int64
内部标识号    7580
交易次数       16
交易金额      607
Name: 7579, dtype: int64
内部标识号    7581
交易次数        4
交易金额      281
Name: 7580, dtype: int64
内部标识号    7582
交易次数       12
交易金额      615
Name: 7581, dtype: int64
内部标识号    7583
交易次数        5
交易金额      107
Name: 7582, dtype: int64
内部标识号    7584
交易次数       27
交易金额     6723
Name: 7583, dtype: int64
内部标识号    7585
交易次数       10
交易金额      561
Name: 7584, dtype: int64
内部标识号    7586
交易次数        1
交易金额      882
Name: 7585, dtype: int64
内部标识号    7587
交易次数        8
交易金额      473
Name: 7586, dtype: int64
内部标识号    7588
交易次数        3
交易金额      346
Name: 7587, dtype: int64
内部标识号     7589
交易次数         6
交易金额     63023
Name: 7588, dtype: int64
内部标识号    7590
交易次数        3
交易金额      392
Name: 7589, dtype: int64
内部标识号    7591
交易次数        1
交易金额     3935
Name: 7590, dtype: int64
内部标识号    7592
交易次数        3
交易金额      313
Name: 7591, dtype: int64
内部标识号    7593
交易次数       12
交易金额      320
Name: 7592, dtype: int64
内部标识号    7594
交易次数        1
交易金额      696
Name: 7593, dtype: int64
内部标识号    7595
交易次数        2
交易金额      412
Name: 7594, dtype: int64
内部标识号    7596
交易次数        3
交易金额      320
Name: 7595, dtype: int64
内部标识号    7597
交易次数       22
交易金额     7260
Name: 7596, dtype: int64
内部标识号    7598
交易次数        2
交易金额      364
Name: 7597, dtype: int64
内部标识号    7599
交易次数       15
交易金额      879
Name: 7598, dtype: int64
内部标识号    7600
交易次数       10
交易金额      307
Name: 7599, dtype: int64
内部标识号    7601
交易次数        7
交易金额      123
Name: 7600, dtype: int64
内部标识号    7602
交易次数        1
交易金额     6094
Name: 7601, dtype: int64
内部标识号    7603
交易次数        0
交易金额     2403
Name: 7602, dtype: int64
内部标识号    7604
交易次数        0
交易金额     7042
Name: 7603, dtype: int64
内部标识号    7605
交易次数       20
交易金额      668
Name: 7604, dtype: int64
内部标识号    7606
交易次数        2
交易金额      188
Name: 7605, dtype: int64
内部标识号    7607
交易次数       12
交易金额      863
Name: 7606, dtype: int64
内部标识号    7608
交易次数       17
交易金额     4637
Name: 7607, dtype: int64
内部标识号    7609
交易次数       20
交易金额     2391
Name: 7608, dtype: int64
内部标识号    7610
交易次数       13
交易金额      773
Name: 7609, dtype: int64
内部标识号     7611
交易次数         8
交易金额     66263
Name: 7610, dtype: int64
内部标识号    7612
交易次数        3
交易金额      405
Name: 7611, dtype: int64
内部标识号     7613
交易次数         6
交易金额     15296
Name: 7612, dtype: int64
内部标识号    7614
交易次数       24
交易金额      756
Name: 7613, dtype: int64
内部标识号    7615
交易次数       10
交易金额      436
Name: 7614, dtype: int64
内部标识号    7616
交易次数       14
交易金额      790
Name: 7615, dtype: int64
内部标识号    7617
交易次数        1
交易金额      698
Name: 7616, dtype: int64
内部标识号    7618
交易次数       14
交易金额      511
Name: 7617, dtype: int64
内部标识号    7619
交易次数        8
交易金额      411
Name: 7618, dtype: int64
内部标识号     7620
交易次数       174
交易金额     80897
Name: 7619, dtype: int64
内部标识号    7621
交易次数       22
交易金额      670
Name: 7620, dtype: int64
内部标识号     7622
交易次数        46
交易金额     76956
Name: 7621, dtype: int64
内部标识号    7623
交易次数        0
交易金额     1547
Name: 7622, dtype: int64
内部标识号    7624
交易次数       13
交易金额      553
Name: 7623, dtype: int64
内部标识号    7625
交易次数        8
交易金额      288
Name: 7624, dtype: int64
内部标识号    7626
交易次数        9
交易金额      878
Name: 7625, dtype: int64
内部标识号    7627
交易次数        3
交易金额      345
Name: 7626, dtype: int64
内部标识号    7628
交易次数        7
交易金额      177
Name: 7627, dtype: int64
内部标识号     7629
交易次数         6
交易金额     24180
Name: 7628, dtype: int64
内部标识号    7630
交易次数        2
交易金额      491
Name: 7629, dtype: int64
内部标识号    7631
交易次数       11
交易金额      624
Name: 7630, dtype: int64
内部标识号    7632
交易次数       15
交易金额      913
Name: 7631, dtype: int64
内部标识号    7633
交易次数        8
交易金额      650
Name: 7632, dtype: int64
内部标识号    7634
交易次数        8
交易金额      944
Name: 7633, dtype: int64
内部标识号    7635
交易次数        2
交易金额      610
Name: 7634, dtype: int64
内部标识号    7636
交易次数       12
交易金额      511
Name: 7635, dtype: int64
内部标识号    7637
交易次数        2
交易金额      377
Name: 7636, dtype: int64
内部标识号    7638
交易次数        1
交易金额      804
Name: 7637, dtype: int64
内部标识号    7639
交易次数        2
交易金额      853
Name: 7638, dtype: int64
内部标识号    7640
交易次数        3
交易金额      390
Name: 7639, dtype: int64
内部标识号    7641
交易次数       25
交易金额     1186
Name: 7640, dtype: int64
内部标识号    7642
交易次数       22
交易金额      963
Name: 7641, dtype: int64
内部标识号    7643
交易次数        2
交易金额      476
Name: 7642, dtype: int64
内部标识号    7644
交易次数        3
交易金额      385
Name: 7643, dtype: int64
内部标识号    7645
交易次数        2
交易金额      322
Name: 7644, dtype: int64
内部标识号    7646
交易次数        9
交易金额      656
Name: 7645, dtype: int64
内部标识号    7647
交易次数        6
交易金额      278
Name: 7646, dtype: int64
内部标识号    7648
交易次数       18
交易金额      762
Name: 7647, dtype: int64
内部标识号    7649
交易次数        2
交易金额      769
Name: 7648, dtype: int64
内部标识号    7650
交易次数        3
交易金额      413
Name: 7649, dtype: int64
内部标识号    7651
交易次数        2
交易金额      363
Name: 7650, dtype: int64
内部标识号    7652
交易次数       13
交易金额      434
Name: 7651, dtype: int64
内部标识号    7653
交易次数        7
交易金额      275
Name: 7652, dtype: int64
内部标识号    7654
交易次数        0
交易金额     2842
Name: 7653, dtype: int64
内部标识号    7655
交易次数        1
交易金额      509
Name: 7654, dtype: int64
内部标识号    7656
交易次数       22
交易金额     4863
Name: 7655, dtype: int64
内部标识号    7657
交易次数        0
交易金额     8374
Name: 7656, dtype: int64
内部标识号    7658
交易次数        3
交易金额      357
Name: 7657, dtype: int64
内部标识号    7659
交易次数        5
交易金额      182
Name: 7658, dtype: int64
内部标识号    7660
交易次数        2
交易金额      419
Name: 7659, dtype: int64
内部标识号     7661
交易次数         7
交易金额     17145
Name: 7660, dtype: int64
内部标识号    7662
交易次数        3
交易金额      184
Name: 7661, dtype: int64
内部标识号    7663
交易次数        8
交易金额      645
Name: 7662, dtype: int64
内部标识号    7664
交易次数        2
交易金额      496
Name: 7663, dtype: int64
内部标识号    7665
交易次数        6
交易金额      115
Name: 7664, dtype: int64
内部标识号    7666
交易次数        2
交易金额      502
Name: 7665, dtype: int64
内部标识号    7667
交易次数        5
交易金额      287
Name: 7666, dtype: int64
内部标识号    7668
交易次数        0
交易金额     4946
Name: 7667, dtype: int64
内部标识号    7669
交易次数        3
交易金额      495
Name: 7668, dtype: int64
内部标识号    7670
交易次数       12
交易金额      326
Name: 7669, dtype: int64
内部标识号    7671
交易次数        3
交易金额      493
Name: 7670, dtype: int64
内部标识号    7672
交易次数       14
交易金额      873
Name: 7671, dtype: int64
内部标识号    7673
交易次数        4
交易金额      157
Name: 7672, dtype: int64
内部标识号    7674
交易次数       17
交易金额       55
Name: 7673, dtype: int64
内部标识号    7675
交易次数        0
交易金额     1968
Name: 7674, dtype: int64
内部标识号    7676
交易次数        2
交易金额      789
Name: 7675, dtype: int64
内部标识号    7677
交易次数       12
交易金额      971
Name: 7676, dtype: int64
内部标识号    7678
交易次数       13
交易金额      486
Name: 7677, dtype: int64
内部标识号     7679
交易次数         7
交易金额     16507
Name: 7678, dtype: int64
内部标识号    7680
交易次数       11
交易金额      900
Name: 7679, dtype: int64
内部标识号    7681
交易次数        3
交易金额      315
Name: 7680, dtype: int64
内部标识号    7682
交易次数       12
交易金额      943
Name: 7681, dtype: int64
内部标识号    7683
交易次数        1
交易金额      778
Name: 7682, dtype: int64
内部标识号     7684
交易次数       262
交易金额     20969
Name: 7683, dtype: int64
内部标识号    7685
交易次数       22
交易金额     3327
Name: 7684, dtype: int64
内部标识号    7686
交易次数       14
交易金额      498
Name: 7685, dtype: int64
内部标识号    7687
交易次数       12
交易金额      734
Name: 7686, dtype: int64
内部标识号     7688
交易次数       210
交易金额     54527
Name: 7687, dtype: int64
内部标识号    7689
交易次数       30
交易金额     4501
Name: 7688, dtype: int64
内部标识号    7690
交易次数        1
交易金额      960
Name: 7689, dtype: int64
内部标识号    7691
交易次数        2
交易金额      309
Name: 7690, dtype: int64
内部标识号     7692
交易次数         3
交易金额     63917
Name: 7691, dtype: int64
内部标识号    7693
交易次数       10
交易金额      393
Name: 7692, dtype: int64
内部标识号    7694
交易次数        1
交易金额     6700
Name: 7693, dtype: int64
内部标识号    7695
交易次数        1
交易金额      659
Name: 7694, dtype: int64
内部标识号    7696
交易次数       11
交易金额      813
Name: 7695, dtype: int64
内部标识号    7697
交易次数        2
交易金额      996
Name: 7696, dtype: int64
内部标识号    7698
交易次数       11
交易金额      976
Name: 7697, dtype: int64
内部标识号     7699
交易次数         5
交易金额     39194
Name: 7698, dtype: int64
内部标识号    7700
交易次数       15
交易金额      852
Name: 7699, dtype: int64
内部标识号    7701
交易次数        0
交易金额     4234
Name: 7700, dtype: int64
内部标识号    7702
交易次数        2
交易金额      369
Name: 7701, dtype: int64
内部标识号    7703
交易次数        5
交易金额      134
Name: 7702, dtype: int64
内部标识号     7704
交易次数       190
交易金额     36962
Name: 7703, dtype: int64
内部标识号    7705
交易次数       14
交易金额      730
Name: 7704, dtype: int64
内部标识号    7706
交易次数        3
交易金额      278
Name: 7705, dtype: int64
内部标识号    7707
交易次数        8
交易金额      178
Name: 7706, dtype: int64
内部标识号    7708
交易次数        3
交易金额      352
Name: 7707, dtype: int64
内部标识号    7709
交易次数        7
交易金额      126
Name: 7708, dtype: int64
内部标识号    7710
交易次数        1
交易金额      901
Name: 7709, dtype: int64
内部标识号    7711
交易次数       18
交易金额      595
Name: 7710, dtype: int64
内部标识号    7712
交易次数        5
交易金额      134
Name: 7711, dtype: int64
内部标识号    7713
交易次数       13
交易金额      958
Name: 7712, dtype: int64
内部标识号    7714
交易次数        1
交易金额      621
Name: 7713, dtype: int64
内部标识号    7715
交易次数        3
交易金额      359
Name: 7714, dtype: int64
内部标识号    7716
交易次数        2
交易金额      560
Name: 7715, dtype: int64
内部标识号     7717
交易次数       109
交易金额     71271
Name: 7716, dtype: int64
内部标识号    7718
交易次数       10
交易金额      704
Name: 7717, dtype: int64
内部标识号    7719
交易次数        5
交易金额      138
Name: 7718, dtype: int64
内部标识号    7720
交易次数       19
交易金额     3095
Name: 7719, dtype: int64
内部标识号    7721
交易次数        1
交易金额     1620
Name: 7720, dtype: int64
内部标识号    7722
交易次数        0
交易金额     2174
Name: 7721, dtype: int64
内部标识号    7723
交易次数        8
交易金额      550
Name: 7722, dtype: int64
内部标识号    7724
交易次数        5
交易金额      116
Name: 7723, dtype: int64
内部标识号    7725
交易次数        1
交易金额      784
Name: 7724, dtype: int64
内部标识号    7726
交易次数        0
交易金额     5860
Name: 7725, dtype: int64
内部标识号    7727
交易次数       11
交易金额      825
Name: 7726, dtype: int64
内部标识号    7728
交易次数        2
交易金额      910
Name: 7727, dtype: int64
内部标识号    7729
交易次数       15
交易金额      443
Name: 7728, dtype: int64
内部标识号    7730
交易次数        0
交易金额     3871
Name: 7729, dtype: int64
内部标识号    7731
交易次数        2
交易金额      382
Name: 7730, dtype: int64
内部标识号    7732
交易次数       15
交易金额      752
Name: 7731, dtype: int64
内部标识号    7733
交易次数        8
交易金额      499
Name: 7732, dtype: int64
内部标识号     7734
交易次数         8
交易金额     96186
Name: 7733, dtype: int64
内部标识号    7735
交易次数       13
交易金额      629
Name: 7734, dtype: int64
内部标识号    7736
交易次数        1
交易金额      993
Name: 7735, dtype: int64
内部标识号     7737
交易次数         3
交易金额     15916
Name: 7736, dtype: int64
内部标识号     7738
交易次数       209
交易金额     91067
Name: 7737, dtype: int64
内部标识号    7739
交易次数        8
交易金额      511
Name: 7738, dtype: int64
内部标识号    7740
交易次数        9
交易金额      395
Name: 7739, dtype: int64
内部标识号    7741
交易次数       14
交易金额      780
Name: 7740, dtype: int64
内部标识号    7742
交易次数        3
交易金额      302
Name: 7741, dtype: int64
内部标识号    7743
交易次数        9
交易金额      700
Name: 7742, dtype: int64
内部标识号    7744
交易次数        3
交易金额      172
Name: 7743, dtype: int64
内部标识号    7745
交易次数        3
交易金额      148
Name: 7744, dtype: int64
内部标识号    7746
交易次数        8
交易金额      129
Name: 7745, dtype: int64
内部标识号    7747
交易次数        2
交易金额      381
Name: 7746, dtype: int64
内部标识号    7748
交易次数       11
交易金额      506
Name: 7747, dtype: int64
内部标识号    7749
交易次数        6
交易金额      111
Name: 7748, dtype: int64
内部标识号    7750
交易次数       28
交易金额      730
Name: 7749, dtype: int64
内部标识号    7751
交易次数        3
交易金额      278
Name: 7750, dtype: int64
内部标识号    7752
交易次数        2
交易金额      784
Name: 7751, dtype: int64
内部标识号    7753
交易次数        8
交易金额      346
Name: 7752, dtype: int64
内部标识号    7754
交易次数        1
交易金额      944
Name: 7753, dtype: int64
内部标识号    7755
交易次数       11
交易金额      444
Name: 7754, dtype: int64
内部标识号    7756
交易次数        2
交易金额      521
Name: 7755, dtype: int64
内部标识号    7757
交易次数        1
交易金额      651
Name: 7756, dtype: int64
内部标识号     7758
交易次数         7
交易金额     81096
Name: 7757, dtype: int64
内部标识号    7759
交易次数       15
交易金额      956
Name: 7758, dtype: int64
内部标识号    7760
交易次数        3
交易金额      169
Name: 7759, dtype: int64
内部标识号    7761
交易次数       13
交易金额     1000
Name: 7760, dtype: int64
内部标识号    7762
交易次数        3
交易金额      355
Name: 7761, dtype: int64
内部标识号    7763
交易次数        4
交易金额      242
Name: 7762, dtype: int64
内部标识号    7764
交易次数       15
交易金额      700
Name: 7763, dtype: int64
内部标识号    7765
交易次数        8
交易金额      260
Name: 7764, dtype: int64
内部标识号    7766
交易次数       13
交易金额      398

Name: 7765, dtype: int64
内部标识号    7767
交易次数        5
交易金额      204
Name: 7766, dtype: int64
内部标识号    7768
交易次数       10
交易金额      520
Name: 7767, dtype: int64
内部标识号    7769
交易次数        6
交易金额      259
Name: 7768, dtype: int64
内部标识号    7770
交易次数       29
交易金额     3005
Name: 7769, dtype: int64
内部标识号    7771
交易次数        0
交易金额     5540
Name: 7770, dtype: int64
内部标识号    7772
交易次数       13
交易金额      752
Name: 7771, dtype: int64
内部标识号    7773
交易次数        1
交易金额      803
Name: 7772, dtype: int64
内部标识号    7774
交易次数        2
交易金额      973
Name: 7773, dtype: int64
内部标识号    7775
交易次数        0
交易金额     1562
Name: 7774, dtype: int64
内部标识号     7776
交易次数         6
交易金额     83313
Name: 7775, dtype: int64
内部标识号    7777
交易次数       17
交易金额     3836
Name: 7776, dtype: int64
内部标识号    7778
交易次数        7
交易金额      130
Name: 7777, dtype: int64
内部标识号    7779
交易次数        3
交易金额      414
Name: 7778, dtype: int64
内部标识号    7780
交易次数       15
交易金额       42
Name: 7779, dtype: int64
内部标识号    7781
交易次数       10
交易金额      558
Name: 7780, dtype: int64
内部标识号    7782
交易次数        6
交易金额      203
Name: 7781, dtype: int64
内部标识号    7783
交易次数        3
交易金额      482
Name: 7782, dtype: int64
内部标识号     7784
交易次数       180
交易金额     34089
Name: 7783, dtype: int64
内部标识号    7785
交易次数        8
交易金额      172
Name: 7784, dtype: int64
内部标识号    7786
交易次数       13
交易金额      577
Name: 7785, dtype: int64
内部标识号    7787
交易次数        0
交易金额     1490
Name: 7786, dtype: int64
内部标识号    7788
交易次数       11
交易金额      957
Name: 7787, dtype: int64
内部标识号    7789
交易次数        2
交易金额      397
Name: 7788, dtype: int64
内部标识号    7790
交易次数        4
交易金额      281
Name: 7789, dtype: int64
内部标识号    7791
交易次数        8
交易金额      165
Name: 7790, dtype: int64
内部标识号     7792
交易次数         6
交易金额     54440
Name: 7791, dtype: int64
内部标识号    7793
交易次数       22
交易金额     6459
Name: 7792, dtype: int64
内部标识号     7794
交易次数       146
交易金额     40008
Name: 7793, dtype: int64
内部标识号    7795
交易次数       10
交易金额      937
Name: 7794, dtype: int64
内部标识号    7796
交易次数        5
交易金额      298
Name: 7795, dtype: int64
内部标识号    7797
交易次数        1
交易金额      752
Name: 7796, dtype: int64
内部标识号    7798
交易次数        2
交易金额      843
Name: 7797, dtype: int64
内部标识号    7799
交易次数        2
交易金额      520
Name: 7798, dtype: int64
内部标识号    7800
交易次数       13
交易金额      518
Name: 7799, dtype: int64
内部标识号    7801
交易次数        1
交易金额     5926
Name: 7800, dtype: int64
内部标识号    7802
交易次数        2
交易金额      345
Name: 7801, dtype: int64
内部标识号     7803
交易次数         7
交易金额     79216
Name: 7802, dtype: int64
内部标识号    7804
交易次数        2
交易金额      852
Name: 7803, dtype: int64
内部标识号    7805
交易次数       27
交易金额     5641
Name: 7804, dtype: int64
内部标识号    7806
交易次数        2
交易金额      949
Name: 7805, dtype: int64
内部标识号    7807
交易次数       15
交易金额      494
Name: 7806, dtype: int64
内部标识号    7808
交易次数        8
交易金额      424
Name: 7807, dtype: int64
内部标识号    7809
交易次数       23
交易金额     7144
Name: 7808, dtype: int64
内部标识号    7810
交易次数        4
交易金额      194
Name: 7809, dtype: int64
内部标识号    7811
交易次数        2
交易金额      829
Name: 7810, dtype: int64
内部标识号    7812
交易次数        8
交易金额      799
Name: 7811, dtype: int64
内部标识号    7813
交易次数        9
交易金额      580
Name: 7812, dtype: int64
内部标识号    7814
交易次数        3
交易金额      191
Name: 7813, dtype: int64
内部标识号     7815
交易次数       277
交易金额     81145
Name: 7814, dtype: int64
内部标识号    7816
交易次数        0
交易金额     8265
Name: 7815, dtype: int64
内部标识号    7817
交易次数        2
交易金额      973
Name: 7816, dtype: int64
内部标识号    7818
交易次数       11
交易金额      356
Name: 7817, dtype: int64
内部标识号    7819
交易次数        1
交易金额      589
Name: 7818, dtype: int64
内部标识号    7820
交易次数        3
交易金额      364
Name: 7819, dtype: int64
内部标识号    7821
交易次数        2
交易金额      475
Name: 7820, dtype: int64
内部标识号    7822
交易次数        7
交易金额      255
Name: 7821, dtype: int64
内部标识号    7823
交易次数        3
交易金额      316
Name: 7822, dtype: int64
内部标识号    7824
交易次数        2
交易金额      323
Name: 7823, dtype: int64
内部标识号    7825
交易次数        5
交易金额      198
Name: 7824, dtype: int64
内部标识号    7826
交易次数       24
交易金额      804
Name: 7825, dtype: int64
内部标识号    7827
交易次数        2
交易金额      347
Name: 7826, dtype: int64
内部标识号    7828
交易次数       29
交易金额      686
Name: 7827, dtype: int64
内部标识号    7829
交易次数        2
交易金额      740
Name: 7828, dtype: int64
内部标识号    7830
交易次数       10
交易金额      883
Name: 7829, dtype: int64
内部标识号    7831
交易次数       11
交易金额      426
Name: 7830, dtype: int64
内部标识号    7832
交易次数        8
交易金额      258
Name: 7831, dtype: int64
内部标识号    7833
交易次数        2
交易金额      332
Name: 7832, dtype: int64
内部标识号    7834
交易次数        8
交易金额      866
Name: 7833, dtype: int64
内部标识号    7835
交易次数       22
交易金额      821
Name: 7834, dtype: int64
内部标识号    7836
交易次数        0
交易金额     1946
Name: 7835, dtype: int64
内部标识号     7837
交易次数         8
交易金额     44581
Name: 7836, dtype: int64
内部标识号    7838
交易次数       19
交易金额      534
Name: 7837, dtype: int64
内部标识号    7839
交易次数        9
交易金额      896
Name: 7838, dtype: int64
内部标识号    7840
交易次数        3
交易金额      282
Name: 7839, dtype: int64
内部标识号    7841
交易次数       28
交易金额     2624
Name: 7840, dtype: int64
内部标识号    7842
交易次数        4
交易金额      229
Name: 7841, dtype: int64
内部标识号    7843
交易次数        5
交易金额      223
Name: 7842, dtype: int64
内部标识号    7844
交易次数        3
交易金额      481
Name: 7843, dtype: int64
内部标识号    7845
交易次数        7
交易金额      220
Name: 7844, dtype: int64
内部标识号    7846
交易次数        2
交易金额      492
Name: 7845, dtype: int64
内部标识号     7847
交易次数         5
交易金额     12298
Name: 7846, dtype: int64
内部标识号    7848
交易次数        4
交易金额      178
Name: 7847, dtype: int64
内部标识号    7849
交易次数        2
交易金额      478
Name: 7848, dtype: int64
内部标识号    7850
交易次数        3
交易金额      200
Name: 7849, dtype: int64
内部标识号    7851
交易次数        3
交易金额      486
Name: 7850, dtype: int64
内部标识号    7852
交易次数       11
交易金额      549
Name: 7851, dtype: int64
内部标识号    7853
交易次数       14
交易金额      957
Name: 7852, dtype: int64
内部标识号    7854
交易次数        1
交易金额     4308
Name: 7853, dtype: int64
内部标识号    7855
交易次数        2
交易金额      770
Name: 7854, dtype: int64
内部标识号    7856
交易次数        0
交易金额     8956
Name: 7855, dtype: int64
内部标识号    7857
交易次数        3
交易金额      272
Name: 7856, dtype: int64
内部标识号     7858
交易次数       285
交易金额     92746
Name: 7857, dtype: int64
内部标识号    7859
交易次数        0
交易金额     2269
Name: 7858, dtype: int64
内部标识号    7860
交易次数       11
交易金额      318
Name: 7859, dtype: int64
内部标识号    7861
交易次数        3
交易金额      322
Name: 7860, dtype: int64
内部标识号    7862
交易次数        9
交易金额      662
Name: 7861, dtype: int64
内部标识号    7863
交易次数        1
交易金额     9545
Name: 7862, dtype: int64
内部标识号    7864
交易次数       11
交易金额      332
Name: 7863, dtype: int64
内部标识号    7865
交易次数        3
交易金额      442
Name: 7864, dtype: int64
内部标识号    7866
交易次数        1
交易金额     8510
Name: 7865, dtype: int64
内部标识号    7867
交易次数        3
交易金额      240
Name: 7866, dtype: int64
内部标识号    7868
交易次数       11
交易金额      757
Name: 7867, dtype: int64
内部标识号    7869
交易次数        1
交易金额      566
Name: 7868, dtype: int64
内部标识号    7870
交易次数       10
交易金额      976
Name: 7869, dtype: int64
内部标识号    7871
交易次数        9
交易金额      390
Name: 7870, dtype: int64
内部标识号    7872
交易次数        6
交易金额      123
Name: 7871, dtype: int64
内部标识号    7873
交易次数        3
交易金额      460
Name: 7872, dtype: int64
内部标识号    7874
交易次数        2
交易金额      431
Name: 7873, dtype: int64
内部标识号    7875
交易次数       11
交易金额      633
Name: 7874, dtype: int64
内部标识号    7876
交易次数        3
交易金额      442
Name: 7875, dtype: int64
内部标识号    7877
交易次数       23
交易金额       26
Name: 7876, dtype: int64
内部标识号    7878
交易次数        2
交易金额      379
Name: 7877, dtype: int64
内部标识号    7879
交易次数        2
交易金额      461
Name: 7878, dtype: int64
内部标识号    7880
交易次数       13
交易金额      900
Name: 7879, dtype: int64
内部标识号    7881
交易次数       10
交易金额      459
Name: 7880, dtype: int64
内部标识号    7882
交易次数       29
交易金额      923
Name: 7881, dtype: int64
内部标识号    7883
交易次数        9
交易金额      543
Name: 7882, dtype: int64
内部标识号    7884
交易次数        0
交易金额     4353
Name: 7883, dtype: int64
内部标识号    7885
交易次数       29
交易金额     9651
Name: 7884, dtype: int64
内部标识号    7886
交易次数       30
交易金额     4400
Name: 7885, dtype: int64
内部标识号    7887
交易次数       14
交易金额      662
Name: 7886, dtype: int64
内部标识号    7888
交易次数       13
交易金额      474
Name: 7887, dtype: int64
内部标识号     7889
交易次数        78
交易金额     58995
Name: 7888, dtype: int64
内部标识号    7890
交易次数        3
交易金额      430
Name: 7889, dtype: int64
内部标识号    7891
交易次数       27
交易金额      626
Name: 7890, dtype: int64
内部标识号    7892
交易次数       11
交易金额      402
Name: 7891, dtype: int64
内部标识号    7893
交易次数        1
交易金额      654
Name: 7892, dtype: int64
内部标识号    7894
交易次数        6
交易金额      266
Name: 7893, dtype: int64
内部标识号    7895
交易次数        3
交易金额      334
Name: 7894, dtype: int64
内部标识号    7896
交易次数       10
交易金额      523
Name: 7895, dtype: int64
内部标识号    7897
交易次数       10
交易金额      836
Name: 7896, dtype: int64
内部标识号     7898
交易次数        36
交易金额     19851
Name: 7897, dtype: int64
内部标识号    7899
交易次数       10
交易金额      704
Name: 7898, dtype: int64
内部标识号    7900
交易次数        6
交易金额      113
Name: 7899, dtype: int64
内部标识号    7901
交易次数        1
交易金额      586
Name: 7900, dtype: int64
内部标识号     7902
交易次数         7
交易金额     47339
Name: 7901, dtype: int64
内部标识号    7903
交易次数       10
交易金额      796
Name: 7902, dtype: int64
内部标识号    7904
交易次数        8
交易金额      901
Name: 7903, dtype: int64
内部标识号     7905
交易次数       140
交易金额     53636
Name: 7904, dtype: int64
内部标识号    7906
交易次数       28
交易金额     6333
Name: 7905, dtype: int64
内部标识号    7907
交易次数       10
交易金额      371
Name: 7906, dtype: int64
内部标识号    7908
交易次数        6
交易金额      146
Name: 7907, dtype: int64
内部标识号    7909
交易次数       27
交易金额     7970
Name: 7908, dtype: int64
内部标识号    7910
交易次数       18
交易金额      586
Name: 7909, dtype: int64
内部标识号    7911
交易次数        1
交易金额      913
Name: 7910, dtype: int64
内部标识号    7912
交易次数        2
交易金额      153
Name: 7911, dtype: int64
内部标识号     7913
交易次数         5
交易金额     16205
Name: 7912, dtype: int64
内部标识号    7914
交易次数       24
交易金额     9173
Name: 7913, dtype: int64
内部标识号    7915
交易次数       10
交易金额      354
Name: 7914, dtype: int64
内部标识号    7916
交易次数        9
交易金额      985
Name: 7915, dtype: int64
内部标识号    7917
交易次数        5
交易金额      243
Name: 7916, dtype: int64
内部标识号    7918
交易次数       10
交易金额      696
Name: 7917, dtype: int64
内部标识号    7919
交易次数        6
交易金额      171
Name: 7918, dtype: int64
内部标识号    7920
交易次数       11
交易金额      809
Name: 7919, dtype: int64
内部标识号    7921
交易次数        8
交易金额      422
Name: 7920, dtype: int64
内部标识号    7922
交易次数        3
交易金额      358
Name: 7921, dtype: int64
内部标识号    7923
交易次数        2
交易金额      500
Name: 7922, dtype: int64
内部标识号    7924
交易次数       11
交易金额      808
Name: 7923, dtype: int64
内部标识号    7925
交易次数        2
交易金额      397
Name: 7924, dtype: int64
内部标识号    7926
交易次数        5
交易金额      210
Name: 7925, dtype: int64
内部标识号    7927
交易次数        1
交易金额     6048
Name: 7926, dtype: int64
内部标识号    7928
交易次数        8
交易金额      701
Name: 7927, dtype: int64
内部标识号    7929
交易次数        9
交易金额      380
Name: 7928, dtype: int64
内部标识号     7930
交易次数       132
交易金额     22439
Name: 7929, dtype: int64
内部标识号    7931
交易次数       21
交易金额     6404
Name: 7930, dtype: int64
内部标识号     7932
交易次数       144
交易金额     85201
Name: 7931, dtype: int64
内部标识号    7933
交易次数        8
交易金额      118
Name: 7932, dtype: int64
内部标识号    7934
交易次数        3
交易金额      428
Name: 7933, dtype: int64
内部标识号    7935
交易次数        0
交易金额     6905
Name: 7934, dtype: int64
内部标识号    7936
交易次数       13
交易金额      957
Name: 7935, dtype: int64
内部标识号    7937
交易次数        3
交易金额      435
Name: 7936, dtype: int64
内部标识号    7938
交易次数        1
交易金额     4006
Name: 7937, dtype: int64
内部标识号    7939
交易次数       14
交易金额      812
Name: 7938, dtype: int64
内部标识号    7940
交易次数        1
交易金额     1550
Name: 7939, dtype: int64
内部标识号     7941
交易次数         4
交易金额     54848
Name: 7940, dtype: int64
内部标识号     7942
交易次数         4
交易金额     10371
Name: 7941, dtype: int64
内部标识号    7943
交易次数       11
交易金额      382
Name: 7942, dtype: int64
内部标识号    7944
交易次数        4
交易金额      162
Name: 7943, dtype: int64
内部标识号    7945
交易次数       15
交易金额      311
Name: 7944, dtype: int64
内部标识号    7946
交易次数        8
交易金额      822
Name: 7945, dtype: int64
内部标识号    7947
交易次数       28
交易金额      690
Name: 7946, dtype: int64
内部标识号    7948
交易次数        1
交易金额      816
Name: 7947, dtype: int64
内部标识号    7949
交易次数       15
交易金额     2855
Name: 7948, dtype: int64
内部标识号    7950
交易次数        3
交易金额      361
Name: 7949, dtype: int64
内部标识号    7951
交易次数        1
交易金额      867
Name: 7950, dtype: int64
内部标识号    7952
交易次数        2
交易金额      496
Name: 7951, dtype: int64
内部标识号    7953
交易次数       30
交易金额     7486
Name: 7952, dtype: int64
内部标识号    7954
交易次数        0
交易金额     1441
Name: 7953, dtype: int64
内部标识号    7955
交易次数        3
交易金额      353
Name: 7954, dtype: int64
内部标识号     7956
交易次数         8
交易金额     37378
Name: 7955, dtype: int64
内部标识号    7957
交易次数        0
交易金额     1502
Name: 7956, dtype: int64
内部标识号    7958
交易次数        8
交易金额      483
Name: 7957, dtype: int64
内部标识号    7959
交易次数        3
交易金额      241
Name: 7958, dtype: int64
内部标识号    7960
交易次数       10
交易金额      346
Name: 7959, dtype: int64
内部标识号    7961
交易次数       22
交易金额      639
Name: 7960, dtype: int64
内部标识号    7962
交易次数        3
交易金额      467
Name: 7961, dtype: int64
内部标识号    7963
交易次数        3
交易金额      354
Name: 7962, dtype: int64
内部标识号    7964
交易次数       19
交易金额     8375
Name: 7963, dtype: int64
内部标识号    7965
交易次数       19
交易金额      747
Name: 7964, dtype: int64
内部标识号    7966
交易次数        3
交易金额      277
Name: 7965, dtype: int64
内部标识号    7967
交易次数        2
交易金额      474
Name: 7966, dtype: int64
内部标识号    7968
交易次数        2
交易金额      350
Name: 7967, dtype: int64
内部标识号    7969
交易次数        2
交易金额      688
Name: 7968, dtype: int64
内部标识号    7970
交易次数       10
交易金额      763
Name: 7969, dtype: int64
内部标识号     7971
交易次数         8
交易金额     72312
Name: 7970, dtype: int64
内部标识号    7972
交易次数        8
交易金额      214
Name: 7971, dtype: int64
内部标识号    7973
交易次数        0
交易金额     1889
Name: 7972, dtype: int64
内部标识号    7974
交易次数        0
交易金额     8696
Name: 7973, dtype: int64
内部标识号     7975
交易次数         5
交易金额     78606
Name: 7974, dtype: int64
内部标识号    7976
交易次数        8
交易金额      965
Name: 7975, dtype: int64
内部标识号    7977
交易次数        8
交易金额      778
Name: 7976, dtype: int64
内部标识号    7978
交易次数        2
交易金额      560
Name: 7977, dtype: int64
内部标识号    7979
交易次数        4
交易金额      285
Name: 7978, dtype: int64
内部标识号    7980
交易次数        8
交易金额      788
Name: 7979, dtype: int64
内部标识号     7981
交易次数         8
交易金额     55200
Name: 7980, dtype: int64
内部标识号    7982
交易次数        1
交易金额     4300
Name: 7981, dtype: int64
内部标识号    7983
交易次数        1
交易金额      555
Name: 7982, dtype: int64
内部标识号    7984
交易次数       14
交易金额      376
Name: 7983, dtype: int64
内部标识号    7985
交易次数        9
交易金额      425
Name: 7984, dtype: int64
内部标识号    7986
交易次数        7
交易金额      233
Name: 7985, dtype: int64
内部标识号    7987
交易次数        4
交易金额      120
Name: 7986, dtype: int64
内部标识号    7988
交易次数        3
交易金额      197
Name: 7987, dtype: int64
内部标识号    7989
交易次数        6
交易金额      174
Name: 7988, dtype: int64
内部标识号    7990
交易次数        3
交易金额      391
Name: 7989, dtype: int64
内部标识号    7991
交易次数        0
交易金额     9629
Name: 7990, dtype: int64
内部标识号    7992
交易次数       14
交易金额      717
Name: 7991, dtype: int64
内部标识号    7993
交易次数        1
交易金额     9179
Name: 7992, dtype: int64
内部标识号    7994
交易次数       13
交易金额      440
Name: 7993, dtype: int64
内部标识号     7995
交易次数         7
交易金额     18672
Name: 7994, dtype: int64
内部标识号    7996
交易次数        3
交易金额      224
Name: 7995, dtype: int64
内部标识号    7997
交易次数        3
交易金额      420
Name: 7996, dtype: int64
内部标识号    7998
交易次数        8
交易金额      298
Name: 7997, dtype: int64
内部标识号    7999
交易次数        3
交易金额      478
Name: 7998, dtype: int64
内部标识号    8000
交易次数        2
交易金额      666
Name: 7999, dtype: int64
内部标识号    8001
交易次数        2
交易金额      136
Name: 8000, dtype: int64
内部标识号    8002
交易次数        2
交易金额      192
Name: 8001, dtype: int64
内部标识号    8003
交易次数        2
交易金额      554
Name: 8002, dtype: int64
内部标识号    8004
交易次数        0
交易金额     3735
Name: 8003, dtype: int64
内部标识号    8005
交易次数       10
交易金额      997
Name: 8004, dtype: int64
内部标识号    8006
交易次数        3
交易金额      204
Name: 8005, dtype: int64
内部标识号    8007
交易次数        3
交易金额      200
Name: 8006, dtype: int64
内部标识号     8008
交易次数         5
交易金额     44696
Name: 8007, dtype: int64
内部标识号    8009
交易次数        2
交易金额      862
Name: 8008, dtype: int64
内部标识号    8010
交易次数       15
交易金额      865
Name: 8009, dtype: int64
内部标识号    8011
交易次数       14
交易金额      365
Name: 8010, dtype: int64
内部标识号    8012
交易次数        2
交易金额      215
Name: 8011, dtype: int64
内部标识号     8013
交易次数       283
交易金额     14133
Name: 8012, dtype: int64
内部标识号    8014
交易次数        8
交易金额      606
Name: 8013, dtype: int64
内部标识号    8015
交易次数        2
交易金额      428
Name: 8014, dtype: int64
内部标识号    8016
交易次数       14
交易金额      715
Name: 8015, dtype: int64
内部标识号    8017
交易次数       11
交易金额      348
Name: 8016, dtype: int64
内部标识号    8018
交易次数        2
交易金额      687
Name: 8017, dtype: int64
内部标识号    8019
交易次数        0
交易金额     5979
Name: 8018, dtype: int64
内部标识号    8020
交易次数        3
交易金额      246
Name: 8019, dtype: int64
内部标识号    8021
交易次数        0
交易金额     7666
Name: 8020, dtype: int64
内部标识号    8022
交易次数        3
交易金额      150
Name: 8021, dtype: int64
内部标识号    8023
交易次数       13
交易金额      489
Name: 8022, dtype: int64
内部标识号    8024
交易次数        3
交易金额      283
Name: 8023, dtype: int64
内部标识号    8025
交易次数        8
交易金额      154
Name: 8024, dtype: int64
内部标识号    8026
交易次数        1
交易金额      924
Name: 8025, dtype: int64
内部标识号    8027
交易次数        1
交易金额     3853
Name: 8026, dtype: int64
内部标识号    8028
交易次数        4
交易金额      224
Name: 8027, dtype: int64
内部标识号    8029
交易次数       13
交易金额      700
Name: 8028, dtype: int64
内部标识号    8030
交易次数       13
交易金额      446
Name: 8029, dtype: int64
内部标识号    8031
交易次数        8
交易金额      266
Name: 8030, dtype: int64
内部标识号    8032
交易次数       12
交易金额      342
Name: 8031, dtype: int64
内部标识号    8033
交易次数       15
交易金额      645
Name: 8032, dtype: int64
内部标识号    8034
交易次数        7
交易金额      266
Name: 8033, dtype: int64
内部标识号    8035
交易次数       20
交易金额     9019
Name: 8034, dtype: int64
内部标识号    8036
交易次数        3
交易金额      136
Name: 8035, dtype: int64
内部标识号    8037
交易次数       15
交易金额     2032
Name: 8036, dtype: int64
内部标识号    8038
交易次数       24
交易金额       47
Name: 8037, dtype: int64
内部标识号     8039
交易次数       281
交易金额     62297
Name: 8038, dtype: int64
内部标识号    8040
交易次数        2
交易金额      490
Name: 8039, dtype: int64
内部标识号     8041
交易次数         5
交易金额     66849
Name: 8040, dtype: int64
内部标识号    8042
交易次数       14
交易金额      675
Name: 8041, dtype: int64
内部标识号    8043
交易次数        1
交易金额     4260
Name: 8042, dtype: int64
内部标识号    8044
交易次数        1
交易金额     4186
Name: 8043, dtype: int64
内部标识号    8045
交易次数        2
交易金额      898
Name: 8044, dtype: int64
内部标识号    8046
交易次数        8
交易金额      208
Name: 8045, dtype: int64
内部标识号    8047
交易次数        1
交易金额     9964
Name: 8046, dtype: int64
内部标识号    8048
交易次数        2
交易金额      454
Name: 8047, dtype: int64
内部标识号    8049
交易次数        5
交易金额      113
Name: 8048, dtype: int64
内部标识号    8050
交易次数        6
交易金额      276
Name: 8049, dtype: int64
内部标识号    8051
交易次数        2
交易金额      955
Name: 8050, dtype: int64
内部标识号    8052
交易次数       10
交易金额      756
Name: 8051, dtype: int64
内部标识号    8053
交易次数       14
交易金额      962
Name: 8052, dtype: int64
内部标识号    8054
交易次数        2
交易金额      411
Name: 8053, dtype: int64
内部标识号    8055
交易次数       13
交易金额      469
Name: 8054, dtype: int64
内部标识号    8056
交易次数       14
交易金额      341
Name: 8055, dtype: int64
内部标识号    8057
交易次数        6
交易金额      129
Name: 8056, dtype: int64
内部标识号    8058
交易次数        8
交易金额      161
Name: 8057, dtype: int64
内部标识号    8059
交易次数        0
交易金额     1160
Name: 8058, dtype: int64
内部标识号    8060
交易次数       27
交易金额     1662
Name: 8059, dtype: int64
内部标识号     8061
交易次数       236
交易金额     63859
Name: 8060, dtype: int64
内部标识号    8062
交易次数        5
交易金额      226
Name: 8061, dtype: int64
内部标识号    8063
交易次数       13
交易金额      999

Name: 8195, dtype: int64
内部标识号    8197
交易次数       12
交易金额      302
Name: 8196, dtype: int64
内部标识号    8198
交易次数        9
交易金额      412
Name: 8197, dtype: int64
内部标识号    8199
交易次数       13
交易金额      448
Name: 8198, dtype: int64
内部标识号    8200
交易次数        1
交易金额     5570
Name: 8199, dtype: int64
内部标识号    8201
交易次数        9
交易金额      942
Name: 8200, dtype: int64
内部标识号    8202
交易次数        7
交易金额      150
Name: 8201, dtype: int64
内部标识号    8203
交易次数        3
交易金额      250
Name: 8202, dtype: int64
内部标识号    8204
交易次数       14
交易金额      750
Name: 8203, dtype: int64
内部标识号    8205
交易次数       10
交易金额      312
Name: 8204, dtype: int64
内部标识号    8206
交易次数        8
交易金额      640
Name: 8205, dtype: int64
内部标识号    8207
交易次数       15
交易金额      503
Name: 8206, dtype: int64
内部标识号    8208
交易次数       21
交易金额     9766
Name: 8207, dtype: int64
内部标识号    8209
交易次数       11
交易金额      546
Name: 8208, dtype: int64
内部标识号    8210
交易次数       26
交易金额      528
Name: 8209, dtype: int64
内部标识号    8211
交易次数       12
交易金额      336
Name: 8210, dtype: int64
内部标识号    8212
交易次数       18
交易金额     6230
Name: 8211, dtype: int64
内部标识号    8213
交易次数        3
交易金额      491
Name: 8212, dtype: int64
内部标识号    8214
交易次数       22
交易金额     4146
Name: 8213, dtype: int64
内部标识号    8215
交易次数        2
交易金额      766
Name: 8214, dtype: int64
内部标识号    8216
交易次数        8
交易金额      125
Name: 8215, dtype: int64
内部标识号    8217
交易次数       14
交易金额      480
Name: 8216, dtype: int64
内部标识号    8218
交易次数        1
交易金额     3326
Name: 8217, dtype: int64
内部标识号    8219
交易次数        4
交易金额      228
Name: 8218, dtype: int64
内部标识号    8220
交易次数       13
交易金额      337
Name: 8219, dtype: int64
内部标识号    8221
交易次数        1
交易金额     7407
Name: 8220, dtype: int64
内部标识号    8222
交易次数        1
交易金额      795
Name: 8221, dtype: int64
内部标识号    8223
交易次数        1
交易金额      608
Name: 8222, dtype: int64
内部标识号    8224
交易次数        2
交易金额      630
Name: 8223, dtype: int64
内部标识号    8225
交易次数        5
交易金额      245
Name: 8224, dtype: int64
内部标识号    8226
交易次数       19
交易金额      666
Name: 8225, dtype: int64
内部标识号    8227
交易次数       15
交易金额      822
Name: 8226, dtype: int64
内部标识号    8228
交易次数        3
交易金额      440
Name: 8227, dtype: int64
内部标识号    8229
交易次数        3
交易金额      266
Name: 8228, dtype: int64
内部标识号    8230
交易次数       10
交易金额      435
Name: 8229, dtype: int64
内部标识号    8231
交易次数        4
交易金额      203
Name: 8230, dtype: int64
内部标识号    8232
交易次数        2
交易金额      857
Name: 8231, dtype: int64
内部标识号    8233
交易次数        8
交易金额      135
Name: 8232, dtype: int64
内部标识号    8234
交易次数        0
交易金额     7810
Name: 8233, dtype: int64
内部标识号    8235
交易次数        4
交易金额      298
Name: 8234, dtype: int64
内部标识号    8236
交易次数        8
交易金额      992
Name: 8235, dtype: int64
内部标识号    8237
交易次数       19
交易金额     2315
Name: 8236, dtype: int64
内部标识号    8238
交易次数        0
交易金额     4495
Name: 8237, dtype: int64
内部标识号    8239
交易次数        5
交易金额      100
Name: 8238, dtype: int64
内部标识号    8240
交易次数        2
交易金额      367
Name: 8239, dtype: int64
内部标识号    8241
交易次数        6
交易金额      274
Name: 8240, dtype: int64
内部标识号    8242
交易次数       11
交易金额      853
Name: 8241, dtype: int64
内部标识号    8243
交易次数       12
交易金额      320
Name: 8242, dtype: int64
内部标识号    8244
交易次数       11
交易金额      315
Name: 8243, dtype: int64
内部标识号    8245
交易次数       15
交易金额      704
Name: 8244, dtype: int64
内部标识号    8246
交易次数        9
交易金额      842
Name: 8245, dtype: int64
内部标识号    8247
交易次数       27
交易金额     7717
Name: 8246, dtype: int64
内部标识号    8248
交易次数       27
交易金额     6188
Name: 8247, dtype: int64
内部标识号    8249
交易次数       22
交易金额     3111
Name: 8248, dtype: int64
内部标识号    8250
交易次数        2
交易金额      342
Name: 8249, dtype: int64
内部标识号    8251
交易次数        9
交易金额      901
Name: 8250, dtype: int64
内部标识号    8252
交易次数       15
交易金额      924
Name: 8251, dtype: int64
内部标识号    8253
交易次数       11
交易金额      909
Name: 8252, dtype: int64
内部标识号    8254
交易次数       13
交易金额      806
Name: 8253, dtype: int64
内部标识号    8255
交易次数        3
交易金额      197
Name: 8254, dtype: int64
内部标识号    8256
交易次数       13
交易金额      456
Name: 8255, dtype: int64
内部标识号    8257
交易次数        3
交易金额      324
Name: 8256, dtype: int64
内部标识号     8258
交易次数         5
交易金额     98156
Name: 8257, dtype: int64
内部标识号    8259
交易次数        1
交易金额     7198
Name: 8258, dtype: int64
内部标识号    8260
交易次数       10
交易金额      479
Name: 8259, dtype: int64
内部标识号    8261
交易次数        2
交易金额      369
Name: 8260, dtype: int64
内部标识号    8262
交易次数        6
交易金额      130
Name: 8261, dtype: int64
内部标识号    8263
交易次数        1
交易金额      742
Name: 8262, dtype: int64
内部标识号    8264
交易次数       13
交易金额      347
Name: 8263, dtype: int64
内部标识号    8265
交易次数        2
交易金额      785
Name: 8264, dtype: int64
内部标识号    8266
交易次数       11
交易金额      305
Name: 8265, dtype: int64
内部标识号    8267
交易次数       14
交易金额      334
Name: 8266, dtype: int64
内部标识号    8268
交易次数        3
交易金额      432
Name: 8267, dtype: int64
内部标识号    8269
交易次数        9
交易金额      409
Name: 8268, dtype: int64
内部标识号    8270
交易次数       15
交易金额      772
Name: 8269, dtype: int64
内部标识号    8271
交易次数        8
交易金额      657
Name: 8270, dtype: int64
内部标识号    8272
交易次数        2
交易金额      636
Name: 8271, dtype: int64
内部标识号    8273
交易次数       14
交易金额      380
Name: 8272, dtype: int64
内部标识号     8274
交易次数       107
交易金额     52713
Name: 8273, dtype: int64
内部标识号    8275
交易次数       13
交易金额      435
Name: 8274, dtype: int64
内部标识号    8276
交易次数       16
交易金额     9076
Name: 8275, dtype: int64
内部标识号    8277
交易次数        1
交易金额     9776
Name: 8276, dtype: int64
内部标识号    8278
交易次数       12
交易金额      619
Name: 8277, dtype: int64
内部标识号    8279
交易次数        2
交易金额      980
Name: 8278, dtype: int64
内部标识号    8280
交易次数       11
交易金额      582
Name: 8279, dtype: int64
内部标识号    8281
交易次数        7
交易金额      248
Name: 8280, dtype: int64
内部标识号    8282
交易次数        3
交易金额      413
Name: 8281, dtype: int64
内部标识号     8283
交易次数         4
交易金额     22510
Name: 8282, dtype: int64
内部标识号    8284
交易次数        1
交易金额     7167
Name: 8283, dtype: int64
内部标识号    8285
交易次数       10
交易金额      373
Name: 8284, dtype: int64
内部标识号    8286
交易次数       26
交易金额     2943
Name: 8285, dtype: int64
内部标识号     8287
交易次数       138
交易金额     20206
Name: 8286, dtype: int64
内部标识号    8288
交易次数        1
交易金额      817
Name: 8287, dtype: int64
内部标识号    8289
交易次数        2
交易金额      617
Name: 8288, dtype: int64
内部标识号    8290
交易次数        0
交易金额     5245
Name: 8289, dtype: int64
内部标识号     8291
交易次数         3
交易金额     85241
Name: 8290, dtype: int64
内部标识号    8292
交易次数        9
交易金额      977
Name: 8291, dtype: int64
内部标识号    8293
交易次数        2
交易金额      420
Name: 8292, dtype: int64
内部标识号    8294
交易次数        2
交易金额      343
Name: 8293, dtype: int64
内部标识号    8295
交易次数       12
交易金额      828
Name: 8294, dtype: int64
内部标识号     8296
交易次数         5
交易金额     14179
Name: 8295, dtype: int64
内部标识号    8297
交易次数       11
交易金额      850
Name: 8296, dtype: int64
内部标识号    8298
交易次数        3
交易金额      253
Name: 8297, dtype: int64
内部标识号    8299
交易次数        1
交易金额      938
Name: 8298, dtype: int64
内部标识号    8300
交易次数       14
交易金额      359
Name: 8299, dtype: int64
内部标识号    8301
交易次数       20
交易金额     6230
Name: 8300, dtype: int64
内部标识号     8302
交易次数         6
交易金额     37793
Name: 8301, dtype: int64
内部标识号    8303
交易次数        7
交易金额      153
Name: 8302, dtype: int64
内部标识号    8304
交易次数        0
交易金额     8647
Name: 8303, dtype: int64
内部标识号    8305
交易次数       11
交易金额      437
Name: 8304, dtype: int64
内部标识号    8306
交易次数       10
交易金额      505
Name: 8305, dtype: int64
内部标识号    8307
交易次数        3
交易金额      361
Name: 8306, dtype: int64
内部标识号     8308
交易次数         3
交易金额     93006
Name: 8307, dtype: int64
内部标识号    8309
交易次数        2
交易金额      392
Name: 8308, dtype: int64
内部标识号    8310
交易次数       14
交易金额      631
Name: 8309, dtype: int64
内部标识号    8311
交易次数        1
交易金额      626
Name: 8310, dtype: int64
内部标识号    8312
交易次数        0
交易金额     5146
Name: 8311, dtype: int64
内部标识号    8313
交易次数        2
交易金额      374
Name: 8312, dtype: int64
内部标识号    8314
交易次数       17
交易金额     4434
Name: 8313, dtype: int64
内部标识号    8315
交易次数        2
交易金额      308
Name: 8314, dtype: int64
内部标识号    8316
交易次数        1
交易金额      517
Name: 8315, dtype: int64
内部标识号    8317
交易次数       10
交易金额      359
Name: 8316, dtype: int64
内部标识号    8318
交易次数        3
交易金额      233
Name: 8317, dtype: int64
内部标识号    8319
交易次数        2
交易金额      507
Name: 8318, dtype: int64
内部标识号    8320
交易次数        3
交易金额      228
Name: 8319, dtype: int64
内部标识号    8321
交易次数        5
交易金额      181
Name: 8320, dtype: int64
内部标识号    8322
交易次数        2
交易金额      495
Name: 8321, dtype: int64
内部标识号    8323
交易次数        2
交易金额      324
Name: 8322, dtype: int64
内部标识号    8324
交易次数        2
交易金额      720
Name: 8323, dtype: int64
内部标识号    8325
交易次数        2
交易金额      505
Name: 8324, dtype: int64
内部标识号    8326
交易次数        3
交易金额      243
Name: 8325, dtype: int64
内部标识号    8327
交易次数        5
交易金额      131
Name: 8326, dtype: int64
内部标识号    8328
交易次数        8
交易金额      230
Name: 8327, dtype: int64
内部标识号    8329
交易次数       11
交易金额      588
Name: 8328, dtype: int64
内部标识号    8330
交易次数       11
交易金额      376
Name: 8329, dtype: int64
内部标识号    8331
交易次数        9
交易金额      875
Name: 8330, dtype: int64
内部标识号    8332
交易次数        4
交易金额      242
Name: 8331, dtype: int64
内部标识号    8333
交易次数        2
交易金额      418
Name: 8332, dtype: int64
内部标识号    8334
交易次数        1
交易金额     8296
Name: 8333, dtype: int64
内部标识号    8335
交易次数        5
交易金额      211
Name: 8334, dtype: int64
内部标识号    8336
交易次数        4
交易金额      182
Name: 8335, dtype: int64
内部标识号    8337
交易次数        2
交易金额      681
Name: 8336, dtype: int64
内部标识号    8338
交易次数       10
交易金额      666
Name: 8337, dtype: int64
内部标识号    8339
交易次数        0
交易金额     1295
Name: 8338, dtype: int64
内部标识号    8340
交易次数        2
交易金额      608
Name: 8339, dtype: int64
内部标识号    8341
交易次数        2
交易金额      330
Name: 8340, dtype: int64
内部标识号    8342
交易次数        2
交易金额      513
Name: 8341, dtype: int64
内部标识号    8343
交易次数        2
交易金额      425
Name: 8342, dtype: int64
内部标识号    8344
交易次数       13
交易金额      404
Name: 8343, dtype: int64
内部标识号    8345
交易次数        2
交易金额      535
Name: 8344, dtype: int64
内部标识号    8346
交易次数        0
交易金额     8183
Name: 8345, dtype: int64
内部标识号    8347
交易次数        1
交易金额     7773
Name: 8346, dtype: int64
内部标识号    8348
交易次数       24
交易金额      546
Name: 8347, dtype: int64
内部标识号    8349
交易次数        4
交易金额      191
Name: 8348, dtype: int64
内部标识号    8350
交易次数       28
交易金额     3488
Name: 8349, dtype: int64
内部标识号    8351
交易次数        7
交易金额      182
Name: 8350, dtype: int64
内部标识号    8352
交易次数        4
交易金额      225
Name: 8351, dtype: int64
内部标识号    8353
交易次数       13
交易金额      711
Name: 8352, dtype: int64
内部标识号    8354
交易次数        4
交易金额      209
Name: 8353, dtype: int64
内部标识号    8355
交易次数        0
交易金额     2252
Name: 8354, dtype: int64
内部标识号    8356
交易次数        0
交易金额     6484
Name: 8355, dtype: int64
内部标识号     8357
交易次数         5
交易金额     40485
Name: 8356, dtype: int64
内部标识号    8358
交易次数        2
交易金额      734
Name: 8357, dtype: int64
内部标识号    8359
交易次数       24
交易金额     1503
Name: 8358, dtype: int64
内部标识号    8360
交易次数        2
交易金额      510
Name: 8359, dtype: int64
内部标识号    8361
交易次数       15
交易金额      525
Name: 8360, dtype: int64
内部标识号    8362
交易次数        2
交易金额      200
Name: 8361, dtype: int64
内部标识号    8363
交易次数       14
交易金额      340
Name: 8362, dtype: int64
内部标识号    8364
交易次数       11
交易金额      356
Name: 8363, dtype: int64
内部标识号    8365
交易次数       14
交易金额      900
Name: 8364, dtype: int64
内部标识号    8366
交易次数       21
交易金额      777
Name: 8365, dtype: int64
内部标识号    8367
交易次数        2
交易金额      334
Name: 8366, dtype: int64
内部标识号    8368
交易次数       10
交易金额      816
Name: 8367, dtype: int64
内部标识号    8369
交易次数       25
交易金额      707
Name: 8368, dtype: int64
内部标识号    8370
交易次数       14
交易金额      643
Name: 8369, dtype: int64
内部标识号    8371
交易次数       21
交易金额      830
Name: 8370, dtype: int64
内部标识号    8372
交易次数        8
交易金额      690
Name: 8371, dtype: int64
内部标识号    8373
交易次数        5
交易金额      133
Name: 8372, dtype: int64
内部标识号    8374
交易次数        1
交易金额     7048
Name: 8373, dtype: int64
内部标识号    8375
交易次数        0
交易金额     1334
Name: 8374, dtype: int64
内部标识号    8376
交易次数       17
交易金额      880
Name: 8375, dtype: int64
内部标识号     8377
交易次数         5
交易金额     47875
Name: 8376, dtype: int64
内部标识号    8378
交易次数        2
交易金额      153
Name: 8377, dtype: int64
内部标识号    8379
交易次数       10
交易金额      354
Name: 8378, dtype: int64
内部标识号    8380
交易次数        2
交易金额      453
Name: 8379, dtype: int64
内部标识号     8381
交易次数       144
交易金额     68448
Name: 8380, dtype: int64
内部标识号    8382
交易次数       15
交易金额      315
Name: 8381, dtype: int64
内部标识号    8383
交易次数        2
交易金额      992
Name: 8382, dtype: int64
内部标识号    8384
交易次数        7
交易金额      300
Name: 8383, dtype: int64
内部标识号    8385
交易次数       16
交易金额      500
Name: 8384, dtype: int64
内部标识号    8386
交易次数       15
交易金额      878
Name: 8385, dtype: int64
内部标识号    8387
交易次数       11
交易金额      679
Name: 8386, dtype: int64
内部标识号    8388
交易次数       27
交易金额       14
Name: 8387, dtype: int64
内部标识号    8389
交易次数       13
交易金额      893
Name: 8388, dtype: int64
内部标识号    8390
交易次数       25
交易金额     3769
Name: 8389, dtype: int64
内部标识号    8391
交易次数        3
交易金额      342
Name: 8390, dtype: int64
内部标识号    8392
交易次数       25
交易金额     4716
Name: 8391, dtype: int64
内部标识号    8393
交易次数        0
交易金额     3372
Name: 8392, dtype: int64
内部标识号    8394
交易次数        5
交易金额      232
Name: 8393, dtype: int64
内部标识号    8395
交易次数        7
交易金额      189
Name: 8394, dtype: int64
内部标识号    8396
交易次数       15
交易金额      344
Name: 8395, dtype: int64
内部标识号    8397
交易次数        2
交易金额      449
Name: 8396, dtype: int64
内部标识号    8398
交易次数       10
交易金额      376
Name: 8397, dtype: int64
内部标识号    8399
交易次数        5
交易金额      257
Name: 8398, dtype: int64
内部标识号    8400
交易次数       12
交易金额      445
Name: 8399, dtype: int64
内部标识号    8401
交易次数        0
交易金额     1742
Name: 8400, dtype: int64
内部标识号    8402
交易次数        5
交易金额      114
Name: 8401, dtype: int64
内部标识号    8403
交易次数        0
交易金额     2492
Name: 8402, dtype: int64
内部标识号    8404
交易次数        8
交易金额      384
Name: 8403, dtype: int64
内部标识号    8405
交易次数        6
交易金额      208
Name: 8404, dtype: int64
内部标识号     8406
交易次数       113
交易金额     23340
Name: 8405, dtype: int64
内部标识号    8407
交易次数        1
交易金额      889
Name: 8406, dtype: int64
内部标识号    8408
交易次数       10
交易金额      370
Name: 8407, dtype: int64
内部标识号     8409
交易次数       178
交易金额     20771
Name: 8408, dtype: int64
内部标识号    8410
交易次数       21
交易金额       32
Name: 8409, dtype: int64
内部标识号    8411
交易次数        9
交易金额      332
Name: 8410, dtype: int64
内部标识号    8412
交易次数       22
交易金额     1496
Name: 8411, dtype: int64
内部标识号     8413
交易次数         4
交易金额     23849
Name: 8412, dtype: int64
内部标识号    8414
交易次数       11
交易金额      469
Name: 8413, dtype: int64
内部标识号    8415
交易次数        1
交易金额      892
Name: 8414, dtype: int64
内部标识号     8416
交易次数       242
交易金额     70991
Name: 8415, dtype: int64
内部标识号    8417
交易次数        3
交易金额      381
Name: 8416, dtype: int64
内部标识号    8418
交易次数        2
交易金额      474
Name: 8417, dtype: int64
内部标识号    8419
交易次数       15
交易金额      538
Name: 8418, dtype: int64
内部标识号    8420
交易次数        9
交易金额      425
Name: 8419, dtype: int64
内部标识号    8421
交易次数       13
交易金额      725
Name: 8420, dtype: int64
内部标识号    8422
交易次数       12
交易金额      676
Name: 8421, dtype: int64
内部标识号    8423
交易次数       26
交易金额     6265
Name: 8422, dtype: int64
内部标识号    8424
交易次数       10
交易金额      696
Name: 8423, dtype: int64
内部标识号    8425
交易次数       12
交易金额      396
Name: 8424, dtype: int64
内部标识号    8426
交易次数        1
交易金额     1732
Name: 8425, dtype: int64
内部标识号    8427
交易次数        8
交易金额      914
Name: 8426, dtype: int64
内部标识号    8428
交易次数        9
交易金额      323
Name: 8427, dtype: int64
内部标识号    8429
交易次数       28
交易金额      530
Name: 8428, dtype: int64
内部标识号    8430
交易次数       18
交易金额       58
Name: 8429, dtype: int64
内部标识号     8431
交易次数         5
交易金额     89231
Name: 8430, dtype: int64
内部标识号    8432
交易次数        0
交易金额     7643
Name: 8431, dtype: int64
内部标识号    8433
交易次数        3
交易金额      258
Name: 8432, dtype: int64
内部标识号    8434
交易次数       30
交易金额      529
Name: 8433, dtype: int64
内部标识号    8435
交易次数       10
交易金额      345
Name: 8434, dtype: int64
内部标识号    8436
交易次数        3
交易金额      425
Name: 8435, dtype: int64
内部标识号    8437
交易次数       13
交易金额      820
Name: 8436, dtype: int64
内部标识号    8438
交易次数        4
交易金额      251
Name: 8437, dtype: int64
内部标识号    8439
交易次数       27
交易金额     1509
Name: 8438, dtype: int64
内部标识号    8440
交易次数        8
交易金额      684
Name: 8439, dtype: int64
内部标识号    8441
交易次数        3
交易金额      261
Name: 8440, dtype: int64
内部标识号    8442
交易次数       20
交易金额     7544
Name: 8441, dtype: int64
内部标识号    8443
交易次数       12
交易金额      331
Name: 8442, dtype: int64
内部标识号    8444
交易次数       15
交易金额      946
Name: 8443, dtype: int64
内部标识号    8445
交易次数       20
交易金额     9075
Name: 8444, dtype: int64
内部标识号    8446
交易次数        2
交易金额      347
Name: 8445, dtype: int64
内部标识号    8447
交易次数       13
交易金额      314
Name: 8446, dtype: int64
内部标识号    8448
交易次数        3
交易金额      326
Name: 8447, dtype: int64
内部标识号    8449
交易次数        8
交易金额      253
Name: 8448, dtype: int64
内部标识号    8450
交易次数        4
交易金额      269
Name: 8449, dtype: int64
内部标识号    8451
交易次数       16
交易金额     9165
Name: 8450, dtype: int64
内部标识号    8452
交易次数        8
交易金额      287
Name: 8451, dtype: int64
内部标识号    8453
交易次数       12
交易金额      495
Name: 8452, dtype: int64
内部标识号    8454
交易次数        2
交易金额      306
Name: 8453, dtype: int64
内部标识号    8455
交易次数        0
交易金额     8756
Name: 8454, dtype: int64
内部标识号    8456
交易次数       22
交易金额      862
Name: 8455, dtype: int64
内部标识号    8457
交易次数       11
交易金额      424
Name: 8456, dtype: int64
内部标识号    8458
交易次数        0
交易金额     1035
Name: 8457, dtype: int64
内部标识号    8459
交易次数        9
交易金额      512
Name: 8458, dtype: int64
内部标识号    8460
交易次数        2
交易金额      714
Name: 8459, dtype: int64
内部标识号    8461
交易次数       13
交易金额      574
Name: 8460, dtype: int64
内部标识号     8462
交易次数         8
交易金额     69716
Name: 8461, dtype: int64
内部标识号    8463
交易次数        9
交易金额      646
Name: 8462, dtype: int64
内部标识号    8464
交易次数        0
交易金额     8061
Name: 8463, dtype: int64
内部标识号    8465
交易次数       19
交易金额     7338
Name: 8464, dtype: int64
内部标识号    8466
交易次数        9
交易金额      671
Name: 8465, dtype: int64
内部标识号    8467
交易次数        1
交易金额      852
Name: 8466, dtype: int64
内部标识号    8468
交易次数        1
交易金额      751
Name: 8467, dtype: int64
内部标识号    8469
交易次数        4
交易金额      221
Name: 8468, dtype: int64
内部标识号    8470
交易次数        8
交易金额      155
Name: 8469, dtype: int64
内部标识号    8471
交易次数        8
交易金额      214
Name: 8470, dtype: int64
内部标识号    8472
交易次数        3
交易金额      144
Name: 8471, dtype: int64
内部标识号     8473
交易次数         3
交易金额     21956
Name: 8472, dtype: int64
内部标识号    8474
交易次数       21
交易金额     5623
Name: 8473, dtype: int64
内部标识号     8475
交易次数         7
交易金额     50463
Name: 8474, dtype: int64
内部标识号    8476
交易次数        8
交易金额      389
Name: 8475, dtype: int64
内部标识号    8477
交易次数       14
交易金额      384
Name: 8476, dtype: int64
内部标识号    8478
交易次数        7
交易金额      100
Name: 8477, dtype: int64
内部标识号    8479
交易次数        2
交易金额      414
Name: 8478, dtype: int64
内部标识号    8480
交易次数       15
交易金额      317
Name: 8479, dtype: int64
内部标识号    8481
交易次数        7
交易金额      209
Name: 8480, dtype: int64
内部标识号    8482
交易次数       17
交易金额      500
Name: 8481, dtype: int64
内部标识号    8483
交易次数        2
交易金额      611
Name: 8482, dtype: int64
内部标识号    8484
交易次数        2
交易金额      128
Name: 8483, dtype: int64
内部标识号    8485
交易次数       10
交易金额      670
Name: 8484, dtype: int64
内部标识号    8486
交易次数        8
交易金额      639
Name: 8485, dtype: int64
内部标识号    8487
交易次数        2
交易金额      788
Name: 8486, dtype: int64
内部标识号    8488
交易次数        5
交易金额      119
Name: 8487, dtype: int64
内部标识号    8489
交易次数        2
交易金额      322
Name: 8488, dtype: int64
内部标识号    8490
交易次数       10
交易金额      902
Name: 8489, dtype: int64
内部标识号    8491
交易次数        8
交易金额      504
Name: 8490, dtype: int64
内部标识号    8492
交易次数        2
交易金额      456
Name: 8491, dtype: int64
内部标识号    8493
交易次数        4
交易金额      259
Name: 8492, dtype: int64
内部标识号    8494

内部标识号    8498
交易次数        1
交易金额     5555
Name: 8497, dtype: int64
内部标识号    8499
交易次数       15
交易金额      770
Name: 8498, dtype: int64
内部标识号    8500
交易次数       19
交易金额     3813
Name: 8499, dtype: int64
内部标识号    8501
交易次数       13
交易金额      396
Name: 8500, dtype: int64
内部标识号    8502
交易次数        5
交易金额      199
Name: 8501, dtype: int64
内部标识号    8503
交易次数       15
交易金额      685
Name: 8502, dtype: int64
内部标识号    8504
交易次数       11
交易金额      467
Name: 8503, dtype: int64
内部标识号    8505
交易次数        2
交易金额      846
Name: 8504, dtype: int64
内部标识号    8506
交易次数       14
交易金额      324
Name: 8505, dtype: int64
内部标识号    8507
交易次数       18
交易金额     6705
Name: 8506, dtype: int64
内部标识号    8508
交易次数       13
交易金额      592
Name: 8507, dtype: int64
内部标识号    8509
交易次数       19
交易金额     9918
Name: 8508, dtype: int64
内部标识号    8510
交易次数        3
交易金额      290
Name: 8509, dtype: int64
内部标识号    8511
交易次数        3
交易金额      242
Name: 8510, dtype: int64
内部标识号    8512
交易次数       30
交易金额     5726
Name: 8511, dtype: int64
内部标识号    8513
交易次数       10
交易金额      415
Name: 8512, dtype: int64
内部标识号    8514
交易次数       17
交易金额     1455
Name: 8513, dtype: int64
内部标识号    8515
交易次数       15
交易金额      946
Name: 8514, dtype: int64
内部标识号    8516
交易次数        2
交易金额      456
Name: 8515, dtype: int64
内部标识号    8517
交易次数        2
交易金额      812
Name: 8516, dtype: int64
内部标识号     8518
交易次数         6
交易金额     42508
Name: 8517, dtype: int64
内部标识号    8519
交易次数       14
交易金额      959
Name: 8518, dtype: int64
内部标识号    8520
交易次数        2
交易金额      496
Name: 8519, dtype: int64
内部标识号    8521
交易次数       26
交易金额      640
Name: 8520, dtype: int64
内部标识号    8522
交易次数        6
交易金额      140
Name: 8521, dtype: int64
内部标识号    8523
交易次数        0
交易金额     9894
Name: 8522, dtype: int64
内部标识号    8524
交易次数        3
交易金额      470
Name: 8523, dtype: int64
内部标识号    8525
交易次数        1
交易金额      555
Name: 8524, dtype: int64
内部标识号    8526
交易次数        7
交易金额      244
Name: 8525, dtype: int64
内部标识号    8527
交易次数        2
交易金额      497
Name: 8526, dtype: int64
内部标识号    8528
交易次数       12
交易金额      314
Name: 8527, dtype: int64
内部标识号    8529
交易次数        3
交易金额      224
Name: 8528, dtype: int64
内部标识号    8530
交易次数        2
交易金额      846
Name: 8529, dtype: int64
内部标识号     8531
交易次数         3
交易金额     90952
Name: 8530, dtype: int64
内部标识号    8532
交易次数        3
交易金额      328
Name: 8531, dtype: int64
内部标识号    8533
交易次数        3
交易金额      145
Name: 8532, dtype: int64
内部标识号    8534
交易次数       11
交易金额      956
Name: 8533, dtype: int64
内部标识号    8535
交易次数       13
交易金额      784
Name: 8534, dtype: int64
内部标识号    8536
交易次数        0
交易金额     8581
Name: 8535, dtype: int64
内部标识号    8537
交易次数        8
交易金额      337
Name: 8536, dtype: int64
内部标识号    8538
交易次数       25
交易金额     5916
Name: 8537, dtype: int64
内部标识号    8539
交易次数        6
交易金额      228
Name: 8538, dtype: int64
内部标识号    8540
交易次数        2
交易金额      754
Name: 8539, dtype: int64
内部标识号    8541
交易次数        8
交易金额      423
Name: 8540, dtype: int64
内部标识号    8542
交易次数       25
交易金额     6788
Name: 8541, dtype: int64
内部标识号    8543
交易次数       10
交易金额      718
Name: 8542, dtype: int64
内部标识号    8544
交易次数        1
交易金额      699
Name: 8543, dtype: int64
内部标识号    8545
交易次数       30
交易金额      728
Name: 8544, dtype: int64
内部标识号    8546
交易次数        3
交易金额      209
Name: 8545, dtype: int64
内部标识号    8547
交易次数        1
交易金额      539
Name: 8546, dtype: int64
内部标识号    8548
交易次数        0
交易金额     3991
Name: 8547, dtype: int64
内部标识号    8549
交易次数       12
交易金额      812
Name: 8548, dtype: int64
内部标识号    8550
交易次数        7
交易金额      108
Name: 8549, dtype: int64
内部标识号    8551
交易次数        1
交易金额     2062
Name: 8550, dtype: int64
内部标识号    8552
交易次数        0
交易金额     2280
Name: 8551, dtype: int64
内部标识号    8553
交易次数        1
交易金额      767
Name: 8552, dtype: int64
内部标识号    8554
交易次数       22
交易金额     2460
Name: 8553, dtype: int64
内部标识号    8555
交易次数       28
交易金额     3665
Name: 8554, dtype: int64
内部标识号    8556
交易次数        1
交易金额     1151
Name: 8555, dtype: int64
内部标识号    8557
交易次数        2
交易金额      874
Name: 8556, dtype: int64
内部标识号    8558
交易次数        7
交易金额      298
Name: 8557, dtype: int64
内部标识号    8559
交易次数        6
交易金额      244
Name: 8558, dtype: int64
内部标识号    8560
交易次数        2
交易金额      374
Name: 8559, dtype: int64
内部标识号    8561
交易次数        3
交易金额      116
Name: 8560, dtype: int64
内部标识号    8562
交易次数        4
交易金额      227
Name: 8561, dtype: int64
内部标识号    8563
交易次数       25
交易金额       83
Name: 8562, dtype: int64
内部标识号    8564
交易次数        3
交易金额      319
Name: 8563, dtype: int64
内部标识号    8565
交易次数        3
交易金额      291
Name: 8564, dtype: int64
内部标识号    8566
交易次数        2
交易金额      462
Name: 8565, dtype: int64
内部标识号    8567
交易次数       11
交易金额      793
Name: 8566, dtype: int64
内部标识号    8568
交易次数        2
交易金额      409
Name: 8567, dtype: int64
内部标识号    8569
交易次数        1
交易金额     5699
Name: 8568, dtype: int64
内部标识号    8570
交易次数        5
交易金额      230
Name: 8569, dtype: int64
内部标识号    8571
交易次数        0
交易金额     2835
Name: 8570, dtype: int64
内部标识号    8572
交易次数       25
交易金额      907
Name: 8571, dtype: int64
内部标识号    8573
交易次数        9
交易金额      444
Name: 8572, dtype: int64
内部标识号    8574
交易次数        3
交易金额      451
Name: 8573, dtype: int64
内部标识号    8575
交易次数        2
交易金额      344
Name: 8574, dtype: int64
内部标识号    8576
交易次数        1
交易金额     1197
Name: 8575, dtype: int64
内部标识号     8577
交易次数       234
交易金额     60365
Name: 8576, dtype: int64
内部标识号    8578
交易次数        8
交易金额      693
Name: 8577, dtype: int64
内部标识号    8579
交易次数        3
交易金额      176
Name: 8578, dtype: int64
内部标识号    8580
交易次数        1
交易金额     7831
Name: 8579, dtype: int64
内部标识号    8581
交易次数        2
交易金额      710
Name: 8580, dtype: int64
内部标识号    8582
交易次数       27
交易金额     4282
Name: 8581, dtype: int64
内部标识号    8583
交易次数        8
交易金额      256
Name: 8582, dtype: int64
内部标识号    8584
交易次数       22
交易金额     7433
Name: 8583, dtype: int64
内部标识号    8585
交易次数        0
交易金额     5610
Name: 8584, dtype: int64
内部标识号    8586
交易次数        5
交易金额      158
Name: 8585, dtype: int64
内部标识号     8587
交易次数       264
交易金额     59497
Name: 8586, dtype: int64
内部标识号    8588
交易次数       14
交易金额      913
Name: 8587, dtype: int64
内部标识号     8589
交易次数         7
交易金额     63824
Name: 8588, dtype: int64
内部标识号    8590
交易次数       28
交易金额     3830
Name: 8589, dtype: int64
内部标识号    8591
交易次数       14
交易金额      656
Name: 8590, dtype: int64
内部标识号    8592
交易次数       25
交易金额     5713
Name: 8591, dtype: int64
内部标识号    8593
交易次数        7
交易金额      170
Name: 8592, dtype: int64
内部标识号     8594
交易次数         6
交易金额     54961
Name: 8593, dtype: int64
内部标识号    8595
交易次数       11
交易金额      525
Name: 8594, dtype: int64
内部标识号    8596
交易次数        8
交易金额      133
Name: 8595, dtype: int64
内部标识号     8597
交易次数         3
交易金额     47874
Name: 8596, dtype: int64
内部标识号    8598
交易次数        3
交易金额      481
Name: 8597, dtype: int64
内部标识号    8599
交易次数        9
交易金额      659
Name: 8598, dtype: int64
内部标识号     8600
交易次数         4
交易金额     36737
Name: 8599, dtype: int64
内部标识号    8601
交易次数       15
交易金额      555
Name: 8600, dtype: int64
内部标识号    8602
交易次数       13
交易金额      368
Name: 8601, dtype: int64
内部标识号    8603
交易次数       13
交易金额      571
Name: 8602, dtype: int64
内部标识号    8604
交易次数       22
交易金额     8525
Name: 8603, dtype: int64
内部标识号    8605
交易次数       10
交易金额      370
Name: 8604, dtype: int64
内部标识号    8606
交易次数        6
交易金额      129
Name: 8605, dtype: int64
内部标识号    8607
交易次数       10
交易金额      662
Name: 8606, dtype: int64
内部标识号    8608
交易次数        7
交易金额      119
Name: 8607, dtype: int64
内部标识号    8609
交易次数        2
交易金额      476
Name: 8608, dtype: int64
内部标识号    8610
交易次数        1
交易金额     1910
Name: 8609, dtype: int64
内部标识号    8611
交易次数        2
交易金额      636
Name: 8610, dtype: int64
内部标识号     8612
交易次数         6
交易金额     68406
Name: 8611, dtype: int64
内部标识号    8613
交易次数       13
交易金额      938
Name: 8612, dtype: int64
内部标识号     8614
交易次数         5
交易金额     87412
Name: 8613, dtype: int64
内部标识号     8615
交易次数         4
交易金额     41307
Name: 8614, dtype: int64
内部标识号    8616
交易次数        2
交易金额      526
Name: 8615, dtype: int64
内部标识号    8617
交易次数        1
交易金额     9591
Name: 8616, dtype: int64
内部标识号    8618
交易次数       14
交易金额      318
Name: 8617, dtype: int64
内部标识号    8619
交易次数        3
交易金额      460
Name: 8618, dtype: int64
内部标识号    8620
交易次数       11
交易金额      880
Name: 8619, dtype: int64
内部标识号     8621
交易次数         3
交易金额     66435
Name: 8620, dtype: int64
内部标识号    8622
交易次数        1
交易金额      501
Name: 8621, dtype: int64
内部标识号    8623
交易次数        3
交易金额      363
Name: 8622, dtype: int64
内部标识号    8624
交易次数        9
交易金额      507
Name: 8623, dtype: int64
内部标识号     8625
交易次数         8
交易金额     75533
Name: 8624, dtype: int64
内部标识号    8626
交易次数       15
交易金额     4304
Name: 8625, dtype: int64
内部标识号    8627
交易次数        8
交易金额      217
Name: 8626, dtype: int64
内部标识号     8628
交易次数         7
交易金额     32792
Name: 8627, dtype: int64
内部标识号    8629
交易次数        3
交易金额      171
Name: 8628, dtype: int64
内部标识号    8630
交易次数        9
交易金额      658
Name: 8629, dtype: int64
内部标识号    8631
交易次数        8
交易金额      128
Name: 8630, dtype: int64
内部标识号    8632
交易次数       14
交易金额      634
Name: 8631, dtype: int64
内部标识号    8633
交易次数        0
交易金额     2396
Name: 8632, dtype: int64
内部标识号    8634
交易次数        8
交易金额      739
Name: 8633, dtype: int64
内部标识号    8635
交易次数       12
交易金额      651
Name: 8634, dtype: int64
内部标识号    8636
交易次数        2
交易金额      412
Name: 8635, dtype: int64
内部标识号    8637
交易次数        2
交易金额      584
Name: 8636, dtype: int64
内部标识号    8638
交易次数        5
交易金额      214
Name: 8637, dtype: int64
内部标识号    8639
交易次数        9
交易金额      331
Name: 8638, dtype: int64
内部标识号    8640
交易次数        7
交易金额      169
Name: 8639, dtype: int64
内部标识号    8641
交易次数       12
交易金额      772
Name: 8640, dtype: int64
内部标识号    8642
交易次数       15
交易金额      532
Name: 8641, dtype: int64
内部标识号    8643
交易次数        8
交易金额      871
Name: 8642, dtype: int64
内部标识号     8644
交易次数         6
交易金额     76396
Name: 8643, dtype: int64
内部标识号    8645
交易次数       14
交易金额      949
Name: 8644, dtype: int64
内部标识号    8646
交易次数        2
交易金额      366
Name: 8645, dtype: int64
内部标识号    8647
交易次数       23
交易金额      933
Name: 8646, dtype: int64
内部标识号    8648
交易次数       16
交易金额      726
Name: 8647, dtype: int64
内部标识号    8649
交易次数        1
交易金额     6053
Name: 8648, dtype: int64
内部标识号    8650
交易次数        4
交易金额      220
Name: 8649, dtype: int64
内部标识号    8651
交易次数        1
交易金额      815
Name: 8650, dtype: int64
内部标识号    8652
交易次数        7
交易金额      195
Name: 8651, dtype: int64
内部标识号    8653
交易次数       15
交易金额      705
Name: 8652, dtype: int64
内部标识号    8654
交易次数        1
交易金额      507
Name: 8653, dtype: int64
内部标识号    8655
交易次数        1
交易金额      533
Name: 8654, dtype: int64
内部标识号    8656
交易次数        6
交易金额      258
Name: 8655, dtype: int64
内部标识号    8657
交易次数        9
交易金额      713
Name: 8656, dtype: int64
内部标识号    8658
交易次数        8
交易金额      380
Name: 8657, dtype: int64
内部标识号    8659
交易次数        9
交易金额      376
Name: 8658, dtype: int64
内部标识号    8660
交易次数        1
交易金额      989
Name: 8659, dtype: int64
内部标识号    8661
交易次数       11
交易金额      584
Name: 8660, dtype: int64
内部标识号    8662
交易次数        7
交易金额      249
Name: 8661, dtype: int64
内部标识号    8663
交易次数       11
交易金额      318
Name: 8662, dtype: int64
内部标识号    8664
交易次数       13
交易金额      386
Name: 8663, dtype: int64
内部标识号    8665
交易次数       11
交易金额      320
Name: 8664, dtype: int64
内部标识号     8666
交易次数       227
交易金额     64835
Name: 8665, dtype: int64
内部标识号    8667
交易次数        2
交易金额      668
Name: 8666, dtype: int64
内部标识号    8668
交易次数       20
交易金额     4444
Name: 8667, dtype: int64
内部标识号    8669
交易次数        1
交易金额     1000
Name: 8668, dtype: int64
内部标识号    8670
交易次数       16
交易金额     8296
Name: 8669, dtype: int64
内部标识号    8671
交易次数        3
交易金额      456
Name: 8670, dtype: int64
内部标识号    8672
交易次数        4
交易金额      104
Name: 8671, dtype: int64
内部标识号     8673
交易次数         7
交易金额     61359
Name: 8672, dtype: int64
内部标识号    8674
交易次数        3
交易金额      426
Name: 8673, dtype: int64
内部标识号    8675
交易次数        3
交易金额      162
Name: 8674, dtype: int64
内部标识号     8676
交易次数         7
交易金额     52133
Name: 8675, dtype: int64
内部标识号     8677
交易次数       170
交易金额     22765
Name: 8676, dtype: int64
内部标识号    8678
交易次数       22
交易金额      988
Name: 8677, dtype: int64
内部标识号    8679
交易次数        0
交易金额     3182
Name: 8678, dtype: int64
内部标识号    8680
交易次数        2
交易金额      289
Name: 8679, dtype: int64
内部标识号     8681
交易次数        78
交易金额     31366
Name: 8680, dtype: int64
内部标识号    8682
交易次数        2
交易金额      439
Name: 8681, dtype: int64
内部标识号    8683
交易次数        1
交易金额      533
Name: 8682, dtype: int64
内部标识号    8684
交易次数        3
交易金额      234
Name: 8683, dtype: int64
内部标识号    8685
交易次数        0
交易金额     8736
Name: 8684, dtype: int64
内部标识号    8686
交易次数        2
交易金额      311
Name: 8685, dtype: int64
内部标识号    8687
交易次数        5
交易金额      103
Name: 8686, dtype: int64
内部标识号    8688
交易次数        7
交易金额      122
Name: 8687, dtype: int64
内部标识号    8689
交易次数        2
交易金额      572
Name: 8688, dtype: int64
内部标识号    8690
交易次数        8
交易金额      150
Name: 8689, dtype: int64
内部标识号    8691
交易次数        5
交易金额      262
Name: 8690, dtype: int64
内部标识号    8692
交易次数        1
交易金额      640
Name: 8691, dtype: int64
内部标识号    8693
交易次数        0
交易金额     6114
Name: 8692, dtype: int64
内部标识号     8694
交易次数         3
交易金额     60787
Name: 8693, dtype: int64
内部标识号    8695
交易次数       11
交易金额      770
Name: 8694, dtype: int64
内部标识号    8696
交易次数       18
交易金额      575
Name: 8695, dtype: int64
内部标识号    8697
交易次数       19
交易金额       68
Name: 8696, dtype: int64
内部标识号    8698
交易次数        0
交易金额     5522
Name: 8697, dtype: int64
内部标识号    8699
交易次数        2
交易金额      379
Name: 8698, dtype: int64
内部标识号    8700
交易次数        5
交易金额      118
Name: 8699, dtype: int64
内部标识号    8701
交易次数        2
交易金额      364
Name: 8700, dtype: int64
内部标识号    8702
交易次数        0
交易金额     7732
Name: 8701, dtype: int64
内部标识号    8703
交易次数        8
交易金额      153
Name: 8702, dtype: int64
内部标识号    8704
交易次数        2
交易金额      764
Name: 8703, dtype: int64
内部标识号    8705
交易次数       15
交易金额      698
Name: 8704, dtype: int64
内部标识号    8706
交易次数        3
交易金额      339
Name: 8705, dtype: int64
内部标识号    8707
交易次数        9
交易金额      450
Name: 8706, dtype: int64
内部标识号     8708
交易次数       103
交易金额     60055
Name: 8707, dtype: int64
内部标识号    8709
交易次数       27
交易金额     2566
Name: 8708, dtype: int64
内部标识号    8710
交易次数        1
交易金额     7468
Name: 8709, dtype: int64
内部标识号    8711
交易次数        9
交易金额      472
Name: 8710, dtype: int64
内部标识号    8712
交易次数        8
交易金额      936
Name: 8711, dtype: int64
内部标识号    8713
交易次数        3
交易金额      208
Name: 8712, dtype: int64
内部标识号    8714
交易次数        2
交易金额      487
Name: 8713, dtype: int64
内部标识号    8715
交易次数        8
交易金额      256
Name: 8714, dtype: int64
内部标识号    8716
交易次数       11
交易金额      677
Name: 8715, dtype: int64
内部标识号    8717
交易次数       11
交易金额      989
Name: 8716, dtype: int64
内部标识号    8718
交易次数        9
交易金额      794
Name: 8717, dtype: int64
内部标识号     8719
交易次数         8
交易金额     42173
Name: 8718, dtype: int64
内部标识号    8720
交易次数        8
交易金额      395
Name: 8719, dtype: int64
内部标识号    8721
交易次数       13
交易金额      515
Name: 8720, dtype: int64
内部标识号    8722
交易次数       28
交易金额     8473
Name: 8721, dtype: int64
内部标识号    8723
交易次数        0
交易金额     7679
Name: 8722, dtype: int64
内部标识号    8724
交易次数        2
交易金额      521
Name: 8723, dtype: int64
内部标识号    8725
交易次数       11
交易金额      366
Name: 8724, dtype: int64
内部标识号    8726
交易次数        4
交易金额      126
Name: 8725, dtype: int64
内部标识号    8727
交易次数       15
交易金额      995
Name: 8726, dtype: int64
内部标识号    8728
交易次数       13
交易金额      692
Name: 8727, dtype: int64
内部标识号    8729
交易次数       15
交易金额      512
Name: 8728, dtype: int64
内部标识号    8730
交易次数       19
交易金额     9204
Name: 8729, dtype: int64
内部标识号    8731
交易次数       17
交易金额     4016
Name: 8730, dtype: int64
内部标识号    8732
交易次数        2
交易金额      435
Name: 8731, dtype: int64
内部标识号    8733
交易次数        9
交易金额      993
Name: 8732, dtype: int64
内部标识号    8734
交易次数        9
交易金额      917
Name: 8733, dtype: int64
内部标识号    8735
交易次数        2
交易金额      451
Name: 8734, dtype: int64
内部标识号    8736
交易次数       13
交易金额      397
Name: 8735, dtype: int64
内部标识号    8737
交易次数       11
交易金额      584
Name: 8736, dtype: int64
内部标识号    8738
交易次数       14
交易金额      564
Name: 8737, dtype: int64
内部标识号    8739
交易次数        1
交易金额      562
Name: 8738, dtype: int64
内部标识号    8740
交易次数        8
交易金额      212
Name: 8739, dtype: int64
内部标识号    8741
交易次数       17
交易金额     8398
Name: 8740, dtype: int64
内部标识号    8742
交易次数        2
交易金额      420
Name: 8741, dtype: int64
内部标识号    8743
交易次数       25
交易金额      636
Name: 8742, dtype: int64
内部标识号    8744
交易次数        2
交易金额      335
Name: 8743, dtype: int64
内部标识号    8745
交易次数        3
交易金额      323
Name: 8744, dtype: int64
内部标识号    8746
交易次数       26
交易金额     1833
Name: 8745, dtype: int64
内部标识号    8747
交易次数        9
交易金额      748
Name: 8746, dtype: int64
内部标识号     8748
交易次数       296
交易金额     65279
Name: 8747, dtype: int64
内部标识号    8749
交易次数        2
交易金额      376
Name: 8748, dtype: int64
内部标识号    8750
交易次数        8
交易金额      120
Name: 8749, dtype: int64
内部标识号    8751
交易次数        2
交易金额      899
Name: 8750, dtype: int64
内部标识号    8752
交易次数        1
交易金额     5705
Name: 8751, dtype: int64
内部标识号    8753
交易次数        1
交易金额     9924
Name: 8752, dtype: int64
内部标识号    8754
交易次数        1
交易金额     2568
Name: 8753, dtype: int64
内部标识号     8755
交易次数        93
交易金额     69237
Name: 8754, dtype: int64
内部标识号     8756
交易次数       174
交易金额     43614
Name: 8755, dtype: int64
内部标识号    8757
交易次数        7
交易金额      291
Name: 8756, dtype: int64
内部标识号    8758
交易次数        8
交易金额      426
Name: 8757, dtype: int64
内部标识号    8759
交易次数       14
交易金额      363
Name: 8758, dtype: int64
内部标识号    8760
交易次数       12
交易金额      431
Name: 8759, dtype: int64
内部标识号    8761
交易次数        3
交易金额      478
Name: 8760, dtype: int64
内部标识号    8762
交易次数        8
交易金额      108
Name: 8761, dtype: int64
内部标识号    8763
交易次数        3
交易金额      409
Name: 8762, dtype: int64
内部标识号    8764
交易次数       14
交易金额      611
Name: 8763, dtype: int64

内部标识号    8765
交易次数        0
交易金额     3675
Name: 8764, dtype: int64
内部标识号    8766
交易次数        8
交易金额      144
Name: 8765, dtype: int64
内部标识号    8767
交易次数        2
交易金额      319
Name: 8766, dtype: int64
内部标识号     8768
交易次数       137
交易金额     76460
Name: 8767, dtype: int64
内部标识号    8769
交易次数        6
交易金额      144
Name: 8768, dtype: int64
内部标识号    8770
交易次数       25
交易金额     9469
Name: 8769, dtype: int64
内部标识号    8771
交易次数       12
交易金额      697
Name: 8770, dtype: int64
内部标识号    8772
交易次数       24
交易金额     4145
Name: 8771, dtype: int64
内部标识号    8773
交易次数       12
交易金额      319
Name: 8772, dtype: int64
内部标识号    8774
交易次数       21
交易金额      649
Name: 8773, dtype: int64
内部标识号    8775
交易次数        9
交易金额      335
Name: 8774, dtype: int64
内部标识号    8776
交易次数        8
交易金额      590
Name: 8775, dtype: int64
内部标识号    8777
交易次数        5
交易金额      290
Name: 8776, dtype: int64
内部标识号    8778
交易次数        2
交易金额      405
Name: 8777, dtype: int64
内部标识号    8779
交易次数       15
交易金额      488
Name: 8778, dtype: int64
内部标识号    8780
交易次数        1
交易金额     2001
Name: 8779, dtype: int64
内部标识号    8781
交易次数       22
交易金额       59
Name: 8780, dtype: int64
内部标识号    8782
交易次数       19
交易金额     5399
Name: 8781, dtype: int64
内部标识号     8783
交易次数         6
交易金额     71930
Name: 8782, dtype: int64
内部标识号    8784
交易次数        0
交易金额     7589
Name: 8783, dtype: int64
内部标识号    8785
交易次数        8
交易金额      185
Name: 8784, dtype: int64
内部标识号    8786
交易次数       11
交易金额      657
Name: 8785, dtype: int64
内部标识号    8787
交易次数        7
交易金额      280
Name: 8786, dtype: int64
内部标识号    8788
交易次数       13
交易金额      443
Name: 8787, dtype: int64
内部标识号    8789
交易次数        2
交易金额      579
Name: 8788, dtype: int64
内部标识号    8790
交易次数        1
交易金额     2250
Name: 8789, dtype: int64
内部标识号    8791
交易次数       15
交易金额      585
Name: 8790, dtype: int64
内部标识号    8792
交易次数        9
交易金额      437
Name: 8791, dtype: int64
内部标识号    8793
交易次数       15
交易金额      565
Name: 8792, dtype: int64
内部标识号    8794
交易次数        4
交易金额      290
Name: 8793, dtype: int64
内部标识号    8795
交易次数        4
交易金额      272
Name: 8794, dtype: int64
内部标识号    8796
交易次数        9
交易金额      323
Name: 8795, dtype: int64
内部标识号    8797
交易次数       29
交易金额     1853
Name: 8796, dtype: int64
内部标识号    8798
交易次数       12
交易金额      913
Name: 8797, dtype: int64
内部标识号    8799
交易次数       12
交易金额      371
Name: 8798, dtype: int64
内部标识号    8800
交易次数        9
交易金额      324
Name: 8799, dtype: int64
内部标识号    8801
交易次数        6
交易金额      165
Name: 8800, dtype: int64
内部标识号    8802
交易次数       20
交易金额        2
Name: 8801, dtype: int64
内部标识号    8803
交易次数        3
交易金额      202
Name: 8802, dtype: int64
内部标识号    8804
交易次数       15
交易金额      973
Name: 8803, dtype: int64
内部标识号    8805
交易次数        2
交易金额      860
Name: 8804, dtype: int64
内部标识号    8806
交易次数        6
交易金额      145
Name: 8805, dtype: int64
内部标识号    8807
交易次数        0
交易金额     2317
Name: 8806, dtype: int64
内部标识号    8808
交易次数        7
交易金额      177
Name: 8807, dtype: int64
内部标识号    8809
交易次数       15
交易金额      930
Name: 8808, dtype: int64
内部标识号    8810
交易次数        1
交易金额      852
Name: 8809, dtype: int64
内部标识号    8811
交易次数        8
交易金额      561
Name: 8810, dtype: int64
内部标识号    8812
交易次数       13
交易金额      836
Name: 8811, dtype: int64
内部标识号    8813
交易次数       12
交易金额      707
Name: 8812, dtype: int64
内部标识号    8814
交易次数       10
交易金额      301
Name: 8813, dtype: int64
内部标识号    8815
交易次数        2
交易金额      933
Name: 8814, dtype: int64
内部标识号    8816
交易次数        6
交易金额      281
Name: 8815, dtype: int64
内部标识号    8817
交易次数       30
交易金额      520
Name: 8816, dtype: int64
内部标识号    8818
交易次数        2
交易金额      661
Name: 8817, dtype: int64
内部标识号    8819
交易次数       10
交易金额      918
Name: 8818, dtype: int64
内部标识号    8820
交易次数        3
交易金额      300
Name: 8819, dtype: int64
内部标识号    8821
交易次数        2
交易金额      684
Name: 8820, dtype: int64
内部标识号     8822
交易次数         8
交易金额     70190
Name: 8821, dtype: int64
内部标识号    8823
交易次数        3
交易金额      157
Name: 8822, dtype: int64
内部标识号    8824
交易次数        1
交易金额      748
Name: 8823, dtype: int64
内部标识号    8825
交易次数        3
交易金额      330
Name: 8824, dtype: int64
内部标识号    8826
交易次数       11
交易金额      309
Name: 8825, dtype: int64
内部标识号    8827
交易次数        0
交易金额     3700
Name: 8826, dtype: int64
内部标识号    8828
交易次数       12
交易金额      422
Name: 8827, dtype: int64
内部标识号    8829
交易次数       28
交易金额      671
Name: 8828, dtype: int64
内部标识号    8830
交易次数        4
交易金额      111
Name: 8829, dtype: int64
内部标识号    8831
交易次数       10
交易金额      313
Name: 8830, dtype: int64
内部标识号    8832
交易次数       14
交易金额      301
Name: 8831, dtype: int64
内部标识号    8833
交易次数       21
交易金额      756
Name: 8832, dtype: int64
内部标识号    8834
交易次数        3
交易金额      238
Name: 8833, dtype: int64
内部标识号    8835
交易次数       15
交易金额      758
Name: 8834, dtype: int64
内部标识号    8836
交易次数        1
交易金额     5209
Name: 8835, dtype: int64
内部标识号    8837
交易次数        3
交易金额      345
Name: 8836, dtype: int64
内部标识号    8838
交易次数        0
交易金额     8604
Name: 8837, dtype: int64
内部标识号    8839
交易次数        9
交易金额      964
Name: 8838, dtype: int64
内部标识号    8840
交易次数       24
交易金额     6966
Name: 8839, dtype: int64
内部标识号    8841
交易次数        3
交易金额      252
Name: 8840, dtype: int64
内部标识号    8842
交易次数        3
交易金额      336
Name: 8841, dtype: int64
内部标识号    8843
交易次数        2
交易金额      435
Name: 8842, dtype: int64
内部标识号    8844
交易次数       15
交易金额      925
Name: 8843, dtype: int64
内部标识号    8845
交易次数        3
交易金额      360
Name: 8844, dtype: int64
内部标识号    8846
交易次数       14
交易金额      350
Name: 8845, dtype: int64
内部标识号    8847
交易次数       11
交易金额      349
Name: 8846, dtype: int64
内部标识号    8848
交易次数       15
交易金额      784
Name: 8847, dtype: int64
内部标识号    8849
交易次数       24
交易金额      760
Name: 8848, dtype: int64
内部标识号    8850
交易次数        1
交易金额      664
Name: 8849, dtype: int64
内部标识号    8851
交易次数       14
交易金额      631
Name: 8850, dtype: int64
内部标识号    8852
交易次数        3
交易金额      429
Name: 8851, dtype: int64
内部标识号    8853
交易次数        3
交易金额      140
Name: 8852, dtype: int64
内部标识号     8854
交易次数       103
交易金额     31612
Name: 8853, dtype: int64
内部标识号    8855
交易次数        7
交易金额      231
Name: 8854, dtype: int64
内部标识号    8856
交易次数        2
交易金额      649
Name: 8855, dtype: int64
内部标识号    8857
交易次数       24
交易金额      818
Name: 8856, dtype: int64
内部标识号    8858
交易次数        5
交易金额      177
Name: 8857, dtype: int64
内部标识号    8859
交易次数        1
交易金额      535
Name: 8858, dtype: int64
内部标识号    8860
交易次数        3
交易金额      211
Name: 8859, dtype: int64
内部标识号    8861
交易次数       26
交易金额      774
Name: 8860, dtype: int64
内部标识号    8862
交易次数        3
交易金额      475
Name: 8861, dtype: int64
内部标识号    8863
交易次数       14
交易金额      494
Name: 8862, dtype: int64
内部标识号    8864
交易次数        6
交易金额      284
Name: 8863, dtype: int64
内部标识号    8865
交易次数        3
交易金额      447
Name: 8864, dtype: int64
内部标识号     8866
交易次数        77
交易金额     44939
Name: 8865, dtype: int64
内部标识号    8867
交易次数       10
交易金额      696
Name: 8866, dtype: int64
内部标识号     8868
交易次数       190
交易金额     84954
Name: 8867, dtype: int64
内部标识号    8869
交易次数        3
交易金额      435
Name: 8868, dtype: int64
内部标识号    8870
交易次数        9
交易金额      423
Name: 8869, dtype: int64
内部标识号    8871
交易次数       23
交易金额      875
Name: 8870, dtype: int64
内部标识号     8872
交易次数       278
交易金额     20384
Name: 8871, dtype: int64
内部标识号    8873
交易次数        8
交易金额      427
Name: 8872, dtype: int64
内部标识号    8874
交易次数        2
交易金额      584
Name: 8873, dtype: int64
内部标识号    8875
交易次数       11
交易金额      502
Name: 8874, dtype: int64
内部标识号    8876
交易次数        9
交易金额      469
Name: 8875, dtype: int64
内部标识号    8877
交易次数        3
交易金额      345
Name: 8876, dtype: int64
内部标识号    8878
交易次数       26
交易金额     3119
Name: 8877, dtype: int64
内部标识号    8879
交易次数        2
交易金额      338
Name: 8878, dtype: int64
内部标识号     8880
交易次数         4
交易金额     90003
Name: 8879, dtype: int64
内部标识号    8881
交易次数       26
交易金额     9016
Name: 8880, dtype: int64
内部标识号    8882
交易次数        2
交易金额      508
Name: 8881, dtype: int64
内部标识号    8883
交易次数        1
交易金额      541
Name: 8882, dtype: int64
内部标识号    8884
交易次数       14
交易金额      959
Name: 8883, dtype: int64
内部标识号    8885
交易次数        3
交易金额      450
Name: 8884, dtype: int64
内部标识号    8886
交易次数       15
交易金额      406
Name: 8885, dtype: int64
内部标识号     8887
交易次数         5
交易金额     68379
Name: 8886, dtype: int64
内部标识号    8888
交易次数        0
交易金额     1491
Name: 8887, dtype: int64
内部标识号    8889
交易次数        0
交易金额     6839
Name: 8888, dtype: int64
内部标识号    8890
交易次数       21
交易金额       82
Name: 8889, dtype: int64
内部标识号    8891
交易次数        1
交易金额     9430
Name: 8890, dtype: int64
内部标识号    8892
交易次数        6
交易金额      190
Name: 8891, dtype: int64
内部标识号     8893
交易次数        64
交易金额     61385
Name: 8892, dtype: int64
内部标识号    8894
交易次数        8
交易金额      928
Name: 8893, dtype: int64
内部标识号    8895
交易次数        4
交易金额      258
Name: 8894, dtype: int64
内部标识号    8896
交易次数       11
交易金额      561
Name: 8895, dtype: int64
内部标识号    8897
交易次数        3
交易金额      100
Name: 8896, dtype: int64
内部标识号    8898
交易次数        3
交易金额      428
Name: 8897, dtype: int64
内部标识号    8899
交易次数        0
交易金额     1245
Name: 8898, dtype: int64
内部标识号    8900
交易次数        0
交易金额     5050
Name: 8899, dtype: int64
内部标识号    8901
交易次数       15
交易金额      327
Name: 8900, dtype: int64
内部标识号    8902
交易次数        4
交易金额      214
Name: 8901, dtype: int64
内部标识号    8903
交易次数        9
交易金额      956
Name: 8902, dtype: int64
内部标识号    8904
交易次数        0
交易金额     1712
Name: 8903, dtype: int64
内部标识号     8905
交易次数       190
交易金额     79175
Name: 8904, dtype: int64
内部标识号    8906
交易次数       17
交易金额     2703
Name: 8905, dtype: int64
内部标识号    8907
交易次数       11
交易金额      446
Name: 8906, dtype: int64
内部标识号    8908
交易次数       26
交易金额     6073
Name: 8907, dtype: int64
内部标识号    8909
交易次数       14
交易金额      468
Name: 8908, dtype: int64
内部标识号    8910
交易次数       23
交易金额     7221
Name: 8909, dtype: int64
内部标识号    8911
交易次数        0
交易金额     3396
Name: 8910, dtype: int64
内部标识号    8912
交易次数       15
交易金额      985
Name: 8911, dtype: int64
内部标识号    8913
交易次数        4
交易金额      161
Name: 8912, dtype: int64
内部标识号    8914
交易次数       13
交易金额      660
Name: 8913, dtype: int64
内部标识号    8915
交易次数       23
交易金额     1676
Name: 8914, dtype: int64
内部标识号    8916
交易次数        0
交易金额     3865
Name: 8915, dtype: int64
内部标识号    8917
交易次数       30
交易金额       75
Name: 8916, dtype: int64
内部标识号    8918
交易次数       12
交易金额      954
Name: 8917, dtype: int64
内部标识号    8919
交易次数       27
交易金额      832
Name: 8918, dtype: int64
内部标识号    8920
交易次数       11
交易金额      862
Name: 8919, dtype: int64
内部标识号    8921
交易次数        4
交易金额      217
Name: 8920, dtype: int64
内部标识号    8922
交易次数       14
交易金额      436
Name: 8921, dtype: int64
内部标识号    8923
交易次数        5
交易金额      243
Name: 8922, dtype: int64
内部标识号    8924
交易次数       14
交易金额      555
Name: 8923, dtype: int64
内部标识号    8925
交易次数        2
交易金额      428
Name: 8924, dtype: int64
内部标识号    8926
交易次数       16
交易金额     6087
Name: 8925, dtype: int64
内部标识号    8927
交易次数       22
交易金额     6632
Name: 8926, dtype: int64
内部标识号    8928
交易次数       12
交易金额      374
Name: 8927, dtype: int64
内部标识号    8929
交易次数       11
交易金额      751
Name: 8928, dtype: int64
内部标识号    8930
交易次数        7
交易金额      119
Name: 8929, dtype: int64
内部标识号    8931
交易次数        1
交易金额      633
Name: 8930, dtype: int64
内部标识号    8932
交易次数        2
交易金额      429
Name: 8931, dtype: int64
内部标识号    8933
交易次数       29
交易金额      632
Name: 8932, dtype: int64
内部标识号    8934
交易次数       14
交易金额      308
Name: 8933, dtype: int64
内部标识号    8935
交易次数       25
交易金额     4013
Name: 8934, dtype: int64
内部标识号    8936
交易次数       14
交易金额      470
Name: 8935, dtype: int64
内部标识号    8937
交易次数        5
交易金额      272
Name: 8936, dtype: int64
内部标识号    8938
交易次数       14
交易金额      792
Name: 8937, dtype: int64
内部标识号    8939
交易次数       12
交易金额      977
Name: 8938, dtype: int64
内部标识号    8940
交易次数       15
交易金额     5580
Name: 8939, dtype: int64
内部标识号    8941
交易次数        2
交易金额      600
Name: 8940, dtype: int64
内部标识号    8942
交易次数       12
交易金额      511
Name: 8941, dtype: int64
内部标识号    8943
交易次数       26
交易金额      693
Name: 8942, dtype: int64
内部标识号     8944
交易次数       254
交易金额     49758
Name: 8943, dtype: int64
内部标识号    8945
交易次数        1
交易金额      880
Name: 8944, dtype: int64
内部标识号    8946
交易次数       20
交易金额     4769
Name: 8945, dtype: int64
内部标识号    8947
交易次数        1
交易金额      544
Name: 8946, dtype: int64
内部标识号    8948
交易次数        2
交易金额      300
Name: 8947, dtype: int64
内部标识号    8949
交易次数       13
交易金额      334
Name: 8948, dtype: int64
内部标识号    8950
交易次数        8
交易金额      319
Name: 8949, dtype: int64
内部标识号    8951
交易次数        2
交易金额      585
Name: 8950, dtype: int64
内部标识号    8952
交易次数        9
交易金额      813
Name: 8951, dtype: int64
内部标识号    8953
交易次数       29
交易金额      514
Name: 8952, dtype: int64
内部标识号    8954
交易次数       30
交易金额       71
Name: 8953, dtype: int64
内部标识号    8955
交易次数        1
交易金额      728
Name: 8954, dtype: int64
内部标识号    8956
交易次数       14
交易金额      975
Name: 8955, dtype: int64
内部标识号    8957
交易次数        3
交易金额      210
Name: 8956, dtype: int64
内部标识号    8958
交易次数        8
交易金额      309
Name: 8957, dtype: int64
内部标识号    8959
交易次数        7
交易金额      102
Name: 8958, dtype: int64
内部标识号    8960
交易次数       11
交易金额      467
Name: 8959, dtype: int64
内部标识号    8961
交易次数       21
交易金额     6028
Name: 8960, dtype: int64
内部标识号    8962
交易次数       12
交易金额      425
Name: 8961, dtype: int64
内部标识号    8963
交易次数        5
交易金额      230
Name: 8962, dtype: int64
内部标识号    8964
交易次数        2
交易金额      496
Name: 8963, dtype: int64
内部标识号    8965
交易次数        6
交易金额      152
Name: 8964, dtype: int64
内部标识号    8966
交易次数       11
交易金额      482
Name: 8965, dtype: int64
内部标识号    8967
交易次数       17
交易金额      878
Name: 8966, dtype: int64
内部标识号    8968
交易次数        8
交易金额      318
Name: 8967, dtype: int64
内部标识号    8969
交易次数       13
交易金额      954
Name: 8968, dtype: int64
内部标识号    8970
交易次数        7
交易金额      240
Name: 8969, dtype: int64
内部标识号    8971
交易次数        3
交易金额      322
Name: 8970, dtype: int64
内部标识号    8972
交易次数        2
交易金额      501
Name: 8971, dtype: int64
内部标识号    8973
交易次数        4
交易金额      123
Name: 8972, dtype: int64
内部标识号    8974
交易次数        3
交易金额      323
Name: 8973, dtype: int64
内部标识号    8975
交易次数        4
交易金额      168
Name: 8974, dtype: int64
内部标识号    8976
交易次数        7
交易金额      254
Name: 8975, dtype: int64
内部标识号     8977
交易次数       158
交易金额     48741
Name: 8976, dtype: int64
内部标识号    8978
交易次数       10
交易金额      775
Name: 8977, dtype: int64
内部标识号    8979
交易次数        3
交易金额      307
Name: 8978, dtype: int64
内部标识号     8980
交易次数         6
交易金额     66403
Name: 8979, dtype: int64
内部标识号     8981
交易次数         7
交易金额     15410
Name: 8980, dtype: int64
内部标识号    8982
交易次数        0
交易金额     3544
Name: 8981, dtype: int64
内部标识号    8983
交易次数       10
交易金额      302
Name: 8982, dtype: int64
内部标识号    8984
交易次数        3
交易金额      169
Name: 8983, dtype: int64
内部标识号    8985
交易次数        3
交易金额      124
Name: 8984, dtype: int64
内部标识号    8986
交易次数        3
交易金额      308
Name: 8985, dtype: int64
内部标识号    8987
交易次数       12
交易金额      307
Name: 8986, dtype: int64
内部标识号     8988
交易次数        79
交易金额     58826
Name: 8987, dtype: int64
内部标识号    8989
交易次数       11
交易金额      974
Name: 8988, dtype: int64
内部标识号    8990
交易次数        8
交易金额      108
Name: 8989, dtype: int64
内部标识号    8991
交易次数        1
交易金额      881
Name: 8990, dtype: int64
内部标识号    8992
交易次数        2
交易金额      768
Name: 8991, dtype: int64
内部标识号    8993
交易次数       15
交易金额      658
Name: 8992, dtype: int64
内部标识号    8994
交易次数       10
交易金额      487
Name: 8993, dtype: int64
内部标识号    8995
交易次数        0
交易金额     4287
Name: 8994, dtype: int64
内部标识号    8996
交易次数       13
交易金额      765
Name: 8995, dtype: int64
内部标识号    8997
交易次数        2
交易金额      941
Name: 8996, dtype: int64
内部标识号    8998
交易次数        2
交易金额      667
Name: 8997, dtype: int64
内部标识号     8999
交易次数         8
交易金额     48103
Name: 8998, dtype: int64
内部标识号     9000
交易次数         8
交易金额     63357
Name: 8999, dtype: int64
内部标识号    9001
交易次数        1
交易金额      911
Name: 9000, dtype: int64
内部标识号    9002
交易次数       25
交易金额     1967
Name: 9001, dtype: int64
内部标识号    9003
交易次数       12
交易金额      409
Name: 9002, dtype: int64
内部标识号    9004
交易次数        4
交易金额      169
Name: 9003, dtype: int64
内部标识号    9005
交易次数        0
交易金额     6532
Name: 9004, dtype: int64
内部标识号    9006
交易次数       12
交易金额      927
Name: 9005, dtype: int64
内部标识号    9007
交易次数        3
交易金额      297
Name: 9006, dtype: int64
内部标识号    9008
交易次数        3
交易金额      367
Name: 9007, dtype: int64
内部标识号     9009
交易次数       134
交易金额     40487
Name: 9008, dtype: int64
内部标识号    9010
交易次数       11
交易金额      459
Name: 9009, dtype: int64
内部标识号     9011
交易次数         8
交易金额     75781
Name: 9010, dtype: int64
内部标识号    9012
交易次数        5
交易金额      119
Name: 9011, dtype: int64
内部标识号    9013
交易次数       10
交易金额      634
Name: 9012, dtype: int64
内部标识号    9014
交易次数       19
交易金额     5136
Name: 9013, dtype: int64
内部标识号    9015
交易次数       12
交易金额      430
Name: 9014, dtype: int64
内部标识号    9016
交易次数       19
交易金额     1623
Name: 9015, dtype: int64
内部标识号    9017
交易次数        3
交易金额      145
Name: 9016, dtype: int64
内部标识号     9018
交易次数       156
交易金额     59197
Name: 9017, dtype: int64
内部标识号    9019
交易次数       23
交易金额     6781
Name: 9018, dtype: int64
内部标识号    9020
交易次数        6
交易金额      235
Name: 9019, dtype: int64
内部标识号    9021
交易次数        0
交易金额     4529
Name: 9020, dtype: int64
内部标识号    9022
交易次数        4
交易金额      273
Name: 9021, dtype: int64
内部标识号    9023
交易次数        2
交易金额      768
Name: 9022, dtype: int64
内部标识号    9024
交易次数        9
交易金额      636
Name: 9023, dtype: int64
内部标识号    9025
交易次数        0
交易金额     2977
Name: 9024, dtype: int64
内部标识号     9026
交易次数         7
交易金额     17552
Name: 9025, dtype: int64
内部标识号    9027
交易次数       15
交易金额      767
Name: 9026, dtype: int64
内部标识号    9028
交易次数        1
交易金额     6263
Name: 9027, dtype: int64
内部标识号    9029
交易次数        7
交易金额      272
Name: 9028, dtype: int64
内部标识号    9030
交易次数       14
交易金额      993
Name: 9029, dtype: int64
内部标识号    9031
交易次数        2
交易金额      405
Name: 9030, dtype: int64
内部标识号    9032
交易次数        3
交易金额      148
Name: 9031, dtype: int64
内部标识号    9033
交易次数        6
交易金额      219
Name: 9032, dtype: int64
内部标识号    9034
交易次数        2
交易金额      460
Name: 9033, dtype: int64
内部标识号    9035
交易次数        1
交易金额      556
Name: 9034, dtype: int64
内部标识号     9036
交易次数         8
交易金额     54579
Name: 9035, dtype: int64
内部标识号    9037
交易次数        3
交易金额      176
Name: 9036, dtype: int64
内部标识号    9038
交易次数       25
交易金额     7843
Name: 9037, dtype: int64
内部标识号    9039
交易次数       13
交易金额      589
Name: 9038, dtype: int64
内部标识号    9040
交易次数        3
交易金额      178
Name: 9039, dtype: int64
内部标识号    9041
交易次数        2
交易金额      119
Name: 9040, dtype: int64
内部标识号     9042
交易次数         8
交易金额     57097
Name: 9041, dtype: int64
内部标识号    9043
交易次数        2
交易金额      812
Name: 9042, dtype: int64
内部标识号    9044
交易次数       15
交易金额      342
Name: 9043, dtype: int64
内部标识号    9045
交易次数        2
交易金额      896
Name: 9044, dtype: int64
内部标识号    9046
交易次数       13
交易金额      495
Name: 9045, dtype: int64
内部标识号     9047
交易次数         8
交易金额     62490
Name: 9046, dtype: int64
内部标识号    9048
交易次数       13
交易金额      460
Name: 9047, dtype: int64
内部标识号    9049
交易次数        0
交易金额     2455
Name: 9048, dtype: int64
内部标识号    9050
交易次数        1
交易金额      922
Name: 9049, dtype: int64
内部标识号    9051
交易次数        0
交易金额     2385
Name: 9050, dtype: int64
内部标识号    9052
交易次数        0
交易金额     6007
Name: 9051, dtype: int64
内部标识号    9053
交易次数        7
交易金额      229
Name: 9052, dtype: int64
内部标识号    9054
交易次数       12
交易金额      584
Name: 9053, dtype: int64
内部标识号    9055
交易次数        2
交易金额      984
Name: 9054, dtype: int64
内部标识号    9056
交易次数        3
交易金额      300
Name: 9055, dtype: int64
内部标识号    9057
交易次数        3
交易金额      445
Name: 9056, dtype: int64
内部标识号    9058
交易次数       12
交易金额      983
Name: 9057, dtype: int64
内部标识号    9059
交易次数       15
交易金额      818
Name: 9058, dtype: int64
内部标识号    9060
交易次数        1
交易金额      934
Name: 9059, dtype: int64
内部标识号    9061
交易次数        2
交易金额      307
Name: 9060, dtype: int64
内部标识号    9062

Name: 9162, dtype: int64
内部标识号    9164
交易次数       13
交易金额      667
Name: 9163, dtype: int64
内部标识号    9165
交易次数       14
交易金额      394
Name: 9164, dtype: int64
内部标识号    9166
交易次数        1
交易金额      743
Name: 9165, dtype: int64
内部标识号    9167
交易次数       11
交易金额      385
Name: 9166, dtype: int64
内部标识号    9168
交易次数       11
交易金额      857
Name: 9167, dtype: int64
内部标识号    9169
交易次数        2
交易金额      485
Name: 9168, dtype: int64
内部标识号    9170
交易次数       16
交易金额     1945
Name: 9169, dtype: int64
内部标识号    9171
交易次数        2
交易金额      417
Name: 9170, dtype: int64
内部标识号    9172
交易次数       17
交易金额     4569
Name: 9171, dtype: int64
内部标识号    9173
交易次数        4
交易金额      212
Name: 9172, dtype: int64
内部标识号    9174
交易次数       29
交易金额      527
Name: 9173, dtype: int64
内部标识号    9175
交易次数        1
交易金额      757
Name: 9174, dtype: int64
内部标识号    9176
交易次数       12
交易金额      644
Name: 9175, dtype: int64
内部标识号    9177
交易次数        2
交易金额      400
Name: 9176, dtype: int64
内部标识号    9178
交易次数        3
交易金额      313
Name: 9177, dtype: int64
内部标识号     9179
交易次数         3
交易金额     21235
Name: 9178, dtype: int64
内部标识号    9180
交易次数        9
交易金额      498
Name: 9179, dtype: int64
内部标识号    9181
交易次数        8
交易金额      300
Name: 9180, dtype: int64
内部标识号    9182
交易次数        8
交易金额      362
Name: 9181, dtype: int64
内部标识号    9183
交易次数        2
交易金额      370
Name: 9182, dtype: int64
内部标识号    9184
交易次数        4
交易金额      278
Name: 9183, dtype: int64
内部标识号    9185
交易次数        7
交易金额      295
Name: 9184, dtype: int64
内部标识号    9186
交易次数        1
交易金额      970
Name: 9185, dtype: int64
内部标识号    9187
交易次数       19
交易金额     2440
Name: 9186, dtype: int64
内部标识号     9188
交易次数         7
交易金额     27391
Name: 9187, dtype: int64
内部标识号    9189
交易次数       21
交易金额     7859
Name: 9188, dtype: int64
内部标识号    9190
交易次数        1
交易金额      953
Name: 9189, dtype: int64
内部标识号    9191
交易次数        0
交易金额     1042
Name: 9190, dtype: int64
内部标识号    9192
交易次数        5
交易金额      188
Name: 9191, dtype: int64
内部标识号    9193
交易次数       20
交易金额     2517
Name: 9192, dtype: int64
内部标识号    9194
交易次数       15
交易金额      673
Name: 9193, dtype: int64
内部标识号    9195
交易次数        0
交易金额     4872
Name: 9194, dtype: int64
内部标识号    9196
交易次数        3
交易金额      402
Name: 9195, dtype: int64
内部标识号    9197
交易次数        6
交易金额      222
Name: 9196, dtype: int64
内部标识号    9198
交易次数        2
交易金额      105
Name: 9197, dtype: int64
内部标识号    9199
交易次数        1
交易金额     3758
Name: 9198, dtype: int64
内部标识号    9200
交易次数        6
交易金额      262
Name: 9199, dtype: int64
内部标识号    9201
交易次数        6
交易金额      281
Name: 9200, dtype: int64
内部标识号    9202
交易次数        3
交易金额      470
Name: 9201, dtype: int64
内部标识号     9203
交易次数         6
交易金额     11549
Name: 9202, dtype: int64
内部标识号    9204
交易次数       13
交易金额      381
Name: 9203, dtype: int64
内部标识号    9205
交易次数       12
交易金额      980
Name: 9204, dtype: int64
内部标识号    9206
交易次数        9
交易金额      873
Name: 9205, dtype: int64
内部标识号    9207
交易次数       26
交易金额       63
Name: 9206, dtype: int64
内部标识号    9208
交易次数       13
交易金额      882
Name: 9207, dtype: int64
内部标识号    9209
交易次数        2
交易金额      485
Name: 9208, dtype: int64
内部标识号    9210
交易次数        7
交易金额      137
Name: 9209, dtype: int64
内部标识号    9211
交易次数        9
交易金额      493
Name: 9210, dtype: int64
内部标识号    9212
交易次数        2
交易金额      511
Name: 9211, dtype: int64
内部标识号    9213
交易次数        7
交易金额      175
Name: 9212, dtype: int64
内部标识号    9214
交易次数        1
交易金额      606
Name: 9213, dtype: int64
内部标识号    9215
交易次数       15
交易金额      498
Name: 9214, dtype: int64
内部标识号    9216
交易次数       11
交易金额      795
Name: 9215, dtype: int64
内部标识号    9217
交易次数       29
交易金额      504
Name: 9216, dtype: int64
内部标识号    9218
交易次数        8
交易金额      689
Name: 9217, dtype: int64
内部标识号    9219
交易次数       12
交易金额      600
Name: 9218, dtype: int64
内部标识号    9220
交易次数        1
交易金额     3195
Name: 9219, dtype: int64
内部标识号    9221
交易次数        4
交易金额      293
Name: 9220, dtype: int64
内部标识号    9222
交易次数        0
交易金额     5421
Name: 9221, dtype: int64
内部标识号     9223
交易次数       196
交易金额     74312
Name: 9222, dtype: int64
内部标识号    9224
交易次数       10
交易金额      992
Name: 9223, dtype: int64
内部标识号    9225
交易次数        6
交易金额      297
Name: 9224, dtype: int64
内部标识号    9226
交易次数        3
交易金额      394
Name: 9225, dtype: int64
内部标识号    9227
交易次数        2
交易金额      768
Name: 9226, dtype: int64
内部标识号     9228
交易次数       234
交易金额     53240
Name: 9227, dtype: int64
内部标识号    9229
交易次数       30
交易金额      100
Name: 9228, dtype: int64
内部标识号    9230
交易次数        8
交易金额      201
Name: 9229, dtype: int64
内部标识号    9231
交易次数        3
交易金额      491
Name: 9230, dtype: int64
内部标识号    9232
交易次数        8
交易金额      204
Name: 9231, dtype: int64
内部标识号    9233
交易次数        0
交易金额     3198
Name: 9232, dtype: int64
内部标识号     9234
交易次数       227
交易金额     63507
Name: 9233, dtype: int64
内部标识号    9235
交易次数        5
交易金额      188
Name: 9234, dtype: int64
内部标识号    9236
交易次数       21
交易金额       98
Name: 9235, dtype: int64
内部标识号     9237
交易次数       259
交易金额     34041
Name: 9236, dtype: int64
内部标识号    9238
交易次数       18
交易金额      643
Name: 9237, dtype: int64
内部标识号    9239
交易次数        6
交易金额      291
Name: 9238, dtype: int64
内部标识号    9240
交易次数        9
交易金额      990
Name: 9239, dtype: int64
内部标识号    9241
交易次数       10
交易金额      462
Name: 9240, dtype: int64
内部标识号    9242
交易次数        8
交易金额      197
Name: 9241, dtype: int64
内部标识号    9243
交易次数        2
交易金额      945
Name: 9242, dtype: int64
内部标识号    9244
交易次数       11
交易金额      398
Name: 9243, dtype: int64
内部标识号    9245
交易次数        1
交易金额     4975
Name: 9244, dtype: int64
内部标识号    9246
交易次数       13
交易金额      867
Name: 9245, dtype: int64
内部标识号    9247
交易次数        8
交易金额      313
Name: 9246, dtype: int64
内部标识号    9248
交易次数       25
交易金额     4663
Name: 9247, dtype: int64
内部标识号     9249
交易次数         8
交易金额     36946
Name: 9248, dtype: int64
内部标识号    9250
交易次数       14
交易金额      853
Name: 9249, dtype: int64
内部标识号    9251
交易次数       11
交易金额      607
Name: 9250, dtype: int64
内部标识号    9252
交易次数       14
交易金额      835
Name: 9251, dtype: int64
内部标识号    9253
交易次数        2
交易金额      462
Name: 9252, dtype: int64
内部标识号    9254
交易次数       11
交易金额      872
Name: 9253, dtype: int64
内部标识号    9255
交易次数        7
交易金额      188
Name: 9254, dtype: int64
内部标识号    9256
交易次数       28
交易金额     1841
Name: 9255, dtype: int64
内部标识号    9257
交易次数       24
交易金额     4054
Name: 9256, dtype: int64
内部标识号    9258
交易次数       10
交易金额      430
Name: 9257, dtype: int64
内部标识号    9259
交易次数        8
交易金额      400
Name: 9258, dtype: int64
内部标识号    9260
交易次数        8
交易金额      473
Name: 9259, dtype: int64
内部标识号    9261
交易次数        0
交易金额     9187
Name: 9260, dtype: int64
内部标识号    9262
交易次数       13
交易金额      471
Name: 9261, dtype: int64
内部标识号    9263
交易次数        0
交易金额     5510
Name: 9262, dtype: int64
内部标识号     9264
交易次数         6
交易金额     32679
Name: 9263, dtype: int64
内部标识号    9265
交易次数        3
交易金额      325
Name: 9264, dtype: int64
内部标识号     9266
交易次数       203
交易金额     66108
Name: 9265, dtype: int64
内部标识号    9267
交易次数        3
交易金额      162
Name: 9266, dtype: int64
内部标识号    9268
交易次数        2
交易金额      638
Name: 9267, dtype: int64
内部标识号    9269
交易次数        2
交易金额      917
Name: 9268, dtype: int64
内部标识号    9270
交易次数       25
交易金额      987
Name: 9269, dtype: int64
内部标识号    9271
交易次数       26
交易金额      541
Name: 9270, dtype: int64
内部标识号    9272
交易次数       12
交易金额      509
Name: 9271, dtype: int64
内部标识号    9273
交易次数        7
交易金额      153
Name: 9272, dtype: int64
内部标识号    9274
交易次数       30
交易金额     7645
Name: 9273, dtype: int64
内部标识号    9275
交易次数       16
交易金额     7443
Name: 9274, dtype: int64
内部标识号    9276
交易次数       25
交易金额     4758
Name: 9275, dtype: int64
内部标识号    9277
交易次数        8
交易金额      966
Name: 9276, dtype: int64
内部标识号    9278
交易次数        2
交易金额      347
Name: 9277, dtype: int64
内部标识号    9279
交易次数       14
交易金额      305
Name: 9278, dtype: int64
内部标识号    9280
交易次数       23
交易金额       41
Name: 9279, dtype: int64
内部标识号    9281
交易次数       12
交易金额      347
Name: 9280, dtype: int64
内部标识号    9282
交易次数       15
交易金额      643
Name: 9281, dtype: int64
内部标识号    9283
交易次数        2
交易金额      670
Name: 9282, dtype: int64
内部标识号    9284
交易次数        9
交易金额      789
Name: 9283, dtype: int64
内部标识号     9285
交易次数         3
交易金额     33274
Name: 9284, dtype: int64
内部标识号    9286
交易次数        2
交易金额      441
Name: 9285, dtype: int64
内部标识号    9287
交易次数        4
交易金额      109
Name: 9286, dtype: int64
内部标识号    9288
交易次数       21
交易金额     4471
Name: 9287, dtype: int64
内部标识号    9289
交易次数       11
交易金额      361
Name: 9288, dtype: int64
内部标识号    9290
交易次数       15
交易金额      607
Name: 9289, dtype: int64
内部标识号    9291
交易次数        8
交易金额      365
Name: 9290, dtype: int64
内部标识号    9292
交易次数       30
交易金额      712
Name: 9291, dtype: int64
内部标识号    9293
交易次数       29
交易金额     7421
Name: 9292, dtype: int64
内部标识号    9294
交易次数        8
交易金额      133
Name: 9293, dtype: int64
内部标识号    9295
交易次数       19
交易金额       71
Name: 9294, dtype: int64
内部标识号    9296
交易次数        2
交易金额      148
Name: 9295, dtype: int64
内部标识号    9297
交易次数        2
交易金额      309
Name: 9296, dtype: int64
内部标识号    9298
交易次数        5
交易金额      235
Name: 9297, dtype: int64
内部标识号    9299
交易次数       13
交易金额      338
Name: 9298, dtype: int64
内部标识号    9300
交易次数       10
交易金额      788
Name: 9299, dtype: int64
内部标识号    9301
交易次数        2
交易金额      463
Name: 9300, dtype: int64
内部标识号    9302
交易次数        3
交易金额      406
Name: 9301, dtype: int64
内部标识号    9303
交易次数       11
交易金额      681
Name: 9302, dtype: int64
内部标识号    9304
交易次数        3
交易金额      319
Name: 9303, dtype: int64
内部标识号    9305
交易次数       14
交易金额      388
Name: 9304, dtype: int64
内部标识号    9306
交易次数        2
交易金额      386
Name: 9305, dtype: int64
内部标识号    9307
交易次数       11
交易金额      394
Name: 9306, dtype: int64
内部标识号    9308
交易次数       15
交易金额      860
Name: 9307, dtype: int64
内部标识号    9309
交易次数        6
交易金额      134
Name: 9308, dtype: int64
内部标识号    9310
交易次数        2
交易金额      492
Name: 9309, dtype: int64
内部标识号    9311
交易次数        8
交易金额      425
Name: 9310, dtype: int64
内部标识号    9312
交易次数        4
交易金额      183
Name: 9311, dtype: int64
内部标识号    9313
交易次数       13
交易金额      406
Name: 9312, dtype: int64
内部标识号    9314
交易次数       15
交易金额      958
Name: 9313, dtype: int64
内部标识号    9315
交易次数        1
交易金额      721
Name: 9314, dtype: int64
内部标识号    9316
交易次数       10
交易金额      345
Name: 9315, dtype: int64
内部标识号    9317
交易次数        2
交易金额      304
Name: 9316, dtype: int64
内部标识号    9318
交易次数        3
交易金额      151
Name: 9317, dtype: int64
内部标识号    9319
交易次数        8
交易金额      756
Name: 9318, dtype: int64
内部标识号    9320
交易次数        2
交易金额      784
Name: 9319, dtype: int64
内部标识号    9321
交易次数        7
交易金额      180
Name: 9320, dtype: int64
内部标识号    9322
交易次数       28
交易金额     2598
Name: 9321, dtype: int64
内部标识号    9323
交易次数        3
交易金额      489
Name: 9322, dtype: int64
内部标识号    9324
交易次数        2
交易金额      165
Name: 9323, dtype: int64
内部标识号    9325
交易次数        1
交易金额      895
Name: 9324, dtype: int64
内部标识号    9326
交易次数       12
交易金额      946
Name: 9325, dtype: int64
内部标识号    9327
交易次数       10
交易金额      593
Name: 9326, dtype: int64
内部标识号    9328
交易次数        7
交易金额      269
Name: 9327, dtype: int64
内部标识号    9329
交易次数        0
交易金额     8130
Name: 9328, dtype: int64
内部标识号    9330
交易次数       17
交易金额     6990
Name: 9329, dtype: int64
内部标识号    9331
交易次数        8
交易金额      668
Name: 9330, dtype: int64
内部标识号    9332
交易次数        2
交易金额      476
Name: 9331, dtype: int64
内部标识号    9333
交易次数        9
交易金额      449
Name: 9332, dtype: int64
内部标识号    9334
交易次数        1
交易金额      695
Name: 9333, dtype: int64
内部标识号    9335
交易次数       15
交易金额      741
Name: 9334, dtype: int64
内部标识号    9336
交易次数       25
交易金额       55
Name: 9335, dtype: int64
内部标识号    9337
交易次数       22
交易金额       17
Name: 9336, dtype: int64
内部标识号    9338
交易次数        7
交易金额      160
Name: 9337, dtype: int64
内部标识号    9339
交易次数        0
交易金额     1142
Name: 9338, dtype: int64
内部标识号    9340
交易次数       13
交易金额      839
Name: 9339, dtype: int64
内部标识号    9341
交易次数       11
交易金额      482
Name: 9340, dtype: int64
内部标识号    9342
交易次数        1
交易金额      926
Name: 9341, dtype: int64
内部标识号    9343
交易次数        2
交易金额      516
Name: 9342, dtype: int64
内部标识号    9344
交易次数        0
交易金额     6147
Name: 9343, dtype: int64
内部标识号    9345
交易次数        1
交易金额      566
Name: 9344, dtype: int64
内部标识号    9346
交易次数        2
交易金额      338
Name: 9345, dtype: int64
内部标识号    9347
交易次数        3
交易金额      362
Name: 9346, dtype: int64
内部标识号     9348
交易次数         5
交易金额     96445
Name: 9347, dtype: int64
内部标识号    9349
交易次数        0
交易金额     9640
Name: 9348, dtype: int64
内部标识号    9350
交易次数       14
交易金额      971
Name: 9349, dtype: int64
内部标识号    9351
交易次数       14
交易金额      337
Name: 9350, dtype: int64
内部标识号    9352
交易次数       12
交易金额      588
Name: 9351, dtype: int64
内部标识号    9353
交易次数       13
交易金额      423
Name: 9352, dtype: int64
内部标识号    9354
交易次数        1
交易金额     6962
Name: 9353, dtype: int64
内部标识号    9355
交易次数        9
交易金额      624
Name: 9354, dtype: int64
内部标识号    9356
交易次数        3
交易金额      483
Name: 9355, dtype: int64
内部标识号    9357
交易次数       14
交易金额      497
Name: 9356, dtype: int64
内部标识号     9358
交易次数         6
交易金额     32560
Name: 9357, dtype: int64
内部标识号    9359
交易次数       25
交易金额     2237
Name: 9358, dtype: int64
内部标识号    9360
交易次数        5
交易金额      127
Name: 9359, dtype: int64
内部标识号    9361
交易次数        3
交易金额      230
Name: 9360, dtype: int64
内部标识号    9362
交易次数        3
交易金额      320
Name: 9361, dtype: int64
内部标识号    9363
交易次数        2
交易金额      353
Name: 9362, dtype: int64
内部标识号    9364
交易次数        3
交易金额      364
Name: 9363, dtype: int64
内部标识号    9365
交易次数        5
交易金额      108
Name: 9364, dtype: int64
内部标识号    9366
交易次数        3
交易金额      422
Name: 9365, dtype: int64
内部标识号    9367
交易次数        2
交易金额      630
Name: 9366, dtype: int64
内部标识号    9368
交易次数        3
交易金额      415
Name: 9367, dtype: int64
内部标识号    9369
交易次数        1
交易金额      840
Name: 9368, dtype: int64
内部标识号    9370
交易次数       28
交易金额     4254
Name: 9369, dtype: int64
内部标识号     9371
交易次数         6
交易金额     92353
Name: 9370, dtype: int64
内部标识号    9372
交易次数       11
交易金额      888
Name: 9371, dtype: int64
内部标识号    9373
交易次数        2
交易金额      964
Name: 9372, dtype: int64
内部标识号    9374
交易次数        3
交易金额      383
Name: 9373, dtype: int64
内部标识号    9375
交易次数       30
交易金额     9546
Name: 9374, dtype: int64
内部标识号    9376
交易次数        3
交易金额      423
Name: 9375, dtype: int64
内部标识号    9377
交易次数       30
交易金额     8301
Name: 9376, dtype: int64
内部标识号    9378
交易次数        5
交易金额      130
Name: 9377, dtype: int64
内部标识号    9379
交易次数       27
交易金额     5638
Name: 9378, dtype: int64
内部标识号    9380
交易次数        6
交易金额      296
Name: 9379, dtype: int64
内部标识号     9381
交易次数         5
交易金额     65156
Name: 9380, dtype: int64
内部标识号    9382
交易次数        3
交易金额      416
Name: 9381, dtype: int64
内部标识号    9383
交易次数       11
交易金额      669
Name: 9382, dtype: int64
内部标识号    9384
交易次数       28
交易金额      772
Name: 9383, dtype: int64
内部标识号    9385
交易次数       10
交易金额      414
Name: 9384, dtype: int64
内部标识号    9386
交易次数       11
交易金额      971
Name: 9385, dtype: int64
内部标识号    9387
交易次数        8
交易金额      350
Name: 9386, dtype: int64
内部标识号    9388
交易次数        2
交易金额      376
Name: 9387, dtype: int64
内部标识号    9389
交易次数       18
交易金额     7383
Name: 9388, dtype: int64
内部标识号    9390
交易次数        2
交易金额      728
Name: 9389, dtype: int64
内部标识号    9391
交易次数       12
交易金额      361
Name: 9390, dtype: int64
内部标识号    9392
交易次数        3
交易金额      182
Name: 9391, dtype: int64
内部标识号    9393
交易次数        3
交易金额      248
Name: 9392, dtype: int64
内部标识号    9394
交易次数        3
交易金额      333
Name: 9393, dtype: int64
内部标识号    9395
交易次数        4
交易金额      133
Name: 9394, dtype: int64
内部标识号    9396
交易次数        2
交易金额      902
Name: 9395, dtype: int64
内部标识号    9397
交易次数        6
交易金额      291
Name: 9396, dtype: int64
内部标识号    9398
交易次数        1
交易金额      626
Name: 9397, dtype: int64
内部标识号    9399
交易次数        4
交易金额      278
Name: 9398, dtype: int64
内部标识号    9400
交易次数        2
交易金额      359
Name: 9399, dtype: int64
内部标识号    9401
交易次数        2
交易金额      956
Name: 9400, dtype: int64
内部标识号    9402
交易次数       15
交易金额     8206
Name: 9401, dtype: int64
内部标识号    9403
交易次数        5
交易金额      202
Name: 9402, dtype: int64
内部标识号    9404
交易次数        3
交易金额      424
Name: 9403, dtype: int64
内部标识号    9405
交易次数        2
交易金额      657
Name: 9404, dtype: int64
内部标识号    9406
交易次数        3
交易金额      363
Name: 9405, dtype: int64
内部标识号     9407
交易次数        80
交易金额     75060
Name: 9406, dtype: int64
内部标识号    9408
交易次数        9
交易金额      328
Name: 9407, dtype: int64
内部标识号     9409
交易次数         8
交易金额     92074
Name: 9408, dtype: int64
内部标识号    9410
交易次数       13
交易金额      466
Name: 9409, dtype: int64
内部标识号    9411
交易次数        8
交易金额      934
Name: 9410, dtype: int64
内部标识号    9412
交易次数        5
交易金额      276
Name: 9411, dtype: int64
内部标识号     9413
交易次数         4
交易金额     43441
Name: 9412, dtype: int64
内部标识号    9414
交易次数       22
交易金额       70
Name: 9413, dtype: int64
内部标识号    9415
交易次数       15
交易金额      468
Name: 9414, dtype: int64
内部标识号    9416
交易次数        3
交易金额      182
Name: 9415, dtype: int64
内部标识号    9417
交易次数        0
交易金额     7411
Name: 9416, dtype: int64
内部标识号    9418
交易次数       13
交易金额      531
Name: 9417, dtype: int64
内部标识号     9419
交易次数       281
交易金额     80587
Name: 9418, dtype: int64
内部标识号    9420
交易次数       12
交易金额      730
Name: 9419, dtype: int64
内部标识号     9421
交易次数         3
交易金额     26535
Name: 9420, dtype: int64
内部标识号    9422
交易次数        2
交易金额      644
Name: 9421, dtype: int64
内部标识号    9423
交易次数       12
交易金额      430
Name: 9422, dtype: int64
内部标识号    9424
交易次数        2
交易金额      226
Name: 9423, dtype: int64
内部标识号    9425
交易次数        7
交易金额      225
Name: 9424, dtype: int64
内部标识号    9426
交易次数        1
交易金额     3114
Name: 9425, dtype: int64
内部标识号    9427
交易次数       13
交易金额      721
Name: 9426, dtype: int64
内部标识号    9428
交易次数        3
交易金额      176
Name: 9427, dtype: int64
内部标识号     9429
交易次数         8
交易金额     96276
Name: 9428, dtype: int64
内部标识号     9430
交易次数        60
交易金额     12447
Name: 9429, dtype: int64
内部标识号    9431
交易次数       29
交易金额      769
Name: 9430, dtype: int64
内部标识号    9432
交易次数        8
交易金额      110
Name: 9431, dtype: int64
内部标识号    9433
交易次数        4
交易金额      136
Name: 9432, dtype: int64
内部标识号    9434
交易次数        2
交易金额      401
Name: 9433, dtype: int64
内部标识号    9435
交易次数        9
交易金额      422
Name: 9434, dtype: int64
内部标识号    9436
交易次数        8
交易金额      325
Name: 9435, dtype: int64
内部标识号    9437
交易次数        8
交易金额      130
Name: 9436, dtype: int64
内部标识号    9438
交易次数        9
交易金额      849
Name: 9437, dtype: int64
内部标识号    9439
交易次数        8
交易金额      262
Name: 9438, dtype: int64
内部标识号    9440
交易次数        1
交易金额      977
Name: 9439, dtype: int64
内部标识号    9441
交易次数        1
交易金额      793
Name: 9440, dtype: int64
内部标识号    9442
交易次数        0
交易金额     8945
Name: 9441, dtype: int64
内部标识号    9443
交易次数       13
交易金额      859
Name: 9442, dtype: int64
内部标识号    9444
交易次数        4
交易金额      216
Name: 9443, dtype: int64
内部标识号    9445
交易次数        3
交易金额      417
Name: 9444, dtype: int64
内部标识号    9446
交易次数        1
交易金额      631
Name: 9445, dtype: int64
内部标识号    9447
交易次数        0
交易金额     8493
Name: 9446, dtype: int64
内部标识号    9448
交易次数       13
交易金额      539
Name: 9447, dtype: int64
内部标识号    9449
交易次数        6
交易金额      101
Name: 9448, dtype: int64
内部标识号    9450
交易次数       13
交易金额      374
Name: 9449, dtype: int64
内部标识号    9451
交易次数       16
交易金额      574
Name: 9450, dtype: int64
内部标识号    9452
交易次数       11
交易金额      806
Name: 9451, dtype: int64
内部标识号    9453
交易次数        3
交易金额      105
Name: 9452, dtype: int64
内部标识号    9454
交易次数       15
交易金额      767
Name: 9453, dtype: int64
内部标识号    9455
交易次数        1
交易金额     5136
Name: 9454, dtype: int64
内部标识号    9456
交易次数        2
交易金额      484
Name: 9455, dtype: int64
内部标识号    9457
交易次数       13
交易金额      560
Name: 9456, dtype: int64
内部标识号    9458
交易次数        1
交易金额      535
Name: 9457, dtype: int64
内部标识号    9459
交易次数       13
交易金额      423
Name: 9458, dtype: int64
内部标识号    9460
交易次数       10
交易金额      379
Name: 9459, dtype: int64

Name: 9465, dtype: int64
内部标识号    9467
交易次数       11
交易金额      600
Name: 9466, dtype: int64
内部标识号     9468
交易次数         3
交易金额     12649
Name: 9467, dtype: int64
内部标识号    9469
交易次数       13
交易金额      481
Name: 9468, dtype: int64
内部标识号    9470
交易次数       15
交易金额      954
Name: 9469, dtype: int64
内部标识号    9471
交易次数        3
交易金额      494
Name: 9470, dtype: int64
内部标识号    9472
交易次数        3
交易金额      393
Name: 9471, dtype: int64
内部标识号    9473
交易次数        7
交易金额      300
Name: 9472, dtype: int64
内部标识号    9474
交易次数       11
交易金额      727
Name: 9473, dtype: int64
内部标识号    9475
交易次数       11
交易金额      478
Name: 9474, dtype: int64
内部标识号    9476
交易次数        1
交易金额     1831
Name: 9475, dtype: int64
内部标识号    9477
交易次数        1
交易金额      584
Name: 9476, dtype: int64
内部标识号    9478
交易次数        1
交易金额      758
Name: 9477, dtype: int64
内部标识号     9479
交易次数       167
交易金额     91922
Name: 9478, dtype: int64
内部标识号    9480
交易次数       11
交易金额      758
Name: 9479, dtype: int64
内部标识号    9481
交易次数        8
交易金额      710
Name: 9480, dtype: int64
内部标识号     9482
交易次数         5
交易金额     86430
Name: 9481, dtype: int64
内部标识号    9483
交易次数        8
交易金额      420
Name: 9482, dtype: int64
内部标识号    9484
交易次数        2
交易金额      639
Name: 9483, dtype: int64
内部标识号    9485
交易次数       10
交易金额      793
Name: 9484, dtype: int64
内部标识号    9486
交易次数       14
交易金额      478
Name: 9485, dtype: int64
内部标识号    9487
交易次数        6
交易金额      151
Name: 9486, dtype: int64
内部标识号    9488
交易次数        6
交易金额      237
Name: 9487, dtype: int64
内部标识号    9489
交易次数        0
交易金额     9759
Name: 9488, dtype: int64
内部标识号    9490
交易次数       24
交易金额      730
Name: 9489, dtype: int64
内部标识号    9491
交易次数        3
交易金额      312
Name: 9490, dtype: int64
内部标识号    9492
交易次数        1
交易金额      909
Name: 9491, dtype: int64
内部标识号    9493
交易次数       24
交易金额     9481
Name: 9492, dtype: int64
内部标识号    9494
交易次数        6
交易金额      104
Name: 9493, dtype: int64
内部标识号     9495
交易次数       133
交易金额     75384
Name: 9494, dtype: int64
内部标识号    9496
交易次数       15
交易金额      396
Name: 9495, dtype: int64
内部标识号    9497
交易次数       18
交易金额     8615
Name: 9496, dtype: int64
内部标识号    9498
交易次数       13
交易金额      358
Name: 9497, dtype: int64
内部标识号    9499
交易次数        1
交易金额      612
Name: 9498, dtype: int64
内部标识号    9500
交易次数        4
交易金额      145
Name: 9499, dtype: int64
内部标识号    9501
交易次数       10
交易金额      398
Name: 9500, dtype: int64
内部标识号    9502
交易次数        7
交易金额      129
Name: 9501, dtype: int64
内部标识号    9503
交易次数       29
交易金额     9798
Name: 9502, dtype: int64
内部标识号    9504
交易次数        2
交易金额      439
Name: 9503, dtype: int64
内部标识号    9505
交易次数        1
交易金额      815
Name: 9504, dtype: int64
内部标识号     9506
交易次数       200
交易金额     99772
Name: 9505, dtype: int64
内部标识号    9507
交易次数        8
交易金额      304
Name: 9506, dtype: int64
内部标识号    9508
交易次数       13
交易金额      675
Name: 9507, dtype: int64
内部标识号     9509
交易次数        52
交易金额     84956
Name: 9508, dtype: int64
内部标识号    9510
交易次数        0
交易金额     2219
Name: 9509, dtype: int64
内部标识号    9511
交易次数       16
交易金额     3409
Name: 9510, dtype: int64
内部标识号    9512
交易次数        3
交易金额      371
Name: 9511, dtype: int64
内部标识号    9513
交易次数       14
交易金额      467
Name: 9512, dtype: int64
内部标识号    9514
交易次数       10
交易金额      836
Name: 9513, dtype: int64
内部标识号    9515
交易次数        2
交易金额      423
Name: 9514, dtype: int64
内部标识号     9516
交易次数       155
交易金额     95397
Name: 9515, dtype: int64
内部标识号    9517
交易次数        9
交易金额      462
Name: 9516, dtype: int64
内部标识号    9518
交易次数       12
交易金额      653
Name: 9517, dtype: int64
内部标识号    9519
交易次数        3
交易金额      341
Name: 9518, dtype: int64
内部标识号    9520
交易次数       13
交易金额      486
Name: 9519, dtype: int64
内部标识号    9521
交易次数       18
交易金额      956
Name: 9520, dtype: int64
内部标识号    9522
交易次数       10
交易金额      397
Name: 9521, dtype: int64
内部标识号    9523
交易次数       14
交易金额      509
Name: 9522, dtype: int64
内部标识号    9524
交易次数       17
交易金额     1229
Name: 9523, dtype: int64
内部标识号    9525
交易次数        2
交易金额      411
Name: 9524, dtype: int64
内部标识号    9526
交易次数        2
交易金额      493
Name: 9525, dtype: int64
内部标识号    9527
交易次数        3
交易金额      463
Name: 9526, dtype: int64
内部标识号    9528
交易次数        1
交易金额      640
Name: 9527, dtype: int64
内部标识号    9529
交易次数        0
交易金额     2413
Name: 9528, dtype: int64
内部标识号    9530
交易次数        1
交易金额     8219
Name: 9529, dtype: int64
内部标识号    9531
交易次数        2
交易金额      862
Name: 9530, dtype: int64
内部标识号    9532
交易次数        3
交易金额      135
Name: 9531, dtype: int64
内部标识号    9533
交易次数        2
交易金额      545
Name: 9532, dtype: int64
内部标识号    9534
交易次数       10
交易金额      355
Name: 9533, dtype: int64
内部标识号    9535
交易次数        8
交易金额      255
Name: 9534, dtype: int64
内部标识号    9536
交易次数        1
交易金额     5222
Name: 9535, dtype: int64
内部标识号    9537
交易次数        3
交易金额      174
Name: 9536, dtype: int64
内部标识号    9538
交易次数       30
交易金额      801
Name: 9537, dtype: int64
内部标识号     9539
交易次数       176
交易金额     22485
Name: 9538, dtype: int64
内部标识号    9540
交易次数        8
交易金额      844
Name: 9539, dtype: int64
内部标识号    9541
交易次数        8
交易金额      387
Name: 9540, dtype: int64
内部标识号    9542
交易次数        2
交易金额      256
Name: 9541, dtype: int64
内部标识号    9543
交易次数       15
交易金额      381
Name: 9542, dtype: int64
内部标识号    9544
交易次数       12
交易金额      455
Name: 9543, dtype: int64
内部标识号    9545
交易次数        3
交易金额      281
Name: 9544, dtype: int64
内部标识号    9546
交易次数       13
交易金额      531
Name: 9545, dtype: int64
内部标识号    9547
交易次数       21
交易金额     3275
Name: 9546, dtype: int64
内部标识号    9548
交易次数        4
交易金额      173
Name: 9547, dtype: int64
内部标识号    9549
交易次数        3
交易金额      398
Name: 9548, dtype: int64
内部标识号     9550
交易次数       118
交易金额     39803
Name: 9549, dtype: int64
内部标识号    9551
交易次数        3
交易金额      485
Name: 9550, dtype: int64
内部标识号    9552
交易次数        4
交易金额      232
Name: 9551, dtype: int64
内部标识号    9553
交易次数       12
交易金额      817
Name: 9552, dtype: int64
内部标识号    9554
交易次数        8
交易金额      600
Name: 9553, dtype: int64
内部标识号    9555
交易次数        2
交易金额      223
Name: 9554, dtype: int64
内部标识号    9556
交易次数        8
交易金额      268
Name: 9555, dtype: int64
内部标识号    9557
交易次数       20
交易金额     8371
Name: 9556, dtype: int64
内部标识号    9558
交易次数        2
交易金额      204
Name: 9557, dtype: int64
内部标识号    9559
交易次数       15
交易金额      532
Name: 9558, dtype: int64
内部标识号    9560
交易次数        1
交易金额      768
Name: 9559, dtype: int64
内部标识号    9561
交易次数        8
交易金额      997
Name: 9560, dtype: int64
内部标识号    9562
交易次数        1
交易金额     8354
Name: 9561, dtype: int64
内部标识号    9563
交易次数        1
交易金额      930
Name: 9562, dtype: int64
内部标识号    9564
交易次数        0
交易金额     8661
Name: 9563, dtype: int64
内部标识号    9565
交易次数       12
交易金额      808
Name: 9564, dtype: int64
内部标识号    9566
交易次数        9
交易金额      387
Name: 9565, dtype: int64
内部标识号    9567
交易次数       13
交易金额      882
Name: 9566, dtype: int64
内部标识号    9568
交易次数       20
交易金额       68
Name: 9567, dtype: int64
内部标识号    9569
交易次数        4
交易金额      214
Name: 9568, dtype: int64
内部标识号    9570
交易次数        1
交易金额     7023
Name: 9569, dtype: int64
内部标识号    9571
交易次数       15
交易金额      634
Name: 9570, dtype: int64
内部标识号    9572
交易次数       15
交易金额      439
Name: 9571, dtype: int64
内部标识号    9573
交易次数        6
交易金额      214
Name: 9572, dtype: int64
内部标识号    9574
交易次数        5
交易金额      147
Name: 9573, dtype: int64
内部标识号    9575
交易次数       28
交易金额     6590
Name: 9574, dtype: int64
内部标识号     9576
交易次数       222
交易金额     40007
Name: 9575, dtype: int64
内部标识号    9577
交易次数       12
交易金额      512
Name: 9576, dtype: int64
内部标识号    9578
交易次数        2
交易金额      870
Name: 9577, dtype: int64
内部标识号    9579
交易次数        2
交易金额      380
Name: 9578, dtype: int64
内部标识号    9580
交易次数        7
交易金额      272
Name: 9579, dtype: int64
内部标识号    9581
交易次数        3
交易金额      255
Name: 9580, dtype: int64
内部标识号    9582
交易次数        8
交易金额      298
Name: 9581, dtype: int64
内部标识号    9583
交易次数       15
交易金额      839
Name: 9582, dtype: int64
内部标识号    9584
交易次数        1
交易金额      923
Name: 9583, dtype: int64
内部标识号     9585
交易次数       170
交易金额     32110
Name: 9584, dtype: int64
内部标识号    9586
交易次数        3
交易金额      472
Name: 9585, dtype: int64
内部标识号    9587
交易次数       12
交易金额      995
Name: 9586, dtype: int64
内部标识号    9588
交易次数        4
交易金额      235
Name: 9587, dtype: int64
内部标识号    9589
交易次数        7
交易金额      195
Name: 9588, dtype: int64
内部标识号    9590
交易次数        1
交易金额     6237
Name: 9589, dtype: int64
内部标识号    9591
交易次数        3
交易金额      105
Name: 9590, dtype: int64
内部标识号    9592
交易次数        4
交易金额      169
Name: 9591, dtype: int64
内部标识号    9593
交易次数       14
交易金额      573
Name: 9592, dtype: int64
内部标识号    9594
交易次数        2
交易金额      998
Name: 9593, dtype: int64
内部标识号    9595
交易次数        6
交易金额      104
Name: 9594, dtype: int64
内部标识号    9596
交易次数        2
交易金额      910
Name: 9595, dtype: int64
内部标识号    9597
交易次数        8
交易金额      236
Name: 9596, dtype: int64
内部标识号    9598
交易次数       12
交易金额      530
Name: 9597, dtype: int64
内部标识号    9599
交易次数        2
交易金额      348
Name: 9598, dtype: int64
内部标识号    9600
交易次数       10
交易金额      367
Name: 9599, dtype: int64
内部标识号     9601
交易次数       157
交易金额     98875
Name: 9600, dtype: int64
内部标识号    9602
交易次数        0
交易金额     5946
Name: 9601, dtype: int64
内部标识号    9603
交易次数       13
交易金额      432
Name: 9602, dtype: int64
内部标识号    9604
交易次数        0
交易金额     5220
Name: 9603, dtype: int64
内部标识号     9605
交易次数       161
交易金额     59808
Name: 9604, dtype: int64
内部标识号    9606
交易次数       26
交易金额     1321
Name: 9605, dtype: int64
内部标识号    9607
交易次数       10
交易金额      623
Name: 9606, dtype: int64
内部标识号    9608
交易次数        2
交易金额      346
Name: 9607, dtype: int64
内部标识号    9609
交易次数        0
交易金额     7179
Name: 9608, dtype: int64
内部标识号    9610
交易次数        2
交易金额      360
Name: 9609, dtype: int64
内部标识号    9611
交易次数        3
交易金额      376
Name: 9610, dtype: int64
内部标识号    9612
交易次数        3
交易金额      316
Name: 9611, dtype: int64
内部标识号    9613
交易次数        4
交易金额      196
Name: 9612, dtype: int64
内部标识号    9614
交易次数        5
交易金额      184
Name: 9613, dtype: int64
内部标识号    9615
交易次数        2
交易金额      394
Name: 9614, dtype: int64
内部标识号    9616
交易次数        1
交易金额      823
Name: 9615, dtype: int64
内部标识号    9617
交易次数        8
交易金额      488
Name: 9616, dtype: int64
内部标识号    9618
交易次数       15
交易金额      997
Name: 9617, dtype: int64
内部标识号     9619
交易次数       265
交易金额     69066
Name: 9618, dtype: int64
内部标识号    9620
交易次数       10
交易金额      917
Name: 9619, dtype: int64
内部标识号    9621
交易次数       11
交易金额      845
Name: 9620, dtype: int64
内部标识号     9622
交易次数         6
交易金额     35543
Name: 9621, dtype: int64
内部标识号    9623
交易次数       13
交易金额      402
Name: 9622, dtype: int64
内部标识号    9624
交易次数        2
交易金额      987
Name: 9623, dtype: int64
内部标识号    9625
交易次数        0
交易金额     9759
Name: 9624, dtype: int64
内部标识号     9626
交易次数         5
交易金额     48513
Name: 9625, dtype: int64
内部标识号    9627
交易次数        6
交易金额      168
Name: 9626, dtype: int64
内部标识号    9628
交易次数        8
交易金额      704
Name: 9627, dtype: int64
内部标识号    9629
交易次数        2
交易金额      367
Name: 9628, dtype: int64
内部标识号    9630
交易次数        1
交易金额      903
Name: 9629, dtype: int64
内部标识号    9631
交易次数       12
交易金额      729
Name: 9630, dtype: int64
内部标识号    9632
交易次数        3
交易金额      347
Name: 9631, dtype: int64
内部标识号    9633
交易次数        4
交易金额      300
Name: 9632, dtype: int64
内部标识号    9634
交易次数        3
交易金额      445
Name: 9633, dtype: int64
内部标识号    9635
交易次数       14
交易金额      832
Name: 9634, dtype: int64
内部标识号    9636
交易次数        3
交易金额      242
Name: 9635, dtype: int64
内部标识号    9637
交易次数        0
交易金额     7322
Name: 9636, dtype: int64
内部标识号    9638
交易次数       14
交易金额      556
Name: 9637, dtype: int64
内部标识号     9639
交易次数       268
交易金额     80786
Name: 9638, dtype: int64
内部标识号    9640
交易次数       21
交易金额     2976
Name: 9639, dtype: int64
内部标识号     9641
交易次数        82
交易金额     59687
Name: 9640, dtype: int64
内部标识号    9642
交易次数        7
交易金额      252
Name: 9641, dtype: int64
内部标识号    9643
交易次数       29
交易金额     3885
Name: 9642, dtype: int64
内部标识号    9644
交易次数        2
交易金额      641
Name: 9643, dtype: int64
内部标识号    9645
交易次数       18
交易金额     7387
Name: 9644, dtype: int64
内部标识号    9646
交易次数        1
交易金额      756
Name: 9645, dtype: int64
内部标识号     9647
交易次数        42
交易金额     64045
Name: 9646, dtype: int64
内部标识号    9648
交易次数        8
交易金额      307
Name: 9647, dtype: int64
内部标识号    9649
交易次数       10
交易金额      913
Name: 9648, dtype: int64
内部标识号    9650
交易次数       12
交易金额      492
Name: 9649, dtype: int64
内部标识号    9651
交易次数        4
交易金额      209
Name: 9650, dtype: int64
内部标识号    9652
交易次数        2
交易金额      863
Name: 9651, dtype: int64
内部标识号    9653
交易次数       24
交易金额        5
Name: 9652, dtype: int64
内部标识号    9654
交易次数       14
交易金额      462
Name: 9653, dtype: int64
内部标识号    9655
交易次数        3
交易金额      425
Name: 9654, dtype: int64
内部标识号    9656
交易次数        4
交易金额      128
Name: 9655, dtype: int64
内部标识号     9657
交易次数         5
交易金额     68001
Name: 9656, dtype: int64
内部标识号     9658
交易次数       199
交易金额     67249
Name: 9657, dtype: int64
内部标识号    9659
交易次数        2
交易金额      970
Name: 9658, dtype: int64
内部标识号    9660
交易次数        4
交易金额      127
Name: 9659, dtype: int64
内部标识号    9661
交易次数        8
交易金额      101
Name: 9660, dtype: int64
内部标识号    9662
交易次数       10
交易金额      468
Name: 9661, dtype: int64
内部标识号    9663
交易次数        4
交易金额      160
Name: 9662, dtype: int64
内部标识号    9664
交易次数        3
交易金额      338
Name: 9663, dtype: int64
内部标识号    9665
交易次数       10
交易金额      459
Name: 9664, dtype: int64
内部标识号    9666
交易次数        1
交易金额      930
Name: 9665, dtype: int64
内部标识号    9667
交易次数        6
交易金额      213
Name: 9666, dtype: int64
内部标识号    9668
交易次数        7
交易金额      173
Name: 9667, dtype: int64
内部标识号    9669
交易次数       14
交易金额      571
Name: 9668, dtype: int64
内部标识号    9670
交易次数       30
交易金额      839
Name: 9669, dtype: int64
内部标识号    9671
交易次数        1
交易金额     6757
Name: 9670, dtype: int64
内部标识号    9672
交易次数        2
交易金额      767
Name: 9671, dtype: int64
内部标识号     9673
交易次数       281
交易金额     87491
Name: 9672, dtype: int64
内部标识号    9674
交易次数        7
交易金额      204
Name: 9673, dtype: int64
内部标识号    9675
交易次数       10
交易金额      669
Name: 9674, dtype: int64
内部标识号    9676
交易次数        8
交易金额      101
Name: 9675, dtype: int64
内部标识号    9677
交易次数       11
交易金额      391
Name: 9676, dtype: int64
内部标识号     9678
交易次数       202
交易金额     90858
Name: 9677, dtype: int64
内部标识号    9679
交易次数       10
交易金额      896
Name: 9678, dtype: int64
内部标识号    9680
交易次数       11
交易金额      669
Name: 9679, dtype: int64
内部标识号    9681
交易次数       10
交易金额      887
Name: 9680, dtype: int64
内部标识号    9682
交易次数       12
交易金额      924
Name: 9681, dtype: int64
内部标识号    9683
交易次数        4
交易金额      226
Name: 9682, dtype: int64
内部标识号     9684
交易次数         3
交易金额     63125
Name: 9683, dtype: int64
内部标识号    9685
交易次数       27
交易金额     4580
Name: 9684, dtype: int64
内部标识号    9686
交易次数       11
交易金额      886
Name: 9685, dtype: int64
内部标识号    9687
交易次数       14
交易金额      598
Name: 9686, dtype: int64
内部标识号    9688
交易次数        2
交易金额      691
Name: 9687, dtype: int64
内部标识号    9689
交易次数        2
交易金额      252
Name: 9688, dtype: int64
内部标识号    9690
交易次数       27
交易金额      813
Name: 9689, dtype: int64
内部标识号    9691
交易次数       14
交易金额      486
Name: 9690, dtype: int64
内部标识号    9692
交易次数        1
交易金额      612
Name: 9691, dtype: int64
内部标识号    9693
交易次数       13
交易金额      454
Name: 9692, dtype: int64
内部标识号    9694
交易次数        9
交易金额      505
Name: 9693, dtype: int64
内部标识号    9695
交易次数        2
交易金额      472
Name: 9694, dtype: int64
内部标识号    9696
交易次数       11
交易金额      835
Name: 9695, dtype: int64
内部标识号    9697
交易次数        1
交易金额      640
Name: 9696, dtype: int64
内部标识号    9698
交易次数        9
交易金额      598
Name: 9697, dtype: int64
内部标识号    9699
交易次数        8
交易金额      184
Name: 9698, dtype: int64
内部标识号    9700
交易次数        1
交易金额     4778
Name: 9699, dtype: int64
内部标识号    9701
交易次数        3
交易金额      161
Name: 9700, dtype: int64
内部标识号    9702
交易次数        9
交易金额      320
Name: 9701, dtype: int64
内部标识号    9703
交易次数        0
交易金额     7681
Name: 9702, dtype: int64
内部标识号     9704
交易次数         4
交易金额     96481
Name: 9703, dtype: int64
内部标识号    9705
交易次数       14
交易金额      320
Name: 9704, dtype: int64
内部标识号    9706
交易次数        0
交易金额     7457
Name: 9705, dtype: int64
内部标识号    9707
交易次数        3
交易金额      488
Name: 9706, dtype: int64
内部标识号    9708
交易次数        2
交易金额      412
Name: 9707, dtype: int64
内部标识号    9709
交易次数        1
交易金额      920
Name: 9708, dtype: int64
内部标识号    9710
交易次数       20
交易金额     7480
Name: 9709, dtype: int64
内部标识号    9711
交易次数       14
交易金额      770
Name: 9710, dtype: int64
内部标识号    9712
交易次数       12
交易金额      516
Name: 9711, dtype: int64
内部标识号    9713
交易次数       10
交易金额      636
Name: 9712, dtype: int64
内部标识号    9714
交易次数        5
交易金额      104
Name: 9713, dtype: int64
内部标识号    9715
交易次数       13
交易金额      546
Name: 9714, dtype: int64
内部标识号    9716
交易次数       10
交易金额      397
Name: 9715, dtype: int64
内部标识号     9717
交易次数         8
交易金额     91213
Name: 9716, dtype: int64
内部标识号    9718
交易次数        0
交易金额     6904
Name: 9717, dtype: int64
内部标识号    9719
交易次数       13
交易金额      329
Name: 9718, dtype: int64
内部标识号    9720
交易次数       28
交易金额     4956
Name: 9719, dtype: int64
内部标识号    9721
交易次数       19
交易金额      854
Name: 9720, dtype: int64
内部标识号     9722
交易次数        32
交易金额     41325
Name: 9721, dtype: int64
内部标识号    9723
交易次数        8
交易金额      584
Name: 9722, dtype: int64
内部标识号    9724
交易次数        7
交易金额      238
Name: 9723, dtype: int64
内部标识号    9725
交易次数        0
交易金额     1149
Name: 9724, dtype: int64
内部标识号    9726
交易次数       12
交易金额      419
Name: 9725, dtype: int64
内部标识号    9727
交易次数        3
交易金额      481
Name: 9726, dtype: int64
内部标识号    9728
交易次数        8
交易金额      747
Name: 9727, dtype: int64
内部标识号    9729
交易次数       15
交易金额      348
Name: 9728, dtype: int64
内部标识号    9730
交易次数       10
交易金额      893
Name: 9729, dtype: int64
内部标识号    9731
交易次数        2
交易金额      893
Name: 9730, dtype: int64
内部标识号    9732
交易次数       10
交易金额      734
Name: 9731, dtype: int64
内部标识号    9733
交易次数       13
交易金额      366
Name: 9732, dtype: int64
内部标识号    9734
交易次数        3
交易金额      350
Name: 9733, dtype: int64
内部标识号    9735
交易次数        9
交易金额      378
Name: 9734, dtype: int64
内部标识号    9736
交易次数        1
交易金额      946
Name: 9735, dtype: int64
内部标识号    9737
交易次数       13
交易金额      709
Name: 9736, dtype: int64
内部标识号    9738
交易次数       20
交易金额     5268
Name: 9737, dtype: int64
内部标识号    9739
交易次数       16
交易金额     9473
Name: 9738, dtype: int64
内部标识号    9740
交易次数        4
交易金额      119
Name: 9739, dtype: int64
内部标识号    9741
交易次数        5
交易金额      163
Name: 9740, dtype: int64
内部标识号    9742
交易次数        8
交易金额      885
Name: 9741, dtype: int64
内部标识号    9743
交易次数        6
交易金额      288
Name: 9742, dtype: int64
内部标识号    9744
交易次数       14
交易金额      493
Name: 9743, dtype: int64
内部标识号    9745
交易次数        1
交易金额      842
Name: 9744, dtype: int64
内部标识号    9746
交易次数       14
交易金额      493
Name: 9745, dtype: int64
内部标识号     9747
交易次数         6
交易金额     18378
Name: 9746, dtype: int64
内部标识号    9748
交易次数       13
交易金额      452
Name: 9747, dtype: int64
内部标识号    9749
交易次数       13
交易金额      335
Name: 9748, dtype: int64
内部标识号    9750
交易次数       24
交易金额       86
Name: 9749, dtype: int64
内部标识号    9751
交易次数       13
交易金额      487
Name: 9750, dtype: int64
内部标识号    9752
交易次数       12
交易金额      979
Name: 9751, dtype: int64
内部标识号    9753
交易次数       21
交易金额     7945
Name: 9752, dtype: int64
内部标识号    9754
交易次数        2
交易金额      708
Name: 9753, dtype: int64
内部标识号    9755
交易次数        4
交易金额      215
Name: 9754, dtype: int64
内部标识号    9756
交易次数        3
交易金额      107
Name: 9755, dtype: int64
内部标识号    9757
交易次数        0
交易金额     2324
Name: 9756, dtype: int64
内部标识号    9758
交易次数        2
交易金额      311
Name: 9757, dtype: int64
内部标识号    9759
交易次数        9
交易金额      495
Name: 9758, dtype: int64
内部标识号    9760
交易次数       12
交易金额      658
Name: 9759, dtype: int64
内部标识号    9761
交易次数       14
交易金额      331
Name: 9760, dtype: int64
内部标识号     9762
交易次数         7
交易金额     14887
Name: 9761, dtype: int64
内部标识号    9763
交易次数        1
交易金额      590

Name: 9762, dtype: int64
内部标识号    9764
交易次数       12
交易金额      859
Name: 9763, dtype: int64
内部标识号    9765
交易次数        9
交易金额      618
Name: 9764, dtype: int64
内部标识号    9766
交易次数        0
交易金额     9265
Name: 9765, dtype: int64
内部标识号    9767
交易次数       12
交易金额      320
Name: 9766, dtype: int64
内部标识号    9768
交易次数        5
交易金额      197
Name: 9767, dtype: int64
内部标识号    9769
交易次数        2
交易金额      544
Name: 9768, dtype: int64
内部标识号    9770
交易次数        9
交易金额      381
Name: 9769, dtype: int64
内部标识号    9771
交易次数       10
交易金额      777
Name: 9770, dtype: int64
内部标识号    9772
交易次数        0
交易金额     5048
Name: 9771, dtype: int64
内部标识号    9773
交易次数        2
交易金额      715
Name: 9772, dtype: int64
内部标识号    9774
交易次数       14
交易金额      814
Name: 9773, dtype: int64
内部标识号    9775
交易次数        3
交易金额      377
Name: 9774, dtype: int64
内部标识号    9776
交易次数       15
交易金额     6740
Name: 9775, dtype: int64
内部标识号    9777
交易次数        1
交易金额      547
Name: 9776, dtype: int64
内部标识号    9778
交易次数        0
交易金额     4036
Name: 9777, dtype: int64
内部标识号    9779
交易次数       13
交易金额      438
Name: 9778, dtype: int64
内部标识号    9780
交易次数       30
交易金额     9975
Name: 9779, dtype: int64
内部标识号    9781
交易次数        3
交易金额      187
Name: 9780, dtype: int64
内部标识号    9782
交易次数        3
交易金额      397
Name: 9781, dtype: int64
内部标识号     9783
交易次数       264
交易金额     51107
Name: 9782, dtype: int64
内部标识号    9784
交易次数        4
交易金额      270
Name: 9783, dtype: int64
内部标识号    9785
交易次数       11
交易金额      590
Name: 9784, dtype: int64
内部标识号    9786
交易次数        0
交易金额     1513
Name: 9785, dtype: int64
内部标识号    9787
交易次数       11
交易金额      386
Name: 9786, dtype: int64
内部标识号    9788
交易次数        9
交易金额      365
Name: 9787, dtype: int64
内部标识号     9789
交易次数       200
交易金额     17613
Name: 9788, dtype: int64
内部标识号    9790
交易次数        0
交易金额     5697
Name: 9789, dtype: int64
内部标识号    9791
交易次数        1
交易金额     4406
Name: 9790, dtype: int64
内部标识号     9792
交易次数         5
交易金额     58233
Name: 9791, dtype: int64
内部标识号    9793
交易次数        3
交易金额      383
Name: 9792, dtype: int64
内部标识号    9794
交易次数        2
交易金额      295
Name: 9793, dtype: int64
内部标识号    9795
交易次数        7
交易金额      255
Name: 9794, dtype: int64
内部标识号    9796
交易次数       11
交易金额      497
Name: 9795, dtype: int64
内部标识号    9797
交易次数        9
交易金额      338
Name: 9796, dtype: int64
内部标识号    9798
交易次数       15
交易金额      336
Name: 9797, dtype: int64
内部标识号    9799
交易次数        2
交易金额      378
Name: 9798, dtype: int64
内部标识号    9800
交易次数       13
交易金额      945
Name: 9799, dtype: int64
内部标识号    9801
交易次数        3
交易金额      419
Name: 9800, dtype: int64
内部标识号     9802
交易次数       131
交易金额     63149
Name: 9801, dtype: int64
内部标识号    9803
交易次数        8
交易金额      232
Name: 9802, dtype: int64
内部标识号    9804
交易次数        3
交易金额      109
Name: 9803, dtype: int64
内部标识号    9805
交易次数        8
交易金额      242
Name: 9804, dtype: int64
内部标识号    9806
交易次数        8
交易金额      888
Name: 9805, dtype: int64
内部标识号    9807
交易次数       24
交易金额      629
Name: 9806, dtype: int64
内部标识号    9808
交易次数        3
交易金额      386
Name: 9807, dtype: int64
内部标识号     9809
交易次数         7
交易金额     68577
Name: 9808, dtype: int64
内部标识号    9810
交易次数       13
交易金额      331
Name: 9809, dtype: int64
内部标识号    9811
交易次数        3
交易金额      446
Name: 9810, dtype: int64
内部标识号    9812
交易次数        3
交易金额      406
Name: 9811, dtype: int64
内部标识号    9813
交易次数       23
交易金额     9734
Name: 9812, dtype: int64
内部标识号    9814
交易次数        6
交易金额      226
Name: 9813, dtype: int64
内部标识号    9815
交易次数       14
交易金额      710
Name: 9814, dtype: int64
内部标识号    9816
交易次数        0
交易金额     7568
Name: 9815, dtype: int64
内部标识号    9817
交易次数        1
交易金额      575
Name: 9816, dtype: int64
内部标识号    9818
交易次数       19
交易金额     7121
Name: 9817, dtype: int64
内部标识号    9819
交易次数        2
交易金额      591
Name: 9818, dtype: int64
内部标识号    9820
交易次数        2
交易金额      757
Name: 9819, dtype: int64
内部标识号    9821
交易次数       14
交易金额      798
Name: 9820, dtype: int64
内部标识号    9822
交易次数        3
交易金额      434
Name: 9821, dtype: int64
内部标识号    9823
交易次数       10
交易金额      427
Name: 9822, dtype: int64
内部标识号    9824
交易次数        2
交易金额      351
Name: 9823, dtype: int64
内部标识号    9825
交易次数        2
交易金额      475
Name: 9824, dtype: int64
内部标识号    9826
交易次数        1
交易金额      901
Name: 9825, dtype: int64
内部标识号    9827
交易次数        2
交易金额      128
Name: 9826, dtype: int64
内部标识号    9828
交易次数        6
交易金额      241
Name: 9827, dtype: int64
内部标识号    9829
交易次数        0
交易金额     2197
Name: 9828, dtype: int64
内部标识号    9830
交易次数       14
交易金额      818
Name: 9829, dtype: int64
内部标识号    9831
交易次数        8
交易金额      883
Name: 9830, dtype: int64
内部标识号    9832
交易次数        8
交易金额      971
Name: 9831, dtype: int64
内部标识号    9833
交易次数       14
交易金额      365
Name: 9832, dtype: int64
内部标识号    9834
交易次数        5
交易金额      254
Name: 9833, dtype: int64
内部标识号    9835
交易次数        3
交易金额      253
Name: 9834, dtype: int64
内部标识号    9836
交易次数        3
交易金额      362
Name: 9835, dtype: int64
内部标识号    9837
交易次数        0
交易金额     3909
Name: 9836, dtype: int64
内部标识号    9838
交易次数        7
交易金额      103
Name: 9837, dtype: int64
内部标识号    9839
交易次数        9
交易金额      675
Name: 9838, dtype: int64
内部标识号    9840
交易次数       10
交易金额      853
Name: 9839, dtype: int64
内部标识号    9841
交易次数       23
交易金额      686
Name: 9840, dtype: int64
内部标识号    9842
交易次数        2
交易金额      432
Name: 9841, dtype: int64
内部标识号    9843
交易次数        5
交易金额      298
Name: 9842, dtype: int64
内部标识号    9844
交易次数        3
交易金额      222
Name: 9843, dtype: int64
内部标识号    9845
交易次数       18
交易金额      699
Name: 9844, dtype: int64
内部标识号    9846
交易次数        8
交易金额      641
Name: 9845, dtype: int64
内部标识号    9847
交易次数        2
交易金额      727
Name: 9846, dtype: int64
内部标识号    9848
交易次数        3
交易金额      460
Name: 9847, dtype: int64
内部标识号    9849
交易次数       14
交易金额      386
Name: 9848, dtype: int64
内部标识号    9850
交易次数        2
交易金额      905
Name: 9849, dtype: int64
内部标识号    9851
交易次数        8
交易金额      774
Name: 9850, dtype: int64
内部标识号    9852
交易次数       10
交易金额      350
Name: 9851, dtype: int64
内部标识号    9853
交易次数        0
交易金额     1298
Name: 9852, dtype: int64
内部标识号     9854
交易次数         4
交易金额     84634
Name: 9853, dtype: int64
内部标识号    9855
交易次数       12
交易金额      765
Name: 9854, dtype: int64
内部标识号    9856
交易次数        2
交易金额      624
Name: 9855, dtype: int64
内部标识号    9857
交易次数        2
交易金额      365
Name: 9856, dtype: int64
内部标识号    9858
交易次数        9
交易金额      764
Name: 9857, dtype: int64
内部标识号    9859
交易次数        2
交易金额      493
Name: 9858, dtype: int64
内部标识号    9860
交易次数       14
交易金额      967
Name: 9859, dtype: int64
内部标识号    9861
交易次数        1
交易金额      679
Name: 9860, dtype: int64
内部标识号    9862
交易次数       24
交易金额      699
Name: 9861, dtype: int64
内部标识号     9863
交易次数       297
交易金额     34777
Name: 9862, dtype: int64
内部标识号    9864
交易次数        0
交易金额     1038
Name: 9863, dtype: int64
内部标识号    9865
交易次数        3
交易金额      468
Name: 9864, dtype: int64
内部标识号    9866
交易次数        2
交易金额      444
Name: 9865, dtype: int64
内部标识号    9867
交易次数       15
交易金额      625
Name: 9866, dtype: int64
内部标识号    9868
交易次数        3
交易金额      174
Name: 9867, dtype: int64
内部标识号    9869
交易次数        3
交易金额      373
Name: 9868, dtype: int64
内部标识号    9870
交易次数        7
交易金额      130
Name: 9869, dtype: int64
内部标识号     9871
交易次数         7
交易金额     38148
Name: 9870, dtype: int64
内部标识号    9872
交易次数       18
交易金额      972
Name: 9871, dtype: int64
内部标识号    9873
交易次数       15
交易金额      687
Name: 9872, dtype: int64
内部标识号    9874
交易次数        2
交易金额      523
Name: 9873, dtype: int64
内部标识号    9875
交易次数       12
交易金额      691
Name: 9874, dtype: int64
内部标识号    9876
交易次数       11
交易金额      908
Name: 9875, dtype: int64
内部标识号     9877
交易次数         5
交易金额     35162
Name: 9876, dtype: int64
内部标识号    9878
交易次数       10
交易金额      495
Name: 9877, dtype: int64
内部标识号     9879
交易次数         6
交易金额     13669
Name: 9878, dtype: int64
内部标识号    9880
交易次数       17
交易金额      896
Name: 9879, dtype: int64
内部标识号    9881
交易次数       11
交易金额      682
Name: 9880, dtype: int64
内部标识号     9882
交易次数       183
交易金额     55213
Name: 9881, dtype: int64
内部标识号    9883
交易次数        1
交易金额     2552
Name: 9882, dtype: int64
内部标识号    9884
交易次数        2
交易金额      951
Name: 9883, dtype: int64
内部标识号    9885
交易次数        1
交易金额      702
Name: 9884, dtype: int64
内部标识号    9886
交易次数       11
交易金额      319
Name: 9885, dtype: int64
内部标识号    9887
交易次数       13
交易金额      535
Name: 9886, dtype: int64
内部标识号    9888
交易次数       14
交易金额      965
Name: 9887, dtype: int64
内部标识号    9889
交易次数        8
交易金额      167
Name: 9888, dtype: int64
内部标识号    9890
交易次数        2
交易金额      433
Name: 9889, dtype: int64
内部标识号    9891
交易次数        5
交易金额      277
Name: 9890, dtype: int64
内部标识号    9892
交易次数       24
交易金额     4331
Name: 9891, dtype: int64
内部标识号    9893
交易次数        2
交易金额      460
Name: 9892, dtype: int64
内部标识号    9894
交易次数       24
交易金额     2724
Name: 9893, dtype: int64
内部标识号    9895
交易次数       29
交易金额     9547
Name: 9894, dtype: int64
内部标识号    9896
交易次数        2
交易金额      305
Name: 9895, dtype: int64
内部标识号    9897
交易次数        3
交易金额      307
Name: 9896, dtype: int64
内部标识号    9898
交易次数        1
交易金额      873
Name: 9897, dtype: int64
内部标识号    9899
交易次数       15
交易金额      885
Name: 9898, dtype: int64
内部标识号     9900
交易次数         7
交易金额     10366
Name: 9899, dtype: int64
内部标识号    9901
交易次数       10
交易金额      300
Name: 9900, dtype: int64
内部标识号    9902
交易次数       16
交易金额     6350
Name: 9901, dtype: int64
内部标识号    9903
交易次数        0
交易金额     3391
Name: 9902, dtype: int64
内部标识号     9904
交易次数         8
交易金额     58995
Name: 9903, dtype: int64
内部标识号    9905
交易次数       26
交易金额      880
Name: 9904, dtype: int64
内部标识号    9906
交易次数        3
交易金额      169
Name: 9905, dtype: int64
内部标识号    9907
交易次数        2
交易金额      825
Name: 9906, dtype: int64
内部标识号    9908
交易次数       14
交易金额      479
Name: 9907, dtype: int64
内部标识号    9909
交易次数       19
交易金额     7793
Name: 9908, dtype: int64
内部标识号    9910
交易次数        7
交易金额      133
Name: 9909, dtype: int64
内部标识号    9911
交易次数       11
交易金额      568
Name: 9910, dtype: int64
内部标识号    9912
交易次数        2
交易金额      471
Name: 9911, dtype: int64
内部标识号     9913
交易次数       178
交易金额     34260
Name: 9912, dtype: int64
内部标识号    9914
交易次数       15
交易金额      961
Name: 9913, dtype: int64
内部标识号    9915
交易次数       28
交易金额     1091
Name: 9914, dtype: int64
内部标识号    9916
交易次数       11
交易金额      760
Name: 9915, dtype: int64
内部标识号    9917
交易次数        3
交易金额      248
Name: 9916, dtype: int64
内部标识号    9918
交易次数       18
交易金额     3722
Name: 9917, dtype: int64
内部标识号    9919
交易次数        9
交易金额      796
Name: 9918, dtype: int64
内部标识号    9920
交易次数        9
交易金额      619
Name: 9919, dtype: int64
内部标识号    9921
交易次数        8
交易金额      897
Name: 9920, dtype: int64
内部标识号    9922
交易次数        3
交易金额      363
Name: 9921, dtype: int64
内部标识号    9923
交易次数        3
交易金额      283
Name: 9922, dtype: int64
内部标识号    9924
交易次数       13
交易金额      450
Name: 9923, dtype: int64
内部标识号    9925
交易次数        4
交易金额      209
Name: 9924, dtype: int64
内部标识号    9926
交易次数       14
交易金额      378
Name: 9925, dtype: int64
内部标识号    9927
交易次数        8
交易金额      365
Name: 9926, dtype: int64
内部标识号    9928
交易次数       19
交易金额     5491
Name: 9927, dtype: int64
内部标识号    9929
交易次数        5
交易金额      137
Name: 9928, dtype: int64
内部标识号    9930
交易次数        8
交易金额      516
Name: 9929, dtype: int64
内部标识号    9931
交易次数       11
交易金额      340
Name: 9930, dtype: int64
内部标识号    9932
交易次数       10
交易金额      807
Name: 9931, dtype: int64
内部标识号    9933
交易次数        7
交易金额      204
Name: 9932, dtype: int64
内部标识号    9934
交易次数        2
交易金额      726
Name: 9933, dtype: int64
内部标识号    9935
交易次数       15
交易金额      426
Name: 9934, dtype: int64
内部标识号    9936
交易次数       11
交易金额      577
Name: 9935, dtype: int64
内部标识号    9937
交易次数        7
交易金额      173
Name: 9936, dtype: int64
内部标识号    9938
交易次数        3
交易金额      264
Name: 9937, dtype: int64
内部标识号    9939
交易次数        7
交易金额      149
Name: 9938, dtype: int64
内部标识号    9940
交易次数        3
交易金额      347
Name: 9939, dtype: int64
内部标识号     9941
交易次数         3
交易金额     73143
Name: 9940, dtype: int64
内部标识号    9942
交易次数        1
交易金额     9066
Name: 9941, dtype: int64
内部标识号    9943
交易次数       11
交易金额      550
Name: 9942, dtype: int64
内部标识号    9944
交易次数       23
交易金额      656
Name: 9943, dtype: int64
内部标识号    9945
交易次数       14
交易金额      769
Name: 9944, dtype: int64
内部标识号    9946
交易次数        2
交易金额      409
Name: 9945, dtype: int64
内部标识号    9947
交易次数        3
交易金额      454
Name: 9946, dtype: int64
内部标识号    9948
交易次数       15
交易金额      630
Name: 9947, dtype: int64
内部标识号    9949
交易次数        3
交易金额      300
Name: 9948, dtype: int64
内部标识号    9950
交易次数       19
交易金额     2483
Name: 9949, dtype: int64
内部标识号    9951
交易次数       28
交易金额      615
Name: 9950, dtype: int64
内部标识号     9952
交易次数         4
交易金额     55781
Name: 9951, dtype: int64
内部标识号    9953
交易次数        3
交易金额      249
Name: 9952, dtype: int64
内部标识号    9954
交易次数       28
交易金额       94
Name: 9953, dtype: int64
内部标识号    9955
交易次数        2
交易金额      375
Name: 9954, dtype: int64
内部标识号    9956
交易次数       27
交易金额     9009
Name: 9955, dtype: int64
内部标识号    9957
交易次数        3
交易金额      369
Name: 9956, dtype: int64
内部标识号    9958
交易次数        3
交易金额      244
Name: 9957, dtype: int64
内部标识号    9959
交易次数        4
交易金额      184
Name: 9958, dtype: int64
内部标识号    9960
交易次数       12
交易金额      673
Name: 9959, dtype: int64
内部标识号     9961
交易次数         5
交易金额     41195
Name: 9960, dtype: int64
内部标识号    9962
交易次数        2
交易金额      371
Name: 9961, dtype: int64
内部标识号    9963
交易次数       22
交易金额      942
Name: 9962, dtype: int64
内部标识号    9964
交易次数        0
交易金额     2957
Name: 9963, dtype: int64
内部标识号    9965
交易次数        8
交易金额      687
Name: 9964, dtype: int64
内部标识号     9966
交易次数        81
交易金额     32392
Name: 9965, dtype: int64
内部标识号     9967
交易次数         6
交易金额     90260
Name: 9966, dtype: int64
内部标识号    9968
交易次数       13
交易金额      418
Name: 9967, dtype: int64
内部标识号    9969
交易次数       14
交易金额      540
Name: 9968, dtype: int64
内部标识号    9970
交易次数        2
交易金额      349
Name: 9969, dtype: int64
内部标识号    9971
交易次数       12
交易金额      388
Name: 9970, dtype: int64
内部标识号     9972
交易次数         4
交易金额     50613
Name: 9971, dtype: int64
内部标识号    9973
交易次数        3
交易金额      349
Name: 9972, dtype: int64
内部标识号    9974
交易次数        1
交易金额      554
Name: 9973, dtype: int64
内部标识号    9975
交易次数       11
交易金额      655
Name: 9974, dtype: int64
内部标识号    9976
交易次数        3
交易金额      421
Name: 9975, dtype: int64
内部标识号    9977
交易次数       12
交易金额      717
Name: 9976, dtype: int64
内部标识号    9978
交易次数       12
交易金额      450
Name: 9977, dtype: int64
内部标识号    9979
交易次数        1
交易金额      955
Name: 9978, dtype: int64
内部标识号    9980
交易次数       15
交易金额     4990
Name: 9979, dtype: int64
内部标识号    9981
交易次数       12
交易金额      373
Name: 9980, dtype: int64
内部标识号    9982
交易次数        8
交易金额      300
Name: 9981, dtype: int64
内部标识号    9983
交易次数       13
交易金额      533
Name: 9982, dtype: int64
内部标识号    9984
交易次数        9
交易金额      909
Name: 9983, dtype: int64
内部标识号    9985
交易次数       15
交易金额       97
Name: 9984, dtype: int64
内部标识号    9986
交易次数        8
交易金额      986
Name: 9985, dtype: int64
内部标识号    9987
交易次数        3
交易金额      453
Name: 9986, dtype: int64
内部标识号    9988
交易次数       16
交易金额     4222
Name: 9987, dtype: int64
内部标识号    9989
交易次数        3
交易金额      387
Name: 9988, dtype: int64
内部标识号    9990
交易次数        2
交易金额      761
Name: 9989, dtype: int64
内部标识号     9991
交易次数       107
交易金额     67648
Name: 9990, dtype: int64
内部标识号    9992
交易次数        6
交易金额      198
Name: 9991, dtype: int64
内部标识号    9993
交易次数       13
交易金额      385
Name: 9992, dtype: int64
内部标识号    9994
交易次数        3
交易金额      114
Name: 9993, dtype: int64
内部标识号    9995
交易次数       25
交易金额       63
Name: 9994, dtype: int64
内部标识号    9996
交易次数        8
交易金额      262
Name: 9995, dtype: int64
内部标识号    9997
交易次数        2
交易金额      712
Name: 9996, dtype: int64
内部标识号    9998
交易次数       10
交易金额      414
Name: 9997, dtype: int64
内部标识号    9999
交易次数        1
交易金额      967
Name: 9998, dtype: int64
内部标识号    10000
交易次数         3
交易金额       284
Name: 9999, dtype: int64
内部标识号    10001
交易次数         3
交易金额       265
Name: 10000, dtype: int64
内部标识号    10002
交易次数        13
交易金额       477
Name: 10001, dtype: int64
内部标识号    10003
交易次数         3
交易金额       271
Name: 10002, dtype: int64
内部标识号    10004
交易次数        11
交易金额       409
Name: 10003, dtype: int64
内部标识号    10005
交易次数         1
交易金额       869
Name: 10004, dtype: int64
内部标识号    10006
交易次数         5
交易金额       119
Name: 10005, dtype: int64
内部标识号    10007
交易次数         8
交易金额       890
Name: 10006, dtype: int64
内部标识号    10008
交易次数        12
交易金额       619
Name: 10007, dtype: int64
内部标识号    10009
交易次数         6
交易金额       102
Name: 10008, dtype: int64
内部标识号    10010
交易次数         1
交易金额      7409
Name: 10009, dtype: int64
内部标识号    10011
交易次数         0
交易金额      4786
Name: 10010, dtype: int64
内部标识号    10012
交易次数        20
交易金额      3052
Name: 10011, dtype: int64
内部标识号    10013
交易次数         2
交易金额       774
Name: 10012, dtype: int64
内部标识号    10014
交易次数        25
交易金额      4065
Name: 10013, dtype: int64
内部标识号    10015
交易次数         1
交易金额      1394
Name: 10014, dtype: int64
内部标识号    10016
交易次数        16
交易金额      3781
Name: 10015, dtype: int64
内部标识号    10017
交易次数         7
交易金额     56956
Name: 10016, dtype: int64
内部标识号    10018
交易次数         8
交易金额       217
Name: 10017, dtype: int64
内部标识号    10019
交易次数         8
交易金额       987
Name: 10018, dtype: int64
内部标识号    10020
交易次数        13
交易金额       419
Name: 10019, dtype: int64
内部标识号    10021
交易次数        10
交易金额       320
Name: 10020, dtype: int64
内部标识号    10022
交易次数         2
交易金额       499
Name: 10021, dtype: int64
内部标识号    10023
交易次数         8
交易金额     15800
Name: 10022, dtype: int64
内部标识号    10024
交易次数         3
交易金额     79203
Name: 10023, dtype: int64
内部标识号    10025
交易次数         3
交易金额       223
Name: 10024, dtype: int64
内部标识号    10026
交易次数        11
交易金额       478
Name: 10025, dtype: int64
内部标识号    10027
交易次数         4
交易金额       300
Name: 10026, dtype: int64
内部标识号    10028
交易次数       281
交易金额     55347
Name: 10027, dtype: int64
内部标识号    10029
交易次数         1
交易金额       882
Name: 10028, dtype: int64
内部标识号    10030
交易次数         8
交易金额       321
Name: 10029, dtype: int64
内部标识号    10031
交易次数        29
交易金额       938
Name: 10030, dtype: int64
内部标识号    10032
交易次数        15
交易金额       866
Name: 10031, dtype: int64
内部标识号    10033
交易次数         2
交易金额       397
Name: 10032, dtype: int64
内部标识号    10034
交易次数         5
交易金额       203
Name: 10033, dtype: int64
内部标识号    10035
交易次数        20
交易金额      6265
Name: 10034, dtype: int64
内部标识号    10036
交易次数         0
交易金额      4477
Name: 10035, dtype: int64
内部标识号    10037
交易次数        30
交易金额       820
Name: 10036, dtype: int64
内部标识号    10038
交易次数         8
交易金额       293
Name: 10037, dtype: int64
内部标识号    10039
交易次数         8
交易金额       158
Name: 10038, dtype: int64
内部标识号    10040
交易次数         1
交易金额      8492
Name: 10039, dtype: int64
内部标识号    10041
交易次数         2
交易金额       329
Name: 10040, dtype: int64
内部标识号    10042
交易次数        15
交易金额       693
Name: 10041, dtype: int64
内部标识号    10043
交易次数         8
交易金额       230
Name: 10042, dtype: int64
内部标识号    10044
交易次数        10
交易金额       403
Name: 10043, dtype: int64
内部标识号    10045
交易次数         2
交易金额       697
Name: 10044, dtype: int64
内部标识号    10046
交易次数         0
交易金额      6647
Name: 10045, dtype: int64
内部标识号    10047
交易次数         1
交易金额       855
Name: 10046, dtype: int64
内部标识号    10048
交易次数         2
交易金额       474
Name: 10047, dtype: int64
内部标识号    10049
交易次数        25
交易金额      7327
Name: 10048, dtype: int64
内部标识号    10050
交易次数         2
交易金额       847
Name: 10049, dtype: int64
内部标识号    10051
交易次数         6
交易金额     54041
Name: 10050, dtype: int64
内部标识号    10052
交易次数         6
交易金额       125
Name: 10051, dtype: int64
内部标识号    10053
交易次数       242
交易金额     17952
Name: 10052, dtype: int64
内部标识号    10054
交易次数         3
交易金额       443
Name: 10053, dtype: int64
内部标识号    10055
交易次数        12
交易金额       399
Name: 10054, dtype: int64
内部标识号    10056
交易次数         3
交易金额       108
Name: 10055, dtype: int64
内部标识号    10057
交易次数         3
交易金额       298

Name: 10214, dtype: int64
内部标识号    10216
交易次数         2
交易金额       486
Name: 10215, dtype: int64
内部标识号    10217
交易次数        11
交易金额       871
Name: 10216, dtype: int64
内部标识号    10218
交易次数         3
交易金额       363
Name: 10217, dtype: int64
内部标识号    10219
交易次数         3
交易金额       458
Name: 10218, dtype: int64
内部标识号    10220
交易次数       154
交易金额     96529
Name: 10219, dtype: int64
内部标识号    10221
交易次数        16
交易金额      7957
Name: 10220, dtype: int64
内部标识号    10222
交易次数         7
交易金额       150
Name: 10221, dtype: int64
内部标识号    10223
交易次数         1
交易金额      8438
Name: 10222, dtype: int64
内部标识号    10224
交易次数        15
交易金额      7050
Name: 10223, dtype: int64
内部标识号    10225
交易次数         3
交易金额       491
Name: 10224, dtype: int64
内部标识号    10226
交易次数         8
交易金额       176
Name: 10225, dtype: int64
内部标识号    10227
交易次数         2
交易金额       486
Name: 10226, dtype: int64
内部标识号    10228
交易次数         6
交易金额       145
Name: 10227, dtype: int64
内部标识号    10229
交易次数         0
交易金额      1528
Name: 10228, dtype: int64
内部标识号    10230
交易次数         0
交易金额      1742
Name: 10229, dtype: int64
内部标识号    10231
交易次数         7
交易金额       129
Name: 10230, dtype: int64
内部标识号    10232
交易次数        10
交易金额       583
Name: 10231, dtype: int64
内部标识号    10233
交易次数         9
交易金额       582
Name: 10232, dtype: int64
内部标识号    10234
交易次数         8
交易金额       228
Name: 10233, dtype: int64
内部标识号    10235
交易次数         5
交易金额       109
Name: 10234, dtype: int64
内部标识号    10236
交易次数         5
交易金额     14477
Name: 10235, dtype: int64
内部标识号    10237
交易次数         5
交易金额       209
Name: 10236, dtype: int64
内部标识号    10238
交易次数        11
交易金额       552
Name: 10237, dtype: int64
内部标识号    10239
交易次数        15
交易金额       363
Name: 10238, dtype: int64
内部标识号    10240
交易次数        19
交易金额        10
Name: 10239, dtype: int64
内部标识号    10241
交易次数        22
交易金额      3003
Name: 10240, dtype: int64
内部标识号    10242
交易次数        13
交易金额       988
Name: 10241, dtype: int64
内部标识号    10243
交易次数        23
交易金额      2431
Name: 10242, dtype: int64
内部标识号    10244
交易次数        12
交易金额       470
Name: 10243, dtype: int64
内部标识号    10245
交易次数         3
交易金额       258
Name: 10244, dtype: int64
内部标识号    10246
交易次数         1
交易金额      8821
Name: 10245, dtype: int64
内部标识号    10247
交易次数        28
交易金额       596
Name: 10246, dtype: int64
内部标识号    10248
交易次数        21
交易金额      9092
Name: 10247, dtype: int64
内部标识号    10249
交易次数         7
交易金额       139
Name: 10248, dtype: int64
内部标识号    10250
交易次数         1
交易金额       972
Name: 10249, dtype: int64
内部标识号    10251
交易次数        13
交易金额      1000
Name: 10250, dtype: int64
内部标识号    10252
交易次数         7
交易金额       174
Name: 10251, dtype: int64
内部标识号    10253
交易次数        15
交易金额       928
Name: 10252, dtype: int64
内部标识号    10254
交易次数       298
交易金额     26166
Name: 10253, dtype: int64
内部标识号    10255
交易次数         6
交易金额       116
Name: 10254, dtype: int64
内部标识号    10256
交易次数         4
交易金额     55727
Name: 10255, dtype: int64
内部标识号    10257
交易次数         1
交易金额       865
Name: 10256, dtype: int64
内部标识号    10258
交易次数         8
交易金额       650
Name: 10257, dtype: int64
内部标识号    10259
交易次数       256
交易金额     57381
Name: 10258, dtype: int64
内部标识号    10260
交易次数         2
交易金额       303
Name: 10259, dtype: int64
内部标识号    10261
交易次数         3
交易金额       170
Name: 10260, dtype: int64
内部标识号    10262
交易次数        14
交易金额       403
Name: 10261, dtype: int64
内部标识号    10263
交易次数         8
交易金额       295
Name: 10262, dtype: int64
内部标识号    10264
交易次数         2
交易金额       472
Name: 10263, dtype: int64
内部标识号    10265
交易次数         2
交易金额       736
Name: 10264, dtype: int64
内部标识号    10266
交易次数        11
交易金额       532
Name: 10265, dtype: int64
内部标识号    10267
交易次数        11
交易金额       315
Name: 10266, dtype: int64
内部标识号    10268
交易次数         2
交易金额       478
Name: 10267, dtype: int64
内部标识号    10269
交易次数         9
交易金额       843
Name: 10268, dtype: int64
内部标识号    10270
交易次数        11
交易金额       981
Name: 10269, dtype: int64
内部标识号    10271
交易次数        13
交易金额       811
Name: 10270, dtype: int64
内部标识号    10272
交易次数         7
交易金额       158
Name: 10271, dtype: int64
内部标识号    10273
交易次数         3
交易金额       315
Name: 10272, dtype: int64
内部标识号    10274
交易次数        16
交易金额       930
Name: 10273, dtype: int64
内部标识号    10275
交易次数         2
交易金额       435
Name: 10274, dtype: int64
内部标识号    10276
交易次数         9
交易金额       837
Name: 10275, dtype: int64
内部标识号    10277
交易次数        12
交易金额       321
Name: 10276, dtype: int64
内部标识号    10278
交易次数         9
交易金额       950
Name: 10277, dtype: int64
内部标识号    10279
交易次数         2
交易金额       324
Name: 10278, dtype: int64
内部标识号    10280
交易次数         6
交易金额     86595
Name: 10279, dtype: int64
内部标识号    10281
交易次数        11
交易金额       325
Name: 10280, dtype: int64
内部标识号    10282
交易次数         8
交易金额       627
Name: 10281, dtype: int64
内部标识号    10283
交易次数        10
交易金额       468
Name: 10282, dtype: int64
内部标识号    10284
交易次数         1
交易金额       510
Name: 10283, dtype: int64
内部标识号    10285
交易次数       272
交易金额     94474
Name: 10284, dtype: int64
内部标识号    10286
交易次数         1
交易金额       658
Name: 10285, dtype: int64
内部标识号    10287
交易次数        15
交易金额       645
Name: 10286, dtype: int64
内部标识号    10288
交易次数        13
交易金额       906
Name: 10287, dtype: int64
内部标识号    10289
交易次数         3
交易金额       345
Name: 10288, dtype: int64
内部标识号    10290
交易次数         9
交易金额       752
Name: 10289, dtype: int64
内部标识号    10291
交易次数        14
交易金额       612
Name: 10290, dtype: int64
内部标识号    10292
交易次数        11
交易金额       945
Name: 10291, dtype: int64
内部标识号    10293
交易次数        21
交易金额       998
Name: 10292, dtype: int64
内部标识号    10294
交易次数         1
交易金额      3578
Name: 10293, dtype: int64
内部标识号    10295
交易次数         6
交易金额       225
Name: 10294, dtype: int64
内部标识号    10296
交易次数         3
交易金额       228
Name: 10295, dtype: int64
内部标识号    10297
交易次数       213
交易金额     56805
Name: 10296, dtype: int64
内部标识号    10298
交易次数       125
交易金额     14545
Name: 10297, dtype: int64
内部标识号    10299
交易次数         7
交易金额       173
Name: 10298, dtype: int64
内部标识号    10300
交易次数        15
交易金额       932
Name: 10299, dtype: int64
内部标识号    10301
交易次数        11
交易金额       360
Name: 10300, dtype: int64
内部标识号    10302
交易次数         3
交易金额       267
Name: 10301, dtype: int64
内部标识号    10303
交易次数         6
交易金额       264
Name: 10302, dtype: int64
内部标识号    10304
交易次数         2
交易金额       560
Name: 10303, dtype: int64
内部标识号    10305
交易次数        10
交易金额       798
Name: 10304, dtype: int64
内部标识号    10306
交易次数         2
交易金额       927
Name: 10305, dtype: int64
内部标识号    10307
交易次数         8
交易金额       968
Name: 10306, dtype: int64
内部标识号    10308
交易次数        14
交易金额       959
Name: 10307, dtype: int64
内部标识号    10309
交易次数        10
交易金额       315
Name: 10308, dtype: int64
内部标识号    10310
交易次数         1
交易金额       911
Name: 10309, dtype: int64
内部标识号    10311
交易次数         5
交易金额       127
Name: 10310, dtype: int64
内部标识号    10312
交易次数        12
交易金额       792
Name: 10311, dtype: int64
内部标识号    10313
交易次数         3
交易金额       372
Name: 10312, dtype: int64
内部标识号    10314
交易次数         0
交易金额      5012
Name: 10313, dtype: int64
内部标识号    10315
交易次数        15
交易金额       976
Name: 10314, dtype: int64
内部标识号    10316
交易次数        10
交易金额       532
Name: 10315, dtype: int64
内部标识号    10317
交易次数        20
交易金额      4716
Name: 10316, dtype: int64
内部标识号    10318
交易次数        14
交易金额       336
Name: 10317, dtype: int64
内部标识号    10319
交易次数         2
交易金额       449
Name: 10318, dtype: int64
内部标识号    10320
交易次数        60
交易金额     64108
Name: 10319, dtype: int64
内部标识号    10321
交易次数        11
交易金额       953
Name: 10320, dtype: int64
内部标识号    10322
交易次数        11
交易金额       421
Name: 10321, dtype: int64
内部标识号    10323
交易次数         9
交易金额       530
Name: 10322, dtype: int64
内部标识号    10324
交易次数         4
交易金额       169
Name: 10323, dtype: int64
内部标识号    10325
交易次数         3
交易金额       486
Name: 10324, dtype: int64
内部标识号    10326
交易次数        10
交易金额       554
Name: 10325, dtype: int64
内部标识号    10327
交易次数         9
交易金额       416
Name: 10326, dtype: int64
内部标识号    10328
交易次数         3
交易金额       407
Name: 10327, dtype: int64
内部标识号    10329
交易次数         1
交易金额       739
Name: 10328, dtype: int64
内部标识号    10330
交易次数        14
交易金额       393
Name: 10329, dtype: int64
内部标识号    10331
交易次数         0
交易金额      4413
Name: 10330, dtype: int64
内部标识号    10332
交易次数        16
交易金额        20
Name: 10331, dtype: int64
内部标识号    10333
交易次数        18
交易金额       945
Name: 10332, dtype: int64
内部标识号    10334
交易次数         3
交易金额     53963
Name: 10333, dtype: int64
内部标识号    10335
交易次数        10
交易金额       332
Name: 10334, dtype: int64
内部标识号    10336
交易次数         3
交易金额       441
Name: 10335, dtype: int64
内部标识号    10337
交易次数         0
交易金额      3950
Name: 10336, dtype: int64
内部标识号    10338
交易次数        14
交易金额       790
Name: 10337, dtype: int64
内部标识号    10339
交易次数         2
交易金额       490
Name: 10338, dtype: int64
内部标识号    10340
交易次数         1
交易金额      5005
Name: 10339, dtype: int64
内部标识号    10341
交易次数         1
交易金额       871
Name: 10340, dtype: int64
内部标识号    10342
交易次数        13
交易金额       563
Name: 10341, dtype: int64
内部标识号    10343
交易次数         3
交易金额       328
Name: 10342, dtype: int64
内部标识号    10344
交易次数         2
交易金额       426
Name: 10343, dtype: int64
内部标识号    10345
交易次数        28
交易金额       657
Name: 10344, dtype: int64
内部标识号    10346
交易次数         9
交易金额       561
Name: 10345, dtype: int64
内部标识号    10347
交易次数         8
交易金额       123
Name: 10346, dtype: int64
内部标识号    10348
交易次数         3
交易金额       170
Name: 10347, dtype: int64
内部标识号    10349
交易次数         6
交易金额       255
Name: 10348, dtype: int64
内部标识号    10350
交易次数         8
交易金额     18107
Name: 10349, dtype: int64
内部标识号    10351
交易次数         1
交易金额       561
Name: 10350, dtype: int64
内部标识号    10352
交易次数        15
交易金额       571
Name: 10351, dtype: int64
内部标识号    10353
交易次数         8
交易金额       304
Name: 10352, dtype: int64
内部标识号    10354
交易次数         9
交易金额       497
Name: 10353, dtype: int64
内部标识号    10355
交易次数         1
交易金额       895
Name: 10354, dtype: int64
内部标识号    10356
交易次数         3
交易金额       343
Name: 10355, dtype: int64
内部标识号    10357
交易次数         1
交易金额       702
Name: 10356, dtype: int64
内部标识号    10358
交易次数       128
交易金额     97593
Name: 10357, dtype: int64
内部标识号    10359
交易次数        12
交易金额       310
Name: 10358, dtype: int64
内部标识号    10360
交易次数         2
交易金额       903
Name: 10359, dtype: int64
内部标识号    10361
交易次数        16
交易金额      3246
Name: 10360, dtype: int64
内部标识号    10362
交易次数        52
交易金额     22711
Name: 10361, dtype: int64
内部标识号    10363
交易次数         2
交易金额       222
Name: 10362, dtype: int64
内部标识号    10364
交易次数        11
交易金额       635
Name: 10363, dtype: int64
内部标识号    10365
交易次数         2
交易金额       432
Name: 10364, dtype: int64
内部标识号    10366
交易次数        29
交易金额       778
Name: 10365, dtype: int64
内部标识号    10367
交易次数         3
交易金额       323
Name: 10366, dtype: int64
内部标识号    10368
交易次数        52
交易金额     86414
Name: 10367, dtype: int64
内部标识号    10369
交易次数        14
交易金额       909
Name: 10368, dtype: int64
内部标识号    10370
交易次数        13
交易金额       867
Name: 10369, dtype: int64
内部标识号    10371
交易次数        22
交易金额       712
Name: 10370, dtype: int64
内部标识号    10372
交易次数         6
交易金额       172
Name: 10371, dtype: int64
内部标识号    10373
交易次数         5
交易金额       246
Name: 10372, dtype: int64
内部标识号    10374
交易次数         2
交易金额       310
Name: 10373, dtype: int64
内部标识号    10375
交易次数         2
交易金额       466
Name: 10374, dtype: int64
内部标识号    10376
交易次数        15
交易金额      2831
Name: 10375, dtype: int64
内部标识号    10377
交易次数        23
交易金额       675
Name: 10376, dtype: int64
内部标识号    10378
交易次数        15
交易金额       531
Name: 10377, dtype: int64
内部标识号    10379
交易次数        14
交易金额       953
Name: 10378, dtype: int64
内部标识号    10380
交易次数         2
交易金额       402
Name: 10379, dtype: int64
内部标识号    10381
交易次数        11
交易金额       594
Name: 10380, dtype: int64
内部标识号    10382
交易次数         6
交易金额       284
Name: 10381, dtype: int64
内部标识号    10383
交易次数         7
交易金额       220
Name: 10382, dtype: int64
内部标识号    10384
交易次数         3
交易金额       340
Name: 10383, dtype: int64
内部标识号    10385
交易次数        15
交易金额       770
Name: 10384, dtype: int64
内部标识号    10386
交易次数        11
交易金额       702
Name: 10385, dtype: int64
内部标识号    10387
交易次数        11
交易金额       720
Name: 10386, dtype: int64
内部标识号    10388
交易次数         1
交易金额       975
Name: 10387, dtype: int64
内部标识号    10389
交易次数         0
交易金额      8720
Name: 10388, dtype: int64
内部标识号    10390
交易次数         4
交易金额       286
Name: 10389, dtype: int64
内部标识号    10391
交易次数         5
交易金额     73524
Name: 10390, dtype: int64
内部标识号    10392
交易次数         1
交易金额       877
Name: 10391, dtype: int64
内部标识号    10393
交易次数        12
交易金额       485
Name: 10392, dtype: int64
内部标识号    10394
交易次数         3
交易金额       465
Name: 10393, dtype: int64
内部标识号    10395
交易次数         2
交易金额       519
Name: 10394, dtype: int64
内部标识号    10396
交易次数         6
交易金额       182
Name: 10395, dtype: int64
内部标识号    10397
交易次数         0
交易金额      3415
Name: 10396, dtype: int64
内部标识号    10398
交易次数         9
交易金额       705
Name: 10397, dtype: int64
内部标识号    10399
交易次数         7
交易金额     83417
Name: 10398, dtype: int64
内部标识号    10400
交易次数        16
交易金额      3412
Name: 10399, dtype: int64
内部标识号    10401
交易次数        11
交易金额       843
Name: 10400, dtype: int64
内部标识号    10402
交易次数         3
交易金额       391
Name: 10401, dtype: int64
内部标识号    10403
交易次数         8
交易金额       324
Name: 10402, dtype: int64
内部标识号    10404
交易次数         5
交易金额       153
Name: 10403, dtype: int64
内部标识号    10405
交易次数        13
交易金额       732
Name: 10404, dtype: int64
内部标识号    10406
交易次数        14
交易金额       537
Name: 10405, dtype: int64
内部标识号    10407
交易次数        13
交易金额       420
Name: 10406, dtype: int64
内部标识号    10408
交易次数        15
交易金额       327
Name: 10407, dtype: int64
内部标识号    10409
交易次数         2
交易金额       576
Name: 10408, dtype: int64
内部标识号    10410
交易次数        13
交易金额       501
Name: 10409, dtype: int64
内部标识号    10411
交易次数         0
交易金额      1156
Name: 10410, dtype: int64
内部标识号    10412
交易次数         0
交易金额      2352
Name: 10411, dtype: int64
内部标识号    10413
交易次数         1
交易金额       593
Name: 10412, dtype: int64
内部标识号    10414
交易次数         4
交易金额       242
Name: 10413, dtype: int64
内部标识号    10415
交易次数         8
交易金额       609
Name: 10414, dtype: int64
内部标识号    10416
交易次数         3
交易金额       166
Name: 10415, dtype: int64
内部标识号    10417
交易次数         8
交易金额       859
Name: 10416, dtype: int64
内部标识号    10418
交易次数         3
交易金额       147
Name: 10417, dtype: int64
内部标识号    10419
交易次数        16
交易金额      4372
Name: 10418, dtype: int64
内部标识号    10420
交易次数        11
交易金额       459
Name: 10419, dtype: int64
内部标识号    10421
交易次数        11
交易金额       756
Name: 10420, dtype: int64
内部标识号    10422
交易次数         9
交易金额       819
Name: 10421, dtype: int64
内部标识号    10423
交易次数         2
交易金额       403
Name: 10422, dtype: int64
内部标识号    10424
交易次数        18
交易金额       612
Name: 10423, dtype: int64
内部标识号    10425
交易次数         9
交易金额       369
Name: 10424, dtype: int64
内部标识号    10426
交易次数         1
交易金额      3279
Name: 10425, dtype: int64
内部标识号    10427
交易次数        14
交易金额       343
Name: 10426, dtype: int64
内部标识号    10428
交易次数         9
交易金额       389
Name: 10427, dtype: int64
内部标识号    10429
交易次数        10
交易金额       556
Name: 10428, dtype: int64
内部标识号    10430
交易次数         3
交易金额       485
Name: 10429, dtype: int64
内部标识号    10431
交易次数         3
交易金额       352
Name: 10430, dtype: int64
内部标识号    10432
交易次数        15
交易金额       392
Name: 10431, dtype: int64
内部标识号    10433
交易次数         4
交易金额     10791
Name: 10432, dtype: int64
内部标识号    10434
交易次数         0
交易金额      9205
Name: 10433, dtype: int64
内部标识号    10435
交易次数         7
交易金额       171
Name: 10434, dtype: int64
内部标识号    10436
交易次数         1
交易金额       890
Name: 10435, dtype: int64
内部标识号    10437
交易次数        20
交易金额       744
Name: 10436, dtype: int64
内部标识号    10438
交易次数        26
交易金额      7126
Name: 10437, dtype: int64
内部标识号    10439
交易次数         8
交易金额       899
Name: 10438, dtype: int64
内部标识号    10440
交易次数         2
交易金额       446
Name: 10439, dtype: int64
内部标识号    10441
交易次数         9
交易金额       947
Name: 10440, dtype: int64
内部标识号    10442
交易次数         3
交易金额       459
Name: 10441, dtype: int64
内部标识号    10443
交易次数        19
交易金额      3676
Name: 10442, dtype: int64
内部标识号    10444
交易次数         8
交易金额       895
Name: 10443, dtype: int64
内部标识号    10445
交易次数        14
交易金额       519
Name: 10444, dtype: int64
内部标识号    10446
交易次数         7
交易金额       247
Name: 10445, dtype: int64
内部标识号    10447
交易次数         4
交易金额       234
Name: 10446, dtype: int64
内部标识号    10448
交易次数         1
交易金额       690
Name: 10447, dtype: int64
内部标识号    10449
交易次数         8
交易金额       980
Name: 10448, dtype: int64
内部标识号    10450
交易次数         8
交易金额       520
Name: 10449, dtype: int64
内部标识号    10451
交易次数         6
交易金额       216
Name: 10450, dtype: int64
内部标识号    10452
交易次数        12
交易金额       695
Name: 10451, dtype: int64
内部标识号    10453
交易次数       231
交易金额     88959
Name: 10452, dtype: int64
内部标识号    10454
交易次数        13
交易金额       704
Name: 10453, dtype: int64
内部标识号    10455
交易次数        10
交易金额       442
Name: 10454, dtype: int64
内部标识号    10456
交易次数         1
交易金额      5489
Name: 10455, dtype: int64
内部标识号    10457
交易次数         2
交易金额       137
Name: 10456, dtype: int64
内部标识号    10458
交易次数         2
交易金额       653
Name: 10457, dtype: int64
内部标识号    10459
交易次数        11
交易金额       380
Name: 10458, dtype: int64
内部标识号    10460
交易次数       230
交易金额     31128
Name: 10459, dtype: int64
内部标识号    10461
交易次数        28
交易金额        52
Name: 10460, dtype: int64
内部标识号    10462
交易次数         8
交易金额       782
Name: 10461, dtype: int64
内部标识号    10463
交易次数         1
交易金额      6914
Name: 10462, dtype: int64
内部标识号    10464
交易次数        25
交易金额      7513
Name: 10463, dtype: int64
内部标识号    10465
交易次数        10
交易金额       847
Name: 10464, dtype: int64
内部标识号    10466
交易次数         0
交易金额      5572
Name: 10465, dtype: int64
内部标识号    10467
交易次数        12
交易金额       760
Name: 10466, dtype: int64
内部标识号    10468
交易次数         2
交易金额       474
Name: 10467, dtype: int64
内部标识号    10469
交易次数        14
交易金额       563
Name: 10468, dtype: int64
内部标识号    10470
交易次数         1
交易金额       890
Name: 10469, dtype: int64
内部标识号    10471
交易次数        25
交易金额      7782
Name: 10470, dtype: int64
内部标识号    10472
交易次数         2
交易金额       909
Name: 10471, dtype: int64
内部标识号    10473
交易次数         1
交易金额      3775
Name: 10472, dtype: int64
内部标识号    10474
交易次数         3
交易金额       456
Name: 10473, dtype: int64
内部标识号    10475
交易次数        12
交易金额       590
Name: 10474, dtype: int64
内部标识号    10476
交易次数        11
交易金额       859
Name: 10475, dtype: int64
内部标识号    10477
交易次数        13
交易金额       799
Name: 10476, dtype: int64
内部标识号    10478
交易次数         1
交易金额      5089
Name: 10477, dtype: int64
内部标识号    10479
交易次数         7
交易金额       193
Name: 10478, dtype: int64
内部标识号    10480
交易次数        11
交易金额       411
Name: 10479, dtype: int64
内部标识号    10481
交易次数        15
交易金额       430
Name: 10480, dtype: int64
内部标识号    10482
交易次数         1
交易金额      4607
Name: 10481, dtype: int64
内部标识号    10483
交易次数        23
交易金额        45
Name: 10482, dtype: int64
内部标识号    10484
交易次数         1
交易金额       670
Name: 10483, dtype: int64
内部标识号    10485
交易次数         3
交易金额       377
Name: 10484, dtype: int64
内部标识号    10486
交易次数         4
交易金额       142
Name: 10485, dtype: int64
内部标识号    10487
交易次数        10
交易金额       392
Name: 10486, dtype: int64
内部标识号    10488
交易次数        12
交易金额       360
Name: 10487, dtype: int64
内部标识号    10489
交易次数        15
交易金额       500
Name: 10488, dtype: int64
内部标识号    10490
交易次数        10
交易金额       423
Name: 10489, dtype: int64
内部标识号    10491
交易次数         9
交易金额       385
Name: 10490, dtype: int64
内部标识号    10492
交易次数         2
交易金额       648
Name: 10491, dtype: int64
内部标识号    10493
交易次数         2
交易金额       800
Name: 10492, dtype: int64
内部标识号    10494
交易次数        29
交易金额       610
Name: 10493, dtype: int64
内部标识号    10495
交易次数         8
交易金额       988
Name: 10494, dtype: int64
内部标识号    10496
交易次数        15
交易金额       458
Name: 10495, dtype: int64
内部标识号    10497

Name: 10537, dtype: int64
内部标识号    10539
交易次数        27
交易金额       633
Name: 10538, dtype: int64
内部标识号    10540
交易次数         2
交易金额       830
Name: 10539, dtype: int64
内部标识号    10541
交易次数        30
交易金额      8382
Name: 10540, dtype: int64
内部标识号    10542
交易次数         2
交易金额       391
Name: 10541, dtype: int64
内部标识号    10543
交易次数         6
交易金额       131
Name: 10542, dtype: int64
内部标识号    10544
交易次数         7
交易金额       139
Name: 10543, dtype: int64
内部标识号    10545
交易次数         4
交易金额     93387
Name: 10544, dtype: int64
内部标识号    10546
交易次数        30
交易金额      6379
Name: 10545, dtype: int64
内部标识号    10547
交易次数         3
交易金额       498
Name: 10546, dtype: int64
内部标识号    10548
交易次数         2
交易金额       462
Name: 10547, dtype: int64
内部标识号    10549
交易次数        25
交易金额      4133
Name: 10548, dtype: int64
内部标识号    10550
交易次数        28
交易金额      3324
Name: 10549, dtype: int64
内部标识号    10551
交易次数         9
交易金额       665
Name: 10550, dtype: int64
内部标识号    10552
交易次数        13
交易金额       729
Name: 10551, dtype: int64
内部标识号    10553
交易次数         8
交易金额       565
Name: 10552, dtype: int64
内部标识号    10554
交易次数        14
交易金额       300
Name: 10553, dtype: int64
内部标识号    10555
交易次数         5
交易金额     15643
Name: 10554, dtype: int64
内部标识号    10556
交易次数        21
交易金额      3729
Name: 10555, dtype: int64
内部标识号    10557
交易次数         3
交易金额       204
Name: 10556, dtype: int64
内部标识号    10558
交易次数         3
交易金额       422
Name: 10557, dtype: int64
内部标识号    10559
交易次数        10
交易金额       481
Name: 10558, dtype: int64
内部标识号    10560
交易次数        20
交易金额      4027
Name: 10559, dtype: int64
内部标识号    10561
交易次数        10
交易金额       976
Name: 10560, dtype: int64
内部标识号    10562
交易次数        12
交易金额       576
Name: 10561, dtype: int64
内部标识号    10563
交易次数         4
交易金额       146
Name: 10562, dtype: int64
内部标识号    10564
交易次数        26
交易金额       593
Name: 10563, dtype: int64
内部标识号    10565
交易次数        15
交易金额       302
Name: 10564, dtype: int64
内部标识号    10566
交易次数         7
交易金额       266
Name: 10565, dtype: int64
内部标识号    10567
交易次数         0
交易金额      1046
Name: 10566, dtype: int64
内部标识号    10568
交易次数         8
交易金额       207
Name: 10567, dtype: int64
内部标识号    10569
交易次数        30
交易金额      3000
Name: 10568, dtype: int64
内部标识号    10570
交易次数         8
交易金额       110
Name: 10569, dtype: int64
内部标识号    10571
交易次数        15
交易金额       306
Name: 10570, dtype: int64
内部标识号    10572
交易次数         9
交易金额       485
Name: 10571, dtype: int64
内部标识号    10573
交易次数         2
交易金额       489
Name: 10572, dtype: int64
内部标识号    10574
交易次数         4
交易金额       208
Name: 10573, dtype: int64
内部标识号    10575
交易次数         8
交易金额       197
Name: 10574, dtype: int64
内部标识号    10576
交易次数        12
交易金额       334
Name: 10575, dtype: int64
内部标识号    10577
交易次数         8
交易金额       420
Name: 10576, dtype: int64
内部标识号    10578
交易次数         3
交易金额       451
Name: 10577, dtype: int64
内部标识号    10579
交易次数        13
交易金额       395
Name: 10578, dtype: int64
内部标识号    10580
交易次数         5
交易金额       173
Name: 10579, dtype: int64
内部标识号    10581
交易次数         7
交易金额       143
Name: 10580, dtype: int64
内部标识号    10582
交易次数        10
交易金额       595
Name: 10581, dtype: int64
内部标识号    10583
交易次数         6
交易金额       277
Name: 10582, dtype: int64
内部标识号    10584
交易次数        21
交易金额        56
Name: 10583, dtype: int64
内部标识号    10585
交易次数        26
交易金额      7037
Name: 10584, dtype: int64
内部标识号    10586
交易次数        14
交易金额       452
Name: 10585, dtype: int64
内部标识号    10587
交易次数        12
交易金额       726
Name: 10586, dtype: int64
内部标识号    10588
交易次数         7
交易金额       262
Name: 10587, dtype: int64
内部标识号    10589
交易次数         2
交易金额       597
Name: 10588, dtype: int64
内部标识号    10590
交易次数         8
交易金额       133
Name: 10589, dtype: int64
内部标识号    10591
交易次数         7
交易金额     86305
Name: 10590, dtype: int64
内部标识号    10592
交易次数         0
交易金额      8225
Name: 10591, dtype: int64
内部标识号    10593
交易次数         0
交易金额      3156
Name: 10592, dtype: int64
内部标识号    10594
交易次数         8
交易金额       766
Name: 10593, dtype: int64
内部标识号    10595
交易次数        13
交易金额       725
Name: 10594, dtype: int64
内部标识号    10596
交易次数         2
交易金额       478
Name: 10595, dtype: int64
内部标识号    10597
交易次数        15
交易金额       750
Name: 10596, dtype: int64
内部标识号    10598
交易次数        14
交易金额       953
Name: 10597, dtype: int64
内部标识号    10599
交易次数        27
交易金额        67
Name: 10598, dtype: int64
内部标识号    10600
交易次数         2
交易金额       388
Name: 10599, dtype: int64
内部标识号    10601
交易次数         8
交易金额       219
Name: 10600, dtype: int64
内部标识号    10602
交易次数        15
交易金额       546
Name: 10601, dtype: int64
内部标识号    10603
交易次数        20
交易金额      4050
Name: 10602, dtype: int64
内部标识号    10604
交易次数        12
交易金额       373
Name: 10603, dtype: int64
内部标识号    10605
交易次数         9
交易金额       649
Name: 10604, dtype: int64
内部标识号    10606
交易次数         0
交易金额      6335
Name: 10605, dtype: int64
内部标识号    10607
交易次数         6
交易金额       199
Name: 10606, dtype: int64
内部标识号    10608
交易次数         2
交易金额       474
Name: 10607, dtype: int64
内部标识号    10609
交易次数        29
交易金额       882
Name: 10608, dtype: int64
内部标识号    10610
交易次数        10
交易金额       603
Name: 10609, dtype: int64
内部标识号    10611
交易次数         2
交易金额       906
Name: 10610, dtype: int64
内部标识号    10612
交易次数         3
交易金额     26601
Name: 10611, dtype: int64
内部标识号    10613
交易次数         2
交易金额       407
Name: 10612, dtype: int64
内部标识号    10614
交易次数        11
交易金额       561
Name: 10613, dtype: int64
内部标识号    10615
交易次数        11
交易金额       646
Name: 10614, dtype: int64
内部标识号    10616
交易次数        27
交易金额      7711
Name: 10615, dtype: int64
内部标识号    10617
交易次数         6
交易金额       112
Name: 10616, dtype: int64
内部标识号    10618
交易次数         8
交易金额       266
Name: 10617, dtype: int64
内部标识号    10619
交易次数         2
交易金额       894
Name: 10618, dtype: int64
内部标识号    10620
交易次数        25
交易金额      5494
Name: 10619, dtype: int64
内部标识号    10621
交易次数         1
交易金额       522
Name: 10620, dtype: int64
内部标识号    10622
交易次数         3
交易金额       425
Name: 10621, dtype: int64
内部标识号    10623
交易次数         6
交易金额       270
Name: 10622, dtype: int64
内部标识号    10624
交易次数         8
交易金额     92420
Name: 10623, dtype: int64
内部标识号    10625
交易次数         8
交易金额       351
Name: 10624, dtype: int64
内部标识号    10626
交易次数       240
交易金额     74904
Name: 10625, dtype: int64
内部标识号    10627
交易次数         3
交易金额       411
Name: 10626, dtype: int64
内部标识号    10628
交易次数         3
交易金额       443
Name: 10627, dtype: int64
内部标识号    10629
交易次数         1
交易金额      4763
Name: 10628, dtype: int64
内部标识号    10630
交易次数         4
交易金额       235
Name: 10629, dtype: int64
内部标识号    10631
交易次数         1
交易金额      6285
Name: 10630, dtype: int64
内部标识号    10632
交易次数       292
交易金额     96669
Name: 10631, dtype: int64
内部标识号    10633
交易次数         7
交易金额       267
Name: 10632, dtype: int64
内部标识号    10634
交易次数         7
交易金额     89809
Name: 10633, dtype: int64
内部标识号    10635
交易次数        10
交易金额       746
Name: 10634, dtype: int64
内部标识号    10636
交易次数         2
交易金额       414
Name: 10635, dtype: int64
内部标识号    10637
交易次数        13
交易金额       353
Name: 10636, dtype: int64
内部标识号    10638
交易次数        12
交易金额       342
Name: 10637, dtype: int64
内部标识号    10639
交易次数         1
交易金额      4459
Name: 10638, dtype: int64
内部标识号    10640
交易次数        15
交易金额       663
Name: 10639, dtype: int64
内部标识号    10641
交易次数        13
交易金额       829
Name: 10640, dtype: int64
内部标识号    10642
交易次数        23
交易金额       666
Name: 10641, dtype: int64
内部标识号    10643
交易次数         8
交易金额       140
Name: 10642, dtype: int64
内部标识号    10644
交易次数         0
交易金额      6514
Name: 10643, dtype: int64
内部标识号    10645
交易次数         0
交易金额      7063
Name: 10644, dtype: int64
内部标识号    10646
交易次数        15
交易金额       993
Name: 10645, dtype: int64
内部标识号    10647
交易次数         3
交易金额       396
Name: 10646, dtype: int64
内部标识号    10648
交易次数        13
交易金额       828
Name: 10647, dtype: int64
内部标识号    10649
交易次数         8
交易金额     93818
Name: 10648, dtype: int64
内部标识号    10650
交易次数        12
交易金额       666
Name: 10649, dtype: int64
内部标识号    10651
交易次数         2
交易金额       286
Name: 10650, dtype: int64
内部标识号    10652
交易次数        26
交易金额        86
Name: 10651, dtype: int64
内部标识号    10653
交易次数         3
交易金额       498
Name: 10652, dtype: int64
内部标识号    10654
交易次数        15
交易金额       554
Name: 10653, dtype: int64
内部标识号    10655
交易次数         8
交易金额       299
Name: 10654, dtype: int64
内部标识号    10656
交易次数         1
交易金额       770
Name: 10655, dtype: int64
内部标识号    10657
交易次数         2
交易金额       494
Name: 10656, dtype: int64
内部标识号    10658
交易次数         0
交易金额      1154
Name: 10657, dtype: int64
内部标识号    10659
交易次数        27
交易金额      1148
Name: 10658, dtype: int64
内部标识号    10660
交易次数         0
交易金额      9460
Name: 10659, dtype: int64
内部标识号    10661
交易次数         3
交易金额       247
Name: 10660, dtype: int64
内部标识号    10662
交易次数         9
交易金额       633
Name: 10661, dtype: int64
内部标识号    10663
交易次数         3
交易金额       181
Name: 10662, dtype: int64
内部标识号    10664
交易次数         8
交易金额       138
Name: 10663, dtype: int64
内部标识号    10665
交易次数         5
交易金额       269
Name: 10664, dtype: int64
内部标识号    10666
交易次数        10
交易金额       673
Name: 10665, dtype: int64
内部标识号    10667
交易次数         3
交易金额       112
Name: 10666, dtype: int64
内部标识号    10668
交易次数        12
交易金额       672
Name: 10667, dtype: int64
内部标识号    10669
交易次数         3
交易金额       475
Name: 10668, dtype: int64
内部标识号    10670
交易次数         9
交易金额       570
Name: 10669, dtype: int64
内部标识号    10671
交易次数         6
交易金额       229
Name: 10670, dtype: int64
内部标识号    10672
交易次数         4
交易金额       161
Name: 10671, dtype: int64
内部标识号    10673
交易次数         7
交易金额       132
Name: 10672, dtype: int64
内部标识号    10674
交易次数         2
交易金额       281
Name: 10673, dtype: int64
内部标识号    10675
交易次数        11
交易金额       694
Name: 10674, dtype: int64
内部标识号    10676
交易次数        24
交易金额      5339
Name: 10675, dtype: int64
内部标识号    10677
交易次数         3
交易金额       115
Name: 10676, dtype: int64
内部标识号    10678
交易次数         8
交易金额       238
Name: 10677, dtype: int64
内部标识号    10679
交易次数        21
交易金额      6682
Name: 10678, dtype: int64
内部标识号    10680
交易次数        13
交易金额       947
Name: 10679, dtype: int64
内部标识号    10681
交易次数         2
交易金额       995
Name: 10680, dtype: int64
内部标识号    10682
交易次数        19
交易金额      5113
Name: 10681, dtype: int64
内部标识号    10683
交易次数         8
交易金额       362
Name: 10682, dtype: int64
内部标识号    10684
交易次数         2
交易金额       401
Name: 10683, dtype: int64
内部标识号    10685
交易次数         8
交易金额       254
Name: 10684, dtype: int64
内部标识号    10686
交易次数        11
交易金额       509
Name: 10685, dtype: int64
内部标识号    10687
交易次数         5
交易金额     22759
Name: 10686, dtype: int64
内部标识号    10688
交易次数         1
交易金额       850
Name: 10687, dtype: int64
内部标识号    10689
交易次数        13
交易金额       929
Name: 10688, dtype: int64
内部标识号    10690
交易次数         2
交易金额       353
Name: 10689, dtype: int64
内部标识号    10691
交易次数        11
交易金额       314
Name: 10690, dtype: int64
内部标识号    10692
交易次数         2
交易金额       431
Name: 10691, dtype: int64
内部标识号    10693
交易次数        15
交易金额      5465
Name: 10692, dtype: int64
内部标识号    10694
交易次数         0
交易金额      2870
Name: 10693, dtype: int64
内部标识号    10695
交易次数         8
交易金额       101
Name: 10694, dtype: int64
内部标识号    10696
交易次数         0
交易金额      6354
Name: 10695, dtype: int64
内部标识号    10697
交易次数        16
交易金额      6660
Name: 10696, dtype: int64
内部标识号    10698
交易次数         2
交易金额       734
Name: 10697, dtype: int64
内部标识号    10699
交易次数        19
交易金额        73
Name: 10698, dtype: int64
内部标识号    10700
交易次数         4
交易金额       108
Name: 10699, dtype: int64
内部标识号    10701
交易次数       196
交易金额     35395
Name: 10700, dtype: int64
内部标识号    10702
交易次数         3
交易金额       101
Name: 10701, dtype: int64
内部标识号    10703
交易次数        23
交易金额       519
Name: 10702, dtype: int64
内部标识号    10704
交易次数        12
交易金额       732
Name: 10703, dtype: int64
内部标识号    10705
交易次数         9
交易金额       900
Name: 10704, dtype: int64
内部标识号    10706
交易次数         0
交易金额      1997
Name: 10705, dtype: int64
内部标识号    10707
交易次数         3
交易金额       345
Name: 10706, dtype: int64
内部标识号    10708
交易次数         2
交易金额       407
Name: 10707, dtype: int64
内部标识号    10709
交易次数         5
交易金额       139
Name: 10708, dtype: int64
内部标识号    10710
交易次数         2
交易金额       350
Name: 10709, dtype: int64
内部标识号    10711
交易次数        13
交易金额       874
Name: 10710, dtype: int64
内部标识号    10712
交易次数         0
交易金额      3724
Name: 10711, dtype: int64
内部标识号    10713
交易次数         8
交易金额       355
Name: 10712, dtype: int64
内部标识号    10714
交易次数         8
交易金额       336
Name: 10713, dtype: int64
内部标识号    10715
交易次数         4
交易金额       232
Name: 10714, dtype: int64
内部标识号    10716
交易次数         8
交易金额       817
Name: 10715, dtype: int64
内部标识号    10717
交易次数         1
交易金额       631
Name: 10716, dtype: int64
内部标识号    10718
交易次数         0
交易金额      2323
Name: 10717, dtype: int64
内部标识号    10719
交易次数        18
交易金额       819
Name: 10718, dtype: int64
内部标识号    10720
交易次数        14
交易金额       644
Name: 10719, dtype: int64
内部标识号    10721
交易次数         9
交易金额       445
Name: 10720, dtype: int64
内部标识号    10722
交易次数         8
交易金额     69665
Name: 10721, dtype: int64
内部标识号    10723
交易次数        13
交易金额       713
Name: 10722, dtype: int64
内部标识号    10724
交易次数         1
交易金额      1139
Name: 10723, dtype: int64
内部标识号    10725
交易次数         1
交易金额      6972
Name: 10724, dtype: int64
内部标识号    10726
交易次数         9
交易金额       656
Name: 10725, dtype: int64
内部标识号    10727
交易次数         8
交易金额       171
Name: 10726, dtype: int64
内部标识号    10728
交易次数         6
交易金额     40912
Name: 10727, dtype: int64
内部标识号    10729
交易次数         6
交易金额       165
Name: 10728, dtype: int64
内部标识号    10730
交易次数        15
交易金额       825
Name: 10729, dtype: int64
内部标识号    10731
交易次数         8
交易金额       966
Name: 10730, dtype: int64
内部标识号    10732
交易次数         3
交易金额       126
Name: 10731, dtype: int64
内部标识号    10733
交易次数        15
交易金额       463
Name: 10732, dtype: int64
内部标识号    10734
交易次数        10
交易金额       890
Name: 10733, dtype: int64
内部标识号    10735
交易次数        30
交易金额         1
Name: 10734, dtype: int64
内部标识号    10736
交易次数         2
交易金额       207
Name: 10735, dtype: int64
内部标识号    10737
交易次数         2
交易金额       372
Name: 10736, dtype: int64
内部标识号    10738
交易次数         3
交易金额       366
Name: 10737, dtype: int64
内部标识号    10739
交易次数         2
交易金额       865
Name: 10738, dtype: int64
内部标识号    10740
交易次数        15
交易金额       960
Name: 10739, dtype: int64
内部标识号    10741
交易次数        14
交易金额       320
Name: 10740, dtype: int64
内部标识号    10742
交易次数        13
交易金额       654
Name: 10741, dtype: int64
内部标识号    10743
交易次数         7
交易金额     48768
Name: 10742, dtype: int64
内部标识号    10744
交易次数        13
交易金额       895
Name: 10743, dtype: int64
内部标识号    10745
交易次数        12
交易金额       930
Name: 10744, dtype: int64
内部标识号    10746
交易次数         8
交易金额     33082
Name: 10745, dtype: int64
内部标识号    10747
交易次数         9
交易金额       873
Name: 10746, dtype: int64
内部标识号    10748
交易次数        12
交易金额       459
Name: 10747, dtype: int64
内部标识号    10749
交易次数         3
交易金额       354
Name: 10748, dtype: int64
内部标识号    10750
交易次数        13
交易金额       578
Name: 10749, dtype: int64
内部标识号    10751
交易次数         5
交易金额       164
Name: 10750, dtype: int64
内部标识号    10752
交易次数        10
交易金额       424
Name: 10751, dtype: int64
内部标识号    10753
交易次数        12
交易金额       738
Name: 10752, dtype: int64
内部标识号    10754
交易次数         2
交易金额       123
Name: 10753, dtype: int64
内部标识号    10755
交易次数        10
交易金额       370
Name: 10754, dtype: int64
内部标识号    10756
交易次数         2
交易金额       838
Name: 10755, dtype: int64
内部标识号    10757
交易次数        27
交易金额       662
Name: 10756, dtype: int64
内部标识号    10758
交易次数        12
交易金额       757
Name: 10757, dtype: int64
内部标识号    10759
交易次数         2
交易金额       445
Name: 10758, dtype: int64
内部标识号    10760
交易次数         3
交易金额     24066
Name: 10759, dtype: int64
内部标识号    10761
交易次数         5
交易金额     35896
Name: 10760, dtype: int64

内部标识号    10762
交易次数        15
交易金额       324
Name: 10761, dtype: int64
内部标识号    10763
交易次数         9
交易金额       530
Name: 10762, dtype: int64
内部标识号    10764
交易次数        15
交易金额       451
Name: 10763, dtype: int64
内部标识号    10765
交易次数         3
交易金额       368
Name: 10764, dtype: int64
内部标识号    10766
交易次数         2
交易金额       868
Name: 10765, dtype: int64
内部标识号    10767
交易次数         2
交易金额       829
Name: 10766, dtype: int64
内部标识号    10768
交易次数       299
交易金额     20726
Name: 10767, dtype: int64
内部标识号    10769
交易次数        12
交易金额       993
Name: 10768, dtype: int64
内部标识号    10770
交易次数         8
交易金额     55081
Name: 10769, dtype: int64
内部标识号    10771
交易次数         4
交易金额       131
Name: 10770, dtype: int64
内部标识号    10772
交易次数         8
交易金额       136
Name: 10771, dtype: int64
内部标识号    10773
交易次数        23
交易金额       668
Name: 10772, dtype: int64
内部标识号    10774
交易次数        15
交易金额       590
Name: 10773, dtype: int64
内部标识号    10775
交易次数        11
交易金额       338
Name: 10774, dtype: int64
内部标识号    10776
交易次数        13
交易金额       307
Name: 10775, dtype: int64
内部标识号    10777
交易次数         1
交易金额       683
Name: 10776, dtype: int64
内部标识号    10778
交易次数         9
交易金额       428
Name: 10777, dtype: int64
内部标识号    10779
交易次数         1
交易金额       933
Name: 10778, dtype: int64
内部标识号    10780
交易次数        12
交易金额       505
Name: 10779, dtype: int64
内部标识号    10781
交易次数        83
交易金额     11774
Name: 10780, dtype: int64
内部标识号    10782
交易次数        10
交易金额       876
Name: 10781, dtype: int64
内部标识号    10783
交易次数         8
交易金额       869
Name: 10782, dtype: int64
内部标识号    10784
交易次数        10
交易金额       354
Name: 10783, dtype: int64
内部标识号    10785
交易次数         4
交易金额       176
Name: 10784, dtype: int64
内部标识号    10786
交易次数         2
交易金额       138
Name: 10785, dtype: int64
内部标识号    10787
交易次数         0
交易金额      3709
Name: 10786, dtype: int64
内部标识号    10788
交易次数         4
交易金额       239
Name: 10787, dtype: int64
内部标识号    10789
交易次数        10
交易金额       414
Name: 10788, dtype: int64
内部标识号    10790
交易次数         8
交易金额       173
Name: 10789, dtype: int64
内部标识号    10791
交易次数         1
交易金额      3258
Name: 10790, dtype: int64
内部标识号    10792
交易次数         3
交易金额       191
Name: 10791, dtype: int64
内部标识号    10793
交易次数        23
交易金额      1363
Name: 10792, dtype: int64
内部标识号    10794
交易次数         2
交易金额       493
Name: 10793, dtype: int64
内部标识号    10795
交易次数         8
交易金额       116
Name: 10794, dtype: int64
内部标识号    10796
交易次数        14
交易金额       788
Name: 10795, dtype: int64
内部标识号    10797
交易次数         3
交易金额       325
Name: 10796, dtype: int64
内部标识号    10798
交易次数         8
交易金额     36581
Name: 10797, dtype: int64
内部标识号    10799
交易次数         2
交易金额       451
Name: 10798, dtype: int64
内部标识号    10800
交易次数         3
交易金额       180
Name: 10799, dtype: int64
内部标识号    10801
交易次数        20
交易金额      3684
Name: 10800, dtype: int64
内部标识号    10802
交易次数         1
交易金额      6143
Name: 10801, dtype: int64
内部标识号    10803
交易次数        92
交易金额     42881
Name: 10802, dtype: int64
内部标识号    10804
交易次数         2
交易金额       213
Name: 10803, dtype: int64
内部标识号    10805
交易次数         8
交易金额       971
Name: 10804, dtype: int64
内部标识号    10806
交易次数         8
交易金额       561
Name: 10805, dtype: int64
内部标识号    10807
交易次数         8
交易金额       780
Name: 10806, dtype: int64
内部标识号    10808
交易次数         3
交易金额       378
Name: 10807, dtype: int64
内部标识号    10809
交易次数         8
交易金额       981
Name: 10808, dtype: int64
内部标识号    10810
交易次数        13
交易金额       689
Name: 10809, dtype: int64
内部标识号    10811
交易次数         5
交易金额       129
Name: 10810, dtype: int64
内部标识号    10812
交易次数         5
交易金额       259
Name: 10811, dtype: int64
内部标识号    10813
交易次数        10
交易金额       326
Name: 10812, dtype: int64
内部标识号    10814
交易次数         7
交易金额     38912
Name: 10813, dtype: int64
内部标识号    10815
交易次数         1
交易金额       867
Name: 10814, dtype: int64
内部标识号    10816
交易次数        12
交易金额       314
Name: 10815, dtype: int64
内部标识号    10817
交易次数         6
交易金额       109
Name: 10816, dtype: int64
内部标识号    10818
交易次数         9
交易金额       500
Name: 10817, dtype: int64
内部标识号    10819
交易次数         4
交易金额     92294
Name: 10818, dtype: int64
内部标识号    10820
交易次数         7
交易金额       241
Name: 10819, dtype: int64
内部标识号    10821
交易次数         2
交易金额       975
Name: 10820, dtype: int64
内部标识号    10822
交易次数         0
交易金额      1774
Name: 10821, dtype: int64
内部标识号    10823
交易次数         1
交易金额       782
Name: 10822, dtype: int64
内部标识号    10824
交易次数         2
交易金额       745
Name: 10823, dtype: int64
内部标识号    10825
交易次数        13
交易金额       798
Name: 10824, dtype: int64
内部标识号    10826
交易次数         2
交易金额       534
Name: 10825, dtype: int64
内部标识号    10827
交易次数         5
交易金额     79146
Name: 10826, dtype: int64
内部标识号    10828
交易次数        12
交易金额       924
Name: 10827, dtype: int64
内部标识号    10829
交易次数         3
交易金额       222
Name: 10828, dtype: int64
内部标识号    10830
交易次数         8
交易金额       780
Name: 10829, dtype: int64
内部标识号    10831
交易次数        23
交易金额      1000
Name: 10830, dtype: int64
内部标识号    10832
交易次数         1
交易金额       915
Name: 10831, dtype: int64
内部标识号    10833
交易次数         3
交易金额       359
Name: 10832, dtype: int64
内部标识号    10834
交易次数         3
交易金额       243
Name: 10833, dtype: int64
内部标识号    10835
交易次数         3
交易金额       500
Name: 10834, dtype: int64
内部标识号    10836
交易次数         1
交易金额      5376
Name: 10835, dtype: int64
内部标识号    10837
交易次数         1
交易金额       673
Name: 10836, dtype: int64
内部标识号    10838
交易次数         6
交易金额       117
Name: 10837, dtype: int64
内部标识号    10839
交易次数         3
交易金额       242
Name: 10838, dtype: int64
内部标识号    10840
交易次数         8
交易金额       498
Name: 10839, dtype: int64
内部标识号    10841
交易次数         5
交易金额     59364
Name: 10840, dtype: int64
内部标识号    10842
交易次数         3
交易金额       203
Name: 10841, dtype: int64
内部标识号    10843
交易次数         2
交易金额       398
Name: 10842, dtype: int64
内部标识号    10844
交易次数         6
交易金额       247
Name: 10843, dtype: int64
内部标识号    10845
交易次数        16
交易金额      9491
Name: 10844, dtype: int64
内部标识号    10846
交易次数         8
交易金额       365
Name: 10845, dtype: int64
内部标识号    10847
交易次数         4
交易金额       174
Name: 10846, dtype: int64
内部标识号    10848
交易次数         6
交易金额       208
Name: 10847, dtype: int64
内部标识号    10849
交易次数         4
交易金额       161
Name: 10848, dtype: int64
内部标识号    10850
交易次数         3
交易金额       478
Name: 10849, dtype: int64
内部标识号    10851
交易次数         3
交易金额       374
Name: 10850, dtype: int64
内部标识号    10852
交易次数         6
交易金额       297
Name: 10851, dtype: int64
内部标识号    10853
交易次数         3
交易金额       238
Name: 10852, dtype: int64
内部标识号    10854
交易次数         7
交易金额       113
Name: 10853, dtype: int64
内部标识号    10855
交易次数        14
交易金额       384
Name: 10854, dtype: int64
内部标识号    10856
交易次数        19
交易金额      3238
Name: 10855, dtype: int64
内部标识号    10857
交易次数       110
交易金额     36233
Name: 10856, dtype: int64
内部标识号    10858
交易次数        12
交易金额       477
Name: 10857, dtype: int64
内部标识号    10859
交易次数         1
交易金额       993
Name: 10858, dtype: int64
内部标识号    10860
交易次数         3
交易金额       231
Name: 10859, dtype: int64
内部标识号    10861
交易次数         0
交易金额      8111
Name: 10860, dtype: int64
内部标识号    10862
交易次数        12
交易金额       439
Name: 10861, dtype: int64
内部标识号    10863
交易次数        11
交易金额       469
Name: 10862, dtype: int64
内部标识号    10864
交易次数         7
交易金额       105
Name: 10863, dtype: int64
内部标识号    10865
交易次数         8
交易金额       964
Name: 10864, dtype: int64
内部标识号    10866
交易次数         8
交易金额     47965
Name: 10865, dtype: int64
内部标识号    10867
交易次数        12
交易金额       865
Name: 10866, dtype: int64
内部标识号    10868
交易次数         3
交易金额       368
Name: 10867, dtype: int64
内部标识号    10869
交易次数         3
交易金额       148
Name: 10868, dtype: int64
内部标识号    10870
交易次数        29
交易金额      5318
Name: 10869, dtype: int64
内部标识号    10871
交易次数         6
交易金额     62248
Name: 10870, dtype: int64
内部标识号    10872
交易次数         2
交易金额       426
Name: 10871, dtype: int64
内部标识号    10873
交易次数        29
交易金额        62
Name: 10872, dtype: int64
内部标识号    10874
交易次数        25
交易金额      4421
Name: 10873, dtype: int64
内部标识号    10875
交易次数         5
交易金额       289
Name: 10874, dtype: int64
内部标识号    10876
交易次数         2
交易金额       478
Name: 10875, dtype: int64
内部标识号    10877
交易次数         1
交易金额       631
Name: 10876, dtype: int64
内部标识号    10878
交易次数        12
交易金额       954
Name: 10877, dtype: int64
内部标识号    10879
交易次数         7
交易金额       142
Name: 10878, dtype: int64
内部标识号    10880
交易次数        14
交易金额       483
Name: 10879, dtype: int64
内部标识号    10881
交易次数        15
交易金额       314
Name: 10880, dtype: int64
内部标识号    10882
交易次数        14
交易金额       743
Name: 10881, dtype: int64
内部标识号    10883
交易次数         5
交易金额       248
Name: 10882, dtype: int64
内部标识号    10884
交易次数        11
交易金额       445
Name: 10883, dtype: int64
内部标识号    10885
交易次数       288
交易金额     20743
Name: 10884, dtype: int64
内部标识号    10886
交易次数        10
交易金额       385
Name: 10885, dtype: int64
内部标识号    10887
交易次数         1
交易金额       914
Name: 10886, dtype: int64
内部标识号    10888
交易次数         5
交易金额       218
Name: 10887, dtype: int64
内部标识号    10889
交易次数        17
交易金额      3887
Name: 10888, dtype: int64
内部标识号    10890
交易次数        10
交易金额       364
Name: 10889, dtype: int64
内部标识号    10891
交易次数        12
交易金额       420
Name: 10890, dtype: int64
内部标识号    10892
交易次数         3
交易金额       260
Name: 10891, dtype: int64
内部标识号    10893
交易次数         0
交易金额      8533
Name: 10892, dtype: int64
内部标识号    10894
交易次数        15
交易金额       826
Name: 10893, dtype: int64
内部标识号    10895
交易次数        10
交易金额       491
Name: 10894, dtype: int64
内部标识号    10896
交易次数        12
交易金额       492
Name: 10895, dtype: int64
内部标识号    10897
交易次数        12
交易金额       566
Name: 10896, dtype: int64
内部标识号    10898
交易次数        11
交易金额       914
Name: 10897, dtype: int64
内部标识号    10899
交易次数         8
交易金额       213
Name: 10898, dtype: int64
内部标识号    10900
交易次数         5
交易金额       214
Name: 10899, dtype: int64
内部标识号    10901
交易次数         8
交易金额       253
Name: 10900, dtype: int64
内部标识号    10902
交易次数         2
交易金额       236
Name: 10901, dtype: int64
内部标识号    10903
交易次数        30
交易金额      4081
Name: 10902, dtype: int64
内部标识号    10904
交易次数         3
交易金额       298
Name: 10903, dtype: int64
内部标识号    10905
交易次数         5
交易金额       218
Name: 10904, dtype: int64
内部标识号    10906
交易次数        28
交易金额      3451
Name: 10905, dtype: int64
内部标识号    10907
交易次数         6
交易金额       202
Name: 10906, dtype: int64
内部标识号    10908
交易次数        15
交易金额       574
Name: 10907, dtype: int64
内部标识号    10909
交易次数        10
交易金额       743
Name: 10908, dtype: int64
内部标识号    10910
交易次数         4
交易金额       214
Name: 10909, dtype: int64
内部标识号    10911
交易次数        15
交易金额      3855
Name: 10910, dtype: int64
内部标识号    10912
交易次数        12
交易金额       527
Name: 10911, dtype: int64
内部标识号    10913
交易次数         4
交易金额       187
Name: 10912, dtype: int64
内部标识号    10914
交易次数         8
交易金额       160
Name: 10913, dtype: int64
内部标识号    10915
交易次数         2
交易金额       554
Name: 10914, dtype: int64
内部标识号    10916
交易次数         0
交易金额      5972
Name: 10915, dtype: int64
内部标识号    10917
交易次数        15
交易金额       548
Name: 10916, dtype: int64
内部标识号    10918
交易次数         0
交易金额      9687
Name: 10917, dtype: int64
内部标识号    10919
交易次数        13
交易金额       838
Name: 10918, dtype: int64
内部标识号    10920
交易次数         3
交易金额       423
Name: 10919, dtype: int64
内部标识号    10921
交易次数         5
交易金额       167
Name: 10920, dtype: int64
内部标识号    10922
交易次数         1
交易金额       936
Name: 10921, dtype: int64
内部标识号    10923
交易次数        14
交易金额       959
Name: 10922, dtype: int64
内部标识号    10924
交易次数         2
交易金额       490
Name: 10923, dtype: int64
内部标识号    10925
交易次数         0
交易金额      8465
Name: 10924, dtype: int64
内部标识号    10926
交易次数        11
交易金额       736
Name: 10925, dtype: int64
内部标识号    10927
交易次数         6
交易金额       284
Name: 10926, dtype: int64
内部标识号    10928
交易次数       188
交易金额     70406
Name: 10927, dtype: int64
内部标识号    10929
交易次数         5
交易金额       116
Name: 10928, dtype: int64
内部标识号    10930
交易次数         3
交易金额       285
Name: 10929, dtype: int64
内部标识号    10931
交易次数        15
交易金额       727
Name: 10930, dtype: int64
内部标识号    10932
交易次数        13
交易金额       663
Name: 10931, dtype: int64
内部标识号    10933
交易次数         2
交易金额       345
Name: 10932, dtype: int64
内部标识号    10934
交易次数        10
交易金额       815
Name: 10933, dtype: int64
内部标识号    10935
交易次数        19
交易金额      8771
Name: 10934, dtype: int64
内部标识号    10936
交易次数        13
交易金额       974
Name: 10935, dtype: int64
内部标识号    10937
交易次数        13
交易金额       448
Name: 10936, dtype: int64
内部标识号    10938
交易次数         4
交易金额       156
Name: 10937, dtype: int64
内部标识号    10939
交易次数         8
交易金额       160
Name: 10938, dtype: int64
内部标识号    10940
交易次数        27
交易金额      8789
Name: 10939, dtype: int64
内部标识号    10941
交易次数         0
交易金额      8737
Name: 10940, dtype: int64
内部标识号    10942
交易次数       193
交易金额     39110
Name: 10941, dtype: int64
内部标识号    10943
交易次数         2
交易金额       118
Name: 10942, dtype: int64
内部标识号    10944
交易次数         3
交易金额       200
Name: 10943, dtype: int64
内部标识号    10945
交易次数         7
交易金额     23764
Name: 10944, dtype: int64
内部标识号    10946
交易次数        30
交易金额      5213
Name: 10945, dtype: int64
内部标识号    10947
交易次数         9
交易金额       486
Name: 10946, dtype: int64
内部标识号    10948
交易次数        11
交易金额       854
Name: 10947, dtype: int64
内部标识号    10949
交易次数       129
交易金额     38638
Name: 10948, dtype: int64
内部标识号    10950
交易次数         0
交易金额      5257
Name: 10949, dtype: int64
内部标识号    10951
交易次数         2
交易金额       347
Name: 10950, dtype: int64
内部标识号    10952
交易次数         5
交易金额       178
Name: 10951, dtype: int64
内部标识号    10953
交易次数        22
交易金额      6708
Name: 10952, dtype: int64
内部标识号    10954
交易次数        11
交易金额       691
Name: 10953, dtype: int64
内部标识号    10955
交易次数        12
交易金额       431
Name: 10954, dtype: int64
内部标识号    10956
交易次数        10
交易金额       442
Name: 10955, dtype: int64
内部标识号    10957
交易次数         8
交易金额       956
Name: 10956, dtype: int64
内部标识号    10958
交易次数         5
交易金额       116
Name: 10957, dtype: int64
内部标识号    10959
交易次数         2
交易金额       538
Name: 10958, dtype: int64
内部标识号    10960
交易次数         6
交易金额       253
Name: 10959, dtype: int64
内部标识号    10961
交易次数         4
交易金额       151
Name: 10960, dtype: int64
内部标识号    10962
交易次数         3
交易金额       358
Name: 10961, dtype: int64
内部标识号    10963
交易次数         2
交易金额       934
Name: 10962, dtype: int64
内部标识号    10964
交易次数         3
交易金额       350
Name: 10963, dtype: int64
内部标识号    10965
交易次数         2
交易金额       339
Name: 10964, dtype: int64
内部标识号    10966
交易次数         3
交易金额       106
Name: 10965, dtype: int64
内部标识号    10967
交易次数         1
交易金额       883
Name: 10966, dtype: int64
内部标识号    10968
交易次数        10
交易金额       336
Name: 10967, dtype: int64
内部标识号    10969
交易次数         2
交易金额       641
Name: 10968, dtype: int64
内部标识号    10970
交易次数         2
交易金额       304
Name: 10969, dtype: int64
内部标识号    10971
交易次数         3
交易金额       335
Name: 10970, dtype: int64
内部标识号    10972
交易次数        24
交易金额       889
Name: 10971, dtype: int64
内部标识号    10973
交易次数        18
交易金额        16
Name: 10972, dtype: int64
内部标识号    10974
交易次数         8
交易金额     15533
Name: 10973, dtype: int64
内部标识号    10975
交易次数        26
交易金额      2429
Name: 10974, dtype: int64
内部标识号    10976
交易次数         5
交易金额     72158
Name: 10975, dtype: int64
内部标识号    10977
交易次数        26
交易金额      9742
Name: 10976, dtype: int64
内部标识号    10978
交易次数         4
交易金额     84207
Name: 10977, dtype: int64
内部标识号    10979
交易次数         5
交易金额       246
Name: 10978, dtype: int64
内部标识号    10980
交易次数         2
交易金额       873
Name: 10979, dtype: int64
内部标识号    10981
交易次数         1
交易金额      8960
Name: 10980, dtype: int64
内部标识号    10982
交易次数        13
交易金额       499
Name: 10981, dtype: int64
内部标识号    10983
交易次数         3
交易金额       398
Name: 10982, dtype: int64
内部标识号    10984
交易次数         0
交易金额      4500
Name: 10983, dtype: int64
内部标识号    10985
交易次数         2
交易金额       409
Name: 10984, dtype: int64
内部标识号    10986
交易次数         5
交易金额       124
Name: 10985, dtype: int64
内部标识号    10987
交易次数         8
交易金额       166
Name: 10986, dtype: int64
内部标识号    10988
交易次数        11
交易金额       987
Name: 10987, dtype: int64
内部标识号    10989
交易次数         3
交易金额       445
Name: 10988, dtype: int64
内部标识号    10990
交易次数         3
交易金额       104
Name: 10989, dtype: int64
内部标识号    10991
交易次数         9
交易金额       889
Name: 10990, dtype: int64
内部标识号    10992
交易次数         7
交易金额     69253
Name: 10991, dtype: int64
内部标识号    10993
交易次数        12
交易金额       338
Name: 10992, dtype: int64
内部标识号    10994
交易次数         5
交易金额       218
Name: 10993, dtype: int64
内部标识号    10995
交易次数        15
交易金额       768
Name: 10994, dtype: int64
内部标识号    10996
交易次数         3
交易金额       131
Name: 10995, dtype: int64
内部标识号    10997
交易次数         3
交易金额       319
Name: 10996, dtype: int64
内部标识号    10998
交易次数       126
交易金额     14527
Name: 10997, dtype: int64
内部标识号    10999
交易次数        10
交易金额       953
Name: 10998, dtype: int64
内部标识号    11000
交易次数        10
交易金额       561
Name: 10999, dtype: int64
内部标识号    11001
交易次数        13
交易金额       357
Name: 11000, dtype: int64
内部标识号    11002
交易次数        14
交易金额       477
Name: 11001, dtype: int64
内部标识号    11003
交易次数         9
交易金额       455
Name: 11002, dtype: int64
内部标识号    11004
交易次数       283
交易金额     54298
Name: 11003, dtype: int64
内部标识号    11005
交易次数        12
交易金额       912
Name: 11004, dtype: int64
内部标识号    11006
交易次数         7
交易金额       207
Name: 11005, dtype: int64
内部标识号    11007
交易次数         3
交易金额       184
Name: 11006, dtype: int64
内部标识号    11008
交易次数        13
交易金额       412
Name: 11007, dtype: int64
内部标识号    11009
交易次数        19
交易金额      1645
Name: 11008, dtype: int64
内部标识号    11010
交易次数        30
交易金额       690
Name: 11009, dtype: int64
内部标识号    11011
交易次数       222
交易金额     36714
Name: 11010, dtype: int64
内部标识号    11012
交易次数         0
交易金额      4809
Name: 11011, dtype: int64
内部标识号    11013
交易次数         9
交易金额       546
Name: 11012, dtype: int64
内部标识号    11014
交易次数        15
交易金额       789
Name: 11013, dtype: int64
内部标识号    11015
交易次数        13
交易金额       781
Name: 11014, dtype: int64
内部标识号    11016
交易次数        22
交易金额      1157
Name: 11015, dtype: int64
内部标识号    11017
交易次数         6
交易金额       142
Name: 11016, dtype: int64
内部标识号    11018
交易次数         4
交易金额       299
Name: 11017, dtype: int64
内部标识号    11019
交易次数         8
交易金额       772
Name: 11018, dtype: int64
内部标识号    11020
交易次数        20
交易金额      1559
Name: 11019, dtype: int64
内部标识号    11021
交易次数         8
交易金额     85134
Name: 11020, dtype: int64
内部标识号    11022
交易次数         3
交易金额       499
Name: 11021, dtype: int64
内部标识号    11023
交易次数         1
交易金额       913
Name: 11022, dtype: int64
内部标识号    11024
交易次数        11
交易金额       307
Name: 11023, dtype: int64
内部标识号    11025
交易次数         1
交易金额       902
Name: 11024, dtype: int64
内部标识号    11026
交易次数        14
交易金额       405
Name: 11025, dtype: int64
内部标识号    11027
交易次数         2
交易金额       605
Name: 11026, dtype: int64
内部标识号    11028
交易次数         0
交易金额      5175
Name: 11027, dtype: int64
内部标识号    11029
交易次数         5
交易金额     58852
Name: 11028, dtype: int64
内部标识号    11030
交易次数         5
交易金额       214
Name: 11029, dtype: int64
内部标识号    11031
交易次数         7
交易金额       263
Name: 11030, dtype: int64
内部标识号    11032
交易次数        17
交易金额      9672
Name: 11031, dtype: int64
内部标识号    11033
交易次数         0
交易金额      2363
Name: 11032, dtype: int64
内部标识号    11034
交易次数        12
交易金额       510
Name: 11033, dtype: int64
内部标识号    11035
交易次数         3
交易金额       273
Name: 11034, dtype: int64
内部标识号    11036
交易次数        25
交易金额       604
Name: 11035, dtype: int64
内部标识号    11037
交易次数         8
交易金额       666
Name: 11036, dtype: int64
内部标识号    11038
交易次数         2
交易金额       324
Name: 11037, dtype: int64
内部标识号    11039
交易次数         2
交易金额       477
Name: 11038, dtype: int64
内部标识号    11040
交易次数        20
交易金额       934
Name: 11039, dtype: int64
内部标识号    11041
交易次数        12
交易金额       303
Name: 11040, dtype: int64
内部标识号    11042
交易次数         1
交易金额       977
Name: 11041, dtype: int64
内部标识号    11043
交易次数        16
交易金额      6694

内部标识号    11191
交易次数       238
交易金额     69242
Name: 11190, dtype: int64
内部标识号    11192
交易次数         5
交易金额     17686
Name: 11191, dtype: int64
内部标识号    11193
交易次数         4
交易金额       288
Name: 11192, dtype: int64
内部标识号    11194
交易次数         3
交易金额       271
Name: 11193, dtype: int64
内部标识号    11195
交易次数        12
交易金额       398
Name: 11194, dtype: int64
内部标识号    11196
交易次数         4
交易金额       144
Name: 11195, dtype: int64
内部标识号    11197
交易次数         8
交易金额       128
Name: 11196, dtype: int64
内部标识号    11198
交易次数         1
交易金额       516
Name: 11197, dtype: int64
内部标识号    11199
交易次数        11
交易金额       387
Name: 11198, dtype: int64
内部标识号    11200
交易次数         4
交易金额       247
Name: 11199, dtype: int64
内部标识号    11201
交易次数         9
交易金额       590
Name: 11200, dtype: int64
内部标识号    11202
交易次数         8
交易金额       352
Name: 11201, dtype: int64
内部标识号    11203
交易次数        19
交易金额        66
Name: 11202, dtype: int64
内部标识号    11204
交易次数        30
交易金额      2681
Name: 11203, dtype: int64
内部标识号    11205
交易次数        23
交易金额      5077
Name: 11204, dtype: int64
内部标识号    11206
交易次数         2
交易金额       374
Name: 11205, dtype: int64
内部标识号    11207
交易次数         4
交易金额       197
Name: 11206, dtype: int64
内部标识号    11208
交易次数         3
交易金额       117
Name: 11207, dtype: int64
内部标识号    11209
交易次数         2
交易金额       393
Name: 11208, dtype: int64
内部标识号    11210
交易次数       140
交易金额     83633
Name: 11209, dtype: int64
内部标识号    11211
交易次数        21
交易金额       866
Name: 11210, dtype: int64
内部标识号    11212
交易次数         4
交易金额       258
Name: 11211, dtype: int64
内部标识号    11213
交易次数        12
交易金额       541
Name: 11212, dtype: int64
内部标识号    11214
交易次数        14
交易金额       688
Name: 11213, dtype: int64
内部标识号    11215
交易次数         8
交易金额       921
Name: 11214, dtype: int64
内部标识号    11216
交易次数        18
交易金额       621
Name: 11215, dtype: int64
内部标识号    11217
交易次数         1
交易金额       516
Name: 11216, dtype: int64
内部标识号    11218
交易次数        30
交易金额       503
Name: 11217, dtype: int64
内部标识号    11219
交易次数        13
交易金额       335
Name: 11218, dtype: int64
内部标识号    11220
交易次数        15
交易金额       533
Name: 11219, dtype: int64
内部标识号    11221
交易次数        25
交易金额       577
Name: 11220, dtype: int64
内部标识号    11222
交易次数         2
交易金额       512
Name: 11221, dtype: int64
内部标识号    11223
交易次数         0
交易金额      9414
Name: 11222, dtype: int64
内部标识号    11224
交易次数         2
交易金额       708
Name: 11223, dtype: int64
内部标识号    11225
交易次数         2
交易金额       831
Name: 11224, dtype: int64
内部标识号    11226
交易次数         3
交易金额       494
Name: 11225, dtype: int64
内部标识号    11227
交易次数        19
交易金额      5284
Name: 11226, dtype: int64
内部标识号    11228
交易次数        12
交易金额       392
Name: 11227, dtype: int64
内部标识号    11229
交易次数         3
交易金额       254
Name: 11228, dtype: int64
内部标识号    11230
交易次数        19
交易金额      6085
Name: 11229, dtype: int64
内部标识号    11231
交易次数        13
交易金额       850
Name: 11230, dtype: int64
内部标识号    11232
交易次数         1
交易金额       534
Name: 11231, dtype: int64
内部标识号    11233
交易次数        10
交易金额       746
Name: 11232, dtype: int64
内部标识号    11234
交易次数        26
交易金额        63
Name: 11233, dtype: int64
内部标识号    11235
交易次数         3
交易金额       169
Name: 11234, dtype: int64
内部标识号    11236
交易次数        11
交易金额       942
Name: 11235, dtype: int64
内部标识号    11237
交易次数        11
交易金额       613
Name: 11236, dtype: int64
内部标识号    11238
交易次数         8
交易金额       180
Name: 11237, dtype: int64
内部标识号    11239
交易次数        11
交易金额       351
Name: 11238, dtype: int64
内部标识号    11240
交易次数         2
交易金额       938
Name: 11239, dtype: int64
内部标识号    11241
交易次数         3
交易金额       434
Name: 11240, dtype: int64
内部标识号    11242
交易次数         0
交易金额      4148
Name: 11241, dtype: int64
内部标识号    11243
交易次数         2
交易金额       968
Name: 11242, dtype: int64
内部标识号    11244
交易次数        15
交易金额      1000
Name: 11243, dtype: int64
内部标识号    11245
交易次数         1
交易金额       817
Name: 11244, dtype: int64
内部标识号    11246
交易次数         8
交易金额       165
Name: 11245, dtype: int64
内部标识号    11247
交易次数         4
交易金额       155
Name: 11246, dtype: int64
内部标识号    11248
交易次数         2
交易金额       869
Name: 11247, dtype: int64
内部标识号    11249
交易次数         8
交易金额       175
Name: 11248, dtype: int64
内部标识号    11250
交易次数        29
交易金额      9651
Name: 11249, dtype: int64
内部标识号    11251
交易次数        21
交易金额        26
Name: 11250, dtype: int64
内部标识号    11252
交易次数         9
交易金额       315
Name: 11251, dtype: int64
内部标识号    11253
交易次数         9
交易金额       922
Name: 11252, dtype: int64
内部标识号    11254
交易次数         1
交易金额       788
Name: 11253, dtype: int64
内部标识号    11255
交易次数        13
交易金额       410
Name: 11254, dtype: int64
内部标识号    11256
交易次数         1
交易金额      6021
Name: 11255, dtype: int64
内部标识号    11257
交易次数         3
交易金额       116
Name: 11256, dtype: int64
内部标识号    11258
交易次数         8
交易金额     44875
Name: 11257, dtype: int64
内部标识号    11259
交易次数         3
交易金额       426
Name: 11258, dtype: int64
内部标识号    11260
交易次数         3
交易金额       460
Name: 11259, dtype: int64
内部标识号    11261
交易次数         0
交易金额      1548
Name: 11260, dtype: int64
内部标识号    11262
交易次数         0
交易金额      5309
Name: 11261, dtype: int64
内部标识号    11263
交易次数         0
交易金额      7032
Name: 11262, dtype: int64
内部标识号    11264
交易次数        13
交易金额       433
Name: 11263, dtype: int64
内部标识号    11265
交易次数         0
交易金额      8886
Name: 11264, dtype: int64
内部标识号    11266
交易次数         3
交易金额       242
Name: 11265, dtype: int64
内部标识号    11267
交易次数        16
交易金额       688
Name: 11266, dtype: int64
内部标识号    11268
交易次数        10
交易金额       408
Name: 11267, dtype: int64
内部标识号    11269
交易次数         5
交易金额       274
Name: 11268, dtype: int64
内部标识号    11270
交易次数         4
交易金额       274
Name: 11269, dtype: int64
内部标识号    11271
交易次数        10
交易金额       795
Name: 11270, dtype: int64
内部标识号    11272
交易次数        21
交易金额      7102
Name: 11271, dtype: int64
内部标识号    11273
交易次数        96
交易金额     56983
Name: 11272, dtype: int64
内部标识号    11274
交易次数         8
交易金额     77272
Name: 11273, dtype: int64
内部标识号    11275
交易次数        14
交易金额       864
Name: 11274, dtype: int64
内部标识号    11276
交易次数         8
交易金额       345
Name: 11275, dtype: int64
内部标识号    11277
交易次数         6
交易金额       140
Name: 11276, dtype: int64
内部标识号    11278
交易次数         2
交易金额       673
Name: 11277, dtype: int64
内部标识号    11279
交易次数        12
交易金额       584
Name: 11278, dtype: int64
内部标识号    11280
交易次数        14
交易金额       941
Name: 11279, dtype: int64
内部标识号    11281
交易次数         8
交易金额       805
Name: 11280, dtype: int64
内部标识号    11282
交易次数         8
交易金额     82293
Name: 11281, dtype: int64
内部标识号    11283
交易次数         1
交易金额       969
Name: 11282, dtype: int64
内部标识号    11284
交易次数         2
交易金额       993
Name: 11283, dtype: int64
内部标识号    11285
交易次数        15
交易金额       517
Name: 11284, dtype: int64
内部标识号    11286
交易次数        11
交易金额       585
Name: 11285, dtype: int64
内部标识号    11287
交易次数        26
交易金额      6545
Name: 11286, dtype: int64
内部标识号    11288
交易次数         5
交易金额     83599
Name: 11287, dtype: int64
内部标识号    11289
交易次数         9
交易金额       372
Name: 11288, dtype: int64
内部标识号    11290
交易次数        15
交易金额       702
Name: 11289, dtype: int64
内部标识号    11291
交易次数         2
交易金额       575
Name: 11290, dtype: int64
内部标识号    11292
交易次数         3
交易金额       473
Name: 11291, dtype: int64
内部标识号    11293
交易次数        13
交易金额       591
Name: 11292, dtype: int64
内部标识号    11294
交易次数         9
交易金额       868
Name: 11293, dtype: int64
内部标识号    11295
交易次数        12
交易金额       392
Name: 11294, dtype: int64
内部标识号    11296
交易次数         3
交易金额       436
Name: 11295, dtype: int64
内部标识号    11297
交易次数         9
交易金额       793
Name: 11296, dtype: int64
内部标识号    11298
交易次数         2
交易金额       775
Name: 11297, dtype: int64
内部标识号    11299
交易次数         0
交易金额      4357
Name: 11298, dtype: int64
内部标识号    11300
交易次数        12
交易金额       568
Name: 11299, dtype: int64
内部标识号    11301
交易次数         3
交易金额       493
Name: 11300, dtype: int64
内部标识号    11302
交易次数        17
交易金额       742
Name: 11301, dtype: int64
内部标识号    11303
交易次数         2
交易金额       421
Name: 11302, dtype: int64
内部标识号    11304
交易次数         1
交易金额       820
Name: 11303, dtype: int64
内部标识号    11305
交易次数         2
交易金额       456
Name: 11304, dtype: int64
内部标识号    11306
交易次数         2
交易金额       469
Name: 11305, dtype: int64
内部标识号    11307
交易次数        16
交易金额      8080
Name: 11306, dtype: int64
内部标识号    11308
交易次数         8
交易金额       228
Name: 11307, dtype: int64
内部标识号    11309
交易次数         2
交易金额       361
Name: 11308, dtype: int64
内部标识号    11310
交易次数         3
交易金额       371
Name: 11309, dtype: int64
内部标识号    11311
交易次数         7
交易金额       190
Name: 11310, dtype: int64
内部标识号    11312
交易次数         6
交易金额       139
Name: 11311, dtype: int64
内部标识号    11313
交易次数         2
交易金额       571
Name: 11312, dtype: int64
内部标识号    11314
交易次数        13
交易金额       467
Name: 11313, dtype: int64
内部标识号    11315
交易次数         5
交易金额       297
Name: 11314, dtype: int64
内部标识号    11316
交易次数         3
交易金额       426
Name: 11315, dtype: int64
内部标识号    11317
交易次数         4
交易金额     27148
Name: 11316, dtype: int64
内部标识号    11318
交易次数        69
交易金额     61393
Name: 11317, dtype: int64
内部标识号    11319
交易次数         2
交易金额       377
Name: 11318, dtype: int64
内部标识号    11320
交易次数         0
交易金额      3177
Name: 11319, dtype: int64
内部标识号    11321
交易次数        11
交易金额       924
Name: 11320, dtype: int64
内部标识号    11322
交易次数         2
交易金额       116
Name: 11321, dtype: int64
内部标识号    11323
交易次数         3
交易金额       306
Name: 11322, dtype: int64
内部标识号    11324
交易次数         2
交易金额       349
Name: 11323, dtype: int64
内部标识号    11325
交易次数        19
交易金额       924
Name: 11324, dtype: int64
内部标识号    11326
交易次数         2
交易金额       441
Name: 11325, dtype: int64
内部标识号    11327
交易次数         8
交易金额       144
Name: 11326, dtype: int64
内部标识号    11328
交易次数        12
交易金额       698
Name: 11327, dtype: int64
内部标识号    11329
交易次数         0
交易金额      2554
Name: 11328, dtype: int64
内部标识号    11330
交易次数        13
交易金额       509
Name: 11329, dtype: int64
内部标识号    11331
交易次数        10
交易金额       889
Name: 11330, dtype: int64
内部标识号    11332
交易次数         0
交易金额      2227
Name: 11331, dtype: int64
内部标识号    11333
交易次数        13
交易金额       557
Name: 11332, dtype: int64
内部标识号    11334
交易次数        28
交易金额      6693
Name: 11333, dtype: int64
内部标识号    11335
交易次数        18
交易金额       639
Name: 11334, dtype: int64
内部标识号    11336
交易次数         1
交易金额       719
Name: 11335, dtype: int64
内部标识号    11337
交易次数         2
交易金额       399
Name: 11336, dtype: int64
内部标识号    11338
交易次数        12
交易金额       733
Name: 11337, dtype: int64
内部标识号    11339
交易次数        10
交易金额       814
Name: 11338, dtype: int64
内部标识号    11340
交易次数        11
交易金额       337
Name: 11339, dtype: int64
内部标识号    11341
交易次数        11
交易金额       596
Name: 11340, dtype: int64
内部标识号    11342
交易次数         5
交易金额       240
Name: 11341, dtype: int64
内部标识号    11343
交易次数         1
交易金额       653
Name: 11342, dtype: int64
内部标识号    11344
交易次数         8
交易金额       251
Name: 11343, dtype: int64
内部标识号    11345
交易次数        30
交易金额      9410
Name: 11344, dtype: int64
内部标识号    11346
交易次数         8
交易金额       676
Name: 11345, dtype: int64
内部标识号    11347
交易次数        13
交易金额       481
Name: 11346, dtype: int64
内部标识号    11348
交易次数         2
交易金额       121
Name: 11347, dtype: int64
内部标识号    11349
交易次数         1
交易金额       606
Name: 11348, dtype: int64
内部标识号    11350
交易次数         2
交易金额       337
Name: 11349, dtype: int64
内部标识号    11351
交易次数         5
交易金额       215
Name: 11350, dtype: int64
内部标识号    11352
交易次数         2
交易金额       437
Name: 11351, dtype: int64
内部标识号    11353
交易次数         9
交易金额       637
Name: 11352, dtype: int64
内部标识号    11354
交易次数        11
交易金额       607
Name: 11353, dtype: int64
内部标识号    11355
交易次数         1
交易金额      4074
Name: 11354, dtype: int64
内部标识号    11356
交易次数         6
交易金额     51929
Name: 11355, dtype: int64
内部标识号    11357
交易次数         2
交易金额       344
Name: 11356, dtype: int64
内部标识号    11358
交易次数         4
交易金额       148
Name: 11357, dtype: int64
内部标识号    11359
交易次数         5
交易金额       189
Name: 11358, dtype: int64
内部标识号    11360
交易次数        15
交易金额      3401
Name: 11359, dtype: int64
内部标识号    11361
交易次数       174
交易金额     22767
Name: 11360, dtype: int64
内部标识号    11362
交易次数         8
交易金额       757
Name: 11361, dtype: int64
内部标识号    11363
交易次数         3
交易金额       137
Name: 11362, dtype: int64
内部标识号    11364
交易次数        26
交易金额       761
Name: 11363, dtype: int64
内部标识号    11365
交易次数         6
交易金额     79519
Name: 11364, dtype: int64
内部标识号    11366
交易次数         2
交易金额       395
Name: 11365, dtype: int64
内部标识号    11367
交易次数         1
交易金额       923
Name: 11366, dtype: int64
内部标识号    11368
交易次数         7
交易金额       134
Name: 11367, dtype: int64
内部标识号    11369
交易次数         1
交易金额      4581
Name: 11368, dtype: int64
内部标识号    11370
交易次数         3
交易金额       295
Name: 11369, dtype: int64
内部标识号    11371
交易次数        16
交易金额      3276
Name: 11370, dtype: int64
内部标识号    11372
交易次数        22
交易金额        14
Name: 11371, dtype: int64
内部标识号    11373
交易次数        15
交易金额       327
Name: 11372, dtype: int64
内部标识号    11374
交易次数         2
交易金额       287
Name: 11373, dtype: int64
内部标识号    11375
交易次数         4
交易金额       141
Name: 11374, dtype: int64
内部标识号    11376
交易次数         8
交易金额       557
Name: 11375, dtype: int64
内部标识号    11377
交易次数         0
交易金额      8911
Name: 11376, dtype: int64
内部标识号    11378
交易次数        13
交易金额       474
Name: 11377, dtype: int64
内部标识号    11379
交易次数         7
交易金额     59698
Name: 11378, dtype: int64
内部标识号    11380
交易次数        15
交易金额       514
Name: 11379, dtype: int64
内部标识号    11381
交易次数         0
交易金额      6325
Name: 11380, dtype: int64
内部标识号    11382
交易次数        11
交易金额       358
Name: 11381, dtype: int64
内部标识号    11383
交易次数        20
交易金额       695
Name: 11382, dtype: int64
内部标识号    11384
交易次数         4
交易金额       221
Name: 11383, dtype: int64
内部标识号    11385
交易次数        12
交易金额       796
Name: 11384, dtype: int64
内部标识号    11386
交易次数         3
交易金额     26864
Name: 11385, dtype: int64
内部标识号    11387
交易次数         1
交易金额      8109
Name: 11386, dtype: int64
内部标识号    11388
交易次数        17
交易金额       709
Name: 11387, dtype: int64
内部标识号    11389
交易次数         0
交易金额      7606
Name: 11388, dtype: int64
内部标识号    11390
交易次数         3
交易金额       313
Name: 11389, dtype: int64
内部标识号    11391
交易次数         9
交易金额       423
Name: 11390, dtype: int64
内部标识号    11392
交易次数         3
交易金额       162
Name: 11391, dtype: int64
内部标识号    11393
交易次数         2
交易金额       151
Name: 11392, dtype: int64
内部标识号    11394
交易次数        30
交易金额       660
Name: 11393, dtype: int64
内部标识号    11395
交易次数         2
交易金额       350
Name: 11394, dtype: int64
内部标识号    11396
交易次数         1
交易金额       771
Name: 11395, dtype: int64
内部标识号    11397
交易次数        12
交易金额       494
Name: 11396, dtype: int64
内部标识号    11398
交易次数         7
交易金额       260
Name: 11397, dtype: int64
内部标识号    11399
交易次数        10
交易金额       585
Name: 11398, dtype: int64
内部标识号    11400
交易次数        13
交易金额       785
Name: 11399, dtype: int64
内部标识号    11401
交易次数        13
交易金额       638
Name: 11400, dtype: int64
内部标识号    11402
交易次数        21
交易金额      7636
Name: 11401, dtype: int64
内部标识号    11403
交易次数        12
交易金额       790
Name: 11402, dtype: int64
内部标识号    11404
交易次数         5
交易金额     24932
Name: 11403, dtype: int64
内部标识号    11405
交易次数         8
交易金额       110
Name: 11404, dtype: int64
内部标识号    11406
交易次数        10
交易金额       570
Name: 11405, dtype: int64
内部标识号    11407
交易次数         2
交易金额       953
Name: 11406, dtype: int64
内部标识号    11408
交易次数         9
交易金额       507
Name: 11407, dtype: int64
内部标识号    11409
交易次数        22
交易金额        56
Name: 11408, dtype: int64
内部标识号    11410
交易次数       237
交易金额     90831
Name: 11409, dtype: int64
内部标识号    11411
交易次数         0
交易金额      5948
Name: 11410, dtype: int64
内部标识号    11412
交易次数        28
交易金额      2512
Name: 11411, dtype: int64
内部标识号    11413
交易次数         5
交易金额       136
Name: 11412, dtype: int64
内部标识号    11414
交易次数       118
交易金额     97218
Name: 11413, dtype: int64
内部标识号    11415
交易次数         4
交易金额       164
Name: 11414, dtype: int64
内部标识号    11416
交易次数        16
交易金额      2333
Name: 11415, dtype: int64
内部标识号    11417
交易次数         8
交易金额       899
Name: 11416, dtype: int64
内部标识号    11418
交易次数         0
交易金额      8707
Name: 11417, dtype: int64
内部标识号    11419
交易次数        21
交易金额      7057
Name: 11418, dtype: int64
内部标识号    11420
交易次数        16
交易金额       862
Name: 11419, dtype: int64
内部标识号    11421
交易次数         1
交易金额       835
Name: 11420, dtype: int64
内部标识号    11422
交易次数       257
交易金额     68337
Name: 11421, dtype: int64
内部标识号    11423
交易次数        14
交易金额       627
Name: 11422, dtype: int64
内部标识号    11424
交易次数        13
交易金额       483
Name: 11423, dtype: int64
内部标识号    11425
交易次数        22
交易金额        62
Name: 11424, dtype: int64
内部标识号    11426
交易次数        30
交易金额       642
Name: 11425, dtype: int64
内部标识号    11427
交易次数         5
交易金额       156
Name: 11426, dtype: int64
内部标识号    11428
交易次数         2
交易金额       771
Name: 11427, dtype: int64
内部标识号    11429
交易次数         8
交易金额       234
Name: 11428, dtype: int64
内部标识号    11430
交易次数         6
交易金额     43294
Name: 11429, dtype: int64
内部标识号    11431
交易次数         0
交易金额      6986
Name: 11430, dtype: int64
内部标识号    11432
交易次数       192
交易金额     15357
Name: 11431, dtype: int64
内部标识号    11433
交易次数         1
交易金额      7605
Name: 11432, dtype: int64
内部标识号    11434
交易次数         1
交易金额       551
Name: 11433, dtype: int64
内部标识号    11435
交易次数         2
交易金额       346
Name: 11434, dtype: int64
内部标识号    11436
交易次数        25
交易金额      1965
Name: 11435, dtype: int64
内部标识号    11437
交易次数         5
交易金额     22278
Name: 11436, dtype: int64
内部标识号    11438
交易次数        12
交易金额       666
Name: 11437, dtype: int64
内部标识号    11439
交易次数         9
交易金额       918
Name: 11438, dtype: int64
内部标识号    11440
交易次数         9
交易金额       912
Name: 11439, dtype: int64
内部标识号    11441
交易次数       240
交易金额     41073
Name: 11440, dtype: int64
内部标识号    11442
交易次数        13
交易金额       579
Name: 11441, dtype: int64
内部标识号    11443
交易次数        11
交易金额       373
Name: 11442, dtype: int64
内部标识号    11444
交易次数         8
交易金额       452
Name: 11443, dtype: int64
内部标识号    11445
交易次数        12
交易金额       917
Name: 11444, dtype: int64
内部标识号    11446
交易次数        21
交易金额        45
Name: 11445, dtype: int64
内部标识号    11447
交易次数        14
交易金额       551
Name: 11446, dtype: int64
内部标识号    11448
交易次数        13
交易金额       684
Name: 11447, dtype: int64
内部标识号    11449
交易次数         5
交易金额       270
Name: 11448, dtype: int64
内部标识号    11450
交易次数        11
交易金额       311
Name: 11449, dtype: int64
内部标识号    11451
交易次数       208
交易金额     68326
Name: 11450, dtype: int64
内部标识号    11452
交易次数         5
交易金额       184
Name: 11451, dtype: int64
内部标识号    11453
交易次数         6
交易金额       240
Name: 11452, dtype: int64
内部标识号    11454
交易次数         0
交易金额      7189
Name: 11453, dtype: int64
内部标识号    11455
交易次数       104
交易金额     69209
Name: 11454, dtype: int64
内部标识号    11456
交易次数         6
交易金额     21757
Name: 11455, dtype: int64
内部标识号    11457
交易次数         5
交易金额       295
Name: 11456, dtype: int64
内部标识号    11458
交易次数         8
交易金额     11113
Name: 11457, dtype: int64
内部标识号    11459
交易次数        26
交易金额      2591
Name: 11458, dtype: int64
内部标识号    11460
交易次数         8
交易金额       117
Name: 11459, dtype: int64
内部标识号    11461
交易次数         7
交易金额       119
Name: 11460, dtype: int64
内部标识号    11462
交易次数        11
交易金额       600
Name: 11461, dtype: int64
内部标识号    11463
交易次数         3
交易金额       429
Name: 11462, dtype: int64
内部标识号    11464
交易次数         4
交易金额       105
Name: 11463, dtype: int64
内部标识号    11465
交易次数         3
交易金额       157
Name: 11464, dtype: int64
内部标识号    11466
交易次数         1
交易金额       754
Name: 11465, dtype: int64
内部标识号    11467
交易次数        23
交易金额      2986
Name: 11466, dtype: int64
内部标识号    11468
交易次数       138
交易金额     34146
Name: 11467, dtype: int64
内部标识号    11469
交易次数         9
交易金额       742
Name: 11468, dtype: int64
内部标识号    11470
交易次数        15
交易金额       853
Name: 11469, dtype: int64
内部标识号    11471
交易次数        11
交易金额       585
Name: 11470, dtype: int64
内部标识号    11472
交易次数        23
交易金额      2107

Name: 11545, dtype: int64
内部标识号    11547
交易次数         5
交易金额       155
Name: 11546, dtype: int64
内部标识号    11548
交易次数        15
交易金额       928
Name: 11547, dtype: int64
内部标识号    11549
交易次数         8
交易金额       353
Name: 11548, dtype: int64
内部标识号    11550
交易次数         3
交易金额     11444
Name: 11549, dtype: int64
内部标识号    11551
交易次数         2
交易金额       456
Name: 11550, dtype: int64
内部标识号    11552
交易次数         2
交易金额       123
Name: 11551, dtype: int64
内部标识号    11553
交易次数         3
交易金额       500
Name: 11552, dtype: int64
内部标识号    11554
交易次数        12
交易金额       610
Name: 11553, dtype: int64
内部标识号    11555
交易次数        10
交易金额       898
Name: 11554, dtype: int64
内部标识号    11556
交易次数         2
交易金额       487
Name: 11555, dtype: int64
内部标识号    11557
交易次数        11
交易金额       975
Name: 11556, dtype: int64
内部标识号    11558
交易次数         1
交易金额      4229
Name: 11557, dtype: int64
内部标识号    11559
交易次数        27
交易金额      2684
Name: 11558, dtype: int64
内部标识号    11560
交易次数        14
交易金额       399
Name: 11559, dtype: int64
内部标识号    11561
交易次数         2
交易金额       380
Name: 11560, dtype: int64
内部标识号    11562
交易次数         2
交易金额       361
Name: 11561, dtype: int64
内部标识号    11563
交易次数        24
交易金额      1724
Name: 11562, dtype: int64
内部标识号    11564
交易次数        11
交易金额       808
Name: 11563, dtype: int64
内部标识号    11565
交易次数        10
交易金额       323
Name: 11564, dtype: int64
内部标识号    11566
交易次数        13
交易金额       967
Name: 11565, dtype: int64
内部标识号    11567
交易次数         2
交易金额       676
Name: 11566, dtype: int64
内部标识号    11568
交易次数        15
交易金额       431
Name: 11567, dtype: int64
内部标识号    11569
交易次数        11
交易金额       482
Name: 11568, dtype: int64
内部标识号    11570
交易次数         8
交易金额       126
Name: 11569, dtype: int64
内部标识号    11571
交易次数         0
交易金额      8410
Name: 11570, dtype: int64
内部标识号    11572
交易次数         5
交易金额       159
Name: 11571, dtype: int64
内部标识号    11573
交易次数         2
交易金额       738
Name: 11572, dtype: int64
内部标识号    11574
交易次数         1
交易金额       618
Name: 11573, dtype: int64
内部标识号    11575
交易次数         2
交易金额       614
Name: 11574, dtype: int64
内部标识号    11576
交易次数       295
交易金额     12724
Name: 11575, dtype: int64
内部标识号    11577
交易次数         9
交易金额       426
Name: 11576, dtype: int64
内部标识号    11578
交易次数        10
交易金额       626
Name: 11577, dtype: int64
内部标识号    11579
交易次数         3
交易金额       344
Name: 11578, dtype: int64
内部标识号    11580
交易次数         2
交易金额       489
Name: 11579, dtype: int64
内部标识号    11581
交易次数        18
交易金额       896
Name: 11580, dtype: int64
内部标识号    11582
交易次数         1
交易金额       639
Name: 11581, dtype: int64
内部标识号    11583
交易次数         1
交易金额      3230
Name: 11582, dtype: int64
内部标识号    11584
交易次数        10
交易金额       859
Name: 11583, dtype: int64
内部标识号    11585
交易次数         4
交易金额       116
Name: 11584, dtype: int64
内部标识号    11586
交易次数         1
交易金额      7203
Name: 11585, dtype: int64
内部标识号    11587
交易次数         5
交易金额       217
Name: 11586, dtype: int64
内部标识号    11588
交易次数         0
交易金额      5589
Name: 11587, dtype: int64
内部标识号    11589
交易次数         2
交易金额       948
Name: 11588, dtype: int64
内部标识号    11590
交易次数         3
交易金额       322
Name: 11589, dtype: int64
内部标识号    11591
交易次数         1
交易金额      5918
Name: 11590, dtype: int64
内部标识号    11592
交易次数        13
交易金额       316
Name: 11591, dtype: int64
内部标识号    11593
交易次数         4
交易金额       115
Name: 11592, dtype: int64
内部标识号    11594
交易次数         5
交易金额       297
Name: 11593, dtype: int64
内部标识号    11595
交易次数         3
交易金额       345
Name: 11594, dtype: int64
内部标识号    11596
交易次数         3
交易金额       308
Name: 11595, dtype: int64
内部标识号    11597
交易次数        16
交易金额      1779
Name: 11596, dtype: int64
内部标识号    11598
交易次数         9
交易金额       452
Name: 11597, dtype: int64
内部标识号    11599
交易次数        14
交易金额       777
Name: 11598, dtype: int64
内部标识号    11600
交易次数        21
交易金额      6180
Name: 11599, dtype: int64
内部标识号    11601
交易次数        15
交易金额       407
Name: 11600, dtype: int64
内部标识号    11602
交易次数        10
交易金额       996
Name: 11601, dtype: int64
内部标识号    11603
交易次数         1
交易金额      6197
Name: 11602, dtype: int64
内部标识号    11604
交易次数         3
交易金额       276
Name: 11603, dtype: int64
内部标识号    11605
交易次数         3
交易金额       345
Name: 11604, dtype: int64
内部标识号    11606
交易次数         4
交易金额       166
Name: 11605, dtype: int64
内部标识号    11607
交易次数         2
交易金额       476
Name: 11606, dtype: int64
内部标识号    11608
交易次数         3
交易金额       244
Name: 11607, dtype: int64
内部标识号    11609
交易次数        29
交易金额       982
Name: 11608, dtype: int64
内部标识号    11610
交易次数         1
交易金额       938
Name: 11609, dtype: int64
内部标识号    11611
交易次数         3
交易金额       244
Name: 11610, dtype: int64
内部标识号    11612
交易次数         0
交易金额      3252
Name: 11611, dtype: int64
内部标识号    11613
交易次数        16
交易金额      9183
Name: 11612, dtype: int64
内部标识号    11614
交易次数         9
交易金额       430
Name: 11613, dtype: int64
内部标识号    11615
交易次数         7
交易金额       132
Name: 11614, dtype: int64
内部标识号    11616
交易次数        13
交易金额       579
Name: 11615, dtype: int64
内部标识号    11617
交易次数         8
交易金额       247
Name: 11616, dtype: int64
内部标识号    11618
交易次数         2
交易金额       382
Name: 11617, dtype: int64
内部标识号    11619
交易次数        24
交易金额       741
Name: 11618, dtype: int64
内部标识号    11620
交易次数         8
交易金额       428
Name: 11619, dtype: int64
内部标识号    11621
交易次数        29
交易金额      2311
Name: 11620, dtype: int64
内部标识号    11622
交易次数        13
交易金额       937
Name: 11621, dtype: int64
内部标识号    11623
交易次数         3
交易金额       350
Name: 11622, dtype: int64
内部标识号    11624
交易次数        24
交易金额       510
Name: 11623, dtype: int64
内部标识号    11625
交易次数         2
交易金额       335
Name: 11624, dtype: int64
内部标识号    11626
交易次数        34
交易金额     28288
Name: 11625, dtype: int64
内部标识号    11627
交易次数         5
交易金额       149
Name: 11626, dtype: int64
内部标识号    11628
交易次数         0
交易金额      9469
Name: 11627, dtype: int64
内部标识号    11629
交易次数         3
交易金额       347
Name: 11628, dtype: int64
内部标识号    11630
交易次数         1
交易金额       971
Name: 11629, dtype: int64
内部标识号    11631
交易次数         5
交易金额     18405
Name: 11630, dtype: int64
内部标识号    11632
交易次数         3
交易金额       466
Name: 11631, dtype: int64
内部标识号    11633
交易次数        15
交易金额       307
Name: 11632, dtype: int64
内部标识号    11634
交易次数        12
交易金额       740
Name: 11633, dtype: int64
内部标识号    11635
交易次数        26
交易金额      7090
Name: 11634, dtype: int64
内部标识号    11636
交易次数         4
交易金额       285
Name: 11635, dtype: int64
内部标识号    11637
交易次数         6
交易金额     57537
Name: 11636, dtype: int64
内部标识号    11638
交易次数        12
交易金额       470
Name: 11637, dtype: int64
内部标识号    11639
交易次数         9
交易金额       422
Name: 11638, dtype: int64
内部标识号    11640
交易次数         7
交易金额       227
Name: 11639, dtype: int64
内部标识号    11641
交易次数         2
交易金额       161
Name: 11640, dtype: int64
内部标识号    11642
交易次数         5
交易金额       114
Name: 11641, dtype: int64
内部标识号    11643
交易次数        13
交易金额       386
Name: 11642, dtype: int64
内部标识号    11644
交易次数         0
交易金额      2688
Name: 11643, dtype: int64
内部标识号    11645
交易次数         8
交易金额     34939
Name: 11644, dtype: int64
内部标识号    11646
交易次数         0
交易金额      5623
Name: 11645, dtype: int64
内部标识号    11647
交易次数         3
交易金额       341
Name: 11646, dtype: int64
内部标识号    11648
交易次数        12
交易金额       419
Name: 11647, dtype: int64
内部标识号    11649
交易次数         1
交易金额       747
Name: 11648, dtype: int64
内部标识号    11650
交易次数         9
交易金额       340
Name: 11649, dtype: int64
内部标识号    11651
交易次数        13
交易金额       818
Name: 11650, dtype: int64
内部标识号    11652
交易次数        55
交易金额     16182
Name: 11651, dtype: int64
内部标识号    11653
交易次数         9
交易金额       326
Name: 11652, dtype: int64
内部标识号    11654
交易次数        11
交易金额       430
Name: 11653, dtype: int64
内部标识号    11655
交易次数       151
交易金额     73152
Name: 11654, dtype: int64
内部标识号    11656
交易次数         2
交易金额       317
Name: 11655, dtype: int64
内部标识号    11657
交易次数       114
交易金额     59177
Name: 11656, dtype: int64
内部标识号    11658
交易次数         0
交易金额      3495
Name: 11657, dtype: int64
内部标识号    11659
交易次数        12
交易金额       853
Name: 11658, dtype: int64
内部标识号    11660
交易次数         2
交易金额       944
Name: 11659, dtype: int64
内部标识号    11661
交易次数        26
交易金额       725
Name: 11660, dtype: int64
内部标识号    11662
交易次数         2
交易金额       927
Name: 11661, dtype: int64
内部标识号    11663
交易次数        16
交易金额      5635
Name: 11662, dtype: int64
内部标识号    11664
交易次数         1
交易金额       990
Name: 11663, dtype: int64
内部标识号    11665
交易次数         1
交易金额       723
Name: 11664, dtype: int64
内部标识号    11666
交易次数        19
交易金额      4477
Name: 11665, dtype: int64
内部标识号    11667
交易次数        14
交易金额       774
Name: 11666, dtype: int64
内部标识号    11668
交易次数         4
交易金额       177
Name: 11667, dtype: int64
内部标识号    11669
交易次数        15
交易金额       876
Name: 11668, dtype: int64
内部标识号    11670
交易次数         1
交易金额      7278
Name: 11669, dtype: int64
内部标识号    11671
交易次数         1
交易金额      4420
Name: 11670, dtype: int64
内部标识号    11672
交易次数         3
交易金额       134
Name: 11671, dtype: int64
内部标识号    11673
交易次数         2
交易金额       292
Name: 11672, dtype: int64
内部标识号    11674
交易次数         3
交易金额       231
Name: 11673, dtype: int64
内部标识号    11675
交易次数         3
交易金额       368
Name: 11674, dtype: int64
内部标识号    11676
交易次数         9
交易金额       673
Name: 11675, dtype: int64
内部标识号    11677
交易次数        13
交易金额       636
Name: 11676, dtype: int64
内部标识号    11678
交易次数         6
交易金额       298
Name: 11677, dtype: int64
内部标识号    11679
交易次数         2
交易金额       399
Name: 11678, dtype: int64
内部标识号    11680
交易次数         6
交易金额       201
Name: 11679, dtype: int64
内部标识号    11681
交易次数        12
交易金额       579
Name: 11680, dtype: int64
内部标识号    11682
交易次数         8
交易金额       103
Name: 11681, dtype: int64
内部标识号    11683
交易次数        16
交易金额      8281
Name: 11682, dtype: int64
内部标识号    11684
交易次数         9
交易金额       942
Name: 11683, dtype: int64
内部标识号    11685
交易次数         5
交易金额       284
Name: 11684, dtype: int64
内部标识号    11686
交易次数        23
交易金额      6834
Name: 11685, dtype: int64
内部标识号    11687
交易次数         0
交易金额      6723
Name: 11686, dtype: int64
内部标识号    11688
交易次数         3
交易金额       331
Name: 11687, dtype: int64
内部标识号    11689
交易次数        11
交易金额       977
Name: 11688, dtype: int64
内部标识号    11690
交易次数        10
交易金额       663
Name: 11689, dtype: int64
内部标识号    11691
交易次数        10
交易金额       533
Name: 11690, dtype: int64
内部标识号    11692
交易次数         5
交易金额       265
Name: 11691, dtype: int64
内部标识号    11693
交易次数        14
交易金额       523
Name: 11692, dtype: int64
内部标识号    11694
交易次数         2
交易金额       308
Name: 11693, dtype: int64
内部标识号    11695
交易次数         2
交易金额       588
Name: 11694, dtype: int64
内部标识号    11696
交易次数        13
交易金额       406
Name: 11695, dtype: int64
内部标识号    11697
交易次数         0
交易金额      3757
Name: 11696, dtype: int64
内部标识号    11698
交易次数         1
交易金额      5377
Name: 11697, dtype: int64
内部标识号    11699
交易次数         0
交易金额      6452
Name: 11698, dtype: int64
内部标识号    11700
交易次数        14
交易金额       431
Name: 11699, dtype: int64
内部标识号    11701
交易次数         3
交易金额       500
Name: 11700, dtype: int64
内部标识号    11702
交易次数        13
交易金额       476
Name: 11701, dtype: int64
内部标识号    11703
交易次数         2
交易金额       255
Name: 11702, dtype: int64
内部标识号    11704
交易次数        12
交易金额       555
Name: 11703, dtype: int64
内部标识号    11705
交易次数        14
交易金额       911
Name: 11704, dtype: int64
内部标识号    11706
交易次数        14
交易金额       699
Name: 11705, dtype: int64
内部标识号    11707
交易次数         2
交易金额       469
Name: 11706, dtype: int64
内部标识号    11708
交易次数        30
交易金额      5181
Name: 11707, dtype: int64
内部标识号    11709
交易次数         8
交易金额       207
Name: 11708, dtype: int64
内部标识号    11710
交易次数         9
交易金额       490
Name: 11709, dtype: int64
内部标识号    11711
交易次数        15
交易金额       678
Name: 11710, dtype: int64
内部标识号    11712
交易次数        24
交易金额      8912
Name: 11711, dtype: int64
内部标识号    11713
交易次数        10
交易金额       679
Name: 11712, dtype: int64
内部标识号    11714
交易次数         0
交易金额      6489
Name: 11713, dtype: int64
内部标识号    11715
交易次数         8
交易金额       166
Name: 11714, dtype: int64
内部标识号    11716
交易次数         7
交易金额       220
Name: 11715, dtype: int64
内部标识号    11717
交易次数         4
交易金额       259
Name: 11716, dtype: int64
内部标识号    11718
交易次数        19
交易金额      9980
Name: 11717, dtype: int64
内部标识号    11719
交易次数        17
交易金额      1858
Name: 11718, dtype: int64
内部标识号    11720
交易次数         4
交易金额       142
Name: 11719, dtype: int64
内部标识号    11721
交易次数         1
交易金额       983
Name: 11720, dtype: int64
内部标识号    11722
交易次数         7
交易金额       253
Name: 11721, dtype: int64
内部标识号    11723
交易次数        14
交易金额       999
Name: 11722, dtype: int64
内部标识号    11724
交易次数        14
交易金额       909
Name: 11723, dtype: int64
内部标识号    11725
交易次数        17
交易金额      5434
Name: 11724, dtype: int64
内部标识号    11726
交易次数        21
交易金额      3733
Name: 11725, dtype: int64
内部标识号    11727
交易次数        14
交易金额       305
Name: 11726, dtype: int64
内部标识号    11728
交易次数        10
交易金额       370
Name: 11727, dtype: int64
内部标识号    11729
交易次数         3
交易金额       244
Name: 11728, dtype: int64
内部标识号    11730
交易次数        12
交易金额       600
Name: 11729, dtype: int64
内部标识号    11731
交易次数        15
交易金额       760
Name: 11730, dtype: int64
内部标识号    11732
交易次数        10
交易金额       303
Name: 11731, dtype: int64
内部标识号    11733
交易次数        11
交易金额       813
Name: 11732, dtype: int64
内部标识号    11734
交易次数         6
交易金额     41913
Name: 11733, dtype: int64
内部标识号    11735
交易次数         3
交易金额       245
Name: 11734, dtype: int64
内部标识号    11736
交易次数         3
交易金额       194
Name: 11735, dtype: int64
内部标识号    11737
交易次数       292
交易金额     84928
Name: 11736, dtype: int64
内部标识号    11738
交易次数         2
交易金额       780
Name: 11737, dtype: int64
内部标识号    11739
交易次数         6
交易金额       114
Name: 11738, dtype: int64
内部标识号    11740
交易次数        11
交易金额       527
Name: 11739, dtype: int64
内部标识号    11741
交易次数        11
交易金额       357
Name: 11740, dtype: int64
内部标识号    11742
交易次数         2
交易金额       466
Name: 11741, dtype: int64
内部标识号    11743
交易次数         2
交易金额       106
Name: 11742, dtype: int64
内部标识号    11744
交易次数         3
交易金额       463
Name: 11743, dtype: int64
内部标识号    11745
交易次数        15
交易金额       556
Name: 11744, dtype: int64
内部标识号    11746
交易次数       216
交易金额     44350
Name: 11745, dtype: int64
内部标识号    11747
交易次数         2
交易金额       456
Name: 11746, dtype: int64
内部标识号    11748
交易次数         3
交易金额       402
Name: 11747, dtype: int64
内部标识号    11749
交易次数         3
交易金额       188
Name: 11748, dtype: int64
内部标识号    11750
交易次数        22
交易金额      4029
Name: 11749, dtype: int64
内部标识号    11751
交易次数        12
交易金额       820
Name: 11750, dtype: int64
内部标识号    11752
交易次数        13
交易金额       879
Name: 11751, dtype: int64
内部标识号    11753
交易次数        14
交易金额       429
Name: 11752, dtype: int64
内部标识号    11754
交易次数         0
交易金额      5483
Name: 11753, dtype: int64
内部标识号    11755
交易次数         2
交易金额       259
Name: 11754, dtype: int64
内部标识号    11756
交易次数        30
交易金额       981
Name: 11755, dtype: int64
内部标识号    11757
交易次数         9
交易金额       539
Name: 11756, dtype: int64
内部标识号    11758
交易次数         8
交易金额       257
Name: 11757, dtype: int64
内部标识号    11759
交易次数         3
交易金额       297
Name: 11758, dtype: int64
内部标识号    11760
交易次数         8
交易金额       901

Name: 11759, dtype: int64
内部标识号    11761
交易次数        13
交易金额       828
Name: 11760, dtype: int64
内部标识号    11762
交易次数       232
交易金额     81051
Name: 11761, dtype: int64
内部标识号    11763
交易次数         9
交易金额       957
Name: 11762, dtype: int64
内部标识号    11764
交易次数        29
交易金额      6370
Name: 11763, dtype: int64
内部标识号    11765
交易次数         2
交易金额       417
Name: 11764, dtype: int64
内部标识号    11766
交易次数         4
交易金额       158
Name: 11765, dtype: int64
内部标识号    11767
交易次数        15
交易金额       420
Name: 11766, dtype: int64
内部标识号    11768
交易次数         1
交易金额       893
Name: 11767, dtype: int64
内部标识号    11769
交易次数         1
交易金额       777
Name: 11768, dtype: int64
内部标识号    11770
交易次数        10
交易金额       421
Name: 11769, dtype: int64
内部标识号    11771
交易次数        26
交易金额      5066
Name: 11770, dtype: int64
内部标识号    11772
交易次数         4
交易金额       257
Name: 11771, dtype: int64
内部标识号    11773
交易次数         4
交易金额       269
Name: 11772, dtype: int64
内部标识号    11774
交易次数        16
交易金额       841
Name: 11773, dtype: int64
内部标识号    11775
交易次数         5
交易金额     88333
Name: 11774, dtype: int64
内部标识号    11776
交易次数        11
交易金额       739
Name: 11775, dtype: int64
内部标识号    11777
交易次数        14
交易金额       342
Name: 11776, dtype: int64
内部标识号    11778
交易次数         1
交易金额       580
Name: 11777, dtype: int64
内部标识号    11779
交易次数         5
交易金额       199
Name: 11778, dtype: int64
内部标识号    11780
交易次数       225
交易金额     22511
Name: 11779, dtype: int64
内部标识号    11781
交易次数         3
交易金额       112
Name: 11780, dtype: int64
内部标识号    11782
交易次数         0
交易金额      3098
Name: 11781, dtype: int64
内部标识号    11783
交易次数        15
交易金额       895
Name: 11782, dtype: int64
内部标识号    11784
交易次数         2
交易金额       353
Name: 11783, dtype: int64
内部标识号    11785
交易次数         0
交易金额      7349
Name: 11784, dtype: int64
内部标识号    11786
交易次数         8
交易金额       579
Name: 11785, dtype: int64
内部标识号    11787
交易次数         2
交易金额       573
Name: 11786, dtype: int64
内部标识号    11788
交易次数         2
交易金额       105
Name: 11787, dtype: int64
内部标识号    11789
交易次数         8
交易金额       216
Name: 11788, dtype: int64
内部标识号    11790
交易次数        12
交易金额       331
Name: 11789, dtype: int64
内部标识号    11791
交易次数        14
交易金额       815
Name: 11790, dtype: int64
内部标识号    11792
交易次数        15
交易金额       372
Name: 11791, dtype: int64
内部标识号    11793
交易次数        14
交易金额       549
Name: 11792, dtype: int64
内部标识号    11794
交易次数        12
交易金额       909
Name: 11793, dtype: int64
内部标识号    11795
交易次数        10
交易金额       740
Name: 11794, dtype: int64
内部标识号    11796
交易次数        19
交易金额      2689
Name: 11795, dtype: int64
内部标识号    11797
交易次数        15
交易金额       996
Name: 11796, dtype: int64
内部标识号    11798
交易次数       143
交易金额     82911
Name: 11797, dtype: int64
内部标识号    11799
交易次数         2
交易金额       432
Name: 11798, dtype: int64
内部标识号    11800
交易次数         2
交易金额       969
Name: 11799, dtype: int64
内部标识号    11801
交易次数         5
交易金额     90509
Name: 11800, dtype: int64
内部标识号    11802
交易次数         2
交易金额       385
Name: 11801, dtype: int64
内部标识号    11803
交易次数         8
交易金额       125
Name: 11802, dtype: int64
内部标识号    11804
交易次数        10
交易金额       990
Name: 11803, dtype: int64
内部标识号    11805
交易次数        10
交易金额       317
Name: 11804, dtype: int64
内部标识号    11806
交易次数        10
交易金额       425
Name: 11805, dtype: int64
内部标识号    11807
交易次数        13
交易金额       839
Name: 11806, dtype: int64
内部标识号    11808
交易次数         3
交易金额       300
Name: 11807, dtype: int64
内部标识号    11809
交易次数         1
交易金额       731
Name: 11808, dtype: int64
内部标识号    11810
交易次数         1
交易金额       956
Name: 11809, dtype: int64
内部标识号    11811
交易次数         3
交易金额       324
Name: 11810, dtype: int64
内部标识号    11812
交易次数         8
交易金额       247
Name: 11811, dtype: int64
内部标识号    11813
交易次数         8
交易金额       383
Name: 11812, dtype: int64
内部标识号    11814
交易次数         6
交易金额       166
Name: 11813, dtype: int64
内部标识号    11815
交易次数         1
交易金额       908
Name: 11814, dtype: int64
内部标识号    11816
交易次数         9
交易金额       624
Name: 11815, dtype: int64
内部标识号    11817
交易次数         4
交易金额       184
Name: 11816, dtype: int64
内部标识号    11818
交易次数         6
交易金额       237
Name: 11817, dtype: int64
内部标识号    11819
交易次数        12
交易金额       460
Name: 11818, dtype: int64
内部标识号    11820
交易次数         2
交易金额       343
Name: 11819, dtype: int64
内部标识号    11821
交易次数       177
交易金额     55983
Name: 11820, dtype: int64
内部标识号    11822
交易次数         3
交易金额       404
Name: 11821, dtype: int64
内部标识号    11823
交易次数         3
交易金额       468
Name: 11822, dtype: int64
内部标识号    11824
交易次数        12
交易金额       462
Name: 11823, dtype: int64
内部标识号    11825
交易次数        13
交易金额       523
Name: 11824, dtype: int64
内部标识号    11826
交易次数         8
交易金额       755
Name: 11825, dtype: int64
内部标识号    11827
交易次数         1
交易金额       916
Name: 11826, dtype: int64
内部标识号    11828
交易次数         5
交易金额       166
Name: 11827, dtype: int64
内部标识号    11829
交易次数         8
交易金额       327
Name: 11828, dtype: int64
内部标识号    11830
交易次数        13
交易金额       702
Name: 11829, dtype: int64
内部标识号    11831
交易次数         8
交易金额     38934
Name: 11830, dtype: int64
内部标识号    11832
交易次数         2
交易金额       457
Name: 11831, dtype: int64
内部标识号    11833
交易次数        28
交易金额       556
Name: 11832, dtype: int64
内部标识号    11834
交易次数         8
交易金额       667
Name: 11833, dtype: int64
内部标识号    11835
交易次数         2
交易金额       324
Name: 11834, dtype: int64
内部标识号    11836
交易次数        27
交易金额      7600
Name: 11835, dtype: int64
内部标识号    11837
交易次数         2
交易金额       703
Name: 11836, dtype: int64
内部标识号    11838
交易次数         1
交易金额       733
Name: 11837, dtype: int64
内部标识号    11839
交易次数         1
交易金额       852
Name: 11838, dtype: int64
内部标识号    11840
交易次数         2
交易金额       488
Name: 11839, dtype: int64
内部标识号    11841
交易次数        20
交易金额      6200
Name: 11840, dtype: int64
内部标识号    11842
交易次数         8
交易金额       789
Name: 11841, dtype: int64
内部标识号    11843
交易次数         7
交易金额       174
Name: 11842, dtype: int64
内部标识号    11844
交易次数        13
交易金额       569
Name: 11843, dtype: int64
内部标识号    11845
交易次数         1
交易金额       614
Name: 11844, dtype: int64
内部标识号    11846
交易次数        12
交易金额       950
Name: 11845, dtype: int64
内部标识号    11847
交易次数         8
交易金额       913
Name: 11846, dtype: int64
内部标识号    11848
交易次数         8
交易金额       772
Name: 11847, dtype: int64
内部标识号    11849
交易次数         4
交易金额       184
Name: 11848, dtype: int64
内部标识号    11850
交易次数        15
交易金额       304
Name: 11849, dtype: int64
内部标识号    11851
交易次数         1
交易金额       593
Name: 11850, dtype: int64
内部标识号    11852
交易次数         4
交易金额       251
Name: 11851, dtype: int64
内部标识号    11853
交易次数        50
交易金额     25368
Name: 11852, dtype: int64
内部标识号    11854
交易次数         0
交易金额      9966
Name: 11853, dtype: int64
内部标识号    11855
交易次数         3
交易金额       222
Name: 11854, dtype: int64
内部标识号    11856
交易次数         2
交易金额       323
Name: 11855, dtype: int64
内部标识号    11857
交易次数         2
交易金额       301
Name: 11856, dtype: int64
内部标识号    11858
交易次数         3
交易金额       307
Name: 11857, dtype: int64
内部标识号    11859
交易次数         4
交易金额       138
Name: 11858, dtype: int64
内部标识号    11860
交易次数        26
交易金额      7826
Name: 11859, dtype: int64
内部标识号    11861
交易次数        29
交易金额       624
Name: 11860, dtype: int64
内部标识号    11862
交易次数         1
交易金额      7594
Name: 11861, dtype: int64
内部标识号    11863
交易次数         2
交易金额       453
Name: 11862, dtype: int64
内部标识号    11864
交易次数         8
交易金额     78606
Name: 11863, dtype: int64
内部标识号    11865
交易次数         2
交易金额       928
Name: 11864, dtype: int64
内部标识号    11866
交易次数        13
交易金额       526
Name: 11865, dtype: int64
内部标识号    11867
交易次数         9
交易金额       635
Name: 11866, dtype: int64
内部标识号    11868
交易次数         2
交易金额       433
Name: 11867, dtype: int64
内部标识号    11869
交易次数       206
交易金额     11701
Name: 11868, dtype: int64
内部标识号    11870
交易次数         2
交易金额       720
Name: 11869, dtype: int64
内部标识号    11871
交易次数         1
交易金额       902
Name: 11870, dtype: int64
内部标识号    11872
交易次数        15
交易金额       314
Name: 11871, dtype: int64
内部标识号    11873
交易次数         3
交易金额       474
Name: 11872, dtype: int64
内部标识号    11874
交易次数        25
交易金额       572
Name: 11873, dtype: int64
内部标识号    11875
交易次数       119
交易金额     28935
Name: 11874, dtype: int64
内部标识号    11876
交易次数         0
交易金额      9911
Name: 11875, dtype: int64
内部标识号    11877
交易次数         4
交易金额       146
Name: 11876, dtype: int64
内部标识号    11878
交易次数         3
交易金额       294
Name: 11877, dtype: int64
内部标识号    11879
交易次数         8
交易金额       526
Name: 11878, dtype: int64
内部标识号    11880
交易次数        12
交易金额       908
Name: 11879, dtype: int64
内部标识号    11881
交易次数        13
交易金额       575
Name: 11880, dtype: int64
内部标识号    11882
交易次数        14
交易金额       659
Name: 11881, dtype: int64
内部标识号    11883
交易次数        28
交易金额       853
Name: 11882, dtype: int64
内部标识号    11884
交易次数         9
交易金额       349
Name: 11883, dtype: int64
内部标识号    11885
交易次数        10
交易金额       732
Name: 11884, dtype: int64
内部标识号    11886
交易次数        13
交易金额       346
Name: 11885, dtype: int64
内部标识号    11887
交易次数         5
交易金额       136
Name: 11886, dtype: int64
内部标识号    11888
交易次数        15
交易金额       574
Name: 11887, dtype: int64
内部标识号    11889
交易次数         9
交易金额       671
Name: 11888, dtype: int64
内部标识号    11890
交易次数        29
交易金额      4220
Name: 11889, dtype: int64
内部标识号    11891
交易次数        13
交易金额       325
Name: 11890, dtype: int64
内部标识号    11892
交易次数        17
交易金额      4546
Name: 11891, dtype: int64
内部标识号    11893
交易次数        10
交易金额       311
Name: 11892, dtype: int64
内部标识号    11894
交易次数         2
交易金额       113
Name: 11893, dtype: int64
内部标识号    11895
交易次数         2
交易金额       125
Name: 11894, dtype: int64
内部标识号    11896
交易次数        13
交易金额       329
Name: 11895, dtype: int64
内部标识号    11897
交易次数         8
交易金额       979
Name: 11896, dtype: int64
内部标识号    11898
交易次数         8
交易金额       103
Name: 11897, dtype: int64
内部标识号    11899
交易次数         7
交易金额       150
Name: 11898, dtype: int64
内部标识号    11900
交易次数        12
交易金额       730
Name: 11899, dtype: int64
内部标识号    11901
交易次数         3
交易金额       293
Name: 11900, dtype: int64
内部标识号    11902
交易次数         9
交易金额       438
Name: 11901, dtype: int64
内部标识号    11903
交易次数        11
交易金额       387
Name: 11902, dtype: int64
内部标识号    11904
交易次数       173
交易金额     47345
Name: 11903, dtype: int64
内部标识号    11905
交易次数         0
交易金额      2173
Name: 11904, dtype: int64
内部标识号    11906
交易次数        12
交易金额       562
Name: 11905, dtype: int64
内部标识号    11907
交易次数         9
交易金额       396
Name: 11906, dtype: int64
内部标识号    11908
交易次数         2
交易金额       340
Name: 11907, dtype: int64
内部标识号    11909
交易次数         2
交易金额       114
Name: 11908, dtype: int64
内部标识号    11910
交易次数         4
交易金额       188
Name: 11909, dtype: int64
内部标识号    11911
交易次数        15
交易金额       516
Name: 11910, dtype: int64
内部标识号    11912
交易次数         2
交易金额       423
Name: 11911, dtype: int64
内部标识号    11913
交易次数         8
交易金额       485
Name: 11912, dtype: int64
内部标识号    11914
交易次数         1
交易金额      4121
Name: 11913, dtype: int64
内部标识号    11915
交易次数         2
交易金额       806
Name: 11914, dtype: int64
内部标识号    11916
交易次数         8
交易金额       191
Name: 11915, dtype: int64
内部标识号    11917
交易次数        15
交易金额       600
Name: 11916, dtype: int64
内部标识号    11918
交易次数        22
交易金额      5194
Name: 11917, dtype: int64
内部标识号    11919
交易次数         2
交易金额       768
Name: 11918, dtype: int64
内部标识号    11920
交易次数        19
交易金额      8508
Name: 11919, dtype: int64
内部标识号    11921
交易次数        25
交易金额       598
Name: 11920, dtype: int64
内部标识号    11922
交易次数         7
交易金额       147
Name: 11921, dtype: int64
内部标识号    11923
交易次数        13
交易金额       444
Name: 11922, dtype: int64
内部标识号    11924
交易次数         2
交易金额       541
Name: 11923, dtype: int64
内部标识号    11925
交易次数         3
交易金额     34689
Name: 11924, dtype: int64
内部标识号    11926
交易次数         8
交易金额       405
Name: 11925, dtype: int64
内部标识号    11927
交易次数         4
交易金额       153
Name: 11926, dtype: int64
内部标识号    11928
交易次数        15
交易金额       452
Name: 11927, dtype: int64
内部标识号    11929
交易次数         2
交易金额       367
Name: 11928, dtype: int64
内部标识号    11930
交易次数        12
交易金额       370
Name: 11929, dtype: int64
内部标识号    11931
交易次数         2
交易金额       865
Name: 11930, dtype: int64
内部标识号    11932
交易次数         3
交易金额     67127
Name: 11931, dtype: int64
内部标识号    11933
交易次数        10
交易金额       523
Name: 11932, dtype: int64
内部标识号    11934
交易次数        15
交易金额       865
Name: 11933, dtype: int64
内部标识号    11935
交易次数         4
交易金额       185
Name: 11934, dtype: int64
内部标识号    11936
交易次数        13
交易金额       712
Name: 11935, dtype: int64
内部标识号    11937
交易次数        13
交易金额       784
Name: 11936, dtype: int64
内部标识号    11938
交易次数         2
交易金额       427
Name: 11937, dtype: int64
内部标识号    11939
交易次数        12
交易金额       829
Name: 11938, dtype: int64
内部标识号    11940
交易次数        22
交易金额      7835
Name: 11939, dtype: int64
内部标识号    11941
交易次数         8
交易金额       454
Name: 11940, dtype: int64
内部标识号    11942
交易次数         2
交易金额       700
Name: 11941, dtype: int64
内部标识号    11943
交易次数         1
交易金额       504
Name: 11942, dtype: int64
内部标识号    11944
交易次数         5
交易金额       158
Name: 11943, dtype: int64
内部标识号    11945
交易次数         3
交易金额       210
Name: 11944, dtype: int64
内部标识号    11946
交易次数         3
交易金额       356
Name: 11945, dtype: int64
内部标识号    11947
交易次数         8
交易金额       833
Name: 11946, dtype: int64
内部标识号    11948
交易次数        15
交易金额       323
Name: 11947, dtype: int64
内部标识号    11949
交易次数         1
交易金额      5820
Name: 11948, dtype: int64
内部标识号    11950
交易次数         7
交易金额       112
Name: 11949, dtype: int64
内部标识号    11951
交易次数        11
交易金额       665
Name: 11950, dtype: int64
内部标识号    11952
交易次数        19
交易金额      9261
Name: 11951, dtype: int64
内部标识号    11953
交易次数         6
交易金额       182
Name: 11952, dtype: int64
内部标识号    11954
交易次数        28
交易金额      4514
Name: 11953, dtype: int64
内部标识号    11955
交易次数         1
交易金额      4458
Name: 11954, dtype: int64
内部标识号    11956
交易次数         3
交易金额       160
Name: 11955, dtype: int64
内部标识号    11957
交易次数         5
交易金额       208
Name: 11956, dtype: int64
内部标识号    11958
交易次数        12
交易金额       334
Name: 11957, dtype: int64
内部标识号    11959
交易次数       201
交易金额     23474
Name: 11958, dtype: int64
内部标识号    11960
交易次数         5
交易金额       105
Name: 11959, dtype: int64
内部标识号    11961
交易次数         3
交易金额       402
Name: 11960, dtype: int64
内部标识号    11962
交易次数         1
交易金额       531
Name: 11961, dtype: int64
内部标识号    11963
交易次数         2
交易金额       330
Name: 11962, dtype: int64
内部标识号    11964
交易次数        13
交易金额       681
Name: 11963, dtype: int64
内部标识号    11965
交易次数         2
交易金额       361
Name: 11964, dtype: int64
内部标识号    11966
交易次数         2
交易金额       146
Name: 11965, dtype: int64
内部标识号    11967
交易次数        13
交易金额       319
Name: 11966, dtype: int64
内部标识号    11968
交易次数         3
交易金额       385
Name: 11967, dtype: int64
内部标识号    11969
交易次数         3
交易金额       472
Name: 11968, dtype: int64
内部标识号    11970
交易次数         3
交易金额       206
Name: 11969, dtype: int64
内部标识号    11971
交易次数        14
交易金额       441
Name: 11970, dtype: int64
内部标识号    11972
交易次数        10
交易金额       722
Name: 11971, dtype: int64
内部标识号    11973
交易次数       203
交易金额     59591
Name: 11972, dtype: int64
内部标识号    11974
交易次数        12
交易金额       572
Name: 11973, dtype: int64
内部标识号    11975
交易次数         8
交易金额       133
Name: 11974, dtype: int64
内部标识号    11976
交易次数         1
交易金额       911
Name: 11975, dtype: int64
内部标识号    11977
交易次数         5
交易金额       267
Name: 11976, dtype: int64
内部标识号    11978
交易次数        11
交易金额       533
Name: 11977, dtype: int64
内部标识号    11979
交易次数        15
交易金额       859
Name: 11978, dtype: int64
内部标识号    11980
交易次数         4
交易金额       229
Name: 11979, dtype: int64
内部标识号    11981
交易次数        17
交易金额       949
Name: 11980, dtype: int64
内部标识号    11982
交易次数        15
交易金额       548
Name: 11981, dtype: int64
内部标识号    11983
交易次数         2
交易金额       808
Name: 11982, dtype: int64
内部标识号    11984
交易次数         1
交易金额       913
Name: 11983, dtype: int64
内部标识号    11985
交易次数         4
交易金额       123
Name: 11984, dtype: int64
内部标识号    11986
交易次数         7
交易金额       178
Name: 11985, dtype: int64
内部标识号    11987
交易次数         8
交易金额       188
Name: 11986, dtype: int64
内部标识号    11988
交易次数        12
交易金额       434
Name: 11987, dtype: int64
内部标识号    11989
交易次数         1
交易金额       928
Name: 11988, dtype: int64
内部标识号    11990
交易次数        13
交易金额       742
Name: 11989, dtype: int64
内部标识号    11991
交易次数         1
交易金额      8071
Name: 11990, dtype: int64
内部标识号    11992
交易次数         8
交易金额       425
Name: 11991, dtype: int64
内部标识号    11993
交易次数         2
交易金额       386
Name: 11992, dtype: int64
内部标识号    11994
交易次数        62
交易金额     71107
Name: 11993, dtype: int64
内部标识号    11995
交易次数        23
交易金额      1221
Name: 11994, dtype: int64
内部标识号    11996
交易次数         3
交易金额       281
Name: 11995, dtype: int64
内部标识号    11997
交易次数        11
交易金额       716
Name: 11996, dtype: int64
内部标识号    11998
交易次数         7
交易金额       270
Name: 11997, dtype: int64
内部标识号    11999
交易次数        15
交易金额       621
Name: 11998, dtype: int64
内部标识号    12000
交易次数        13
交易金额       327
Name: 11999, dtype: int64
内部标识号    12001
交易次数         4
交易金额       297
Name: 12000, dtype: int64
内部标识号    12002
交易次数         2
交易金额       448
Name: 12001, dtype: int64
内部标识号    12003
交易次数        12
交易金额       985
Name: 12002, dtype: int64
内部标识号    12004
交易次数        10
交易金额       718
Name: 12003, dtype: int64
内部标识号    12005
交易次数         9
交易金额       395
Name: 12004, dtype: int64
内部标识号    12006
交易次数         4
交易金额       298
Name: 12005, dtype: int64
内部标识号    12007
交易次数        11
交易金额       846
Name: 12006, dtype: int64
内部标识号    12008
交易次数         1
交易金额       974
Name: 12007, dtype: int64
内部标识号    12009
交易次数         1
交易金额       985
Name: 12008, dtype: int64
内部标识号    12010
交易次数         3
交易金额       247
Name: 12009, dtype: int64
内部标识号    12011
交易次数         7
交易金额       160
Name: 12010, dtype: int64
内部标识号    12012
交易次数         1
交易金额      3070
Name: 12011, dtype: int64
内部标识号    12013
交易次数       154
交易金额     22882
Name: 12012, dtype: int64
内部标识号    12014
交易次数        12
交易金额       839
Name: 12013, dtype: int64
内部标识号    12015
交易次数         2
交易金额       783
Name: 12014, dtype: int64
内部标识号    12016
交易次数        15
交易金额       927
Name: 12015, dtype: int64
内部标识号    12017
交易次数        19
交易金额      4753
Name: 12016, dtype: int64
内部标识号    12018
交易次数         3
交易金额       182
Name: 12017, dtype: int64
内部标识号    12019
交易次数         9
交易金额       722
Name: 12018, dtype: int64
内部标识号    12020
交易次数        13
交易金额       845
Name: 12019, dtype: int64
内部标识号    12021
交易次数         3
交易金额       232
Name: 12020, dtype: int64
内部标识号    12022
交易次数         7
交易金额       244
Name: 12021, dtype: int64
内部标识号    12023
交易次数         9
交易金额       888
Name: 12022, dtype: int64
内部标识号    12024
交易次数        15
交易金额      3395
Name: 12023, dtype: int64
内部标识号    12025
交易次数         1
交易金额      3849
Name: 12024, dtype: int64
内部标识号    12026
交易次数         3
交易金额       463
Name: 12025, dtype: int64
内部标识号    12027
交易次数         2
交易金额       683
Name: 12026, dtype: int64
内部标识号    12028
交易次数         3
交易金额       318
Name: 12027, dtype: int64
内部标识号    12029
交易次数        14
交易金额       479
Name: 12028, dtype: int64
内部标识号    12030
交易次数        13
交易金额       798
Name: 12029, dtype: int64
内部标识号    12031
交易次数         3
交易金额       299
Name: 12030, dtype: int64
内部标识号    12032
交易次数        14
交易金额       415
Name: 12031, dtype: int64
内部标识号    12033
交易次数         2
交易金额       610
Name: 12032, dtype: int64
内部标识号    12034
交易次数        10
交易金额       958
Name: 12033, dtype: int64
内部标识号    12035
交易次数         1
交易金额      1488
Name: 12034, dtype: int64
内部标识号    12036
交易次数         5
交易金额       108
Name: 12035, dtype: int64
内部标识号    12037
交易次数         9
交易金额       973
Name: 12036, dtype: int64
内部标识号    12038
交易次数         0
交易金额      2842
Name: 12037, dtype: int64
内部标识号    12039
交易次数         9
交易金额       858
Name: 12038, dtype: int64
内部标识号    12040
交易次数         2
交易金额       951
Name: 12039, dtype: int64
内部标识号    12041
交易次数         2
交易金额       888
Name: 12040, dtype: int64
内部标识号    12042

内部标识号    12260
交易次数         0
交易金额      3286
Name: 12259, dtype: int64
内部标识号    12261
交易次数        11
交易金额       681
Name: 12260, dtype: int64
内部标识号    12262
交易次数         3
交易金额       110
Name: 12261, dtype: int64
内部标识号    12263
交易次数         3
交易金额       431
Name: 12262, dtype: int64
内部标识号    12264
交易次数         5
交易金额       104
Name: 12263, dtype: int64
内部标识号    12265
交易次数         2
交易金额       381
Name: 12264, dtype: int64
内部标识号    12266
交易次数        13
交易金额       895
Name: 12265, dtype: int64
内部标识号    12267
交易次数        15
交易金额      6203
Name: 12266, dtype: int64
内部标识号    12268
交易次数         1
交易金额       747
Name: 12267, dtype: int64
内部标识号    12269
交易次数         3
交易金额     65457
Name: 12268, dtype: int64
内部标识号    12270
交易次数        25
交易金额      2354
Name: 12269, dtype: int64
内部标识号    12271
交易次数         0
交易金额      3280
Name: 12270, dtype: int64
内部标识号    12272
交易次数         2
交易金额       487
Name: 12271, dtype: int64
内部标识号    12273
交易次数         0
交易金额      2679
Name: 12272, dtype: int64
内部标识号    12274
交易次数         8
交易金额       406
Name: 12273, dtype: int64
内部标识号    12275
交易次数         1
交易金额      4850
Name: 12274, dtype: int64
内部标识号    12276
交易次数         1
交易金额       780
Name: 12275, dtype: int64
内部标识号    12277
交易次数         2
交易金额       469
Name: 12276, dtype: int64
内部标识号    12278
交易次数         1
交易金额       693
Name: 12277, dtype: int64
内部标识号    12279
交易次数        23
交易金额      1074
Name: 12278, dtype: int64
内部标识号    12280
交易次数         7
交易金额       164
Name: 12279, dtype: int64
内部标识号    12281
交易次数         1
交易金额       508
Name: 12280, dtype: int64
内部标识号    12282
交易次数        16
交易金额      2756
Name: 12281, dtype: int64
内部标识号    12283
交易次数        10
交易金额       690
Name: 12282, dtype: int64
内部标识号    12284
交易次数         3
交易金额       346
Name: 12283, dtype: int64
内部标识号    12285
交易次数         6
交易金额       164
Name: 12284, dtype: int64
内部标识号    12286
交易次数         3
交易金额       231
Name: 12285, dtype: int64
内部标识号    12287
交易次数        14
交易金额       717
Name: 12286, dtype: int64
内部标识号    12288
交易次数        13
交易金额       339
Name: 12287, dtype: int64
内部标识号    12289
交易次数         3
交易金额       487
Name: 12288, dtype: int64
内部标识号    12290
交易次数        12
交易金额       323
Name: 12289, dtype: int64
内部标识号    12291
交易次数         2
交易金额       931
Name: 12290, dtype: int64
内部标识号    12292
交易次数         5
交易金额     93622
Name: 12291, dtype: int64
内部标识号    12293
交易次数         8
交易金额       635
Name: 12292, dtype: int64
内部标识号    12294
交易次数        13
交易金额       456
Name: 12293, dtype: int64
内部标识号    12295
交易次数        12
交易金额       421
Name: 12294, dtype: int64
内部标识号    12296
交易次数        12
交易金额       432
Name: 12295, dtype: int64
内部标识号    12297
交易次数         1
交易金额       932
Name: 12296, dtype: int64
内部标识号    12298
交易次数         7
交易金额       171
Name: 12297, dtype: int64
内部标识号    12299
交易次数        15
交易金额       698
Name: 12298, dtype: int64
内部标识号    12300
交易次数         5
交易金额       246
Name: 12299, dtype: int64
内部标识号    12301
交易次数        11
交易金额       679
Name: 12300, dtype: int64
内部标识号    12302
交易次数        16
交易金额      9047
Name: 12301, dtype: int64
内部标识号    12303
交易次数         2
交易金额       675
Name: 12302, dtype: int64
内部标识号    12304
交易次数        12
交易金额       469
Name: 12303, dtype: int64
内部标识号    12305
交易次数        67
交易金额     60218
Name: 12304, dtype: int64
内部标识号    12306
交易次数         9
交易金额       413
Name: 12305, dtype: int64
内部标识号    12307
交易次数         0
交易金额      2479
Name: 12306, dtype: int64
内部标识号    12308
交易次数         1
交易金额      2854
Name: 12307, dtype: int64
内部标识号    12309
交易次数        13
交易金额       438
Name: 12308, dtype: int64
内部标识号    12310
交易次数         3
交易金额       271
Name: 12309, dtype: int64
内部标识号    12311
交易次数         0
交易金额      9512
Name: 12310, dtype: int64
内部标识号    12312
交易次数        15
交易金额       693
Name: 12311, dtype: int64
内部标识号    12313
交易次数         3
交易金额     68732
Name: 12312, dtype: int64
内部标识号    12314
交易次数        18
交易金额      6695
Name: 12313, dtype: int64
内部标识号    12315
交易次数        12
交易金额       993
Name: 12314, dtype: int64
内部标识号    12316
交易次数        21
交易金额      7219
Name: 12315, dtype: int64
内部标识号    12317
交易次数         3
交易金额       279
Name: 12316, dtype: int64
内部标识号    12318
交易次数         4
交易金额       186
Name: 12317, dtype: int64
内部标识号    12319
交易次数         4
交易金额     36483
Name: 12318, dtype: int64
内部标识号    12320
交易次数         8
交易金额     29760
Name: 12319, dtype: int64
内部标识号    12321
交易次数        11
交易金额       505
Name: 12320, dtype: int64
内部标识号    12322
交易次数        10
交易金额       943
Name: 12321, dtype: int64
内部标识号    12323
交易次数       261
交易金额     74058
Name: 12322, dtype: int64
内部标识号    12324
交易次数        12
交易金额       466
Name: 12323, dtype: int64
内部标识号    12325
交易次数        22
交易金额       790
Name: 12324, dtype: int64
内部标识号    12326
交易次数         0
交易金额      2744
Name: 12325, dtype: int64
内部标识号    12327
交易次数         2
交易金额       297
Name: 12326, dtype: int64
内部标识号    12328
交易次数        21
交易金额      8971
Name: 12327, dtype: int64
内部标识号    12329
交易次数        15
交易金额       528
Name: 12328, dtype: int64
内部标识号    12330
交易次数         2
交易金额       515
Name: 12329, dtype: int64
内部标识号    12331
交易次数        14
交易金额       950
Name: 12330, dtype: int64
内部标识号    12332
交易次数        17
交易金额       524
Name: 12331, dtype: int64
内部标识号    12333
交易次数        12
交易金额       780
Name: 12332, dtype: int64
内部标识号    12334
交易次数         2
交易金额       455
Name: 12333, dtype: int64
内部标识号    12335
交易次数         8
交易金额       226
Name: 12334, dtype: int64
内部标识号    12336
交易次数        26
交易金额      3598
Name: 12335, dtype: int64
内部标识号    12337
交易次数         5
交易金额       213
Name: 12336, dtype: int64
内部标识号    12338
交易次数        10
交易金额       957
Name: 12337, dtype: int64
内部标识号    12339
交易次数         9
交易金额       940
Name: 12338, dtype: int64
内部标识号    12340
交易次数         9
交易金额       918
Name: 12339, dtype: int64
内部标识号    12341
交易次数         4
交易金额       274
Name: 12340, dtype: int64
内部标识号    12342
交易次数        21
交易金额       831
Name: 12341, dtype: int64
内部标识号    12343
交易次数        30
交易金额       533
Name: 12342, dtype: int64
内部标识号    12344
交易次数         3
交易金额       250
Name: 12343, dtype: int64
内部标识号    12345
交易次数         9
交易金额       894
Name: 12344, dtype: int64
内部标识号    12346
交易次数        28
交易金额      3071
Name: 12345, dtype: int64
内部标识号    12347
交易次数         8
交易金额       209
Name: 12346, dtype: int64
内部标识号    12348
交易次数         4
交易金额     79087
Name: 12347, dtype: int64
内部标识号    12349
交易次数         5
交易金额     18721
Name: 12348, dtype: int64
内部标识号    12350
交易次数         8
交易金额       247
Name: 12349, dtype: int64
内部标识号    12351
交易次数         8
交易金额       425
Name: 12350, dtype: int64
内部标识号    12352
交易次数       233
交易金额     49352
Name: 12351, dtype: int64
内部标识号    12353
交易次数        13
交易金额       347
Name: 12352, dtype: int64
内部标识号    12354
交易次数        26
交易金额      1974
Name: 12353, dtype: int64
内部标识号    12355
交易次数       197
交易金额     41072
Name: 12354, dtype: int64
内部标识号    12356
交易次数         8
交易金额       658
Name: 12355, dtype: int64
内部标识号    12357
交易次数         0
交易金额      2714
Name: 12356, dtype: int64
内部标识号    12358
交易次数         1
交易金额       799
Name: 12357, dtype: int64
内部标识号    12359
交易次数         3
交易金额       358
Name: 12358, dtype: int64
内部标识号    12360
交易次数         1
交易金额      8966
Name: 12359, dtype: int64
内部标识号    12361
交易次数        10
交易金额       418
Name: 12360, dtype: int64
内部标识号    12362
交易次数        20
交易金额        17
Name: 12361, dtype: int64
内部标识号    12363
交易次数        10
交易金额       302
Name: 12362, dtype: int64
内部标识号    12364
交易次数         5
交易金额       289
Name: 12363, dtype: int64
内部标识号    12365
交易次数        15
交易金额       698
Name: 12364, dtype: int64
内部标识号    12366
交易次数        15
交易金额       670
Name: 12365, dtype: int64
内部标识号    12367
交易次数         7
交易金额       196
Name: 12366, dtype: int64
内部标识号    12368
交易次数         1
交易金额      6598
Name: 12367, dtype: int64
内部标识号    12369
交易次数         3
交易金额       463
Name: 12368, dtype: int64
内部标识号    12370
交易次数        19
交易金额       942
Name: 12369, dtype: int64
内部标识号    12371
交易次数         1
交易金额      7660
Name: 12370, dtype: int64
内部标识号    12372
交易次数         8
交易金额       649
Name: 12371, dtype: int64
内部标识号    12373
交易次数         1
交易金额       509
Name: 12372, dtype: int64
内部标识号    12374
交易次数        11
交易金额       746
Name: 12373, dtype: int64
内部标识号    12375
交易次数         0
交易金额      1321
Name: 12374, dtype: int64
内部标识号    12376
交易次数         3
交易金额       254
Name: 12375, dtype: int64
内部标识号    12377
交易次数         2
交易金额       664
Name: 12376, dtype: int64
内部标识号    12378
交易次数         8
交易金额       297
Name: 12377, dtype: int64
内部标识号    12379
交易次数        17
交易金额      2283
Name: 12378, dtype: int64
内部标识号    12380
交易次数        18
交易金额      7569
Name: 12379, dtype: int64
内部标识号    12381
交易次数         3
交易金额       342
Name: 12380, dtype: int64
内部标识号    12382
交易次数         9
交易金额       306
Name: 12381, dtype: int64
内部标识号    12383
交易次数         0
交易金额      2039
Name: 12382, dtype: int64
内部标识号    12384
交易次数         2
交易金额       264
Name: 12383, dtype: int64
内部标识号    12385
交易次数         1
交易金额      9180
Name: 12384, dtype: int64
内部标识号    12386
交易次数        15
交易金额       420
Name: 12385, dtype: int64
内部标识号    12387
交易次数        21
交易金额        18
Name: 12386, dtype: int64
内部标识号    12388
交易次数        17
交易金额      9713
Name: 12387, dtype: int64
内部标识号    12389
交易次数         2
交易金额       811
Name: 12388, dtype: int64
内部标识号    12390
交易次数         8
交易金额       343
Name: 12389, dtype: int64
内部标识号    12391
交易次数        15
交易金额       932
Name: 12390, dtype: int64
内部标识号    12392
交易次数         6
交易金额       286
Name: 12391, dtype: int64
内部标识号    12393
交易次数        13
交易金额       516
Name: 12392, dtype: int64
内部标识号    12394
交易次数         0
交易金额      4929
Name: 12393, dtype: int64
内部标识号    12395
交易次数        14
交易金额       832
Name: 12394, dtype: int64
内部标识号    12396
交易次数        26
交易金额        73
Name: 12395, dtype: int64
内部标识号    12397
交易次数        13
交易金额       842
Name: 12396, dtype: int64
内部标识号    12398
交易次数         2
交易金额       531
Name: 12397, dtype: int64
内部标识号    12399
交易次数        28
交易金额       708
Name: 12398, dtype: int64
内部标识号    12400
交易次数         3
交易金额       190
Name: 12399, dtype: int64
内部标识号    12401
交易次数        11
交易金额       508
Name: 12400, dtype: int64
内部标识号    12402
交易次数         2
交易金额       364
Name: 12401, dtype: int64
内部标识号    12403
交易次数        11
交易金额       467
Name: 12402, dtype: int64
内部标识号    12404
交易次数         5
交易金额       272
Name: 12403, dtype: int64
内部标识号    12405
交易次数         2
交易金额       875
Name: 12404, dtype: int64
内部标识号    12406
交易次数         3
交易金额       358
Name: 12405, dtype: int64
内部标识号    12407
交易次数        11
交易金额       881
Name: 12406, dtype: int64
内部标识号    12408
交易次数        14
交易金额       776
Name: 12407, dtype: int64
内部标识号    12409
交易次数         0
交易金额      3348
Name: 12408, dtype: int64
内部标识号    12410
交易次数         2
交易金额       497
Name: 12409, dtype: int64
内部标识号    12411
交易次数         2
交易金额       160
Name: 12410, dtype: int64
内部标识号    12412
交易次数         7
交易金额       232
Name: 12411, dtype: int64
内部标识号    12413
交易次数        24
交易金额      3439
Name: 12412, dtype: int64
内部标识号    12414
交易次数        15
交易金额       586
Name: 12413, dtype: int64
内部标识号    12415
交易次数        11
交易金额       807
Name: 12414, dtype: int64
内部标识号    12416
交易次数         3
交易金额       467
Name: 12415, dtype: int64
内部标识号    12417
交易次数         2
交易金额       861
Name: 12416, dtype: int64
内部标识号    12418
交易次数        11
交易金额       969
Name: 12417, dtype: int64
内部标识号    12419
交易次数         2
交易金额       343
Name: 12418, dtype: int64
内部标识号    12420
交易次数       115
交易金额     30764
Name: 12419, dtype: int64
内部标识号    12421
交易次数         9
交易金额       500
Name: 12420, dtype: int64
内部标识号    12422
交易次数         6
交易金额     41980
Name: 12421, dtype: int64
内部标识号    12423
交易次数         3
交易金额       482
Name: 12422, dtype: int64
内部标识号    12424
交易次数        11
交易金额       329
Name: 12423, dtype: int64
内部标识号    12425
交易次数         4
交易金额       189
Name: 12424, dtype: int64
内部标识号    12426
交易次数         1
交易金额      8560
Name: 12425, dtype: int64
内部标识号    12427
交易次数         6
交易金额       192
Name: 12426, dtype: int64
内部标识号    12428
交易次数         3
交易金额       267
Name: 12427, dtype: int64
内部标识号    12429
交易次数         8
交易金额       266
Name: 12428, dtype: int64
内部标识号    12430
交易次数         2
交易金额       134
Name: 12429, dtype: int64
内部标识号    12431
交易次数         2
交易金额       573
Name: 12430, dtype: int64
内部标识号    12432
交易次数         7
交易金额       245
Name: 12431, dtype: int64
内部标识号    12433
交易次数         3
交易金额       292
Name: 12432, dtype: int64
内部标识号    12434
交易次数        13
交易金额       629
Name: 12433, dtype: int64
内部标识号    12435
交易次数        18
交易金额      2987
Name: 12434, dtype: int64
内部标识号    12436
交易次数         7
交易金额       279
Name: 12435, dtype: int64
内部标识号    12437
交易次数        10
交易金额       456
Name: 12436, dtype: int64
内部标识号    12438
交易次数         2
交易金额       659
Name: 12437, dtype: int64
内部标识号    12439
交易次数         5
交易金额       265
Name: 12438, dtype: int64
内部标识号    12440
交易次数         3
交易金额       301
Name: 12439, dtype: int64
内部标识号    12441
交易次数         2
交易金额       493
Name: 12440, dtype: int64
内部标识号    12442
交易次数         9
交易金额       379
Name: 12441, dtype: int64
内部标识号    12443
交易次数        28
交易金额      8085
Name: 12442, dtype: int64
内部标识号    12444
交易次数        14
交易金额       847
Name: 12443, dtype: int64
内部标识号    12445
交易次数        10
交易金额       556
Name: 12444, dtype: int64
内部标识号    12446
交易次数        21
交易金额       503
Name: 12445, dtype: int64
内部标识号    12447
交易次数         3
交易金额       356
Name: 12446, dtype: int64
内部标识号    12448
交易次数       103
交易金额     51504
Name: 12447, dtype: int64
内部标识号    12449
交易次数         2
交易金额       551
Name: 12448, dtype: int64
内部标识号    12450
交易次数        26
交易金额      2957
Name: 12449, dtype: int64
内部标识号    12451
交易次数         7
交易金额     88403
Name: 12450, dtype: int64
内部标识号    12452
交易次数         8
交易金额       141
Name: 12451, dtype: int64
内部标识号    12453
交易次数        14
交易金额       482
Name: 12452, dtype: int64
内部标识号    12454
交易次数         2
交易金额       309
Name: 12453, dtype: int64
内部标识号    12455
交易次数         3
交易金额       497
Name: 12454, dtype: int64
内部标识号    12456
交易次数         1
交易金额       607
Name: 12455, dtype: int64
内部标识号    12457
交易次数         6
交易金额       109
Name: 12456, dtype: int64
内部标识号    12458
交易次数        21
交易金额      4941
Name: 12457, dtype: int64
内部标识号    12459
交易次数        29
交易金额       930
Name: 12458, dtype: int64
内部标识号    12460
交易次数        15
交易金额       762
Name: 12459, dtype: int64
内部标识号    12461
交易次数         2
交易金额       537
Name: 12460, dtype: int64
内部标识号    12462
交易次数        11
交易金额       306
Name: 12461, dtype: int64
内部标识号    12463
交易次数         3
交易金额       196
Name: 12462, dtype: int64
内部标识号    12464
交易次数         1
交易金额       904
Name: 12463, dtype: int64
内部标识号    12465
交易次数         2
交易金额       436
Name: 12464, dtype: int64
内部标识号    12466
交易次数         2
交易金额       864
Name: 12465, dtype: int64
内部标识号    12467
交易次数        13
交易金额       467
Name: 12466, dtype: int64
内部标识号    12468
交易次数         1
交易金额      7819
Name: 12467, dtype: int64
内部标识号    12469
交易次数        15
交易金额       801
Name: 12468, dtype: int64
内部标识号    12470
交易次数       285
交易金额     75549
Name: 12469, dtype: int64
内部标识号    12471
交易次数        13
交易金额       556
Name: 12470, dtype: int64
内部标识号    12472
交易次数       175
交易金额     12926
Name: 12471, dtype: int64
内部标识号    12473
交易次数        12
交易金额       676
Name: 12472, dtype: int64
内部标识号    12474
交易次数         2
交易金额       357
Name: 12473, dtype: int64
内部标识号    12475
交易次数        25
交易金额      7653
Name: 12474, dtype: int64
内部标识号    12476
交易次数         3
交易金额       496
Name: 12475, dtype: int64
内部标识号    12477
交易次数        15
交易金额       754
Name: 12476, dtype: int64
内部标识号    12478
交易次数         1
交易金额       820
Name: 12477, dtype: int64
内部标识号    12479
交易次数        15
交易金额       677
Name: 12478, dtype: int64
内部标识号    12480
交易次数         3
交易金额     40086
Name: 12479, dtype: int64
内部标识号    12481
交易次数       166
交易金额     28814
Name: 12480, dtype: int64
内部标识号    12482
交易次数        27
交易金额        77
Name: 12481, dtype: int64
内部标识号    12483
交易次数         0
交易金额      6671
Name: 12482, dtype: int64
内部标识号    12484
交易次数         9
交易金额       587
Name: 12483, dtype: int64
内部标识号    12485
交易次数         6
交易金额       154
Name: 12484, dtype: int64
内部标识号    12486
交易次数        29
交易金额      9062
Name: 12485, dtype: int64
内部标识号    12487
交易次数         2
交易金额       256
Name: 12486, dtype: int64
内部标识号    12488
交易次数         6
交易金额       143
Name: 12487, dtype: int64
内部标识号    12489
交易次数         1
交易金额       994
Name: 12488, dtype: int64
内部标识号    12490
交易次数         3
交易金额     94501
Name: 12489, dtype: int64
内部标识号    12491
交易次数         2
交易金额       485
Name: 12490, dtype: int64
内部标识号    12492
交易次数        13
交易金额       743
Name: 12491, dtype: int64
内部标识号    12493
交易次数        17
交易金额       539
Name: 12492, dtype: int64
内部标识号    12494
交易次数        19
交易金额      6262
Name: 12493, dtype: int64
内部标识号    12495
交易次数         8
交易金额       174
Name: 12494, dtype: int64
内部标识号    12496
交易次数        13
交易金额       450
Name: 12495, dtype: int64
内部标识号    12497
交易次数        19
交易金额      4009
Name: 12496, dtype: int64
内部标识号    12498
交易次数         1
交易金额      1815
Name: 12497, dtype: int64
内部标识号    12499
交易次数         3
交易金额       145
Name: 12498, dtype: int64
内部标识号    12500
交易次数         2
交易金额       489
Name: 12499, dtype: int64
内部标识号    12501
交易次数         2
交易金额       541
Name: 12500, dtype: int64
内部标识号    12502
交易次数         4
交易金额       167
Name: 12501, dtype: int64
内部标识号    12503
交易次数         2
交易金额       391
Name: 12502, dtype: int64
内部标识号    12504
交易次数         3
交易金额       285
Name: 12503, dtype: int64
内部标识号    12505
交易次数        15
交易金额       510
Name: 12504, dtype: int64
内部标识号    12506
交易次数        12
交易金额       878
Name: 12505, dtype: int64
内部标识号    12507
交易次数         8
交易金额       276
Name: 12506, dtype: int64
内部标识号    12508
交易次数        13
交易金额       695
Name: 12507, dtype: int64
内部标识号    12509
交易次数         1
交易金额       988
Name: 12508, dtype: int64
内部标识号    12510
交易次数        10
交易金额       975
Name: 12509, dtype: int64
内部标识号    12511
交易次数         5
交易金额       195
Name: 12510, dtype: int64
内部标识号    12512
交易次数         6
交易金额       153
Name: 12511, dtype: int64
内部标识号    12513
交易次数       203
交易金额     37451
Name: 12512, dtype: int64
内部标识号    12514
交易次数        10
交易金额       378
Name: 12513, dtype: int64
内部标识号    12515
交易次数         6
交易金额     81919
Name: 12514, dtype: int64
内部标识号    12516
交易次数         3
交易金额       442
Name: 12515, dtype: int64
内部标识号    12517
交易次数         9
交易金额       326
Name: 12516, dtype: int64
内部标识号    12518
交易次数         2
交易金额       479
Name: 12517, dtype: int64
内部标识号    12519
交易次数         1
交易金额       569
Name: 12518, dtype: int64
内部标识号    12520
交易次数        15
交易金额       604
Name: 12519, dtype: int64
内部标识号    12521
交易次数        19
交易金额      5192
Name: 12520, dtype: int64
内部标识号    12522
交易次数        15
交易金额       665
Name: 12521, dtype: int64
内部标识号    12523
交易次数         4
交易金额       130
Name: 12522, dtype: int64
内部标识号    12524
交易次数         2
交易金额       673
Name: 12523, dtype: int64
内部标识号    12525
交易次数         3
交易金额       215
Name: 12524, dtype: int64
内部标识号    12526
交易次数         0
交易金额      5887
Name: 12525, dtype: int64
内部标识号    12527
交易次数        11
交易金额       415
Name: 12526, dtype: int64
内部标识号    12528
交易次数        25
交易金额      7448
Name: 12527, dtype: int64
内部标识号    12529
交易次数         2
交易金额       507
Name: 12528, dtype: int64
内部标识号    12530
交易次数         1
交易金额       864
Name: 12529, dtype: int64
内部标识号    12531
交易次数        10
交易金额       406
Name: 12530, dtype: int64
内部标识号    12532
交易次数        12
交易金额       334
Name: 12531, dtype: int64
内部标识号    12533
交易次数         1
交易金额      7906
Name: 12532, dtype: int64
内部标识号    12534
交易次数        13
交易金额       765
Name: 12533, dtype: int64
内部标识号    12535
交易次数        29
交易金额      5303
Name: 12534, dtype: int64
内部标识号    12536
交易次数         2
交易金额       499
Name: 12535, dtype: int64
内部标识号    12537
交易次数         2
交易金额       974
Name: 12536, dtype: int64
内部标识号    12538
交易次数         5
交易金额     38955
Name: 12537, dtype: int64
内部标识号    12539
交易次数         8
交易金额       963
Name: 12538, dtype: int64
内部标识号    12540
交易次数         3
交易金额     82608
Name: 12539, dtype: int64
内部标识号    12541
交易次数         6
交易金额       150

Name: 12716, dtype: int64
内部标识号    12718
交易次数        24
交易金额      2144
Name: 12717, dtype: int64
内部标识号    12719
交易次数        14
交易金额       679
Name: 12718, dtype: int64
内部标识号    12720
交易次数         1
交易金额      6942
Name: 12719, dtype: int64
内部标识号    12721
交易次数         1
交易金额       798
Name: 12720, dtype: int64
内部标识号    12722
交易次数        19
交易金额       945
Name: 12721, dtype: int64
内部标识号    12723
交易次数        13
交易金额       415
Name: 12722, dtype: int64
内部标识号    12724
交易次数         5
交易金额       137
Name: 12723, dtype: int64
内部标识号    12725
交易次数        15
交易金额       330
Name: 12724, dtype: int64
内部标识号    12726
交易次数         2
交易金额       455
Name: 12725, dtype: int64
内部标识号    12727
交易次数       196
交易金额     75272
Name: 12726, dtype: int64
内部标识号    12728
交易次数        14
交易金额       455
Name: 12727, dtype: int64
内部标识号    12729
交易次数         1
交易金额       547
Name: 12728, dtype: int64
内部标识号    12730
交易次数         1
交易金额       791
Name: 12729, dtype: int64
内部标识号    12731
交易次数         0
交易金额      8558
Name: 12730, dtype: int64
内部标识号    12732
交易次数         2
交易金额       263
Name: 12731, dtype: int64
内部标识号    12733
交易次数         4
交易金额     52102
Name: 12732, dtype: int64
内部标识号    12734
交易次数         3
交易金额       316
Name: 12733, dtype: int64
内部标识号    12735
交易次数         2
交易金额       460
Name: 12734, dtype: int64
内部标识号    12736
交易次数         8
交易金额       860
Name: 12735, dtype: int64
内部标识号    12737
交易次数        13
交易金额       335
Name: 12736, dtype: int64
内部标识号    12738
交易次数         0
交易金额      9562
Name: 12737, dtype: int64
内部标识号    12739
交易次数         3
交易金额       182
Name: 12738, dtype: int64
内部标识号    12740
交易次数         2
交易金额       402
Name: 12739, dtype: int64
内部标识号    12741
交易次数        14
交易金额       776
Name: 12740, dtype: int64
内部标识号    12742
交易次数         2
交易金额       347
Name: 12741, dtype: int64
内部标识号    12743
交易次数         4
交易金额       182
Name: 12742, dtype: int64
内部标识号    12744
交易次数         2
交易金额       343
Name: 12743, dtype: int64
内部标识号    12745
交易次数         0
交易金额      2947
Name: 12744, dtype: int64
内部标识号    12746
交易次数         3
交易金额       166
Name: 12745, dtype: int64
内部标识号    12747
交易次数         9
交易金额       429
Name: 12746, dtype: int64
内部标识号    12748
交易次数         7
交易金额       154
Name: 12747, dtype: int64
内部标识号    12749
交易次数         9
交易金额       463
Name: 12748, dtype: int64
内部标识号    12750
交易次数        13
交易金额       754
Name: 12749, dtype: int64
内部标识号    12751
交易次数        11
交易金额       413
Name: 12750, dtype: int64
内部标识号    12752
交易次数         0
交易金额      1786
Name: 12751, dtype: int64
内部标识号    12753
交易次数         5
交易金额       258
Name: 12752, dtype: int64
内部标识号    12754
交易次数        24
交易金额       743
Name: 12753, dtype: int64
内部标识号    12755
交易次数         3
交易金额       489
Name: 12754, dtype: int64
内部标识号    12756
交易次数        26
交易金额      6968
Name: 12755, dtype: int64
内部标识号    12757
交易次数         8
交易金额     90778
Name: 12756, dtype: int64
内部标识号    12758
交易次数        30
交易金额      5195
Name: 12757, dtype: int64
内部标识号    12759
交易次数         2
交易金额       319
Name: 12758, dtype: int64
内部标识号    12760
交易次数         2
交易金额       384
Name: 12759, dtype: int64
内部标识号    12761
交易次数         3
交易金额       306
Name: 12760, dtype: int64
内部标识号    12762
交易次数        14
交易金额       384
Name: 12761, dtype: int64
内部标识号    12763
交易次数         6
交易金额       291
Name: 12762, dtype: int64
内部标识号    12764
交易次数        10
交易金额       729
Name: 12763, dtype: int64
内部标识号    12765
交易次数        12
交易金额       861
Name: 12764, dtype: int64
内部标识号    12766
交易次数         9
交易金额       820
Name: 12765, dtype: int64
内部标识号    12767
交易次数        15
交易金额       666
Name: 12766, dtype: int64
内部标识号    12768
交易次数         7
交易金额     70931
Name: 12767, dtype: int64
内部标识号    12769
交易次数         2
交易金额       489
Name: 12768, dtype: int64
内部标识号    12770
交易次数         2
交易金额       480
Name: 12769, dtype: int64
内部标识号    12771
交易次数        22
交易金额       945
Name: 12770, dtype: int64
内部标识号    12772
交易次数       243
交易金额     57758
Name: 12771, dtype: int64
内部标识号    12773
交易次数         6
交易金额     61557
Name: 12772, dtype: int64
内部标识号    12774
交易次数         2
交易金额       879
Name: 12773, dtype: int64
内部标识号    12775
交易次数         1
交易金额      2881
Name: 12774, dtype: int64
内部标识号    12776
交易次数        15
交易金额       365
Name: 12775, dtype: int64
内部标识号    12777
交易次数        15
交易金额       528
Name: 12776, dtype: int64
内部标识号    12778
交易次数         0
交易金额      3953
Name: 12777, dtype: int64
内部标识号    12779
交易次数         3
交易金额       307
Name: 12778, dtype: int64
内部标识号    12780
交易次数         0
交易金额      9290
Name: 12779, dtype: int64
内部标识号    12781
交易次数         0
交易金额      5336
Name: 12780, dtype: int64
内部标识号    12782
交易次数        15
交易金额       803
Name: 12781, dtype: int64
内部标识号    12783
交易次数        10
交易金额       378
Name: 12782, dtype: int64
内部标识号    12784
交易次数         8
交易金额       924
Name: 12783, dtype: int64
内部标识号    12785
交易次数       152
交易金额     46331
Name: 12784, dtype: int64
内部标识号    12786
交易次数         3
交易金额       407
Name: 12785, dtype: int64
内部标识号    12787
交易次数        62
交易金额     49312
Name: 12786, dtype: int64
内部标识号    12788
交易次数        17
交易金额       862
Name: 12787, dtype: int64
内部标识号    12789
交易次数         2
交易金额       872
Name: 12788, dtype: int64
内部标识号    12790
交易次数        11
交易金额       618
Name: 12789, dtype: int64
内部标识号    12791
交易次数       269
交易金额     31877
Name: 12790, dtype: int64
内部标识号    12792
交易次数         2
交易金额       404
Name: 12791, dtype: int64
内部标识号    12793
交易次数         8
交易金额       143
Name: 12792, dtype: int64
内部标识号    12794
交易次数        23
交易金额       916
Name: 12793, dtype: int64
内部标识号    12795
交易次数         0
交易金额      6980
Name: 12794, dtype: int64
内部标识号    12796
交易次数        26
交易金额      2015
Name: 12795, dtype: int64
内部标识号    12797
交易次数         1
交易金额      9218
Name: 12796, dtype: int64
内部标识号    12798
交易次数         3
交易金额       281
Name: 12797, dtype: int64
内部标识号    12799
交易次数         1
交易金额      7945
Name: 12798, dtype: int64
内部标识号    12800
交易次数         5
交易金额     20072
Name: 12799, dtype: int64
内部标识号    12801
交易次数        15
交易金额      1246
Name: 12800, dtype: int64
内部标识号    12802
交易次数         2
交易金额       331
Name: 12801, dtype: int64
内部标识号    12803
交易次数        29
交易金额      3236
Name: 12802, dtype: int64
内部标识号    12804
交易次数         3
交易金额       472
Name: 12803, dtype: int64
内部标识号    12805
交易次数         2
交易金额       521
Name: 12804, dtype: int64
内部标识号    12806
交易次数         8
交易金额       102
Name: 12805, dtype: int64
内部标识号    12807
交易次数         7
交易金额       123
Name: 12806, dtype: int64
内部标识号    12808
交易次数         2
交易金额       489
Name: 12807, dtype: int64
内部标识号    12809
交易次数         3
交易金额       335
Name: 12808, dtype: int64
内部标识号    12810
交易次数        13
交易金额       614
Name: 12809, dtype: int64
内部标识号    12811
交易次数        10
交易金额       353
Name: 12810, dtype: int64
内部标识号    12812
交易次数         3
交易金额       104
Name: 12811, dtype: int64
内部标识号    12813
交易次数        15
交易金额       533
Name: 12812, dtype: int64
内部标识号    12814
交易次数         0
交易金额      5856
Name: 12813, dtype: int64
内部标识号    12815
交易次数        19
交易金额      7661
Name: 12814, dtype: int64
内部标识号    12816
交易次数         7
交易金额     57788
Name: 12815, dtype: int64
内部标识号    12817
交易次数        15
交易金额       676
Name: 12816, dtype: int64
内部标识号    12818
交易次数         3
交易金额       388
Name: 12817, dtype: int64
内部标识号    12819
交易次数        23
交易金额      9607
Name: 12818, dtype: int64
内部标识号    12820
交易次数         7
交易金额     77992
Name: 12819, dtype: int64
内部标识号    12821
交易次数         2
交易金额       458
Name: 12820, dtype: int64
内部标识号    12822
交易次数        12
交易金额       879
Name: 12821, dtype: int64
内部标识号    12823
交易次数         3
交易金额       227
Name: 12822, dtype: int64
内部标识号    12824
交易次数        12
交易金额       841
Name: 12823, dtype: int64
内部标识号    12825
交易次数        30
交易金额      3772
Name: 12824, dtype: int64
内部标识号    12826
交易次数       190
交易金额     57381
Name: 12825, dtype: int64
内部标识号    12827
交易次数         3
交易金额       476
Name: 12826, dtype: int64
内部标识号    12828
交易次数         2
交易金额       654
Name: 12827, dtype: int64
内部标识号    12829
交易次数         4
交易金额       108
Name: 12828, dtype: int64
内部标识号    12830
交易次数         3
交易金额       407
Name: 12829, dtype: int64
内部标识号    12831
交易次数        16
交易金额       944
Name: 12830, dtype: int64
内部标识号    12832
交易次数         2
交易金额       286
Name: 12831, dtype: int64
内部标识号    12833
交易次数         0
交易金额      4085
Name: 12832, dtype: int64
内部标识号    12834
交易次数         6
交易金额       246
Name: 12833, dtype: int64
内部标识号    12835
交易次数         3
交易金额       329
Name: 12834, dtype: int64
内部标识号    12836
交易次数        13
交易金额       784
Name: 12835, dtype: int64
内部标识号    12837
交易次数        12
交易金额       371
Name: 12836, dtype: int64
内部标识号    12838
交易次数         2
交易金额       496
Name: 12837, dtype: int64
内部标识号    12839
交易次数        15
交易金额       947
Name: 12838, dtype: int64
内部标识号    12840
交易次数        15
交易金额       789
Name: 12839, dtype: int64
内部标识号    12841
交易次数         6
交易金额       270
Name: 12840, dtype: int64
内部标识号    12842
交易次数        15
交易金额        26
Name: 12841, dtype: int64
内部标识号    12843
交易次数         6
交易金额     53624
Name: 12842, dtype: int64
内部标识号    12844
交易次数         8
交易金额       967
Name: 12843, dtype: int64
内部标识号    12845
交易次数        30
交易金额       904
Name: 12844, dtype: int64
内部标识号    12846
交易次数         8
交易金额       251
Name: 12845, dtype: int64
内部标识号    12847
交易次数         3
交易金额       303
Name: 12846, dtype: int64
内部标识号    12848
交易次数         3
交易金额       304
Name: 12847, dtype: int64
内部标识号    12849
交易次数        14
交易金额       377
Name: 12848, dtype: int64
内部标识号    12850
交易次数         5
交易金额     51055
Name: 12849, dtype: int64
内部标识号    12851
交易次数         8
交易金额       186
Name: 12850, dtype: int64
内部标识号    12852
交易次数         3
交易金额       300
Name: 12851, dtype: int64
内部标识号    12853
交易次数         3
交易金额     94113
Name: 12852, dtype: int64
内部标识号    12854
交易次数         2
交易金额       353
Name: 12853, dtype: int64
内部标识号    12855
交易次数         0
交易金额      1911
Name: 12854, dtype: int64
内部标识号    12856
交易次数         2
交易金额       340
Name: 12855, dtype: int64
内部标识号    12857
交易次数         0
交易金额      9137
Name: 12856, dtype: int64
内部标识号    12858
交易次数        26
交易金额       717
Name: 12857, dtype: int64
内部标识号    12859
交易次数         1
交易金额       740
Name: 12858, dtype: int64
内部标识号    12860
交易次数         2
交易金额       409
Name: 12859, dtype: int64
内部标识号    12861
交易次数        16
交易金额       940
Name: 12860, dtype: int64
内部标识号    12862
交易次数         3
交易金额       462
Name: 12861, dtype: int64
内部标识号    12863
交易次数        17
交易金额       547
Name: 12862, dtype: int64
内部标识号    12864
交易次数         6
交易金额     21378
Name: 12863, dtype: int64
内部标识号    12865
交易次数        30
交易金额     98359
Name: 12864, dtype: int64
内部标识号    12866
交易次数        94
交易金额     17554
Name: 12865, dtype: int64
内部标识号    12867
交易次数        15
交易金额       895
Name: 12866, dtype: int64
内部标识号    12868
交易次数         1
交易金额       757
Name: 12867, dtype: int64
内部标识号    12869
交易次数        11
交易金额       389
Name: 12868, dtype: int64
内部标识号    12870
交易次数       271
交易金额     96356
Name: 12869, dtype: int64
内部标识号    12871
交易次数         0
交易金额      7824
Name: 12870, dtype: int64
内部标识号    12872
交易次数        10
交易金额       360
Name: 12871, dtype: int64
内部标识号    12873
交易次数         3
交易金额       488
Name: 12872, dtype: int64
内部标识号    12874
交易次数        22
交易金额       827
Name: 12873, dtype: int64
内部标识号    12875
交易次数        10
交易金额       672
Name: 12874, dtype: int64
内部标识号    12876
交易次数        13
交易金额       908
Name: 12875, dtype: int64
内部标识号    12877
交易次数         9
交易金额       875
Name: 12876, dtype: int64
内部标识号    12878
交易次数         1
交易金额      5369
Name: 12877, dtype: int64
内部标识号    12879
交易次数         7
交易金额       107
Name: 12878, dtype: int64
内部标识号    12880
交易次数         5
交易金额     24496
Name: 12879, dtype: int64
内部标识号    12881
交易次数        13
交易金额       629
Name: 12880, dtype: int64
内部标识号    12882
交易次数        14
交易金额       853
Name: 12881, dtype: int64
内部标识号    12883
交易次数        76
交易金额     97984
Name: 12882, dtype: int64
内部标识号    12884
交易次数         2
交易金额       896
Name: 12883, dtype: int64
内部标识号    12885
交易次数         0
交易金额      7689
Name: 12884, dtype: int64
内部标识号    12886
交易次数         0
交易金额      1761
Name: 12885, dtype: int64
内部标识号    12887
交易次数         2
交易金额       358
Name: 12886, dtype: int64
内部标识号    12888
交易次数       134
交易金额     82069
Name: 12887, dtype: int64
内部标识号    12889
交易次数        12
交易金额       683
Name: 12888, dtype: int64
内部标识号    12890
交易次数         3
交易金额       332
Name: 12889, dtype: int64
内部标识号    12891
交易次数        21
交易金额      2894
Name: 12890, dtype: int64
内部标识号    12892
交易次数         2
交易金额       430
Name: 12891, dtype: int64
内部标识号    12893
交易次数         8
交易金额       152
Name: 12892, dtype: int64
内部标识号    12894
交易次数         8
交易金额       205
Name: 12893, dtype: int64
内部标识号    12895
交易次数         2
交易金额       433
Name: 12894, dtype: int64
内部标识号    12896
交易次数        10
交易金额       393
Name: 12895, dtype: int64
内部标识号    12897
交易次数        21
交易金额      7768
Name: 12896, dtype: int64
内部标识号    12898
交易次数         3
交易金额       186
Name: 12897, dtype: int64
内部标识号    12899
交易次数         9
交易金额       389
Name: 12898, dtype: int64
内部标识号    12900
交易次数        10
交易金额       303
Name: 12899, dtype: int64
内部标识号    12901
交易次数         2
交易金额       818
Name: 12900, dtype: int64
内部标识号    12902
交易次数        29
交易金额       724
Name: 12901, dtype: int64
内部标识号    12903
交易次数         8
交易金额       180
Name: 12902, dtype: int64
内部标识号    12904
交易次数         3
交易金额       238
Name: 12903, dtype: int64
内部标识号    12905
交易次数         1
交易金额       810
Name: 12904, dtype: int64
内部标识号    12906
交易次数         2
交易金额       890
Name: 12905, dtype: int64
内部标识号    12907
交易次数        10
交易金额       587
Name: 12906, dtype: int64
内部标识号    12908
交易次数         3
交易金额       338
Name: 12907, dtype: int64
内部标识号    12909
交易次数        12
交易金额       692
Name: 12908, dtype: int64
内部标识号    12910
交易次数        11
交易金额       644
Name: 12909, dtype: int64
内部标识号    12911
交易次数         2
交易金额       497
Name: 12910, dtype: int64
内部标识号    12912
交易次数         0
交易金额      7159
Name: 12911, dtype: int64
内部标识号    12913
交易次数         4
交易金额       109
Name: 12912, dtype: int64
内部标识号    12914
交易次数        14
交易金额       789
Name: 12913, dtype: int64
内部标识号    12915
交易次数         8
交易金额       946
Name: 12914, dtype: int64
内部标识号    12916
交易次数        14
交易金额       627
Name: 12915, dtype: int64
内部标识号    12917
交易次数         8
交易金额       580
Name: 12916, dtype: int64
内部标识号    12918
交易次数         5
交易金额       205
Name: 12917, dtype: int64
内部标识号    12919
交易次数        11
交易金额       344
Name: 12918, dtype: int64
内部标识号    12920
交易次数         8
交易金额       167
Name: 12919, dtype: int64
内部标识号    12921
交易次数         9
交易金额       598
Name: 12920, dtype: int64
内部标识号    12922
交易次数        14
交易金额       487
Name: 12921, dtype: int64
内部标识号    12923
交易次数        24
交易金额      9127
Name: 12922, dtype: int64
内部标识号    12924
交易次数         0
交易金额      4951
Name: 12923, dtype: int64
内部标识号    12925
交易次数        25
交易金额       850
Name: 12924, dtype: int64
内部标识号    12926
交易次数        17
交易金额       619
Name: 12925, dtype: int64
内部标识号    12927
交易次数         8
交易金额     65937
Name: 12926, dtype: int64
内部标识号    12928
交易次数         8
交易金额       416
Name: 12927, dtype: int64
内部标识号    12929
交易次数         6
交易金额       258
Name: 12928, dtype: int64
内部标识号    12930
交易次数         1
交易金额      6781
Name: 12929, dtype: int64
内部标识号    12931
交易次数         8
交易金额       425
Name: 12930, dtype: int64
内部标识号    12932
交易次数         4
交易金额     33551
Name: 12931, dtype: int64
内部标识号    12933
交易次数        12
交易金额       505
Name: 12932, dtype: int64
内部标识号    12934
交易次数         1
交易金额       611
Name: 12933, dtype: int64
内部标识号    12935
交易次数         2
交易金额       880
Name: 12934, dtype: int64
内部标识号    12936
交易次数         3
交易金额       199
Name: 12935, dtype: int64
内部标识号    12937
交易次数         0
交易金额      9721
Name: 12936, dtype: int64
内部标识号    12938
交易次数         2
交易金额       635
Name: 12937, dtype: int64
内部标识号    12939
交易次数        10
交易金额       635
Name: 12938, dtype: int64
内部标识号    12940
交易次数         1
交易金额      3621
Name: 12939, dtype: int64
内部标识号    12941
交易次数         8
交易金额     19173
Name: 12940, dtype: int64
内部标识号    12942
交易次数         3
交易金额       422
Name: 12941, dtype: int64
内部标识号    12943
交易次数         1
交易金额       561
Name: 12942, dtype: int64
内部标识号    12944
交易次数        29
交易金额      2104
Name: 12943, dtype: int64
内部标识号    12945
交易次数         0
交易金额      4603
Name: 12944, dtype: int64
内部标识号    12946
交易次数        12
交易金额       952
Name: 12945, dtype: int64
内部标识号    12947
交易次数        15
交易金额       739
Name: 12946, dtype: int64
内部标识号    12948
交易次数         3
交易金额     74175
Name: 12947, dtype: int64
内部标识号    12949
交易次数         8
交易金额       622
Name: 12948, dtype: int64
内部标识号    12950
交易次数         8
交易金额       276
Name: 12949, dtype: int64
内部标识号    12951
交易次数        22
交易金额        63
Name: 12950, dtype: int64
内部标识号    12952
交易次数        27
交易金额      8867
Name: 12951, dtype: int64
内部标识号    12953
交易次数        15
交易金额       377
Name: 12952, dtype: int64
内部标识号    12954
交易次数         6
交易金额       240
Name: 12953, dtype: int64
内部标识号    12955
交易次数         2
交易金额       395
Name: 12954, dtype: int64
内部标识号    12956
交易次数         8
交易金额     30058
Name: 12955, dtype: int64
内部标识号    12957
交易次数         2
交易金额       458
Name: 12956, dtype: int64
内部标识号    12958
交易次数        11
交易金额       483
Name: 12957, dtype: int64
内部标识号    12959
交易次数        12
交易金额       452
Name: 12958, dtype: int64
内部标识号    12960
交易次数        63
交易金额     36862
Name: 12959, dtype: int64
内部标识号    12961
交易次数        15
交易金额       579
Name: 12960, dtype: int64
内部标识号    12962
交易次数         8
交易金额       441
Name: 12961, dtype: int64
内部标识号    12963
交易次数         5
交易金额       197
Name: 12962, dtype: int64
内部标识号    12964
交易次数         6
交易金额       231
Name: 12963, dtype: int64
内部标识号    12965
交易次数         2
交易金额       561
Name: 12964, dtype: int64
内部标识号    12966
交易次数        29
交易金额       819
Name: 12965, dtype: int64
内部标识号    12967
交易次数         3
交易金额       496
Name: 12966, dtype: int64
内部标识号    12968
交易次数         2
交易金额       707
Name: 12967, dtype: int64
内部标识号    12969
交易次数         2
交易金额       381
Name: 12968, dtype: int64
内部标识号    12970
交易次数         8
交易金额       452
Name: 12969, dtype: int64
内部标识号    12971
交易次数         8
交易金额       207
Name: 12970, dtype: int64
内部标识号    12972
交易次数         8
交易金额       281
Name: 12971, dtype: int64
内部标识号    12973
交易次数        13
交易金额       367
Name: 12972, dtype: int64
内部标识号    12974
交易次数         7
交易金额     42885
Name: 12973, dtype: int64
内部标识号    12975
交易次数         3
交易金额       446
Name: 12974, dtype: int64
内部标识号    12976
交易次数         6
交易金额       133
Name: 12975, dtype: int64
内部标识号    12977
交易次数        21
交易金额      2150
Name: 12976, dtype: int64
内部标识号    12978
交易次数         8
交易金额       142
Name: 12977, dtype: int64
内部标识号    12979
交易次数        11
交易金额       711
Name: 12978, dtype: int64
内部标识号    12980
交易次数        30
交易金额      5422
Name: 12979, dtype: int64
内部标识号    12981
交易次数        26
交易金额      6442
Name: 12980, dtype: int64
内部标识号    12982
交易次数         0
交易金额      2818
Name: 12981, dtype: int64
内部标识号    12983
交易次数        11
交易金额       375
Name: 12982, dtype: int64
内部标识号    12984
交易次数         7
交易金额       282
Name: 12983, dtype: int64
内部标识号    12985
交易次数         7
交易金额     63802
Name: 12984, dtype: int64
内部标识号    12986
交易次数         2
交易金额       405
Name: 12985, dtype: int64
内部标识号    12987
交易次数         4
交易金额       204
Name: 12986, dtype: int64
内部标识号    12988
交易次数         6
交易金额     13665
Name: 12987, dtype: int64
内部标识号    12989
交易次数         1
交易金额      4464
Name: 12988, dtype: int64
内部标识号    12990
交易次数        20
交易金额      4547
Name: 12989, dtype: int64
内部标识号    12991
交易次数         1
交易金额       621
Name: 12990, dtype: int64
内部标识号    12992
交易次数         6
交易金额       123
Name: 12991, dtype: int64
内部标识号    12993
交易次数         2
交易金额       515
Name: 12992, dtype: int64
内部标识号    12994
交易次数         8
交易金额       716
Name: 12993, dtype: int64
内部标识号    12995
交易次数         6
交易金额     41003
Name: 12994, dtype: int64
内部标识号    12996
交易次数        10
交易金额       873
Name: 12995, dtype: int64
内部标识号    12997
交易次数         2
交易金额       995
Name: 12996, dtype: int64
内部标识号    12998
交易次数         8
交易金额       955
Name: 12997, dtype: int64
内部标识号    12999

Name: 13057, dtype: int64
内部标识号    13059
交易次数         2
交易金额       425
Name: 13058, dtype: int64
内部标识号    13060
交易次数         8
交易金额     21865
Name: 13059, dtype: int64
内部标识号    13061
交易次数        15
交易金额       709
Name: 13060, dtype: int64
内部标识号    13062
交易次数         8
交易金额       259
Name: 13061, dtype: int64
内部标识号    13063
交易次数         8
交易金额       700
Name: 13062, dtype: int64
内部标识号    13064
交易次数         0
交易金额      3023
Name: 13063, dtype: int64
内部标识号    13065
交易次数        13
交易金额       668
Name: 13064, dtype: int64
内部标识号    13066
交易次数         0
交易金额      9313
Name: 13065, dtype: int64
内部标识号    13067
交易次数         2
交易金额       463
Name: 13066, dtype: int64
内部标识号    13068
交易次数        14
交易金额       388
Name: 13067, dtype: int64
内部标识号    13069
交易次数         3
交易金额       499
Name: 13068, dtype: int64
内部标识号    13070
交易次数        12
交易金额       460
Name: 13069, dtype: int64
内部标识号    13071
交易次数         0
交易金额      4171
Name: 13070, dtype: int64
内部标识号    13072
交易次数         4
交易金额       275
Name: 13071, dtype: int64
内部标识号    13073
交易次数        10
交易金额       554
Name: 13072, dtype: int64
内部标识号    13074
交易次数         0
交易金额      7835
Name: 13073, dtype: int64
内部标识号    13075
交易次数         1
交易金额      4392
Name: 13074, dtype: int64
内部标识号    13076
交易次数         8
交易金额       311
Name: 13075, dtype: int64
内部标识号    13077
交易次数         2
交易金额       760
Name: 13076, dtype: int64
内部标识号    13078
交易次数         3
交易金额       459
Name: 13077, dtype: int64
内部标识号    13079
交易次数         0
交易金额      2253
Name: 13078, dtype: int64
内部标识号    13080
交易次数         2
交易金额       986
Name: 13079, dtype: int64
内部标识号    13081
交易次数        10
交易金额       542
Name: 13080, dtype: int64
内部标识号    13082
交易次数        13
交易金额       646
Name: 13081, dtype: int64
内部标识号    13083
交易次数         4
交易金额       294
Name: 13082, dtype: int64
内部标识号    13084
交易次数         6
交易金额       281
Name: 13083, dtype: int64
内部标识号    13085
交易次数         7
交易金额       247
Name: 13084, dtype: int64
内部标识号    13086
交易次数         1
交易金额       734
Name: 13085, dtype: int64
内部标识号    13087
交易次数         8
交易金额       922
Name: 13086, dtype: int64
内部标识号    13088
交易次数         0
交易金额      3031
Name: 13087, dtype: int64
内部标识号    13089
交易次数         3
交易金额       325
Name: 13088, dtype: int64
内部标识号    13090
交易次数         2
交易金额       333
Name: 13089, dtype: int64
内部标识号    13091
交易次数         9
交易金额       439
Name: 13090, dtype: int64
内部标识号    13092
交易次数         9
交易金额       597
Name: 13091, dtype: int64
内部标识号    13093
交易次数        14
交易金额       701
Name: 13092, dtype: int64
内部标识号    13094
交易次数        22
交易金额      8536
Name: 13093, dtype: int64
内部标识号    13095
交易次数        11
交易金额       447
Name: 13094, dtype: int64
内部标识号    13096
交易次数         3
交易金额       241
Name: 13095, dtype: int64
内部标识号    13097
交易次数        13
交易金额       397
Name: 13096, dtype: int64
内部标识号    13098
交易次数        12
交易金额       318
Name: 13097, dtype: int64
内部标识号    13099
交易次数         4
交易金额       202
Name: 13098, dtype: int64
内部标识号    13100
交易次数         3
交易金额       414
Name: 13099, dtype: int64
内部标识号    13101
交易次数         9
交易金额       969
Name: 13100, dtype: int64
内部标识号    13102
交易次数         6
交易金额       253
Name: 13101, dtype: int64
内部标识号    13103
交易次数         3
交易金额       141
Name: 13102, dtype: int64
内部标识号    13104
交易次数         2
交易金额       228
Name: 13103, dtype: int64
内部标识号    13105
交易次数        30
交易金额       938
Name: 13104, dtype: int64
内部标识号    13106
交易次数        25
交易金额       652
Name: 13105, dtype: int64
内部标识号    13107
交易次数         3
交易金额       352
Name: 13106, dtype: int64
内部标识号    13108
交易次数        10
交易金额       729
Name: 13107, dtype: int64
内部标识号    13109
交易次数         5
交易金额       203
Name: 13108, dtype: int64
内部标识号    13110
交易次数         5
交易金额       126
Name: 13109, dtype: int64
内部标识号    13111
交易次数        11
交易金额       437
Name: 13110, dtype: int64
内部标识号    13112
交易次数         5
交易金额       249
Name: 13111, dtype: int64
内部标识号    13113
交易次数        10
交易金额       749
Name: 13112, dtype: int64
内部标识号    13114
交易次数         2
交易金额       121
Name: 13113, dtype: int64
内部标识号    13115
交易次数        14
交易金额       950
Name: 13114, dtype: int64
内部标识号    13116
交易次数        15
交易金额      2528
Name: 13115, dtype: int64
内部标识号    13117
交易次数        11
交易金额       974
Name: 13116, dtype: int64
内部标识号    13118
交易次数         3
交易金额     86766
Name: 13117, dtype: int64
内部标识号    13119
交易次数        26
交易金额      7031
Name: 13118, dtype: int64
内部标识号    13120
交易次数         4
交易金额       108
Name: 13119, dtype: int64
内部标识号    13121
交易次数         0
交易金额      2451
Name: 13120, dtype: int64
内部标识号    13122
交易次数        14
交易金额       423
Name: 13121, dtype: int64
内部标识号    13123
交易次数        28
交易金额      5141
Name: 13122, dtype: int64
内部标识号    13124
交易次数        15
交易金额       954
Name: 13123, dtype: int64
内部标识号    13125
交易次数         3
交易金额       309
Name: 13124, dtype: int64
内部标识号    13126
交易次数         3
交易金额       281
Name: 13125, dtype: int64
内部标识号    13127
交易次数        10
交易金额       984
Name: 13126, dtype: int64
内部标识号    13128
交易次数        11
交易金额       307
Name: 13127, dtype: int64
内部标识号    13129
交易次数         6
交易金额       197
Name: 13128, dtype: int64
内部标识号    13130
交易次数         2
交易金额       639
Name: 13129, dtype: int64
内部标识号    13131
交易次数        12
交易金额       794
Name: 13130, dtype: int64
内部标识号    13132
交易次数         5
交易金额       236
Name: 13131, dtype: int64
内部标识号    13133
交易次数        15
交易金额       424
Name: 13132, dtype: int64
内部标识号    13134
交易次数         0
交易金额      5809
Name: 13133, dtype: int64
内部标识号    13135
交易次数        22
交易金额      7555
Name: 13134, dtype: int64
内部标识号    13136
交易次数         0
交易金额      7920
Name: 13135, dtype: int64
内部标识号    13137
交易次数         9
交易金额       927
Name: 13136, dtype: int64
内部标识号    13138
交易次数         0
交易金额      6501
Name: 13137, dtype: int64
内部标识号    13139
交易次数         1
交易金额       641
Name: 13138, dtype: int64
内部标识号    13140
交易次数        12
交易金额       472
Name: 13139, dtype: int64
内部标识号    13141
交易次数         2
交易金额       725
Name: 13140, dtype: int64
内部标识号    13142
交易次数        13
交易金额       491
Name: 13141, dtype: int64
内部标识号    13143
交易次数        14
交易金额       767
Name: 13142, dtype: int64
内部标识号    13144
交易次数         9
交易金额       623
Name: 13143, dtype: int64
内部标识号    13145
交易次数        11
交易金额       370
Name: 13144, dtype: int64
内部标识号    13146
交易次数        25
交易金额      2770
Name: 13145, dtype: int64
内部标识号    13147
交易次数         8
交易金额       299
Name: 13146, dtype: int64
内部标识号    13148
交易次数        18
交易金额       672
Name: 13147, dtype: int64
内部标识号    13149
交易次数         0
交易金额      1277
Name: 13148, dtype: int64
内部标识号    13150
交易次数         6
交易金额       268
Name: 13149, dtype: int64
内部标识号    13151
交易次数        13
交易金额       632
Name: 13150, dtype: int64
内部标识号    13152
交易次数         1
交易金额       828
Name: 13151, dtype: int64
内部标识号    13153
交易次数         3
交易金额     68908
Name: 13152, dtype: int64
内部标识号    13154
交易次数        11
交易金额       900
Name: 13153, dtype: int64
内部标识号    13155
交易次数         6
交易金额     62080
Name: 13154, dtype: int64
内部标识号    13156
交易次数         9
交易金额       416
Name: 13155, dtype: int64
内部标识号    13157
交易次数         1
交易金额       773
Name: 13156, dtype: int64
内部标识号    13158
交易次数        24
交易金额      3776
Name: 13157, dtype: int64
内部标识号    13159
交易次数        15
交易金额       632
Name: 13158, dtype: int64
内部标识号    13160
交易次数        19
交易金额      6402
Name: 13159, dtype: int64
内部标识号    13161
交易次数         1
交易金额       862
Name: 13160, dtype: int64
内部标识号    13162
交易次数        11
交易金额       477
Name: 13161, dtype: int64
内部标识号    13163
交易次数        15
交易金额       821
Name: 13162, dtype: int64
内部标识号    13164
交易次数         8
交易金额       361
Name: 13163, dtype: int64
内部标识号    13165
交易次数         8
交易金额       489
Name: 13164, dtype: int64
内部标识号    13166
交易次数         2
交易金额       302
Name: 13165, dtype: int64
内部标识号    13167
交易次数        66
交易金额     89541
Name: 13166, dtype: int64
内部标识号    13168
交易次数         2
交易金额       169
Name: 13167, dtype: int64
内部标识号    13169
交易次数         6
交易金额       149
Name: 13168, dtype: int64
内部标识号    13170
交易次数        17
交易金额      4390
Name: 13169, dtype: int64
内部标识号    13171
交易次数        10
交易金额       421
Name: 13170, dtype: int64
内部标识号    13172
交易次数         8
交易金额       505
Name: 13171, dtype: int64
内部标识号    13173
交易次数        14
交易金额       952
Name: 13172, dtype: int64
内部标识号    13174
交易次数        20
交易金额       934
Name: 13173, dtype: int64
内部标识号    13175
交易次数         2
交易金额       344
Name: 13174, dtype: int64
内部标识号    13176
交易次数        13
交易金额       479
Name: 13175, dtype: int64
内部标识号    13177
交易次数         1
交易金额       532
Name: 13176, dtype: int64
内部标识号    13178
交易次数        11
交易金额       933
Name: 13177, dtype: int64
内部标识号    13179
交易次数        26
交易金额      7487
Name: 13178, dtype: int64
内部标识号    13180
交易次数         2
交易金额       818
Name: 13179, dtype: int64
内部标识号    13181
交易次数         0
交易金额      6274
Name: 13180, dtype: int64
内部标识号    13182
交易次数         0
交易金额      4998
Name: 13181, dtype: int64
内部标识号    13183
交易次数        23
交易金额       680
Name: 13182, dtype: int64
内部标识号    13184
交易次数         2
交易金额       421
Name: 13183, dtype: int64
内部标识号    13185
交易次数         2
交易金额       369
Name: 13184, dtype: int64
内部标识号    13186
交易次数         8
交易金额       934
Name: 13185, dtype: int64
内部标识号    13187
交易次数        13
交易金额       646
Name: 13186, dtype: int64
内部标识号    13188
交易次数         7
交易金额       158
Name: 13187, dtype: int64
内部标识号    13189
交易次数         1
交易金额       840
Name: 13188, dtype: int64
内部标识号    13190
交易次数         2
交易金额       398
Name: 13189, dtype: int64
内部标识号    13191
交易次数         3
交易金额       298
Name: 13190, dtype: int64
内部标识号    13192
交易次数         4
交易金额       244
Name: 13191, dtype: int64
内部标识号    13193
交易次数         0
交易金额      3833
Name: 13192, dtype: int64
内部标识号    13194
交易次数        27
交易金额      5776
Name: 13193, dtype: int64
内部标识号    13195
交易次数         2
交易金额       839
Name: 13194, dtype: int64
内部标识号    13196
交易次数        12
交易金额       792
Name: 13195, dtype: int64
内部标识号    13197
交易次数         2
交易金额       617
Name: 13196, dtype: int64
内部标识号    13198
交易次数         1
交易金额       591
Name: 13197, dtype: int64
内部标识号    13199
交易次数         3
交易金额       478
Name: 13198, dtype: int64
内部标识号    13200
交易次数         2
交易金额       871
Name: 13199, dtype: int64
内部标识号    13201
交易次数         1
交易金额       649
Name: 13200, dtype: int64
内部标识号    13202
交易次数         2
交易金额       779
Name: 13201, dtype: int64
内部标识号    13203
交易次数         8
交易金额       230
Name: 13202, dtype: int64
内部标识号    13204
交易次数         2
交易金额       413
Name: 13203, dtype: int64
内部标识号    13205
交易次数        10
交易金额       330
Name: 13204, dtype: int64
内部标识号    13206
交易次数         5
交易金额     47612
Name: 13205, dtype: int64
内部标识号    13207
交易次数        26
交易金额       577
Name: 13206, dtype: int64
内部标识号    13208
交易次数        10
交易金额       328
Name: 13207, dtype: int64
内部标识号    13209
交易次数        11
交易金额       905
Name: 13208, dtype: int64
内部标识号    13210
交易次数        11
交易金额       448
Name: 13209, dtype: int64
内部标识号    13211
交易次数        30
交易金额      9441
Name: 13210, dtype: int64
内部标识号    13212
交易次数        13
交易金额       356
Name: 13211, dtype: int64
内部标识号    13213
交易次数        20
交易金额      5523
Name: 13212, dtype: int64
内部标识号    13214
交易次数         9
交易金额       536
Name: 13213, dtype: int64
内部标识号    13215
交易次数        21
交易金额      5445
Name: 13214, dtype: int64
内部标识号    13216
交易次数         4
交易金额       110
Name: 13215, dtype: int64
内部标识号    13217
交易次数       222
交易金额     58264
Name: 13216, dtype: int64
内部标识号    13218
交易次数        23
交易金额      3662
Name: 13217, dtype: int64
内部标识号    13219
交易次数         8
交易金额       367
Name: 13218, dtype: int64
内部标识号    13220
交易次数         8
交易金额       549
Name: 13219, dtype: int64
内部标识号    13221
交易次数         8
交易金额       272
Name: 13220, dtype: int64
内部标识号    13222
交易次数        15
交易金额       769
Name: 13221, dtype: int64
内部标识号    13223
交易次数        14
交易金额       622
Name: 13222, dtype: int64
内部标识号    13224
交易次数         8
交易金额       857
Name: 13223, dtype: int64
内部标识号    13225
交易次数         1
交易金额       735
Name: 13224, dtype: int64
内部标识号    13226
交易次数        25
交易金额      3233
Name: 13225, dtype: int64
内部标识号    13227
交易次数         3
交易金额       413
Name: 13226, dtype: int64
内部标识号    13228
交易次数         8
交易金额       273
Name: 13227, dtype: int64
内部标识号    13229
交易次数         2
交易金额       993
Name: 13228, dtype: int64
内部标识号    13230
交易次数        31
交易金额     62699
Name: 13229, dtype: int64
内部标识号    13231
交易次数        10
交易金额       739
Name: 13230, dtype: int64
内部标识号    13232
交易次数         3
交易金额       469
Name: 13231, dtype: int64
内部标识号    13233
交易次数       247
交易金额     27300
Name: 13232, dtype: int64
内部标识号    13234
交易次数        55
交易金额     81093
Name: 13233, dtype: int64
内部标识号    13235
交易次数         9
交易金额       650
Name: 13234, dtype: int64
内部标识号    13236
交易次数        26
交易金额      4183
Name: 13235, dtype: int64
内部标识号    13237
交易次数         5
交易金额       268
Name: 13236, dtype: int64
内部标识号    13238
交易次数         8
交易金额       853
Name: 13237, dtype: int64
内部标识号    13239
交易次数        10
交易金额       968
Name: 13238, dtype: int64
内部标识号    13240
交易次数         3
交易金额       385
Name: 13239, dtype: int64
内部标识号    13241
交易次数        12
交易金额       521
Name: 13240, dtype: int64
内部标识号    13242
交易次数         6
交易金额       134
Name: 13241, dtype: int64
内部标识号    13243
交易次数         8
交易金额       129
Name: 13242, dtype: int64
内部标识号    13244
交易次数       210
交易金额     92851
Name: 13243, dtype: int64
内部标识号    13245
交易次数         9
交易金额       396
Name: 13244, dtype: int64
内部标识号    13246
交易次数        15
交易金额       466
Name: 13245, dtype: int64
内部标识号    13247
交易次数         2
交易金额       418
Name: 13246, dtype: int64
内部标识号    13248
交易次数        11
交易金额       352
Name: 13247, dtype: int64
内部标识号    13249
交易次数       259
交易金额     62150
Name: 13248, dtype: int64
内部标识号    13250
交易次数        13
交易金额       534
Name: 13249, dtype: int64
内部标识号    13251
交易次数        15
交易金额       343
Name: 13250, dtype: int64
内部标识号    13252
交易次数         8
交易金额       983
Name: 13251, dtype: int64
内部标识号    13253
交易次数         0
交易金额      4734
Name: 13252, dtype: int64
内部标识号    13254
交易次数       218
交易金额     79877
Name: 13253, dtype: int64
内部标识号    13255
交易次数        10
交易金额       540
Name: 13254, dtype: int64
内部标识号    13256
交易次数        12
交易金额       551
Name: 13255, dtype: int64
内部标识号    13257
交易次数         3
交易金额       138
Name: 13256, dtype: int64
内部标识号    13258
交易次数         2
交易金额       250

Name: 13257, dtype: int64
内部标识号    13259
交易次数        10
交易金额       815
Name: 13258, dtype: int64
内部标识号    13260
交易次数        15
交易金额       335
Name: 13259, dtype: int64
内部标识号    13261
交易次数        15
交易金额       391
Name: 13260, dtype: int64
内部标识号    13262
交易次数        21
交易金额      2690
Name: 13261, dtype: int64
内部标识号    13263
交易次数         4
交易金额       132
Name: 13262, dtype: int64
内部标识号    13264
交易次数        14
交易金额       415
Name: 13263, dtype: int64
内部标识号    13265
交易次数         2
交易金额       686
Name: 13264, dtype: int64
内部标识号    13266
交易次数         2
交易金额       934
Name: 13265, dtype: int64
内部标识号    13267
交易次数         9
交易金额       860
Name: 13266, dtype: int64
内部标识号    13268
交易次数         4
交易金额     88732
Name: 13267, dtype: int64
内部标识号    13269
交易次数         8
交易金额       370
Name: 13268, dtype: int64
内部标识号    13270
交易次数         3
交易金额       358
Name: 13269, dtype: int64
内部标识号    13271
交易次数         2
交易金额       426
Name: 13270, dtype: int64
内部标识号    13272
交易次数         3
交易金额       334
Name: 13271, dtype: int64
内部标识号    13273
交易次数        11
交易金额       436
Name: 13272, dtype: int64
内部标识号    13274
交易次数         2
交易金额       754
Name: 13273, dtype: int64
内部标识号    13275
交易次数        23
交易金额      7691
Name: 13274, dtype: int64
内部标识号    13276
交易次数         4
交易金额       166
Name: 13275, dtype: int64
内部标识号    13277
交易次数         4
交易金额       249
Name: 13276, dtype: int64
内部标识号    13278
交易次数        11
交易金额       486
Name: 13277, dtype: int64
内部标识号    13279
交易次数         0
交易金额      3886
Name: 13278, dtype: int64
内部标识号    13280
交易次数         1
交易金额      5857
Name: 13279, dtype: int64
内部标识号    13281
交易次数         3
交易金额       184
Name: 13280, dtype: int64
内部标识号    13282
交易次数        10
交易金额       551
Name: 13281, dtype: int64
内部标识号    13283
交易次数        12
交易金额       981
Name: 13282, dtype: int64
内部标识号    13284
交易次数       295
交易金额     55004
Name: 13283, dtype: int64
内部标识号    13285
交易次数         3
交易金额       384
Name: 13284, dtype: int64
内部标识号    13286
交易次数        12
交易金额       421
Name: 13285, dtype: int64
内部标识号    13287
交易次数         6
交易金额       233
Name: 13286, dtype: int64
内部标识号    13288
交易次数         2
交易金额       343
Name: 13287, dtype: int64
内部标识号    13289
交易次数        15
交易金额       384
Name: 13288, dtype: int64
内部标识号    13290
交易次数         1
交易金额       535
Name: 13289, dtype: int64
内部标识号    13291
交易次数         9
交易金额       887
Name: 13290, dtype: int64
内部标识号    13292
交易次数         1
交易金额       877
Name: 13291, dtype: int64
内部标识号    13293
交易次数         3
交易金额       324
Name: 13292, dtype: int64
内部标识号    13294
交易次数        15
交易金额       460
Name: 13293, dtype: int64
内部标识号    13295
交易次数         5
交易金额       195
Name: 13294, dtype: int64
内部标识号    13296
交易次数         1
交易金额      1268
Name: 13295, dtype: int64
内部标识号    13297
交易次数         7
交易金额       199
Name: 13296, dtype: int64
内部标识号    13298
交易次数        14
交易金额       491
Name: 13297, dtype: int64
内部标识号    13299
交易次数         1
交易金额       888
Name: 13298, dtype: int64
内部标识号    13300
交易次数         7
交易金额     99033
Name: 13299, dtype: int64
内部标识号    13301
交易次数         9
交易金额       575
Name: 13300, dtype: int64
内部标识号    13302
交易次数        13
交易金额       308
Name: 13301, dtype: int64
内部标识号    13303
交易次数         3
交易金额       350
Name: 13302, dtype: int64
内部标识号    13304
交易次数         3
交易金额       242
Name: 13303, dtype: int64
内部标识号    13305
交易次数        12
交易金额       365
Name: 13304, dtype: int64
内部标识号    13306
交易次数         3
交易金额       312
Name: 13305, dtype: int64
内部标识号    13307
交易次数         2
交易金额       397
Name: 13306, dtype: int64
内部标识号    13308
交易次数        15
交易金额       934
Name: 13307, dtype: int64
内部标识号    13309
交易次数         4
交易金额       135
Name: 13308, dtype: int64
内部标识号    13310
交易次数         2
交易金额       477
Name: 13309, dtype: int64
内部标识号    13311
交易次数         2
交易金额       430
Name: 13310, dtype: int64
内部标识号    13312
交易次数         1
交易金额      1838
Name: 13311, dtype: int64
内部标识号    13313
交易次数         1
交易金额       716
Name: 13312, dtype: int64
内部标识号    13314
交易次数         8
交易金额       541
Name: 13313, dtype: int64
内部标识号    13315
交易次数        25
交易金额      7341
Name: 13314, dtype: int64
内部标识号    13316
交易次数         1
交易金额      7817
Name: 13315, dtype: int64
内部标识号    13317
交易次数         9
交易金额       839
Name: 13316, dtype: int64
内部标识号    13318
交易次数        11
交易金额       958
Name: 13317, dtype: int64
内部标识号    13319
交易次数        15
交易金额       787
Name: 13318, dtype: int64
内部标识号    13320
交易次数       105
交易金额     48442
Name: 13319, dtype: int64
内部标识号    13321
交易次数        16
交易金额      5129
Name: 13320, dtype: int64
内部标识号    13322
交易次数        13
交易金额       482
Name: 13321, dtype: int64
内部标识号    13323
交易次数         1
交易金额       556
Name: 13322, dtype: int64
内部标识号    13324
交易次数         3
交易金额       316
Name: 13323, dtype: int64
内部标识号    13325
交易次数         8
交易金额       151
Name: 13324, dtype: int64
内部标识号    13326
交易次数         3
交易金额       483
Name: 13325, dtype: int64
内部标识号    13327
交易次数       125
交易金额     98090
Name: 13326, dtype: int64
内部标识号    13328
交易次数         1
交易金额       925
Name: 13327, dtype: int64
内部标识号    13329
交易次数        10
交易金额       992
Name: 13328, dtype: int64
内部标识号    13330
交易次数         8
交易金额       943
Name: 13329, dtype: int64
内部标识号    13331
交易次数        12
交易金额       852
Name: 13330, dtype: int64
内部标识号    13332
交易次数        21
交易金额      9384
Name: 13331, dtype: int64
内部标识号    13333
交易次数         2
交易金额       409
Name: 13332, dtype: int64
内部标识号    13334
交易次数         2
交易金额       422
Name: 13333, dtype: int64
内部标识号    13335
交易次数         1
交易金额      7342
Name: 13334, dtype: int64
内部标识号    13336
交易次数       248
交易金额     24016
Name: 13335, dtype: int64
内部标识号    13337
交易次数         2
交易金额       354
Name: 13336, dtype: int64
内部标识号    13338
交易次数        15
交易金额       976
Name: 13337, dtype: int64
内部标识号    13339
交易次数        14
交易金额       332
Name: 13338, dtype: int64
内部标识号    13340
交易次数         1
交易金额       830
Name: 13339, dtype: int64
内部标识号    13341
交易次数        23
交易金额       885
Name: 13340, dtype: int64
内部标识号    13342
交易次数        12
交易金额       396
Name: 13341, dtype: int64
内部标识号    13343
交易次数         1
交易金额       626
Name: 13342, dtype: int64
内部标识号    13344
交易次数         2
交易金额       674
Name: 13343, dtype: int64
内部标识号    13345
交易次数         1
交易金额       961
Name: 13344, dtype: int64
内部标识号    13346
交易次数        14
交易金额       481
Name: 13345, dtype: int64
内部标识号    13347
交易次数        23
交易金额      2301
Name: 13346, dtype: int64
内部标识号    13348
交易次数         6
交易金额       105
Name: 13347, dtype: int64
内部标识号    13349
交易次数         1
交易金额       867
Name: 13348, dtype: int64
内部标识号    13350
交易次数         6
交易金额     73924
Name: 13349, dtype: int64
内部标识号    13351
交易次数        13
交易金额       787
Name: 13350, dtype: int64
内部标识号    13352
交易次数        17
交易金额      8719
Name: 13351, dtype: int64
内部标识号    13353
交易次数         3
交易金额       203
Name: 13352, dtype: int64
内部标识号    13354
交易次数        21
交易金额       758
Name: 13353, dtype: int64
内部标识号    13355
交易次数         1
交易金额      2454
Name: 13354, dtype: int64
内部标识号    13356
交易次数        10
交易金额       889
Name: 13355, dtype: int64
内部标识号    13357
交易次数         8
交易金额       528
Name: 13356, dtype: int64
内部标识号    13358
交易次数         8
交易金额       236
Name: 13357, dtype: int64
内部标识号    13359
交易次数         7
交易金额     57569
Name: 13358, dtype: int64
内部标识号    13360
交易次数         2
交易金额       463
Name: 13359, dtype: int64
内部标识号    13361
交易次数         3
交易金额       282
Name: 13360, dtype: int64
内部标识号    13362
交易次数         3
交易金额     35565
Name: 13361, dtype: int64
内部标识号    13363
交易次数        15
交易金额       433
Name: 13362, dtype: int64
内部标识号    13364
交易次数         0
交易金额      6882
Name: 13363, dtype: int64
内部标识号    13365
交易次数         7
交易金额     95319
Name: 13364, dtype: int64
内部标识号    13366
交易次数         2
交易金额       324
Name: 13365, dtype: int64
内部标识号    13367
交易次数        10
交易金额       613
Name: 13366, dtype: int64
内部标识号    13368
交易次数         6
交易金额       298
Name: 13367, dtype: int64
内部标识号    13369
交易次数        15
交易金额       846
Name: 13368, dtype: int64
内部标识号    13370
交易次数        24
交易金额      7026
Name: 13369, dtype: int64
内部标识号    13371
交易次数        12
交易金额       857
Name: 13370, dtype: int64
内部标识号    13372
交易次数         9
交易金额       388
Name: 13371, dtype: int64
内部标识号    13373
交易次数         0
交易金额      6635
Name: 13372, dtype: int64
内部标识号    13374
交易次数         3
交易金额       318
Name: 13373, dtype: int64
内部标识号    13375
交易次数         2
交易金额       453
Name: 13374, dtype: int64
内部标识号    13376
交易次数         1
交易金额       785
Name: 13375, dtype: int64
内部标识号    13377
交易次数        15
交易金额       308
Name: 13376, dtype: int64
内部标识号    13378
交易次数         2
交易金额       100
Name: 13377, dtype: int64
内部标识号    13379
交易次数         1
交易金额      6351
Name: 13378, dtype: int64
内部标识号    13380
交易次数         2
交易金额       437
Name: 13379, dtype: int64
内部标识号    13381
交易次数         2
交易金额       507
Name: 13380, dtype: int64
内部标识号    13382
交易次数         2
交易金额       357
Name: 13381, dtype: int64
内部标识号    13383
交易次数         1
交易金额       890
Name: 13382, dtype: int64
内部标识号    13384
交易次数       192
交易金额     59812
Name: 13383, dtype: int64
内部标识号    13385
交易次数         7
交易金额       175
Name: 13384, dtype: int64
内部标识号    13386
交易次数         0
交易金额      3803
Name: 13385, dtype: int64
内部标识号    13387
交易次数        27
交易金额      4641
Name: 13386, dtype: int64
内部标识号    13388
交易次数       252
交易金额     43416
Name: 13387, dtype: int64
内部标识号    13389
交易次数        10
交易金额       874
Name: 13388, dtype: int64
内部标识号    13390
交易次数        10
交易金额       677
Name: 13389, dtype: int64
内部标识号    13391
交易次数        29
交易金额        73
Name: 13390, dtype: int64
内部标识号    13392
交易次数         3
交易金额       352
Name: 13391, dtype: int64
内部标识号    13393
交易次数        20
交易金额       588
Name: 13392, dtype: int64
内部标识号    13394
交易次数        14
交易金额       443
Name: 13393, dtype: int64
内部标识号    13395
交易次数         5
交易金额       276
Name: 13394, dtype: int64
内部标识号    13396
交易次数         5
交易金额       122
Name: 13395, dtype: int64
内部标识号    13397
交易次数        15
交易金额       676
Name: 13396, dtype: int64
内部标识号    13398
交易次数         0
交易金额      3225
Name: 13397, dtype: int64
内部标识号    13399
交易次数         2
交易金额       328
Name: 13398, dtype: int64
内部标识号    13400
交易次数         2
交易金额       438
Name: 13399, dtype: int64
内部标识号    13401
交易次数        11
交易金额       764
Name: 13400, dtype: int64
内部标识号    13402
交易次数         0
交易金额      6857
Name: 13401, dtype: int64
内部标识号    13403
交易次数        19
交易金额      1123
Name: 13402, dtype: int64
内部标识号    13404
交易次数         9
交易金额       817
Name: 13403, dtype: int64
内部标识号    13405
交易次数        11
交易金额       398
Name: 13404, dtype: int64
内部标识号    13406
交易次数        26
交易金额      9369
Name: 13405, dtype: int64
内部标识号    13407
交易次数         2
交易金额       465
Name: 13406, dtype: int64
内部标识号    13408
交易次数         6
交易金额       190
Name: 13407, dtype: int64
内部标识号    13409
交易次数        23
交易金额        21
Name: 13408, dtype: int64
内部标识号    13410
交易次数        14
交易金额       825
Name: 13409, dtype: int64
内部标识号    13411
交易次数         7
交易金额       139
Name: 13410, dtype: int64
内部标识号    13412
交易次数         3
交易金额       343
Name: 13411, dtype: int64
内部标识号    13413
交易次数         1
交易金额       951
Name: 13412, dtype: int64
内部标识号    13414
交易次数         1
交易金额       847
Name: 13413, dtype: int64
内部标识号    13415
交易次数         8
交易金额       697
Name: 13414, dtype: int64
内部标识号    13416
交易次数        27
交易金额       524
Name: 13415, dtype: int64
内部标识号    13417
交易次数        10
交易金额       415
Name: 13416, dtype: int64
内部标识号    13418
交易次数        13
交易金额       801
Name: 13417, dtype: int64
内部标识号    13419
交易次数         9
交易金额       500
Name: 13418, dtype: int64
内部标识号    13420
交易次数         1
交易金额      6341
Name: 13419, dtype: int64
内部标识号    13421
交易次数         4
交易金额       251
Name: 13420, dtype: int64
内部标识号    13422
交易次数         5
交易金额       258
Name: 13421, dtype: int64
内部标识号    13423
交易次数         5
交易金额       195
Name: 13422, dtype: int64
内部标识号    13424
交易次数         2
交易金额       392
Name: 13423, dtype: int64
内部标识号    13425
交易次数         0
交易金额      1171
Name: 13424, dtype: int64
内部标识号    13426
交易次数         3
交易金额     96195
Name: 13425, dtype: int64
内部标识号    13427
交易次数         0
交易金额      1935
Name: 13426, dtype: int64
内部标识号    13428
交易次数         2
交易金额       470
Name: 13427, dtype: int64
内部标识号    13429
交易次数        13
交易金额       353
Name: 13428, dtype: int64
内部标识号    13430
交易次数         3
交易金额       384
Name: 13429, dtype: int64
内部标识号    13431
交易次数         0
交易金额      4906
Name: 13430, dtype: int64
内部标识号    13432
交易次数        19
交易金额      6126
Name: 13431, dtype: int64
内部标识号    13433
交易次数         0
交易金额      8710
Name: 13432, dtype: int64
内部标识号    13434
交易次数         7
交易金额       180
Name: 13433, dtype: int64
内部标识号    13435
交易次数        12
交易金额       777
Name: 13434, dtype: int64
内部标识号    13436
交易次数         2
交易金额       627
Name: 13435, dtype: int64
内部标识号    13437
交易次数         4
交易金额       223
Name: 13436, dtype: int64
内部标识号    13438
交易次数         9
交易金额       977
Name: 13437, dtype: int64
内部标识号    13439
交易次数         5
交易金额       182
Name: 13438, dtype: int64
内部标识号    13440
交易次数         0
交易金额      6204
Name: 13439, dtype: int64
内部标识号    13441
交易次数         1
交易金额       999
Name: 13440, dtype: int64
内部标识号    13442
交易次数         1
交易金额      8230
Name: 13441, dtype: int64
内部标识号    13443
交易次数         7
交易金额       131
Name: 13442, dtype: int64
内部标识号    13444
交易次数         3
交易金额       424
Name: 13443, dtype: int64
内部标识号    13445
交易次数         9
交易金额       418
Name: 13444, dtype: int64
内部标识号    13446
交易次数         1
交易金额      3461
Name: 13445, dtype: int64
内部标识号    13447
交易次数         1
交易金额       679
Name: 13446, dtype: int64
内部标识号    13448
交易次数         3
交易金额       464
Name: 13447, dtype: int64
内部标识号    13449
交易次数         2
交易金额       811
Name: 13448, dtype: int64
内部标识号    13450
交易次数         8
交易金额       164
Name: 13449, dtype: int64
内部标识号    13451
交易次数         3
交易金额       457
Name: 13450, dtype: int64
内部标识号    13452
交易次数         1
交易金额      7342
Name: 13451, dtype: int64
内部标识号    13453
交易次数        32
交易金额     86830
Name: 13452, dtype: int64
内部标识号    13454
交易次数         5
交易金额     52261
Name: 13453, dtype: int64
内部标识号    13455
交易次数         8
交易金额       561
Name: 13454, dtype: int64
内部标识号    13456
交易次数         4
交易金额       211
Name: 13455, dtype: int64
内部标识号    13457
交易次数         7
交易金额     24441
Name: 13456, dtype: int64
内部标识号    13458
交易次数        11
交易金额       979
Name: 13457, dtype: int64
内部标识号    13459
交易次数        10
交易金额       681
Name: 13458, dtype: int64
内部标识号    13460
交易次数       205
交易金额     23422
Name: 13459, dtype: int64
内部标识号    13461
交易次数         2
交易金额       616
Name: 13460, dtype: int64
内部标识号    13462
交易次数        14
交易金额       893
Name: 13461, dtype: int64
内部标识号    13463
交易次数         2
交易金额       341
Name: 13462, dtype: int64
内部标识号    13464
交易次数         0
交易金额      9324
Name: 13463, dtype: int64
内部标识号    13465
交易次数        11
交易金额       732
Name: 13464, dtype: int64
内部标识号    13466
交易次数         1
交易金额       717
Name: 13465, dtype: int64
内部标识号    13467
交易次数        12
交易金额       360
Name: 13466, dtype: int64
内部标识号    13468
交易次数         6
交易金额       260
Name: 13467, dtype: int64
内部标识号    13469
交易次数         2
交易金额       161
Name: 13468, dtype: int64
内部标识号    13470
交易次数         2
交易金额       555
Name: 13469, dtype: int64
内部标识号    13471
交易次数        15
交易金额       350
Name: 13470, dtype: int64
内部标识号    13472
交易次数         3
交易金额       408
Name: 13471, dtype: int64
内部标识号    13473
交易次数        10
交易金额       853
Name: 13472, dtype: int64
内部标识号    13474
交易次数         4
交易金额     71071
Name: 13473, dtype: int64
内部标识号    13475
交易次数        24
交易金额      2202
Name: 13474, dtype: int64
内部标识号    13476
交易次数        26
交易金额        66
Name: 13475, dtype: int64
内部标识号    13477
交易次数         3
交易金额       260
Name: 13476, dtype: int64
内部标识号    13478
交易次数         2
交易金额       535
Name: 13477, dtype: int64
内部标识号    13479
交易次数        10
交易金额       668
Name: 13478, dtype: int64
内部标识号    13480
交易次数        12
交易金额       458
Name: 13479, dtype: int64
内部标识号    13481
交易次数         3
交易金额       428
Name: 13480, dtype: int64
内部标识号    13482
交易次数         6
交易金额       245
Name: 13481, dtype: int64
内部标识号    13483
交易次数        18
交易金额      5131
Name: 13482, dtype: int64
内部标识号    13484
交易次数        15
交易金额       768
Name: 13483, dtype: int64
内部标识号    13485
交易次数        10
交易金额       308
Name: 13484, dtype: int64
内部标识号    13486
交易次数        10
交易金额       779
Name: 13485, dtype: int64
内部标识号    13487
交易次数        10
交易金额       892
Name: 13486, dtype: int64
内部标识号    13488
交易次数         4
交易金额       107
Name: 13487, dtype: int64
内部标识号    13489
交易次数        23
交易金额       969
Name: 13488, dtype: int64
内部标识号    13490
交易次数        16
交易金额       648
Name: 13489, dtype: int64
内部标识号    13491
交易次数        11
交易金额       770
Name: 13490, dtype: int64
内部标识号    13492
交易次数         1
交易金额       746
Name: 13491, dtype: int64
内部标识号    13493
交易次数        17
交易金额      2577
Name: 13492, dtype: int64
内部标识号    13494
交易次数        12
交易金额       681
Name: 13493, dtype: int64
内部标识号    13495
交易次数         3
交易金额       279
Name: 13494, dtype: int64
内部标识号    13496
交易次数        14
交易金额       368
Name: 13495, dtype: int64
内部标识号    13497
交易次数         8
交易金额       248
Name: 13496, dtype: int64
内部标识号    13498
交易次数         1
交易金额       996
Name: 13497, dtype: int64
内部标识号    13499
交易次数       226
交易金额     64786
Name: 13498, dtype: int64
内部标识号    13500
交易次数        18
交易金额      2903
Name: 13499, dtype: int64
内部标识号    13501
交易次数        20
交易金额        93
Name: 13500, dtype: int64
内部标识号    13502
交易次数        13
交易金额       432
Name: 13501, dtype: int64
内部标识号    13503
交易次数         1
交易金额       921
Name: 13502, dtype: int64
内部标识号    13504
交易次数         8
交易金额       235
Name: 13503, dtype: int64
内部标识号    13505
交易次数        13
交易金额       965
Name: 13504, dtype: int64
内部标识号    13506
交易次数        13
交易金额       908
Name: 13505, dtype: int64
内部标识号    13507
交易次数        10
交易金额       328
Name: 13506, dtype: int64
内部标识号    13508
交易次数         9
交易金额       605
Name: 13507, dtype: int64
内部标识号    13509
交易次数         1
交易金额       928
Name: 13508, dtype: int64
内部标识号    13510
交易次数         5
交易金额       298
Name: 13509, dtype: int64
内部标识号    13511
交易次数         8
交易金额       432
Name: 13510, dtype: int64
内部标识号    13512
交易次数         1
交易金额      4247
Name: 13511, dtype: int64
内部标识号    13513
交易次数         2
交易金额       325
Name: 13512, dtype: int64
内部标识号    13514
交易次数         7
交易金额       162
Name: 13513, dtype: int64
内部标识号    13515
交易次数         4
交易金额       260
Name: 13514, dtype: int64
内部标识号    13516
交易次数         6
交易金额       113
Name: 13515, dtype: int64
内部标识号    13517
交易次数         2
交易金额       425
Name: 13516, dtype: int64
内部标识号    13518
交易次数         3
交易金额     42698
Name: 13517, dtype: int64
内部标识号    13519
交易次数         3
交易金额       217
Name: 13518, dtype: int64
内部标识号    13520
交易次数         3
交易金额       470
Name: 13519, dtype: int64
内部标识号    13521
交易次数         1
交易金额       744
Name: 13520, dtype: int64
内部标识号    13522
交易次数         2
交易金额       444
Name: 13521, dtype: int64
内部标识号    13523
交易次数        23
交易金额      8703
Name: 13522, dtype: int64
内部标识号    13524
交易次数         4
交易金额       118
Name: 13523, dtype: int64
内部标识号    13525
交易次数        13
交易金额       868
Name: 13524, dtype: int64
内部标识号    13526
交易次数        12
交易金额       875
Name: 13525, dtype: int64
内部标识号    13527
交易次数         5
交易金额       200
Name: 13526, dtype: int64
内部标识号    13528
交易次数        13
交易金额       307
Name: 13527, dtype: int64
内部标识号    13529
交易次数        15
交易金额       482
Name: 13528, dtype: int64
内部标识号    13530
交易次数         1
交易金额      8846
Name: 13529, dtype: int64
内部标识号    13531
交易次数       291
交易金额     70093
Name: 13530, dtype: int64
内部标识号    13532
交易次数        23
交易金额      8971
Name: 13531, dtype: int64
内部标识号    13533
交易次数        10
交易金额       649
Name: 13532, dtype: int64
内部标识号    13534
交易次数         5
交易金额       116
Name: 13533, dtype: int64
内部标识号    13535
交易次数         3
交易金额       372
Name: 13534, dtype: int64
内部标识号    13536
交易次数         1
交易金额       636
Name: 13535, dtype: int64
内部标识号    13537
交易次数        10
交易金额       394
Name: 13536, dtype: int64
内部标识号    13538
交易次数         1
交易金额       532
Name: 13537, dtype: int64
内部标识号    13539
交易次数         1
交易金额       923
Name: 13538, dtype: int64
内部标识号    13540

内部标识号    13758
交易次数        10
交易金额       644
Name: 13757, dtype: int64
内部标识号    13759
交易次数         1
交易金额       630
Name: 13758, dtype: int64
内部标识号    13760
交易次数        12
交易金额       379
Name: 13759, dtype: int64
内部标识号    13761
交易次数        10
交易金额       509
Name: 13760, dtype: int64
内部标识号    13762
交易次数         2
交易金额       366
Name: 13761, dtype: int64
内部标识号    13763
交易次数         4
交易金额       246
Name: 13762, dtype: int64
内部标识号    13764
交易次数         4
交易金额       252
Name: 13763, dtype: int64
内部标识号    13765
交易次数         8
交易金额       120
Name: 13764, dtype: int64
内部标识号    13766
交易次数         3
交易金额       239
Name: 13765, dtype: int64
内部标识号    13767
交易次数         4
交易金额     64586
Name: 13766, dtype: int64
内部标识号    13768
交易次数         2
交易金额       679
Name: 13767, dtype: int64
内部标识号    13769
交易次数         3
交易金额       253
Name: 13768, dtype: int64
内部标识号    13770
交易次数         8
交易金额       331
Name: 13769, dtype: int64
内部标识号    13771
交易次数        14
交易金额       330
Name: 13770, dtype: int64
内部标识号    13772
交易次数        26
交易金额      5299
Name: 13771, dtype: int64
内部标识号    13773
交易次数         0
交易金额      1445
Name: 13772, dtype: int64
内部标识号    13774
交易次数        29
交易金额       624
Name: 13773, dtype: int64
内部标识号    13775
交易次数         3
交易金额       437
Name: 13774, dtype: int64
内部标识号    13776
交易次数         1
交易金额      9003
Name: 13775, dtype: int64
内部标识号    13777
交易次数         9
交易金额       393
Name: 13776, dtype: int64
内部标识号    13778
交易次数         2
交易金额       399
Name: 13777, dtype: int64
内部标识号    13779
交易次数         2
交易金额       481
Name: 13778, dtype: int64
内部标识号    13780
交易次数         2
交易金额       461
Name: 13779, dtype: int64
内部标识号    13781
交易次数        11
交易金额       918
Name: 13780, dtype: int64
内部标识号    13782
交易次数         3
交易金额       356
Name: 13781, dtype: int64
内部标识号    13783
交易次数         1
交易金额      1781
Name: 13782, dtype: int64
内部标识号    13784
交易次数         2
交易金额       477
Name: 13783, dtype: int64
内部标识号    13785
交易次数         2
交易金额       855
Name: 13784, dtype: int64
内部标识号    13786
交易次数         0
交易金额      6547
Name: 13785, dtype: int64
内部标识号    13787
交易次数         7
交易金额       300
Name: 13786, dtype: int64
内部标识号    13788
交易次数       259
交易金额     91051
Name: 13787, dtype: int64
内部标识号    13789
交易次数         3
交易金额       400
Name: 13788, dtype: int64
内部标识号    13790
交易次数        14
交易金额       459
Name: 13789, dtype: int64
内部标识号    13791
交易次数         0
交易金额      8406
Name: 13790, dtype: int64
内部标识号    13792
交易次数        13
交易金额       877
Name: 13791, dtype: int64
内部标识号    13793
交易次数         3
交易金额       495
Name: 13792, dtype: int64
内部标识号    13794
交易次数        15
交易金额       590
Name: 13793, dtype: int64
内部标识号    13795
交易次数         3
交易金额       485
Name: 13794, dtype: int64
内部标识号    13796
交易次数        18
交易金额       592
Name: 13795, dtype: int64
内部标识号    13797
交易次数        12
交易金额       691
Name: 13796, dtype: int64
内部标识号    13798
交易次数         1
交易金额       977
Name: 13797, dtype: int64
内部标识号    13799
交易次数         4
交易金额       132
Name: 13798, dtype: int64
内部标识号    13800
交易次数        13
交易金额       917
Name: 13799, dtype: int64
内部标识号    13801
交易次数         0
交易金额      4936
Name: 13800, dtype: int64
内部标识号    13802
交易次数         8
交易金额     66137
Name: 13801, dtype: int64
内部标识号    13803
交易次数        10
交易金额       470
Name: 13802, dtype: int64
内部标识号    13804
交易次数         0
交易金额      7762
Name: 13803, dtype: int64
内部标识号    13805
交易次数         1
交易金额      9697
Name: 13804, dtype: int64
内部标识号    13806
交易次数         2
交易金额       366
Name: 13805, dtype: int64
内部标识号    13807
交易次数         3
交易金额       374
Name: 13806, dtype: int64
内部标识号    13808
交易次数         2
交易金额       394
Name: 13807, dtype: int64
内部标识号    13809
交易次数         2
交易金额       492
Name: 13808, dtype: int64
内部标识号    13810
交易次数         3
交易金额       173
Name: 13809, dtype: int64
内部标识号    13811
交易次数         4
交易金额       124
Name: 13810, dtype: int64
内部标识号    13812
交易次数         2
交易金额       149
Name: 13811, dtype: int64
内部标识号    13813
交易次数        12
交易金额       672
Name: 13812, dtype: int64
内部标识号    13814
交易次数         3
交易金额     41846
Name: 13813, dtype: int64
内部标识号    13815
交易次数        25
交易金额        59
Name: 13814, dtype: int64
内部标识号    13816
交易次数        15
交易金额       958
Name: 13815, dtype: int64
内部标识号    13817
交易次数         8
交易金额       659
Name: 13816, dtype: int64
内部标识号    13818
交易次数         2
交易金额       601
Name: 13817, dtype: int64
内部标识号    13819
交易次数         8
交易金额       322
Name: 13818, dtype: int64
内部标识号    13820
交易次数         8
交易金额       230
Name: 13819, dtype: int64
内部标识号    13821
交易次数        13
交易金额       723
Name: 13820, dtype: int64
内部标识号    13822
交易次数         1
交易金额       920
Name: 13821, dtype: int64
内部标识号    13823
交易次数         1
交易金额       936
Name: 13822, dtype: int64
内部标识号    13824
交易次数         2
交易金额       520
Name: 13823, dtype: int64
内部标识号    13825
交易次数        28
交易金额      4995
Name: 13824, dtype: int64
内部标识号    13826
交易次数        12
交易金额       475
Name: 13825, dtype: int64
内部标识号    13827
交易次数        22
交易金额      4039
Name: 13826, dtype: int64
内部标识号    13828
交易次数         1
交易金额       879
Name: 13827, dtype: int64
内部标识号    13829
交易次数         5
交易金额     23611
Name: 13828, dtype: int64
内部标识号    13830
交易次数         3
交易金额       397
Name: 13829, dtype: int64
内部标识号    13831
交易次数        18
交易金额      3977
Name: 13830, dtype: int64
内部标识号    13832
交易次数         1
交易金额       704
Name: 13831, dtype: int64
内部标识号    13833
交易次数         8
交易金额       220
Name: 13832, dtype: int64
内部标识号    13834
交易次数         2
交易金额       452
Name: 13833, dtype: int64
内部标识号    13835
交易次数        25
交易金额      5768
Name: 13834, dtype: int64
内部标识号    13836
交易次数         6
交易金额       249
Name: 13835, dtype: int64
内部标识号    13837
交易次数         8
交易金额       874
Name: 13836, dtype: int64
内部标识号    13838
交易次数        10
交易金额       987
Name: 13837, dtype: int64
内部标识号    13839
交易次数         0
交易金额      5979
Name: 13838, dtype: int64
内部标识号    13840
交易次数         1
交易金额       809
Name: 13839, dtype: int64
内部标识号    13841
交易次数        15
交易金额       581
Name: 13840, dtype: int64
内部标识号    13842
交易次数         8
交易金额       230
Name: 13841, dtype: int64
内部标识号    13843
交易次数        14
交易金额       491
Name: 13842, dtype: int64
内部标识号    13844
交易次数         2
交易金额       563
Name: 13843, dtype: int64
内部标识号    13845
交易次数         1
交易金额       771
Name: 13844, dtype: int64
内部标识号    13846
交易次数         4
交易金额       251
Name: 13845, dtype: int64
内部标识号    13847
交易次数        15
交易金额       350
Name: 13846, dtype: int64
内部标识号    13848
交易次数         3
交易金额       300
Name: 13847, dtype: int64
内部标识号    13849
交易次数         3
交易金额       322
Name: 13848, dtype: int64
内部标识号    13850
交易次数         1
交易金额       900
Name: 13849, dtype: int64
内部标识号    13851
交易次数        11
交易金额       804
Name: 13850, dtype: int64
内部标识号    13852
交易次数         1
交易金额       832
Name: 13851, dtype: int64
内部标识号    13853
交易次数         1
交易金额       848
Name: 13852, dtype: int64
内部标识号    13854
交易次数         6
交易金额     60204
Name: 13853, dtype: int64
内部标识号    13855
交易次数        29
交易金额       902
Name: 13854, dtype: int64
内部标识号    13856
交易次数        10
交易金额       929
Name: 13855, dtype: int64
内部标识号    13857
交易次数         5
交易金额       112
Name: 13856, dtype: int64
内部标识号    13858
交易次数        20
交易金额      7751
Name: 13857, dtype: int64
内部标识号    13859
交易次数        10
交易金额       963
Name: 13858, dtype: int64
内部标识号    13860
交易次数         3
交易金额       107
Name: 13859, dtype: int64
内部标识号    13861
交易次数         3
交易金额       486
Name: 13860, dtype: int64
内部标识号    13862
交易次数       205
交易金额     27040
Name: 13861, dtype: int64
内部标识号    13863
交易次数         9
交易金额       513
Name: 13862, dtype: int64
内部标识号    13864
交易次数         4
交易金额       252
Name: 13863, dtype: int64
内部标识号    13865
交易次数         3
交易金额       182
Name: 13864, dtype: int64
内部标识号    13866
交易次数        30
交易金额      4064
Name: 13865, dtype: int64
内部标识号    13867
交易次数         1
交易金额       915
Name: 13866, dtype: int64
内部标识号    13868
交易次数         2
交易金额       464
Name: 13867, dtype: int64
内部标识号    13869
交易次数         5
交易金额       157
Name: 13868, dtype: int64
内部标识号    13870
交易次数         0
交易金额      5042
Name: 13869, dtype: int64
内部标识号    13871
交易次数         1
交易金额      1637
Name: 13870, dtype: int64
内部标识号    13872
交易次数         5
交易金额     82975
Name: 13871, dtype: int64
内部标识号    13873
交易次数         3
交易金额       305
Name: 13872, dtype: int64
内部标识号    13874
交易次数         3
交易金额       452
Name: 13873, dtype: int64
内部标识号    13875
交易次数         0
交易金额      2929
Name: 13874, dtype: int64
内部标识号    13876
交易次数         0
交易金额      5135
Name: 13875, dtype: int64
内部标识号    13877
交易次数        12
交易金额       590
Name: 13876, dtype: int64
内部标识号    13878
交易次数         8
交易金额       165
Name: 13877, dtype: int64
内部标识号    13879
交易次数        13
交易金额       361
Name: 13878, dtype: int64
内部标识号    13880
交易次数         8
交易金额       373
Name: 13879, dtype: int64
内部标识号    13881
交易次数         2
交易金额       431
Name: 13880, dtype: int64
内部标识号    13882
交易次数         2
交易金额       702
Name: 13881, dtype: int64
内部标识号    13883
交易次数         0
交易金额      3556
Name: 13882, dtype: int64
内部标识号    13884
交易次数        10
交易金额       336
Name: 13883, dtype: int64
内部标识号    13885
交易次数        10
交易金额       634
Name: 13884, dtype: int64
内部标识号    13886
交易次数         0
交易金额      3119
Name: 13885, dtype: int64
内部标识号    13887
交易次数         6
交易金额       115
Name: 13886, dtype: int64
内部标识号    13888
交易次数         2
交易金额       742
Name: 13887, dtype: int64
内部标识号    13889
交易次数        25
交易金额       953
Name: 13888, dtype: int64
内部标识号    13890
交易次数         7
交易金额       292
Name: 13889, dtype: int64
内部标识号    13891
交易次数        13
交易金额       856
Name: 13890, dtype: int64
内部标识号    13892
交易次数         7
交易金额       119
Name: 13891, dtype: int64
内部标识号    13893
交易次数         6
交易金额     40740
Name: 13892, dtype: int64
内部标识号    13894
交易次数         7
交易金额       290
Name: 13893, dtype: int64
内部标识号    13895
交易次数        15
交易金额       799
Name: 13894, dtype: int64
内部标识号    13896
交易次数         3
交易金额       393
Name: 13895, dtype: int64
内部标识号    13897
交易次数         7
交易金额       267
Name: 13896, dtype: int64
内部标识号    13898
交易次数         0
交易金额      5208
Name: 13897, dtype: int64
内部标识号    13899
交易次数        28
交易金额       629
Name: 13898, dtype: int64
内部标识号    13900
交易次数        12
交易金额       984
Name: 13899, dtype: int64
内部标识号    13901
交易次数         1
交易金额       691
Name: 13900, dtype: int64
内部标识号    13902
交易次数         5
交易金额     87810
Name: 13901, dtype: int64
内部标识号    13903
交易次数         2
交易金额       892
Name: 13902, dtype: int64
内部标识号    13904
交易次数         0
交易金额      5234
Name: 13903, dtype: int64
内部标识号    13905
交易次数         2
交易金额       420
Name: 13904, dtype: int64
内部标识号    13906
交易次数         8
交易金额       933
Name: 13905, dtype: int64
内部标识号    13907
交易次数         3
交易金额       396
Name: 13906, dtype: int64
内部标识号    13908
交易次数         7
交易金额       162
Name: 13907, dtype: int64
内部标识号    13909
交易次数        30
交易金额      9410
Name: 13908, dtype: int64
内部标识号    13910
交易次数        29
交易金额        28
Name: 13909, dtype: int64
内部标识号    13911
交易次数         4
交易金额       272
Name: 13910, dtype: int64
内部标识号    13912
交易次数        15
交易金额       530
Name: 13911, dtype: int64
内部标识号    13913
交易次数         0
交易金额      8745
Name: 13912, dtype: int64
内部标识号    13914
交易次数         1
交易金额       707
Name: 13913, dtype: int64
内部标识号    13915
交易次数        10
交易金额       950
Name: 13914, dtype: int64
内部标识号    13916
交易次数        24
交易金额       785
Name: 13915, dtype: int64
内部标识号    13917
交易次数        29
交易金额       671
Name: 13916, dtype: int64
内部标识号    13918
交易次数        12
交易金额       503
Name: 13917, dtype: int64
内部标识号    13919
交易次数        13
交易金额       862
Name: 13918, dtype: int64
内部标识号    13920
交易次数         9
交易金额       321
Name: 13919, dtype: int64
内部标识号    13921
交易次数         1
交易金额      7413
Name: 13920, dtype: int64
内部标识号    13922
交易次数        11
交易金额       860
Name: 13921, dtype: int64
内部标识号    13923
交易次数        13
交易金额       966
Name: 13922, dtype: int64
内部标识号    13924
交易次数         3
交易金额       327
Name: 13923, dtype: int64
内部标识号    13925
交易次数         1
交易金额      2559
Name: 13924, dtype: int64
内部标识号    13926
交易次数        15
交易金额      9088
Name: 13925, dtype: int64
内部标识号    13927
交易次数        11
交易金额       778
Name: 13926, dtype: int64
内部标识号    13928
交易次数         3
交易金额       216
Name: 13927, dtype: int64
内部标识号    13929
交易次数         8
交易金额       387
Name: 13928, dtype: int64
内部标识号    13930
交易次数        11
交易金额       776
Name: 13929, dtype: int64
内部标识号    13931
交易次数         2
交易金额       396
Name: 13930, dtype: int64
内部标识号    13932
交易次数         1
交易金额       707
Name: 13931, dtype: int64
内部标识号    13933
交易次数         2
交易金额       472
Name: 13932, dtype: int64
内部标识号    13934
交易次数        14
交易金额       371
Name: 13933, dtype: int64
内部标识号    13935
交易次数         8
交易金额       476
Name: 13934, dtype: int64
内部标识号    13936
交易次数         9
交易金额       418
Name: 13935, dtype: int64
内部标识号    13937
交易次数         4
交易金额     74628
Name: 13936, dtype: int64
内部标识号    13938
交易次数        15
交易金额       482
Name: 13937, dtype: int64
内部标识号    13939
交易次数        28
交易金额      6808
Name: 13938, dtype: int64
内部标识号    13940
交易次数         2
交易金额       947
Name: 13939, dtype: int64
内部标识号    13941
交易次数         5
交易金额       216
Name: 13940, dtype: int64
内部标识号    13942
交易次数       245
交易金额     19465
Name: 13941, dtype: int64
内部标识号    13943
交易次数         1
交易金额       903
Name: 13942, dtype: int64
内部标识号    13944
交易次数         0
交易金额      2762
Name: 13943, dtype: int64
内部标识号    13945
交易次数         2
交易金额       769
Name: 13944, dtype: int64
内部标识号    13946
交易次数        12
交易金额       415
Name: 13945, dtype: int64
内部标识号    13947
交易次数         5
交易金额       181
Name: 13946, dtype: int64
内部标识号    13948
交易次数        10
交易金额       668
Name: 13947, dtype: int64
内部标识号    13949
交易次数         8
交易金额       463
Name: 13948, dtype: int64
内部标识号    13950
交易次数         3
交易金额       460
Name: 13949, dtype: int64
内部标识号    13951
交易次数         4
交易金额     25646
Name: 13950, dtype: int64
内部标识号    13952
交易次数         3
交易金额       244
Name: 13951, dtype: int64
内部标识号    13953
交易次数         0
交易金额      1635
Name: 13952, dtype: int64
内部标识号    13954
交易次数         1
交易金额      7040
Name: 13953, dtype: int64
内部标识号    13955
交易次数         9
交易金额       557
Name: 13954, dtype: int64
内部标识号    13956
交易次数        13
交易金额       613
Name: 13955, dtype: int64
内部标识号    13957
交易次数         0
交易金额      9595
Name: 13956, dtype: int64
内部标识号    13958
交易次数         5
交易金额     87298
Name: 13957, dtype: int64
内部标识号    13959
交易次数         2
交易金额       483
Name: 13958, dtype: int64
内部标识号    13960
交易次数         0
交易金额      8393
Name: 13959, dtype: int64
内部标识号    13961
交易次数         2
交易金额       313
Name: 13960, dtype: int64
内部标识号    13962
交易次数         9
交易金额       924
Name: 13961, dtype: int64
内部标识号    13963
交易次数         3
交易金额       201
Name: 13962, dtype: int64
内部标识号    13964
交易次数        15
交易金额       672
Name: 13963, dtype: int64
内部标识号    13965
交易次数         2
交易金额       398
Name: 13964, dtype: int64
内部标识号    13966
交易次数         6
交易金额       212
Name: 13965, dtype: int64
内部标识号    13967
交易次数         3
交易金额       305
Name: 13966, dtype: int64
内部标识号    13968
交易次数        15
交易金额      3581
Name: 13967, dtype: int64
内部标识号    13969
交易次数         3
交易金额       444
Name: 13968, dtype: int64
内部标识号    13970
交易次数        23
交易金额       950
Name: 13969, dtype: int64
内部标识号    13971
交易次数        11
交易金额       394
Name: 13970, dtype: int64
内部标识号    13972
交易次数         2
交易金额       328
Name: 13971, dtype: int64
内部标识号    13973
交易次数        21
交易金额      7463
Name: 13972, dtype: int64
内部标识号    13974
交易次数        13
交易金额       581
Name: 13973, dtype: int64
内部标识号    13975
交易次数         8
交易金额       849
Name: 13974, dtype: int64
内部标识号    13976
交易次数        23
交易金额       930
Name: 13975, dtype: int64
内部标识号    13977
交易次数        10
交易金额       951
Name: 13976, dtype: int64
内部标识号    13978
交易次数        18
交易金额      5626
Name: 13977, dtype: int64
内部标识号    13979
交易次数        18
交易金额        73
Name: 13978, dtype: int64
内部标识号    13980
交易次数         6
交易金额     38594
Name: 13979, dtype: int64
内部标识号    13981
交易次数        13
交易金额       944
Name: 13980, dtype: int64
内部标识号    13982
交易次数         9
交易金额       392
Name: 13981, dtype: int64
内部标识号    13983
交易次数         3
交易金额       205
Name: 13982, dtype: int64
内部标识号    13984
交易次数        13
交易金额       490
Name: 13983, dtype: int64
内部标识号    13985
交易次数         9
交易金额       908
Name: 13984, dtype: int64
内部标识号    13986
交易次数        13
交易金额       401
Name: 13985, dtype: int64
内部标识号    13987
交易次数        25
交易金额      9579
Name: 13986, dtype: int64
内部标识号    13988
交易次数        15
交易金额       926
Name: 13987, dtype: int64
内部标识号    13989
交易次数         6
交易金额       224
Name: 13988, dtype: int64
内部标识号    13990
交易次数        24
交易金额       570
Name: 13989, dtype: int64
内部标识号    13991
交易次数         3
交易金额       413
Name: 13990, dtype: int64
内部标识号    13992
交易次数        13
交易金额       838
Name: 13991, dtype: int64
内部标识号    13993
交易次数         2
交易金额       962
Name: 13992, dtype: int64
内部标识号    13994
交易次数        21
交易金额       654
Name: 13993, dtype: int64
内部标识号    13995
交易次数         8
交易金额       104
Name: 13994, dtype: int64
内部标识号    13996
交易次数         6
交易金额       233
Name: 13995, dtype: int64
内部标识号    13997
交易次数        12
交易金额       619
Name: 13996, dtype: int64
内部标识号    13998
交易次数         8
交易金额       985
Name: 13997, dtype: int64
内部标识号    13999
交易次数         2
交易金额       586
Name: 13998, dtype: int64
内部标识号    14000
交易次数         2
交易金额       725
Name: 13999, dtype: int64
内部标识号    14001
交易次数         0
交易金额      4131
Name: 14000, dtype: int64
内部标识号    14002
交易次数         4
交易金额       210
Name: 14001, dtype: int64
内部标识号    14003
交易次数         1
交易金额       731
Name: 14002, dtype: int64
内部标识号    14004
交易次数         3
交易金额     46001
Name: 14003, dtype: int64
内部标识号    14005
交易次数         5
交易金额       293
Name: 14004, dtype: int64
内部标识号    14006
交易次数         6
交易金额     48597
Name: 14005, dtype: int64
内部标识号    14007
交易次数        11
交易金额       564
Name: 14006, dtype: int64
内部标识号    14008
交易次数         6
交易金额     32796
Name: 14007, dtype: int64
内部标识号    14009
交易次数        30
交易金额        54
Name: 14008, dtype: int64
内部标识号    14010
交易次数        19
交易金额       986
Name: 14009, dtype: int64
内部标识号    14011
交易次数         2
交易金额       393
Name: 14010, dtype: int64
内部标识号    14012
交易次数         0
交易金额      7108
Name: 14011, dtype: int64
内部标识号    14013
交易次数         3
交易金额       122
Name: 14012, dtype: int64
内部标识号    14014
交易次数         3
交易金额       427
Name: 14013, dtype: int64
内部标识号    14015
交易次数        11
交易金额       974
Name: 14014, dtype: int64
内部标识号    14016
交易次数        13
交易金额       371
Name: 14015, dtype: int64
内部标识号    14017
交易次数        14
交易金额       905
Name: 14016, dtype: int64
内部标识号    14018
交易次数       155
交易金额     25878
Name: 14017, dtype: int64
内部标识号    14019
交易次数        17
交易金额      5180
Name: 14018, dtype: int64
内部标识号    14020
交易次数         0
交易金额      5388
Name: 14019, dtype: int64
内部标识号    14021
交易次数         1
交易金额       638
Name: 14020, dtype: int64
内部标识号    14022
交易次数         1
交易金额       583
Name: 14021, dtype: int64
内部标识号    14023
交易次数         2
交易金额       981
Name: 14022, dtype: int64
内部标识号    14024
交易次数         6
交易金额     67635
Name: 14023, dtype: int64
内部标识号    14025
交易次数         3
交易金额       392
Name: 14024, dtype: int64
内部标识号    14026
交易次数         0
交易金额      4287
Name: 14025, dtype: int64
内部标识号    14027
交易次数        12
交易金额       340
Name: 14026, dtype: int64
内部标识号    14028
交易次数         2
交易金额       393
Name: 14027, dtype: int64
内部标识号    14029
交易次数        23
交易金额      2465
Name: 14028, dtype: int64
内部标识号    14030
交易次数         1
交易金额       513
Name: 14029, dtype: int64
内部标识号    14031
交易次数         2
交易金额       538
Name: 14030, dtype: int64
内部标识号    14032
交易次数        13
交易金额       492
Name: 14031, dtype: int64
内部标识号    14033
交易次数         7
交易金额       248
Name: 14032, dtype: int64
内部标识号    14034
交易次数         1
交易金额       714
Name: 14033, dtype: int64
内部标识号    14035
交易次数         2
交易金额       799
Name: 14034, dtype: int64
内部标识号    14036
交易次数         2
交易金额       962
Name: 14035, dtype: int64
内部标识号    14037
交易次数         2
交易金额       380
Name: 14036, dtype: int64
内部标识号    14038
交易次数        18
交易金额       683
Name: 14037, dtype: int64
内部标识号    14039
交易次数         8
交易金额       400

Name: 14256, dtype: int64
内部标识号    14258
交易次数         1
交易金额       529
Name: 14257, dtype: int64
内部标识号    14259
交易次数         0
交易金额      6594
Name: 14258, dtype: int64
内部标识号    14260
交易次数         2
交易金额       672
Name: 14259, dtype: int64
内部标识号    14261
交易次数         8
交易金额       272
Name: 14260, dtype: int64
内部标识号    14262
交易次数         2
交易金额       450
Name: 14261, dtype: int64
内部标识号    14263
交易次数         0
交易金额      2770
Name: 14262, dtype: int64
内部标识号    14264
交易次数        14
交易金额       964
Name: 14263, dtype: int64
内部标识号    14265
交易次数         3
交易金额       242
Name: 14264, dtype: int64
内部标识号    14266
交易次数        13
交易金额       381
Name: 14265, dtype: int64
内部标识号    14267
交易次数         7
交易金额       153
Name: 14266, dtype: int64
内部标识号    14268
交易次数         5
交易金额       213
Name: 14267, dtype: int64
内部标识号    14269
交易次数        13
交易金额       844
Name: 14268, dtype: int64
内部标识号    14270
交易次数         0
交易金额      8061
Name: 14269, dtype: int64
内部标识号    14271
交易次数        13
交易金额       448
Name: 14270, dtype: int64
内部标识号    14272
交易次数         6
交易金额     87186
Name: 14271, dtype: int64
内部标识号    14273
交易次数         0
交易金额      3364
Name: 14272, dtype: int64
内部标识号    14274
交易次数         7
交易金额       197
Name: 14273, dtype: int64
内部标识号    14275
交易次数        13
交易金额       332
Name: 14274, dtype: int64
内部标识号    14276
交易次数         2
交易金额       416
Name: 14275, dtype: int64
内部标识号    14277
交易次数         8
交易金额       156
Name: 14276, dtype: int64
内部标识号    14278
交易次数         3
交易金额       156
Name: 14277, dtype: int64
内部标识号    14279
交易次数         0
交易金额      6246
Name: 14278, dtype: int64
内部标识号    14280
交易次数         2
交易金额       931
Name: 14279, dtype: int64
内部标识号    14281
交易次数         2
交易金额       522
Name: 14280, dtype: int64
内部标识号    14282
交易次数         5
交易金额       158
Name: 14281, dtype: int64
内部标识号    14283
交易次数        13
交易金额       382
Name: 14282, dtype: int64
内部标识号    14284
交易次数         3
交易金额       490
Name: 14283, dtype: int64
内部标识号    14285
交易次数         3
交易金额       202
Name: 14284, dtype: int64
内部标识号    14286
交易次数        12
交易金额       717
Name: 14285, dtype: int64
内部标识号    14287
交易次数        13
交易金额       485
Name: 14286, dtype: int64
内部标识号    14288
交易次数         8
交易金额       120
Name: 14287, dtype: int64
内部标识号    14289
交易次数         7
交易金额     32463
Name: 14288, dtype: int64
内部标识号    14290
交易次数         1
交易金额       703
Name: 14289, dtype: int64
内部标识号    14291
交易次数         6
交易金额       237
Name: 14290, dtype: int64
内部标识号    14292
交易次数         3
交易金额       210
Name: 14291, dtype: int64
内部标识号    14293
交易次数        17
交易金额       859
Name: 14292, dtype: int64
内部标识号    14294
交易次数         1
交易金额      8796
Name: 14293, dtype: int64
内部标识号    14295
交易次数       185
交易金额     31593
Name: 14294, dtype: int64
内部标识号    14296
交易次数        20
交易金额       976
Name: 14295, dtype: int64
内部标识号    14297
交易次数        27
交易金额       761
Name: 14296, dtype: int64
内部标识号    14298
交易次数         9
交易金额       843
Name: 14297, dtype: int64
内部标识号    14299
交易次数         2
交易金额       212
Name: 14298, dtype: int64
内部标识号    14300
交易次数        13
交易金额       364
Name: 14299, dtype: int64
内部标识号    14301
交易次数         7
交易金额       179
Name: 14300, dtype: int64
内部标识号    14302
交易次数         8
交易金额       384
Name: 14301, dtype: int64
内部标识号    14303
交易次数        23
交易金额      4608
Name: 14302, dtype: int64
内部标识号    14304
交易次数         9
交易金额       856
Name: 14303, dtype: int64
内部标识号    14305
交易次数        12
交易金额       874
Name: 14304, dtype: int64
内部标识号    14306
交易次数        10
交易金额       340
Name: 14305, dtype: int64
内部标识号    14307
交易次数         3
交易金额       414
Name: 14306, dtype: int64
内部标识号    14308
交易次数        10
交易金额       527
Name: 14307, dtype: int64
内部标识号    14309
交易次数        15
交易金额       544
Name: 14308, dtype: int64
内部标识号    14310
交易次数        30
交易金额      9281
Name: 14309, dtype: int64
内部标识号    14311
交易次数         2
交易金额       801
Name: 14310, dtype: int64
内部标识号    14312
交易次数         1
交易金额      5990
Name: 14311, dtype: int64
内部标识号    14313
交易次数         3
交易金额       196
Name: 14312, dtype: int64
内部标识号    14314
交易次数         8
交易金额       873
Name: 14313, dtype: int64
内部标识号    14315
交易次数         2
交易金额       744
Name: 14314, dtype: int64
内部标识号    14316
交易次数         4
交易金额       269
Name: 14315, dtype: int64
内部标识号    14317
交易次数        27
交易金额      2646
Name: 14316, dtype: int64
内部标识号    14318
交易次数        18
交易金额       904
Name: 14317, dtype: int64
内部标识号    14319
交易次数        10
交易金额       823
Name: 14318, dtype: int64
内部标识号    14320
交易次数        15
交易金额       506
Name: 14319, dtype: int64
内部标识号    14321
交易次数         3
交易金额     28858
Name: 14320, dtype: int64
内部标识号    14322
交易次数        10
交易金额       982
Name: 14321, dtype: int64
内部标识号    14323
交易次数        15
交易金额       409
Name: 14322, dtype: int64
内部标识号    14324
交易次数        15
交易金额       433
Name: 14323, dtype: int64
内部标识号    14325
交易次数         1
交易金额      4865
Name: 14324, dtype: int64
内部标识号    14326
交易次数         7
交易金额       110
Name: 14325, dtype: int64
内部标识号    14327
交易次数        15
交易金额       818
Name: 14326, dtype: int64
内部标识号    14328
交易次数        10
交易金额       495
Name: 14327, dtype: int64
内部标识号    14329
交易次数         0
交易金额      4966
Name: 14328, dtype: int64
内部标识号    14330
交易次数         3
交易金额       496
Name: 14329, dtype: int64
内部标识号    14331
交易次数         3
交易金额       200
Name: 14330, dtype: int64
内部标识号    14332
交易次数        14
交易金额       949
Name: 14331, dtype: int64
内部标识号    14333
交易次数         2
交易金额       806
Name: 14332, dtype: int64
内部标识号    14334
交易次数         5
交易金额     86567
Name: 14333, dtype: int64
内部标识号    14335
交易次数         8
交易金额       984
Name: 14334, dtype: int64
内部标识号    14336
交易次数        17
交易金额       762
Name: 14335, dtype: int64
内部标识号    14337
交易次数         8
交易金额       395
Name: 14336, dtype: int64
内部标识号    14338
交易次数         0
交易金额      1037
Name: 14337, dtype: int64
内部标识号    14339
交易次数         2
交易金额       116
Name: 14338, dtype: int64
内部标识号    14340
交易次数         0
交易金额      5556
Name: 14339, dtype: int64
内部标识号    14341
交易次数         2
交易金额       346
Name: 14340, dtype: int64
内部标识号    14342
交易次数         3
交易金额       461
Name: 14341, dtype: int64
内部标识号    14343
交易次数         3
交易金额     20663
Name: 14342, dtype: int64
内部标识号    14344
交易次数         9
交易金额       628
Name: 14343, dtype: int64
内部标识号    14345
交易次数        14
交易金额       329
Name: 14344, dtype: int64
内部标识号    14346
交易次数        12
交易金额       443
Name: 14345, dtype: int64
内部标识号    14347
交易次数         2
交易金额       533
Name: 14346, dtype: int64
内部标识号    14348
交易次数         3
交易金额       200
Name: 14347, dtype: int64
内部标识号    14349
交易次数         4
交易金额       157
Name: 14348, dtype: int64
内部标识号    14350
交易次数         3
交易金额       336
Name: 14349, dtype: int64
内部标识号    14351
交易次数        27
交易金额       790
Name: 14350, dtype: int64
内部标识号    14352
交易次数         8
交易金额       645
Name: 14351, dtype: int64
内部标识号    14353
交易次数         0
交易金额      3997
Name: 14352, dtype: int64
内部标识号    14354
交易次数         4
交易金额       245
Name: 14353, dtype: int64
内部标识号    14355
交易次数         2
交易金额       378
Name: 14354, dtype: int64
内部标识号    14356
交易次数         2
交易金额       561
Name: 14355, dtype: int64
内部标识号    14357
交易次数         3
交易金额       344
Name: 14356, dtype: int64
内部标识号    14358
交易次数        13
交易金额       558
Name: 14357, dtype: int64
内部标识号    14359
交易次数        10
交易金额       381
Name: 14358, dtype: int64
内部标识号    14360
交易次数        14
交易金额       551
Name: 14359, dtype: int64
内部标识号    14361
交易次数         9
交易金额       356
Name: 14360, dtype: int64
内部标识号    14362
交易次数        15
交易金额       944
Name: 14361, dtype: int64
内部标识号    14363
交易次数         1
交易金额       706
Name: 14362, dtype: int64
内部标识号    14364
交易次数         4
交易金额       199
Name: 14363, dtype: int64
内部标识号    14365
交易次数         9
交易金额       425
Name: 14364, dtype: int64
内部标识号    14366
交易次数         4
交易金额       285
Name: 14365, dtype: int64
内部标识号    14367
交易次数        10
交易金额       842
Name: 14366, dtype: int64
内部标识号    14368
交易次数         6
交易金额       105
Name: 14367, dtype: int64
内部标识号    14369
交易次数         0
交易金额      9080
Name: 14368, dtype: int64
内部标识号    14370
交易次数         0
交易金额      6223
Name: 14369, dtype: int64
内部标识号    14371
交易次数         8
交易金额       364
Name: 14370, dtype: int64
内部标识号    14372
交易次数         0
交易金额      4316
Name: 14371, dtype: int64
内部标识号    14373
交易次数        20
交易金额       567
Name: 14372, dtype: int64
内部标识号    14374
交易次数        27
交易金额      7657
Name: 14373, dtype: int64
内部标识号    14375
交易次数        11
交易金额       774
Name: 14374, dtype: int64
内部标识号    14376
交易次数         1
交易金额       601
Name: 14375, dtype: int64
内部标识号    14377
交易次数        30
交易金额      8990
Name: 14376, dtype: int64
内部标识号    14378
交易次数        10
交易金额       463
Name: 14377, dtype: int64
内部标识号    14379
交易次数        14
交易金额       681
Name: 14378, dtype: int64
内部标识号    14380
交易次数        15
交易金额       398
Name: 14379, dtype: int64
内部标识号    14381
交易次数         3
交易金额       318
Name: 14380, dtype: int64
内部标识号    14382
交易次数        11
交易金额       869
Name: 14381, dtype: int64
内部标识号    14383
交易次数         2
交易金额       130
Name: 14382, dtype: int64
内部标识号    14384
交易次数         4
交易金额     83516
Name: 14383, dtype: int64
内部标识号    14385
交易次数         0
交易金额      7970
Name: 14384, dtype: int64
内部标识号    14386
交易次数         3
交易金额       143
Name: 14385, dtype: int64
内部标识号    14387
交易次数        22
交易金额       546
Name: 14386, dtype: int64
内部标识号    14388
交易次数         4
交易金额     91700
Name: 14387, dtype: int64
内部标识号    14389
交易次数         6
交易金额       247
Name: 14388, dtype: int64
内部标识号    14390
交易次数         0
交易金额      6429
Name: 14389, dtype: int64
内部标识号    14391
交易次数         2
交易金额       276
Name: 14390, dtype: int64
内部标识号    14392
交易次数        14
交易金额       497
Name: 14391, dtype: int64
内部标识号    14393
交易次数         2
交易金额       390
Name: 14392, dtype: int64
内部标识号    14394
交易次数         1
交易金额       744
Name: 14393, dtype: int64
内部标识号    14395
交易次数         4
交易金额       281
Name: 14394, dtype: int64
内部标识号    14396
交易次数         7
交易金额       220
Name: 14395, dtype: int64
内部标识号    14397
交易次数         4
交易金额       131
Name: 14396, dtype: int64
内部标识号    14398
交易次数         2
交易金额       550
Name: 14397, dtype: int64
内部标识号    14399
交易次数        29
交易金额      3644
Name: 14398, dtype: int64
内部标识号    14400
交易次数        15
交易金额       303
Name: 14399, dtype: int64
内部标识号    14401
交易次数         1
交易金额       700
Name: 14400, dtype: int64
内部标识号    14402
交易次数         8
交易金额       259
Name: 14401, dtype: int64
内部标识号    14403
交易次数       284
交易金额     17326
Name: 14402, dtype: int64
内部标识号    14404
交易次数         2
交易金额       329
Name: 14403, dtype: int64
内部标识号    14405
交易次数        23
交易金额      4580
Name: 14404, dtype: int64
内部标识号    14406
交易次数        15
交易金额       517
Name: 14405, dtype: int64
内部标识号    14407
交易次数        19
交易金额        82
Name: 14406, dtype: int64
内部标识号    14408
交易次数         0
交易金额      3972
Name: 14407, dtype: int64
内部标识号    14409
交易次数         3
交易金额       307
Name: 14408, dtype: int64
内部标识号    14410
交易次数        22
交易金额      9003
Name: 14409, dtype: int64
内部标识号    14411
交易次数       261
交易金额     92852
Name: 14410, dtype: int64
内部标识号    14412
交易次数         8
交易金额       486
Name: 14411, dtype: int64
内部标识号    14413
交易次数        14
交易金额       718
Name: 14412, dtype: int64
内部标识号    14414
交易次数         3
交易金额     66007
Name: 14413, dtype: int64
内部标识号    14415
交易次数         5
交易金额       101
Name: 14414, dtype: int64
内部标识号    14416
交易次数        15
交易金额       432
Name: 14415, dtype: int64
内部标识号    14417
交易次数        20
交易金额      2760
Name: 14416, dtype: int64
内部标识号    14418
交易次数         0
交易金额      7004
Name: 14417, dtype: int64
内部标识号    14419
交易次数        14
交易金额       869
Name: 14418, dtype: int64
内部标识号    14420
交易次数         7
交易金额     26588
Name: 14419, dtype: int64
内部标识号    14421
交易次数         2
交易金额       878
Name: 14420, dtype: int64
内部标识号    14422
交易次数         2
交易金额       899
Name: 14421, dtype: int64
内部标识号    14423
交易次数        14
交易金额       486
Name: 14422, dtype: int64
内部标识号    14424
交易次数       201
交易金额     29454
Name: 14423, dtype: int64
内部标识号    14425
交易次数        10
交易金额       570
Name: 14424, dtype: int64
内部标识号    14426
交易次数         0
交易金额      8786
Name: 14425, dtype: int64
内部标识号    14427
交易次数         6
交易金额       192
Name: 14426, dtype: int64
内部标识号    14428
交易次数        25
交易金额      1347
Name: 14427, dtype: int64
内部标识号    14429
交易次数         0
交易金额      2995
Name: 14428, dtype: int64
内部标识号    14430
交易次数        10
交易金额       532
Name: 14429, dtype: int64
内部标识号    14431
交易次数         5
交易金额     28626
Name: 14430, dtype: int64
内部标识号    14432
交易次数        14
交易金额       918
Name: 14431, dtype: int64
内部标识号    14433
交易次数        23
交易金额      7349
Name: 14432, dtype: int64
内部标识号    14434
交易次数        10
交易金额       971
Name: 14433, dtype: int64
内部标识号    14435
交易次数         3
交易金额       493
Name: 14434, dtype: int64
内部标识号    14436
交易次数         5
交易金额       298
Name: 14435, dtype: int64
内部标识号    14437
交易次数         0
交易金额      2847
Name: 14436, dtype: int64
内部标识号    14438
交易次数         3
交易金额       161
Name: 14437, dtype: int64
内部标识号    14439
交易次数         7
交易金额       123
Name: 14438, dtype: int64
内部标识号    14440
交易次数         8
交易金额       194
Name: 14439, dtype: int64
内部标识号    14441
交易次数        15
交易金额       729
Name: 14440, dtype: int64
内部标识号    14442
交易次数         2
交易金额       261
Name: 14441, dtype: int64
内部标识号    14443
交易次数        11
交易金额       636
Name: 14442, dtype: int64
内部标识号    14444
交易次数         2
交易金额       458
Name: 14443, dtype: int64
内部标识号    14445
交易次数         4
交易金额     39760
Name: 14444, dtype: int64
内部标识号    14446
交易次数         1
交易金额      2124
Name: 14445, dtype: int64
内部标识号    14447
交易次数         8
交易金额       116
Name: 14446, dtype: int64
内部标识号    14448
交易次数        14
交易金额       629
Name: 14447, dtype: int64
内部标识号    14449
交易次数         3
交易金额       496
Name: 14448, dtype: int64
内部标识号    14450
交易次数         0
交易金额      2164
Name: 14449, dtype: int64
内部标识号    14451
交易次数         3
交易金额       362
Name: 14450, dtype: int64
内部标识号    14452
交易次数         0
交易金额      5640
Name: 14451, dtype: int64
内部标识号    14453
交易次数        10
交易金额       350
Name: 14452, dtype: int64
内部标识号    14454
交易次数        15
交易金额       393
Name: 14453, dtype: int64
内部标识号    14455
交易次数       170
交易金额     67902
Name: 14454, dtype: int64
内部标识号    14456
交易次数        29
交易金额       500
Name: 14455, dtype: int64
内部标识号    14457
交易次数         9
交易金额       300
Name: 14456, dtype: int64
内部标识号    14458
交易次数        25
交易金额       864
Name: 14457, dtype: int64
内部标识号    14459
交易次数         4
交易金额       176
Name: 14458, dtype: int64
内部标识号    14460
交易次数         3
交易金额       172
Name: 14459, dtype: int64
内部标识号    14461
交易次数        15
交易金额       746
Name: 14460, dtype: int64
内部标识号    14462
交易次数         3
交易金额       142
Name: 14461, dtype: int64
内部标识号    14463
交易次数         8
交易金额       321
Name: 14462, dtype: int64
内部标识号    14464
交易次数         1
交易金额       828
Name: 14463, dtype: int64
内部标识号    14465
交易次数         0
交易金额      1208
Name: 14464, dtype: int64
内部标识号    14466
交易次数         6
交易金额       137
Name: 14465, dtype: int64
内部标识号    14467
交易次数        10
交易金额       858
Name: 14466, dtype: int64
内部标识号    14468
交易次数         8
交易金额       343
Name: 14467, dtype: int64
内部标识号    14469
交易次数        16
交易金额       748
Name: 14468, dtype: int64
内部标识号    14470
交易次数        11
交易金额       553
Name: 14469, dtype: int64
内部标识号    14471
交易次数        13
交易金额       976
Name: 14470, dtype: int64
内部标识号    14472
交易次数         0
交易金额      1472
Name: 14471, dtype: int64
内部标识号    14473
交易次数         3
交易金额       270
Name: 14472, dtype: int64
内部标识号    14474
交易次数         0
交易金额      7051
Name: 14473, dtype: int64
内部标识号    14475
交易次数         1
交易金额      6892
Name: 14474, dtype: int64
内部标识号    14476
交易次数         9
交易金额       389
Name: 14475, dtype: int64
内部标识号    14477
交易次数         8
交易金额       103
Name: 14476, dtype: int64
内部标识号    14478
交易次数         2
交易金额       497
Name: 14477, dtype: int64
内部标识号    14479
交易次数        29
交易金额      8313
Name: 14478, dtype: int64
内部标识号    14480
交易次数         8
交易金额       950
Name: 14479, dtype: int64
内部标识号    14481
交易次数        17
交易金额      3851
Name: 14480, dtype: int64
内部标识号    14482
交易次数         2
交易金额       495
Name: 14481, dtype: int64
内部标识号    14483
交易次数         2
交易金额       657
Name: 14482, dtype: int64
内部标识号    14484
交易次数        11
交易金额       351
Name: 14483, dtype: int64
内部标识号    14485
交易次数         2
交易金额       827
Name: 14484, dtype: int64
内部标识号    14486
交易次数        12
交易金额       587
Name: 14485, dtype: int64
内部标识号    14487
交易次数         2
交易金额       403
Name: 14486, dtype: int64
内部标识号    14488
交易次数         4
交易金额       111
Name: 14487, dtype: int64
内部标识号    14489
交易次数         2
交易金额       948
Name: 14488, dtype: int64
内部标识号    14490
交易次数         6
交易金额     35588
Name: 14489, dtype: int64
内部标识号    14491
交易次数         0
交易金额      1901
Name: 14490, dtype: int64
内部标识号    14492
交易次数         9
交易金额       749
Name: 14491, dtype: int64
内部标识号    14493
交易次数        22
交易金额      4610
Name: 14492, dtype: int64
内部标识号    14494
交易次数        14
交易金额       768
Name: 14493, dtype: int64
内部标识号    14495
交易次数        15
交易金额       312
Name: 14494, dtype: int64
内部标识号    14496
交易次数        14
交易金额       833
Name: 14495, dtype: int64
内部标识号    14497
交易次数        12
交易金额       354
Name: 14496, dtype: int64
内部标识号    14498
交易次数         6
交易金额       185
Name: 14497, dtype: int64
内部标识号    14499
交易次数        34
交易金额     28938
Name: 14498, dtype: int64
内部标识号    14500
交易次数         3
交易金额       252
Name: 14499, dtype: int64
内部标识号    14501
交易次数         2
交易金额       775
Name: 14500, dtype: int64
内部标识号    14502
交易次数         0
交易金额      3586
Name: 14501, dtype: int64
内部标识号    14503
交易次数         2
交易金额       328
Name: 14502, dtype: int64
内部标识号    14504
交易次数        10
交易金额       441
Name: 14503, dtype: int64
内部标识号    14505
交易次数         5
交易金额       293
Name: 14504, dtype: int64
内部标识号    14506
交易次数        13
交易金额       824
Name: 14505, dtype: int64
内部标识号    14507
交易次数         3
交易金额       314
Name: 14506, dtype: int64
内部标识号    14508
交易次数         8
交易金额       137
Name: 14507, dtype: int64
内部标识号    14509
交易次数        16
交易金额      8680
Name: 14508, dtype: int64
内部标识号    14510
交易次数         3
交易金额       253
Name: 14509, dtype: int64
内部标识号    14511
交易次数        12
交易金额       668
Name: 14510, dtype: int64
内部标识号    14512
交易次数        13
交易金额       957
Name: 14511, dtype: int64
内部标识号    14513
交易次数         1
交易金额      3001
Name: 14512, dtype: int64
内部标识号    14514
交易次数         8
交易金额       229
Name: 14513, dtype: int64
内部标识号    14515
交易次数         3
交易金额       219
Name: 14514, dtype: int64
内部标识号    14516
交易次数         3
交易金额       300
Name: 14515, dtype: int64
内部标识号    14517
交易次数        15
交易金额       981
Name: 14516, dtype: int64
内部标识号    14518
交易次数         2
交易金额       798
Name: 14517, dtype: int64
内部标识号    14519
交易次数         3
交易金额       326
Name: 14518, dtype: int64
内部标识号    14520
交易次数         3
交易金额       438
Name: 14519, dtype: int64
内部标识号    14521
交易次数         1
交易金额      8996
Name: 14520, dtype: int64
内部标识号    14522
交易次数         1
交易金额      8076
Name: 14521, dtype: int64
内部标识号    14523
交易次数       194
交易金额     72286
Name: 14522, dtype: int64
内部标识号    14524
交易次数        12
交易金额       925
Name: 14523, dtype: int64
内部标识号    14525
交易次数         0
交易金额      8484
Name: 14524, dtype: int64
内部标识号    14526
交易次数         4
交易金额       148
Name: 14525, dtype: int64
内部标识号    14527
交易次数         3
交易金额       109
Name: 14526, dtype: int64
内部标识号    14528
交易次数         3
交易金额       465
Name: 14527, dtype: int64
内部标识号    14529
交易次数         1
交易金额       771
Name: 14528, dtype: int64
内部标识号    14530
交易次数         8
交易金额       816
Name: 14529, dtype: int64
内部标识号    14531
交易次数        27
交易金额      1689
Name: 14530, dtype: int64
内部标识号    14532
交易次数         2
交易金额       823
Name: 14531, dtype: int64
内部标识号    14533
交易次数         2
交易金额       529
Name: 14532, dtype: int64
内部标识号    14534
交易次数        11
交易金额       460
Name: 14533, dtype: int64
内部标识号    14535
交易次数        10
交易金额       524
Name: 14534, dtype: int64
内部标识号    14536
交易次数        11
交易金额       330
Name: 14535, dtype: int64
内部标识号    14537
交易次数        16
交易金额      5011
Name: 14536, dtype: int64
内部标识号    14538
交易次数         2
交易金额       416
Name: 14537, dtype: int64
内部标识号    14539

Name: 14737, dtype: int64
内部标识号    14739
交易次数         7
交易金额     50248
Name: 14738, dtype: int64
内部标识号    14740
交易次数        11
交易金额       431
Name: 14739, dtype: int64
内部标识号    14741
交易次数         1
交易金额       696
Name: 14740, dtype: int64
内部标识号    14742
交易次数       190
交易金额     79246
Name: 14741, dtype: int64
内部标识号    14743
交易次数         3
交易金额       382
Name: 14742, dtype: int64
内部标识号    14744
交易次数         3
交易金额       493
Name: 14743, dtype: int64
内部标识号    14745
交易次数         8
交易金额       230
Name: 14744, dtype: int64
内部标识号    14746
交易次数         5
交易金额     64427
Name: 14745, dtype: int64
内部标识号    14747
交易次数         6
交易金额     31145
Name: 14746, dtype: int64
内部标识号    14748
交易次数        63
交易金额     64082
Name: 14747, dtype: int64
内部标识号    14749
交易次数         2
交易金额       380
Name: 14748, dtype: int64
内部标识号    14750
交易次数        21
交易金额      9009
Name: 14749, dtype: int64
内部标识号    14751
交易次数         2
交易金额       404
Name: 14750, dtype: int64
内部标识号    14752
交易次数        14
交易金额       646
Name: 14751, dtype: int64
内部标识号    14753
交易次数         5
交易金额     11678
Name: 14752, dtype: int64
内部标识号    14754
交易次数         3
交易金额       497
Name: 14753, dtype: int64
内部标识号    14755
交易次数         1
交易金额      2717
Name: 14754, dtype: int64
内部标识号    14756
交易次数         2
交易金额       863
Name: 14755, dtype: int64
内部标识号    14757
交易次数         6
交易金额       118
Name: 14756, dtype: int64
内部标识号    14758
交易次数         3
交易金额       104
Name: 14757, dtype: int64
内部标识号    14759
交易次数         3
交易金额       466
Name: 14758, dtype: int64
内部标识号    14760
交易次数         8
交易金额       537
Name: 14759, dtype: int64
内部标识号    14761
交易次数         3
交易金额       123
Name: 14760, dtype: int64
内部标识号    14762
交易次数         1
交易金额      1919
Name: 14761, dtype: int64
内部标识号    14763
交易次数        15
交易金额       859
Name: 14762, dtype: int64
内部标识号    14764
交易次数        15
交易金额      6134
Name: 14763, dtype: int64
内部标识号    14765
交易次数         6
交易金额       198
Name: 14764, dtype: int64
内部标识号    14766
交易次数         2
交易金额       454
Name: 14765, dtype: int64
内部标识号    14767
交易次数         2
交易金额       407
Name: 14766, dtype: int64
内部标识号    14768
交易次数         9
交易金额       591
Name: 14767, dtype: int64
内部标识号    14769
交易次数         1
交易金额      6732
Name: 14768, dtype: int64
内部标识号    14770
交易次数        15
交易金额      2106
Name: 14769, dtype: int64
内部标识号    14771
交易次数         2
交易金额       481
Name: 14770, dtype: int64
内部标识号    14772
交易次数         0
交易金额      8627
Name: 14771, dtype: int64
内部标识号    14773
交易次数        13
交易金额       698
Name: 14772, dtype: int64
内部标识号    14774
交易次数         3
交易金额       325
Name: 14773, dtype: int64
内部标识号    14775
交易次数         5
交易金额       167
Name: 14774, dtype: int64
内部标识号    14776
交易次数         0
交易金额      8915
Name: 14775, dtype: int64
内部标识号    14777
交易次数        15
交易金额       592
Name: 14776, dtype: int64
内部标识号    14778
交易次数         8
交易金额       788
Name: 14777, dtype: int64
内部标识号    14779
交易次数        13
交易金额       348
Name: 14778, dtype: int64
内部标识号    14780
交易次数         2
交易金额       365
Name: 14779, dtype: int64
内部标识号    14781
交易次数         7
交易金额       112
Name: 14780, dtype: int64
内部标识号    14782
交易次数         6
交易金额     10069
Name: 14781, dtype: int64
内部标识号    14783
交易次数         9
交易金额       673
Name: 14782, dtype: int64
内部标识号    14784
交易次数         8
交易金额       189
Name: 14783, dtype: int64
内部标识号    14785
交易次数        14
交易金额       927
Name: 14784, dtype: int64
内部标识号    14786
交易次数        15
交易金额       399
Name: 14785, dtype: int64
内部标识号    14787
交易次数         0
交易金额      3204
Name: 14786, dtype: int64
内部标识号    14788
交易次数        25
交易金额      1000
Name: 14787, dtype: int64
内部标识号    14789
交易次数        47
交易金额     31005
Name: 14788, dtype: int64
内部标识号    14790
交易次数        14
交易金额       693
Name: 14789, dtype: int64
内部标识号    14791
交易次数         3
交易金额       433
Name: 14790, dtype: int64
内部标识号    14792
交易次数        10
交易金额       861
Name: 14791, dtype: int64
内部标识号    14793
交易次数         9
交易金额       611
Name: 14792, dtype: int64
内部标识号    14794
交易次数        13
交易金额       341
Name: 14793, dtype: int64
内部标识号    14795
交易次数         1
交易金额       755
Name: 14794, dtype: int64
内部标识号    14796
交易次数         3
交易金额       257
Name: 14795, dtype: int64
内部标识号    14797
交易次数         8
交易金额       315
Name: 14796, dtype: int64
内部标识号    14798
交易次数        76
交易金额     82550
Name: 14797, dtype: int64
内部标识号    14799
交易次数         8
交易金额       295
Name: 14798, dtype: int64
内部标识号    14800
交易次数        28
交易金额      3189
Name: 14799, dtype: int64
内部标识号    14801
交易次数        28
交易金额      2995
Name: 14800, dtype: int64
内部标识号    14802
交易次数         1
交易金额       953
Name: 14801, dtype: int64
内部标识号    14803
交易次数        10
交易金额       753
Name: 14802, dtype: int64
内部标识号    14804
交易次数         9
交易金额       981
Name: 14803, dtype: int64
内部标识号    14805
交易次数        12
交易金额       928
Name: 14804, dtype: int64
内部标识号    14806
交易次数        20
交易金额       750
Name: 14805, dtype: int64
内部标识号    14807
交易次数       298
交易金额     66787
Name: 14806, dtype: int64
内部标识号    14808
交易次数        18
交易金额      6602
Name: 14807, dtype: int64
内部标识号    14809
交易次数        24
交易金额       806
Name: 14808, dtype: int64
内部标识号    14810
交易次数         3
交易金额       364
Name: 14809, dtype: int64
内部标识号    14811
交易次数        11
交易金额       474
Name: 14810, dtype: int64
内部标识号    14812
交易次数        13
交易金额       748
Name: 14811, dtype: int64
内部标识号    14813
交易次数         1
交易金额       596
Name: 14812, dtype: int64
内部标识号    14814
交易次数        28
交易金额      7148
Name: 14813, dtype: int64
内部标识号    14815
交易次数         2
交易金额       280
Name: 14814, dtype: int64
内部标识号    14816
交易次数         8
交易金额       133
Name: 14815, dtype: int64
内部标识号    14817
交易次数         2
交易金额       351
Name: 14816, dtype: int64
内部标识号    14818
交易次数         2
交易金额       508
Name: 14817, dtype: int64
内部标识号    14819
交易次数         6
交易金额       173
Name: 14818, dtype: int64
内部标识号    14820
交易次数        24
交易金额       581
Name: 14819, dtype: int64
内部标识号    14821
交易次数       248
交易金额     77230
Name: 14820, dtype: int64
内部标识号    14822
交易次数        14
交易金额       735
Name: 14821, dtype: int64
内部标识号    14823
交易次数         5
交易金额       254
Name: 14822, dtype: int64
内部标识号    14824
交易次数        13
交易金额       972
Name: 14823, dtype: int64
内部标识号    14825
交易次数         4
交易金额     38614
Name: 14824, dtype: int64
内部标识号    14826
交易次数         6
交易金额       248
Name: 14825, dtype: int64
内部标识号    14827
交易次数         2
交易金额       559
Name: 14826, dtype: int64
内部标识号    14828
交易次数         7
交易金额       300
Name: 14827, dtype: int64
内部标识号    14829
交易次数         3
交易金额       442
Name: 14828, dtype: int64
内部标识号    14830
交易次数         2
交易金额       427
Name: 14829, dtype: int64
内部标识号    14831
交易次数        26
交易金额        13
Name: 14830, dtype: int64
内部标识号    14832
交易次数         8
交易金额     56839
Name: 14831, dtype: int64
内部标识号    14833
交易次数        10
交易金额       610
Name: 14832, dtype: int64
内部标识号    14834
交易次数         3
交易金额     81868
Name: 14833, dtype: int64
内部标识号    14835
交易次数         1
交易金额      8319
Name: 14834, dtype: int64
内部标识号    14836
交易次数       273
交易金额     10594
Name: 14835, dtype: int64
内部标识号    14837
交易次数        27
交易金额      7457
Name: 14836, dtype: int64
内部标识号    14838
交易次数         1
交易金额      3123
Name: 14837, dtype: int64
内部标识号    14839
交易次数        11
交易金额       841
Name: 14838, dtype: int64
内部标识号    14840
交易次数        30
交易金额      9574
Name: 14839, dtype: int64
内部标识号    14841
交易次数         9
交易金额       599
Name: 14840, dtype: int64
内部标识号    14842
交易次数         2
交易金额       831
Name: 14841, dtype: int64
内部标识号    14843
交易次数         4
交易金额       187
Name: 14842, dtype: int64
内部标识号    14844
交易次数         3
交易金额       381
Name: 14843, dtype: int64
内部标识号    14845
交易次数        11
交易金额       458
Name: 14844, dtype: int64
内部标识号    14846
交易次数        28
交易金额       994
Name: 14845, dtype: int64
内部标识号    14847
交易次数         3
交易金额       485
Name: 14846, dtype: int64
内部标识号    14848
交易次数         3
交易金额       331
Name: 14847, dtype: int64
内部标识号    14849
交易次数         3
交易金额       249
Name: 14848, dtype: int64
内部标识号    14850
交易次数        36
交易金额     17305
Name: 14849, dtype: int64
内部标识号    14851
交易次数        12
交易金额       311
Name: 14850, dtype: int64
内部标识号    14852
交易次数        14
交易金额       313
Name: 14851, dtype: int64
内部标识号    14853
交易次数         2
交易金额       493
Name: 14852, dtype: int64
内部标识号    14854
交易次数        10
交易金额       920
Name: 14853, dtype: int64
内部标识号    14855
交易次数         5
交易金额       133
Name: 14854, dtype: int64
内部标识号    14856
交易次数        14
交易金额       321
Name: 14855, dtype: int64
内部标识号    14857
交易次数         2
交易金额       363
Name: 14856, dtype: int64
内部标识号    14858
交易次数         2
交易金额       468
Name: 14857, dtype: int64
内部标识号    14859
交易次数         5
交易金额     16757
Name: 14858, dtype: int64
内部标识号    14860
交易次数         6
交易金额       183
Name: 14859, dtype: int64
内部标识号    14861
交易次数        23
交易金额       860
Name: 14860, dtype: int64
内部标识号    14862
交易次数        13
交易金额       975
Name: 14861, dtype: int64
内部标识号    14863
交易次数         2
交易金额       407
Name: 14862, dtype: int64
内部标识号    14864
交易次数        15
交易金额       481
Name: 14863, dtype: int64
内部标识号    14865
交易次数        25
交易金额      2062
Name: 14864, dtype: int64
内部标识号    14866
交易次数         6
交易金额       265
Name: 14865, dtype: int64
内部标识号    14867
交易次数         3
交易金额       312
Name: 14866, dtype: int64
内部标识号    14868
交易次数         9
交易金额       408
Name: 14867, dtype: int64
内部标识号    14869
交易次数         7
交易金额       216
Name: 14868, dtype: int64
内部标识号    14870
交易次数         3
交易金额       493
Name: 14869, dtype: int64
内部标识号    14871
交易次数        14
交易金额       483
Name: 14870, dtype: int64
内部标识号    14872
交易次数        11
交易金额       796
Name: 14871, dtype: int64
内部标识号    14873
交易次数         5
交易金额       277
Name: 14872, dtype: int64
内部标识号    14874
交易次数        30
交易金额      7021
Name: 14873, dtype: int64
内部标识号    14875
交易次数         1
交易金额       680
Name: 14874, dtype: int64
内部标识号    14876
交易次数         6
交易金额     62345
Name: 14875, dtype: int64
内部标识号    14877
交易次数        26
交易金额      4609
Name: 14876, dtype: int64
内部标识号    14878
交易次数         1
交易金额      5515
Name: 14877, dtype: int64
内部标识号    14879
交易次数         9
交易金额       392
Name: 14878, dtype: int64
内部标识号    14880
交易次数         7
交易金额     28113
Name: 14879, dtype: int64
内部标识号    14881
交易次数         1
交易金额       709
Name: 14880, dtype: int64
内部标识号    14882
交易次数         8
交易金额       603
Name: 14881, dtype: int64
内部标识号    14883
交易次数        11
交易金额       482
Name: 14882, dtype: int64
内部标识号    14884
交易次数         2
交易金额       332
Name: 14883, dtype: int64
内部标识号    14885
交易次数         8
交易金额       567
Name: 14884, dtype: int64
内部标识号    14886
交易次数         8
交易金额       603
Name: 14885, dtype: int64
内部标识号    14887
交易次数         2
交易金额       475
Name: 14886, dtype: int64
内部标识号    14888
交易次数         8
交易金额       996
Name: 14887, dtype: int64
内部标识号    14889
交易次数        30
交易金额      5633
Name: 14888, dtype: int64
内部标识号    14890
交易次数        15
交易金额       597
Name: 14889, dtype: int64
内部标识号    14891
交易次数        15
交易金额      7856
Name: 14890, dtype: int64
内部标识号    14892
交易次数        21
交易金额       790
Name: 14891, dtype: int64
内部标识号    14893
交易次数         2
交易金额       834
Name: 14892, dtype: int64
内部标识号    14894
交易次数         2
交易金额       421
Name: 14893, dtype: int64
内部标识号    14895
交易次数        25
交易金额      9329
Name: 14894, dtype: int64
内部标识号    14896
交易次数         8
交易金额       104
Name: 14895, dtype: int64
内部标识号    14897
交易次数         3
交易金额       231
Name: 14896, dtype: int64
内部标识号    14898
交易次数         4
交易金额     48314
Name: 14897, dtype: int64
内部标识号    14899
交易次数       291
交易金额     90205
Name: 14898, dtype: int64
内部标识号    14900
交易次数         7
交易金额       299
Name: 14899, dtype: int64
内部标识号    14901
交易次数        15
交易金额       714
Name: 14900, dtype: int64
内部标识号    14902
交易次数        14
交易金额       943
Name: 14901, dtype: int64
内部标识号    14903
交易次数        94
交易金额     73941
Name: 14902, dtype: int64
内部标识号    14904
交易次数         9
交易金额       516
Name: 14903, dtype: int64
内部标识号    14905
交易次数        12
交易金额       777
Name: 14904, dtype: int64
内部标识号    14906
交易次数         1
交易金额      6882
Name: 14905, dtype: int64
内部标识号    14907
交易次数        12
交易金额       628
Name: 14906, dtype: int64
内部标识号    14908
交易次数         7
交易金额       129
Name: 14907, dtype: int64
内部标识号    14909
交易次数         3
交易金额       307
Name: 14908, dtype: int64
内部标识号    14910
交易次数         3
交易金额       169
Name: 14909, dtype: int64
内部标识号    14911
交易次数        60
交易金额     55868
Name: 14910, dtype: int64
内部标识号    14912
交易次数       169
交易金额     19107
Name: 14911, dtype: int64
内部标识号    14913
交易次数         9
交易金额       569
Name: 14912, dtype: int64
内部标识号    14914
交易次数        15
交易金额       848
Name: 14913, dtype: int64
内部标识号    14915
交易次数         5
交易金额       243
Name: 14914, dtype: int64
内部标识号    14916
交易次数        18
交易金额      6298
Name: 14915, dtype: int64
内部标识号    14917
交易次数        12
交易金额       622
Name: 14916, dtype: int64
内部标识号    14918
交易次数       255
交易金额     16758
Name: 14917, dtype: int64
内部标识号    14919
交易次数        12
交易金额       336
Name: 14918, dtype: int64
内部标识号    14920
交易次数         3
交易金额       330
Name: 14919, dtype: int64
内部标识号    14921
交易次数         2
交易金额       421
Name: 14920, dtype: int64
内部标识号    14922
交易次数         4
交易金额       240
Name: 14921, dtype: int64
内部标识号    14923
交易次数         3
交易金额       362
Name: 14922, dtype: int64
内部标识号    14924
交易次数        10
交易金额       543
Name: 14923, dtype: int64
内部标识号    14925
交易次数        19
交易金额        49
Name: 14924, dtype: int64
内部标识号    14926
交易次数        23
交易金额       728
Name: 14925, dtype: int64
内部标识号    14927
交易次数        11
交易金额       981
Name: 14926, dtype: int64
内部标识号    14928
交易次数         3
交易金额       437
Name: 14927, dtype: int64
内部标识号    14929
交易次数         2
交易金额       874
Name: 14928, dtype: int64
内部标识号    14930
交易次数       284
交易金额     38998
Name: 14929, dtype: int64
内部标识号    14931
交易次数         5
交易金额       277
Name: 14930, dtype: int64
内部标识号    14932
交易次数         3
交易金额       332
Name: 14931, dtype: int64
内部标识号    14933
交易次数         2
交易金额       449
Name: 14932, dtype: int64
内部标识号    14934
交易次数        10
交易金额       379
Name: 14933, dtype: int64
内部标识号    14935
交易次数        14
交易金额       480
Name: 14934, dtype: int64
内部标识号    14936
交易次数         2
交易金额       323
Name: 14935, dtype: int64
内部标识号    14937
交易次数         1
交易金额      7881
Name: 14936, dtype: int64
内部标识号    14938
交易次数        14
交易金额       302
Name: 14937, dtype: int64
内部标识号    14939
交易次数        12
交易金额       399
Name: 14938, dtype: int64
内部标识号    14940
交易次数         1
交易金额       700
Name: 14939, dtype: int64
内部标识号    14941
交易次数         7
交易金额     28445
Name: 14940, dtype: int64
内部标识号    14942
交易次数        11
交易金额       582
Name: 14941, dtype: int64
内部标识号    14943
交易次数        10
交易金额       991
Name: 14942, dtype: int64
内部标识号    14944
交易次数        14
交易金额       477
Name: 14943, dtype: int64
内部标识号    14945
交易次数        14
交易金额       417
Name: 14944, dtype: int64
内部标识号    14946
交易次数         1
交易金额       811
Name: 14945, dtype: int64
内部标识号    14947
交易次数         2
交易金额       399
Name: 14946, dtype: int64
内部标识号    14948
交易次数        10
交易金额       907
Name: 14947, dtype: int64
内部标识号    14949
交易次数         8
交易金额     13311
Name: 14948, dtype: int64
内部标识号    14950
交易次数         9
交易金额       309
Name: 14949, dtype: int64
内部标识号    14951
交易次数        18
交易金额        15
Name: 14950, dtype: int64
内部标识号    14952
交易次数        28
交易金额       887
Name: 14951, dtype: int64
内部标识号    14953
交易次数         9
交易金额       848
Name: 14952, dtype: int64
内部标识号    14954
交易次数         2
交易金额       482
Name: 14953, dtype: int64
内部标识号    14955
交易次数         2
交易金额      1000
Name: 14954, dtype: int64
内部标识号    14956
交易次数         3
交易金额       309
Name: 14955, dtype: int64
内部标识号    14957
交易次数         8
交易金额       586
Name: 14956, dtype: int64
内部标识号    14958
交易次数         8
交易金额       850
Name: 14957, dtype: int64
内部标识号    14959
交易次数         2
交易金额       538
Name: 14958, dtype: int64
内部标识号    14960
交易次数         4
交易金额       103
Name: 14959, dtype: int64
内部标识号    14961
交易次数        15
交易金额       740
Name: 14960, dtype: int64
内部标识号    14962
交易次数         2
交易金额       409
Name: 14961, dtype: int64
内部标识号    14963
交易次数         8
交易金额       221
Name: 14962, dtype: int64
内部标识号    14964
交易次数         9
交易金额       507
Name: 14963, dtype: int64
内部标识号    14965
交易次数         7
交易金额       149
Name: 14964, dtype: int64
内部标识号    14966
交易次数        15
交易金额       372
Name: 14965, dtype: int64
内部标识号    14967
交易次数         8
交易金额       398
Name: 14966, dtype: int64
内部标识号    14968
交易次数         3
交易金额     92282
Name: 14967, dtype: int64
内部标识号    14969
交易次数         1
交易金额       975
Name: 14968, dtype: int64
内部标识号    14970
交易次数         8
交易金额       286
Name: 14969, dtype: int64
内部标识号    14971
交易次数         3
交易金额       402
Name: 14970, dtype: int64
内部标识号    14972
交易次数         8
交易金额       126
Name: 14971, dtype: int64
内部标识号    14973
交易次数         4
交易金额       175
Name: 14972, dtype: int64
内部标识号    14974
交易次数         5
交易金额       189
Name: 14973, dtype: int64
内部标识号    14975
交易次数         4
交易金额       225
Name: 14974, dtype: int64
内部标识号    14976
交易次数        14
交易金额       565
Name: 14975, dtype: int64
内部标识号    14977
交易次数         1
交易金额       786
Name: 14976, dtype: int64
内部标识号    14978
交易次数         2
交易金额       841
Name: 14977, dtype: int64
内部标识号    14979
交易次数        18
交易金额       873
Name: 14978, dtype: int64
内部标识号    14980
交易次数        14
交易金额       476
Name: 14979, dtype: int64
内部标识号    14981
交易次数        19
交易金额      8232
Name: 14980, dtype: int64
内部标识号    14982
交易次数         7
交易金额     74458
Name: 14981, dtype: int64
内部标识号    14983
交易次数        10
交易金额       490
Name: 14982, dtype: int64
内部标识号    14984
交易次数         9
交易金额       473
Name: 14983, dtype: int64
内部标识号    14985
交易次数         8
交易金额       525
Name: 14984, dtype: int64
内部标识号    14986
交易次数        15
交易金额      3589
Name: 14985, dtype: int64
内部标识号    14987
交易次数         6
交易金额       253
Name: 14986, dtype: int64
内部标识号    14988
交易次数         7
交易金额       205
Name: 14987, dtype: int64
内部标识号    14989
交易次数        23
交易金额      8400
Name: 14988, dtype: int64
内部标识号    14990
交易次数        15
交易金额       358
Name: 14989, dtype: int64
内部标识号    14991
交易次数         9
交易金额       462
Name: 14990, dtype: int64
内部标识号    14992
交易次数        10
交易金额       424
Name: 14991, dtype: int64
内部标识号    14993
交易次数         2
交易金额       336
Name: 14992, dtype: int64
内部标识号    14994
交易次数         2
交易金额       563
Name: 14993, dtype: int64
内部标识号    14995
交易次数         0
交易金额      9240
Name: 14994, dtype: int64
内部标识号    14996
交易次数        13
交易金额       510
Name: 14995, dtype: int64
内部标识号    14997
交易次数         5
交易金额       106
Name: 14996, dtype: int64
内部标识号    14998
交易次数         7
交易金额       199
Name: 14997, dtype: int64
内部标识号    14999
交易次数        11
交易金额       565
Name: 14998, dtype: int64
内部标识号    15000
交易次数        13
交易金额       321
Name: 14999, dtype: int64
内部标识号    15001
交易次数         5
交易金额       288
Name: 15000, dtype: int64
内部标识号    15002
交易次数         0
交易金额      4793
Name: 15001, dtype: int64
内部标识号    15003
交易次数         2
交易金额       402
Name: 15002, dtype: int64
内部标识号    15004
交易次数        29
交易金额         4
Name: 15003, dtype: int64
内部标识号    15005
交易次数         6
交易金额     44642
Name: 15004, dtype: int64
内部标识号    15006
交易次数         1
交易金额       567
Name: 15005, dtype: int64
内部标识号    15007
交易次数         8
交易金额     69007
Name: 15006, dtype: int64
内部标识号    15008
交易次数         7
交易金额       116
Name: 15007, dtype: int64
内部标识号    15009
交易次数       252
交易金额     28447
Name: 15008, dtype: int64
内部标识号    15010
交易次数        27
交易金额       934
Name: 15009, dtype: int64
内部标识号    15011
交易次数         8
交易金额       208
Name: 15010, dtype: int64
内部标识号    15012
交易次数         1
交易金额       965
Name: 15011, dtype: int64
内部标识号    15013
交易次数         8
交易金额       853
Name: 15012, dtype: int64
内部标识号    15014
交易次数         3
交易金额       404
Name: 15013, dtype: int64
内部标识号    15015
交易次数         2
交易金额       322
Name: 15014, dtype: int64
内部标识号    15016
交易次数        14
交易金额       964
Name: 15015, dtype: int64
内部标识号    15017
交易次数        30
交易金额      1081
Name: 15016, dtype: int64
内部标识号    15018
交易次数        15
交易金额       340
Name: 15017, dtype: int64
内部标识号    15019
交易次数         3
交易金额       186
Name: 15018, dtype: int64
内部标识号    15020

Name: 15068, dtype: int64
内部标识号    15070
交易次数         3
交易金额       466
Name: 15069, dtype: int64
内部标识号    15071
交易次数         0
交易金额      6067
Name: 15070, dtype: int64
内部标识号    15072
交易次数        13
交易金额       406
Name: 15071, dtype: int64
内部标识号    15073
交易次数        15
交易金额       505
Name: 15072, dtype: int64
内部标识号    15074
交易次数         1
交易金额       836
Name: 15073, dtype: int64
内部标识号    15075
交易次数         2
交易金额       171
Name: 15074, dtype: int64
内部标识号    15076
交易次数        15
交易金额       573
Name: 15075, dtype: int64
内部标识号    15077
交易次数         7
交易金额       276
Name: 15076, dtype: int64
内部标识号    15078
交易次数        14
交易金额       641
Name: 15077, dtype: int64
内部标识号    15079
交易次数        14
交易金额       554
Name: 15078, dtype: int64
内部标识号    15080
交易次数        11
交易金额       428
Name: 15079, dtype: int64
内部标识号    15081
交易次数        11
交易金额      1000
Name: 15080, dtype: int64
内部标识号    15082
交易次数         3
交易金额       428
Name: 15081, dtype: int64
内部标识号    15083
交易次数         1
交易金额       881
Name: 15082, dtype: int64
内部标识号    15084
交易次数         1
交易金额       736
Name: 15083, dtype: int64
内部标识号    15085
交易次数       142
交易金额     79657
Name: 15084, dtype: int64
内部标识号    15086
交易次数        22
交易金额        75
Name: 15085, dtype: int64
内部标识号    15087
交易次数        13
交易金额       416
Name: 15086, dtype: int64
内部标识号    15088
交易次数         1
交易金额       763
Name: 15087, dtype: int64
内部标识号    15089
交易次数         3
交易金额       127
Name: 15088, dtype: int64
内部标识号    15090
交易次数         6
交易金额       107
Name: 15089, dtype: int64
内部标识号    15091
交易次数        36
交易金额     16414
Name: 15090, dtype: int64
内部标识号    15092
交易次数        19
交易金额        72
Name: 15091, dtype: int64
内部标识号    15093
交易次数         2
交易金额       358
Name: 15092, dtype: int64
内部标识号    15094
交易次数         9
交易金额       838
Name: 15093, dtype: int64
内部标识号    15095
交易次数        14
交易金额       372
Name: 15094, dtype: int64
内部标识号    15096
交易次数         1
交易金额      4415
Name: 15095, dtype: int64
内部标识号    15097
交易次数         6
交易金额       225
Name: 15096, dtype: int64
内部标识号    15098
交易次数         3
交易金额       357
Name: 15097, dtype: int64
内部标识号    15099
交易次数         2
交易金额       404
Name: 15098, dtype: int64
内部标识号    15100
交易次数         3
交易金额       467
Name: 15099, dtype: int64
内部标识号    15101
交易次数        10
交易金额       817
Name: 15100, dtype: int64
内部标识号    15102
交易次数        92
交易金额     50939
Name: 15101, dtype: int64
内部标识号    15103
交易次数         2
交易金额       372
Name: 15102, dtype: int64
内部标识号    15104
交易次数         1
交易金额       834
Name: 15103, dtype: int64
内部标识号    15105
交易次数       153
交易金额     31347
Name: 15104, dtype: int64
内部标识号    15106
交易次数        19
交易金额       827
Name: 15105, dtype: int64
内部标识号    15107
交易次数        17
交易金额      4900
Name: 15106, dtype: int64
内部标识号    15108
交易次数        30
交易金额        19
Name: 15107, dtype: int64
内部标识号    15109
交易次数         4
交易金额       193
Name: 15108, dtype: int64
内部标识号    15110
交易次数         2
交易金额       809
Name: 15109, dtype: int64
内部标识号    15111
交易次数         1
交易金额       710
Name: 15110, dtype: int64
内部标识号    15112
交易次数        10
交易金额       765
Name: 15111, dtype: int64
内部标识号    15113
交易次数         3
交易金额       329
Name: 15112, dtype: int64
内部标识号    15114
交易次数        12
交易金额       967
Name: 15113, dtype: int64
内部标识号    15115
交易次数        15
交易金额       466
Name: 15114, dtype: int64
内部标识号    15116
交易次数         6
交易金额       165
Name: 15115, dtype: int64
内部标识号    15117
交易次数        11
交易金额       837
Name: 15116, dtype: int64
内部标识号    15118
交易次数         9
交易金额       323
Name: 15117, dtype: int64
内部标识号    15119
交易次数        12
交易金额       724
Name: 15118, dtype: int64
内部标识号    15120
交易次数        26
交易金额      8086
Name: 15119, dtype: int64
内部标识号    15121
交易次数         6
交易金额       267
Name: 15120, dtype: int64
内部标识号    15122
交易次数         9
交易金额       420
Name: 15121, dtype: int64
内部标识号    15123
交易次数        15
交易金额       565
Name: 15122, dtype: int64
内部标识号    15124
交易次数         2
交易金额       307
Name: 15123, dtype: int64
内部标识号    15125
交易次数         9
交易金额       495
Name: 15124, dtype: int64
内部标识号    15126
交易次数         2
交易金额       672
Name: 15125, dtype: int64
内部标识号    15127
交易次数         8
交易金额     44480
Name: 15126, dtype: int64
内部标识号    15128
交易次数         8
交易金额       242
Name: 15127, dtype: int64
内部标识号    15129
交易次数        11
交易金额       548
Name: 15128, dtype: int64
内部标识号    15130
交易次数         2
交易金额       389
Name: 15129, dtype: int64
内部标识号    15131
交易次数        12
交易金额       391
Name: 15130, dtype: int64
内部标识号    15132
交易次数         3
交易金额       243
Name: 15131, dtype: int64
内部标识号    15133
交易次数        58
交易金额     54192
Name: 15132, dtype: int64
内部标识号    15134
交易次数         1
交易金额       947
Name: 15133, dtype: int64
内部标识号    15135
交易次数        11
交易金额       848
Name: 15134, dtype: int64
内部标识号    15136
交易次数         1
交易金额       915
Name: 15135, dtype: int64
内部标识号    15137
交易次数         2
交易金额       266
Name: 15136, dtype: int64
内部标识号    15138
交易次数        13
交易金额       357
Name: 15137, dtype: int64
内部标识号    15139
交易次数         8
交易金额       320
Name: 15138, dtype: int64
内部标识号    15140
交易次数         3
交易金额     68810
Name: 15139, dtype: int64
内部标识号    15141
交易次数         4
交易金额       196
Name: 15140, dtype: int64
内部标识号    15142
交易次数         2
交易金额       604
Name: 15141, dtype: int64
内部标识号    15143
交易次数         7
交易金额       281
Name: 15142, dtype: int64
内部标识号    15144
交易次数        17
交易金额      7602
Name: 15143, dtype: int64
内部标识号    15145
交易次数         2
交易金额       981
Name: 15144, dtype: int64
内部标识号    15146
交易次数        29
交易金额      6287
Name: 15145, dtype: int64
内部标识号    15147
交易次数        19
交易金额       500
Name: 15146, dtype: int64
内部标识号    15148
交易次数        10
交易金额       319
Name: 15147, dtype: int64
内部标识号    15149
交易次数         6
交易金额       139
Name: 15148, dtype: int64
内部标识号    15150
交易次数        18
交易金额      1752
Name: 15149, dtype: int64
内部标识号    15151
交易次数         3
交易金额       122
Name: 15150, dtype: int64
内部标识号    15152
交易次数         1
交易金额       798
Name: 15151, dtype: int64
内部标识号    15153
交易次数         5
交易金额     62262
Name: 15152, dtype: int64
内部标识号    15154
交易次数        24
交易金额       969
Name: 15153, dtype: int64
内部标识号    15155
交易次数        26
交易金额      4751
Name: 15154, dtype: int64
内部标识号    15156
交易次数         8
交易金额       145
Name: 15155, dtype: int64
内部标识号    15157
交易次数         2
交易金额       404
Name: 15156, dtype: int64
内部标识号    15158
交易次数         2
交易金额       816
Name: 15157, dtype: int64
内部标识号    15159
交易次数        10
交易金额       465
Name: 15158, dtype: int64
内部标识号    15160
交易次数         3
交易金额       215
Name: 15159, dtype: int64
内部标识号    15161
交易次数         2
交易金额       448
Name: 15160, dtype: int64
内部标识号    15162
交易次数         2
交易金额       544
Name: 15161, dtype: int64
内部标识号    15163
交易次数       117
交易金额     99524
Name: 15162, dtype: int64
内部标识号    15164
交易次数         2
交易金额       345
Name: 15163, dtype: int64
内部标识号    15165
交易次数         3
交易金额       357
Name: 15164, dtype: int64
内部标识号    15166
交易次数         2
交易金额       600
Name: 15165, dtype: int64
内部标识号    15167
交易次数        11
交易金额       486
Name: 15166, dtype: int64
内部标识号    15168
交易次数         0
交易金额      7024
Name: 15167, dtype: int64
内部标识号    15169
交易次数        14
交易金额       353
Name: 15168, dtype: int64
内部标识号    15170
交易次数         0
交易金额      5493
Name: 15169, dtype: int64
内部标识号    15171
交易次数         6
交易金额       107
Name: 15170, dtype: int64
内部标识号    15172
交易次数       267
交易金额     79559
Name: 15171, dtype: int64
内部标识号    15173
交易次数         3
交易金额     69925
Name: 15172, dtype: int64
内部标识号    15174
交易次数         6
交易金额       121
Name: 15173, dtype: int64
内部标识号    15175
交易次数         5
交易金额       255
Name: 15174, dtype: int64
内部标识号    15176
交易次数         3
交易金额       451
Name: 15175, dtype: int64
内部标识号    15177
交易次数         2
交易金额       315
Name: 15176, dtype: int64
内部标识号    15178
交易次数        14
交易金额       973
Name: 15177, dtype: int64
内部标识号    15179
交易次数         3
交易金额       500
Name: 15178, dtype: int64
内部标识号    15180
交易次数        10
交易金额       885
Name: 15179, dtype: int64
内部标识号    15181
交易次数        13
交易金额       782
Name: 15180, dtype: int64
内部标识号    15182
交易次数        21
交易金额      3870
Name: 15181, dtype: int64
内部标识号    15183
交易次数         3
交易金额       302
Name: 15182, dtype: int64
内部标识号    15184
交易次数         3
交易金额       486
Name: 15183, dtype: int64
内部标识号    15185
交易次数         2
交易金额       972
Name: 15184, dtype: int64
内部标识号    15186
交易次数         1
交易金额       737
Name: 15185, dtype: int64
内部标识号    15187
交易次数         1
交易金额       511
Name: 15186, dtype: int64
内部标识号    15188
交易次数        16
交易金额      2326
Name: 15187, dtype: int64
内部标识号    15189
交易次数       230
交易金额     20173
Name: 15188, dtype: int64
内部标识号    15190
交易次数         4
交易金额       125
Name: 15189, dtype: int64
内部标识号    15191
交易次数         0
交易金额      1084
Name: 15190, dtype: int64
内部标识号    15192
交易次数        22
交易金额       577
Name: 15191, dtype: int64
内部标识号    15193
交易次数        26
交易金额       556
Name: 15192, dtype: int64
内部标识号    15194
交易次数         6
交易金额     78915
Name: 15193, dtype: int64
内部标识号    15195
交易次数        17
交易金额       851
Name: 15194, dtype: int64
内部标识号    15196
交易次数        28
交易金额       866
Name: 15195, dtype: int64
内部标识号    15197
交易次数        10
交易金额       493
Name: 15196, dtype: int64
内部标识号    15198
交易次数         3
交易金额       244
Name: 15197, dtype: int64
内部标识号    15199
交易次数         9
交易金额       408
Name: 15198, dtype: int64
内部标识号    15200
交易次数         5
交易金额       257
Name: 15199, dtype: int64
内部标识号    15201
交易次数         0
交易金额      9135
Name: 15200, dtype: int64
内部标识号    15202
交易次数       249
交易金额     67320
Name: 15201, dtype: int64
内部标识号    15203
交易次数        13
交易金额       870
Name: 15202, dtype: int64
内部标识号    15204
交易次数         0
交易金额      7793
Name: 15203, dtype: int64
内部标识号    15205
交易次数         2
交易金额       937
Name: 15204, dtype: int64
内部标识号    15206
交易次数        12
交易金额       305
Name: 15205, dtype: int64
内部标识号    15207
交易次数        10
交易金额       497
Name: 15206, dtype: int64
内部标识号    15208
交易次数        11
交易金额       748
Name: 15207, dtype: int64
内部标识号    15209
交易次数        22
交易金额       560
Name: 15208, dtype: int64
内部标识号    15210
交易次数         0
交易金额      7293
Name: 15209, dtype: int64
内部标识号    15211
交易次数         3
交易金额     63373
Name: 15210, dtype: int64
内部标识号    15212
交易次数         6
交易金额       213
Name: 15211, dtype: int64
内部标识号    15213
交易次数         3
交易金额       415
Name: 15212, dtype: int64
内部标识号    15214
交易次数        25
交易金额      6669
Name: 15213, dtype: int64
内部标识号    15215
交易次数         1
交易金额       520
Name: 15214, dtype: int64
内部标识号    15216
交易次数        24
交易金额      8428
Name: 15215, dtype: int64
内部标识号    15217
交易次数        10
交易金额       650
Name: 15216, dtype: int64
内部标识号    15218
交易次数        11
交易金额       851
Name: 15217, dtype: int64
内部标识号    15219
交易次数        11
交易金额       348
Name: 15218, dtype: int64
内部标识号    15220
交易次数        10
交易金额       362
Name: 15219, dtype: int64
内部标识号    15221
交易次数        24
交易金额       883
Name: 15220, dtype: int64
内部标识号    15222
交易次数         8
交易金额       647
Name: 15221, dtype: int64
内部标识号    15223
交易次数         8
交易金额       841
Name: 15222, dtype: int64
内部标识号    15224
交易次数        13
交易金额       981
Name: 15223, dtype: int64
内部标识号    15225
交易次数         1
交易金额       714
Name: 15224, dtype: int64
内部标识号    15226
交易次数        13
交易金额       649
Name: 15225, dtype: int64
内部标识号    15227
交易次数        29
交易金额      3990
Name: 15226, dtype: int64
内部标识号    15228
交易次数        13
交易金额       993
Name: 15227, dtype: int64
内部标识号    15229
交易次数         1
交易金额       961
Name: 15228, dtype: int64
内部标识号    15230
交易次数        14
交易金额       475
Name: 15229, dtype: int64
内部标识号    15231
交易次数         2
交易金额       510
Name: 15230, dtype: int64
内部标识号    15232
交易次数         1
交易金额      3842
Name: 15231, dtype: int64
内部标识号    15233
交易次数         4
交易金额       254
Name: 15232, dtype: int64
内部标识号    15234
交易次数        24
交易金额       816
Name: 15233, dtype: int64
内部标识号    15235
交易次数        11
交易金额       528
Name: 15234, dtype: int64
内部标识号    15236
交易次数        14
交易金额       666
Name: 15235, dtype: int64
内部标识号    15237
交易次数         6
交易金额       289
Name: 15236, dtype: int64
内部标识号    15238
交易次数         4
交易金额       117
Name: 15237, dtype: int64
内部标识号    15239
交易次数        10
交易金额       740
Name: 15238, dtype: int64
内部标识号    15240
交易次数         0
交易金额      7464
Name: 15239, dtype: int64
内部标识号    15241
交易次数        21
交易金额      6833
Name: 15240, dtype: int64
内部标识号    15242
交易次数         2
交易金额       320
Name: 15241, dtype: int64
内部标识号    15243
交易次数        10
交易金额       801
Name: 15242, dtype: int64
内部标识号    15244
交易次数         6
交易金额       118
Name: 15243, dtype: int64
内部标识号    15245
交易次数         9
交易金额       316
Name: 15244, dtype: int64
内部标识号    15246
交易次数         1
交易金额      2274
Name: 15245, dtype: int64
内部标识号    15247
交易次数         1
交易金额      8597
Name: 15246, dtype: int64
内部标识号    15248
交易次数         8
交易金额     19882
Name: 15247, dtype: int64
内部标识号    15249
交易次数         2
交易金额       637
Name: 15248, dtype: int64
内部标识号    15250
交易次数         1
交易金额       624
Name: 15249, dtype: int64
内部标识号    15251
交易次数         5
交易金额       162
Name: 15250, dtype: int64
内部标识号    15252
交易次数         5
交易金额       194
Name: 15251, dtype: int64
内部标识号    15253
交易次数         4
交易金额     49009
Name: 15252, dtype: int64
内部标识号    15254
交易次数         8
交易金额       718
Name: 15253, dtype: int64
内部标识号    15255
交易次数         8
交易金额       600
Name: 15254, dtype: int64
内部标识号    15256
交易次数       167
交易金额     89812
Name: 15255, dtype: int64
内部标识号    15257
交易次数        11
交易金额       786
Name: 15256, dtype: int64
内部标识号    15258
交易次数        11
交易金额       765
Name: 15257, dtype: int64
内部标识号    15259
交易次数        24
交易金额      4496
Name: 15258, dtype: int64
内部标识号    15260
交易次数        26
交易金额       507
Name: 15259, dtype: int64
内部标识号    15261
交易次数        14
交易金额       521
Name: 15260, dtype: int64
内部标识号    15262
交易次数         2
交易金额       864
Name: 15261, dtype: int64
内部标识号    15263
交易次数        17
交易金额       678
Name: 15262, dtype: int64
内部标识号    15264
交易次数       221
交易金额     58852
Name: 15263, dtype: int64
内部标识号    15265
交易次数        13
交易金额       436
Name: 15264, dtype: int64
内部标识号    15266
交易次数         4
交易金额       132
Name: 15265, dtype: int64
内部标识号    15267
交易次数        15
交易金额       300
Name: 15266, dtype: int64
内部标识号    15268
交易次数        14
交易金额       401
Name: 15267, dtype: int64
内部标识号    15269
交易次数         1
交易金额       635
Name: 15268, dtype: int64
内部标识号    15270
交易次数        15
交易金额       634
Name: 15269, dtype: int64
内部标识号    15271
交易次数         7
交易金额       280
Name: 15270, dtype: int64
内部标识号    15272
交易次数         6
交易金额     59243
Name: 15271, dtype: int64
内部标识号    15273
交易次数        11
交易金额       971
Name: 15272, dtype: int64
内部标识号    15274
交易次数         3
交易金额     42252
Name: 15273, dtype: int64
内部标识号    15275
交易次数        15
交易金额       422
Name: 15274, dtype: int64
内部标识号    15276
交易次数         5
交易金额       270
Name: 15275, dtype: int64
内部标识号    15277
交易次数         2
交易金额       425
Name: 15276, dtype: int64
内部标识号    15278
交易次数         3
交易金额       470
Name: 15277, dtype: int64
内部标识号    15279
交易次数         1
交易金额       685
Name: 15278, dtype: int64
内部标识号    15280
交易次数         9
交易金额       509
Name: 15279, dtype: int64
内部标识号    15281
交易次数         1
交易金额       826
Name: 15280, dtype: int64
内部标识号    15282
交易次数         9
交易金额       553
Name: 15281, dtype: int64
内部标识号    15283
交易次数        14
交易金额       890
Name: 15282, dtype: int64
内部标识号    15284
交易次数         2
交易金额       569
Name: 15283, dtype: int64
内部标识号    15285
交易次数         2
交易金额       597
Name: 15284, dtype: int64
内部标识号    15286
交易次数         2
交易金额       384
Name: 15285, dtype: int64
内部标识号    15287
交易次数        11
交易金额       702
Name: 15286, dtype: int64
内部标识号    15288
交易次数         8
交易金额       317
Name: 15287, dtype: int64
内部标识号    15289
交易次数         5
交易金额       228
Name: 15288, dtype: int64
内部标识号    15290
交易次数        11
交易金额       302
Name: 15289, dtype: int64
内部标识号    15291
交易次数         7
交易金额       201
Name: 15290, dtype: int64
内部标识号    15292
交易次数        21
交易金额       722
Name: 15291, dtype: int64
内部标识号    15293
交易次数         2
交易金额       350
Name: 15292, dtype: int64
内部标识号    15294
交易次数         9
交易金额       892
Name: 15293, dtype: int64
内部标识号    15295
交易次数        14
交易金额       755
Name: 15294, dtype: int64
内部标识号    15296
交易次数         8
交易金额       120
Name: 15295, dtype: int64
内部标识号    15297
交易次数         2
交易金额       360
Name: 15296, dtype: int64
内部标识号    15298
交易次数         2
交易金额       651
Name: 15297, dtype: int64
内部标识号    15299
交易次数         2
交易金额       388
Name: 15298, dtype: int64
内部标识号    15300
交易次数        15
交易金额       759
Name: 15299, dtype: int64
内部标识号    15301
交易次数         2
交易金额       418
Name: 15300, dtype: int64
内部标识号    15302
交易次数        19
交易金额       895
Name: 15301, dtype: int64
内部标识号    15303
交易次数         1
交易金额       678
Name: 15302, dtype: int64
内部标识号    15304
交易次数         1
交易金额       659
Name: 15303, dtype: int64
内部标识号    15305
交易次数         2
交易金额       387
Name: 15304, dtype: int64
内部标识号    15306
交易次数         1
交易金额       619
Name: 15305, dtype: int64
内部标识号    15307
交易次数         2
交易金额       642
Name: 15306, dtype: int64
内部标识号    15308
交易次数         3
交易金额       402
Name: 15307, dtype: int64
内部标识号    15309
交易次数         1
交易金额       959
Name: 15308, dtype: int64
内部标识号    15310
交易次数       136
交易金额     62847
Name: 15309, dtype: int64
内部标识号    15311
交易次数        14
交易金额       789
Name: 15310, dtype: int64
内部标识号    15312
交易次数         9
交易金额       370
Name: 15311, dtype: int64
内部标识号    15313
交易次数        14
交易金额       365
Name: 15312, dtype: int64
内部标识号    15314
交易次数         5
交易金额       110
Name: 15313, dtype: int64
内部标识号    15315
交易次数         3
交易金额       327
Name: 15314, dtype: int64
内部标识号    15316
交易次数        10
交易金额       698
Name: 15315, dtype: int64
内部标识号    15317
交易次数         3
交易金额       486
Name: 15316, dtype: int64
内部标识号    15318
交易次数        15
交易金额       514
Name: 15317, dtype: int64
内部标识号    15319
交易次数        68
交易金额     22457
Name: 15318, dtype: int64
内部标识号    15320
交易次数         3
交易金额       429
Name: 15319, dtype: int64
内部标识号    15321
交易次数         2
交易金额       410
Name: 15320, dtype: int64
内部标识号    15322
交易次数        12
交易金额       389
Name: 15321, dtype: int64
内部标识号    15323
交易次数        24
交易金额        50
Name: 15322, dtype: int64
内部标识号    15324
交易次数         2
交易金额       374
Name: 15323, dtype: int64
内部标识号    15325
交易次数        10
交易金额       975
Name: 15324, dtype: int64
内部标识号    15326
交易次数        14
交易金额       407
Name: 15325, dtype: int64
内部标识号    15327
交易次数         7
交易金额       140
Name: 15326, dtype: int64
内部标识号    15328
交易次数         0
交易金额      1501
Name: 15327, dtype: int64
内部标识号    15329
交易次数        10
交易金额       402
Name: 15328, dtype: int64
内部标识号    15330
交易次数        12
交易金额       933
Name: 15329, dtype: int64
内部标识号    15331
交易次数        13
交易金额       378
Name: 15330, dtype: int64
内部标识号    15332
交易次数         6
交易金额       273
Name: 15331, dtype: int64
内部标识号    15333
交易次数         1
交易金额       668
Name: 15332, dtype: int64
内部标识号    15334
交易次数         8
交易金额     96763
Name: 15333, dtype: int64
内部标识号    15335
交易次数         1
交易金额      4496
Name: 15334, dtype: int64
内部标识号    15336
交易次数         9
交易金额       740
Name: 15335, dtype: int64
内部标识号    15337
交易次数         9
交易金额       417
Name: 15336, dtype: int64
内部标识号    15338
交易次数         2
交易金额       322
Name: 15337, dtype: int64
内部标识号    15339
交易次数         8
交易金额     20896
Name: 15338, dtype: int64
内部标识号    15340
交易次数         8
交易金额       400
Name: 15339, dtype: int64
内部标识号    15341
交易次数         3
交易金额       197
Name: 15340, dtype: int64
内部标识号    15342
交易次数        15
交易金额       467
Name: 15341, dtype: int64
内部标识号    15343
交易次数         9
交易金额       644
Name: 15342, dtype: int64
内部标识号    15344
交易次数         6
交易金额     66401
Name: 15343, dtype: int64
内部标识号    15345
交易次数         2
交易金额       597
Name: 15344, dtype: int64
内部标识号    15346
交易次数         3
交易金额       377
Name: 15345, dtype: int64
内部标识号    15347
交易次数         8
交易金额       409
Name: 15346, dtype: int64
内部标识号    15348
交易次数         2
交易金额       242
Name: 15347, dtype: int64
内部标识号    15349
交易次数        11
交易金额       432
Name: 15348, dtype: int64
内部标识号    15350
交易次数       256
交易金额     50789
Name: 15349, dtype: int64
内部标识号    15351

Name: 15428, dtype: int64
内部标识号    15430
交易次数         3
交易金额       323
Name: 15429, dtype: int64
内部标识号    15431
交易次数         3
交易金额       169
Name: 15430, dtype: int64
内部标识号    15432
交易次数         9
交易金额       913
Name: 15431, dtype: int64
内部标识号    15433
交易次数         8
交易金额     74178
Name: 15432, dtype: int64
内部标识号    15434
交易次数        53
交易金额     64487
Name: 15433, dtype: int64
内部标识号    15435
交易次数         6
交易金额       116
Name: 15434, dtype: int64
内部标识号    15436
交易次数         2
交易金额       337
Name: 15435, dtype: int64
内部标识号    15437
交易次数         2
交易金额       356
Name: 15436, dtype: int64
内部标识号    15438
交易次数         6
交易金额     37537
Name: 15437, dtype: int64
内部标识号    15439
交易次数        10
交易金额       435
Name: 15438, dtype: int64
内部标识号    15440
交易次数         3
交易金额     70282
Name: 15439, dtype: int64
内部标识号    15441
交易次数       293
交易金额     60434
Name: 15440, dtype: int64
内部标识号    15442
交易次数        22
交易金额      9523
Name: 15441, dtype: int64
内部标识号    15443
交易次数         4
交易金额       290
Name: 15442, dtype: int64
内部标识号    15444
交易次数         2
交易金额       215
Name: 15443, dtype: int64
内部标识号    15445
交易次数         8
交易金额       176
Name: 15444, dtype: int64
内部标识号    15446
交易次数         6
交易金额       116
Name: 15445, dtype: int64
内部标识号    15447
交易次数         0
交易金额      4114
Name: 15446, dtype: int64
内部标识号    15448
交易次数         3
交易金额       358
Name: 15447, dtype: int64
内部标识号    15449
交易次数         2
交易金额       962
Name: 15448, dtype: int64
内部标识号    15450
交易次数         8
交易金额       186
Name: 15449, dtype: int64
内部标识号    15451
交易次数         1
交易金额       582
Name: 15450, dtype: int64
内部标识号    15452
交易次数        19
交易金额       579
Name: 15451, dtype: int64
内部标识号    15453
交易次数         2
交易金额       494
Name: 15452, dtype: int64
内部标识号    15454
交易次数         0
交易金额      9151
Name: 15453, dtype: int64
内部标识号    15455
交易次数         7
交易金额     67658
Name: 15454, dtype: int64
内部标识号    15456
交易次数        11
交易金额       736
Name: 15455, dtype: int64
内部标识号    15457
交易次数         3
交易金额       208
Name: 15456, dtype: int64
内部标识号    15458
交易次数        18
交易金额      7345
Name: 15457, dtype: int64
内部标识号    15459
交易次数         8
交易金额       165
Name: 15458, dtype: int64
内部标识号    15460
交易次数        24
交易金额      4293
Name: 15459, dtype: int64
内部标识号    15461
交易次数         0
交易金额      2819
Name: 15460, dtype: int64
内部标识号    15462
交易次数         1
交易金额       855
Name: 15461, dtype: int64
内部标识号    15463
交易次数         3
交易金额       462
Name: 15462, dtype: int64
内部标识号    15464
交易次数         8
交易金额       447
Name: 15463, dtype: int64
内部标识号    15465
交易次数         4
交易金额       283
Name: 15464, dtype: int64
内部标识号    15466
交易次数       104
交易金额     22299
Name: 15465, dtype: int64
内部标识号    15467
交易次数        13
交易金额       825
Name: 15466, dtype: int64
内部标识号    15468
交易次数        22
交易金额      8952
Name: 15467, dtype: int64
内部标识号    15469
交易次数         5
交易金额       174
Name: 15468, dtype: int64
内部标识号    15470
交易次数        10
交易金额       379
Name: 15469, dtype: int64
内部标识号    15471
交易次数        10
交易金额       966
Name: 15470, dtype: int64
内部标识号    15472
交易次数        13
交易金额       365
Name: 15471, dtype: int64
内部标识号    15473
交易次数         3
交易金额       239
Name: 15472, dtype: int64
内部标识号    15474
交易次数        95
交易金额     46069
Name: 15473, dtype: int64
内部标识号    15475
交易次数         9
交易金额       658
Name: 15474, dtype: int64
内部标识号    15476
交易次数        11
交易金额       399
Name: 15475, dtype: int64
内部标识号    15477
交易次数        10
交易金额       357
Name: 15476, dtype: int64
内部标识号    15478
交易次数        29
交易金额      3211
Name: 15477, dtype: int64
内部标识号    15479
交易次数         7
交易金额       128
Name: 15478, dtype: int64
内部标识号    15480
交易次数        29
交易金额       699
Name: 15479, dtype: int64
内部标识号    15481
交易次数       226
交易金额     15093
Name: 15480, dtype: int64
内部标识号    15482
交易次数         8
交易金额       165
Name: 15481, dtype: int64
内部标识号    15483
交易次数         3
交易金额       168
Name: 15482, dtype: int64
内部标识号    15484
交易次数         5
交易金额       127
Name: 15483, dtype: int64
内部标识号    15485
交易次数        15
交易金额       390
Name: 15484, dtype: int64
内部标识号    15486
交易次数        11
交易金额       381
Name: 15485, dtype: int64
内部标识号    15487
交易次数         0
交易金额      4311
Name: 15486, dtype: int64
内部标识号    15488
交易次数         0
交易金额      2929
Name: 15487, dtype: int64
内部标识号    15489
交易次数         4
交易金额       274
Name: 15488, dtype: int64
内部标识号    15490
交易次数        23
交易金额       531
Name: 15489, dtype: int64
内部标识号    15491
交易次数         1
交易金额       943
Name: 15490, dtype: int64
内部标识号    15492
交易次数        10
交易金额       373
Name: 15491, dtype: int64
内部标识号    15493
交易次数         6
交易金额       137
Name: 15492, dtype: int64
内部标识号    15494
交易次数         6
交易金额       234
Name: 15493, dtype: int64
内部标识号    15495
交易次数        12
交易金额       986
Name: 15494, dtype: int64
内部标识号    15496
交易次数       185
交易金额     91182
Name: 15495, dtype: int64
内部标识号    15497
交易次数         5
交易金额       272
Name: 15496, dtype: int64
内部标识号    15498
交易次数         0
交易金额      2833
Name: 15497, dtype: int64
内部标识号    15499
交易次数         8
交易金额       236
Name: 15498, dtype: int64
内部标识号    15500
交易次数         0
交易金额      4463
Name: 15499, dtype: int64
内部标识号    15501
交易次数        14
交易金额       906
Name: 15500, dtype: int64
内部标识号    15502
交易次数        10
交易金额       525
Name: 15501, dtype: int64
内部标识号    15503
交易次数         3
交易金额       194
Name: 15502, dtype: int64
内部标识号    15504
交易次数        15
交易金额       693
Name: 15503, dtype: int64
内部标识号    15505
交易次数         2
交易金额       483
Name: 15504, dtype: int64
内部标识号    15506
交易次数         9
交易金额       463
Name: 15505, dtype: int64
内部标识号    15507
交易次数        27
交易金额       652
Name: 15506, dtype: int64
内部标识号    15508
交易次数        19
交易金额      3827
Name: 15507, dtype: int64
内部标识号    15509
交易次数         3
交易金额       327
Name: 15508, dtype: int64
内部标识号    15510
交易次数        15
交易金额       751
Name: 15509, dtype: int64
内部标识号    15511
交易次数        12
交易金额       571
Name: 15510, dtype: int64
内部标识号    15512
交易次数        12
交易金额       646
Name: 15511, dtype: int64
内部标识号    15513
交易次数        13
交易金额       497
Name: 15512, dtype: int64
内部标识号    15514
交易次数         1
交易金额       742
Name: 15513, dtype: int64
内部标识号    15515
交易次数         1
交易金额       650
Name: 15514, dtype: int64
内部标识号    15516
交易次数        11
交易金额       446
Name: 15515, dtype: int64
内部标识号    15517
交易次数         4
交易金额     37617
Name: 15516, dtype: int64
内部标识号    15518
交易次数         2
交易金额       858
Name: 15517, dtype: int64
内部标识号    15519
交易次数         7
交易金额       113
Name: 15518, dtype: int64
内部标识号    15520
交易次数       212
交易金额     64286
Name: 15519, dtype: int64
内部标识号    15521
交易次数        12
交易金额       558
Name: 15520, dtype: int64
内部标识号    15522
交易次数         3
交易金额       339
Name: 15521, dtype: int64
内部标识号    15523
交易次数        15
交易金额       453
Name: 15522, dtype: int64
内部标识号    15524
交易次数         7
交易金额     87535
Name: 15523, dtype: int64
内部标识号    15525
交易次数         1
交易金额       945
Name: 15524, dtype: int64
内部标识号    15526
交易次数         5
交易金额       105
Name: 15525, dtype: int64
内部标识号    15527
交易次数        12
交易金额       671
Name: 15526, dtype: int64
内部标识号    15528
交易次数        14
交易金额       605
Name: 15527, dtype: int64
内部标识号    15529
交易次数         9
交易金额       307
Name: 15528, dtype: int64
内部标识号    15530
交易次数         3
交易金额       483
Name: 15529, dtype: int64
内部标识号    15531
交易次数         2
交易金额       389
Name: 15530, dtype: int64
内部标识号    15532
交易次数         9
交易金额       351
Name: 15531, dtype: int64
内部标识号    15533
交易次数         1
交易金额      2951
Name: 15532, dtype: int64
内部标识号    15534
交易次数        14
交易金额       319
Name: 15533, dtype: int64
内部标识号    15535
交易次数        14
交易金额       704
Name: 15534, dtype: int64
内部标识号    15536
交易次数        10
交易金额       320
Name: 15535, dtype: int64
内部标识号    15537
交易次数        15
交易金额       667
Name: 15536, dtype: int64
内部标识号    15538
交易次数         4
交易金额       233
Name: 15537, dtype: int64
内部标识号    15539
交易次数        11
交易金额       324
Name: 15538, dtype: int64
内部标识号    15540
交易次数         1
交易金额      8700
Name: 15539, dtype: int64
内部标识号    15541
交易次数         6
交易金额       280
Name: 15540, dtype: int64
内部标识号    15542
交易次数       183
交易金额     18630
Name: 15541, dtype: int64
内部标识号    15543
交易次数        30
交易金额      1594
Name: 15542, dtype: int64
内部标识号    15544
交易次数         9
交易金额       437
Name: 15543, dtype: int64
内部标识号    15545
交易次数         2
交易金额       693
Name: 15544, dtype: int64
内部标识号    15546
交易次数         9
交易金额       541
Name: 15545, dtype: int64
内部标识号    15547
交易次数        28
交易金额      8677
Name: 15546, dtype: int64
内部标识号    15548
交易次数        16
交易金额      9955
Name: 15547, dtype: int64
内部标识号    15549
交易次数        14
交易金额       359
Name: 15548, dtype: int64
内部标识号    15550
交易次数         4
交易金额     64824
Name: 15549, dtype: int64
内部标识号    15551
交易次数        13
交易金额       969
Name: 15550, dtype: int64
内部标识号    15552
交易次数        13
交易金额       425
Name: 15551, dtype: int64
内部标识号    15553
交易次数       265
交易金额     37664
Name: 15552, dtype: int64
内部标识号    15554
交易次数        14
交易金额       378
Name: 15553, dtype: int64
内部标识号    15555
交易次数         1
交易金额       771
Name: 15554, dtype: int64
内部标识号    15556
交易次数         1
交易金额       614
Name: 15555, dtype: int64
内部标识号    15557
交易次数         3
交易金额       321
Name: 15556, dtype: int64
内部标识号    15558
交易次数        15
交易金额       758
Name: 15557, dtype: int64
内部标识号    15559
交易次数        15
交易金额       304
Name: 15558, dtype: int64
内部标识号    15560
交易次数        14
交易金额       511
Name: 15559, dtype: int64
内部标识号    15561
交易次数        13
交易金额       312
Name: 15560, dtype: int64
内部标识号    15562
交易次数         9
交易金额       724
Name: 15561, dtype: int64
内部标识号    15563
交易次数         2
交易金额       939
Name: 15562, dtype: int64
内部标识号    15564
交易次数         3
交易金额       320
Name: 15563, dtype: int64
内部标识号    15565
交易次数         2
交易金额       341
Name: 15564, dtype: int64
内部标识号    15566
交易次数        74
交易金额     88556
Name: 15565, dtype: int64
内部标识号    15567
交易次数         2
交易金额       348
Name: 15566, dtype: int64
内部标识号    15568
交易次数         5
交易金额       190
Name: 15567, dtype: int64
内部标识号    15569
交易次数        11
交易金额       680
Name: 15568, dtype: int64
内部标识号    15570
交易次数         8
交易金额       394
Name: 15569, dtype: int64
内部标识号    15571
交易次数        29
交易金额      6236
Name: 15570, dtype: int64
内部标识号    15572
交易次数        23
交易金额      6359
Name: 15571, dtype: int64
内部标识号    15573
交易次数        13
交易金额       687
Name: 15572, dtype: int64
内部标识号    15574
交易次数        13
交易金额       815
Name: 15573, dtype: int64
内部标识号    15575
交易次数         8
交易金额       277
Name: 15574, dtype: int64
内部标识号    15576
交易次数        10
交易金额       468
Name: 15575, dtype: int64
内部标识号    15577
交易次数         2
交易金额       337
Name: 15576, dtype: int64
内部标识号    15578
交易次数       146
交易金额     47776
Name: 15577, dtype: int64
内部标识号    15579
交易次数        10
交易金额       984
Name: 15578, dtype: int64
内部标识号    15580
交易次数        11
交易金额       552
Name: 15579, dtype: int64
内部标识号    15581
交易次数       100
交易金额     43739
Name: 15580, dtype: int64
内部标识号    15582
交易次数         8
交易金额     76357
Name: 15581, dtype: int64
内部标识号    15583
交易次数         2
交易金额       337
Name: 15582, dtype: int64
内部标识号    15584
交易次数         0
交易金额      3473
Name: 15583, dtype: int64
内部标识号    15585
交易次数        14
交易金额       467
Name: 15584, dtype: int64
内部标识号    15586
交易次数         1
交易金额       651
Name: 15585, dtype: int64
内部标识号    15587
交易次数        15
交易金额       488
Name: 15586, dtype: int64
内部标识号    15588
交易次数        11
交易金额       815
Name: 15587, dtype: int64
内部标识号    15589
交易次数        13
交易金额       819
Name: 15588, dtype: int64
内部标识号    15590
交易次数         3
交易金额     93835
Name: 15589, dtype: int64
内部标识号    15591
交易次数         5
交易金额       166
Name: 15590, dtype: int64
内部标识号    15592
交易次数        18
交易金额      1322
Name: 15591, dtype: int64
内部标识号    15593
交易次数         6
交易金额       200
Name: 15592, dtype: int64
内部标识号    15594
交易次数         5
交易金额       193
Name: 15593, dtype: int64
内部标识号    15595
交易次数         2
交易金额       937
Name: 15594, dtype: int64
内部标识号    15596
交易次数         3
交易金额       392
Name: 15595, dtype: int64
内部标识号    15597
交易次数         8
交易金额       117
Name: 15596, dtype: int64
内部标识号    15598
交易次数        28
交易金额       682
Name: 15597, dtype: int64
内部标识号    15599
交易次数        28
交易金额       663
Name: 15598, dtype: int64
内部标识号    15600
交易次数        13
交易金额       639
Name: 15599, dtype: int64
内部标识号    15601
交易次数        12
交易金额       381
Name: 15600, dtype: int64
内部标识号    15602
交易次数         8
交易金额       796
Name: 15601, dtype: int64
内部标识号    15603
交易次数         8
交易金额     34496
Name: 15602, dtype: int64
内部标识号    15604
交易次数         8
交易金额     34646
Name: 15603, dtype: int64
内部标识号    15605
交易次数         9
交易金额       712
Name: 15604, dtype: int64
内部标识号    15606
交易次数         2
交易金额       768
Name: 15605, dtype: int64
内部标识号    15607
交易次数         2
交易金额       774
Name: 15606, dtype: int64
内部标识号    15608
交易次数         2
交易金额       491
Name: 15607, dtype: int64
内部标识号    15609
交易次数         6
交易金额     74237
Name: 15608, dtype: int64
内部标识号    15610
交易次数        11
交易金额       487
Name: 15609, dtype: int64
内部标识号    15611
交易次数         8
交易金额       621
Name: 15610, dtype: int64
内部标识号    15612
交易次数         8
交易金额       279
Name: 15611, dtype: int64
内部标识号    15613
交易次数        15
交易金额       369
Name: 15612, dtype: int64
内部标识号    15614
交易次数         1
交易金额       759
Name: 15613, dtype: int64
内部标识号    15615
交易次数         3
交易金额       242
Name: 15614, dtype: int64
内部标识号    15616
交易次数        12
交易金额       866
Name: 15615, dtype: int64
内部标识号    15617
交易次数        11
交易金额       447
Name: 15616, dtype: int64
内部标识号    15618
交易次数         1
交易金额      3726
Name: 15617, dtype: int64
内部标识号    15619
交易次数        10
交易金额       459
Name: 15618, dtype: int64
内部标识号    15620
交易次数         1
交易金额      6188
Name: 15619, dtype: int64
内部标识号    15621
交易次数         3
交易金额       338
Name: 15620, dtype: int64
内部标识号    15622
交易次数         3
交易金额       199
Name: 15621, dtype: int64
内部标识号    15623
交易次数         2
交易金额       439
Name: 15622, dtype: int64
内部标识号    15624
交易次数         8
交易金额       473
Name: 15623, dtype: int64
内部标识号    15625
交易次数        22
交易金额      8131
Name: 15624, dtype: int64
内部标识号    15626
交易次数         2
交易金额       300
Name: 15625, dtype: int64
内部标识号    15627
交易次数         0
交易金额      6911
Name: 15626, dtype: int64
内部标识号    15628
交易次数         5
交易金额       245
Name: 15627, dtype: int64
内部标识号    15629
交易次数        20
交易金额      8793
Name: 15628, dtype: int64
内部标识号    15630
交易次数        13
交易金额       450
Name: 15629, dtype: int64
内部标识号    15631
交易次数       290
交易金额     22169
Name: 15630, dtype: int64
内部标识号    15632
交易次数         7
交易金额       202
Name: 15631, dtype: int64
内部标识号    15633
交易次数        20
交易金额       921
Name: 15632, dtype: int64
内部标识号    15634
交易次数        15
交易金额       932
Name: 15633, dtype: int64
内部标识号    15635
交易次数         2
交易金额       386
Name: 15634, dtype: int64
内部标识号    15636
交易次数         2
交易金额       412
Name: 15635, dtype: int64
内部标识号    15637
交易次数         7
交易金额       134
Name: 15636, dtype: int64
内部标识号    15638
交易次数        20
交易金额      2329
Name: 15637, dtype: int64
内部标识号    15639
交易次数         4
交易金额     40253
Name: 15638, dtype: int64
内部标识号    15640
交易次数         1
交易金额       656
Name: 15639, dtype: int64
内部标识号    15641
交易次数         3
交易金额       319
Name: 15640, dtype: int64
内部标识号    15642
交易次数         8
交易金额       429
Name: 15641, dtype: int64
内部标识号    15643
交易次数        10
交易金额       370
Name: 15642, dtype: int64
内部标识号    15644
交易次数        13
交易金额       412
Name: 15643, dtype: int64
内部标识号    15645
交易次数         9
交易金额       500
Name: 15644, dtype: int64
内部标识号    15646
交易次数        16
交易金额      5296
Name: 15645, dtype: int64
内部标识号    15647
交易次数         8
交易金额       900
Name: 15646, dtype: int64
内部标识号    15648
交易次数         1
交易金额       506
Name: 15647, dtype: int64
内部标识号    15649
交易次数        15
交易金额       444
Name: 15648, dtype: int64
内部标识号    15650
交易次数         8
交易金额       767
Name: 15649, dtype: int64
内部标识号    15651
交易次数        14
交易金额       977
Name: 15650, dtype: int64
内部标识号    15652
交易次数         9
交易金额       373
Name: 15651, dtype: int64
内部标识号    15653
交易次数         9
交易金额       360
Name: 15652, dtype: int64
内部标识号    15654
交易次数         8
交易金额       989
Name: 15653, dtype: int64
内部标识号    15655
交易次数         7
交易金额       138
Name: 15654, dtype: int64
内部标识号    15656
交易次数        11
交易金额       623
Name: 15655, dtype: int64
内部标识号    15657
交易次数         0
交易金额      4564
Name: 15656, dtype: int64
内部标识号    15658
交易次数        21
交易金额       915
Name: 15657, dtype: int64
内部标识号    15659
交易次数        26
交易金额       707
Name: 15658, dtype: int64
内部标识号    15660
交易次数         0
交易金额      9255
Name: 15659, dtype: int64
内部标识号    15661
交易次数         8
交易金额       139
Name: 15660, dtype: int64
内部标识号    15662
交易次数         4
交易金额       116
Name: 15661, dtype: int64
内部标识号    15663
交易次数        14
交易金额       436
Name: 15662, dtype: int64
内部标识号    15664
交易次数         5
交易金额       134
Name: 15663, dtype: int64
内部标识号    15665
交易次数        11
交易金额       969
Name: 15664, dtype: int64
内部标识号    15666
交易次数         3
交易金额       256
Name: 15665, dtype: int64
内部标识号    15667
交易次数        72
交易金额     65744
Name: 15666, dtype: int64
内部标识号    15668
交易次数         4
交易金额     12579
Name: 15667, dtype: int64
内部标识号    15669
交易次数        10
交易金额       482
Name: 15668, dtype: int64
内部标识号    15670
交易次数         0
交易金额      4228
Name: 15669, dtype: int64
内部标识号    15671
交易次数        10
交易金额       476
Name: 15670, dtype: int64
内部标识号    15672
交易次数         3
交易金额     82211
Name: 15671, dtype: int64
内部标识号    15673
交易次数         0
交易金额      1517
Name: 15672, dtype: int64
内部标识号    15674
交易次数         8
交易金额       550
Name: 15673, dtype: int64
内部标识号    15675
交易次数         2
交易金额       784
Name: 15674, dtype: int64
内部标识号    15676
交易次数        12
交易金额       596
Name: 15675, dtype: int64
内部标识号    15677
交易次数        10
交易金额       608
Name: 15676, dtype: int64
内部标识号    15678
交易次数         8
交易金额       347
Name: 15677, dtype: int64
内部标识号    15679
交易次数        17
交易金额       965
Name: 15678, dtype: int64
内部标识号    15680
交易次数        10
交易金额       801
Name: 15679, dtype: int64
内部标识号    15681
交易次数       268
交易金额     43600
Name: 15680, dtype: int64
内部标识号    15682
交易次数         8
交易金额       824
Name: 15681, dtype: int64
内部标识号    15683
交易次数         3
交易金额       439
Name: 15682, dtype: int64
内部标识号    15684
交易次数         0
交易金额      7608
Name: 15683, dtype: int64
内部标识号    15685
交易次数        18
交易金额      7648
Name: 15684, dtype: int64
内部标识号    15686
交易次数         1
交易金额       682
Name: 15685, dtype: int64
内部标识号    15687
交易次数         2
交易金额       683
Name: 15686, dtype: int64
内部标识号    15688
交易次数        19
交易金额        88
Name: 15687, dtype: int64
内部标识号    15689
交易次数         1
交易金额       996
Name: 15688, dtype: int64
内部标识号    15690
交易次数         1
交易金额       631
Name: 15689, dtype: int64
内部标识号    15691
交易次数        12
交易金额       576
Name: 15690, dtype: int64
内部标识号    15692
交易次数         3
交易金额       423
Name: 15691, dtype: int64
内部标识号    15693
交易次数        24
交易金额       931
Name: 15692, dtype: int64
内部标识号    15694
交易次数        20
交易金额      8375
Name: 15693, dtype: int64
内部标识号    15695
交易次数        25
交易金额       668
Name: 15694, dtype: int64
内部标识号    15696
交易次数         3
交易金额       113
Name: 15695, dtype: int64
内部标识号    15697
交易次数        10
交易金额       492
Name: 15696, dtype: int64
内部标识号    15698
交易次数       262
交易金额     83402
Name: 15697, dtype: int64
内部标识号    15699
交易次数        12
交易金额       522
Name: 15698, dtype: int64
内部标识号    15700
交易次数         4
交易金额     23706
Name: 15699, dtype: int64
内部标识号    15701
交易次数         7
交易金额       138
Name: 15700, dtype: int64
内部标识号    15702
交易次数        95
交易金额     20254
Name: 15701, dtype: int64
内部标识号    15703
交易次数        15
交易金额       844
Name: 15702, dtype: int64
内部标识号    15704
交易次数        19
交易金额      6391
Name: 15703, dtype: int64
内部标识号    15705
交易次数        14
交易金额       700
Name: 15704, dtype: int64
内部标识号    15706
交易次数         8
交易金额       541
Name: 15705, dtype: int64
内部标识号    15707
交易次数        12
交易金额       883
Name: 15706, dtype: int64
内部标识号    15708
交易次数       272
交易金额     77000
Name: 15707, dtype: int64
内部标识号    15709
交易次数        12
交易金额       709
Name: 15708, dtype: int64
内部标识号    15710
交易次数        13
交易金额       373
Name: 15709, dtype: int64
内部标识号    15711

Name: 15754, dtype: int64
内部标识号    15756
交易次数         1
交易金额       798
Name: 15755, dtype: int64
内部标识号    15757
交易次数        12
交易金额       355
Name: 15756, dtype: int64
内部标识号    15758
交易次数         1
交易金额       711
Name: 15757, dtype: int64
内部标识号    15759
交易次数         0
交易金额      3196
Name: 15758, dtype: int64
内部标识号    15760
交易次数         2
交易金额       406
Name: 15759, dtype: int64
内部标识号    15761
交易次数         1
交易金额       915
Name: 15760, dtype: int64
内部标识号    15762
交易次数         2
交易金额       437
Name: 15761, dtype: int64
内部标识号    15763
交易次数        15
交易金额      4403
Name: 15762, dtype: int64
内部标识号    15764
交易次数         1
交易金额       676
Name: 15763, dtype: int64
内部标识号    15765
交易次数        14
交易金额       360
Name: 15764, dtype: int64
内部标识号    15766
交易次数         1
交易金额       533
Name: 15765, dtype: int64
内部标识号    15767
交易次数         3
交易金额       197
Name: 15766, dtype: int64
内部标识号    15768
交易次数         0
交易金额      6978
Name: 15767, dtype: int64
内部标识号    15769
交易次数         6
交易金额       173
Name: 15768, dtype: int64
内部标识号    15770
交易次数         2
交易金额       471
Name: 15769, dtype: int64
内部标识号    15771
交易次数         2
交易金额       760
Name: 15770, dtype: int64
内部标识号    15772
交易次数        27
交易金额      9019
Name: 15771, dtype: int64
内部标识号    15773
交易次数         2
交易金额       612
Name: 15772, dtype: int64
内部标识号    15774
交易次数         1
交易金额       916
Name: 15773, dtype: int64
内部标识号    15775
交易次数        29
交易金额       597
Name: 15774, dtype: int64
内部标识号    15776
交易次数         3
交易金额       314
Name: 15775, dtype: int64
内部标识号    15777
交易次数         4
交易金额       267
Name: 15776, dtype: int64
内部标识号    15778
交易次数        27
交易金额         3
Name: 15777, dtype: int64
内部标识号    15779
交易次数        20
交易金额      7906
Name: 15778, dtype: int64
内部标识号    15780
交易次数        13
交易金额       671
Name: 15779, dtype: int64
内部标识号    15781
交易次数        18
交易金额       920
Name: 15780, dtype: int64
内部标识号    15782
交易次数        21
交易金额        17
Name: 15781, dtype: int64
内部标识号    15783
交易次数         2
交易金额       759
Name: 15782, dtype: int64
内部标识号    15784
交易次数         9
交易金额       474
Name: 15783, dtype: int64
内部标识号    15785
交易次数         2
交易金额       214
Name: 15784, dtype: int64
内部标识号    15786
交易次数         1
交易金额       853
Name: 15785, dtype: int64
内部标识号    15787
交易次数         9
交易金额       453
Name: 15786, dtype: int64
内部标识号    15788
交易次数         2
交易金额       428
Name: 15787, dtype: int64
内部标识号    15789
交易次数         2
交易金额       366
Name: 15788, dtype: int64
内部标识号    15790
交易次数         1
交易金额      5590
Name: 15789, dtype: int64
内部标识号    15791
交易次数        14
交易金额       814
Name: 15790, dtype: int64
内部标识号    15792
交易次数         2
交易金额       672
Name: 15791, dtype: int64
内部标识号    15793
交易次数         2
交易金额       404
Name: 15792, dtype: int64
内部标识号    15794
交易次数        13
交易金额       454
Name: 15793, dtype: int64
内部标识号    15795
交易次数         3
交易金额     61459
Name: 15794, dtype: int64
内部标识号    15796
交易次数         1
交易金额       941
Name: 15795, dtype: int64
内部标识号    15797
交易次数         6
交易金额     14108
Name: 15796, dtype: int64
内部标识号    15798
交易次数         0
交易金额      4318
Name: 15797, dtype: int64
内部标识号    15799
交易次数         3
交易金额       146
Name: 15798, dtype: int64
内部标识号    15800
交易次数         5
交易金额     51084
Name: 15799, dtype: int64
内部标识号    15801
交易次数         0
交易金额      1717
Name: 15800, dtype: int64
内部标识号    15802
交易次数         2
交易金额       834
Name: 15801, dtype: int64
内部标识号    15803
交易次数         3
交易金额     24391
Name: 15802, dtype: int64
内部标识号    15804
交易次数       191
交易金额     23306
Name: 15803, dtype: int64
内部标识号    15805
交易次数        15
交易金额       855
Name: 15804, dtype: int64
内部标识号    15806
交易次数         4
交易金额       223
Name: 15805, dtype: int64
内部标识号    15807
交易次数         3
交易金额       416
Name: 15806, dtype: int64
内部标识号    15808
交易次数        12
交易金额       340
Name: 15807, dtype: int64
内部标识号    15809
交易次数         7
交易金额       273
Name: 15808, dtype: int64
内部标识号    15810
交易次数        27
交易金额      3681
Name: 15809, dtype: int64
内部标识号    15811
交易次数         0
交易金额      7107
Name: 15810, dtype: int64
内部标识号    15812
交易次数         2
交易金额       362
Name: 15811, dtype: int64
内部标识号    15813
交易次数        14
交易金额       656
Name: 15812, dtype: int64
内部标识号    15814
交易次数         9
交易金额       674
Name: 15813, dtype: int64
内部标识号    15815
交易次数        18
交易金额       704
Name: 15814, dtype: int64
内部标识号    15816
交易次数        18
交易金额      4723
Name: 15815, dtype: int64
内部标识号    15817
交易次数         9
交易金额       657
Name: 15816, dtype: int64
内部标识号    15818
交易次数         2
交易金额       321
Name: 15817, dtype: int64
内部标识号    15819
交易次数        11
交易金额       812
Name: 15818, dtype: int64
内部标识号    15820
交易次数         7
交易金额       275
Name: 15819, dtype: int64
内部标识号    15821
交易次数        30
交易金额      6728
Name: 15820, dtype: int64
内部标识号    15822
交易次数       168
交易金额     52376
Name: 15821, dtype: int64
内部标识号    15823
交易次数       232
交易金额     34115
Name: 15822, dtype: int64
内部标识号    15824
交易次数        13
交易金额       743
Name: 15823, dtype: int64
内部标识号    15825
交易次数        11
交易金额       396
Name: 15824, dtype: int64
内部标识号    15826
交易次数        31
交易金额     35686
Name: 15825, dtype: int64
内部标识号    15827
交易次数        13
交易金额       361
Name: 15826, dtype: int64
内部标识号    15828
交易次数         6
交易金额       247
Name: 15827, dtype: int64
内部标识号    15829
交易次数         4
交易金额     39818
Name: 15828, dtype: int64
内部标识号    15830
交易次数        24
交易金额      9871
Name: 15829, dtype: int64
内部标识号    15831
交易次数        14
交易金额       457
Name: 15830, dtype: int64
内部标识号    15832
交易次数        17
交易金额      6953
Name: 15831, dtype: int64
内部标识号    15833
交易次数        13
交易金额       999
Name: 15832, dtype: int64
内部标识号    15834
交易次数         9
交易金额       562
Name: 15833, dtype: int64
内部标识号    15835
交易次数         3
交易金额       185
Name: 15834, dtype: int64
内部标识号    15836
交易次数        10
交易金额       480
Name: 15835, dtype: int64
内部标识号    15837
交易次数         5
交易金额       146
Name: 15836, dtype: int64
内部标识号    15838
交易次数        22
交易金额       879
Name: 15837, dtype: int64
内部标识号    15839
交易次数         3
交易金额       310
Name: 15838, dtype: int64
内部标识号    15840
交易次数        15
交易金额       389
Name: 15839, dtype: int64
内部标识号    15841
交易次数        12
交易金额       619
Name: 15840, dtype: int64
内部标识号    15842
交易次数        13
交易金额       396
Name: 15841, dtype: int64
内部标识号    15843
交易次数         1
交易金额      1753
Name: 15842, dtype: int64
内部标识号    15844
交易次数         2
交易金额       351
Name: 15843, dtype: int64
内部标识号    15845
交易次数        22
交易金额      2931
Name: 15844, dtype: int64
内部标识号    15846
交易次数        12
交易金额       490
Name: 15845, dtype: int64
内部标识号    15847
交易次数         6
交易金额       249
Name: 15846, dtype: int64
内部标识号    15848
交易次数         1
交易金额       939
Name: 15847, dtype: int64
内部标识号    15849
交易次数         1
交易金额       914
Name: 15848, dtype: int64
内部标识号    15850
交易次数         8
交易金额       985
Name: 15849, dtype: int64
内部标识号    15851
交易次数         2
交易金额       445
Name: 15850, dtype: int64
内部标识号    15852
交易次数         9
交易金额       707
Name: 15851, dtype: int64
内部标识号    15853
交易次数         3
交易金额       439
Name: 15852, dtype: int64
内部标识号    15854
交易次数       235
交易金额     79352
Name: 15853, dtype: int64
内部标识号    15855
交易次数        15
交易金额       885
Name: 15854, dtype: int64
内部标识号    15856
交易次数         3
交易金额       366
Name: 15855, dtype: int64
内部标识号    15857
交易次数         0
交易金额      5871
Name: 15856, dtype: int64
内部标识号    15858
交易次数         6
交易金额       103
Name: 15857, dtype: int64
内部标识号    15859
交易次数        23
交易金额      3049
Name: 15858, dtype: int64
内部标识号    15860
交易次数         2
交易金额       903
Name: 15859, dtype: int64
内部标识号    15861
交易次数         5
交易金额       237
Name: 15860, dtype: int64
内部标识号    15862
交易次数         0
交易金额      5752
Name: 15861, dtype: int64
内部标识号    15863
交易次数         9
交易金额       797
Name: 15862, dtype: int64
内部标识号    15864
交易次数        10
交易金额       926
Name: 15863, dtype: int64
内部标识号    15865
交易次数        11
交易金额       408
Name: 15864, dtype: int64
内部标识号    15866
交易次数        14
交易金额       362
Name: 15865, dtype: int64
内部标识号    15867
交易次数        14
交易金额       934
Name: 15866, dtype: int64
内部标识号    15868
交易次数         2
交易金额       478
Name: 15867, dtype: int64
内部标识号    15869
交易次数        28
交易金额      2637
Name: 15868, dtype: int64
内部标识号    15870
交易次数         2
交易金额       664
Name: 15869, dtype: int64
内部标识号    15871
交易次数        12
交易金额       491
Name: 15870, dtype: int64
内部标识号    15872
交易次数         2
交易金额       957
Name: 15871, dtype: int64
内部标识号    15873
交易次数       154
交易金额     29684
Name: 15872, dtype: int64
内部标识号    15874
交易次数         6
交易金额     22120
Name: 15873, dtype: int64
内部标识号    15875
交易次数         0
交易金额      5747
Name: 15874, dtype: int64
内部标识号    15876
交易次数        25
交易金额        21
Name: 15875, dtype: int64
内部标识号    15877
交易次数       154
交易金额     68939
Name: 15876, dtype: int64
内部标识号    15878
交易次数        14
交易金额       332
Name: 15877, dtype: int64
内部标识号    15879
交易次数         2
交易金额       275
Name: 15878, dtype: int64
内部标识号    15880
交易次数         2
交易金额       318
Name: 15879, dtype: int64
内部标识号    15881
交易次数         5
交易金额       278
Name: 15880, dtype: int64
内部标识号    15882
交易次数         3
交易金额     52580
Name: 15881, dtype: int64
内部标识号    15883
交易次数        27
交易金额      6751
Name: 15882, dtype: int64
内部标识号    15884
交易次数        27
交易金额       757
Name: 15883, dtype: int64
内部标识号    15885
交易次数         2
交易金额       320
Name: 15884, dtype: int64
内部标识号    15886
交易次数         4
交易金额       184
Name: 15885, dtype: int64
内部标识号    15887
交易次数         2
交易金额       457
Name: 15886, dtype: int64
内部标识号    15888
交易次数         2
交易金额       381
Name: 15887, dtype: int64
内部标识号    15889
交易次数         1
交易金额       550
Name: 15888, dtype: int64
内部标识号    15890
交易次数        11
交易金额       826
Name: 15889, dtype: int64
内部标识号    15891
交易次数        11
交易金额       325
Name: 15890, dtype: int64
内部标识号    15892
交易次数        15
交易金额       538
Name: 15891, dtype: int64
内部标识号    15893
交易次数        11
交易金额       540
Name: 15892, dtype: int64
内部标识号    15894
交易次数         3
交易金额       318
Name: 15893, dtype: int64
内部标识号    15895
交易次数        15
交易金额       414
Name: 15894, dtype: int64
内部标识号    15896
交易次数         0
交易金额      9185
Name: 15895, dtype: int64
内部标识号    15897
交易次数         2
交易金额       470
Name: 15896, dtype: int64
内部标识号    15898
交易次数        10
交易金额       799
Name: 15897, dtype: int64
内部标识号    15899
交易次数         6
交易金额       146
Name: 15898, dtype: int64
内部标识号    15900
交易次数         8
交易金额       681
Name: 15899, dtype: int64
内部标识号    15901
交易次数        30
交易金额       987
Name: 15900, dtype: int64
内部标识号    15902
交易次数         9
交易金额       719
Name: 15901, dtype: int64
内部标识号    15903
交易次数         3
交易金额       291
Name: 15902, dtype: int64
内部标识号    15904
交易次数        12
交易金额       596
Name: 15903, dtype: int64
内部标识号    15905
交易次数         2
交易金额       313
Name: 15904, dtype: int64
内部标识号    15906
交易次数         2
交易金额       335
Name: 15905, dtype: int64
内部标识号    15907
交易次数         1
交易金额       719
Name: 15906, dtype: int64
内部标识号    15908
交易次数        22
交易金额       930
Name: 15907, dtype: int64
内部标识号    15909
交易次数         1
交易金额      3089
Name: 15908, dtype: int64
内部标识号    15910
交易次数         8
交易金额       846
Name: 15909, dtype: int64
内部标识号    15911
交易次数         5
交易金额       123
Name: 15910, dtype: int64
内部标识号    15912
交易次数         0
交易金额      6440
Name: 15911, dtype: int64
内部标识号    15913
交易次数         3
交易金额       143
Name: 15912, dtype: int64
内部标识号    15914
交易次数         0
交易金额      3926
Name: 15913, dtype: int64
内部标识号    15915
交易次数         7
交易金额       210
Name: 15914, dtype: int64
内部标识号    15916
交易次数         6
交易金额       111
Name: 15915, dtype: int64
内部标识号    15917
交易次数         1
交易金额       944
Name: 15916, dtype: int64
内部标识号    15918
交易次数         0
交易金额      2254
Name: 15917, dtype: int64
内部标识号    15919
交易次数         3
交易金额       402
Name: 15918, dtype: int64
内部标识号    15920
交易次数         3
交易金额       365
Name: 15919, dtype: int64
内部标识号    15921
交易次数         0
交易金额      8067
Name: 15920, dtype: int64
内部标识号    15922
交易次数         1
交易金额      5560
Name: 15921, dtype: int64
内部标识号    15923
交易次数        13
交易金额       437
Name: 15922, dtype: int64
内部标识号    15924
交易次数         1
交易金额       759
Name: 15923, dtype: int64
内部标识号    15925
交易次数        27
交易金额       696
Name: 15924, dtype: int64
内部标识号    15926
交易次数        24
交易金额      8360
Name: 15925, dtype: int64
内部标识号    15927
交易次数         1
交易金额       730
Name: 15926, dtype: int64
内部标识号    15928
交易次数        10
交易金额       449
Name: 15927, dtype: int64
内部标识号    15929
交易次数        19
交易金额       544
Name: 15928, dtype: int64
内部标识号    15930
交易次数        30
交易金额       658
Name: 15929, dtype: int64
内部标识号    15931
交易次数        29
交易金额       987
Name: 15930, dtype: int64
内部标识号    15932
交易次数        25
交易金额      3712
Name: 15931, dtype: int64
内部标识号    15933
交易次数         2
交易金额       111
Name: 15932, dtype: int64
内部标识号    15934
交易次数        12
交易金额       394
Name: 15933, dtype: int64
内部标识号    15935
交易次数        13
交易金额       996
Name: 15934, dtype: int64
内部标识号    15936
交易次数         5
交易金额       238
Name: 15935, dtype: int64
内部标识号    15937
交易次数        18
交易金额      4723
Name: 15936, dtype: int64
内部标识号    15938
交易次数         5
交易金额       145
Name: 15937, dtype: int64
内部标识号    15939
交易次数        11
交易金额       461
Name: 15938, dtype: int64
内部标识号    15940
交易次数        17
交易金额      9509
Name: 15939, dtype: int64
内部标识号    15941
交易次数        12
交易金额       622
Name: 15940, dtype: int64
内部标识号    15942
交易次数        14
交易金额       800
Name: 15941, dtype: int64
内部标识号    15943
交易次数         7
交易金额     57272
Name: 15942, dtype: int64
内部标识号    15944
交易次数        10
交易金额       592
Name: 15943, dtype: int64
内部标识号    15945
交易次数        12
交易金额       785
Name: 15944, dtype: int64
内部标识号    15946
交易次数         1
交易金额       908
Name: 15945, dtype: int64
内部标识号    15947
交易次数         2
交易金额       681
Name: 15946, dtype: int64
内部标识号    15948
交易次数        13
交易金额       675
Name: 15947, dtype: int64
内部标识号    15949
交易次数        30
交易金额      5107
Name: 15948, dtype: int64
内部标识号    15950
交易次数         2
交易金额       500
Name: 15949, dtype: int64
内部标识号    15951
交易次数        13
交易金额       987
Name: 15950, dtype: int64
内部标识号    15952
交易次数         6
交易金额     88298
Name: 15951, dtype: int64
内部标识号    15953
交易次数       122
交易金额     66660
Name: 15952, dtype: int64
内部标识号    15954
交易次数        14
交易金额       615
Name: 15953, dtype: int64
内部标识号    15955
交易次数        11
交易金额       754
Name: 15954, dtype: int64
内部标识号    15956
交易次数        25
交易金额        98
Name: 15955, dtype: int64
内部标识号    15957
交易次数         2
交易金额       453
Name: 15956, dtype: int64
内部标识号    15958
交易次数         1
交易金额       804
Name: 15957, dtype: int64
内部标识号    15959
交易次数         6
交易金额     58735
Name: 15958, dtype: int64
内部标识号    15960
交易次数         4
交易金额       226
Name: 15959, dtype: int64
内部标识号    15961
交易次数         9
交易金额       611
Name: 15960, dtype: int64
内部标识号    15962
交易次数         3
交易金额       377
Name: 15961, dtype: int64
内部标识号    15963
交易次数        10
交易金额       796
Name: 15962, dtype: int64
内部标识号    15964
交易次数         4
交易金额     67448
Name: 15963, dtype: int64
内部标识号    15965
交易次数         8
交易金额     54266
Name: 15964, dtype: int64
内部标识号    15966
交易次数         2
交易金额       405
Name: 15965, dtype: int64
内部标识号    15967
交易次数         6
交易金额       101
Name: 15966, dtype: int64
内部标识号    15968
交易次数         6
交易金额       210
Name: 15967, dtype: int64
内部标识号    15969
交易次数        12
交易金额       438
Name: 15968, dtype: int64
内部标识号    15970
交易次数         0
交易金额      8016
Name: 15969, dtype: int64
内部标识号    15971
交易次数         2
交易金额       356
Name: 15970, dtype: int64
内部标识号    15972
交易次数         8
交易金额       531
Name: 15971, dtype: int64
内部标识号    15973
交易次数         5
交易金额       226
Name: 15972, dtype: int64
内部标识号    15974
交易次数        14
交易金额       401
Name: 15973, dtype: int64
内部标识号    15975
交易次数        15
交易金额       343
Name: 15974, dtype: int64
内部标识号    15976
交易次数       143
交易金额     86520
Name: 15975, dtype: int64
内部标识号    15977
交易次数         1
交易金额      1103
Name: 15976, dtype: int64
内部标识号    15978
交易次数         0
交易金额      8463
Name: 15977, dtype: int64
内部标识号    15979
交易次数         3
交易金额     54706
Name: 15978, dtype: int64
内部标识号    15980
交易次数         3
交易金额       209
Name: 15979, dtype: int64
内部标识号    15981
交易次数         2
交易金额       343
Name: 15980, dtype: int64
内部标识号    15982
交易次数         2
交易金额       859
Name: 15981, dtype: int64
内部标识号    15983
交易次数         8
交易金额       577
Name: 15982, dtype: int64
内部标识号    15984
交易次数         1
交易金额       653
Name: 15983, dtype: int64
内部标识号    15985
交易次数         3
交易金额       418
Name: 15984, dtype: int64
内部标识号    15986
交易次数         8
交易金额     34604
Name: 15985, dtype: int64
内部标识号    15987
交易次数        13
交易金额       354
Name: 15986, dtype: int64
内部标识号    15988
交易次数         2
交易金额       298
Name: 15987, dtype: int64
内部标识号    15989
交易次数        11
交易金额       347
Name: 15988, dtype: int64
内部标识号    15990
交易次数         3
交易金额       137
Name: 15989, dtype: int64
内部标识号    15991
交易次数        12
交易金额       489
Name: 15990, dtype: int64
内部标识号    15992
交易次数         3
交易金额       161
Name: 15991, dtype: int64
内部标识号    15993
交易次数        15
交易金额       687
Name: 15992, dtype: int64
内部标识号    15994
交易次数        13
交易金额       335
Name: 15993, dtype: int64
内部标识号    15995
交易次数        16
交易金额       589
Name: 15994, dtype: int64
内部标识号    15996
交易次数         8
交易金额     47606
Name: 15995, dtype: int64
内部标识号    15997
交易次数         2
交易金额       610
Name: 15996, dtype: int64
内部标识号    15998
交易次数        12
交易金额       941
Name: 15997, dtype: int64
内部标识号    15999
交易次数         7
交易金额       252
Name: 15998, dtype: int64
内部标识号    16000
交易次数         1
交易金额       553
Name: 15999, dtype: int64
内部标识号    16001
交易次数         6
交易金额     39869
Name: 16000, dtype: int64
内部标识号    16002
交易次数         6
交易金额       124
Name: 16001, dtype: int64
内部标识号    16003
交易次数       273
交易金额     16422
Name: 16002, dtype: int64
内部标识号    16004
交易次数        19
交易金额      6809
Name: 16003, dtype: int64
内部标识号    16005
交易次数         4
交易金额       293
Name: 16004, dtype: int64
内部标识号    16006
交易次数         0
交易金额      2191
Name: 16005, dtype: int64
内部标识号    16007
交易次数         3
交易金额       497
Name: 16006, dtype: int64
内部标识号    16008
交易次数         8
交易金额       832
Name: 16007, dtype: int64
内部标识号    16009
交易次数         2
交易金额       431
Name: 16008, dtype: int64
内部标识号    16010
交易次数        12
交易金额       317
Name: 16009, dtype: int64
内部标识号    16011
交易次数         1
交易金额      5169
Name: 16010, dtype: int64
内部标识号    16012
交易次数        17
交易金额      8133
Name: 16011, dtype: int64
内部标识号    16013
交易次数         1
交易金额      9792
Name: 16012, dtype: int64
内部标识号    16014
交易次数         7
交易金额       121
Name: 16013, dtype: int64
内部标识号    16015
交易次数         3
交易金额       133
Name: 16014, dtype: int64
内部标识号    16016
交易次数        10
交易金额       956
Name: 16015, dtype: int64
内部标识号    16017
交易次数         1
交易金额       957
Name: 16016, dtype: int64
内部标识号    16018
交易次数        11
交易金额       703
Name: 16017, dtype: int64
内部标识号    16019
交易次数        25
交易金额      3660
Name: 16018, dtype: int64
内部标识号    16020
交易次数         1
交易金额       510
Name: 16019, dtype: int64
内部标识号    16021
交易次数         8
交易金额       662
Name: 16020, dtype: int64
内部标识号    16022
交易次数        13
交易金额       837
Name: 16021, dtype: int64
内部标识号    16023
交易次数         8
交易金额       179
Name: 16022, dtype: int64
内部标识号    16024
交易次数         8
交易金额       361
Name: 16023, dtype: int64
内部标识号    16025
交易次数         2
交易金额       927
Name: 16024, dtype: int64
内部标识号    16026
交易次数         1
交易金额      4448
Name: 16025, dtype: int64
内部标识号    16027
交易次数        15
交易金额       887
Name: 16026, dtype: int64
内部标识号    16028
交易次数        15
交易金额       597
Name: 16027, dtype: int64
内部标识号    16029
交易次数        10
交易金额       594
Name: 16028, dtype: int64
内部标识号    16030
交易次数        19
交易金额      4140
Name: 16029, dtype: int64
内部标识号    16031
交易次数       290
交易金额     94730
Name: 16030, dtype: int64
内部标识号    16032
交易次数         3
交易金额       447
Name: 16031, dtype: int64
内部标识号    16033
交易次数        12
交易金额       385
Name: 16032, dtype: int64
内部标识号    16034
交易次数         4
交易金额       215
Name: 16033, dtype: int64
内部标识号    16035
交易次数         5
交易金额       246
Name: 16034, dtype: int64
内部标识号    16036
交易次数         2
交易金额       443
Name: 16035, dtype: int64
内部标识号    16037

内部标识号    16255
交易次数         1
交易金额       573
Name: 16254, dtype: int64
内部标识号    16256
交易次数        30
交易金额      9503
Name: 16255, dtype: int64
内部标识号    16257
交易次数        13
交易金额       489
Name: 16256, dtype: int64
内部标识号    16258
交易次数        30
交易金额      1322
Name: 16257, dtype: int64
内部标识号    16259
交易次数         3
交易金额       334
Name: 16258, dtype: int64
内部标识号    16260
交易次数         3
交易金额       304
Name: 16259, dtype: int64
内部标识号    16261
交易次数        28
交易金额      6113
Name: 16260, dtype: int64
内部标识号    16262
交易次数        13
交易金额       772
Name: 16261, dtype: int64
内部标识号    16263
交易次数         5
交易金额       286
Name: 16262, dtype: int64
内部标识号    16264
交易次数         3
交易金额       253
Name: 16263, dtype: int64
内部标识号    16265
交易次数         5
交易金额       196
Name: 16264, dtype: int64
内部标识号    16266
交易次数        13
交易金额       851
Name: 16265, dtype: int64
内部标识号    16267
交易次数         6
交易金额       244
Name: 16266, dtype: int64
内部标识号    16268
交易次数        15
交易金额       764
Name: 16267, dtype: int64
内部标识号    16269
交易次数        12
交易金额       805
Name: 16268, dtype: int64
内部标识号    16270
交易次数         8
交易金额       454
Name: 16269, dtype: int64
内部标识号    16271
交易次数        14
交易金额       751
Name: 16270, dtype: int64
内部标识号    16272
交易次数         3
交易金额       421
Name: 16271, dtype: int64
内部标识号    16273
交易次数        15
交易金额       548
Name: 16272, dtype: int64
内部标识号    16274
交易次数         9
交易金额       554
Name: 16273, dtype: int64
内部标识号    16275
交易次数        13
交易金额       480
Name: 16274, dtype: int64
内部标识号    16276
交易次数         0
交易金额      3886
Name: 16275, dtype: int64
内部标识号    16277
交易次数         0
交易金额      9179
Name: 16276, dtype: int64
内部标识号    16278
交易次数        11
交易金额       828
Name: 16277, dtype: int64
内部标识号    16279
交易次数         1
交易金额       656
Name: 16278, dtype: int64
内部标识号    16280
交易次数         9
交易金额       738
Name: 16279, dtype: int64
内部标识号    16281
交易次数         1
交易金额       773
Name: 16280, dtype: int64
内部标识号    16282
交易次数         5
交易金额     64537
Name: 16281, dtype: int64
内部标识号    16283
交易次数         0
交易金额      9326
Name: 16282, dtype: int64
内部标识号    16284
交易次数        28
交易金额       935
Name: 16283, dtype: int64
内部标识号    16285
交易次数         6
交易金额     81197
Name: 16284, dtype: int64
内部标识号    16286
交易次数         3
交易金额       129
Name: 16285, dtype: int64
内部标识号    16287
交易次数        13
交易金额       571
Name: 16286, dtype: int64
内部标识号    16288
交易次数        15
交易金额       533
Name: 16287, dtype: int64
内部标识号    16289
交易次数        17
交易金额      7777
Name: 16288, dtype: int64
内部标识号    16290
交易次数        12
交易金额       649
Name: 16289, dtype: int64
内部标识号    16291
交易次数         8
交易金额     59287
Name: 16290, dtype: int64
内部标识号    16292
交易次数        12
交易金额       342
Name: 16291, dtype: int64
内部标识号    16293
交易次数        17
交易金额        44
Name: 16292, dtype: int64
内部标识号    16294
交易次数         6
交易金额     17605
Name: 16293, dtype: int64
内部标识号    16295
交易次数         8
交易金额       285
Name: 16294, dtype: int64
内部标识号    16296
交易次数        14
交易金额       971
Name: 16295, dtype: int64
内部标识号    16297
交易次数         2
交易金额       329
Name: 16296, dtype: int64
内部标识号    16298
交易次数        10
交易金额       809
Name: 16297, dtype: int64
内部标识号    16299
交易次数         0
交易金额      6612
Name: 16298, dtype: int64
内部标识号    16300
交易次数         2
交易金额       569
Name: 16299, dtype: int64
内部标识号    16301
交易次数        16
交易金额       902
Name: 16300, dtype: int64
内部标识号    16302
交易次数         3
交易金额       115
Name: 16301, dtype: int64
内部标识号    16303
交易次数        13
交易金额       518
Name: 16302, dtype: int64
内部标识号    16304
交易次数         7
交易金额       148
Name: 16303, dtype: int64
内部标识号    16305
交易次数         8
交易金额       153
Name: 16304, dtype: int64
内部标识号    16306
交易次数         9
交易金额       347
Name: 16305, dtype: int64
内部标识号    16307
交易次数        10
交易金额       934
Name: 16306, dtype: int64
内部标识号    16308
交易次数         7
交易金额       276
Name: 16307, dtype: int64
内部标识号    16309
交易次数        15
交易金额       889
Name: 16308, dtype: int64
内部标识号    16310
交易次数         3
交易金额       439
Name: 16309, dtype: int64
内部标识号    16311
交易次数         0
交易金额      1395
Name: 16310, dtype: int64
内部标识号    16312
交易次数         3
交易金额       107
Name: 16311, dtype: int64
内部标识号    16313
交易次数        10
交易金额       402
Name: 16312, dtype: int64
内部标识号    16314
交易次数         0
交易金额      3632
Name: 16313, dtype: int64
内部标识号    16315
交易次数        20
交易金额       897
Name: 16314, dtype: int64
内部标识号    16316
交易次数         2
交易金额       760
Name: 16315, dtype: int64
内部标识号    16317
交易次数        14
交易金额       676
Name: 16316, dtype: int64
内部标识号    16318
交易次数         1
交易金额      1262
Name: 16317, dtype: int64
内部标识号    16319
交易次数        28
交易金额      2660
Name: 16318, dtype: int64
内部标识号    16320
交易次数        13
交易金额       715
Name: 16319, dtype: int64
内部标识号    16321
交易次数         9
交易金额       769
Name: 16320, dtype: int64
内部标识号    16322
交易次数         1
交易金额       599
Name: 16321, dtype: int64
内部标识号    16323
交易次数         4
交易金额       168
Name: 16322, dtype: int64
内部标识号    16324
交易次数         8
交易金额     53276
Name: 16323, dtype: int64
内部标识号    16325
交易次数         0
交易金额      3314
Name: 16324, dtype: int64
内部标识号    16326
交易次数         1
交易金额      3536
Name: 16325, dtype: int64
内部标识号    16327
交易次数        14
交易金额       594
Name: 16326, dtype: int64
内部标识号    16328
交易次数         3
交易金额       339
Name: 16327, dtype: int64
内部标识号    16329
交易次数        14
交易金额       385
Name: 16328, dtype: int64
内部标识号    16330
交易次数        14
交易金额       452
Name: 16329, dtype: int64
内部标识号    16331
交易次数         5
交易金额       148
Name: 16330, dtype: int64
内部标识号    16332
交易次数        26
交易金额      7537
Name: 16331, dtype: int64
内部标识号    16333
交易次数        10
交易金额       699
Name: 16332, dtype: int64
内部标识号    16334
交易次数         8
交易金额       155
Name: 16333, dtype: int64
内部标识号    16335
交易次数         3
交易金额       143
Name: 16334, dtype: int64
内部标识号    16336
交易次数        28
交易金额       660
Name: 16335, dtype: int64
内部标识号    16337
交易次数         8
交易金额       184
Name: 16336, dtype: int64
内部标识号    16338
交易次数         5
交易金额     44483
Name: 16337, dtype: int64
内部标识号    16339
交易次数         3
交易金额       375
Name: 16338, dtype: int64
内部标识号    16340
交易次数         3
交易金额       329
Name: 16339, dtype: int64
内部标识号    16341
交易次数        11
交易金额       698
Name: 16340, dtype: int64
内部标识号    16342
交易次数         1
交易金额       723
Name: 16341, dtype: int64
内部标识号    16343
交易次数         2
交易金额       479
Name: 16342, dtype: int64
内部标识号    16344
交易次数        23
交易金额      6484
Name: 16343, dtype: int64
内部标识号    16345
交易次数         8
交易金额       442
Name: 16344, dtype: int64
内部标识号    16346
交易次数        21
交易金额       642
Name: 16345, dtype: int64
内部标识号    16347
交易次数        14
交易金额       810
Name: 16346, dtype: int64
内部标识号    16348
交易次数         0
交易金额      4368
Name: 16347, dtype: int64
内部标识号    16349
交易次数         3
交易金额       497
Name: 16348, dtype: int64
内部标识号    16350
交易次数         5
交易金额       256
Name: 16349, dtype: int64
内部标识号    16351
交易次数        19
交易金额      8987
Name: 16350, dtype: int64
内部标识号    16352
交易次数         3
交易金额     71253
Name: 16351, dtype: int64
内部标识号    16353
交易次数        13
交易金额       645
Name: 16352, dtype: int64
内部标识号    16354
交易次数        13
交易金额       388
Name: 16353, dtype: int64
内部标识号    16355
交易次数         9
交易金额       970
Name: 16354, dtype: int64
内部标识号    16356
交易次数         3
交易金额       168
Name: 16355, dtype: int64
内部标识号    16357
交易次数         8
交易金额       190
Name: 16356, dtype: int64
内部标识号    16358
交易次数         3
交易金额       376
Name: 16357, dtype: int64
内部标识号    16359
交易次数        14
交易金额       584
Name: 16358, dtype: int64
内部标识号    16360
交易次数         1
交易金额       723
Name: 16359, dtype: int64
内部标识号    16361
交易次数        12
交易金额       516
Name: 16360, dtype: int64
内部标识号    16362
交易次数         0
交易金额      8231
Name: 16361, dtype: int64
内部标识号    16363
交易次数         5
交易金额       287
Name: 16362, dtype: int64
内部标识号    16364
交易次数         9
交易金额       969
Name: 16363, dtype: int64
内部标识号    16365
交易次数         2
交易金额       384
Name: 16364, dtype: int64
内部标识号    16366
交易次数         2
交易金额       804
Name: 16365, dtype: int64
内部标识号    16367
交易次数        23
交易金额      5827
Name: 16366, dtype: int64
内部标识号    16368
交易次数         3
交易金额       140
Name: 16367, dtype: int64
内部标识号    16369
交易次数         8
交易金额       826
Name: 16368, dtype: int64
内部标识号    16370
交易次数        10
交易金额       460
Name: 16369, dtype: int64
内部标识号    16371
交易次数         1
交易金额      9985
Name: 16370, dtype: int64
内部标识号    16372
交易次数         7
交易金额     94463
Name: 16371, dtype: int64
内部标识号    16373
交易次数         8
交易金额       102
Name: 16372, dtype: int64
内部标识号    16374
交易次数        12
交易金额       368
Name: 16373, dtype: int64
内部标识号    16375
交易次数         6
交易金额       199
Name: 16374, dtype: int64
内部标识号    16376
交易次数         2
交易金额       957
Name: 16375, dtype: int64
内部标识号    16377
交易次数         2
交易金额       302
Name: 16376, dtype: int64
内部标识号    16378
交易次数        14
交易金额       414
Name: 16377, dtype: int64
内部标识号    16379
交易次数        15
交易金额       580
Name: 16378, dtype: int64
内部标识号    16380
交易次数         8
交易金额       171
Name: 16379, dtype: int64
内部标识号    16381
交易次数         1
交易金额       587
Name: 16380, dtype: int64
内部标识号    16382
交易次数         1
交易金额       731
Name: 16381, dtype: int64
内部标识号    16383
交易次数        10
交易金额       368
Name: 16382, dtype: int64
内部标识号    16384
交易次数        13
交易金额       825
Name: 16383, dtype: int64
内部标识号    16385
交易次数         2
交易金额       506
Name: 16384, dtype: int64
内部标识号    16386
交易次数         3
交易金额       364
Name: 16385, dtype: int64
内部标识号    16387
交易次数       280
交易金额     79162
Name: 16386, dtype: int64
内部标识号    16388
交易次数         3
交易金额       274
Name: 16387, dtype: int64
内部标识号    16389
交易次数        24
交易金额      8150
Name: 16388, dtype: int64
内部标识号    16390
交易次数         3
交易金额       465
Name: 16389, dtype: int64
内部标识号    16391
交易次数         7
交易金额       179
Name: 16390, dtype: int64
内部标识号    16392
交易次数       140
交易金额     80958
Name: 16391, dtype: int64
内部标识号    16393
交易次数        13
交易金额       685
Name: 16392, dtype: int64
内部标识号    16394
交易次数         8
交易金额     25996
Name: 16393, dtype: int64
内部标识号    16395
交易次数        15
交易金额        57
Name: 16394, dtype: int64
内部标识号    16396
交易次数         4
交易金额       177
Name: 16395, dtype: int64
内部标识号    16397
交易次数        12
交易金额       379
Name: 16396, dtype: int64
内部标识号    16398
交易次数         3
交易金额       438
Name: 16397, dtype: int64
内部标识号    16399
交易次数         0
交易金额      4334
Name: 16398, dtype: int64
内部标识号    16400
交易次数         4
交易金额       281
Name: 16399, dtype: int64
内部标识号    16401
交易次数         0
交易金额      5162
Name: 16400, dtype: int64
内部标识号    16402
交易次数         0
交易金额      1144
Name: 16401, dtype: int64
内部标识号    16403
交易次数         5
交易金额       209
Name: 16402, dtype: int64
内部标识号    16404
交易次数         1
交易金额       994
Name: 16403, dtype: int64
内部标识号    16405
交易次数         4
交易金额       252
Name: 16404, dtype: int64
内部标识号    16406
交易次数         2
交易金额       363
Name: 16405, dtype: int64
内部标识号    16407
交易次数         5
交易金额       129
Name: 16406, dtype: int64
内部标识号    16408
交易次数        10
交易金额       355
Name: 16407, dtype: int64
内部标识号    16409
交易次数        30
交易金额       815
Name: 16408, dtype: int64
内部标识号    16410
交易次数         2
交易金额       662
Name: 16409, dtype: int64
内部标识号    16411
交易次数        29
交易金额      3719
Name: 16410, dtype: int64
内部标识号    16412
交易次数         5
交易金额       181
Name: 16411, dtype: int64
内部标识号    16413
交易次数        10
交易金额       707
Name: 16412, dtype: int64
内部标识号    16414
交易次数         2
交易金额       370
Name: 16413, dtype: int64
内部标识号    16415
交易次数         1
交易金额       799
Name: 16414, dtype: int64
内部标识号    16416
交易次数         5
交易金额       168
Name: 16415, dtype: int64
内部标识号    16417
交易次数         3
交易金额       327
Name: 16416, dtype: int64
内部标识号    16418
交易次数         7
交易金额       216
Name: 16417, dtype: int64
内部标识号    16419
交易次数         6
交易金额     79111
Name: 16418, dtype: int64
内部标识号    16420
交易次数        10
交易金额       920
Name: 16419, dtype: int64
内部标识号    16421
交易次数         2
交易金额       821
Name: 16420, dtype: int64
内部标识号    16422
交易次数         2
交易金额       343
Name: 16421, dtype: int64
内部标识号    16423
交易次数        14
交易金额       923
Name: 16422, dtype: int64
内部标识号    16424
交易次数         7
交易金额       130
Name: 16423, dtype: int64
内部标识号    16425
交易次数         2
交易金额       341
Name: 16424, dtype: int64
内部标识号    16426
交易次数         3
交易金额       431
Name: 16425, dtype: int64
内部标识号    16427
交易次数         0
交易金额      5860
Name: 16426, dtype: int64
内部标识号    16428
交易次数         9
交易金额       604
Name: 16427, dtype: int64
内部标识号    16429
交易次数        23
交易金额       648
Name: 16428, dtype: int64
内部标识号    16430
交易次数         1
交易金额       837
Name: 16429, dtype: int64
内部标识号    16431
交易次数         3
交易金额       333
Name: 16430, dtype: int64
内部标识号    16432
交易次数         1
交易金额       785
Name: 16431, dtype: int64
内部标识号    16433
交易次数        15
交易金额       466
Name: 16432, dtype: int64
内部标识号    16434
交易次数         3
交易金额       389
Name: 16433, dtype: int64
内部标识号    16435
交易次数         3
交易金额       462
Name: 16434, dtype: int64
内部标识号    16436
交易次数        12
交易金额       578
Name: 16435, dtype: int64
内部标识号    16437
交易次数         1
交易金额      8263
Name: 16436, dtype: int64
内部标识号    16438
交易次数         3
交易金额       434
Name: 16437, dtype: int64
内部标识号    16439
交易次数        23
交易金额       678
Name: 16438, dtype: int64
内部标识号    16440
交易次数         3
交易金额       324
Name: 16439, dtype: int64
内部标识号    16441
交易次数         6
交易金额       113
Name: 16440, dtype: int64
内部标识号    16442
交易次数         8
交易金额       128
Name: 16441, dtype: int64
内部标识号    16443
交易次数         0
交易金额      3095
Name: 16442, dtype: int64
内部标识号    16444
交易次数         3
交易金额     11940
Name: 16443, dtype: int64
内部标识号    16445
交易次数         2
交易金额       346
Name: 16444, dtype: int64
内部标识号    16446
交易次数       263
交易金额     40870
Name: 16445, dtype: int64
内部标识号    16447
交易次数         2
交易金额       802
Name: 16446, dtype: int64
内部标识号    16448
交易次数         4
交易金额       267
Name: 16447, dtype: int64
内部标识号    16449
交易次数         1
交易金额       503
Name: 16448, dtype: int64
内部标识号    16450
交易次数        10
交易金额       306
Name: 16449, dtype: int64
内部标识号    16451
交易次数         8
交易金额       885
Name: 16450, dtype: int64
内部标识号    16452
交易次数         2
交易金额       285
Name: 16451, dtype: int64
内部标识号    16453
交易次数         7
交易金额       197
Name: 16452, dtype: int64
内部标识号    16454
交易次数        15
交易金额       656
Name: 16453, dtype: int64
内部标识号    16455
交易次数        10
交易金额       453
Name: 16454, dtype: int64
内部标识号    16456
交易次数         8
交易金额       332
Name: 16455, dtype: int64
内部标识号    16457
交易次数        21
交易金额      8252
Name: 16456, dtype: int64
内部标识号    16458
交易次数         0
交易金额      6632
Name: 16457, dtype: int64
内部标识号    16459
交易次数         4
交易金额       139
Name: 16458, dtype: int64
内部标识号    16460
交易次数         6
交易金额       239
Name: 16459, dtype: int64
内部标识号    16461
交易次数        10
交易金额       748
Name: 16460, dtype: int64
内部标识号    16462
交易次数        11
交易金额       511
Name: 16461, dtype: int64
内部标识号    16463
交易次数        11
交易金额       639
Name: 16462, dtype: int64
内部标识号    16464
交易次数         2
交易金额       163
Name: 16463, dtype: int64
内部标识号    16465
交易次数         1
交易金额       902
Name: 16464, dtype: int64
内部标识号    16466
交易次数         1
交易金额       626
Name: 16465, dtype: int64
内部标识号    16467
交易次数        18
交易金额      5414
Name: 16466, dtype: int64
内部标识号    16468
交易次数         7
交易金额       119
Name: 16467, dtype: int64
内部标识号    16469
交易次数         2
交易金额       365
Name: 16468, dtype: int64
内部标识号    16470
交易次数         1
交易金额       725
Name: 16469, dtype: int64
内部标识号    16471
交易次数         2
交易金额       568
Name: 16470, dtype: int64
内部标识号    16472
交易次数         6
交易金额       122
Name: 16471, dtype: int64
内部标识号    16473
交易次数        15
交易金额       704
Name: 16472, dtype: int64
内部标识号    16474
交易次数         8
交易金额       494
Name: 16473, dtype: int64
内部标识号    16475
交易次数        21
交易金额       752
Name: 16474, dtype: int64
内部标识号    16476
交易次数        22
交易金额      6477
Name: 16475, dtype: int64
内部标识号    16477
交易次数         9
交易金额       513
Name: 16476, dtype: int64
内部标识号    16478
交易次数         2
交易金额       448
Name: 16477, dtype: int64
内部标识号    16479
交易次数        10
交易金额       658
Name: 16478, dtype: int64
内部标识号    16480
交易次数       185
交易金额     28538
Name: 16479, dtype: int64
内部标识号    16481
交易次数         3
交易金额       295
Name: 16480, dtype: int64
内部标识号    16482
交易次数        14
交易金额       383
Name: 16481, dtype: int64
内部标识号    16483
交易次数         2
交易金额       518
Name: 16482, dtype: int64
内部标识号    16484
交易次数         5
交易金额     68384
Name: 16483, dtype: int64
内部标识号    16485
交易次数         9
交易金额       752
Name: 16484, dtype: int64
内部标识号    16486
交易次数         1
交易金额      3427
Name: 16485, dtype: int64
内部标识号    16487
交易次数         8
交易金额       220
Name: 16486, dtype: int64
内部标识号    16488
交易次数         1
交易金额      1411
Name: 16487, dtype: int64
内部标识号    16489
交易次数         7
交易金额       230
Name: 16488, dtype: int64
内部标识号    16490
交易次数         4
交易金额       177
Name: 16489, dtype: int64
内部标识号    16491
交易次数         2
交易金额       587
Name: 16490, dtype: int64
内部标识号    16492
交易次数        24
交易金额      5937
Name: 16491, dtype: int64
内部标识号    16493
交易次数        12
交易金额       872
Name: 16492, dtype: int64
内部标识号    16494
交易次数         3
交易金额       247
Name: 16493, dtype: int64
内部标识号    16495
交易次数        10
交易金额       634
Name: 16494, dtype: int64
内部标识号    16496
交易次数         6
交易金额       258
Name: 16495, dtype: int64
内部标识号    16497
交易次数        22
交易金额      9274
Name: 16496, dtype: int64
内部标识号    16498
交易次数         6
交易金额       141
Name: 16497, dtype: int64
内部标识号    16499
交易次数        26
交易金额       744
Name: 16498, dtype: int64
内部标识号    16500
交易次数        18
交易金额       871
Name: 16499, dtype: int64
内部标识号    16501
交易次数         9
交易金额       762
Name: 16500, dtype: int64
内部标识号    16502
交易次数        11
交易金额       715
Name: 16501, dtype: int64
内部标识号    16503
交易次数        23
交易金额      5475
Name: 16502, dtype: int64
内部标识号    16504
交易次数        10
交易金额       319
Name: 16503, dtype: int64
内部标识号    16505
交易次数         2
交易金额       367
Name: 16504, dtype: int64
内部标识号    16506
交易次数         3
交易金额       488
Name: 16505, dtype: int64
内部标识号    16507
交易次数        12
交易金额       996
Name: 16506, dtype: int64
内部标识号    16508
交易次数         2
交易金额       434
Name: 16507, dtype: int64
内部标识号    16509
交易次数         2
交易金额       764
Name: 16508, dtype: int64
内部标识号    16510
交易次数        13
交易金额       343
Name: 16509, dtype: int64
内部标识号    16511
交易次数         2
交易金额       566
Name: 16510, dtype: int64
内部标识号    16512
交易次数        10
交易金额       481
Name: 16511, dtype: int64
内部标识号    16513
交易次数         3
交易金额       327
Name: 16512, dtype: int64
内部标识号    16514
交易次数         3
交易金额       415
Name: 16513, dtype: int64
内部标识号    16515
交易次数         0
交易金额      3747
Name: 16514, dtype: int64
内部标识号    16516
交易次数         2
交易金额       628
Name: 16515, dtype: int64
内部标识号    16517
交易次数        15
交易金额        69
Name: 16516, dtype: int64
内部标识号    16518
交易次数        13
交易金额       319
Name: 16517, dtype: int64
内部标识号    16519
交易次数        21
交易金额       509
Name: 16518, dtype: int64
内部标识号    16520
交易次数         1
交易金额       636
Name: 16519, dtype: int64
内部标识号    16521
交易次数         9
交易金额       377
Name: 16520, dtype: int64
内部标识号    16522
交易次数        20
交易金额      6291
Name: 16521, dtype: int64
内部标识号    16523
交易次数         0
交易金额      7060
Name: 16522, dtype: int64
内部标识号    16524
交易次数         7
交易金额       109
Name: 16523, dtype: int64
内部标识号    16525
交易次数         2
交易金额       465
Name: 16524, dtype: int64
内部标识号    16526
交易次数         6
交易金额       216
Name: 16525, dtype: int64
内部标识号    16527
交易次数         3
交易金额       218
Name: 16526, dtype: int64
内部标识号    16528
交易次数         4
交易金额       204
Name: 16527, dtype: int64
内部标识号    16529
交易次数        14
交易金额       483
Name: 16528, dtype: int64
内部标识号    16530
交易次数        15
交易金额       460
Name: 16529, dtype: int64
内部标识号    16531
交易次数         6
交易金额     97284
Name: 16530, dtype: int64
内部标识号    16532
交易次数        11
交易金额       580
Name: 16531, dtype: int64
内部标识号    16533
交易次数         2
交易金额       379
Name: 16532, dtype: int64
内部标识号    16534
交易次数        10
交易金额       769
Name: 16533, dtype: int64
内部标识号    16535
交易次数        19
交易金额       854
Name: 16534, dtype: int64
内部标识号    16536
交易次数         2
交易金额       778

Name: 16713, dtype: int64
内部标识号    16715
交易次数        23
交易金额       884
Name: 16714, dtype: int64
内部标识号    16716
交易次数         9
交易金额       870
Name: 16715, dtype: int64
内部标识号    16717
交易次数         3
交易金额       356
Name: 16716, dtype: int64
内部标识号    16718
交易次数         3
交易金额       243
Name: 16717, dtype: int64
内部标识号    16719
交易次数        11
交易金额       541
Name: 16718, dtype: int64
内部标识号    16720
交易次数        12
交易金额       430
Name: 16719, dtype: int64
内部标识号    16721
交易次数         2
交易金额       366
Name: 16720, dtype: int64
内部标识号    16722
交易次数         8
交易金额       156
Name: 16721, dtype: int64
内部标识号    16723
交易次数        27
交易金额      7564
Name: 16722, dtype: int64
内部标识号    16724
交易次数       299
交易金额     30095
Name: 16723, dtype: int64
内部标识号    16725
交易次数         3
交易金额       233
Name: 16724, dtype: int64
内部标识号    16726
交易次数         7
交易金额       287
Name: 16725, dtype: int64
内部标识号    16727
交易次数         5
交易金额       259
Name: 16726, dtype: int64
内部标识号    16728
交易次数         3
交易金额       454
Name: 16727, dtype: int64
内部标识号    16729
交易次数       124
交易金额     47274
Name: 16728, dtype: int64
内部标识号    16730
交易次数         1
交易金额       946
Name: 16729, dtype: int64
内部标识号    16731
交易次数        14
交易金额       352
Name: 16730, dtype: int64
内部标识号    16732
交易次数         0
交易金额      8375
Name: 16731, dtype: int64
内部标识号    16733
交易次数       247
交易金额     31770
Name: 16732, dtype: int64
内部标识号    16734
交易次数        11
交易金额       689
Name: 16733, dtype: int64
内部标识号    16735
交易次数         3
交易金额       361
Name: 16734, dtype: int64
内部标识号    16736
交易次数        10
交易金额       318
Name: 16735, dtype: int64
内部标识号    16737
交易次数         3
交易金额       432
Name: 16736, dtype: int64
内部标识号    16738
交易次数         8
交易金额       856
Name: 16737, dtype: int64
内部标识号    16739
交易次数         1
交易金额       794
Name: 16738, dtype: int64
内部标识号    16740
交易次数         8
交易金额       801
Name: 16739, dtype: int64
内部标识号    16741
交易次数         5
交易金额       248
Name: 16740, dtype: int64
内部标识号    16742
交易次数        12
交易金额       382
Name: 16741, dtype: int64
内部标识号    16743
交易次数         6
交易金额       216
Name: 16742, dtype: int64
内部标识号    16744
交易次数        14
交易金额       338
Name: 16743, dtype: int64
内部标识号    16745
交易次数         5
交易金额       186
Name: 16744, dtype: int64
内部标识号    16746
交易次数         4
交易金额       183
Name: 16745, dtype: int64
内部标识号    16747
交易次数         4
交易金额     65700
Name: 16746, dtype: int64
内部标识号    16748
交易次数         3
交易金额       177
Name: 16747, dtype: int64
内部标识号    16749
交易次数        30
交易金额       983
Name: 16748, dtype: int64
内部标识号    16750
交易次数         5
交易金额       229
Name: 16749, dtype: int64
内部标识号    16751
交易次数         1
交易金额       593
Name: 16750, dtype: int64
内部标识号    16752
交易次数       296
交易金额     21253
Name: 16751, dtype: int64
内部标识号    16753
交易次数         2
交易金额       579
Name: 16752, dtype: int64
内部标识号    16754
交易次数       268
交易金额     68043
Name: 16753, dtype: int64
内部标识号    16755
交易次数         1
交易金额       503
Name: 16754, dtype: int64
内部标识号    16756
交易次数         8
交易金额       180
Name: 16755, dtype: int64
内部标识号    16757
交易次数         2
交易金额       658
Name: 16756, dtype: int64
内部标识号    16758
交易次数        11
交易金额       381
Name: 16757, dtype: int64
内部标识号    16759
交易次数         0
交易金额      2465
Name: 16758, dtype: int64
内部标识号    16760
交易次数         1
交易金额       819
Name: 16759, dtype: int64
内部标识号    16761
交易次数         0
交易金额      5691
Name: 16760, dtype: int64
内部标识号    16762
交易次数         1
交易金额       717
Name: 16761, dtype: int64
内部标识号    16763
交易次数         6
交易金额       209
Name: 16762, dtype: int64
内部标识号    16764
交易次数        16
交易金额      8506
Name: 16763, dtype: int64
内部标识号    16765
交易次数         3
交易金额       348
Name: 16764, dtype: int64
内部标识号    16766
交易次数         7
交易金额       203
Name: 16765, dtype: int64
内部标识号    16767
交易次数         4
交易金额       147
Name: 16766, dtype: int64
内部标识号    16768
交易次数        26
交易金额       502
Name: 16767, dtype: int64
内部标识号    16769
交易次数        14
交易金额       659
Name: 16768, dtype: int64
内部标识号    16770
交易次数        10
交易金额       618
Name: 16769, dtype: int64
内部标识号    16771
交易次数        19
交易金额      3042
Name: 16770, dtype: int64
内部标识号    16772
交易次数         2
交易金额       347
Name: 16771, dtype: int64
内部标识号    16773
交易次数        15
交易金额       396
Name: 16772, dtype: int64
内部标识号    16774
交易次数         2
交易金额       575
Name: 16773, dtype: int64
内部标识号    16775
交易次数         4
交易金额     89019
Name: 16774, dtype: int64
内部标识号    16776
交易次数         8
交易金额     81908
Name: 16775, dtype: int64
内部标识号    16777
交易次数        15
交易金额       346
Name: 16776, dtype: int64
内部标识号    16778
交易次数         5
交易金额       162
Name: 16777, dtype: int64
内部标识号    16779
交易次数         9
交易金额       630
Name: 16778, dtype: int64
内部标识号    16780
交易次数         4
交易金额       160
Name: 16779, dtype: int64
内部标识号    16781
交易次数         2
交易金额       846
Name: 16780, dtype: int64
内部标识号    16782
交易次数         0
交易金额      5181
Name: 16781, dtype: int64
内部标识号    16783
交易次数         2
交易金额       610
Name: 16782, dtype: int64
内部标识号    16784
交易次数         2
交易金额       386
Name: 16783, dtype: int64
内部标识号    16785
交易次数        10
交易金额       415
Name: 16784, dtype: int64
内部标识号    16786
交易次数        27
交易金额       913
Name: 16785, dtype: int64
内部标识号    16787
交易次数        11
交易金额       930
Name: 16786, dtype: int64
内部标识号    16788
交易次数        10
交易金额       499
Name: 16787, dtype: int64
内部标识号    16789
交易次数        19
交易金额      1823
Name: 16788, dtype: int64
内部标识号    16790
交易次数         8
交易金额       758
Name: 16789, dtype: int64
内部标识号    16791
交易次数         0
交易金额      5311
Name: 16790, dtype: int64
内部标识号    16792
交易次数        15
交易金额       492
Name: 16791, dtype: int64
内部标识号    16793
交易次数         2
交易金额       454
Name: 16792, dtype: int64
内部标识号    16794
交易次数         3
交易金额     13806
Name: 16793, dtype: int64
内部标识号    16795
交易次数         4
交易金额     77091
Name: 16794, dtype: int64
内部标识号    16796
交易次数        14
交易金额       909
Name: 16795, dtype: int64
内部标识号    16797
交易次数       121
交易金额     55986
Name: 16796, dtype: int64
内部标识号    16798
交易次数        37
交易金额     20326
Name: 16797, dtype: int64
内部标识号    16799
交易次数        16
交易金额      9213
Name: 16798, dtype: int64
内部标识号    16800
交易次数         6
交易金额       253
Name: 16799, dtype: int64
内部标识号    16801
交易次数        15
交易金额       680
Name: 16800, dtype: int64
内部标识号    16802
交易次数         6
交易金额     49266
Name: 16801, dtype: int64
内部标识号    16803
交易次数         5
交易金额       120
Name: 16802, dtype: int64
内部标识号    16804
交易次数        22
交易金额      1687
Name: 16803, dtype: int64
内部标识号    16805
交易次数         7
交易金额     43021
Name: 16804, dtype: int64
内部标识号    16806
交易次数       169
交易金额     83359
Name: 16805, dtype: int64
内部标识号    16807
交易次数         3
交易金额       304
Name: 16806, dtype: int64
内部标识号    16808
交易次数         6
交易金额       174
Name: 16807, dtype: int64
内部标识号    16809
交易次数        11
交易金额       383
Name: 16808, dtype: int64
内部标识号    16810
交易次数        13
交易金额       364
Name: 16809, dtype: int64
内部标识号    16811
交易次数        25
交易金额        28
Name: 16810, dtype: int64
内部标识号    16812
交易次数         3
交易金额       342
Name: 16811, dtype: int64
内部标识号    16813
交易次数         3
交易金额       469
Name: 16812, dtype: int64
内部标识号    16814
交易次数         3
交易金额       357
Name: 16813, dtype: int64
内部标识号    16815
交易次数        24
交易金额      9514
Name: 16814, dtype: int64
内部标识号    16816
交易次数         3
交易金额       170
Name: 16815, dtype: int64
内部标识号    16817
交易次数         0
交易金额      7845
Name: 16816, dtype: int64
内部标识号    16818
交易次数        12
交易金额       742
Name: 16817, dtype: int64
内部标识号    16819
交易次数         3
交易金额       241
Name: 16818, dtype: int64
内部标识号    16820
交易次数        19
交易金额      5068
Name: 16819, dtype: int64
内部标识号    16821
交易次数        15
交易金额       692
Name: 16820, dtype: int64
内部标识号    16822
交易次数         5
交易金额     86262
Name: 16821, dtype: int64
内部标识号    16823
交易次数         2
交易金额       493
Name: 16822, dtype: int64
内部标识号    16824
交易次数         0
交易金额      8824
Name: 16823, dtype: int64
内部标识号    16825
交易次数         2
交易金额       388
Name: 16824, dtype: int64
内部标识号    16826
交易次数        13
交易金额       494
Name: 16825, dtype: int64
内部标识号    16827
交易次数         1
交易金额       732
Name: 16826, dtype: int64
内部标识号    16828
交易次数       100
交易金额     31342
Name: 16827, dtype: int64
内部标识号    16829
交易次数         9
交易金额       310
Name: 16828, dtype: int64
内部标识号    16830
交易次数         0
交易金额      5905
Name: 16829, dtype: int64
内部标识号    16831
交易次数         0
交易金额      1087
Name: 16830, dtype: int64
内部标识号    16832
交易次数         2
交易金额       107
Name: 16831, dtype: int64
内部标识号    16833
交易次数        13
交易金额       668
Name: 16832, dtype: int64
内部标识号    16834
交易次数         2
交易金额       444
Name: 16833, dtype: int64
内部标识号    16835
交易次数         0
交易金额      8582
Name: 16834, dtype: int64
内部标识号    16836
交易次数         3
交易金额       403
Name: 16835, dtype: int64
内部标识号    16837
交易次数         5
交易金额       186
Name: 16836, dtype: int64
内部标识号    16838
交易次数         2
交易金额       607
Name: 16837, dtype: int64
内部标识号    16839
交易次数        11
交易金额       885
Name: 16838, dtype: int64
内部标识号    16840
交易次数         0
交易金额      2769
Name: 16839, dtype: int64
内部标识号    16841
交易次数        17
交易金额      4866
Name: 16840, dtype: int64
内部标识号    16842
交易次数         2
交易金额       489
Name: 16841, dtype: int64
内部标识号    16843
交易次数         0
交易金额      6180
Name: 16842, dtype: int64
内部标识号    16844
交易次数        26
交易金额       764
Name: 16843, dtype: int64
内部标识号    16845
交易次数       223
交易金额     97136
Name: 16844, dtype: int64
内部标识号    16846
交易次数        10
交易金额       813
Name: 16845, dtype: int64
内部标识号    16847
交易次数         2
交易金额       375
Name: 16846, dtype: int64
内部标识号    16848
交易次数         0
交易金额      9789
Name: 16847, dtype: int64
内部标识号    16849
交易次数        13
交易金额       724
Name: 16848, dtype: int64
内部标识号    16850
交易次数         9
交易金额       646
Name: 16849, dtype: int64
内部标识号    16851
交易次数         2
交易金额       157
Name: 16850, dtype: int64
内部标识号    16852
交易次数         8
交易金额       488
Name: 16851, dtype: int64
内部标识号    16853
交易次数        12
交易金额       717
Name: 16852, dtype: int64
内部标识号    16854
交易次数         2
交易金额       454
Name: 16853, dtype: int64
内部标识号    16855
交易次数        13
交易金额       580
Name: 16854, dtype: int64
内部标识号    16856
交易次数         3
交易金额       415
Name: 16855, dtype: int64
内部标识号    16857
交易次数         9
交易金额       893
Name: 16856, dtype: int64
内部标识号    16858
交易次数         6
交易金额       189
Name: 16857, dtype: int64
内部标识号    16859
交易次数        15
交易金额       646
Name: 16858, dtype: int64
内部标识号    16860
交易次数         9
交易金额       765
Name: 16859, dtype: int64
内部标识号    16861
交易次数        10
交易金额       663
Name: 16860, dtype: int64
内部标识号    16862
交易次数         9
交易金额       375
Name: 16861, dtype: int64
内部标识号    16863
交易次数        30
交易金额      2071
Name: 16862, dtype: int64
内部标识号    16864
交易次数         8
交易金额       592
Name: 16863, dtype: int64
内部标识号    16865
交易次数         3
交易金额       332
Name: 16864, dtype: int64
内部标识号    16866
交易次数         9
交易金额       935
Name: 16865, dtype: int64
内部标识号    16867
交易次数         1
交易金额       578
Name: 16866, dtype: int64
内部标识号    16868
交易次数         3
交易金额       417
Name: 16867, dtype: int64
内部标识号    16869
交易次数         8
交易金额       750
Name: 16868, dtype: int64
内部标识号    16870
交易次数         0
交易金额      2651
Name: 16869, dtype: int64
内部标识号    16871
交易次数         2
交易金额       690
Name: 16870, dtype: int64
内部标识号    16872
交易次数        12
交易金额       679
Name: 16871, dtype: int64
内部标识号    16873
交易次数        13
交易金额       327
Name: 16872, dtype: int64
内部标识号    16874
交易次数        23
交易金额        56
Name: 16873, dtype: int64
内部标识号    16875
交易次数         8
交易金额       170
Name: 16874, dtype: int64
内部标识号    16876
交易次数         1
交易金额      2700
Name: 16875, dtype: int64
内部标识号    16877
交易次数         2
交易金额       788
Name: 16876, dtype: int64
内部标识号    16878
交易次数         3
交易金额     85010
Name: 16877, dtype: int64
内部标识号    16879
交易次数         5
交易金额       296
Name: 16878, dtype: int64
内部标识号    16880
交易次数         2
交易金额       344
Name: 16879, dtype: int64
内部标识号    16881
交易次数         9
交易金额       492
Name: 16880, dtype: int64
内部标识号    16882
交易次数        19
交易金额      4993
Name: 16881, dtype: int64
内部标识号    16883
交易次数         5
交易金额     32347
Name: 16882, dtype: int64
内部标识号    16884
交易次数         3
交易金额     99653
Name: 16883, dtype: int64
内部标识号    16885
交易次数        13
交易金额       379
Name: 16884, dtype: int64
内部标识号    16886
交易次数         7
交易金额     65180
Name: 16885, dtype: int64
内部标识号    16887
交易次数         1
交易金额       817
Name: 16886, dtype: int64
内部标识号    16888
交易次数         8
交易金额       731
Name: 16887, dtype: int64
内部标识号    16889
交易次数         8
交易金额       349
Name: 16888, dtype: int64
内部标识号    16890
交易次数        14
交易金额       583
Name: 16889, dtype: int64
内部标识号    16891
交易次数        10
交易金额       392
Name: 16890, dtype: int64
内部标识号    16892
交易次数        29
交易金额       976
Name: 16891, dtype: int64
内部标识号    16893
交易次数         9
交易金额       712
Name: 16892, dtype: int64
内部标识号    16894
交易次数         8
交易金额       605
Name: 16893, dtype: int64
内部标识号    16895
交易次数         2
交易金额       460
Name: 16894, dtype: int64
内部标识号    16896
交易次数         2
交易金额       458
Name: 16895, dtype: int64
内部标识号    16897
交易次数         4
交易金额       151
Name: 16896, dtype: int64
内部标识号    16898
交易次数        12
交易金额       505
Name: 16897, dtype: int64
内部标识号    16899
交易次数        15
交易金额       793
Name: 16898, dtype: int64
内部标识号    16900
交易次数         0
交易金额      8169
Name: 16899, dtype: int64
内部标识号    16901
交易次数         3
交易金额       108
Name: 16900, dtype: int64
内部标识号    16902
交易次数         6
交易金额       182
Name: 16901, dtype: int64
内部标识号    16903
交易次数        15
交易金额      8559
Name: 16902, dtype: int64
内部标识号    16904
交易次数        11
交易金额       932
Name: 16903, dtype: int64
内部标识号    16905
交易次数        10
交易金额       567
Name: 16904, dtype: int64
内部标识号    16906
交易次数        15
交易金额       996
Name: 16905, dtype: int64
内部标识号    16907
交易次数        12
交易金额       313
Name: 16906, dtype: int64
内部标识号    16908
交易次数        10
交易金额       968
Name: 16907, dtype: int64
内部标识号    16909
交易次数         2
交易金额       479
Name: 16908, dtype: int64
内部标识号    16910
交易次数         3
交易金额       116
Name: 16909, dtype: int64
内部标识号    16911
交易次数         8
交易金额       134
Name: 16910, dtype: int64
内部标识号    16912
交易次数        12
交易金额       351
Name: 16911, dtype: int64
内部标识号    16913
交易次数        12
交易金额       439
Name: 16912, dtype: int64
内部标识号    16914
交易次数         1
交易金额       790
Name: 16913, dtype: int64
内部标识号    16915
交易次数         2
交易金额       431
Name: 16914, dtype: int64
内部标识号    16916
交易次数        30
交易金额        37
Name: 16915, dtype: int64
内部标识号    16917
交易次数         3
交易金额       426
Name: 16916, dtype: int64
内部标识号    16918
交易次数         5
交易金额       270
Name: 16917, dtype: int64
内部标识号    16919
交易次数         8
交易金额       661
Name: 16918, dtype: int64
内部标识号    16920
交易次数         3
交易金额       465
Name: 16919, dtype: int64
内部标识号    16921
交易次数         6
交易金额       191
Name: 16920, dtype: int64
内部标识号    16922
交易次数         2
交易金额       358
Name: 16921, dtype: int64
内部标识号    16923
交易次数        14
交易金额       381
Name: 16922, dtype: int64
内部标识号    16924
交易次数         0
交易金额      1845
Name: 16923, dtype: int64
内部标识号    16925
交易次数         1
交易金额       997
Name: 16924, dtype: int64
内部标识号    16926
交易次数         1
交易金额       676
Name: 16925, dtype: int64
内部标识号    16927
交易次数         2
交易金额       513
Name: 16926, dtype: int64
内部标识号    16928
交易次数        12
交易金额       435
Name: 16927, dtype: int64
内部标识号    16929
交易次数         1
交易金额      4704
Name: 16928, dtype: int64
内部标识号    16930
交易次数        25
交易金额       997
Name: 16929, dtype: int64
内部标识号    16931
交易次数        29
交易金额      5187
Name: 16930, dtype: int64
内部标识号    16932
交易次数         0
交易金额      9466
Name: 16931, dtype: int64
内部标识号    16933
交易次数        11
交易金额       436
Name: 16932, dtype: int64
内部标识号    16934
交易次数         2
交易金额       828
Name: 16933, dtype: int64
内部标识号    16935
交易次数        19
交易金额       990
Name: 16934, dtype: int64
内部标识号    16936
交易次数         8
交易金额       400
Name: 16935, dtype: int64
内部标识号    16937
交易次数         0
交易金额      5284
Name: 16936, dtype: int64
内部标识号    16938
交易次数         3
交易金额       437
Name: 16937, dtype: int64
内部标识号    16939
交易次数         1
交易金额       727
Name: 16938, dtype: int64
内部标识号    16940
交易次数        20
交易金额       755
Name: 16939, dtype: int64
内部标识号    16941
交易次数         8
交易金额       275
Name: 16940, dtype: int64
内部标识号    16942
交易次数         2
交易金额       310
Name: 16941, dtype: int64
内部标识号    16943
交易次数         3
交易金额       379
Name: 16942, dtype: int64
内部标识号    16944
交易次数        28
交易金额       901
Name: 16943, dtype: int64
内部标识号    16945
交易次数         3
交易金额       120
Name: 16944, dtype: int64
内部标识号    16946
交易次数        13
交易金额       489
Name: 16945, dtype: int64
内部标识号    16947
交易次数         2
交易金额       776
Name: 16946, dtype: int64
内部标识号    16948
交易次数        28
交易金额       545
Name: 16947, dtype: int64
内部标识号    16949
交易次数         8
交易金额     61915
Name: 16948, dtype: int64
内部标识号    16950
交易次数         2
交易金额       421
Name: 16949, dtype: int64
内部标识号    16951
交易次数        17
交易金额       649
Name: 16950, dtype: int64
内部标识号    16952
交易次数         5
交易金额       269
Name: 16951, dtype: int64
内部标识号    16953
交易次数         4
交易金额       197
Name: 16952, dtype: int64
内部标识号    16954
交易次数        10
交易金额       390
Name: 16953, dtype: int64
内部标识号    16955
交易次数        10
交易金额       617
Name: 16954, dtype: int64
内部标识号    16956
交易次数         7
交易金额       259
Name: 16955, dtype: int64
内部标识号    16957
交易次数        14
交易金额       730
Name: 16956, dtype: int64
内部标识号    16958
交易次数         1
交易金额       778
Name: 16957, dtype: int64
内部标识号    16959
交易次数        15
交易金额       802
Name: 16958, dtype: int64
内部标识号    16960
交易次数        11
交易金额       411
Name: 16959, dtype: int64
内部标识号    16961
交易次数         1
交易金额       830
Name: 16960, dtype: int64
内部标识号    16962
交易次数         0
交易金额      1464
Name: 16961, dtype: int64
内部标识号    16963
交易次数        13
交易金额       302
Name: 16962, dtype: int64
内部标识号    16964
交易次数        12
交易金额       480
Name: 16963, dtype: int64
内部标识号    16965
交易次数         1
交易金额       509
Name: 16964, dtype: int64
内部标识号    16966
交易次数        14
交易金额       736
Name: 16965, dtype: int64
内部标识号    16967
交易次数         3
交易金额       405
Name: 16966, dtype: int64
内部标识号    16968
交易次数         1
交易金额       677
Name: 16967, dtype: int64
内部标识号    16969
交易次数         2
交易金额       768
Name: 16968, dtype: int64
内部标识号    16970
交易次数         0
交易金额      6739
Name: 16969, dtype: int64
内部标识号    16971
交易次数        26
交易金额       959
Name: 16970, dtype: int64
内部标识号    16972
交易次数         9
交易金额       675
Name: 16971, dtype: int64
内部标识号    16973
交易次数         2
交易金额       517
Name: 16972, dtype: int64
内部标识号    16974
交易次数         8
交易金额       445
Name: 16973, dtype: int64
内部标识号    16975
交易次数        11
交易金额       338
Name: 16974, dtype: int64
内部标识号    16976
交易次数        28
交易金额       767
Name: 16975, dtype: int64
内部标识号    16977
交易次数       261
交易金额     23510
Name: 16976, dtype: int64
内部标识号    16978
交易次数         5
交易金额       185
Name: 16977, dtype: int64
内部标识号    16979
交易次数         8
交易金额       736
Name: 16978, dtype: int64
内部标识号    16980
交易次数         2
交易金额       321
Name: 16979, dtype: int64
内部标识号    16981
交易次数         4
交易金额       137
Name: 16980, dtype: int64
内部标识号    16982
交易次数        10
交易金额       517
Name: 16981, dtype: int64
内部标识号    16983
交易次数         9
交易金额       333
Name: 16982, dtype: int64
内部标识号    16984
交易次数         3
交易金额       122
Name: 16983, dtype: int64
内部标识号    16985
交易次数         0
交易金额      8722
Name: 16984, dtype: int64
内部标识号    16986
交易次数        15
交易金额       413
Name: 16985, dtype: int64
内部标识号    16987
交易次数         5
交易金额     21436
Name: 16986, dtype: int64
内部标识号    16988
交易次数        18
交易金额      1570
Name: 16987, dtype: int64
内部标识号    16989
交易次数         9
交易金额       874
Name: 16988, dtype: int64
内部标识号    16990
交易次数         2
交易金额       862
Name: 16989, dtype: int64
内部标识号    16991
交易次数        15
交易金额       698
Name: 16990, dtype: int64
内部标识号    16992
交易次数         1
交易金额       554
Name: 16991, dtype: int64
内部标识号    16993
交易次数        24
交易金额       637
Name: 16992, dtype: int64
内部标识号    16994
交易次数        14
交易金额       762
Name: 16993, dtype: int64
内部标识号    16995
交易次数         5
交易金额       280
Name: 16994, dtype: int64
内部标识号    16996

Name: 17034, dtype: int64
内部标识号    17036
交易次数       136
交易金额     59988
Name: 17035, dtype: int64
内部标识号    17037
交易次数        29
交易金额       613
Name: 17036, dtype: int64
内部标识号    17038
交易次数        15
交易金额       883
Name: 17037, dtype: int64
内部标识号    17039
交易次数         6
交易金额       224
Name: 17038, dtype: int64
内部标识号    17040
交易次数        15
交易金额       944
Name: 17039, dtype: int64
内部标识号    17041
交易次数         2
交易金额       447
Name: 17040, dtype: int64
内部标识号    17042
交易次数        26
交易金额      8786
Name: 17041, dtype: int64
内部标识号    17043
交易次数        11
交易金额       572
Name: 17042, dtype: int64
内部标识号    17044
交易次数         2
交易金额       684
Name: 17043, dtype: int64
内部标识号    17045
交易次数         3
交易金额       241
Name: 17044, dtype: int64
内部标识号    17046
交易次数         8
交易金额       152
Name: 17045, dtype: int64
内部标识号    17047
交易次数         8
交易金额       237
Name: 17046, dtype: int64
内部标识号    17048
交易次数        10
交易金额       563
Name: 17047, dtype: int64
内部标识号    17049
交易次数         2
交易金额       317
Name: 17048, dtype: int64
内部标识号    17050
交易次数        11
交易金额       425
Name: 17049, dtype: int64
内部标识号    17051
交易次数        12
交易金额       586
Name: 17050, dtype: int64
内部标识号    17052
交易次数         7
交易金额       218
Name: 17051, dtype: int64
内部标识号    17053
交易次数         2
交易金额       411
Name: 17052, dtype: int64
内部标识号    17054
交易次数        29
交易金额       599
Name: 17053, dtype: int64
内部标识号    17055
交易次数        11
交易金额       403
Name: 17054, dtype: int64
内部标识号    17056
交易次数        12
交易金额       305
Name: 17055, dtype: int64
内部标识号    17057
交易次数         0
交易金额      1237
Name: 17056, dtype: int64
内部标识号    17058
交易次数         1
交易金额       734
Name: 17057, dtype: int64
内部标识号    17059
交易次数         3
交易金额       219
Name: 17058, dtype: int64
内部标识号    17060
交易次数         1
交易金额       942
Name: 17059, dtype: int64
内部标识号    17061
交易次数         4
交易金额       267
Name: 17060, dtype: int64
内部标识号    17062
交易次数        15
交易金额       662
Name: 17061, dtype: int64
内部标识号    17063
交易次数         4
交易金额       103
Name: 17062, dtype: int64
内部标识号    17064
交易次数         2
交易金额       676
Name: 17063, dtype: int64
内部标识号    17065
交易次数         8
交易金额       400
Name: 17064, dtype: int64
内部标识号    17066
交易次数        11
交易金额       305
Name: 17065, dtype: int64
内部标识号    17067
交易次数         8
交易金额       763
Name: 17066, dtype: int64
内部标识号    17068
交易次数         3
交易金额       318
Name: 17067, dtype: int64
内部标识号    17069
交易次数         2
交易金额       382
Name: 17068, dtype: int64
内部标识号    17070
交易次数         2
交易金额       394
Name: 17069, dtype: int64
内部标识号    17071
交易次数         9
交易金额       438
Name: 17070, dtype: int64
内部标识号    17072
交易次数         3
交易金额       493
Name: 17071, dtype: int64
内部标识号    17073
交易次数        15
交易金额       910
Name: 17072, dtype: int64
内部标识号    17074
交易次数        10
交易金额       496
Name: 17073, dtype: int64
内部标识号    17075
交易次数         3
交易金额       310
Name: 17074, dtype: int64
内部标识号    17076
交易次数        26
交易金额      3845
Name: 17075, dtype: int64
内部标识号    17077
交易次数         3
交易金额       203
Name: 17076, dtype: int64
内部标识号    17078
交易次数        10
交易金额       695
Name: 17077, dtype: int64
内部标识号    17079
交易次数         0
交易金额      3789
Name: 17078, dtype: int64
内部标识号    17080
交易次数        26
交易金额      9522
Name: 17079, dtype: int64
内部标识号    17081
交易次数         7
交易金额     39363
Name: 17080, dtype: int64
内部标识号    17082
交易次数        19
交易金额      4143
Name: 17081, dtype: int64
内部标识号    17083
交易次数         3
交易金额       353
Name: 17082, dtype: int64
内部标识号    17084
交易次数         0
交易金额      2787
Name: 17083, dtype: int64
内部标识号    17085
交易次数         9
交易金额       728
Name: 17084, dtype: int64
内部标识号    17086
交易次数         6
交易金额     44547
Name: 17085, dtype: int64
内部标识号    17087
交易次数         2
交易金额       669
Name: 17086, dtype: int64
内部标识号    17088
交易次数         3
交易金额       488
Name: 17087, dtype: int64
内部标识号    17089
交易次数        14
交易金额       785
Name: 17088, dtype: int64
内部标识号    17090
交易次数        11
交易金额       361
Name: 17089, dtype: int64
内部标识号    17091
交易次数        11
交易金额       339
Name: 17090, dtype: int64
内部标识号    17092
交易次数         3
交易金额       494
Name: 17091, dtype: int64
内部标识号    17093
交易次数         2
交易金额       827
Name: 17092, dtype: int64
内部标识号    17094
交易次数        11
交易金额       430
Name: 17093, dtype: int64
内部标识号    17095
交易次数        10
交易金额       937
Name: 17094, dtype: int64
内部标识号    17096
交易次数         8
交易金额     35171
Name: 17095, dtype: int64
内部标识号    17097
交易次数        15
交易金额       870
Name: 17096, dtype: int64
内部标识号    17098
交易次数        14
交易金额       526
Name: 17097, dtype: int64
内部标识号    17099
交易次数        14
交易金额       550
Name: 17098, dtype: int64
内部标识号    17100
交易次数         8
交易金额       843
Name: 17099, dtype: int64
内部标识号    17101
交易次数         9
交易金额       424
Name: 17100, dtype: int64
内部标识号    17102
交易次数        29
交易金额      1722
Name: 17101, dtype: int64
内部标识号    17103
交易次数        25
交易金额      7092
Name: 17102, dtype: int64
内部标识号    17104
交易次数         1
交易金额      1405
Name: 17103, dtype: int64
内部标识号    17105
交易次数        27
交易金额      9488
Name: 17104, dtype: int64
内部标识号    17106
交易次数         3
交易金额       130
Name: 17105, dtype: int64
内部标识号    17107
交易次数         2
交易金额       581
Name: 17106, dtype: int64
内部标识号    17108
交易次数        13
交易金额       555
Name: 17107, dtype: int64
内部标识号    17109
交易次数        12
交易金额       571
Name: 17108, dtype: int64
内部标识号    17110
交易次数         4
交易金额       193
Name: 17109, dtype: int64
内部标识号    17111
交易次数        28
交易金额      9712
Name: 17110, dtype: int64
内部标识号    17112
交易次数        15
交易金额       449
Name: 17111, dtype: int64
内部标识号    17113
交易次数        25
交易金额      9179
Name: 17112, dtype: int64
内部标识号    17114
交易次数       150
交易金额     78935
Name: 17113, dtype: int64
内部标识号    17115
交易次数         4
交易金额       249
Name: 17114, dtype: int64
内部标识号    17116
交易次数         7
交易金额       212
Name: 17115, dtype: int64
内部标识号    17117
交易次数         2
交易金额       443
Name: 17116, dtype: int64
内部标识号    17118
交易次数        11
交易金额       605
Name: 17117, dtype: int64
内部标识号    17119
交易次数        27
交易金额       952
Name: 17118, dtype: int64
内部标识号    17120
交易次数         2
交易金额       995
Name: 17119, dtype: int64
内部标识号    17121
交易次数         3
交易金额       425
Name: 17120, dtype: int64
内部标识号    17122
交易次数         2
交易金额       469
Name: 17121, dtype: int64
内部标识号    17123
交易次数         0
交易金额      2043
Name: 17122, dtype: int64
内部标识号    17124
交易次数        12
交易金额       488
Name: 17123, dtype: int64
内部标识号    17125
交易次数         1
交易金额       899
Name: 17124, dtype: int64
内部标识号    17126
交易次数       165
交易金额     21495
Name: 17125, dtype: int64
内部标识号    17127
交易次数        14
交易金额       358
Name: 17126, dtype: int64
内部标识号    17128
交易次数        26
交易金额       583
Name: 17127, dtype: int64
内部标识号    17129
交易次数         2
交易金额       318
Name: 17128, dtype: int64
内部标识号    17130
交易次数         2
交易金额       598
Name: 17129, dtype: int64
内部标识号    17131
交易次数         4
交易金额     99546
Name: 17130, dtype: int64
内部标识号    17132
交易次数         3
交易金额       344
Name: 17131, dtype: int64
内部标识号    17133
交易次数         1
交易金额       764
Name: 17132, dtype: int64
内部标识号    17134
交易次数         3
交易金额     93168
Name: 17133, dtype: int64
内部标识号    17135
交易次数        11
交易金额       828
Name: 17134, dtype: int64
内部标识号    17136
交易次数        14
交易金额       321
Name: 17135, dtype: int64
内部标识号    17137
交易次数         3
交易金额       469
Name: 17136, dtype: int64
内部标识号    17138
交易次数         3
交易金额       401
Name: 17137, dtype: int64
内部标识号    17139
交易次数         0
交易金额      9690
Name: 17138, dtype: int64
内部标识号    17140
交易次数        11
交易金额       896
Name: 17139, dtype: int64
内部标识号    17141
交易次数         6
交易金额     78627
Name: 17140, dtype: int64
内部标识号    17142
交易次数        10
交易金额       917
Name: 17141, dtype: int64
内部标识号    17143
交易次数         0
交易金额      2273
Name: 17142, dtype: int64
内部标识号    17144
交易次数         2
交易金额       283
Name: 17143, dtype: int64
内部标识号    17145
交易次数         3
交易金额       189
Name: 17144, dtype: int64
内部标识号    17146
交易次数        27
交易金额       699
Name: 17145, dtype: int64
内部标识号    17147
交易次数         1
交易金额       822
Name: 17146, dtype: int64
内部标识号    17148
交易次数         7
交易金额       149
Name: 17147, dtype: int64
内部标识号    17149
交易次数         3
交易金额       102
Name: 17148, dtype: int64
内部标识号    17150
交易次数        19
交易金额      3554
Name: 17149, dtype: int64
内部标识号    17151
交易次数         2
交易金额       722
Name: 17150, dtype: int64
内部标识号    17152
交易次数         9
交易金额       376
Name: 17151, dtype: int64
内部标识号    17153
交易次数         6
交易金额       259
Name: 17152, dtype: int64
内部标识号    17154
交易次数         6
交易金额       141
Name: 17153, dtype: int64
内部标识号    17155
交易次数        13
交易金额       359
Name: 17154, dtype: int64
内部标识号    17156
交易次数        11
交易金额       695
Name: 17155, dtype: int64
内部标识号    17157
交易次数        22
交易金额      3972
Name: 17156, dtype: int64
内部标识号    17158
交易次数         2
交易金额       572
Name: 17157, dtype: int64
内部标识号    17159
交易次数        13
交易金额       923
Name: 17158, dtype: int64
内部标识号    17160
交易次数        13
交易金额       475
Name: 17159, dtype: int64
内部标识号    17161
交易次数         7
交易金额       169
Name: 17160, dtype: int64
内部标识号    17162
交易次数         2
交易金额       346
Name: 17161, dtype: int64
内部标识号    17163
交易次数         5
交易金额     10860
Name: 17162, dtype: int64
内部标识号    17164
交易次数       172
交易金额     17652
Name: 17163, dtype: int64
内部标识号    17165
交易次数         2
交易金额       391
Name: 17164, dtype: int64
内部标识号    17166
交易次数         8
交易金额       582
Name: 17165, dtype: int64
内部标识号    17167
交易次数         7
交易金额       246
Name: 17166, dtype: int64
内部标识号    17168
交易次数         8
交易金额       205
Name: 17167, dtype: int64
内部标识号    17169
交易次数        10
交易金额       357
Name: 17168, dtype: int64
内部标识号    17170
交易次数         8
交易金额     63612
Name: 17169, dtype: int64
内部标识号    17171
交易次数        27
交易金额      6101
Name: 17170, dtype: int64
内部标识号    17172
交易次数        28
交易金额      5194
Name: 17171, dtype: int64
内部标识号    17173
交易次数        14
交易金额       859
Name: 17172, dtype: int64
内部标识号    17174
交易次数         3
交易金额       155
Name: 17173, dtype: int64
内部标识号    17175
交易次数         1
交易金额       879
Name: 17174, dtype: int64
内部标识号    17176
交易次数         0
交易金额      1350
Name: 17175, dtype: int64
内部标识号    17177
交易次数        23
交易金额       686
Name: 17176, dtype: int64
内部标识号    17178
交易次数         3
交易金额       142
Name: 17177, dtype: int64
内部标识号    17179
交易次数         6
交易金额       111
Name: 17178, dtype: int64
内部标识号    17180
交易次数         2
交易金额       435
Name: 17179, dtype: int64
内部标识号    17181
交易次数         3
交易金额       480
Name: 17180, dtype: int64
内部标识号    17182
交易次数         8
交易金额       462
Name: 17181, dtype: int64
内部标识号    17183
交易次数        11
交易金额       466
Name: 17182, dtype: int64
内部标识号    17184
交易次数        14
交易金额       961
Name: 17183, dtype: int64
内部标识号    17185
交易次数        11
交易金额       947
Name: 17184, dtype: int64
内部标识号    17186
交易次数         6
交易金额     39050
Name: 17185, dtype: int64
内部标识号    17187
交易次数         6
交易金额       103
Name: 17186, dtype: int64
内部标识号    17188
交易次数         3
交易金额       366
Name: 17187, dtype: int64
内部标识号    17189
交易次数        15
交易金额       457
Name: 17188, dtype: int64
内部标识号    17190
交易次数        12
交易金额       981
Name: 17189, dtype: int64
内部标识号    17191
交易次数         9
交易金额       737
Name: 17190, dtype: int64
内部标识号    17192
交易次数         6
交易金额     87340
Name: 17191, dtype: int64
内部标识号    17193
交易次数        28
交易金额      1074
Name: 17192, dtype: int64
内部标识号    17194
交易次数        21
交易金额      9257
Name: 17193, dtype: int64
内部标识号    17195
交易次数        15
交易金额       549
Name: 17194, dtype: int64
内部标识号    17196
交易次数         3
交易金额       474
Name: 17195, dtype: int64
内部标识号    17197
交易次数        11
交易金额       801
Name: 17196, dtype: int64
内部标识号    17198
交易次数        11
交易金额       348
Name: 17197, dtype: int64
内部标识号    17199
交易次数       177
交易金额     44324
Name: 17198, dtype: int64
内部标识号    17200
交易次数        25
交易金额      1652
Name: 17199, dtype: int64
内部标识号    17201
交易次数         5
交易金额       221
Name: 17200, dtype: int64
内部标识号    17202
交易次数         2
交易金额       609
Name: 17201, dtype: int64
内部标识号    17203
交易次数         3
交易金额       268
Name: 17202, dtype: int64
内部标识号    17204
交易次数       190
交易金额     86700
Name: 17203, dtype: int64
内部标识号    17205
交易次数        12
交易金额       586
Name: 17204, dtype: int64
内部标识号    17206
交易次数         2
交易金额       315
Name: 17205, dtype: int64
内部标识号    17207
交易次数         8
交易金额       710
Name: 17206, dtype: int64
内部标识号    17208
交易次数         3
交易金额       485
Name: 17207, dtype: int64
内部标识号    17209
交易次数        15
交易金额       371
Name: 17208, dtype: int64
内部标识号    17210
交易次数         3
交易金额       423
Name: 17209, dtype: int64
内部标识号    17211
交易次数         8
交易金额       851
Name: 17210, dtype: int64
内部标识号    17212
交易次数         0
交易金额      2698
Name: 17211, dtype: int64
内部标识号    17213
交易次数         7
交易金额       243
Name: 17212, dtype: int64
内部标识号    17214
交易次数        10
交易金额       844
Name: 17213, dtype: int64
内部标识号    17215
交易次数         3
交易金额       130
Name: 17214, dtype: int64
内部标识号    17216
交易次数        15
交易金额      5450
Name: 17215, dtype: int64
内部标识号    17217
交易次数         5
交易金额       167
Name: 17216, dtype: int64
内部标识号    17218
交易次数        23
交易金额      7391
Name: 17217, dtype: int64
内部标识号    17219
交易次数         3
交易金额       496
Name: 17218, dtype: int64
内部标识号    17220
交易次数         3
交易金额       192
Name: 17219, dtype: int64
内部标识号    17221
交易次数        13
交易金额       438
Name: 17220, dtype: int64
内部标识号    17222
交易次数         8
交易金额       729
Name: 17221, dtype: int64
内部标识号    17223
交易次数         0
交易金额      8278
Name: 17222, dtype: int64
内部标识号    17224
交易次数         2
交易金额       944
Name: 17223, dtype: int64
内部标识号    17225
交易次数        15
交易金额       660
Name: 17224, dtype: int64
内部标识号    17226
交易次数        17
交易金额      1553
Name: 17225, dtype: int64
内部标识号    17227
交易次数        15
交易金额       767
Name: 17226, dtype: int64
内部标识号    17228
交易次数         3
交易金额       334
Name: 17227, dtype: int64
内部标识号    17229
交易次数         6
交易金额     46873
Name: 17228, dtype: int64
内部标识号    17230
交易次数        10
交易金额       372
Name: 17229, dtype: int64
内部标识号    17231
交易次数         8
交易金额     89071
Name: 17230, dtype: int64
内部标识号    17232
交易次数         2
交易金额       773
Name: 17231, dtype: int64
内部标识号    17233
交易次数        25
交易金额       891
Name: 17232, dtype: int64
内部标识号    17234
交易次数        18
交易金额      9779
Name: 17233, dtype: int64
内部标识号    17235
交易次数         4
交易金额     37985
Name: 17234, dtype: int64
内部标识号    17236
交易次数        15
交易金额       768
Name: 17235, dtype: int64
内部标识号    17237
交易次数         1
交易金额       665
Name: 17236, dtype: int64
内部标识号    17238
交易次数         7
交易金额     85808
Name: 17237, dtype: int64
内部标识号    17239
交易次数         1
交易金额      8808
Name: 17238, dtype: int64
内部标识号    17240
交易次数         6
交易金额     23847
Name: 17239, dtype: int64
内部标识号    17241
交易次数       111
交易金额     13469
Name: 17240, dtype: int64
内部标识号    17242
交易次数         9
交易金额       455
Name: 17241, dtype: int64
内部标识号    17243
交易次数         7
交易金额       270
Name: 17242, dtype: int64
内部标识号    17244
交易次数         8
交易金额       658
Name: 17243, dtype: int64
内部标识号    17245
交易次数         2
交易金额       341
Name: 17244, dtype: int64
内部标识号    17246
交易次数        14
交易金额       596
Name: 17245, dtype: int64
内部标识号    17247
交易次数        22
交易金额       516
Name: 17246, dtype: int64
内部标识号    17248
交易次数        13
交易金额       441
Name: 17247, dtype: int64
内部标识号    17249
交易次数       252
交易金额     54274
Name: 17248, dtype: int64
内部标识号    17250
交易次数        45
交易金额     16262
Name: 17249, dtype: int64
内部标识号    17251
交易次数        19
交易金额        33
Name: 17250, dtype: int64
内部标识号    17252
交易次数         1
交易金额      4212
Name: 17251, dtype: int64
内部标识号    17253
交易次数        17
交易金额       803
Name: 17252, dtype: int64
内部标识号    17254
交易次数         2
交易金额       431
Name: 17253, dtype: int64
内部标识号    17255
交易次数         3
交易金额       118
Name: 17254, dtype: int64
内部标识号    17256
交易次数        12
交易金额       400
Name: 17255, dtype: int64
内部标识号    17257
交易次数         2
交易金额       415
Name: 17256, dtype: int64
内部标识号    17258
交易次数         4
交易金额       282
Name: 17257, dtype: int64
内部标识号    17259
交易次数         1
交易金额       753
Name: 17258, dtype: int64
内部标识号    17260
交易次数        14
交易金额       320
Name: 17259, dtype: int64
内部标识号    17261
交易次数        10
交易金额       848
Name: 17260, dtype: int64
内部标识号    17262
交易次数        13
交易金额       347
Name: 17261, dtype: int64
内部标识号    17263
交易次数        10
交易金额       329
Name: 17262, dtype: int64
内部标识号    17264
交易次数         4
交易金额       132
Name: 17263, dtype: int64
内部标识号    17265
交易次数         6
交易金额       293
Name: 17264, dtype: int64
内部标识号    17266
交易次数        29
交易金额       803
Name: 17265, dtype: int64
内部标识号    17267
交易次数         2
交易金额       412
Name: 17266, dtype: int64
内部标识号    17268
交易次数        24
交易金额      9374
Name: 17267, dtype: int64
内部标识号    17269
交易次数       194
交易金额     67729
Name: 17268, dtype: int64
内部标识号    17270
交易次数        11
交易金额       859
Name: 17269, dtype: int64
内部标识号    17271
交易次数        58
交易金额     51976
Name: 17270, dtype: int64
内部标识号    17272
交易次数        12
交易金额       459
Name: 17271, dtype: int64
内部标识号    17273
交易次数         4
交易金额       128
Name: 17272, dtype: int64
内部标识号    17274
交易次数         1
交易金额       847
Name: 17273, dtype: int64
内部标识号    17275
交易次数         2
交易金额       634
Name: 17274, dtype: int64
内部标识号    17276
交易次数        12
交易金额       322
Name: 17275, dtype: int64
内部标识号    17277
交易次数         3
交易金额       238
Name: 17276, dtype: int64
内部标识号    17278
交易次数         2
交易金额       431
Name: 17277, dtype: int64
内部标识号    17279
交易次数       293
交易金额     84916
Name: 17278, dtype: int64
内部标识号    17280
交易次数         3
交易金额       251
Name: 17279, dtype: int64
内部标识号    17281
交易次数        11
交易金额       662
Name: 17280, dtype: int64
内部标识号    17282
交易次数         6
交易金额       171
Name: 17281, dtype: int64
内部标识号    17283
交易次数        15
交易金额       656
Name: 17282, dtype: int64
内部标识号    17284
交易次数         2
交易金额       373
Name: 17283, dtype: int64
内部标识号    17285
交易次数         2
交易金额       720
Name: 17284, dtype: int64
内部标识号    17286
交易次数        13
交易金额       389
Name: 17285, dtype: int64
内部标识号    17287
交易次数         1
交易金额       652
Name: 17286, dtype: int64
内部标识号    17288
交易次数         3
交易金额       376
Name: 17287, dtype: int64
内部标识号    17289
交易次数         8
交易金额       246
Name: 17288, dtype: int64
内部标识号    17290
交易次数        15
交易金额      2459
Name: 17289, dtype: int64
内部标识号    17291
交易次数         2
交易金额       148
Name: 17290, dtype: int64
内部标识号    17292
交易次数        28
交易金额      9751
Name: 17291, dtype: int64
内部标识号    17293
交易次数        14
交易金额       719
Name: 17292, dtype: int64
内部标识号    17294
交易次数         9
交易金额       827
Name: 17293, dtype: int64
内部标识号    17295
交易次数         9
交易金额       640
Name: 17294, dtype: int64
内部标识号    17296
交易次数        28
交易金额       504
Name: 17295, dtype: int64
内部标识号    17297
交易次数       178
交易金额     94842
Name: 17296, dtype: int64
内部标识号    17298
交易次数         1
交易金额       979
Name: 17297, dtype: int64
内部标识号    17299
交易次数         5
交易金额       297
Name: 17298, dtype: int64
内部标识号    17300
交易次数         3
交易金额       384
Name: 17299, dtype: int64
内部标识号    17301
交易次数        14
交易金额       438
Name: 17300, dtype: int64
内部标识号    17302
交易次数        19
交易金额       695
Name: 17301, dtype: int64
内部标识号    17303
交易次数       108
交易金额     65183
Name: 17302, dtype: int64
内部标识号    17304
交易次数         4
交易金额       249
Name: 17303, dtype: int64
内部标识号    17305
交易次数         8
交易金额       676
Name: 17304, dtype: int64
内部标识号    17306
交易次数         7
交易金额     35895
Name: 17305, dtype: int64
内部标识号    17307
交易次数         9
交易金额       332
Name: 17306, dtype: int64
内部标识号    17308
交易次数        14
交易金额       399
Name: 17307, dtype: int64
内部标识号    17309
交易次数         2
交易金额       377
Name: 17308, dtype: int64
内部标识号    17310
交易次数         2
交易金额       334
Name: 17309, dtype: int64
内部标识号    17311
交易次数        28
交易金额      9713
Name: 17310, dtype: int64
内部标识号    17312
交易次数         2
交易金额       527
Name: 17311, dtype: int64
内部标识号    17313
交易次数        14
交易金额       811
Name: 17312, dtype: int64
内部标识号    17314
交易次数         0
交易金额      8253
Name: 17313, dtype: int64
内部标识号    17315
交易次数         8
交易金额       246
Name: 17314, dtype: int64
内部标识号    17316
交易次数         3
交易金额       341
Name: 17315, dtype: int64
内部标识号    17317

Name: 17438, dtype: int64
内部标识号    17440
交易次数         8
交易金额       981
Name: 17439, dtype: int64
内部标识号    17441
交易次数       196
交易金额     94095
Name: 17440, dtype: int64
内部标识号    17442
交易次数         8
交易金额       359
Name: 17441, dtype: int64
内部标识号    17443
交易次数         9
交易金额       551
Name: 17442, dtype: int64
内部标识号    17444
交易次数         3
交易金额     27522
Name: 17443, dtype: int64
内部标识号    17445
交易次数         2
交易金额       604
Name: 17444, dtype: int64
内部标识号    17446
交易次数         2
交易金额       309
Name: 17445, dtype: int64
内部标识号    17447
交易次数        10
交易金额       916
Name: 17446, dtype: int64
内部标识号    17448
交易次数        10
交易金额       998
Name: 17447, dtype: int64
内部标识号    17449
交易次数        15
交易金额      7630
Name: 17448, dtype: int64
内部标识号    17450
交易次数        10
交易金额       314
Name: 17449, dtype: int64
内部标识号    17451
交易次数         3
交易金额       362
Name: 17450, dtype: int64
内部标识号    17452
交易次数         8
交易金额       264
Name: 17451, dtype: int64
内部标识号    17453
交易次数         3
交易金额       364
Name: 17452, dtype: int64
内部标识号    17454
交易次数         2
交易金额       903
Name: 17453, dtype: int64
内部标识号    17455
交易次数        15
交易金额      6862
Name: 17454, dtype: int64
内部标识号    17456
交易次数         1
交易金额      1095
Name: 17455, dtype: int64
内部标识号    17457
交易次数         7
交易金额       129
Name: 17456, dtype: int64
内部标识号    17458
交易次数         2
交易金额       418
Name: 17457, dtype: int64
内部标识号    17459
交易次数         1
交易金额       872
Name: 17458, dtype: int64
内部标识号    17460
交易次数        14
交易金额       300
Name: 17459, dtype: int64
内部标识号    17461
交易次数         2
交易金额       186
Name: 17460, dtype: int64
内部标识号    17462
交易次数        16
交易金额      3424
Name: 17461, dtype: int64
内部标识号    17463
交易次数         2
交易金额       403
Name: 17462, dtype: int64
内部标识号    17464
交易次数         1
交易金额      4753
Name: 17463, dtype: int64
内部标识号    17465
交易次数         5
交易金额       187
Name: 17464, dtype: int64
内部标识号    17466
交易次数         3
交易金额       294
Name: 17465, dtype: int64
内部标识号    17467
交易次数         2
交易金额       796
Name: 17466, dtype: int64
内部标识号    17468
交易次数         0
交易金额      6021
Name: 17467, dtype: int64
内部标识号    17469
交易次数         8
交易金额       215
Name: 17468, dtype: int64
内部标识号    17470
交易次数        17
交易金额      4875
Name: 17469, dtype: int64
内部标识号    17471
交易次数         2
交易金额       486
Name: 17470, dtype: int64
内部标识号    17472
交易次数         2
交易金额       375
Name: 17471, dtype: int64
内部标识号    17473
交易次数        13
交易金额       804
Name: 17472, dtype: int64
内部标识号    17474
交易次数        13
交易金额       681
Name: 17473, dtype: int64
内部标识号    17475
交易次数         4
交易金额       240
Name: 17474, dtype: int64
内部标识号    17476
交易次数         2
交易金额       221
Name: 17475, dtype: int64
内部标识号    17477
交易次数         7
交易金额       143
Name: 17476, dtype: int64
内部标识号    17478
交易次数        29
交易金额      7985
Name: 17477, dtype: int64
内部标识号    17479
交易次数        20
交易金额       928
Name: 17478, dtype: int64
内部标识号    17480
交易次数         2
交易金额       307
Name: 17479, dtype: int64
内部标识号    17481
交易次数         7
交易金额     83555
Name: 17480, dtype: int64
内部标识号    17482
交易次数        14
交易金额       654
Name: 17481, dtype: int64
内部标识号    17483
交易次数        13
交易金额       913
Name: 17482, dtype: int64
内部标识号    17484
交易次数         0
交易金额      8971
Name: 17483, dtype: int64
内部标识号    17485
交易次数        21
交易金额       600
Name: 17484, dtype: int64
内部标识号    17486
交易次数         3
交易金额       144
Name: 17485, dtype: int64
内部标识号    17487
交易次数         0
交易金额      7995
Name: 17486, dtype: int64
内部标识号    17488
交易次数         5
交易金额       227
Name: 17487, dtype: int64
内部标识号    17489
交易次数         0
交易金额      8494
Name: 17488, dtype: int64
内部标识号    17490
交易次数        12
交易金额       704
Name: 17489, dtype: int64
内部标识号    17491
交易次数         3
交易金额       122
Name: 17490, dtype: int64
内部标识号    17492
交易次数         1
交易金额      3319
Name: 17491, dtype: int64
内部标识号    17493
交易次数         9
交易金额       673
Name: 17492, dtype: int64
内部标识号    17494
交易次数        13
交易金额       672
Name: 17493, dtype: int64
内部标识号    17495
交易次数        13
交易金额       726
Name: 17494, dtype: int64
内部标识号    17496
交易次数         2
交易金额       397
Name: 17495, dtype: int64
内部标识号    17497
交易次数        12
交易金额       816
Name: 17496, dtype: int64
内部标识号    17498
交易次数         2
交易金额       383
Name: 17497, dtype: int64
内部标识号    17499
交易次数        21
交易金额        35
Name: 17498, dtype: int64
内部标识号    17500
交易次数         2
交易金额       631
Name: 17499, dtype: int64
内部标识号    17501
交易次数         4
交易金额       228
Name: 17500, dtype: int64
内部标识号    17502
交易次数         8
交易金额       281
Name: 17501, dtype: int64
内部标识号    17503
交易次数         3
交易金额       357
Name: 17502, dtype: int64
内部标识号    17504
交易次数         0
交易金额      8289
Name: 17503, dtype: int64
内部标识号    17505
交易次数        16
交易金额      9927
Name: 17504, dtype: int64
内部标识号    17506
交易次数         8
交易金额       945
Name: 17505, dtype: int64
内部标识号    17507
交易次数         0
交易金额      9293
Name: 17506, dtype: int64
内部标识号    17508
交易次数        88
交易金额     62059
Name: 17507, dtype: int64
内部标识号    17509
交易次数         2
交易金额       290
Name: 17508, dtype: int64
内部标识号    17510
交易次数        14
交易金额       348
Name: 17509, dtype: int64
内部标识号    17511
交易次数        12
交易金额       409
Name: 17510, dtype: int64
内部标识号    17512
交易次数         5
交易金额       291
Name: 17511, dtype: int64
内部标识号    17513
交易次数         8
交易金额       258
Name: 17512, dtype: int64
内部标识号    17514
交易次数        12
交易金额       353
Name: 17513, dtype: int64
内部标识号    17515
交易次数         3
交易金额       423
Name: 17514, dtype: int64
内部标识号    17516
交易次数        11
交易金额       313
Name: 17515, dtype: int64
内部标识号    17517
交易次数         0
交易金额      5934
Name: 17516, dtype: int64
内部标识号    17518
交易次数        15
交易金额       316
Name: 17517, dtype: int64
内部标识号    17519
交易次数        20
交易金额        89
Name: 17518, dtype: int64
内部标识号    17520
交易次数         2
交易金额       792
Name: 17519, dtype: int64
内部标识号    17521
交易次数         2
交易金额       723
Name: 17520, dtype: int64
内部标识号    17522
交易次数         3
交易金额       420
Name: 17521, dtype: int64
内部标识号    17523
交易次数         9
交易金额       401
Name: 17522, dtype: int64
内部标识号    17524
交易次数         2
交易金额       863
Name: 17523, dtype: int64
内部标识号    17525
交易次数         0
交易金额      5751
Name: 17524, dtype: int64
内部标识号    17526
交易次数         7
交易金额     49592
Name: 17525, dtype: int64
内部标识号    17527
交易次数        10
交易金额       745
Name: 17526, dtype: int64
内部标识号    17528
交易次数         7
交易金额       250
Name: 17527, dtype: int64
内部标识号    17529
交易次数         2
交易金额       179
Name: 17528, dtype: int64
内部标识号    17530
交易次数        15
交易金额       496
Name: 17529, dtype: int64
内部标识号    17531
交易次数         8
交易金额       267
Name: 17530, dtype: int64
内部标识号    17532
交易次数        58
交易金额     66524
Name: 17531, dtype: int64
内部标识号    17533
交易次数         6
交易金额       244
Name: 17532, dtype: int64
内部标识号    17534
交易次数         2
交易金额       303
Name: 17533, dtype: int64
内部标识号    17535
交易次数        13
交易金额       434
Name: 17534, dtype: int64
内部标识号    17536
交易次数         7
交易金额       251
Name: 17535, dtype: int64
内部标识号    17537
交易次数         3
交易金额       176
Name: 17536, dtype: int64
内部标识号    17538
交易次数       135
交易金额     99494
Name: 17537, dtype: int64
内部标识号    17539
交易次数         6
交易金额     64253
Name: 17538, dtype: int64
内部标识号    17540
交易次数       236
交易金额     81195
Name: 17539, dtype: int64
内部标识号    17541
交易次数         2
交易金额       843
Name: 17540, dtype: int64
内部标识号    17542
交易次数        23
交易金额      8644
Name: 17541, dtype: int64
内部标识号    17543
交易次数         7
交易金额       218
Name: 17542, dtype: int64
内部标识号    17544
交易次数         8
交易金额       322
Name: 17543, dtype: int64
内部标识号    17545
交易次数         5
交易金额       136
Name: 17544, dtype: int64
内部标识号    17546
交易次数         2
交易金额       314
Name: 17545, dtype: int64
内部标识号    17547
交易次数         2
交易金额       301
Name: 17546, dtype: int64
内部标识号    17548
交易次数         6
交易金额     48893
Name: 17547, dtype: int64
内部标识号    17549
交易次数         8
交易金额       148
Name: 17548, dtype: int64
内部标识号    17550
交易次数        28
交易金额      6066
Name: 17549, dtype: int64
内部标识号    17551
交易次数         8
交易金额       939
Name: 17550, dtype: int64
内部标识号    17552
交易次数        23
交易金额      9871
Name: 17551, dtype: int64
内部标识号    17553
交易次数         6
交易金额     10537
Name: 17552, dtype: int64
内部标识号    17554
交易次数        12
交易金额       337
Name: 17553, dtype: int64
内部标识号    17555
交易次数        15
交易金额       514
Name: 17554, dtype: int64
内部标识号    17556
交易次数         0
交易金额      2951
Name: 17555, dtype: int64
内部标识号    17557
交易次数         6
交易金额       287
Name: 17556, dtype: int64
内部标识号    17558
交易次数         8
交易金额       574
Name: 17557, dtype: int64
内部标识号    17559
交易次数         3
交易金额       281
Name: 17558, dtype: int64
内部标识号    17560
交易次数         5
交易金额       300
Name: 17559, dtype: int64
内部标识号    17561
交易次数         0
交易金额      2130
Name: 17560, dtype: int64
内部标识号    17562
交易次数        11
交易金额       500
Name: 17561, dtype: int64
内部标识号    17563
交易次数         1
交易金额       521
Name: 17562, dtype: int64
内部标识号    17564
交易次数        10
交易金额       622
Name: 17563, dtype: int64
内部标识号    17565
交易次数         6
交易金额     33714
Name: 17564, dtype: int64
内部标识号    17566
交易次数         2
交易金额       536
Name: 17565, dtype: int64
内部标识号    17567
交易次数         6
交易金额       244
Name: 17566, dtype: int64
内部标识号    17568
交易次数        11
交易金额       686
Name: 17567, dtype: int64
内部标识号    17569
交易次数         1
交易金额       592
Name: 17568, dtype: int64
内部标识号    17570
交易次数         8
交易金额       815
Name: 17569, dtype: int64
内部标识号    17571
交易次数         6
交易金额       163
Name: 17570, dtype: int64
内部标识号    17572
交易次数        15
交易金额       644
Name: 17571, dtype: int64
内部标识号    17573
交易次数        13
交易金额       474
Name: 17572, dtype: int64
内部标识号    17574
交易次数         8
交易金额       286
Name: 17573, dtype: int64
内部标识号    17575
交易次数         0
交易金额      3553
Name: 17574, dtype: int64
内部标识号    17576
交易次数        11
交易金额       395
Name: 17575, dtype: int64
内部标识号    17577
交易次数         3
交易金额       385
Name: 17576, dtype: int64
内部标识号    17578
交易次数        10
交易金额       945
Name: 17577, dtype: int64
内部标识号    17579
交易次数        15
交易金额       955
Name: 17578, dtype: int64
内部标识号    17580
交易次数        27
交易金额       918
Name: 17579, dtype: int64
内部标识号    17581
交易次数        28
交易金额      4793
Name: 17580, dtype: int64
内部标识号    17582
交易次数         3
交易金额     49737
Name: 17581, dtype: int64
内部标识号    17583
交易次数        22
交易金额       856
Name: 17582, dtype: int64
内部标识号    17584
交易次数        12
交易金额       696
Name: 17583, dtype: int64
内部标识号    17585
交易次数        23
交易金额       775
Name: 17584, dtype: int64
内部标识号    17586
交易次数        15
交易金额       626
Name: 17585, dtype: int64
内部标识号    17587
交易次数         3
交易金额       384
Name: 17586, dtype: int64
内部标识号    17588
交易次数        15
交易金额       316
Name: 17587, dtype: int64
内部标识号    17589
交易次数         1
交易金额      1033
Name: 17588, dtype: int64
内部标识号    17590
交易次数        14
交易金额       748
Name: 17589, dtype: int64
内部标识号    17591
交易次数        27
交易金额      3226
Name: 17590, dtype: int64
内部标识号    17592
交易次数        10
交易金额       930
Name: 17591, dtype: int64
内部标识号    17593
交易次数         3
交易金额       236
Name: 17592, dtype: int64
内部标识号    17594
交易次数        15
交易金额       897
Name: 17593, dtype: int64
内部标识号    17595
交易次数         5
交易金额     66076
Name: 17594, dtype: int64
内部标识号    17596
交易次数        14
交易金额       555
Name: 17595, dtype: int64
内部标识号    17597
交易次数        14
交易金额       722
Name: 17596, dtype: int64
内部标识号    17598
交易次数         1
交易金额      4053
Name: 17597, dtype: int64
内部标识号    17599
交易次数        10
交易金额       788
Name: 17598, dtype: int64
内部标识号    17600
交易次数         1
交易金额       773
Name: 17599, dtype: int64
内部标识号    17601
交易次数         4
交易金额       299
Name: 17600, dtype: int64
内部标识号    17602
交易次数         2
交易金额       380
Name: 17601, dtype: int64
内部标识号    17603
交易次数        12
交易金额       449
Name: 17602, dtype: int64
内部标识号    17604
交易次数       173
交易金额     49651
Name: 17603, dtype: int64
内部标识号    17605
交易次数         8
交易金额       273
Name: 17604, dtype: int64
内部标识号    17606
交易次数        22
交易金额      8376
Name: 17605, dtype: int64
内部标识号    17607
交易次数         2
交易金额       477
Name: 17606, dtype: int64
内部标识号    17608
交易次数         3
交易金额       408
Name: 17607, dtype: int64
内部标识号    17609
交易次数         5
交易金额       168
Name: 17608, dtype: int64
内部标识号    17610
交易次数         5
交易金额       242
Name: 17609, dtype: int64
内部标识号    17611
交易次数         2
交易金额       453
Name: 17610, dtype: int64
内部标识号    17612
交易次数        26
交易金额      4167
Name: 17611, dtype: int64
内部标识号    17613
交易次数        14
交易金额       428
Name: 17612, dtype: int64
内部标识号    17614
交易次数        15
交易金额       606
Name: 17613, dtype: int64
内部标识号    17615
交易次数         2
交易金额       902
Name: 17614, dtype: int64
内部标识号    17616
交易次数        15
交易金额       553
Name: 17615, dtype: int64
内部标识号    17617
交易次数        10
交易金额       406
Name: 17616, dtype: int64
内部标识号    17618
交易次数         2
交易金额       361
Name: 17617, dtype: int64
内部标识号    17619
交易次数         2
交易金额       611
Name: 17618, dtype: int64
内部标识号    17620
交易次数         0
交易金额      3850
Name: 17619, dtype: int64
内部标识号    17621
交易次数         3
交易金额       130
Name: 17620, dtype: int64
内部标识号    17622
交易次数        14
交易金额       763
Name: 17621, dtype: int64
内部标识号    17623
交易次数         2
交易金额       676
Name: 17622, dtype: int64
内部标识号    17624
交易次数         3
交易金额       330
Name: 17623, dtype: int64
内部标识号    17625
交易次数         7
交易金额     16034
Name: 17624, dtype: int64
内部标识号    17626
交易次数        20
交易金额      4814
Name: 17625, dtype: int64
内部标识号    17627
交易次数        11
交易金额       674
Name: 17626, dtype: int64
内部标识号    17628
交易次数        10
交易金额       803
Name: 17627, dtype: int64
内部标识号    17629
交易次数         0
交易金额      8186
Name: 17628, dtype: int64
内部标识号    17630
交易次数        10
交易金额       803
Name: 17629, dtype: int64
内部标识号    17631
交易次数         5
交易金额       145
Name: 17630, dtype: int64
内部标识号    17632
交易次数         3
交易金额       444
Name: 17631, dtype: int64
内部标识号    17633
交易次数         1
交易金额       961
Name: 17632, dtype: int64
内部标识号    17634
交易次数        12
交易金额       954
Name: 17633, dtype: int64
内部标识号    17635
交易次数        10
交易金额       396
Name: 17634, dtype: int64
内部标识号    17636
交易次数        11
交易金额       321
Name: 17635, dtype: int64
内部标识号    17637
交易次数         9
交易金额       327
Name: 17636, dtype: int64
内部标识号    17638
交易次数         2
交易金额       459
Name: 17637, dtype: int64
内部标识号    17639
交易次数         8
交易金额       199
Name: 17638, dtype: int64
内部标识号    17640
交易次数        10
交易金额       863
Name: 17639, dtype: int64
内部标识号    17641
交易次数         3
交易金额       450
Name: 17640, dtype: int64
内部标识号    17642
交易次数        11
交易金额       538
Name: 17641, dtype: int64
内部标识号    17643
交易次数         0
交易金额      1742
Name: 17642, dtype: int64
内部标识号    17644
交易次数        13
交易金额       444
Name: 17643, dtype: int64
内部标识号    17645
交易次数         7
交易金额       275
Name: 17644, dtype: int64
内部标识号    17646
交易次数         9
交易金额       864
Name: 17645, dtype: int64
内部标识号    17647
交易次数         3
交易金额       335
Name: 17646, dtype: int64
内部标识号    17648
交易次数         0
交易金额      9857
Name: 17647, dtype: int64
内部标识号    17649
交易次数         1
交易金额      8248
Name: 17648, dtype: int64
内部标识号    17650
交易次数         3
交易金额       495
Name: 17649, dtype: int64
内部标识号    17651
交易次数         7
交易金额       277
Name: 17650, dtype: int64
内部标识号    17652
交易次数         0
交易金额      4041
Name: 17651, dtype: int64
内部标识号    17653
交易次数        19
交易金额       981
Name: 17652, dtype: int64
内部标识号    17654
交易次数         6
交易金额       175
Name: 17653, dtype: int64
内部标识号    17655
交易次数        15
交易金额       310
Name: 17654, dtype: int64
内部标识号    17656
交易次数         3
交易金额       221
Name: 17655, dtype: int64
内部标识号    17657
交易次数       142
交易金额     47732
Name: 17656, dtype: int64
内部标识号    17658
交易次数         0
交易金额      2685
Name: 17657, dtype: int64
内部标识号    17659
交易次数         3
交易金额       364
Name: 17658, dtype: int64
内部标识号    17660
交易次数         8
交易金额     97147
Name: 17659, dtype: int64
内部标识号    17661
交易次数         5
交易金额       225
Name: 17660, dtype: int64
内部标识号    17662
交易次数         3
交易金额       241
Name: 17661, dtype: int64
内部标识号    17663
交易次数         3
交易金额       484
Name: 17662, dtype: int64
内部标识号    17664
交易次数        11
交易金额       795
Name: 17663, dtype: int64
内部标识号    17665
交易次数         1
交易金额      8952
Name: 17664, dtype: int64
内部标识号    17666
交易次数         2
交易金额       477
Name: 17665, dtype: int64
内部标识号    17667
交易次数        20
交易金额      2196
Name: 17666, dtype: int64
内部标识号    17668
交易次数        13
交易金额       411
Name: 17667, dtype: int64
内部标识号    17669
交易次数        13
交易金额       424
Name: 17668, dtype: int64
内部标识号    17670
交易次数        13
交易金额       595
Name: 17669, dtype: int64
内部标识号    17671
交易次数         1
交易金额       575
Name: 17670, dtype: int64
内部标识号    17672
交易次数         2
交易金额       823
Name: 17671, dtype: int64
内部标识号    17673
交易次数         5
交易金额       160
Name: 17672, dtype: int64
内部标识号    17674
交易次数        89
交易金额     49060
Name: 17673, dtype: int64
内部标识号    17675
交易次数        11
交易金额       328
Name: 17674, dtype: int64
内部标识号    17676
交易次数        13
交易金额       449
Name: 17675, dtype: int64
内部标识号    17677
交易次数         8
交易金额       392
Name: 17676, dtype: int64
内部标识号    17678
交易次数         1
交易金额       568
Name: 17677, dtype: int64
内部标识号    17679
交易次数         0
交易金额      5082
Name: 17678, dtype: int64
内部标识号    17680
交易次数         2
交易金额       446
Name: 17679, dtype: int64
内部标识号    17681
交易次数         9
交易金额       642
Name: 17680, dtype: int64
内部标识号    17682
交易次数         3
交易金额       188
Name: 17681, dtype: int64
内部标识号    17683
交易次数         2
交易金额       334
Name: 17682, dtype: int64
内部标识号    17684
交易次数         7
交易金额       256
Name: 17683, dtype: int64
内部标识号    17685
交易次数         3
交易金额       449
Name: 17684, dtype: int64
内部标识号    17686
交易次数         2
交易金额       907
Name: 17685, dtype: int64
内部标识号    17687
交易次数        14
交易金额       761
Name: 17686, dtype: int64
内部标识号    17688
交易次数         3
交易金额       350
Name: 17687, dtype: int64
内部标识号    17689
交易次数         3
交易金额       323
Name: 17688, dtype: int64
内部标识号    17690
交易次数         2
交易金额       340
Name: 17689, dtype: int64
内部标识号    17691
交易次数         8
交易金额       204
Name: 17690, dtype: int64
内部标识号    17692
交易次数        26
交易金额       604
Name: 17691, dtype: int64
内部标识号    17693
交易次数        28
交易金额      3397
Name: 17692, dtype: int64
内部标识号    17694
交易次数        14
交易金额       481
Name: 17693, dtype: int64
内部标识号    17695
交易次数         3
交易金额       340
Name: 17694, dtype: int64
内部标识号    17696
交易次数        15
交易金额       429
Name: 17695, dtype: int64
内部标识号    17697
交易次数         2
交易金额       389
Name: 17696, dtype: int64
内部标识号    17698
交易次数         2
交易金额       527
Name: 17697, dtype: int64
内部标识号    17699
交易次数         2
交易金额       440
Name: 17698, dtype: int64
内部标识号    17700
交易次数         8
交易金额       493
Name: 17699, dtype: int64
内部标识号    17701
交易次数         2
交易金额       365
Name: 17700, dtype: int64
内部标识号    17702
交易次数        29
交易金额      5275
Name: 17701, dtype: int64
内部标识号    17703
交易次数         6
交易金额       210
Name: 17702, dtype: int64
内部标识号    17704
交易次数         3
交易金额       264
Name: 17703, dtype: int64
内部标识号    17705
交易次数         2
交易金额       840
Name: 17704, dtype: int64
内部标识号    17706
交易次数        14
交易金额       315
Name: 17705, dtype: int64
内部标识号    17707
交易次数        11
交易金额       840
Name: 17706, dtype: int64
内部标识号    17708
交易次数         7
交易金额     90226
Name: 17707, dtype: int64
内部标识号    17709
交易次数         2
交易金额       331
Name: 17708, dtype: int64
内部标识号    17710
交易次数         2
交易金额       132
Name: 17709, dtype: int64
内部标识号    17711
交易次数         2
交易金额       894
Name: 17710, dtype: int64
内部标识号    17712
交易次数         4
交易金额       276
Name: 17711, dtype: int64
内部标识号    17713
交易次数         1
交易金额      7663
Name: 17712, dtype: int64
内部标识号    17714
交易次数         3
交易金额     74322
Name: 17713, dtype: int64
内部标识号    17715
交易次数        20
交易金额        70
Name: 17714, dtype: int64
内部标识号    17716
交易次数         3
交易金额       487
Name: 17715, dtype: int64
内部标识号    17717
交易次数         8
交易金额       422
Name: 17716, dtype: int64
内部标识号    17718
交易次数         4
交易金额       238
Name: 17717, dtype: int64
内部标识号    17719
交易次数         1
交易金额      8342
Name: 17718, dtype: int64
内部标识号    17720
交易次数         8
交易金额       834
Name: 17719, dtype: int64
内部标识号    17721

内部标识号    17753
交易次数         2
交易金额       348
Name: 17752, dtype: int64
内部标识号    17754
交易次数         0
交易金额      1434
Name: 17753, dtype: int64
内部标识号    17755
交易次数         3
交易金额       441
Name: 17754, dtype: int64
内部标识号    17756
交易次数         2
交易金额       787
Name: 17755, dtype: int64
内部标识号    17757
交易次数         2
交易金额       396
Name: 17756, dtype: int64
内部标识号    17758
交易次数         3
交易金额       145
Name: 17757, dtype: int64
内部标识号    17759
交易次数         5
交易金额       171
Name: 17758, dtype: int64
内部标识号    17760
交易次数        10
交易金额       768
Name: 17759, dtype: int64
内部标识号    17761
交易次数         5
交易金额       215
Name: 17760, dtype: int64
内部标识号    17762
交易次数        22
交易金额       676
Name: 17761, dtype: int64
内部标识号    17763
交易次数         3
交易金额       254
Name: 17762, dtype: int64
内部标识号    17764
交易次数         3
交易金额       390
Name: 17763, dtype: int64
内部标识号    17765
交易次数         3
交易金额       155
Name: 17764, dtype: int64
内部标识号    17766
交易次数         3
交易金额       370
Name: 17765, dtype: int64
内部标识号    17767
交易次数         0
交易金额      7594
Name: 17766, dtype: int64
内部标识号    17768
交易次数         2
交易金额       666
Name: 17767, dtype: int64
内部标识号    17769
交易次数        21
交易金额        47
Name: 17768, dtype: int64
内部标识号    17770
交易次数        24
交易金额      8139
Name: 17769, dtype: int64
内部标识号    17771
交易次数        12
交易金额       477
Name: 17770, dtype: int64
内部标识号    17772
交易次数         2
交易金额       368
Name: 17771, dtype: int64
内部标识号    17773
交易次数         1
交易金额       755
Name: 17772, dtype: int64
内部标识号    17774
交易次数         0
交易金额      5244
Name: 17773, dtype: int64
内部标识号    17775
交易次数         2
交易金额       510
Name: 17774, dtype: int64
内部标识号    17776
交易次数         5
交易金额       155
Name: 17775, dtype: int64
内部标识号    17777
交易次数        24
交易金额      6855
Name: 17776, dtype: int64
内部标识号    17778
交易次数         4
交易金额       169
Name: 17777, dtype: int64
内部标识号    17779
交易次数         9
交易金额       337
Name: 17778, dtype: int64
内部标识号    17780
交易次数         3
交易金额       447
Name: 17779, dtype: int64
内部标识号    17781
交易次数        27
交易金额      4712
Name: 17780, dtype: int64
内部标识号    17782
交易次数        11
交易金额       614
Name: 17781, dtype: int64
内部标识号    17783
交易次数        13
交易金额       319
Name: 17782, dtype: int64
内部标识号    17784
交易次数         8
交易金额       485
Name: 17783, dtype: int64
内部标识号    17785
交易次数         7
交易金额       251
Name: 17784, dtype: int64
内部标识号    17786
交易次数        15
交易金额       593
Name: 17785, dtype: int64
内部标识号    17787
交易次数         3
交易金额     12638
Name: 17786, dtype: int64
内部标识号    17788
交易次数        25
交易金额        22
Name: 17787, dtype: int64
内部标识号    17789
交易次数        11
交易金额       316
Name: 17788, dtype: int64
内部标识号    17790
交易次数        18
交易金额       963
Name: 17789, dtype: int64
内部标识号    17791
交易次数       187
交易金额     74712
Name: 17790, dtype: int64
内部标识号    17792
交易次数         2
交易金额       907
Name: 17791, dtype: int64
内部标识号    17793
交易次数         1
交易金额       573
Name: 17792, dtype: int64
内部标识号    17794
交易次数         2
交易金额       603
Name: 17793, dtype: int64
内部标识号    17795
交易次数         5
交易金额     72351
Name: 17794, dtype: int64
内部标识号    17796
交易次数         0
交易金额      7066
Name: 17795, dtype: int64
内部标识号    17797
交易次数         5
交易金额       239
Name: 17796, dtype: int64
内部标识号    17798
交易次数        12
交易金额       590
Name: 17797, dtype: int64
内部标识号    17799
交易次数         8
交易金额       456
Name: 17798, dtype: int64
内部标识号    17800
交易次数         0
交易金额      6230
Name: 17799, dtype: int64
内部标识号    17801
交易次数        12
交易金额       375
Name: 17800, dtype: int64
内部标识号    17802
交易次数         6
交易金额       221
Name: 17801, dtype: int64
内部标识号    17803
交易次数        11
交易金额       950
Name: 17802, dtype: int64
内部标识号    17804
交易次数        13
交易金额       479
Name: 17803, dtype: int64
内部标识号    17805
交易次数         1
交易金额       853
Name: 17804, dtype: int64
内部标识号    17806
交易次数         3
交易金额       264
Name: 17805, dtype: int64
内部标识号    17807
交易次数         7
交易金额       272
Name: 17806, dtype: int64
内部标识号    17808
交易次数         0
交易金额      3790
Name: 17807, dtype: int64
内部标识号    17809
交易次数        28
交易金额        59
Name: 17808, dtype: int64
内部标识号    17810
交易次数         7
交易金额       171
Name: 17809, dtype: int64
内部标识号    17811
交易次数         6
交易金额       263
Name: 17810, dtype: int64
内部标识号    17812
交易次数        15
交易金额       534
Name: 17811, dtype: int64
内部标识号    17813
交易次数         0
交易金额      4787
Name: 17812, dtype: int64
内部标识号    17814
交易次数         2
交易金额       756
Name: 17813, dtype: int64
内部标识号    17815
交易次数        12
交易金额       490
Name: 17814, dtype: int64
内部标识号    17816
交易次数        11
交易金额       464
Name: 17815, dtype: int64
内部标识号    17817
交易次数        13
交易金额       740
Name: 17816, dtype: int64
内部标识号    17818
交易次数        10
交易金额       419
Name: 17817, dtype: int64
内部标识号    17819
交易次数         2
交易金额       462
Name: 17818, dtype: int64
内部标识号    17820
交易次数         7
交易金额       169
Name: 17819, dtype: int64
内部标识号    17821
交易次数         1
交易金额      6632
Name: 17820, dtype: int64
内部标识号    17822
交易次数         2
交易金额       996
Name: 17821, dtype: int64
内部标识号    17823
交易次数        10
交易金额       464
Name: 17822, dtype: int64
内部标识号    17824
交易次数         8
交易金额       283
Name: 17823, dtype: int64
内部标识号    17825
交易次数        15
交易金额       450
Name: 17824, dtype: int64
内部标识号    17826
交易次数        26
交易金额      2309
Name: 17825, dtype: int64
内部标识号    17827
交易次数        84
交易金额     60856
Name: 17826, dtype: int64
内部标识号    17828
交易次数         2
交易金额       978
Name: 17827, dtype: int64
内部标识号    17829
交易次数         9
交易金额       399
Name: 17828, dtype: int64
内部标识号    17830
交易次数        15
交易金额       324
Name: 17829, dtype: int64
内部标识号    17831
交易次数         1
交易金额       808
Name: 17830, dtype: int64
内部标识号    17832
交易次数         9
交易金额       343
Name: 17831, dtype: int64
内部标识号    17833
交易次数         4
交易金额     87803
Name: 17832, dtype: int64
内部标识号    17834
交易次数        15
交易金额      3171
Name: 17833, dtype: int64
内部标识号    17835
交易次数         2
交易金额       132
Name: 17834, dtype: int64
内部标识号    17836
交易次数         4
交易金额       252
Name: 17835, dtype: int64
内部标识号    17837
交易次数         7
交易金额       136
Name: 17836, dtype: int64
内部标识号    17838
交易次数         6
交易金额       150
Name: 17837, dtype: int64
内部标识号    17839
交易次数        12
交易金额       336
Name: 17838, dtype: int64
内部标识号    17840
交易次数         2
交易金额       458
Name: 17839, dtype: int64
内部标识号    17841
交易次数         6
交易金额       295
Name: 17840, dtype: int64
内部标识号    17842
交易次数         6
交易金额       164
Name: 17841, dtype: int64
内部标识号    17843
交易次数         9
交易金额       691
Name: 17842, dtype: int64
内部标识号    17844
交易次数        15
交易金额       695
Name: 17843, dtype: int64
内部标识号    17845
交易次数         1
交易金额       818
Name: 17844, dtype: int64
内部标识号    17846
交易次数        14
交易金额       885
Name: 17845, dtype: int64
内部标识号    17847
交易次数        19
交易金额       518
Name: 17846, dtype: int64
内部标识号    17848
交易次数        24
交易金额      7964
Name: 17847, dtype: int64
内部标识号    17849
交易次数         2
交易金额       658
Name: 17848, dtype: int64
内部标识号    17850
交易次数        14
交易金额       313
Name: 17849, dtype: int64
内部标识号    17851
交易次数         8
交易金额       440
Name: 17850, dtype: int64
内部标识号    17852
交易次数        15
交易金额      2594
Name: 17851, dtype: int64
内部标识号    17853
交易次数         5
交易金额     23776
Name: 17852, dtype: int64
内部标识号    17854
交易次数         9
交易金额       592
Name: 17853, dtype: int64
内部标识号    17855
交易次数         8
交易金额       436
Name: 17854, dtype: int64
内部标识号    17856
交易次数         3
交易金额       118
Name: 17855, dtype: int64
内部标识号    17857
交易次数         3
交易金额       326
Name: 17856, dtype: int64
内部标识号    17858
交易次数         2
交易金额       481
Name: 17857, dtype: int64
内部标识号    17859
交易次数        11
交易金额       362
Name: 17858, dtype: int64
内部标识号    17860
交易次数        27
交易金额        56
Name: 17859, dtype: int64
内部标识号    17861
交易次数         3
交易金额       419
Name: 17860, dtype: int64
内部标识号    17862
交易次数         0
交易金额      4008
Name: 17861, dtype: int64
内部标识号    17863
交易次数        10
交易金额       641
Name: 17862, dtype: int64
内部标识号    17864
交易次数        13
交易金额       923
Name: 17863, dtype: int64
内部标识号    17865
交易次数        15
交易金额       973
Name: 17864, dtype: int64
内部标识号    17866
交易次数         8
交易金额       217
Name: 17865, dtype: int64
内部标识号    17867
交易次数        14
交易金额       838
Name: 17866, dtype: int64
内部标识号    17868
交易次数        27
交易金额       666
Name: 17867, dtype: int64
内部标识号    17869
交易次数         8
交易金额     35896
Name: 17868, dtype: int64
内部标识号    17870
交易次数        15
交易金额       427
Name: 17869, dtype: int64
内部标识号    17871
交易次数        10
交易金额       459
Name: 17870, dtype: int64
内部标识号    17872
交易次数        11
交易金额       430
Name: 17871, dtype: int64
内部标识号    17873
交易次数         0
交易金额      1184
Name: 17872, dtype: int64
内部标识号    17874
交易次数         3
交易金额       188
Name: 17873, dtype: int64
内部标识号    17875
交易次数        14
交易金额       388
Name: 17874, dtype: int64
内部标识号    17876
交易次数         3
交易金额       460
Name: 17875, dtype: int64
内部标识号    17877
交易次数         6
交易金额       172
Name: 17876, dtype: int64
内部标识号    17878
交易次数         8
交易金额       177
Name: 17877, dtype: int64
内部标识号    17879
交易次数         5
交易金额       196
Name: 17878, dtype: int64
内部标识号    17880
交易次数         5
交易金额     81291
Name: 17879, dtype: int64
内部标识号    17881
交易次数         5
交易金额       250
Name: 17880, dtype: int64
内部标识号    17882
交易次数         0
交易金额      3905
Name: 17881, dtype: int64
内部标识号    17883
交易次数       250
交易金额     65021
Name: 17882, dtype: int64
内部标识号    17884
交易次数         2
交易金额       332
Name: 17883, dtype: int64
内部标识号    17885
交易次数         1
交易金额       616
Name: 17884, dtype: int64
内部标识号    17886
交易次数        15
交易金额       628
Name: 17885, dtype: int64
内部标识号    17887
交易次数        28
交易金额       578
Name: 17886, dtype: int64
内部标识号    17888
交易次数        11
交易金额       529
Name: 17887, dtype: int64
内部标识号    17889
交易次数         8
交易金额       245
Name: 17888, dtype: int64
内部标识号    17890
交易次数        15
交易金额       932
Name: 17889, dtype: int64
内部标识号    17891
交易次数        16
交易金额        70
Name: 17890, dtype: int64
内部标识号    17892
交易次数         5
交易金额       275
Name: 17891, dtype: int64
内部标识号    17893
交易次数         5
交易金额       211
Name: 17892, dtype: int64
内部标识号    17894
交易次数        27
交易金额        33
Name: 17893, dtype: int64
内部标识号    17895
交易次数         7
交易金额       166
Name: 17894, dtype: int64
内部标识号    17896
交易次数        14
交易金额       899
Name: 17895, dtype: int64
内部标识号    17897
交易次数         9
交易金额       636
Name: 17896, dtype: int64
内部标识号    17898
交易次数        23
交易金额      1838
Name: 17897, dtype: int64
内部标识号    17899
交易次数        15
交易金额       673
Name: 17898, dtype: int64
内部标识号    17900
交易次数         2
交易金额       328
Name: 17899, dtype: int64
内部标识号    17901
交易次数       129
交易金额     77830
Name: 17900, dtype: int64
内部标识号    17902
交易次数        14
交易金额       448
Name: 17901, dtype: int64
内部标识号    17903
交易次数        17
交易金额      4821
Name: 17902, dtype: int64
内部标识号    17904
交易次数        13
交易金额       336
Name: 17903, dtype: int64
内部标识号    17905
交易次数         1
交易金额      6381
Name: 17904, dtype: int64
内部标识号    17906
交易次数        12
交易金额       377
Name: 17905, dtype: int64
内部标识号    17907
交易次数         4
交易金额     81585
Name: 17906, dtype: int64
内部标识号    17908
交易次数        13
交易金额       314
Name: 17907, dtype: int64
内部标识号    17909
交易次数        10
交易金额       550
Name: 17908, dtype: int64
内部标识号    17910
交易次数        14
交易金额       402
Name: 17909, dtype: int64
内部标识号    17911
交易次数         2
交易金额       915
Name: 17910, dtype: int64
内部标识号    17912
交易次数         5
交易金额       144
Name: 17911, dtype: int64
内部标识号    17913
交易次数         1
交易金额      2953
Name: 17912, dtype: int64
内部标识号    17914
交易次数        14
交易金额       499
Name: 17913, dtype: int64
内部标识号    17915
交易次数         3
交易金额       156
Name: 17914, dtype: int64
内部标识号    17916
交易次数         8
交易金额       124
Name: 17915, dtype: int64
内部标识号    17917
交易次数         7
交易金额       268
Name: 17916, dtype: int64
内部标识号    17918
交易次数         8
交易金额       332
Name: 17917, dtype: int64
内部标识号    17919
交易次数         1
交易金额       603
Name: 17918, dtype: int64
内部标识号    17920
交易次数        27
交易金额      2174
Name: 17919, dtype: int64
内部标识号    17921
交易次数         8
交易金额       163
Name: 17920, dtype: int64
内部标识号    17922
交易次数        15
交易金额       822
Name: 17921, dtype: int64
内部标识号    17923
交易次数         2
交易金额       470
Name: 17922, dtype: int64
内部标识号    17924
交易次数         1
交易金额      5429
Name: 17923, dtype: int64
内部标识号    17925
交易次数         1
交易金额       560
Name: 17924, dtype: int64
内部标识号    17926
交易次数       105
交易金额     76617
Name: 17925, dtype: int64
内部标识号    17927
交易次数        15
交易金额       931
Name: 17926, dtype: int64
内部标识号    17928
交易次数         0
交易金额      9119
Name: 17927, dtype: int64
内部标识号    17929
交易次数         2
交易金额       930
Name: 17928, dtype: int64
内部标识号    17930
交易次数         0
交易金额      5127
Name: 17929, dtype: int64
内部标识号    17931
交易次数         8
交易金额       288
Name: 17930, dtype: int64
内部标识号    17932
交易次数         8
交易金额       307
Name: 17931, dtype: int64
内部标识号    17933
交易次数         7
交易金额       182
Name: 17932, dtype: int64
内部标识号    17934
交易次数         1
交易金额       648
Name: 17933, dtype: int64
内部标识号    17935
交易次数         2
交易金额       276
Name: 17934, dtype: int64
内部标识号    17936
交易次数         3
交易金额       399
Name: 17935, dtype: int64
内部标识号    17937
交易次数         3
交易金额       388
Name: 17936, dtype: int64
内部标识号    17938
交易次数         2
交易金额       994
Name: 17937, dtype: int64
内部标识号    17939
交易次数        10
交易金额       736
Name: 17938, dtype: int64
内部标识号    17940
交易次数        12
交易金额       358
Name: 17939, dtype: int64
内部标识号    17941
交易次数         3
交易金额       214
Name: 17940, dtype: int64
内部标识号    17942
交易次数        10
交易金额       813
Name: 17941, dtype: int64
内部标识号    17943
交易次数         2
交易金额       652
Name: 17942, dtype: int64
内部标识号    17944
交易次数         7
交易金额     22098
Name: 17943, dtype: int64
内部标识号    17945
交易次数         3
交易金额       418
Name: 17944, dtype: int64
内部标识号    17946
交易次数        15
交易金额       591
Name: 17945, dtype: int64
内部标识号    17947
交易次数         0
交易金额      7738
Name: 17946, dtype: int64
内部标识号    17948
交易次数         2
交易金额       926
Name: 17947, dtype: int64
内部标识号    17949
交易次数         1
交易金额       552
Name: 17948, dtype: int64
内部标识号    17950
交易次数         3
交易金额       448
Name: 17949, dtype: int64
内部标识号    17951
交易次数         1
交易金额      2195
Name: 17950, dtype: int64
内部标识号    17952
交易次数         2
交易金额       505
Name: 17951, dtype: int64
内部标识号    17953
交易次数         4
交易金额       149
Name: 17952, dtype: int64
内部标识号    17954
交易次数         9
交易金额       320
Name: 17953, dtype: int64
内部标识号    17955
交易次数         2
交易金额       705
Name: 17954, dtype: int64
内部标识号    17956
交易次数        25
交易金额        98
Name: 17955, dtype: int64
内部标识号    17957
交易次数         3
交易金额       337
Name: 17956, dtype: int64
内部标识号    17958
交易次数        18
交易金额      6460
Name: 17957, dtype: int64
内部标识号    17959
交易次数         3
交易金额       386
Name: 17958, dtype: int64
内部标识号    17960
交易次数        19
交易金额      6628
Name: 17959, dtype: int64
内部标识号    17961
交易次数        14
交易金额       637
Name: 17960, dtype: int64
内部标识号    17962
交易次数         4
交易金额     50773
Name: 17961, dtype: int64
内部标识号    17963
交易次数         8
交易金额       149
Name: 17962, dtype: int64
内部标识号    17964
交易次数        14
交易金额       430
Name: 17963, dtype: int64
内部标识号    17965
交易次数         3
交易金额       283
Name: 17964, dtype: int64
内部标识号    17966
交易次数         1
交易金额       708
Name: 17965, dtype: int64
内部标识号    17967
交易次数        14
交易金额       870
Name: 17966, dtype: int64
内部标识号    17968
交易次数         8
交易金额       906
Name: 17967, dtype: int64
内部标识号    17969
交易次数        13
交易金额       348
Name: 17968, dtype: int64
内部标识号    17970
交易次数        14
交易金额       839
Name: 17969, dtype: int64
内部标识号    17971
交易次数         2
交易金额       767
Name: 17970, dtype: int64
内部标识号    17972
交易次数         7
交易金额       140
Name: 17971, dtype: int64
内部标识号    17973
交易次数        15
交易金额       975
Name: 17972, dtype: int64
内部标识号    17974
交易次数         2
交易金额       330
Name: 17973, dtype: int64
内部标识号    17975
交易次数        12
交易金额       885
Name: 17974, dtype: int64
内部标识号    17976
交易次数         3
交易金额       414
Name: 17975, dtype: int64
内部标识号    17977
交易次数         2
交易金额       314
Name: 17976, dtype: int64
内部标识号    17978
交易次数         6
交易金额       234
Name: 17977, dtype: int64
内部标识号    17979
交易次数         2
交易金额       230
Name: 17978, dtype: int64
内部标识号    17980
交易次数        11
交易金额       489
Name: 17979, dtype: int64
内部标识号    17981
交易次数         9
交易金额       779
Name: 17980, dtype: int64
内部标识号    17982
交易次数         8
交易金额     48611
Name: 17981, dtype: int64
内部标识号    17983
交易次数        13
交易金额       741
Name: 17982, dtype: int64
内部标识号    17984
交易次数         1
交易金额       527
Name: 17983, dtype: int64
内部标识号    17985
交易次数        19
交易金额       613
Name: 17984, dtype: int64
内部标识号    17986
交易次数        43
交易金额     71284
Name: 17985, dtype: int64
内部标识号    17987
交易次数         8
交易金额       186
Name: 17986, dtype: int64
内部标识号    17988
交易次数        14
交易金额       931
Name: 17987, dtype: int64
内部标识号    17989
交易次数         1
交易金额       620
Name: 17988, dtype: int64
内部标识号    17990
交易次数        15
交易金额       450
Name: 17989, dtype: int64
内部标识号    17991
交易次数         2
交易金额       484
Name: 17990, dtype: int64
内部标识号    17992
交易次数         2
交易金额       111
Name: 17991, dtype: int64
内部标识号    17993
交易次数        30
交易金额      5241
Name: 17992, dtype: int64
内部标识号    17994
交易次数         1
交易金额      9795
Name: 17993, dtype: int64
内部标识号    17995
交易次数        10
交易金额       792
Name: 17994, dtype: int64
内部标识号    17996
交易次数         8
交易金额       907
Name: 17995, dtype: int64
内部标识号    17997
交易次数        26
交易金额      4875
Name: 17996, dtype: int64
内部标识号    17998
交易次数        13
交易金额       762
Name: 17997, dtype: int64
内部标识号    17999
交易次数         6
交易金额       194
Name: 17998, dtype: int64
内部标识号    18000
交易次数        25
交易金额      6831
Name: 17999, dtype: int64
内部标识号    18001
交易次数         2
交易金额       419
Name: 18000, dtype: int64
内部标识号    18002
交易次数         2
交易金额       517
Name: 18001, dtype: int64
内部标识号    18003
交易次数        22
交易金额      7908
Name: 18002, dtype: int64
内部标识号    18004
交易次数         3
交易金额       264
Name: 18003, dtype: int64
内部标识号    18005
交易次数         6
交易金额       109
Name: 18004, dtype: int64
内部标识号    18006
交易次数         3
交易金额       216
Name: 18005, dtype: int64
内部标识号    18007
交易次数         6
交易金额       275
Name: 18006, dtype: int64
内部标识号    18008
交易次数         0
交易金额      8298
Name: 18007, dtype: int64
内部标识号    18009
交易次数         4
交易金额       274
Name: 18008, dtype: int64
内部标识号    18010
交易次数         3
交易金额       210
Name: 18009, dtype: int64
内部标识号    18011
交易次数         3
交易金额       174
Name: 18010, dtype: int64
内部标识号    18012
交易次数         6
交易金额       230
Name: 18011, dtype: int64
内部标识号    18013
交易次数        15
交易金额       901
Name: 18012, dtype: int64
内部标识号    18014
交易次数         8
交易金额       970
Name: 18013, dtype: int64
内部标识号    18015
交易次数         2
交易金额       575
Name: 18014, dtype: int64
内部标识号    18016
交易次数        11
交易金额       996
Name: 18015, dtype: int64
内部标识号    18017
交易次数         6
交易金额       246
Name: 18016, dtype: int64
内部标识号    18018
交易次数         9
交易金额       379
Name: 18017, dtype: int64
内部标识号    18019
交易次数         0
交易金额      9161
Name: 18018, dtype: int64
内部标识号    18020
交易次数         4
交易金额       106
Name: 18019, dtype: int64
内部标识号    18021
交易次数        12
交易金额       371
Name: 18020, dtype: int64
内部标识号    18022
交易次数         9
交易金额       765
Name: 18021, dtype: int64
内部标识号    18023
交易次数        15
交易金额       950
Name: 18022, dtype: int64
内部标识号    18024
交易次数        12
交易金额       639
Name: 18023, dtype: int64
内部标识号    18025
交易次数         6
交易金额     25226
Name: 18024, dtype: int64
内部标识号    18026
交易次数         5
交易金额       270
Name: 18025, dtype: int64
内部标识号    18027
交易次数         3
交易金额       225
Name: 18026, dtype: int64
内部标识号    18028
交易次数        15
交易金额       642
Name: 18027, dtype: int64
内部标识号    18029
交易次数         2
交易金额       701
Name: 18028, dtype: int64
内部标识号    18030
交易次数        11
交易金额       630
Name: 18029, dtype: int64
内部标识号    18031
交易次数         2
交易金额       303
Name: 18030, dtype: int64
内部标识号    18032
交易次数         1
交易金额       675
Name: 18031, dtype: int64
内部标识号    18033
交易次数         1
交易金额      4619
Name: 18032, dtype: int64
内部标识号    18034
交易次数        14
交易金额       566

Name: 18251, dtype: int64
内部标识号    18253
交易次数        13
交易金额       371
Name: 18252, dtype: int64
内部标识号    18254
交易次数        16
交易金额      9346
Name: 18253, dtype: int64
内部标识号    18255
交易次数        12
交易金额       374
Name: 18254, dtype: int64
内部标识号    18256
交易次数         1
交易金额       834
Name: 18255, dtype: int64
内部标识号    18257
交易次数         2
交易金额       451
Name: 18256, dtype: int64
内部标识号    18258
交易次数         2
交易金额       322
Name: 18257, dtype: int64
内部标识号    18259
交易次数         0
交易金额      4774
Name: 18258, dtype: int64
内部标识号    18260
交易次数         3
交易金额     17154
Name: 18259, dtype: int64
内部标识号    18261
交易次数        10
交易金额       385
Name: 18260, dtype: int64
内部标识号    18262
交易次数        13
交易金额       606
Name: 18261, dtype: int64
内部标识号    18263
交易次数         3
交易金额       313
Name: 18262, dtype: int64
内部标识号    18264
交易次数        15
交易金额       594
Name: 18263, dtype: int64
内部标识号    18265
交易次数         1
交易金额      9090
Name: 18264, dtype: int64
内部标识号    18266
交易次数         7
交易金额     94966
Name: 18265, dtype: int64
内部标识号    18267
交易次数        10
交易金额       717
Name: 18266, dtype: int64
内部标识号    18268
交易次数       215
交易金额     28424
Name: 18267, dtype: int64
内部标识号    18269
交易次数         3
交易金额       141
Name: 18268, dtype: int64
内部标识号    18270
交易次数        14
交易金额       468
Name: 18269, dtype: int64
内部标识号    18271
交易次数         1
交易金额       818
Name: 18270, dtype: int64
内部标识号    18272
交易次数        12
交易金额       537
Name: 18271, dtype: int64
内部标识号    18273
交易次数        26
交易金额        33
Name: 18272, dtype: int64
内部标识号    18274
交易次数        11
交易金额       344
Name: 18273, dtype: int64
内部标识号    18275
交易次数        14
交易金额       636
Name: 18274, dtype: int64
内部标识号    18276
交易次数         5
交易金额     96253
Name: 18275, dtype: int64
内部标识号    18277
交易次数         4
交易金额     42322
Name: 18276, dtype: int64
内部标识号    18278
交易次数       100
交易金额     99725
Name: 18277, dtype: int64
内部标识号    18279
交易次数        17
交易金额      7442
Name: 18278, dtype: int64
内部标识号    18280
交易次数         4
交易金额       247
Name: 18279, dtype: int64
内部标识号    18281
交易次数         3
交易金额       327
Name: 18280, dtype: int64
内部标识号    18282
交易次数        15
交易金额      7411
Name: 18281, dtype: int64
内部标识号    18283
交易次数         6
交易金额       148
Name: 18282, dtype: int64
内部标识号    18284
交易次数         2
交易金额       535
Name: 18283, dtype: int64
内部标识号    18285
交易次数         2
交易金额       564
Name: 18284, dtype: int64
内部标识号    18286
交易次数        59
交易金额     67031
Name: 18285, dtype: int64
内部标识号    18287
交易次数        13
交易金额       427
Name: 18286, dtype: int64
内部标识号    18288
交易次数        29
交易金额      1179
Name: 18287, dtype: int64
内部标识号    18289
交易次数         6
交易金额     86353
Name: 18288, dtype: int64
内部标识号    18290
交易次数         0
交易金额      2584
Name: 18289, dtype: int64
内部标识号    18291
交易次数         2
交易金额       320
Name: 18290, dtype: int64
内部标识号    18292
交易次数        20
交易金额       798
Name: 18291, dtype: int64
内部标识号    18293
交易次数        12
交易金额       880
Name: 18292, dtype: int64
内部标识号    18294
交易次数        28
交易金额      6739
Name: 18293, dtype: int64
内部标识号    18295
交易次数        12
交易金额       423
Name: 18294, dtype: int64
内部标识号    18296
交易次数         4
交易金额       142
Name: 18295, dtype: int64
内部标识号    18297
交易次数         3
交易金额       434
Name: 18296, dtype: int64
内部标识号    18298
交易次数         2
交易金额       749
Name: 18297, dtype: int64
内部标识号    18299
交易次数        17
交易金额      6673
Name: 18298, dtype: int64
内部标识号    18300
交易次数         9
交易金额       864
Name: 18299, dtype: int64
内部标识号    18301
交易次数        13
交易金额       462
Name: 18300, dtype: int64
内部标识号    18302
交易次数         1
交易金额       885
Name: 18301, dtype: int64
内部标识号    18303
交易次数         6
交易金额     78728
Name: 18302, dtype: int64
内部标识号    18304
交易次数        22
交易金额       856
Name: 18303, dtype: int64
内部标识号    18305
交易次数        15
交易金额       821
Name: 18304, dtype: int64
内部标识号    18306
交易次数         2
交易金额       325
Name: 18305, dtype: int64
内部标识号    18307
交易次数        20
交易金额      1932
Name: 18306, dtype: int64
内部标识号    18308
交易次数         9
交易金额       790
Name: 18307, dtype: int64
内部标识号    18309
交易次数        24
交易金额      1942
Name: 18308, dtype: int64
内部标识号    18310
交易次数        22
交易金额      4175
Name: 18309, dtype: int64
内部标识号    18311
交易次数        10
交易金额       350
Name: 18310, dtype: int64
内部标识号    18312
交易次数         4
交易金额     14698
Name: 18311, dtype: int64
内部标识号    18313
交易次数         8
交易金额     12006
Name: 18312, dtype: int64
内部标识号    18314
交易次数        15
交易金额       511
Name: 18313, dtype: int64
内部标识号    18315
交易次数        54
交易金额     91902
Name: 18314, dtype: int64
内部标识号    18316
交易次数         4
交易金额       147
Name: 18315, dtype: int64
内部标识号    18317
交易次数         3
交易金额       244
Name: 18316, dtype: int64
内部标识号    18318
交易次数         1
交易金额      7913
Name: 18317, dtype: int64
内部标识号    18319
交易次数         8
交易金额       503
Name: 18318, dtype: int64
内部标识号    18320
交易次数         4
交易金额       259
Name: 18319, dtype: int64
内部标识号    18321
交易次数         4
交易金额       198
Name: 18320, dtype: int64
内部标识号    18322
交易次数         9
交易金额       357
Name: 18321, dtype: int64
内部标识号    18323
交易次数        11
交易金额       585
Name: 18322, dtype: int64
内部标识号    18324
交易次数        26
交易金额      9370
Name: 18323, dtype: int64
内部标识号    18325
交易次数         8
交易金额       683
Name: 18324, dtype: int64
内部标识号    18326
交易次数        16
交易金额      4495
Name: 18325, dtype: int64
内部标识号    18327
交易次数         9
交易金额       778
Name: 18326, dtype: int64
内部标识号    18328
交易次数        11
交易金额       373
Name: 18327, dtype: int64
内部标识号    18329
交易次数        14
交易金额       983
Name: 18328, dtype: int64
内部标识号    18330
交易次数        20
交易金额       819
Name: 18329, dtype: int64
内部标识号    18331
交易次数         8
交易金额       951
Name: 18330, dtype: int64
内部标识号    18332
交易次数         1
交易金额      4910
Name: 18331, dtype: int64
内部标识号    18333
交易次数        14
交易金额       405
Name: 18332, dtype: int64
内部标识号    18334
交易次数        11
交易金额       478
Name: 18333, dtype: int64
内部标识号    18335
交易次数        13
交易金额       317
Name: 18334, dtype: int64
内部标识号    18336
交易次数         9
交易金额       539
Name: 18335, dtype: int64
内部标识号    18337
交易次数         2
交易金额       559
Name: 18336, dtype: int64
内部标识号    18338
交易次数         7
交易金额       157
Name: 18337, dtype: int64
内部标识号    18339
交易次数         8
交易金额       141
Name: 18338, dtype: int64
内部标识号    18340
交易次数        20
交易金额       815
Name: 18339, dtype: int64
内部标识号    18341
交易次数         0
交易金额      4021
Name: 18340, dtype: int64
内部标识号    18342
交易次数        23
交易金额      8547
Name: 18341, dtype: int64
内部标识号    18343
交易次数         2
交易金额       414
Name: 18342, dtype: int64
内部标识号    18344
交易次数         4
交易金额       277
Name: 18343, dtype: int64
内部标识号    18345
交易次数         9
交易金额       323
Name: 18344, dtype: int64
内部标识号    18346
交易次数        14
交易金额       371
Name: 18345, dtype: int64
内部标识号    18347
交易次数         1
交易金额      3185
Name: 18346, dtype: int64
内部标识号    18348
交易次数        11
交易金额       405
Name: 18347, dtype: int64
内部标识号    18349
交易次数        15
交易金额       958
Name: 18348, dtype: int64
内部标识号    18350
交易次数         2
交易金额       806
Name: 18349, dtype: int64
内部标识号    18351
交易次数        15
交易金额       713
Name: 18350, dtype: int64
内部标识号    18352
交易次数         7
交易金额     60605
Name: 18351, dtype: int64
内部标识号    18353
交易次数         8
交易金额       574
Name: 18352, dtype: int64
内部标识号    18354
交易次数         7
交易金额       282
Name: 18353, dtype: int64
内部标识号    18355
交易次数         5
交易金额       285
Name: 18354, dtype: int64
内部标识号    18356
交易次数         4
交易金额     58670
Name: 18355, dtype: int64
内部标识号    18357
交易次数        11
交易金额       594
Name: 18356, dtype: int64
内部标识号    18358
交易次数         3
交易金额     50686
Name: 18357, dtype: int64
内部标识号    18359
交易次数         2
交易金额       401
Name: 18358, dtype: int64
内部标识号    18360
交易次数        10
交易金额       518
Name: 18359, dtype: int64
内部标识号    18361
交易次数         2
交易金额       491
Name: 18360, dtype: int64
内部标识号    18362
交易次数         2
交易金额       380
Name: 18361, dtype: int64
内部标识号    18363
交易次数        14
交易金额       370
Name: 18362, dtype: int64
内部标识号    18364
交易次数         0
交易金额      7712
Name: 18363, dtype: int64
内部标识号    18365
交易次数         8
交易金额       576
Name: 18364, dtype: int64
内部标识号    18366
交易次数        29
交易金额      2888
Name: 18365, dtype: int64
内部标识号    18367
交易次数         2
交易金额       374
Name: 18366, dtype: int64
内部标识号    18368
交易次数        13
交易金额       426
Name: 18367, dtype: int64
内部标识号    18369
交易次数         2
交易金额       484
Name: 18368, dtype: int64
内部标识号    18370
交易次数         3
交易金额       137
Name: 18369, dtype: int64
内部标识号    18371
交易次数         9
交易金额       614
Name: 18370, dtype: int64
内部标识号    18372
交易次数        58
交易金额     19771
Name: 18371, dtype: int64
内部标识号    18373
交易次数         0
交易金额      1837
Name: 18372, dtype: int64
内部标识号    18374
交易次数         3
交易金额       452
Name: 18373, dtype: int64
内部标识号    18375
交易次数        10
交易金额       969
Name: 18374, dtype: int64
内部标识号    18376
交易次数        22
交易金额      2317
Name: 18375, dtype: int64
内部标识号    18377
交易次数         9
交易金额       767
Name: 18376, dtype: int64
内部标识号    18378
交易次数         3
交易金额       245
Name: 18377, dtype: int64
内部标识号    18379
交易次数         8
交易金额       192
Name: 18378, dtype: int64
内部标识号    18380
交易次数       254
交易金额     95017
Name: 18379, dtype: int64
内部标识号    18381
交易次数        12
交易金额       318
Name: 18380, dtype: int64
内部标识号    18382
交易次数         9
交易金额       907
Name: 18381, dtype: int64
内部标识号    18383
交易次数        14
交易金额       491
Name: 18382, dtype: int64
内部标识号    18384
交易次数         2
交易金额       281
Name: 18383, dtype: int64
内部标识号    18385
交易次数        10
交易金额       378
Name: 18384, dtype: int64
内部标识号    18386
交易次数         7
交易金额       105
Name: 18385, dtype: int64
内部标识号    18387
交易次数        12
交易金额       776
Name: 18386, dtype: int64
内部标识号    18388
交易次数         9
交易金额       918
Name: 18387, dtype: int64
内部标识号    18389
交易次数         4
交易金额       139
Name: 18388, dtype: int64
内部标识号    18390
交易次数         1
交易金额       806
Name: 18389, dtype: int64
内部标识号    18391
交易次数         0
交易金额      1841
Name: 18390, dtype: int64
内部标识号    18392
交易次数        10
交易金额       382
Name: 18391, dtype: int64
内部标识号    18393
交易次数        15
交易金额       709
Name: 18392, dtype: int64
内部标识号    18394
交易次数        13
交易金额       634
Name: 18393, dtype: int64
内部标识号    18395
交易次数         9
交易金额       944
Name: 18394, dtype: int64
内部标识号    18396
交易次数         0
交易金额      5752
Name: 18395, dtype: int64
内部标识号    18397
交易次数        13
交易金额       756
Name: 18396, dtype: int64
内部标识号    18398
交易次数         3
交易金额       337
Name: 18397, dtype: int64
内部标识号    18399
交易次数         4
交易金额     72418
Name: 18398, dtype: int64
内部标识号    18400
交易次数         2
交易金额       340
Name: 18399, dtype: int64
内部标识号    18401
交易次数         8
交易金额       328
Name: 18400, dtype: int64
内部标识号    18402
交易次数        21
交易金额       560
Name: 18401, dtype: int64
内部标识号    18403
交易次数        19
交易金额       937
Name: 18402, dtype: int64
内部标识号    18404
交易次数         4
交易金额       293
Name: 18403, dtype: int64
内部标识号    18405
交易次数        13
交易金额       345
Name: 18404, dtype: int64
内部标识号    18406
交易次数         7
交易金额       211
Name: 18405, dtype: int64
内部标识号    18407
交易次数        13
交易金额       582
Name: 18406, dtype: int64
内部标识号    18408
交易次数         3
交易金额       469
Name: 18407, dtype: int64
内部标识号    18409
交易次数         4
交易金额       252
Name: 18408, dtype: int64
内部标识号    18410
交易次数         8
交易金额       476
Name: 18409, dtype: int64
内部标识号    18411
交易次数        13
交易金额       898
Name: 18410, dtype: int64
内部标识号    18412
交易次数        17
交易金额      8361
Name: 18411, dtype: int64
内部标识号    18413
交易次数         1
交易金额       909
Name: 18412, dtype: int64
内部标识号    18414
交易次数         4
交易金额     50580
Name: 18413, dtype: int64
内部标识号    18415
交易次数         9
交易金额       846
Name: 18414, dtype: int64
内部标识号    18416
交易次数         2
交易金额       783
Name: 18415, dtype: int64
内部标识号    18417
交易次数         1
交易金额      7909
Name: 18416, dtype: int64
内部标识号    18418
交易次数        10
交易金额       704
Name: 18417, dtype: int64
内部标识号    18419
交易次数         8
交易金额     46586
Name: 18418, dtype: int64
内部标识号    18420
交易次数         2
交易金额       400
Name: 18419, dtype: int64
内部标识号    18421
交易次数         2
交易金额       904
Name: 18420, dtype: int64
内部标识号    18422
交易次数         3
交易金额       476
Name: 18421, dtype: int64
内部标识号    18423
交易次数         0
交易金额      5599
Name: 18422, dtype: int64
内部标识号    18424
交易次数         1
交易金额      6946
Name: 18423, dtype: int64
内部标识号    18425
交易次数         2
交易金额       773
Name: 18424, dtype: int64
内部标识号    18426
交易次数        10
交易金额       472
Name: 18425, dtype: int64
内部标识号    18427
交易次数         4
交易金额       174
Name: 18426, dtype: int64
内部标识号    18428
交易次数         9
交易金额       811
Name: 18427, dtype: int64
内部标识号    18429
交易次数         1
交易金额       747
Name: 18428, dtype: int64
内部标识号    18430
交易次数         3
交易金额       406
Name: 18429, dtype: int64
内部标识号    18431
交易次数         1
交易金额       639
Name: 18430, dtype: int64
内部标识号    18432
交易次数         7
交易金额       246
Name: 18431, dtype: int64
内部标识号    18433
交易次数         3
交易金额       347
Name: 18432, dtype: int64
内部标识号    18434
交易次数       183
交易金额     98065
Name: 18433, dtype: int64
内部标识号    18435
交易次数        29
交易金额      4702
Name: 18434, dtype: int64
内部标识号    18436
交易次数        86
交易金额     29879
Name: 18435, dtype: int64
内部标识号    18437
交易次数         1
交易金额      4601
Name: 18436, dtype: int64
内部标识号    18438
交易次数         0
交易金额      2845
Name: 18437, dtype: int64
内部标识号    18439
交易次数        13
交易金额       807
Name: 18438, dtype: int64
内部标识号    18440
交易次数         0
交易金额      8359
Name: 18439, dtype: int64
内部标识号    18441
交易次数        11
交易金额       938
Name: 18440, dtype: int64
内部标识号    18442
交易次数         9
交易金额       358
Name: 18441, dtype: int64
内部标识号    18443
交易次数         2
交易金额       466
Name: 18442, dtype: int64
内部标识号    18444
交易次数         1
交易金额       543
Name: 18443, dtype: int64
内部标识号    18445
交易次数         2
交易金额       346
Name: 18444, dtype: int64
内部标识号    18446
交易次数       269
交易金额     36116
Name: 18445, dtype: int64
内部标识号    18447
交易次数        30
交易金额        55
Name: 18446, dtype: int64
内部标识号    18448
交易次数         6
交易金额       101
Name: 18447, dtype: int64
内部标识号    18449
交易次数        15
交易金额       453
Name: 18448, dtype: int64
内部标识号    18450
交易次数        14
交易金额       707
Name: 18449, dtype: int64
内部标识号    18451
交易次数         2
交易金额       682
Name: 18450, dtype: int64
内部标识号    18452
交易次数         5
交易金额       260
Name: 18451, dtype: int64
内部标识号    18453
交易次数         0
交易金额      1551
Name: 18452, dtype: int64
内部标识号    18454
交易次数         7
交易金额     98062
Name: 18453, dtype: int64
内部标识号    18455
交易次数         0
交易金额      5475
Name: 18454, dtype: int64
内部标识号    18456
交易次数         4
交易金额     69895
Name: 18455, dtype: int64
内部标识号    18457
交易次数        15
交易金额       998
Name: 18456, dtype: int64
内部标识号    18458
交易次数        12
交易金额       442
Name: 18457, dtype: int64
内部标识号    18459
交易次数         3
交易金额       239
Name: 18458, dtype: int64
内部标识号    18460
交易次数        71
交易金额     80007
Name: 18459, dtype: int64
内部标识号    18461
交易次数         2
交易金额       928
Name: 18460, dtype: int64
内部标识号    18462
交易次数         3
交易金额       301
Name: 18461, dtype: int64
内部标识号    18463
交易次数         2
交易金额       413
Name: 18462, dtype: int64
内部标识号    18464
交易次数         3
交易金额       331
Name: 18463, dtype: int64
内部标识号    18465
交易次数       177
交易金额     24456
Name: 18464, dtype: int64
内部标识号    18466
交易次数        11
交易金额       438
Name: 18465, dtype: int64
内部标识号    18467
交易次数         1
交易金额       777
Name: 18466, dtype: int64
内部标识号    18468
交易次数        19
交易金额      4541
Name: 18467, dtype: int64
内部标识号    18469
交易次数         2
交易金额       487
Name: 18468, dtype: int64
内部标识号    18470
交易次数        12
交易金额       922
Name: 18469, dtype: int64
内部标识号    18471
交易次数        11
交易金额       395
Name: 18470, dtype: int64
内部标识号    18472
交易次数         2
交易金额       335
Name: 18471, dtype: int64
内部标识号    18473
交易次数        10
交易金额       842
Name: 18472, dtype: int64
内部标识号    18474
交易次数         1
交易金额       864
Name: 18473, dtype: int64
内部标识号    18475
交易次数         3
交易金额       199
Name: 18474, dtype: int64
内部标识号    18476
交易次数         1
交易金额       839
Name: 18475, dtype: int64
内部标识号    18477
交易次数         8
交易金额       137
Name: 18476, dtype: int64
内部标识号    18478
交易次数        11
交易金额       443
Name: 18477, dtype: int64
内部标识号    18479
交易次数         9
交易金额       653
Name: 18478, dtype: int64
内部标识号    18480
交易次数         4
交易金额       236
Name: 18479, dtype: int64
内部标识号    18481
交易次数         2
交易金额       977
Name: 18480, dtype: int64
内部标识号    18482
交易次数         8
交易金额       350
Name: 18481, dtype: int64
内部标识号    18483
交易次数         2
交易金额       697
Name: 18482, dtype: int64
内部标识号    18484
交易次数        25
交易金额       632
Name: 18483, dtype: int64
内部标识号    18485
交易次数        13
交易金额       701
Name: 18484, dtype: int64
内部标识号    18486
交易次数         1
交易金额       964
Name: 18485, dtype: int64
内部标识号    18487
交易次数         3
交易金额       354
Name: 18486, dtype: int64
内部标识号    18488
交易次数         4
交易金额     19416
Name: 18487, dtype: int64
内部标识号    18489
交易次数         9
交易金额       402
Name: 18488, dtype: int64
内部标识号    18490
交易次数        12
交易金额       836
Name: 18489, dtype: int64
内部标识号    18491
交易次数         2
交易金额       725
Name: 18490, dtype: int64
内部标识号    18492
交易次数         3
交易金额       401
Name: 18491, dtype: int64
内部标识号    18493
交易次数         0
交易金额      2869
Name: 18492, dtype: int64
内部标识号    18494
交易次数         2
交易金额       644
Name: 18493, dtype: int64
内部标识号    18495
交易次数        12
交易金额       336
Name: 18494, dtype: int64
内部标识号    18496
交易次数         4
交易金额       184
Name: 18495, dtype: int64
内部标识号    18497
交易次数         3
交易金额       300
Name: 18496, dtype: int64
内部标识号    18498
交易次数         1
交易金额       798
Name: 18497, dtype: int64
内部标识号    18499
交易次数         2
交易金额       736
Name: 18498, dtype: int64
内部标识号    18500
交易次数         9
交易金额       480
Name: 18499, dtype: int64
内部标识号    18501
交易次数        13
交易金额       920
Name: 18500, dtype: int64
内部标识号    18502
交易次数         9
交易金额       370
Name: 18501, dtype: int64
内部标识号    18503
交易次数         0
交易金额      6399
Name: 18502, dtype: int64
内部标识号    18504
交易次数         5
交易金额       153
Name: 18503, dtype: int64
内部标识号    18505
交易次数         6
交易金额       148
Name: 18504, dtype: int64
内部标识号    18506
交易次数         2
交易金额       311
Name: 18505, dtype: int64
内部标识号    18507
交易次数         7
交易金额       282
Name: 18506, dtype: int64
内部标识号    18508
交易次数         3
交易金额       187
Name: 18507, dtype: int64
内部标识号    18509
交易次数        29
交易金额      7423
Name: 18508, dtype: int64
内部标识号    18510
交易次数         7
交易金额       151
Name: 18509, dtype: int64
内部标识号    18511
交易次数         2
交易金额       371
Name: 18510, dtype: int64
内部标识号    18512
交易次数        14
交易金额       394
Name: 18511, dtype: int64
内部标识号    18513
交易次数         2
交易金额       436
Name: 18512, dtype: int64
内部标识号    18514
交易次数         3
交易金额       388
Name: 18513, dtype: int64
内部标识号    18515
交易次数        11
交易金额       562
Name: 18514, dtype: int64
内部标识号    18516
交易次数         9
交易金额       363
Name: 18515, dtype: int64
内部标识号    18517
交易次数       101
交易金额     72709
Name: 18516, dtype: int64
内部标识号    18518
交易次数        10
交易金额       685
Name: 18517, dtype: int64
内部标识号    18519
交易次数         2
交易金额       463
Name: 18518, dtype: int64
内部标识号    18520
交易次数         8
交易金额     88538
Name: 18519, dtype: int64
内部标识号    18521
交易次数         0
交易金额      9112
Name: 18520, dtype: int64
内部标识号    18522
交易次数         2
交易金额       764
Name: 18521, dtype: int64
内部标识号    18523
交易次数         2
交易金额       993
Name: 18522, dtype: int64
内部标识号    18524
交易次数        24
交易金额       552
Name: 18523, dtype: int64
内部标识号    18525
交易次数        24
交易金额      6349
Name: 18524, dtype: int64
内部标识号    18526
交易次数        15
交易金额      2063
Name: 18525, dtype: int64
内部标识号    18527
交易次数         4
交易金额       150
Name: 18526, dtype: int64
内部标识号    18528
交易次数        10
交易金额       304
Name: 18527, dtype: int64
内部标识号    18529
交易次数         2
交易金额       405
Name: 18528, dtype: int64
内部标识号    18530
交易次数         6
交易金额     61734
Name: 18529, dtype: int64
内部标识号    18531
交易次数         7
交易金额       175
Name: 18530, dtype: int64
内部标识号    18532
交易次数         2
交易金额       746
Name: 18531, dtype: int64
内部标识号    18533
交易次数         3
交易金额       378
Name: 18532, dtype: int64
内部标识号    18534

内部标识号    18752
交易次数         2
交易金额       475
Name: 18751, dtype: int64
内部标识号    18753
交易次数         3
交易金额       160
Name: 18752, dtype: int64
内部标识号    18754
交易次数        10
交易金额       987
Name: 18753, dtype: int64
内部标识号    18755
交易次数         2
交易金额       932
Name: 18754, dtype: int64
内部标识号    18756
交易次数         6
交易金额     57944
Name: 18755, dtype: int64
内部标识号    18757
交易次数        11
交易金额       955
Name: 18756, dtype: int64
内部标识号    18758
交易次数        12
交易金额       786
Name: 18757, dtype: int64
内部标识号    18759
交易次数         3
交易金额     38837
Name: 18758, dtype: int64
内部标识号    18760
交易次数         2
交易金额       405
Name: 18759, dtype: int64
内部标识号    18761
交易次数        15
交易金额       572
Name: 18760, dtype: int64
内部标识号    18762
交易次数        12
交易金额       408
Name: 18761, dtype: int64
内部标识号    18763
交易次数         5
交易金额       232
Name: 18762, dtype: int64
内部标识号    18764
交易次数        19
交易金额      2926
Name: 18763, dtype: int64
内部标识号    18765
交易次数        10
交易金额       761
Name: 18764, dtype: int64
内部标识号    18766
交易次数         6
交易金额     49134
Name: 18765, dtype: int64
内部标识号    18767
交易次数        15
交易金额       302
Name: 18766, dtype: int64
内部标识号    18768
交易次数        95
交易金额     87835
Name: 18767, dtype: int64
内部标识号    18769
交易次数        55
交易金额     12548
Name: 18768, dtype: int64
内部标识号    18770
交易次数         7
交易金额       281
Name: 18769, dtype: int64
内部标识号    18771
交易次数        25
交易金额      1226
Name: 18770, dtype: int64
内部标识号    18772
交易次数         3
交易金额       469
Name: 18771, dtype: int64
内部标识号    18773
交易次数         3
交易金额       445
Name: 18772, dtype: int64
内部标识号    18774
交易次数        14
交易金额       969
Name: 18773, dtype: int64
内部标识号    18775
交易次数         1
交易金额       814
Name: 18774, dtype: int64
内部标识号    18776
交易次数         2
交易金额       339
Name: 18775, dtype: int64
内部标识号    18777
交易次数         3
交易金额       125
Name: 18776, dtype: int64
内部标识号    18778
交易次数         8
交易金额       679
Name: 18777, dtype: int64
内部标识号    18779
交易次数         7
交易金额       134
Name: 18778, dtype: int64
内部标识号    18780
交易次数         0
交易金额      4533
Name: 18779, dtype: int64
内部标识号    18781
交易次数         8
交易金额       779
Name: 18780, dtype: int64
内部标识号    18782
交易次数         4
交易金额       225
Name: 18781, dtype: int64
内部标识号    18783
交易次数         2
交易金额       469
Name: 18782, dtype: int64
内部标识号    18784
交易次数         3
交易金额       104
Name: 18783, dtype: int64
内部标识号    18785
交易次数        11
交易金额       363
Name: 18784, dtype: int64
内部标识号    18786
交易次数         4
交易金额     12391
Name: 18785, dtype: int64
内部标识号    18787
交易次数         3
交易金额       404
Name: 18786, dtype: int64
内部标识号    18788
交易次数        22
交易金额       685
Name: 18787, dtype: int64
内部标识号    18789
交易次数         9
交易金额       308
Name: 18788, dtype: int64
内部标识号    18790
交易次数         2
交易金额       471
Name: 18789, dtype: int64
内部标识号    18791
交易次数         0
交易金额      1549
Name: 18790, dtype: int64
内部标识号    18792
交易次数         8
交易金额       504
Name: 18791, dtype: int64
内部标识号    18793
交易次数        11
交易金额       615
Name: 18792, dtype: int64
内部标识号    18794
交易次数        13
交易金额       977
Name: 18793, dtype: int64
内部标识号    18795
交易次数         3
交易金额     82738
Name: 18794, dtype: int64
内部标识号    18796
交易次数        22
交易金额      4889
Name: 18795, dtype: int64
内部标识号    18797
交易次数         3
交易金额       498
Name: 18796, dtype: int64
内部标识号    18798
交易次数         3
交易金额       419
Name: 18797, dtype: int64
内部标识号    18799
交易次数         6
交易金额     83399
Name: 18798, dtype: int64
内部标识号    18800
交易次数         8
交易金额       880
Name: 18799, dtype: int64
内部标识号    18801
交易次数         5
交易金额       204
Name: 18800, dtype: int64
内部标识号    18802
交易次数         3
交易金额     38591
Name: 18801, dtype: int64
内部标识号    18803
交易次数         8
交易金额       238
Name: 18802, dtype: int64
内部标识号    18804
交易次数         7
交易金额       138
Name: 18803, dtype: int64
内部标识号    18805
交易次数         4
交易金额       208
Name: 18804, dtype: int64
内部标识号    18806
交易次数         2
交易金额       649
Name: 18805, dtype: int64
内部标识号    18807
交易次数        16
交易金额       997
Name: 18806, dtype: int64
内部标识号    18808
交易次数        14
交易金额       374
Name: 18807, dtype: int64
内部标识号    18809
交易次数         4
交易金额       288
Name: 18808, dtype: int64
内部标识号    18810
交易次数        25
交易金额       535
Name: 18809, dtype: int64
内部标识号    18811
交易次数        16
交易金额        56
Name: 18810, dtype: int64
内部标识号    18812
交易次数        14
交易金额       618
Name: 18811, dtype: int64
内部标识号    18813
交易次数        11
交易金额       532
Name: 18812, dtype: int64
内部标识号    18814
交易次数         2
交易金额       302
Name: 18813, dtype: int64
内部标识号    18815
交易次数         6
交易金额       156
Name: 18814, dtype: int64
内部标识号    18816
交易次数        10
交易金额       864
Name: 18815, dtype: int64
内部标识号    18817
交易次数        10
交易金额       425
Name: 18816, dtype: int64
内部标识号    18818
交易次数         1
交易金额       772
Name: 18817, dtype: int64
内部标识号    18819
交易次数        22
交易金额       542
Name: 18818, dtype: int64
内部标识号    18820
交易次数        13
交易金额       897
Name: 18819, dtype: int64
内部标识号    18821
交易次数        26
交易金额      7494
Name: 18820, dtype: int64
内部标识号    18822
交易次数         6
交易金额       105
Name: 18821, dtype: int64
内部标识号    18823
交易次数         3
交易金额       305
Name: 18822, dtype: int64
内部标识号    18824
交易次数         1
交易金额       790
Name: 18823, dtype: int64
内部标识号    18825
交易次数         5
交易金额       195
Name: 18824, dtype: int64
内部标识号    18826
交易次数        12
交易金额       893
Name: 18825, dtype: int64
内部标识号    18827
交易次数        29
交易金额      1597
Name: 18826, dtype: int64
内部标识号    18828
交易次数         3
交易金额       138
Name: 18827, dtype: int64
内部标识号    18829
交易次数         2
交易金额       649
Name: 18828, dtype: int64
内部标识号    18830
交易次数         2
交易金额       513
Name: 18829, dtype: int64
内部标识号    18831
交易次数         8
交易金额       116
Name: 18830, dtype: int64
内部标识号    18832
交易次数         2
交易金额       883
Name: 18831, dtype: int64
内部标识号    18833
交易次数         7
交易金额       194
Name: 18832, dtype: int64
内部标识号    18834
交易次数         2
交易金额       863
Name: 18833, dtype: int64
内部标识号    18835
交易次数         1
交易金额       628
Name: 18834, dtype: int64
内部标识号    18836
交易次数         0
交易金额      6662
Name: 18835, dtype: int64
内部标识号    18837
交易次数         1
交易金额       537
Name: 18836, dtype: int64
内部标识号    18838
交易次数         8
交易金额       698
Name: 18837, dtype: int64
内部标识号    18839
交易次数        14
交易金额      1000
Name: 18838, dtype: int64
内部标识号    18840
交易次数         2
交易金额       450
Name: 18839, dtype: int64
内部标识号    18841
交易次数         0
交易金额      4503
Name: 18840, dtype: int64
内部标识号    18842
交易次数         2
交易金额       499
Name: 18841, dtype: int64
内部标识号    18843
交易次数        17
交易金额        18
Name: 18842, dtype: int64
内部标识号    18844
交易次数         3
交易金额       360
Name: 18843, dtype: int64
内部标识号    18845
交易次数        15
交易金额       383
Name: 18844, dtype: int64
内部标识号    18846
交易次数         8
交易金额       249
Name: 18845, dtype: int64
内部标识号    18847
交易次数        11
交易金额       871
Name: 18846, dtype: int64
内部标识号    18848
交易次数         3
交易金额       348
Name: 18847, dtype: int64
内部标识号    18849
交易次数        14
交易金额       851
Name: 18848, dtype: int64
内部标识号    18850
交易次数         3
交易金额       321
Name: 18849, dtype: int64
内部标识号    18851
交易次数        13
交易金额       930
Name: 18850, dtype: int64
内部标识号    18852
交易次数        15
交易金额       612
Name: 18851, dtype: int64
内部标识号    18853
交易次数         8
交易金额       452
Name: 18852, dtype: int64
内部标识号    18854
交易次数        13
交易金额       658
Name: 18853, dtype: int64
内部标识号    18855
交易次数         3
交易金额       300
Name: 18854, dtype: int64
内部标识号    18856
交易次数         2
交易金额       320
Name: 18855, dtype: int64
内部标识号    18857
交易次数        14
交易金额       667
Name: 18856, dtype: int64
内部标识号    18858
交易次数        24
交易金额      5574
Name: 18857, dtype: int64
内部标识号    18859
交易次数        14
交易金额       863
Name: 18858, dtype: int64
内部标识号    18860
交易次数         3
交易金额     69458
Name: 18859, dtype: int64
内部标识号    18861
交易次数        66
交易金额     75537
Name: 18860, dtype: int64
内部标识号    18862
交易次数         7
交易金额       158
Name: 18861, dtype: int64
内部标识号    18863
交易次数        23
交易金额      4718
Name: 18862, dtype: int64
内部标识号    18864
交易次数        12
交易金额       903
Name: 18863, dtype: int64
内部标识号    18865
交易次数        13
交易金额       835
Name: 18864, dtype: int64
内部标识号    18866
交易次数         8
交易金额     35399
Name: 18865, dtype: int64
内部标识号    18867
交易次数        13
交易金额       330
Name: 18866, dtype: int64
内部标识号    18868
交易次数         8
交易金额       503
Name: 18867, dtype: int64
内部标识号    18869
交易次数         1
交易金额       569
Name: 18868, dtype: int64
内部标识号    18870
交易次数        12
交易金额       390
Name: 18869, dtype: int64
内部标识号    18871
交易次数         2
交易金额       232
Name: 18870, dtype: int64
内部标识号    18872
交易次数         1
交易金额      8154
Name: 18871, dtype: int64
内部标识号    18873
交易次数        10
交易金额       423
Name: 18872, dtype: int64
内部标识号    18874
交易次数         3
交易金额       166
Name: 18873, dtype: int64
内部标识号    18875
交易次数         4
交易金额       116
Name: 18874, dtype: int64
内部标识号    18876
交易次数         3
交易金额       153
Name: 18875, dtype: int64
内部标识号    18877
交易次数        30
交易金额      5865
Name: 18876, dtype: int64
内部标识号    18878
交易次数        15
交易金额      7276
Name: 18877, dtype: int64
内部标识号    18879
交易次数        11
交易金额       344
Name: 18878, dtype: int64
内部标识号    18880
交易次数         3
交易金额     80894
Name: 18879, dtype: int64
内部标识号    18881
交易次数        11
交易金额       790
Name: 18880, dtype: int64
内部标识号    18882
交易次数         8
交易金额       856
Name: 18881, dtype: int64
内部标识号    18883
交易次数         3
交易金额     88476
Name: 18882, dtype: int64
内部标识号    18884
交易次数       128
交易金额     22763
Name: 18883, dtype: int64
内部标识号    18885
交易次数         3
交易金额       470
Name: 18884, dtype: int64
内部标识号    18886
交易次数         0
交易金额      9912
Name: 18885, dtype: int64
内部标识号    18887
交易次数       176
交易金额     26667
Name: 18886, dtype: int64
内部标识号    18888
交易次数         8
交易金额       666
Name: 18887, dtype: int64
内部标识号    18889
交易次数        10
交易金额       509
Name: 18888, dtype: int64
内部标识号    18890
交易次数        11
交易金额       611
Name: 18889, dtype: int64
内部标识号    18891
交易次数        24
交易金额       918
Name: 18890, dtype: int64
内部标识号    18892
交易次数        15
交易金额       566
Name: 18891, dtype: int64
内部标识号    18893
交易次数         8
交易金额       910
Name: 18892, dtype: int64
内部标识号    18894
交易次数        11
交易金额       475
Name: 18893, dtype: int64
内部标识号    18895
交易次数        13
交易金额       541
Name: 18894, dtype: int64
内部标识号    18896
交易次数        15
交易金额       922
Name: 18895, dtype: int64
内部标识号    18897
交易次数         4
交易金额       208
Name: 18896, dtype: int64
内部标识号    18898
交易次数         2
交易金额       553
Name: 18897, dtype: int64
内部标识号    18899
交易次数         2
交易金额       686
Name: 18898, dtype: int64
内部标识号    18900
交易次数        12
交易金额       823
Name: 18899, dtype: int64
内部标识号    18901
交易次数         6
交易金额     61868
Name: 18900, dtype: int64
内部标识号    18902
交易次数        30
交易金额       636
Name: 18901, dtype: int64
内部标识号    18903
交易次数         3
交易金额       260
Name: 18902, dtype: int64
内部标识号    18904
交易次数         4
交易金额       227
Name: 18903, dtype: int64
内部标识号    18905
交易次数         8
交易金额       313
Name: 18904, dtype: int64
内部标识号    18906
交易次数        10
交易金额       826
Name: 18905, dtype: int64
内部标识号    18907
交易次数         3
交易金额       134
Name: 18906, dtype: int64
内部标识号    18908
交易次数         1
交易金额       519
Name: 18907, dtype: int64
内部标识号    18909
交易次数        26
交易金额      5006
Name: 18908, dtype: int64
内部标识号    18910
交易次数         1
交易金额      7875
Name: 18909, dtype: int64
内部标识号    18911
交易次数        27
交易金额       765
Name: 18910, dtype: int64
内部标识号    18912
交易次数         3
交易金额       203
Name: 18911, dtype: int64
内部标识号    18913
交易次数         2
交易金额       377
Name: 18912, dtype: int64
内部标识号    18914
交易次数        39
交易金额     44421
Name: 18913, dtype: int64
内部标识号    18915
交易次数        10
交易金额       312
Name: 18914, dtype: int64
内部标识号    18916
交易次数        26
交易金额       786
Name: 18915, dtype: int64
内部标识号    18917
交易次数        13
交易金额       323
Name: 18916, dtype: int64
内部标识号    18918
交易次数         6
交易金额     88735
Name: 18917, dtype: int64
内部标识号    18919
交易次数        13
交易金额       923
Name: 18918, dtype: int64
内部标识号    18920
交易次数        11
交易金额       700
Name: 18919, dtype: int64
内部标识号    18921
交易次数        11
交易金额       973
Name: 18920, dtype: int64
内部标识号    18922
交易次数         8
交易金额       187
Name: 18921, dtype: int64
内部标识号    18923
交易次数         3
交易金额       479
Name: 18922, dtype: int64
内部标识号    18924
交易次数         8
交易金额       202
Name: 18923, dtype: int64
内部标识号    18925
交易次数         9
交易金额       536
Name: 18924, dtype: int64
内部标识号    18926
交易次数         2
交易金额       734
Name: 18925, dtype: int64
内部标识号    18927
交易次数         7
交易金额     41459
Name: 18926, dtype: int64
内部标识号    18928
交易次数         9
交易金额       781
Name: 18927, dtype: int64
内部标识号    18929
交易次数        11
交易金额       667
Name: 18928, dtype: int64
内部标识号    18930
交易次数         4
交易金额       197
Name: 18929, dtype: int64
内部标识号    18931
交易次数        15
交易金额       729
Name: 18930, dtype: int64
内部标识号    18932
交易次数        15
交易金额       878
Name: 18931, dtype: int64
内部标识号    18933
交易次数        18
交易金额       813
Name: 18932, dtype: int64
内部标识号    18934
交易次数         8
交易金额       768
Name: 18933, dtype: int64
内部标识号    18935
交易次数        30
交易金额       855
Name: 18934, dtype: int64
内部标识号    18936
交易次数         3
交易金额       311
Name: 18935, dtype: int64
内部标识号    18937
交易次数         0
交易金额      8216
Name: 18936, dtype: int64
内部标识号    18938
交易次数         3
交易金额       411
Name: 18937, dtype: int64
内部标识号    18939
交易次数         3
交易金额       350
Name: 18938, dtype: int64
内部标识号    18940
交易次数         1
交易金额      5823
Name: 18939, dtype: int64
内部标识号    18941
交易次数         9
交易金额       858
Name: 18940, dtype: int64
内部标识号    18942
交易次数         7
交易金额     37748
Name: 18941, dtype: int64
内部标识号    18943
交易次数         0
交易金额      1234
Name: 18942, dtype: int64
内部标识号    18944
交易次数         3
交易金额       307
Name: 18943, dtype: int64
内部标识号    18945
交易次数         3
交易金额       330
Name: 18944, dtype: int64
内部标识号    18946
交易次数        16
交易金额      1176
Name: 18945, dtype: int64
内部标识号    18947
交易次数        16
交易金额       849
Name: 18946, dtype: int64
内部标识号    18948
交易次数         1
交易金额       916
Name: 18947, dtype: int64
内部标识号    18949
交易次数         3
交易金额       267
Name: 18948, dtype: int64
内部标识号    18950
交易次数         2
交易金额       385
Name: 18949, dtype: int64
内部标识号    18951
交易次数        13
交易金额       468
Name: 18950, dtype: int64
内部标识号    18952
交易次数        14
交易金额       314
Name: 18951, dtype: int64
内部标识号    18953
交易次数         1
交易金额      2681
Name: 18952, dtype: int64
内部标识号    18954
交易次数         3
交易金额       275
Name: 18953, dtype: int64
内部标识号    18955
交易次数        21
交易金额       874
Name: 18954, dtype: int64
内部标识号    18956
交易次数         3
交易金额       431
Name: 18955, dtype: int64
内部标识号    18957
交易次数         8
交易金额       883
Name: 18956, dtype: int64
内部标识号    18958
交易次数         6
交易金额     50592
Name: 18957, dtype: int64
内部标识号    18959
交易次数         2
交易金额       350
Name: 18958, dtype: int64
内部标识号    18960
交易次数         2
交易金额       488
Name: 18959, dtype: int64
内部标识号    18961
交易次数         8
交易金额       945
Name: 18960, dtype: int64
内部标识号    18962
交易次数         1
交易金额      9925
Name: 18961, dtype: int64
内部标识号    18963
交易次数         9
交易金额       619
Name: 18962, dtype: int64
内部标识号    18964
交易次数       243
交易金额     85782
Name: 18963, dtype: int64
内部标识号    18965
交易次数        16
交易金额      2852
Name: 18964, dtype: int64
内部标识号    18966
交易次数         1
交易金额       770
Name: 18965, dtype: int64
内部标识号    18967
交易次数        10
交易金额       701
Name: 18966, dtype: int64
内部标识号    18968
交易次数         4
交易金额       264
Name: 18967, dtype: int64
内部标识号    18969
交易次数         1
交易金额       768
Name: 18968, dtype: int64
内部标识号    18970
交易次数        15
交易金额       745
Name: 18969, dtype: int64
内部标识号    18971
交易次数         3
交易金额       444
Name: 18970, dtype: int64
内部标识号    18972
交易次数        13
交易金额       683
Name: 18971, dtype: int64
内部标识号    18973
交易次数        16
交易金额      7932
Name: 18972, dtype: int64
内部标识号    18974
交易次数        15
交易金额       693
Name: 18973, dtype: int64
内部标识号    18975
交易次数        23
交易金额      5796
Name: 18974, dtype: int64
内部标识号    18976
交易次数         3
交易金额       460
Name: 18975, dtype: int64
内部标识号    18977
交易次数        17
交易金额       569
Name: 18976, dtype: int64
内部标识号    18978
交易次数         7
交易金额       262
Name: 18977, dtype: int64
内部标识号    18979
交易次数         7
交易金额       176
Name: 18978, dtype: int64
内部标识号    18980
交易次数         5
交易金额       102
Name: 18979, dtype: int64
内部标识号    18981
交易次数        30
交易金额      6847
Name: 18980, dtype: int64
内部标识号    18982
交易次数         8
交易金额       265
Name: 18981, dtype: int64
内部标识号    18983
交易次数         1
交易金额      6724
Name: 18982, dtype: int64
内部标识号    18984
交易次数        24
交易金额      1040
Name: 18983, dtype: int64
内部标识号    18985
交易次数         2
交易金额       212
Name: 18984, dtype: int64
内部标识号    18986
交易次数        12
交易金额       492
Name: 18985, dtype: int64
内部标识号    18987
交易次数         5
交易金额     71685
Name: 18986, dtype: int64
内部标识号    18988
交易次数         6
交易金额       268
Name: 18987, dtype: int64
内部标识号    18989
交易次数         1
交易金额       613
Name: 18988, dtype: int64
内部标识号    18990
交易次数         5
交易金额       281
Name: 18989, dtype: int64
内部标识号    18991
交易次数         5
交易金额       299
Name: 18990, dtype: int64
内部标识号    18992
交易次数        99
交易金额     97968
Name: 18991, dtype: int64
内部标识号    18993
交易次数         1
交易金额      3952
Name: 18992, dtype: int64
内部标识号    18994
交易次数         1
交易金额      3137
Name: 18993, dtype: int64
内部标识号    18995
交易次数         8
交易金额       119
Name: 18994, dtype: int64
内部标识号    18996
交易次数        10
交易金额       402
Name: 18995, dtype: int64
内部标识号    18997
交易次数        14
交易金额       834
Name: 18996, dtype: int64
内部标识号    18998
交易次数         1
交易金额       768
Name: 18997, dtype: int64
内部标识号    18999
交易次数         8
交易金额       656
Name: 18998, dtype: int64
内部标识号    19000
交易次数       147
交易金额     17124
Name: 18999, dtype: int64
内部标识号    19001
交易次数         2
交易金额       770
Name: 19000, dtype: int64
内部标识号    19002
交易次数         3
交易金额       355
Name: 19001, dtype: int64
内部标识号    19003
交易次数         1
交易金额      6266
Name: 19002, dtype: int64
内部标识号    19004
交易次数        10
交易金额       334
Name: 19003, dtype: int64
内部标识号    19005
交易次数         9
交易金额       322
Name: 19004, dtype: int64
内部标识号    19006
交易次数         9
交易金额       890
Name: 19005, dtype: int64
内部标识号    19007
交易次数         8
交易金额       336
Name: 19006, dtype: int64
内部标识号    19008
交易次数        20
交易金额      6316
Name: 19007, dtype: int64
内部标识号    19009
交易次数        28
交易金额       765
Name: 19008, dtype: int64
内部标识号    19010
交易次数         2
交易金额       745
Name: 19009, dtype: int64
内部标识号    19011
交易次数         3
交易金额       376
Name: 19010, dtype: int64
内部标识号    19012
交易次数        29
交易金额      6466
Name: 19011, dtype: int64
内部标识号    19013
交易次数         0
交易金额      8131
Name: 19012, dtype: int64
内部标识号    19014
交易次数        20
交易金额       944
Name: 19013, dtype: int64
内部标识号    19015
交易次数         2
交易金额       521
Name: 19014, dtype: int64
内部标识号    19016
交易次数        15
交易金额       640
Name: 19015, dtype: int64
内部标识号    19017
交易次数        22
交易金额       892
Name: 19016, dtype: int64
内部标识号    19018
交易次数        10
交易金额       364
Name: 19017, dtype: int64
内部标识号    19019
交易次数         3
交易金额       264
Name: 19018, dtype: int64
内部标识号    19020
交易次数         2
交易金额       471
Name: 19019, dtype: int64
内部标识号    19021
交易次数         7
交易金额       135
Name: 19020, dtype: int64
内部标识号    19022
交易次数         5
交易金额       218
Name: 19021, dtype: int64
内部标识号    19023
交易次数        24
交易金额      9831
Name: 19022, dtype: int64
内部标识号    19024
交易次数       219
交易金额     40596
Name: 19023, dtype: int64
内部标识号    19025
交易次数         1
交易金额      8592
Name: 19024, dtype: int64
内部标识号    19026
交易次数         1
交易金额       743
Name: 19025, dtype: int64
内部标识号    19027
交易次数         8
交易金额       822
Name: 19026, dtype: int64
内部标识号    19028
交易次数       235
交易金额     58646
Name: 19027, dtype: int64
内部标识号    19029
交易次数         3
交易金额     32688
Name: 19028, dtype: int64
内部标识号    19030
交易次数         3
交易金额       340
Name: 19029, dtype: int64
内部标识号    19031
交易次数         2
交易金额       377
Name: 19030, dtype: int64
内部标识号    19032
交易次数         4
交易金额       240
Name: 19031, dtype: int64
内部标识号    19033
交易次数         1
交易金额       775

Name: 19250, dtype: int64
内部标识号    19252
交易次数        14
交易金额       383
Name: 19251, dtype: int64
内部标识号    19253
交易次数         1
交易金额      7245
Name: 19252, dtype: int64
内部标识号    19254
交易次数        17
交易金额       653
Name: 19253, dtype: int64
内部标识号    19255
交易次数         3
交易金额       440
Name: 19254, dtype: int64
内部标识号    19256
交易次数         3
交易金额       451
Name: 19255, dtype: int64
内部标识号    19257
交易次数         6
交易金额       294
Name: 19256, dtype: int64
内部标识号    19258
交易次数        35
交易金额     25133
Name: 19257, dtype: int64
内部标识号    19259
交易次数         7
交易金额       215
Name: 19258, dtype: int64
内部标识号    19260
交易次数        12
交易金额       668
Name: 19259, dtype: int64
内部标识号    19261
交易次数         2
交易金额       480
Name: 19260, dtype: int64
内部标识号    19262
交易次数         8
交易金额       183
Name: 19261, dtype: int64
内部标识号    19263
交易次数         5
交易金额       118
Name: 19262, dtype: int64
内部标识号    19264
交易次数        24
交易金额       993
Name: 19263, dtype: int64
内部标识号    19265
交易次数         1
交易金额       993
Name: 19264, dtype: int64
内部标识号    19266
交易次数         5
交易金额       167
Name: 19265, dtype: int64
内部标识号    19267
交易次数        12
交易金额       977
Name: 19266, dtype: int64
内部标识号    19268
交易次数         7
交易金额       195
Name: 19267, dtype: int64
内部标识号    19269
交易次数         7
交易金额       293
Name: 19268, dtype: int64
内部标识号    19270
交易次数         0
交易金额      5696
Name: 19269, dtype: int64
内部标识号    19271
交易次数         5
交易金额     46225
Name: 19270, dtype: int64
内部标识号    19272
交易次数         1
交易金额      2492
Name: 19271, dtype: int64
内部标识号    19273
交易次数         1
交易金额       650
Name: 19272, dtype: int64
内部标识号    19274
交易次数        15
交易金额       469
Name: 19273, dtype: int64
内部标识号    19275
交易次数        15
交易金额       486
Name: 19274, dtype: int64
内部标识号    19276
交易次数         0
交易金额      9331
Name: 19275, dtype: int64
内部标识号    19277
交易次数         2
交易金额       871
Name: 19276, dtype: int64
内部标识号    19278
交易次数        11
交易金额       337
Name: 19277, dtype: int64
内部标识号    19279
交易次数       171
交易金额     37300
Name: 19278, dtype: int64
内部标识号    19280
交易次数         8
交易金额       404
Name: 19279, dtype: int64
内部标识号    19281
交易次数         2
交易金额       195
Name: 19280, dtype: int64
内部标识号    19282
交易次数        12
交易金额       727
Name: 19281, dtype: int64
内部标识号    19283
交易次数         8
交易金额       253
Name: 19282, dtype: int64
内部标识号    19284
交易次数        14
交易金额       593
Name: 19283, dtype: int64
内部标识号    19285
交易次数         0
交易金额      2094
Name: 19284, dtype: int64
内部标识号    19286
交易次数         0
交易金额      2815
Name: 19285, dtype: int64
内部标识号    19287
交易次数         6
交易金额       140
Name: 19286, dtype: int64
内部标识号    19288
交易次数        13
交易金额       630
Name: 19287, dtype: int64
内部标识号    19289
交易次数         0
交易金额      6044
Name: 19288, dtype: int64
内部标识号    19290
交易次数        24
交易金额      3370
Name: 19289, dtype: int64
内部标识号    19291
交易次数        21
交易金额      4964
Name: 19290, dtype: int64
内部标识号    19292
交易次数         5
交易金额       205
Name: 19291, dtype: int64
内部标识号    19293
交易次数        25
交易金额      4517
Name: 19292, dtype: int64
内部标识号    19294
交易次数        11
交易金额       364
Name: 19293, dtype: int64
内部标识号    19295
交易次数         0
交易金额      7452
Name: 19294, dtype: int64
内部标识号    19296
交易次数        17
交易金额      7637
Name: 19295, dtype: int64
内部标识号    19297
交易次数        23
交易金额      5702
Name: 19296, dtype: int64
内部标识号    19298
交易次数         7
交易金额       186
Name: 19297, dtype: int64
内部标识号    19299
交易次数         2
交易金额       377
Name: 19298, dtype: int64
内部标识号    19300
交易次数         7
交易金额     24528
Name: 19299, dtype: int64
内部标识号    19301
交易次数         9
交易金额       654
Name: 19300, dtype: int64
内部标识号    19302
交易次数        15
交易金额       912
Name: 19301, dtype: int64
内部标识号    19303
交易次数         2
交易金额       373
Name: 19302, dtype: int64
内部标识号    19304
交易次数         4
交易金额       121
Name: 19303, dtype: int64
内部标识号    19305
交易次数         0
交易金额      5974
Name: 19304, dtype: int64
内部标识号    19306
交易次数         2
交易金额       391
Name: 19305, dtype: int64
内部标识号    19307
交易次数         3
交易金额       266
Name: 19306, dtype: int64
内部标识号    19308
交易次数         3
交易金额       409
Name: 19307, dtype: int64
内部标识号    19309
交易次数        13
交易金额       457
Name: 19308, dtype: int64
内部标识号    19310
交易次数        14
交易金额       833
Name: 19309, dtype: int64
内部标识号    19311
交易次数       295
交易金额     47828
Name: 19310, dtype: int64
内部标识号    19312
交易次数         8
交易金额       331
Name: 19311, dtype: int64
内部标识号    19313
交易次数        14
交易金额       987
Name: 19312, dtype: int64
内部标识号    19314
交易次数        15
交易金额       392
Name: 19313, dtype: int64
内部标识号    19315
交易次数        24
交易金额       818
Name: 19314, dtype: int64
内部标识号    19316
交易次数         3
交易金额     19383
Name: 19315, dtype: int64
内部标识号    19317
交易次数        22
交易金额      9489
Name: 19316, dtype: int64
内部标识号    19318
交易次数         3
交易金额       155
Name: 19317, dtype: int64
内部标识号    19319
交易次数         9
交易金额       894
Name: 19318, dtype: int64
内部标识号    19320
交易次数        10
交易金额       776
Name: 19319, dtype: int64
内部标识号    19321
交易次数        10
交易金额       658
Name: 19320, dtype: int64
内部标识号    19322
交易次数        26
交易金额      1620
Name: 19321, dtype: int64
内部标识号    19323
交易次数         3
交易金额     56275
Name: 19322, dtype: int64
内部标识号    19324
交易次数         6
交易金额       170
Name: 19323, dtype: int64
内部标识号    19325
交易次数         2
交易金额       303
Name: 19324, dtype: int64
内部标识号    19326
交易次数        27
交易金额      4885
Name: 19325, dtype: int64
内部标识号    19327
交易次数        15
交易金额       418
Name: 19326, dtype: int64
内部标识号    19328
交易次数        29
交易金额        33
Name: 19327, dtype: int64
内部标识号    19329
交易次数         2
交易金额       836
Name: 19328, dtype: int64
内部标识号    19330
交易次数         1
交易金额      7048
Name: 19329, dtype: int64
内部标识号    19331
交易次数        13
交易金额       735
Name: 19330, dtype: int64
内部标识号    19332
交易次数         0
交易金额      9375
Name: 19331, dtype: int64
内部标识号    19333
交易次数         6
交易金额       276
Name: 19332, dtype: int64
内部标识号    19334
交易次数       142
交易金额     92322
Name: 19333, dtype: int64
内部标识号    19335
交易次数         7
交易金额       131
Name: 19334, dtype: int64
内部标识号    19336
交易次数        27
交易金额       513
Name: 19335, dtype: int64
内部标识号    19337
交易次数         7
交易金额       134
Name: 19336, dtype: int64
内部标识号    19338
交易次数         9
交易金额       549
Name: 19337, dtype: int64
内部标识号    19339
交易次数        13
交易金额       393
Name: 19338, dtype: int64
内部标识号    19340
交易次数        19
交易金额      2954
Name: 19339, dtype: int64
内部标识号    19341
交易次数        24
交易金额       994
Name: 19340, dtype: int64
内部标识号    19342
交易次数         3
交易金额       440
Name: 19341, dtype: int64
内部标识号    19343
交易次数         2
交易金额       838
Name: 19342, dtype: int64
内部标识号    19344
交易次数         7
交易金额       154
Name: 19343, dtype: int64
内部标识号    19345
交易次数        23
交易金额       578
Name: 19344, dtype: int64
内部标识号    19346
交易次数         0
交易金额      9385
Name: 19345, dtype: int64
内部标识号    19347
交易次数       133
交易金额     80152
Name: 19346, dtype: int64
内部标识号    19348
交易次数         2
交易金额       372
Name: 19347, dtype: int64
内部标识号    19349
交易次数        22
交易金额        26
Name: 19348, dtype: int64
内部标识号    19350
交易次数        13
交易金额       873
Name: 19349, dtype: int64
内部标识号    19351
交易次数        27
交易金额      2340
Name: 19350, dtype: int64
内部标识号    19352
交易次数         3
交易金额       267
Name: 19351, dtype: int64
内部标识号    19353
交易次数         4
交易金额       104
Name: 19352, dtype: int64
内部标识号    19354
交易次数         6
交易金额     44862
Name: 19353, dtype: int64
内部标识号    19355
交易次数        22
交易金额      3925
Name: 19354, dtype: int64
内部标识号    19356
交易次数         5
交易金额     74377
Name: 19355, dtype: int64
内部标识号    19357
交易次数         4
交易金额       255
Name: 19356, dtype: int64
内部标识号    19358
交易次数         0
交易金额      5984
Name: 19357, dtype: int64
内部标识号    19359
交易次数         2
交易金额       391
Name: 19358, dtype: int64
内部标识号    19360
交易次数         7
交易金额       217
Name: 19359, dtype: int64
内部标识号    19361
交易次数         6
交易金额       141
Name: 19360, dtype: int64
内部标识号    19362
交易次数         3
交易金额       125
Name: 19361, dtype: int64
内部标识号    19363
交易次数         3
交易金额       390
Name: 19362, dtype: int64
内部标识号    19364
交易次数        20
交易金额      4462
Name: 19363, dtype: int64
内部标识号    19365
交易次数         8
交易金额       786
Name: 19364, dtype: int64
内部标识号    19366
交易次数         3
交易金额       497
Name: 19365, dtype: int64
内部标识号    19367
交易次数        44
交易金额     23552
Name: 19366, dtype: int64
内部标识号    19368
交易次数         2
交易金额       851
Name: 19367, dtype: int64
内部标识号    19369
交易次数        11
交易金额       547
Name: 19368, dtype: int64
内部标识号    19370
交易次数        33
交易金额     21127
Name: 19369, dtype: int64
内部标识号    19371
交易次数         2
交易金额       694
Name: 19370, dtype: int64
内部标识号    19372
交易次数        18
交易金额        23
Name: 19371, dtype: int64
内部标识号    19373
交易次数        30
交易金额      7574
Name: 19372, dtype: int64
内部标识号    19374
交易次数        50
交易金额     96808
Name: 19373, dtype: int64
内部标识号    19375
交易次数         8
交易金额       263
Name: 19374, dtype: int64
内部标识号    19376
交易次数         5
交易金额     69011
Name: 19375, dtype: int64
内部标识号    19377
交易次数        28
交易金额        55
Name: 19376, dtype: int64
内部标识号    19378
交易次数         1
交易金额       923
Name: 19377, dtype: int64
内部标识号    19379
交易次数        11
交易金额       412
Name: 19378, dtype: int64
内部标识号    19380
交易次数         0
交易金额      3764
Name: 19379, dtype: int64
内部标识号    19381
交易次数         3
交易金额       423
Name: 19380, dtype: int64
内部标识号    19382
交易次数         9
交易金额       717
Name: 19381, dtype: int64
内部标识号    19383
交易次数         2
交易金额       342
Name: 19382, dtype: int64
内部标识号    19384
交易次数         3
交易金额       366
Name: 19383, dtype: int64
内部标识号    19385
交易次数        13
交易金额       941
Name: 19384, dtype: int64
内部标识号    19386
交易次数         7
交易金额       197
Name: 19385, dtype: int64
内部标识号    19387
交易次数       176
交易金额     51187
Name: 19386, dtype: int64
内部标识号    19388
交易次数         3
交易金额       437
Name: 19387, dtype: int64
内部标识号    19389
交易次数         5
交易金额       139
Name: 19388, dtype: int64
内部标识号    19390
交易次数         0
交易金额      6452
Name: 19389, dtype: int64
内部标识号    19391
交易次数        13
交易金额       525
Name: 19390, dtype: int64
内部标识号    19392
交易次数        62
交易金额     92419
Name: 19391, dtype: int64
内部标识号    19393
交易次数        29
交易金额       587
Name: 19392, dtype: int64
内部标识号    19394
交易次数         3
交易金额       460
Name: 19393, dtype: int64
内部标识号    19395
交易次数         1
交易金额      9360
Name: 19394, dtype: int64
内部标识号    19396
交易次数         7
交易金额       185
Name: 19395, dtype: int64
内部标识号    19397
交易次数         8
交易金额       174
Name: 19396, dtype: int64
内部标识号    19398
交易次数         9
交易金额       970
Name: 19397, dtype: int64
内部标识号    19399
交易次数         5
交易金额       219
Name: 19398, dtype: int64
内部标识号    19400
交易次数         2
交易金额       328
Name: 19399, dtype: int64
内部标识号    19401
交易次数         8
交易金额     81380
Name: 19400, dtype: int64
内部标识号    19402
交易次数         3
交易金额       263
Name: 19401, dtype: int64
内部标识号    19403
交易次数         8
交易金额       390
Name: 19402, dtype: int64
内部标识号    19404
交易次数        10
交易金额       718
Name: 19403, dtype: int64
内部标识号    19405
交易次数         2
交易金额       129
Name: 19404, dtype: int64
内部标识号    19406
交易次数        11
交易金额       826
Name: 19405, dtype: int64
内部标识号    19407
交易次数         5
交易金额       159
Name: 19406, dtype: int64
内部标识号    19408
交易次数         5
交易金额       139
Name: 19407, dtype: int64
内部标识号    19409
交易次数         2
交易金额       325
Name: 19408, dtype: int64
内部标识号    19410
交易次数         1
交易金额       855
Name: 19409, dtype: int64
内部标识号    19411
交易次数         2
交易金额       248
Name: 19410, dtype: int64
内部标识号    19412
交易次数         2
交易金额       373
Name: 19411, dtype: int64
内部标识号    19413
交易次数         3
交易金额       436
Name: 19412, dtype: int64
内部标识号    19414
交易次数         3
交易金额       354
Name: 19413, dtype: int64
内部标识号    19415
交易次数        10
交易金额       362
Name: 19414, dtype: int64
内部标识号    19416
交易次数         1
交易金额       593
Name: 19415, dtype: int64
内部标识号    19417
交易次数         4
交易金额       202
Name: 19416, dtype: int64
内部标识号    19418
交易次数        12
交易金额       536
Name: 19417, dtype: int64
内部标识号    19419
交易次数         0
交易金额      8539
Name: 19418, dtype: int64
内部标识号    19420
交易次数         1
交易金额      6745
Name: 19419, dtype: int64
内部标识号    19421
交易次数        15
交易金额       843
Name: 19420, dtype: int64
内部标识号    19422
交易次数         6
交易金额     20168
Name: 19421, dtype: int64
内部标识号    19423
交易次数        13
交易金额       613
Name: 19422, dtype: int64
内部标识号    19424
交易次数        19
交易金额      5873
Name: 19423, dtype: int64
内部标识号    19425
交易次数         4
交易金额       168
Name: 19424, dtype: int64
内部标识号    19426
交易次数       162
交易金额     78961
Name: 19425, dtype: int64
内部标识号    19427
交易次数         8
交易金额       214
Name: 19426, dtype: int64
内部标识号    19428
交易次数         1
交易金额       807
Name: 19427, dtype: int64
内部标识号    19429
交易次数         4
交易金额       111
Name: 19428, dtype: int64
内部标识号    19430
交易次数         3
交易金额       239
Name: 19429, dtype: int64
内部标识号    19431
交易次数         8
交易金额       884
Name: 19430, dtype: int64
内部标识号    19432
交易次数        26
交易金额        54
Name: 19431, dtype: int64
内部标识号    19433
交易次数        26
交易金额      7419
Name: 19432, dtype: int64
内部标识号    19434
交易次数         3
交易金额       499
Name: 19433, dtype: int64
内部标识号    19435
交易次数         0
交易金额      3960
Name: 19434, dtype: int64
内部标识号    19436
交易次数        25
交易金额      9222
Name: 19435, dtype: int64
内部标识号    19437
交易次数         3
交易金额     78205
Name: 19436, dtype: int64
内部标识号    19438
交易次数         2
交易金额       664
Name: 19437, dtype: int64
内部标识号    19439
交易次数         3
交易金额       495
Name: 19438, dtype: int64
内部标识号    19440
交易次数        25
交易金额       948
Name: 19439, dtype: int64
内部标识号    19441
交易次数        12
交易金额       393
Name: 19440, dtype: int64
内部标识号    19442
交易次数         3
交易金额       409
Name: 19441, dtype: int64
内部标识号    19443
交易次数         2
交易金额       778
Name: 19442, dtype: int64
内部标识号    19444
交易次数       178
交易金额     10469
Name: 19443, dtype: int64
内部标识号    19445
交易次数         4
交易金额       208
Name: 19444, dtype: int64
内部标识号    19446
交易次数         0
交易金额      3413
Name: 19445, dtype: int64
内部标识号    19447
交易次数        11
交易金额       720
Name: 19446, dtype: int64
内部标识号    19448
交易次数         6
交易金额       275
Name: 19447, dtype: int64
内部标识号    19449
交易次数        25
交易金额       959
Name: 19448, dtype: int64
内部标识号    19450
交易次数         3
交易金额       468
Name: 19449, dtype: int64
内部标识号    19451
交易次数         3
交易金额       224
Name: 19450, dtype: int64
内部标识号    19452
交易次数         3
交易金额       361
Name: 19451, dtype: int64
内部标识号    19453
交易次数        11
交易金额       403
Name: 19452, dtype: int64
内部标识号    19454
交易次数         5
交易金额       103
Name: 19453, dtype: int64
内部标识号    19455
交易次数        12
交易金额       408
Name: 19454, dtype: int64
内部标识号    19456
交易次数         9
交易金额       414
Name: 19455, dtype: int64
内部标识号    19457
交易次数         5
交易金额     87796
Name: 19456, dtype: int64
内部标识号    19458
交易次数         5
交易金额       186
Name: 19457, dtype: int64
内部标识号    19459
交易次数         4
交易金额       296
Name: 19458, dtype: int64
内部标识号    19460
交易次数         6
交易金额       271
Name: 19459, dtype: int64
内部标识号    19461
交易次数         1
交易金额      6194
Name: 19460, dtype: int64
内部标识号    19462
交易次数         2
交易金额       675
Name: 19461, dtype: int64
内部标识号    19463
交易次数         3
交易金额       444
Name: 19462, dtype: int64
内部标识号    19464
交易次数       171
交易金额     75181
Name: 19463, dtype: int64
内部标识号    19465
交易次数         4
交易金额       259
Name: 19464, dtype: int64
内部标识号    19466
交易次数         2
交易金额       103
Name: 19465, dtype: int64
内部标识号    19467
交易次数        25
交易金额       873
Name: 19466, dtype: int64
内部标识号    19468
交易次数         8
交易金额       818
Name: 19467, dtype: int64
内部标识号    19469
交易次数        11
交易金额       652
Name: 19468, dtype: int64
内部标识号    19470
交易次数         7
交易金额       158
Name: 19469, dtype: int64
内部标识号    19471
交易次数         4
交易金额       101
Name: 19470, dtype: int64
内部标识号    19472
交易次数        15
交易金额       746
Name: 19471, dtype: int64
内部标识号    19473
交易次数         6
交易金额       105
Name: 19472, dtype: int64
内部标识号    19474
交易次数         2
交易金额       117
Name: 19473, dtype: int64
内部标识号    19475
交易次数         5
交易金额       236
Name: 19474, dtype: int64
内部标识号    19476
交易次数         6
交易金额       285
Name: 19475, dtype: int64
内部标识号    19477
交易次数         1
交易金额       530
Name: 19476, dtype: int64
内部标识号    19478
交易次数         1
交易金额      1966
Name: 19477, dtype: int64
内部标识号    19479
交易次数         1
交易金额       739
Name: 19478, dtype: int64
内部标识号    19480
交易次数         1
交易金额      5823
Name: 19479, dtype: int64
内部标识号    19481
交易次数         9
交易金额       306
Name: 19480, dtype: int64
内部标识号    19482
交易次数         0
交易金额      7280
Name: 19481, dtype: int64
内部标识号    19483
交易次数         8
交易金额       191
Name: 19482, dtype: int64
内部标识号    19484
交易次数        14
交易金额       447
Name: 19483, dtype: int64
内部标识号    19485
交易次数         6
交易金额       286
Name: 19484, dtype: int64
内部标识号    19486
交易次数        13
交易金额       716
Name: 19485, dtype: int64
内部标识号    19487
交易次数       212
交易金额     59797
Name: 19486, dtype: int64
内部标识号    19488
交易次数        15
交易金额       915
Name: 19487, dtype: int64
内部标识号    19489
交易次数         2
交易金额       338
Name: 19488, dtype: int64
内部标识号    19490
交易次数         9
交易金额       521
Name: 19489, dtype: int64
内部标识号    19491
交易次数         5
交易金额     24746
Name: 19490, dtype: int64
内部标识号    19492
交易次数        11
交易金额       351
Name: 19491, dtype: int64
内部标识号    19493
交易次数         9
交易金额       505
Name: 19492, dtype: int64
内部标识号    19494
交易次数         9
交易金额       488
Name: 19493, dtype: int64
内部标识号    19495
交易次数        30
交易金额       990
Name: 19494, dtype: int64
内部标识号    19496
交易次数         0
交易金额      9346
Name: 19495, dtype: int64
内部标识号    19497
交易次数         2
交易金额       496
Name: 19496, dtype: int64
内部标识号    19498
交易次数        21
交易金额      3328
Name: 19497, dtype: int64
内部标识号    19499
交易次数        15
交易金额       788
Name: 19498, dtype: int64
内部标识号    19500
交易次数         8
交易金额       540
Name: 19499, dtype: int64
内部标识号    19501
交易次数         4
交易金额       263
Name: 19500, dtype: int64
内部标识号    19502
交易次数         2
交易金额       326
Name: 19501, dtype: int64
内部标识号    19503
交易次数        18
交易金额      2291
Name: 19502, dtype: int64
内部标识号    19504
交易次数         8
交易金额       201
Name: 19503, dtype: int64
内部标识号    19505
交易次数         8
交易金额       345
Name: 19504, dtype: int64
内部标识号    19506
交易次数         2
交易金额       360
Name: 19505, dtype: int64
内部标识号    19507
交易次数         2
交易金额       965
Name: 19506, dtype: int64
内部标识号    19508
交易次数        21
交易金额       758
Name: 19507, dtype: int64
内部标识号    19509
交易次数        28
交易金额       716
Name: 19508, dtype: int64
内部标识号    19510
交易次数        25
交易金额       560
Name: 19509, dtype: int64
内部标识号    19511
交易次数        14
交易金额       337
Name: 19510, dtype: int64
内部标识号    19512
交易次数        15
交易金额       480
Name: 19511, dtype: int64
内部标识号    19513
交易次数        10
交易金额       358
Name: 19512, dtype: int64
内部标识号    19514
交易次数        12
交易金额       729
Name: 19513, dtype: int64
内部标识号    19515
交易次数         3
交易金额     41579
Name: 19514, dtype: int64
内部标识号    19516
交易次数         1
交易金额       932
Name: 19515, dtype: int64
内部标识号    19517
交易次数        13
交易金额       947
Name: 19516, dtype: int64
内部标识号    19518
交易次数         7
交易金额       161
Name: 19517, dtype: int64
内部标识号    19519
交易次数         1
交易金额       888
Name: 19518, dtype: int64
内部标识号    19520
交易次数        10
交易金额       612
Name: 19519, dtype: int64
内部标识号    19521
交易次数         9
交易金额       463
Name: 19520, dtype: int64
内部标识号    19522
交易次数         3
交易金额       434
Name: 19521, dtype: int64
内部标识号    19523
交易次数         3
交易金额       294
Name: 19522, dtype: int64
内部标识号    19524
交易次数         4
交易金额       125
Name: 19523, dtype: int64
内部标识号    19525
交易次数         0
交易金额      4210
Name: 19524, dtype: int64
内部标识号    19526
交易次数         2
交易金额       835
Name: 19525, dtype: int64
内部标识号    19527
交易次数         2
交易金额       381
Name: 19526, dtype: int64
内部标识号    19528
交易次数        19
交易金额       842
Name: 19527, dtype: int64
内部标识号    19529
交易次数         2
交易金额       481
Name: 19528, dtype: int64
内部标识号    19530
交易次数        10
交易金额       908
Name: 19529, dtype: int64
内部标识号    19531
交易次数         8
交易金额       652
Name: 19530, dtype: int64
内部标识号    19532
交易次数        29
交易金额       638
Name: 19531, dtype: int64
内部标识号    19533

内部标识号    19751
交易次数         3
交易金额       271
Name: 19750, dtype: int64
内部标识号    19752
交易次数         2
交易金额       482
Name: 19751, dtype: int64
内部标识号    19753
交易次数        30
交易金额     64556
Name: 19752, dtype: int64
内部标识号    19754
交易次数        23
交易金额      1781
Name: 19753, dtype: int64
内部标识号    19755
交易次数         0
交易金额      1956
Name: 19754, dtype: int64
内部标识号    19756
交易次数         3
交易金额       369
Name: 19755, dtype: int64
内部标识号    19757
交易次数         7
交易金额       142
Name: 19756, dtype: int64
内部标识号    19758
交易次数         2
交易金额       557
Name: 19757, dtype: int64
内部标识号    19759
交易次数         4
交易金额       200
Name: 19758, dtype: int64
内部标识号    19760
交易次数         7
交易金额       154
Name: 19759, dtype: int64
内部标识号    19761
交易次数         2
交易金额       516
Name: 19760, dtype: int64
内部标识号    19762
交易次数         3
交易金额       452
Name: 19761, dtype: int64
内部标识号    19763
交易次数         2
交易金额       371
Name: 19762, dtype: int64
内部标识号    19764
交易次数         5
交易金额     57330
Name: 19763, dtype: int64
内部标识号    19765
交易次数         0
交易金额      7599
Name: 19764, dtype: int64
内部标识号    19766
交易次数        17
交易金额      5671
Name: 19765, dtype: int64
内部标识号    19767
交易次数         5
交易金额       240
Name: 19766, dtype: int64
内部标识号    19768
交易次数        15
交易金额       968
Name: 19767, dtype: int64
内部标识号    19769
交易次数        20
交易金额       929
Name: 19768, dtype: int64
内部标识号    19770
交易次数        14
交易金额       537
Name: 19769, dtype: int64
内部标识号    19771
交易次数        12
交易金额       490
Name: 19770, dtype: int64
内部标识号    19772
交易次数        12
交易金额       697
Name: 19771, dtype: int64
内部标识号    19773
交易次数         1
交易金额      2578
Name: 19772, dtype: int64
内部标识号    19774
交易次数        30
交易金额      6353
Name: 19773, dtype: int64
内部标识号    19775
交易次数         7
交易金额       261
Name: 19774, dtype: int64
内部标识号    19776
交易次数         8
交易金额       953
Name: 19775, dtype: int64
内部标识号    19777
交易次数         7
交易金额       201
Name: 19776, dtype: int64
内部标识号    19778
交易次数         3
交易金额       495
Name: 19777, dtype: int64
内部标识号    19779
交易次数         9
交易金额       776
Name: 19778, dtype: int64
内部标识号    19780
交易次数         2
交易金额       542
Name: 19779, dtype: int64
内部标识号    19781
交易次数         6
交易金额       231
Name: 19780, dtype: int64
内部标识号    19782
交易次数         3
交易金额       344
Name: 19781, dtype: int64
内部标识号    19783
交易次数         9
交易金额       504
Name: 19782, dtype: int64
内部标识号    19784
交易次数         2
交易金额       375
Name: 19783, dtype: int64
内部标识号    19785
交易次数         2
交易金额       875
Name: 19784, dtype: int64
内部标识号    19786
交易次数         3
交易金额       352
Name: 19785, dtype: int64
内部标识号    19787
交易次数        16
交易金额      2237
Name: 19786, dtype: int64
内部标识号    19788
交易次数         8
交易金额       256
Name: 19787, dtype: int64
内部标识号    19789
交易次数        10
交易金额       476
Name: 19788, dtype: int64
内部标识号    19790
交易次数        21
交易金额      7214
Name: 19789, dtype: int64
内部标识号    19791
交易次数        14
交易金额       623
Name: 19790, dtype: int64
内部标识号    19792
交易次数         2
交易金额       926
Name: 19791, dtype: int64
内部标识号    19793
交易次数        10
交易金额       776
Name: 19792, dtype: int64
内部标识号    19794
交易次数         1
交易金额       664
Name: 19793, dtype: int64
内部标识号    19795
交易次数         2
交易金额       713
Name: 19794, dtype: int64
内部标识号    19796
交易次数         5
交易金额       300
Name: 19795, dtype: int64
内部标识号    19797
交易次数        12
交易金额       971
Name: 19796, dtype: int64
内部标识号    19798
交易次数        14
交易金额       505
Name: 19797, dtype: int64
内部标识号    19799
交易次数         8
交易金额       897
Name: 19798, dtype: int64
内部标识号    19800
交易次数         1
交易金额       732
Name: 19799, dtype: int64
内部标识号    19801
交易次数         2
交易金额       352
Name: 19800, dtype: int64
内部标识号    19802
交易次数        10
交易金额       475
Name: 19801, dtype: int64
内部标识号    19803
交易次数        24
交易金额      6303
Name: 19802, dtype: int64
内部标识号    19804
交易次数         4
交易金额       115
Name: 19803, dtype: int64
内部标识号    19805
交易次数       123
交易金额     21251
Name: 19804, dtype: int64
内部标识号    19806
交易次数         8
交易金额       699
Name: 19805, dtype: int64
内部标识号    19807
交易次数         0
交易金额      8959
Name: 19806, dtype: int64
内部标识号    19808
交易次数        12
交易金额       364
Name: 19807, dtype: int64
内部标识号    19809
交易次数        14
交易金额       378
Name: 19808, dtype: int64
内部标识号    19810
交易次数        10
交易金额       454
Name: 19809, dtype: int64
内部标识号    19811
交易次数         2
交易金额       300
Name: 19810, dtype: int64
内部标识号    19812
交易次数         4
交易金额     58536
Name: 19811, dtype: int64
内部标识号    19813
交易次数         8
交易金额     15096
Name: 19812, dtype: int64
内部标识号    19814
交易次数         1
交易金额       506
Name: 19813, dtype: int64
内部标识号    19815
交易次数         3
交易金额       356
Name: 19814, dtype: int64
内部标识号    19816
交易次数        10
交易金额       400
Name: 19815, dtype: int64
内部标识号    19817
交易次数         6
交易金额       263
Name: 19816, dtype: int64
内部标识号    19818
交易次数         6
交易金额       230
Name: 19817, dtype: int64
内部标识号    19819
交易次数         3
交易金额       282
Name: 19818, dtype: int64
内部标识号    19820
交易次数         8
交易金额       109
Name: 19819, dtype: int64
内部标识号    19821
交易次数         2
交易金额       368
Name: 19820, dtype: int64
内部标识号    19822
交易次数        15
交易金额       988
Name: 19821, dtype: int64
内部标识号    19823
交易次数         3
交易金额       483
Name: 19822, dtype: int64
内部标识号    19824
交易次数         2
交易金额       323
Name: 19823, dtype: int64
内部标识号    19825
交易次数         7
交易金额       213
Name: 19824, dtype: int64
内部标识号    19826
交易次数         2
交易金额       645
Name: 19825, dtype: int64
内部标识号    19827
交易次数         0
交易金额      5519
Name: 19826, dtype: int64
内部标识号    19828
交易次数         8
交易金额       969
Name: 19827, dtype: int64
内部标识号    19829
交易次数        27
交易金额        43
Name: 19828, dtype: int64
内部标识号    19830
交易次数        28
交易金额      5184
Name: 19829, dtype: int64
内部标识号    19831
交易次数         2
交易金额       403
Name: 19830, dtype: int64
内部标识号    19832
交易次数         6
交易金额       223
Name: 19831, dtype: int64
内部标识号    19833
交易次数       110
交易金额     91539
Name: 19832, dtype: int64
内部标识号    19834
交易次数        11
交易金额       434
Name: 19833, dtype: int64
内部标识号    19835
交易次数         2
交易金额       312
Name: 19834, dtype: int64
内部标识号    19836
交易次数        10
交易金额       916
Name: 19835, dtype: int64
内部标识号    19837
交易次数        12
交易金额       856
Name: 19836, dtype: int64
内部标识号    19838
交易次数         9
交易金额       722
Name: 19837, dtype: int64
内部标识号    19839
交易次数        21
交易金额      5498
Name: 19838, dtype: int64
内部标识号    19840
交易次数         3
交易金额       368
Name: 19839, dtype: int64
内部标识号    19841
交易次数         2
交易金额       842
Name: 19840, dtype: int64
内部标识号    19842
交易次数        25
交易金额       781
Name: 19841, dtype: int64
内部标识号    19843
交易次数        29
交易金额        38
Name: 19842, dtype: int64
内部标识号    19844
交易次数         5
交易金额       180
Name: 19843, dtype: int64
内部标识号    19845
交易次数         1
交易金额       929
Name: 19844, dtype: int64
内部标识号    19846
交易次数        26
交易金额      5373
Name: 19845, dtype: int64
内部标识号    19847
交易次数         4
交易金额       207
Name: 19846, dtype: int64
内部标识号    19848
交易次数         1
交易金额       878
Name: 19847, dtype: int64
内部标识号    19849
交易次数         2
交易金额       465
Name: 19848, dtype: int64
内部标识号    19850
交易次数        10
交易金额       434
Name: 19849, dtype: int64
内部标识号    19851
交易次数         2
交易金额       383
Name: 19850, dtype: int64
内部标识号    19852
交易次数         6
交易金额       101
Name: 19851, dtype: int64
内部标识号    19853
交易次数        23
交易金额      7508
Name: 19852, dtype: int64
内部标识号    19854
交易次数        12
交易金额       367
Name: 19853, dtype: int64
内部标识号    19855
交易次数         2
交易金额       410
Name: 19854, dtype: int64
内部标识号    19856
交易次数         0
交易金额      4741
Name: 19855, dtype: int64
内部标识号    19857
交易次数        19
交易金额       531
Name: 19856, dtype: int64
内部标识号    19858
交易次数         0
交易金额      4085
Name: 19857, dtype: int64
内部标识号    19859
交易次数         1
交易金额       833
Name: 19858, dtype: int64
内部标识号    19860
交易次数         1
交易金额       651
Name: 19859, dtype: int64
内部标识号    19861
交易次数         2
交易金额       320
Name: 19860, dtype: int64
内部标识号    19862
交易次数         4
交易金额     37029
Name: 19861, dtype: int64
内部标识号    19863
交易次数         2
交易金额       465
Name: 19862, dtype: int64
内部标识号    19864
交易次数         1
交易金额       974
Name: 19863, dtype: int64
内部标识号    19865
交易次数        14
交易金额       666
Name: 19864, dtype: int64
内部标识号    19866
交易次数         5
交易金额       244
Name: 19865, dtype: int64
内部标识号    19867
交易次数         3
交易金额       390
Name: 19866, dtype: int64
内部标识号    19868
交易次数        11
交易金额       629
Name: 19867, dtype: int64
内部标识号    19869
交易次数        11
交易金额       457
Name: 19868, dtype: int64
内部标识号    19870
交易次数         9
交易金额       544
Name: 19869, dtype: int64
内部标识号    19871
交易次数        13
交易金额       665
Name: 19870, dtype: int64
内部标识号    19872
交易次数         2
交易金额       500
Name: 19871, dtype: int64
内部标识号    19873
交易次数        10
交易金额       504
Name: 19872, dtype: int64
内部标识号    19874
交易次数         2
交易金额       628
Name: 19873, dtype: int64
内部标识号    19875
交易次数         3
交易金额       272
Name: 19874, dtype: int64
内部标识号    19876
交易次数         6
交易金额       189
Name: 19875, dtype: int64
内部标识号    19877
交易次数         2
交易金额       376
Name: 19876, dtype: int64
内部标识号    19878
交易次数        15
交易金额       605
Name: 19877, dtype: int64
内部标识号    19879
交易次数         3
交易金额       382
Name: 19878, dtype: int64
内部标识号    19880
交易次数        22
交易金额       732
Name: 19879, dtype: int64
内部标识号    19881
交易次数         3
交易金额       445
Name: 19880, dtype: int64
内部标识号    19882
交易次数         2
交易金额       945
Name: 19881, dtype: int64
内部标识号    19883
交易次数        26
交易金额       760
Name: 19882, dtype: int64
内部标识号    19884
交易次数         9
交易金额       434
Name: 19883, dtype: int64
内部标识号    19885
交易次数         1
交易金额       501
Name: 19884, dtype: int64
内部标识号    19886
交易次数         6
交易金额       171
Name: 19885, dtype: int64
内部标识号    19887
交易次数         9
交易金额       937
Name: 19886, dtype: int64
内部标识号    19888
交易次数         9
交易金额       498
Name: 19887, dtype: int64
内部标识号    19889
交易次数         3
交易金额     13831
Name: 19888, dtype: int64
内部标识号    19890
交易次数         8
交易金额     11660
Name: 19889, dtype: int64
内部标识号    19891
交易次数         1
交易金额      5066
Name: 19890, dtype: int64
内部标识号    19892
交易次数         0
交易金额      5161
Name: 19891, dtype: int64
内部标识号    19893
交易次数        30
交易金额      2227
Name: 19892, dtype: int64
内部标识号    19894
交易次数        14
交易金额       540
Name: 19893, dtype: int64
内部标识号    19895
交易次数         9
交易金额       865
Name: 19894, dtype: int64
内部标识号    19896
交易次数        28
交易金额      1113
Name: 19895, dtype: int64
内部标识号    19897
交易次数        21
交易金额      7352
Name: 19896, dtype: int64
内部标识号    19898
交易次数        14
交易金额       912
Name: 19897, dtype: int64
内部标识号    19899
交易次数         7
交易金额     52693
Name: 19898, dtype: int64
内部标识号    19900
交易次数         0
交易金额      6337
Name: 19899, dtype: int64
内部标识号    19901
交易次数         9
交易金额       606
Name: 19900, dtype: int64
内部标识号    19902
交易次数         5
交易金额       154
Name: 19901, dtype: int64
内部标识号    19903
交易次数        12
交易金额       847
Name: 19902, dtype: int64
内部标识号    19904
交易次数        15
交易金额       341
Name: 19903, dtype: int64
内部标识号    19905
交易次数         2
交易金额       617
Name: 19904, dtype: int64
内部标识号    19906
交易次数        26
交易金额       610
Name: 19905, dtype: int64
内部标识号    19907
交易次数         7
交易金额       229
Name: 19906, dtype: int64
内部标识号    19908
交易次数         3
交易金额       440
Name: 19907, dtype: int64
内部标识号    19909
交易次数        14
交易金额       440
Name: 19908, dtype: int64
内部标识号    19910
交易次数        13
交易金额       323
Name: 19909, dtype: int64
内部标识号    19911
交易次数         1
交易金额       741
Name: 19910, dtype: int64
内部标识号    19912
交易次数         1
交易金额       613
Name: 19911, dtype: int64
内部标识号    19913
交易次数        16
交易金额      7296
Name: 19912, dtype: int64
内部标识号    19914
交易次数         3
交易金额       433
Name: 19913, dtype: int64
内部标识号    19915
交易次数         0
交易金额      1919
Name: 19914, dtype: int64
内部标识号    19916
交易次数         7
交易金额     48849
Name: 19915, dtype: int64
内部标识号    19917
交易次数         3
交易金额       402
Name: 19916, dtype: int64
内部标识号    19918
交易次数         6
交易金额     67498
Name: 19917, dtype: int64
内部标识号    19919
交易次数        18
交易金额      1124
Name: 19918, dtype: int64
内部标识号    19920
交易次数         2
交易金额       410
Name: 19919, dtype: int64
内部标识号    19921
交易次数        14
交易金额       605
Name: 19920, dtype: int64
内部标识号    19922
交易次数        12
交易金额       388
Name: 19921, dtype: int64
内部标识号    19923
交易次数         1
交易金额       908
Name: 19922, dtype: int64
内部标识号    19924
交易次数       249
交易金额     88925
Name: 19923, dtype: int64
内部标识号    19925
交易次数        10
交易金额       377
Name: 19924, dtype: int64
内部标识号    19926
交易次数         6
交易金额       255
Name: 19925, dtype: int64
内部标识号    19927
交易次数         3
交易金额       168
Name: 19926, dtype: int64
内部标识号    19928
交易次数         2
交易金额       393
Name: 19927, dtype: int64
内部标识号    19929
交易次数         8
交易金额       114
Name: 19928, dtype: int64
内部标识号    19930
交易次数        13
交易金额       464
Name: 19929, dtype: int64
内部标识号    19931
交易次数        23
交易金额       690
Name: 19930, dtype: int64
内部标识号    19932
交易次数         3
交易金额     88012
Name: 19931, dtype: int64
内部标识号    19933
交易次数        12
交易金额       587
Name: 19932, dtype: int64
内部标识号    19934
交易次数         3
交易金额       376
Name: 19933, dtype: int64
内部标识号    19935
交易次数         1
交易金额       809
Name: 19934, dtype: int64
内部标识号    19936
交易次数         9
交易金额       731
Name: 19935, dtype: int64
内部标识号    19937
交易次数         2
交易金额       306
Name: 19936, dtype: int64
内部标识号    19938
交易次数         3
交易金额       466
Name: 19937, dtype: int64
内部标识号    19939
交易次数         7
交易金额     21421
Name: 19938, dtype: int64
内部标识号    19940
交易次数         9
交易金额       618
Name: 19939, dtype: int64
内部标识号    19941
交易次数         2
交易金额       738
Name: 19940, dtype: int64
内部标识号    19942
交易次数         9
交易金额       725
Name: 19941, dtype: int64
内部标识号    19943
交易次数         7
交易金额       212
Name: 19942, dtype: int64
内部标识号    19944
交易次数         6
交易金额       153
Name: 19943, dtype: int64
内部标识号    19945
交易次数        15
交易金额       468
Name: 19944, dtype: int64
内部标识号    19946
交易次数         2
交易金额       134
Name: 19945, dtype: int64
内部标识号    19947
交易次数         8
交易金额       160
Name: 19946, dtype: int64
内部标识号    19948
交易次数         0
交易金额      5124
Name: 19947, dtype: int64
内部标识号    19949
交易次数         1
交易金额       616
Name: 19948, dtype: int64
内部标识号    19950
交易次数         6
交易金额     99294
Name: 19949, dtype: int64
内部标识号    19951
交易次数         2
交易金额       487
Name: 19950, dtype: int64
内部标识号    19952
交易次数        15
交易金额       852
Name: 19951, dtype: int64
内部标识号    19953
交易次数        33
交易金额     24393
Name: 19952, dtype: int64
内部标识号    19954
交易次数         5
交易金额       273
Name: 19953, dtype: int64
内部标识号    19955
交易次数         1
交易金额      3806
Name: 19954, dtype: int64
内部标识号    19956
交易次数        19
交易金额       622
Name: 19955, dtype: int64
内部标识号    19957
交易次数         5
交易金额       181
Name: 19956, dtype: int64
内部标识号    19958
交易次数        26
交易金额      8298
Name: 19957, dtype: int64
内部标识号    19959
交易次数         5
交易金额       187
Name: 19958, dtype: int64
内部标识号    19960
交易次数         3
交易金额       444
Name: 19959, dtype: int64
内部标识号    19961
交易次数        15
交易金额       629
Name: 19960, dtype: int64
内部标识号    19962
交易次数        25
交易金额       972
Name: 19961, dtype: int64
内部标识号    19963
交易次数        15
交易金额       877
Name: 19962, dtype: int64
内部标识号    19964
交易次数         9
交易金额       413
Name: 19963, dtype: int64
内部标识号    19965
交易次数         9
交易金额       378
Name: 19964, dtype: int64
内部标识号    19966
交易次数         2
交易金额       776
Name: 19965, dtype: int64
内部标识号    19967
交易次数         5
交易金额       249
Name: 19966, dtype: int64
内部标识号    19968
交易次数         8
交易金额       540
Name: 19967, dtype: int64
内部标识号    19969
交易次数       115
交易金额     16479
Name: 19968, dtype: int64
内部标识号    19970
交易次数         2
交易金额       117
Name: 19969, dtype: int64
内部标识号    19971
交易次数        12
交易金额       869
Name: 19970, dtype: int64
内部标识号    19972
交易次数         3
交易金额       422
Name: 19971, dtype: int64
内部标识号    19973
交易次数         0
交易金额      6643
Name: 19972, dtype: int64
内部标识号    19974
交易次数         2
交易金额       500
Name: 19973, dtype: int64
内部标识号    19975
交易次数        35
交易金额     42746
Name: 19974, dtype: int64
内部标识号    19976
交易次数         8
交易金额       149
Name: 19975, dtype: int64
内部标识号    19977
交易次数       114
交易金额     38421
Name: 19976, dtype: int64
内部标识号    19978
交易次数         8
交易金额       530
Name: 19977, dtype: int64
内部标识号    19979
交易次数        13
交易金额       539
Name: 19978, dtype: int64
内部标识号    19980
交易次数         1
交易金额      1509
Name: 19979, dtype: int64
内部标识号    19981
交易次数         2
交易金额       314
Name: 19980, dtype: int64
内部标识号    19982
交易次数         7
交易金额       120
Name: 19981, dtype: int64
内部标识号    19983
交易次数       285
交易金额     28079
Name: 19982, dtype: int64
内部标识号    19984
交易次数        18
交易金额      7629
Name: 19983, dtype: int64
内部标识号    19985
交易次数         0
交易金额      6875
Name: 19984, dtype: int64
内部标识号    19986
交易次数         5
交易金额       290
Name: 19985, dtype: int64
内部标识号    19987
交易次数         3
交易金额       400
Name: 19986, dtype: int64
内部标识号    19988
交易次数         3
交易金额       478
Name: 19987, dtype: int64
内部标识号    19989
交易次数        88
交易金额     68853
Name: 19988, dtype: int64
内部标识号    19990
交易次数         5
交易金额       119
Name: 19989, dtype: int64
内部标识号    19991
交易次数        10
交易金额       859
Name: 19990, dtype: int64
内部标识号    19992
交易次数         1
交易金额       623
Name: 19991, dtype: int64
内部标识号    19993
交易次数       234
交易金额     39960
Name: 19992, dtype: int64
内部标识号    19994
交易次数         6
交易金额       293
Name: 19993, dtype: int64
内部标识号    19995
交易次数       134
交易金额     20159
Name: 19994, dtype: int64
内部标识号    19996
交易次数         3
交易金额       152
Name: 19995, dtype: int64
内部标识号    19997
交易次数         8
交易金额     93963
Name: 19996, dtype: int64
内部标识号    19998
交易次数         1
交易金额       747
Name: 19997, dtype: int64
内部标识号    19999
交易次数         1
交易金额      4055
Name: 19998, dtype: int64
内部标识号    20000
交易次数        15
交易金额       458
Name: 19999, dtype: int64
内部标识号    20001
交易次数         2
交易金额       402
Name: 20000, dtype: int64
内部标识号    20002
交易次数        12
交易金额       239
Name: 20001, dtype: int64
内部标识号    20003
交易次数         8
交易金额       183
Name: 20002, dtype: int64
内部标识号    20004
交易次数         1
交易金额       682
Name: 20003, dtype: int64
内部标识号    20005
交易次数         6
交易金额       401
Name: 20004, dtype: int64
内部标识号    20006
交易次数         3
交易金额       421
Name: 20005, dtype: int64
内部标识号    20007
交易次数         8
交易金额       263
Name: 20006, dtype: int64
内部标识号    20008
交易次数        11
交易金额       104
Name: 20007, dtype: int64
内部标识号    20009
交易次数         2
交易金额       373
Name: 20008, dtype: int64
内部标识号    20010
交易次数        29
交易金额       796
Name: 20009, dtype: int64
内部标识号    20011
交易次数         1
交易金额       252
Name: 20010, dtype: int64
内部标识号    20012
交易次数         8
交易金额       326
Name: 20011, dtype: int64
内部标识号    20013
交易次数         3
交易金额       419
Name: 20012, dtype: int64
内部标识号    20014
交易次数         7
交易金额      5386
Name: 20013, dtype: int64
内部标识号    20015
交易次数        26
交易金额       670
Name: 20014, dtype: int64
内部标识号    20016
交易次数         8
交易金额      1195
Name: 20015, dtype: int64
内部标识号    20017
交易次数         4
交易金额      3291
Name: 20016, dtype: int64
内部标识号    20018
交易次数         2
交易金额       742
Name: 20017, dtype: int64
内部标识号    20019
交易次数         3
交易金额       421
Name: 20018, dtype: int64
内部标识号    20020
交易次数         3
交易金额       381
Name: 20019, dtype: int64
内部标识号    20021
交易次数        19
交易金额       662
Name: 20020, dtype: int64
内部标识号    20022
交易次数         8
交易金额       308
Name: 20021, dtype: int64
内部标识号    20023
交易次数         0
交易金额     63921
Name: 20022, dtype: int64
内部标识号    20024
交易次数         7
交易金额      3192
Name: 20023, dtype: int64
内部标识号    20025
交易次数         3
交易金额       403
Name: 20024, dtype: int64
内部标识号    20026
交易次数         3
交易金额       393
Name: 20025, dtype: int64
内部标识号    20027
交易次数         3
交易金额      7589
Name: 20026, dtype: int64
内部标识号    20028
交易次数         7
交易金额      9139
Name: 20027, dtype: int64
内部标识号    20029
交易次数         0
交易金额       238
Name: 20028, dtype: int64
内部标识号    20030
交易次数         2
交易金额       328
Name: 20029, dtype: int64
内部标识号    20031
交易次数         8
交易金额      5196
Name: 20030, dtype: int64
内部标识号    20032
交易次数         1
交易金额       299

Name: 20249, dtype: int64
内部标识号    20251
交易次数         2
交易金额       490
Name: 20250, dtype: int64
内部标识号    20252
交易次数         3
交易金额       478
Name: 20251, dtype: int64
内部标识号    20253
交易次数         3
交易金额       329
Name: 20252, dtype: int64
内部标识号    20254
交易次数         2
交易金额       921
Name: 20253, dtype: int64
内部标识号    20255
交易次数        29
交易金额       621
Name: 20254, dtype: int64
内部标识号    20256
交易次数        12
交易金额       287
Name: 20255, dtype: int64
内部标识号    20257
交易次数         2
交易金额         5
Name: 20256, dtype: int64
内部标识号    20258
交易次数         2
交易金额       493
Name: 20257, dtype: int64
内部标识号    20259
交易次数         0
交易金额       219
Name: 20258, dtype: int64
内部标识号    20260
交易次数         8
交易金额       245
Name: 20259, dtype: int64
内部标识号    20261
交易次数         1
交易金额       978
Name: 20260, dtype: int64
内部标识号    20262
交易次数         2
交易金额       317
Name: 20261, dtype: int64
内部标识号    20263
交易次数         5
交易金额      1785
Name: 20262, dtype: int64
内部标识号    20264
交易次数         6
交易金额      8949
Name: 20263, dtype: int64
内部标识号    20265
交易次数         2
交易金额       515
Name: 20264, dtype: int64
内部标识号    20266
交易次数         0
交易金额       193
Name: 20265, dtype: int64
内部标识号    20267
交易次数         3
交易金额       407
Name: 20266, dtype: int64
内部标识号    20268
交易次数         6
交易金额       729
Name: 20267, dtype: int64
内部标识号    20269
交易次数         7
交易金额      7413
Name: 20268, dtype: int64
内部标识号    20270
交易次数         2
交易金额       321
Name: 20269, dtype: int64
内部标识号    20271
交易次数        24
交易金额       557
Name: 20270, dtype: int64
内部标识号    20272
交易次数         6
交易金额       453
Name: 20271, dtype: int64
内部标识号    20273
交易次数         1
交易金额       659
Name: 20272, dtype: int64
内部标识号    20274
交易次数         4
交易金额       837
Name: 20273, dtype: int64
内部标识号    20275
交易次数         5
交易金额      1269
Name: 20274, dtype: int64
内部标识号    20276
交易次数         0
交易金额       284
Name: 20275, dtype: int64
内部标识号    20277
交易次数         6
交易金额      7176
Name: 20276, dtype: int64
内部标识号    20278
交易次数         8
交易金额      4342
Name: 20277, dtype: int64
内部标识号    20279
交易次数         2
交易金额       866
Name: 20278, dtype: int64
内部标识号    20280
交易次数         2
交易金额     73362
Name: 20279, dtype: int64
内部标识号    20281
交易次数         1
交易金额       781
Name: 20280, dtype: int64
内部标识号    20282
交易次数         2
交易金额       531
Name: 20281, dtype: int64
内部标识号    20283
交易次数         3
交易金额       319
Name: 20282, dtype: int64
内部标识号    20284
交易次数         2
交易金额       457
Name: 20283, dtype: int64
内部标识号    20285
交易次数         1
交易金额       294
Name: 20284, dtype: int64
内部标识号    20286
交易次数         2
交易金额       451
Name: 20285, dtype: int64
内部标识号    20287
交易次数         1
交易金额       160
Name: 20286, dtype: int64
内部标识号    20288
交易次数         1
交易金额        45
Name: 20287, dtype: int64
内部标识号    20289
交易次数         3
交易金额      8686
Name: 20288, dtype: int64
内部标识号    20290
交易次数         7
交易金额      7955
Name: 20289, dtype: int64
内部标识号    20291
交易次数         2
交易金额       602
Name: 20290, dtype: int64
内部标识号    20292
交易次数         8
交易金额      7749
Name: 20291, dtype: int64
内部标识号    20293
交易次数         6
交易金额       500
Name: 20292, dtype: int64
内部标识号    20294
交易次数         0
交易金额     69694
Name: 20293, dtype: int64
内部标识号    20295
交易次数        14
交易金额       128
Name: 20294, dtype: int64
内部标识号    20296
交易次数         5
交易金额      6480
Name: 20295, dtype: int64
内部标识号    20297
交易次数         1
交易金额       846
Name: 20296, dtype: int64
内部标识号    20298
交易次数         3
交易金额       382
Name: 20297, dtype: int64
内部标识号    20299
交易次数         3
交易金额       476
Name: 20298, dtype: int64
内部标识号    20300
交易次数         2
交易金额       337
Name: 20299, dtype: int64
内部标识号    20301
交易次数         2
交易金额       885
Name: 20300, dtype: int64
内部标识号    20302
交易次数         2
交易金额       437
Name: 20301, dtype: int64
内部标识号    20303
交易次数         5
交易金额      7785
Name: 20302, dtype: int64
内部标识号    20304
交易次数         1
交易金额       534
Name: 20303, dtype: int64
内部标识号    20305
交易次数         1
交易金额        26
Name: 20304, dtype: int64
内部标识号    20306
交易次数        28
交易金额       778
Name: 20305, dtype: int64
内部标识号    20307
交易次数        12
交易金额       245
Name: 20306, dtype: int64
内部标识号    20308
交易次数         5
交易金额       488
Name: 20307, dtype: int64
内部标识号    20309
交易次数        10
交易金额       138
Name: 20308, dtype: int64
内部标识号    20310
交易次数         2
交易金额       473
Name: 20309, dtype: int64
内部标识号    20311
交易次数         3
交易金额       418
Name: 20310, dtype: int64
内部标识号    20312
交易次数         3
交易金额       351
Name: 20311, dtype: int64
内部标识号    20313
交易次数        11
交易金额       171
Name: 20312, dtype: int64
内部标识号    20314
交易次数         0
交易金额       215
Name: 20313, dtype: int64
内部标识号    20315
交易次数         3
交易金额       434
Name: 20314, dtype: int64
内部标识号    20316
交易次数         3
交易金额       485
Name: 20315, dtype: int64
内部标识号    20317
交易次数         3
交易金额       479
Name: 20316, dtype: int64
内部标识号    20318
交易次数         2
交易金额       378
Name: 20317, dtype: int64
内部标识号    20319
交易次数         0
交易金额     53261
Name: 20318, dtype: int64
内部标识号    20320
交易次数         1
交易金额       667
Name: 20319, dtype: int64
内部标识号    20321
交易次数        12
交易金额       103
Name: 20320, dtype: int64
内部标识号    20322
交易次数         0
交易金额     78646
Name: 20321, dtype: int64
内部标识号    20323
交易次数        22
交易金额       735
Name: 20322, dtype: int64
内部标识号    20324
交易次数         7
交易金额       476
Name: 20323, dtype: int64
内部标识号    20325
交易次数         2
交易金额       801
Name: 20324, dtype: int64
内部标识号    20326
交易次数         0
交易金额       139
Name: 20325, dtype: int64
内部标识号    20327
交易次数         0
交易金额     18193
Name: 20326, dtype: int64
内部标识号    20328
交易次数         7
交易金额      8899
Name: 20327, dtype: int64
内部标识号    20329
交易次数         3
交易金额       317
Name: 20328, dtype: int64
内部标识号    20330
交易次数        14
交易金额       296
Name: 20329, dtype: int64
内部标识号    20331
交易次数        11
交易金额       270
Name: 20330, dtype: int64
内部标识号    20332
交易次数         2
交易金额       472
Name: 20331, dtype: int64
内部标识号    20333
交易次数         3
交易金额      3309
Name: 20332, dtype: int64
内部标识号    20334
交易次数         2
交易金额       484
Name: 20333, dtype: int64
内部标识号    20335
交易次数         1
交易金额       592
Name: 20334, dtype: int64
内部标识号    20336
交易次数         2
交易金额       887
Name: 20335, dtype: int64
内部标识号    20337
交易次数         0
交易金额       196
Name: 20336, dtype: int64
内部标识号    20338
交易次数        26
交易金额       613
Name: 20337, dtype: int64
内部标识号    20339
交易次数         3
交易金额       318
Name: 20338, dtype: int64
内部标识号    20340
交易次数         0
交易金额       109
Name: 20339, dtype: int64
内部标识号    20341
交易次数         8
交易金额       309
Name: 20340, dtype: int64
内部标识号    20342
交易次数         0
交易金额       120
Name: 20341, dtype: int64
内部标识号    20343
交易次数         3
交易金额      2572
Name: 20342, dtype: int64
内部标识号    20344
交易次数        24
交易金额       676
Name: 20343, dtype: int64
内部标识号    20345
交易次数         3
交易金额       341
Name: 20344, dtype: int64
内部标识号    20346
交易次数        15
交易金额       131
Name: 20345, dtype: int64
内部标识号    20347
交易次数        24
交易金额       569
Name: 20346, dtype: int64
内部标识号    20348
交易次数         0
交易金额       107
Name: 20347, dtype: int64
内部标识号    20349
交易次数         3
交易金额       475
Name: 20348, dtype: int64
内部标识号    20350
交易次数         2
交易金额       519
Name: 20349, dtype: int64
内部标识号    20351
交易次数         3
交易金额       380
Name: 20350, dtype: int64
内部标识号    20352
交易次数        15
交易金额       511
Name: 20351, dtype: int64
内部标识号    20353
交易次数         7
交易金额      3524
Name: 20352, dtype: int64
内部标识号    20354
交易次数        20
交易金额       759
Name: 20353, dtype: int64
内部标识号    20355
交易次数        21
交易金额       586
Name: 20354, dtype: int64
内部标识号    20356
交易次数        29
交易金额       607
Name: 20355, dtype: int64
内部标识号    20357
交易次数         8
交易金额       494
Name: 20356, dtype: int64
内部标识号    20358
交易次数         1
交易金额        26
Name: 20357, dtype: int64
内部标识号    20359
交易次数         7
交易金额      2692
Name: 20358, dtype: int64
内部标识号    20360
交易次数         2
交易金额       481
Name: 20359, dtype: int64
内部标识号    20361
交易次数         3
交易金额       486
Name: 20360, dtype: int64
内部标识号    20362
交易次数         3
交易金额       458
Name: 20361, dtype: int64
内部标识号    20363
交易次数         3
交易金额       363
Name: 20362, dtype: int64
内部标识号    20364
交易次数         3
交易金额       450
Name: 20363, dtype: int64
内部标识号    20365
交易次数         2
交易金额       464
Name: 20364, dtype: int64
内部标识号    20366
交易次数         2
交易金额       447
Name: 20365, dtype: int64
内部标识号    20367
交易次数         1
交易金额       915
Name: 20366, dtype: int64
内部标识号    20368
交易次数        14
交易金额       107
Name: 20367, dtype: int64
内部标识号    20369
交易次数         0
交易金额     61990
Name: 20368, dtype: int64
内部标识号    20370
交易次数        13
交易金额       295
Name: 20369, dtype: int64
内部标识号    20371
交易次数         3
交易金额       435
Name: 20370, dtype: int64
内部标识号    20372
交易次数        21
交易金额       760
Name: 20371, dtype: int64
内部标识号    20373
交易次数         2
交易金额       316
Name: 20372, dtype: int64
内部标识号    20374
交易次数         0
交易金额     44109
Name: 20373, dtype: int64
内部标识号    20375
交易次数         0
交易金额     67542
Name: 20374, dtype: int64
内部标识号    20376
交易次数         1
交易金额       973
Name: 20375, dtype: int64
内部标识号    20377
交易次数        12
交易金额       286
Name: 20376, dtype: int64
内部标识号    20378
交易次数         2
交易金额     90503
Name: 20377, dtype: int64
内部标识号    20379
交易次数         4
交易金额       560
Name: 20378, dtype: int64
内部标识号    20380
交易次数         2
交易金额       347
Name: 20379, dtype: int64
内部标识号    20381
交易次数         0
交易金额       184
Name: 20380, dtype: int64
内部标识号    20382
交易次数         5
交易金额      3793
Name: 20381, dtype: int64
内部标识号    20383
交易次数         3
交易金额      9843
Name: 20382, dtype: int64
内部标识号    20384
交易次数         2
交易金额       416
Name: 20383, dtype: int64
内部标识号    20385
交易次数         2
交易金额       458
Name: 20384, dtype: int64
内部标识号    20386
交易次数         7
交易金额      7951
Name: 20385, dtype: int64
内部标识号    20387
交易次数         3
交易金额      2155
Name: 20386, dtype: int64
内部标识号    20388
交易次数         2
交易金额       585
Name: 20387, dtype: int64
内部标识号    20389
交易次数        64
交易金额     24343
Name: 20388, dtype: int64
内部标识号    20390
交易次数       223
交易金额     44472
Name: 20389, dtype: int64
内部标识号    20391
交易次数         2
交易金额       334
Name: 20390, dtype: int64
内部标识号    20392
交易次数         2
交易金额       431
Name: 20391, dtype: int64
内部标识号    20393
交易次数         2
交易金额       795
Name: 20392, dtype: int64
内部标识号    20394
交易次数         2
交易金额       461
Name: 20393, dtype: int64
内部标识号    20395
交易次数         2
交易金额       329
Name: 20394, dtype: int64
内部标识号    20396
交易次数         3
交易金额       331
Name: 20395, dtype: int64
内部标识号    20397
交易次数         3
交易金额      6033
Name: 20396, dtype: int64
内部标识号    20398
交易次数         2
交易金额       406
Name: 20397, dtype: int64
内部标识号    20399
交易次数         2
交易金额       318
Name: 20398, dtype: int64
内部标识号    20400
交易次数         3
交易金额       337
Name: 20399, dtype: int64
内部标识号    20401
交易次数        27
交易金额       904
Name: 20400, dtype: int64
内部标识号    20402
交易次数         2
交易金额        71
Name: 20401, dtype: int64
内部标识号    20403
交易次数         3
交易金额       362
Name: 20402, dtype: int64
内部标识号    20404
交易次数         3
交易金额       301
Name: 20403, dtype: int64
内部标识号    20405
交易次数        15
交易金额       145
Name: 20404, dtype: int64
内部标识号    20406
交易次数         1
交易金额       169
Name: 20405, dtype: int64
内部标识号    20407
交易次数         1
交易金额        35
Name: 20406, dtype: int64
内部标识号    20408
交易次数        14
交易金额       146
Name: 20407, dtype: int64
内部标识号    20409
交易次数         5
交易金额       724
Name: 20408, dtype: int64
内部标识号    20410
交易次数         0
交易金额     17591
Name: 20409, dtype: int64
内部标识号    20411
交易次数         1
交易金额       190
Name: 20410, dtype: int64
内部标识号    20412
交易次数         8
交易金额      7010
Name: 20411, dtype: int64
内部标识号    20413
交易次数         0
交易金额       250
Name: 20412, dtype: int64
内部标识号    20414
交易次数         0
交易金额       150
Name: 20413, dtype: int64
内部标识号    20415
交易次数         3
交易金额       353
Name: 20414, dtype: int64
内部标识号    20416
交易次数         3
交易金额       402
Name: 20415, dtype: int64
内部标识号    20417
交易次数         2
交易金额       320
Name: 20416, dtype: int64
内部标识号    20418
交易次数         6
交易金额      9840
Name: 20417, dtype: int64
内部标识号    20419
交易次数         3
交易金额       317
Name: 20418, dtype: int64
内部标识号    20420
交易次数         1
交易金额       129
Name: 20419, dtype: int64
内部标识号    20421
交易次数        13
交易金额       217
Name: 20420, dtype: int64
内部标识号    20422
交易次数         2
交易金额       843
Name: 20421, dtype: int64
内部标识号    20423
交易次数        14
交易金额       278
Name: 20422, dtype: int64
内部标识号    20424
交易次数         2
交易金额       424
Name: 20423, dtype: int64
内部标识号    20425
交易次数         3
交易金额       414
Name: 20424, dtype: int64
内部标识号    20426
交易次数        11
交易金额       153
Name: 20425, dtype: int64
内部标识号    20427
交易次数         2
交易金额       351
Name: 20426, dtype: int64
内部标识号    20428
交易次数         7
交易金额       357
Name: 20427, dtype: int64
内部标识号    20429
交易次数         2
交易金额       813
Name: 20428, dtype: int64
内部标识号    20430
交易次数         5
交易金额      3901
Name: 20429, dtype: int64
内部标识号    20431
交易次数         3
交易金额       357
Name: 20430, dtype: int64
内部标识号    20432
交易次数         1
交易金额       292
Name: 20431, dtype: int64
内部标识号    20433
交易次数         7
交易金额      6212
Name: 20432, dtype: int64
内部标识号    20434
交易次数         4
交易金额      2434
Name: 20433, dtype: int64
内部标识号    20435
交易次数         2
交易金额       408
Name: 20434, dtype: int64
内部标识号    20436
交易次数        16
交易金额       877
Name: 20435, dtype: int64
内部标识号    20437
交易次数         4
交易金额      8100
Name: 20436, dtype: int64
内部标识号    20438
交易次数         2
交易金额       407
Name: 20437, dtype: int64
内部标识号    20439
交易次数         2
交易金额       733
Name: 20438, dtype: int64
内部标识号    20440
交易次数         3
交易金额       369
Name: 20439, dtype: int64
内部标识号    20441
交易次数         8
交易金额       352
Name: 20440, dtype: int64
内部标识号    20442
交易次数         3
交易金额       377
Name: 20441, dtype: int64
内部标识号    20443
交易次数        21
交易金额       812
Name: 20442, dtype: int64
内部标识号    20444
交易次数         1
交易金额       140
Name: 20443, dtype: int64
内部标识号    20445
交易次数         2
交易金额       907
Name: 20444, dtype: int64
内部标识号    20446
交易次数        10
交易金额       131
Name: 20445, dtype: int64
内部标识号    20447
交易次数         1
交易金额       691
Name: 20446, dtype: int64
内部标识号    20448
交易次数         1
交易金额       105
Name: 20447, dtype: int64
内部标识号    20449
交易次数         2
交易金额       331
Name: 20448, dtype: int64
内部标识号    20450
交易次数         3
交易金额      2058
Name: 20449, dtype: int64
内部标识号    20451
交易次数         1
交易金额       504
Name: 20450, dtype: int64
内部标识号    20452
交易次数         2
交易金额       444
Name: 20451, dtype: int64
内部标识号    20453
交易次数         8
交易金额       291
Name: 20452, dtype: int64
内部标识号    20454
交易次数         0
交易金额     48038
Name: 20453, dtype: int64
内部标识号    20455
交易次数         1
交易金额       988
Name: 20454, dtype: int64
内部标识号    20456
交易次数         0
交易金额       229
Name: 20455, dtype: int64
内部标识号    20457
交易次数         2
交易金额       719
Name: 20456, dtype: int64
内部标识号    20458
交易次数         1
交易金额       300
Name: 20457, dtype: int64
内部标识号    20459
交易次数         1
交易金额       616
Name: 20458, dtype: int64
内部标识号    20460
交易次数         1
交易金额       250
Name: 20459, dtype: int64
内部标识号    20461
交易次数         1
交易金额       688
Name: 20460, dtype: int64
内部标识号    20462
交易次数         1
交易金额       286
Name: 20461, dtype: int64
内部标识号    20463
交易次数         2
交易金额       389
Name: 20462, dtype: int64
内部标识号    20464
交易次数         2
交易金额       953
Name: 20463, dtype: int64
内部标识号    20465
交易次数         2
交易金额       310
Name: 20464, dtype: int64
内部标识号    20466
交易次数        12
交易金额       198
Name: 20465, dtype: int64
内部标识号    20467
交易次数         1
交易金额        34
Name: 20466, dtype: int64
内部标识号    20468
交易次数         1
交易金额       264
Name: 20467, dtype: int64
内部标识号    20469
交易次数         3
交易金额       381
Name: 20468, dtype: int64
内部标识号    20470
交易次数         3
交易金额       336
Name: 20469, dtype: int64
内部标识号    20471
交易次数         7
交易金额      2449
Name: 20470, dtype: int64
内部标识号    20472
交易次数         3
交易金额       355
Name: 20471, dtype: int64
内部标识号    20473
交易次数         5
交易金额      3885
Name: 20472, dtype: int64
内部标识号    20474
交易次数         0
交易金额       244
Name: 20473, dtype: int64
内部标识号    20475
交易次数        10
交易金额       131
Name: 20474, dtype: int64
内部标识号    20476
交易次数        15
交易金额       266
Name: 20475, dtype: int64
内部标识号    20477
交易次数         1
交易金额       796
Name: 20476, dtype: int64
内部标识号    20478
交易次数         2
交易金额       486
Name: 20477, dtype: int64
内部标识号    20479
交易次数         3
交易金额       453
Name: 20478, dtype: int64
内部标识号    20480
交易次数         2
交易金额       318
Name: 20479, dtype: int64
内部标识号    20481
交易次数        11
交易金额       119
Name: 20480, dtype: int64
内部标识号    20482
交易次数         1
交易金额       531
Name: 20481, dtype: int64
内部标识号    20483
交易次数         2
交易金额       308
Name: 20482, dtype: int64
内部标识号    20484
交易次数         5
交易金额       385
Name: 20483, dtype: int64
内部标识号    20485
交易次数         7
交易金额       329
Name: 20484, dtype: int64
内部标识号    20486
交易次数         4
交易金额       440
Name: 20485, dtype: int64
内部标识号    20487
交易次数         2
交易金额       370
Name: 20486, dtype: int64
内部标识号    20488
交易次数         3
交易金额       300
Name: 20487, dtype: int64
内部标识号    20489
交易次数         1
交易金额        22
Name: 20488, dtype: int64
内部标识号    20490
交易次数         4
交易金额      1991
Name: 20489, dtype: int64
内部标识号    20491
交易次数         2
交易金额       651
Name: 20490, dtype: int64
内部标识号    20492
交易次数         2
交易金额       865
Name: 20491, dtype: int64
内部标识号    20493
交易次数         3
交易金额      4299
Name: 20492, dtype: int64
内部标识号    20494
交易次数         0
交易金额       205
Name: 20493, dtype: int64
内部标识号    20495
交易次数         1
交易金额        21
Name: 20494, dtype: int64
内部标识号    20496
交易次数         6
交易金额       436
Name: 20495, dtype: int64
内部标识号    20497
交易次数         2
交易金额       510
Name: 20496, dtype: int64
内部标识号    20498
交易次数         3
交易金额       315
Name: 20497, dtype: int64
内部标识号    20499
交易次数         2
交易金额       326
Name: 20498, dtype: int64
内部标识号    20500
交易次数         0
交易金额     20513
Name: 20499, dtype: int64
内部标识号    20501
交易次数         3
交易金额       328
Name: 20500, dtype: int64
内部标识号    20502
交易次数       170
交易金额     42237
Name: 20501, dtype: int64
内部标识号    20503
交易次数         7
交易金额      2808
Name: 20502, dtype: int64
内部标识号    20504
交易次数         9
交易金额       227
Name: 20503, dtype: int64
内部标识号    20505
交易次数         1
交易金额       954
Name: 20504, dtype: int64
内部标识号    20506
交易次数         2
交易金额       388
Name: 20505, dtype: int64
内部标识号    20507
交易次数         1
交易金额       772
Name: 20506, dtype: int64
内部标识号    20508
交易次数         2
交易金额       494
Name: 20507, dtype: int64
内部标识号    20509
交易次数         2
交易金额     63435
Name: 20508, dtype: int64
内部标识号    20510
交易次数         3
交易金额       396
Name: 20509, dtype: int64
内部标识号    20511
交易次数         2
交易金额       418
Name: 20510, dtype: int64
内部标识号    20512
交易次数       267
交易金额     41491
Name: 20511, dtype: int64
内部标识号    20513
交易次数         3
交易金额       346
Name: 20512, dtype: int64
内部标识号    20514
交易次数         1
交易金额       883
Name: 20513, dtype: int64
内部标识号    20515
交易次数         3
交易金额       338
Name: 20514, dtype: int64
内部标识号    20516
交易次数         0
交易金额     14213
Name: 20515, dtype: int64
内部标识号    20517
交易次数         2
交易金额       346
Name: 20516, dtype: int64
内部标识号    20518
交易次数         1
交易金额       138
Name: 20517, dtype: int64
内部标识号    20519
交易次数         3
交易金额      5259
Name: 20518, dtype: int64
内部标识号    20520
交易次数         2
交易金额       467
Name: 20519, dtype: int64
内部标识号    20521
交易次数         3
交易金额       419
Name: 20520, dtype: int64
内部标识号    20522
交易次数         1
交易金额       959
Name: 20521, dtype: int64
内部标识号    20523
交易次数         1
交易金额       844
Name: 20522, dtype: int64
内部标识号    20524
交易次数         3
交易金额       496
Name: 20523, dtype: int64
内部标识号    20525
交易次数         3
交易金额       343
Name: 20524, dtype: int64
内部标识号    20526
交易次数         0
交易金额       260
Name: 20525, dtype: int64
内部标识号    20527
交易次数        12
交易金额       199
Name: 20526, dtype: int64
内部标识号    20528
交易次数         1
交易金额       821
Name: 20527, dtype: int64
内部标识号    20529
交易次数         0
交易金额       229
Name: 20528, dtype: int64
内部标识号    20530
交易次数        14
交易金额       291
Name: 20529, dtype: int64
内部标识号    20531
交易次数        23
交易金额       808
Name: 20530, dtype: int64
内部标识号    20532

内部标识号    20750
交易次数         3
交易金额       310
Name: 20749, dtype: int64
内部标识号    20751
交易次数         1
交易金额       250
Name: 20750, dtype: int64
内部标识号    20752
交易次数         8
交易金额       345
Name: 20751, dtype: int64
内部标识号    20753
交易次数         7
交易金额      4440
Name: 20752, dtype: int64
内部标识号    20754
交易次数         3
交易金额       331
Name: 20753, dtype: int64
内部标识号    20755
交易次数         2
交易金额       473
Name: 20754, dtype: int64
内部标识号    20756
交易次数         1
交易金额       131
Name: 20755, dtype: int64
内部标识号    20757
交易次数         3
交易金额       366
Name: 20756, dtype: int64
内部标识号    20758
交易次数         2
交易金额        63
Name: 20757, dtype: int64
内部标识号    20759
交易次数         1
交易金额       650
Name: 20758, dtype: int64
内部标识号    20760
交易次数         3
交易金额       312
Name: 20759, dtype: int64
内部标识号    20761
交易次数         3
交易金额       322
Name: 20760, dtype: int64
内部标识号    20762
交易次数         2
交易金额       373
Name: 20761, dtype: int64
内部标识号    20763
交易次数         3
交易金额       330
Name: 20762, dtype: int64
内部标识号    20764
交易次数         6
交易金额      3688
Name: 20763, dtype: int64
内部标识号    20765
交易次数        18
交易金额       741
Name: 20764, dtype: int64
内部标识号    20766
交易次数       282
交易金额     26119
Name: 20765, dtype: int64
内部标识号    20767
交易次数         2
交易金额       411
Name: 20766, dtype: int64
内部标识号    20768
交易次数         2
交易金额       912
Name: 20767, dtype: int64
内部标识号    20769
交易次数         0
交易金额     33308
Name: 20768, dtype: int64
内部标识号    20770
交易次数         3
交易金额       467
Name: 20769, dtype: int64
内部标识号    20771
交易次数         4
交易金额      2981
Name: 20770, dtype: int64
内部标识号    20772
交易次数         1
交易金额       567
Name: 20771, dtype: int64
内部标识号    20773
交易次数         0
交易金额     33178
Name: 20772, dtype: int64
内部标识号    20774
交易次数         1
交易金额       761
Name: 20773, dtype: int64
内部标识号    20775
交易次数         2
交易金额       651
Name: 20774, dtype: int64
内部标识号    20776
交易次数        10
交易金额       223
Name: 20775, dtype: int64
内部标识号    20777
交易次数         3
交易金额       313
Name: 20776, dtype: int64
内部标识号    20778
交易次数         2
交易金额       807
Name: 20777, dtype: int64
内部标识号    20779
交易次数         5
交易金额      5659
Name: 20778, dtype: int64
内部标识号    20780
交易次数         1
交易金额       211
Name: 20779, dtype: int64
内部标识号    20781
交易次数         2
交易金额       397
Name: 20780, dtype: int64
内部标识号    20782
交易次数         7
交易金额       384
Name: 20781, dtype: int64
内部标识号    20783
交易次数         4
交易金额      5644
Name: 20782, dtype: int64
内部标识号    20784
交易次数        13
交易金额       125
Name: 20783, dtype: int64
内部标识号    20785
交易次数         2
交易金额       491
Name: 20784, dtype: int64
内部标识号    20786
交易次数         8
交易金额       449
Name: 20785, dtype: int64
内部标识号    20787
交易次数         2
交易金额       455
Name: 20786, dtype: int64
内部标识号    20788
交易次数         8
交易金额      1454
Name: 20787, dtype: int64
内部标识号    20789
交易次数        29
交易金额       653
Name: 20788, dtype: int64
内部标识号    20790
交易次数         2
交易金额       485
Name: 20789, dtype: int64
内部标识号    20791
交易次数         0
交易金额     99671
Name: 20790, dtype: int64
内部标识号    20792
交易次数         0
交易金额     26868
Name: 20791, dtype: int64
内部标识号    20793
交易次数         2
交易金额       383
Name: 20792, dtype: int64
内部标识号    20794
交易次数        10
交易金额       177
Name: 20793, dtype: int64
内部标识号    20795
交易次数         2
交易金额       839
Name: 20794, dtype: int64
内部标识号    20796
交易次数         2
交易金额       456
Name: 20795, dtype: int64
内部标识号    20797
交易次数         5
交易金额      6787
Name: 20796, dtype: int64
内部标识号    20798
交易次数         5
交易金额      7650
Name: 20797, dtype: int64
内部标识号    20799
交易次数         6
交易金额      4264
Name: 20798, dtype: int64
内部标识号    20800
交易次数         3
交易金额       353
Name: 20799, dtype: int64
内部标识号    20801
交易次数         8
交易金额       483
Name: 20800, dtype: int64
内部标识号    20802
交易次数        15
交易金额       554
Name: 20801, dtype: int64
内部标识号    20803
交易次数         2
交易金额       441
Name: 20802, dtype: int64
内部标识号    20804
交易次数         2
交易金额       300
Name: 20803, dtype: int64
内部标识号    20805
交易次数         8
交易金额       842
Name: 20804, dtype: int64
内部标识号    20806
交易次数        12
交易金额       177
Name: 20805, dtype: int64
内部标识号    20807
交易次数        11
交易金额       141
Name: 20806, dtype: int64
内部标识号    20808
交易次数         2
交易金额       317
Name: 20807, dtype: int64
内部标识号    20809
交易次数         7
交易金额       728
Name: 20808, dtype: int64
内部标识号    20810
交易次数         3
交易金额      8241
Name: 20809, dtype: int64
内部标识号    20811
交易次数         3
交易金额       476
Name: 20810, dtype: int64
内部标识号    20812
交易次数         1
交易金额       509
Name: 20811, dtype: int64
内部标识号    20813
交易次数         0
交易金额       200
Name: 20812, dtype: int64
内部标识号    20814
交易次数         0
交易金额     76260
Name: 20813, dtype: int64
内部标识号    20815
交易次数         3
交易金额       342
Name: 20814, dtype: int64
内部标识号    20816
交易次数         3
交易金额       315
Name: 20815, dtype: int64
内部标识号    20817
交易次数        24
交易金额       933
Name: 20816, dtype: int64
内部标识号    20818
交易次数         2
交易金额       438
Name: 20817, dtype: int64
内部标识号    20819
交易次数         2
交易金额       454
Name: 20818, dtype: int64
内部标识号    20820
交易次数         1
交易金额       603
Name: 20819, dtype: int64
内部标识号    20821
交易次数         3
交易金额       356
Name: 20820, dtype: int64
内部标识号    20822
交易次数         1
交易金额       259
Name: 20821, dtype: int64
内部标识号    20823
交易次数         2
交易金额       414
Name: 20822, dtype: int64
内部标识号    20824
交易次数         6
交易金额      7647
Name: 20823, dtype: int64
内部标识号    20825
交易次数         3
交易金额       315
Name: 20824, dtype: int64
内部标识号    20826
交易次数         2
交易金额       332
Name: 20825, dtype: int64
内部标识号    20827
交易次数         3
交易金额       404
Name: 20826, dtype: int64
内部标识号    20828
交易次数       240
交易金额     99473
Name: 20827, dtype: int64
内部标识号    20829
交易次数         3
交易金额       371
Name: 20828, dtype: int64
内部标识号    20830
交易次数        13
交易金额       113
Name: 20829, dtype: int64
内部标识号    20831
交易次数         8
交易金额      9930
Name: 20830, dtype: int64
内部标识号    20832
交易次数         1
交易金额       763
Name: 20831, dtype: int64
内部标识号    20833
交易次数         3
交易金额       302
Name: 20832, dtype: int64
内部标识号    20834
交易次数         3
交易金额       439
Name: 20833, dtype: int64
内部标识号    20835
交易次数         3
交易金额       375
Name: 20834, dtype: int64
内部标识号    20836
交易次数         1
交易金额       504
Name: 20835, dtype: int64
内部标识号    20837
交易次数        16
交易金额       643
Name: 20836, dtype: int64
内部标识号    20838
交易次数         0
交易金额       142
Name: 20837, dtype: int64
内部标识号    20839
交易次数        21
交易金额       871
Name: 20838, dtype: int64
内部标识号    20840
交易次数        95
交易金额     29842
Name: 20839, dtype: int64
内部标识号    20841
交易次数         5
交易金额      5789
Name: 20840, dtype: int64
内部标识号    20842
交易次数        19
交易金额       929
Name: 20841, dtype: int64
内部标识号    20843
交易次数         3
交易金额       346
Name: 20842, dtype: int64
内部标识号    20844
交易次数         2
交易金额       957
Name: 20843, dtype: int64
内部标识号    20845
交易次数         3
交易金额       469
Name: 20844, dtype: int64
内部标识号    20846
交易次数         2
交易金额       778
Name: 20845, dtype: int64
内部标识号    20847
交易次数         2
交易金额       550
Name: 20846, dtype: int64
内部标识号    20848
交易次数         8
交易金额       272
Name: 20847, dtype: int64
内部标识号    20849
交易次数         1
交易金额       515
Name: 20848, dtype: int64
内部标识号    20850
交易次数         2
交易金额       326
Name: 20849, dtype: int64
内部标识号    20851
交易次数         2
交易金额        45
Name: 20850, dtype: int64
内部标识号    20852
交易次数         1
交易金额       761
Name: 20851, dtype: int64
内部标识号    20853
交易次数         7
交易金额      5188
Name: 20852, dtype: int64
内部标识号    20854
交易次数        12
交易金额       119
Name: 20853, dtype: int64
内部标识号    20855
交易次数        24
交易金额       733
Name: 20854, dtype: int64
内部标识号    20856
交易次数         4
交易金额      9177
Name: 20855, dtype: int64
内部标识号    20857
交易次数         7
交易金额      4377
Name: 20856, dtype: int64
内部标识号    20858
交易次数         2
交易金额     27293
Name: 20857, dtype: int64
内部标识号    20859
交易次数         1
交易金额       720
Name: 20858, dtype: int64
内部标识号    20860
交易次数         8
交易金额       455
Name: 20859, dtype: int64
内部标识号    20861
交易次数         8
交易金额      1815
Name: 20860, dtype: int64
内部标识号    20862
交易次数         2
交易金额       697
Name: 20861, dtype: int64
内部标识号    20863
交易次数         9
交易金额       269
Name: 20862, dtype: int64
内部标识号    20864
交易次数        15
交易金额       104
Name: 20863, dtype: int64
内部标识号    20865
交易次数         3
交易金额       332
Name: 20864, dtype: int64
内部标识号    20866
交易次数         3
交易金额       367
Name: 20865, dtype: int64
内部标识号    20867
交易次数         2
交易金额       420
Name: 20866, dtype: int64
内部标识号    20868
交易次数         4
交易金额       484
Name: 20867, dtype: int64
内部标识号    20869
交易次数        54
交易金额     31098
Name: 20868, dtype: int64
内部标识号    20870
交易次数       234
交易金额     94895
Name: 20869, dtype: int64
内部标识号    20871
交易次数         0
交易金额     27521
Name: 20870, dtype: int64
内部标识号    20872
交易次数         3
交易金额       351
Name: 20871, dtype: int64
内部标识号    20873
交易次数        18
交易金额       751
Name: 20872, dtype: int64
内部标识号    20874
交易次数         1
交易金额        96
Name: 20873, dtype: int64
内部标识号    20875
交易次数        15
交易金额       130
Name: 20874, dtype: int64
内部标识号    20876
交易次数         7
交易金额       335
Name: 20875, dtype: int64
内部标识号    20877
交易次数         1
交易金额       515
Name: 20876, dtype: int64
内部标识号    20878
交易次数         3
交易金额       496
Name: 20877, dtype: int64
内部标识号    20879
交易次数         0
交易金额       219
Name: 20878, dtype: int64
内部标识号    20880
交易次数         0
交易金额       286
Name: 20879, dtype: int64
内部标识号    20881
交易次数         2
交易金额       326
Name: 20880, dtype: int64
内部标识号    20882
交易次数         4
交易金额      1549
Name: 20881, dtype: int64
内部标识号    20883
交易次数        13
交易金额       130
Name: 20882, dtype: int64
内部标识号    20884
交易次数         0
交易金额       270
Name: 20883, dtype: int64
内部标识号    20885
交易次数         0
交易金额     33192
Name: 20884, dtype: int64
内部标识号    20886
交易次数         0
交易金额     22470
Name: 20885, dtype: int64
内部标识号    20887
交易次数         2
交易金额       363
Name: 20886, dtype: int64
内部标识号    20888
交易次数         1
交易金额       724
Name: 20887, dtype: int64
内部标识号    20889
交易次数         3
交易金额       380
Name: 20888, dtype: int64
内部标识号    20890
交易次数         8
交易金额       241
Name: 20889, dtype: int64
内部标识号    20891
交易次数         1
交易金额       939
Name: 20890, dtype: int64
内部标识号    20892
交易次数         2
交易金额       426
Name: 20891, dtype: int64
内部标识号    20893
交易次数         9
交易金额       195
Name: 20892, dtype: int64
内部标识号    20894
交易次数         5
交易金额      5116
Name: 20893, dtype: int64
内部标识号    20895
交易次数         6
交易金额      9035
Name: 20894, dtype: int64
内部标识号    20896
交易次数         8
交易金额       248
Name: 20895, dtype: int64
内部标识号    20897
交易次数         3
交易金额       372
Name: 20896, dtype: int64
内部标识号    20898
交易次数        12
交易金额       267
Name: 20897, dtype: int64
内部标识号    20899
交易次数         1
交易金额       140
Name: 20898, dtype: int64
内部标识号    20900
交易次数         4
交易金额      1782
Name: 20899, dtype: int64
内部标识号    20901
交易次数         7
交易金额      1523
Name: 20900, dtype: int64
内部标识号    20902
交易次数        41
交易金额     89482
Name: 20901, dtype: int64
内部标识号    20903
交易次数         1
交易金额       917
Name: 20902, dtype: int64
内部标识号    20904
交易次数         3
交易金额       306
Name: 20903, dtype: int64
内部标识号    20905
交易次数         2
交易金额       410
Name: 20904, dtype: int64
内部标识号    20906
交易次数        12
交易金额       147
Name: 20905, dtype: int64
内部标识号    20907
交易次数        10
交易金额       269
Name: 20906, dtype: int64
内部标识号    20908
交易次数         1
交易金额       182
Name: 20907, dtype: int64
内部标识号    20909
交易次数         3
交易金额       465
Name: 20908, dtype: int64
内部标识号    20910
交易次数         3
交易金额       412
Name: 20909, dtype: int64
内部标识号    20911
交易次数         2
交易金额       365
Name: 20910, dtype: int64
内部标识号    20912
交易次数         2
交易金额     57412
Name: 20911, dtype: int64
内部标识号    20913
交易次数         6
交易金额       310
Name: 20912, dtype: int64
内部标识号    20914
交易次数         9
交易金额       178
Name: 20913, dtype: int64
内部标识号    20915
交易次数         1
交易金额       772
Name: 20914, dtype: int64
内部标识号    20916
交易次数         1
交易金额       195
Name: 20915, dtype: int64
内部标识号    20917
交易次数         2
交易金额       942
Name: 20916, dtype: int64
内部标识号    20918
交易次数        15
交易金额       578
Name: 20917, dtype: int64
内部标识号    20919
交易次数         3
交易金额       484
Name: 20918, dtype: int64
内部标识号    20920
交易次数         3
交易金额       461
Name: 20919, dtype: int64
内部标识号    20921
交易次数         6
交易金额       867
Name: 20920, dtype: int64
内部标识号    20922
交易次数         2
交易金额       374
Name: 20921, dtype: int64
内部标识号    20923
交易次数         3
交易金额       332
Name: 20922, dtype: int64
内部标识号    20924
交易次数        11
交易金额       280
Name: 20923, dtype: int64
内部标识号    20925
交易次数         3
交易金额       467
Name: 20924, dtype: int64
内部标识号    20926
交易次数         2
交易金额       345
Name: 20925, dtype: int64
内部标识号    20927
交易次数        12
交易金额       154
Name: 20926, dtype: int64
内部标识号    20928
交易次数         2
交易金额       429
Name: 20927, dtype: int64
内部标识号    20929
交易次数         0
交易金额     29277
Name: 20928, dtype: int64
内部标识号    20930
交易次数        11
交易金额       161
Name: 20929, dtype: int64
内部标识号    20931
交易次数         6
交易金额      4081
Name: 20930, dtype: int64
内部标识号    20932
交易次数         0
交易金额     53071
Name: 20931, dtype: int64
内部标识号    20933
交易次数         4
交易金额      3654
Name: 20932, dtype: int64
内部标识号    20934
交易次数         2
交易金额       366
Name: 20933, dtype: int64
内部标识号    20935
交易次数         0
交易金额       276
Name: 20934, dtype: int64
内部标识号    20936
交易次数        12
交易金额       297
Name: 20935, dtype: int64
内部标识号    20937
交易次数        13
交易金额       255
Name: 20936, dtype: int64
内部标识号    20938
交易次数         6
交易金额      8427
Name: 20937, dtype: int64
内部标识号    20939
交易次数         6
交易金额       994
Name: 20938, dtype: int64
内部标识号    20940
交易次数         1
交易金额     91717
Name: 20939, dtype: int64
内部标识号    20941
交易次数         1
交易金额        71
Name: 20940, dtype: int64
内部标识号    20942
交易次数         3
交易金额       496
Name: 20941, dtype: int64
内部标识号    20943
交易次数        16
交易金额       712
Name: 20942, dtype: int64
内部标识号    20944
交易次数         3
交易金额       410
Name: 20943, dtype: int64
内部标识号    20945
交易次数         8
交易金额       460
Name: 20944, dtype: int64
内部标识号    20946
交易次数         6
交易金额       308
Name: 20945, dtype: int64
内部标识号    20947
交易次数         2
交易金额       826
Name: 20946, dtype: int64
内部标识号    20948
交易次数        13
交易金额       181
Name: 20947, dtype: int64
内部标识号    20949
交易次数         2
交易金额       479
Name: 20948, dtype: int64
内部标识号    20950
交易次数         1
交易金额       195
Name: 20949, dtype: int64
内部标识号    20951
交易次数         4
交易金额       315
Name: 20950, dtype: int64
内部标识号    20952
交易次数         1
交易金额       162
Name: 20951, dtype: int64
内部标识号    20953
交易次数         2
交易金额       486
Name: 20952, dtype: int64
内部标识号    20954
交易次数         5
交易金额       419
Name: 20953, dtype: int64
内部标识号    20955
交易次数         2
交易金额       679
Name: 20954, dtype: int64
内部标识号    20956
交易次数         4
交易金额      4812
Name: 20955, dtype: int64
内部标识号    20957
交易次数         2
交易金额       363
Name: 20956, dtype: int64
内部标识号    20958
交易次数         1
交易金额       145
Name: 20957, dtype: int64
内部标识号    20959
交易次数         3
交易金额       495
Name: 20958, dtype: int64
内部标识号    20960
交易次数         2
交易金额       444
Name: 20959, dtype: int64
内部标识号    20961
交易次数         0
交易金额     80970
Name: 20960, dtype: int64
内部标识号    20962
交易次数         2
交易金额       344
Name: 20961, dtype: int64
内部标识号    20963
交易次数         2
交易金额        19
Name: 20962, dtype: int64
内部标识号    20964
交易次数         2
交易金额       790
Name: 20963, dtype: int64
内部标识号    20965
交易次数         2
交易金额       402
Name: 20964, dtype: int64
内部标识号    20966
交易次数         3
交易金额       346
Name: 20965, dtype: int64
内部标识号    20967
交易次数         2
交易金额       372
Name: 20966, dtype: int64
内部标识号    20968
交易次数         2
交易金额       446
Name: 20967, dtype: int64
内部标识号    20969
交易次数         3
交易金额       347
Name: 20968, dtype: int64
内部标识号    20970
交易次数         2
交易金额       372
Name: 20969, dtype: int64
内部标识号    20971
交易次数        27
交易金额       796
Name: 20970, dtype: int64
内部标识号    20972
交易次数         5
交易金额      4163
Name: 20971, dtype: int64
内部标识号    20973
交易次数         7
交易金额      4406
Name: 20972, dtype: int64
内部标识号    20974
交易次数         2
交易金额       367
Name: 20973, dtype: int64
内部标识号    20975
交易次数        12
交易金额       121
Name: 20974, dtype: int64
内部标识号    20976
交易次数         2
交易金额       414
Name: 20975, dtype: int64
内部标识号    20977
交易次数         1
交易金额       112
Name: 20976, dtype: int64
内部标识号    20978
交易次数         1
交易金额       771
Name: 20977, dtype: int64
内部标识号    20979
交易次数         2
交易金额       493
Name: 20978, dtype: int64
内部标识号    20980
交易次数        12
交易金额       283
Name: 20979, dtype: int64
内部标识号    20981
交易次数         3
交易金额       441
Name: 20980, dtype: int64
内部标识号    20982
交易次数         7
交易金额       481
Name: 20981, dtype: int64
内部标识号    20983
交易次数         7
交易金额      8947
Name: 20982, dtype: int64
内部标识号    20984
交易次数         1
交易金额       146
Name: 20983, dtype: int64
内部标识号    20985
交易次数         0
交易金额       232
Name: 20984, dtype: int64
内部标识号    20986
交易次数         3
交易金额       312
Name: 20985, dtype: int64
内部标识号    20987
交易次数         3
交易金额       445
Name: 20986, dtype: int64
内部标识号    20988
交易次数         2
交易金额       944
Name: 20987, dtype: int64
内部标识号    20989
交易次数         2
交易金额       699
Name: 20988, dtype: int64
内部标识号    20990
交易次数         1
交易金额       291
Name: 20989, dtype: int64
内部标识号    20991
交易次数         6
交易金额       367
Name: 20990, dtype: int64
内部标识号    20992
交易次数         1
交易金额       140
Name: 20991, dtype: int64
内部标识号    20993
交易次数         3
交易金额       630
Name: 20992, dtype: int64
内部标识号    20994
交易次数         3
交易金额       364
Name: 20993, dtype: int64
内部标识号    20995
交易次数       158
交易金额     46241
Name: 20994, dtype: int64
内部标识号    20996
交易次数        11
交易金额       162
Name: 20995, dtype: int64
内部标识号    20997
交易次数        13
交易金额       256
Name: 20996, dtype: int64
内部标识号    20998
交易次数         7
交易金额      2538
Name: 20997, dtype: int64
内部标识号    20999
交易次数        19
交易金额       845
Name: 20998, dtype: int64
内部标识号    21000
交易次数         3
交易金额       392
Name: 20999, dtype: int64
内部标识号    21001
交易次数        10
交易金额       241
Name: 21000, dtype: int64
内部标识号    21002
交易次数         0
交易金额       158
Name: 21001, dtype: int64
内部标识号    21003
交易次数         5
交易金额       420
Name: 21002, dtype: int64
内部标识号    21004
交易次数         2
交易金额       311
Name: 21003, dtype: int64
内部标识号    21005
交易次数         2
交易金额       629
Name: 21004, dtype: int64
内部标识号    21006
交易次数         1
交易金额       680
Name: 21005, dtype: int64
内部标识号    21007
交易次数         3
交易金额       474
Name: 21006, dtype: int64
内部标识号    21008
交易次数         5
交易金额      2627
Name: 21007, dtype: int64
内部标识号    21009
交易次数         2
交易金额       427
Name: 21008, dtype: int64
内部标识号    21010
交易次数        12
交易金额       155
Name: 21009, dtype: int64
内部标识号    21011
交易次数        13
交易金额       248
Name: 21010, dtype: int64
内部标识号    21012
交易次数        26
交易金额       928
Name: 21011, dtype: int64
内部标识号    21013
交易次数         3
交易金额       385
Name: 21012, dtype: int64
内部标识号    21014
交易次数         2
交易金额       369
Name: 21013, dtype: int64
内部标识号    21015
交易次数         1
交易金额       635
Name: 21014, dtype: int64
内部标识号    21016
交易次数         2
交易金额       417
Name: 21015, dtype: int64
内部标识号    21017
交易次数         8
交易金额       472
Name: 21016, dtype: int64
内部标识号    21018
交易次数         2
交易金额        23
Name: 21017, dtype: int64
内部标识号    21019
交易次数        17
交易金额       968
Name: 21018, dtype: int64
内部标识号    21020
交易次数         3
交易金额       351
Name: 21019, dtype: int64
内部标识号    21021
交易次数         0
交易金额     61143
Name: 21020, dtype: int64
内部标识号    21022
交易次数         1
交易金额       633
Name: 21021, dtype: int64
内部标识号    21023
交易次数        18
交易金额       792
Name: 21022, dtype: int64
内部标识号    21024
交易次数         1
交易金额       704
Name: 21023, dtype: int64
内部标识号    21025
交易次数         1
交易金额       581
Name: 21024, dtype: int64
内部标识号    21026
交易次数         5
交易金额      2331
Name: 21025, dtype: int64
内部标识号    21027
交易次数         3
交易金额       313
Name: 21026, dtype: int64
内部标识号    21028
交易次数       169
交易金额     67963
Name: 21027, dtype: int64
内部标识号    21029
交易次数        10
交易金额       120
Name: 21028, dtype: int64
内部标识号    21030
交易次数         0
交易金额       247
Name: 21029, dtype: int64
内部标识号    21031
交易次数         1
交易金额        10

Name: 21248, dtype: int64
内部标识号    21250
交易次数         1
交易金额       295
Name: 21249, dtype: int64
内部标识号    21251
交易次数         1
交易金额       217
Name: 21250, dtype: int64
内部标识号    21252
交易次数         4
交易金额       386
Name: 21251, dtype: int64
内部标识号    21253
交易次数         2
交易金额       331
Name: 21252, dtype: int64
内部标识号    21254
交易次数         0
交易金额     65543
Name: 21253, dtype: int64
内部标识号    21255
交易次数       196
交易金额     75622
Name: 21254, dtype: int64
内部标识号    21256
交易次数         2
交易金额       379
Name: 21255, dtype: int64
内部标识号    21257
交易次数         6
交易金额      5547
Name: 21256, dtype: int64
内部标识号    21258
交易次数         2
交易金额       367
Name: 21257, dtype: int64
内部标识号    21259
交易次数        10
交易金额       218
Name: 21258, dtype: int64
内部标识号    21260
交易次数         2
交易金额       402
Name: 21259, dtype: int64
内部标识号    21261
交易次数         3
交易金额       482
Name: 21260, dtype: int64
内部标识号    21262
交易次数         2
交易金额        32
Name: 21261, dtype: int64
内部标识号    21263
交易次数         1
交易金额       286
Name: 21262, dtype: int64
内部标识号    21264
交易次数         0
交易金额     48066
Name: 21263, dtype: int64
内部标识号    21265
交易次数         1
交易金额       106
Name: 21264, dtype: int64
内部标识号    21266
交易次数         3
交易金额       312
Name: 21265, dtype: int64
内部标识号    21267
交易次数         2
交易金额       335
Name: 21266, dtype: int64
内部标识号    21268
交易次数        13
交易金额       189
Name: 21267, dtype: int64
内部标识号    21269
交易次数         1
交易金额         0
Name: 21268, dtype: int64
内部标识号    21270
交易次数         7
交易金额      4414
Name: 21269, dtype: int64
内部标识号    21271
交易次数         2
交易金额       854
Name: 21270, dtype: int64
内部标识号    21272
交易次数        29
交易金额       706
Name: 21271, dtype: int64
内部标识号    21273
交易次数         7
交易金额      1229
Name: 21272, dtype: int64
内部标识号    21274
交易次数         0
交易金额     85286
Name: 21273, dtype: int64
内部标识号    21275
交易次数        12
交易金额       277
Name: 21274, dtype: int64
内部标识号    21276
交易次数        13
交易金额       154
Name: 21275, dtype: int64
内部标识号    21277
交易次数         3
交易金额       500
Name: 21276, dtype: int64
内部标识号    21278
交易次数         8
交易金额      5916
Name: 21277, dtype: int64
内部标识号    21279
交易次数         5
交易金额      4140
Name: 21278, dtype: int64
内部标识号    21280
交易次数         7
交易金额       341
Name: 21279, dtype: int64
内部标识号    21281
交易次数         6
交易金额      8914
Name: 21280, dtype: int64
内部标识号    21282
交易次数         4
交易金额       764
Name: 21281, dtype: int64
内部标识号    21283
交易次数         0
交易金额       256
Name: 21282, dtype: int64
内部标识号    21284
交易次数         2
交易金额        13
Name: 21283, dtype: int64
内部标识号    21285
交易次数         7
交易金额      9999
Name: 21284, dtype: int64
内部标识号    21286
交易次数         2
交易金额       506
Name: 21285, dtype: int64
内部标识号    21287
交易次数         7
交易金额      4083
Name: 21286, dtype: int64
内部标识号    21288
交易次数         0
交易金额     23700
Name: 21287, dtype: int64
内部标识号    21289
交易次数         1
交易金额       570
Name: 21288, dtype: int64
内部标识号    21290
交易次数         7
交易金额       488
Name: 21289, dtype: int64
内部标识号    21291
交易次数         2
交易金额       451
Name: 21290, dtype: int64
内部标识号    21292
交易次数         1
交易金额       131
Name: 21291, dtype: int64
内部标识号    21293
交易次数         1
交易金额       290
Name: 21292, dtype: int64
内部标识号    21294
交易次数         1
交易金额       129
Name: 21293, dtype: int64
内部标识号    21295
交易次数         2
交易金额       367
Name: 21294, dtype: int64
内部标识号    21296
交易次数         1
交易金额       723
Name: 21295, dtype: int64
内部标识号    21297
交易次数         3
交易金额       482
Name: 21296, dtype: int64
内部标识号    21298
交易次数         1
交易金额       537
Name: 21297, dtype: int64
内部标识号    21299
交易次数         0
交易金额       233
Name: 21298, dtype: int64
内部标识号    21300
交易次数         1
交易金额     59219
Name: 21299, dtype: int64
内部标识号    21301
交易次数         1
交易金额       945
Name: 21300, dtype: int64
内部标识号    21302
交易次数         6
交易金额      5211
Name: 21301, dtype: int64
内部标识号    21303
交易次数         2
交易金额       614
Name: 21302, dtype: int64
内部标识号    21304
交易次数         3
交易金额       383
Name: 21303, dtype: int64
内部标识号    21305
交易次数         3
交易金额       481
Name: 21304, dtype: int64
内部标识号    21306
交易次数         1
交易金额       942
Name: 21305, dtype: int64
内部标识号    21307
交易次数         2
交易金额       881
Name: 21306, dtype: int64
内部标识号    21308
交易次数         3
交易金额       390
Name: 21307, dtype: int64
内部标识号    21309
交易次数         1
交易金额        50
Name: 21308, dtype: int64
内部标识号    21310
交易次数         2
交易金额       913
Name: 21309, dtype: int64
内部标识号    21311
交易次数         2
交易金额       630
Name: 21310, dtype: int64
内部标识号    21312
交易次数        13
交易金额       234
Name: 21311, dtype: int64
内部标识号    21313
交易次数         2
交易金额       405
Name: 21312, dtype: int64
内部标识号    21314
交易次数         2
交易金额        87
Name: 21313, dtype: int64
内部标识号    21315
交易次数         2
交易金额       819
Name: 21314, dtype: int64
内部标识号    21316
交易次数         2
交易金额       845
Name: 21315, dtype: int64
内部标识号    21317
交易次数         2
交易金额       334
Name: 21316, dtype: int64
内部标识号    21318
交易次数         9
交易金额       232
Name: 21317, dtype: int64
内部标识号    21319
交易次数         2
交易金额     26888
Name: 21318, dtype: int64
内部标识号    21320
交易次数         0
交易金额       297
Name: 21319, dtype: int64
内部标识号    21321
交易次数        15
交易金额       266
Name: 21320, dtype: int64
内部标识号    21322
交易次数        10
交易金额       213
Name: 21321, dtype: int64
内部标识号    21323
交易次数         2
交易金额       390
Name: 21322, dtype: int64
内部标识号    21324
交易次数         2
交易金额       307
Name: 21323, dtype: int64
内部标识号    21325
交易次数        11
交易金额       271
Name: 21324, dtype: int64
内部标识号    21326
交易次数         8
交易金额       842
Name: 21325, dtype: int64
内部标识号    21327
交易次数        11
交易金额       221
Name: 21326, dtype: int64
内部标识号    21328
交易次数         2
交易金额       869
Name: 21327, dtype: int64
内部标识号    21329
交易次数         3
交易金额       457
Name: 21328, dtype: int64
内部标识号    21330
交易次数         0
交易金额     35972
Name: 21329, dtype: int64
内部标识号    21331
交易次数         1
交易金额       784
Name: 21330, dtype: int64
内部标识号    21332
交易次数         3
交易金额       436
Name: 21331, dtype: int64
内部标识号    21333
交易次数         3
交易金额      9101
Name: 21332, dtype: int64
内部标识号    21334
交易次数        26
交易金额       518
Name: 21333, dtype: int64
内部标识号    21335
交易次数         1
交易金额       152
Name: 21334, dtype: int64
内部标识号    21336
交易次数         1
交易金额       123
Name: 21335, dtype: int64
内部标识号    21337
交易次数        15
交易金额       276
Name: 21336, dtype: int64
内部标识号    21338
交易次数         2
交易金额       445
Name: 21337, dtype: int64
内部标识号    21339
交易次数        12
交易金额       200
Name: 21338, dtype: int64
内部标识号    21340
交易次数         8
交易金额      8261
Name: 21339, dtype: int64
内部标识号    21341
交易次数         7
交易金额      1565
Name: 21340, dtype: int64
内部标识号    21342
交易次数         2
交易金额       498
Name: 21341, dtype: int64
内部标识号    21343
交易次数         5
交易金额       388
Name: 21342, dtype: int64
内部标识号    21344
交易次数        11
交易金额       119
Name: 21343, dtype: int64
内部标识号    21345
交易次数         2
交易金额       353
Name: 21344, dtype: int64
内部标识号    21346
交易次数        15
交易金额       160
Name: 21345, dtype: int64
内部标识号    21347
交易次数        11
交易金额       144
Name: 21346, dtype: int64
内部标识号    21348
交易次数         0
交易金额     29039
Name: 21347, dtype: int64
内部标识号    21349
交易次数         2
交易金额       336
Name: 21348, dtype: int64
内部标识号    21350
交易次数         8
交易金额       371
Name: 21349, dtype: int64
内部标识号    21351
交易次数         2
交易金额       379
Name: 21350, dtype: int64
内部标识号    21352
交易次数         1
交易金额        71
Name: 21351, dtype: int64
内部标识号    21353
交易次数         3
交易金额       392
Name: 21352, dtype: int64
内部标识号    21354
交易次数         2
交易金额       888
Name: 21353, dtype: int64
内部标识号    21355
交易次数        13
交易金额       161
Name: 21354, dtype: int64
内部标识号    21356
交易次数        19
交易金额       715
Name: 21355, dtype: int64
内部标识号    21357
交易次数         2
交易金额       453
Name: 21356, dtype: int64
内部标识号    21358
交易次数        14
交易金额       137
Name: 21357, dtype: int64
内部标识号    21359
交易次数         2
交易金额       434
Name: 21358, dtype: int64
内部标识号    21360
交易次数         2
交易金额       604
Name: 21359, dtype: int64
内部标识号    21361
交易次数         2
交易金额       353
Name: 21360, dtype: int64
内部标识号    21362
交易次数         3
交易金额      2822
Name: 21361, dtype: int64
内部标识号    21363
交易次数         1
交易金额       107
Name: 21362, dtype: int64
内部标识号    21364
交易次数         3
交易金额       367
Name: 21363, dtype: int64
内部标识号    21365
交易次数         3
交易金额       316
Name: 21364, dtype: int64
内部标识号    21366
交易次数         1
交易金额       265
Name: 21365, dtype: int64
内部标识号    21367
交易次数         1
交易金额       788
Name: 21366, dtype: int64
内部标识号    21368
交易次数         1
交易金额       852
Name: 21367, dtype: int64
内部标识号    21369
交易次数         2
交易金额       357
Name: 21368, dtype: int64
内部标识号    21370
交易次数         0
交易金额       171
Name: 21369, dtype: int64
内部标识号    21371
交易次数         0
交易金额       243
Name: 21370, dtype: int64
内部标识号    21372
交易次数         5
交易金额      1290
Name: 21371, dtype: int64
内部标识号    21373
交易次数        12
交易金额       259
Name: 21372, dtype: int64
内部标识号    21374
交易次数         2
交易金额       755
Name: 21373, dtype: int64
内部标识号    21375
交易次数         2
交易金额       476
Name: 21374, dtype: int64
内部标识号    21376
交易次数         3
交易金额       482
Name: 21375, dtype: int64
内部标识号    21377
交易次数         3
交易金额       445
Name: 21376, dtype: int64
内部标识号    21378
交易次数         8
交易金额       173
Name: 21377, dtype: int64
内部标识号    21379
交易次数         4
交易金额      8920
Name: 21378, dtype: int64
内部标识号    21380
交易次数         0
交易金额     49108
Name: 21379, dtype: int64
内部标识号    21381
交易次数         2
交易金额       352
Name: 21380, dtype: int64
内部标识号    21382
交易次数         3
交易金额       420
Name: 21381, dtype: int64
内部标识号    21383
交易次数         2
交易金额       986
Name: 21382, dtype: int64
内部标识号    21384
交易次数         0
交易金额     26730
Name: 21383, dtype: int64
内部标识号    21385
交易次数         3
交易金额       338
Name: 21384, dtype: int64
内部标识号    21386
交易次数        29
交易金额       843
Name: 21385, dtype: int64
内部标识号    21387
交易次数        12
交易金额       228
Name: 21386, dtype: int64
内部标识号    21388
交易次数         8
交易金额       239
Name: 21387, dtype: int64
内部标识号    21389
交易次数        11
交易金额       219
Name: 21388, dtype: int64
内部标识号    21390
交易次数         0
交易金额     18144
Name: 21389, dtype: int64
内部标识号    21391
交易次数         1
交易金额       900
Name: 21390, dtype: int64
内部标识号    21392
交易次数         1
交易金额       742
Name: 21391, dtype: int64
内部标识号    21393
交易次数         1
交易金额       917
Name: 21392, dtype: int64
内部标识号    21394
交易次数         0
交易金额       108
Name: 21393, dtype: int64
内部标识号    21395
交易次数        11
交易金额       123
Name: 21394, dtype: int64
内部标识号    21396
交易次数         2
交易金额       364
Name: 21395, dtype: int64
内部标识号    21397
交易次数       153
交易金额     15226
Name: 21396, dtype: int64
内部标识号    21398
交易次数         1
交易金额       164
Name: 21397, dtype: int64
内部标识号    21399
交易次数         8
交易金额      4579
Name: 21398, dtype: int64
内部标识号    21400
交易次数         2
交易金额       326
Name: 21399, dtype: int64
内部标识号    21401
交易次数         0
交易金额     62076
Name: 21400, dtype: int64
内部标识号    21402
交易次数         8
交易金额      8240
Name: 21401, dtype: int64
内部标识号    21403
交易次数         4
交易金额      6305
Name: 21402, dtype: int64
内部标识号    21404
交易次数        10
交易金额       300
Name: 21403, dtype: int64
内部标识号    21405
交易次数        12
交易金额       106
Name: 21404, dtype: int64
内部标识号    21406
交易次数         4
交易金额       496
Name: 21405, dtype: int64
内部标识号    21407
交易次数         0
交易金额     75953
Name: 21406, dtype: int64
内部标识号    21408
交易次数         2
交易金额       375
Name: 21407, dtype: int64
内部标识号    21409
交易次数         0
交易金额     92974
Name: 21408, dtype: int64
内部标识号    21410
交易次数         1
交易金额       239
Name: 21409, dtype: int64
内部标识号    21411
交易次数         2
交易金额       394
Name: 21410, dtype: int64
内部标识号    21412
交易次数        12
交易金额       172
Name: 21411, dtype: int64
内部标识号    21413
交易次数         2
交易金额       982
Name: 21412, dtype: int64
内部标识号    21414
交易次数         8
交易金额      9535
Name: 21413, dtype: int64
内部标识号    21415
交易次数        11
交易金额       227
Name: 21414, dtype: int64
内部标识号    21416
交易次数         0
交易金额       268
Name: 21415, dtype: int64
内部标识号    21417
交易次数         0
交易金额     39416
Name: 21416, dtype: int64
内部标识号    21418
交易次数         0
交易金额       103
Name: 21417, dtype: int64
内部标识号    21419
交易次数         3
交易金额       539
Name: 21418, dtype: int64
内部标识号    21420
交易次数         3
交易金额       310
Name: 21419, dtype: int64
内部标识号    21421
交易次数         2
交易金额       444
Name: 21420, dtype: int64
内部标识号    21422
交易次数         2
交易金额       982
Name: 21421, dtype: int64
内部标识号    21423
交易次数        25
交易金额       585
Name: 21422, dtype: int64
内部标识号    21424
交易次数         0
交易金额     61191
Name: 21423, dtype: int64
内部标识号    21425
交易次数         3
交易金额       395
Name: 21424, dtype: int64
内部标识号    21426
交易次数         3
交易金额       395
Name: 21425, dtype: int64
内部标识号    21427
交易次数         1
交易金额       134
Name: 21426, dtype: int64
内部标识号    21428
交易次数         0
交易金额     65721
Name: 21427, dtype: int64
内部标识号    21429
交易次数        89
交易金额     41418
Name: 21428, dtype: int64
内部标识号    21430
交易次数         4
交易金额      1761
Name: 21429, dtype: int64
内部标识号    21431
交易次数         3
交易金额       356
Name: 21430, dtype: int64
内部标识号    21432
交易次数         2
交易金额     80295
Name: 21431, dtype: int64
内部标识号    21433
交易次数         9
交易金额       285
Name: 21432, dtype: int64
内部标识号    21434
交易次数         0
交易金额       291
Name: 21433, dtype: int64
内部标识号    21435
交易次数         1
交易金额       985
Name: 21434, dtype: int64
内部标识号    21436
交易次数         1
交易金额       863
Name: 21435, dtype: int64
内部标识号    21437
交易次数         8
交易金额       173
Name: 21436, dtype: int64
内部标识号    21438
交易次数         2
交易金额       330
Name: 21437, dtype: int64
内部标识号    21439
交易次数        17
交易金额       852
Name: 21438, dtype: int64
内部标识号    21440
交易次数         2
交易金额       337
Name: 21439, dtype: int64
内部标识号    21441
交易次数         5
交易金额      1426
Name: 21440, dtype: int64
内部标识号    21442
交易次数         0
交易金额       286
Name: 21441, dtype: int64
内部标识号    21443
交易次数         1
交易金额       294
Name: 21442, dtype: int64
内部标识号    21444
交易次数         2
交易金额       945
Name: 21443, dtype: int64
内部标识号    21445
交易次数         6
交易金额      8245
Name: 21444, dtype: int64
内部标识号    21446
交易次数         2
交易金额       851
Name: 21445, dtype: int64
内部标识号    21447
交易次数         3
交易金额      9381
Name: 21446, dtype: int64
内部标识号    21448
交易次数         4
交易金额      5084
Name: 21447, dtype: int64
内部标识号    21449
交易次数         3
交易金额       318
Name: 21448, dtype: int64
内部标识号    21450
交易次数         1
交易金额       109
Name: 21449, dtype: int64
内部标识号    21451
交易次数         1
交易金额       594
Name: 21450, dtype: int64
内部标识号    21452
交易次数         2
交易金额       906
Name: 21451, dtype: int64
内部标识号    21453
交易次数         2
交易金额       410
Name: 21452, dtype: int64
内部标识号    21454
交易次数         2
交易金额       335
Name: 21453, dtype: int64
内部标识号    21455
交易次数         2
交易金额       343
Name: 21454, dtype: int64
内部标识号    21456
交易次数        14
交易金额       234
Name: 21455, dtype: int64
内部标识号    21457
交易次数         2
交易金额       425
Name: 21456, dtype: int64
内部标识号    21458
交易次数         1
交易金额       198
Name: 21457, dtype: int64
内部标识号    21459
交易次数         1
交易金额       227
Name: 21458, dtype: int64
内部标识号    21460
交易次数         4
交易金额      5825
Name: 21459, dtype: int64
内部标识号    21461
交易次数         0
交易金额       249
Name: 21460, dtype: int64
内部标识号    21462
交易次数         2
交易金额       398
Name: 21461, dtype: int64
内部标识号    21463
交易次数         3
交易金额       361
Name: 21462, dtype: int64
内部标识号    21464
交易次数         7
交易金额       357
Name: 21463, dtype: int64
内部标识号    21465
交易次数         2
交易金额       629
Name: 21464, dtype: int64
内部标识号    21466
交易次数        27
交易金额       776
Name: 21465, dtype: int64
内部标识号    21467
交易次数         4
交易金额       877
Name: 21466, dtype: int64
内部标识号    21468
交易次数         1
交易金额       604
Name: 21467, dtype: int64
内部标识号    21469
交易次数         2
交易金额        98
Name: 21468, dtype: int64
内部标识号    21470
交易次数         3
交易金额       448
Name: 21469, dtype: int64
内部标识号    21471
交易次数         2
交易金额        92
Name: 21470, dtype: int64
内部标识号    21472
交易次数         3
交易金额      6372
Name: 21471, dtype: int64
内部标识号    21473
交易次数         1
交易金额       960
Name: 21472, dtype: int64
内部标识号    21474
交易次数         3
交易金额       452
Name: 21473, dtype: int64
内部标识号    21475
交易次数         4
交易金额       504
Name: 21474, dtype: int64
内部标识号    21476
交易次数         7
交易金额      8004
Name: 21475, dtype: int64
内部标识号    21477
交易次数         3
交易金额       440
Name: 21476, dtype: int64
内部标识号    21478
交易次数         0
交易金额     46871
Name: 21477, dtype: int64
内部标识号    21479
交易次数         3
交易金额       378
Name: 21478, dtype: int64
内部标识号    21480
交易次数         3
交易金额      4319
Name: 21479, dtype: int64
内部标识号    21481
交易次数         8
交易金额       242
Name: 21480, dtype: int64
内部标识号    21482
交易次数         2
交易金额       397
Name: 21481, dtype: int64
内部标识号    21483
交易次数         5
交易金额      9060
Name: 21482, dtype: int64
内部标识号    21484
交易次数         1
交易金额       133
Name: 21483, dtype: int64
内部标识号    21485
交易次数         3
交易金额       428
Name: 21484, dtype: int64
内部标识号    21486
交易次数        15
交易金额       243
Name: 21485, dtype: int64
内部标识号    21487
交易次数         0
交易金额     57636
Name: 21486, dtype: int64
内部标识号    21488
交易次数        19
交易金额       898
Name: 21487, dtype: int64
内部标识号    21489
交易次数         0
交易金额     74517
Name: 21488, dtype: int64
内部标识号    21490
交易次数         3
交易金额       426
Name: 21489, dtype: int64
内部标识号    21491
交易次数         7
交易金额       447
Name: 21490, dtype: int64
内部标识号    21492
交易次数        14
交易金额       112
Name: 21491, dtype: int64
内部标识号    21493
交易次数        10
交易金额       300
Name: 21492, dtype: int64
内部标识号    21494
交易次数         3
交易金额       367
Name: 21493, dtype: int64
内部标识号    21495
交易次数         1
交易金额       196
Name: 21494, dtype: int64
内部标识号    21496
交易次数         3
交易金额       452
Name: 21495, dtype: int64
内部标识号    21497
交易次数        10
交易金额       184
Name: 21496, dtype: int64
内部标识号    21498
交易次数         2
交易金额       330
Name: 21497, dtype: int64
内部标识号    21499
交易次数         0
交易金额     84474
Name: 21498, dtype: int64
内部标识号    21500
交易次数         2
交易金额       924
Name: 21499, dtype: int64
内部标识号    21501
交易次数        12
交易金额       256
Name: 21500, dtype: int64
内部标识号    21502
交易次数        17
交易金额       553
Name: 21501, dtype: int64
内部标识号    21503
交易次数        12
交易金额       203
Name: 21502, dtype: int64
内部标识号    21504
交易次数         4
交易金额       320
Name: 21503, dtype: int64
内部标识号    21505
交易次数         2
交易金额     43706
Name: 21504, dtype: int64
内部标识号    21506
交易次数         2
交易金额       498
Name: 21505, dtype: int64
内部标识号    21507
交易次数         4
交易金额       370
Name: 21506, dtype: int64
内部标识号    21508
交易次数         0
交易金额     34821
Name: 21507, dtype: int64
内部标识号    21509
交易次数        12
交易金额       290
Name: 21508, dtype: int64
内部标识号    21510
交易次数         7
交易金额      3094
Name: 21509, dtype: int64
内部标识号    21511
交易次数        11
交易金额       193
Name: 21510, dtype: int64
内部标识号    21512
交易次数         2
交易金额       401
Name: 21511, dtype: int64
内部标识号    21513
交易次数         2
交易金额       697
Name: 21512, dtype: int64
内部标识号    21514
交易次数         1
交易金额       576
Name: 21513, dtype: int64
内部标识号    21515
交易次数         1
交易金额       250
Name: 21514, dtype: int64
内部标识号    21516
交易次数         3
交易金额      7102
Name: 21515, dtype: int64
内部标识号    21517
交易次数         2
交易金额       570
Name: 21516, dtype: int64
内部标识号    21518
交易次数         3
交易金额       374
Name: 21517, dtype: int64
内部标识号    21519
交易次数         1
交易金额       559
Name: 21518, dtype: int64
内部标识号    21520
交易次数         2
交易金额       617
Name: 21519, dtype: int64
内部标识号    21521
交易次数         2
交易金额       684
Name: 21520, dtype: int64
内部标识号    21522
交易次数       171
交易金额     43097
Name: 21521, dtype: int64
内部标识号    21523
交易次数        12
交易金额       204
Name: 21522, dtype: int64
内部标识号    21524
交易次数         3
交易金额       334
Name: 21523, dtype: int64
内部标识号    21525
交易次数         2
交易金额       318
Name: 21524, dtype: int64
内部标识号    21526
交易次数         3
交易金额       310
Name: 21525, dtype: int64
内部标识号    21527
交易次数        16
交易金额       836
Name: 21526, dtype: int64
内部标识号    21528
交易次数         0
交易金额     47579
Name: 21527, dtype: int64
内部标识号    21529
交易次数         3
交易金额       448
Name: 21528, dtype: int64
内部标识号    21530
交易次数         2
交易金额       421
Name: 21529, dtype: int64
内部标识号    21531

Name: 21717, dtype: int64
内部标识号    21719
交易次数         9
交易金额       235
Name: 21718, dtype: int64
内部标识号    21720
交易次数         5
交易金额      2566
Name: 21719, dtype: int64
内部标识号    21721
交易次数         4
交易金额       831
Name: 21720, dtype: int64
内部标识号    21722
交易次数        26
交易金额       887
Name: 21721, dtype: int64
内部标识号    21723
交易次数         2
交易金额       437
Name: 21722, dtype: int64
内部标识号    21724
交易次数         3
交易金额       500
Name: 21723, dtype: int64
内部标识号    21725
交易次数        22
交易金额       875
Name: 21724, dtype: int64
内部标识号    21726
交易次数         4
交易金额      9675
Name: 21725, dtype: int64
内部标识号    21727
交易次数       288
交易金额     75941
Name: 21726, dtype: int64
内部标识号    21728
交易次数         3
交易金额       438
Name: 21727, dtype: int64
内部标识号    21729
交易次数         8
交易金额      9139
Name: 21728, dtype: int64
内部标识号    21730
交易次数         6
交易金额      8241
Name: 21729, dtype: int64
内部标识号    21731
交易次数         3
交易金额       407
Name: 21730, dtype: int64
内部标识号    21732
交易次数         2
交易金额       802
Name: 21731, dtype: int64
内部标识号    21733
交易次数         2
交易金额       753
Name: 21732, dtype: int64
内部标识号    21734
交易次数         0
交易金额       256
Name: 21733, dtype: int64
内部标识号    21735
交易次数         3
交易金额       306
Name: 21734, dtype: int64
内部标识号    21736
交易次数         6
交易金额       373
Name: 21735, dtype: int64
内部标识号    21737
交易次数         2
交易金额       452
Name: 21736, dtype: int64
内部标识号    21738
交易次数         2
交易金额       389
Name: 21737, dtype: int64
内部标识号    21739
交易次数         0
交易金额       207
Name: 21738, dtype: int64
内部标识号    21740
交易次数         1
交易金额       164
Name: 21739, dtype: int64
内部标识号    21741
交易次数        10
交易金额       234
Name: 21740, dtype: int64
内部标识号    21742
交易次数         8
交易金额       822
Name: 21741, dtype: int64
内部标识号    21743
交易次数         2
交易金额       395
Name: 21742, dtype: int64
内部标识号    21744
交易次数         0
交易金额     27982
Name: 21743, dtype: int64
内部标识号    21745
交易次数         7
交易金额       716
Name: 21744, dtype: int64
内部标识号    21746
交易次数         8
交易金额      1323
Name: 21745, dtype: int64
内部标识号    21747
交易次数         8
交易金额       962
Name: 21746, dtype: int64
内部标识号    21748
交易次数         0
交易金额     78545
Name: 21747, dtype: int64
内部标识号    21749
交易次数         5
交易金额       342
Name: 21748, dtype: int64
内部标识号    21750
交易次数         1
交易金额       905
Name: 21749, dtype: int64
内部标识号    21751
交易次数         3
交易金额       427
Name: 21750, dtype: int64
内部标识号    21752
交易次数         3
交易金额       355
Name: 21751, dtype: int64
内部标识号    21753
交易次数         1
交易金额       255
Name: 21752, dtype: int64
内部标识号    21754
交易次数        15
交易金额       136
Name: 21753, dtype: int64
内部标识号    21755
交易次数         3
交易金额       364
Name: 21754, dtype: int64
内部标识号    21756
交易次数        11
交易金额       153
Name: 21755, dtype: int64
内部标识号    21757
交易次数         3
交易金额      9785
Name: 21756, dtype: int64
内部标识号    21758
交易次数         8
交易金额      9917
Name: 21757, dtype: int64
内部标识号    21759
交易次数         8
交易金额      5429
Name: 21758, dtype: int64
内部标识号    21760
交易次数         3
交易金额       427
Name: 21759, dtype: int64
内部标识号    21761
交易次数        15
交易金额       784
Name: 21760, dtype: int64
内部标识号    21762
交易次数         9
交易金额       112
Name: 21761, dtype: int64
内部标识号    21763
交易次数         8
交易金额       179
Name: 21762, dtype: int64
内部标识号    21764
交易次数         1
交易金额       946
Name: 21763, dtype: int64
内部标识号    21765
交易次数         1
交易金额        80
Name: 21764, dtype: int64
内部标识号    21766
交易次数         2
交易金额       363
Name: 21765, dtype: int64
内部标识号    21767
交易次数         1
交易金额       959
Name: 21766, dtype: int64
内部标识号    21768
交易次数         5
交易金额      8164
Name: 21767, dtype: int64
内部标识号    21769
交易次数        13
交易金额       257
Name: 21768, dtype: int64
内部标识号    21770
交易次数         8
交易金额       380
Name: 21769, dtype: int64
内部标识号    21771
交易次数         8
交易金额      5657
Name: 21770, dtype: int64
内部标识号    21772
交易次数         2
交易金额       565
Name: 21771, dtype: int64
内部标识号    21773
交易次数         2
交易金额       500
Name: 21772, dtype: int64
内部标识号    21774
交易次数         3
交易金额       480
Name: 21773, dtype: int64
内部标识号    21775
交易次数         8
交易金额       230
Name: 21774, dtype: int64
内部标识号    21776
交易次数         3
交易金额       316
Name: 21775, dtype: int64
内部标识号    21777
交易次数         7
交易金额      9289
Name: 21776, dtype: int64
内部标识号    21778
交易次数         2
交易金额       369
Name: 21777, dtype: int64
内部标识号    21779
交易次数        16
交易金额       676
Name: 21778, dtype: int64
内部标识号    21780
交易次数         0
交易金额       111
Name: 21779, dtype: int64
内部标识号    21781
交易次数         7
交易金额       322
Name: 21780, dtype: int64
内部标识号    21782
交易次数         2
交易金额       361
Name: 21781, dtype: int64
内部标识号    21783
交易次数         2
交易金额       818
Name: 21782, dtype: int64
内部标识号    21784
交易次数         2
交易金额       379
Name: 21783, dtype: int64
内部标识号    21785
交易次数         2
交易金额       463
Name: 21784, dtype: int64
内部标识号    21786
交易次数         0
交易金额       284
Name: 21785, dtype: int64
内部标识号    21787
交易次数        10
交易金额       190
Name: 21786, dtype: int64
内部标识号    21788
交易次数        17
交易金额       840
Name: 21787, dtype: int64
内部标识号    21789
交易次数        12
交易金额       288
Name: 21788, dtype: int64
内部标识号    21790
交易次数         2
交易金额       435
Name: 21789, dtype: int64
内部标识号    21791
交易次数         5
交易金额       969
Name: 21790, dtype: int64
内部标识号    21792
交易次数         3
交易金额       373
Name: 21791, dtype: int64
内部标识号    21793
交易次数         5
交易金额       303
Name: 21792, dtype: int64
内部标识号    21794
交易次数         2
交易金额       809
Name: 21793, dtype: int64
内部标识号    21795
交易次数        29
交易金额       999
Name: 21794, dtype: int64
内部标识号    21796
交易次数         2
交易金额       465
Name: 21795, dtype: int64
内部标识号    21797
交易次数         1
交易金额       169
Name: 21796, dtype: int64
内部标识号    21798
交易次数        12
交易金额       227
Name: 21797, dtype: int64
内部标识号    21799
交易次数         3
交易金额       319
Name: 21798, dtype: int64
内部标识号    21800
交易次数         0
交易金额       259
Name: 21799, dtype: int64
内部标识号    21801
交易次数         2
交易金额       443
Name: 21800, dtype: int64
内部标识号    21802
交易次数         2
交易金额       344
Name: 21801, dtype: int64
内部标识号    21803
交易次数         2
交易金额       855
Name: 21802, dtype: int64
内部标识号    21804
交易次数         3
交易金额       343
Name: 21803, dtype: int64
内部标识号    21805
交易次数         1
交易金额       836
Name: 21804, dtype: int64
内部标识号    21806
交易次数         0
交易金额     74239
Name: 21805, dtype: int64
内部标识号    21807
交易次数         3
交易金额       430
Name: 21806, dtype: int64
内部标识号    21808
交易次数         3
交易金额       366
Name: 21807, dtype: int64
内部标识号    21809
交易次数         1
交易金额       966
Name: 21808, dtype: int64
内部标识号    21810
交易次数         6
交易金额       328
Name: 21809, dtype: int64
内部标识号    21811
交易次数         2
交易金额       778
Name: 21810, dtype: int64
内部标识号    21812
交易次数         9
交易金额       120
Name: 21811, dtype: int64
内部标识号    21813
交易次数        30
交易金额       585
Name: 21812, dtype: int64
内部标识号    21814
交易次数         1
交易金额       225
Name: 21813, dtype: int64
内部标识号    21815
交易次数        21
交易金额       804
Name: 21814, dtype: int64
内部标识号    21816
交易次数         2
交易金额       408
Name: 21815, dtype: int64
内部标识号    21817
交易次数         3
交易金额       312
Name: 21816, dtype: int64
内部标识号    21818
交易次数         6
交易金额      3020
Name: 21817, dtype: int64
内部标识号    21819
交易次数         1
交易金额       698
Name: 21818, dtype: int64
内部标识号    21820
交易次数         3
交易金额       366
Name: 21819, dtype: int64
内部标识号    21821
交易次数         3
交易金额      9981
Name: 21820, dtype: int64
内部标识号    21822
交易次数         3
交易金额       468
Name: 21821, dtype: int64
内部标识号    21823
交易次数         3
交易金额       557
Name: 21822, dtype: int64
内部标识号    21824
交易次数         2
交易金额       471
Name: 21823, dtype: int64
内部标识号    21825
交易次数         8
交易金额      9547
Name: 21824, dtype: int64
内部标识号    21826
交易次数         3
交易金额       348
Name: 21825, dtype: int64
内部标识号    21827
交易次数         5
交易金额      6512
Name: 21826, dtype: int64
内部标识号    21828
交易次数         0
交易金额       238
Name: 21827, dtype: int64
内部标识号    21829
交易次数         2
交易金额       404
Name: 21828, dtype: int64
内部标识号    21830
交易次数         2
交易金额        40
Name: 21829, dtype: int64
内部标识号    21831
交易次数        13
交易金额       179
Name: 21830, dtype: int64
内部标识号    21832
交易次数        27
交易金额       780
Name: 21831, dtype: int64
内部标识号    21833
交易次数         9
交易金额       171
Name: 21832, dtype: int64
内部标识号    21834
交易次数         1
交易金额       968
Name: 21833, dtype: int64
内部标识号    21835
交易次数       163
交易金额     40861
Name: 21834, dtype: int64
内部标识号    21836
交易次数         1
交易金额       204
Name: 21835, dtype: int64
内部标识号    21837
交易次数         0
交易金额     39688
Name: 21836, dtype: int64
内部标识号    21838
交易次数         8
交易金额       243
Name: 21837, dtype: int64
内部标识号    21839
交易次数         0
交易金额       241
Name: 21838, dtype: int64
内部标识号    21840
交易次数        17
交易金额       849
Name: 21839, dtype: int64
内部标识号    21841
交易次数         2
交易金额       405
Name: 21840, dtype: int64
内部标识号    21842
交易次数         3
交易金额       401
Name: 21841, dtype: int64
内部标识号    21843
交易次数         1
交易金额       935
Name: 21842, dtype: int64
内部标识号    21844
交易次数         2
交易金额       896
Name: 21843, dtype: int64
内部标识号    21845
交易次数         4
交易金额      5223
Name: 21844, dtype: int64
内部标识号    21846
交易次数         2
交易金额       352
Name: 21845, dtype: int64
内部标识号    21847
交易次数         2
交易金额       418
Name: 21846, dtype: int64
内部标识号    21848
交易次数         2
交易金额       712
Name: 21847, dtype: int64
内部标识号    21849
交易次数        13
交易金额       115
Name: 21848, dtype: int64
内部标识号    21850
交易次数         2
交易金额       437
Name: 21849, dtype: int64
内部标识号    21851
交易次数         3
交易金额       494
Name: 21850, dtype: int64
内部标识号    21852
交易次数         2
交易金额       354
Name: 21851, dtype: int64
内部标识号    21853
交易次数        26
交易金额       546
Name: 21852, dtype: int64
内部标识号    21854
交易次数         6
交易金额      2014
Name: 21853, dtype: int64
内部标识号    21855
交易次数         6
交易金额       861
Name: 21854, dtype: int64
内部标识号    21856
交易次数         8
交易金额      7349
Name: 21855, dtype: int64
内部标识号    21857
交易次数         3
交易金额       396
Name: 21856, dtype: int64
内部标识号    21858
交易次数         3
交易金额       301
Name: 21857, dtype: int64
内部标识号    21859
交易次数         1
交易金额       512
Name: 21858, dtype: int64
内部标识号    21860
交易次数         0
交易金额     64958
Name: 21859, dtype: int64
内部标识号    21861
交易次数         1
交易金额        21
Name: 21860, dtype: int64
内部标识号    21862
交易次数        13
交易金额       277
Name: 21861, dtype: int64
内部标识号    21863
交易次数         0
交易金额       295
Name: 21862, dtype: int64
内部标识号    21864
交易次数         2
交易金额       449
Name: 21863, dtype: int64
内部标识号    21865
交易次数         3
交易金额       412
Name: 21864, dtype: int64
内部标识号    21866
交易次数         6
交易金额      9993
Name: 21865, dtype: int64
内部标识号    21867
交易次数        14
交易金额       184
Name: 21866, dtype: int64
内部标识号    21868
交易次数         3
交易金额       411
Name: 21867, dtype: int64
内部标识号    21869
交易次数         0
交易金额       205
Name: 21868, dtype: int64
内部标识号    21870
交易次数         3
交易金额       496
Name: 21869, dtype: int64
内部标识号    21871
交易次数         0
交易金额       294
Name: 21870, dtype: int64
内部标识号    21872
交易次数         3
交易金额       325
Name: 21871, dtype: int64
内部标识号    21873
交易次数         3
交易金额       321
Name: 21872, dtype: int64
内部标识号    21874
交易次数         3
交易金额       471
Name: 21873, dtype: int64
内部标识号    21875
交易次数         1
交易金额       165
Name: 21874, dtype: int64
内部标识号    21876
交易次数         6
交易金额      2439
Name: 21875, dtype: int64
内部标识号    21877
交易次数         2
交易金额       485
Name: 21876, dtype: int64
内部标识号    21878
交易次数         2
交易金额       359
Name: 21877, dtype: int64
内部标识号    21879
交易次数         1
交易金额     31805
Name: 21878, dtype: int64
内部标识号    21880
交易次数         2
交易金额       316
Name: 21879, dtype: int64
内部标识号    21881
交易次数         1
交易金额     12333
Name: 21880, dtype: int64
内部标识号    21882
交易次数         4
交易金额      9577
Name: 21881, dtype: int64
内部标识号    21883
交易次数         2
交易金额       434
Name: 21882, dtype: int64
内部标识号    21884
交易次数         7
交易金额      7431
Name: 21883, dtype: int64
内部标识号    21885
交易次数         6
交易金额       362
Name: 21884, dtype: int64
内部标识号    21886
交易次数         2
交易金额       466
Name: 21885, dtype: int64
内部标识号    21887
交易次数         4
交易金额       416
Name: 21886, dtype: int64
内部标识号    21888
交易次数         3
交易金额       408
Name: 21887, dtype: int64
内部标识号    21889
交易次数         2
交易金额       890
Name: 21888, dtype: int64
内部标识号    21890
交易次数         2
交易金额       529
Name: 21889, dtype: int64
内部标识号    21891
交易次数         4
交易金额       481
Name: 21890, dtype: int64
内部标识号    21892
交易次数         1
交易金额       190
Name: 21891, dtype: int64
内部标识号    21893
交易次数         3
交易金额       419
Name: 21892, dtype: int64
内部标识号    21894
交易次数         3
交易金额       415
Name: 21893, dtype: int64
内部标识号    21895
交易次数         1
交易金额        67
Name: 21894, dtype: int64
内部标识号    21896
交易次数         8
交易金额      6182
Name: 21895, dtype: int64
内部标识号    21897
交易次数         2
交易金额       325
Name: 21896, dtype: int64
内部标识号    21898
交易次数         4
交易金额      3744
Name: 21897, dtype: int64
内部标识号    21899
交易次数         2
交易金额       396
Name: 21898, dtype: int64
内部标识号    21900
交易次数         3
交易金额       443
Name: 21899, dtype: int64
内部标识号    21901
交易次数         0
交易金额     37629
Name: 21900, dtype: int64
内部标识号    21902
交易次数         3
交易金额       462
Name: 21901, dtype: int64
内部标识号    21903
交易次数        15
交易金额       158
Name: 21902, dtype: int64
内部标识号    21904
交易次数         5
交易金额      7938
Name: 21903, dtype: int64
内部标识号    21905
交易次数         8
交易金额       135
Name: 21904, dtype: int64
内部标识号    21906
交易次数         1
交易金额        57
Name: 21905, dtype: int64
内部标识号    21907
交易次数         2
交易金额       832
Name: 21906, dtype: int64
内部标识号    21908
交易次数         8
交易金额       495
Name: 21907, dtype: int64
内部标识号    21909
交易次数         7
交易金额       311
Name: 21908, dtype: int64
内部标识号    21910
交易次数        17
交易金额       638
Name: 21909, dtype: int64
内部标识号    21911
交易次数         6
交易金额      7405
Name: 21910, dtype: int64
内部标识号    21912
交易次数         1
交易金额       134
Name: 21911, dtype: int64
内部标识号    21913
交易次数         0
交易金额       223
Name: 21912, dtype: int64
内部标识号    21914
交易次数         4
交易金额       350
Name: 21913, dtype: int64
内部标识号    21915
交易次数         1
交易金额       110
Name: 21914, dtype: int64
内部标识号    21916
交易次数         1
交易金额       102
Name: 21915, dtype: int64
内部标识号    21917
交易次数        15
交易金额       613
Name: 21916, dtype: int64
内部标识号    21918
交易次数         2
交易金额       305
Name: 21917, dtype: int64
内部标识号    21919
交易次数         8
交易金额       227
Name: 21918, dtype: int64
内部标识号    21920
交易次数         2
交易金额     34941
Name: 21919, dtype: int64
内部标识号    21921
交易次数        25
交易金额       865
Name: 21920, dtype: int64
内部标识号    21922
交易次数         2
交易金额       433
Name: 21921, dtype: int64
内部标识号    21923
交易次数         3
交易金额       301
Name: 21922, dtype: int64
内部标识号    21924
交易次数         1
交易金额       229
Name: 21923, dtype: int64
内部标识号    21925
交易次数         0
交易金额       292
Name: 21924, dtype: int64
内部标识号    21926
交易次数         0
交易金额       101
Name: 21925, dtype: int64
内部标识号    21927
交易次数         2
交易金额       446
Name: 21926, dtype: int64
内部标识号    21928
交易次数         8
交易金额      4068
Name: 21927, dtype: int64
内部标识号    21929
交易次数         3
交易金额       402
Name: 21928, dtype: int64
内部标识号    21930
交易次数         4
交易金额      4990
Name: 21929, dtype: int64
内部标识号    21931
交易次数         2
交易金额       431
Name: 21930, dtype: int64
内部标识号    21932
交易次数         2
交易金额       824
Name: 21931, dtype: int64
内部标识号    21933
交易次数         1
交易金额       196
Name: 21932, dtype: int64
内部标识号    21934
交易次数         3
交易金额       402
Name: 21933, dtype: int64
内部标识号    21935
交易次数         0
交易金额     99270
Name: 21934, dtype: int64
内部标识号    21936
交易次数         2
交易金额       483
Name: 21935, dtype: int64
内部标识号    21937
交易次数        13
交易金额       169
Name: 21936, dtype: int64
内部标识号    21938
交易次数         3
交易金额       881
Name: 21937, dtype: int64
内部标识号    21939
交易次数        21
交易金额       866
Name: 21938, dtype: int64
内部标识号    21940
交易次数         2
交易金额       476
Name: 21939, dtype: int64
内部标识号    21941
交易次数         0
交易金额       172
Name: 21940, dtype: int64
内部标识号    21942
交易次数         1
交易金额       287
Name: 21941, dtype: int64
内部标识号    21943
交易次数        12
交易金额       263
Name: 21942, dtype: int64
内部标识号    21944
交易次数         0
交易金额       262
Name: 21943, dtype: int64
内部标识号    21945
交易次数         2
交易金额       417
Name: 21944, dtype: int64
内部标识号    21946
交易次数         3
交易金额       461
Name: 21945, dtype: int64
内部标识号    21947
交易次数         2
交易金额       389
Name: 21946, dtype: int64
内部标识号    21948
交易次数         1
交易金额       251
Name: 21947, dtype: int64
内部标识号    21949
交易次数         2
交易金额       478
Name: 21948, dtype: int64
内部标识号    21950
交易次数         0
交易金额       146
Name: 21949, dtype: int64
内部标识号    21951
交易次数         8
交易金额      2658
Name: 21950, dtype: int64
内部标识号    21952
交易次数         3
交易金额       472
Name: 21951, dtype: int64
内部标识号    21953
交易次数         3
交易金额       444
Name: 21952, dtype: int64
内部标识号    21954
交易次数         2
交易金额       455
Name: 21953, dtype: int64
内部标识号    21955
交易次数         8
交易金额       429
Name: 21954, dtype: int64
内部标识号    21956
交易次数        14
交易金额       196
Name: 21955, dtype: int64
内部标识号    21957
交易次数         2
交易金额       350
Name: 21956, dtype: int64
内部标识号    21958
交易次数         2
交易金额       896
Name: 21957, dtype: int64
内部标识号    21959
交易次数         1
交易金额       248
Name: 21958, dtype: int64
内部标识号    21960
交易次数        69
交易金额     86715
Name: 21959, dtype: int64
内部标识号    21961
交易次数         5
交易金额      3838
Name: 21960, dtype: int64
内部标识号    21962
交易次数         4
交易金额      1259
Name: 21961, dtype: int64
内部标识号    21963
交易次数         0
交易金额     16190
Name: 21962, dtype: int64
内部标识号    21964
交易次数         2
交易金额       408
Name: 21963, dtype: int64
内部标识号    21965
交易次数         3
交易金额       361
Name: 21964, dtype: int64
内部标识号    21966
交易次数         3
交易金额       312
Name: 21965, dtype: int64
内部标识号    21967
交易次数         3
交易金额       387
Name: 21966, dtype: int64
内部标识号    21968
交易次数         3
交易金额       324
Name: 21967, dtype: int64
内部标识号    21969
交易次数         1
交易金额       556
Name: 21968, dtype: int64
内部标识号    21970
交易次数         6
交易金额      9888
Name: 21969, dtype: int64
内部标识号    21971
交易次数         7
交易金额       820
Name: 21970, dtype: int64
内部标识号    21972
交易次数         2
交易金额       484
Name: 21971, dtype: int64
内部标识号    21973
交易次数         3
交易金额       352
Name: 21972, dtype: int64
内部标识号    21974
交易次数        17
交易金额       738
Name: 21973, dtype: int64
内部标识号    21975
交易次数         1
交易金额       956
Name: 21974, dtype: int64
内部标识号    21976
交易次数         2
交易金额       551
Name: 21975, dtype: int64
内部标识号    21977
交易次数         2
交易金额       320
Name: 21976, dtype: int64
内部标识号    21978
交易次数         2
交易金额       448
Name: 21977, dtype: int64
内部标识号    21979
交易次数         0
交易金额     54984
Name: 21978, dtype: int64
内部标识号    21980
交易次数         3
交易金额       437
Name: 21979, dtype: int64
内部标识号    21981
交易次数         5
交易金额       341
Name: 21980, dtype: int64
内部标识号    21982
交易次数         3
交易金额      6480
Name: 21981, dtype: int64
内部标识号    21983
交易次数         8
交易金额       611
Name: 21982, dtype: int64
内部标识号    21984
交易次数         1
交易金额       885
Name: 21983, dtype: int64
内部标识号    21985
交易次数         2
交易金额       386
Name: 21984, dtype: int64
内部标识号    21986
交易次数        10
交易金额       192
Name: 21985, dtype: int64
内部标识号    21987
交易次数         8
交易金额      9705
Name: 21986, dtype: int64
内部标识号    21988
交易次数         1
交易金额       282
Name: 21987, dtype: int64
内部标识号    21989
交易次数         6
交易金额      2914
Name: 21988, dtype: int64
内部标识号    21990
交易次数         4
交易金额      7059
Name: 21989, dtype: int64
内部标识号    21991
交易次数         0
交易金额     16896
Name: 21990, dtype: int64
内部标识号    21992
交易次数         3
交易金额      5143
Name: 21991, dtype: int64
内部标识号    21993
交易次数        10
交易金额       159
Name: 21992, dtype: int64
内部标识号    21994
交易次数         1
交易金额       135
Name: 21993, dtype: int64
内部标识号    21995
交易次数         2
交易金额       716
Name: 21994, dtype: int64
内部标识号    21996
交易次数         3
交易金额      8688
Name: 21995, dtype: int64
内部标识号    21997
交易次数         2
交易金额       390
Name: 21996, dtype: int64
内部标识号    21998
交易次数         1
交易金额       512
Name: 21997, dtype: int64
内部标识号    21999
交易次数         2
交易金额       484
Name: 21998, dtype: int64
内部标识号    22000

Name: 22097, dtype: int64
内部标识号    22099
交易次数         3
交易金额       424
Name: 22098, dtype: int64
内部标识号    22100
交易次数         0
交易金额       239
Name: 22099, dtype: int64
内部标识号    22101
交易次数         5
交易金额       718
Name: 22100, dtype: int64
内部标识号    22102
交易次数         1
交易金额       857
Name: 22101, dtype: int64
内部标识号    22103
交易次数         2
交易金额       327
Name: 22102, dtype: int64
内部标识号    22104
交易次数         0
交易金额     49240
Name: 22103, dtype: int64
内部标识号    22105
交易次数         2
交易金额       818
Name: 22104, dtype: int64
内部标识号    22106
交易次数         5
交易金额       398
Name: 22105, dtype: int64
内部标识号    22107
交易次数         8
交易金额       984
Name: 22106, dtype: int64
内部标识号    22108
交易次数        14
交易金额       183
Name: 22107, dtype: int64
内部标识号    22109
交易次数         2
交易金额       410
Name: 22108, dtype: int64
内部标识号    22110
交易次数        14
交易金额       153
Name: 22109, dtype: int64
内部标识号    22111
交易次数         2
交易金额       890
Name: 22110, dtype: int64
内部标识号    22112
交易次数         4
交易金额      4734
Name: 22111, dtype: int64
内部标识号    22113
交易次数         1
交易金额       201
Name: 22112, dtype: int64
内部标识号    22114
交易次数         1
交易金额       570
Name: 22113, dtype: int64
内部标识号    22115
交易次数        14
交易金额       177
Name: 22114, dtype: int64
内部标识号    22116
交易次数         2
交易金额       497
Name: 22115, dtype: int64
内部标识号    22117
交易次数        10
交易金额       299
Name: 22116, dtype: int64
内部标识号    22118
交易次数         8
交易金额       118
Name: 22117, dtype: int64
内部标识号    22119
交易次数       146
交易金额     98518
Name: 22118, dtype: int64
内部标识号    22120
交易次数         2
交易金额       427
Name: 22119, dtype: int64
内部标识号    22121
交易次数         2
交易金额        10
Name: 22120, dtype: int64
内部标识号    22122
交易次数         1
交易金额       882
Name: 22121, dtype: int64
内部标识号    22123
交易次数         3
交易金额       323
Name: 22122, dtype: int64
内部标识号    22124
交易次数         8
交易金额       228
Name: 22123, dtype: int64
内部标识号    22125
交易次数        13
交易金额       111
Name: 22124, dtype: int64
内部标识号    22126
交易次数         1
交易金额       287
Name: 22125, dtype: int64
内部标识号    22127
交易次数         3
交易金额      8591
Name: 22126, dtype: int64
内部标识号    22128
交易次数         0
交易金额       175
Name: 22127, dtype: int64
内部标识号    22129
交易次数         0
交易金额       148
Name: 22128, dtype: int64
内部标识号    22130
交易次数         2
交易金额       387
Name: 22129, dtype: int64
内部标识号    22131
交易次数         2
交易金额       484
Name: 22130, dtype: int64
内部标识号    22132
交易次数         2
交易金额       304
Name: 22131, dtype: int64
内部标识号    22133
交易次数         2
交易金额       875
Name: 22132, dtype: int64
内部标识号    22134
交易次数         1
交易金额       129
Name: 22133, dtype: int64
内部标识号    22135
交易次数         1
交易金额       126
Name: 22134, dtype: int64
内部标识号    22136
交易次数        10
交易金额       290
Name: 22135, dtype: int64
内部标识号    22137
交易次数         3
交易金额       392
Name: 22136, dtype: int64
内部标识号    22138
交易次数         2
交易金额       639
Name: 22137, dtype: int64
内部标识号    22139
交易次数         3
交易金额       409
Name: 22138, dtype: int64
内部标识号    22140
交易次数         3
交易金额       321
Name: 22139, dtype: int64
内部标识号    22141
交易次数         0
交易金额       222
Name: 22140, dtype: int64
内部标识号    22142
交易次数         8
交易金额       556
Name: 22141, dtype: int64
内部标识号    22143
交易次数         2
交易金额       398
Name: 22142, dtype: int64
内部标识号    22144
交易次数         1
交易金额       748
Name: 22143, dtype: int64
内部标识号    22145
交易次数         0
交易金额     98141
Name: 22144, dtype: int64
内部标识号    22146
交易次数         2
交易金额       318
Name: 22145, dtype: int64
内部标识号    22147
交易次数         2
交易金额       381
Name: 22146, dtype: int64
内部标识号    22148
交易次数         3
交易金额      2238
Name: 22147, dtype: int64
内部标识号    22149
交易次数         0
交易金额       178
Name: 22148, dtype: int64
内部标识号    22150
交易次数         0
交易金额       191
Name: 22149, dtype: int64
内部标识号    22151
交易次数         2
交易金额       464
Name: 22150, dtype: int64
内部标识号    22152
交易次数         0
交易金额       169
Name: 22151, dtype: int64
内部标识号    22153
交易次数         0
交易金额     19347
Name: 22152, dtype: int64
内部标识号    22154
交易次数         1
交易金额       151
Name: 22153, dtype: int64
内部标识号    22155
交易次数         3
交易金额       388
Name: 22154, dtype: int64
内部标识号    22156
交易次数         4
交易金额      6512
Name: 22155, dtype: int64
内部标识号    22157
交易次数         1
交易金额       844
Name: 22156, dtype: int64
内部标识号    22158
交易次数         3
交易金额       490
Name: 22157, dtype: int64
内部标识号    22159
交易次数         2
交易金额       668
Name: 22158, dtype: int64
内部标识号    22160
交易次数         0
交易金额       201
Name: 22159, dtype: int64
内部标识号    22161
交易次数         3
交易金额       427
Name: 22160, dtype: int64
内部标识号    22162
交易次数         1
交易金额       780
Name: 22161, dtype: int64
内部标识号    22163
交易次数        16
交易金额       858
Name: 22162, dtype: int64
内部标识号    22164
交易次数         3
交易金额       483
Name: 22163, dtype: int64
内部标识号    22165
交易次数         9
交易金额       240
Name: 22164, dtype: int64
内部标识号    22166
交易次数         2
交易金额       417
Name: 22165, dtype: int64
内部标识号    22167
交易次数        13
交易金额       221
Name: 22166, dtype: int64
内部标识号    22168
交易次数         2
交易金额       411
Name: 22167, dtype: int64
内部标识号    22169
交易次数         0
交易金额     74988
Name: 22168, dtype: int64
内部标识号    22170
交易次数         0
交易金额       263
Name: 22169, dtype: int64
内部标识号    22171
交易次数         3
交易金额       377
Name: 22170, dtype: int64
内部标识号    22172
交易次数         0
交易金额       138
Name: 22171, dtype: int64
内部标识号    22173
交易次数         1
交易金额       576
Name: 22172, dtype: int64
内部标识号    22174
交易次数        12
交易金额       246
Name: 22173, dtype: int64
内部标识号    22175
交易次数         6
交易金额      7118
Name: 22174, dtype: int64
内部标识号    22176
交易次数         2
交易金额        64
Name: 22175, dtype: int64
内部标识号    22177
交易次数        14
交易金额       179
Name: 22176, dtype: int64
内部标识号    22178
交易次数         3
交易金额       309
Name: 22177, dtype: int64
内部标识号    22179
交易次数        10
交易金额       188
Name: 22178, dtype: int64
内部标识号    22180
交易次数         4
交易金额       404
Name: 22179, dtype: int64
内部标识号    22181
交易次数         4
交易金额      1649
Name: 22180, dtype: int64
内部标识号    22182
交易次数         5
交易金额      6017
Name: 22181, dtype: int64
内部标识号    22183
交易次数         5
交易金额       490
Name: 22182, dtype: int64
内部标识号    22184
交易次数         0
交易金额     70714
Name: 22183, dtype: int64
内部标识号    22185
交易次数         3
交易金额      9699
Name: 22184, dtype: int64
内部标识号    22186
交易次数         2
交易金额       436
Name: 22185, dtype: int64
内部标识号    22187
交易次数         0
交易金额     69097
Name: 22186, dtype: int64
内部标识号    22188
交易次数         6
交易金额      2838
Name: 22187, dtype: int64
内部标识号    22189
交易次数         6
交易金额       412
Name: 22188, dtype: int64
内部标识号    22190
交易次数         5
交易金额      7924
Name: 22189, dtype: int64
内部标识号    22191
交易次数         5
交易金额      6027
Name: 22190, dtype: int64
内部标识号    22192
交易次数         1
交易金额       264
Name: 22191, dtype: int64
内部标识号    22193
交易次数         1
交易金额       824
Name: 22192, dtype: int64
内部标识号    22194
交易次数         1
交易金额       171
Name: 22193, dtype: int64
内部标识号    22195
交易次数         2
交易金额       450
Name: 22194, dtype: int64
内部标识号    22196
交易次数         2
交易金额       434
Name: 22195, dtype: int64
内部标识号    22197
交易次数         2
交易金额       499
Name: 22196, dtype: int64
内部标识号    22198
交易次数       171
交易金额     70685
Name: 22197, dtype: int64
内部标识号    22199
交易次数       239
交易金额     79725
Name: 22198, dtype: int64
内部标识号    22200
交易次数        10
交易金额       100
Name: 22199, dtype: int64
内部标识号    22201
交易次数         2
交易金额       417
Name: 22200, dtype: int64
内部标识号    22202
交易次数         3
交易金额       317
Name: 22201, dtype: int64
内部标识号    22203
交易次数         9
交易金额       126
Name: 22202, dtype: int64
内部标识号    22204
交易次数        12
交易金额       224
Name: 22203, dtype: int64
内部标识号    22205
交易次数         2
交易金额       370
Name: 22204, dtype: int64
内部标识号    22206
交易次数         8
交易金额      2713
Name: 22205, dtype: int64
内部标识号    22207
交易次数        10
交易金额       178
Name: 22206, dtype: int64
内部标识号    22208
交易次数         4
交易金额      5143
Name: 22207, dtype: int64
内部标识号    22209
交易次数         2
交易金额       336
Name: 22208, dtype: int64
内部标识号    22210
交易次数        18
交易金额       715
Name: 22209, dtype: int64
内部标识号    22211
交易次数         2
交易金额       362
Name: 22210, dtype: int64
内部标识号    22212
交易次数         2
交易金额       329
Name: 22211, dtype: int64
内部标识号    22213
交易次数         1
交易金额       821
Name: 22212, dtype: int64
内部标识号    22214
交易次数         3
交易金额       485
Name: 22213, dtype: int64
内部标识号    22215
交易次数        14
交易金额       280
Name: 22214, dtype: int64
内部标识号    22216
交易次数         4
交易金额       356
Name: 22215, dtype: int64
内部标识号    22217
交易次数         3
交易金额       493
Name: 22216, dtype: int64
内部标识号    22218
交易次数         1
交易金额        37
Name: 22217, dtype: int64
内部标识号    22219
交易次数         3
交易金额       432
Name: 22218, dtype: int64
内部标识号    22220
交易次数         2
交易金额       964
Name: 22219, dtype: int64
内部标识号    22221
交易次数         1
交易金额       122
Name: 22220, dtype: int64
内部标识号    22222
交易次数         1
交易金额       608
Name: 22221, dtype: int64
内部标识号    22223
交易次数        18
交易金额       867
Name: 22222, dtype: int64
内部标识号    22224
交易次数         2
交易金额       835
Name: 22223, dtype: int64
内部标识号    22225
交易次数         6
交易金额      2745
Name: 22224, dtype: int64
内部标识号    22226
交易次数         3
交易金额       414
Name: 22225, dtype: int64
内部标识号    22227
交易次数         1
交易金额       212
Name: 22226, dtype: int64
内部标识号    22228
交易次数         3
交易金额       393
Name: 22227, dtype: int64
内部标识号    22229
交易次数         5
交易金额       655
Name: 22228, dtype: int64
内部标识号    22230
交易次数        30
交易金额       521
Name: 22229, dtype: int64
内部标识号    22231
交易次数         7
交易金额       479
Name: 22230, dtype: int64
内部标识号    22232
交易次数         3
交易金额       316
Name: 22231, dtype: int64
内部标识号    22233
交易次数         1
交易金额       972
Name: 22232, dtype: int64
内部标识号    22234
交易次数         2
交易金额       333
Name: 22233, dtype: int64
内部标识号    22235
交易次数         3
交易金额       430
Name: 22234, dtype: int64
内部标识号    22236
交易次数         2
交易金额       302
Name: 22235, dtype: int64
内部标识号    22237
交易次数        14
交易金额       183
Name: 22236, dtype: int64
内部标识号    22238
交易次数         1
交易金额       575
Name: 22237, dtype: int64
内部标识号    22239
交易次数         2
交易金额       684
Name: 22238, dtype: int64
内部标识号    22240
交易次数        23
交易金额       649
Name: 22239, dtype: int64
内部标识号    22241
交易次数         2
交易金额       440
Name: 22240, dtype: int64
内部标识号    22242
交易次数         9
交易金额       214
Name: 22241, dtype: int64
内部标识号    22243
交易次数         9
交易金额       129
Name: 22242, dtype: int64
内部标识号    22244
交易次数         8
交易金额      3482
Name: 22243, dtype: int64
内部标识号    22245
交易次数        22
交易金额       690
Name: 22244, dtype: int64
内部标识号    22246
交易次数         3
交易金额       445
Name: 22245, dtype: int64
内部标识号    22247
交易次数         3
交易金额       322
Name: 22246, dtype: int64
内部标识号    22248
交易次数        13
交易金额       273
Name: 22247, dtype: int64
内部标识号    22249
交易次数         3
交易金额       450
Name: 22248, dtype: int64
内部标识号    22250
交易次数         2
交易金额       308
Name: 22249, dtype: int64
内部标识号    22251
交易次数         9
交易金额       140
Name: 22250, dtype: int64
内部标识号    22252
交易次数         1
交易金额       585
Name: 22251, dtype: int64
内部标识号    22253
交易次数        11
交易金额       164
Name: 22252, dtype: int64
内部标识号    22254
交易次数         1
交易金额       139
Name: 22253, dtype: int64
内部标识号    22255
交易次数         3
交易金额       492
Name: 22254, dtype: int64
内部标识号    22256
交易次数         3
交易金额       320
Name: 22255, dtype: int64
内部标识号    22257
交易次数         8
交易金额       171
Name: 22256, dtype: int64
内部标识号    22258
交易次数         3
交易金额       312
Name: 22257, dtype: int64
内部标识号    22259
交易次数       119
交易金额     33765
Name: 22258, dtype: int64
内部标识号    22260
交易次数         2
交易金额       412
Name: 22259, dtype: int64
内部标识号    22261
交易次数         1
交易金额       646
Name: 22260, dtype: int64
内部标识号    22262
交易次数         2
交易金额       400
Name: 22261, dtype: int64
内部标识号    22263
交易次数         4
交易金额       596
Name: 22262, dtype: int64
内部标识号    22264
交易次数         2
交易金额       394
Name: 22263, dtype: int64
内部标识号    22265
交易次数         1
交易金额       238
Name: 22264, dtype: int64
内部标识号    22266
交易次数         0
交易金额     88226
Name: 22265, dtype: int64
内部标识号    22267
交易次数         4
交易金额       309
Name: 22266, dtype: int64
内部标识号    22268
交易次数         2
交易金额       635
Name: 22267, dtype: int64
内部标识号    22269
交易次数         7
交易金额       419
Name: 22268, dtype: int64
内部标识号    22270
交易次数         2
交易金额       807
Name: 22269, dtype: int64
内部标识号    22271
交易次数         1
交易金额       943
Name: 22270, dtype: int64
内部标识号    22272
交易次数         2
交易金额       425
Name: 22271, dtype: int64
内部标识号    22273
交易次数         4
交易金额      1327
Name: 22272, dtype: int64
内部标识号    22274
交易次数         4
交易金额      2328
Name: 22273, dtype: int64
内部标识号    22275
交易次数         2
交易金额       423
Name: 22274, dtype: int64
内部标识号    22276
交易次数         1
交易金额       610
Name: 22275, dtype: int64
内部标识号    22277
交易次数         8
交易金额       355
Name: 22276, dtype: int64
内部标识号    22278
交易次数         0
交易金额       117
Name: 22277, dtype: int64
内部标识号    22279
交易次数        10
交易金额       113
Name: 22278, dtype: int64
内部标识号    22280
交易次数        13
交易金额       151
Name: 22279, dtype: int64
内部标识号    22281
交易次数         6
交易金额      6860
Name: 22280, dtype: int64
内部标识号    22282
交易次数         8
交易金额      3638
Name: 22281, dtype: int64
内部标识号    22283
交易次数         0
交易金额     43643
Name: 22282, dtype: int64
内部标识号    22284
交易次数         4
交易金额      1773
Name: 22283, dtype: int64
内部标识号    22285
交易次数        10
交易金额       165
Name: 22284, dtype: int64
内部标识号    22286
交易次数         2
交易金额       381
Name: 22285, dtype: int64
内部标识号    22287
交易次数         1
交易金额       858
Name: 22286, dtype: int64
内部标识号    22288
交易次数        14
交易金额       104
Name: 22287, dtype: int64
内部标识号    22289
交易次数         1
交易金额       223
Name: 22288, dtype: int64
内部标识号    22290
交易次数         2
交易金额       375
Name: 22289, dtype: int64
内部标识号    22291
交易次数         2
交易金额       614
Name: 22290, dtype: int64
内部标识号    22292
交易次数         9
交易金额       232
Name: 22291, dtype: int64
内部标识号    22293
交易次数         0
交易金额       242
Name: 22292, dtype: int64
内部标识号    22294
交易次数         2
交易金额       319
Name: 22293, dtype: int64
内部标识号    22295
交易次数        15
交易金额       280
Name: 22294, dtype: int64
内部标识号    22296
交易次数         8
交易金额      9842
Name: 22295, dtype: int64
内部标识号    22297
交易次数        15
交易金额       294
Name: 22296, dtype: int64
内部标识号    22298
交易次数         2
交易金额       703
Name: 22297, dtype: int64
内部标识号    22299
交易次数         1
交易金额       793
Name: 22298, dtype: int64
内部标识号    22300
交易次数         1
交易金额       556
Name: 22299, dtype: int64
内部标识号    22301
交易次数         3
交易金额       489
Name: 22300, dtype: int64
内部标识号    22302
交易次数         1
交易金额       603
Name: 22301, dtype: int64
内部标识号    22303
交易次数         4
交易金额      5977
Name: 22302, dtype: int64
内部标识号    22304
交易次数         2
交易金额       663
Name: 22303, dtype: int64
内部标识号    22305
交易次数         2
交易金额       947
Name: 22304, dtype: int64
内部标识号    22306
交易次数         3
交易金额       412
Name: 22305, dtype: int64
内部标识号    22307
交易次数         2
交易金额       452
Name: 22306, dtype: int64
内部标识号    22308
交易次数        15
交易金额       253
Name: 22307, dtype: int64
内部标识号    22309
交易次数        10
交易金额       243
Name: 22308, dtype: int64
内部标识号    22310
交易次数         2
交易金额       435
Name: 22309, dtype: int64
内部标识号    22311
交易次数         2
交易金额       387
Name: 22310, dtype: int64
内部标识号    22312
交易次数         3
交易金额       372
Name: 22311, dtype: int64
内部标识号    22313
交易次数       246
交易金额     37657
Name: 22312, dtype: int64
内部标识号    22314
交易次数        11
交易金额       189
Name: 22313, dtype: int64
内部标识号    22315
交易次数         3
交易金额       441
Name: 22314, dtype: int64
内部标识号    22316
交易次数         2
交易金额       809
Name: 22315, dtype: int64
内部标识号    22317
交易次数         2
交易金额       728
Name: 22316, dtype: int64
内部标识号    22318
交易次数        15
交易金额       791
Name: 22317, dtype: int64
内部标识号    22319
交易次数         1
交易金额       877
Name: 22318, dtype: int64
内部标识号    22320
交易次数         3
交易金额       483
Name: 22319, dtype: int64
内部标识号    22321
交易次数         4
交易金额       629
Name: 22320, dtype: int64
内部标识号    22322
交易次数         2
交易金额       433
Name: 22321, dtype: int64
内部标识号    22323
交易次数         1
交易金额       730
Name: 22322, dtype: int64
内部标识号    22324
交易次数         1
交易金额       199
Name: 22323, dtype: int64
内部标识号    22325
交易次数         8
交易金额       282
Name: 22324, dtype: int64
内部标识号    22326
交易次数         3
交易金额       435
Name: 22325, dtype: int64
内部标识号    22327
交易次数         7
交易金额      1061
Name: 22326, dtype: int64
内部标识号    22328
交易次数         6
交易金额      7598
Name: 22327, dtype: int64
内部标识号    22329
交易次数        15
交易金额       255
Name: 22328, dtype: int64
内部标识号    22330
交易次数         1
交易金额       548
Name: 22329, dtype: int64
内部标识号    22331
交易次数         5
交易金额      1345
Name: 22330, dtype: int64
内部标识号    22332
交易次数         3
交易金额       309
Name: 22331, dtype: int64
内部标识号    22333
交易次数         3
交易金额       493
Name: 22332, dtype: int64
内部标识号    22334
交易次数        15
交易金额       163
Name: 22333, dtype: int64
内部标识号    22335
交易次数         4
交易金额       300
Name: 22334, dtype: int64
内部标识号    22336
交易次数        11
交易金额       250
Name: 22335, dtype: int64
内部标识号    22337
交易次数         1
交易金额       152
Name: 22336, dtype: int64
内部标识号    22338
交易次数         6
交易金额      5330
Name: 22337, dtype: int64
内部标识号    22339
交易次数         0
交易金额     89392
Name: 22338, dtype: int64
内部标识号    22340
交易次数         2
交易金额       692
Name: 22339, dtype: int64
内部标识号    22341
交易次数         4
交易金额       978
Name: 22340, dtype: int64
内部标识号    22342
交易次数         2
交易金额         2
Name: 22341, dtype: int64
内部标识号    22343
交易次数         1
交易金额       828
Name: 22342, dtype: int64
内部标识号    22344
交易次数         5
交易金额      5926
Name: 22343, dtype: int64
内部标识号    22345
交易次数         0
交易金额     24811
Name: 22344, dtype: int64
内部标识号    22346
交易次数         3
交易金额       325
Name: 22345, dtype: int64
内部标识号    22347
交易次数         3
交易金额       341
Name: 22346, dtype: int64
内部标识号    22348
交易次数         4
交易金额      1348
Name: 22347, dtype: int64
内部标识号    22349
交易次数         1
交易金额       872
Name: 22348, dtype: int64
内部标识号    22350
交易次数         5
交易金额      8800
Name: 22349, dtype: int64
内部标识号    22351
交易次数         2
交易金额       584
Name: 22350, dtype: int64
内部标识号    22352
交易次数         2
交易金额       437
Name: 22351, dtype: int64
内部标识号    22353
交易次数         3
交易金额       491
Name: 22352, dtype: int64
内部标识号    22354
交易次数         1
交易金额       174
Name: 22353, dtype: int64
内部标识号    22355
交易次数         7
交易金额       303
Name: 22354, dtype: int64
内部标识号    22356
交易次数         0
交易金额       180
Name: 22355, dtype: int64
内部标识号    22357
交易次数         8
交易金额       300
Name: 22356, dtype: int64
内部标识号    22358
交易次数         2
交易金额       498
Name: 22357, dtype: int64
内部标识号    22359
交易次数         2
交易金额       401
Name: 22358, dtype: int64
内部标识号    22360
交易次数         2
交易金额       597
Name: 22359, dtype: int64
内部标识号    22361
交易次数         3
交易金额       497
Name: 22360, dtype: int64
内部标识号    22362
交易次数         1
交易金额       181
Name: 22361, dtype: int64
内部标识号    22363
交易次数        26
交易金额       610
Name: 22362, dtype: int64
内部标识号    22364
交易次数         2
交易金额       364
Name: 22363, dtype: int64
内部标识号    22365
交易次数        10
交易金额       181
Name: 22364, dtype: int64
内部标识号    22366
交易次数         0
交易金额     95555
Name: 22365, dtype: int64
内部标识号    22367
交易次数         5
交易金额      1318
Name: 22366, dtype: int64
内部标识号    22368
交易次数         8
交易金额      7171
Name: 22367, dtype: int64
内部标识号    22369
交易次数         2
交易金额       637
Name: 22368, dtype: int64
内部标识号    22370
交易次数         3
交易金额       337
Name: 22369, dtype: int64
内部标识号    22371
交易次数         2
交易金额       694
Name: 22370, dtype: int64
内部标识号    22372
交易次数         0
交易金额       109
Name: 22371, dtype: int64
内部标识号    22373
交易次数         2
交易金额       489
Name: 22372, dtype: int64
内部标识号    22374
交易次数         2
交易金额       315
Name: 22373, dtype: int64
内部标识号    22375
交易次数         3
交易金额       587
Name: 22374, dtype: int64
内部标识号    22376
交易次数         3
交易金额       491
Name: 22375, dtype: int64
内部标识号    22377
交易次数         3
交易金额       310
Name: 22376, dtype: int64
内部标识号    22378
交易次数         2
交易金额       431
Name: 22377, dtype: int64
内部标识号    22379
交易次数         2
交易金额       318
Name: 22378, dtype: int64
内部标识号    22380

Name: 22532, dtype: int64
内部标识号    22534
交易次数        18
交易金额       732
Name: 22533, dtype: int64
内部标识号    22535
交易次数         5
交易金额      3029
Name: 22534, dtype: int64
内部标识号    22536
交易次数        10
交易金额       109
Name: 22535, dtype: int64
内部标识号    22537
交易次数         0
交易金额     18971
Name: 22536, dtype: int64
内部标识号    22538
交易次数         2
交易金额       383
Name: 22537, dtype: int64
内部标识号    22539
交易次数         6
交易金额      7875
Name: 22538, dtype: int64
内部标识号    22540
交易次数         3
交易金额       458
Name: 22539, dtype: int64
内部标识号    22541
交易次数         2
交易金额       477
Name: 22540, dtype: int64
内部标识号    22542
交易次数         2
交易金额       430
Name: 22541, dtype: int64
内部标识号    22543
交易次数         1
交易金额       283
Name: 22542, dtype: int64
内部标识号    22544
交易次数         3
交易金额       408
Name: 22543, dtype: int64
内部标识号    22545
交易次数         2
交易金额       351
Name: 22544, dtype: int64
内部标识号    22546
交易次数        14
交易金额       264
Name: 22545, dtype: int64
内部标识号    22547
交易次数         2
交易金额       377
Name: 22546, dtype: int64
内部标识号    22548
交易次数        29
交易金额       653
Name: 22547, dtype: int64
内部标识号    22549
交易次数         8
交易金额      7695
Name: 22548, dtype: int64
内部标识号    22550
交易次数       182
交易金额     82926
Name: 22549, dtype: int64
内部标识号    22551
交易次数         2
交易金额       420
Name: 22550, dtype: int64
内部标识号    22552
交易次数         3
交易金额       480
Name: 22551, dtype: int64
内部标识号    22553
交易次数        35
交易金额     79367
Name: 22552, dtype: int64
内部标识号    22554
交易次数         4
交易金额      5199
Name: 22553, dtype: int64
内部标识号    22555
交易次数         2
交易金额       441
Name: 22554, dtype: int64
内部标识号    22556
交易次数         0
交易金额     84251
Name: 22555, dtype: int64
内部标识号    22557
交易次数        10
交易金额       115
Name: 22556, dtype: int64
内部标识号    22558
交易次数        14
交易金额       270
Name: 22557, dtype: int64
内部标识号    22559
交易次数         0
交易金额       175
Name: 22558, dtype: int64
内部标识号    22560
交易次数         1
交易金额       265
Name: 22559, dtype: int64
内部标识号    22561
交易次数         1
交易金额       201
Name: 22560, dtype: int64
内部标识号    22562
交易次数         0
交易金额     54857
Name: 22561, dtype: int64
内部标识号    22563
交易次数         1
交易金额       299
Name: 22562, dtype: int64
内部标识号    22564
交易次数        16
交易金额       769
Name: 22563, dtype: int64
内部标识号    22565
交易次数         2
交易金额       488
Name: 22564, dtype: int64
内部标识号    22566
交易次数         2
交易金额       513
Name: 22565, dtype: int64
内部标识号    22567
交易次数        15
交易金额       221
Name: 22566, dtype: int64
内部标识号    22568
交易次数       114
交易金额     26343
Name: 22567, dtype: int64
内部标识号    22569
交易次数        11
交易金额       174
Name: 22568, dtype: int64
内部标识号    22570
交易次数         2
交易金额     25823
Name: 22569, dtype: int64
内部标识号    22571
交易次数         1
交易金额       545
Name: 22570, dtype: int64
内部标识号    22572
交易次数        30
交易金额       795
Name: 22571, dtype: int64
内部标识号    22573
交易次数         7
交易金额      9172
Name: 22572, dtype: int64
内部标识号    22574
交易次数        13
交易金额       263
Name: 22573, dtype: int64
内部标识号    22575
交易次数        12
交易金额       246
Name: 22574, dtype: int64
内部标识号    22576
交易次数         0
交易金额       137
Name: 22575, dtype: int64
内部标识号    22577
交易次数         0
交易金额       275
Name: 22576, dtype: int64
内部标识号    22578
交易次数         2
交易金额       341
Name: 22577, dtype: int64
内部标识号    22579
交易次数        10
交易金额       182
Name: 22578, dtype: int64
内部标识号    22580
交易次数         2
交易金额       725
Name: 22579, dtype: int64
内部标识号    22581
交易次数         0
交易金额       179
Name: 22580, dtype: int64
内部标识号    22582
交易次数         2
交易金额       411
Name: 22581, dtype: int64
内部标识号    22583
交易次数       165
交易金额     23881
Name: 22582, dtype: int64
内部标识号    22584
交易次数         6
交易金额      1967
Name: 22583, dtype: int64
内部标识号    22585
交易次数         2
交易金额       321
Name: 22584, dtype: int64
内部标识号    22586
交易次数         3
交易金额       485
Name: 22585, dtype: int64
内部标识号    22587
交易次数         3
交易金额       423
Name: 22586, dtype: int64
内部标识号    22588
交易次数         3
交易金额       346
Name: 22587, dtype: int64
内部标识号    22589
交易次数         1
交易金额       183
Name: 22588, dtype: int64
内部标识号    22590
交易次数         3
交易金额      1751
Name: 22589, dtype: int64
内部标识号    22591
交易次数         3
交易金额       485
Name: 22590, dtype: int64
内部标识号    22592
交易次数        15
交易金额       274
Name: 22591, dtype: int64
内部标识号    22593
交易次数        73
交易金额     75882
Name: 22592, dtype: int64
内部标识号    22594
交易次数         4
交易金额       921
Name: 22593, dtype: int64
内部标识号    22595
交易次数         7
交易金额      2993
Name: 22594, dtype: int64
内部标识号    22596
交易次数         8
交易金额       943
Name: 22595, dtype: int64
内部标识号    22597
交易次数         3
交易金额       392
Name: 22596, dtype: int64
内部标识号    22598
交易次数         3
交易金额       409
Name: 22597, dtype: int64
内部标识号    22599
交易次数         8
交易金额      6022
Name: 22598, dtype: int64
内部标识号    22600
交易次数         4
交易金额      9920
Name: 22599, dtype: int64
内部标识号    22601
交易次数         2
交易金额       345
Name: 22600, dtype: int64
内部标识号    22602
交易次数         5
交易金额       490
Name: 22601, dtype: int64
内部标识号    22603
交易次数         3
交易金额       474
Name: 22602, dtype: int64
内部标识号    22604
交易次数        10
交易金额       209
Name: 22603, dtype: int64
内部标识号    22605
交易次数         3
交易金额       329
Name: 22604, dtype: int64
内部标识号    22606
交易次数         8
交易金额       161
Name: 22605, dtype: int64
内部标识号    22607
交易次数         8
交易金额       288
Name: 22606, dtype: int64
内部标识号    22608
交易次数         1
交易金额       721
Name: 22607, dtype: int64
内部标识号    22609
交易次数         3
交易金额       427
Name: 22608, dtype: int64
内部标识号    22610
交易次数         6
交易金额       458
Name: 22609, dtype: int64
内部标识号    22611
交易次数         2
交易金额       413
Name: 22610, dtype: int64
内部标识号    22612
交易次数         9
交易金额       156
Name: 22611, dtype: int64
内部标识号    22613
交易次数        29
交易金额       819
Name: 22612, dtype: int64
内部标识号    22614
交易次数         0
交易金额     84447
Name: 22613, dtype: int64
内部标识号    22615
交易次数         9
交易金额       237
Name: 22614, dtype: int64
内部标识号    22616
交易次数         1
交易金额       275
Name: 22615, dtype: int64
内部标识号    22617
交易次数       261
交易金额     34106
Name: 22616, dtype: int64
内部标识号    22618
交易次数         3
交易金额       379
Name: 22617, dtype: int64
内部标识号    22619
交易次数         0
交易金额     30402
Name: 22618, dtype: int64
内部标识号    22620
交易次数         2
交易金额     38623
Name: 22619, dtype: int64
内部标识号    22621
交易次数         6
交易金额      8492
Name: 22620, dtype: int64
内部标识号    22622
交易次数         3
交易金额       322
Name: 22621, dtype: int64
内部标识号    22623
交易次数         3
交易金额       300
Name: 22622, dtype: int64
内部标识号    22624
交易次数         7
交易金额       550
Name: 22623, dtype: int64
内部标识号    22625
交易次数       195
交易金额     98165
Name: 22624, dtype: int64
内部标识号    22626
交易次数         1
交易金额       243
Name: 22625, dtype: int64
内部标识号    22627
交易次数        10
交易金额       275
Name: 22626, dtype: int64
内部标识号    22628
交易次数         2
交易金额       359
Name: 22627, dtype: int64
内部标识号    22629
交易次数        13
交易金额       184
Name: 22628, dtype: int64
内部标识号    22630
交易次数         3
交易金额       879
Name: 22629, dtype: int64
内部标识号    22631
交易次数         2
交易金额       496
Name: 22630, dtype: int64
内部标识号    22632
交易次数         0
交易金额       166
Name: 22631, dtype: int64
内部标识号    22633
交易次数         5
交易金额      5810
Name: 22632, dtype: int64
内部标识号    22634
交易次数         2
交易金额       441
Name: 22633, dtype: int64
内部标识号    22635
交易次数         2
交易金额       361
Name: 22634, dtype: int64
内部标识号    22636
交易次数         8
交易金额       213
Name: 22635, dtype: int64
内部标识号    22637
交易次数         9
交易金额       218
Name: 22636, dtype: int64
内部标识号    22638
交易次数         0
交易金额       147
Name: 22637, dtype: int64
内部标识号    22639
交易次数         0
交易金额     81352
Name: 22638, dtype: int64
内部标识号    22640
交易次数         0
交易金额     84649
Name: 22639, dtype: int64
内部标识号    22641
交易次数         2
交易金额       323
Name: 22640, dtype: int64
内部标识号    22642
交易次数         3
交易金额       371
Name: 22641, dtype: int64
内部标识号    22643
交易次数         1
交易金额       880
Name: 22642, dtype: int64
内部标识号    22644
交易次数         4
交易金额      8836
Name: 22643, dtype: int64
内部标识号    22645
交易次数         2
交易金额       957
Name: 22644, dtype: int64
内部标识号    22646
交易次数         2
交易金额       334
Name: 22645, dtype: int64
内部标识号    22647
交易次数         1
交易金额        11
Name: 22646, dtype: int64
内部标识号    22648
交易次数         2
交易金额       396
Name: 22647, dtype: int64
内部标识号    22649
交易次数         0
交易金额       128
Name: 22648, dtype: int64
内部标识号    22650
交易次数         8
交易金额       335
Name: 22649, dtype: int64
内部标识号    22651
交易次数         2
交易金额       402
Name: 22650, dtype: int64
内部标识号    22652
交易次数         2
交易金额       412
Name: 22651, dtype: int64
内部标识号    22653
交易次数        16
交易金额       607
Name: 22652, dtype: int64
内部标识号    22654
交易次数         2
交易金额       752
Name: 22653, dtype: int64
内部标识号    22655
交易次数         7
交易金额      8634
Name: 22654, dtype: int64
内部标识号    22656
交易次数        15
交易金额       159
Name: 22655, dtype: int64
内部标识号    22657
交易次数         2
交易金额       492
Name: 22656, dtype: int64
内部标识号    22658
交易次数         8
交易金额      7497
Name: 22657, dtype: int64
内部标识号    22659
交易次数         1
交易金额       188
Name: 22658, dtype: int64
内部标识号    22660
交易次数         2
交易金额        91
Name: 22659, dtype: int64
内部标识号    22661
交易次数         6
交易金额       422
Name: 22660, dtype: int64
内部标识号    22662
交易次数        13
交易金额       223
Name: 22661, dtype: int64
内部标识号    22663
交易次数         0
交易金额     95652
Name: 22662, dtype: int64
内部标识号    22664
交易次数         1
交易金额       763
Name: 22663, dtype: int64
内部标识号    22665
交易次数         3
交易金额       453
Name: 22664, dtype: int64
内部标识号    22666
交易次数         8
交易金额      1319
Name: 22665, dtype: int64
内部标识号    22667
交易次数         1
交易金额       789
Name: 22666, dtype: int64
内部标识号    22668
交易次数        15
交易金额       182
Name: 22667, dtype: int64
内部标识号    22669
交易次数         0
交易金额       116
Name: 22668, dtype: int64
内部标识号    22670
交易次数         3
交易金额       492
Name: 22669, dtype: int64
内部标识号    22671
交易次数         2
交易金额       944
Name: 22670, dtype: int64
内部标识号    22672
交易次数         1
交易金额       207
Name: 22671, dtype: int64
内部标识号    22673
交易次数         0
交易金额     19916
Name: 22672, dtype: int64
内部标识号    22674
交易次数         2
交易金额       640
Name: 22673, dtype: int64
内部标识号    22675
交易次数         7
交易金额      9925
Name: 22674, dtype: int64
内部标识号    22676
交易次数         2
交易金额       327
Name: 22675, dtype: int64
内部标识号    22677
交易次数         6
交易金额       403
Name: 22676, dtype: int64
内部标识号    22678
交易次数        10
交易金额       259
Name: 22677, dtype: int64
内部标识号    22679
交易次数         1
交易金额       816
Name: 22678, dtype: int64
内部标识号    22680
交易次数         3
交易金额       313
Name: 22679, dtype: int64
内部标识号    22681
交易次数         8
交易金额      8302
Name: 22680, dtype: int64
内部标识号    22682
交易次数        69
交易金额     49640
Name: 22681, dtype: int64
内部标识号    22683
交易次数         2
交易金额        74
Name: 22682, dtype: int64
内部标识号    22684
交易次数         2
交易金额       715
Name: 22683, dtype: int64
内部标识号    22685
交易次数         8
交易金额       193
Name: 22684, dtype: int64
内部标识号    22686
交易次数         5
交易金额      9832
Name: 22685, dtype: int64
内部标识号    22687
交易次数        26
交易金额       876
Name: 22686, dtype: int64
内部标识号    22688
交易次数         7
交易金额      3608
Name: 22687, dtype: int64
内部标识号    22689
交易次数        18
交易金额       569
Name: 22688, dtype: int64
内部标识号    22690
交易次数         0
交易金额     91192
Name: 22689, dtype: int64
内部标识号    22691
交易次数         4
交易金额      3164
Name: 22690, dtype: int64
内部标识号    22692
交易次数         3
交易金额       439
Name: 22691, dtype: int64
内部标识号    22693
交易次数         0
交易金额     30195
Name: 22692, dtype: int64
内部标识号    22694
交易次数         2
交易金额       481
Name: 22693, dtype: int64
内部标识号    22695
交易次数         3
交易金额       341
Name: 22694, dtype: int64
内部标识号    22696
交易次数         9
交易金额       153
Name: 22695, dtype: int64
内部标识号    22697
交易次数         5
交易金额      2634
Name: 22696, dtype: int64
内部标识号    22698
交易次数         0
交易金额       149
Name: 22697, dtype: int64
内部标识号    22699
交易次数         2
交易金额       387
Name: 22698, dtype: int64
内部标识号    22700
交易次数         2
交易金额       432
Name: 22699, dtype: int64
内部标识号    22701
交易次数         3
交易金额       454
Name: 22700, dtype: int64
内部标识号    22702
交易次数         0
交易金额     57335
Name: 22701, dtype: int64
内部标识号    22703
交易次数         3
交易金额       488
Name: 22702, dtype: int64
内部标识号    22704
交易次数         2
交易金额       389
Name: 22703, dtype: int64
内部标识号    22705
交易次数         3
交易金额       371
Name: 22704, dtype: int64
内部标识号    22706
交易次数         2
交易金额       477
Name: 22705, dtype: int64
内部标识号    22707
交易次数        22
交易金额       755
Name: 22706, dtype: int64
内部标识号    22708
交易次数         3
交易金额       341
Name: 22707, dtype: int64
内部标识号    22709
交易次数        17
交易金额       814
Name: 22708, dtype: int64
内部标识号    22710
交易次数         3
交易金额       331
Name: 22709, dtype: int64
内部标识号    22711
交易次数         8
交易金额       105
Name: 22710, dtype: int64
内部标识号    22712
交易次数         1
交易金额       101
Name: 22711, dtype: int64
内部标识号    22713
交易次数         3
交易金额       350
Name: 22712, dtype: int64
内部标识号    22714
交易次数         5
交易金额      1632
Name: 22713, dtype: int64
内部标识号    22715
交易次数         2
交易金额       355
Name: 22714, dtype: int64
内部标识号    22716
交易次数         2
交易金额       482
Name: 22715, dtype: int64
内部标识号    22717
交易次数         1
交易金额       219
Name: 22716, dtype: int64
内部标识号    22718
交易次数         2
交易金额       927
Name: 22717, dtype: int64
内部标识号    22719
交易次数        17
交易金额       818
Name: 22718, dtype: int64
内部标识号    22720
交易次数         6
交易金额      9839
Name: 22719, dtype: int64
内部标识号    22721
交易次数         2
交易金额       882
Name: 22720, dtype: int64
内部标识号    22722
交易次数        13
交易金额       156
Name: 22721, dtype: int64
内部标识号    22723
交易次数         0
交易金额       170
Name: 22722, dtype: int64
内部标识号    22724
交易次数         6
交易金额      1844
Name: 22723, dtype: int64
内部标识号    22725
交易次数        26
交易金额       906
Name: 22724, dtype: int64
内部标识号    22726
交易次数         0
交易金额       116
Name: 22725, dtype: int64
内部标识号    22727
交易次数         1
交易金额       609
Name: 22726, dtype: int64
内部标识号    22728
交易次数         2
交易金额       406
Name: 22727, dtype: int64
内部标识号    22729
交易次数         8
交易金额      5077
Name: 22728, dtype: int64
内部标识号    22730
交易次数         2
交易金额       353
Name: 22729, dtype: int64
内部标识号    22731
交易次数        10
交易金额       282
Name: 22730, dtype: int64
内部标识号    22732
交易次数         0
交易金额       298
Name: 22731, dtype: int64
内部标识号    22733
交易次数         1
交易金额       268
Name: 22732, dtype: int64
内部标识号    22734
交易次数        15
交易金额       106
Name: 22733, dtype: int64
内部标识号    22735
交易次数        14
交易金额       241
Name: 22734, dtype: int64
内部标识号    22736
交易次数         2
交易金额       374
Name: 22735, dtype: int64
内部标识号    22737
交易次数         0
交易金额     67766
Name: 22736, dtype: int64
内部标识号    22738
交易次数         1
交易金额       845
Name: 22737, dtype: int64
内部标识号    22739
交易次数         8
交易金额       552
Name: 22738, dtype: int64
内部标识号    22740
交易次数         2
交易金额       394
Name: 22739, dtype: int64
内部标识号    22741
交易次数         6
交易金额       324
Name: 22740, dtype: int64
内部标识号    22742
交易次数         3
交易金额       489
Name: 22741, dtype: int64
内部标识号    22743
交易次数         3
交易金额       321
Name: 22742, dtype: int64
内部标识号    22744
交易次数         3
交易金额       326
Name: 22743, dtype: int64
内部标识号    22745
交易次数         3
交易金额       340
Name: 22744, dtype: int64
内部标识号    22746
交易次数         2
交易金额       328
Name: 22745, dtype: int64
内部标识号    22747
交易次数         2
交易金额        42
Name: 22746, dtype: int64
内部标识号    22748
交易次数        22
交易金额       671
Name: 22747, dtype: int64
内部标识号    22749
交易次数         1
交易金额       916
Name: 22748, dtype: int64
内部标识号    22750
交易次数        40
交易金额     49418
Name: 22749, dtype: int64
内部标识号    22751
交易次数        12
交易金额       249
Name: 22750, dtype: int64
内部标识号    22752
交易次数         2
交易金额       611
Name: 22751, dtype: int64
内部标识号    22753
交易次数         3
交易金额       473
Name: 22752, dtype: int64
内部标识号    22754
交易次数         5
交易金额      9805
Name: 22753, dtype: int64
内部标识号    22755
交易次数         8
交易金额       290
Name: 22754, dtype: int64
内部标识号    22756
交易次数         1
交易金额       258
Name: 22755, dtype: int64
内部标识号    22757
交易次数         3
交易金额       618
Name: 22756, dtype: int64
内部标识号    22758
交易次数         2
交易金额       434
Name: 22757, dtype: int64
内部标识号    22759
交易次数         3
交易金额       409
Name: 22758, dtype: int64
内部标识号    22760
交易次数         1
交易金额       873
Name: 22759, dtype: int64
内部标识号    22761
交易次数         0
交易金额     74742
Name: 22760, dtype: int64
内部标识号    22762
交易次数         5
交易金额      8017
Name: 22761, dtype: int64
内部标识号    22763
交易次数         3
交易金额       359
Name: 22762, dtype: int64
内部标识号    22764
交易次数         2
交易金额       909
Name: 22763, dtype: int64
内部标识号    22765
交易次数         1
交易金额        86
Name: 22764, dtype: int64
内部标识号    22766
交易次数         2
交易金额       361
Name: 22765, dtype: int64
内部标识号    22767
交易次数         3
交易金额       414
Name: 22766, dtype: int64
内部标识号    22768
交易次数         2
交易金额       302
Name: 22767, dtype: int64
内部标识号    22769
交易次数         2
交易金额       345
Name: 22768, dtype: int64
内部标识号    22770
交易次数        18
交易金额       940
Name: 22769, dtype: int64
内部标识号    22771
交易次数         3
交易金额       338
Name: 22770, dtype: int64
内部标识号    22772
交易次数         3
交易金额       333
Name: 22771, dtype: int64
内部标识号    22773
交易次数        16
交易金额       760
Name: 22772, dtype: int64
内部标识号    22774
交易次数         1
交易金额        36
Name: 22773, dtype: int64
内部标识号    22775
交易次数         3
交易金额      6474
Name: 22774, dtype: int64
内部标识号    22776
交易次数         8
交易金额       113
Name: 22775, dtype: int64
内部标识号    22777
交易次数         7
交易金额      2913
Name: 22776, dtype: int64
内部标识号    22778
交易次数         3
交易金额       470
Name: 22777, dtype: int64
内部标识号    22779
交易次数         3
交易金额       390
Name: 22778, dtype: int64
内部标识号    22780
交易次数         3
交易金额       400
Name: 22779, dtype: int64
内部标识号    22781
交易次数         2
交易金额       975
Name: 22780, dtype: int64
内部标识号    22782
交易次数        10
交易金额       113
Name: 22781, dtype: int64
内部标识号    22783
交易次数         2
交易金额       389
Name: 22782, dtype: int64
内部标识号    22784
交易次数         2
交易金额       430
Name: 22783, dtype: int64
内部标识号    22785
交易次数        14
交易金额       110
Name: 22784, dtype: int64
内部标识号    22786
交易次数         1
交易金额       856
Name: 22785, dtype: int64
内部标识号    22787
交易次数         4
交易金额      8620
Name: 22786, dtype: int64
内部标识号    22788
交易次数         8
交易金额       257
Name: 22787, dtype: int64
内部标识号    22789
交易次数         3
交易金额       355
Name: 22788, dtype: int64
内部标识号    22790
交易次数         3
交易金额       398
Name: 22789, dtype: int64
内部标识号    22791
交易次数         2
交易金额       324
Name: 22790, dtype: int64
内部标识号    22792
交易次数        27
交易金额       922
Name: 22791, dtype: int64
内部标识号    22793
交易次数         9
交易金额       240
Name: 22792, dtype: int64
内部标识号    22794
交易次数         3
交易金额       475
Name: 22793, dtype: int64
内部标识号    22795
交易次数        12
交易金额       124
Name: 22794, dtype: int64
内部标识号    22796
交易次数         5
交易金额       500
Name: 22795, dtype: int64
内部标识号    22797
交易次数         5
交易金额      1047
Name: 22796, dtype: int64
内部标识号    22798
交易次数         3
交易金额      3874
Name: 22797, dtype: int64
内部标识号    22799
交易次数         9
交易金额       112
Name: 22798, dtype: int64
内部标识号    22800
交易次数         1
交易金额       809
Name: 22799, dtype: int64
内部标识号    22801
交易次数         0
交易金额       187
Name: 22800, dtype: int64
内部标识号    22802
交易次数         3
交易金额       473
Name: 22801, dtype: int64
内部标识号    22803
交易次数       117
交易金额     30331
Name: 22802, dtype: int64
内部标识号    22804
交易次数         2
交易金额       467
Name: 22803, dtype: int64
内部标识号    22805
交易次数         2
交易金额       311
Name: 22804, dtype: int64
内部标识号    22806
交易次数         9
交易金额       169
Name: 22805, dtype: int64
内部标识号    22807
交易次数         3
交易金额       343
Name: 22806, dtype: int64
内部标识号    22808
交易次数         6
交易金额       472
Name: 22807, dtype: int64
内部标识号    22809
交易次数         3
交易金额       382
Name: 22808, dtype: int64
内部标识号    22810
交易次数        12
交易金额       121
Name: 22809, dtype: int64
内部标识号    22811
交易次数         3
交易金额       307
Name: 22810, dtype: int64
内部标识号    22812
交易次数         3
交易金额       496
Name: 22811, dtype: int64
内部标识号    22813
交易次数         0
交易金额     15279
Name: 22812, dtype: int64
内部标识号    22814
交易次数         2
交易金额       305
Name: 22813, dtype: int64
内部标识号    22815

Name: 23008, dtype: int64
内部标识号    23010
交易次数         0
交易金额     66120
Name: 23009, dtype: int64
内部标识号    23011
交易次数         3
交易金额       467
Name: 23010, dtype: int64
内部标识号    23012
交易次数         0
交易金额     28528
Name: 23011, dtype: int64
内部标识号    23013
交易次数         0
交易金额       165
Name: 23012, dtype: int64
内部标识号    23014
交易次数         0
交易金额       294
Name: 23013, dtype: int64
内部标识号    23015
交易次数         2
交易金额       303
Name: 23014, dtype: int64
内部标识号    23016
交易次数         1
交易金额       116
Name: 23015, dtype: int64
内部标识号    23017
交易次数         2
交易金额       355
Name: 23016, dtype: int64
内部标识号    23018
交易次数         2
交易金额       425
Name: 23017, dtype: int64
内部标识号    23019
交易次数         0
交易金额     28118
Name: 23018, dtype: int64
内部标识号    23020
交易次数         6
交易金额      4297
Name: 23019, dtype: int64
内部标识号    23021
交易次数         0
交易金额     12107
Name: 23020, dtype: int64
内部标识号    23022
交易次数         3
交易金额      4174
Name: 23021, dtype: int64
内部标识号    23023
交易次数         8
交易金额       266
Name: 23022, dtype: int64
内部标识号    23024
交易次数         2
交易金额       364
Name: 23023, dtype: int64
内部标识号    23025
交易次数         3
交易金额       481
Name: 23024, dtype: int64
内部标识号    23026
交易次数         2
交易金额       463
Name: 23025, dtype: int64
内部标识号    23027
交易次数         3
交易金额       469
Name: 23026, dtype: int64
内部标识号    23028
交易次数         3
交易金额       330
Name: 23027, dtype: int64
内部标识号    23029
交易次数         0
交易金额     92419
Name: 23028, dtype: int64
内部标识号    23030
交易次数         2
交易金额       385
Name: 23029, dtype: int64
内部标识号    23031
交易次数         1
交易金额       711
Name: 23030, dtype: int64
内部标识号    23032
交易次数         3
交易金额       492
Name: 23031, dtype: int64
内部标识号    23033
交易次数         9
交易金额       276
Name: 23032, dtype: int64
内部标识号    23034
交易次数        12
交易金额       282
Name: 23033, dtype: int64
内部标识号    23035
交易次数         3
交易金额       412
Name: 23034, dtype: int64
内部标识号    23036
交易次数         0
交易金额       293
Name: 23035, dtype: int64
内部标识号    23037
交易次数         2
交易金额         2
Name: 23036, dtype: int64
内部标识号    23038
交易次数         3
交易金额       459
Name: 23037, dtype: int64
内部标识号    23039
交易次数         1
交易金额       787
Name: 23038, dtype: int64
内部标识号    23040
交易次数         3
交易金额       335
Name: 23039, dtype: int64
内部标识号    23041
交易次数         6
交易金额       484
Name: 23040, dtype: int64
内部标识号    23042
交易次数         7
交易金额      8760
Name: 23041, dtype: int64
内部标识号    23043
交易次数         2
交易金额       614
Name: 23042, dtype: int64
内部标识号    23044
交易次数         2
交易金额       404
Name: 23043, dtype: int64
内部标识号    23045
交易次数         1
交易金额       122
Name: 23044, dtype: int64
内部标识号    23046
交易次数         2
交易金额       357
Name: 23045, dtype: int64
内部标识号    23047
交易次数         2
交易金额       494
Name: 23046, dtype: int64
内部标识号    23048
交易次数         3
交易金额       354
Name: 23047, dtype: int64
内部标识号    23049
交易次数         1
交易金额       212
Name: 23048, dtype: int64
内部标识号    23050
交易次数         6
交易金额       397
Name: 23049, dtype: int64
内部标识号    23051
交易次数         2
交易金额       793
Name: 23050, dtype: int64
内部标识号    23052
交易次数        32
交易金额     49892
Name: 23051, dtype: int64
内部标识号    23053
交易次数         3
交易金额       474
Name: 23052, dtype: int64
内部标识号    23054
交易次数         1
交易金额     67580
Name: 23053, dtype: int64
内部标识号    23055
交易次数         3
交易金额       372
Name: 23054, dtype: int64
内部标识号    23056
交易次数         7
交易金额       941
Name: 23055, dtype: int64
内部标识号    23057
交易次数        12
交易金额       259
Name: 23056, dtype: int64
内部标识号    23058
交易次数        15
交易金额       847
Name: 23057, dtype: int64
内部标识号    23059
交易次数         1
交易金额       293
Name: 23058, dtype: int64
内部标识号    23060
交易次数         1
交易金额       143
Name: 23059, dtype: int64
内部标识号    23061
交易次数        27
交易金额       705
Name: 23060, dtype: int64
内部标识号    23062
交易次数        15
交易金额       598
Name: 23061, dtype: int64
内部标识号    23063
交易次数         5
交易金额       374
Name: 23062, dtype: int64
内部标识号    23064
交易次数         0
交易金额     46238
Name: 23063, dtype: int64
内部标识号    23065
交易次数       200
交易金额     41731
Name: 23064, dtype: int64
内部标识号    23066
交易次数         7
交易金额      6446
Name: 23065, dtype: int64
内部标识号    23067
交易次数         6
交易金额      5699
Name: 23066, dtype: int64
内部标识号    23068
交易次数         4
交易金额      3206
Name: 23067, dtype: int64
内部标识号    23069
交易次数         3
交易金额      6121
Name: 23068, dtype: int64
内部标识号    23070
交易次数        11
交易金额       137
Name: 23069, dtype: int64
内部标识号    23071
交易次数         2
交易金额       327
Name: 23070, dtype: int64
内部标识号    23072
交易次数         2
交易金额       467
Name: 23071, dtype: int64
内部标识号    23073
交易次数        13
交易金额       139
Name: 23072, dtype: int64
内部标识号    23074
交易次数         7
交易金额      3738
Name: 23073, dtype: int64
内部标识号    23075
交易次数         2
交易金额       488
Name: 23074, dtype: int64
内部标识号    23076
交易次数         0
交易金额       294
Name: 23075, dtype: int64
内部标识号    23077
交易次数         2
交易金额       333
Name: 23076, dtype: int64
内部标识号    23078
交易次数         1
交易金额       903
Name: 23077, dtype: int64
内部标识号    23079
交易次数         0
交易金额       260
Name: 23078, dtype: int64
内部标识号    23080
交易次数         1
交易金额       866
Name: 23079, dtype: int64
内部标识号    23081
交易次数         5
交易金额      8488
Name: 23080, dtype: int64
内部标识号    23082
交易次数        15
交易金额       122
Name: 23081, dtype: int64
内部标识号    23083
交易次数         4
交易金额       330
Name: 23082, dtype: int64
内部标识号    23084
交易次数         6
交易金额       624
Name: 23083, dtype: int64
内部标识号    23085
交易次数         2
交易金额       499
Name: 23084, dtype: int64
内部标识号    23086
交易次数         2
交易金额        19
Name: 23085, dtype: int64
内部标识号    23087
交易次数         8
交易金额       158
Name: 23086, dtype: int64
内部标识号    23088
交易次数         0
交易金额     27137
Name: 23087, dtype: int64
内部标识号    23089
交易次数         3
交易金额       375
Name: 23088, dtype: int64
内部标识号    23090
交易次数         3
交易金额       452
Name: 23089, dtype: int64
内部标识号    23091
交易次数         2
交易金额       408
Name: 23090, dtype: int64
内部标识号    23092
交易次数         1
交易金额       599
Name: 23091, dtype: int64
内部标识号    23093
交易次数         2
交易金额       804
Name: 23092, dtype: int64
内部标识号    23094
交易次数        15
交易金额       608
Name: 23093, dtype: int64
内部标识号    23095
交易次数         8
交易金额       308
Name: 23094, dtype: int64
内部标识号    23096
交易次数         6
交易金额       406
Name: 23095, dtype: int64
内部标识号    23097
交易次数         3
交易金额       380
Name: 23096, dtype: int64
内部标识号    23098
交易次数         2
交易金额        44
Name: 23097, dtype: int64
内部标识号    23099
交易次数         3
交易金额      9207
Name: 23098, dtype: int64
内部标识号    23100
交易次数         1
交易金额       254
Name: 23099, dtype: int64
内部标识号    23101
交易次数         5
交易金额      4724
Name: 23100, dtype: int64
内部标识号    23102
交易次数         0
交易金额       259
Name: 23101, dtype: int64
内部标识号    23103
交易次数         0
交易金额     21068
Name: 23102, dtype: int64
内部标识号    23104
交易次数         8
交易金额       617
Name: 23103, dtype: int64
内部标识号    23105
交易次数         3
交易金额       440
Name: 23104, dtype: int64
内部标识号    23106
交易次数         3
交易金额       308
Name: 23105, dtype: int64
内部标识号    23107
交易次数         3
交易金额       440
Name: 23106, dtype: int64
内部标识号    23108
交易次数         2
交易金额       403
Name: 23107, dtype: int64
内部标识号    23109
交易次数         2
交易金额       386
Name: 23108, dtype: int64
内部标识号    23110
交易次数         0
交易金额       170
Name: 23109, dtype: int64
内部标识号    23111
交易次数         2
交易金额       340
Name: 23110, dtype: int64
内部标识号    23112
交易次数         3
交易金额       308
Name: 23111, dtype: int64
内部标识号    23113
交易次数         1
交易金额       234
Name: 23112, dtype: int64
内部标识号    23114
交易次数         5
交易金额      1783
Name: 23113, dtype: int64
内部标识号    23115
交易次数         7
交易金额      2375
Name: 23114, dtype: int64
内部标识号    23116
交易次数         1
交易金额       202
Name: 23115, dtype: int64
内部标识号    23117
交易次数         5
交易金额       614
Name: 23116, dtype: int64
内部标识号    23118
交易次数        13
交易金额       225
Name: 23117, dtype: int64
内部标识号    23119
交易次数         1
交易金额       857
Name: 23118, dtype: int64
内部标识号    23120
交易次数         7
交易金额       473
Name: 23119, dtype: int64
内部标识号    23121
交易次数        13
交易金额       199
Name: 23120, dtype: int64
内部标识号    23122
交易次数         3
交易金额       353
Name: 23121, dtype: int64
内部标识号    23123
交易次数         1
交易金额       877
Name: 23122, dtype: int64
内部标识号    23124
交易次数        15
交易金额       240
Name: 23123, dtype: int64
内部标识号    23125
交易次数        14
交易金额       110
Name: 23124, dtype: int64
内部标识号    23126
交易次数         7
交易金额       381
Name: 23125, dtype: int64
内部标识号    23127
交易次数         0
交易金额       286
Name: 23126, dtype: int64
内部标识号    23128
交易次数         5
交易金额      9739
Name: 23127, dtype: int64
内部标识号    23129
交易次数         1
交易金额       972
Name: 23128, dtype: int64
内部标识号    23130
交易次数        12
交易金额       223
Name: 23129, dtype: int64
内部标识号    23131
交易次数         4
交易金额       453
Name: 23130, dtype: int64
内部标识号    23132
交易次数         0
交易金额       220
Name: 23131, dtype: int64
内部标识号    23133
交易次数         5
交易金额      5620
Name: 23132, dtype: int64
内部标识号    23134
交易次数        12
交易金额       167
Name: 23133, dtype: int64
内部标识号    23135
交易次数         1
交易金额      1000
Name: 23134, dtype: int64
内部标识号    23136
交易次数         3
交易金额       451
Name: 23135, dtype: int64
内部标识号    23137
交易次数         0
交易金额       116
Name: 23136, dtype: int64
内部标识号    23138
交易次数         0
交易金额     51455
Name: 23137, dtype: int64
内部标识号    23139
交易次数         2
交易金额        85
Name: 23138, dtype: int64
内部标识号    23140
交易次数         3
交易金额       470
Name: 23139, dtype: int64
内部标识号    23141
交易次数         2
交易金额       419
Name: 23140, dtype: int64
内部标识号    23142
交易次数         2
交易金额       496
Name: 23141, dtype: int64
内部标识号    23143
交易次数         1
交易金额       602
Name: 23142, dtype: int64
内部标识号    23144
交易次数         1
交易金额       734
Name: 23143, dtype: int64
内部标识号    23145
交易次数         2
交易金额       492
Name: 23144, dtype: int64
内部标识号    23146
交易次数        12
交易金额       100
Name: 23145, dtype: int64
内部标识号    23147
交易次数         1
交易金额       209
Name: 23146, dtype: int64
内部标识号    23148
交易次数        12
交易金额       171
Name: 23147, dtype: int64
内部标识号    23149
交易次数         3
交易金额      8694
Name: 23148, dtype: int64
内部标识号    23150
交易次数        52
交易金额     12971
Name: 23149, dtype: int64
内部标识号    23151
交易次数         8
交易金额       379
Name: 23150, dtype: int64
内部标识号    23152
交易次数         3
交易金额       713
Name: 23151, dtype: int64
内部标识号    23153
交易次数         6
交易金额       433
Name: 23152, dtype: int64
内部标识号    23154
交易次数         2
交易金额       461
Name: 23153, dtype: int64
内部标识号    23155
交易次数         1
交易金额       730
Name: 23154, dtype: int64
内部标识号    23156
交易次数         3
交易金额       393
Name: 23155, dtype: int64
内部标识号    23157
交易次数        14
交易金额       280
Name: 23156, dtype: int64
内部标识号    23158
交易次数         3
交易金额       328
Name: 23157, dtype: int64
内部标识号    23159
交易次数         2
交易金额        14
Name: 23158, dtype: int64
内部标识号    23160
交易次数         3
交易金额       378
Name: 23159, dtype: int64
内部标识号    23161
交易次数        27
交易金额       834
Name: 23160, dtype: int64
内部标识号    23162
交易次数         3
交易金额       573
Name: 23161, dtype: int64
内部标识号    23163
交易次数         3
交易金额       436
Name: 23162, dtype: int64
内部标识号    23164
交易次数        15
交易金额       508
Name: 23163, dtype: int64
内部标识号    23165
交易次数         0
交易金额     74110
Name: 23164, dtype: int64
内部标识号    23166
交易次数         2
交易金额       342
Name: 23165, dtype: int64
内部标识号    23167
交易次数         6
交易金额      6121
Name: 23166, dtype: int64
内部标识号    23168
交易次数         1
交易金额       753
Name: 23167, dtype: int64
内部标识号    23169
交易次数         1
交易金额       204
Name: 23168, dtype: int64
内部标识号    23170
交易次数         5
交易金额      3191
Name: 23169, dtype: int64
内部标识号    23171
交易次数         2
交易金额       385
Name: 23170, dtype: int64
内部标识号    23172
交易次数        11
交易金额       204
Name: 23171, dtype: int64
内部标识号    23173
交易次数       142
交易金额     56987
Name: 23172, dtype: int64
内部标识号    23174
交易次数         2
交易金额       438
Name: 23173, dtype: int64
内部标识号    23175
交易次数         3
交易金额      6806
Name: 23174, dtype: int64
内部标识号    23176
交易次数        14
交易金额       199
Name: 23175, dtype: int64
内部标识号    23177
交易次数         4
交易金额      7744
Name: 23176, dtype: int64
内部标识号    23178
交易次数         3
交易金额       348
Name: 23177, dtype: int64
内部标识号    23179
交易次数         8
交易金额      2393
Name: 23178, dtype: int64
内部标识号    23180
交易次数         2
交易金额       324
Name: 23179, dtype: int64
内部标识号    23181
交易次数        21
交易金额       792
Name: 23180, dtype: int64
内部标识号    23182
交易次数         3
交易金额       400
Name: 23181, dtype: int64
内部标识号    23183
交易次数         3
交易金额       458
Name: 23182, dtype: int64
内部标识号    23184
交易次数         3
交易金额       366
Name: 23183, dtype: int64
内部标识号    23185
交易次数         6
交易金额       325
Name: 23184, dtype: int64
内部标识号    23186
交易次数         0
交易金额     61232
Name: 23185, dtype: int64
内部标识号    23187
交易次数         4
交易金额      2837
Name: 23186, dtype: int64
内部标识号    23188
交易次数         3
交易金额       325
Name: 23187, dtype: int64
内部标识号    23189
交易次数         2
交易金额       411
Name: 23188, dtype: int64
内部标识号    23190
交易次数        12
交易金额       248
Name: 23189, dtype: int64
内部标识号    23191
交易次数         6
交易金额      8676
Name: 23190, dtype: int64
内部标识号    23192
交易次数         1
交易金额       555
Name: 23191, dtype: int64
内部标识号    23193
交易次数         2
交易金额       460
Name: 23192, dtype: int64
内部标识号    23194
交易次数         0
交易金额       130
Name: 23193, dtype: int64
内部标识号    23195
交易次数       276
交易金额     23942
Name: 23194, dtype: int64
内部标识号    23196
交易次数         2
交易金额       337
Name: 23195, dtype: int64
内部标识号    23197
交易次数         3
交易金额      3896
Name: 23196, dtype: int64
内部标识号    23198
交易次数        14
交易金额       138
Name: 23197, dtype: int64
内部标识号    23199
交易次数         6
交易金额      9579
Name: 23198, dtype: int64
内部标识号    23200
交易次数        10
交易金额       105
Name: 23199, dtype: int64
内部标识号    23201
交易次数         3
交易金额      2293
Name: 23200, dtype: int64
内部标识号    23202
交易次数         5
交易金额       488
Name: 23201, dtype: int64
内部标识号    23203
交易次数         3
交易金额      3628
Name: 23202, dtype: int64
内部标识号    23204
交易次数         3
交易金额       481
Name: 23203, dtype: int64
内部标识号    23205
交易次数         0
交易金额     99884
Name: 23204, dtype: int64
内部标识号    23206
交易次数         3
交易金额       476
Name: 23205, dtype: int64
内部标识号    23207
交易次数         0
交易金额     57309
Name: 23206, dtype: int64
内部标识号    23208
交易次数         4
交易金额       809
Name: 23207, dtype: int64
内部标识号    23209
交易次数         3
交易金额      9640
Name: 23208, dtype: int64
内部标识号    23210
交易次数         6
交易金额      9347
Name: 23209, dtype: int64
内部标识号    23211
交易次数        10
交易金额       164
Name: 23210, dtype: int64
内部标识号    23212
交易次数         0
交易金额     28581
Name: 23211, dtype: int64
内部标识号    23213
交易次数         0
交易金额       140
Name: 23212, dtype: int64
内部标识号    23214
交易次数        20
交易金额       532
Name: 23213, dtype: int64
内部标识号    23215
交易次数         3
交易金额       333
Name: 23214, dtype: int64
内部标识号    23216
交易次数         1
交易金额       988
Name: 23215, dtype: int64
内部标识号    23217
交易次数         2
交易金额       486
Name: 23216, dtype: int64
内部标识号    23218
交易次数         2
交易金额       502
Name: 23217, dtype: int64
内部标识号    23219
交易次数         2
交易金额       359
Name: 23218, dtype: int64
内部标识号    23220
交易次数         2
交易金额       376
Name: 23219, dtype: int64
内部标识号    23221
交易次数         0
交易金额       160
Name: 23220, dtype: int64
内部标识号    23222
交易次数         3
交易金额       493
Name: 23221, dtype: int64
内部标识号    23223
交易次数         5
交易金额       887
Name: 23222, dtype: int64
内部标识号    23224
交易次数         6
交易金额      2409
Name: 23223, dtype: int64
内部标识号    23225
交易次数         0
交易金额       120
Name: 23224, dtype: int64
内部标识号    23226
交易次数         8
交易金额       370
Name: 23225, dtype: int64
内部标识号    23227
交易次数        19
交易金额       901
Name: 23226, dtype: int64
内部标识号    23228
交易次数         0
交易金额       114
Name: 23227, dtype: int64
内部标识号    23229
交易次数         2
交易金额       497
Name: 23228, dtype: int64
内部标识号    23230
交易次数       191
交易金额     90871
Name: 23229, dtype: int64
内部标识号    23231
交易次数        12
交易金额       110
Name: 23230, dtype: int64
内部标识号    23232
交易次数         2
交易金额       396
Name: 23231, dtype: int64
内部标识号    23233
交易次数         1
交易金额       203
Name: 23232, dtype: int64
内部标识号    23234
交易次数         3
交易金额       369
Name: 23233, dtype: int64
内部标识号    23235
交易次数         1
交易金额       248
Name: 23234, dtype: int64
内部标识号    23236
交易次数         0
交易金额     27164
Name: 23235, dtype: int64
内部标识号    23237
交易次数        14
交易金额       185
Name: 23236, dtype: int64
内部标识号    23238
交易次数        15
交易金额       209
Name: 23237, dtype: int64
内部标识号    23239
交易次数         2
交易金额       456
Name: 23238, dtype: int64
内部标识号    23240
交易次数         3
交易金额       411
Name: 23239, dtype: int64
内部标识号    23241
交易次数         2
交易金额       362
Name: 23240, dtype: int64
内部标识号    23242
交易次数         2
交易金额       476
Name: 23241, dtype: int64
内部标识号    23243
交易次数        13
交易金额       288
Name: 23242, dtype: int64
内部标识号    23244
交易次数         1
交易金额       826
Name: 23243, dtype: int64
内部标识号    23245
交易次数         2
交易金额       489
Name: 23244, dtype: int64
内部标识号    23246
交易次数         2
交易金额       751
Name: 23245, dtype: int64

内部标识号    23247
交易次数         0
交易金额       137
Name: 23246, dtype: int64
内部标识号    23248
交易次数         1
交易金额     16118
Name: 23247, dtype: int64
内部标识号    23249
交易次数        10
交易金额       191
Name: 23248, dtype: int64
内部标识号    23250
交易次数         2
交易金额       411
Name: 23249, dtype: int64
内部标识号    23251
交易次数         4
交易金额       488
Name: 23250, dtype: int64
内部标识号    23252
交易次数         1
交易金额       505
Name: 23251, dtype: int64
内部标识号    23253
交易次数         7
交易金额       317
Name: 23252, dtype: int64
内部标识号    23254
交易次数        19
交易金额       746
Name: 23253, dtype: int64
内部标识号    23255
交易次数         4
交易金额       885
Name: 23254, dtype: int64
内部标识号    23256
交易次数         3
交易金额       355
Name: 23255, dtype: int64
内部标识号    23257
交易次数         2
交易金额       381
Name: 23256, dtype: int64
内部标识号    23258
交易次数        25
交易金额       956
Name: 23257, dtype: int64
内部标识号    23259
交易次数         2
交易金额       352
Name: 23258, dtype: int64
内部标识号    23260
交易次数         2
交易金额        51
Name: 23259, dtype: int64
内部标识号    23261
交易次数         2
交易金额       506
Name: 23260, dtype: int64
内部标识号    23262
交易次数         2
交易金额       881
Name: 23261, dtype: int64
内部标识号    23263
交易次数        14
交易金额       160
Name: 23262, dtype: int64
内部标识号    23264
交易次数         3
交易金额       385
Name: 23263, dtype: int64
内部标识号    23265
交易次数         2
交易金额        21
Name: 23264, dtype: int64
内部标识号    23266
交易次数         8
交易金额      1633
Name: 23265, dtype: int64
内部标识号    23267
交易次数         2
交易金额       402
Name: 23266, dtype: int64
内部标识号    23268
交易次数         3
交易金额       732
Name: 23267, dtype: int64
内部标识号    23269
交易次数         5
交易金额       887
Name: 23268, dtype: int64
内部标识号    23270
交易次数         4
交易金额       444
Name: 23269, dtype: int64
内部标识号    23271
交易次数         8
交易金额      4826
Name: 23270, dtype: int64
内部标识号    23272
交易次数         1
交易金额       972
Name: 23271, dtype: int64
内部标识号    23273
交易次数         1
交易金额       557
Name: 23272, dtype: int64
内部标识号    23274
交易次数         7
交易金额       437
Name: 23273, dtype: int64
内部标识号    23275
交易次数         2
交易金额       604
Name: 23274, dtype: int64
内部标识号    23276
交易次数         7
交易金额       694
Name: 23275, dtype: int64
内部标识号    23277
交易次数         8
交易金额      4104
Name: 23276, dtype: int64
内部标识号    23278
交易次数         6
交易金额      3905
Name: 23277, dtype: int64
内部标识号    23279
交易次数        14
交易金额       249
Name: 23278, dtype: int64
内部标识号    23280
交易次数         2
交易金额       375
Name: 23279, dtype: int64
内部标识号    23281
交易次数         2
交易金额       627
Name: 23280, dtype: int64
内部标识号    23282
交易次数         3
交易金额       406
Name: 23281, dtype: int64
内部标识号    23283
交易次数         3
交易金额       433
Name: 23282, dtype: int64
内部标识号    23284
交易次数         3
交易金额       873
Name: 23283, dtype: int64
内部标识号    23285
交易次数         0
交易金额       102
Name: 23284, dtype: int64
内部标识号    23286
交易次数         0
交易金额     75404
Name: 23285, dtype: int64
内部标识号    23287
交易次数         3
交易金额       413
Name: 23286, dtype: int64
内部标识号    23288
交易次数        27
交易金额       632
Name: 23287, dtype: int64
内部标识号    23289
交易次数         3
交易金额       327
Name: 23288, dtype: int64
内部标识号    23290
交易次数         2
交易金额       765
Name: 23289, dtype: int64
内部标识号    23291
交易次数         9
交易金额       253
Name: 23290, dtype: int64
内部标识号    23292
交易次数         2
交易金额       396
Name: 23291, dtype: int64
内部标识号    23293
交易次数         7
交易金额       350
Name: 23292, dtype: int64
内部标识号    23294
交易次数         6
交易金额       454
Name: 23293, dtype: int64
内部标识号    23295
交易次数         2
交易金额       477
Name: 23294, dtype: int64
内部标识号    23296
交易次数         3
交易金额       384
Name: 23295, dtype: int64
内部标识号    23297
交易次数        11
交易金额       178
Name: 23296, dtype: int64
内部标识号    23298
交易次数         2
交易金额     89211
Name: 23297, dtype: int64
内部标识号    23299
交易次数         8
交易金额      4327
Name: 23298, dtype: int64
内部标识号    23300
交易次数         4
交易金额       593
Name: 23299, dtype: int64
内部标识号    23301
交易次数         6
交易金额      4902
Name: 23300, dtype: int64
内部标识号    23302
交易次数         1
交易金额       217
Name: 23301, dtype: int64
内部标识号    23303
交易次数         2
交易金额       450
Name: 23302, dtype: int64
内部标识号    23304
交易次数         3
交易金额       318
Name: 23303, dtype: int64
内部标识号    23305
交易次数         1
交易金额        90
Name: 23304, dtype: int64
内部标识号    23306
交易次数         3
交易金额       404
Name: 23305, dtype: int64
内部标识号    23307
交易次数         7
交易金额       326
Name: 23306, dtype: int64
内部标识号    23308
交易次数         3
交易金额      2796
Name: 23307, dtype: int64
内部标识号    23309
交易次数         3
交易金额       361
Name: 23308, dtype: int64
内部标识号    23310
交易次数         2
交易金额       390
Name: 23309, dtype: int64
内部标识号    23311
交易次数         3
交易金额       359
Name: 23310, dtype: int64
内部标识号    23312
交易次数        14
交易金额       229
Name: 23311, dtype: int64
内部标识号    23313
交易次数         3
交易金额       474
Name: 23312, dtype: int64
内部标识号    23314
交易次数         4
交易金额      1842
Name: 23313, dtype: int64
内部标识号    23315
交易次数       122
交易金额     22888
Name: 23314, dtype: int64
内部标识号    23316
交易次数         2
交易金额       457
Name: 23315, dtype: int64
内部标识号    23317
交易次数         2
交易金额       855
Name: 23316, dtype: int64
内部标识号    23318
交易次数         8
交易金额      6316
Name: 23317, dtype: int64
内部标识号    23319
交易次数         2
交易金额       780
Name: 23318, dtype: int64
内部标识号    23320
交易次数         2
交易金额       438
Name: 23319, dtype: int64
内部标识号    23321
交易次数         1
交易金额       519
Name: 23320, dtype: int64
内部标识号    23322
交易次数         3
交易金额       376
Name: 23321, dtype: int64
内部标识号    23323
交易次数         6
交易金额      6270
Name: 23322, dtype: int64
内部标识号    23324
交易次数       246
交易金额     87543
Name: 23323, dtype: int64
内部标识号    23325
交易次数         3
交易金额       411
Name: 23324, dtype: int64
内部标识号    23326
交易次数         4
交易金额      2207
Name: 23325, dtype: int64
内部标识号    23327
交易次数        18
交易金额       500
Name: 23326, dtype: int64
内部标识号    23328
交易次数        17
交易金额       739
Name: 23327, dtype: int64
内部标识号    23329
交易次数         3
交易金额       433
Name: 23328, dtype: int64
内部标识号    23330
交易次数         2
交易金额       479
Name: 23329, dtype: int64
内部标识号    23331
交易次数         8
交易金额       130
Name: 23330, dtype: int64
内部标识号    23332
交易次数         0
交易金额     55833
Name: 23331, dtype: int64
内部标识号    23333
交易次数        12
交易金额       160
Name: 23332, dtype: int64
内部标识号    23334
交易次数        23
交易金额       978
Name: 23333, dtype: int64
内部标识号    23335
交易次数        15
交易金额       158
Name: 23334, dtype: int64
内部标识号    23336
交易次数         8
交易金额       480
Name: 23335, dtype: int64
内部标识号    23337
交易次数         3
交易金额       355
Name: 23336, dtype: int64
内部标识号    23338
交易次数         8
交易金额       119
Name: 23337, dtype: int64
内部标识号    23339
交易次数         2
交易金额       469
Name: 23338, dtype: int64
内部标识号    23340
交易次数         2
交易金额       869
Name: 23339, dtype: int64
内部标识号    23341
交易次数         6
交易金额      8126
Name: 23340, dtype: int64
内部标识号    23342
交易次数        10
交易金额       267
Name: 23341, dtype: int64
内部标识号    23343
交易次数         3
交易金额       351
Name: 23342, dtype: int64
内部标识号    23344
交易次数        14
交易金额       193
Name: 23343, dtype: int64
内部标识号    23345
交易次数        25
交易金额       636
Name: 23344, dtype: int64
内部标识号    23346
交易次数         7
交易金额       449
Name: 23345, dtype: int64
内部标识号    23347
交易次数         6
交易金额       613
Name: 23346, dtype: int64
内部标识号    23348
交易次数         1
交易金额       292
Name: 23347, dtype: int64
内部标识号    23349
交易次数        10
交易金额       184
Name: 23348, dtype: int64
内部标识号    23350
交易次数         1
交易金额        93
Name: 23349, dtype: int64
内部标识号    23351
交易次数         0
交易金额     10544
Name: 23350, dtype: int64
内部标识号    23352
交易次数         5
交易金额      6404
Name: 23351, dtype: int64
内部标识号    23353
交易次数         3
交易金额       479
Name: 23352, dtype: int64
内部标识号    23354
交易次数         3
交易金额       342
Name: 23353, dtype: int64
内部标识号    23355
交易次数         2
交易金额       374
Name: 23354, dtype: int64
内部标识号    23356
交易次数        15
交易金额       225
Name: 23355, dtype: int64
内部标识号    23357
交易次数         0
交易金额       282
Name: 23356, dtype: int64
内部标识号    23358
交易次数         3
交易金额      9141
Name: 23357, dtype: int64
内部标识号    23359
交易次数         3
交易金额       322
Name: 23358, dtype: int64
内部标识号    23360
交易次数         3
交易金额       313
Name: 23359, dtype: int64
内部标识号    23361
交易次数         1
交易金额       728
Name: 23360, dtype: int64
内部标识号    23362
交易次数         5
交易金额       403
Name: 23361, dtype: int64
内部标识号    23363
交易次数        11
交易金额       176
Name: 23362, dtype: int64
内部标识号    23364
交易次数        11
交易金额       267
Name: 23363, dtype: int64
内部标识号    23365
交易次数         1
交易金额       509
Name: 23364, dtype: int64
内部标识号    23366
交易次数        12
交易金额       274
Name: 23365, dtype: int64
内部标识号    23367
交易次数         2
交易金额       450
Name: 23366, dtype: int64
内部标识号    23368
交易次数         3
交易金额       379
Name: 23367, dtype: int64
内部标识号    23369
交易次数         1
交易金额       581
Name: 23368, dtype: int64
内部标识号    23370
交易次数         4
交易金额      7247
Name: 23369, dtype: int64
内部标识号    23371
交易次数         5
交易金额      5377
Name: 23370, dtype: int64
内部标识号    23372
交易次数         7
交易金额      7340
Name: 23371, dtype: int64
内部标识号    23373
交易次数         3
交易金额       402
Name: 23372, dtype: int64
内部标识号    23374
交易次数         1
交易金额       994
Name: 23373, dtype: int64
内部标识号    23375
交易次数         7
交易金额       752
Name: 23374, dtype: int64
内部标识号    23376
交易次数         5
交易金额      8204
Name: 23375, dtype: int64
内部标识号    23377
交易次数         6
交易金额      3782
Name: 23376, dtype: int64
内部标识号    23378
交易次数         2
交易金额     45433
Name: 23377, dtype: int64
内部标识号    23379
交易次数         7
交易金额      5611
Name: 23378, dtype: int64
内部标识号    23380
交易次数         3
交易金额       440
Name: 23379, dtype: int64
内部标识号    23381
交易次数         1
交易金额       139
Name: 23380, dtype: int64
内部标识号    23382
交易次数         7
交易金额      2843
Name: 23381, dtype: int64
内部标识号    23383
交易次数         3
交易金额       344
Name: 23382, dtype: int64
内部标识号    23384
交易次数         2
交易金额       946
Name: 23383, dtype: int64
内部标识号    23385
交易次数         3
交易金额       404
Name: 23384, dtype: int64
内部标识号    23386
交易次数         6
交易金额       773
Name: 23385, dtype: int64
内部标识号    23387
交易次数         3
交易金额       342
Name: 23386, dtype: int64
内部标识号    23388
交易次数         0
交易金额       155
Name: 23387, dtype: int64
内部标识号    23389
交易次数         1
交易金额       298
Name: 23388, dtype: int64
内部标识号    23390
交易次数        10
交易金额       160
Name: 23389, dtype: int64
内部标识号    23391
交易次数         0
交易金额     83801
Name: 23390, dtype: int64
内部标识号    23392
交易次数         8
交易金额       249
Name: 23391, dtype: int64
内部标识号    23393
交易次数         1
交易金额        55
Name: 23392, dtype: int64
内部标识号    23394
交易次数         2
交易金额       333
Name: 23393, dtype: int64
内部标识号    23395
交易次数        12
交易金额       210
Name: 23394, dtype: int64
内部标识号    23396
交易次数         8
交易金额       153
Name: 23395, dtype: int64
内部标识号    23397
交易次数         7
交易金额       492
Name: 23396, dtype: int64
内部标识号    23398
交易次数         2
交易金额       823
Name: 23397, dtype: int64
内部标识号    23399
交易次数         2
交易金额       334
Name: 23398, dtype: int64
内部标识号    23400
交易次数         1
交易金额       632
Name: 23399, dtype: int64
内部标识号    23401
交易次数         3
交易金额       341
Name: 23400, dtype: int64
内部标识号    23402
交易次数         0
交易金额     73855
Name: 23401, dtype: int64
内部标识号    23403
交易次数         2
交易金额       468
Name: 23402, dtype: int64
内部标识号    23404
交易次数        11
交易金额       200
Name: 23403, dtype: int64
内部标识号    23405
交易次数        14
交易金额       114
Name: 23404, dtype: int64
内部标识号    23406
交易次数         2
交易金额       398
Name: 23405, dtype: int64
内部标识号    23407
交易次数       147
交易金额     34478
Name: 23406, dtype: int64
内部标识号    23408
交易次数         1
交易金额       240
Name: 23407, dtype: int64
内部标识号    23409
交易次数         0
交易金额       215
Name: 23408, dtype: int64
内部标识号    23410
交易次数         3
交易金额       334
Name: 23409, dtype: int64
内部标识号    23411
交易次数         6
交易金额      5105
Name: 23410, dtype: int64
内部标识号    23412
交易次数         2
交易金额       772
Name: 23411, dtype: int64
内部标识号    23413
交易次数         1
交易金额       520
Name: 23412, dtype: int64
内部标识号    23414
交易次数         0
交易金额     42087
Name: 23413, dtype: int64
内部标识号    23415
交易次数        21
交易金额       675
Name: 23414, dtype: int64
内部标识号    23416
交易次数        16
交易金额       780
Name: 23415, dtype: int64
内部标识号    23417
交易次数         2
交易金额       442
Name: 23416, dtype: int64
内部标识号    23418
交易次数         0
交易金额       287
Name: 23417, dtype: int64
内部标识号    23419
交易次数         3
交易金额       308
Name: 23418, dtype: int64
内部标识号    23420
交易次数         2
交易金额       464
Name: 23419, dtype: int64
内部标识号    23421
交易次数         3
交易金额       368
Name: 23420, dtype: int64
内部标识号    23422
交易次数         2
交易金额       418
Name: 23421, dtype: int64
内部标识号    23423
交易次数         2
交易金额       363
Name: 23422, dtype: int64
内部标识号    23424
交易次数         8
交易金额       874
Name: 23423, dtype: int64
内部标识号    23425
交易次数         2
交易金额       628
Name: 23424, dtype: int64
内部标识号    23426
交易次数         1
交易金额       138
Name: 23425, dtype: int64
内部标识号    23427
交易次数        27
交易金额       703
Name: 23426, dtype: int64
内部标识号    23428
交易次数         2
交易金额       342
Name: 23427, dtype: int64
内部标识号    23429
交易次数         2
交易金额       362
Name: 23428, dtype: int64
内部标识号    23430
交易次数         1
交易金额       651
Name: 23429, dtype: int64
内部标识号    23431
交易次数         8
交易金额      5148
Name: 23430, dtype: int64
内部标识号    23432
交易次数         2
交易金额        47
Name: 23431, dtype: int64
内部标识号    23433
交易次数         2
交易金额       383
Name: 23432, dtype: int64
内部标识号    23434
交易次数         1
交易金额       180
Name: 23433, dtype: int64
内部标识号    23435
交易次数         3
交易金额       994
Name: 23434, dtype: int64
内部标识号    23436
交易次数         1
交易金额       910
Name: 23435, dtype: int64
内部标识号    23437
交易次数         2
交易金额       862
Name: 23436, dtype: int64
内部标识号    23438
交易次数         4
交易金额      5121
Name: 23437, dtype: int64
内部标识号    23439
交易次数         8
交易金额       217
Name: 23438, dtype: int64
内部标识号    23440
交易次数         2
交易金额       373
Name: 23439, dtype: int64
内部标识号    23441
交易次数         2
交易金额       414
Name: 23440, dtype: int64
内部标识号    23442
交易次数        29
交易金额       674
Name: 23441, dtype: int64
内部标识号    23443
交易次数        10
交易金额       138
Name: 23442, dtype: int64
内部标识号    23444
交易次数         5
交易金额       321
Name: 23443, dtype: int64
内部标识号    23445
交易次数         2
交易金额       440
Name: 23444, dtype: int64
内部标识号    23446
交易次数        10
交易金额       165
Name: 23445, dtype: int64
内部标识号    23447
交易次数         2
交易金额       577
Name: 23446, dtype: int64
内部标识号    23448
交易次数         7
交易金额      8499
Name: 23447, dtype: int64
内部标识号    23449
交易次数         1
交易金额     30025
Name: 23448, dtype: int64
内部标识号    23450
交易次数         3
交易金额       353
Name: 23449, dtype: int64
内部标识号    23451
交易次数         2
交易金额       352
Name: 23450, dtype: int64
内部标识号    23452
交易次数         2
交易金额        66
Name: 23451, dtype: int64
内部标识号    23453
交易次数         2
交易金额       520
Name: 23452, dtype: int64
内部标识号    23454
交易次数         8
交易金额      6358
Name: 23453, dtype: int64
内部标识号    23455
交易次数         3
交易金额       470
Name: 23454, dtype: int64
内部标识号    23456
交易次数         2
交易金额       416
Name: 23455, dtype: int64
内部标识号    23457
交易次数         2
交易金额       489
Name: 23456, dtype: int64
内部标识号    23458
交易次数         5
交易金额       338
Name: 23457, dtype: int64
内部标识号    23459
交易次数         6
交易金额      5956
Name: 23458, dtype: int64
内部标识号    23460
交易次数         2
交易金额       879
Name: 23459, dtype: int64
内部标识号    23461
交易次数         2
交易金额       409
Name: 23460, dtype: int64
内部标识号    23462
交易次数         3
交易金额       481
Name: 23461, dtype: int64
内部标识号    23463
交易次数         2
交易金额       374
Name: 23462, dtype: int64
内部标识号    23464
交易次数         3
交易金额       496
Name: 23463, dtype: int64
内部标识号    23465
交易次数         2
交易金额       482
Name: 23464, dtype: int64
内部标识号    23466
交易次数        13
交易金额       280
Name: 23465, dtype: int64
内部标识号    23467
交易次数         3
交易金额       360
Name: 23466, dtype: int64
内部标识号    23468
交易次数         2
交易金额       749
Name: 23467, dtype: int64
内部标识号    23469
交易次数         8
交易金额      8907
Name: 23468, dtype: int64
内部标识号    23470
交易次数         5
交易金额      8264
Name: 23469, dtype: int64
内部标识号    23471
交易次数         5
交易金额      8035
Name: 23470, dtype: int64
内部标识号    23472
交易次数         3
交易金额       460
Name: 23471, dtype: int64
内部标识号    23473
交易次数         2
交易金额       405
Name: 23472, dtype: int64
内部标识号    23474
交易次数         2
交易金额       386
Name: 23473, dtype: int64
内部标识号    23475
交易次数         2
交易金额       963
Name: 23474, dtype: int64
内部标识号    23476
交易次数         0
交易金额     38244
Name: 23475, dtype: int64
内部标识号    23477
交易次数        12
交易金额       178
Name: 23476, dtype: int64
内部标识号    23478
交易次数        15
交易金额       194
Name: 23477, dtype: int64
内部标识号    23479
交易次数        30
交易金额       922
Name: 23478, dtype: int64
内部标识号    23480
交易次数        26
交易金额       802
Name: 23479, dtype: int64
内部标识号    23481
交易次数         0
交易金额       171
Name: 23480, dtype: int64
内部标识号    23482
交易次数         1
交易金额       270
Name: 23481, dtype: int64
内部标识号    23483
交易次数         3
交易金额       447
Name: 23482, dtype: int64
内部标识号    23484
交易次数         1
交易金额        55
Name: 23483, dtype: int64
内部标识号    23485
交易次数         3
交易金额       440
Name: 23484, dtype: int64
内部标识号    23486
交易次数         8
交易金额       785
Name: 23485, dtype: int64
内部标识号    23487
交易次数         3
交易金额       323
Name: 23486, dtype: int64
内部标识号    23488
交易次数         7
交易金额      5221
Name: 23487, dtype: int64
内部标识号    23489
交易次数        12
交易金额       122
Name: 23488, dtype: int64
内部标识号    23490
交易次数         8
交易金额       713
Name: 23489, dtype: int64
内部标识号    23491
交易次数         4
交易金额      4832
Name: 23490, dtype: int64
内部标识号    23492
交易次数         2
交易金额       730
Name: 23491, dtype: int64
内部标识号    23493
交易次数        11
交易金额       187
Name: 23492, dtype: int64
内部标识号    23494
交易次数         2
交易金额       689
Name: 23493, dtype: int64
内部标识号    23495
交易次数        14
交易金额       221
Name: 23494, dtype: int64
内部标识号    23496
交易次数         6
交易金额      4439
Name: 23495, dtype: int64
内部标识号    23497
交易次数         2
交易金额       350
Name: 23496, dtype: int64
内部标识号    23498
交易次数         1
交易金额       153
Name: 23497, dtype: int64
内部标识号    23499
交易次数         0
交易金额       274
Name: 23498, dtype: int64
内部标识号    23500
交易次数         2
交易金额       508
Name: 23499, dtype: int64
内部标识号    23501
交易次数         1
交易金额       224
Name: 23500, dtype: int64
内部标识号    23502
交易次数         3
交易金额       408
Name: 23501, dtype: int64
内部标识号    23503
交易次数         6
交易金额      3206
Name: 23502, dtype: int64
内部标识号    23504
交易次数         3
交易金额       449
Name: 23503, dtype: int64
内部标识号    23505
交易次数         3
交易金额       332
Name: 23504, dtype: int64
内部标识号    23506
交易次数         7
交易金额      8694
Name: 23505, dtype: int64
内部标识号    23507
交易次数         0
交易金额       256
Name: 23506, dtype: int64
内部标识号    23508
交易次数         0
交易金额     58826
Name: 23507, dtype: int64
内部标识号    23509
交易次数         5
交易金额       485
Name: 23508, dtype: int64
内部标识号    23510
交易次数         3
交易金额      4106
Name: 23509, dtype: int64
内部标识号    23511
交易次数         2
交易金额       592
Name: 23510, dtype: int64
内部标识号    23512
交易次数         0
交易金额       129
Name: 23511, dtype: int64
内部标识号    23513
交易次数         5
交易金额       882
Name: 23512, dtype: int64
内部标识号    23514
交易次数         5
交易金额      2189
Name: 23513, dtype: int64
内部标识号    23515
交易次数         3
交易金额       364
Name: 23514, dtype: int64
内部标识号    23516
交易次数        11
交易金额       147
Name: 23515, dtype: int64
内部标识号    23517
交易次数         3
交易金额       371
Name: 23516, dtype: int64
内部标识号    23518
交易次数         2
交易金额       355
Name: 23517, dtype: int64
内部标识号    23519
交易次数         2
交易金额       951
Name: 23518, dtype: int64
内部标识号    23520
交易次数         2
交易金额       489
Name: 23519, dtype: int64
内部标识号    23521
交易次数         1
交易金额       241
Name: 23520, dtype: int64
内部标识号    23522
交易次数         5
交易金额      3539
Name: 23521, dtype: int64
内部标识号    23523
交易次数         4
交易金额      8479
Name: 23522, dtype: int64
内部标识号    23524
交易次数         3
交易金额       490
Name: 23523, dtype: int64
内部标识号    23525
交易次数         2
交易金额       397
Name: 23524, dtype: int64
内部标识号    23526
交易次数         1
交易金额       225
Name: 23525, dtype: int64
内部标识号    23527
交易次数         7
交易金额      9375
Name: 23526, dtype: int64
内部标识号    23528
交易次数         3
交易金额       363

Name: 23745, dtype: int64
内部标识号    23747
交易次数         2
交易金额       391
Name: 23746, dtype: int64
内部标识号    23748
交易次数         3
交易金额      1918
Name: 23747, dtype: int64
内部标识号    23749
交易次数         3
交易金额       360
Name: 23748, dtype: int64
内部标识号    23750
交易次数         7
交易金额      2152
Name: 23749, dtype: int64
内部标识号    23751
交易次数         0
交易金额       257
Name: 23750, dtype: int64
内部标识号    23752
交易次数         0
交易金额       193
Name: 23751, dtype: int64
内部标识号    23753
交易次数         1
交易金额     74477
Name: 23752, dtype: int64
内部标识号    23754
交易次数         5
交易金额      5481
Name: 23753, dtype: int64
内部标识号    23755
交易次数        30
交易金额       661
Name: 23754, dtype: int64
内部标识号    23756
交易次数         5
交易金额      2721
Name: 23755, dtype: int64
内部标识号    23757
交易次数         3
交易金额       303
Name: 23756, dtype: int64
内部标识号    23758
交易次数         3
交易金额       333
Name: 23757, dtype: int64
内部标识号    23759
交易次数         8
交易金额       291
Name: 23758, dtype: int64
内部标识号    23760
交易次数         3
交易金额       416
Name: 23759, dtype: int64
内部标识号    23761
交易次数         0
交易金额       293
Name: 23760, dtype: int64
内部标识号    23762
交易次数         2
交易金额       439
Name: 23761, dtype: int64
内部标识号    23763
交易次数         2
交易金额       396
Name: 23762, dtype: int64
内部标识号    23764
交易次数         1
交易金额       173
Name: 23763, dtype: int64
内部标识号    23765
交易次数         3
交易金额       683
Name: 23764, dtype: int64
内部标识号    23766
交易次数         3
交易金额      2514
Name: 23765, dtype: int64
内部标识号    23767
交易次数        12
交易金额       290
Name: 23766, dtype: int64
内部标识号    23768
交易次数         1
交易金额       986
Name: 23767, dtype: int64
内部标识号    23769
交易次数         1
交易金额       742
Name: 23768, dtype: int64
内部标识号    23770
交易次数         3
交易金额       334
Name: 23769, dtype: int64
内部标识号    23771
交易次数         0
交易金额       213
Name: 23770, dtype: int64
内部标识号    23772
交易次数         1
交易金额       110
Name: 23771, dtype: int64
内部标识号    23773
交易次数         3
交易金额       498
Name: 23772, dtype: int64
内部标识号    23774
交易次数         0
交易金额       219
Name: 23773, dtype: int64
内部标识号    23775
交易次数         1
交易金额       213
Name: 23774, dtype: int64
内部标识号    23776
交易次数         2
交易金额       830
Name: 23775, dtype: int64
内部标识号    23777
交易次数         2
交易金额       761
Name: 23776, dtype: int64
内部标识号    23778
交易次数         2
交易金额       351
Name: 23777, dtype: int64
内部标识号    23779
交易次数         1
交易金额       521
Name: 23778, dtype: int64
内部标识号    23780
交易次数         3
交易金额       445
Name: 23779, dtype: int64
内部标识号    23781
交易次数         8
交易金额       231
Name: 23780, dtype: int64
内部标识号    23782
交易次数         3
交易金额       491
Name: 23781, dtype: int64
内部标识号    23783
交易次数         5
交易金额      1412
Name: 23782, dtype: int64
内部标识号    23784
交易次数         2
交易金额       418
Name: 23783, dtype: int64
内部标识号    23785
交易次数         6
交易金额      3821
Name: 23784, dtype: int64
内部标识号    23786
交易次数         0
交易金额     58761
Name: 23785, dtype: int64
内部标识号    23787
交易次数         3
交易金额       452
Name: 23786, dtype: int64
内部标识号    23788
交易次数         0
交易金额       230
Name: 23787, dtype: int64
内部标识号    23789
交易次数         5
交易金额      9272
Name: 23788, dtype: int64
内部标识号    23790
交易次数        14
交易金额       254
Name: 23789, dtype: int64
内部标识号    23791
交易次数         3
交易金额       406
Name: 23790, dtype: int64
内部标识号    23792
交易次数         2
交易金额       315
Name: 23791, dtype: int64
内部标识号    23793
交易次数         8
交易金额       141
Name: 23792, dtype: int64
内部标识号    23794
交易次数         0
交易金额       139
Name: 23793, dtype: int64
内部标识号    23795
交易次数         8
交易金额       880
Name: 23794, dtype: int64
内部标识号    23796
交易次数         0
交易金额       211
Name: 23795, dtype: int64
内部标识号    23797
交易次数         1
交易金额     31901
Name: 23796, dtype: int64
内部标识号    23798
交易次数         2
交易金额       372
Name: 23797, dtype: int64
内部标识号    23799
交易次数         0
交易金额     56240
Name: 23798, dtype: int64
内部标识号    23800
交易次数         2
交易金额       922
Name: 23799, dtype: int64
内部标识号    23801
交易次数        23
交易金额       786
Name: 23800, dtype: int64
内部标识号    23802
交易次数        12
交易金额       157
Name: 23801, dtype: int64
内部标识号    23803
交易次数         2
交易金额       477
Name: 23802, dtype: int64
内部标识号    23804
交易次数         1
交易金额       566
Name: 23803, dtype: int64
内部标识号    23805
交易次数         3
交易金额       368
Name: 23804, dtype: int64
内部标识号    23806
交易次数         1
交易金额       235
Name: 23805, dtype: int64
内部标识号    23807
交易次数         9
交易金额       119
Name: 23806, dtype: int64
内部标识号    23808
交易次数        28
交易金额       787
Name: 23807, dtype: int64
内部标识号    23809
交易次数         3
交易金额       427
Name: 23808, dtype: int64
内部标识号    23810
交易次数         6
交易金额       846
Name: 23809, dtype: int64
内部标识号    23811
交易次数         3
交易金额       494
Name: 23810, dtype: int64
内部标识号    23812
交易次数         2
交易金额       495
Name: 23811, dtype: int64
内部标识号    23813
交易次数         0
交易金额       273
Name: 23812, dtype: int64
内部标识号    23814
交易次数         3
交易金额       398
Name: 23813, dtype: int64
内部标识号    23815
交易次数         3
交易金额       326
Name: 23814, dtype: int64
内部标识号    23816
交易次数         2
交易金额       844
Name: 23815, dtype: int64
内部标识号    23817
交易次数         3
交易金额       451
Name: 23816, dtype: int64
内部标识号    23818
交易次数        29
交易金额       772
Name: 23817, dtype: int64
内部标识号    23819
交易次数         4
交易金额       993
Name: 23818, dtype: int64
内部标识号    23820
交易次数         2
交易金额       320
Name: 23819, dtype: int64
内部标识号    23821
交易次数         4
交易金额       904
Name: 23820, dtype: int64
内部标识号    23822
交易次数         2
交易金额       673
Name: 23821, dtype: int64
内部标识号    23823
交易次数         3
交易金额       362
Name: 23822, dtype: int64
内部标识号    23824
交易次数         0
交易金额       284
Name: 23823, dtype: int64
内部标识号    23825
交易次数         2
交易金额       305
Name: 23824, dtype: int64
内部标识号    23826
交易次数         7
交易金额       322
Name: 23825, dtype: int64
内部标识号    23827
交易次数         0
交易金额       148
Name: 23826, dtype: int64
内部标识号    23828
交易次数         2
交易金额       347
Name: 23827, dtype: int64
内部标识号    23829
交易次数         0
交易金额     59290
Name: 23828, dtype: int64
内部标识号    23830
交易次数         2
交易金额       473
Name: 23829, dtype: int64
内部标识号    23831
交易次数         0
交易金额       262
Name: 23830, dtype: int64
内部标识号    23832
交易次数         1
交易金额       548
Name: 23831, dtype: int64
内部标识号    23833
交易次数        11
交易金额       239
Name: 23832, dtype: int64
内部标识号    23834
交易次数         6
交易金额       427
Name: 23833, dtype: int64
内部标识号    23835
交易次数         4
交易金额      2133
Name: 23834, dtype: int64
内部标识号    23836
交易次数         7
交易金额       558
Name: 23835, dtype: int64
内部标识号    23837
交易次数        10
交易金额       297
Name: 23836, dtype: int64
内部标识号    23838
交易次数         3
交易金额       421
Name: 23837, dtype: int64
内部标识号    23839
交易次数         3
交易金额       475
Name: 23838, dtype: int64
内部标识号    23840
交易次数         3
交易金额       434
Name: 23839, dtype: int64
内部标识号    23841
交易次数        11
交易金额       190
Name: 23840, dtype: int64
内部标识号    23842
交易次数         4
交易金额      6931
Name: 23841, dtype: int64
内部标识号    23843
交易次数         0
交易金额     83860
Name: 23842, dtype: int64
内部标识号    23844
交易次数         2
交易金额       515
Name: 23843, dtype: int64
内部标识号    23845
交易次数        30
交易金额       847
Name: 23844, dtype: int64
内部标识号    23846
交易次数         3
交易金额       319
Name: 23845, dtype: int64
内部标识号    23847
交易次数         2
交易金额       817
Name: 23846, dtype: int64
内部标识号    23848
交易次数         2
交易金额       335
Name: 23847, dtype: int64
内部标识号    23849
交易次数        11
交易金额       196
Name: 23848, dtype: int64
内部标识号    23850
交易次数         1
交易金额        40
Name: 23849, dtype: int64
内部标识号    23851
交易次数         2
交易金额       566
Name: 23850, dtype: int64
内部标识号    23852
交易次数         8
交易金额       344
Name: 23851, dtype: int64
内部标识号    23853
交易次数         2
交易金额       392
Name: 23852, dtype: int64
内部标识号    23854
交易次数        17
交易金额       939
Name: 23853, dtype: int64
内部标识号    23855
交易次数         0
交易金额     88116
Name: 23854, dtype: int64
内部标识号    23856
交易次数         8
交易金额       359
Name: 23855, dtype: int64
内部标识号    23857
交易次数         3
交易金额       437
Name: 23856, dtype: int64
内部标识号    23858
交易次数        13
交易金额       273
Name: 23857, dtype: int64
内部标识号    23859
交易次数        18
交易金额       892
Name: 23858, dtype: int64
内部标识号    23860
交易次数         0
交易金额     53779
Name: 23859, dtype: int64
内部标识号    23861
交易次数         6
交易金额      1097
Name: 23860, dtype: int64
内部标识号    23862
交易次数         2
交易金额       572
Name: 23861, dtype: int64
内部标识号    23863
交易次数        15
交易金额       252
Name: 23862, dtype: int64
内部标识号    23864
交易次数         0
交易金额       285
Name: 23863, dtype: int64
内部标识号    23865
交易次数         7
交易金额      8289
Name: 23864, dtype: int64
内部标识号    23866
交易次数         3
交易金额       498
Name: 23865, dtype: int64
内部标识号    23867
交易次数         2
交易金额       867
Name: 23866, dtype: int64
内部标识号    23868
交易次数         5
交易金额       858
Name: 23867, dtype: int64
内部标识号    23869
交易次数         4
交易金额      2905
Name: 23868, dtype: int64
内部标识号    23870
交易次数         7
交易金额       438
Name: 23869, dtype: int64
内部标识号    23871
交易次数         4
交易金额      2229
Name: 23870, dtype: int64
内部标识号    23872
交易次数         3
交易金额      8304
Name: 23871, dtype: int64
内部标识号    23873
交易次数         1
交易金额       129
Name: 23872, dtype: int64
内部标识号    23874
交易次数         6
交易金额       385
Name: 23873, dtype: int64
内部标识号    23875
交易次数        14
交易金额       183
Name: 23874, dtype: int64
内部标识号    23876
交易次数       266
交易金额     28890
Name: 23875, dtype: int64
内部标识号    23877
交易次数         2
交易金额       353
Name: 23876, dtype: int64
内部标识号    23878
交易次数         4
交易金额      6359
Name: 23877, dtype: int64
内部标识号    23879
交易次数         1
交易金额        43
Name: 23878, dtype: int64
内部标识号    23880
交易次数         8
交易金额       323
Name: 23879, dtype: int64
内部标识号    23881
交易次数         3
交易金额       372
Name: 23880, dtype: int64
内部标识号    23882
交易次数         2
交易金额       451
Name: 23881, dtype: int64
内部标识号    23883
交易次数         0
交易金额       216
Name: 23882, dtype: int64
内部标识号    23884
交易次数         2
交易金额       458
Name: 23883, dtype: int64
内部标识号    23885
交易次数         3
交易金额       413
Name: 23884, dtype: int64
内部标识号    23886
交易次数        10
交易金额       107
Name: 23885, dtype: int64
内部标识号    23887
交易次数        26
交易金额       533
Name: 23886, dtype: int64
内部标识号    23888
交易次数         1
交易金额       671
Name: 23887, dtype: int64
内部标识号    23889
交易次数       263
交易金额     83568
Name: 23888, dtype: int64
内部标识号    23890
交易次数         2
交易金额       779
Name: 23889, dtype: int64
内部标识号    23891
交易次数        25
交易金额       589
Name: 23890, dtype: int64
内部标识号    23892
交易次数         4
交易金额       779
Name: 23891, dtype: int64
内部标识号    23893
交易次数         1
交易金额       192
Name: 23892, dtype: int64
内部标识号    23894
交易次数         7
交易金额       624
Name: 23893, dtype: int64
内部标识号    23895
交易次数         4
交易金额      4935
Name: 23894, dtype: int64
内部标识号    23896
交易次数         2
交易金额       435
Name: 23895, dtype: int64
内部标识号    23897
交易次数         4
交易金额      8652
Name: 23896, dtype: int64
内部标识号    23898
交易次数         3
交易金额      2627
Name: 23897, dtype: int64
内部标识号    23899
交易次数         3
交易金额      6310
Name: 23898, dtype: int64
内部标识号    23900
交易次数         5
交易金额      8455
Name: 23899, dtype: int64
内部标识号    23901
交易次数         8
交易金额       239
Name: 23900, dtype: int64
内部标识号    23902
交易次数         1
交易金额       926
Name: 23901, dtype: int64
内部标识号    23903
交易次数         3
交易金额       416
Name: 23902, dtype: int64
内部标识号    23904
交易次数         4
交易金额       367
Name: 23903, dtype: int64
内部标识号    23905
交易次数         4
交易金额      5393
Name: 23904, dtype: int64
内部标识号    23906
交易次数         8
交易金额       261
Name: 23905, dtype: int64
内部标识号    23907
交易次数         8
交易金额       104
Name: 23906, dtype: int64
内部标识号    23908
交易次数         3
交易金额       491
Name: 23907, dtype: int64
内部标识号    23909
交易次数         1
交易金额       221
Name: 23908, dtype: int64
内部标识号    23910
交易次数         2
交易金额       584
Name: 23909, dtype: int64
内部标识号    23911
交易次数         1
交易金额       269
Name: 23910, dtype: int64
内部标识号    23912
交易次数         2
交易金额       305
Name: 23911, dtype: int64
内部标识号    23913
交易次数        15
交易金额       793
Name: 23912, dtype: int64
内部标识号    23914
交易次数         3
交易金额       344
Name: 23913, dtype: int64
内部标识号    23915
交易次数         0
交易金额       138
Name: 23914, dtype: int64
内部标识号    23916
交易次数         1
交易金额       795
Name: 23915, dtype: int64
内部标识号    23917
交易次数         8
交易金额       123
Name: 23916, dtype: int64
内部标识号    23918
交易次数         2
交易金额       382
Name: 23917, dtype: int64
内部标识号    23919
交易次数         1
交易金额     83062
Name: 23918, dtype: int64
内部标识号    23920
交易次数         1
交易金额       104
Name: 23919, dtype: int64
内部标识号    23921
交易次数        11
交易金额       155
Name: 23920, dtype: int64
内部标识号    23922
交易次数         8
交易金额      4746
Name: 23921, dtype: int64
内部标识号    23923
交易次数         0
交易金额     48609
Name: 23922, dtype: int64
内部标识号    23924
交易次数         2
交易金额       355
Name: 23923, dtype: int64
内部标识号    23925
交易次数         3
交易金额       378
Name: 23924, dtype: int64
内部标识号    23926
交易次数         2
交易金额       851
Name: 23925, dtype: int64
内部标识号    23927
交易次数         1
交易金额       906
Name: 23926, dtype: int64
内部标识号    23928
交易次数         7
交易金额      6783
Name: 23927, dtype: int64
内部标识号    23929
交易次数         3
交易金额       334
Name: 23928, dtype: int64
内部标识号    23930
交易次数         2
交易金额       369
Name: 23929, dtype: int64
内部标识号    23931
交易次数         6
交易金额      5153
Name: 23930, dtype: int64
内部标识号    23932
交易次数         7
交易金额       415
Name: 23931, dtype: int64
内部标识号    23933
交易次数         8
交易金额       144
Name: 23932, dtype: int64
内部标识号    23934
交易次数        11
交易金额       129
Name: 23933, dtype: int64
内部标识号    23935
交易次数         3
交易金额       342
Name: 23934, dtype: int64
内部标识号    23936
交易次数       239
交易金额     16580
Name: 23935, dtype: int64
内部标识号    23937
交易次数         8
交易金额       228
Name: 23936, dtype: int64
内部标识号    23938
交易次数        14
交易金额       175
Name: 23937, dtype: int64
内部标识号    23939
交易次数        15
交易金额       526
Name: 23938, dtype: int64
内部标识号    23940
交易次数         7
交易金额       434
Name: 23939, dtype: int64
内部标识号    23941
交易次数         3
交易金额       358
Name: 23940, dtype: int64
内部标识号    23942
交易次数         1
交易金额       647
Name: 23941, dtype: int64
内部标识号    23943
交易次数         8
交易金额      2722
Name: 23942, dtype: int64
内部标识号    23944
交易次数         3
交易金额      2784
Name: 23943, dtype: int64
内部标识号    23945
交易次数         2
交易金额       415
Name: 23944, dtype: int64
内部标识号    23946
交易次数         5
交易金额       659
Name: 23945, dtype: int64
内部标识号    23947
交易次数         1
交易金额       134
Name: 23946, dtype: int64
内部标识号    23948
交易次数         2
交易金额       434
Name: 23947, dtype: int64
内部标识号    23949
交易次数         4
交易金额      7103
Name: 23948, dtype: int64
内部标识号    23950
交易次数         1
交易金额       827
Name: 23949, dtype: int64
内部标识号    23951
交易次数         2
交易金额       393
Name: 23950, dtype: int64
内部标识号    23952
交易次数         0
交易金额     95767
Name: 23951, dtype: int64
内部标识号    23953
交易次数         3
交易金额       341
Name: 23952, dtype: int64
内部标识号    23954
交易次数         2
交易金额       460
Name: 23953, dtype: int64
内部标识号    23955
交易次数         3
交易金额       451
Name: 23954, dtype: int64
内部标识号    23956
交易次数         0
交易金额     90433
Name: 23955, dtype: int64
内部标识号    23957
交易次数         3
交易金额       463
Name: 23956, dtype: int64
内部标识号    23958
交易次数         5
交易金额       302
Name: 23957, dtype: int64
内部标识号    23959
交易次数         0
交易金额     93812
Name: 23958, dtype: int64
内部标识号    23960
交易次数         2
交易金额       585
Name: 23959, dtype: int64
内部标识号    23961
交易次数         1
交易金额       227
Name: 23960, dtype: int64
内部标识号    23962
交易次数        10
交易金额       247
Name: 23961, dtype: int64
内部标识号    23963
交易次数         3
交易金额       379
Name: 23962, dtype: int64
内部标识号    23964
交易次数         3
交易金额       375
Name: 23963, dtype: int64
内部标识号    23965
交易次数         0
交易金额       281
Name: 23964, dtype: int64
内部标识号    23966
交易次数         8
交易金额      7181
Name: 23965, dtype: int64
内部标识号    23967
交易次数         1
交易金额       727
Name: 23966, dtype: int64
内部标识号    23968
交易次数         3
交易金额       367
Name: 23967, dtype: int64
内部标识号    23969
交易次数        11
交易金额       278
Name: 23968, dtype: int64
内部标识号    23970
交易次数         8
交易金额       148
Name: 23969, dtype: int64
内部标识号    23971
交易次数         0
交易金额       263
Name: 23970, dtype: int64
内部标识号    23972
交易次数         1
交易金额       279
Name: 23971, dtype: int64
内部标识号    23973
交易次数         0
交易金额     50375
Name: 23972, dtype: int64
内部标识号    23974
交易次数        26
交易金额       703
Name: 23973, dtype: int64
内部标识号    23975
交易次数         6
交易金额       488
Name: 23974, dtype: int64
内部标识号    23976
交易次数         8
交易金额      3138
Name: 23975, dtype: int64
内部标识号    23977
交易次数        13
交易金额       175
Name: 23976, dtype: int64
内部标识号    23978
交易次数         3
交易金额       425
Name: 23977, dtype: int64
内部标识号    23979
交易次数        13
交易金额       110
Name: 23978, dtype: int64
内部标识号    23980
交易次数         2
交易金额       699
Name: 23979, dtype: int64
内部标识号    23981
交易次数         9
交易金额       102
Name: 23980, dtype: int64
内部标识号    23982
交易次数         0
交易金额       163
Name: 23981, dtype: int64
内部标识号    23983
交易次数         7
交易金额       926
Name: 23982, dtype: int64
内部标识号    23984
交易次数         3
交易金额       446
Name: 23983, dtype: int64
内部标识号    23985
交易次数        29
交易金额       984
Name: 23984, dtype: int64
内部标识号    23986
交易次数        11
交易金额       121
Name: 23985, dtype: int64
内部标识号    23987
交易次数         5
交易金额      9894
Name: 23986, dtype: int64
内部标识号    23988
交易次数         8
交易金额       160
Name: 23987, dtype: int64
内部标识号    23989
交易次数        19
交易金额       878
Name: 23988, dtype: int64
内部标识号    23990
交易次数         1
交易金额       121
Name: 23989, dtype: int64
内部标识号    23991
交易次数        10
交易金额       296
Name: 23990, dtype: int64
内部标识号    23992
交易次数         7
交易金额       386
Name: 23991, dtype: int64
内部标识号    23993
交易次数         2
交易金额       306
Name: 23992, dtype: int64
内部标识号    23994
交易次数         1
交易金额       790
Name: 23993, dtype: int64
内部标识号    23995
交易次数         2
交易金额       617
Name: 23994, dtype: int64
内部标识号    23996
交易次数         2
交易金额        83
Name: 23995, dtype: int64
内部标识号    23997
交易次数         2
交易金额       406
Name: 23996, dtype: int64
内部标识号    23998
交易次数         3
交易金额       351
Name: 23997, dtype: int64
内部标识号    23999
交易次数         1
交易金额       221
Name: 23998, dtype: int64
内部标识号    24000
交易次数         0
交易金额       207
Name: 23999, dtype: int64
内部标识号    24001
交易次数         7
交易金额      2797
Name: 24000, dtype: int64
内部标识号    24002
交易次数         1
交易金额       863
Name: 24001, dtype: int64
内部标识号    24003
交易次数         6
交易金额      7869
Name: 24002, dtype: int64
内部标识号    24004
交易次数         0
交易金额     73170
Name: 24003, dtype: int64
内部标识号    24005
交易次数         2
交易金额       340
Name: 24004, dtype: int64
内部标识号    24006
交易次数         3
交易金额       452
Name: 24005, dtype: int64
内部标识号    24007
交易次数        11
交易金额       152
Name: 24006, dtype: int64
内部标识号    24008
交易次数         8
交易金额       593
Name: 24007, dtype: int64
内部标识号    24009
交易次数         1
交易金额       725
Name: 24008, dtype: int64
内部标识号    24010
交易次数        16
交易金额       545
Name: 24009, dtype: int64
内部标识号    24011
交易次数         4
交易金额       900
Name: 24010, dtype: int64
内部标识号    24012
交易次数         1
交易金额       845
Name: 24011, dtype: int64
内部标识号    24013
交易次数         3
交易金额       350
Name: 24012, dtype: int64
内部标识号    24014
交易次数         2
交易金额       433
Name: 24013, dtype: int64
内部标识号    24015
交易次数         2
交易金额       701
Name: 24014, dtype: int64
内部标识号    24016
交易次数         4
交易金额      6774
Name: 24015, dtype: int64
内部标识号    24017
交易次数         2
交易金额       381
Name: 24016, dtype: int64
内部标识号    24018
交易次数         1
交易金额       560
Name: 24017, dtype: int64
内部标识号    24019
交易次数         3
交易金额       442
Name: 24018, dtype: int64
内部标识号    24020
交易次数         8
交易金额       355
Name: 24019, dtype: int64
内部标识号    24021
交易次数         2
交易金额       500
Name: 24020, dtype: int64
内部标识号    24022
交易次数        13
交易金额       159
Name: 24021, dtype: int64
内部标识号    24023
交易次数        12
交易金额       128
Name: 24022, dtype: int64
内部标识号    24024
交易次数         1
交易金额       875
Name: 24023, dtype: int64
内部标识号    24025
交易次数        11
交易金额       250
Name: 24024, dtype: int64
内部标识号    24026
交易次数         0
交易金额       195
Name: 24025, dtype: int64
内部标识号    24027
交易次数         2
交易金额       350
Name: 24026, dtype: int64
内部标识号    24028

Name: 24238, dtype: int64
内部标识号    24240
交易次数         2
交易金额       316
Name: 24239, dtype: int64
内部标识号    24241
交易次数         1
交易金额       586
Name: 24240, dtype: int64
内部标识号    24242
交易次数         1
交易金额       793
Name: 24241, dtype: int64
内部标识号    24243
交易次数         2
交易金额       816
Name: 24242, dtype: int64
内部标识号    24244
交易次数        14
交易金额       106
Name: 24243, dtype: int64
内部标识号    24245
交易次数        19
交易金额       608
Name: 24244, dtype: int64
内部标识号    24246
交易次数       186
交易金额     98281
Name: 24245, dtype: int64
内部标识号    24247
交易次数         2
交易金额       756
Name: 24246, dtype: int64
内部标识号    24248
交易次数        26
交易金额       732
Name: 24247, dtype: int64
内部标识号    24249
交易次数         1
交易金额        67
Name: 24248, dtype: int64
内部标识号    24250
交易次数         8
交易金额       471
Name: 24249, dtype: int64
内部标识号    24251
交易次数         8
交易金额       265
Name: 24250, dtype: int64
内部标识号    24252
交易次数         3
交易金额       338
Name: 24251, dtype: int64
内部标识号    24253
交易次数         8
交易金额       438
Name: 24252, dtype: int64
内部标识号    24254
交易次数         2
交易金额       447
Name: 24253, dtype: int64
内部标识号    24255
交易次数         1
交易金额       282
Name: 24254, dtype: int64
内部标识号    24256
交易次数         0
交易金额       196
Name: 24255, dtype: int64
内部标识号    24257
交易次数         2
交易金额       301
Name: 24256, dtype: int64
内部标识号    24258
交易次数         8
交易金额      2680
Name: 24257, dtype: int64
内部标识号    24259
交易次数         1
交易金额        69
Name: 24258, dtype: int64
内部标识号    24260
交易次数         8
交易金额      8014
Name: 24259, dtype: int64
内部标识号    24261
交易次数         8
交易金额      8854
Name: 24260, dtype: int64
内部标识号    24262
交易次数         3
交易金额       332
Name: 24261, dtype: int64
内部标识号    24263
交易次数        13
交易金额       184
Name: 24262, dtype: int64
内部标识号    24264
交易次数        10
交易金额       113
Name: 24263, dtype: int64
内部标识号    24265
交易次数         3
交易金额      5134
Name: 24264, dtype: int64
内部标识号    24266
交易次数        29
交易金额       555
Name: 24265, dtype: int64
内部标识号    24267
交易次数        10
交易金额       138
Name: 24266, dtype: int64
内部标识号    24268
交易次数         0
交易金额       213
Name: 24267, dtype: int64
内部标识号    24269
交易次数         2
交易金额       305
Name: 24268, dtype: int64
内部标识号    24270
交易次数         3
交易金额       493
Name: 24269, dtype: int64
内部标识号    24271
交易次数         3
交易金额       422
Name: 24270, dtype: int64
内部标识号    24272
交易次数         3
交易金额       328
Name: 24271, dtype: int64
内部标识号    24273
交易次数         1
交易金额       531
Name: 24272, dtype: int64
内部标识号    24274
交易次数         3
交易金额       376
Name: 24273, dtype: int64
内部标识号    24275
交易次数         1
交易金额        61
Name: 24274, dtype: int64
内部标识号    24276
交易次数         2
交易金额       595
Name: 24275, dtype: int64
内部标识号    24277
交易次数         0
交易金额       152
Name: 24276, dtype: int64
内部标识号    24278
交易次数         1
交易金额       191
Name: 24277, dtype: int64
内部标识号    24279
交易次数         8
交易金额       121
Name: 24278, dtype: int64
内部标识号    24280
交易次数         6
交易金额      4687
Name: 24279, dtype: int64
内部标识号    24281
交易次数         3
交易金额       477
Name: 24280, dtype: int64
内部标识号    24282
交易次数         3
交易金额       986
Name: 24281, dtype: int64
内部标识号    24283
交易次数         0
交易金额       108
Name: 24282, dtype: int64
内部标识号    24284
交易次数         1
交易金额       159
Name: 24283, dtype: int64
内部标识号    24285
交易次数         7
交易金额       846
Name: 24284, dtype: int64
内部标识号    24286
交易次数         7
交易金额      8468
Name: 24285, dtype: int64
内部标识号    24287
交易次数         2
交易金额       865
Name: 24286, dtype: int64
内部标识号    24288
交易次数         3
交易金额       336
Name: 24287, dtype: int64
内部标识号    24289
交易次数        15
交易金额       260
Name: 24288, dtype: int64
内部标识号    24290
交易次数        26
交易金额       805
Name: 24289, dtype: int64
内部标识号    24291
交易次数         0
交易金额     91949
Name: 24290, dtype: int64
内部标识号    24292
交易次数         1
交易金额       203
Name: 24291, dtype: int64
内部标识号    24293
交易次数        10
交易金额       253
Name: 24292, dtype: int64
内部标识号    24294
交易次数         2
交易金额       405
Name: 24293, dtype: int64
内部标识号    24295
交易次数         0
交易金额       182
Name: 24294, dtype: int64
内部标识号    24296
交易次数         3
交易金额       456
Name: 24295, dtype: int64
内部标识号    24297
交易次数         3
交易金额       385
Name: 24296, dtype: int64
内部标识号    24298
交易次数         7
交易金额       475
Name: 24297, dtype: int64
内部标识号    24299
交易次数         4
交易金额       843
Name: 24298, dtype: int64
内部标识号    24300
交易次数         1
交易金额       222
Name: 24299, dtype: int64
内部标识号    24301
交易次数         3
交易金额       475
Name: 24300, dtype: int64
内部标识号    24302
交易次数         0
交易金额     51917
Name: 24301, dtype: int64
内部标识号    24303
交易次数         3
交易金额       351
Name: 24302, dtype: int64
内部标识号    24304
交易次数        29
交易金额       841
Name: 24303, dtype: int64
内部标识号    24305
交易次数         4
交易金额      2395
Name: 24304, dtype: int64
内部标识号    24306
交易次数         2
交易金额       308
Name: 24305, dtype: int64
内部标识号    24307
交易次数         3
交易金额       472
Name: 24306, dtype: int64
内部标识号    24308
交易次数         7
交易金额      6908
Name: 24307, dtype: int64
内部标识号    24309
交易次数         3
交易金额       425
Name: 24308, dtype: int64
内部标识号    24310
交易次数         2
交易金额       367
Name: 24309, dtype: int64
内部标识号    24311
交易次数         0
交易金额       273
Name: 24310, dtype: int64
内部标识号    24312
交易次数         8
交易金额       396
Name: 24311, dtype: int64
内部标识号    24313
交易次数         3
交易金额       399
Name: 24312, dtype: int64
内部标识号    24314
交易次数         3
交易金额       493
Name: 24313, dtype: int64
内部标识号    24315
交易次数         3
交易金额      1579
Name: 24314, dtype: int64
内部标识号    24316
交易次数         3
交易金额       457
Name: 24315, dtype: int64
内部标识号    24317
交易次数         2
交易金额       394
Name: 24316, dtype: int64
内部标识号    24318
交易次数         2
交易金额       398
Name: 24317, dtype: int64
内部标识号    24319
交易次数         1
交易金额       735
Name: 24318, dtype: int64
内部标识号    24320
交易次数         3
交易金额       362
Name: 24319, dtype: int64
内部标识号    24321
交易次数         8
交易金额      9947
Name: 24320, dtype: int64
内部标识号    24322
交易次数         0
交易金额       201
Name: 24321, dtype: int64
内部标识号    24323
交易次数         2
交易金额       859
Name: 24322, dtype: int64
内部标识号    24324
交易次数         3
交易金额       348
Name: 24323, dtype: int64
内部标识号    24325
交易次数        10
交易金额       219
Name: 24324, dtype: int64
内部标识号    24326
交易次数         0
交易金额       118
Name: 24325, dtype: int64
内部标识号    24327
交易次数         2
交易金额       827
Name: 24326, dtype: int64
内部标识号    24328
交易次数         1
交易金额       193
Name: 24327, dtype: int64
内部标识号    24329
交易次数        23
交易金额       820
Name: 24328, dtype: int64
内部标识号    24330
交易次数        31
交易金额     30912
Name: 24329, dtype: int64
内部标识号    24331
交易次数         1
交易金额     91012
Name: 24330, dtype: int64
内部标识号    24332
交易次数         3
交易金额       360
Name: 24331, dtype: int64
内部标识号    24333
交易次数         6
交易金额      1125
Name: 24332, dtype: int64
内部标识号    24334
交易次数         2
交易金额     92937
Name: 24333, dtype: int64
内部标识号    24335
交易次数         1
交易金额       110
Name: 24334, dtype: int64
内部标识号    24336
交易次数         2
交易金额        95
Name: 24335, dtype: int64
内部标识号    24337
交易次数         1
交易金额       599
Name: 24336, dtype: int64
内部标识号    24338
交易次数        12
交易金额       145
Name: 24337, dtype: int64
内部标识号    24339
交易次数         3
交易金额       400
Name: 24338, dtype: int64
内部标识号    24340
交易次数        13
交易金额       234
Name: 24339, dtype: int64
内部标识号    24341
交易次数        12
交易金额       246
Name: 24340, dtype: int64
内部标识号    24342
交易次数         1
交易金额       560
Name: 24341, dtype: int64
内部标识号    24343
交易次数         8
交易金额       128
Name: 24342, dtype: int64
内部标识号    24344
交易次数         0
交易金额     89018
Name: 24343, dtype: int64
内部标识号    24345
交易次数         3
交易金额      6567
Name: 24344, dtype: int64
内部标识号    24346
交易次数         7
交易金额       525
Name: 24345, dtype: int64
内部标识号    24347
交易次数         2
交易金额       590
Name: 24346, dtype: int64
内部标识号    24348
交易次数         1
交易金额       642
Name: 24347, dtype: int64
内部标识号    24349
交易次数         2
交易金额       453
Name: 24348, dtype: int64
内部标识号    24350
交易次数         7
交易金额       739
Name: 24349, dtype: int64
内部标识号    24351
交易次数         3
交易金额       337
Name: 24350, dtype: int64
内部标识号    24352
交易次数         8
交易金额      2034
Name: 24351, dtype: int64
内部标识号    24353
交易次数         3
交易金额       368
Name: 24352, dtype: int64
内部标识号    24354
交易次数        25
交易金额       997
Name: 24353, dtype: int64
内部标识号    24355
交易次数         3
交易金额       422
Name: 24354, dtype: int64
内部标识号    24356
交易次数         0
交易金额       294
Name: 24355, dtype: int64
内部标识号    24357
交易次数         3
交易金额       473
Name: 24356, dtype: int64
内部标识号    24358
交易次数        12
交易金额       104
Name: 24357, dtype: int64
内部标识号    24359
交易次数         3
交易金额       430
Name: 24358, dtype: int64
内部标识号    24360
交易次数         3
交易金额       408
Name: 24359, dtype: int64
内部标识号    24361
交易次数         1
交易金额       926
Name: 24360, dtype: int64
内部标识号    24362
交易次数        12
交易金额       250
Name: 24361, dtype: int64
内部标识号    24363
交易次数         2
交易金额       768
Name: 24362, dtype: int64
内部标识号    24364
交易次数         6
交易金额       376
Name: 24363, dtype: int64
内部标识号    24365
交易次数         9
交易金额       295
Name: 24364, dtype: int64
内部标识号    24366
交易次数         3
交易金额       393
Name: 24365, dtype: int64
内部标识号    24367
交易次数        14
交易金额       283
Name: 24366, dtype: int64
内部标识号    24368
交易次数         3
交易金额       408
Name: 24367, dtype: int64
内部标识号    24369
交易次数         1
交易金额       160
Name: 24368, dtype: int64
内部标识号    24370
交易次数         3
交易金额      3024
Name: 24369, dtype: int64
内部标识号    24371
交易次数        16
交易金额       721
Name: 24370, dtype: int64
内部标识号    24372
交易次数        29
交易金额       988
Name: 24371, dtype: int64
内部标识号    24373
交易次数         2
交易金额       361
Name: 24372, dtype: int64
内部标识号    24374
交易次数         1
交易金额       182
Name: 24373, dtype: int64
内部标识号    24375
交易次数         8
交易金额       114
Name: 24374, dtype: int64
内部标识号    24376
交易次数         2
交易金额       694
Name: 24375, dtype: int64
内部标识号    24377
交易次数         2
交易金额       500
Name: 24376, dtype: int64
内部标识号    24378
交易次数         7
交易金额      9323
Name: 24377, dtype: int64
内部标识号    24379
交易次数         2
交易金额       387
Name: 24378, dtype: int64
内部标识号    24380
交易次数         0
交易金额     10079
Name: 24379, dtype: int64
内部标识号    24381
交易次数         1
交易金额     79214
Name: 24380, dtype: int64
内部标识号    24382
交易次数         2
交易金额       975
Name: 24381, dtype: int64
内部标识号    24383
交易次数         4
交易金额      2151
Name: 24382, dtype: int64
内部标识号    24384
交易次数         0
交易金额       289
Name: 24383, dtype: int64
内部标识号    24385
交易次数         1
交易金额       716
Name: 24384, dtype: int64
内部标识号    24386
交易次数         1
交易金额       162
Name: 24385, dtype: int64
内部标识号    24387
交易次数         1
交易金额       726
Name: 24386, dtype: int64
内部标识号    24388
交易次数        15
交易金额       236
Name: 24387, dtype: int64
内部标识号    24389
交易次数        11
交易金额       293
Name: 24388, dtype: int64
内部标识号    24390
交易次数         2
交易金额       368
Name: 24389, dtype: int64
内部标识号    24391
交易次数         3
交易金额      8028
Name: 24390, dtype: int64
内部标识号    24392
交易次数         4
交易金额      1098
Name: 24391, dtype: int64
内部标识号    24393
交易次数         2
交易金额       807
Name: 24392, dtype: int64
内部标识号    24394
交易次数         2
交易金额       752
Name: 24393, dtype: int64
内部标识号    24395
交易次数         2
交易金额       400
Name: 24394, dtype: int64
内部标识号    24396
交易次数         5
交易金额       307
Name: 24395, dtype: int64
内部标识号    24397
交易次数         0
交易金额       117
Name: 24396, dtype: int64
内部标识号    24398
交易次数         1
交易金额       137
Name: 24397, dtype: int64
内部标识号    24399
交易次数         1
交易金额       180
Name: 24398, dtype: int64
内部标识号    24400
交易次数        14
交易金额       276
Name: 24399, dtype: int64
内部标识号    24401
交易次数         1
交易金额       143
Name: 24400, dtype: int64
内部标识号    24402
交易次数         1
交易金额       158
Name: 24401, dtype: int64
内部标识号    24403
交易次数        14
交易金额       281
Name: 24402, dtype: int64
内部标识号    24404
交易次数         2
交易金额        95
Name: 24403, dtype: int64
内部标识号    24405
交易次数         1
交易金额       544
Name: 24404, dtype: int64
内部标识号    24406
交易次数         0
交易金额     47762
Name: 24405, dtype: int64
内部标识号    24407
交易次数         3
交易金额       397
Name: 24406, dtype: int64
内部标识号    24408
交易次数         2
交易金额       452
Name: 24407, dtype: int64
内部标识号    24409
交易次数         8
交易金额       908
Name: 24408, dtype: int64
内部标识号    24410
交易次数       227
交易金额     15384
Name: 24409, dtype: int64
内部标识号    24411
交易次数         1
交易金额       219
Name: 24410, dtype: int64
内部标识号    24412
交易次数         3
交易金额       455
Name: 24411, dtype: int64
内部标识号    24413
交易次数         2
交易金额       484
Name: 24412, dtype: int64
内部标识号    24414
交易次数         9
交易金额       236
Name: 24413, dtype: int64
内部标识号    24415
交易次数         0
交易金额       268
Name: 24414, dtype: int64
内部标识号    24416
交易次数         3
交易金额       344
Name: 24415, dtype: int64
内部标识号    24417
交易次数        96
交易金额     17418
Name: 24416, dtype: int64
内部标识号    24418
交易次数         0
交易金额       100
Name: 24417, dtype: int64
内部标识号    24419
交易次数        12
交易金额       266
Name: 24418, dtype: int64
内部标识号    24420
交易次数         3
交易金额       443
Name: 24419, dtype: int64
内部标识号    24421
交易次数        23
交易金额       900
Name: 24420, dtype: int64
内部标识号    24422
交易次数         1
交易金额       660
Name: 24421, dtype: int64
内部标识号    24423
交易次数         3
交易金额       936
Name: 24422, dtype: int64
内部标识号    24424
交易次数         6
交易金额      8459
Name: 24423, dtype: int64
内部标识号    24425
交易次数         0
交易金额       299
Name: 24424, dtype: int64
内部标识号    24426
交易次数         3
交易金额       377
Name: 24425, dtype: int64
内部标识号    24427
交易次数         2
交易金额       393
Name: 24426, dtype: int64
内部标识号    24428
交易次数         8
交易金额       497
Name: 24427, dtype: int64
内部标识号    24429
交易次数         0
交易金额     78939
Name: 24428, dtype: int64
内部标识号    24430
交易次数         3
交易金额       300
Name: 24429, dtype: int64
内部标识号    24431
交易次数         5
交易金额      2231
Name: 24430, dtype: int64
内部标识号    24432
交易次数        23
交易金额       766
Name: 24431, dtype: int64
内部标识号    24433
交易次数         6
交易金额       327
Name: 24432, dtype: int64
内部标识号    24434
交易次数         0
交易金额       172
Name: 24433, dtype: int64
内部标识号    24435
交易次数         0
交易金额       148
Name: 24434, dtype: int64
内部标识号    24436
交易次数         0
交易金额     36742
Name: 24435, dtype: int64
内部标识号    24437
交易次数         7
交易金额      2057
Name: 24436, dtype: int64
内部标识号    24438
交易次数         8
交易金额      1334
Name: 24437, dtype: int64
内部标识号    24439
交易次数         7
交易金额      4559
Name: 24438, dtype: int64
内部标识号    24440
交易次数        14
交易金额       285
Name: 24439, dtype: int64
内部标识号    24441
交易次数         0
交易金额       142
Name: 24440, dtype: int64
内部标识号    24442
交易次数         9
交易金额       160
Name: 24441, dtype: int64
内部标识号    24443
交易次数         3
交易金额      3710
Name: 24442, dtype: int64
内部标识号    24444
交易次数         0
交易金额       240
Name: 24443, dtype: int64
内部标识号    24445
交易次数        12
交易金额       145
Name: 24444, dtype: int64
内部标识号    24446
交易次数         8
交易金额      1702
Name: 24445, dtype: int64
内部标识号    24447
交易次数         0
交易金额       186
Name: 24446, dtype: int64
内部标识号    24448
交易次数         5
交易金额      1834
Name: 24447, dtype: int64
内部标识号    24449
交易次数         0
交易金额     84788
Name: 24448, dtype: int64
内部标识号    24450
交易次数         1
交易金额       167
Name: 24449, dtype: int64
内部标识号    24451
交易次数         3
交易金额       378
Name: 24450, dtype: int64
内部标识号    24452
交易次数         0
交易金额     68054
Name: 24451, dtype: int64
内部标识号    24453
交易次数         3
交易金额       472
Name: 24452, dtype: int64
内部标识号    24454
交易次数         2
交易金额       347
Name: 24453, dtype: int64
内部标识号    24455
交易次数       116
交易金额     93222
Name: 24454, dtype: int64
内部标识号    24456
交易次数         0
交易金额       231
Name: 24455, dtype: int64
内部标识号    24457
交易次数         2
交易金额        13
Name: 24456, dtype: int64
内部标识号    24458
交易次数         2
交易金额         3
Name: 24457, dtype: int64
内部标识号    24459
交易次数         1
交易金额       114
Name: 24458, dtype: int64
内部标识号    24460
交易次数        11
交易金额       201
Name: 24459, dtype: int64
内部标识号    24461
交易次数         0
交易金额       177
Name: 24460, dtype: int64
内部标识号    24462
交易次数        13
交易金额       134
Name: 24461, dtype: int64
内部标识号    24463
交易次数         8
交易金额       289
Name: 24462, dtype: int64
内部标识号    24464
交易次数         9
交易金额       183
Name: 24463, dtype: int64
内部标识号    24465
交易次数         1
交易金额       144
Name: 24464, dtype: int64
内部标识号    24466
交易次数         8
交易金额       228
Name: 24465, dtype: int64
内部标识号    24467
交易次数         1
交易金额       710
Name: 24466, dtype: int64
内部标识号    24468
交易次数         1
交易金额       216
Name: 24467, dtype: int64
内部标识号    24469
交易次数         2
交易金额       317
Name: 24468, dtype: int64
内部标识号    24470
交易次数         3
交易金额       418
Name: 24469, dtype: int64
内部标识号    24471
交易次数         2
交易金额       681
Name: 24470, dtype: int64
内部标识号    24472
交易次数         9
交易金额       295
Name: 24471, dtype: int64
内部标识号    24473
交易次数         9
交易金额       280
Name: 24472, dtype: int64
内部标识号    24474
交易次数        15
交易金额       290
Name: 24473, dtype: int64
内部标识号    24475
交易次数         6
交易金额       369
Name: 24474, dtype: int64
内部标识号    24476
交易次数        29
交易金额       837
Name: 24475, dtype: int64
内部标识号    24477
交易次数         0
交易金额     35330
Name: 24476, dtype: int64
内部标识号    24478
交易次数         4
交易金额      9947
Name: 24477, dtype: int64
内部标识号    24479
交易次数         0
交易金额       123
Name: 24478, dtype: int64
内部标识号    24480
交易次数         3
交易金额       301
Name: 24479, dtype: int64
内部标识号    24481
交易次数         2
交易金额       418
Name: 24480, dtype: int64
内部标识号    24482
交易次数         2
交易金额       374
Name: 24481, dtype: int64
内部标识号    24483
交易次数         2
交易金额       409
Name: 24482, dtype: int64
内部标识号    24484
交易次数         9
交易金额       296
Name: 24483, dtype: int64
内部标识号    24485
交易次数         3
交易金额       378
Name: 24484, dtype: int64
内部标识号    24486
交易次数        13
交易金额       136
Name: 24485, dtype: int64
内部标识号    24487
交易次数         2
交易金额       584
Name: 24486, dtype: int64
内部标识号    24488
交易次数         3
交易金额       426
Name: 24487, dtype: int64
内部标识号    24489
交易次数       133
交易金额     51964
Name: 24488, dtype: int64
内部标识号    24490
交易次数         2
交易金额       330
Name: 24489, dtype: int64
内部标识号    24491
交易次数         2
交易金额        94
Name: 24490, dtype: int64
内部标识号    24492
交易次数        25
交易金额       837
Name: 24491, dtype: int64
内部标识号    24493
交易次数         2
交易金额       443
Name: 24492, dtype: int64
内部标识号    24494
交易次数         7
交易金额      6575
Name: 24493, dtype: int64
内部标识号    24495
交易次数         3
交易金额       404
Name: 24494, dtype: int64
内部标识号    24496
交易次数         2
交易金额       420
Name: 24495, dtype: int64
内部标识号    24497
交易次数         1
交易金额       114
Name: 24496, dtype: int64
内部标识号    24498
交易次数         2
交易金额       470
Name: 24497, dtype: int64
内部标识号    24499
交易次数         2
交易金额       426
Name: 24498, dtype: int64
内部标识号    24500
交易次数         3
交易金额      7770
Name: 24499, dtype: int64
内部标识号    24501
交易次数        11
交易金额       109
Name: 24500, dtype: int64
内部标识号    24502
交易次数         2
交易金额     25761
Name: 24501, dtype: int64
内部标识号    24503
交易次数         3
交易金额      9277
Name: 24502, dtype: int64
内部标识号    24504
交易次数         2
交易金额       668
Name: 24503, dtype: int64
内部标识号    24505
交易次数         5
交易金额       403
Name: 24504, dtype: int64
内部标识号    24506
交易次数        10
交易金额       253
Name: 24505, dtype: int64
内部标识号    24507
交易次数         0
交易金额     30335
Name: 24506, dtype: int64
内部标识号    24508
交易次数         1
交易金额       629
Name: 24507, dtype: int64
内部标识号    24509
交易次数         1
交易金额     62261
Name: 24508, dtype: int64
内部标识号    24510
交易次数         1
交易金额       794
Name: 24509, dtype: int64
内部标识号    24511
交易次数         1
交易金额       226
Name: 24510, dtype: int64
内部标识号    24512
交易次数         0
交易金额       151
Name: 24511, dtype: int64
内部标识号    24513
交易次数         0
交易金额       279
Name: 24512, dtype: int64
内部标识号    24514
交易次数         1
交易金额        20
Name: 24513, dtype: int64
内部标识号    24515
交易次数        15
交易金额       203
Name: 24514, dtype: int64
内部标识号    24516
交易次数         2
交易金额       887
Name: 24515, dtype: int64
内部标识号    24517
交易次数         7
交易金额       808
Name: 24516, dtype: int64
内部标识号    24518
交易次数         2
交易金额     46979
Name: 24517, dtype: int64
内部标识号    24519
交易次数         1
交易金额       209
Name: 24518, dtype: int64
内部标识号    24520
交易次数         3
交易金额       375
Name: 24519, dtype: int64
内部标识号    24521

Name: 24718, dtype: int64
内部标识号    24720
交易次数         4
交易金额      2023
Name: 24719, dtype: int64
内部标识号    24721
交易次数         9
交易金额       288
Name: 24720, dtype: int64
内部标识号    24722
交易次数        10
交易金额       146
Name: 24721, dtype: int64
内部标识号    24723
交易次数         0
交易金额       258
Name: 24722, dtype: int64
内部标识号    24724
交易次数         3
交易金额       347
Name: 24723, dtype: int64
内部标识号    24725
交易次数         2
交易金额       898
Name: 24724, dtype: int64
内部标识号    24726
交易次数        13
交易金额       155
Name: 24725, dtype: int64
内部标识号    24727
交易次数         3
交易金额       487
Name: 24726, dtype: int64
内部标识号    24728
交易次数         3
交易金额       309
Name: 24727, dtype: int64
内部标识号    24729
交易次数         3
交易金额       437
Name: 24728, dtype: int64
内部标识号    24730
交易次数         1
交易金额       251
Name: 24729, dtype: int64
内部标识号    24731
交易次数        10
交易金额       206
Name: 24730, dtype: int64
内部标识号    24732
交易次数         3
交易金额       498
Name: 24731, dtype: int64
内部标识号    24733
交易次数         3
交易金额       474
Name: 24732, dtype: int64
内部标识号    24734
交易次数        13
交易金额       150
Name: 24733, dtype: int64
内部标识号    24735
交易次数         5
交易金额       375
Name: 24734, dtype: int64
内部标识号    24736
交易次数         1
交易金额       257
Name: 24735, dtype: int64
内部标识号    24737
交易次数         5
交易金额      3575
Name: 24736, dtype: int64
内部标识号    24738
交易次数         3
交易金额      5098
Name: 24737, dtype: int64
内部标识号    24739
交易次数         7
交易金额      8088
Name: 24738, dtype: int64
内部标识号    24740
交易次数         2
交易金额       541
Name: 24739, dtype: int64
内部标识号    24741
交易次数         0
交易金额     37294
Name: 24740, dtype: int64
内部标识号    24742
交易次数         1
交易金额       237
Name: 24741, dtype: int64
内部标识号    24743
交易次数         6
交易金额      2326
Name: 24742, dtype: int64
内部标识号    24744
交易次数        12
交易金额       170
Name: 24743, dtype: int64
内部标识号    24745
交易次数         2
交易金额       382
Name: 24744, dtype: int64
内部标识号    24746
交易次数         2
交易金额       302
Name: 24745, dtype: int64
内部标识号    24747
交易次数         3
交易金额       375
Name: 24746, dtype: int64
内部标识号    24748
交易次数         3
交易金额      4399
Name: 24747, dtype: int64
内部标识号    24749
交易次数         3
交易金额       423
Name: 24748, dtype: int64
内部标识号    24750
交易次数         2
交易金额       579
Name: 24749, dtype: int64
内部标识号    24751
交易次数         0
交易金额     30943
Name: 24750, dtype: int64
内部标识号    24752
交易次数         1
交易金额       665
Name: 24751, dtype: int64
内部标识号    24753
交易次数         8
交易金额       453
Name: 24752, dtype: int64
内部标识号    24754
交易次数        73
交易金额     20052
Name: 24753, dtype: int64
内部标识号    24755
交易次数         2
交易金额       325
Name: 24754, dtype: int64
内部标识号    24756
交易次数         1
交易金额       963
Name: 24755, dtype: int64
内部标识号    24757
交易次数         0
交易金额     88816
Name: 24756, dtype: int64
内部标识号    24758
交易次数        14
交易金额       273
Name: 24757, dtype: int64
内部标识号    24759
交易次数         3
交易金额       463
Name: 24758, dtype: int64
内部标识号    24760
交易次数        30
交易金额       779
Name: 24759, dtype: int64
内部标识号    24761
交易次数         8
交易金额       473
Name: 24760, dtype: int64
内部标识号    24762
交易次数         3
交易金额       360
Name: 24761, dtype: int64
内部标识号    24763
交易次数         3
交易金额       433
Name: 24762, dtype: int64
内部标识号    24764
交易次数        23
交易金额       603
Name: 24763, dtype: int64
内部标识号    24765
交易次数        10
交易金额       229
Name: 24764, dtype: int64
内部标识号    24766
交易次数         2
交易金额       860
Name: 24765, dtype: int64
内部标识号    24767
交易次数         1
交易金额       113
Name: 24766, dtype: int64
内部标识号    24768
交易次数        12
交易金额       183
Name: 24767, dtype: int64
内部标识号    24769
交易次数         7
交易金额       679
Name: 24768, dtype: int64
内部标识号    24770
交易次数         2
交易金额        16
Name: 24769, dtype: int64
内部标识号    24771
交易次数         2
交易金额       988
Name: 24770, dtype: int64
内部标识号    24772
交易次数         2
交易金额       365
Name: 24771, dtype: int64
内部标识号    24773
交易次数         3
交易金额      2955
Name: 24772, dtype: int64
内部标识号    24774
交易次数         0
交易金额       226
Name: 24773, dtype: int64
内部标识号    24775
交易次数         8
交易金额      4549
Name: 24774, dtype: int64
内部标识号    24776
交易次数         0
交易金额     35357
Name: 24775, dtype: int64
内部标识号    24777
交易次数         2
交易金额       542
Name: 24776, dtype: int64
内部标识号    24778
交易次数         6
交易金额       495
Name: 24777, dtype: int64
内部标识号    24779
交易次数         1
交易金额       216
Name: 24778, dtype: int64
内部标识号    24780
交易次数         3
交易金额       352
Name: 24779, dtype: int64
内部标识号    24781
交易次数         1
交易金额       588
Name: 24780, dtype: int64
内部标识号    24782
交易次数         2
交易金额       364
Name: 24781, dtype: int64
内部标识号    24783
交易次数         1
交易金额       957
Name: 24782, dtype: int64
内部标识号    24784
交易次数         3
交易金额       356
Name: 24783, dtype: int64
内部标识号    24785
交易次数         3
交易金额      9428
Name: 24784, dtype: int64
内部标识号    24786
交易次数         2
交易金额       429
Name: 24785, dtype: int64
内部标识号    24787
交易次数         2
交易金额       366
Name: 24786, dtype: int64
内部标识号    24788
交易次数         2
交易金额       695
Name: 24787, dtype: int64
内部标识号    24789
交易次数         2
交易金额       361
Name: 24788, dtype: int64
内部标识号    24790
交易次数        15
交易金额       182
Name: 24789, dtype: int64
内部标识号    24791
交易次数         1
交易金额        92
Name: 24790, dtype: int64
内部标识号    24792
交易次数         3
交易金额       416
Name: 24791, dtype: int64
内部标识号    24793
交易次数         2
交易金额       453
Name: 24792, dtype: int64
内部标识号    24794
交易次数         1
交易金额       920
Name: 24793, dtype: int64
内部标识号    24795
交易次数         0
交易金额     53453
Name: 24794, dtype: int64
内部标识号    24796
交易次数         0
交易金额       203
Name: 24795, dtype: int64
内部标识号    24797
交易次数         1
交易金额       261
Name: 24796, dtype: int64
内部标识号    24798
交易次数         2
交易金额       772
Name: 24797, dtype: int64
内部标识号    24799
交易次数         1
交易金额       978
Name: 24798, dtype: int64
内部标识号    24800
交易次数         3
交易金额       429
Name: 24799, dtype: int64
内部标识号    24801
交易次数         0
交易金额       240
Name: 24800, dtype: int64
内部标识号    24802
交易次数         0
交易金额       249
Name: 24801, dtype: int64
内部标识号    24803
交易次数         3
交易金额       317
Name: 24802, dtype: int64
内部标识号    24804
交易次数         2
交易金额       314
Name: 24803, dtype: int64
内部标识号    24805
交易次数         4
交易金额       608
Name: 24804, dtype: int64
内部标识号    24806
交易次数         2
交易金额       408
Name: 24805, dtype: int64
内部标识号    24807
交易次数         2
交易金额       907
Name: 24806, dtype: int64
内部标识号    24808
交易次数         7
交易金额      9449
Name: 24807, dtype: int64
内部标识号    24809
交易次数         3
交易金额       383
Name: 24808, dtype: int64
内部标识号    24810
交易次数        15
交易金额       142
Name: 24809, dtype: int64
内部标识号    24811
交易次数         0
交易金额       105
Name: 24810, dtype: int64
内部标识号    24812
交易次数        30
交易金额       912
Name: 24811, dtype: int64
内部标识号    24813
交易次数         7
交易金额       487
Name: 24812, dtype: int64
内部标识号    24814
交易次数         2
交易金额        70
Name: 24813, dtype: int64
内部标识号    24815
交易次数         0
交易金额     90266
Name: 24814, dtype: int64
内部标识号    24816
交易次数         3
交易金额       389
Name: 24815, dtype: int64
内部标识号    24817
交易次数         3
交易金额       393
Name: 24816, dtype: int64
内部标识号    24818
交易次数         3
交易金额      4978
Name: 24817, dtype: int64
内部标识号    24819
交易次数         0
交易金额       191
Name: 24818, dtype: int64
内部标识号    24820
交易次数         2
交易金额        20
Name: 24819, dtype: int64
内部标识号    24821
交易次数        13
交易金额       170
Name: 24820, dtype: int64
内部标识号    24822
交易次数         1
交易金额       970
Name: 24821, dtype: int64
内部标识号    24823
交易次数         3
交易金额       353
Name: 24822, dtype: int64
内部标识号    24824
交易次数         7
交易金额       345
Name: 24823, dtype: int64
内部标识号    24825
交易次数         3
交易金额       328
Name: 24824, dtype: int64
内部标识号    24826
交易次数         3
交易金额       404
Name: 24825, dtype: int64
内部标识号    24827
交易次数         0
交易金额       288
Name: 24826, dtype: int64
内部标识号    24828
交易次数         3
交易金额       385
Name: 24827, dtype: int64
内部标识号    24829
交易次数         1
交易金额       120
Name: 24828, dtype: int64
内部标识号    24830
交易次数         2
交易金额       417
Name: 24829, dtype: int64
内部标识号    24831
交易次数         3
交易金额       313
Name: 24830, dtype: int64
内部标识号    24832
交易次数        10
交易金额       247
Name: 24831, dtype: int64
内部标识号    24833
交易次数         3
交易金额       441
Name: 24832, dtype: int64
内部标识号    24834
交易次数         2
交易金额       838
Name: 24833, dtype: int64
内部标识号    24835
交易次数         5
交易金额      4085
Name: 24834, dtype: int64
内部标识号    24836
交易次数         8
交易金额       213
Name: 24835, dtype: int64
内部标识号    24837
交易次数         2
交易金额       472
Name: 24836, dtype: int64
内部标识号    24838
交易次数         3
交易金额       396
Name: 24837, dtype: int64
内部标识号    24839
交易次数         0
交易金额     70494
Name: 24838, dtype: int64
内部标识号    24840
交易次数         2
交易金额       898
Name: 24839, dtype: int64
内部标识号    24841
交易次数        22
交易金额       761
Name: 24840, dtype: int64
内部标识号    24842
交易次数         3
交易金额       421
Name: 24841, dtype: int64
内部标识号    24843
交易次数         1
交易金额       135
Name: 24842, dtype: int64
内部标识号    24844
交易次数         2
交易金额       407
Name: 24843, dtype: int64
内部标识号    24845
交易次数        26
交易金额       682
Name: 24844, dtype: int64
内部标识号    24846
交易次数         1
交易金额       526
Name: 24845, dtype: int64
内部标识号    24847
交易次数        13
交易金额       249
Name: 24846, dtype: int64
内部标识号    24848
交易次数         2
交易金额       432
Name: 24847, dtype: int64
内部标识号    24849
交易次数        19
交易金额       553
Name: 24848, dtype: int64
内部标识号    24850
交易次数         2
交易金额       815
Name: 24849, dtype: int64
内部标识号    24851
交易次数         8
交易金额       276
Name: 24850, dtype: int64
内部标识号    24852
交易次数         2
交易金额       347
Name: 24851, dtype: int64
内部标识号    24853
交易次数         3
交易金额       301
Name: 24852, dtype: int64
内部标识号    24854
交易次数         9
交易金额       173
Name: 24853, dtype: int64
内部标识号    24855
交易次数         1
交易金额       290
Name: 24854, dtype: int64
内部标识号    24856
交易次数         1
交易金额       156
Name: 24855, dtype: int64
内部标识号    24857
交易次数         6
交易金额      4221
Name: 24856, dtype: int64
内部标识号    24858
交易次数         2
交易金额       455
Name: 24857, dtype: int64
内部标识号    24859
交易次数         2
交易金额       400
Name: 24858, dtype: int64
内部标识号    24860
交易次数         3
交易金额       383
Name: 24859, dtype: int64
内部标识号    24861
交易次数         0
交易金额     97413
Name: 24860, dtype: int64
内部标识号    24862
交易次数        10
交易金额       179
Name: 24861, dtype: int64
内部标识号    24863
交易次数        11
交易金额       270
Name: 24862, dtype: int64
内部标识号    24864
交易次数         3
交易金额       415
Name: 24863, dtype: int64
内部标识号    24865
交易次数         2
交易金额       813
Name: 24864, dtype: int64
内部标识号    24866
交易次数         2
交易金额        42
Name: 24865, dtype: int64
内部标识号    24867
交易次数        11
交易金额       140
Name: 24866, dtype: int64
内部标识号    24868
交易次数         3
交易金额       389
Name: 24867, dtype: int64
内部标识号    24869
交易次数         2
交易金额       347
Name: 24868, dtype: int64
内部标识号    24870
交易次数         4
交易金额       825
Name: 24869, dtype: int64
内部标识号    24871
交易次数         1
交易金额       238
Name: 24870, dtype: int64
内部标识号    24872
交易次数        26
交易金额       975
Name: 24871, dtype: int64
内部标识号    24873
交易次数        12
交易金额       236
Name: 24872, dtype: int64
内部标识号    24874
交易次数         7
交易金额       871
Name: 24873, dtype: int64
内部标识号    24875
交易次数         0
交易金额       251
Name: 24874, dtype: int64
内部标识号    24876
交易次数         0
交易金额     95577
Name: 24875, dtype: int64
内部标识号    24877
交易次数         1
交易金额       159
Name: 24876, dtype: int64
内部标识号    24878
交易次数         4
交易金额       306
Name: 24877, dtype: int64
内部标识号    24879
交易次数         1
交易金额       788
Name: 24878, dtype: int64
内部标识号    24880
交易次数         3
交易金额      5666
Name: 24879, dtype: int64
内部标识号    24881
交易次数         0
交易金额     23435
Name: 24880, dtype: int64
内部标识号    24882
交易次数         8
交易金额       309
Name: 24881, dtype: int64
内部标识号    24883
交易次数         1
交易金额        71
Name: 24882, dtype: int64
内部标识号    24884
交易次数         8
交易金额      3312
Name: 24883, dtype: int64
内部标识号    24885
交易次数         1
交易金额       719
Name: 24884, dtype: int64
内部标识号    24886
交易次数         2
交易金额       333
Name: 24885, dtype: int64
内部标识号    24887
交易次数         1
交易金额       738
Name: 24886, dtype: int64
内部标识号    24888
交易次数         9
交易金额       133
Name: 24887, dtype: int64
内部标识号    24889
交易次数         3
交易金额       352
Name: 24888, dtype: int64
内部标识号    24890
交易次数        17
交易金额       969
Name: 24889, dtype: int64
内部标识号    24891
交易次数         3
交易金额       346
Name: 24890, dtype: int64
内部标识号    24892
交易次数         2
交易金额       749
Name: 24891, dtype: int64
内部标识号    24893
交易次数         5
交易金额       312
Name: 24892, dtype: int64
内部标识号    24894
交易次数         2
交易金额       758
Name: 24893, dtype: int64
内部标识号    24895
交易次数         2
交易金额       458
Name: 24894, dtype: int64
内部标识号    24896
交易次数         0
交易金额       250
Name: 24895, dtype: int64
内部标识号    24897
交易次数         3
交易金额       344
Name: 24896, dtype: int64
内部标识号    24898
交易次数         1
交易金额       132
Name: 24897, dtype: int64
内部标识号    24899
交易次数         5
交易金额       310
Name: 24898, dtype: int64
内部标识号    24900
交易次数        11
交易金额       164
Name: 24899, dtype: int64
内部标识号    24901
交易次数         1
交易金额       605
Name: 24900, dtype: int64
内部标识号    24902
交易次数        13
交易金额       288
Name: 24901, dtype: int64
内部标识号    24903
交易次数         4
交易金额       945
Name: 24902, dtype: int64
内部标识号    24904
交易次数        15
交易金额       269
Name: 24903, dtype: int64
内部标识号    24905
交易次数         1
交易金额       688
Name: 24904, dtype: int64
内部标识号    24906
交易次数        10
交易金额       282
Name: 24905, dtype: int64
内部标识号    24907
交易次数        25
交易金额       913
Name: 24906, dtype: int64
内部标识号    24908
交易次数         0
交易金额     74825
Name: 24907, dtype: int64
内部标识号    24909
交易次数       106
交易金额     73084
Name: 24908, dtype: int64
内部标识号    24910
交易次数       289
交易金额     22932
Name: 24909, dtype: int64
内部标识号    24911
交易次数       187
交易金额     71096
Name: 24910, dtype: int64
内部标识号    24912
交易次数         1
交易金额       718
Name: 24911, dtype: int64
内部标识号    24913
交易次数         2
交易金额       831
Name: 24912, dtype: int64
内部标识号    24914
交易次数         2
交易金额       420
Name: 24913, dtype: int64
内部标识号    24915
交易次数         1
交易金额        50
Name: 24914, dtype: int64
内部标识号    24916
交易次数         2
交易金额       390
Name: 24915, dtype: int64
内部标识号    24917
交易次数         6
交易金额      7399
Name: 24916, dtype: int64
内部标识号    24918
交易次数         8
交易金额      2826
Name: 24917, dtype: int64
内部标识号    24919
交易次数         3
交易金额      3854
Name: 24918, dtype: int64
内部标识号    24920
交易次数         2
交易金额       359
Name: 24919, dtype: int64
内部标识号    24921
交易次数         8
交易金额      1657
Name: 24920, dtype: int64
内部标识号    24922
交易次数         2
交易金额       997
Name: 24921, dtype: int64
内部标识号    24923
交易次数         8
交易金额       101
Name: 24922, dtype: int64
内部标识号    24924
交易次数         1
交易金额       145
Name: 24923, dtype: int64
内部标识号    24925
交易次数         4
交易金额      9633
Name: 24924, dtype: int64
内部标识号    24926
交易次数         3
交易金额       442
Name: 24925, dtype: int64
内部标识号    24927
交易次数         4
交易金额       305
Name: 24926, dtype: int64
内部标识号    24928
交易次数         8
交易金额      7671
Name: 24927, dtype: int64
内部标识号    24929
交易次数         4
交易金额      2889
Name: 24928, dtype: int64
内部标识号    24930
交易次数        15
交易金额       227
Name: 24929, dtype: int64
内部标识号    24931
交易次数         8
交易金额      1628
Name: 24930, dtype: int64
内部标识号    24932
交易次数         3
交易金额       322
Name: 24931, dtype: int64
内部标识号    24933
交易次数         3
交易金额      4761
Name: 24932, dtype: int64
内部标识号    24934
交易次数         8
交易金额       309
Name: 24933, dtype: int64
内部标识号    24935
交易次数         3
交易金额       457
Name: 24934, dtype: int64
内部标识号    24936
交易次数         0
交易金额     83216
Name: 24935, dtype: int64
内部标识号    24937
交易次数         2
交易金额       521
Name: 24936, dtype: int64
内部标识号    24938
交易次数         2
交易金额       302
Name: 24937, dtype: int64
内部标识号    24939
交易次数         8
交易金额       371
Name: 24938, dtype: int64
内部标识号    24940
交易次数         3
交易金额      1146
Name: 24939, dtype: int64
内部标识号    24941
交易次数        13
交易金额       145
Name: 24940, dtype: int64
内部标识号    24942
交易次数         3
交易金额       364
Name: 24941, dtype: int64
内部标识号    24943
交易次数         1
交易金额       698
Name: 24942, dtype: int64
内部标识号    24944
交易次数         3
交易金额       410
Name: 24943, dtype: int64
内部标识号    24945
交易次数         3
交易金额       378
Name: 24944, dtype: int64
内部标识号    24946
交易次数         2
交易金额       489
Name: 24945, dtype: int64
内部标识号    24947
交易次数         5
交易金额      7850
Name: 24946, dtype: int64
内部标识号    24948
交易次数         0
交易金额       182
Name: 24947, dtype: int64
内部标识号    24949
交易次数        29
交易金额       514
Name: 24948, dtype: int64
内部标识号    24950
交易次数         3
交易金额       407
Name: 24949, dtype: int64
内部标识号    24951
交易次数         0
交易金额       155
Name: 24950, dtype: int64
内部标识号    24952
交易次数       232
交易金额     59477
Name: 24951, dtype: int64
内部标识号    24953
交易次数         0
交易金额       183
Name: 24952, dtype: int64
内部标识号    24954
交易次数         2
交易金额     71063
Name: 24953, dtype: int64
内部标识号    24955
交易次数        11
交易金额       103
Name: 24954, dtype: int64
内部标识号    24956
交易次数         3
交易金额       358
Name: 24955, dtype: int64
内部标识号    24957
交易次数         3
交易金额       471
Name: 24956, dtype: int64
内部标识号    24958
交易次数         0
交易金额     40511
Name: 24957, dtype: int64
内部标识号    24959
交易次数        10
交易金额       293
Name: 24958, dtype: int64
内部标识号    24960
交易次数         1
交易金额       662
Name: 24959, dtype: int64
内部标识号    24961
交易次数         2
交易金额       423
Name: 24960, dtype: int64
内部标识号    24962
交易次数         3
交易金额       374
Name: 24961, dtype: int64
内部标识号    24963
交易次数         6
交易金额       579
Name: 24962, dtype: int64
内部标识号    24964
交易次数         3
交易金额      7283
Name: 24963, dtype: int64

KeyboardInterrupt:

In [18]:
zcfz_resulte_df.shape

(1440000, 5)

In [5]:
nbbsh_df

             0
0            0
1            1
2            2
3            3
4            4
5            5
6            6
7            7
8            8
9            9
10          10
11          11
12          12
13          13
14          14
15          15
16          16
17          17
18          18
19          19
20          20
21          21
22          22
23          23
24          24
25          25
26          26
27          27
28          28
29          29
...        ...
119970  119970
119971  119971
119972  119972
119973  119973
119974  119974
119975  119975
119976  119976
119977  119977
119978  119978
119979  119979
119980  119980
119981  119981
119982  119982
119983  119983
119984  119984
119985  119985
119986  119986
119987  119987
119988  119988
119989  119989
119990  119990
119991  119991
119992  119992
119993  119993
119994  119994
119995  119995
119996  119996
119997  119997
119998  119998
119999  119999

[120000 rows x 1 columns]

In [130]:
column_name=['id','target','card_type','netlong','owner_city','arpu','out_prdct_fee','prdct_fee','point_fee','myth_fee','brand','listing_date','listing_price','nettime','user_level','sex','family_client','group_client','music','expirationtime','video_member','other_tv','finance','bank','campus_client','migu_tv','age','adis','arpu_avg','myth_fee_avg','out_prdct_fee_avg','prdct_fee_avg','os','battery_capacity','storage','screen_size']

# names = ['id','target','card_type','netlong','owner_city','arpu','out_prdct_fee','prdct_fee','point_fee','myth_fee','brand','listing_date','listing_price','nettime','user_level','sex','family_client','group_client','music','expirationtime','video_member','other_tv','finance','bank','campus_client','migu_tv','age','adis','arpu_avg','myth_fee_avg','out_prdct_fee_avg','prdct_fee_avg']
original = pd.read_table('ZZ0702GuangFa_Samples100000_FeatureData.txt',names=column_name)
display(original.head(),original.shape)

,id,target,card_type,netlong,owner_city,arpu,out_prdct_fee,prdct_fee,point_fee,myth_fee,...,age,adis,arpu_avg,myth_fee_avg,out_prdct_fee_avg,prdct_fee_avg,os,battery_capacity,storage,screen_size
0,13013302938,1,0.0,NaN,联通联通,9.0,0.0,0.0,0.0,0.0,...,NaN,NaN,38.863332,0.0,NaN,0.0,4.0,4120mAh,64GB,6.0
1,13022062073,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,13035901978,1,NaN,NaN,NaN,37.2,0.0,0.0,0.0,0.0,...,NaN,NaN,37.013334,0.0,NaN,0.0,NaN,NaN,NaN,NaN
3,13042151031,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4.0,3050mAh,16/64GB,5.0
4,13045173577,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

(103513, 36)

In [131]:
display(original.target.value_counts())

0    92989
1    10524
Name: target, dtype: int64

In [132]:
sample_false=original[original['target']==0].sample(n=10000, replace=False,random_state=0, axis=None).reset_index(drop=True)
sample_true=original[original['target']==1].sample(n=10000, replace=False,random_state=0, axis=None).reset_index(drop=True)
combin_df=sample_true.append(sample_false)
combin_df.to_excel('d:\sample_model.xlsx',index=None)

In [133]:
sample_true.head()

,id,target,card_type,netlong,owner_city,arpu,out_prdct_fee,prdct_fee,point_fee,myth_fee,...,age,adis,arpu_avg,myth_fee_avg,out_prdct_fee_avg,prdct_fee_avg,os,battery_capacity,storage,screen_size
0,18746191488,1,1.0,37.0,黑龙江哈尔滨,45.32,6.48,29.0,0.0,0.0,...,NaN,1.0,45.320000,0.0,6.48,29.0,NaN,NaN,NaN,NaN
1,13769713610,1,0.0,NaN,云南曲靖,115.70,0.00,0.0,0.0,0.0,...,NaN,NaN,115.099998,0.0,NaN,0.0,4.0,2920mAH,16GB/32GB,5.0
2,13838040676,1,1.0,NaN,河南郑州,143.20,0.20,135.0,9951.0,0.0,...,NaN,1.0,148.810003,0.0,0.20,135.0,4.0,3000mAh,32GB,5.5
3,15945389676,1,0.0,30.0,黑龙江牡丹江,60.99,1.00,90.0,0.0,0.0,...,NaN,NaN,60.990002,0.0,1.00,90.0,4.0,3000mAh,16GB,5.7
4,13888246777,1,1.0,NaN,云南昆明,258.00,0.00,0.0,0.0,0.0,...,NaN,NaN,258.000000,0.0,NaN,0.0,3.0,1715mAh,16GB/64GB/128GB,4.7

In [123]:
import random
import pandas as pd
def create_column_randomsample(column_random_dict):
    total_column_dict={}
    total_column_df=[]
    for columns_name in column_random_dict:
        if columns_name not in total_column_dict:
            total_column_dict[columns_name]=[]        
        for value_keys in column_random_dict[columns_name]:
            value_keys_counts=int(column_random_dict[columns_name][value_keys]*100000)
            for index in range(value_keys_counts):
                total_column_dict[columns_name].append(value_keys)
            
    result_df=pd.DataFrame(total_column_dict)
    for columns in result_df.columns:
        result_df[columns]=result_df[columns].sample(frac=1).reset_index(drop=True)
    return result_df

def create_number_randomsample(number_random_dict):
    import numpy as np
    import random
    
    total_column_dict={}
    
    all_True_column_df={}
    all_False_column_df={}
    
    for columns_name in number_random_dict:
        number_random_dict_column_keyslist=list(number_random_dict[columns_name].keys())
        random.shuffle(number_random_dict_column_keyslist)        
        if columns_name not in total_column_dict:
            signle_True_column_df=[]
            for column_section_key in number_random_dict_column_keyslist:
                True_column_df=[]
                
                left_value=int(column_section_key.split('-')[0])
                right_value=int(column_section_key.split('-')[1])
                
                True_sample_number=int(100000*number_random_dict[columns_name][column_section_key]['false_ratio'])
                for value_number in range(True_sample_number):
                    True_column_df.append(random.randint(left_value,right_value))
                #print(left_value,right_value,True_column_df)
                signle_True_column_df+=(True_column_df)
            #print(signle_True_column_df)
            all_True_column_df[columns_name]=signle_True_column_df
            
    
    for columns_name in number_random_dict:
        number_random_dict_column_keyslist=list(number_random_dict[columns_name].keys())
        random.shuffle(number_random_dict_column_keyslist)        
        if columns_name not in total_column_dict:
            signle_False_column_df=[]
            for column_section_key in number_random_dict_column_keyslist:
                False_column_df=[]
                
                left_value=int(column_section_key.split('-')[0])
                right_value=int(column_section_key.split('-')[1])
                False_sample_number=int(100000*number_random_dict[columns_name][column_section_key]['true_ratio'])
                for value_number in range(False_sample_number):
                    False_column_df.append(random.randint(left_value,right_value))
                #print(left_value,right_value,True_column_df)
                signle_False_column_df+=(False_column_df)
            all_False_column_df[columns_name]=signle_False_column_df
            
    for columns_name in number_random_dict:       
        total_column_dict[columns_name]=all_True_column_df[columns_name]+all_False_column_df[columns_name]
        
    
    return pd.DataFrame(total_column_dict)
            
    
True_number_random_dict={
                        '年龄':{
                                 '18-18':{'false_ratio':0.01,'true_ratio':0.01},'19-25':{'false_ratio':0.08,'true_ratio':0.01},
                                 '25-35':{'false_ratio':0.5,'true_ratio':0.3},'35-45':{'false_ratio':0.3,'true_ratio':0.53},
                                 '45-60':{'false_ratio':0.1,'true_ratio':0.14},'60-90':{'false_ratio':0.01,'true_ratio':0.01},},
                        '近1个月交易次数':{
                                 '0-0':{'false_ratio':0.04,'true_ratio':0.03},'0-1':{'false_ratio':0.11,'true_ratio':0.05},
                                 '1-2':{'false_ratio':0.16,'true_ratio':0.10},'2-3':{'false_ratio':0.3,'true_ratio':0.15},
                                 '3-8':{'false_ratio':0.2,'true_ratio':0.21},'8-15':{'false_ratio':0.12,'true_ratio':0.3},
                                 '15-30':{'false_ratio':0.05,'true_ratio':0.12},'30-300':{'false_ratio':0.02,'true_ratio':0.04},}, 
                        '近1个月笔均交易金额':{
                                 '0-100':{'false_ratio':0.02,'true_ratio':0.01},'100-300':{'false_ratio':0.23,'true_ratio':0.18},
                                 '300-500':{'false_ratio':0.35,'true_ratio':0.25},'500-1000':{'false_ratio':0.21,'true_ratio':0.32},
                                 '1000-10000':{'false_ratio':0.12,'true_ratio':0.15},'10000-100000':{'false_ratio':0.07,'true_ratio':0.09},},                                 
                         '近3个月交易次数':{
                                 '0-0':{'false_ratio':0.04,'true_ratio':0.02},'0-3':{'false_ratio':0.11,'true_ratio':0.04},
                                 '3-6':{'false_ratio':0.16,'true_ratio':0.11},'6-10':{'false_ratio':0.2,'true_ratio':0.15},
                                 '10-25':{'false_ratio':0.3,'true_ratio':0.19},'25-50':{'false_ratio':0.12,'true_ratio':0.33},
                                 '50-100':{'false_ratio':0.05,'true_ratio':0.12},'100-1000':{'false_ratio':0.02,'true_ratio':0.04},}, 
                         '近3个月笔均交易金额':{
                                 '0-100':{'false_ratio':0.02,'true_ratio':0.01},'100-300':{'false_ratio':0.2,'true_ratio':0.17},
                                 '300-500':{'false_ratio':0.38,'true_ratio':0.24},'500-1000':{'false_ratio':0.23,'true_ratio':0.34},
                                 '1000-10000':{'false_ratio':0.11,'true_ratio':0.16},'10000-100000':{'false_ratio':0.06,'true_ratio':0.08},}, 
                         '近6个月交易次数':{
                                 '0-0':{'false_ratio':0.04,'true_ratio':0.01},'0-5':{'false_ratio':0.09,'true_ratio':0.05},
                                 '5-10':{'false_ratio':0.16,'true_ratio':0.10},'10-20':{'false_ratio':0.2,'true_ratio':0.15},
                                 '20-50':{'false_ratio':0.32,'true_ratio':0.23},'50-100':{'false_ratio':0.12,'true_ratio':0.31},
                                 '100-200':{'false_ratio':0.05,'true_ratio':0.11},'200-2000':{'false_ratio':0.02,'true_ratio':0.04},},
                         '近6个月笔均交易金额':{
                                 '0-100':{'false_ratio':0.02,'true_ratio':0.01},'100-300':{'false_ratio':0.19,'true_ratio':0.16},
                                 '300-500':{'false_ratio':0.36,'true_ratio':0.20},'500-1000':{'false_ratio':0.24,'true_ratio':0.37},
                                 '1000-10000':{'false_ratio':0.13,'true_ratio':0.17},'10000-100000':{'false_ratio':0.06,'true_ratio':0.09},}, 
                         '近12个月交易次数':{
                                 '0-0':{'false_ratio':0.04,'true_ratio':0.01},'0-10':{'false_ratio':0.08,'true_ratio':0.02},
                                 '10-20':{'false_ratio':0.15,'true_ratio':0.08},'20-50':{'false_ratio':0.21,'true_ratio':0.13},
                                 '50-100':{'false_ratio':0.33,'true_ratio':0.23},'100-200':{'false_ratio':0.12,'true_ratio':0.34},
                                 '200-400':{'false_ratio':0.05,'true_ratio':0.15},'400-4000':{'false_ratio':0.02,'true_ratio':0.04},},
    
                         '近12个月笔均交易金额':{
                                 '0-100':{'false_ratio':0.02,'true_ratio':0.01},'100-300':{'false_ratio':0.21,'true_ratio':0.14},
                                 '300-500':{'false_ratio':0.4,'true_ratio':0.22},'500-1000':{'false_ratio':0.21,'true_ratio':0.35},
                                 '1000-10000':{'false_ratio':0.12,'true_ratio':0.2},'10000-100000':{'false_ratio':0.04,'true_ratio':0.08},},
    
                         '近1个月人民币活期存款':{
                                 '0-5000':{'false_ratio':0.15,'true_ratio':0.06},'5000-10000':{'false_ratio':0.07,'true_ratio':0.07},
                                 '10000-30000':{'false_ratio':0.1,'true_ratio':0.1},'30000-50000':{'false_ratio':0.17,'true_ratio':0.14},
                                 '50000-80000':{'false_ratio':0.25,'true_ratio':0.33},'80000-150000':{'false_ratio':0.14,'true_ratio':0.14},
                                 '150000-500000':{'false_ratio':0.08,'true_ratio':0.12},'500000-5000000':{'false_ratio':0.04,'true_ratio':0.04},},
                         '近3个月人民币活期存款':{
                                 '0-5000':{'false_ratio':0.13,'true_ratio':0.05},'5000-10000':{'false_ratio':0.06,'true_ratio':0.07},
                                 '10000-30000':{'false_ratio':0.11,'true_ratio':0.09},'30000-50000':{'false_ratio':0.17,'true_ratio':0.16},
                                 '50000-80000':{'false_ratio':0.26,'true_ratio':0.35},'80000-150000':{'false_ratio':0.15,'true_ratio':0.14},
                                 '150000-500000':{'false_ratio':0.08,'true_ratio':0.1},'500000-5000000':{'false_ratio':0.04,'true_ratio':0.04},},
    
    
    
    
    
    

                        '近6个月人民币活期存款余额均值':{
                                                         '0-5000':{'false_ratio':0.14,'true_ratio':0.04},'5000-10000':{'false_ratio':0.08,'true_ratio':0.07},
                                                         '10000-30000':{'false_ratio':0.11,'true_ratio':0.09},'30000-50000':{'false_ratio':0.17,'true_ratio':0.16},
                                                         '50000-80000':{'false_ratio':0.25,'true_ratio':0.32},'80000-150000':{'false_ratio':0.14,'true_ratio':0.18},
                                                         '150000-500000':{'false_ratio':0.07,'true_ratio':0.1},
                                                         '500000-5000000':{'false_ratio':0.04,'true_ratio':0.04}},

                        '近12个月人民币活期存款余额均值':{
                                                         '0-5000':{'false_ratio':0.11,'true_ratio':0.03},'5000-10000':{'false_ratio':0.08,'true_ratio':0.08},
                                                         '10000-30000':{'false_ratio':0.11,'true_ratio':0.12},'30000-50000':{'false_ratio':0.18,'true_ratio':0.16},
                                                         '50000-80000':{'false_ratio':0.27,'true_ratio':0.33},'80000-150000':{'false_ratio':0.12,'true_ratio':0.14},
                                                         '150000-500000':{'false_ratio':0.09,'true_ratio':0.09},
                                                         '500000-5000000':{'false_ratio':0.04,'true_ratio':0.05}},

                        '近1个月人民币定期存款余额':{
                                                 '0-10000':{'false_ratio':0.05,'true_ratio':0.02},'10000-20000':{'false_ratio':0.09,'true_ratio':0.06},
                                                 '20000-50000':{'false_ratio':0.21,'true_ratio':0.18},'50000-80000':{'false_ratio':0.32,'true_ratio':0.28},
                                                 '80000-150000':{'false_ratio':0.18,'true_ratio':0.22},'150000-500000':{'false_ratio':0.09,'true_ratio':0.15},
                                                 '500000-1000000':{'false_ratio':0.04,'true_ratio':0.07},
                                                 '1000000-10000000':{'false_ratio':0.02,'true_ratio':0.02}},
                        '近3个月人民币定期存款余额均值':{
                                                         '0-10000':{'false_ratio':0.05,'true_ratio':0.02},'10000-20000':{'false_ratio':0.08,'true_ratio':0.07},
                                                         '20000-50000':{'false_ratio':0.2,'true_ratio':0.18},'50000-80000':{'false_ratio':0.31,'true_ratio':0.27},
                                                         '80000-150000':{'false_ratio':0.2,'true_ratio':0.23},'150000-500000':{'false_ratio':0.09,'true_ratio':0.14},
                                                         '500000-1000000':{'false_ratio':0.05,'true_ratio':0.07},
                                                        '1000000-10000000':{'false_ratio':0.02,'true_ratio':0.02}},

                        '客户级信用额度':{
                                           '2000-4000':{'false_ratio':0.06,'true_ratio':0},'4000-6000':{'false_ratio':0.14,'true_ratio':0.02},
                                           '6000-10000':{'false_ratio':0.12,'true_ratio':0.12},'10000-20000':{'false_ratio':0.05,'true_ratio':0.18},
                                           '20000-50000':{'false_ratio':0.02,'true_ratio':0.27},'50000-500000':{'false_ratio':0.01,'true_ratio':0.05},
                                            '999999999-999999999':{'false_ratio':0.6,'true_ratio':0.36}},

                        '近1个月个人贷款':{
                                        '0-0':{'false_ratio':0.3,'true_ratio':0.45},
                                        '0-20000':{'false_ratio':0.1,'true_ratio':0.15},
                                        '20000-25000':{'false_ratio':0.3,'true_ratio':0.2},
                                        '25000-50000':{'false_ratio':0.15,'true_ratio':0.1},
                                        '50000-100000':{'false_ratio':0.1,'true_ratio':0.05},
                                        '100000-500000':{'false_ratio':0.03,'true_ratio':0.03},
                                        '500000-5000000':{'false_ratio':0.02,'true_ratio':0.02},},

                        
                        '近12个月行内总资产均值':{
                                            '0-10000':{'false_ratio':0.13,'true_ratio':0.03},
                                            '10000-30000':{'false_ratio':0.09,'true_ratio':0.08},
                                            '30000-100000':{'false_ratio':0.21,'true_ratio':0.15},
                                            '100000-150000':{'false_ratio':0.31,'true_ratio':0.23},
                                            '150000-300000':{'false_ratio':0.13,'true_ratio':0.31},
                                            '300000-500000':{'false_ratio':0.07,'true_ratio':0.12},
                                            '500000-1000000':{'false_ratio':0.04,'true_ratio':0.06},
                                            '1000000-10000000':{'false_ratio':0.02,'true_ratio':0.02}},

                        '近1个月行内总资产':{
                                        '0-10000':{'false_ratio':0.15,'true_ratio':0.04},
                                        '10000-30000':{'false_ratio':0.12,'true_ratio':0.12},
                                        '30000-100000':{'false_ratio':0.2,'true_ratio':0.19},
                                        '100000-150000':{'false_ratio':0.30,'true_ratio':0.24},
                                        '150000-300000':{'false_ratio':0.12,'true_ratio':0.19},
                                        '300000-500000':{'false_ratio':0.08,'true_ratio':0.14},
                                        '500000-1000000':{'false_ratio':0.02,'true_ratio':0.06},
                                        '1000000-10000000':{'false_ratio':0.01,'true_ratio':0.02}},

                        '近12个月收入总额':{
                                        '0-50000':{'false_ratio':0.15,'true_ratio':0.08},
                                        '50000-60000':{'false_ratio':0.22,'true_ratio':0.15},
                                        '60000-85000':{'false_ratio':0.25,'true_ratio':0.18},
                                        '85000-120000':{'false_ratio':0.14,'true_ratio':0.2},
                                        '120000-180000':{'false_ratio':0.1,'true_ratio':0.25},
                                        '180000-240000':{'false_ratio':0.09,'true_ratio':0.09},
                                        '240000-360000':{'false_ratio':0.04,'true_ratio':0.04},
                                        '360000-3600000':{'false_ratio':0.01,'true_ratio':0.01},},



                        '近6个月人民币定期存款余额均值':{
                                                    '0-10000':{'false_ratio':0.05,'true_ratio':0.02},
                                                    '10000-20000':{'false_ratio':0.08,'true_ratio':0.07},
                                                    '20000-50000':{'false_ratio':0.20,'true_ratio':0.18},
                                                    '50000-80000':{'false_ratio':0.30,'true_ratio':0.27},
                                                    '80000-150000':{'false_ratio':0.20,'true_ratio':0.23},
                                                    '150000-500000':{'false_ratio':0.1,'true_ratio':0.14},
                                                    '500000-1000000':{'false_ratio':0.05,'true_ratio':0.07},
                                                    '1000000-1000000':{'false_ratio':0.02,'true_ratio':0.02},
                                                    },


                        '近12个月人民币定期存款余额均值':{
                                                    '0-10000':{'false_ratio':0.04,'true_ratio':0.03},
                                                    '10000-20000':{'false_ratio':0.08,'true_ratio':0.07},
                                                    '20000-50000':{'false_ratio':0.16,'true_ratio':0.14},
                                                    '50000-80000':{'false_ratio':0.35,'true_ratio':0.30},
                                                    '80000-150000':{'false_ratio':0.20,'true_ratio':0.22},
                                                    '150000-500000':{'false_ratio':0.1,'true_ratio':0.15},
                                                    '500000-1000000':{'false_ratio':0.05,'true_ratio':0.05},
                                                    '1000000-1000000':{'false_ratio':0.02,'true_ratio':0.04},
                                                    },


                        '征信认定年收入':{
                                    '0-20000':{'false_ratio':0.01,'true_ratio':0.01},
                                    '20000-50000':{'false_ratio':0.05,'true_ratio':0.05},
                                    '50000-80000':{'false_ratio':0.2,'true_ratio':0.1},
                                    '80000-120000':{'false_ratio':0.19,'true_ratio':0.14},
                                    '120000-200000':{'false_ratio':0.15,'true_ratio':0.3},
                                    '200000-500000':{'false_ratio':0.1,'true_ratio':0.1},
                                    '500000-1000000':{'false_ratio':0.05,'true_ratio':0.05},
                                    '1000000-10000000':{'false_ratio':0.01,'true_ratio':0.01},
                                    '999999999-999999999':{'false_ratio':0.24,'true_ratio':0.24},
                                    },


                        '近3个月平均收入':{
                                    '0-3000':{'false_ratio':0.08,'true_ratio':0.1},
                                    '3000-7000':{'false_ratio':0.12,'true_ratio':0.1},
                                    '7000-10000':{'false_ratio':0.35,'true_ratio':0.2},
                                    '10000-15000':{'false_ratio':0.20,'true_ratio':0.25},
                                    '15000-20000':{'false_ratio':0.12,'true_ratio':0.1},
                                    '20000-25000':{'false_ratio':0.1,'true_ratio':0.1},
                                    '25000-50000':{'false_ratio':0.02,'true_ratio':0.1},
                                    '50000-500000':{'false_ratio':0.01,'true_ratio':0.05},
                                    },

                        '近3个月平均支出':{
                                    '0-1000':{'false_ratio':0.05,'true_ratio':0.1},
                                    '1000-1200':{'false_ratio':0.15,'true_ratio':0.1},
                                    '1200-1500':{'false_ratio':0.30,'true_ratio':0.15},
                                    '1500-2000':{'false_ratio':0.25,'true_ratio':0.15},
                                    '2000-2500':{'false_ratio':0.12,'true_ratio':0.15},
                                    '2500-3000':{'false_ratio':0.08,'true_ratio':0.22},
                                    '3000-3500':{'false_ratio':0.04,'true_ratio':0.11},
                                    '3500-35000':{'false_ratio':0.01,'true_ratio':0.02},
                                    },

                        '近3个月平均净收入（收入-支出）':{
                                                    '0-2000':{'false_ratio':0.06,'true_ratio':0.06},
                                                    '2000-5000':{'false_ratio':0.16,'true_ratio':0.16},
                                                    '5000-8000':{'false_ratio':0.34,'true_ratio':0.20},
                                                    '8000-12000':{'false_ratio':0.19,'true_ratio':0.20},
                                                    '12000-15000':{'false_ratio':0.12,'true_ratio':0.19},
                                                    '15000-20000':{'false_ratio':0.08,'true_ratio':0.14},
                                                    '20000-40000':{'false_ratio':0.04,'true_ratio':0.04},
                                                    '40000-400000':{'false_ratio':0.01,'true_ratio':0.01},
                                                    },
                        
                        }


False_column_random_dict={'性别':{'0':0.56,'1':0.44},
                         '婚姻状况':{'D':0.07,'M':0.42,'S':0.35,'W':0.04,'O':0.12},
                         '学历':{'0':0.01,'1':0.03,'2':0.05,'3':0.15,'4':0.45,'5':0.15,'6':0.05,'7':0.05,'8':0.05,'9':0.01},
                         '居住情况':{'1':0.03,'2':0.03,'3':0.44,'4':0.1,'5':0.2,'6':0.1,'7':0.1},
                         '社会保障':{'1':0.7,'0':0.3},
                         '单位性质':{'00':0.07,'01':0.01,'02':0.3,'03':0.23,'04':0.01,'05':0.08,'06':0.1,'07':0.06,'08':0.07,
                                     '09':0.04,'10':0,'11':0.03},
                         '所属城市级别':{'1':0.25,'2':0.25,'3':0.15,'4':0.15,'5':0.1,'6':0.05,'7':0.05},
                         '客户风险承受能力等级':{'1':0.33,'2':0.23,'3':0.22,'4':0.13,'5':0.09},                       
                         
                        }
True_column_random_dict={'性别':{'0':0.68,'1':0.32},
                         '婚姻状况':{'D':0.05,'M':0.45,'S':0.35,'W':0.04,'O':0.11},
                         '学历':{'0':0,'1':0.01,'2':0.02,'3':0.1,'4':0.35,'5':0.25,'6':0.2,'7':0.05,'8':0.02,'9':0},
                         '居住情况':{'1':0.01,'2':0.01,'3':0.1,'4':0.3,'5':0.35,'6':0.2,'7':0.03},
                         '社会保障':{'1':0.9,'0':0.1},                         
                         '单位性质':{'00':0.15,'01':0.01,'02':0.38,'03':0.1,'04':0.01,'05':0.08,'06':0.1,'07':0.06,'08':0.07,
                                     '09':0.01,'10':0,'11':0.03},
                         '所属城市级别':{'1':0.35,'2':0.25,'3':0.15,'4':0.15,'5':0.05,'6':0.03,'7':0.02},
                         '客户风险承受能力等级':{'1':0.33,'2':0.33,'3':0.22,'4':0.1,'5':0.02},                
                                                
                        }



False_result_df=create_column_randomsample(False_column_random_dict)
False_result_df['target']=0
True_result_df=create_column_randomsample(True_column_random_dict)
True_result_df['target']=1

total_classify_df=False_result_df.append(True_result_df)
total_numerical_df=create_number_randomsample(True_number_random_dict)
total_classify_df.reset_index(drop=True,inplace=True)
total_numerical_df.reset_index(drop=True,inplace=True)

Resulet_combin_df_total=total_classify_df.merge(total_numerical_df,left_index=True, right_index=True)
Resulet_combin_df_total=Resulet_combin_df_total[['性别', '婚姻状况', '学历', '居住情况', '社会保障', '单位性质', '所属城市级别', '客户风险承受能力等级',
       '年龄', '近1个月交易次数', '近1个月笔均交易金额', '近3个月交易次数', '近3个月笔均交易金额',
       '近6个月交易次数', '近6个月笔均交易金额', '近12个月交易次数', '近12个月笔均交易金额', '近1个月人民币活期存款',
       '近3个月人民币活期存款', '近6个月人民币活期存款余额均值', '近12个月人民币活期存款余额均值', '近1个月人民币定期存款余额',
       '近3个月人民币定期存款余额均值', '客户级信用额度', '近1个月个人贷款', '近12个月行内总资产均值', '近1个月行内总资产',
       '近12个月收入总额', '近6个月人民币定期存款余额均值', '近12个月人民币定期存款余额均值', '征信认定年收入',
       '近3个月平均收入', '近3个月平均支出', '近3个月平均净收入（收入-支出）','target']]


Resulet_combin_df_sample=Resulet_combin_df_total[Resulet_combin_df_total['target']==1].sample(n=20000).append(Resulet_combin_df_total[Resulet_combin_df_total['target']==0].sample(frac=1))

Resulet_combin_df_sample.to_excel('d:\\上海兴业银行样本造数.xlsx',index=None)

In [124]:
total_numerical_df.to_excel('d:\\兴业连续变量.xlsx',index=None)

In [92]:
display(Resulet_combin_df_total.columns,Resulet_combin_df_total[Resulet_combin_df['target']==1].sample(n=20000).head())

Index(['性别', '婚姻状况', '学历', '居住情况', '社会保障', '单位性质', '所属城市级别', '客户风险承受能力等级',
       'target', '年龄', '近1个月交易次数', '近1个月笔均交易金额', '近3个月交易次数', '近3个月笔均交易金额',
       '近6个月交易次数', '近6个月笔均交易金额', '近12个月交易次数', '近12个月笔均交易金额', '近1个月人民币活期存款',
       '近3个月人民币活期存款', '近6个月人民币活期存款余额均值', '近12个月人民币活期存款余额均值', '近1个月人民币定期存款余额',
       '近3个月人民币定期存款余额均值', '客户级信用额度', '近1个月个人贷款', '近12个月行内总资产均值', '近1个月行内总资产',
       '近12个月收入总额', '近6个月人民币定期存款余额均值', '近12个月人民币定期存款余额均值', '征信认定年收入',
       '近3个月平均收入', '近3个月平均支出', '近3个月平均净收入（收入-支出）'],
      dtype='object')

,性别,婚姻状况,学历,居住情况,社会保障,单位性质,所属城市级别,客户风险承受能力等级,target,年龄,...,近1个月个人贷款,近12个月行内总资产均值,近1个月行内总资产,近12个月收入总额,近6个月人民币定期存款余额均值,近12个月人民币定期存款余额均值,征信认定年收入,近3个月平均收入,近3个月平均支出,近3个月平均净收入（收入-支出）
84200,男,S,4,6,0,02,1,2,1,69,...,67766,89593,230335,84930,145674,21885,999999999,9240,1928,23737
70522,男,S,4,6,1,05,1,2,1,30,...,1636909,79146,51336,404720,62771,1000000,999999999,9882,2936,19151
582,男,S,6,5,0,02,2,1,1,19,...,678410,6295,135632,99330,9283,345939,635480,112850,1382,87046
67137,男,S,7,4,1,03,1,1,1,30,...,2718967,231844,84116,52908,68066,858703,999999999,9582,2987,21313
34071,男,S,5,6,0,01,1,2,1,87,...,10452,149693,4514,43783,25378,51326,110532,19763,2438,12402

In [68]:
display(False_result_df.head(),True_result_df.head())

,性别,婚姻状况,学历,征信认定年收入,社会保障,单位性质,客户评级结果,手机品牌,客户风险承受能力等级,客户级信用额度,零售潜在客户,近12月是否贷款,target
0,男,未婚,大专,5万,1,私营企业,C4,小米,较低,50000,否,是,0
1,男,未婚,高中,10万,1,股份制企业,C2,荣耀,基本,10000,否,否,0
2,男,已婚,大专,5万,1,股份制企业,C3,荣耀,基本,10000,是,否,0
3,男,已婚,研究生,5万,1,外商投资企业,C4,小米,较低,5000,否,否,0
4,女,未婚,高中中专,10万,1,私营企业,C2,华为,基本,30000,是,否,0

,性别,婚姻状况,学历,征信认定年收入,社会保障,单位性质,客户评级结果,手机品牌,客户风险承受能力等级,客户级信用额度,零售潜在客户,近12月是否贷款,target
0,男,未婚,初中,10万,1,私营企业,C3,苹果,基本,50000,否,是,1
1,男,已婚,大专,5万,1,外商投资企业,C3,苹果,基本,20000,否,否,1
2,男,未婚,本科,30万,1,国有企业,C4,OPPO,中等,20000,是,是,1
3,男,已婚,研究生,5万,1,私营企业,C4,vivo,较低,20000,否,否,1
4,男,已婚,研究生,10万,1,私营企业,C5,华为,中等,50000,否,否,1

In [65]:
display(Resulet_combin_df.shape,Resulet_combin_df.head())

(200000, 39)

,性别,婚姻状况,学历,征信认定年收入_x,社会保障,单位性质,客户评级结果,手机品牌,客户风险承受能力等级,客户级信用额度_x,...,近1个月个人贷款,近12个月行内总资产均值,近1个月行内总资产,近12个月收入总额,近6个月人民币定期存款余额均值,近12个月人民币定期存款余额均值,征信认定年收入_y,近3个月平均收入,近3个月平均支出,近3个月平均净收入（收入-支出）
0,女,未婚,高中中专,10万,1,外商投资企业,C1,小米,较低,5000,...,1829810,126076,111308,5447,7782,1000000,76044,3127,2843,26612
0,男,已婚,初中,5万,1,外商投资企业,C3,苹果,中等,20000,...,1829810,126076,111308,5447,7782,1000000,76044,3127,2843,26612
1,女,已婚,高中中专,10万,0,股份制企业,C3,小米,较低,10000,...,1412901,136978,132059,16073,9280,1000000,76589,3392,2986,24731
1,女,未婚,大专,5万,0,私营企业,C4,OPPO,基本,50000,...,1412901,136978,132059,16073,9280,1000000,76589,3392,2986,24731
2,女,已婚,高中中专,5万,1,股份制企业,C1,vivo,基本,10000,...,1622047,119023,135160,23569,7482,1000000,72220,2165,2838,26745

In [59]:
display(False_result_df.head(),total_classify_df.head(),True_result_df.tail(),total_classify_df.tail())

,性别,婚姻状况,学历,征信认定年收入,社会保障,单位性质,客户评级结果,手机品牌,客户风险承受能力等级,客户级信用额度,零售潜在客户,近12月是否贷款
0,女,未婚,大专,5万,1,外商投资企业,C2,小米,基本,20000,否,是
1,女,已婚,高中中专,5万,0,私营企业,C1,荣耀,较低,20000,否,是
2,女,已婚,大专,10万,0,外商投资企业,C2,华为,中等,10000,否,否
3,女,已婚,高中中专,5万,0,股份制企业,C2,小米,较低,10000,否,否
4,男,已婚,高中中专,10万,0,股份制企业,C2,vivo,较低,10000,是,否

,性别,婚姻状况,学历,征信认定年收入,社会保障,单位性质,客户评级结果,手机品牌,客户风险承受能力等级,客户级信用额度,零售潜在客户,近12月是否贷款
0,女,未婚,大专,5万,1,外商投资企业,C2,小米,基本,20000,否,是
1,女,已婚,高中中专,5万,0,私营企业,C1,荣耀,较低,20000,否,是
2,女,已婚,大专,10万,0,外商投资企业,C2,华为,中等,10000,否,否
3,女,已婚,高中中专,5万,0,股份制企业,C2,小米,较低,10000,否,否
4,男,已婚,高中中专,10万,0,股份制企业,C2,vivo,较低,10000,是,否

,性别,婚姻状况,学历,征信认定年收入,社会保障,单位性质,客户评级结果,手机品牌,客户风险承受能力等级,客户级信用额度,零售潜在客户,近12月是否贷款
99995,男,已婚,大专,40万,1,私营企业,C3,小米,基本,50000,否,是
99996,女,未婚,大专,5万,1,外商投资企业,C4,荣耀,基本,20000,是,否
99997,女,已婚,大专,10万,1,外商投资企业,C3,OPPO,基本,50000,是,否
99998,女,已婚,大专,10万,1,外商投资企业,C4,苹果,较低,50000,是,是
99999,男,已婚,大专,10万,1,股份制企业,C3,vivo,基本,10000,是,是

,性别,婚姻状况,学历,征信认定年收入,社会保障,单位性质,客户评级结果,手机品牌,客户风险承受能力等级,客户级信用额度,零售潜在客户,近12月是否贷款
99995,男,已婚,大专,40万,1,私营企业,C3,小米,基本,50000,否,是
99996,女,未婚,大专,5万,1,外商投资企业,C4,荣耀,基本,20000,是,否
99997,女,已婚,大专,10万,1,外商投资企业,C3,OPPO,基本,50000,是,否
99998,女,已婚,大专,10万,1,外商投资企业,C4,苹果,较低,50000,是,是
99999,男,已婚,大专,10万,1,股份制企业,C3,vivo,基本,10000,是,是

In [47]:
#True_result_df.shape()
total_df.head()

,年龄,近1个月交易次数,近1个月笔均交易金额,近3个月交易次数,近3个月笔均交易金额,近6个月交易次数,近6个月笔均交易金额,近12个月交易次数,近12个月笔均交易金额,近1个月人民币活期存款,...,近1个月个人贷款,近12个月行内总资产均值,近1个月行内总资产,近12个月收入总额,近6个月人民币定期存款余额均值,近12个月人民币定期存款余额均值,征信认定年收入,近3个月平均收入,近3个月平均支出,近3个月平均净收入（收入-支出）
0,65,8,236,775,592,184,226,122,778,140597,...,22637,3421,282852,2965888,654147,321262,108817,8459,1426,580478
1,65,3,149,803,661,108,161,122,751,101894,...,37904,6686,228287,1427034,591676,236010,86954,9936,1328,899123
2,68,5,220,868,929,173,182,188,980,109067,...,43135,2077,282867,2260092,712199,242831,93481,9244,1462,417861
3,70,5,247,432,758,128,131,133,558,141182,...,24243,4467,201001,2235795,751191,222176,98540,7019,1420,879418
4,62,8,107,718,816,161,200,101,799,101291,...,48265,3217,259453,1901095,954362,163385,106441,9390,1350,140804

In [36]:
total_df.head()

,年龄,近1个月交易次数,近1个月笔均交易金额,近3个月交易次数,近3个月笔均交易金额,近6个月交易次数,近6个月笔均交易金额,近12个月交易次数,近12个月笔均交易金额,近1个月人民币活期存款,...,近1个月个人贷款,近12个月行内总资产均值,近1个月行内总资产,近12个月收入总额,近6个月人民币定期存款余额均值,近12个月人民币定期存款余额均值,征信认定年收入,近3个月平均收入,近3个月平均支出,近3个月平均净收入（收入-支出）
0,27,1,94,34,7853,886,66134,3,146,8751,...,2743081,107077,135617,158016,859239,13739,501743,38603,2500,183926
1,26,1,28,29,1917,1999,63161,2,174,9732,...,1107996,139670,145622,177851,589064,14032,975132,34732,2123,414954
2,27,2,32,44,9667,316,28266,9,163,5204,...,2788589,100820,149984,148057,674287,12326,628014,32343,2314,183618
3,26,1,73,47,5556,934,50342,0,240,9138,...,1688877,137135,102210,143818,664788,15863,726177,33273,2079,279426
4,25,2,92,48,3441,801,26665,5,174,9480,...,2904329,142293,137022,165602,609329,18874,513511,40285,2084,490758

In [37]:
for columns in total_df:
    print(columns,total_df[columns].value_counts())
#pandas_profiling.ProfileReport(total_df[['近1个月交易次数']])

年龄 35     9898
25     7674
45     7179
40     5224
42     5167
39     5137
37     5131
44     5047
43     5042
38     5032
36     5029
41     4979
27     4813
33     4773
26     4741
29     4711
32     4699
30     4682
31     4672
28     4659
34     4654
60     4095
24     2950
22     2926
20     2890
18     2864
19     2834
21     2821
23     2783
70     2336
       ...
80      205
74      204
94      202
90      201
71      199
104     196
79      195
118     195
82      194
111     193
77      189
110     187
15      134
13      134
0       122
1       120
16      118
11      115
2       115
7       114
4       114
6       111
9       110
5       107
10      106
17      104
8       101
14       97
3        91
12       87
Name: 年龄, Length: 121, dtype: int64
近1个月交易次数 2      35439
3      29301
1      20983
0      15038
8      12141
6       6961
5       6884
4       6876
7       6689
15      6215
10      5311
14      5292
9       5268
12      5249
11      5237
13      5151
26      1108
19      1102
21      1094
29      1089
18      1083
17      1081
16      1075
25      1057
22      1055
20      1052
24      1052
23      1046
28      1042
30      1037
       ...
143       17
299       17
266       17
99        17
172       17
78        17
234       17
122       16
201       16
262       16
125       16
254       16
104       15
182       15
260       15
278       15
237       15
181       14
192       14
221       14
102       14
291       14
45        13
92        13
167       13
141       12
212       12
282       11
91        10
173        8
Name: 近1个月交易次数, Length: 301, dtype: int64
近1个月笔均交易金额 300      486
500      421
431      340
429      339
357      335
387      335
392      333
313      332
379      329
483      329
369      328
472      328
485      326
491      326
480      325
384      325
316      323
337      323
411      322
358      321
342      321
453      320
312      319
482      318
325      317
443      317
419      317
414      316
391      316
346      316
        ...
66554      1
75537      1
20540      1
73494      1
2103       1
61288      1
3567       1
68475      1
8242       1
63529      1
38949      1
92187      1
69652      1
98310      1
20412      1
52163      1
53100      1
51053      1
64453      1
34725      1
98202      1
60359      1
35787      1
1845       1
28131      1
14131      1
10033      1
12080      1
89886      1
56176      1
Name: 近1个月笔均交易金额, Length: 24205, dtype: int64
近3个月交易次数 6      13737
3      10446
10     10199
0       9791
8       7061
9       7006
4       6907
7       6811
5       6646
25      4700
1       3787
2       3699
21      3152
24      3112
23      3096
14      3077
20      3076
19      3076
18      3061
11      3060
13      3054
12      3026
16      3025
15      3025
17      3017
22      3008
50      2115
26      1815
46      1814
29      1794
       ...
395        2
948        2
299        2
312        2
368        2
818        2
225        2
555        2
632        2
353        2
915        2
830        2
243        2
887        2
211        2
718        2
448        2
985        2
671        2
251        2
529        2
644        2
786        2
942        1
141        1
104        1
752        1
171        1
356        1
257        1
Name: 近3个月交易次数, Length: 1001, dtype: int64
近3个月笔均交易金额 300      475
500      411
308      353
471      349
460      344
413      341
407      340
484      339
315      338
337      338
453      336
302      336
466      335
333      335
450      334
433      333
414      333
483      332
325      331
419      331
418      331
320      331
403      330
301      330
364      330
451      330
495      330
452      329
424      329
372      329
        ...
9023       1
46253      1
21681      1
21357      1
66971      1
5689       1
78657      1
44590      1
77342      1
79389      1
73240      1
1467       1
68422      1
30133      1
42415      1
56736      1
85394      1
2918       1
15676      1
5433       1
97096      1
50467      1
72984      1
91415      1
97556      1
87313      1
99595      1
11106      1
4965       1
73558      1
Name: 近3个月笔均交易金额, Length: 22495, dtype: int64
近6个月交易次数 10      7616
0       7301
5       6719
20      5071
8       4397
7       4323
6       4316
9       4290
19      3234
15      3216
18      3207
13      3197
17      3184
16      3161
12      3095
11      3082
14      3068
50      2594
4       2368
1       2358
3       2303
2       2269
22      1872
32      1846
39      1844
43      1837
37      1834
23      1830
38      1809
44      1809
        ...
1163       1
216        1
614        1
398        1
206        1
629        1
1312       1
1440       1
1751       1
1037       1
1844       1
781        1
397        1
1381       1
1313       1
1472       1
1420       1
1204       1
1653       1
357        1
1984       1
948        1
396        1
674        1
692        1
564        1
449        1
1252       1
1270       1
840        1
Name: 近6个月交易次数, Length: 1938, dtype: int64
近6个月笔均交易金额 300      435
500      420
429      331
362      323
398      321
309      319
393      318
430      316
404      313
498      311
304      309
370      308
447      306
402      306
355      305
317      303
336      302
344      302
319      300
382      300
443      299
414      299
325      298
391      298
492      298
385      297
335      297
301      297
358      297
378      296
        ...
12739      1
47698      1
41553      1
29259      1
31306      1
27208      1
4347       1
90601      1
92648      1
63962      1
59864      1
35284      1
18892      1
98633      1
10688      1
14530      1
96618      1
78179      1
57689      1
41297      1
20815      1
22862      1
72026      1
86255      1
73953      1
20687      1
30922      1
4295       1
43372      1
89876      1
Name: 近6个月笔均交易金额, Length: 23532, dtype: int64
近12个月交易次数 0       5910
20      3239
10      2915
50      2187
12      2160
17      2120
15      2119
18      2113
14      2102
13      2093
11      2062
16      2050
19      2045
100     1562
53      1199
91      1171
48      1159
92      1155
96      1150
31      1148
94      1147
67      1147
80      1146
26      1143
89      1143
70      1143
45      1142
23      1140
57      1136
44      1134
        ...
1447       1
3622       1
3797       1
1748       1
1620       1
1108       1
2473       1
2601       1
3028       1
1958       1
3543       1
1574       1
3748       1
1701       1
2903       1
2087       1
854        1
2215       1
726        1
2647       1
678        1
2727       1
598        1
934        1
2983       1
470        1
1190       1
2391       1
1446       1
2047       1
Name: 近12个月交易次数, Length: 3329, dtype: int64
近12个月笔均交易金额 300      508
500      404
357      360
461      356
320      353
331      347
482      346
398      346
485      342
360      342
442      342
477      341
497      340
428      338
434      337
344      335
460      334
338      333
448      333
390      332
467      332
458      330
304      330
307      330
321      329
455      329
487      329
494      328
472      328
334      327
        ...
21669      1
23716      1
70797      1
72844      1
85126      1
37949      1
54325      1
21797      1
75000      1
38222      1
2636       1
77322      1
81416      1
87557      1
34239      1
40380      1
12875      1
3502       1
63861      1
33146      1
32083      1
11690      1
15784      1
28066      1
81288      1
38205      1
62769      1
94660      1
18915      1
81392      1
Name: 近12个月笔均交易金额, Length: 20963, dtype: int64
近1个月人民币活期存款 3978       12
2434       12
772        12
2573       12
2720       12
3699       11
1027       11
1333       11
3364       11
1421       11
246        11
658        11
4511       11
4888       11
4427       11
4414       11
4915       11
3834       11
868        11
1013       11
3251       11
3119       10
2794       10
613        10
2561       10
93         10
1727       10
130        10
388        10
3306       10
           ..
27135       1
101097      1
296528      1
40531       1
46678       1
50776       1
54874       1
56923       1
29180       1
61021       1
477723      1
237107      1
99824       1
226862      1
101873      1
105971      1
108020      1
120314      1
124412      1
126461      1
134657      1
402948      1
415242      1
1990155     1
161294      1
171539      1
202274      1
470565      1
482859      1
175850      1
Name: 近1个月人民币活期存款, Length: 114182, dtype: int64
近3个月人民币活期存款 4062       12
1279       11
3457       11
3119       11
1983       10
4499       10
2186       10
56440      10
245        10
77724      10
3902       10
1703       10
4702       10
525        10
56605      10
343        10
4843       10
1950       10
3368       10
4170       10
3451       10
53166       9
4359        9
1079        9
2883        9
2126        9
3254        9
1698        9
70736       9
2884        9
           ..
138741      1
1232367     1
94592       1
116182      1
177632      1
476638      1
17854       1
21948       1
16500       1
32185       1
3511        1
8162        1
6115        1
20456       1
53240       1
52655       1
4507054     1
24554       1
124481      1
22507       1
32750       1
62888       1
1603567     1
38308       1
44451       1
48545       1
91546       1
69015       1
49142       1
188583      1
Name: 近3个月人民币活期存款, Length: 113755, dtype: int64
近6个月人民币活期存款余额均值 5000       13
2366       12
2135       12
7242       11
4334       11
3051       11
6746       11
1436       11
2031       11
2078       11
5329       11
260        10
1488       10
5279       10
900        10
4478       10
8553       10
281        10
8526       10
3683       10
791        10
4547       10
1036       10
64220      10
1800       10
4395       10
305        10
2161       10
4736       10
9293       10
           ..
68813       1
14685       1
140273      1
142320      1
320980      1
2475665     1
291100      1
4934620     1
2036695     1
4404179     1
4428743     1
1657625     1
3456493     1
17341       1
62379       1
81099       1
10591       1
119136      1
7094        1
949         1
115042      1
13235       1
19453       1
23551       1
11184       1
54191       1
129381      1
123238      1
52140       1
16056       1
Name: 近6个月人民币活期存款余额均值, Length: 114158, dtype: int64
近12个月人民币活期存款余额均值 5683       12
8452       12
4230       12
6864       10
62824      10
6961       10
8914       10
7715       10
2507       10
9901        9
8175        9
5883        9
8872        9
2265        9
5134        9
9075        9
5447        9
922         9
6868        9
1953        9
386         9
9419        9
7789        9
4593        9
16039       9
8680        9
8943        9
37750       9
8417        9
9518        9
           ..
49874       1
60119       1
37592       1
39641       1
346851      1
92903       1
342765      1
74478       1
115442      1
3908286     1
254646      1
295923      1
98938       1
4813412     1
96869       1
72297       1
68203       1
4846196     1
123510      1
105081      1
111228      1
223911      1
154241      1
284581      1
408205      1
4510806     1
195221      1
432793      1
305770      1
279558      1
Name: 近12个月人民币活期存款余额均值, Length: 113617, dtype: int64
近1个月人民币定期存款余额 54478     10
62601     10
10600     10
60869      9
31351      9
60694      9
65221      9
17874      9
23343      9
79073      9
56296      9
78646      8
63235      8
28286      8
50331      8
73124      8
25806      8
75920      8
55415      8
74034      8
14804      8
62365      8
76506      8
63395      8
60088      8
59244      8
59611      8
62366      8
63620      8
68208      8
          ..
32812      1
338128     1
327383     1
24624      1
26673      1
28722      1
234394     1
250770     1
93125      1
69662      1
95174      1
97223      1
145405     1
143358     1
383955     1
124929     1
126978     1
114692     1
118790     1
12920      1
106504     1
471469     1
98316      1
209234     1
119762     1
115664     1
83989      1
348182     1
74700      1
75529      1
Name: 近1个月人民币定期存款余额, Length: 129099, dtype: int64
近3个月人民币定期存款余额均值 64010      10
69162       9
78197       9
66272       9
72489       9
65526       8
58369       8
62328       8
12745       8
17484       8
58780       8
78593       8
62890       8
76992       8
60665       8
63550       8
54040       8
73634       8
56359       7
62981       7
63411       7
79744       7
77034       7
67878       7
60507       7
62291       7
63057       7
67968       7
52765       7
55641       7
           ..
331364      1
380633      1
71271       1
97898       1
85612       1
1605        1
253502      1
137387      1
425482      1
124409      1
130554      1
128507      1
116221      1
122366      1
130482      1
132613      1
138758      1
136711      1
15116       1
247357      1
8515615     1
173585      1
4924961     1
210467      1
334101      1
740908      1
371093      1
495156      1
230965      1
907907      1
Name: 近3个月人民币定期存款余额均值, Length: 130594, dtype: int64

客户级信用额度 999999999    96000
7174            19
5350            19
4613            18
5695            18
5292            18
5322            17
5066            17
4450            17
4749            16
4603            16
5180            16
4609            16
5917            16
5328            16
8728            16
4161            16
5877            16
5661            16
5594            16
5605            16
6000            16
4815            16
8818            16
4529            16
5145            15
4650            15
5056            15
9396            15
5635            15
             ...
314039           1
195843           1
37564            1
33470            1
35519            1
434938           1
29472            1
99564            1
27427            1
44361            1
23205            1
36173            1
43579            1
11609            1
21846            1
30034            1
6701             1
27985            1
25936            1
40271            1
37436            1
25250            1
33342            1
38222            1
258640           1
494175           1
457329           1
332428           1
29344            1
295445           1
Name: 客户级信用额度, Length: 41494, dtype: int64
近1个月个人贷款 7385        13
8615        13
32          13
5419        13
7521        13
3111        12
5464        12
2191        12
435         12
489         12
4845        12
8768        12
2955        12
5580        12
7625        12
6197        12
5454        12
8706        12
4959        12
6188        12
9473        12
653         12
2105        12
9102        11
278         11
8360        11
6939        11
3267        11
7910        11
7852        11
            ..
1378162      1
597873       1
51696        1
647017       1
876409       1
907112       1
27476400     1
2656832      1
364387       1
368481       1
28511        1
66413        1
643373       1
670050       1
184203       1
19294110     1
153496       1
409493       1
659347       1
2031501      1
877047       1
1748871      1
85883        1
68460        1
692099       1
169856       1
880511       1
884605       1
588351       1
0            1
Name: 近1个月个人贷款, Length: 157319, dtype: int64
近12个月行内总资产均值 6716       8
128669     8
2047       7
143154     7
2747       7
7496       7
4303       7
6719       7
6060       7
128658     7
135527     7
9752       7
136118     7
141828     7
4774       7
1119       7
118335     7
3694       7
110649     6
102479     6
6706       6
502        6
1363       6
9771       6
114494     6
4399       6
61128      6
9558       6
2605       6
110239     6
          ..
69482      1
281146     1
259893     1
196372     1
431897     1
165659     1
440093     1
2335707    1
751397     1
225062     1
223015     1
198443     1
210733     1
470830     1
261940     1
233274     1
94054      1
20290      1
8008       1
5961       1
395505     1
12110      1
150098     1
57168      1
589652     1
61270      1
38745      1
34651      1
9783139    1
639364     1
Name: 近12个月行内总资产均值, Length: 151008, dtype: int64
近1个月行内总资产 6922      10
4119       9
2350       8
8520       8
8657       8
19362      8
9803       8
3237       8
1136       8
1103       8
2941       8
9333       8
103520     8
3805       7
5257       7
14018      7
117539     7
8200       7
124052     7
1207       7
1265       7
4339       7
6873       7
6093       7
6888       7
3154       7
3292       7
3703       7
6198       7
5819       7
          ..
182424     1
196769     1
292265     1
6254       1
77927      1
79974      1
36947      1
4163       1
53367      1
270405     1
573557     1
280648     1
22602      1
269016     1
290895     1
34896      1
32849      1
277920     1
73829      1
644419     1
831575     1
319601     1
573529     1
53339      1
57437      1
63582      1
65633      1
71778      1
338020     1
280119     1
Name: 近1个月行内总资产, Length: 145097, dtype: int64
近12个月收入总额 58021     12
58713     12
54598     12
50453     12
54992     11
58650     11
56388     11
53456     11
56156     11
55672     11
56873     11
51459     11
51604     11
56424     11
58609     11
54685     11
54558     11
53055     11
53128     10
55128     10
51287     10
52651     10
51138     10
54553     10
59236     10
50739     10
51496     10
56630     10
57907     10
54374     10
          ..
63445      1
303064     1
38873      1
36826      1
47069      1
85986      1
216994     1
186257     1
1867       1
143246     1
57168      1
65364      1
63317      1
61270      1
38745      1
34651      1
96101      1
67435      1
79725      1
122736     1
100219     1
114556     1
108415     1
155520     1
161669     1
159622     1
139144     1
137097     1
46270      1
4098       1
Name: 近12个月收入总额, Length: 122234, dtype: int64
近6个月人民币定期存款余额均值 1000000    4000
66243        10
68804        10
74532         9
63698         9
71848         9
66465         9
71781         9
56137         9
77389         9
77098         9
63474         9
76280         9
66051         9
54828         8
53173         8
51655         8
11926         8
65140         8
74755         8
74789         8
78513         8
72522         8
54059         8
72535         8
79578         8
74678         8
56523         8
64378         8
60094         8
           ...
469901        1
205708        1
744323        1
28598         1
82835         1
43901         1
1979          1
39803         1
754584        1
234394        1
398968        1
53154         1
106376        1
102282        1
110478        1
108431        1
614288        1
87953         1
412577        1
98196         1
96149         1
87822         1
350499        1
71577         1
67483         1
81820         1
341917        1
77726         1
75679         1
12486         1
Name: 近6个月人民币定期存款余额均值, Length: 127117, dtype: int64
近12个月人民币定期存款余额均值 1000000    6000
63760        10
51280         9
63945         9
55617         9
53149         8
62972         8
53645         8
58962         8
64807         8
55506         8
72019         8
50272         8
68809         8
65229         8
12707         8
63106         8
50375         8
66520         8
51361         8
65943         8
14323         8
61022         8
57023         8
59933         8
59436         8
64785         8
76233         8
57427         8
56239         8
           ...
29122         1
16836         1
18885         1
8648          1
10697         1
14795         1
106872        1
121207        1
119158        1
117109        1
24896         1
31043         1
18757         1
22855         1
12618         1
14667         1
332           1
57680         1
59729         1
63827         1
49492         1
33116         1
301407        1
86374         1
88423         1
76137         1
78186         1
125297        1
129395        1
2049          1
Name: 近12个月人民币定期存款余额均值, Length: 123728, dtype: int64
征信认定年收入 999999999    48000
57795            7
78555            7
196247           7
64554            6
94302            6
112299           6
53157            6
106919           6
94101            6
86768            6
95231            6
61031            6
59190            6
59925            6
65460            6
51837            6
73842            6
143974           6
68921            6
76116            6
60834            6
113240           6
53172            6
74055            6
58551            6
116326           6
66166            6
82251            6
75739            6
             ...
272203           1
8394573          1
197642           1
327504           1
982800           1
403211           1
98016            1
145161           1
91875            1
89828            1
85734            1
83687            1
79593            1
77546            1
599787           1
855790           1
130800           1
124659           1
382709           1
118518           1
116471           1
198045           1
634618           1
108283           1
102142           1
137821           1
157443           1
356279           1
409352           1
4098             1
Name: 征信认定年收入, Length: 117586, dtype: int64
近3个月平均收入 9713      35
8367      34
9151      33
7776      33
8769      32
9745      32
9358      31
8340      31
8797      31
8205      31
7170      31
8137      31
7000      31
7984      31
9489      30
9615      30
9841      30
7703      30
9038      30
9899      30
8817      30
7300      30
9480      29
8436      29
8270      29
7772      29
8703      29
8639      29
9049      29
8705      29
          ..
201920     1
328962     1
81141      1
347387     1
21928      1
134419     1
34114      1
36163      1
30044      1
32093      1
27999      1
191887     1
226636     1
44343      1
36147      1
38336      1
40241      1
40385      1
34242      1
44487      1
23849      1
320974     1
30172      1
15653      1
26078      1
28127      1
120296     1
116202     1
355599     1
41044      1
Name: 近3个月平均收入, Length: 42636, dtype: int64
近3个月平均支出 1200     271
1500     234
1483     184
1328     179
1324     175
1377     174
1437     174
1257     173
1219     173
1339     171
1462     170
1320     169
1333     169
1321     169
1440     168
1342     168
1228     168
1470     168
1234     168
1449     167
1208     167
1230     166
1372     166
1408     166
1337     166
1380     166
1442     165
1452     165
1267     164
1498     164
        ...
22701      1
5481       1
18387      1
22447      1
24494      1
28390      1
16290      1
17070      1
13088      1
8408       1
23725      1
15905      1
34230      1
21217      1
14276      1
13037      1
21345      1
11555      1
15649      1
24784      1
32979      1
31716      1
27691      1
22600      1
9199       1
23648      1
18634      1
29480      1
27750      1
33593      1
Name: 近3个月平均支出, Length: 6366, dtype: int64
近3个月平均净收入（收入-支出） 18252     24
19714     22
22584     22
21623     21
19122     21
18219     21
18554     20
18357     20
18478     20
18731     19
23909     19
21717     19
23867     19
18034     19
18330     18
23284     18
23359     18
20548     18
18729     18
21482     18
18294     18
19524     18
24000     18
19724     18
19181     18
23238     18
23489     18
23770     18
22762     18
21886     18
          ..
10052      1
193        1
814925     1
556879     1
55130      1
63326      1
65375      1
79718      1
6082       1
8131       1
49111      1
53209      1
55258      1
57307      1
63454      1
73699      1
10506      1
360431     1
716831     1
8261       1
30798      1
38994      1
36947      1
47190      1
55386      1
71778      1
79974      1
77927      1
84072      1
0          1
Name: 近3个月平均净收入（收入-支出）, Length: 59201, dtype: int64

In [ ]:
                         

true_result_df=create_column_randomsample(True_column_random_dict)
true_result_number_df=create_number_randomsample(True_number_random_dict)

True_combin_df=true_result_df.merge(true_result_number_df,left_index=True, right_index=True)



#True_combin_df=True_combin_df.merge(pd.DataFrame(sample_true[['id','owner_city']]),left_index=True, right_index=True)
#True_combin_df.rename(columns={'owner_city':'籍贯'},inplace=True)

                            
                                
'''
True_combin_df['target']=1


False_result_df=create_column_randomsample(False_column_random_dict)
False_result_number_df=create_number_randomsample(False_number_random_dict)
False_combin_df=False_result_df.merge(False_result_number_df,left_index=True, right_index=True)
#False_combin_df=False_combin_df.merge(pd.DataFrame(sample_false[['id','owner_city']]),left_index=True, right_index=True)
#False_combin_df.rename(columns={'owner_city':'籍贯'},inplace=True)
False_combin_df['target']=0

total_comple=True_combin_df.append(False_combin_df).reset_index(drop=True)

#total_comple=total_comple[['id','性别','年龄','籍贯','婚姻状况','学历','征信认定年收入','社会保障','客户级信用额度','美元账户额度','CRM评级结果','客户评级结果','借记卡层级','附卡卡数','存款期限','是否为低保户','受否贫困户','行业','职业','零售潜在客户','理财产品风险等级','手机品牌','基金风险等级','理财产品是否保本','客户风险承受能力等级','电子渠道购买标志','贷款放款本金','账户余额','贷款期数','剩余贷款本金','购买金额_事件表','数量_事件表','可用余额_事件表','分期金额_事件表','贷款期限_事件表','未还本金_事件表','偿还金额_事件表','金额_事件表','交易金额_交易日志表','产品万份收益_基金产品','车产价值_字典列表','房产价值_字典列表','交易金额_交易往来','存期_交易账务','交易金额_交易账务','行内总资产_资产负债','行内总负债_资产负债','本外币存款_资产负债','人民币活期存款_资产负债','人民币定期存款_资产负债','本外币理财_资产负债','人民币理财_资产负债','万利宝理财_资产负债','保本型理财_人民币_资产负债','结构性存款_人民币_资产负债','兴业宝资产_资产负债','综合金融资产_资产负债','券商集合理财_资产负债','保险_资产负债','个人贷款_资产负债','个人购房按揭贷款_资产负债','个人委托贷款_资产负债','个人消费贷款_资产负债','target']]
total_comple=total_comple[['性别','年龄','婚姻状况','学历','开户日期','征信认定年收入','社会保障','客户级信用额度','美元账户额度','CRM评级结果','客户评级结果','借记卡层级','附卡卡数','存款期限','是否为低保户','受否贫困户','行业','职业','零售潜在客户','理财产品风险等级','手机品牌','基金风险等级','理财产品是否保本','客户风险承受能力等级','电子渠道购买标志','贷款放款本金','账户余额','贷款期数','剩余贷款本金','购买金额_事件表','数量_事件表','可用余额_事件表','分期金额_事件表','贷款期限_事件表','未还本金_事件表','偿还金额_事件表','金额_事件表','交易金额_交易日志表','产品万份收益_基金产品','车产价值_字典列表','房产价值_字典列表','交易金额_交易往来','存期_交易账务','交易金额_交易账务','行内总资产_资产负债','行内总负债_资产负债','本外币存款_资产负债','人民币活期存款_资产负债','人民币定期存款_资产负债','本外币理财_资产负债','人民币理财_资产负债','万利宝理财_资产负债','保本型理财_人民币_资产负债','结构性存款_人民币_资产负债','兴业宝资产_资产负债','综合金融资产_资产负债','券商集合理财_资产负债','保险_资产负债','个人贷款_资产负债','个人购房按揭贷款_资产负债','个人委托贷款_资产负债','个人消费贷款_资产负债','target']]


# 生成随机日期函数：
import datetime
def create_random_date(rowdata):
    #print (datetime.datetime.now()+datetime.timedelta(days=-1)).strftime("%Y-%m-%d %H:%M:%S")
    #print(datetime.datetime.now()+datetime.timedelta(days=rowdata['开户日期']).strftime("%Y-%m-%d"))
    print((datetime.datetime.now()-datetime.timedelta(days=rowdata['开户日期'])).strftime("%Y-%m-%d"))
    return (datetime.datetime.now()-datetime.timedelta(days=rowdata['开户日期'])).strftime("%Y-%m-%d")
total_comple['开户日期']=total_comple.apply(create_random_date,axis=1)
'''

In [135]:
total_comple.head()

,性别,年龄,婚姻状况,学历,开户日期,征信认定年收入,社会保障,客户级信用额度,美元账户额度,CRM评级结果,...,结构性存款_人民币_资产负债,兴业宝资产_资产负债,综合金融资产_资产负债,券商集合理财_资产负债,保险_资产负债,个人贷款_资产负债,个人购房按揭贷款_资产负债,个人委托贷款_资产负债,个人消费贷款_资产负债,target
0,男,12,未婚,大专,1999-08-15,5万,0,20000,0,核心,...,49405,23432,25468,10041,4184,78639,376452,12277,5605,1
1,女,25,已婚,初中中专,2019-09-17,10万,1,50000,0,普通,...,39884,18805,14512,7880,3957,80815,379467,11764,3858,1
2,男,-10,未婚,大专,2015-03-27,5万,0,10000,0,普通,...,50171,11834,11639,9109,4451,66963,295913,18028,5434,1
3,男,20,已婚,大专,2002-10-13,10万,1,30000,0,核心,...,44882,19946,9732,10432,4529,70032,510295,14891,4267,1
4,男,19,已婚,大专,2003-02-18,5万,0,50000,0,普通,...,44677,15478,12109,9432,4324,72221,343757,18678,5915,1

In [136]:
# 对样本数据进行处理，将负值修改为0

random_columns_list=['贷款放款本金','账户余额','贷款期数','剩余贷款本金','购买金额_事件表','数量_事件表','可用余额_事件表','分期金额_事件表','贷款期限_事件表','未还本金_事件表','偿还金额_事件表','金额_事件表','交易金额_交易日志表','产品万份收益_基金产品','车产价值_字典列表','房产价值_字典列表','交易金额_交易往来','存期_交易账务','交易金额_交易账务','行内总资产_资产负债','行内总负债_资产负债','本外币存款_资产负债','人民币活期存款_资产负债','人民币定期存款_资产负债','本外币理财_资产负债','人民币理财_资产负债','万利宝理财_资产负债','保本型理财_人民币_资产负债','结构性存款_人民币_资产负债','兴业宝资产_资产负债','综合金融资产_资产负债','券商集合理财_资产负债','保险_资产负债','个人贷款_资产负债','个人购房按揭贷款_资产负债','个人委托贷款_资产负债','个人消费贷款_资产负债']


def deal_zero_value(rowdata,column):
    if rowdata[column]<0:
        return 0
    else:
        return rowdata[column]
    
    
for random_colum in random_columns_list:    
    total_comple[random_colum]=total_comple.apply(deal_zero_value,axis=1, args = (random_colum,))

In [137]:
display(True_combin_df.head(),False_combin_df.head(),total_comple.tail())
print(total_comple.shape,True_combin_df.shape,False_combin_df.shape,total_comple.columns)

,性别,婚姻状况,学历,征信认定年收入,社会保障,客户级信用额度,美元账户额度,CRM评级结果,客户评级结果,借记卡层级,...,兴业宝资产_资产负债,综合金融资产_资产负债,券商集合理财_资产负债,保险_资产负债,个人贷款_资产负债,个人购房按揭贷款_资产负债,个人委托贷款_资产负债,个人消费贷款_资产负债,开户日期,target
0,男,未婚,大专,5万,0,20000,0,核心,C5,金卡,...,23432,25468,10041,4184,78639,376452,12277,5605,7446.714355,1
1,女,已婚,初中中专,10万,1,50000,0,普通,C1,金卡,...,18805,14512,7880,3957,80815,379467,11764,3858,108.866684,1
2,男,未婚,大专,5万,0,10000,0,普通,C3,普卡,...,11834,11639,9109,4451,66963,295913,18028,5434,1744.237549,1
3,男,已婚,大专,10万,1,30000,0,核心,C2,白金,...,19946,9732,10432,4529,70032,510295,14891,4267,6292.313477,1
4,男,已婚,大专,5万,0,50000,0,普通,C4,普卡,...,15478,12109,9432,4324,72221,343757,18678,5915,6164.348145,1

,性别,婚姻状况,学历,征信认定年收入,社会保障,客户级信用额度,美元账户额度,CRM评级结果,客户评级结果,借记卡层级,...,兴业宝资产_资产负债,综合金融资产_资产负债,券商集合理财_资产负债,保险_资产负债,个人贷款_资产负债,个人购房按揭贷款_资产负债,个人委托贷款_资产负债,个人消费贷款_资产负债,开户日期,target
0,男,已婚,小学,40万,1,10000,0,普通,C3,普卡,...,11747,9048,9531,929,47535,213117,6595,22222,1088.429199,0
1,女,未婚,大专,5万,1,10000,0,准核心,C2,白金,...,7289,12950,8118,861,48017,162023,11036,9673,1220.908081,0
2,女,已婚,高中中专,5万,0,20000,0,普通,C4,普卡,...,15520,9893,7520,767,53450,151895,10159,-3269,957.995117,0
3,男,未婚,高中中专,5万,1,10000,0,普通,C3,普卡,...,8076,9410,4284,487,45945,103304,6625,-11558,1077.512817,0
4,女,未婚,高中中专,5万,1,10000,0,普通,C3,白金,...,13992,13881,4240,786,55331,176267,10152,-4469,689.687500,0

,性别,年龄,婚姻状况,学历,开户日期,征信认定年收入,社会保障,客户级信用额度,美元账户额度,CRM评级结果,...,结构性存款_人民币_资产负债,兴业宝资产_资产负债,综合金融资产_资产负债,券商集合理财_资产负债,保险_资产负债,个人贷款_资产负债,个人购房按揭贷款_资产负债,个人委托贷款_资产负债,个人消费贷款_资产负债,target
99995,男,29,已婚,高中中专,2017-03-30,10万,1,20000,0,普通,...,41915,15396,9325,5536,906,50827,82965,11304,9481,0
99996,男,37,未婚,高中,2017-10-11,10万,1,5000,0,核心,...,25032,24468,12483,5174,1037,48866,183879,8211,0,0
99997,男,25,未婚,高中中专,2017-03-30,10万,0,10000,0,普通,...,27005,18522,9303,6758,721,54899,182742,10197,8090,0
99998,女,29,未婚,高中中专,2016-12-19,10万,1,50000,0,普通,...,45068,12262,5797,4672,1036,52021,243886,9382,613,0
99999,男,9,未婚,大专,2017-05-14,5万,0,5000,0,准核心,...,35195,13049,12545,4444,1359,47716,170418,9210,19285,0

(100000, 63) (50000, 63) (50000, 63) Index(['性别', '年龄', '婚姻状况', '学历', '开户日期', '征信认定年收入', '社会保障', '客户级信用额度',
       '美元账户额度', 'CRM评级结果', '客户评级结果', '借记卡层级', '附卡卡数', '存款期限', '是否为低保户',
       '受否贫困户', '行业', '职业', '零售潜在客户', '理财产品风险等级', '手机品牌', '基金风险等级', '理财产品是否保本',
       '客户风险承受能力等级', '电子渠道购买标志', '贷款放款本金', '账户余额', '贷款期数', '剩余贷款本金',
       '购买金额_事件表', '数量_事件表', '可用余额_事件表', '分期金额_事件表', '贷款期限_事件表', '未还本金_事件表',
       '偿还金额_事件表', '金额_事件表', '交易金额_交易日志表', '产品万份收益_基金产品', '车产价值_字典列表',
       '房产价值_字典列表', '交易金额_交易往来', '存期_交易账务', '交易金额_交易账务', '行内总资产_资产负债',
       '行内总负债_资产负债', '本外币存款_资产负债', '人民币活期存款_资产负债', '人民币定期存款_资产负债',
       '本外币理财_资产负债', '人民币理财_资产负债', '万利宝理财_资产负债', '保本型理财_人民币_资产负债',
       '结构性存款_人民币_资产负债', '兴业宝资产_资产负债', '综合金融资产_资产负债', '券商集合理财_资产负债', '保险_资产负债',
       '个人贷款_资产负债', '个人购房按揭贷款_资产负债', '个人委托贷款_资产负债', '个人消费贷款_资产负债', 'target'],
      dtype='object')

In [138]:
total_comple.to_excel('d:/上海兴业银行样本数据集.xlsx',index=None)

In [ ]:
# 生成随机日期函数：
import
def create_random_date(rowdata):
    print(rowdata.)

In [8]:
True_combin_df.head()

,性别,婚姻状况,学历,征信认定年收入,社会保障,客户级信用额度,美元账户额度,CRM评级结果,客户评级结果,借记卡层级,...,存款期限,是否为低保户,受否贫困户,年龄,贷款放款本金,账户余额,贷款期数,剩余贷款本金,id,籍贯
0,女,未婚,本科,5万,1,20000,小于0,核心,C4,普卡,...,6个月,否,否,10,539739,-7114,123,404910,13013302938,联通联通
1,男,已婚,大专,20万,1,20000,大于0,核心,C4,金卡,...,1年,否,否,48,807197,74019,63,404393,13022062073,NaN
2,男,已婚,高中中专,5万,1,10000,小于0,核心,C6,白金,...,1年,否,否,11,679981,216705,117,63766,13035901978,NaN
3,男,已婚,高中,5万,1,50000,小于0,核心,C1,白金,...,5年,否,否,30,498424,185155,201,330451,13042151031,NaN
4,男,已婚,大专,10万,1,50000,小于0,核心,C1,普卡,...,5年,否,否,12,511549,115947,-6,326409,13045173577,NaN

In [21]:
combin_df[['id','性别','籍贯','婚姻状况','学历','征信认定年收入','社会保障','客户级信用额度','美元账户额度','CRM评级结果','客户评级结果','借记卡层级','账户余额','剩余贷款本金']].to_excel('d:\上海兴业银行样本造数.xlsx',index=None)

In [164]:
display(true_result_df.head(),true_result_number_df.head())

,性别,婚姻状况,学历,征信认定年收入,社会保障,客户级信用额度,美元账户额度,CRM评级结果,客户评级结果,借记卡层级,附卡卡数,存款期限,是否为低保户,受否贫困户
0,男,已婚,大专,5万,1,30000,小于0,普通,C3,黑金,4,1年,否,否
1,男,已婚,高中,10万,1,30000,小于0,准核心,C3,普卡,0,3个月,否,否
2,女,已婚,本科,5万,0,20000,小于0,普通,C4,普卡,3,1年,否,否
3,男,已婚,大专,10万,1,20000,小于0,普通,C3,金卡,1,2年,否,否
4,女,已婚,小学,5万,1,20000,小于0,普通,C3,白金,0,5年,否,否

   年龄  贷款放款本金  账户余额  贷款期数  剩余贷款本金
0  37  691320     8   317  445082
1  15  645061    29    49  196353
2  19  579867    29   157  368844
3  10  667989    34    33  329207
4  30  566405    51   118  330431

In [12]:
pd.DataFrame

,id,target,card_type,netlong,owner_city,arpu,out_prdct_fee,prdct_fee,point_fee,myth_fee,...,age,adis,arpu_avg,myth_fee_avg,out_prdct_fee_avg,prdct_fee_avg,os,battery_capacity,storage,screen_size
97032,18746191488,1,1.0,37.0,黑龙江哈尔滨,45.32,6.48,29.0,0.0,0.0,...,NaN,1.0,45.320000,0.0,6.480000,29.000000,NaN,NaN,NaN,NaN
29750,13769713610,1,0.0,NaN,云南曲靖,115.70,0.00,0.0,0.0,0.0,...,NaN,NaN,115.099998,0.0,NaN,0.000000,4.0,2920mAH,16GB/32GB,5.0
36394,13838040676,1,1.0,NaN,河南郑州,143.20,0.20,135.0,9951.0,0.0,...,NaN,1.0,148.810003,0.0,0.200000,135.000000,4.0,3000mAh,32GB,5.5
79629,15945389676,1,0.0,30.0,黑龙江牡丹江,60.99,1.00,90.0,0.0,0.0,...,NaN,NaN,60.990002,0.0,1.000000,90.000000,4.0,3000mAh,16GB,5.7
40228,13888246777,1,1.0,NaN,云南昆明,258.00,0.00,0.0,0.0,0.0,...,NaN,NaN,258.000000,0.0,NaN,0.000000,3.0,1715mAh,16GB/64GB/128GB,4.7
82230,15980726225,1,1.0,NaN,福建福州,78.00,0.00,62.0,0.0,0.0,...,35.0,NaN,91.333333,0.0,NaN,75.333333,4.0,2300mAh,16GB,5.0
62550,15217163366,1,2.0,50.0,广东珠海,55.12,0.00,28.0,0.0,0.0,...,NaN,NaN,54.293334,0.0,NaN,28.000000,4.0,3100mAh,8GB,5.5
99664,18811186422,1,1.0,43.0,北京北京,118.00,0.00,118.0,0.0,0.0,...,NaN,NaN,118.224998,0.0,NaN,118.000000,4.0,3000mAh,16GB,5.5
93368,18374069022,1,0.0,44.0,湖南株洲,31.49,0.00,0.0,0.0,0.0,...,NaN,NaN,22.496667,0.0,NaN,0.000000,NaN,NaN,NaN,NaN
13231,13580829297,1,0.0,NaN,广东东莞,178.00,0.00,173.0,0.0,0.0,...,NaN,NaN,176.866669,0.0,NaN,171.333333,4.0,3750mAh,64GB/128GB/256GB,5.5
50248,15003597752,1,0.0,NaN,山西运城,8.10,0.10,8.0,408.0,0.0,...,NaN,NaN,14.826667,0.0,0.160000,8.000000,4.0,2920mAH,32GB,5.0
21605,13672713333,1,0.0,NaN,广东珠海,118.76,0.00,63.0,0.0,0.0,...,NaN,NaN,105.693334,0.0,NaN,63.000000,4.0,4000mAh,128GB,5.7
15425,13602989303,1,0.0,NaN,广东肇庆,121.00,0.00,111.0,0.0,0.0,...,NaN,NaN,141.486669,0.0,NaN,124.333333,3.0,3470mAh,32GB,4.0
85395,18128373968,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29736,13769461052,1,1.0,NaN,云南红河,169.80,0.00,0.0,0.0,0.0,...,NaN,NaN,183.586670,0.0,NaN,0.000000,4.0,2900mAH,64GB,5.5
57551,15118650080,1,3.0,NaN,广东佛山,128.10,0.00,118.0,0.0,0.0,...,NaN,NaN,128.422501,0.0,NaN,118.000000,4.0,2400mAh,32GB,5.2
26250,13723405448,1,0.0,NaN,广东深圳,185.10,0.00,158.0,0.0,0.0,...,NaN,NaN,184.600001,0.0,NaN,158.000000,4.0,3010mAh,64GB,5.5
66805,15702956415,1,0.0,18.0,陕西西安,100.20,0.00,98.0,0.0,0.0,...,NaN,1.0,99.233332,0.0,NaN,98.000000,NaN,NaN,NaN,NaN
24009,13700074979,1,1.0,NaN,辽宁盘锦,128.00,0.00,178.0,3499.0,0.0,...,NaN,NaN,128.950002,0.0,NaN,178.000000,4.0,3000mAh,16GB,5.5
77370,15914571530,1,3.0,NaN,广东佛山,65.98,0.00,58.0,0.0,0.0,...,27.0,NaN,63.185001,0.0,NaN,54.250000,3.0,1800mAh,16GB/64GB/128GB,5.5
87546,18245335945,1,0.0,57.0,黑龙江牡丹江,48.35,24.35,19.0,7915.0,0.0,...,NaN,NaN,63.280000,0.0,39.280001,19.000000,4.0,2850mAh,64GB,5.5
74429,15868988798,1,0.0,NaN,浙江金华,255.10,0.10,171.0,0.0,0.0,...,NaN,NaN,255.166672,0.0,0.133333,171.000000,4.0,2820mAH,NaN,5.2
12970,13577321585,1,1.0,NaN,云南红河,124.10,0.00,0.0,0.0,0.0,...,NaN,NaN,236.366666,0.0,NaN,0.000000,4.0,1900mAh,4GB,4.5
4708,13466264613,1,0.0,NaN,云南红河,83.69,0.00,0.0,0.0,0.0,...,NaN,NaN,109.896667,0.0,NaN,0.000000,4.0,2000mAh,4GB,5.0
81946,15976516502,1,0.0,NaN,广东茂名,145.00,0.00,145.0,0.0,0.0,...,NaN,NaN,156.990000,0.0,NaN,145.000000,NaN,NaN,NaN,NaN
48904,13997679315,1,1.0,NaN,湖北宜昌,15.00,0.00,15.0,217.0,0.0,...,NaN,NaN,16.033333,0.0,1.033333,15.000000,4.0,2300mAh,4GB,5.0
25189,13711649044,1,0.0,NaN,广东广州,27.77,0.00,26.0,0.0,0.0,...,NaN,NaN,27.080000,0.0,NaN,26.000000,4.0,3010mAh,64GB,5.5
76942,15906034326,1,0.0,NaN,福建泉州,138.10,0.00,138.0,0.0,0.0,...,NaN,NaN,138.033335,0.0,NaN,138.000000,4.0,2850mAh,64GB,5.5
87853,18251671119,1,0.0,25.0,江苏徐州,46.10,0.00,0.0,0.0,0.0,...,NaN,NaN,46.066666,0.0,NaN,0.000000,1.0,1500mAh,256MB,2.3
74794,15873912998,1,0.0,NaN,湖南邵阳,105.40,0.00,0.0,0.0,0.0,...,NaN,NaN,108.383334,0.0,NaN,0.000000,3.0,2000mAh,4GB,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6096,13503264090,0,1.0,NaN,河北廊坊,80.00,0.00,80.0,257.0,0.0,...,NaN,NaN,80.266665,0.0,NaN,80.000000,4.0,1710mAh,4GB,4.0
72454,15842757090,0,1.0,NaN,辽宁盘锦,34.45,0.00,18.0,1250.0,0.0,...,NaN,NaN,27.823334,0.0,NaN,18.000000,NaN,NaN,NaN,NaN
95379,18710559868,0,0.0,NaN,陕西西安,40.24,0.00,54.0,0.0,0.0,...,NaN,NaN,63.910000,0.0,NaN,71.936666,4.0,3075mAh,32GB,5.5
48156,13980828752,0,1.0,48.0,四川成都,24.00,0.00,18.0,0.0,0.0,...,NaN,NaN,24.033333,0.0,0.033333,18.000000,99.0,850mAh,NaN,1.5
95181,18705187080,0,1.0,31.0,江苏南京,26.93,0.00,0.0,0.0,0.0,...,NaN,NaN,34.113334,0.0,NaN,0.000000,4.0,1800mAh,8GB,5.0
37571,13854718328,0,1.0,NaN,山东济宁,27.30,0.00,25.0,0.0,0.0,...,30.0,NaN,25.066666,0.0,NaN,25.000000,4.0,2100mAh,16GB,5.0
17128,13622302392,0,3.0,15.0,广东深圳,58.00,0.00,58.0,0.0,0.0,...,NaN,NaN,59.110001,0.0,NaN,58.000000,99.0,NaN,NaN,2.0
2187,13423486289,0,0.0,11.0,广东东莞,9.00,0.00,9.0,0.0,0.0,...,NaN,NaN,9.000000,0.0,NaN,9.000000,NaN,NaN,NaN,NaN
41448,13907332121,0,1.0,NaN,湖南株洲,60.00,0.00,0.0,0.0,0.0,...,NaN,NaN,60.300001,0.0,NaN,0.000000,4.0,1510mAh,16GB,5.0
43135,13923943843,0,0.0,NaN,广东汕头,27.00,0.00,8.0,0.0,0.0,...,NaN,NaN,17.033333,0.0,NaN,8.000000,4.0,3100mAh,16GB,5.5
46751,13962396991,0,0.0,NaN,江苏苏州,23.90,0.00,0.0,538.0,0.0,...,NaN,NaN,23.600000,0.0,NaN,0.000000,3.0,1715mAh,16GB/32GB/64GB/128GB,4.7
76836,15904596684,0,0.0,NaN,黑龙江大庆,31.15,2.15,19.0,2635.0,0.0,...,NaN,NaN,32.146667,0.0,1.933333,20.666667,NaN,NaN,NaN,NaN
68383,15759867265,0,0.0,NaN,福建泉州,23.70,0.00,18.0,0.0,0.0,...,NaN,NaN,21.356667,0.0,NaN,18.000000,4.0,2400mAh,32GB,5.2
64616,15252992061,0,1.0,NaN,江苏镇江,115.76,0.00,0.0,2606.0,0.0,...,NaN,NaN,118.893333,0.0,NaN,0.000000,3.0,2300mAh,16GB/64GB/128GB,4.7
98328,18767295583,0,1.0,22.0,浙江湖州,37.09,2.09,55.0,0.0,0.0,...,NaN,NaN,37.216667,0.0,2.216667,55.000000,NaN,NaN,NaN,NaN
75994,15893398486,0,1.0,NaN,河南南阳,46.70,11.70,26.0,2333.0,0.0,...,NaN,NaN,40.966667,0.0,7.633333,26.000000,99.0,1650mAH,NaN,NaN
78427,15924235422,0,1.0,31.0,浙江金华,115.32,12.32,117.0,0.0,0.0,...,NaN,NaN,89.300001,0.0,9.300000,117.000000,NaN,NaN,NaN,NaN
64091,15242838797,0,1.0,NaN,辽宁鞍山,110.00,77.00,38.0,1386.0,0.0,...,NaN,NaN,61.500000,0.0,77.000000,38.000000,4.0,3000mAh,64GB/128GB,5.2
51454,15018087996,0,3.0,NaN,广东惠州,8.00,0.00,8.0,0.0,0.0,...,NaN,NaN,8.000000,0.0,NaN,8.000000,99.0,NaN,NaN,2.4
91712,18341753201,0,1.0,7.0,辽宁营口,27.00,0.00,27.0,0.0,0.0,...,NaN,NaN,22.500000,0.0,NaN,27.000000,NaN,NaN,NaN,NaN
44624,13937376806,0,0.0,NaN,河南新乡,21.00,0.00,21.0,965.0,0.0,...,NaN,NaN,44.290000,0.0,23.290000,21.000000,4.0,2000mAh,8GB,5.0
91669,18340422677,0,0.0,NaN,辽宁本溪,18.00,0.00,18.0,638.0,0.0,...,NaN,NaN,18.000000,0.0,NaN,18.000000,4.0,2550mAh,32GB,5.1
15077,13600831527,0,1.0,NaN,福建福州,122.49,0.00,81.0,0.0,0.0,...,27.0,1.0,116.786667,0.0,NaN,81.000000,3.0,3000mAh,16GB/64GB/128GB,4.7
49323,14717797311,0,0.0,NaN,山东济宁,30.79,0.00,18.0,0.0,0.0,...,NaN,NaN,27.116667,0.0,NaN,18.000000,4.0,3060mAh,16GB,5.5
83955,17815515677,0,0.0,20.0,浙江绍兴,54.00,0.00,173.0,0.0,0.0,...,NaN,NaN,55.793334,0.0,0.126667,174.666667,4.0,3001mAh,64GB,5.1
18445,13640148563,0,3.0,24.0,广东韶关,43.10,0.00,43.0,0.0,0.0,...,NaN,NaN,164.850004,0.0,NaN,163.000000,3.0,3000mAh,16GB/64GB/128GB,4.7
56799,15106005956,0,1.0,53.0,福建泉州,111.14,0.00,74.0,0.0,0.0,...,NaN,NaN,85.686666,0.0,NaN,70.666667,4.0,4120mAh,64GB,6.0
72660,15846369966,0,0.0,NaN,黑龙江哈尔滨,122.67,2.67,100.0,6017.0,0.0,...,NaN,NaN,121.590001,0.0,1.590000,100.000000,NaN,NaN,NaN,NaN
58126,15130057192,0,0.0,NaN,河北石家庄,13.77,0.00,3.0,334.0,0.0,...,NaN,NaN,13.473334,0.0,NaN,3.000000,NaN,NaN,NaN,NaN
11881,13565602962,0,0.0,NaN,新疆昌吉,78.00,0.00,78.0,0.0,0.0,...,NaN,NaN,78.000000,0.0,NaN,78.000000,4.0,2300mAh,16GB,4.8